### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Kior** [tgstation/-tg-station#10009]
loading tgstation.dme
loading interface\skin.dmf
code\game\machinery\slotmachine.dm:296:error: throw: invalid variable name: reserved word
code\game\objects\items\weapons\melee\energy.dm:188:error: throw: invalid proc name: reserved word
code\modules\mob\mob_grab.dm:50:error: throw: invalid proc name: reserved word
tgstation.dmb - 3 errors, 0 warnings

**Comment by Jordie0608** [comment]
This is due to running v508, I just merged #9863 which fixes these errors so update your branch if you want to work with v508.

**Comment by Kior** [comment]
Ok, thank you
