### ISSUE TITLE
AoE Flash is not at all balanced

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#10008]
It has basically no cooldown and will blind everyone around you/make them unable to walk straight for what feels like forever. It's basically impossible to lose a fight as a security officer if the other guy isn't wearing a rig.

I took down ~5 gangsters with eguns and tommyguns just spamming my AoE flash and running around

However I don't want to just straight nerf the flash without giving security something else to make up for it, so I'm wondering if people have ideas on what weapon they could get/what weapon they have that could be upgraded to compensate. I don't want them to be useless in combat, just for their combat to have interaction and counterplay

**Comment by francinum** [comment]
Thing is, Yeah, short term they get the shit blinded out of them. 5 seconds straight flashing, the things broken and you need a new one.

**Comment by KorPhaeron** [comment]
@francinum 

Mine never burned out,

The formula is

if(prob(times_used * 2))	//if you use it 5 times in a minute it has a 10% chance to break!

And every 10 seconds times_used goes down one.

Flashes rarely burn out now, it's very easy to safely chain them (and carry a spare just in case RNG decides to fuck with you)

**Comment by francinum** [comment]
:+1:

**Comment by Supermichael777** [comment]
leg cuffs you can load into shotguns like bola rounds or just bolas. that will stop those suspects.

**Comment by freerealestate** [comment]
maybe pepe spray?

i never use it because afaik anyone with a mask, helmet or glasses is immune

often visually they'll look like you could spray their face but you can't for whatever reason
