### ISSUE TITLE
Can't Break Windows with Welder

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10002]
Even if the welder is turned on and you're using harm intent, the window still won't take damage.

**Comment by palpatine213** [comment]
Probably because using a lit welder on a window repairs it.

**Comment by Anonus** [comment]
Yes, but it shouldn't do that on harm intent.

**Comment by Fox-McCloud** [comment]
Yeah, Pap specifically re-added 'harm intent welders damages windows', but it apparently never worked? Or broke at some point?
