### ISSUE TITLE
Being summoned as a wizard apprentice gives no confirmation prompt.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10011]
It just drops you into the game without any warning, Likewise the same happens if you get spawned during ragin mages as a normal wizard.

It should give a yes/no choice like abductors, and ert.

Syndiborgs might also have the same problem.

**Comment by phil235** [comment]
And alien larva.

**Comment by Durkel** [comment]
If anyone can think of more, feel free to write them down. We can knock them all out with one pr.

**Comment by Anonus** [comment]
And syndicate cyborgs.

**Comment by Lumipharon** [comment]
ninja.

Larva is the worst though, since you're completely defenceless, and often spawn out in the fucking open.

**Comment by Incoming5643** [comment]
We really need to standardize this stuff

**Comment by AlexCrimson** [comment]
Agreed 100%. All roles that pull from ghosts should have a popup. It will really help filter out AFK players and those who want to leave the antag option enabled, but not become antag at the very moment(being the first alien/queen is quite the responsibility).

Pretty sure Revenant and Space Ninja are instant too. However you get a sound with those if you are chosen for the role. Still would be nice to have a popup.

**Comment by AlexCrimson** [comment]
Has there been any progress on this? IMO its something we really need.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
