### ISSUE TITLE
Explosives Implants are useless

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10015]
At point-blank with standard armor, Do not even make the target bleed.

**Comment by Lumipharon** [comment]
Explosive implants exist to gib you, denying people your shit. Anything else is purely secondary.

**Comment by Marflowerose** [comment]
They do seem uncomfortably shit compared to the actual size of the explosion it makes. If it's for gibbing self only, we'd still be using the cheaper implant that doesn't explode, just gibs.

**Comment by phil235** [comment]
Realistically, the implant is just a tiny explosive charge inside the person's head so I wouldn't expect it to hurt people except the owner.

**Comment by CosmicScientist** [comment]
Does it deafen anyone next to/on the *deathgasping character? Does it knock them out for a limit time? Does it just do piddly amounts of damage?

Is it meant to teach people beating bloodredhardsuits or the occasional traitor to death that you're going to take it on the chin or is it just for denial with no further reaching consequence?

**Comment by phil235** [comment]
It does knock down and blind nearby people afaik. Right now it does 24 damage to people right next to the owner if they have no protection.

**Comment by PKPenguin321** [comment]
>If it's for gibbing self only, we'd still be using the cheaper implant that doesn't explode, just gibs.

The reason it's that expensive as it is is because cheridan has a hatred for nuke ops having explosive implants or something.

**Comment by Marflowerose** [comment]
Nuke ops don't need the implants with the irremovable suits so nuke ops are irrelevant to explosive implants.

**Comment by PKPenguin321** [comment]
Oh my sweet summer child

**Comment by palpatine213** [comment]
Yeah. Explosive implant is hilariously underpowered. 24 damage is laughable for an explosion that is supposed to be a suicide bomb. Doesn't even seem to make bystanders bleed. It should either be made cheaper, or have its power increased to actually be useful for dieing a glorious death to take out your target.

**Comment by Lumipharon** [comment]
an explosive implant is a tiny thing in a little implanter syringe. You're asking for something like a minibomb.

The inconsistancy only exists because ops lost their 100% functional and effective implants for nonfunctional 'unremovable' hardsuits (that can be removed with a dose of acid), and ops were mde to pay for the implants.

**Comment by Tokiko1** [comment]
The implant is not only avaible for operatives though. For regular traitors, the cost and size of the explosion make the item nearly useless, in my opinion atleast. However, I've seen a lot of newer players purchasing this and then complain in deadchat about the tiny explosion.

**Comment by Dorsisdwarf** [comment]
You can use an explosive implant as a kicker charge for a syndiebomb core in your backpack.

**Comment by palpatine213** [comment]
I've actually seen a traitor use the implant to gib their target.

**Comment by phil235** [comment]
Did the change to micro/macrobomb fix this?

**Comment by Anonus** [comment]
Uh, yes. I mean, it did fix this issue.
