### ISSUE TITLE
Connecting an atmos pipe to another works but gives an error.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#10026]
## ERROR: /obj/machinery/atmospherics/pipe/simple added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) Nearby: (66, 141, 1)

Unlike what the error message say the two pipes are not on the same turf.
Basically the build_pipeline proc is grumpy because the adjacent pipe already has a pipenet.

This doesn't have any visible effect ingame though.

**Comment by Jordie0608** [comment]
Related to #9335?

**Comment by phil235** [comment]
I don't think  this is related, 9335 was linked to filters.

**Comment by duncathan** [comment]
This was fixed
