### ISSUE TITLE
Slaughter Demons can't sink in and out of blood runes

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10030]
My demon summoning requires it.

**Comment by Jordie0608** [comment]
@KorPhaeron Possibly intentional but it sounds like something they should be able to do

**Comment by KorPhaeron** [comment]
It was an oversight/laziness (runes aren't blood decals) but I can't imagine that being anything but monstrously unfair to to the cult if any time they tried to use their powers a badguy would warp in and eat them.

Maybe Nar-Sie's power blocks the demon or something I dunno.

**Comment by GunHog** [comment]
A blood demon definitely sounds like something a cultist would summon!

**Comment by Anonus** [comment]
Maybe let them bind or convert them somehow or something.

**Comment by AlexanderUlanH** [comment]
Thematically, the slaughter demon shouldn't be able to travel through blood that was sacrificed rather than spilled.
>The blood in this rune is not the spawn of slaughter.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
