### ISSUE TITLE
AI tracking is broken 

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/-tg-station#10032]
After the new AI tracking update that creates a delay on AI tracking I've played two rounds as the AI where I would try to track people from the chat only to have them be untrackable.  They would be near cameras once they told me where they were and I could be looking right at them, but they were still untraceable.  

This happened with a good chunk of the crew, including sec officers who shouldn't have been given syndicate antag roles which might have given them access to syndicate ID's

The only thing I noticed that seemed to be consistent with this was the problems seemed to start after people started making changes to t-com scripts, usually to add job info to people  when they spoke.

**Comment by duncathan** [comment]
Comms breaks tracking links.

**Comment by GunHog** [comment]
This issue is caused by https://github.com/tgstation/-tg-station/pull/9602. Any scripts that modify the $source variable will break AI tracking links. Configure your scripts to avoid this.

**Comment by bgobandit** [comment]
Isn't this an older bug? Certain comms scripts have broken AI tracking way before that.

**Comment by GunHog** [comment]
For a different reason. I.E. artificial broadcasts, or copy messages. Intercept scripts had this issue.

**Comment by Jordie0608** [comment]
#9886

**Comment by Miauw62** [comment]
Did you try tracking people by typing "track their-name" in the chatbox?
anyway, i think this isnt my fault?
@Aranclanos

**Comment by Nitrousoxide** [comment]
I did not try "track 'username'"  so i'm not sure.

**Comment by GunHog** [comment]
A script that modifies a mob's name on the radio can cause this. Example: Miku Frost says something on the radio, and with a script, her name is displayed as "Miku Frost [Sec]". The AI link would search for "Miku Frost [Sec]" instead of "Miku Frost", in the tracking list, resulting in a failure.

When AI tracking used to point to the mob, now it points to whatever name is displayed on the radio. Changing it in any way will cause this issue.

**Comment by Miauw62** [comment]
the solution is pretty obvious and simple, though.

**Comment by duncathan** [comment]
the solution is to change the ntsl script

**Comment by GunHog** [comment]
I have already changed my script to work around this. Others may not be aware of this, however. Also, if the solution includes the word "remove", it is not really a good solution.

**Comment by Miauw62** [comment]
did i ever imply that dunca's solution is not autistic?
