### ISSUE TITLE
Mesons dont see false walls

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10038]
It allows people to accidently discover cult early when they hide in the atmos maint below virology,
Just be round the corner to see where a false wall is by not seeing it.

**Comment by Xhuis** [comment]
intentional

**Comment by AlexanderUlanH** [comment]
This was the only advantage I saw to having darkness overlay mesons.  The way to fix it is to remake falsewalls as turfs.

**Comment by palpatine213** [comment]
Not a bug. Meson are supposed to be the way to detect false walls. If your cult base is being found by engineers, maybe don't build it by engineering?
