### ISSUE TITLE
Vault floor and plating all over centcom

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10049]
There's lots of vault tiles around centcom where there really shouldn't be. Vault tiles are very ugly, not used ANYWHERE else in the game, and as they are right now are out of place with their surroundings. There's some in front of the thunderdome, just under the customs desk, and a couple randomly placed in the supply shuttle area,

**Comment by xxalpha** [comment]
I don't think this is worthy of an issue. Centcomm aesthetics are the last thing anybody cares about.
