### ISSUE TITLE
Lizard snout is poking through helmet

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10044]
![](http://i.imgur.com/oOfQHU7.png)

This is the SHARP snout that's doing that, may apply to the regular one too.

@Incoming5643

**Comment by Incoming5643** [comment]
Matter of coverage flags, snouts check for mask but not helmets in terms of face coverage. It's very rare to be wearing a space suit with no mask (because no internals) so this is the first time I've seen this, despite THIS bug having actually predated the new lizard sprites.
