### ISSUE TITLE
Disablers can stack stamina on xenos, and there's no cap to how high it can go.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10042]
This *might* affect plasma build rate, since you know build plasma at half speed when "injured"

**Comment by Xhuis** [comment]
## f e a t u r e

**Comment by Iamgoofball** [comment]
stamina SHOULD effect them, just they should be able to recover from it.

**Comment by WJohn** [comment]
They don't get knocked down by it, I don't even know if they get any slowdown effects from it. There also doesn't appear to be a cap. I recently made myself a really big alien monster using the large alien queen, and at one point had over 500 non-healing stamina damage preventing me from generating any plasma.

**Comment by Iamgoofball** [comment]
simple solution then, fix it to work properly on xenos

**Comment by phil235** [comment]
@phil235 pretty sure that bug came from my life() refactor, I think I let xenos (and maybe monkeys) not handle stamina.

**Comment by WJohn** [comment]
This is back, however now instead it *does* go down, but it doesn't ever reach any cap, meaning they can get hundreds of points of stamina.

**Comment by phil235** [comment]
Fixed
