### ISSUE TITLE
Server logs not fully logging things?

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#10057]
Either something is horribly wrong at my end irl or server logs simply don't fully log things, in this case, deadchat.

For a specific example, I'm pretty sure the logs failed to catch players talking in deadchat at log time 10:30:00, on the 20th of June.

**Comment by Dorsisdwarf** [comment]
@Ausops 

Requesting info on whether this has been encountered since.
Closing if not.

**Comment by Ausops** [comment]
due to the nature of the issue it's hard to catch and I still insist I wasn't hallucinating.

But yeah I haven't encountered it since.

**Comment by MrStonedOne** [comment]
ServerSide bug, I had reverted data's state to recover some player saves that were lost, and this also reverted logs.

Can be closed.
