### ISSUE TITLE
Healing/reviving a slaughter demon via player panel has weird effects.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10058]
The slaughter demon will be turned into ye-olde orange human sprite (orange skin, green eyes) but cannot turn. It retains the same path, health, sound effect, attacks, and blood movement abilities.

@KorPhaeron

**Comment by KorPhaeron** [comment]
Probably because I didnt set living/dead icon stats for it seeing as it gibs when it dies. Should be an easy fix

I'm wondering what circumstances an admin needed to heal them though given their ability/given I told people not to spawn them
