### ISSUE TITLE
Up the Bomb Cap

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10055]
A recent PR went through to make the bomb cap a configuration option--in it, it was suggested that if reactionary explosions are used, a higher bomb cap would be utilized, but the higher bomb cap *wasn't* utilized to test to ensure the feature worked as intended. In any event, to quote @MrStonedOne:

>Ya, generally, when you add a new config option, its best to ensure it defaults to old behavior (if any)

> can make it so the config default is one step up, but the default if no config option is present (for current servers) is the old number.

So this is just putting in for a feature request/balance suggestion of actually bumping up the bomb cap to the secondary level.

**Comment by Anonus** [comment]
The bombcap is currently 5, 10, 20 on the live servers right now.

**Comment by Fox-McCloud** [comment]
@MrStonedOne 

Can you confirm this?

**Comment by palpatine213** [comment]
For a serverside config, github issues aren't really the best place to put it as the config setting on the server isn't dependent on the codebase

**Comment by Iamgoofball** [comment]
separation of code and server

"this is MY code" etc etc.

**Comment by Miauw62** [comment]
this is not a code issue but rather a server issue, thus the issue tracker is not a good place.

**Comment by MrStonedOne** [comment]
@Miauw62 the suggestion here is actually that we change the default in the config, not whats on the servers. This should maybe be re-opened

**Comment by Miauw62** [comment]
fair enough

**Comment by Dorsisdwarf** [comment]
The bomb cap has been increased.
