### ISSUE TITLE
extracting brains creates two identical brains

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#10056]
isn't really a huge problem as the 'soul' of the person who died only inhabits one, but it creates a huge pile of annoying un-MMIable brains (gives an error about the brain being useless; i imagine kind of like the cloning system) seems to happen every time.

**Comment by Nitrousoxide** [comment]
Saw this happen in another round as well so it doesn't seem to be an isolated occurrence.

**Comment by Lumipharon** [comment]
just means more brain cakes/burgers for the chef.

**Comment by Cebasiz** [comment]
OP may have been wrong by the way, i think it's that putting them in the MMI clones the brain, NOT extracting it.

**Comment by Miauw62** [comment]
probably has to do with the changes to unequip

**Comment by phil235** [comment]
fixed by #10082
