### ISSUE TITLE
Allow admins to give people hivemind chats

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10061]
In the same way as being able to give people languages, these could be drone chat, ling hivemind, abductor, xeno, cyborg, shadowling, and blob. I'm not sure if there are more than this, but you get the idea.

I heard miauw say that this would require an extensive amount of rework with hivemind type code, so do this at your own pace.

**Comment by Anonus** [comment]
Hiveminds also don't have follow links for ghosts because they're all awful snowflake stuff that outputs text instead of being an actual said thing.

**Comment by Miauw62** [comment]
deadchat isnt a hivemind chat because they're all different and snowflakey.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
