### ISSUE TITLE
Allow admins to choose who spoke in a "centcom" announcement.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10063]
Right now if you try to make a centcom announcement it's always a "central command update". In the past it may have been randomized or perhaps it was possible to choose it then with stuff like "science empire update".

Basically it'd be nice if we could replace the word "centcom update" with whatever we wanted, like "syndicate announcement" or some scrambled message or whatever we want.

It's a bit odd that there's no way to do this otherwise (without being real hacky and using those green announcement consoles).

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
