### ISSUE TITLE
H/E pipes do not wrench in the correct direction

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#10062]
![thingy](https://cloud.githubusercontent.com/assets/5659269/8269714/c537f884-1782-11e5-870a-dce22c87003e.gif)

Tested on the latest revision as of time of posting. Pipes were dispensed via RPD, the normal pipes don't appear to have this issue.

**Comment by WJohn** [comment]
Yeah this has been like this for months, at least.
