### ISSUE TITLE
Drone dispenser cooldown cannot be modified

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10071]
The dispenser cooldown is hardcoded rather than a var. This inconsistent with almost every other thing that has a cooldown, and makes it so the cooldown time between drones is impossible to modify.

**Comment by Jordie0608** [comment]
@Xhuis

**Comment by WJohn** [comment]
This is probably more of a feature request than a bug.

**Comment by palpatine213** [comment]
I'd say it's part feature request, part consistency issue, since, most other similar devices have a var for their timing or cooldown.

**Comment by Xhuis** [comment]
I'll make this a variable in my upcoming hotfix.
