### ISSUE TITLE
Stocking Drone dispensers with metal and glass doesn't use the metal, nor care about how much you have.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10070]
To reproduce:
Spawn drone dispenser
Spawn i metal and 1 glass sheet
Use a sheet on the fab, and type 50
It will add 50 sheets of metal worth to the dispenser, and you'll still have the 1 glass sheet
Repeat infinitely.

**Comment by Jordie0608** [comment]
@Xhuis

**Comment by xxalpha** [comment]
If we had some sort of datum to handle these things, bugs like this would not happen!

**Comment by Xhuis** [comment]
I was unable to reproduce this in local, but I'll do some experimenting and see what I come up with.

**Comment by Core0verload** [comment]
@phil235, fixed.
