### ISSUE TITLE
Oculine doesn't work

### ISSUE THREAD

**Issue by Cookiesndip** [tgstation/-tg-station#10084]
I tried fixing a screwdrivered patient in medbay with oculine in both pill and patch form to no avail. I even tried squirting oculine in his eye, and, despite having 60 units in his system for several minutes, no change was observed.

**Comment by Iamgoofball** [comment]
fucking eye code

@phil235 did you touch eye code at all doing the life rewrite? i'm not certain how it works anymore

**Comment by bgobandit** [comment]
dupe https://github.com/tgstation/-tg-station/issues/9707

**Comment by Lumipharon** [comment]
If you take enough eye damage, it gives you (or at least, used to) GENETIC blindness. Shit's retarded man.

**Comment by Boggart** [comment]
If I remember correctly eye_stat isn't touched by occuline, only eye surgery. I don't know if that's intentional or accidental. (Eye_stat is the damage type caused by welding and I'd assume screwdrivers to the eye, etc.)

**Comment by Iamgoofball** [comment]
thats retarded, it should heal all

**Comment by optimumtact** [comment]
Yes goof it is retarded.

**Comment by WJohn** [comment]
Closing since it's a dupe.

**Comment by optimumtact** [comment]
of?

**Comment by optimumtact** [comment]
nvm saw bandit's comment
