### ISSUE TITLE
Right-clicking a tile where a jaunted slaughter demon is lets you see them.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#10088]
![honkdemon](https://cloud.githubusercontent.com/assets/9276171/8273838/05b620d8-184c-11e5-8b79-941cf96fd9ef.png)

The 'water' in the list is the jaunted slaughter demon. I'm assuming the same happens with jaunted wizards.

Potential abuse is niche considering odds are by time you see this you're already being dragged into your own blood puddle, just thought I'd point it out.

Honk.

**Comment by WJohn** [comment]
@KorPhaeron or @Incoming5643 whichever one of you wants to fix this for both.
