### ISSUE TITLE
Drones cannot block lasers with double esword

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10086]
A drone holding a double esword does not block lasers. I'm not sure if holding one even gives a block chance either.

Probably only important for if theres ever a syndrone event or whatever.

**Comment by KorPhaeron** [comment]
We're not making drones check_shields like humans for code reasons.

They dont have the combat ability/dexterity to swing around lightsabers if you need a lore reason.

@Wjohn please kill this issue

**Comment by duncathan** [comment]
Drones don't need this and it was never intended so
