### ISSUE TITLE
Singulo doesn't apply tox damage

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#10096]
https://github.com/tgstation/-tg-station/blob/8820662c31da932268591264fc6a980331634d83/code/modules/power/singularity/singularity.dm#L371

The bug's been here for 4+ years. The proc should use apply_damage(), not apply_effect().

**Comment by WJohn** [comment]
I don't think anyone ever noticed because of how irrelevant it is in the face of the singulo. If it's close enough to you that you start getting irradiated, you're usually eaten two seconds later.

**Comment by bgobandit** [comment]
not necessarily, you can be irradiated in the PA chamber if lord sing's coming your way

**Comment by phil235** [comment]
What's funny is that without that proc error, the toxdamage that a stage 3 singulo would deal to an unprotected engineering in the PA chamber would have been enough to instantly crit or kill him. That's why I had to nerf the damage in my PR.

**Comment by xxalpha** [comment]
I think it's unnecessary. It already irradiates, which causes tox damage.
