### ISSUE TITLE
Implanted Team Antags have their icons overlayed with the loyalty hud icon

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10099]
When implanted, Cultists, Gangsters, (and probably nuke ops, too) have their icon covered by the loyalty implant icon.

While it doesn't cover the icon completely, it does make it harder to tell if they're on your team.

**Comment by Incoming5643** [comment]
There's a bit of an outstanding problem with antag hud icons where having more than one makes life confusing. The obvious solution is to tile them, but if you do tile them, and someone who's in the second group but not the the first sees you with a gap where the icon normally is and it displayed else where they can meta that you have another team.

That and I'm pretty sure that HUDglasses loyalty implants work on a completely different system than the antag hud icons

**Comment by xxalpha** [comment]
Yeah, the HUD icons are a different thing than antag icons.
