### ISSUE TITLE
ManualFollow causing ridiculous lag

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#10093]
It managed to get up to around 50k CPU earlier last round. Had to turn it off to save the server.

**Comment by Dorsisdwarf** [comment]
What is ManualFollow?

**Comment by TheVekter** [comment]
It's a proc I noticed going haywire on the server tonight, after the
singularity got out. I'm fairly certain it's called when someone uses the
follow verb.

**Comment by Incoming5643** [comment]
it's the ghost's follow verb, it was recently added to replace jump to mob for admins too, which I'm guessing is the source of this problem somehow.

Also in addition to mobs you can track the singulo specifically, which might be causing issues.

**Comment by RemieRichards** [comment]
@Incoming5643 following the singulo isn't a thing.
OBSERVE verbing it is, but the observe button is shit because to get back to yourself you have to observe yourself.

**Comment by TheVekter** [comment]
No... cancel-camera-view takes you back to your mind.

**Comment by RemieRichards** [comment]
>cancel-camera-view

that's an entirely seperate verb that exists for whole other reasons @TheVekter , most notable for CANCELLING A CAMERA VIEW. The fact that it also resets your eye to your body in observe terms is just because it also uses client.eye. but I'll keep that horribly intuitive thing noted.

**Comment by TheVekter** [comment]
Yo, no need to get pissed, I was just pointing it out. Back on topic, why
is follow causing so much lag?

**Comment by RemieRichards** [comment]
I'm not pissed lol, tbf I did just wake but that's no excuse, sorry.

As for the topic, Follow, unlike Observe (OR CAMERAS :P) does not use client.eye, it instead sits in a loop and constantly moves you to the location of what you're following.
Ghosts have done this for ages, with Sybil tending to have a lot of ghosts by round end, so I see no reason why admins suddenly having it (JMP --> FLW) would change anything.

**Comment by TheVekter** [comment]
I've seen byond do some really weird shit in the past. I'll keep an eye out
and see if I notice it happening again.

**Comment by Incoming5643** [comment]
May be related, but when I've been following lately I've seen my ghost end up in a void (maybe nullspace) for a few seconds before successfully following the person.

**Comment by RemieRichards** [comment]
@Incoming5643 I'm going to go out on a limb and say that's not actually nullspace.
When walking during super lag the game has the tendency to move you before it's even bothered to render where you're walking to.

If your follow target moved a large distance AND it was lagging like fug, I'd expect the same "lol gimme a minute to render" blackness to appear.

**Comment by Boredone** [comment]
As a note, you CAN follow the singularity as a ghost automatically by double clicking it.
Same with other people too.

**Comment by TheVekter** [comment]
Maybe this is what's causing it?

**Comment by Dorsisdwarf** [comment]
Using the verb Follow now crashes my game.

**Comment by TheVekter** [comment]
Fun!

**Comment by MrStonedOne** [comment]
All of these should/might be fixed as of monday morning PST now that i fixed some network delay issues

Let me know if they happen again.

**Comment by MrStonedOne** [comment]
This should be fixed by orbits

**Comment by Jordie0608** [comment]
Orbits lagging would be their own issue anyway
