### ISSUE TITLE
Explosive gelatin blob spore gas explodes multiple times

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10107]
While fighting a blob recently, I was struck numerous times with the "exploding tendrils" attack, which put me into crit multiple times. Apparently the "blob tendrils" attacking you actually refers to the gas left by destroyed spores: "The gas the blob spores left exploded every time something touched the center. Including blob spores. A whole bunch rushed over it after someone and it's like b-b-b-b-b-b-b-booom-boom!'

It seems to do a lot of damage, too.

**Comment by phil235** [comment]
why did you close it?

**Comment by Iamgoofball** [comment]
Fucking

@RemieRichards Can you remove spore clouds carrying the blob reagent and make them just have spore toxin again? It's causing way too many problems and it was your tweak.
