### ISSUE TITLE
Can't fire through smoke

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10106]
I noticed this while fighting a blob today. When you destroy one of the blob spores (or whatever they're called), they leave a smoke cloud (as usual) but because it obscures your vision (leaving black squares behind it) you're unable to fire through it, which prevents you attacking further blob spores or other threats after you destroy one. You have to simply retreat until the cloud clears or the spores advance past it.

**Comment by AlexanderUlanH** [comment]
You can fire past it by clicking a nonadjacent turf between the cloud and you.
Though, it would be nice to be able to fire in a direction by clicking an adjacent turf.

**Comment by CosmicScientist** [comment]
So you want to be able to click on the black "unseen" tiles and have your gun fire?

**Comment by freerealestate** [comment]
Pretty much

It seemed clicking on the edge of the smoke itself prevented firing too
though

**Comment by Lumipharon** [comment]
This issue also pops up in mech v mech fights. If you're right in front of each other, you can't shoot the other mech since it blocks vision (unless you have xray), and clicking on the mech just punches/pushes.

You could probably click on the tiny parts of the floor that the mech doesn't cover, but eh.

**Comment by CosmicScientist** [comment]
Probably click on the tiny parts of the floor is pixel hunting, that's no good.

**Comment by phil235** [comment]
Fixed, clicking on a black unseen tile does allow you to fire.
