### ISSUE TITLE
Cannot dye nuke op jumpsuits

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10109]
In the nuke op starting area, there are washing machines and crayons, which seem to indicate you can dye your nuke op jumpsuit for a stealthy approach if you so choose. However, washing a nuke op jumpsuit with a crayon results in it returning as a nuke op jumpsuit.

**Comment by Ikarrus** [comment]
I don't think that was ever intended as anything more than set dressing. Nuke ops have chameleon jumpsuits for stealth approaches.
