### ISSUE TITLE
Mobs permanently "stunned" after nuke explosion

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10108]
In some cases, after the nuke explodes, people who aren't on the same z-level as the blast are still "stunned" by it, and remain on the ground (though are able to hold things and interact with adjacent objects as though they weren't) until the round ends.

**Comment by xxalpha** [comment]
This isn't a problem because nuke detonation ends the round. What happens is that you are buckled to an invisible object so you don't fuck around when the animation is playing.

**Comment by freerealestate** [comment]
There's still about twenty seconds after the animation ends where people
may want to mess around. It's kind of immersion breaking, too (even though
the round is over).
