### ISSUE TITLE
Field of vision is broken?

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#10104]
I feel like I can see too much on the first screenshot.

![cantsee1](https://cloud.githubusercontent.com/assets/4951579/8296732/365daeda-194c-11e5-932a-353e3d713cdb.png)

![aa](https://cloud.githubusercontent.com/assets/4951579/8296497/0c568f38-1949-11e5-8dce-5a713c80bbae.png)

**Comment by xxalpha** [comment]
Byond issue.

**Comment by Anonus** [comment]
Unfixable byond wizardry.
