### ISSUE TITLE
Golems take damage from hitting stuff with glass shards

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10119]
Yup.

**Comment by Supermichael777** [comment]
golems need a rework because someone decided that the best way to prevent them from being op was to weld their gear on and prevent them from wearing anything else, but accidentally prevented them from getting that gear or wearing it.

**Comment by Anonus** [comment]
They don't use gear anymore, they use the mutantrace system and have a flag for not getting fucked by glass, except nobody put code in the attack of shards to keep them from getting fucked by it.

**Comment by phil235** [comment]
/obj/item/clothing/suit/golem (and gloves, shoes, etc) still exists though apparently.
