### ISSUE TITLE
Bug Report: Atmo Suit Storage Unit Crash

### ISSUE THREAD

**Issue by PrayForSnow93** [tgstation/-tg-station#10122]
First time submitting a report, forgive me if I make any errors.

I was attempting to hack the Atmospherics Suit Storage Unit after spawning in as a Traitor Atmo Tech. I was hoping to fry my target in the Storage unit based off of something I'd read on the wiki, about how the UV intensity can be ramped up to lethal levels, and the safety features can be deactivated to store people and bodies inside.

![image](https://cloud.githubusercontent.com/assets/13026513/8321663/a173708c-19de-11e5-9321-0a96b825f57a.png)

I used the screwdriver on the Unit, then attempted to open the wiring menu, first with an AI Detector Multitool. I got a message saying a fatal error or something had executed (forgot to screen capture it, may do so in a later post). I then softcrashed, with chat updating and the game accepting my keyboard inputs, but nothing on screen would update. I quit the client, then restarted and got the same issue after two more attempts, once while holding wirecutters, and another while holding nothing at all. After that point I just screwed back on the panel and left it alone.

**Comment by francinum** [comment]
dupe of #9413

**Comment by PrayForSnow93** [comment]
Thanks for the heads up, my bad.
