### ISSUE TITLE
It's no longer possible to reach the vodka in the HoS office

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10120]
This is on sybil

![](http://i.imgur.com/UqWtCtI.png)

You have to open the locker to reach it, and honestly this feels sorta clunky. Things need to be shifted around a bit. Maybe have all 3 computers side by side, with the tables all connected on the right side and the HoS's locker above the disposal bin?

**Comment by TheVekter** [comment]
Well fuck, that's easy. I'll get it in the morning.

**Comment by TheVekter** [comment]
Also I'm changing the glasses to shot glasses. There is no one (bar Russians) that drinks fucking glasses of vodka.

**Comment by Iamgoofball** [comment]
@TheVekter Being an HoS is stressful. Sometimes you need a little extra push to get you through the day.
