### ISSUE TITLE
Abductor plasma gland fills the arrivals shuttle with plasma killing all the future abductees.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10123]
Almost always abductees are asleep and cuffed when they are sent to the shuttle. Unfortunately, the time it takes for them to wake up and resist out of cuffs is more than enough time for most of the glands to activate.
When the plasma gland person explodes, they fill the shuttle with plasma. Unless the plasma is cleared, all future abductees will die due to plasma poisoning before they can even wake up.

**Comment by freerealestate** [comment]
Being unconscious is really lame. Especially when it means you're missing
out on experiencing being abducted by aliens.

**Comment by AlexanderUlanH** [comment]
The return beam should probably remove energycuffs.

**Comment by Anonus** [comment]
The glands should not activate before you send them out it just causes stupid issues like this.

**Comment by AnturK** [comment]
They don't and semi-fixed in https://github.com/tgstation/-tg-station/pull/10129

**Comment by Bawhoppen** [comment]
This isn't relevant anymore considering you can set where to put them now, and sending them now decuffs and stuns them for only a few seconds
