### ISSUE TITLE
Experimental welding tool inhands

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10137]
The experimental AND upgraded industrial welding tool's inhands are incorrect for the left hand on its sides. It appears as being held by the right hand even if holding it with your left (this occurs while facing left and right).

Note that this ONLY happens while the welder is *on.* Again, this happens for both the experimental and upgraded industrial welding tools.

![](http://i.imgur.com/znBxSAI.png)

**Comment by Firecage** [comment]
This is what happens when you change the sprites in a PR like 4 times.
