### ISSUE TITLE
Brute damage is completely broken, everyone has 90% damage reduction minimum

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#10133]
https://github.com/tgstation/-tg-station/blob/4b535baafa72d0cdef47adf2a328aa683cfd3ca7/code/modules/mob/living/carbon/human/species.dm#L927

It says max instead of min, which means that everyone is basically unkillable with this active. Funnily enough, punches still do full damage, so you can punch someone to death while they're chopping at you with a fire axe or esword

Fuck, WJ beat me

**Comment by WJohn** [comment]
Fixed already.
