### ISSUE TITLE
The probe setting on abductor batons is pretty much unneeded

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10149]
And it fucks up your baton rotations, which would be a really nice stun-toggle-sleep-toggle-cuff-toggle except that probe is in there.

**Comment by Xhuis** [comment]
you obviously don't know the secret probe technique

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
