### ISSUE TITLE
Syndicate buy screen typo

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10152]
I believe it says the surplus pack says it gives 10 TC's of materials currently, when it should say 20 TC's due to the TC change way back:

Dorsisdwarf updated:
The amount of TC has been increased to 20, but the price of all items has been doubled as well

**Comment by Miauw62** [comment]
>tfw dorsidwarf takes credit for your changes

**Comment by Dorsisdwarf** [comment]
Oh, I remember this. It annoyed me that this change wasnt changelogged, so I made one for it
