### ISSUE TITLE
Portable scrubbers are ineffective

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10162]
They've been like this for so long that nobody questions it, but no one bothers with portable scrubbers to deal with gas leaks anymore because they're useless. This means that gas leaks cause automatic shuttle calls because there's no (effective) counterplay to them.

**Comment by Actionb** [comment]
From my experience, they are way faster than a ground scrubber. Their only problem is that they slow down the closer they get to their maximum capacity (at least it feels that way) - which is fine since you won't be employing just one when shit hits the fan. They are portable (duh), can be used by anyone and can be set up quickly, unlike ground scrubbers that need to be constructed. They never felt ineffective to me.

**Comment by freerealestate** [comment]
Really? Every time I've set up a few to try to clear an area, they barely scrub anything. I'll come back five or ten minutes later and they'll have barely done anything.

I assume this is why no one ever bothers with them.

**Comment by Incoming5643** [comment]
scrubbers (except for the big one in toxins) have limited capacities, once they near those capacities they become mostly useless unless they're wrenched to a distro loop and emptied.

Almost no one ever does this, and I'd wager a lot of people don't even know you can wrench scrubbers/fans to ports.

**Comment by duncathan** [comment]
Related: #9787.

**Comment by Lumipharon** [comment]
You need to max their power, not just turn them on.
Also empty them out when they're full.

They're fine for anything except N2O, which is slow to purge regardless of method.

**Comment by Tokiko1** [comment]
Sometimes, the plasmaoverlay won't clear even when the tile is clean enough not to cause any poisoning or fire. I think that this is what makes scrubbers feel useless.

**Comment by Actionb** [comment]
It's certainly a combination of https://github.com/tgstation/-tg-station/issues/9787 and the overlay bug. To clear the first, you pretty much have to cart around a portable scrubber. For the second problem, removing the floor tile works.

**Comment by Dorsisdwarf** [comment]
Portoscrubs seem a lot more effective after the atmos changes
