### ISSUE TITLE
Trying to put EMP flashlight in a backpack sets it off

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#10160]
HELP: Looping/(Frank Hunt) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Frank (?) (FLW) Hunt blinks the flashlight at the backpack. The flashlight now has 3 charges. uh, is there a way to avoid this?

**Comment by Miauw62** [comment]
Disable the flashlight first, I think.

**Comment by duncathan** [comment]
Using the equip hotkey if you have no other slots for it should work, too.

**Comment by Lumipharon** [comment]
Open bag. Put flashlight into empty bag slot.

It's the same with stuff like the cham projector.
Clicking the bag makes them interact with the bag, putting it inside the back is secondary.

**Comment by bgobandit** [comment]
This is still the case, and happens even when the flashlight is off/never used.

**Comment by phil235** [comment]
It might just need a check for target.loc != user
