### ISSUE TITLE
Jetpack speed varies

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10166]
Using identical jetpack, the speed varies depending on odd factors. One very glaring difference is between regular human and one with Stimulant virus. The stimulant virus jetpacking causes one to go full on sanic (double?) speed. I assume other stupid factors also affect jetpacking speed.

**Comment by freerealestate** [comment]
It's affected by base movement speed, which means if you're injured or
hungry you'll jetpack slower. Doesn't make sense and is annoying, I agree.

**Comment by Lumipharon** [comment]
This didn't happen before slowspace.

**Comment by PKPenguin321** [comment]
>This didn't happen before slowspace.

**Comment by francinum** [comment]
@freerealestate Jet-packs ignore slowdown, but doesn't take into effect speed increase.

**Comment by freerealestate** [comment]
Do they? Because I often notice myself going slower with low nutrition.

**Comment by Kromgar** [comment]
Slow space makes you go slower in space with low nutrition. Slowspace a shit

**Comment by optimumtact** [comment]
If you have a jetpack all status affect slowdowns are ignored in zero gravity

**Comment by freerealestate** [comment]
The jetpack has to actually be on for that to occur, right?

**Comment by optimumtact** [comment]
Yes
