### ISSUE TITLE
Adding pipes to pipeline causes the pipeline's air to be deleted

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#10165]
https://github.com/tgstation/-tg-station/pull/9867

Rev: 799b96fe7bab1983887d39fac8c16117fec51a39

Unwrenching and then >reconnecting< a pipe/pump/whatever that is part of or connected to a pipe network with stuff in it will just delete most of what is in that network.

How to reproduce: Go to atmospherics. Unwrench f.ex. waste-to-distro pump, read the pressure in distro, wrench that pump back in, notice how suddenly most of the air in distro is just gone. Note the gas is lost upon RECONNECTING the pump. It wasn't released anywhere, it's just gone.

**Comment by RemieRichards** [comment]
this is odd.
I suppose this was the true reason pipes with pressure were unwrenchable, because their gas mixture datums just get lost?

**Comment by phil235** [comment]
Related to #10026 ?

**Comment by Actionb** [comment]
I cannot into code. All I can tell you are my ingame observations. 
Maybe this actually isn't an issue with your amazingly fun addition, Remie.
This deletion of gas also happens when you simpy ADD new pipes. Never unwrenching any pipes, just adding more to a network. I just emptied out sybil's distro loop sitting at 6500kpa (yuck!) in 5 seconds by adding three pipes to that system.

There is definitely something very wrong with how pipes update. 
Say you have this setup: -----> pipes filled with gas | active pump | pipe A | nothing

Unwrench pipe A and reconnect it. It will be empty forever unless you also reconstruct the pump. 

Also, If you add a pipe after pipe A (in place of nothing), turn the pump off (not that it'd matter; see above), and unwrench and reconnect them both, the pipes magically contain what I guess was originally in pipe A: ~1400 kpa in pipe A before unwrenching; ~880kpa in both pipes after. Although they should be completely empty?

**Comment by Rinoka** [comment]
Maybe the disabling of being able to unwrech pipes with pressurized gas was because of this problem?

Because this sort of dramatic error seems like the pipe atmos code's problem in general.

**Comment by RemieRichards** [comment]
@Rinoka that was my thought too, but if you read @Actionb's Comment above yours, they explain it happens when ANY PIPE IS ADDED, it doesn't matter about unwrenching.

**Comment by Rinoka** [comment]
@RemieRichards Yeah, but I mean that it's a thing - but it's super obvious when you unwrench pressurized pipes, so it was disabled for the imulsion. Not directly caused or only caused by that, but the dev who disabled pressurized unwrenching realized that happened and tried to hide it.

I'm going to go ahead and give a look at the atmos code, see if I can understand how pipes update.

**Comment by duncathan** [comment]
Pressure lowering when adding a pipe is to be expected; the real problem here is that it appears pipes are losing moles. That's the only thing that explains such a drastic change in pressure by adding so few pipes. This definitely needs looking into.

**Comment by duncathan** [comment]
Just tested on Sybil; no moles are lost when adding pipes, only pressure. This is expected and intended behavior.
