### ISSUE TITLE
Universal recorders records span classes in texts.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#10169]
```universal recorder says, "[00:47] <span class='radio'><span class='name'>[Common] Graham Anderson</span> <span class='message'>says, "<span class=''>To make it noticeable, I will make the majority of them bleed so that they leave a trail.</span>"</span></span>" ```

This wasn't said on the radio but directly by the recorder. The recorder apparently recorded the radio chatter and did not remove the span class stuff.

Possibly linked to #9801 ?

**Comment by Miauw62** [comment]
probably related to me replacing remove_html_properly() by html_encode()

**Comment by Chocobro** [comment]
this bug is still happening. 
![unirecorder](https://cloud.githubusercontent.com/assets/5677255/8627240/93c5528c-2741-11e5-80c1-18d70c01eb2d.png)

**Comment by Miauw62** [comment]
yes i know the PR says "open", meaning that it hasnt been merged yet.
