### ISSUE TITLE
Artificers and Nar-Sie are unable to modify floor tiles

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10180]
All floors are set to generic plating unless they are plating.
Works as intended on space tiles.

**Comment by Boggart** [comment]
I haven't looked into this in any detail but while playing as an artificer I tried to make cult floors in the library and instead turned the wood floor into plating, using it on plating probably has the same result.

**Comment by francinum** [comment]
Nar-Sie seems unable to modify them correctly as well.

**Comment by phil235** [comment]
That's because cult floor and many other floors have been moved to floor/plasteel/cult. The problem is that plasteel/update_icon() change the floor's icon back to the value of the icon_regular_floor var which is "floor" or "plating" most of the time.
