### ISSUE TITLE
Turbine vacuum floor is not reinforced floor

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10183]
Title on the tin. I managed to melt through the incinerator room turbine vacuum floor. Admin said it's just floor with reinforced floor sprite. I assume it's meant to be impervious to heat.

**Comment by WJohn** [comment]
Yeah, I think this only happens on the tile directly above the generator. I'm seeing reinforced floors all around it with the standard high-as-hell heat capacity.

**Comment by Cheridan** [comment]
This must have gotten fixed, I'm not seeing any issue.
