### ISSUE TITLE
Head of Staff lockers are becoming increasingly cluttered with cosmetics

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10185]
It's making it really difficult to use and sift through all the different outfits just so you can grab your equipment.

Please give them a separate wardrobe closet to play dress-up with.

Maybe do this for all equipment lockers.

**Comment by Lumipharon** [comment]
alt click. I'm not opposed to an extra locker but as it is, alt click gets past any issues, and it's not like you open your locker more then maybe twice a round anyway.

**Comment by Kromgar** [comment]
ALT CLICK

**Comment by xxalpha** [comment]
Remove the heads of staff.

**Comment by Dorsisdwarf** [comment]
fixed, pay attention dudes
