### ISSUE TITLE
Blobs shouldn't use reagent datums for hit effects

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10197]
Blobs probably shouldn't use reagent datums for hit bonuses, because reagents don't mesh well with what blobs need to do codewise.
They should instead have datums that aren't reagents, for hitting people, getting a name/color, and maybe other stuff(like different resistances/weaknesses to things) and a reagent that's actually safe to fill mobs with, instead of causing numerous issues.
(this is a maintainability thing, sort of)

**Comment by Iamgoofball** [comment]
# stop using the issue tracker for feedback forum crap

**Comment by xxalpha** [comment]
This is an issue with the code.

**Comment by Anonus** [comment]
Never.

**Comment by Iamgoofball** [comment]
@xxalpha You know damn fucking well this isn't a code issue.

**Comment by xxalpha** [comment]
>Blobs probably shouldn't use reagent datums for hit bonuses, because reagents don't mesh well with what blobs need to do codewise.

**Comment by Iamgoofball** [comment]
And you'd end up redefining basically everything for little to no benefit.

**Comment by Anonus** [comment]
Except if you had them as non-reagent datums you could, you know, make special interactions, like fire blobs taking three hits from welders, or, say, explosive blob exploding at people who melee it with welders, but taking more from brute damage.

**Comment by Iamgoofball** [comment]
And we can do that easily by defining more procs on blob reagent datums only.

**Comment by Anonus** [comment]
If you have to define more procs, you should probably be using a datum specifically for them.

**Comment by Iamgoofball** [comment]
No, we shouldn't

**Comment by optimumtact** [comment]
They should use the reagent datums, but blob specific procs should be added.

**Comment by Iamgoofball** [comment]
^^^

yes that's what I'm saying, we do that

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
