### ISSUE TITLE
Blob cores aren't bomb-immune

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10199]
This is really obvious with the increased cap.

**Comment by Kromgar** [comment]
Good god why. WHY

**Comment by GunHog** [comment]
Are they supposed to be?

**Comment by Incoming5643** [comment]
they used to be, it died a while back, was never sure if intended nerf or bug/accidental feature loss

**Comment by Kromgar** [comment]
Bombs being killed y bombs means science can suicide bomb the blob until they win.

Considering how easy it is to make a max cap bomb its triflingly easy to do so.

(Wish i knew how to make a max cap bomb)

**Comment by PKPenguin321** [comment]
iirc the strong blob walls around the core are supposed to be blast resistant

somebody should test if this is really an issue, because if the strongwalls are pierced and THEN a bomb goes off that would be intentional and i have a feeling that was the case

**Comment by Anonus** [comment]
What happened was, a scientist walked up to near the cores, both with strong blob up, and just activated a maxcap bomb. Took out pretty much all the blob parts except for a resource node.

**Comment by optimumtact** [comment]
Hard to call this a bug, blob needs to protect it's core

**Comment by PKPenguin321** [comment]
yeah, iirc blob cores being bomb immune was really just because at the time we had telesci which could drop bombs onto blobs remotely and instawin

**Comment by Xhuis** [comment]
feature

**Comment by Kromgar** [comment]
Telesci still exists people.

**Comment by PKPenguin321** [comment]
>Telesci still exists people.

yeah but i've only seen one person ever make a fully functioning telesci lab, and that was on extended on basil

**Comment by GunHog** [comment]
TeleScience is too horribly nerfed to be worthwhile now. It takes effort to build, AND you still need a calculator to use it. If it were just a coord + random offset deal, it would be fine.

**Comment by Kromgar** [comment]
Still you can make max cap bombs pretty easily and just have 2 or more people suicide bomb the blob to death

**Comment by Anonus** [comment]
Fun fact blob cores were never actually bomb immune but nobody ever noticed until telesci because the cap was too small to hit the core for instakill
