### ISSUE TITLE
The Space Cube has a (huge) chance to put you in a loop.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#10198]
The space cube doesn't randomize transitions enough, so you can get stuck in a loop.

This is bad because if you are spaced, your speed will be too great for you to be able to change your direction or horizontal/vertical position without a jetpack. You are essentially stuck and will require admin intervention.

**Comment by Incoming5643** [comment]
Feature

Bug

Featured Bug

**Comment by Incoming5643** [comment]
To be fair the fact that getting chucked too fast puts you in a state where you can't actually slow down by throwing things is also a bug.

**Comment by xxalpha** [comment]
Yes, but so is the space cube loop which has existed forever.

**Comment by PKPenguin321** [comment]
pretty much every time i've walked into space to explore in the past 10 or 20 or so rounds i have been unable to do anything but be stuck in a loop or find the mining asteroid to return to the station if i'm lucky
looping is way too common

**Comment by Lumipharon** [comment]
you can slow down, you just need to throw more then 1 thing.

**Comment by AlexanderUlanH** [comment]
Space Rectangle 2016

**Comment by freerealestate** [comment]
Just referencing these so the useful comments are easily readable.

https://github.com/tgstation/-tg-station/issues/5614
https://github.com/tgstation/-tg-station/issues/6338
https://github.com/tgstation/-tg-station/issues/8661
https://github.com/tgstation/-tg-station/issues/8727

**Comment by Shadowlight213** [comment]
Rip spessmen cube
@dorsisdwarf  this can be closed
