### ISSUE TITLE
Syringe/dropper sprites bugged.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#10203]
Dropper sprite icon_states start off with 'dropper', as far as I can tell, they're meant to be either 'dropper0' or 'dropper1' because roundstart and adminspawned ones spawn in as 'dropper' and are thus invisible.

Syringes used to show like a tiny sprite for units below 5 units but they don't anymore, apparently the colour is also more black than it should be.

Reported by Marflow ingame

**Comment by Jordie0608** [comment]
#10200 for the dropper

I'll check the syringe; icon change is intentional, the wrong sprite was being used as a base previously. The color is the same.

**Comment by Ausops** [comment]
neato, thanks
