### ISSUE TITLE
Vending Machine contraband items are supposedly always empty

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10207]
Apparently everyone knows about this issue but nobody reported it?

??????

**Comment by phil235** [comment]
#8993 #8469 It's a recurring issue, every time the list of items inside a vendmachine is changed and the energy amout in resupply packs isn't updated accordingly it fucks up the amount available and contraband is the first thing affected.

A long term solution would be to refactor the vending machine supply system.

**Comment by kyrahabattoir** [comment]
Resupply packs where ment "not" to resupply contraband items tho. I'll have a look at it.

**Comment by phil235** [comment]
>Newly constructed machines draw their items from the supplied packs so it's normal that they don't have sindie items since resupply packs will not touch coin or contraband items.

Actually this has been fixed, contraband and coin items now are supplied by the resupply packs energy. IT causes one issue of contraband items being depleted if you buy some normal items from the machine then deconstruct/reconstruct the machine. A solution could be to give Normal items, coin items and contraband items each their own separate energy for resupply.
