### ISSUE TITLE
Toggling your breath mask no longer works.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10205]
Pulling your breath mask down to eat,drink, or do cpr no longer works and you need to remove the mask to preform those functions.

**Comment by xxalpha** [comment]
Guilty

probably

**Comment by phil235** [comment]
yep, that's because adjustmask() normally add/Remove the var/visor_flags from var/flags but now that there's cover_flags, those aren't affected when adjusting your mask, and that's those flags that are used to check if your mouth is covered.

**Comment by xxalpha** [comment]
I'll look into this later, thanks for the pointer.

**Comment by Marflowerose** [comment]
Also applies for welding masks that are pulled up.

**Comment by phil235** [comment]
It's not mask toggling that doesn't work, it's being able to do certain things with your mask adjusted: eating with your mask down, crp, etc..
