### ISSUE TITLE
Micro/Macrobombs just gib you without any explosion

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#10212]
:hamster:

**Comment by Iamgoofball** [comment]
Huh. I don't really know what to say about this one.

**Comment by Incoming5643** [comment]
imp_in.gib() is called before the explosion, if the gib() resolves before the explosion occurs, the implant may be deleted before it can explode.

**Comment by Xhuis** [comment]
GOOOOOOOOF

**Comment by Anonus** [comment]
Bonus; with my changes they're always slow enough that they'll gib before they trigger the explosion~

**Comment by Marflowerose** [comment]
Happened to me twice, both instances I was already in crit but when dead, I was just gibbed. Never had problems with activating the implant in normal way.

**Comment by PKPenguin321** [comment]
:+1: 
oh wait this is an issue not a PR

**Comment by Lumipharon** [comment]
I consider this a fix, not a bug.

**Comment by Kromgar** [comment]
Implants are only for flops now just fix the explosions already
