### ISSUE TITLE
Spellbooks are bound to mob not mind.

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#10224]
Gibbing wizard/ Wizard going lich makes the spellbook unbound.

I kinda like this as a reward for beating a wizard, but putting this up anyway.

**Comment by PKPenguin321** [comment]
so what you're saying is that if a wizard doesn't use a spell point and gets stripped and gibbed, you could summon guns with his book

**Comment by AnturK** [comment]
Yes. This just happened with summon magic and lich wizard.

**Comment by optimumtact** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
did not add binding but will fix

**Comment by Iamgoofball** [comment]
Whoops, this was my fault.

**Comment by PKPenguin321** [comment]
tbh this is cool as a feature, gib the wizard and get his spells

**Comment by Cheridan** [comment]
Why would a wizard not take all his spells though? Kind of his fault, though I guess spells are all mindbound so this should be consistent with that.

**Comment by PKPenguin321** [comment]
>his fault

leave it as a feature

**Comment by Dorsisdwarf** [comment]
Crushed.
