### ISSUE TITLE
Cannot complete long actions in space

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10235]
When drifting in space, player cannot apply ointment, bruise pack or gauze on self. Also applies to attempting to uncuff self.

**Comment by Xhuis** [comment]
Seems intentional to me

**Comment by Marflowerose** [comment]
Yes but you can do those same things when weightless but just stationary. What's the difference in those tasks if you're moving in space or stationary?

**Comment by Xhuis** [comment]
It's a lot easier to do something when you're not moving at all. Imagine trying to weld down a wall while weightless. Now imagine trying to do it while drifting by in space

**Comment by Marflowerose** [comment]
Yes but the examples I gave was tasks one does on oneself rather than on a wall.

**Comment by phil235** [comment]
Kind of intended, yeah. I guess you can imagine that the mob drifting in space is also spinning which makes complex operations very difficult. Plus, making these actions possible while drifting but not while running sounds pretty tricky to do.

**Comment by PKPenguin321** [comment]
i kind of doubt this is intentional codewise though, especially the cuffs bit

**Comment by Marflowerose** [comment]
Assuming the mob is spinning so fast that it makes complex operations difficult, mob can still:
Inject self with a syringe, apply patches to self, fire a gun at any direction, interact with a backpack, send HoS a message about being shitler, order implant and implant self, reload any gun and best of all, theoretically one can slap ointment on the person drifting with you instantly without any hassle. 
Compare those with slapping some ointment on self, it just doesn't make much logical sense.

**Comment by freerealestate** [comment]
>I guess you can imagine that the mob drifting in space is also spinning
which makes complex operations very difficult.

If the mob was spinning, it would be spinning. Even so, you can still
perform actions that require you to be still while *spinning. We shouldn't
be inventing excuses for inconsistent game design.

**Comment by MrPerson** [comment]
Yeah the code for this isn't "there". I'm trying to fix things up a bit so this can get resolved eventually.
