### ISSUE TITLE
Summon Spells can be casted in Raging Mages

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10232]
I was told this was a bug.

Summon spells totally ruin it for the other wizards who may not have wanted to fight the crew when the game mode is about wizards vs wizards.

**Comment by Marflowerose** [comment]
How is this a bug? Raging Mages is the ultimate annihilation round only comparable to Double Agent after Macrogoofimplants even without summon spells. A crew has hard time even against one wizard let alone several, without summons the crew might aswell just jump out of airlock with epipen, they'll survive longer that way. If the game mode was really about Wizards vs Wizards, they'd be fighting in centcomm arena and not on the station. The game mode is about chaos and summon spells help bring  more of it. Would be better if summon spell actually made Survivors.

**Comment by Incoming5643** [comment]
it was intentionally removed for leading to situations like summon guns x15.

The functionality probably was lost when the spellbook was redone.

**Comment by freerealestate** [comment]
>summon guns x15.

that sounds amazing

**Comment by AnturK** [comment]
Pretty sure i copied checks 1:1, summon events was the only one with raging mages check. I'll check in history to be sure
