### ISSUE TITLE
Asay won't allow just punctuation to be sent

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#10239]
Attempting to send just punctuation via asay causes the message to just be blank.
When I would expect to see 
ADMIN: Ckey/(Name) (FLW):?
I instead see
ADMIN: Ckey/(Name) (FLW):

**Comment by Ricotez** [comment]
semicolons in general appear to be completely sanitized out of asays, even if they're in the middle or at ends of sentences

**Comment by RemieRichards** [comment]
It's because Miauw swapped the encoding from our broken custom proc to the inbuilt one, which is a bit overzealous and can't tell codestrings from just strings.

**Comment by freerealestate** [comment]
feature (^:

**Comment by Miauw62** [comment]
i think i could slightly improve html_encode by wrapping it in a proc that just returns html_encode(html_decode(html_decode(input)). that might work, im not sure.

also, html_encode() is probably the only foolproof way to prevent HTML injection

**Comment by palpatine213** [comment]
critical bug tag needed. Our inability to have smiley faces in asay completely breaks the game for admins.

**Comment by palpatine213** [comment]
Fixed by #10327
