### ISSUE TITLE
Medbots OD you on bicaridine

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#10241]
See above

**Comment by PKPenguin321** [comment]
and antitoxin

i believe it happens when two medibots see you at once and both inject you

**Comment by Iamgoofball** [comment]
This is user error.

Having 2 medibots is not any more effective than having 1 in an area.

Spread out your medibots.

**Comment by GunHog** [comment]
Not really going to call this a bug. We do not need code for a medibot to check for other nearby medibots healing the same person.

**Comment by Marflowerose** [comment]
What about check to see if the person already has said reagents before jabbing more?

**Comment by Iamgoofball** [comment]
I could but I want to encourage people to not cluster their medibots because it's flat out a bad idea.

**Comment by PKPenguin321** [comment]
>What about check to see if the person already has said reagents before jabbing more?

they already do this, but if two medibots see you with 0u of the reagent in your body at the same time, they will both inject you and once the process has started they will not stop halfway

**Comment by phil235** [comment]
We could change the overdose threshold or the amount of reagent injected by the medibot so that it takes three medibots to overdose you. Having two medibots close happens fairly often unfortunately.

**Comment by Dorsisdwarf** [comment]
Excuse me

There were not too medibots.

A single medibot saw me, shouted at me, injected me, I immediately got the bicaridine OD message, then went from nearly full HP to crit in about fifteen seconds.

**Comment by bgobandit** [comment]
are you sure it wasn't emagged/otherwise tampered with

**Comment by Supermichael777** [comment]
looks like the way it handles overdose will kill if you have more than 50 units so 4 medbots. 1 medbots should not be that leathal unless I'm misreading this

**Comment by Supermichael777** [comment]
oh wow someone put brute loss instead of oxyloss there so an od is leathal at 30 units (25*4 you don't heal because of how it resolves) looks like you would stay up for a few minutes though.

**Comment by Supermichael777** [comment]
oh wow someone put brute loss instead of oxyloss there so an od is leathal at 30 units (25*4 you don't heal because of how it resolves) looks like you would stay up for a few minutes though.

**Comment by Supermichael777** [comment]
sorry for tripple post can't eddit my posts from phone. how fast is this supposed to heal you? how many units are processed per second?

**Comment by GunHog** [comment]
You can mantually set the medibot's injection levels through the interface. Default is 15. Does 15 u of any chemical the Medibot uses result in an OD? Emagged medibots inject Toxins instead.

**Comment by Supermichael777** [comment]
oh damn if this is in you system and oding you take all brute healing as 4* brute damage.

**Comment by Supermichael777** [comment]
od is 30 on bicard but the way it's handled is shitty

**Comment by Strathcona** [comment]
Change the default medibot amount to be just under half of the OD threshold.

**Comment by GunHog** [comment]
>Change the default medibot amount to be just under half of the OD threshold.

This is already true. Medibots inject a maximum of 15 units (which can be adjusted via its interface), and do not attempt to add more while they detect it in your mob. The OP was likely injected by two medibots at the same time.

**Comment by Strathcona** [comment]
Is the OD code > or >=? If it's the later 15 and 15 will trigger the OD, if it's the first it'll work as intended. I think the simple solution here is just make it so two simultaneous medibot injections will never put you at or over the threshold.

**Comment by phil235** [comment]
>There were not two medibots.
A single medibot saw me, shouted at me, injected me, I immediately got the bicaridine OD message, then went from nearly full HP to crit in about fifteen seconds.

Can't reproduce with only one medibot.

**Comment by Iamgoofball** [comment]
OD threshold should be 30.

**Comment by GunHog** [comment]
The OD threshold is indeed 30, and the max a medibot injects is 15. They do not attempt to inject someone who already has been recently injected. The only way this issue is possible is if two or more medibots inject at the same time.

Note that sometimes people place two or more medibots on the same tile, so you would see them as only one bot. Perhaps that is what happened?

**Comment by Dorsisdwarf** [comment]
Unless medbots shouting/pointing/injecting messages are pooled so that only one ever displays, I don't see how that could be the case

**Comment by Strathcona** [comment]
Well then is it possible someone had tampered with the medibot? Set it's max inject to 30?

**Comment by GunHog** [comment]
The maximum injection amount of a medibot is hard-coded to 15. A reliable reproduction is required before any changes can/should be made.
