### ISSUE TITLE
Resin walls do not update when connected pieces are destroyed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10240]
What it says on the tin.

![](http://i.imgur.com/KBeTV3N.png)

**Comment by CosmicScientist** [comment]
This also happens for regular walls, I'm not sure about full glass though.

**Comment by Lumipharon** [comment]
happens with regular and r-walls. I assume it happens with all walltypes.

**Comment by Jalleo** [comment]
I think we got a new wall smoothingcode recently could that cause it?

**Comment by WJohn** [comment]
This should get fixed by xxalpha's new wall smoothing, that should hopefully come soon.
