### ISSUE TITLE
Active turfs at roundstart on box

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10253]
>## WARNING: There are 193 active turfs at roundstart, this is a mapping error caused by a difference of the air between the adjacent turfs.

I'm sure every coder has already seen this, but I couldn't find this in the issue tracker, so I thought I'd report it.

**Comment by Incoming5643** [comment]
This message would be a lot more useful if they stated the areas where these turfs were found.

I'm gonna bet most of them are on the derelict

**Comment by Ricotez** [comment]
I think it might be related to the unsim removal or whatever that thing was

**Comment by duncathan** [comment]
The atmos alert computer starts the round with some high priority alerts that very quickly get resolved. By the time I'm able to check it (a second or so after roundstart) they've diminished to one low-priority alert in the AI satellite exterior. That may be a good place to start checking.
