### ISSUE TITLE
There's a stranger in Ian's house!

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#10252]
The kennel box in the HOPs office comes with a free corgi, either lisa or a generic.

**Comment by Jordie0608** [comment]
@TheVekter

**Comment by freerealestate** [comment]
feature

**Comment by TheVekter** [comment]
Uhhh, yeah! Ian has a new friend! I forgot to put it in the changelog.. <_< >_>

I'm replacing that with a dog bed anyway. I'll sort this out in the morning.
