### ISSUE TITLE
Voice changing mechanics do not change race.

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#10264]
As the title states, using a voice changer or the changeling's voice mimic does not allow the user to change his or her voice to that of another race, i.e. humans cannot (effectively) pretend to be lizards over comms, and lizards cannot pretend to be humans.

In accordance with coderbus' advice, I request, via issue report, that this be remedied in the interest of promoting equal-opportunity traitorous scum.

**Comment by Miauw62** [comment]
fucking liggers

**Comment by demonfiren** [comment]
I love you too, Miauw.

**Comment by Dorsisdwarf** [comment]
fixed by #10274

**Comment by Dorsisdwarf** [comment]
Why is this open again
