### ISSUE TITLE
"Check antagonists" Link on new player panel not working

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#10273]
The bluetext link on the Player Panel doesn't work. Doesn't link you to the Check antagonists page.

(edit by phil235: I removed the image showing the IP)

**Comment by MrStonedOne** [comment]
>putting somebody's ip on github for all to see.

Deadmined!

**Comment by peoplearestrange** [comment]
Shit I did?! Im sure I removed them all :/ I'll check the pic when Im home and edit and re-upload it.
(Thanks Phil!)

**Comment by bgobandit** [comment]
can a maintainer close this, it works now
