### ISSUE TITLE
Cyborg mesons are useless

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#10288]
78daa216709836c8aa86de0600b4c3adc98fffdb

They show the station layout like your normal mesons, but only show power lines, pipes, etc on the tile you're on - unless the area is lit, of course. 
Having to swap the flashlight in and out while autism-ing it up as an engiborg is just terrible. It's almost as bad as the module swap dance as a miner borg.

**Comment by Marflowerose** [comment]
This is why we need integrated Cyborg Light, like drones have integrated light. Engiborg is notoriously fiddly with juggling all 3 modules to get anything done.

**Comment by Dorsisdwarf** [comment]
B-bu-but we h-have t-to n-nerf all the silicons! They might even become....



fun



otherwise...

**Comment by GunHog** [comment]
Paprika removed their NVG Mesons. I would like to give those back.

**Comment by xxalpha** [comment]
Yeah this is awful.

**Comment by Actionb** [comment]
The minerborg already has the ability to leave its scanner running even if it's not in an active module slot. Do the same to lights (flashlight and lantern) and mesons. Or add a third option to the medical/security overlay: mesons. Whatever works. 
Having to have two slots occupied at all times to do your job is just silly.

**Comment by xxalpha** [comment]
Cyborg flashlights is retarded, they should be built into all cyborgs, not as modules.

**Comment by Lumipharon** [comment]
Cyborgs have flashes for eyeballs. Making them emit light without module fiddling isn't that much of a stretch.

**Comment by GunHog** [comment]
I think I can work something out for this.

**Comment by Dorsisdwarf** [comment]
Yes!

**Comment by Cebasiz** [comment]
we have the nice buttons at the top

make mesons and other vision modes including flashlights a toggle up there and not a module

though once you are in "cyborg crit" no modules allowed mode due to damage it should probably shut off just to be consistent.

**Comment by duncathan** [comment]
Mostly fixed by #10343
