### ISSUE TITLE
Centcom can be inflitrated

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#10290]
Build an autocloner and autolathe on the cargo shuttle, autoclone yourself and voila. You are there. Nothing fancy to steal, except the centcom shuttle, sadly.

**Comment by freerealestate** [comment]
Centcom being off-limits is needless anyway. Provided players can't get
into the space surrounding Centcom, it doesn't matter.

**Comment by phil235** [comment]
duplicate of #7690 actually
