### ISSUE TITLE
New Map Merge is terrible

### ISSUE THREAD

**Issue by Cheridan** [tgstation/-tg-station#10300]
added in #9784

Running the Preparer works fine, but the merge tool you have to use afterwards is disgusting. You have to type in the full _map folder path every time, you then pick a SINGLE map and then afterwards the program shuts down, and you have to reopen it and then type in the _map folder path again and pick a new map. This makes editing multiple z-levels a horrible chore.

**Comment by Cheridan** [comment]
The map folder path needs to get saved/read from somewhere so you don't have to type it in every time.

Why the hell was the readme.txt removed?

**Comment by Ikarrus** [comment]
Well hey you understand what I've been bitching about all this time on coderbus now.

**Comment by optimumtact** [comment]
I might take a look, although it's been a while since I touched java

**Comment by optimumtact** [comment]
@CorruptComputer any easy wins here?

**Comment by TheVekter** [comment]
Hey look, the fucking preparer STILL DOESN'T WORK FOR ME, and no one has been able to find out why! It doesn't make any backups anywhere, it just prints text and fucks off, and if I run it in admin it says "Cannot find the file specified".

The old one worked for a little bit but then HEY NOW WE'VE CHANGED IT FOR NO REASON so it broke again.

**Comment by optimumtact** [comment]
pebkac

**Comment by TheVekter** [comment]
@optimumtact I'll get on IRC in a moment also >pebkac >open a fucking batch file

**Comment by TheVekter** [comment]
#10305 SUCK A DIIIICK told you it was broken

**Comment by CorruptComputer** [comment]
I never took into consideration editing multiple z-levels, and I made it an input for the maps folder so that other code bases could easily port it.

**Comment by CorruptComputer** [comment]
Also you don't need the directory for the _maps folder, it scans every file in that folder and subfolder for the .dmm extension.

**Comment by TheVekter** [comment]
@CorruptComputer Is it not possible to give the damn thing a gui? Like even a SUPER BASIC java one?

**Comment by CorruptComputer** [comment]
I've never made GUI's in java, so thats something I cannot do, I just updated it as best as I could.

**Comment by CorruptComputer** [comment]
@Cheridan I can easily make it take multiple numbers or run again, which would be better?

**Comment by Miauw62** [comment]
wasn't there a PR that added a menu where you could select all valid paths?

**Comment by Steelpoint** [comment]
Whatever happened to the map merge tool is absolutely horrifying to behold.

**Comment by Alek2ander** [comment]
Just set a default path. ../../_maps is usually it.

**Comment by Rinoka** [comment]
@CorruptComputer 

I've done Java UIs before. If you need/want assistance there, just let me know; it's not particularly hard.
