### ISSUE TITLE
You can run into your own bullet really easily

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#10315]
if you run forwards while shooting, you'll hit yourself. A lot.
![untitled](https://cloud.githubusercontent.com/assets/7869430/8453598/3e08e8ac-204a-11e5-8bb6-f8e3928c6a87.jpg)

I assume it's only a real issue with burst fire weapons, but I'm sure someone else will know more then me, but I was hitting myself with 2/3 shots per burst, which is pretty retarded.

**Comment by phil235** [comment]
Pretty sure this is burst fire's fault, it doesn't check whether you're moving, if a burst is started it will be finished

**Comment by Dorsisdwarf** [comment]
This is, indeed Burst Fire's fault. (I found it while coding the minigun)

 Bursts all fire from the gun towards the target you clicked on. For long bursts or rapidly moving shooters, this lets you move onto the tile you clicked, meaning you become the target and get bulletted/

**Comment by Lumipharon** [comment]
So burst fire fires all the bullets from the tile it started at, not where not firing mob/thingo is?
Honk.

**Comment by phil235** [comment]
Apparently this also happens for mobs shooting guns, which is odd since projectile/Bump() has a specific check so that the shooter can't theoretically never be hit by his own bullet. Something's wrong somewhere.. :confused:
