### ISSUE TITLE
Walls/windows, tables, carpets, and grass all use different code and methods to achieve smoothness.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10320]
Currently we have like at least 4 different kinds of smoothwall: smooth carpet, smooth this, smooth that turfs and objects. Some do the basic like walls and windows, which have an ugly "corner hole" issue with 2x2 walls. Tables have that solved but are incapable of + shapes and many other shapes without going full fill, and are also full of ugly and jarring gradients. Carpets go maximum in this regard and can do every possible shape, but unfortunately this is super huge and bloated in floors.dmi. Finally, grass uses yellow borders so that *in theory* it can have multiple different looking grass tiles to help deal with repetitive looking textures, but this isn't even used.

This is kind of insane.

I propose instead that we use one unified method that's been discussed in coderbus for a while: Splitting up these objects and turfs into 4 corner overlays, and then assembling them as necessary. This, if flatly laid out, is slightly more space consuming in the .dmi (or we could just use directions and solve that), but fixes the above 2x2 wall "corner hole" bug and also every issue tables experience.

I've made a quick representation of what we have (top) and what we could have (bottom).
http://i.imgur.com/Zy3IwVz.png

Effectively, we need only swap out these corner overlays (which will be separated from the others, it won't be grouped up like those in the .dmi) and then assemble them in game as necessary. More specifically, you need to swap out those color coded corners in order to achieve this. This works with walls, windows, tables, carpets and grass, fixes the above mentioned visual bug, works with transparency, works with unevenly spread textures like uranium walls, is compact, and pretty easy to understand for newer spriters.

I'd be happy to provide the sprites for this, as well as fix up our current table sprites (which are full of random gradients themselves).

EDIT: I've gone ahead and done the sprites beforehand, so that anyone who's interested in trying this out will know exactly what to work with.
http://www.mediafire.com/download/rc4mo931qjdcfwq/Smooth_Walls_Overhaul.rar

If you need something edited or a bunch of stuff changed around because you want to handle it differently, let me know.

**Comment by Rinoka** [comment]
How many sprites would this take compared to what we have now? It looks like each corner needs an inner corner, an outer corner, and two variations of smooth in a direction, and flat (for when you have a double+ thick wall) so 5 possible states for 4 areas = 20 sprites. This is 4 states more than what we have for stuff like rwalls.

I do think smoothcode needs to be fixed, it's horrendously spread out right now. But I'm wondering if this is the solution we really want.

**Comment by WJohn** [comment]
It's 20 sprites, yes. If we make use of directions it'd likely be possible to shrink it down to 5 spaces or less.

**Comment by Rinoka** [comment]
On-point; I forgot that overlay rotation is a thing the game supports. Guess the only real reason to wonder if this is a good idea would be determining how efficient this is server-side.

**Comment by WJohn** [comment]
Overlay rotation has been discussed before, and the problem is that it would not work for our tables or for walls with uneven textures, such as uranium and plasma walls.

**Comment by Rinoka** [comment]
Tables is fine; honestly, if it'd fix the tables being silly I'm all for just separate pieces for each.

Walls with uneven textures... All I can say is "why don't we just even them out". I'm sure there's a good way to do it that lets it smooth nicely.

**Comment by WJohn** [comment]
No I mean it actually wouldn't work for tables at all, the top and bottom halves aren't even, and it'd also be a huge limitation to other stuff like lava flows (which I'm working on right now).

The method in the OP works with all of these while not being all that big.

**Comment by Rinoka** [comment]
Yeah, I wasn't disagreeing. Tables would need a similar but separate system, and lava flows would too.

For stationary objects with even corners, I think I like the rotational idea.

**Comment by Jordie0608** [comment]
I've wanted to (and MSO has wanted me to) do this with walls for quite a while now. It's not quite as simple as you make it sound but I can give it a shot. If you're going to cut up the sprites for this into corners i'd suggest you wait until a prototype is done as the sprites used may be different from what you've planned.

**Comment by Supermichael777** [comment]
didn't smooth wall produce the coderant of the century?

**Comment by WJohn** [comment]
Currently working on the sprites for this, there's quite a number of them and I had to overhaul all of the tables to remove that weird-ass gradient some of them had, as well as actually create entirely new sprites (and massively redo) ausops's ayylien tables. There's 6 tables (7 if xeno nests ever get turned properly into tables like it was supposed to be), 14 walls, and 3 windows that are getting their sprites changed to this.

I decided to store these things in 5 separate spots using directions (fill, vertical, horizontal, outside corners, and inside corners), but you can make this more compact if you want and know how to pull it off in your code (combining vertical and horizontal into an 8 direction thing, likewise with the corners).

Should be done soon, the hardest part was redoing and standardizing most of the tables.

**Comment by WJohn** [comment]
Sprites are done: http://www.mediafire.com/download/rc4mo931qjdcfwq/Smooth_Walls_Overhaul.rar
