### ISSUE TITLE
no button on top left of screen for integrated jetpacks

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#10322]
kind of a consistency issue; back-mounted jetpacks have an easy off/on switch that's extremely nice to have. it's actually worse on the internal ones because when you reslot your air-tank it resets the state of the jetpack, meaning you have to toggle it on/off far more often. is it possible to add a button for this?

**Comment by xxalpha** [comment]
I'll look into it. Due to limitations at the time, a button could not exist. The button system changed, so maybe now it's possible.

**Comment by Falamazeer** [comment]
Fingers crossed, here's hoping it works.
