### ISSUE TITLE
Doors: Fast Close Doesn't work

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10326]
Currently, if you override a door's timings and open it, it won't close nearly immediately; it behaves exactly as a normal door--as a matter of fact, doors that have their timing overridden will actually *never* close, once opened.

**Comment by Supermichael777** [comment]
door code is a mess, a readable mess but still so bloated that I can't even find where the timing toggle is.

**Comment by phil235** [comment]
duplicate of #7039
