### ISSUE TITLE
Damp Rag and Morphine

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10323]
Morphine is overpowered, that's nothing new. Using it with Damp Rag however makes it even more cheesier as it can be used to instantly knock out someone without any time delay, red big message or actual reaction to counter it. I don't know how much reagents one use applies but it knocked out instantly.

**Comment by Iamgoofball** [comment]
Instantly? Are you sure it was morphine? Morphine has a delay.

**Comment by AlexanderUlanH** [comment]
I don't know what happened, but it definitely wasn't that morphine knocked you out instantly, because it doesn't.

**Comment by Marflowerose** [comment]
I cannot verify that it was morphine but in OOC later the person using the rag said it was just morphine.

**Comment by Marflowerose** [comment]
Did a bit of testing, the rag seems to take 5 units of reagent, which is weirdly enough to knock out for about a minute after 5-10 seconds, which is enough to shout for help I guess. Aside from goonchem goofiness, there should at least be one of those big red texts when you get ragged.

**Comment by Supermichael777** [comment]
Wait so rag and drag is viable? cool.

**Comment by Lumipharon** [comment]
You can put perflu and neurotox (the drink) in the rag for instant stun + mute.
It's pretty funny. It's instant, but it does give a big message that you're smothering them.

**Comment by Marflowerose** [comment]
Are you sure it gave same big message as being attacked/forcefed does? I only got regular sized red text

**Comment by Lumipharon** [comment]
It might be the same size, but it's in nice visible red.
