### ISSUE TITLE
ai camera issues

### ISSUE THREAD

**Issue by Deitus** [tgstation/-tg-station#10333]
had an issue where clicking on people's names in chat as AI wouldnt allow tracking and came up as not near cameras, even in instances where they were; however, was able to track through the crew list button. restarted byond, worked for first track, then stopped working again.

**Comment by Cebasiz** [comment]
i reported the same and the coders said it was a tcommscript issue. was there a script on tcomms at the time?

**Comment by Deitus** [comment]
actually i think there was, yes. that must have been what happened i guess, i dont know what else it couldve been

**Comment by Marflowerose** [comment]
Tons of duplicates about this, it's probably the comms scripts.

**Comment by Miauw62** [comment]
yeah, this is a dupe. not entirely sure how to handle this issue
