### ISSUE TITLE
Teleportation

### ISSUE THREAD

**Issue by mazen30** [tgstation/-tg-station#10330]
When i was in a mech in my first abductor round i was stormed around by people so i clicked emergency beam and got teleported back,i was taking messsages of mech getting damaged and then when it blew,i automatically got teleported back to the dead mech and got killed,please fix it.

**Comment by Incoming5643** [comment]
A side effect of mechs holding reference to a human pilot in some other fashion than having the human in their contents

**Comment by Thunder12345** [comment]
Another reason to violently rip out mech code and recode them from scratch. Mech code tag when?

**Comment by xxalpha** [comment]
I like the color.
