### ISSUE TITLE
Explosions can kill people by lack of oxygen

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10331]
Steps to repeat:
1.Be by a explosion wearing a spacesuit and setup internals E.G a explosive chem blob
2. Go out into space your rigsuit helmet is still there
3. Find out that your internal slot had its item destoryed E.G gas mask, breath mask
4. Go to @Ikarrus and check if this is a bug and confirms it is

**Comment by Ikarrus** [comment]
Masks shouldn't be deleted by explosions if they're covered by helmets. I'll look into this.

**Comment by Lumipharon** [comment]
Why did we go back to explosions destroying items?
