### ISSUE TITLE
Nobody can join half the jobs

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10340]
1) Have Mutant_Humans disabled
2) Find out you can't join as half the jobs
3) Realize it's because ears defaults to on, and the code doesn't check if Mutant_Humans is disabled

Everyone defaults to being a mutant, having the config option off prevents people from setting themselves back to normal, thus barring them from most jobs.

**Comment by Ikarrus** [comment]
@ricotez

**Comment by Ikarrus** [comment]
The servers will have to have the config option remain enabled until the issue can be resolved.

**Comment by duncathan** [comment]
:+1:

**Comment by Incoming5643** [comment]
Rush fixing this

**Comment by Incoming5643** [comment]
@Ikarrus @MrStonedOne kill the mutant_humans
