### ISSUE TITLE
Players are still starting with cat ears with no way of removing them

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10349]
If mutant_humans are off.

@ricotez
@Incoming5643

**Comment by Incoming5643** [comment]
apparently the setting for ears/tail wasn't saving, and spontaneously turns it on on a chance every round. In an equally existant bug for some reason mutant_humans does not actually quash the ability of those parts from being seen.

https://github.com/tgstation/-tg-station/pull/9986#issuecomment-112236450

**Comment by Ricotez** [comment]
I'm working on a fix, I am sorry that this happened. I just realized I've probably never actually tested the null case since I just created new characters on the fly.

**Comment by Incoming5643** [comment]
@Ricotez was already on it

**Comment by Ricotez** [comment]
@Incoming5643 your fix isn't actually a fix, just remedies the symptoms
