### ISSUE TITLE
Teleporter remains on regardless of power

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#10347]
![shitswackyo](https://cloud.githubusercontent.com/assets/4043781/8501301/1a55d200-219c-11e5-8eef-a6d1a8641984.PNG)

You cant interact with the console or station, but the actual teleporter remains powered.
As you can see on the APC, equipment power is off.

Edit: Of course the picture caught the animation in a frame where nothing is happening.
rofl.

**Comment by Shadowlight213** [comment]
It's pretty funny to see the teleporter powered and flying around a loose singulo in space.
Once saw someone get saved from being eaten by managing to enter it.
