### ISSUE TITLE
40MM DEATH CYLINDERS

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10352]
I don't know what happened but they are literally a wand of death if they hit you in the chest

Not saying this goes against whatever muh realisms argument there is but the Syndiborg having a spammable deathbolt is pretty lame. Same goes for the GL90. Guessing this was caused by the explosions changes, because this was not the case a while ago.

**Comment by WJohn** [comment]
I think it does 74 brute if you are unarmored and it hits you square on, if you HAPPEN to be set on fire as well then yeah, you'll be stunned long enough for it to knock you into crit. I don't know if its damage has changed with the new explosion code, I'd need to test it.

**Comment by Cebasiz** [comment]
it's 40mm amigo it wipes out squads when used correctly

muh realism

**Comment by SconesC** [comment]
Yeah except having a 6-shot endless-range version is

Dumb

**Comment by Cebasiz** [comment]
eh i don't know. you're talking about the m90 right? is it a grenade launcher?

i suppose it's basically a copy of that real life one then which also has six barrels. anyway if it's too good just hike the price but i don't think i've ever seen one used.

underbarrel grenade launchers when, anyway?

**Comment by SconesC** [comment]
I'm talking about the gun

With the underbarrel

**Comment by optimumtact** [comment]
Endless range should be flagged as a bug, the rest probably is arguable, I never really liked multi shot grenade launchers, because they're strong as fuck

**Comment by SconesC** [comment]
I could accept that a direct hit from a grenade should fucking murk me

I'm only bitching because a syndiborg can roll up like AYY LMAO MEATBAG and rapidly pump six or so in my general direction, practically ensuring that if I don't die to a direct hit, the blasts combined will kill/ignite/KO me

**Comment by Aranclanos** [comment]
please use the feedback forums for this
