### ISSUE TITLE
Bombs and hardsuits don't mix well

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#10366]
If shredding RNG decides to break something, it can range between your suit or the suit's helm. Breaking the suit leaves the user with a hardsuit helm they can't remove, and breaking the helm leaves the user with a useless suit that can still engage/disengage the now non-existent helmet. The helmet's overlay also becomes stuck on their sprite and needs to be fixed via admins to make it go away.

Nothing like making the life of a shaft miner all that much more painful honk honk.

**Comment by Ikarrus** [comment]
>Breaking the suit leaves the user with a hardsuit helm they can't remove

This should be fixed as of a few days ago

>breaking the helm leaves the user with a useless suit that can still engage/disengage the now non-existent helmet

What we could do is make the helmets just outright invincible to bombs. But I'll have to see how others feel about this.

>The helmet's overlay also becomes stuck on their sprite and needs to be fixed via admins to make it go away.
Just needs an update_icons() call somewhere

**Comment by Ikarrus** [comment]
Well, upon further discussion, it looks like the best way may be to simply allow the player to repair a damaged suit if they lost their helmet.

It still makes sense logically, and acid works the same way. Either way, this is more of a feature request now than a bug.

**Comment by phil235** [comment]
Fixed. If the suit is destroyed, the helmet automatically is as well, and vice versa.
