### ISSUE TITLE
New throwing mechanics are bad

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#10363]
If you throw a sealed container, like a drink can or a bottle (that hasn't even been opened, let alone ones that have lids/caps/corks, it spills the entire contents.

This doesn't make sense and is silly.

This was specifically happening with bartender also.

**Comment by Kromgar** [comment]
Bartenders now have special ability to throw drinks without spilling

**Comment by Ikarrus** [comment]
I'm guessing checking for the OPEN_CONTAINER flag doesn't cut it, @phil235 ?

**Comment by Lumipharon** [comment]
>Bartenders now have special ability to throw drinks without spilling

This was specifically occuring while I was the bartender.
But even that aside, I don't think it's that unreasonable to throw a sealed container and not had all the contents spill out.

**Comment by AlexanderUlanH** [comment]
The fix to this would be to implement opening cans / screwing caps on bottles.  Those things have open_container to reflect that they're probably open when you're trying to transfer things to or from them.

**Comment by Ikarrus** [comment]
We could probably just make a new flag to use

**Comment by Boredone** [comment]
On a related note, if you throw something full of water, it empties, but the ground isn't wet.
That intentional or?

**Comment by Lumipharon** [comment]
Yeah there's no feedback at all as to whether the thing you just threw spilt anything or not.

**Comment by Ikarrus** [comment]
>On a related note, if you throw something full of water, it empties, but the ground isn't wet.
That intentional or?

For whatever reason, unrelated to the spilling change, water doesn't make floors slippery any more. You can even try with a spray bottle. It does nothing.

That's a different issue altogether.

**Comment by phil235** [comment]
@ikarrus , yeah this might need a new flag or a new mechanic to open/close bottles and cans. Right now bottles and cans always have the OPEN_CONTAINER flag that's why it always spill.

**Comment by Ikarrus** [comment]
I'd rather just add a new one for SPILLABLE instead of adding another pointless toggle.

**Comment by Ikarrus** [comment]
Apparently we're all out of item bitflags, so I might just use a var instead

**Comment by Miauw62** [comment]
If you want, you could convert NODROP to a var, which is something that really should happen but that i've been too lazy to do.
