### ISSUE TITLE
Bomb Suits blown off by new bombs mechanic

### ISSUE THREAD

**Issue by Mongke1356** [tgstation/-tg-station#10364]
While disarming a syndie bomb it blew up in my face and either destroyed my bombsuit or ripped it off but either way I was still gibbed by it

**Comment by Iamgoofball** [comment]
@Ikarrus

**Comment by Ikarrus** [comment]
The actual checks to determine your damage, or if you're gibbed, is done before the clothing shredding happens.

So whatever is causing this bug (if it is one) is likely not due to clothing shredding.

Are you sure you had the helmet on as well?

**Comment by Mongke1356** [comment]
Yeah I was wearing everything in the sec bombsuit locker except the black Jumpsuit, I was wearing the normal sec one Im not sure if that makes a difference

**Comment by Ikarrus** [comment]
Not sure, then. Unless there's special code with the syndicate bomb to gib you, the problem may lie with check_armor()

**Comment by xxalpha** [comment]
Bomb suits shouldn't be destroyed.

**Comment by Dorsisdwarf** [comment]
Probbably fixed
