### ISSUE TITLE
Playable husk race

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#10367]
If someone is burned to the point of husking but then healed enough to get defibrillated, they'll keep the husked overlay.

It's kinda cool looking, but also obviously not intended.

**Comment by Marflowerose** [comment]
Yeah, this creates a bit of metaconfusion, is the walking husk a changeling that was drained or just some burn victim?

**Comment by Incoming5643** [comment]
I've only seen the latter but the former might be possible too?

**Comment by Iamgoofball** [comment]
i don't see a problem with the metaconfusion, more paranoia and confusion is good

**Comment by Supermichael777** [comment]
wait lings husked by other lings can still come back?

**Comment by RemieRichards** [comment]
Lings husked by ANY method (Space/Other lings) can INDEED come back. you have to incinerate lings, even other lings have to incinerate other lings.

**Comment by Dorsisdwarf** [comment]
A reminder that you can steal all of a changelings geonomes by absorbing them. Extra kek on people with escape as objectives who killed and spaced the imitatee

**Comment by Incoming5643** [comment]
another changeling protip: you don't need to steal an id to escape as a target, if you modify your own ids/another id to read as the target's name and job, it counts.

If you don't have to kill the target this additionally means that you you can additionally both make it centcom safe and sound as the same person. It's all kosher

**Comment by Dorsisdwarf** [comment]
Issuemageddon: the killening
