### ISSUE TITLE
DEAD: Krystal Symers says, "bears OP"

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10372]
>The space bear stares alertly at Krystal Symers
The giant spider chitters
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Lindsay Donk
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stares alertly at Krystal Symers
The space bear stomps

The spam was actually about four times as long as this, but you get the drift.

**Comment by Iamgoofball** [comment]
https://github.com/d3athrow/vgstation13/pull/5061

port when

**Comment by phil235** [comment]
Can we have more details about this? How long did it take to create all this spam?

**Comment by Chiefwaffles** [comment]
If this is from the round I'm thinking of, the spam all appeared at once.

**Comment by freerealestate** [comment]
It was instantaneous.

**Comment by phil235** [comment]
how many bears were there? Just one?

**Comment by freerealestate** [comment]
Not sure, sorry.
