### ISSUE TITLE
Water doesn't make the floor slippery any more

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10370]
Try spilling or spraying water onto the floor. It doesn't slip you any more.

RIP fun.

**Comment by Boredone** [comment]
Spraying worked for me. Didn't have anything on hand to test spilling, like via a bucket or something though.

**Comment by phil235** [comment]
@ikarrus did you spray 5 or 10u ? You need to use 10u to make floor slippery now.

**Comment by duncathan** [comment]
This killed me weeks ago because I expected spraying the ground with my portable extinguisher as atmos tech would slip the guy attacking me.

**Comment by freerealestate** [comment]
Who designed spray bottles to work this way now? It doesn't make any sense. You either get a mist, or it just dumps the chemical on a tile in front of you. What spray bottle works like that?
