### ISSUE TITLE
Bug: Steal the Plutonium Core objective

### ISSUE THREAD

**Issue by Anonmare** [tgstation/-tg-station#10377]
Server: Basil

Revision: b6813ff0e4e2e4b7cf388a133a527378bd549d20 

Problem Description: It was impossible to remove the core without admin intervention and to place the spawned core in the nuke container.The Nuke Breaching Plans you spawn with are also completely blank.

What did you expect to happen: I expected to have been able to remove the core but it proved impossible.

What happened instead: I could remove the terminal's plate easy enough but on the "draw cut lines" part I hit a snag as nothing I used would work except wirecutters but it just says I "Cut the wrong wire" and giving me a big boost of rads.

Why is this bad/What are the consequences: It makes this objective impossible and if you spend too long trying to get it to work then you'll get caught through no fault of your own.

Steps to reproduce the problem: I broke into the vault where the self-destruct device is and used the screwdriver provided to remove the panel but that's as far as I could get.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): It was the traitor gamemode but that's as far as relevancy goes.

**Comment by Anonus** [comment]
This is because the person who implemented it was an asshole; all of this is intended and it's possible to remove the core(but the instructions on how to do so are 90% wrong!)

**Comment by Razharas** [comment]
Top notch game design 5/5 gabe jelly

**Comment by Dorsisdwarf** [comment]
Why the fuck did he make it wrong?

??!??!?!?!

Seriously, thats shitty. I didnt catch that in the PR

**Comment by xxalpha** [comment]
Read the instructions, buddy.

**Comment by Anonus** [comment]
The instructions are outright wrong!

**Comment by xxalpha** [comment]
They aren't.

**Comment by Miauw62** [comment]
they are

**Comment by Steelpoint** [comment]
I just tested doing this objective in game, I should also note I have yet to see anyone accomplish this objective in game.

I honestly had no idea what to do, I either kept irradiating myself or doing nothing.

I looked at the code and what you actually have to do is insane? Not for the impossiblity but because there's absolutely no hint as to what you have to do.

Here's how you do the objective:
1: Screwdriver open the front panel with the screwdriver.
2: Using a Cable Coil, use it on the nuke to tie up loose cables.
3: Use a pen to draw in "cut" lines on the wires
4: Use a wielder to cut the wires.
5: Use your Nuke Core Container to contain the nuke. Oh but if your not wearing a rad suit you'll go into crit in three seconds, so wear one before wielding it open.

Honestly this is unintuitive.

**Comment by CorruptComputer** [comment]
Here's how it should be:
1: Screwdriver open the front panel with the screwdriver.
2: Use a wire cutter to cut the wires. (Could pop up and bee like doors, with a bunch of different colors. With a chance of blowing the station.) 
3. Use a welder to cut through the radiation shielding. 
4: Use your Nuke Core Container to contain the nuke.

**Comment by Miauw62** [comment]
>giving people a way to easily nuke the station

NO WAY THAT COULD GO WRONG, RIGHT????

**Comment by CorruptComputer** [comment]
Honestly that's an admins problem, just add logging whe  someone enters the vault.

**Comment by Steelpoint** [comment]
I don't think you can actually remove the nuke core once you've contained it.

Besides, all this is is obfuscating a game play objective for no good reason, its hard enough to break into the vault core let alone trying to steal bloody nuke core.

**Comment by Miauw62** [comment]
corruptcomputer: if you ban somebody after they detonate the nuke the round is still completely ruined. hell, if somebody ACCIDENTALLY sets off the nuke the round is still fucked for everybody. it's just a terrible idea even if you dont consider griefers.
there's a very good reason only admins know the nuke code.

**Comment by CorruptComputer** [comment]
Have the chance to blow the station as a config option. And if it's off it just blows the core and the vault.

**Comment by xxalpha** [comment]
>unintuitive
>obfuscating

The instructions only have one step missing and you can still deduce it from what they say. The OP figured it out, he just used the wrong tool to do it and gave up when he got blasted with rads (pro tip don't try to deconstruct a nuke without radiation protection).
