### ISSUE TITLE
Smes building hiccup

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#10375]
Construct machine frame, add cables, add SMES circuit, add 5 cells and the capacitor, then funky shit happens: adding the 5 pieces of cable result in dropping the cable coil you're holding. It adds the 1 cable piece each time but the dropping is mildly annoying.

**Comment by xxalpha** [comment]
Guilty

**Comment by francinum** [comment]
Not restricted to SMES construction.

**Comment by xxalpha** [comment]
Actually it should be using all 5 pieces at once.
