### ISSUE TITLE
Fucked up ghost follow refs

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#10378]
![2015-07-04 17_18_56-bagil_ immoral depot sierra](https://cloud.githubusercontent.com/assets/3975713/8508439/cab5e7b4-2270-11e5-8108-7e733830eb0f.png)
hrefs in order of appearance
![2015-07-04 17_16_39-](https://cloud.githubusercontent.com/assets/3975713/8508440/cc1fe622-2270-11e5-9d7c-0718bce5e7ca.png)
![2015-07-04 17_17_10-](https://cloud.githubusercontent.com/assets/3975713/8508441/cd4c53dc-2270-11e5-839b-1781597312b3.png)
![2015-07-04 17_17_15-bagil_ immoral depot sierra](https://cloud.githubusercontent.com/assets/3975713/8508442/cfb4ac82-2270-11e5-9a7d-25fddb3ecab5.png)

the person was dead but his body still existed.

**Comment by optimumtact** [comment]
>now following toggle helmet light

loled

**Comment by Jalleo** [comment]
The follow link must of changed memory locations or something

**Comment by tkdrg** [comment]
caused by ntsl apparently
