### ISSUE TITLE
Gang: Not spraying gangsigns, Unable to register spare tools.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10386]
Job: CMO
Server Revision: 0cffe9edce41155e73eaa87ba7f93e6ce030a38e

**Comment by Ikarrus** [comment]
Gang mode is currently disabled for maintenance.

Admins shouldn't be forcing things they don't understand.

**Comment by francinum** [comment]
Datumgangs were added to a traitor round.
