### ISSUE TITLE
If you're buckled you can wet your mop forever

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#10381]
1. take old janicart
2. have mop in hand
3. buckle self to chair
4. have old janicart next to self
5. wet mop forever, it never goes into the cart.

alright this suddenly stopped working, wtf. i cant reproduce anymore, but im sure this happened.

**Comment by Dorsisdwarf** [comment]
[cannot reproduce]

**Comment by phil235** [comment]
Can't really see how that could happen. A problem with trans_to() in wet_mop proc making the mop never full maybe?

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
