### ISSUE TITLE
Issue with Lobby Music RNG?

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10388]
I hear the same new lobby music (guitars) almost every time now. I asked around and everyone said they have the same issue. Is something wrong with the way we're picking them?

**Comment by Incoming5643** [comment]
login_music = pickweight(list('sound/ambience/title2.ogg' = 31, 'sound/ambience/title1.ogg' = 31, 'sound/ambience/title3.ogg' =31, 'sound/ambience/clown.ogg' = 7)) // choose title music!

**Comment by Dorsisdwarf** [comment]
What happened to title1?

**Comment by Ricotez** [comment]
it's right there, the list just lists title2 before title1

**Comment by Aranclanos** [comment]
there's nothing wrong in the repo, ask your host
