### ISSUE TITLE
sorium blob can throw you for a loop

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#10399]
An infinite space loop. it throws you fast enough that you can't affect your trajectory
hapened on sybil

**Comment by WJohn** [comment]
Similarly, being launched from the mass driver will also make you unable to change your trajectory.

**Comment by Supermichael777** [comment]
this is primarily a playability issue as it is so boring you might as well turn away till you hit something. most of the problem comes from the fact that the weird spots it can throw you from have empty lines in most z levels

**Comment by Anonus** [comment]
It can also outright kill you via wallslam.
