### ISSUE TITLE
Mopping the floor will not show a progress bar.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10390]
However using a bar of soap will, even though it's functionally identical.

@Iamgoofball 

I'm sure there's many other things that lack progress bars, but I haven't looked for em. One issue solved at a time I guess.

**Comment by optimumtact** [comment]
It's likely stuff that doesn't use do_after to handle the steps.

**Comment by Iamgoofball** [comment]
Whoops
