### ISSUE TITLE
Admins have no NanoIRC interface, nor an easy way to monitor communications via it.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10404]
While IRC chat is saved to server logs, they are not displayed to ghosts, nor is there an investigate verb for them. This makes it very difficult to monitor, as it requires opening up the server log and looking through it.
An easier way to monitor the NanoIRC chat, possibly by sending it to ghosts, or having an IRC window for admins that saves everything sent, would be appreciated.

**Comment by optimumtact** [comment]
how do pda messages handle it?

**Comment by Dorsisdwarf** [comment]
NTRC just needs an investigate option, like tcommscripts.
