### ISSUE TITLE
Some things that really should be logged don't get logged.

### ISSUE THREAD

**Issue by CreationPro** [tgstation/-tg-station#1040]
I have recently had a certain issue involving people slipping and stripping each other and it was a MAJOR pain because neither slipping nor stripping people gets logged.
So, the things that, in my opinion, should get logged are:

1. Slipping. If it is not possible to track the object the target slipped on, at least let it log the fact that said person slipped+time.
2. Stripping. It has been a pain to search for stolen items and for the person who stole them for me.
3. Setting people on arrest. It is REALLY hard to find the person who decided to griff and set everyone on arrest.
4. Pushing each other. I am not entirely sure this is possible to log, but sometimes there are situations in which people attempt to push each other out the airlocks.

Perhaps I am missing something, but these things are quite a pain to trace.

**Comment by phil235** [comment]
>Stuffing someone into disposals. Yes, this is a bit of a problem, too.

This is already logged.
