### ISSUE TITLE
Stats gathering poll popup at first connection is still a thing

### ISSUE THREAD

**Issue by bustygoku** [tgstation/-tg-station#10417]
Isn't it time this is gotten rid of?

**Comment by optimumtact** [comment]
what on earth are you referring to?

more detail please

**Comment by Aranclanos** [comment]
is it bugged or your server has active polls?

**Comment by Jordie0608** [comment]
It's a old popup that asks about 'expanding our stat gathering'; a holdover from when erro was first adding stat tracking IIRC.

**Comment by Jordie0608** [comment]
Found it https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/new_player/poll.dm#L17

**Comment by optimumtact** [comment]
I've never ever seen that before, is it new players only?

**Comment by Aranclanos** [comment]
oh that thing
fucking nuke it

**Comment by PKPenguin321** [comment]
yeah i think once you've voted on it or whatever it goes away, so it'd be for new players only

**Comment by MrStonedOne** [comment]
It will still show up randomly for players who have voted for !!REASONS!!
