### ISSUE TITLE
Vanilla humans can *wag their tail

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#10414]
*wag and *stopwag work with regular non-lizard non-cat humans as if they had tails. Nothing happens with the sprite. Probably related to cat stuff

**Comment by RemieRichards** [comment]
cats caused this yes.

**Comment by Ricotez** [comment]
whoops, my bad

**Comment by Iamgoofball** [comment]
another reason to remove cattebeest

**Comment by Steelpoint** [comment]
Maybe future space men have evolved a way to move their sacrum's?

**Comment by Xhuis** [comment]
![](http://i.imgur.com/Il2sI.png)
