### ISSUE TITLE
Abandoned Crates opened by mob attacks

### ISSUE THREAD

**Issue by rawraxily** [tgstation/-tg-station#10412]
Pretty self explanatory, the abandoned crates you can find on the roid will disappear and dump their contents if hit by either a Goliath, Gold Grub, or Basilisk. Not sure about anyone else, although I know Hivelords don't cause this issue. This may also extend to regular locked crates, I haven't tested it out yet.

**Comment by phil235** [comment]
Simple animal's attacks opening normal crates is intended I think. The issue is abandoned crate droping their loot when destroyed.

**Comment by Dorsisdwarf** [comment]
I think this should be intentional. Baiting deadly monsters with a crate, risking your life for what may be a pair of shitty shoes, is cooler than math

**Comment by Miauw62** [comment]
abandoned crates literally arent math
