### ISSUE TITLE
Door shocks no longer doing limb damage sucks

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10411]
Why was this ever changed? It makes shocks that much more annoying to treat with a standard white medkit. I see pretty much no reason for this change.

**Comment by PKPenguin321** [comment]
iirc it was to make them more devastating without allowing them to crit you in one hit

**Comment by SconesC** [comment]
really bad change

**Comment by Aranclanos** [comment]
Please use the feedback forums
