### ISSUE TITLE
Golems Retain old name for a split second on creation

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10421]
HELP: Scones/(X) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Found a bug, http://prntscr.com/7pbtwh golems retain old name for a spli second on creation

**Comment by Iamgoofball** [comment]
Don't think we can actually do anything about this

**Comment by Anonus** [comment]
We could rename them first, as in before the mob is spawned and they're put in it.

**Comment by WJohn** [comment]
This is a bit of metaknowledge. It can tell you who's dead if you know that name was being used by someone that round. It's minor but it ought to be dealt with.
