### ISSUE TITLE
You can breathe in space without oxygen

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10420]
Unconfirmed report from a player.

Reply PM from-ForcefulCJS/(Oldman Robustin): in space, with no oxygen, no self respiration virus, and im constantly gasping and suffocating without suffering harm 
Reply PM from-ForcefulCJS/(Oldman Robustin): ofc not, I just figured it out myself. Apparently you guys fucked up N2 or something. Shits breathable in pure form.  
Reply PM from-ForcefulCJS/(Oldman Robustin): Even thought you get the 02 warning and you constantly gasp, it never really affects you

**Comment by Robustin** [comment]
Unconfirmed?

Sheeeeit son. You know my words as good as gold.

Did this in multiple rounds, filled up a tank with pure n2 and released the valve intending to suicide. Instead I just sat there gasping like an idiot forever.

**Comment by Dorsisdwarf** [comment]
Clearly our spacemen are evolving

**Comment by WJohn** [comment]
Confirmed: You can survive on pure N2. You'll gasp and get the no oxygen message, but won't actually take any oxygen damage whatsoever. You can use this to ignore breathing requirements in space.

**Comment by CPTANT** [comment]
If I remember correctly the respiration virus works by producing chemicals that cure oxygen damage, not prevent it in the first place.

**Comment by Marflowerose** [comment]
Is the pressure affected aswell? Can you survive with pure nitrogen and pressure set to 1 on the internal?

**Comment by xxalpha** [comment]
Maybe it's runtiming somewhere.

**Comment by Dorsisdwarf** [comment]
Wouldn't something like that totally spam out the runtime logs whenever someone bombed up the station, as everyone started having too little O2, there still being N2, therefore the bug triggers?

**Comment by Supermichael777** [comment]
i survived a wizard murder attempt with a 1 pressure mask and mind-swap sat their in mind-swap unconsciousness and got up just fine. should have been knocked out from the oxyloss.
this is probably critical due to imursions and core gameplay mechanics. probably has to do with you being able to regenerate oxyloss.

**Comment by Robustin** [comment]
I don't always powergame, but when I do, I use 1kPA nitrogen tanks to breathe forever.

**Comment by SconesC** [comment]
I've noticed this, actually

**Comment by xxalpha** [comment]
Has this been fixed? I can't breathe in space.

**Comment by WJohn** [comment]
You can't breathe in space specifically, but you're capable of breathing with an air tank as long as that tank has any amount of N2 in it. Since you never use up N2 you'll live forever, since suffocating on that doesn't actually damage you.
