### ISSUE TITLE
Female Lizards have Mammaries

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10437]
![1365231344665](https://cloud.githubusercontent.com/assets/9098006/8538571/86beb1c8-242b-11e5-8e7c-9b6964ad0099.jpg)

**Comment by WJohn** [comment]
Has been the case literally for years.

**Comment by Ikarrus** [comment]
Well now it's a formal issue

**Comment by Incoming5643** [comment]
Literally entire existance, in fact they used to be bigger

**Comment by Ikarrus** [comment]
I contest the controversial and unresolvable tags

**Comment by Incoming5643** [comment]
Let us never forget the horror that was lizardfat_female_s ![lizbiz](https://cloud.githubusercontent.com/assets/4176358/8538734/0c857ed2-243f-11e5-8d4c-4c07323f7a1e.gif)

Also the latest incarnation of lizard titties do not have nipples so you can't throw down that card anymore. They aren't mammaries.

**Comment by GunHog** [comment]
Not an issue.

**Comment by Miauw62** [comment]
if they arent mammaries than what are they???

**Comment by bgobandit** [comment]
they are features

**Comment by Cheridan** [comment]
>if they arent mammaries than what are they???

Storage for the excess salt that their existence generates.
