### ISSUE TITLE
Runtime with yelling machines "...!!"

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#10441]
Machines that try to yell (quotes that end with "!!") will runtime. This was seen when trying to send an emergency distress from a request console.

requests_console.dm line 318

runtime error: type mismatch: 0 |= "yell"
proc name: say quote (/atom/movable/proc/say_quote)
  source file: say.dm,70
  usr: Aides Curator (/mob/living/carbon/human)
  src: the Bar requests console (/obj/machinery/requests_console)
  call stack:
the Bar requests console (/obj/machinery/requests_console): say quote("Security emergency in Bar!!", 0)
the Bar requests console (/obj/machinery/requests_console): say quote("Security emergency in Bar!!", 0)
Broadcast Message(the Bar requests console (/obj/machinery/requests_console), 0, the station bounced radio (/obj/item/device/radio), "Security emergency in Bar!!", "Bar requests console (Machine)", "Machine", "Bar requests console (Machine)", 0, 0, /list (/list), 1359, 0, "says", "asks", "exclaims", "blares")
the subspace broadcaster (/obj/machinery/telecomms/broadcaster/preset_left): receive information(/datum/signal (/datum/signal), the telecommunication hub (/obj/machinery/telecomms/hub/preset))
the telecommunication hub (/obj/machinery/telecomms/hub/preset): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/broad...", 1, 20)
the telecommunication hub (/obj/machinery/telecomms/hub/preset): receive information(/datum/signal (/datum/signal), Security Server (/obj/machinery/telecomms/server/presets/security))
Security Server (/obj/machinery/telecomms/server/presets/security): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/hub", null, 20)
Security Server (/obj/machinery/telecomms/server/presets/security): receive information(/datum/signal (/datum/signal), the bus mainframe (/obj/machinery/telecomms/bus/preset_three))
the bus mainframe (/obj/machinery/telecomms/bus/preset_three): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/serve...", null, 20)
the bus mainframe (/obj/machinery/telecomms/bus/preset_three): receive information(/datum/signal (/datum/signal), the processor unit (/obj/machinery/telecomms/processor/preset_three))
the processor unit (/obj/machinery/telecomms/processor/preset_three): relay direct information(/datum/signal (/datum/signal), the bus mainframe (/obj/machinery/telecomms/bus/preset_three))
the processor unit (/obj/machinery/telecomms/processor/preset_three): receive information(/datum/signal (/datum/signal), the bus mainframe (/obj/machinery/telecomms/bus/preset_three))
the bus mainframe (/obj/machinery/telecomms/bus/preset_three): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/proce...", null, 20)
the bus mainframe (/obj/machinery/telecomms/bus/preset_three): receive information(/datum/signal (/datum/signal), the telecommunication hub (/obj/machinery/telecomms/hub/preset))
the telecommunication hub (/obj/machinery/telecomms/hub/preset): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/bus", 1, 20)
the telecommunication hub (/obj/machinery/telecomms/hub/preset): receive information(/datum/signal (/datum/signal), the subspace receiver (/obj/machinery/telecomms/receiver/preset_right))
the subspace receiver (/obj/machinery/telecomms/receiver/preset_right): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/hub", null, 20)
the subspace receiver (/obj/machinery/telecomms/receiver/preset_right): receive signal(/datum/signal (/datum/signal))
the station bounced radio (/obj/item/device/radio): talk into(the Bar requests console (/obj/machinery/requests_console), "Security emergency in Bar!!", null, null)
the Bar requests console (/obj/machinery/requests_console): Topic("src=\[0x200b2c9];emergency=1", /list (/list))
BlittzOff (/client): Topic("src=\[0x200b2c9];emergency=1", /list (/list), the Bar requests console (/obj/machinery/requests_console))

**Comment by Ikarrus** [comment]
@GunHog Found that that the issue only seems to happen while an NTSL script is running

**Comment by boopcat** [comment]
remove ntsl!
it's too easy to crash the server with it
