### ISSUE TITLE
Foam flies

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10452]
It can go into a disposals chute and then be thrown back out at another end.

**Comment by Tokiko1** [comment]
Related: Also happens with spacevines.

**Comment by Dorsisdwarf** [comment]
Spacevines going into disposals is intentional. I'm pretty sure they'll also try and go down disposal bins, too.

**Comment by Strathcona** [comment]
Feature? I mean that's pretty funny that you can be standing next to an outlet and suddenly pacid foam comes flying out. Isn't that what you'd expect to happen if a bunch of foam fills a pneumatic disposal tube?
