### ISSUE TITLE
Helmet sirens are obnoxious

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10466]

**Comment by Incoming5643** [comment]
Working as intended

**Comment by xxalpha** [comment]
This is not what the issue tracker is for, friend.

**Comment by freerealestate** [comment]
Issues like this have been allowed for years, it wasn't until this morning
that this apparent new rule was made aware to me. It wouldn't surprise me
if it was made up on the spot right then.

Either way, it's a pretty universally agreed issue that these helmets are
really grating and should be changed.

I won't care if this is closed, because I know they'll get changed
eventually anyway.

**Comment by Iamgoofball** [comment]
the literal point of this is to be an annoying helmet

people like me use it in interrogation of criminals
