### ISSUE TITLE
Thrown objects cannot pass through a border window tile

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10479]
This has been the case since the dawn of time.

If you try to throw an object through the tile of a border window, perpendicular to the window in question, it will hit the window. This extends to all border objects like this such as border firelocks, and alien hunters experience this since I'm told they use something similar if not identical to being thrown.

**Comment by RemieRichards** [comment]
It's the latter, they ARE thrown.

**Comment by Dorsisdwarf** [comment]
Yeah, they literally throw themself at the target (and use SPRITE WIZARDRY for the jump sprite)
