### ISSUE TITLE
you can see if there are stealthmins as a player

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#10476]
OOC: Punnches420: funfact: if there are stealthmins when you adminwho you can see there's an empty space
OOC: Punnches420: if there are no stealthmins there isn't

hard to reproduce since i have admin myself

**Comment by freerealestate** [comment]
>priority: high

:)

**Comment by Iamgoofball** [comment]
Ahahah

**Comment by Jordie0608** [comment]
I'm not getting this from when I adminwho'd as:
Admin
>Current Admins:
Aloraydrel is a TrialAdmin - Observing
KorPhaeron is a HeadAdmin - Lobby
Shadowlight213 is a TrialAdmin - Lobby
Gamarr is a GameAdmin - Playing
Lollerderby is a TrialAdmin - Observing
Jordie0608 is a AdminTrainer - Lobby

>Current Players:

Admin with a stealthmin
>Current Admins:
Aloraydrel is a TrialAdmin (as Ayy) - Observing
KorPhaeron is a HeadAdmin - Lobby
Shadowlight213 is a TrialAdmin - Lobby
Lollerderby is a TrialAdmin - Observing
Jordie0608 is a AdminTrainer - Observing

>Current Players:

Deadmin with a stealthmin
>Current Admins:
KorPhaeron is a HeadAdmin
Shadowlight213 is a TrialAdmin
Lollerderby is a TrialAdmin

>Current Players:

Deadmin with all stealthmin
>Current Admins:

>Current Players:

Seems like there's always an empty space

**Comment by Jalleo** [comment]
This is not a issue then.

**Comment by Miauw62** [comment]
ban punnches
