### ISSUE TITLE
Nanofrost does not close scrubbers

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#10473]
Nanofrost is only closing up vents, not scrubbers.

**Comment by Miauw62** [comment]
duplicate bug.

**Comment by phil235** [comment]
Which issue is this a duplicate of?

**Comment by Miauw62** [comment]
The issue of metal foam not working, dont know the issue number.

Although nanofrost not closing scrubbers isnt a duplicate.
