### ISSUE TITLE
Fluoroacid nades/smoke is too underpowered.

### ISSUE THREAD

**Issue by OhEmGee** [tgstation/-tg-station#10488]
Please revert #10085 posthaste. It is a unecessary nerf, modifying a mechanic that was already reltively balanced. Acidnade clouds are  relatively easy to navigate out of before your shit getd melted, not to mention dodging a grenade before it blows.  Besides, Acidnades were one of the better counters against mm+el nath wizards/nuke ops, and compared to the effort that they need to prepare (à 6-10 minutes, which is about the same as toxin bombs) they're relatively balanced.

**Comment by phil235** [comment]
I have planned to buff smoke and foam, it should make acid nade more useful.

**Comment by Marflowerose** [comment]
You could balance out the gas grenades by increasing gas cloud amounts and their speed and overall movement, would make for more interesting grenades aswell.

**Comment by Ikarrus** [comment]
Smoke was insanely piwerful in that trying to balance acids for them made them virtually useless in a sprayer. 

The smoke nerf was a good one, but the acids should be revisited to make them visble with both methods of delivery

**Comment by Iamgoofball** [comment]
Are you fucking kidding me

Acid was nerfed for being insanely better than every other chem and the fact that it made smoke insanely  OP.

Get good, branch out, try using the other 50 burny explody death chems we added.

**Comment by Iamgoofball** [comment]
Also >6-10 minutes

More like 2 minutes.

**Comment by Iamgoofball** [comment]
Smoke and foam could really use a buff, though, but leave acid as-is.

**Comment by OhEmGee** [comment]
With the nerf fluorosmoke almost never melt even items in the armor slot anymore, making them next to useless in combating wizards. (Or, at least you need a massive amount of fluoroacid for it to work. I didn't manage it with two BS beakers full of acid.)

**Comment by freerealestate** [comment]
Wait, I thought balance discussion was to be taken to the feedback forums?

**Comment by phil235** [comment]
@freerealestate this issue has been discussed in a feedback thread on the forum already. https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4001

**Comment by Lumipharon** [comment]
Acid has gone from hilariously OP to hilariously shit.

Smoke and foam honestly weren't that powerful. It was only in combination with certain chemicals (like acid) where it was broken.

Now though, smoke/foam has been nerfed into the floor, as well as acid. This just leaves us with a whole lot of nothing.

**Comment by freerealestate** [comment]
@phil235 If maintainers actually cared about issue reports not being about balance then this would be closed and feedback would be directed to that thread you linked, or the pull request you made.

**Comment by Dorsisdwarf** [comment]
[balance]
