### ISSUE TITLE
Proposed changes for the crew monitoring computer

### ISSUE THREAD

**Issue by nullquery** [tgstation/-tg-station#10498]
Alright, let's attempt to make everybody happy (see https://github.com/d3athrow/vgstation13/issues/5297).

* If there is sufficient room expand the health indicator to show the full health statistics in addition to the indicator. i.e., if the player increases the width of the crew monitoring computer it'll show the additional statistics. **done**
* Hovering over the area shows the X and Y coordinates in a tooltip. Clicking on the area should copy the coordinates to the clipboard. (This may be natively possible, otherwise you'll have to perform an additional CTRL-C which I'm sure is not a problem since you'd have to do that anyway.) **done, click copies to clipboard (don't ask)**
* Functionality to switch z-levels, with a compile flag to disable this behavior so /tg/ doesn't get this change. **WontFix, this is up to /vg/ to implement in their own branch if they want it IMO**
* Map zooming/scaling. This has actually been suggested before but I hadn't given it much priority. (In my eyes you'd use the mouse wheel to zoom in/out, but you'd receive scrollbars as the map wouldn't fit on the entire screen anymore.) **done**
  * When hovering over a person in the table center the minimap around the player (if applicable) **done**
* Unsure on what to do with AI. Should it be able to view the health? Doesn't this make the AI too powerful? We need to settle on this once and for all. **AI can view health proper again; delay of 5 seconds between updates**

**Comment by clusterfack** [comment]
On /tg/ this may make the AI too powerful, our AI does not have a UI button to open up the crew monitoring computer.

**Comment by nullquery** [comment]
@clusterfack but couldn't your AI just keep the crew monitoring computer open at all times by finding an isolated one on the staiton?

**Comment by GunHog** [comment]
1. Yes, do this.
2. Might not be worth it to try coding.
3. No opinion, as it does not apply to us.
4.I would love this.
5. Make the AI version work exactly as the human version does. This means removing the jump-to ability and having the same health colors. A fine compromise in my opinion.

**Comment by clusterfack** [comment]
Well I should specify this was technically possible before but it was never become a real problem in the past

**Comment by GunHog** [comment]
>@clusterfack but couldn't your AI just keep the crew monitoring computer open at all times by finding an isolated one on the staiton?

This was exactly my practice, and why I asked Goofball to add them to AIs as a built-in option.

**Comment by duncathan** [comment]
Allowing us to see complete statistics with enough room seems like a good enough QOL feature. 

Can't see why not to let us copy coordinates easily.

Maybe for map scaling you could you shift-mousewheel or ctrl-mousewheel? Those are intuitive enough, relatively standard, and wouldn't conflict with the scroll bars. 


AI can't be omnipresent or omniscient. AI's white box is a great way of doing this. Leave it as-is.

**Comment by duncathan** [comment]
Also: man those vg guys were acting like cunts.

**Comment by ike709** [comment]
1. :+1: 
2. :+1: 
3. Don't care, doesn't matter to /tg/
4. Yes please
5. I don't really know.

Dear vg: When you don't like a feature that was ported and merged by people other than the original coder, don't hate on said coder or said feature. Especially when he wants to help.

**Comment by GunHog** [comment]
Then remove the white box for the AI and give it the numbers only. Would you want to have to hover over each and every box to find someone hurt while the bored MD at the counter can find and treat him faster than you can even know he is hurt? It restricts the usefulness of the monitor severely, to the point where *I would rather have the old one instead.*

**Comment by optimumtact** [comment]
Don't worry @nullquery we've got your back

**Comment by Invisty** [comment]
1. Colour -> Hover for stats is perfectly fine from a UI perspective IMO. All you achieve by making these stats visible is allowing people to tell when someone is being murdered in maintenance and what they're being killed with.
3. I don't think navigable maps of off-station z-levels would serve the gameplay well, if this is what you're suggesting.
4. Making it smaller by default would be nice. It's already horrendously large. There needs to be less map and more of the crew listing (which is frequently line-breaking and looking hideous)
5. Have suit sensor reports compiled once every 30/60 seconds, instead of on-demand? I don't see why something like this hasn't already been done to address AIs refresh-spamming the crew tracker to catch antags.

**Comment by nullquery** [comment]
@Invisty Your 4th point sounds exactly right! There shouldn't be any limitations other than what the in-game physics don't allow. By delaying health updates there's a delay between when you can see someone has been damaged which should solve all the OP issues.

I think allowing the AI to click the minimap to jump to places is a very nice feature and not something that should be removed. What I'm aiming for is that the AI will eventually have nothing but the minimap to click on to move to areas, instead of all those verb panels and manually picking camera names.

@GunHog Copying something to the clipboard is trivial to implement. IE has an API for it though I don't know if I can use it (depends if BYOND allows it or if I can ask the user for permission to hijack their clipboard but that may not work out), worst case I can open a dialog with the coordinates pre-selected so you only have to press CTRL-C to copy. Hell, I could make CTRL-C a way to copy tooltip contents by default if one is open, but that may not be intuitive to new players.

**Comment by nullquery** [comment]
I'll have some time to look into this over the course of this weekend. I'd also like to work on https://github.com/tgstation/-tg-station/issues/10321 while I'm at it since the systems are mostly the same.

Do any of you think I should just combine the crew monitoring computer and the security camera computer? They both are in need of an awfully similar interface, and the AI can already jump to cameras by clicking so it's not far-fetched to allow humans to do the same.

And the security camera's and crew monitoring are already near each other most of the time. Maybe not in the medical bay, but perhaps we can introduce a "crew monitoring computer-lite" which doesn't support watching camera's. Or require a security ID before you can view camera's with it.

I'd need to introduce a new feature so you can switch between people-view and camera-view.
