### ISSUE TITLE
Borgs cannot set Airlock access settings, making them unable to build airlocks with their rcd

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#10490]
Clicking the chance access button does nothing, and attempting to build an airlock results in a configure access first message.

**Comment by optimumtact** [comment]
Yeah this got me too, annoying as heck

**Comment by xxalpha** [comment]
@nukeop

**Comment by optimumtact** [comment]
It's because the verb checks for ishuman I'm pretty sure

**Comment by nukeop** [comment]
It's true, it checks for ishuman.

Before I touched it, there was a comment saying that borgs cannot change access levels. Should I change it and make it configurable for them? I see no issue.

**Comment by phil235** [comment]
@nukeop yes please
