### ISSUE TITLE
Crusher still kills when off

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10507]
The crusher was off, the panel was open and it was unsecured. I was dragging it to a safe place. Someone accidentally walked into it, and was immediately killed by it. All their possessions were destroyed. This happened twice. It was hilarious.

**Comment by Supermichael777** [comment]
crusher best weapon
stronger than the nuke

**Comment by Lumipharon** [comment]
Remember when crushers gibbed?
Or that one time a badmin possessed a mobile crusher?

Good times.

**Comment by Dorsisdwarf** [comment]
[bug]
