### ISSUE TITLE
Defib controls are clunky

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10506]
In order to use the defib, you need to use the action button to stow/equip the defib pair in your hand, then you must use the defibs again in your hand to spread it to both hands, THEN you're allowed to use it one someone.

This second step is completely unecessary.

We have the code with gibtonite where both hands MUST be open to simply even hold it, why not force that with defibs too?

**Comment by freerealestate** [comment]
Please, yes. I was going to make an issue report about this, but expected to get the "feedback forum" response.

**Comment by Lumipharon** [comment]
It makes it so frustratingly clunky, jesus fuck is it annoying.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
