### ISSUE TITLE
Mineral Wall smoothing errors

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#10509]
![sybil muppet installation xviii 2015-07-10 154503](https://cloud.githubusercontent.com/assets/4343468/8612875/42b7e5b0-271b-11e5-94dc-6ab464d74e42.png)
Due to their stripes, mineral walls smooth rather badly and turn into a jumbled mess. I'd suggest removing the stripes altogether from them, along with the center corner that was taken out of normal and r-walls.

@WJohn @xxalpha

**Comment by WJohn** [comment]
Yeah, we knew about this when submitting it, and it really just comes down to the mineral wall sprites being shit and needing a resprite. I'll handle that myself soon if ausops or somebody else doesn't just swoop in before me.
