### ISSUE TITLE
Humans (not just borgs) cannot make all-access airlocks with RCD

### ISSUE THREAD

**Issue by vibarexel** [tgstation/-tg-station#10505]
Trying to make an all-access door with the RCD makes the game spit out "Configure access first!" instead of just making an airlock like it should.

**Comment by xxalpha** [comment]
@nukeop

**Comment by phil235** [comment]
Related to #10490

**Comment by nukeop** [comment]
I'll take a look at this.

**Comment by nukeop** [comment]
Fixed. I'll make a pull request taking care of this and related issues.
