### ISSUE TITLE
um server de merda

### ISSUE THREAD

**Issue by gabrielm78** [tgstation/-tg-station#10518]
o lucas325 o host do server é inutul so fica abusando e so fala de porno na merda que ele chama de server e os admin que ele coloca pra cuida do server so ficam abusando e não fasem mais merda nenhuma se estiver lendo isso delete o server dele

**Comment by Nienhaus** [comment]
This isn't a place to report servers.

**Comment by Aranclanos** [comment]
just like my dota games

**Comment by Jalleo** [comment]
If you got issues with a specific host you probably should just not use that specific server.
Whatever that server was its almost certainly not the primary TG servers.

**Comment by Miauw62** [comment]
this is the third time this specific dude has shitposted here. please ban him, somebody.

**Comment by lucas325** [comment]
isso e mentira ele foi banido por freekil e esta com raiva ele tento matar uma pessoa roubo e ainda resistiu a prisao ae eu o bani por 1111 minutos ae meus admins mandaram abaixar o tempo porque nos achamos um esageiro e entao botamos por 1 hora nao lembroe outra esses troço de pornografia e so nos brincando conversando no OOC ae ele fica com raiva porque e um bosta e so isso que eu tenho a dizer

**Comment by Miauw62** [comment]
lol, we have enough drama of our own, we dont need 10-year-old portuguese drama.

**Comment by lucas325** [comment]
e esses troço de abuser nos fazemos realmente não vou mentir mais porem nos já estamos diminuindo nossos abuser inclusive nos estamos se concentrado mais em jogar em extended pra ficar mais rp

**Comment by lucas325** [comment]
MIAU I SPEAK PORTUGUESE RIGHT YOU GOOGLE TRANSLATE ITS ONE SHIT OK

**Comment by lucas325** [comment]
miauw62 google translate its shit man ;-; and yours americans dont help brazilians man ;-; in ss13 ALL ITS ENGLISH

**Comment by Nienhaus** [comment]
Este não é o lugar para relatar um servidor. Você está desperdiçando seu tempo aqui. Nós sabemos que você não fala Inglês , que é companheiro muito claro .

**Comment by Nienhaus** [comment]
Traduz Google para a vitória.

**Comment by lucas325** [comment]
nienhaus gabrielm78 its bad player he iits griefer

**Comment by Nienhaus** [comment]
@lucas325 Eu não me importo quem ele é companheiro, este não é o lugar para ele.

**Comment by lucas325** [comment]
'-' eu sei aqui nao e lugar de DENUCIAR POREM O ADMIN ENTRO NO SERVER E FOI RECLAMA MANO

**Comment by lucas325** [comment]
O ADMIN DO TG STATION O POVO NO SERVER TA ATE AGR CAGANDO LA COM MEDO DO SERVER FECHAR PORCAUSA DESSE MERDA

**Comment by lucas325** [comment]
e OUTRA TEM MAIS NEHUM SERVER BRASILEIRO PRA NOS JOGAR ;-;

**Comment by lucas325** [comment]
TUDO E INGLES TO FICANDO ATE DOIDO ;-; mais nao posso reclama o jogo foi feito nos estados unidos e tudo entao oq mi resta e chora ;-;

**Comment by gabrielm78** [comment]
desculpe por causar tudo isso lucas

**Comment by gabrielm78** [comment]
e desculpe tambem por faser todos perderem o tempo de voces, desculpe principalmente por esse problema que ocorreu hoje

**Comment by lucas325** [comment]
'-' ok aceito suas desculpas

**Comment by lucas325** [comment]
ja que voce pediu desculpas vou retirar seu ban porque na verdade nen vi o log entao nao sei realmente se voce fez freekill ou roubo

**Comment by lucas325** [comment]
gabrielm voce eo gamemaster??

**Comment by gabrielm78** [comment]
ñ sou gamemaster ñ

**Comment by Miauw62** [comment]
your server is banned sorry

**Comment by Aranclanos** [comment]
solve your server bans elsewhere please
