### ISSUE TITLE
You feel a sense of liberation as Nanotrasen's grip on your mind fades away.

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#10515]
When I was gibbed by a suicide explosion as the Head of Security I got the above message in my chat well after I died. 

That message is normally reserved for when your loyalty implant is removed, I assume this message appeared because I was gibbed and the implant was destroyed by the explosion.

The Warden also got this message.

**Comment by GunHog** [comment]
This happened to me as a pAI being gibbed by Nar-Sie. My Master and carrier was a Sec officer, if that changes anything.

**Comment by Jalleo** [comment]
Sounds like the implant is now destroyed before you are gibbed

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/7b6867bc21d5d2f3e86ce5b322d7ac61a36457df/code/game/objects/items/weapons/implants/implant.dm#L257

**Comment by AnturK** [comment]
Related bug : larva bursting from implanted people also get this message.

**Comment by GunHog** [comment]
It sends the message to the LOC? Well, no wonder.

**Comment by Ikarrus** [comment]
@Steelpoint Hey technically what it's saying is true

@everyone else Yeah it shouldn't be appearing for anyone but the implanted.
