### ISSUE TITLE
Shuttle call reason escaping is too effective

### ISSUE THREAD

**Issue by Khubajsn** [tgstation/-tg-station#10514]
![look!](http://i.imgur.com/rmCr3fo.png)

**Comment by GunHog** [comment]
I am not sure what you are trying to say here.

**Comment by Jalleo** [comment]
This is intended it wws more for people to know why the shuttle was called rather than put a cap on what reasons you can put take this to the forums policy discussionarea first. If a change is agreed there then a feature request is needed.

**Comment by RemieRichards** [comment]
Given that the title of this issue includes "escaping" I believe it's actually to do with the encoding of the reason. which html_encode/html_decode()s the ' as &#39;

**Comment by Khubajsn** [comment]
Yes, exactly as RemieRichards said. I'm sorry for the confusion caused by the double meaning of 'escaping' in this context, I didn't think of it when creating the issue.

**Comment by Jalleo** [comment]
Oh this is the ' issue isnt it?

**Comment by phil235** [comment]
duplicate of #10040
