### ISSUE TITLE
Can't put uniforms on people

### ISSUE THREAD

**Issue by nukeop** [tgstation/-tg-station#10519]
You can take them off but never put them back on them.

To reproduce:

-Hold a wizard uniform in hand
-Drag a guy's sprite on yourself to open his inventory window
-Click on the 'empty' uniform slot
-Nothing happens

**Comment by phil235** [comment]
Are you sure you didn't confuse clothes that fits in the uniform slot with clothes that go in the exosuit slot?

**Comment by Aranclanos** [comment]
wizard robe go on exosuit slot, not uniform. It should be clearer I guess

**Comment by phil235** [comment]
Yeah, we need a warning message when trying to put something in the wrong slot.

**Comment by freerealestate** [comment]
what if it just automatically equipped/attempted to strip the right slot?

**Comment by WJohn** [comment]
Frankly there's lots of places we could do with more feedback. Telling the player what slot an items belongs to when trying to put it on them would be much more useful. It might even be a good idea to have a miniature picture of the item on the side to show them what it is.

**Comment by Aranclanos** [comment]
the best thing would be colours maybe?

**Comment by freerealestate** [comment]
icons in the strip menu would be great

**Comment by nukeop** [comment]
I guess I got confused since it looks like a jumpsuit.
