### ISSUE TITLE
Explosions affect Egun battery capacity.

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#10516]
I was caught by the edge of a bomb blast while wielding Egun, and it reduced the number of lethal shots in it to two (2).

**Comment by GunHog** [comment]
This is very likely intended, example as given below:

    /obj/item/weapon/stock_parts/cell/proc/corrupt()
	charge /= 2
	maxcharge = max(maxcharge/2, chargerate)
	if (prob(10))
		rigged = 1 //broken batterys are dangerous

    /obj/item/weapon/stock_parts/cell/ex_act(severity, target)
	..()
	if(!gc_destroyed)
		switch(severity)
			if(2)
				if(prob(50))
					corrupt()
			if(3)
				if(prob(25))
					corrupt()

**Comment by RemieRichards** [comment]
@GunHog you can't say it's "likely" intended and then show the exact code that PROVES it's intended lol.

Yes, it's intentional, not a bug.

**Comment by GunHog** [comment]
I used "likely" because this might not have been intended to affect weapons, which have irreplaceable cells.

**Comment by RemieRichards** [comment]
It's intentional ever since Razh made explosions call ex_act on their contents.
the solution is obviously to add removable cells to guns.

**Comment by GunHog** [comment]
I totally would code this if the maintainership and players wanted such a change...

**Comment by Jalleo** [comment]
It was not infact intended to affect energy weapons since the batteries cant be replaced that needs sorting.
It was a unforseen change when explosions started to affect stuff properly
I believe the original issue is still up

**Comment by RemieRichards** [comment]
@GunHog the alternative is permanently shit guns... so, go ahead?

**Comment by GunHog** [comment]
Sorry RR, I got shot down in IRC. It would probably be too complicated for me to balance anyway.

**Comment by Lumipharon** [comment]
The alternative is to revert explosions fucking items, but that's just me.

**Comment by WJohn** [comment]
Looks like #8676 is back! I thought this got fixed by jordie?

**Comment by Jordie0608** [comment]
@WJohn this is a different issue to that.
