### ISSUE TITLE
Registry-based configuration

### ISSUE THREAD

**Issue by nullquery** [tgstation/-tg-station#10510]
How about a central way to configure all kinds of things using XML?

What I have in mind (example is for the crew monitoring stuff):

```xml
<configuration>
	<element type="/datum/crewmonitor">
		<properties>
			<prop name="allow_ai_health" desc="Allows the AI to see the health of other players.">
				true
			</prop>
			<prop name="map_scaling" desc="Allows the minimap to be scaled by the player.">
				true
			</prop>
			<prop name="roles_allow_camera" desc="Assignments to allow use of the camera. The access levels for the chosen jobs are merged at runtime.">
				Security Officer
				Head of Security
				Captain
			</prop>
			<prop name="clipboard_type" desc="How to copy to the clipboard. Possible values: api (prefer clipboard API over dialog), dialog (always show dialog)">
				dialog
			</prop>
		</properties>
	</element>
</configuration>
```

Of course this would be backed by an XSD so you can load it in your favorite XML editor.

I think by making it flexible will allow anyone to make use of it to add their own configurable options, yet by forcing people to adhere to a strict set of standards (backed up by the XSD) you could write your own configuration tools in the future?

This would of course all be backed by an easy-to-use in-game API for getting the values from the XML (probably something like `getXMLValue(type, property)`).

Any objections to this approach? Things I could do better?

**Comment by Miauw62** [comment]
You could not use XML.
And we do already have a bunch of config options, although they could do
with reorganization.
Op 10-jul.-2015 08:03 schreef "nullquery" <notifications@github.com>:

**Comment by Dorsisdwarf** [comment]
noooooooooooooooooooooooooooooooooooooooooooooooooot a game issue

**Comment by duncathan** [comment]
It's a code issue. It may be considered a feature request but this is definitely the place to put it.

**Comment by nullquery** [comment]
@Dorsisdwarf what are you doing here if you're not a developer??

AFAIK players post on forums, developers (or aspiring ones anyway) create issues from them.

That's how I'd do it anyway. You don't want that clutter...

**Comment by duncathan** [comment]
Players also report bugs, and make feature requests. That's fine. They also use the tracker as a feedback forum, though, which isn't.

**Comment by Chnkr** [comment]
i love it.

**Comment by Dorsisdwarf** [comment]
I code, I sprite, and I contribute to discussions on mapping, @nullquery 

I have no idea what this should be tagged.

**Comment by Dorsisdwarf** [comment]
Closing because nullquery vanished into the ether and nobody showed any interest

**Comment by nullquery** [comment]
Uh, I'm still here. :dancers:

I agree however that this issue is best left for my own issue tracker (and later submitted as a PR) rather than a /tg/station specific issue.
