### ISSUE TITLE
a verdade

### ISSUE THREAD

**Issue by gabrielm78** [tgstation/-tg-station#10521]
eu vou falar a verdade, eu fiquei puto pq me deram ban por frekill, tudo que eu falei é mentira me desculpem, o lucas é um bom host e os admins tbm são boms eu causei merda demais lamento ele numca fes abuse eu so falei isso pq fiquei puto pf não deletem o server dele, vou tentar convreçar com ele lamneo por tudo

**Comment by gabrielm78** [comment]
lamento por causar esses problemas todos me desculpem mesmo

**Comment by gabrielm78** [comment]
eu fico idiota quando to com raiva, desculpe

**Comment by gabrielm78** [comment]
pf não faça nada com o server dele eu lamento por tudo isso

**Comment by gabrielm78** [comment]
o usuario lucas325 e um bom host lamento por causar esses problemas todos lamento

**Comment by Nienhaus** [comment]
Vá embora , você está desperdiçando o tempo dos outros .

**Comment by Razharas** [comment]
@Aranclanos

**Comment by Miauw62** [comment]
oui oui baguette

**Comment by lucas325** [comment]
obrigado gabrielm porem voce ta perdendo tempo cara aqui nao e lugar de reporta porem obrigado

**Comment by lucas325** [comment]
'-' ta mais nao precisa mentir fera eu faço abuser as vezes eu ja possuir uma cadeira e sai correndo pela estaçao

**Comment by Aranclanos** [comment]
solve your server bans elsewhere please
