### ISSUE TITLE
RCD bugs

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10522]
- While the RCD was on my suit storage slot, putting glass into it turned the glass invisible. I was able to use it to fill the RCD again, and then store it in my bag.
- In-hand not cleared when placing glass into RCD in bag
- Deconstructing windows plays the "glass smashing" sound effect, which makes people think you're vandalising things instead of deconstructing them
- No progress bar when deconstructing shuttle windows with it
- Airlock deconstruction doesn't begin until the airlock is fully opened by the click
- Need to remove your ID to unlock the airlock access settings

There were a couple of other problems with it too that I can't remember right now.

Related to #10505

**Comment by xxalpha** [comment]
@nukeop

**Comment by nukeop** [comment]
Glass smashing plays whenever a window is deleted, this is probably part of the window-related code, I'll see if I can do something about it.

I'm working on a small patch fixing other bugs related to this, I'll be sure to keep those you mentioned in mind as well, thanks.

**Comment by nukeop** [comment]
I fixed the first, second, fourth, and fifth bugs on your list.

The glass shattering sound is played whenever a window is destroyed by any means, even with admin delete function. I can't disable the sound without disabling it altogether for all methods of destruction.

With the last bug, can you clarify? The intended behaviour is that you have to put the ID in your hand and click "Swipe ID" in the window that pops up when you pick change airlock access verb.

**Comment by freerealestate** [comment]
I know, it's more of a feature request than a bug. It'd be less clunky if
you could just click the "Swipe ID" button with your ID equipped instead of
having to have it in your other hand.
