### ISSUE TITLE
Sleeping Carp gang is comparative garbage

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#10537]
They fall in pretty much any match up, sec or other gangs, because all their tools require.

A.) Memorizing a ton of special inputs you'll likely only use once every 300 rounds
B.) Melee range
C.) An assumption that no one will bring guns, flashbangs, stun prods, banana peels, water, lube, bombs, or borgs to the kung fu fight.

To be clear, the reason it's garbage is mostly due to the big ease of use gap between this and traditional gang weapons and the lack of a ranged option. The idea isn't bad, it just doesn't survive well in the hectic ecology of a gang round

**Comment by optimumtact** [comment]
Yeah I watched four or five of them get stomped by sec pretty easily

**Comment by Iamgoofball** [comment]
take a page out of krav maga's book and swap it for procs to activate moves

more fun that way

**Comment by Ikarrus** [comment]
@xhuis please

**Comment by Incoming5643** [comment]
The switchblade is a force 20 melee weapon (5 hit KO), it fits in your pocket with a toggle and doesn't have an on_mob sprite.

The Bo Staff is a force 24 melee weapon (5 hit KO), it needs to be held in two hands to do real damage (and gain shield mechanics) and has a big unique on_mob sprite and a unique hit_sound. Clowns stun themselves if they use it after taking double damage. If you use the staff in disarm intent it does 13-20 (5-7 hit KO) stamina damage with a LOW (prob(10)) chance to stun. If a person manages to crit a person with stamina damage, the victim additionally takes brain damage and falls asleep for (30). If you do manage to knock someone down/out with the staff, there's special code that prevents you from attacking with the staff until they get back up, so you can't actually kill humans with it, you have to unwield the staff, switch to your free hand, and kick the sucker through crit.

Besides its desc = "A long, tall staff made of polished wood. Traditionally used in ancient old-Earth martial arts. Can be wielded to both kill and incapacitate." absolutely none of these mechanics are hinted at, and as the only actual weapon the carp gang can give out to people, it's often in the hands of people who've never used it before.

I prefer the switchblade!

**Comment by Incoming5643** [comment]
As for the arts I couldn't tell you how useful they are, as you need a free hand to use them. Which means you can't block projectiles while attempting the combos. Which ends the way you expect it to.

Martial arts only seem useful as a stealth mechanic, meaning the sleeping carp gang becomes progressively worse as it becomes obvious that's it's gang mode. This is even more a problem because the sleeping fist scroll costs thirty influence, and is the top priced item, meaning you're unlikely to have it before things get too crazy to use it.

**Comment by Xhuis** [comment]
I'm glad that this finally got some playtesting. I'll make some major overhauls to this once firelock construction is done.

**Comment by freerealestate** [comment]
I thought balance issues were for the feedback forums?

**Comment by Dorsisdwarf** [comment]
[balance issue]

**Comment by Xhuis** [comment]
Currently doing some changes over at https://github.com/tgstation/-tg-station/pull/10627

**Comment by Dorsisdwarf** [comment]
this is FEEDBACK FORUM material, rather than issue tracker, anyway.
