### ISSUE TITLE
Catching thrown items is broken

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#10536]
How to reproduce:

1. Try to catch something by enabling throwing mode.
2. It hits you instead.

**Comment by phil235** [comment]
@tokiko1 Cannot Reproduce.
What item did you try throwing?

**Comment by Tokiko1** [comment]
It should happen with all items. I just retested this on a local server running the newest version as of this post and tried the following items, none of which were successfully caught despite having throw mode enabled: Pens, cameras(the picture taking one), PDAs, backpacks, emergency oxygen tanks, cable coils and breath masks.

**Comment by phil235** [comment]
Alright, found the error. Fix is on the way.
