### ISSUE TITLE
Xenos can whisper to ghosts.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10535]
When using the whisper button, the pop up tab will also include surrounding ghosts (and they will receive the message).

**Comment by phil235** [comment]
I thought ghosts received all whispers by default?

**Comment by Dorsisdwarf** [comment]
As in, xenoes have a special power that, for 10 plasma, lets them speak to any mob.If you use the verb rather than right-clicking a mob, you can select nearby ghosts and whisper directly into their mind

**Comment by Dorsisdwarf** [comment]
[bug]

**Comment by WJohn** [comment]
So this bug is back again.
