### ISSUE TITLE
Container content transfer is incredibly unintuitive and obnoxious

### ISSUE THREAD

**Issue by bustygoku** [tgstation/-tg-station#10532]
https://github.com/tgstation/-tg-station/pull/9980 needs to be reverted, at least partially.

You need to drag and drop containers onto your character to open them, but if you accidentally miss and hit the tile behind you? Enjoy stuffing all that shit back in the container fuck you!!!!

I can't think of any situation in which this would be used normally and wouldn't just mess with normal gameplay.

**Comment by Lumipharon** [comment]
Being able to misclick and spill all your shit everywhere, but not be able to scoop it back up in the same way is actually really annoying.

**Comment by WJohn** [comment]
Yeah I noticed this too. I was hoping you could drag an item into a box and everything would be dumped back in, but nope.

**Comment by Incoming5643** [comment]
Honestly you shouldn't be able to dump a container on the ground unless it's already in your hand

**Comment by freerealestate** [comment]
Yeah, this is really annoying. I was going to report it myself.
