### ISSUE TITLE
Window damage overlays do not update correctly

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#10533]
Repaired a window but the damage overlay stayed on
http://pastebin.com/P5rxyWeG - vars at the time (can see it has 50 health)
http://puu.sh/iUJwt/e554a6357c.png

Screenshot

**Comment by WJohn** [comment]
Yeah I noticed it seemingly trying to put the overlay on twice before correcting itself.

**Comment by Jordie0608** [comment]
Dupe of #10523, which was fixed.
