### ISSUE TITLE
You can become an unhatched shadowling with hatched powers.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#10546]
1. be shadowling
2. back yourself up in cloner
3. hatch
4. die
5. get cloned
6. enjoy shadowling powers without disadvantages

**Comment by Xhuis** [comment]
Should be easy enough for someone to add a check to see if you're the shadowling race. I would do this but I have other projects I'm working on and I don't want to enter the dark ages of me having ~20 open PRs.

**Comment by Xhuis** [comment]
should be fixed
