### ISSUE TITLE
Window mode of the new RCD allows you to create multiple, untargetable windows on a single tile

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#10547]
By selecting the Grilles & Windows mode of the RCD and clicking a grille multiple times before the building process finishes causes the RCD to create multiple windows on the same tile. This has a very strange effect that prevents any direct interaction with anything on that tile. These stacked windows cannot be deconstructed or attacked with a melee weapon.

**Comment by ike709** [comment]
This is the 3,500th closed issue.
