### ISSUE TITLE
Crusher loves/hates windows and grilles

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10551]
1. Move crusher from disposals
2. Place crusher so left side has a window and grille then wrench
3. Bump the crusher
4. Window and grille moves to the crusher tile even though they are anchored and arent meant to go into a crusher.
5. Break window and grille to be able to move the crusher

Why is this bad?
Using two crusher in a row can be used to make a quick entrance without needing to break anything.

**Comment by Iamgoofball** [comment]
H u h

**Comment by xxalpha** [comment]
The real bug is the crusher remaining operable while unanchored.

**Comment by Jalleo** [comment]
I believe it was anchored but i cant confirm gonna test it sometime next week.

**Comment by Dorsisdwarf** [comment]
[bug]

**Comment by phil235** [comment]
duplicate of #10507 
THe real issue is the crusher being active while unanchored
