### ISSUE TITLE
Metastation shuttle brig tiles don't prevent escape

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10557]
![so](http://puu.sh/iVHwV/5ca2700196.png)
Also, they're blue.
This would probably go to @metacide if they're actually around still.

**Comment by Incoming5643** [comment]
yep, they gotta be red for it to work.

**Comment by palpatine213** [comment]
Metacide has been informed and the issue has been fixed in the next map update.

**Comment by Dorsisdwarf** [comment]
[mapping issue]

**Comment by Metacide** [comment]
Fixed in https://github.com/tgstation/-tg-station/pull/10671
