### ISSUE TITLE
Sentient xenobio aliens randomly plant weeds

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10570]
Kind of weird. The apparent random weed planting code for NPC aliens continues working even when a player is in control of the mob. Player-controlled slime core aliens don't have access to the alien tab (i.e. they can't plant weeds normally).

**Comment by WJohn** [comment]
Simple animal xenos are a very sad hollow shell of something much more fun and enjoyable. I frankly don't know why we have them, because people will call the shuttle just as easily with simple animal xenos bumbling about, despite being harmless.

**Comment by Nitrousoxide** [comment]
Upon being made sentient can the mob be transformed from a simple animal to a proper xeno automatically?  As of right now it has to be done via admin intervention.

**Comment by WJohn** [comment]
Being able to mass produce real actual player controlled xenos from gold cores can only end badly. I propose instead that we throw out fake xenos, or at least blacklist them (or remove them from the whitelist?) of what gold cores can spawn.
