### ISSUE TITLE
Clientless Blob Core (and blobs in general) Runtime

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10573]
@RemieRichards  and @Iamgoofball 

If you use split consciousness to generate a new blob core (and no one is picked for it), it'll throw this runtime, which generates several others. This also occurs with newly created blob effects or blobs generated by random events. End run effect is it fills up the runtime log in a matter of seconds:

Oh, I'd also like to mention that this *seems* to happen if an overmind HAS a client ,but ghosts, as well (could be mistaken on this one).

runtime error: Cannot read null.blob_reagent_datum
proc name: Life (/obj/effect/blob/core/Life)
  source file: core.dm,71
  usr: null
  src: the blob core (/obj/effect/blob/core)
  call stack:

Followed by:

the blob core (/obj/effect/blob/core): Life()
the blob core (/obj/effect/blob/core): process(20)
Objects (/datum/subsystem/objects): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot read null.blob_reagent_datum
proc name: Life (/obj/effect/blob/core/Life)
  source file: core.dm,71
  usr: null
  src: the blob core (/obj/effect/blob/core)
  call stack:

**Comment by tkdrg** [comment]
@Anonus thinks he fixed this in his blob overhaul. Ping me if it's still an issue.
