### ISSUE TITLE
Satchels (spawn option) are Broken

### ISSUE THREAD

**Issue by bustygoku** [tgstation/-tg-station#10584]
Character preference satchels do not work.

If you select satchel in your character options and spawn, you'll always spawn with a backpack.

I'm 30000% sure this has to do with @ricotez and the cat tail shit.

**Comment by GunHog** [comment]
Choosing the backpack caused me to spawn without a backpack, and as a head, without my baton, but only a box.

**Comment by duncathan** [comment]
#10494
Oh yeah, definitely the fault of catgirls. Not the PR that touches backpack preferences; no, that can't be it.

**Comment by phil235** [comment]
my bad

**Comment by bustygoku** [comment]
When in doubt blame catgirls
