### ISSUE TITLE
Metastation: Library Door missing Icon state

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10581]
![](https://i.gyazo.com/fb572a4e56e052b28dd46b8a07785d4a.png)

![](https://i.gyazo.com/ff48eb84ea399cc1cd9afdaea7fffefc.png)

**Comment by NSSherlock** [comment]
Same thing in the mining station dorms.

**Comment by Dorsisdwarf** [comment]
[mapping issue]
[sprites]

**Comment by phil235** [comment]
I think they use the wrong icon var.

**Comment by Metacide** [comment]
Fixed in https://github.com/tgstation/-tg-station/pull/10804

**Comment by Dorsisdwarf** [comment]
Fixed.
