### ISSUE TITLE
End round report saying The station was evacuated before the gangs could claim it for all round types.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10596]
It displays this like midway in the end round report. Been coming up for every round type.

**Comment by Jalleo** [comment]
@Ikarrus due to datumisd gangs?

**Comment by Ikarrus** [comment]
Whoops my bad.

**Comment by Cebasiz** [comment]
put in a legitimate gang blob mode

the blob resource node fires the micro uzi!

the blob resource node fires the micro uzi!

the blob resource node fires the micro uzi!

the blob resource node fires the micro uzi!

the blob resource node fires the micro uzi!
