### ISSUE TITLE
NTSL Only renders the first few characters

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10595]
My god how old is this bug?
![](https://i.gyazo.com/15b9f5eda1362734e4143ee3ae356ea7.png)

**Comment by RemieRichards** [comment]
Fairly new, since you used to be able to read these scripts live on server about 6 months ago.
Probably something to do with text escaping given that NTSL can look a lot like genuine code in places.

**Comment by Dorsisdwarf** [comment]
This has been happening to me for as long as I've been playing on /tg/.

**Comment by RemieRichards** [comment]
@dorsisdwarf then either it's happened twice (as in the bug was fixed and simultaneously broken, which with text escaping around here, is very common) or you've not been playing very long.

**Comment by optimumtact** [comment]
Happened to me only after I updated my byond client from an older 507
