### ISSUE TITLE
Backpack Firefigher Watertank Foam Not Solidifying

### ISSUE THREAD

**Issue by Sven-Grey** [tgstation/-tg-station#10597]
Server: Sybil

Revision: 
Server revision compiled on: 2015-07-13
c429522f3b02b5a057b4fdc353a80934679d6c4c 

Problem Description: 
The Metal Foam setting on the Atmospheric watertank backpack no longer works. It spews out foam, but the foam does not become a metal wall able to seal breaches.

What did you expect to happen: 
I know that the metal foam setting has worked in the past.

What happened instead: 
As mentioned, it spews useless foam on the ground instead of metal foam.

Why is this bad/What are the consequences: 
Atmospherics has one less too to use to seal breaches.

Steps to reproduce the problem: 
1: Equip Backpack
2: Set to Metal Foam Setting
3: Use the Nozzle to coat the ground in useless goop instead of a wall.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): 
I had noticed this problem a while ago. I'm sorry for not posting this sooner.

**Comment by Jalleo** [comment]
@phil235

**Comment by phil235** [comment]
A fix is already on the way
