### ISSUE TITLE
Odd Traitor objective possible.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10602]
Dietrich Richardofen Jr(Olipoly987) as a Scientist (died) (used 0 TC) 
Objective 1: Die a glorious death. Success!
Objective 2: Acquire the "Blue" secret documents held by Olaf Hellhammer, the Chief Medical Officer and syndicate agent Fail.

Stealing documents and dying gloriously seems a bit counter productive.

**Comment by RemieRichards** [comment]
I mean... it doesn't tell you to hand the documents in anywhere so logically it's right...
but yeah this is bonkers.

**Comment by Incoming5643** [comment]
Not actually a mulligan specific thing, I've seen it at roundstart too. You can actually greentext by keeping the documents on your corpse funny enough
