### ISSUE TITLE
Nuke ops  surgeries issue

### ISSUE THREAD

**Issue by hspace** [tgstation/-tg-station#10604]
With the system of blood loss inplace , it is very hard to do any kind of surgery on the syndicate ship because of the blood loss.Even if you do the surgery fast you still get the side effect of blood loss.I propose to add IV drips to the ship.

**Comment by Marflowerose** [comment]
IV drips are a bit bloat for the ship, more convinient solution would be to have few bloodpens/syringes with O- blood.

**Comment by xxalpha** [comment]
What kind of surgery are we talking about here?

**Comment by stapler2025** [comment]
you could like..not fuck up the surgery perhaps?

**Comment by Marflowerose** [comment]
I assume plastic surgery would be beneficial for stealthOps but AFAIK only augments cause bloodloss even if you succeed, rest is just result of fail.

**Comment by Dorsisdwarf** [comment]
Good thing augments are the only surgery nuke ops will ever be doing, since they can buy the damn things!

**Comment by Jalleo** [comment]
Even when not fucking up you lose blood.
Food does help to restore blood quickly.

**Comment by hspace** [comment]
Hot pockets on the ship didnt help with bloodloss, and when brain surgery was being done the op lost alot of blood.

**Comment by phil235** [comment]
IV with O- blood packs is probably the best solution, syringes don't contain enough to be an efficient method of blood transfer.

**Comment by xxalpha** [comment]
The cautery step stops the blood loss. Are you closing your wounds?

**Comment by SconesC** [comment]
There's a decent deal of blood loss IN the surgery sometimes even if you do it right

**Comment by xxalpha** [comment]
There isn't. There's only blood loss when you use the saw because it deals 75 brute. Using the cautery after heals up half (or more?) of that damage, so the bleeding stops and you just have to apply a bandaid after.

How are nukes fucking up surgery?

**Comment by SconesC** [comment]
Nuke player age is way too low, it's always new players being trash and fucking up implants

I see it happen so often I think nuke winrate would go up if implants were removed so we'd have less surgery deaths

**Comment by CPTANT** [comment]
It doesn't matter if doing surgery right doesn't cause blood loss. Surgery is surgery and it WILL go wrong from time to time. Not having blood near the surgery table is just stupid.

**Comment by xxalpha** [comment]
It's really not a code issue that players can't do surgery without sawing a guy to death / heal brute to prevent major blood loss. There are brute patches on the ship you can use to stop bleeding. This can be closed and git gud.

**Comment by Core0verload** [comment]
@Dorsisdwarf, my modifications to surgery system prevent bleeding out in process of cyberimplant installation/removal. Unless surgeon is insanely shitty.

Close it.
