### ISSUE TITLE
SecHuD's are not showing some jobs

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#10607]
Saw the detective, he had his ID on, however it didnt appear on the secHuD glasses, leaving an empty loyalty sprite box

![](http://puu.sh/iYdO7/68c642f0a7.png)

**Comment by tedward1337** [comment]
Found out why
ID's that arent registered names get this grey box

![](http://puu.sh/iZxZM/5c55f78649.png)
Heres an updated one

**Comment by tedward1337** [comment]
Registered jobs*

**Comment by Shadowlight213** [comment]
Grey boxes for custom jobs on the sechud is intended.  Not a bug.

**Comment by xxalpha** [comment]
@phil235 you could have closed this, it's not even an issue. It's intended behavior.
