### ISSUE TITLE
Cheap lighters using wrong flavor text when lighting a cigarette/cigar.

### ISSUE THREAD

**Issue by NSSherlock** [tgstation/-tg-station#10611]
Cheap lighters are using the flavor text proper to the Zippo: "With a single flick of their wrist, [user] smoothly lights their cigarette with the cheap lighter. Damn they're cool.", instead of their own "After some fiddling, [user] manages to light their cigarette with the cheap lighter." Also happens with cigars. 

First noticed it at the same time that lighters fitting into cig packs was broken, so I suspect this likewise goes back to #9932.

**Comment by Xhuis** [comment]
:smoking: feature :smoking:

**Comment by bgobandit** [comment]
I can't reproduce this. Cheap lighters work fine to me:

After a few attempts, you manage to light the cheap lighter.
You quietly shut off the cheap lighter.
You burn yourself while lighting the lighter!
You quietly shut off the cheap lighter.
