### ISSUE TITLE
Plasma Fist Scroll no longer informs the user of combos

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#10617]
1. Use plasma fist scroll

2. Learn nothing

**Comment by Iamgoofball** [comment]
weird

martial arts datums haven't been changed since Sleeping Carp so

@Xhuis

**Comment by Xhuis** [comment]
It never told you what the combos were. The only changes I've done is changing the message you get, which in itself was something like "You have learned the Plasma fist martial art".

**Comment by xxalpha** [comment]
Except it did tell you the combos.

**Comment by Xhuis** [comment]
Not that I know of. I can implement it in the Sleeping Carp buff if you think it's necessary.
