### ISSUE TITLE
Failed to compile world

### ISSUE THREAD

**Issue by 14anthony7095** [tgstation/-tg-station#10615]
code\game\gamemodes\malfunction\malfunction.dm:215:error:= : bad text

set desc = "Activates the self-destruct device on [world.name]."

**Comment by Dorsisdwarf** [comment]
Update your BYOND client. This is not our problem. Sorry.

**Comment by phil235** [comment]
Yeah, the problem is on your end, our code compiles just fine.

**Comment by 14anthony7095** [comment]
it was with the updated client and newest tg-station src

**Comment by duncathan** [comment]
Try downloading the latest beta version of byond. This issue is caused by an out-of-date byond client, so you are for certain out of date.
