### ISSUE TITLE
Borging head revolutionaries does not deconvert them

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#10646]
Current Game Mode: revolution
Round Duration: 0:16:17
Revolutionaries  
RevHead (Leader) PM 

CYBORG (RevHead) (Slaved to: ENIAC): laws:
1. Serve the public trust.
2. Protect the innocent
3. Uphold the law.

Head revolutionary got borged for whatever reason and somehow remained a head revolutionary. Revolutionaries alleged that they could see an icon next the borg, and it still showed up in check-antagonists as a head revolutionary.

**Comment by lollerderby** [comment]
@Ikarrus You changed this right?

**Comment by Ikarrus** [comment]
Oh, that's why they were excluded. 

Yeah I can fix this

**Comment by Anonus** [comment]
Did it convert with flashing?

**Comment by Supermichael777** [comment]
wait could they convert people with their flash, because that would be ~~funny~~ Awful.

**Comment by lollerderby** [comment]
Didn't test that, unfortunately.
