### ISSUE TITLE
Dark vision handling is total shit.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#10657]
It breaks https://github.com/tgstation/-tg-station/issues/10297
You can't just change a mob's see_in_dark var, because it will be updated on life() to default values. There is no way of permanently changing see_in_dark in a non conflicting way either.

**Comment by Cebasiz** [comment]
>changeling >stealthy maint hunters >have to use a fucking flashlight to ambush people 

:^) fix pls
