### ISSUE TITLE
Letter keys read as "Accept" to inputs such as the ghost command

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#10660]
And ghost is right next to OOC! Why is this, it's terrible.

**Comment by optimumtact** [comment]
Lrn2Hotkey

**Comment by Anonus** [comment]
le get gud meme

**Comment by RemieRichards** [comment]
yeah seriously why are you clicking the ooc verb.
just type "ooc [your text here]"

**Comment by Anonus** [comment]
How about remove the ghost verb instead.

**Comment by duncathan** [comment]
Nobody uses the OOC verb in the tab. At least, nobody should.

**Comment by Dorsisdwarf** [comment]
[BYOND issue]
[quality of life]

**Comment by xxalpha** [comment]
You click on the OOC button to speak in OOC? What?

**Comment by Anonus** [comment]
I like being able to have something ready to say in the chatbar, come on. I even use the say button sometimes for useful sneaky shit.

**Comment by duncathan** [comment]
Isn't there a hotkey for OOC?

**Comment by Supermichael777** [comment]
o (hotkey rebinding when)

**Comment by Iamgoofball** [comment]
@Supermichael777 when hell freezes over and BYOND stops being shit and lets us have rebindable keys

then we just need 60fps and totalbiscuit will love our game

**Comment by RemieRichards** [comment]
@Iamgoofball he's played it before.
He mentioned it in his Lost Planet 3 video, about how Lost Planet 3 was the "Second best space janitor simulator" (first being us, I assume, as this was before viscera cleanup detail)

**Comment by Iamgoofball** [comment]
@RemieRichards doesn't count till we get a 30 minute analysis on the framerate of SS13

**Comment by RemieRichards** [comment]
@Iamgoofball that silky smooth 11 fps Mmmm.

**Comment by Dorsisdwarf** [comment]
Deprecated
