### ISSUE TITLE
Indestructible walls do not block explosions

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10664]
What it says on the tin. We have explosions being blocked and obeying walls, r walls, and blast doors, why not have it apply to indestructible walls?

Also I feel like R walls are a tad weak. A max cap can completely shred 3 thick R walls with minimal blocking.

**Comment by phil235** [comment]
>Also I feel like R walls are a tad weak. A max cap can completely shred 3 thick R walls with minimal blocking.

People are complaining the other way, that it blocks too much (e.g. placing a syndicate bomb in maint above telecoms not destroying the APC).

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/-tg-station/issues/10564
https://github.com/tgstation/-tg-station/issues/10564
https://github.com/tgstation/-tg-station/issues/10564
@phil235 
@MrStonedOne 
@RemieRichards

**Comment by WJohn** [comment]
@phil235 that may actually have to do with the lopsided explosions. From what I'm seeing here it's much worse at penetrating walls directly beneath it, and you normally place a bomb above the APC's spot, meaning lots of the explosion potential will be lost. The example I listed was with 3 thick R walls placed to the side of the max cap explosion, and it absolutely obliterated it. An AI may very well die in one hit if someone puts a max cap in the engineering room beneath its core.

**Comment by Dorsisdwarf** [comment]
[balance]
[bug]
