### ISSUE TITLE
Ventcrawler vision isn't working

### ISSUE THREAD

**Issue by bear1ake** [tgstation/-tg-station#10674]
![scrnshot1](https://cloud.githubusercontent.com/assets/9455174/8754640/056289b4-2d00-11e5-8bad-d63c9d42eb43.png)
version: https://github.com/tgstation/-tg-station/commit/b18ea0296d5fdc87f90c9e109b05ae1b9b39bd12
i think, it's caused by #10560

**Comment by phil235** [comment]
@duncathan

**Comment by Cebasiz** [comment]
yeah i played xeno yesterday, this was a real pain.

**Comment by duncathan** [comment]
I'm hoping this will be a simple fix; I barely touched  ventcrawling.
