### ISSUE TITLE
Freezer/Heater are broken

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#10672]
They can't be interacted with. If you use an item on one of the freezer's on the map it will change the pipe connected to it to look disconnected from it, then you get hit by these runtimes each time machines are processed:
 
(/obj/machinery/atmospherics/components/proc/update_parents)
  source file: components_base.dm,204
runtime error: Cannot modify null.update.

Caused by #10560 most likely

**Comment by duncathan** [comment]
Will check right away. I think I know exactly what causes this.

**Comment by bear1ake** [comment]
valves broken too

**Comment by duncathan** [comment]
You're gonna need to be more specific. What's broken? When I tested, they updated their icons and let air through properly.

**Comment by duncathan** [comment]
I can do a hotfix for the freezers/heaters relatively soon, however.

**Comment by bear1ake** [comment]
@duncathan it can't be open normally. Need to unwrench+wrench to make this work normally

**Comment by duncathan** [comment]
And this is just manual/digital valves?

**Comment by bear1ake** [comment]
@duncathan i tested it in manual valves, but digital is child of manual...

**Comment by duncathan** [comment]
Okay, I'll look into it.

**Comment by hspace** [comment]
cryogenic tubes are also not working , you cant interact with them at all

**Comment by bear1ake** [comment]
@hspace and they are disconnecting from pipelines, when you unwrench them when panel is closed, causing runtime

**Comment by duncathan** [comment]
That's the same issue as the freezer/heater.

**Comment by Marflowerose** [comment]
Also mildly related, max upgrade heater/cooler will drain APC completely when used, at least did few weeks ago.

**Comment by phil235** [comment]
@Marflowerose that's an unrelated issue (#9906).

**Comment by duncathan** [comment]
@bear1ake I cannot reproduce the valve issue. I tested with the manual valves in the incinerator; they're working just fine without unwrenching.

**Comment by bear1ake** [comment]
@duncathan i tested valves in toxins lab
