### ISSUE TITLE
Air alarm scrubbers button for N2o doesn't work

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10683]
Clicking on the nitrous oxide scrubber button doesn't make the button light up or anything.

**Comment by duncathan** [comment]
@MrStonedOne you touched air alarms last

**Comment by MrStonedOne** [comment]
*sigh* let me take a look.

**Comment by MrStonedOne** [comment]
Airalarms are fine, its scrubbers that are broke

It would seem SOMEONE did a find replace for n2 to NODE2

@duncathan you wouldn't happen to know anything about that, would you??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/commit/280373489ba120cd1ed02a7797407db7e8771e07#diff-17f55a729673f975c79af2768a1892d7R31

https://github.com/tgstation/-tg-station/commit/280373489ba120cd1ed02a7797407db7e8771e07#diff-a08ab6f3027c56ef209ea4f690f8ee03R90

https://github.com/tgstation/-tg-station/commit/280373489ba120cd1ed02a7797407db7e8771e07#diff-a08ab6f3027c56ef209ea4f690f8ee03R221

https://github.com/tgstation/-tg-station/commit/280373489ba120cd1ed02a7797407db7e8771e07#diff-a08ab6f3027c56ef209ea4f690f8ee03R223

**Comment by duncathan** [comment]
FUCK I thought I'd fixed all those I'm so bad

**Comment by MrStonedOne** [comment]
Fucking and you were all trying to blame me for it...

**Comment by MrStonedOne** [comment]
I see how it is.

**Comment by duncathan** [comment]
I just need to remember that I'm the worst, that's all
Apologies
