### ISSUE TITLE
HoS armor is COMPLETELY better then Riot Armor

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#10684]
HoS armor has MORE melee defense, and other defences as well!
Only vague advantage Riot armor has it that it protects your hands and feet, which I believe doesn't even matter anymore.

**Comment by optimumtact** [comment]
I think thats kinda the point.

**Comment by xxalpha** [comment]
Try here: https://tgstation13.org/phpBB/viewforum.php?f=10

**Comment by Dorsisdwarf** [comment]
[balance issue]

**Comment by GunHog** [comment]
Just finish reverting the rest of the armor nerfs PR. Give the specialty armors their resists back.

**Comment by SconesC** [comment]
Not a balance issue, just something overlooked with other changes

**Comment by Steelpoint** [comment]
What Scones said.

I've got three incoming PR's and one of them fixes this issue.

**Comment by WJohn** [comment]
Rip fix for this. It could just get nerfed into the ground again.

**Comment by Anonus** [comment]
It'll probably get addressed at some point, right after that ling rework.

**Comment by freerealestate** [comment]
I thought we were supposed to take balance discussion to the feedback forums?
