### ISSUE TITLE
Ian will eat his children

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10697]
I gibbed a corgi puppy, and Ian immediately went over and started eating the corgi meat.
This is just messed up.

**Comment by Jordie0608** [comment]
I vaguely remember seeing this reported before but can't find it.

**Comment by freerealestate** [comment]
Could make it so animals won't eat meat of their own species that's butchered in front of them

**Comment by Niknakflak** [comment]
The real question here is why are you gibbing corgi puppies you sick fuck?

**Comment by Chocobro** [comment]
chickens eat their young's broken eggshells
just thought u should know

**Comment by MrStonedOne** [comment]
ARE YOU CALLING IAN A CHICKEN?

**Comment by phil235** [comment]
Ian is a dog, dogs eat meat, dogs aren't intelligent enough to distinguish the origin of the meat they eat. I don't see what the problem is here.

**Comment by freerealestate** [comment]
They are if they know it's their young. (e.g. they've been killed in front
of them). Seems kind of like a pointless change to make though given how
retarded and undog-like Ian's AI is already.

**Comment by Fayrik** [comment]
This is clearly working as intended.
If you put a real dog in front of puppy meat they'd probably eat it.
(Okay, maybe not if you butchered it in front of the dog, but still, SS13 can't do *everything*!)

**Comment by freerealestate** [comment]
Couldn't a fix just be coded in the form of, if Ian sees his young
butchered, then he won't eat the meat from that butchery? Or would that be
too time-consuming for what it is?

**Comment by Marflowerose** [comment]
Ian should turn into a bloodthirsty cerberi if fed corgi meat.

**Comment by Xhuis** [comment]
nice

**Comment by Shadowlight213** [comment]
Make corgi meat act like red slime extract for ian. When he eats it he gets rabies and starts attacking everyone

**Comment by Cheridan** [comment]
feature
