### ISSUE TITLE
Light is visible on the opposite sides of walls

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10695]
Don't know if this is fixable, but kind of ruins any clandestine maint dealings you might be a part of when anyone can see your PDA light as you move around from the outside.

**Comment by WJohn** [comment]
Not really fixable, no. This has been the case since the dawn of time, and unless you want to do something completely insane like pixel shifting lighting onto walls so it only appears like that from your side, it's never going to be fixed.

**Comment by freerealestate** [comment]
Well I was thinking about it, and though I know next to nothing about
coding, surely if optical meson scanners can make lighting on turfs look
different for one player than it does for one without them, it can be coded
so that lighting on a wall can looks different for different players based
on where they're standing.

**Comment by WJohn** [comment]
It's more feasible now that light is an object, rather than being area based, so having shadows be pixel shifted onto walls so it appears dark only on your side might be possible. The downside to this would be ghosts seeing all walls bordering maint as pitch black all the time.

**Comment by Marflowerose** [comment]
It could be fixed by making walls into 4 parts in a grid, person on 1 side sees one half, person on other side sees the other half, in corner pieces, person at the inner corner sees only 1/4th of the wall (the closest corner piece) and the person at the outter corner sees 3/4th of the wall.

**Comment by WJohn** [comment]
That would be hideously inconsistent with everything else we have, and you're also suggesting cutting lighting into 4 little chunks which would make it even MORE expensive than it currently is.

**Comment by KorPhaeron** [comment]
>This has been the case since the dawn of time

My memory must be terrible but I can't remember this being an issue in some of the older lighting systems.

**Comment by WJohn** [comment]
It was definitely around in our previous area based lighting, and we've had that basically since TG started.

**Comment by KorPhaeron** [comment]
Maybe it was just that it was possible to see a couple times in the dark at some point so you could actually move in maint without glowing

**Comment by Dorsisdwarf** [comment]
This would make everything terrible if implemented. Also unwanted feature req

**Comment by freerealestate** [comment]
what
