### ISSUE TITLE
The the box of hugs

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10692]
1. The hug message says "You hug the the box of hugs."
2. It's very easy to spam the chat with the hug message
3. It comes with bruise packs, ointment and a medipen despite not being a medkit for some reason

**Comment by RemieRichards** [comment]
1. somebody wrote ```the``` instead of ```\the``` in the message (Alt: Remove ```the``` altogether)
2. it's a joke item, but yeah, missing cooldown.
3. intentional.

**Comment by freerealestate** [comment]
what's the IC justification for having medical supplies in it though, it
doesn't make any sense to me. it just looks like an oversight due to
inheriting from other boxes with those inside.

**Comment by WJohn** [comment]
It doesn't inherit from medkits because it isn't one.

**Comment by freerealestate** [comment]
That's what I had thought. So why does it have medical supplies in it? I
don't even understand why it's a container.

**Comment by WJohn** [comment]
Because it's a hugbox. It makes things better and safer. That's the joke.

**Comment by Marflowerose** [comment]
Hugging hugbox should transfer omnizine :^)

**Comment by freerealestate** [comment]
Yeah, I think the hugging itself should be what transfers benevolent
effects (even if it's just roleplay-wise), not the poorly justified objects
that spawn inside.

**Comment by Marflowerose** [comment]
And OD on omnizine will result in hilarity.

**Comment by SconesC** [comment]
It has those objects because it spawns in perma on the tables outside the cells, and the contents are a replacement for those that used to be there

**Comment by Xhuis** [comment]
H U G B O X

**Comment by Memendia** [comment]
Someone should close this

**Comment by freerealestate** [comment]
Did it ever end up getting fixed?

**Comment by Jordie0608** [comment]
Yes by #11175
