### ISSUE TITLE
Blob: Pulse Animation and Node/AdjustColors go nuts

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#10696]
Simply put, these two procs seem to go crazy as blobs expand larger and large; particularly when you have more than one colored blob involved. Eventually either of these can end up becoming the costliest proc on the server, when profiled--to the point of sometimes inducing considerable lag.

This is quite odd as flick() doesn't appear to be innately expensive.

**Comment by WJohn** [comment]
Why exactly do we have it do that? There's already an animation there and the most you get is large swathes getting brighter or darker every once in a while.

**Comment by RemieRichards** [comment]
Are you sure this is on our end @Fox-McCloud, I don't believe it ranks that highly for us, and I know you guys only recently ported Blob from and ancient revision of terribad blob to reagent blob.

**Comment by Fox-McCloud** [comment]
Code is identical on the parts that are impacted (one proc in particular only calls flick()). Profiled your own code, and results were similar:

http://gyazo.com/05e58994037cce45a5e0d468cafd563f

**Comment by Iamgoofball** [comment]
can we remove the pulse animation shit yet

**Comment by Anonus** [comment]
The pulse animation was to show if stuff was getting activated by nodes, except it doesn't actually show the range of nodes, just flashes a lot.

**Comment by phil235** [comment]
We just had three blobs on Sybil and the pulse animation is indeed pretty costly. The Objects Subsystem was oscillating between 1.5 and 2 ds during the second half of the round.

**Comment by phil235** [comment]
We ran a profile and the PulseAnimation() proc was the 4th most costly:
/obj/effect/blob/proc/PulseAnimation  19.230(self)       19.237(total)   19.259(realtime)       216002(calls)

**Comment by Iamgoofball** [comment]
c h r i s t

i'll look into gutting it and just making the blob parts that do shit just run on a process() timer

@anonus

**Comment by ChangelingRain** [comment]
The pulse animation actually shows the range of the pulsing thing now, so it's actually useful. If there's a way to have the same effects but less godawfully costly it'd be really nice.
