### ISSUE TITLE
Feature request: flashing internals toggle button (icon already exists)

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#10704]
There's an icon called "internal2" in screen_gen.dmi, which is a flashing red internals toggle button, apparently intended to warn the user about their oxygen tank running low.

Having this implemented would save many newbies' lives.

**Comment by WJohn** [comment]
Alternatively, someone could pick up where you left off with your PR where I've expanded this into action buttons for every possible tank type.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
