### ISSUE TITLE
Simple animals are too slow

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#10712]
With the new changes to run-speed, simplemobs have suddenly become incredibly slow compared to everyone else. This is especially bad for melee animals.

**Comment by GunHog** [comment]
There were more changes? I seem to have the same speed as I always did, except for zero-gravity.

**Comment by MrStonedOne** [comment]
basil has a slightly higher run speed in the config.

**Comment by phil235** [comment]
>basil has a slightly higher run speed in the config.

Basil is sanic as hell.

**Comment by GunHog** [comment]
That is amazing. I love it.

**Comment by MrStonedOne** [comment]
Its really hard to tell how fast a change is gonna be, speed is done as a delay, I changed it from 1 to 0.7 thinking that would be 30% faster, IE not much, but it doesn't seem to work that way.

**Comment by phil235** [comment]
Yeah, it's not continuous, that's why we can't give healthy food a slight speed boost effect.

**Comment by Lumipharon** [comment]
MSO when the speed nerf first happened we literally had that whole thing where almost everyone agreed that a moderate speed decrease would be good, but there was no way in byond to make an increment smaller then what we now have.

Byond mang.

**Comment by Dorsisdwarf** [comment]
Feeback furum
