### ISSUE TITLE
Multiverse sword pulls in logged out players

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#10721]
I was observing a round. 
Logged out as ghost, come back to be alive as a clone of a guy with the sword.
Probably shouldn't happen.
Also the sword has no flag/yes/no option which is kind of annoying

**Comment by AnturK** [comment]
Probably have just been pulled the moment i logged in, but you know putting this up just in case

**Comment by KorPhaeron** [comment]
It must have pulled you as you logged in. It uses the get_candidates proc with the BE_WIZARD flag, which checks for offline/afk people already. Toggling off the wizard flag will stop it pulling you (which I had to do yesterday so I could answer adminhelps)
