### ISSUE TITLE
Thrown objects in space 'stay thrown' until you step on them.

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#10746]
rev: 62f6e3af4343637ef76e5910c99ad3736f6d50b9

How to reproduce: throw stuff at a wall, then step on the stuff.
Result: Get hit by the stuff that should not be moving anymore, damaging you. 
This is more apparent when explosions have happened.

It gets really weird after that. Once you step onto the tile with the thrown objects, they dislodge themselves, bounce of the nearest object and begin drifting in the opposite direction.
This somehow only works once - after having dislodged an item by stepping on it, any thrown object just bounces off walls/windows/etc like usually.

**Comment by phil235** [comment]
Same bug as #10740
