### ISSUE TITLE
Being thrown in space will get you stuck there.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10740]
A man was thrown out the shuttle pod and got stuck nonmoving 3 tiles away form the shuttle in space(when he should have been launched at 50mph). I tried to drag him back inside but he didn't move, He threw something, but didn't move.

This must be related to the throwing into wall = damage and stun, as he was stunned in space.

@phil235 updated:
Thrown things no longer bounces off walls, unless they're in no gravity. Heavy items and mobs thrown can push the mobs and non anchored objects they land on. Throwing a mob onto a mob in no gravity will push each one in opposite direction. Thrown mobs landing on wall, or dense object or mob gets stunned and a bit injured. The damage when mob hit a wall is nerfed.

**Comment by WJohn** [comment]
Oh yeah I actually remember this happening as a xeno hunter. If you leap into a wall and are stunned while sitting over space, you never get up. I'm not sure if that ever got fixed, but it applies to more than just humans.

**Comment by phil235** [comment]
@WJohn I don't think this is related. The current bug is specifically due to my code change.

**Comment by Midaychi** [comment]
Is #10748 related to this? You're getting thrown through the teleporter, and no amount of wiggling (as a drone anyways) or using tables/grills will allow you to move.

**Comment by phil235** [comment]
@Midaychi  Unrelated, 10748 is about space move stuff, whereas this is about throwing.
