### ISSUE TITLE
Box map tech storage missing boards

### ISSUE THREAD

**Issue by Midaychi** [tgstation/-tg-station#10754]
Checked it out on dm; Not sure if this is intentional or not but there's no circuit imprinter or exosuit fab boards in tech storage.

I remember them being there before, so perhaps this is an oversight?

**Comment by Lumipharon** [comment]
Yep, they're not there.
If someone fucks R&D, it;s gone forever.

**Comment by newfren** [comment]
No circuit imprinter board is particularly annoying, and no exofab board means the new traitor surgery kit is pretty useless!
