### ISSUE TITLE
Xray manifest rate extremely low or the requirement is absurdly high.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10756]
I haven't been able to manifest it in two weeks with over 60+ test subjects on multiple injections. It's either broken or nigh impossible to manifest. Looking at the code I notice it has a higher block requirement to manifest than hulk. And that's just retarded.

xray
lowest_value = 256 * 15

hulk
lowest_value = 256 * 14

**Comment by WJohn** [comment]
Probably duped from #7289

**Comment by Supermichael777** [comment]
literally why no one plays geneticist.

**Comment by Supermichael777** [comment]
a tilt looking at this closely this math requires the first value in the fff bloc to be e or f to manifest.

**Comment by Durkel** [comment]
Yeah, I just realized that genetics is done in hexadecimal so xray requires the first block to b F. Which no other power requires. I'm guessing this is more of a consistency problem since it's the only power that needs to be this high for some unknown reason.

**Comment by Durkel** [comment]
#10801 solved this, closing.
