### ISSUE TITLE
unanchored canisters if you wrench it while running through a connector port

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#10753]
1. Have canister.
2. Pull canister over connector port.
3. Wrench canister while running over connector port.
4. If you time it right, the canister isn't anchored at the port and can be moved around.
5. The port does stay occupied, you can't attach anymore canisters to it but the canister itself still appears to act like it's linked.

reported by Jeerman ingame

**Comment by phil235** [comment]
Can't reproduce, how hard is it to do?

**Comment by Ausops** [comment]
Fairly easy, the guy did it when I asked.

**Comment by phil235** [comment]
The bug isn't about being able to move the canister fast enough, there's something wrong with connector ports.

**Comment by Ausops** [comment]
rip. Thanks for looking into it anyway

**Comment by duncathan** [comment]
Out of curiosity, is it all connectors throwing this runtime, or just the ones in toxins?

**Comment by phil235** [comment]
All connectors I think

**Comment by duncathan** [comment]
Cannot reproduce on any connectors save the ones in toxins connected to manual valves. Caused by the same thing as #10682. Additionally, I can only reproduce this when the connectors do not have a node.

**Comment by phil235** [comment]
You're right, I can only reproduce by adminspawning some connector ports machinery. The bug was happening in atmos when reported I think, but can't reproduce it there...

**Comment by duncathan** [comment]
Yeah, that's why it's only immediately reproducible on the toxins connectors; they're the only ones (that I know of) that start connected to a component. Should've been more clear.
