### ISSUE TITLE
syndicate borg has the wrong pinpointer

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10766]
Nuke ops get a /nukeop version of the pinpointer
The borg gets a /operative version.
Why is this bad?
The syndicate borg cant work out how to get back to the shuttle while no syndicates are there.

**Comment by Marflowerose** [comment]
Doesn't it work as intended? AFAIK borg pointer points to nearest operative, not disk or shuttle.

**Comment by phil235** [comment]
Intended

**Comment by Jalleo** [comment]
Not a issue then thanks for clearing this up
