### ISSUE TITLE
Chat links for moving the shuttle and for BSA in centcom messages dont work.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#10764]
The button to move the shuttle when someone requests to move from the station to centcom does not do anything. Additionally, the BSA link on the centcom messages does not work.

**Comment by Jordie0608** [comment]
I've heard problems with the BSA link reported several times, yet it works fine whenever I try to test it and there don't seem to be any associated runtimes.

I can confirm the Move Ferry link not doing anything however.

**Comment by phil235** [comment]
The BSA button on Centcom message/ nuke code request / syndicate message (emagged communication console) can be made to runtime and not work if the mob sender is gibbed, changed into another mob or if the player ghosts out of the mob.

**Comment by phil235** [comment]
Well, actually the BSA issue was way more simple than I thought. It was checking the target's client for admin rights instead of the admin...

The runtime still exist but wasn't what this issue was about.
