### ISSUE TITLE
Resisting out of the odysseus sleeper still says they are in the sleeper

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#10776]
Guy gets picked up by a the sleeper and resists out but the sleeper says he is still in it. So if you hit eject he gets teleported back to the mech without dropping him out.

**Comment by Incoming5643** [comment]
In before mechs are garbage tag

**Comment by Supermichael777** [comment]
MECHCODE WHY? I think this is similar  to the pilot teleportation bug.

**Comment by phil235** [comment]
It's actually my fault, I deleted a line that I shouldn't have.
