### ISSUE TITLE
changeling stings/Damp rags and hardsuit/biosuits/that sort of clothing

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#10784]
So apparently you can damp rag and sting someone through a hardsuit or biosuit
Damp ragging someone through a sealed space suit doesn't even make sense
And for the changeling stings, didn't someone say it shouldn't work through a hardsuit or biosuit?
Well I got cryo stung in a hardsuit. In space. .-.

**Comment by Dorsisdwarf** [comment]
I think the first one is a dupe
The second one is an intended feature

**Comment by phil235** [comment]
Yeah, damp rag is weird on harm intent it uses reaction(TOUCH) which probably doesn't pass through hardsuit. But on any other intent it just reagents.trans_to() which completely bypasses clothing protection.

**Comment by Dorsisdwarf** [comment]
Feedback forum.
