### ISSUE TITLE
Hulks stun even when attacks miss

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10780]
"Attempted to kick"

**Comment by Dorsisdwarf** [comment]
@SconesC  would you mind reproducing this?

**Comment by SconesC** [comment]
Yes I would mind

The issue still exists

Melee attacks with harm intent and empty hands have a chance to miss, giving an "attempted to kick" or "attempted to punch" message instead of a "punched". Hulk attacks will stun even when missing.

**Comment by tkdrg** [comment]
Hulks no longer stun so RIP
