### ISSUE TITLE
Ctrl+C no longer copies text

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#10809]
http://puu.sh/japDK/e39450db6b.png
Thanks to the [recent resist hotkey pull](https://github.com/tgstation/-tg-station/pull/10715), ctrl+c now always tries to resist and no longer copies text. Could the resist hotkey get moved to something else instead?

**Comment by optimumtact** [comment]
I'd prefer the hotkey over copy paste personally.

**Comment by Anonus** [comment]
But muh *roar spam.

**Comment by optimumtact** [comment]
Ctrl + up goes up to the last thing you type in the chatbox

So *roar
Ctrl + up
enter
rinse repeat

There's a secret protip for you

**Comment by optimumtact** [comment]
Plus ctrl enter still submits the roar, so you can go even faster

**Comment by Shapsy** [comment]
Why not just move it to a different key, like does R do anything?

**Comment by Iamgoofball** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: 

what the fuck no no no what are you doing stop no fuck stop i copy paste text from game all the time with this stop no

move resist to a different hotkey holy shit

**Comment by freerealestate** [comment]
Damn, that's annoying. Sorry about that.

I could fix this by removing the CTRL version of the resist hotkey, but that'd be inconsistent with other hotkeys. (No idea why every hotkey needs a CTRL version, both when hotkeys mode is on and off). Or I could just move it to a different key, but there aren't many free reachable ones available. Y, perhaps.

**Comment by Iamgoofball** [comment]
remove the ctrl+c hotkey then for resist
