### ISSUE TITLE
Meta: Corporate Display Nuke can be used as invisible, Projectile blocking cover.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10806]
![](https://i.gyazo.com/2fc3406a959401a598ca39d8e11ddc7a.gif)

**Comment by Incoming5643** [comment]
the dangers of editing iconstates on the map maker instead of creating a subtype of the desired object with that icon state.

The byond random number generator in the wizards den has fallen to the same problem

**Comment by phil235** [comment]
@Metacide

**Comment by francinum** [comment]
Fixed in #10804
