### ISSUE TITLE
Metastation: Emergency Shuttle Cockpit missing a window.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#10812]
![](https://i.gyazo.com/2693ce4acad3c8c093edcc0b6d34a78a.png)

![](https://i.gyazo.com/9b4d5beb8fa38e55758af8a1038a7362.png)

**Comment by WJohn** [comment]
@Metacide

**Comment by Metacide** [comment]
Thanks, will fix soon.

**Comment by MrStonedOne** [comment]
It's not actually missing that window, its that that area isn't the same area as the docking port.

When a shuttle's mobile docking port is in any area of subtype shuttle, it will only copy turfs of that same area.

**Comment by Metacide** [comment]
Fixed in https://github.com/tgstation/-tg-station/pull/10839
