### ISSUE TITLE
Round start firedoors prevent the spread of atmos until closed and opened

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#10828]
On MetaStation, Science department, there was a breach north from where I'm standing in the picture and the air pressure was very clearly divided between two sections, divided by the open firelocks which I'm standing by. To the north from the firelocks the pressure was under 30 kPa, and to south it was perfect 101.3 kPa and not changing. After opening and closing one of the firelocks the air started to flow from south to north.

![sieppaa](https://cloud.githubusercontent.com/assets/5420151/8869890/ed45f7d4-31f1-11e5-990e-c66a8d0017e6.PNG)

**Comment by Metacide** [comment]
How bizarre, looking into this now.

**Comment by MrStonedOne** [comment]
Its not you metacide, Its the firelocks.

Still no idea whats happening here, but air will sometimes like to get stuck at firelocks, and everything I've seen in the code says it shouldn't.

**Comment by phil235** [comment]
Could it be related to firelocks being made constructable/deconstructable?

**Comment by MrStonedOne** [comment]
This has been an issue for awhile, Its also random too, and will solve itself randomly as well.

Like, you can open an air canister in that small section above bridge on box, and the air will stay contained within the firelocks for a random amount of time, then start to spread.

I noticed this when I was doing research for the scrubbers pr and was using unlit room temp plasma

**Comment by Metacide** [comment]
Oh right. Was wondering what it could be, couldn't find anything awry with the tiles.

If it resolves itself given time, though, that works I guess. Mysterious though it is.

**Comment by MrStonedOne** [comment]
I've figured out the cause, but not WHY its causing this, because it shouldn't.

Also, @kingofkosmos or @phil235 Could you edit the issue title to: "Round start firedoors prevent the spread of atmos until closed and opened"
