### ISSUE TITLE
hyperspace sleep chamber icon issue/meta map issue??

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#10824]
Hyperspace sleep chambers on metastation abandoned ship use cryogenics2.dmi instead of the dmi it' supposed to use, stock_parts or something, when in a deconned state. They turn out invisible as a result.

**Comment by francinum** [comment]
They are meant to be deconstructed as a source of metal.

**Comment by Metacide** [comment]
Looking into it

**Comment by Dorsisdwarf** [comment]
@Metacide was this fixed?

**Comment by Metacide** [comment]
Fixed sometime before https://github.com/tgstation/-tg-station/pull/12133 - wrench screwdriver seems to work.
