### ISSUE TITLE
Borging shadowling thralls does not de-thrall them

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#10822]
Shadowling Thralls  
Security Cyborg-677 PM 

People complained about borgs with shadowling icons :/

**Comment by SconesC** [comment]
@Xhuis

**Comment by Xhuis** [comment]
for christ's sake people i'm not the sole person that can work on shadowling, i'm on hiatus
i chose an open-source server for a reason.

**Comment by SconesC** [comment]
yeah but your gamemode is in the rotation as well as being borderline nonfunctional so some attention would be nice
