### ISSUE TITLE
Chaplains who choose clown/banana bibles cannot heal

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#10838]
Alright, so I dug through the history of the relevant changes and I can't pinpoint what exactly caused it, and I don't know how long it's been around, but basically:

* Choosing the clown/banana bible as chaplain makes you a clown with a clown mask and shit
* And it also makes you an actual clown, i.e. with CLOWNMUT, i.e. clumsiness
* Trying to heal someone with a bible when you are clumsy has a high chance of failing and knocking you unconscious
* Which is admittedly fucking hilarious but shitty for the people who expect to be healed
* Like, for instance, if it's a blob round or something, the roundstart chaplain decided to be a clown, and everyone is that much more fucked

this brings great shame upon the honkmother

**Comment by Iamgoofball** [comment]
Try going to medbay.

**Comment by SconesC** [comment]
This is what you fucking get for picking Clown bible

**Comment by Durkel** [comment]
But scones, laughter is the best medicine.

**Comment by freerealestate** [comment]
#9769

**Comment by CosmicScientist** [comment]
But that sounds exceptionally amusing in a blob round or any other round.

So you get a clown mask, a bike horn, no banana peels (ask botany) and a clown mutation for picking the CLOWN bible? Either go to genetics (it's the clumsiness gene right?) or embrace the laughter of the ghosts watching from deadchat.

**Comment by Xhuis** [comment]
:no_entry_sign: :a: :bug:

**Comment by SconesC** [comment]
what does that even mean xhuis

no a caterpillar?

**Comment by Xhuis** [comment]
not a bug

**Comment by Cheridan** [comment]
hahaha oh wow

**Comment by Dorsisdwarf** [comment]
Ideas/Feedback

**Comment by freerealestate** [comment]
this is clearly a bug/unintended functionality

**Comment by Iamgoofball** [comment]
This is entirely intentional by cheridan. You play a clown, get the downsides of a clown.

**Comment by tkdrg** [comment]
what goof said

**Comment by PKPenguin321** [comment]
I feel like this should be reopened and made so the clown-chaplain only has a chance of KOing himself instead of it happening literally every time
