### ISSUE TITLE
Mining dorm airlock sprites, seen through mesons, are honked up

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#10840]
What happened: http://i.imgur.com/EcT1KTq.png

Why this is bad: HONK!

Additional details: I tested a bunch of other doors, all of them seemed to be fine. This is mesons only.

**Comment by Supermichael777** [comment]
i think your seeing the tile under the door. several on meta are fucked up like this

**Comment by MrStonedOne** [comment]
@Metacide

**Comment by Metacide** [comment]
Will fix, thanks for the heads up. :+1: 

If you find this issue anywhere else do flag it up, it's easy to fix them but hard to find them.

**Comment by bgobandit** [comment]
this is box
