### ISSUE TITLE
Quality-Of-Life changes for Multiverse Sword

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/-tg-station#10844]
The Multiverse Sword is a cool idea and all that, but its execution is flawed somewhat. Let me give an example:
You're a survivalist, and have the objective to survive until the end. You die. You could get defibbed, cloned, bolt-of-ressurectioned, replica podded, or other such things. You could get that greentext if someone bothers to resurrect you, but bam! Memesworded, and your old life gets irrevocable redtext. This CAN be rectified by disabling being a wizard, but that is a bit of an inconvenience, disabling wizard every round and re-enabling it every lobby, so here's one simple quality-of-life change: Give memesword duplicate candidates a "Do you want to be a [Memesword user's name]? Please choose quickly." prompt. It's that simple.

**Comment by callanrocks** [comment]
Survivalist is back?

**Comment by Supermichael777** [comment]
meme-sword producing more meme-swords which can be used by other people results in a chaotic mess. whether that is good or bad is debatable but it needs to be more manageable chaos rather than the murder-fest it seems designed to devolve into. also clutters up end-round reporting(60 antags muh eyes)

**Comment by Iamgoofball** [comment]
Why don't we make Meme-swords auto-greentext any objectives you might of had?

**Comment by Incoming5643** [comment]
Honestly while a fun idea, every time I've seen it in play it's had such a dominating influence on the round that it literally ceases to be wizard.

**Comment by daman997** [comment]
multiverse swords make me want to rip my balls off

**Comment by Dorsisdwarf** [comment]
Feedback forum. There's even a thread for this one.
