### ISSUE TITLE
Handcuff bug is back

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#10857]
Handcuff sprite is there, handcuffs are not. Kinda shitty when you assume someone is restrained and then they pull out a gun and kill you. 

It's a pretty high priority issue. Every other round someone is going to die because of this.

**Comment by Incoming5643** [comment]
Less it's back and more it never left methinks.

I presumed that the bug was just a matter of layering, but some part of #10659 must still be off.

**Comment by Boredone** [comment]
I believe the fix was merged, Sybil just hasn't updated to include it yet. Dunno about Bagil.

**Comment by Incoming5643** [comment]
Looking into it, yeah sybill doesn't have the fix live yet.
