### ISSUE TITLE
No progress overlay for digging 

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#10854]
Exactly what it says on the tin: mining rock has progress overlays, but digging up sand on the asteroid does not.

I've only tested this with the standard pickaxe, not the shovel or advanced picks yet. Will do.

**Comment by phil235** [comment]
Yep, that's because digging sand floor tile doesn't use do_after() but sleep(). It happens with shovel and all pickaxes (including drills).

**Comment by WJohn** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
easy fix, replace the retarded snowflake sand digging sleep() call with a do_after()
