### ISSUE TITLE
Box mapping errors.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10863]
Two map errors on box.

SW solars.

http://i.imgur.com/qRXzTdc.png

Random fucking  wall out of nowhere.

Sci maint, just below the testing range.

http://i.imgur.com/3tLfI5l.png

There's grille/window combo there that has a wire missing under it, I believe it fucks with the power. Look to the smashed glass to see it.

**Comment by Supermichael777** [comment]
why such things should be purged. stupid opaque windows.

**Comment by Jalleo** [comment]
That was the issue i thought someone kept breaking it when i first played the updated map
