### ISSUE TITLE
Bartender's uniform is buggy

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10868]
![bartender1](https://cloud.githubusercontent.com/assets/9714964/8894741/6074d704-3376-11e5-92a5-3e677ca5f4ab.png)

Pretty sure this is a dupe but it's an older bug

AI hologram of the Bartender has this as well

**Comment by Supermichael777** [comment]
because its alt modes are fucked up i think. it like doesn't have a sprite for it.

**Comment by SconesC** [comment]
Yeah that's what it is 

But it's odd that the alt mode would be showing up in the sec record
