### ISSUE TITLE
Engineer cyborgs cannot build false walls

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#10874]
The progress bar shows up and says "You start building a false wall..." However it never completes.

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/objects/structures/girders.dm#L105

S.amount instead of S.get_amount()

**Comment by Marflowerose** [comment]
I don't think any borg can even open false walls either.

**Comment by Shad0vvs** [comment]
Borgs can push walls(by holding an item and hitting the wall, at least in the past with a flashlight) yet they can't open them as well.
