### ISSUE TITLE
Hardsuit helmets are not blocking hair

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#10875]
Exposing shitty floorlength braids for days now

**Comment by phil235** [comment]
Cannot reproduce. Which hardsuit helmet?

**Comment by SconesC** [comment]
Engineering Hardsuits, CE and regular

**Comment by phil235** [comment]
Can't reproduce on sybil or basil, it must've been linked to the Layer define issue that was fixed.

**Comment by SconesC** [comment]
Unless it was fixed in the last six hours?
