### ISSUE TITLE
Exchange docs objective can be given to traitors who need to die

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#10883]
![uh](http://puu.sh/jeeaq/e7123eded0.png)

**Comment by Cheridan** [comment]
Did he have the documents on him at the time of the round end? :^)

**Comment by Anonus** [comment]
Steal objectives check if you're alive, nerd.

**Comment by Ikarrus** [comment]
Suicide objective is cancer, just imo

**Comment by Cebasiz** [comment]
nofunallowedrobot.jpg

**Comment by freerealestate** [comment]
>Suicide objective is cancer

this

"In order to win, lose."
