### ISSUE TITLE
More box mapping issues

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10896]
![Turbine Engine](http://i.imgur.com/96FkB0x.png)
Is this wall on the left intended above turbine engine room?

![sadf](http://i.imgur.com/rFmXH34.png)
Bio disposals airlocks are not powered and there's a random ass wire under the first airlock.

**Comment by Marflowerose** [comment]
Pretty sure I saw another random ass wire under the second airlock aswell.

**Comment by Ikarrus** [comment]
@Dorsisdwarf Use this checklist next time https://tgstation13.org/phpBB/viewtopic.php?f=11&t=327

**Comment by Jalleo** [comment]
That wall is intended

**Comment by Shad0vvs** [comment]
If the wall is intended, its blocking a window, Maybe make the window that it's blocking a wall as well then?
