### ISSUE TITLE
Double agents doesn't give anybody targets

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#10904]
The traitors were:
Killbasa was Trevor Glomps the Cargo Technician and survived (used 0 TC) 
Objective #1: Nothing Fail.
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Success!
The traitor has failed!

Keyblock was BAPHOMET-XII the AI and survived
Objective #1: Nothing Success!
Objective #2: Stay alive until the end. Success!
The traitor was successful!

Trinerc was Cluck the Clown and died (used 0 TC) 
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Suede Falcon was Willard Barrels the Cook and had their body destroyed (used 0 TC) 
Objective #1: Nothing Fail.
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Belchinganna was Lizzy Ari the Janitor and survived (used 19 TC)     
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

RehabBaron was Richard Green the Quartermaster and died (used 20 TC)    
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Deskdrawer was Hunter-Of-Glass the Cyborg and survived as Miss Bianca (used 20 TC)     
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Jomckellan was Tyler Hughes the Station Engineer and died (used 20 TC)     
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

ParadoxPancake was Mason Wilkes the Medical Doctor and died (used 17 TC)      
Objective #1: Nothing Success!
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

Smirkingbastard was Garrett Blackburn the Assistant and survived (used 20 TC)   
Objective #1: Nothing Fail.
Objective #2: Escape on the shuttle or an escape pod alive and without being in custody. Fail.
The traitor has failed!

The code phrases were: Head of Security, hate, lock.
The code responses were: peace, Utatul-Deetum, record.

**Comment by Jalleo** [comment]
I knew it was bugged

**Comment by Incoming5643** [comment]
Maybe you should have said something before it was merged. Will look into this ASAINSA (as soon as it's not six am)

**Comment by MrStonedOne** [comment]
I have no idea,

I forced secret on da and this happened.
