### ISSUE TITLE
Appendicitis can clear up on its own.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#10911]
Examined a security officer with a 1/3 appendicitis case, and several seconds later without any intervention it cleared up. Could be a bug or it could be intended, I'm not sure.

**Comment by Fayrik** [comment]
Can confirm.
Have seen hundreds of "spontaneous appendicitis" events trigger, and yet it's been at least 6 months since I last saw someone actually suffer from it.
I think this has been a bug for a long time, somehow.
