### ISSUE TITLE
Cult scaling can start cultists with enough people to finish their objectives

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#10919]
https://imgur.com/N93m0IA

9 roundstart cultists, 9 cultists needed to summon Nar-Sie.

Cult scaling is a terrible idea when they always have one objective that tasks them with conversion.

**Comment by Cebasiz** [comment]
well, what's your idea, remove it? i don't have the exact numbers on highpop cult winrate but i can't imagine it being high. it's not like getting all the words is trivial when the majority of cultists have no idea how it works, nor is it trivial to survive that long with 9 people during researching if you're lucky enough to get someone who knows how to do it.

besides, don't they always have to sacrifice someone relatively important? that's a herculean task itself at times, necessitating as it does a reasonably organized crew with moderate to high tier equipment and a degree of coordination and station control.

**Comment by SconesC** [comment]
I'm fairly certain they can spawn with MORE than nine because scaling memes

I saw a blitz cult in under five minutes because of this

**Comment by PKPenguin321** [comment]
iirc this has been a thing for a while, this issue may be a dupe

either way it's rarely an issue, blitz cults are few and far between due to the incompetence of cultists. the round pictured that i was a starting cultist in took so, so long with absolutely no research made

**Comment by MrStonedOne** [comment]
maybe, just maybe, fix it so the objective scales with the round start cultists. like it used to.

=P

**Comment by bgobandit** [comment]
the problem is narsie summoning involves standing around a rune and unless people lie on top of each other or dumb shit like that, the maximum people involved is 9

**Comment by freerealestate** [comment]
so just make the rune look for people in the surrounding two squares

**Comment by WJohn** [comment]
That works too.

**Comment by Lumipharon** [comment]
Didn't that get suggested previously? I thought someone was going to implement it.

**Comment by advomach** [comment]
If you're going to extend the square looking, that actually might making summoning narsie easier. It's ridiculously hard to get 9 people to stand in a perfect square formation, a lot of people don't seem to get it and even more people just fuck off when it's taking too long, unless there's someone constantly screaming in cultchat to coordinate and for the other cultists stop being such fucks.

**Comment by MrStonedOne** [comment]
So i just noticed that this was about summoning narnar, and not escape with x cultists on the shuddle.

**Comment by neersighted** [comment]
Pretty sure @tkdrg's newcult fixed this.
