### ISSUE TITLE
Nuke ops agent card access bug

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10933]
When getting access legitimately from the hop via your nuke ops agent card, you lose access to the syndie shuttle, but if you drop your card and let another nuke ops scan it, and then you scan theirs, you regain your shuttle access.

**Comment by Anonus** [comment]
Agent IDs shouldn't be able to be put into the ID console; they used to not be able to, probably for a reason similar to this.

**Comment by Incoming5643** [comment]
I think it's  because the id machine scrubs out accesses that it can't grant, meaning you could also strand a centcom official with this.
