### ISSUE TITLE
Cyborg modules don't come with relevant departmental radio 

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10932]
This is a feature request, but it seems like a bit of an anachronism to not get the relevant radio frequency automatically on module change.

**Comment by WJohn** [comment]
I swear they used to start with these things, but then it was intentionally removed so they were forced to get it added to them manually. I don't know the reasoning behind that though.

**Comment by GunHog** [comment]
I would not be against coding this...

**Comment by Cebasiz** [comment]
yeah sure. i suppose in the past it was an intelligence thing, where rogue cyborgs couldn't automatically hear relevant departments. in the old days AIs could only be on one channel at a time. these days though with integrated radio it probably doesn't matter though, as AI has perfect radio intelligence and can just tell the cyborgs if they need to know something.

i don't think it's an issue anymore.

maybe we can give them 15k batteries right off the bat too :^)

**Comment by Cebasiz** [comment]
oh, and another option: give all nonsecborgs default radio. i understand why security wouldn't want a secborg on-channel, so they can better cover up prisoner beatings from something that must respond to them, but engiborg/medborg, yeah why not. it will help them enormously and there's not really a downside.

**Comment by xxalpha** [comment]
Cyborgs do not work for the departments.

Cyborgs work for the AI.

**Comment by Cebasiz** [comment]
incorrect considering human order priority > AI priority. AI is just an organizer, you really serve humans miles before you serve the AI.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request

**Comment by freerealestate** [comment]
All these good ideas, lost to the ether because some guy is going on an
issue report blitz for some reason

**Comment by Miauw62** [comment]
read what he posted.
