### ISSUE TITLE
The mass driver doesn't work because of space wind.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10936]
Any time you try to load someone onto it and push the launch button, the blast doors will open a lot sooner before it launches -- long enough for the payload to get pulled off the mass driver towards space before it can be launched.

Could probably be easily fixed just by changing the timing between the door opening and the mass driver shooting.

**Comment by WJohn** [comment]
Given the amount of air that gets drained with the door before and after the firing, I think the door should open and close MUCH more quickly so it doesn't drain a good chunk of the chapel and render it freezing after one or two uses.

**Comment by Supermichael777** [comment]
I swear I saw this fixed this by making the driver two throwers long. we could implement a similer solution here. also constructable drivers when?

**Comment by optimumtact** [comment]
Drivers should just have a wall that only lets the mass driven objects through

bluespace forceshield technology
