### ISSUE TITLE
Traitors need convenient access to insulated gloves

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#10937]
Just finished my 500th round of dying as a traitor because I managed to shock myself while trying to add wires for a powersink.

It's a huge quality of life issue for traitors and one of the dumbest continuing gimps that they suffer from, I can summon station destroying WMD's, high powered weaponry, etc. but I can't get some damn gloves so I can do basic hacking/sabotage/fuckery. There's so much creative shit I can't do because I don't want to spend my time harassing cargo for gloves

Add them to the PDA or include them in the syndicate toolbox (preferable). I've heard the absurd argument of "You can just get them from..." but 1) If they're so easy to fucking get why are you opposed to let traitors get them easy and 2) traitors need flexibility and versatility, you might not need the gloves initially but get caught in a bind where they become necessary. 

This should be a very simple, uncontroversial way to make traitors a little more enjoyable.

**Comment by Incoming5643** [comment]
could probably add a nefarious looking pair to the syndicate toolbox

**Comment by WJohn** [comment]
That'd be great, yeah. I don't think they really necessarily need to look nefarious, the toolbox is already a giveaway.

**Comment by Incoming5643** [comment]
We'll I'm just saying that they probably should because it's a 1 TC item and people could very easily just ditch the obvious looking toolbox for the gloves, which by itself might be worth 1 TC by itself if it had no tells.

**Comment by WJohn** [comment]
Perhaps buff the cost to 2 TC if the gloves are added to the toolbox?

**Comment by Incoming5643** [comment]
I like having a few 1 TC items, otherwise everyone just ends up with soap

**Comment by Cebasiz** [comment]
i don't think it needs to be increased necessarily, traitor toolboxes are semi-dangerous in that they are of course easily recognized, and if you just take the tools and junk the toolbox you risk it being recovered at some point with your prints on it as you touched it prior to putting on the insulateds.

it will probably still increase traitor power relatively but i don't think that's really a bad thing in this case, anyway.

**Comment by Shad0vvs** [comment]
The traitor menu is pretty large in itself, don't make it bigger just for some gloves, just add it to the toolbox.
