### ISSUE TITLE
Monkeys can use brute/burn patches but not brute packs/ointment.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#10946]
Consistency and balance etc. Both are always found right next to eachother so throwing the "but muh realisms and application difficulty differences" excuse won't work here.

**Comment by Incoming5643** [comment]
While we're talking about consistency between these two sets of items.

Using on yourself:
patches are instant
packs/ointments have a delay

Using on others:
patches have a delay
packs/ointments are instant

**Comment by Cheridan** [comment]
IMO I think we need a general review of what monkeys can and can't do, with my personal preference leaning towards "everything but guns and also maybe guns".

**Comment by Iamgoofball** [comment]
just make them both applicable

or just axe bandages/ointment for styptic/silver sulf patches entirely because they're superior

**Comment by Marflowerose** [comment]
Reason patches have delay is that you can make patches that are not brute/burn patches, as in, make toxic patches. Packs and ointments are never toxic hence no delay. Damp rag should have delay seeing as patches also have it.
