### ISSUE TITLE
Ian's renaming pet collar.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#10942]
Renaming Ian with collar then putting an item on him renames him back to Ian. I've only tried with the HoP hat.

**Comment by CorruptComputer** [comment]
It's cause names with hats are hard defined

**Comment by astralenigma** [comment]
Can we make it soft defined?

**Comment by CorruptComputer** [comment]
I don't know, can we?

**Comment by astralenigma** [comment]
I'm curious about the renaming collar is it a new item or is it an option on Ian?
