### ISSUE TITLE
Multiversal Sword can choose you while you are still alive in your original body

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#10958]
Occured to me just now without any notice @KorPhaeron

**Comment by KorPhaeron** [comment]
Like it ghosted you?

**Comment by Jalleo** [comment]
no it made me one straight from being a my normal player

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/ff8d782b09bca5e991688f5db10c685e5cbbbbe7/code/game/gamemodes/wizard/artefact.dm#L246

**Comment by KorPhaeron** [comment]
The get_candidates proc only checks

for(var/mob/dead/observer/G in player_list)

I have no idea how that would have happened.

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/ff8d782b09bca5e991688f5db10c685e5cbbbbe7/code/game/gamemodes/wizard/artefact.dm#L246

**Comment by astralenigma** [comment]
I have a good question what is a multiversal sword?

**Comment by francinum** [comment]
A recently added wizard items that summon "Clones" ~~that look nothing like you~~ to fight by your side.
In theory this would pull from the pool of observers, but that appears to not be the case.

**Comment by Jalleo** [comment]
This is the only case that its happened in.

**Comment by Supermichael777** [comment]
it draws from people the same way apprentice does so it can totally grab people. i once grabbed another wiz like that in the early days of raging mages. get_candidate(BE_WIZARD) just lists people with the preference on. i don't think it checks to see if your dead first which is the issue.

**Comment by KorPhaeron** [comment]
Supermichael777 it does, check the get_candidate proc in code/_HELPERS/game.dm

	for(var/mob/dead/observer/G in player_list)
			if(G.client != null)
				if(!(G.mind && G.mind.current && G.mind.current.stat != DEAD))

Not only does it only list ghosts, it then checks their mind to make sure their ghost is dead

**Comment by KorPhaeron** [comment]
@tkdrg 

This has not been reproduced in several months

**Comment by tkdrg** [comment]
Yeah, honestly I have no idea how this even happened. Guess I'll just close it, and reopen if it ever happens again.

**Comment by Jalleo** [comment]
Quite a good idea we will need people to watch out for it.
