### ISSUE TITLE
Recent maint remap broke powernets

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#10959]
http://i.imgur.com/DIAx64B.png

@Dorsisdwarf

**Comment by Boredone** [comment]
Incase it isn't noticed, assuming he didn't remove the disposal pipe in the screenshot for some reason, the disposal pipe is also missing there.

**Comment by xxalpha** [comment]
@Steelpoint if you can squeeze this in your PR.

**Comment by daman997** [comment]
this shit is so annoying

**Comment by Jordie0608** [comment]
Duplicate of #10863
