### ISSUE TITLE
Revenants can buckle people to chairs

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#10950]
Also annouces that they did it 

!spoooky!

**Comment by WJohn** [comment]
Totally a feature.

**Comment by Marflowerose** [comment]
They can also spin chairs, which is 100% 10/10 feature.

**Comment by Supermichael777** [comment]
well they are the head-spin soul eating poltergeist. maybe if they could animate and slowly move small objects(like heavy delay tk)

**Comment by Dorsisdwarf** [comment]
This is confirmed to be an actual feature, rather than an oversight, closing
