### ISSUE TITLE
AI detector in-hand sprite doesn't turn red

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10966]
If you don't know already, the AI detector is a multitool that turns red when you're in the AI's line of sight. The in-hand sprite doesn't turn red when you're holding it though.

**Comment by Firecage** [comment]
Do you mean if you hold it in your hand, the sprite on your mob that everyone will see doesn't turn red? If so, I believe thats fully intended.

**Comment by freerealestate** [comment]
Yeah, that's what I mean. I think it was an oversight when that item was
made, the creator forgot to edit the in-hand.

It doesn't make physical sense that the object's light would look different
to the person holding it than to passers-by. The sprite change still shows
up on examine. From a gameplay perspective, there's rarely a reason to hold
it anyway (you can always get a different multitool to hack with if you
think people might see it).

**Comment by Firecage** [comment]
It would make no sense though for a stealth item to instantly give you a way by holding it in your hands.

**Comment by phil235** [comment]
Intended for stealth purposes. Inhands rarely show a highly accurate image of items, the multitool inhands only have 3 pixels of green so I don't think this is a big deal.

**Comment by freerealestate** [comment]
It's not about the image being highly accurate. It's about the image being
wrong. "For stealth purposes" doesn't make sense when you can examine the
person holding the multitool and see that it's red, plus the fact that it
just doesn't make sense to show as green in the mob sprite when it's meant
to be red.

I doubt this was intended, I think it was an oversight.

**Comment by phil235** [comment]
If you really want it to be consistent, we could change the multitool ai detector to use an overlay instead of a red icon_state.

**Comment by Miauw62** [comment]
its still stealthy if you need to examine them to see its red. if it suddenly becomes red while walking its a pretty big giveaway.

**Comment by freerealestate** [comment]
It goes in pockets and toolbelts though, so you don't need to be holding it
to see it.

Just seems like a logical inconsistency to me. I had a look at the original
pull and there's no mention of the in-hands, so it seems like they were
forgotten about.

I can see the gameplay argument for keeping it as is, but it seems pretty
negligible when you won't need to hold it except when hacking.

Close this if you want, though.

**Comment by Dorsisdwarf** [comment]
[consistency issue[
[sprites]

**Comment by Anonus** [comment]
Hey look here have these sprites for red multitools that I never bothered to add.
http://puu.sh/jlpOW/21a45331f2.dmi

**Comment by Firecage** [comment]
I still say that this would ruin a stealth item, since it shouldn't just suddenly give you away by being on your mob. That would be like giving any other stealth items a huge "I am a traitor" sign when they are on your mob.

**Comment by freerealestate** [comment]
How often do you actually carry it, though? I usually keep mine in my
pocket, or in a toolbelt if I have one. If it turns red in your hand, and
you happen to be on one of the two angles where the three red pixels are
visible, you can either quickly hit E to store it or rotate your character
so it can't be seen. And you can always get a second multitool to use for
hacking instead, if you're going to be hacking out in the open where
someone who might report you for having an AI detector would see.

People are pretty myopic in this game, so they likely wouldn't notice or
realise what it meant anyway.

**Comment by Firecage** [comment]
Free, we can just aswell replace it with another non-stealth item then. Since it would litterally become useless if people can see it on our mob and we have to use a second multitool.

**Comment by freerealestate** [comment]
The only time you'd risk getting caught is: 1) You're hacking with it 2)
The AI is tracking you 3) You're facing a direction where the in-hand's 3
red pixels can be seen 4) You keep hacking instead of putting it away 5)
The AI knows the in-hand represnts a multitool 6) The AI notices the 3 red
pixels and 7) The AI knows what a red multitool means.

I don't know why you'd be hacking as a traitor with the AI watching anyway.
Just put away your multitool until it goes away, or carry a spare.

**Comment by Firecage** [comment]
Free. You are making it sound way more complex than it is. Its just simply like this:

Begin using the AI detecting multitool on anything that you can use it on, even if its a wire to check the power in powernet. AI just passes by, multitool turns red, people notice it, GG No RE.

As I said, if you want it to give you away that you are a traitor when you hold it on your hands, or instead take a second normal multitool to use. Then we can honestly just remove the AI detector or replace it with something else. Since then it both fails as a stealth item, and it fails in its purpose to act as a multitool.

**Comment by freerealestate** [comment]
I'm not saying that I want these things to happen, just that it's a
consistency issue and it would make sense for these things to happen.

I think you're overestimate the attention the average player gives to
in-hands, or how long most people spend holding a multitool in their hand
over the course of a round. The overlap between an AI tracking you and
multitool use would be really low.

Maybe instead of the multitool's entire screen turning red, the screen's
outline could just turn red instead. That wouldn't be visible on the
in-hand. Or maybe the multitool could just vibrate on AI detection, and
then vibrate again when the AI goes away, sending the player a message in
the chat and playing a sound only they can hear. The latter would make the
item even stealthier because it couldn't be meta'd by examining a player
holding it or dropping the item on the ground for the AI to look at.

**Comment by ReallyBigRock** [comment]
Really, is it that hard just to explain it with lore?
https://en.wikipedia.org/wiki/Virtual_retinal_display
It beams the red color into the eye of the person holding it. Only they can see the red. Stealth preserved.

**Comment by freerealestate** [comment]
That's a really silly overly elaborate explanation for a sprite mismatch
though

**Comment by Dorsisdwarf** [comment]
Not a bug, not vital, take it to ideas/feedback.

**Comment by freerealestate** [comment]
So we can't report sprite inconsistencies as bugs anymore? Other
inconsistent in-hand bugs have been accepted just fine.

Why are you blitzing all these issues?
