### ISSUE TITLE
Stimpack has little/no effect on stamina damage

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#10979]
This one really crushes me. I was hoping stimpacks would be my answer to STUN > EVERYTHING combat and at least give me brief windows of robustness. Adrenal implants suffer from similar issues, but can be even worse since its not terrible hard for someone with decent ping and reaction time to just reapply the stun and once they know you've got adrenals of some form they will apply stun baton to skull until you're down for the count. 

But I digress. Detective's revolver, disabler spraying, and the lack of fast movement is absolutely destroying traitorling for me. Sec wins the moment they get their stun whereas for the antag a stun is just the very beginning of defeating an opponent, you still need to either knock them out, disable their communications, reapply the stun or otherwise restrain them, don't be seen, don't be on camera, don't have your victim get spotted on suit sensors, but don't leave his shit lying around for scanning/arousing suspicion either, etc....

Err I digress. Shoving 25% of your TC's into your butt just to get slammed by the HoP/Detective/Etc. is just awful.

**Comment by Robustin** [comment]
Tested this further on Thunderdome. Confirmed my original statement. Stimpack is useless against stamina damage. It appears to help you regen stamina faster but getting up from a disabler and moving one tile every 3 seconds means that whoever put you down in the first place is going to have you eating dirt again before you can blink. The effect is pretty obvious when the det unloads his revolver into you, you'll still eat dirt for as long as a normal crewmember would.

Meanwhile adrenals which don't require advanced planning, have unlimited duration, multiple uses, completely hidden, etc. will clear 80% of your stamina damage immediately upon use.

**Comment by phil235** [comment]
I guess we can buff the stamina regen boost of stimulants.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
