### ISSUE TITLE
blobs can grow without needing to be conected

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#10976]
isolated blob parts can be grown of of by any blob even if no physical connection exists. this allows for ridiculous lines of blob to reach for emitters without worrying about getting cut off.

**Comment by WJohn** [comment]
This has been the case since blob got added, and I don't know if there's any easy fix without it doing some large calculations and checks to make sure if it's connected. Could be pretty laggy if you're trying to expand far away from your main blob once you've gotten huge.
