### ISSUE TITLE
space wind blows hard even in moderately depressurised areas

### ISSUE THREAD

**Issue by chimerasable** [tgstation/-tg-station#10987]
I don't ever recall space wind being this bad. I think someone got a little over zealous with thier cvars.

**Comment by xxalpha** [comment]
It's intended.

**Comment by Lumipharon** [comment]
Its not jsut depressurised areas.
Yesterday a rogue CE flooded plasma, and it took about 10 seconds to move PER TILE down the main corridors because space wind was busy fucking you in the ass.

Trying to get through airlocks on the side of the corridor was just bitterly frustrating.

**Comment by chimerasable** [comment]
Intended? Somebodies intentions suck. It's hard to drag things out of depressurizing areas, and the wind isn't constant it pulses.causing a problem where it can continue to smack people into hazards like electric grates.

 If you won't turn it down could you fix the pulsing push of the wind so it's constant and make it so it doesn't interfere with pulling? Or just turn it down a little bit please?

**Comment by Lumipharon** [comment]
As a juggernaut, if you smash a window and try move, you'll take 10 seconds or so jsut to get away from that tile.

A ripley drilled the floor under me as a jugg, and I was stuck there for well over a minute trying to escape.

**Comment by duncathan** [comment]
Feedback forum
