### ISSUE TITLE
Spacewind and lockers defeat drones

### ISSUE THREAD

**Issue by Midaychi** [tgstation/-tg-station#10985]
If a locker is pushed by space wind, it temporarily becomes an object for the purposes of drone's auto passing code. Thus, if you're a drone trying to shove a locker against space wind, you'll often phase right through the locker. This can be extra disadvantageous when combined with the code for 'launching yourself off of lockers', which can trigger at the same time if you're in space (Even if you're next to walls and grills or such)

End result: Drones have hard time pushing against space wind without phasing through locker, if they're in space this is doubly bad because then they'll end up getting launched  into space every which way and the locker getting launched the opposite direction, completely ignoring passing by any solid objects that would normally stop them.

**Comment by WJohn** [comment]
I'd call phasing through lockers when you always push them otherwise a bug.

**Comment by duncathan** [comment]
Fixed by #12469
