### ISSUE TITLE
code\game\machinery\doors\airlock.dm:984:warning: A: variable defined but not used

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10984]
Keep getting this warning when compiling after pulling from the latest version of master.

**Comment by xxalpha** [comment]
Update DM, check for unticked files, ask in coderbus.

Close this.

**Comment by freerealestate** [comment]
As I said, I pulled from the latest version of master and haven't touched
that file so I don't think it's on my end.

**Comment by xxalpha** [comment]
A PR is up to fix this. You don't need to open issues for compilation errors.

**Comment by freerealestate** [comment]
I think I do if they're unfixed bugs, though I wasn't aware it was already
known of and a fix was already up.

Still shouldn't be closed until the fix is pulled though.

**Comment by xxalpha** [comment]
Well you're wrong, this is not the first it has happened. These warnings get fixed eventually as every coder who works on an updated version will know about it. The issue tracker is not necessary for this kind of thing.

**Comment by freerealestate** [comment]
tbh i'm still going to report compilation errors if i find them unless i
know a fix is already up

bugs is bugs, regardless of how many people know about them
