### ISSUE TITLE
Clumsiness shooting you in the foot doesn't actually target the foot

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#10996]
>You shoot yourself in the foot with the laser gun!
>Clown is hit by a laser in the chest!

**Comment by Firecage** [comment]
Know the sad thing? Feet and hands aren't targettable and seperately damageable areas anymore :(

**Comment by phil235** [comment]
But legs are targettable

**Comment by freerealestate** [comment]
Yeah, leg would do.
