### ISSUE TITLE
Pouring radium on the floor yields scoopable uranium

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#10998]
I guess this was the remnants of some old chempiles thing that didn't get followed through with, but if you take radium and splash it on the ground and scoop up the green goop on the floor with a beaker (like how you would get ash), you get back liquid uranium. Since this lets you get roundstart nukacola and EMP's without grinding uranium ore, I think this would count as unintentional and bad

Edit: Oh and it can be made for mute toxin too

**Comment by SconesC** [comment]
@Iamgoofball
