### ISSUE TITLE
Troll Reduction is Bioware. Metatype Reduction is Cyberware

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#11007]
Pg 108 is Troll Reduction increases Charisma cap per rating. Orcs can only take Troll Reduction 1. Trolls can take rating 2.

Pg 73 is Metatype Reduction which can be taken by orcs and trolls and increases charisma cap by 1.

Instead you guys made Metatype Reduction: Orcs and metatype Reduction: Trolls which isn't a thing.

RAW youcan have both as Metatype Reduction only lists it can't be combined with metatype Poseur

**Comment by Miauw62** [comment]
n i c e m e m e

**Comment by Kromgar** [comment]
Whoops wrong github
