### ISSUE TITLE
Drones can use multiverse swords

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#11004]
While amusing this is probably bad, as it makes a human and not a drone.

**Comment by RemieRichards** [comment]
Multiverse sword
Alternate versions of the wielder from different universes
Those versions are humans

Feature! :P

**Comment by GunHog** [comment]
RR's personal tag is basically an index of the funnies and worst issues in the repo! Maybe if drone users had a chance to make sydrones instead of regular drones...

**Comment by tkdrg** [comment]
What RR said, not a bug. This is a silly wizard item with appropriately silly effects.
