### ISSUE TITLE
Temperature gun

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#11017]
Double e-swords do not deflect the shots from temperature guns, not sure if this is a mistake or just over looked, but a temperature gun shoots out /bolts/ of temperature, not balls of gas that change the temperature.

Was a traitor and got killed by a sec officer with a temperature gun by shooting cold shots, while I was wielding a double energy sword

>Was also told it maybe a bug so I brought it here, if it isn't then don't slap me ;-;

**Comment by SconesC** [comment]
>he got killed by a temp gun

**Comment by PKPenguin321** [comment]
how did you get killed by a temp gun

**Comment by phil235** [comment]
That's because you can only deflect projectiles that are child of either projectile/energy or projectile/beam (https://github.com/tgstation/-tg-station/blob/a825eb02e85de7ef4fc5c1807c1f84c2ec6ab99e/code/modules/mob/living/carbon/human/human_defense.dm#L45).
 Temperature gun projectile is obj/item/projectile/temp

**Comment by Firecage** [comment]
....How the fuck did you get killed by a temperature gun.

**Comment by Marflowerose** [comment]
I think we need a new gittag for this momentous occasion, or at least a spam of all the colorful ones. Are you sure you weren't nude in space while someone happened to be shooting a temperature gun at your general direction and died to the exposure rather than temperature gun?

**Comment by Stickymayhem** [comment]
>Trying to reflect the laws of thermodynamics
>Wanting to nerf the literal weakest ranged weapon in the game.

Oh my god Sirnat any shreds of doubt I had about treating you like shit have completely evaporated

**Comment by Ausops** [comment]
>OOC: Marflow: I've seen several Restart votes go through but never even heard of death caused by temperature gun

**Comment by sirnat** [comment]
Im so confused, should I take that as a compliment sticky? xD

**Comment by sirnat** [comment]
I didnt die from the gun its self, I died from being shot with it/slowed down and outright fucked by a baton. But I still had the e-sword deployed and held.     But the gun is the reason I was fucked/killed

**Comment by Lumipharon** [comment]
World first.
Temp gun confirmed new meta.

**Comment by Summoners** [comment]
Tempgun is blocked by a dual esword, I tested it. I have no idea how you even died to it, it hardly even slows you. I had to have two temp guns and have two rechargers and I emptied at-least  7 full clips to even down the guy.

Also it's almost impossible to hit anyone with a dual esword with the temp gun, it's blockrate is extreme.

**Comment by sirnat** [comment]
I had the dual e-sword deployed, it didnt block any of the cold shots the guy sent toward me

**Comment by Summoners** [comment]
@sirnat I just tested it on both servers, about 90% of the shots were blocked. It never deflected, only blocked.

**Comment by sirnat** [comment]
Hm.. Wierd, all of his shots hit, okay well I guess this can be closed then? Sorry if it was a waste of time

**Comment by Marflowerose** [comment]
Was it actually a disabler? I'm not sure if they penetrate the blocking, that could be it, they do stamina damage which slows you and eventually puts you on the ground.

**Comment by TheVekter** [comment]
HE -DIED TO A TEMP GUN-

**Comment by PKPenguin321** [comment]
reminder that this guy died to a temp gun

**Comment by Iamgoofball** [comment]
# HOW DO YOU DIE TO THE MOST USELESS GUN IN THE GAME

**Comment by TheVekter** [comment]
HE  DIED  TO  A  TEMP  GUN

**Comment by Dorsisdwarf** [comment]
Closed by request, get good, etcetera

**Comment by PKPenguin321** [comment]
never forget

**Comment by duncathan** [comment]
;_;7

**Comment by Iamgoofball** [comment]
press ;_;7 to pay respects

**Comment by PKPenguin321** [comment]
;_;7

**Comment by PKPenguin321** [comment]
about six days ago was the one year anniversary of theonly time somebody died to a temp gun never forget o7

**Comment by Iamgoofball** [comment]
F

**Comment by francinum** [comment]
Never 4get

**Comment by Iamgoofball** [comment]
8/11

**Comment by Marflowerose** [comment]
;_;7

**Comment by yackemflam** [comment]
;_;7

**Comment by sirnat** [comment]
F-Fuck you guys xD

**Comment by optimumtact** [comment]
literally died to a temp gun

**Comment by PKPenguin321** [comment]
Really makes you think

**Comment by Militaires** [comment]
new year new temp gun

**Comment by Marflowerose** [comment]
Member to pray respects to temp gun death on easter ;_;7

**Comment by PKPenguin321** [comment]
Will temp gun ever be not useless

**Comment by duncathan** [comment]
at this point it's best that we never let it be useful

**Comment by kevinz000** [comment]
temp gun is my carry weapon as security now

**Comment by Stickymayhem** [comment]
Same

**Comment by sirnat** [comment]
The headmin to remove the tempgun gets my vote.

**Comment by Shadowlight213** [comment]
Tfw you add temp gun to sec a joke and its actually useful.
Did not see that coming tbh.

**Comment by Marflowerose** [comment]
Christmas is the time to spend with loved ones and to remember the sacrifice baby sirnat made for us, never forgetti that he died to a temp gun for our sins.

**Comment by Armhulen** [comment]
:)

**Comment by sirnat** [comment]
Im so happy you all still remember my downfall. :(

**Comment by optimumtact** [comment]
guys this guy died in 2015 to a temp gun

**Comment by ike709** [comment]
new year new temp gun

**Comment by Bawhoppen** [comment]
![happynewtempgun](https://user-images.githubusercontent.com/6510293/34669268-705ae1d0-f436-11e7-88cd-cc650e1ab9bd.png)

**Comment by sirnat** [comment]
That is my new forum profile picture.

**Comment by kevinz000** [comment]
lmao

**Comment by duncathan** [comment]
good times

**Comment by The-Driker** [comment]
Imsxz was also recently killed with a temp gun. I feel like we should consider this a gift going into 2019.

**Comment by optimumtact** [comment]
yo he died in 2015 to a temp gun

**Comment by Anonmare** [comment]
HE 
DIED
TO
A
TEMPGUN
:rofl:

**Comment by nicbn** [comment]
Hm
 Looks like temp gun needs a nerf

**Comment by PKPenguin321** [comment]
❄️ 🔫

**Comment by Bawhoppen** [comment]
We need to do a quick port of https://github.com/AnimusWhite/NTstation13/pull/14 for good measure.

**Comment by sirnat** [comment]
We're almost there boys for the 4 year anniversary!

**Comment by Bawhoppen** [comment]
As a decade of chaos, fear, and division, yet also progress, strength, and devotion, finally draws to a close... I think we can take a step back and look at one common thing which united us all in a common bond: the temperature gun. 
High hopes for the new decade everyone! :tada:

**Comment by sirnat** [comment]
Ahh I love ol TG I hope you all had a good 2019.

**Comment by Anonmare** [comment]
Yo is this the dude who ded to a temp gun on stream?

**Comment by The-Driker** [comment]
I welcome the new decade of the temp gun.

**Comment by loserXD** [comment]
he died

**Comment by notfrying1pans** [comment]
hey its 2021 time for a yearly reminder that you died to a temp gun

**Comment by duncathan** [comment]
he really did die to a temp gun huh

**Comment by sirnat** [comment]
It be 2021, and I still have nightmares about dying to a temp gun in ss13

**Comment by optimumtact** [comment]
o7

**Comment by LemonInTheDark** [comment]
Subscribed

**Comment by Kylerace** [comment]
astonishing

**Comment by PKPenguin321** [comment]
unbelievable... all the gun does is lower your temperature by like 1 degree per shot bro... you died to that fr❓❗

**Comment by optimumtact** [comment]
it slows you down

**Comment by Iamgoofball** [comment]
died to a temp gun in 2015, RIP

**Comment by Anonmare** [comment]
I have only returned purely to ask: Did you really die to a temp gun?

**Comment by Iamgoofball** [comment]
they did, ya

**Comment by sirnat** [comment]
I died bc the temp gun slowed me down massively when i had a double e sword out and it was supposed to block 100 energy projectiles. 

I was a retard back when i played then.

**Comment by Bawhoppen** [comment]
https://github.com/tgstation/tgstation/pull/59949

**Comment by Fikou** [comment]
he died to a temp gun

**Comment by MrDoomBringer** [comment]
this guy's health variable somehow got set to 0 after someone used the temp gun on the same server as him, what an odd bug - wonder what the interactions at play here are

**Comment by Shadowflame909** [comment]
Dont use the temp gun in space bro. Nukies will fear

**Comment by Rhials** [comment]
Unironically died to a temp gun

**Comment by notfrying1pans** [comment]
It's 2022 tomorrow, remember that this person died to a temp gun

**Comment by Mothblocks** [comment]
greetings from 2022! this guy died to a temp gun

**Comment by Iamgoofball** [comment]
i come back to this issue every year to think of the before times when someone died to a temp gun in ss13

**Comment by nicbn** [comment]
Once again blessed by the e-mail notification for the issue about a guy dying to a temp gun seven years ago

**Comment by Lumipharon** [comment]
![index](https://user-images.githubusercontent.com/7869430/153112400-3149adc2-6504-4d0b-9fd1-1c75d1cd1608.jpg)

**Comment by PKPenguin321** [comment]
take me back. take me back

**Comment by notfrying1pans** [comment]
Lol

**Comment by duncathan** [comment]
oh my god it's been 7 years

**Comment by TheBonded** [comment]
amazing

**Comment by anclandor** [comment]
With thermal pistols I foresee many people falling to a tempgun in 2022.  EVEN IF THEY HAVE DESWORDS.  Massive bug abuse.

**Comment by Stickymayhem** [comment]
This is just a list of the boomers now isn't it

**Comment by Bawhoppen** [comment]
@Stickymayhem 
> This is just a list of the boomers now isn't it

Yes
I 'member it like it was yesterday

**Comment by sirnat** [comment]
I remember this day, like it was yesterday.. The day I raged when dying to a temp gun.. With a desword.. Now I hardly even touch ss13.. I love our reunions every year.

**Comment by Spc-Dragonfruits** [comment]
This is part of SS13 history

**Comment by duncathan** [comment]
@sirnat thanks again for bringing us together like this.

**Comment by Mothblocks** [comment]
he died to a temp gun

**Comment by sirnat** [comment]
I'm so happy this comes back around every few years

**Comment by sirnat** [comment]
You lot were some fun ppl to game with. 2015 was the year I graduated high school. Hope all your lives have been going good.

**Comment by anclandor** [comment]
We really need to get around to nerfing the temp gun, I mean its been eight years since this guy was killed by one and STILL no change!

**Comment by Moonlit2000** [comment]
This guy was killed by a tempgun twelve years after the game was made. If we don't nerf it, we could get a second tempgun death in just four years!

**Comment by sirnat** [comment]
I haven't played ss13 in awhile but i remember being such an annoying fucker my notes list was long even though, I almost made it to the staff team on a few occasions I'm glad to have had the memory of this with you lot. @Iamgoofball and @Stickymayhem you two were some of who I saw as decent acquaintances even tho I annoyed tf outta sticky. Hope you guys are doing well if you want to get in touch with me I can get you guys a few ways to connect

**Comment by PKPenguin321** [comment]
@sirnat skill issue

**Comment by duncathan** [comment]
thanks again for intermittent joy i receive seeing this issue appear in my github notifications <3

**Comment by rageguy505** [comment]
you can block tempgun shots now :(

**Comment by notfrying1pans** [comment]
heres to another new year

**Comment by sirnat** [comment]
Here's to the year 2024 the year of blocking temp gun beams

**Comment by anclandor** [comment]
SO happy this horrible bug has been fixed.

**Comment by optimumtact** [comment]
it's only funny if you comment on the anniversary please tone it down.
