### ISSUE TITLE
Fire burns out nearly instantly in fastmos

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#11019]
Combined with the changes to firestacks putting themselves out/diminishing on transfer, fires are often not very deadly at all. 

If someone call tell me where the formula for burning/consuming plasma in the air is I can try to change it myself.

**Comment by Marflowerose** [comment]
It's probably a bit faster but most of the time people who flood plasma forget to add any oxygen to the mix so during plasma flood fire, there's only 20~kPa of oxygen per tile, optimal fire mix is something along the lines of 33% oxygen and 66% plasma so badly done plasma flood will yeld fast fart of a fire. It still leaves the rooms hot which is the proper killer. Though you're probably right, fastmos has some issues, one of them being the mysterious effects during burning.

**Comment by Cebasiz** [comment]
yeah unfortunately station oxygen is very low so it quickly converts o2 to co2

instead of changing that i'd just make body fire do more damage. it should probably be deadlier, though in general i don't think plasma fire is weak by any means. it's effects of heating the station to absurd temperature and/or cooling it (due to all the hull breaches it creates) are still dangerous to anyone who can't make it into EVA.

**Comment by MrStonedOne** [comment]
before you judge this, try looking at the amount of actual plasma and o2 in a tile pre-fire. some times, people setup floods but don't properly disable vent pressure checks, meaning they just put a little in the room to bring it back up to 101kpa, and this spreads around a bit more.

One thing I changed was the sleeping levels for turfs with close to, but not exact amounts of air, so plasma can get spread thinner than it used to be able to. (it can actually spread so thin it stops being visible/lightable/breathable, but only in large low/no pressure environments using small amounts of plasma).

**Comment by optimumtact** [comment]
This is probably really due to the fact that the only fuel fires have is atmos stuff, whereas in real life the room and things in it would provide fuel.

**Comment by WJohn** [comment]
Flammable wood floors and carpets when?

**Comment by KorPhaeron** [comment]
@optimumtact 

Yeah, but it'd be an easier fix to just make gas burn longer than to try and write an entire new system where it consumes objects for fuel.

**Comment by optimumtact** [comment]
We don't do easy fixes, we do it properly

**Comment by Cebasiz** [comment]
i don't think it matters technically if there's fuel or not, the fuel in this case is probably the plasma, which often is still in the air by the end of the burn; you can't really compare a space station's environment with an earthlike atmosphere; in an earthlike there's almost always more air, so the limit is fuel (or, at least, the ability for the fire to draw more oxygen) in a space station you can probably pile up thousands of pieces of paper and set it on fire, and it still may go out; regardless if there's still things to burn, there is no oxygen and thus the fire suffocates.

or am i wrong

**Comment by as334** [comment]
Here's the issue with changing gas burn rates. If you decrease how quickly gases and fire in general burn, then you create issues with bombs as well, as those rely on a lot of fire action happening within 4 ticks of fire, which means that nerfing how quickly it burns away, will be an overall nerf to toxins.

**Comment by Cebasiz** [comment]
if anything were to be changed without redoing the whole system i'd guess it would be the motes of oxygen it takes to sustain fire for 1 second (or tick) of sustained tile file. i don't think that would noticeably impact bomb destructiveness.. would it?

**Comment by as334** [comment]
uh, amount of oxygen burned? It might not effect bombs _super_ heavily, but it would mean that most of the better mixes would have to be reworked. A lot of the stuff inside the fire calculations, while it appears to make more sense is connected, so there's no good way to touch the system without changing a lot. I think the easiest way to make fires last longer while keeping the effectiveness is to cut burn rate in half, but double energy released, that balances out the energy output per tick of fire.
