### ISSUE TITLE
Can't emag MMI's

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#11014]
To unlock an MMI, you need to use your ID on it (with robotics access).
This allows you to remove the brain, for whatever purpose.

I would expect the emag would let you do the same thing, but when I deborged a fellow traitor and put his brain into some random chef I kidnapped, I found the emag didn't unlock it.

I had to ask the admins to lend a hand.

This seem unintended, since the emag unlocks everything else that uses an ID check, that I can think of.

**Comment by Aranclanos** [comment]
why do they even have ID locks
