### ISSUE TITLE
You can still hit and punch people while strapped down to beds or nests.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11012]
Furthermore, if you're strapped down while holding an item, you can still use that item. This is fine enough for regular beds, but shouldn't happen for xeno nests (and should drop the held items). It also breaks the pixel offset when this happens.

**Comment by PKPenguin321** [comment]
this is what enabled self surgery and as far as i know is intended

**Comment by WJohn** [comment]
True, although this was meant to be combined with the "you can punch and KO xenos" issue. This lets you potentially kill a larva or something when you really shouldn't be able to.

**Comment by advomach** [comment]
Realistically if an opportunity presented itself someone would be able to kill a larva even if they were strapped to a xeno nest if the larva isn't careful.

And then there's the movies where someone is entrapped but they're hiding a gun, trying to aim it and waiting for the right opportunity to use it.

Not a bug
