### ISSUE TITLE
Recent update broke cyborg interface.

### ISSUE THREAD

**Issue by Artist561** [tgstation/-tg-station#11026]
It appears that you currently cannot activate any cyborg module no matter what type of cyborg you are. I've tested it with engineering borgs and security borgs.

**Comment by Shad0vvs** [comment]
To clarify, You cannot click to change your module.

**Comment by RemieRichards** [comment]
Ctrl+1, Ctrl+2, Ctrl+3 for non hotkey mode
1,2,3 for hotkey mode

But yes I'll fix clicking not doing it.
