### ISSUE TITLE
Mute sting doesn't always work

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#11035]
Had a player report that he tried to mute sting someone 3 times and it failed to work. No clue why.

**Comment by GunHog** [comment]
Was the Changeling player trying to sting through space or border objects?

**Comment by TheVekter** [comment]
Not that I'm aware of. Are other lings immune to mute sting?

**Comment by GunHog** [comment]
Changelings are immune to certain stings, yes.

**Comment by TheVekter** [comment]
That's probably what happened then.
