### ISSUE TITLE
orbit() has an out of place comment

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#11031]
orbit() has a comment above it that seems to talking about something else:

https://github.com/tgstation/-tg-station/blob/master/code/__HELPERS/unsorted.dm#L1400

not sure whats going on here.

**Comment by optimumtact** [comment]
The comment is for the previous proc which compares if two items are facing each other?

**Comment by RemieRichards** [comment]
@optimumtact yes, it is.
The thing is on the day MSO made this report he made a bunch of other pedantic reports.
I'm not sure whether it was annoy me or if he personally was just ticked off that day.

**Comment by optimumtact** [comment]
weird
