### ISSUE TITLE
Dominator beeping is really loud

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11040]
Like, it's painfully loud with sound at normal levels.

**Comment by Aloraydrel** [comment]
I believe its suppose to beep loudly to give away its position.

**Comment by Jalleo** [comment]
This is down to 3D sounds probably

**Comment by WJohn** [comment]
@Ikarrus

**Comment by Ikarrus** [comment]
It has to be loud because 3D sounds make the volume falloff very sharp. 

There are ways to get around it, but then it wouldn't be a 3D sound any more. 

Ideas to fix this would be appreciated if there are any, otherwise I'll chalk this up as "Will Not Fix"

**Comment by Anonus** [comment]
You could lower the volume a bit, to, say, slightly louder than syndicate bombs.
It's actually ear-piercing, that's not good at all.

**Comment by Ikarrus** [comment]
Ill look into it

**Comment by freerealestate** [comment]
/tg/station's sound volumes are generally pretty inconsistent. Someone should really lay them out from quietest to loudest, but I doubt it'll happen any time soon.

**Comment by RemieRichards** [comment]
@freerealestate you'll also have to list the playsound() calls for each of these sounds, as they often change them to 30%, 50% volume etc.
