### ISSUE TITLE
#10244 has become a serious balance issue

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#11053]
https://github.com/tgstation/-tg-station/pull/10244
@Ikarrus 

I don't know if this was really well thought out, but the ability to transfer all reagents from a container by throwing it has made Chemistry/Medbay as a whole a bit on the wildly overpowered side. 

A morphine bottle (Of which there are quite a few in Medbay at roundstart) will overdose you, among other things - In fact, most bottles can hold enough to overdose or kill. Throwing is somewhat hard to dodge and bypasses shields among other things. Phlog bottles have come into wide use simply because without calomel once the bottle makes contact, you are guaranteed to be husked by the fire.

You claimed it wasn't OP, but I think that was just the result of insufficient foresight. Nobody can really defend this considering it is a:
- Unblockable 
- Harder to dodge than a projectile
- A syringe gun+ that makes the guns totally obsolete

Bio protections will stop that, but they are so niche and Chemistry is so easy to use that I think it's barely a justification, and asking anyone who's had hostile contact with medical lately will tell you the same thing I've written here.

This is less a symptom of the chemicals and more just that they were never intended to have such easy application at a distance. Syringes are 15u as a matter of balance. Being able to apply things like a Krokodil overdose at range is far too good.

Reagent transfers on their own need a revert.

**Comment by Shapsy** [comment]
A bottle of phlog is ggnore even if whoever you throw it at has 3 people using a fire extinguisher on them together, and god knows how much awful shit you can get onto someone if you have a large beaker. Syringe guns are limited to 15u of space and can still be really deadly, being able to chuck 100u beakers of hellmix at people with no counter to them is way too robust

**Comment by WJohn** [comment]
Well for phlog it'd be nice if #10693 actually got merged so it finally got nerfed.

**Comment by Lumipharon** [comment]
If I remember correctly, if you throw specifically at something (ie: target a person instead of say, a tile behind them) then the throw insta hits (assuming a clear path- the animation is just for effect.

Could be wrong about that, but either way, yeah throwing containers is really fucking OP.

**Comment by PKPenguin321** [comment]
wait, morphine applies on touch *AND* ingestion? or are you throwing the beakers directly into their mouth?

**Comment by Cebasiz** [comment]
i picked a dual esword as traitor yesterday and got ggnored by a morphine bottle

which apparently bypasses my whirling deathblade

right into my face

thanks coders :^)

**Comment by phil235** [comment]
We need to change how reaction TOUCH are handled. Right now for reagents without a specific reaction_mob proc that uses TOUCH, the default reaction_mob with TOUCH calculates the mob's permeability protection and transfers a certain volume of the reagent into them depending on that protection.

**Comment by Shapsy** [comment]
can we please do something about phlog for the love of god, it ruins rounds because it's just "toss onto someone and watch as fire extinguishers, silver sulfadiazine, ointment and literally everything else in the game is powerless to save you"

Why did that PR that nerfed phlog not get merged?

**Comment by daman997** [comment]
fix it fix it fix it fix it fix it fix it fix it fix it fix it fix it

**Comment by PKPenguin321** [comment]
me and kevinz0 called it in the original PR, this shit's totally broken lol

why dont you guys ever listen

**Comment by SconesC** [comment]
Ikarrus was warned

**Comment by Shadowlight213** [comment]
Obviously just need to walk around with throw intent on all the time in case of flying ggnore.

**Comment by PKPenguin321** [comment]
can we make this have two high priority tags because it's used literally every single round both by antags and nonantags due to being so dominant, easy, and pretty much uncounterable

seriously this is shit and needs to just be outright reverted instead of tweaked, it's awful

**Comment by freerealestate** [comment]
could the reagents just spread outwards from the thrower across the tiles in front of them in an arc, dividing their content across each tile until used up? (i.e. similar to shotgun spread)
