### ISSUE TITLE
runtime error: Cannot read null.name

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#11050]
runtime error: Cannot read null.name
     proc name: announce head (/datum/job/proc/announce_head)
       source file: job.dm,176
       usr: Shiloh Sidower (/mob/living/carbon/human)
       src: /datum/job/hos (/datum/job/hos)
       call stack:
     /datum/job/hos (/datum/job/hos): announce head(null, /list (/list))

You get this error if you use the Populate World verb, or use Select equipment to dress a human as a head of staff role.

**Comment by phil235** [comment]
It's not just when using that verb, it's every time you spawn an interactive human.
