### ISSUE TITLE
The syndicate poison kit holds more bottles by default than its capacity

### ISSUE THREAD

**Issue by PatchouliKnowledge** [tgstation/-tg-station#11069]
Long story short, it comes with 12 bottles of various nasty stuff, but it can hold a maximum of 7. This means that if you take out some of the bottles, you won't be able to put them back in.

How to reproduce:
- be traitor
- order poison kit
- take out bottle
- try to put it back in
- ???
- goddammit

**Comment by WJohn** [comment]
Make it a special box that holds more, like the light replacement box. We have syndicate-looking boxes so you can get away with it.
