### ISSUE TITLE
Converted clown gangsters, cultists and revs are still clumsy

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11076]
I noticed this in a gang round trying to shoot and fucking up majorly. Then I went and checked the code. Gang bosses, starting cultists and revheads who are clowns "overcome their clownish nature" and can use weapons and shit; however, this never happens for converts. To me this seems inconsistent.

I'm not sure whether this is intentional, and whether this is a bug report or a feature request, but nevertheless it's here.

obligatory HONK

**Comment by Jalleo** [comment]
@Ikarrus

**Comment by RandomMarine** [comment]
Because syndies/cultists make their clowns take time to train to overcome their clumsy nature (Or just hook them up with some mutadone).

Obviously, converted NT clowns aren't going to have that, clean their SEs.

**Comment by Miauw62** [comment]
Yeah, I don't actually mind this.

**Comment by Cebasiz** [comment]
i don't know, i converted a clown called honky into my gang the other day and he became honky - the switchblade clown. he killed a few people with a banana peel and his knife.

i don't know if it's a huge deal really.

**Comment by Lumipharon** [comment]
It's intended - fix your genetics if not being able to shoot people is such a big issue for you.

**Comment by Dorsisdwarf** [comment]
Closed for month-old feature request
