### ISSUE TITLE
Bots Processing Concerns

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11072]
currently bots being removed from the bot SS is only done via the explode proc. While *most* of the time bots call this proc when destroyed----if they are deleted via other means (admin commands or otherwise), the bots will not be removed from bot processing.

Ideally, shouldn't bots being removed from the bot SS be done in bot/Destroy()?

**Comment by WJohn** [comment]
Bots turned into simple animals WHEN.

**Comment by MrStonedOne** [comment]
>Ideally, shouldn't bots being removed from the bot SS be done in bot/destroy()?

YES! everything should be using qdel, and letting destroy clear up references, never anywhere else.

**Comment by Fox-McCloud** [comment]
@WJohn that's what Baystation did.

@MrStonedOne 

Thanks; I thought so.

**Comment by GunHog** [comment]
Does qdel() call Destroy()?

**Comment by RemieRichards** [comment]
```Destroy()``` is essentially the ```Del()``` of ```Qdel()```, so yes.

**Comment by Fox-McCloud** [comment]
this was resolved.
