### ISSUE TITLE
Emitter beams stop next to field generators

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#11078]
We tried to start up the engine but the emitter beams literally just stopped next to the field generators never powering them. They seemed to collide with it or something.

The beams would stay for a while and then just disappear after a certain time or when they ran out of range or something.

Restarting the master controller did nothing

**Comment by Ausops** [comment]
New emitters placed down elsewhere also don't work.

The emitter beams seem to collide or at least stop when something is in the way but won't actually act on them, like not damaging a human.

**Comment by AnturK** [comment]
#11049 Probably ?

**Comment by phil235** [comment]
It's a runtime I think.
