### ISSUE TITLE
Explosions appear to be able to remove the suit jetpack from hardsuits and leave it existing after a explosion

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11083]
That's a suit inbuilt jetpack.
A device that will use your internals tank as a gas source for propulsion.
It is a bulky item.

result of a explosion.

**Comment by xxalpha** [comment]
How in the fuck

@Ikarrus

**Comment by Ikarrus** [comment]
I don't even know what a suit jetpack is.

**Comment by xxalpha** [comment]
You made shredding.

**Comment by xxalpha** [comment]
Why are hardsuits not immune to this shit

**Comment by Ikarrus** [comment]
When clothes get shredded they drop their contents first.

**Comment by Jalleo** [comment]
@ikarrus the suit jetpack is inside the rig suits e.g are one of their contents that isnt meant to be dropped.
