### ISSUE TITLE
AI cant cancel when they tey to call the shuttle

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11109]
Instead they have to close their client and come back on

**Comment by WJohn** [comment]
This has been intended since forever, hasn't it?

Also wait what? They can recall if they rejoin?

**Comment by bgobandit** [comment]
I think he means cancel the prompt

**Comment by WJohn** [comment]
Oh, I misread, I see.

**Comment by GunHog** [comment]
Easy fix, but you do not HAVE to relog, just enter an empty or too short message, and the call will be cancelled due to it not having a reason given.

**Comment by Cebasiz** [comment]
you can just enter an empty message and it will close and not call the shuttle.
