### ISSUE TITLE
The Orion Trail doesn't properly continue.

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/-tg-station#11114]
1. Play the first turn of Orion Trail.
2. Press continue,
3. Watch a blank screen.

It randomly fixed itself after deconstructing and reconstructing the arcade machine multiple times.

**Comment by phil235** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
FFS, I played it extensively and it worked fine.
This is what happens when PRs get left to rot, people pull the rug out from under you and break shit.
