### ISSUE TITLE
Ninja stealth is nonfunctional.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11115]
Attempting to stealth as a Ninja will do nothing but increase your energy drain.

**Comment by WJohn** [comment]
@RemieRichards

**Comment by Poojawa** [comment]
proc name: toggle stealth (/obj/item/clothing/suit/space/space_ninja/proc/toggle_stealth)
  source file: ninja_stealth.dm,18
  usr: Quick Michaelangelo (/mob/living/carbon/human)
  src: the ninja suit (/obj/item/clothing/suit/space/space_ninja)
  call stack:
the ninja suit (/obj/item/clothing/suit/space/space_ninja): toggle stealth()
the ninja suit (/obj/item/clothing/suit/space/space_ninja): Toggle Stealth()
runtime error: list index out of bounds
proc name: cancel stealth (/obj/item/clothing/suit/space/space_ninja/proc/cancel_stealth)
  source file: ninja_stealth.dm,30
  usr: Quick Michaelangelo (/mob/living/carbon/human)
  src: the ninja suit (/obj/item/clothing/suit/space/space_ninja)
  call stack:
the ninja suit (/obj/item/clothing/suit/space/space_ninja): cancel stealth()
the ninja suit (/obj/item/clothing/suit/space/space_ninja): ntick(Quick Michaelangelo (/mob/living/carbon/human))
runtime error: list index out of bounds

That's with #10835 fixes
