### ISSUE TITLE
Explosive implants appear to be fucked

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#11110]
Nuke ops are supposed to start with explosive implants by default.

Currently, they either don't have the implant at all, or at the very least, are missing the action button to use it.

As far as I can tell, it was https://github.com/tgstation/-tg-station/pull/10957 that caused the problem. @Jordie0608 

Also somewhat related, but the old explosive implants gibbed you once you died, regardless of you activating them or not.
The new microbombs, MUST be manually activated.

This makes it much easier for plebs to be looted as ops, since at the very least, with the old system, they'd explode after expiring.

**Comment by Jordie0608** [comment]
@Core0verload

**Comment by Core0verload** [comment]
Easy fix, will add to my surgical update 2.
