### ISSUE TITLE
Maps with roundstart heat exchange pipes cause runtimes.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11118]
Maps that have roundstart heat exchange pipes seem to cause runtime errors when the round starts. Happens both on my custom map and ministation but not on box.

The following errors occur many times when you start a round on ministation:

runtime error: Cannot read null.air
proc name: return air (/obj/machinery/atmospherics/pipe/return_air)
  source file: pipes.dm,29

runtime error: Cannot read null.temperature
proc name: process (/obj/machinery/atmospherics/pipe/simple/heat_exchanging/process)
  source file: he_pipes.dm,89

**Comment by phil235** [comment]
The second runtime is fixed.

**Comment by duncathan** [comment]
Hahahahha wow I thought this was new when I fixed it
Pinging myself to remind me to fix the first runtime here

@duncathan
