### ISSUE TITLE
Embedding doesn't work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11117]
You can throw as many spears as you want at someone, use a pneumatic cannon full of rods and glass shards, even throw throwing stars and ninja stars at people with 100% embed chance over and over and still never get them to stick in anyone.

@RemieRichards

**Comment by RemieRichards** [comment]
Not me, @phil235 touched throwing last, and it's entirely tied to throwing (including explosions)

**Comment by Core0verload** [comment]
Hope that's not me again, because i touched limbs and limbs are closely related to embedding.

**Comment by phil235** [comment]
found the error, just a silly typo.
