### ISSUE TITLE
Blob Cores can be killed by Bombs

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#11129]
You can make a maxcap in less than 10 minutes if you want to powergame it just have a suicide bomber run in and BOOOOOOOOOOM. Repeat 6 more times to win.

They didn't used to kill Blob Cores they used to survive the explosion but now the explosion can kill the core too

**Comment by RemieRichards** [comment]
Dupe.

**Comment by RemieRichards** [comment]
https://github.com/tgstation/-tg-station/issues/10199
