### ISSUE TITLE
Medibot may get stuck in heal mode

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11121]
I was killed, I deathwhispered and noticed later as a ghost that a medibot was constantly trying to heal me. I can't say at what point the medibot decided I should be healed but it seemed to be stuck there. It didn't say anything. It didn't actually inject anything but the needle animation was there.

**Comment by GunHog** [comment]
Not enough data. Please try to be more descriptive, I need steps to reproduce.

**Comment by Marflowerose** [comment]
Sorry, that's pretty much all the data I can give. The medibot was blinking with a syringe like it had a hardon but nobody to heal for quite some time. At the time I didn't pay much attention but I thought it might be useful to report anyway.
