### ISSUE TITLE
Welding tools from the autolathe start with welding fuel in them

### ISSUE THREAD

**Issue by bustygoku** [tgstation/-tg-station#11134]

**Comment by Marflowerose** [comment]
Lots of machines synthesize shit from energy, this isn't a bug or consistency issue and I don't see what it has to do with balance either.

**Comment by Jalleo** [comment]
This is a dupe old issue was closed

**Comment by GunHog** [comment]
I do not see why this is a problem.

**Comment by WJohn** [comment]
Well everyone usually pumps out more and more welding tools from the autolathe during blob, rather than risk bringing out a welding tank that can be used against them.

**Comment by Marflowerose** [comment]
Except that people always bring welderfuel tanks to blob and changing this to be inconsistent and having welders have no fuel would only result in some cargonian bringing a welderfuel tank next to autolathe and just filling them instantly after printing. Blob doesn't need any buffs, least of all ones that are just 100% inconvinience every time even when it's not blob round.

**Comment by xxalpha** [comment]
Stop, we already closed a bunch of issues like this. If you think this is worth an issue thread, code the change yourself.

**Comment by Jalleo** [comment]
@miauw62

**Comment by Iamgoofball** [comment]
this is intentional

**Comment by bustygoku** [comment]
>having welders have no fuel would only result in some cargonian bringing a welderfuel tank next to autolathe and just filling them instantly after printing.

good
