### ISSUE TITLE
Spacevine event does not spawn any vines.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11135]
According to the code, it's supposed to spawn spacevines in the hallways which doesn't actually happen. Doesn't seem to be a mapping issue either as it occurs on both box and meta.

**Comment by bgobandit** [comment]
feature

**Comment by WJohn** [comment]
You're not even trying with calling bugs features anymore, are you?

**Comment by bgobandit** [comment]
preventing kudzu from appearing and shitting up rounds = feature

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/15e50de0feb35850e348919d8f20cb63777fafc7/code/modules/events/spacevine.dm#L12
The issue is that turfs now have a light object in their content, so no turf has an empty content.
