### ISSUE TITLE
Flip coin progress bar

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11136]
Flipping coin and quickly throwing it or placing it in a bag shows progress bar on the coin.

**Comment by WJohn** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
this is fucking hillarious

i refuse to fix this because it's hillarious

unless the progbar isn't disappearing in which case there is a problem

**Comment by Marflowerose** [comment]
The bar does disappear, though it also spins when you throw the coin fast, which is doubly honky.
