### ISSUE TITLE
Mediborg hypospray

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#11145]
The mediborg hypospray currently only recharges when the module is ACTIVE and only for the CURRENT set to chemical. 
This would mean if you used each chemical, you would have to cycle though them each and wait to get them to recharge.

I thought this was intended until I asked scones....

**Comment by Cebasiz** [comment]
oh, yeah. i was going to make an issue of this a while ago and then forgot

yes that is how it works, yes it's annoying fix pls

**Comment by Shad0vvs** [comment]
@SconesC You told me you would fix this. ;_;
