### ISSUE TITLE
Strange Objects can be too powerful

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11151]
A janitor having one can easily lock down areas the cool down between each use for the objects should be increased it is way too fast currently

**Comment by Boredone** [comment]
I believe the cooldown is currently randomized on every strange object?
Its like, a minute to five minutes possible cooldown I think?
Assuming 60 ticks=60 seconds anyway which could be wrong pretty easily.

**Comment by Supermichael777** [comment]
60 ticks is not even close to that long
thats like 20 seconds

**Comment by Dorsisdwarf** [comment]
a delay of 60 in the code is six seconds. BYOND works on tenths of a second.

**Comment by Dorsisdwarf** [comment]
a delay of 60 in the code is a delay of 6 seconds.

**Comment by Miauw62** [comment]
we run at 11 fps, so one tick is aproximately 0.09 seconds.
some objects use world.time for cooldown, dorsi.

**Comment by Alek2ander** [comment]
I think the easiest solution is ID-locking the experimentor so non-scientists have a harder time getting discovered objects

**Comment by Jalleo** [comment]
that wont solve it Alek2ander people would just ask the AI to discover it then.

**Comment by Dorsisdwarf** [comment]
I think "Strange objects can be strong if a certain job with no access gets hold of a certain random object" is Feedback Forum material. Sorry.
