### ISSUE TITLE
Balance Suggestion: Captain's Spacesuit Slowdown

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11150]
May not be the right place for this, and it may belong on the forums, but. Just a suggestion:

remove the slowdown from Captain's spacesuit

Captain is the highest risk job on the station, with literally every traitor potentially gunning for your butt+your stuff (medal, disk, gun, and all access). 

Just as a recommendation: remove the slowdown from the Captain's space suit: this solidly puts it in the category of "best overall armor" to compensate for the increased risk of the job; currently wearing the space helmet is the "best" helmet in the game, armor wise, with no downsides (and then some, with its built in flash+welding protection)--it would seem logical that the space suit armor fall in the same category.

**Comment by PKPenguin321** [comment]
f e e d b a c k 
f o r u m
b o y s

**Comment by GunHog** [comment]
I support this, even though I do not play Captain. He is <b>THE BOSS</b> with the keys to the station AND the nuke. He is a bigger target than even the HoS, and that is saying something. :+1:

As for the helmet, you could go the Paprika route and make the spacesuit a hardsuit variant, so he can only have the helmet on with the suit.

**Comment by Miauw62** [comment]
pls no more feature request
