### ISSUE TITLE
Experimentor can freeze up

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11160]
Its like the old exofab bug where if two people interact at the same time the device crashes. Its that or the other person did something to the strange object as it was loaded or something

**Comment by Miauw62** [comment]
in this case the strange object disappeared and the experimentor was stuck with busy = 1
@sawu-tg

**Comment by Jalleo** [comment]
@GunHog

**Comment by sawu-tg** [comment]
@Miauw62 @GunHog 's problem, not mine. He handles this now.

**Comment by GunHog** [comment]
*Gun Hog begins to cry.*
