### ISSUE TITLE
Burping when stunned?

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#11165]
So, apparently you burp now when stunned with a taser.

Zoey Webb slurs, "Myy th'eeeft isss  foil'ed *BURP*..."

**Comment by GunHog** [comment]
That is the DRUNK state. Tasers make you drunk, then.

**Comment by Dorsisdwarf** [comment]
Tasers are supposed to make you S-ss-st-tutter , not Schsshcll-uuur

**Comment by CosmicScientist** [comment]
Somewhat a duplicate of:
#8189 "You use slur filter when stunned instead of stutter filter"
If not for the lack of context in that old issue and the label that it can't be reproduced.

**Comment by SconesC** [comment]
They've made your slur for ages but I've never seen a burp

**Comment by CosmicScientist** [comment]
@SconesC it does happen.
