### ISSUE TITLE
Topping off CO2 jetpack with N20 broke the jetpack

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#11169]
I haven't been able to replicate this yet but I had a very frustrating round ruined because of this. I was flying around with a co2 jetpack mostly filled with oxygen... I was getting around high 300's in kPA so I flew over to the remains of the execution chamber and topped off my jetpack to max pressure with n20.

Jetpack immediately stopped working. Dropping the jetpack, messing with the valves/pressure, toggling it on and off 1,000 times, messing with the right click menu/stabilization options... nothing worked, I could not get anything to get my jetpack flying again, I confirmed multiple times as I floated along that my jetpack was at max pressure, etc.

**Comment by RemieRichards** [comment]
@Robustin Just to clarify, is this that the jetpack would not turn on when you had mixed gases in it, or that it wouldn't provide thrust as you move with mixed gases?

**Comment by Jalleo** [comment]
wont provide thrust.

**Comment by Robustin** [comment]
It would turn on/off but 0 thrust

**Comment by RemieRichards** [comment]
Was it entirely n2o? because n2o doesn't count for jetpacks, no trace gases (a code thing) are considered, the code actually has a comment, "//fuck trace gases	-Pete"

**Comment by Miauw62** [comment]
i think pete commented //fuck trace gases because trace gases are awful and not even used.

**Comment by RemieRichards** [comment]
@Miauw62 n2o is a trace gas, so they're "used" but there's literally only 1 in the whole trace gas "system"

**Comment by Miauw62** [comment]
yeah thats what i mean by "arent used"

i think we also have agent b and shit in the code.

**Comment by Jalleo** [comment]
It wasnt fully N20

Quote from report "I was getting around high 300's in kPA so I flew over to the remains of the execution chamber and topped off my jetpack to max pressure with n20"

It still had some oxygen in it.

**Comment by RemieRichards** [comment]
Not enough oxygen then.

**Comment by Dorsisdwarf** [comment]
Its a bug because there was *enough* oxygen to fly around before, but as soon as he put N2O into it, it stopped working

**Comment by Robustin** [comment]
Yea there's no way 300kPA of CO2+pure oxygen would run out the instant I shoved 700kPA of N20 into it

**Comment by duncathan** [comment]
Really tho trace gases are fucking garbage
