### ISSUE TITLE
Box: Incinirator camera is not connected to anything

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11170]
This is the camera monitor by the turbine.

**Comment by Chocobro** [comment]
pretty sure there isn't a camera there - could have been built by a player. do you have any more detailed info?

**Comment by Jalleo** [comment]
Its got a camera monitor there no camera.

**Comment by WJohn** [comment]
Oh the camera monitor to the right of the computer. I somehow never noticed that.

**Comment by Jalleo** [comment]
Yeah i have my title incorrectly worded probably.
