### ISSUE TITLE
pumps secured to untiled floor dont show a pipe just the pump element.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11174]
doesn't affect  pipe performance far as i can tell. visual glitch.

**Comment by WJohn** [comment]
Still? I swear we fixed this.

**Comment by duncathan** [comment]
This isn't actually a bug. Intended behavior is that when you crowbar up a tile, lay a component (any component, not just pumps,) and lay the tile back down, the pipe is not shown. Look at vents and scrubbers; that's what this is for. 
There just isn't any handling for when you leave the floor untiled. This should be easy to fix. I'd put a PR up now, but I'm currently updating to Windows 10. Expect a fix sometime today.
