### ISSUE TITLE
Object hitting and gun firing stat gathering doesn't use the object's real name

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11184]
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](http://puu.sh/jAeuV/07c14101cd.png)
This is a picture of the name of a gun someone fired!

**Comment by Iamgoofball** [comment]
uh oh
