### ISSUE TITLE
I ded plz nerf: Burn/Brute Patches Edition

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#11197]
So since I came back and got to experience the joys (tm) of Goofchem, I was told the change was necessary to end the days of people running around with 30 minutes of superheal mix in their blood under trekchem.

So imagine my surprise when I got to experience this today:

Oldman Robustin has stunned Melody Shrew with the stunbaton!
Oldman Robustin has beaten Melody Shrew in the head with the stunbaton!
You put the stunbaton into the industrial satchel.
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!
You fire the energy gun!
Melody Shrew is hit by a laser in the head!

About 20 seconds later Melody gets up stuns, and kills me. She was wearing a sec hardsuit but had residual burn patch chems in her system. Earlier that same round she was also space walking in a winter coat and engaged me in open space combat for 2 minutes without going down.

I assumed she was a ling, got told no. Then I assumed she had sat in chemistry for several minutes putting together some insane healmix, got told no. Turns out it was just plain old healing patches, the kind that are instant to apply, instant to heal, and apparently continue to heal you for a few minutes too. 

The two big issues here are:

1) Why did we fuck up the entire chem system if we still have fleshmend-in-a-pocket (actually they heal way faster than fleshmend but I digress). 

2) Why does an instant heal also continue to give large amount of healing after usage?

**Comment by PKPenguin321** [comment]
as much as i agree,
F E E D B A C K
F O R U M
B O Y S

**Comment by bustygoku** [comment]
lmao did u actual believe when goofball said he was trying to make the med system less bullshit?

**Comment by Cebasiz** [comment]
>goof
>fulfilling his promises
>designing things
>being handed almost total control over an entire system with no real coder or player oversight
>a good idea

??????????????

**Comment by PKPenguin321** [comment]
no he had oversight, oversight that said goofchem won't be reverted because "muh kneejerks" :^)

**Comment by SconesC** [comment]
You barely put her into crit (By like 10 hp) so it's not like they healed a fuckton

It's an issue with the metab rate of the chems

**Comment by Aranclanos** [comment]
third time I have to tell you this, use the feedback forums for this.

**Comment by phil235** [comment]
I'm pretty sure damage to the head is capped at 75, just like legs and arms, so the issue is also with that.

**Comment by PKPenguin321** [comment]
no phil, head has 200 damage cap just like torso as intended
