### ISSUE TITLE
Electrified grilles don't seem to be working

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#11192]
I've noticed two instances today in two separate rounds where people have hit what are supposed to be electrified grilles without protection and not been shocked.

**Comment by SconesC** [comment]
Any grilles and on what map?

Newly made ones?

**Comment by freerealestate** [comment]
A Boxstation warden office grille and a Boxstation cell grille.

**Comment by freerealestate** [comment]
Oh, and no, they were there from roundstart. There weren't any power
failures either, the areas were fully powered.

**Comment by francinum** [comment]
What were they using to break it?

**Comment by Jalleo** [comment]
There is a known bug withing the powerner or master controller with the smes it could be linked to this but highly unlikely. @mrstonedone

**Comment by Robustin** [comment]
Did the grilles have knots under them?

I set a shockwall during a xeno invasion just an hour ago and the grilles did their job just fine with a PACMAN as the power source.

**Comment by freerealestate** [comment]
@francinum they were kicking them

@Robustin Yup, they were roundstart electrified grilles.

Only experienced this issue with brig grilles, so might be an issue with brig wiring?

**Comment by phil235** [comment]
Intended in the code, hitting an electrified grille has a 70% chance of shocking you.
