### ISSUE TITLE
Cyborgs pulled object movement is broken.

### ISSUE THREAD

**Issue by Falamazeer** [tgstation/-tg-station#11199]
Problem Description: Even with no items selected I cannot shift dragged items or prisoners as a cyborg, I was on the shuttle trying to move someone into an empty chair by clicking the desired tile, typically as a normal human, when dragging something clicking a tile will shift the dragged item, IE that trick people use to spam slip people on banana peels.

What did you expect to happen: I expected the dragged cuffed carbon life form to occupy the square I wanted him to occupy, I could not simply walk through the correct area as all other chairs were occupied, preventing me from walking the path I would need to to get past.

What happened instead: they did not move at all, I tried multiple times first making sure I had no item selected, then tried with one of my modules empty and selected, I could in no way shift the dragged human except through dragging

Why is this bad/What are the consequences: Innumerable, Can't shift items around means you could easily trap yourself with your dragged item by accident.

Steps to reproduce the problem:Drag an item, click a tile that touches the tile that the item already occupies, works for humans, not for borgs.

Server: Which server were you playing on? sybil.

**Comment by Cebasiz** [comment]
it's always been like that, as long as i've been playing. i thought it was intentional(?) if not, why has it persisted for a year+? 

i'm starting to worry that half the game is broken and that nobody's noticed.

**Comment by MrStonedOne** [comment]
cyborgs have limited interaction functionality, so nobody knows if that is suppose to be included, Personally I just assumed it was suppose to be a limitation.

**Comment by xxalpha** [comment]
Has always been. I figure it's a limitation, you have no hands to move things.
