### ISSUE TITLE
Empty speech messages

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#11203]
I have seen this pop up over the last week or so.
People will try to say something but it will come out as

*Hivemind,* **alien hunter(69)**
[Security] **Cargo Requests Console**

etc. no verb, no message.

Alien queen said that it was triggered by an exclamation point. (e.g. "give your queen all your plasma!!")

**Comment by Ikarrus** [comment]
!! Is considered yelling, and normally it would bold the whole message.

I've had this runtime before, and I thought it was fixed, but it looks like it's still causing issues.

**Comment by Jordie0608** [comment]
Encountered with a ghost speaking only exclamation marks
>DEAD: Patrick Margaret says, "WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOW"
DEAD: Patrick Margaret 
DEAD: Patrick Margaret exclaims, "!"
DEAD: Patrick Margaret 
DEAD: Patrick Margaret 
DEAD: Patrick Margaret says, "what the fuck"

>[11:22:55]SAY: Ghost/Punnches420: WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOW
[11:22:58]SAY: Ghost/Punnches420: !!!
[11:23:00]SAY: Ghost/Punnches420: !
[11:23:02]SAY: Ghost/Punnches420: !!
[11:23:07]SAY: Ghost/Punnches420: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[11:23:10]SAY: Ghost/Punnches420: what the fuck
