### ISSUE TITLE
We should have a rules button in the game lobby window.

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11212]
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=4421&view=unread#unread

This is more to make it prominent to people rather than anything else.
If a system which can be defined server side for when the rules were last updated and your last login is also done it could be extra prominent until you read it.

This is a feature request to make it more easy for people to notice and suggest they read them.

**Comment by Jordie0608** [comment]
There already is a Rules button on the UI.
The way the changelog alerts when it's unseen won't work with it currently as it's just a direct link to the wiki.

**Comment by Jalleo** [comment]
True there is but its easily un-noticed.
