### ISSUE TITLE
Surgey tables block projectiles

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11211]
Not ALL tables are tables.

**Comment by Sosowski** [comment]
I'm assuming this requires just adding 'pass_flags = LETPASSTHROW' to objects/structures/OpTable.

**Comment by WJohn** [comment]
I'm not sure if this is considered a bug or not, probably more of an oversight? I dunno.

**Comment by freerealestate** [comment]
what situation did you find yourself in where surgery tables blocking projectiles became an issue, out of curiosity

**Comment by Anonus** [comment]
A gangster was defending a dominator in arrivals maint and, uh, surgery table.
I found it funny as fuck.

**Comment by Firecage** [comment]
Well, this is what we get for having a non-table table.

**Comment by Dorsisdwarf** [comment]
The reason surgery tables aren't tables is because there's a shitload of stuff tables do that you dont want a surgery table doing.

**Comment by SweaterKittens** [comment]
Should be fixed by #12924 ?

**Comment by phil235** [comment]
Indeed.
