### ISSUE TITLE
Guardians can attack their owner while not manifested

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#11216]
Which is kind of silly, given, you know, healing guardian.

**Comment by Incoming5643** [comment]
Bug in action https://www.youtube.com/watch?v=7I6OtXYXv20

**Comment by KorPhaeron** [comment]
@Anonus 

I added a check to make sure healing doesn't work while recalled, does it not work?

**Comment by Anonus** [comment]
I'm not actually sure because I haven't seen anyone take healing, but they shouldn't be able to attack their owner when recalled at all.
