### ISSUE TITLE
You can still apply patches to dead people, there's no indication they don't still work

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#11226]
There's no sign that patches aren't still effective on dead bodies other than noticing the changelog or that a dead patient's health doesn't change when given patches, which will probably cause confusion since there's no message saying that it won't work (like you get when you try to use a bruise pack or ointment on a dead dude)

Also the defib's "Severe tissue damage" should be changed to say that recovery is impossible, since it now is

**Comment by WJohn** [comment]
@Miauw62

**Comment by Miauw62** [comment]
literally not an issue, just common sense. there was a changelog, and soon it will become common sense that these reagents dont work on dead mobs because no other reagents work on dead mobs, either.

**Comment by phil235** [comment]
You can inject corpses even though it doesn't do anything. Same thing for patches now.

**Comment by Shapsy** [comment]
Why keep it if it straight up doesn't work though, it's just going to lead to a lot of confusion that could easily be avoided? For better or for worse there's an entire meta built around patching up dead corpses, having it suddenly not work with no indication other than one line in a changelog (which says "patches no longer work on dead people", which is wrong and should say "styptic, silver sulf and synthflesh no longer heal dead people") is going to fuck with people for a long time

At the very least, make defibs say "Recovery of patient is futile" when the body is too damaged

**Comment by phil235** [comment]
@shapsy We keep it so you can still use patches of strange_reagent (to revive it) or of fuel/napalm to set them on fire.

**Comment by idontwannasignup** [comment]
That's not fair. It's not common sense just because it is to you.
