### ISSUE TITLE
mediborgs cannot complete xeno removal (could previously)

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#11220]
before the surgery changes you could use hemostat(?) twice in a row to do the last step then remove the larva, now you require hands to do the last step, where before it could be either. probably not intentional because why nerf mediborgy?

**Comment by Jalleo** [comment]
@core0verlord

**Comment by Core0verload** [comment]
Fuck. Wasn't there **"someone must update wiki with new step"** sign in #11058? Because *nobody updated wiki*, and now we have a bunch of confused players not knowing what to do next.

If you follow the steps described in #11058, xeno removal works fine for both human and borg surgeons.

**Comment by Jalleo** [comment]
@Dorsisdwarf ya know anyone willing to update the wiki

**Comment by phil235** [comment]
Wiki updated, closing this.
