### ISSUE TITLE
Transformation Sting broken

### ISSUE THREAD

**Issue by Memendia** [tgstation/-tg-station#11235]
Problem Description: Unable to use Transformation Sting as a changeling

What did you expect to happen: I expected the monkeys and humans I tried stinging to turn into me.

What happened instead: No Chemicals used nothing saying the sting failed.. it did nothing.

Why is this bad/What are the consequences: You are unable to use a very powerful sting.

Steps to reproduce the problem: Be a changeling and try using transformation sting on a monkey or human.

Server: Bagil

Revision: 848c14a3c675de18ab8bdcb92408fbece5ca7b36

**Comment by phil235** [comment]
@Miauw62

**Comment by SconesC** [comment]
nothing of value lost tbh

**Comment by phil235** [comment]
runtime error: undefined variable /datum/changelingprofile/var/real_name
proc name: sting action (/obj/effect/proc_holder/changeling/sting/transformation/sting_action)
  source file: tiny_prick.dm,90
  usr: Verimonia Reyaga (/mob/living/carbon/human)
  src: Transformation Sting (/obj/effect/proc_holder/changeling/sting/transformation)
  call stack:
Transformation Sting (/obj/effect/proc_holder/changeling/sting/transformation): sting action(Verimonia Reyaga (/mob/living/carbon/human), Becky Garland (/mob/living/carbon/human))
Transformation Sting (/obj/effect/proc_holder/changeling/sting/transformation): try to sting(Verimonia Reyaga (/mob/living/carbon/human), Becky Garland (/mob/living/carbon/human))
Verimonia Reyaga (/mob/living/carbon/human): AltClickOn(Becky Garland (/mob/living/carbon/human))

select_dna() no longer returns a dna but a changeling profile so trying to get the var real_name runtimes.

**Comment by Aranclanos** [comment]
fixed
