### ISSUE TITLE
Certain machines may be broken

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11251]
If the machines destroy proc dosent have a ..() in it the machine may be used to make multiple copies of the machine parts when it is deconstructed.

**Comment by Jalleo** [comment]
@gunhog

**Comment by Jalleo** [comment]
Reopen its potentially still existing for other machibes @phil235 @remierichards

**Comment by Jordie0608** [comment]
Did a quick check through all the Destroy() procs, found only this to not call ..():
/obj/machinery/announcement_system/Destroy()
A more thorough check may reveal more.
