### ISSUE TITLE
Slip and sprite

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11255]
I had Cold Resistance, I slipped on that green shit that cleaner grenades permanently leave and lost the yellow aura from CR instantly. At first I thought it was radiation or something that removed the CR but I was able to waltz around in space without feeling cold. I assume slipping somehow removed the CR effect.

**Comment by WJohn** [comment]
Sounds related to #10772. Some of the power overlays just seem to vanish under very specific conditions, giving you invisible powers.

**Comment by xxalpha** [comment]
Rogue overlays.Cut() lines, I am guessing.

**Comment by PKPenguin321** [comment]
semi-related, once i manifested all powers and then got monkeyed and unmonkeyed and then i still had the powers but no overlays

**Comment by phil235** [comment]
duplicate issue. Mutation overlays aren't properly handled. It also happens if you simply spray space cleaner on someone with a visible mutation like hulk or TK.
