### ISSUE TITLE
Poster sprite change

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11264]
1. Place Nanotrasen Loyalist poster
2. Wirecutter it off
3. Recieve same poster that has same sprite as Syndicate poster.

When placing the syndiposter, it does place the orginal loyalist poster but the inventory sprite and examine info says it's syndiposter.

**Comment by SconesC** [comment]
This has been around for so long

**Comment by Marflowerose** [comment]
Yes, I'm amazed that a game breaking abuse like this has been allowed to linger for so long.

**Comment by Tokiko1** [comment]
This also happens if you walk away while the poster is being applied to the wall. It will drop on the floor and get the syndicate poster sprite.

**Comment by SconesC** [comment]
Where is poster placement handled?

**Comment by Jalleo** [comment]
https://github.com/tgstation/-tg-station/blob/ccd4137a9dc113f33b304711aa1aa3132ca8a10c/code/game/objects/effects/decals/contraband.dm
