### ISSUE TITLE
Syndicate cyborg grenade launchers don't seem to work.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#11267]
Tested on a nuke op bought syndiborg and then an adminspawn one.

Error message is IMPLANT CHECK FAILED

this is in fact a i ded pls fix issue

**Comment by duncathan** [comment]
#11242 
@Firecage

**Comment by Bluespace** [comment]
a month
a fucking month
why the fuck isn't this fixed
they cost FIFTY TELECRYSTALS
AND YOU CANT FIX THEM.

**Comment by WJohn** [comment]
We've had much worse bugs stay open for longer, I'm sure. Go ask someone in coderbus about fixing it.

**Comment by Dorsisdwarf** [comment]
closed
