### ISSUE TITLE
Revenant overload lights doesn't break lights

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11278]
Not sure if the ability is intended to keep lights from breaking when it is used. Gives off the sound/special effect of a light breaking when used though.

**Comment by daman997** [comment]
nah man it is totally intended to be like this

really though fix it

**Comment by Anonus** [comment]
It's not actually intended to break lights and if it did it'd have to do a lot more damage.
Also, lights don't have a breaking sound effect, unless you mean the sparks.

**Comment by duncathan** [comment]
Clearly people want this to stay so

**Comment by duncathan** [comment]
@bgobandit <3
