### ISSUE TITLE
Strangulation completely paralyses you, to the point where resist does nothing.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#11275]
What it says in the title.

There's one thing you can do, and that is talk; but Resist, the button which should be letting you try to break free or move away from this, does not do anything. If you're grabbed, it's GGnore - reminds me of the days of quickchoke.

Again, I'm killed by a bug. Why do we have Resist again?

**Comment by Lumipharon** [comment]
Actual chokehold (for as long as I can remember) has always rendered you utterly helpless.

You can argue about the gameplay/balance/realism of this, but I'm 99% certain this is intended behavior.

**Comment by AnonymousNow** [comment]
Jesus H. tapdancing Christ up and down a pagoda.

**Comment by PKPenguin321** [comment]
yeah it's intentional, it's like a stronger handcuff basically

pro tip: changelings can break out of it with their confusion screech

**Comment by Jalleo** [comment]
There should be a chance to break out of it honestly.

**Comment by Miauw62** [comment]
:hugbox:

**Comment by Miauw62** [comment]
https://tgstation13.org/phpBB/viewforum.php?f=10
