### ISSUE TITLE
Make yourself emit light

### ISSUE THREAD

**Issue by milocv** [tgstation/-tg-station#11282]
You can basically make yourself emit light.

Grab a flashlight
Buckle to a bed with the flashlight turned on by your side
Click the flashlight repeatedly (The more you click, the more bright you will become)
Become light incarnate.

I was able to reproduce this twice consistently..
![fuck](https://cloud.githubusercontent.com/assets/9081305/9362153/46660144-469f-11e5-854c-bde2cb7d3100.png)

**Comment by MrStonedOne** [comment]
@MrPerson

**Comment by Chocobro** [comment]
this is really fucking funny

**Comment by duncathan** [comment]
Shadowlings beware

**Comment by PJB3005** [comment]
Whoosh, baylights is 10x better.

The current system DAL uses for light sources IS TRASH.

Flashlights inside a mob for example will increase the MOB'S brightness, this results in shit like this.

**Comment by Chnkr** [comment]
^ what he said.
