### ISSUE TITLE
Cyborgs can unlock their cover when dead

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11287]
What it says on the tin

**Comment by WJohn** [comment]
spooky

**Comment by Marflowerose** [comment]
TBH while this may be a bug, I think this should be turned into a feature. If a borg dies, it's cover automatically opens up, or just leave it as is.

**Comment by WJohn** [comment]
A borg should not have control over their panel or anything when dead, this is like when humans could roll around while dead.

**Comment by Marflowerose** [comment]
Then just have it be automatic that the cover pops open when dead. It'd help in situations where roboticists etc are dead or missing. For human revival you only need to bash down few windows but for borgs you need to have very spesific ID access to be able to open one single panel, in addition to printing the reset board (which AFAIK doesn't require access)

**Comment by GunHog** [comment]
Btw AIs can unanchor when dead, which is useful for enabling a borg to bring you to the RD for repairs. If no one else beats me to it, I can certainly code auto-unlock and unanchor for cyborgs and AI upon death.

**Comment by Jalleo** [comment]
Sure but make sure emagging a borg dosent work when they are dead

**Comment by Cebasiz** [comment]
why not? seems like a neat feature.

**Comment by WJohn** [comment]
I wouldn't mind being able to kill a cyborg, have their cover be automatically opened from them dying, emagging them, then reviving them with them safely on your side. I think that'd be pretty cool, honestly.
