### ISSUE TITLE
You can ship the dominator and it still works.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11297]
I shouldent need to explain why this is terible

**Comment by bgobandit** [comment]
To clarify: You can place an active dominator on the cargo shuttle, send it back, and the countdown will still continue as normal.

I don't think I have to specify why this is bad.

**Comment by bgobandit** [comment]
@Ikarrus

**Comment by Jalleo** [comment]
Oh god dominator on the white ship/mining/ gulag shuttle.

**Comment by Lumipharon** [comment]
Damn it Ikky, I asked about this when you first put the dominator in.

**Comment by Ikarrus** [comment]
I'm sure it worked at one point, but I think something in the code changed.
