### ISSUE TITLE
Xenomorphs Can't Understand Humans After They Die

### ISSUE THREAD

**Issue by cookingboy3** [tgstation/-tg-station#11295]
If you're a xeno and you get fucked up, the chat remains unreadable, as if you were still alive. Everything humans say remains starred out.

**Comment by WJohn** [comment]
I can't replicate this while I'm moving around as a ghost. If you mean while you're in your body then I don't think that's a bug.

**Comment by Miauw62** [comment]
nothing i can really do about this while you're still in your body.

**Comment by WJohn** [comment]
I don't think this is worth an issue report, honestly.
