### ISSUE TITLE
Rogue air scrubber in virology

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11290]
![it's not connected to the pipeline next to it and there's a scrubber directly to the right of it](http://puu.sh/jHAza/8954c004ed.png)
It's not connected to the pipeline next to it and there's a scrubber directly to the right of it.

**Comment by WJohn** [comment]
I kind of want to redo all of box's piping.

But at the same time uuuuuuugggghhhh. That'd take forever and ever and there'd be so many possible errors.

**Comment by Aloraydrel** [comment]
Deepest lore

**Comment by Jalleo** [comment]
It needs doing @WJohn just do it one small area at a time. Maybe some rooms in maint can get vents and scrubbers.
