### ISSUE TITLE
Chaplain can get unlimited bike horns

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11298]
>Click on bible a bunch of times
>Start spam clicking the clown bible
>Watch as your bible keeps getting a extra bike horn as you keep clicking it

It goes past the limit the bible can hold as well

http://puu.sh/jIl54/a45f5bf983.png

**Comment by bgobandit** [comment]
Not technically past the limit, probably related to the new backpack weight class changes

**Comment by WJohn** [comment]
Why don't we have a pink HONK tag?

**Comment by duncathan** [comment]
@bgobandit no container can hold 37 items it's definitely past the limit
