### ISSUE TITLE
Badmins can spam "Reject Adminhelp"

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#11299]
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
[Common] Garry Armhulen slurs, "WH'ERE 'IS HE"
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.
- AdminHelp Rejected! -
Your admin help was rejected. The adminhelp verb has been returned to you so that you may try again
Please try to be calm, clear, and descriptive in admin helps, do not assume the admin has seen any related events, and clearly state the names of anybody you are reporting.

**Comment by MrStonedOne** [comment]
Feature

**Comment by freerealestate** [comment]
Can we return spam to everything else in the game then too

**Comment by MrStonedOne** [comment]
Admins are allowed to spam, players are not.

**Comment by freerealestate** [comment]
How come?

**Comment by MrStonedOne** [comment]
Because they are admins, admin is a privileged and trusted status. They can do things that have no html filtering, inject html directly to clients, edit every variable, (including the ones that would be used to throttle spam)

At this point you might was well complain that they can spam the trigger meteor storm button.

Or any button at that point. Admins can literally spam click any button. No admin tool has flood prevention on it, and i really don't see the need for any of them to have it.

**Comment by freerealestate** [comment]
If it can be used this easily to spam players, then it should probably have
a cooldown to prevent that

**Comment by MrStonedOne** [comment]
Mashing the trigger event button can easily be used to spam players.

Doing a single sdql2 query can easily be used to spam players.

Admins literally have the power to delete every thing, or delete only certain things. hell they can call gib() on all mobs with one command, but this is where you want to draw the line?

**Comment by freerealestate** [comment]
Why do you think admins are more likely to do this than that though? Because they'll get in trouble for the examples you present. 



It just seems like a small oversight on your part when you made this feature.










On Friday, 21 Aug 2015 at 8:03 am, Kyle Spier-Swenson <notifications@github.com>, wrote:

Mashing the trigger event button can easily be used to spam players.


Doing a single sdql2 query can easily be used to spam players.


Admins literally have the power to delete every thing, or delete only certain things. hell they can call gib() on all mobs with one command, but this is where you want to draw the line?

**Comment by optimumtact** [comment]
WTF, admins acting like a baby isn't a feature you dingbat

This isn't a bug, but the admin in question should be talked to about being a child

**Comment by Niknakflak** [comment]
Feature

**Comment by optimumtact** [comment]
Honestly if the admins are gonna act like that I've changed my mind

I'm gonna have a look at fixing this

**Comment by Aranclanos** [comment]
At the moment, the project expects that the people in admin titles are the ones on higher standards, selected by the server owners.
There are no plans on restricting what admins can do beyond flags, that are under control of also the server owner.
Admins have a million of tools to spam anything, from spawning antags and mobs to centcomm reports and world messages. It's up to each server to keep their admins on their own standards.

**Comment by Stickymayhem** [comment]
How did no one fucking respond with the extremely basic and intuitive "bug fix" of "Making the admins doing this not act like cunts.

I thought we got over reject spam a couple hours after it got merged.
