### ISSUE TITLE
Antagonists have no way to tell if their targets are in the cloner database

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11311]
This becomes a problem when the autocloner is about partially due to the policy that people remember everything after they are cloned from when they last died.

**Comment by phil235** [comment]
Not an issue, you can simply ask the geneticist if the cloner has been upgraded, and you can ask them to scan you to get in genetics and check the database. You can also hack your way into genetics and destroy/emag the cloner.
