### ISSUE TITLE
Temporary bans can only last up to one year

### ISSUE THREAD

**Issue by Fayrik** [tgstation/-tg-station#11312]
Temp bans only go up to five hundred thousand minutes (525599), roughly one year.
This seems to be an artificial limit, I don't know any integer size that would max out at that number.

This is problematic because I do not want to have to apply a permaban and then wait a decade to manually unban the person when the ban should expire on it's own.

**Comment by RemieRichards** [comment]
Why do you need a TEMP ban to go on beyond a year?
It's a TEMPORARY BAN.
Anything beyond a year should really just be a perma+note, like how permabans are handed out to get people to come to the forums and explain.

**Comment by Supermichael777** [comment]
any ban longer than a month probably goes far enough into rule one for the perma and note.

**Comment by Jordie0608** [comment]
Reason aside, if an admin wants to ban someone for upwards of a year then they should be able to; I can't think of any good reason to have an arbitrary limit on the duration.

**Comment by MrStonedOne** [comment]
Generally it would be handy for underaged bans
