### ISSUE TITLE
Slaughter demons freezes when eating a wizard who uses RISE!!

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11310]
As it says in the title

>Eat a wizard who has that spell
>He uses it to resurrect
>Demon now cannot move as it says he is still eating

**Comment by Incoming5643** [comment]
The wizard's old body gets destroyed during Resurrection, so it sounds like slaughter demons weren't checking to see if their victim didn't somehow explode/dust/turn into something else while they were in their "mouth".

It's not quite as edgy a case as it seems at first blush, but it's still pretty edgy

**Comment by phil235** [comment]
````		
			if(kidnapped)
				src << "<B>You begin to feast on [kidnapped]. You can not move while you are doing this.</B>"
				playsound(get_turf(src),'sound/magic/Demon_consume.ogg', 100, 1)
				sleep(30)
				playsound(get_turf(src),'sound/magic/Demon_consume.ogg', 100, 1)
				sleep(30)
				playsound(get_turf(src),'sound/magic/Demon_consume.ogg', 100, 1)
				sleep(30)
				src << "<B>You devour [kidnapped]. Your health is fully restored.</B>"
				src.adjustBruteLoss(-1000)
				src.adjustFireLoss(-1000)
				src.adjustOxyLoss(-1000)
				src.adjustToxLoss(-1000)
				kidnapped.ghostize()
				qdel(kidnapped)
			src.notransform = 0
````
"kidnapped" becomes null during one of the sleep(30), kidnapped.ghostize() probably runtimes and so src.notransform = 0 is never called so the mob is stuck.

**Comment by WJohn** [comment]
@Incoming5643 could you come on IRC sometime soon? I've been meaning to discuss some stuff about wizard artifacts.

**Comment by Incoming5643** [comment]
yeah sure I've been on psudeo break because I was doing an internship but it ends at the end of the month, I'll try to make some time.
