### ISSUE TITLE
Mech HUD takes forever to appear

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#11313]
rev: e66bf6f5a15dacbeefec59c135b8031bb91f7645 

Enter mech, dont get a HUD. It can take MINUTES for it to appear on your screen.

**Comment by phil235** [comment]
It's not just mech buttons, it's all item action buttons. Likely caused by https://github.com/tgstation/-tg-station/pull/11239/files#diff-d673e87b831ff54f11401807aade04d0R44

**Comment by Jalleo** [comment]
I just dont get it to load up sometimes http://imgur.com/kU06APx

**Comment by Lumipharon** [comment]
This is incredibly annoying considering the mech tab was removed for no particular reason.

**Comment by RemieRichards** [comment]
@Lumipharon >no particular reason

if you've been here longer than 2 seconds you'd know Verbs are complete ass and we're removing them wherever possible.

**Comment by Lumipharon** [comment]
Verbs have never not loaded for me, unlike action buttons.

**Comment by RemieRichards** [comment]
@Lumipharon ever right clicked a large pile of objects and had super lag or a client crash because of it?

All the fault of verbs.
