### ISSUE TITLE
Strange things involving AIs inside of Mechs happen in very specific situations.

### ISSUE THREAD

**Issue by cookingboy3** [tgstation/-tg-station#11329]
So, I was an AI that had been put into a Ripley and sent off to go mine. In a personal test of strength (read: terrible idea) I decided to go drill some gibtonite. As soon as I drilled it, I switched to my scanner to stop it exploding, but, alas, I heard an explosion, my screen went black, and my system was now nonfunctional. Somehow, I got vision back a few moments later, to see my mech completely unharmed, standing next to gibtonite that was just going through the "timer to detonation" animation repeatedly. Jump forward about 25 minutes, and I had been talking to one of the admins (I forgot your name, so please make yourself heard if you see this) about what had happened, and he told me that both the explosion and the gibtonite itself runtimed. From whatever happened to cause all of this, I can point out multiple problems:

- Two runtimes
 - Not sure what caused them. Maybe mech drill or the scanner?
- The fact that an AI that's uploaded into the computer of a giant, armored robot can die separate from the robot itself, while the robot is fully functional.
- The mech scanner (maybe) doesn't stop gibtonite.

This was a couple of hours ago, on Sibyl.

**Comment by Shadowlight213** [comment]
Admin here.
From what it looks like, the AI eye getting qdel'd runtimed. Then it looks like the other things runtimed.
Link to runtime log
https://tgstation13.org/parsed-logs/sybil/runtimes/runtime-2015-08-22.txt
Ctrl-f for shrike
But yeah, when I saw it it looked like a moment frozen in time right before the explosion.

**Comment by phil235** [comment]
caused by https://github.com/tgstation/-tg-station/pull/11239/files#diff-f314d5c9accbb64112d6ca62f2fa16b9R19 mob/camera/Destroy calls qdel which calls Destroy, creating an infinite loop.

**Comment by Invisty** [comment]
The return to core button doesn't work when an AI uses camera monitors. You have to reconnect to get back to the mech view.
