### ISSUE TITLE
Emitter Board: Lack Thereof

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11327]
Currently just about every single machine that has a board is able to be produced in R&D....there's one glaring exception, however: the emitter board.

Currently the only way to obtain one of these is by ordering/acquiring a full scale emitter; this should probably be able to be produced in R&D.

**Comment by WJohn** [comment]
Wait it's POSSIBLE to make emitters? Huh. Should definitely be possible to print these, then.

**Comment by Fox-McCloud** [comment]
@WJohn 

Yup; you can upgrade them, too.

**Comment by PKPenguin321** [comment]
@Iamgoofball
