### ISSUE TITLE
Wizerds can refund spells with more than one point invested receve all points back and invest 1 point for that level

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11325]
Wizards with almost max tier in 5 spells
this is terible

**Comment by Jalleo** [comment]
Oh god.

**Comment by WJohn** [comment]
UNLIMITED POWER

**Comment by Jalleo** [comment]
NOW SEE MY TEACHER OF WIZARDRY

**Comment by Jalleo** [comment]
@Incoming5643 probably very important.

**Comment by Incoming5643** [comment]
Not my fault, won't be available to fix this until the 3rd of September, if someone can fix it first I suggest it heartily.

**Comment by Iamgoofball** [comment]
OH MY GOD I CANT WAIT TO ROLL WIZARD
