### ISSUE TITLE
Magboots work in mechs

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#11339]
no more zero-g drifting inside mechs!

**Comment by phil235** [comment]
```
/obj/mecha/Process_Spacemove(var/movement_dir = 0)
	if(occupant)
		return occupant.Process_Spacemove(movement_dir)
	return ..()

```
The mech calls the occupant's Process_Spacemove which obviously checks for magboots and other stuff.

**Comment by Actionb** [comment]
Miauw you fiend! 
It's not too far fetched to think super heavy duty mechs come with some form of magnetic traction though. It's a bit silly to think something designed for work on space stations has no ability to deal with zero-g.

**Comment by Miauw62** [comment]
fun removal is my middle name

**Comment by WJohn** [comment]
So does this mean that turning on magboots while riding a mech prevent the mech from drifting? Can you just walk around in space magically?

**Comment by RemieRichards** [comment]
It also means if a carp was driving the mech the mech could swim in space.
honk honk.

**Comment by Dorsisdwarf** [comment]
What about jetpacks?
