### ISSUE TITLE
you can empty a lit pipe while unconcious.

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11345]
Happens when it runs out of material in you mouth.
Clearly the most critical of bugs.

**Comment by WJohn** [comment]
I don't really think this is a bug? The pipe will continue to burn by itself, shouldn't it eventually run out?

**Comment by Dorsisdwarf** [comment]
I believe the issue is that the message says "You empty the pipe" or something dumb

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/c9870a0fef4681de19f3c2e7fe6568373876f1e2/code/game/objects/items/weapons/cigs_lighters.dm#L364
We should probably use the same message as cigarettes instead. "Your [name] goes out."
