### ISSUE TITLE
Syndicate box folding

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#11352]
If the box is made of distinctive enough cardboard to have a different sprite, then HOW COME YOU CAN MAKE IT INTO A NORMAL BOX BY FOLDING IT TWICE????????????

Priority: critical. Immersions: non-existent.

**Comment by WJohn** [comment]
Maybe we should be able to make any cardboard box we want in our hands when crafting it? There's an awful lot of them, though...

**Comment by Core0verload** [comment]
And then we wonder why our issues list is so awfully big.

**Comment by PKPenguin321** [comment]
not really a real issue

**Comment by Dorsisdwarf** [comment]
Ideas forum, punks.
