### ISSUE TITLE
Traitors with document swap objective not spawning with documents

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#11379]
Reply PM from-Mortimermcmire/(Mortimermcmire): I had the objective to steal from another person who also had them, I never got the traitor message and never spawned with them so they kinda got fucked in that regard

Dunno much else about it.

**Comment by SconesC** [comment]
What job were they?

**Comment by lollerderby** [comment]
HoP, I think.

**Comment by Dorsisdwarf** [comment]
This will be closed in a week if not reproduced/reason found. Sounds like either a runtime of an extreme edge case.

**Comment by Dorsisdwarf** [comment]
It was a long week ok
