### ISSUE TITLE
A ton of issues that should have been closed were tagged yet not resolved

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#11378]
@Dorsisdwarf I looked through older pages of issues... There are QUITE a few that have been fixed by now, but you just seemed to tag everything and not close much (from what I can tell)

Should I make a list or something?

**Comment by Dorsisdwarf** [comment]
I'm not always 100% up-to-date with what exactly has been fixed from the old issues, especially the more technical ones. I'll go do a closing run-through, but if there's any you want to point out, go ahead.

**Comment by optimumtact** [comment]
I think we should formalise  a process where if an issue has no independent verification from another person or no clear steps to reproduce it should be closed - and tagged as unresolved.

That way you can still look into older bugs by searching for closed - unresolved bugs. but the issue tracker would be more manageable and clean.

it would also encourage good bug reports with reproduction steps.

**Comment by xxalpha** [comment]
Listen to oranges.

**Comment by Chocobro** [comment]
I can't he's just text on a screen

**Comment by Dorsisdwarf** [comment]
I closed lots with help, but tagging unresolved as this is a perpetual issue
