### ISSUE TITLE
/obj/item/borg/stun and /obj/item/borg/sight/meson doesn't qdel.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#11372]
This happens if there is still a variable that points to that Object. in order to soft delete properly, the Object's destroy proc needs to clear up all references that point to it.

Failed qdel log:
http://privatepaste.com/edc18b668d

**Comment by Core0verload** [comment]
It's propably all borg module items, not just /obj/item/borg/*. It would explain a bunch of undeleted tools too.
