### ISSUE TITLE
Gold Slime Cores are creating the base /simple_animal

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11387]
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm

I know because I discovered one that was called animal and was invisible and chased its own tail.

**Comment by WJohn** [comment]
This is STILL happening? I swear we fixed this at least once before, if not twice.

**Comment by phil235** [comment]
Everytime someone adds a new animal type where only its children are actually spawned the bu reappears and we have to add the type to the blacklist (simple_animal/hostile/blob, simple_animal/pet, etc...)
