### ISSUE TITLE
Newly built AI's aren't given the preferred name they have saved.

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11383]
Oopsies!

**Comment by Marflowerose** [comment]
We also have the odd feature where borgs cannot name themselves when built.

**Comment by cookingboy3** [comment]
@Marflowerose That's intended. The roboticist can name them using a multitool before they're built.
However, I'm not sure the AI thing is intended.

**Comment by Marflowerose** [comment]
I know it's intended, that's why I said it's a feature. It's still dumb.

**Comment by RemieRichards** [comment]
Not a Bug, AI names come from the user's client preferences (your savefile), like Clown, Mime, etc. names. If the bug is -specifically- that constructed AIs aren't getting their name from their player, rename the Issue, and adjust the OP.
