### ISSUE TITLE
Changeling organic items prevent gibbing

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#11388]
this means that you cant really use the gibber against lings anymore.

**Comment by RemieRichards** [comment]
Excellent.

**Comment by GunHog** [comment]
You can if you upgrade it first! :D

**Comment by phil235** [comment]
How does the gibber manage to ignore ling flesh armor and flesh spacesuit? We just need to do the same thing with organic items if possible.

**Comment by SconesC** [comment]
In the purity of the cremator's flame, the changeling will find absolution

This has also been an issue with the organic armor for ages

**Comment by PKPenguin321** [comment]
also an issue with shadowling chitin
