### ISSUE TITLE
Changeling traitor panel runtime

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11394]
Not really sure what caused this. I was messing around with swap form and such on a spawned in human, then when I tried to open my traitor panel, I got a runtime.

http://pastebin.com/y3iu4vHS

**Comment by phil235** [comment]
Do you remember what kind of swappign you did? Transformation(humanize, monkeyize, Make Alien, etc) ? Maybe rudimentary transformations?

The runtimes is caused by the changeling datum's first_prof becoming null.

**Comment by Shadowlight213** [comment]
I spawned a human mob, and had changed their equipment around and dna extracted them. Was messing around with the new transforming. Then did swap forms

**Comment by Miauw62** [comment]
Not an issue with changeling code, adminspawned humans have fucked up DNA.
