### ISSUE TITLE
You can use fire extinguisher cabinets from two tiles away

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11400]
What happened: Please see handy MS Paint diagram: ![](http://i.imgur.com/rcfnv9b.png)

Why this is bad: Consistency, why should you be able to do this. (Before you ask: The cabinet is on the wall, not on the floor tile, so it actually is two tiles away.)

**Comment by RemieRichards** [comment]
it is NOT on the wall, it IS on the floor tile, it is technically 1 tile away, so it's not a bug.

**Comment by xxalpha** [comment]
Not a bug and necessary if you want to reach things over tables. It's the same thing with wall terminals and anything that's on a wall, really.

**Comment by WJohn** [comment]
It's just a quirk of our mechanics.

**Comment by Anonus** [comment]
If you want to fix this feel free to remap every single map to account for it.
