### ISSUE TITLE
Emptying a bag onto the floor via drag doesn't trigger mousetraps

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11406]
This basically allows you to bypass moustrap bombs pretty easily.

**Comment by Xhuis** [comment]
Seems intentional to me. You aren't opening the backpack, you're emptying it onto the ground which logically wouldn't trigger the mousetrap unless something bumps into it.

**Comment by Shadowlight213** [comment]
Emptying the bag onto the ground would require opening it first though

**Comment by astralenigma** [comment]
I thought that the mouse trap was triggered by putting the hand inside the bag not oppening despite that being seen as 1 action ingame.

**Comment by Miauw62** [comment]
can ghosts trigger mousetrap bombs?

**Comment by Core0verload** [comment]
Sadly, no. At least now. Bombing all the station, shutting down the comms and releasing the singulo as ghost was MEGAFUN.
