### ISSUE TITLE
Blindness is not "true" blindness

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#11404]
Feature request I guess? Intended if it's been around for so long

Currently blindness is handled at least for blindfolds by having tint 4 and I can't fucking find out how other blindless for screen works

Should be total black, not one tile of grace

**Comment by phil235** [comment]
total black would be silly gameplay wise.

**Comment by Iamgoofball** [comment]
Butphil, it makes being blind trivial for people who memorized the station map. If we really wanted to simulate the senses there's better ways than the 3x3 vision cone.

**Comment by Lumipharon** [comment]
All we have in this game is sight and sound. If you make them literally blind, going off sound alone means you're well and truly fucked.

**Comment by Miauw62** [comment]
total blackness for blind people would be dumb because it'd mean you would be unable to interact with anything.

i support total darkness for crit, though

**Comment by Marflowerose** [comment]
Make it so that blindness puts total darkness but you can see the outlines of items around and below you and apply it to dark places aswell. Kinda stupid that a blind person can see more than person in dark hallway despite both being able to touch their way.

**Comment by Alek2ander** [comment]
Bumping a dense object you can't see (either because of blindness or darkness) should make a sound

**Comment by CosmicScientist** [comment]
I'd like to chime in and say you can rightclick to "see" what's beyond the blindness. I believe the same might also be done in actual darkness when roaming around maint or a shadowling infested station.

**Comment by optimumtact** [comment]
no don't be stupid

**Comment by PKPenguin321** [comment]
yeah this is pretty stupid
blindness is already strong because you can no longer interact with anything more than a tile away
if you're mad because you blinded somebody then tried to kill them with a melee weapon and lost, that's pretty much your own fault

**Comment by MrStonedOne** [comment]
>Butphil, it makes being blind trivial for people who memorized the station map.

This is true for the real world as well...

**Comment by Dorsisdwarf** [comment]
Closed for oldness and Feature request. Take it to Ideas.
