### ISSUE TITLE
Metastation syndie base has an area of space in it, making parts unpowered.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11415]
@Metacide 
![Syndie base](http://puu.sh/jPYeW/90f4e7b08f.png)

**Comment by PKPenguin321** [comment]
if i'm not mistaken, this is pretty high priority since it means that ops can no longer pool their TC

**Comment by WJohn** [comment]
I think you're right, they might not even be able to get their equipment in the lockers since I don't think they start with crowbars on them.

**Comment by PKPenguin321** [comment]
oh shit yeah that too

**Comment by Shadowlight213** [comment]
Yeah. The tc console is unpowered, ran into that issue recently, which is why I noticed it

**Comment by Metacide** [comment]
Will put out an urgent fix soon

**Comment by Metacide** [comment]
Waiting on a map merge tool fix, as this isn't terribly high priority considering how rare nuke ops are on Basil anyway.
