### ISSUE TITLE
For maintainers and everyone welcome to discuss [Headcoder debate[

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11413]
Jalleo> also totally other question
Jalleo> what happened in the end with the idea of getting new headcoders?
Jalleo> as in promoting Miauw or phil or whatever
Cheridan> inconclusive i guess
Jalleo> well I think everyone was looking to you at the time to say what was happening for sure
Cheridan> if the code team wants to get more somehow i'm behind them 100%
Jalleo> can you put that in the coderbus title then so people know about it
Cheridan> i don't want to be the one deciding things there though
Jalleo> or shall I just put this on a thread on the coding section and leave it up like that or whatever?
Cheridan> like i don't think it's a good political system for the guy in charge to be deciding elections
Cheridan> know what i'm saying?
Jalleo> got it
Jalleo> right what I suggest is
Jalleo> I make a issue report
Jalleo> ya lock it to maintainers only
Jalleo> and then let them all talk about it
Jalleo> since its really up to them
Jalleo> and I log this whole part of the convo where we talked about this and put it in the issue?
Jalleo> ya think that is the right way to do it cheridan?
Jalleo> so they talk about it and close it when they decided?
Cheridan> yeah, or I could just post there and explain myself
Jalleo> well I did bring it up
Jalleo> makes it seem more transparent
Cheridan> yeah

@tgstation/commit-access 

This is a discussion for all people who code and whatever to talk about do you want some extra people at the top.

I personally would like people who have been long serving good maintainers to be lifted up a spot as they have been doing so good but meh.

**Comment by RemieRichards** [comment]
@tgstation/commit-access

**Comment by WJohn** [comment]
I nominate remierichards as a headcoder, if we're doing nominations right now. Besides that, I don't know who else would fit the role. Phil is a fantastic guy and is largely why we've managed to fight off so many bugs, but he seems pretty quiet and I don't know if he'd want to be a headcoder.

Not sure about anyone else, though.

**Comment by duncathan** [comment]
8============D for headcoder

**Comment by Iamgoofball** [comment]
I want to be a head coder.

**Comment by Jalleo** [comment]
Its more do ya want it and how do you think it should occur cheridan dosent want to define how it should occur. But if everyone wants to go old nominate route whatever runs the bus runs the bus.

**Comment by ike709** [comment]
>making an issue for something that should be on the forums with an ingame announcement

**Comment by xxalpha** [comment]
This sort of thing has been done in github before.

**Comment by Anonus** [comment]
Yeah remie or phil would be nice if they want to take that up.
Honestly I don't know if anyone else is someone we'd want to have as a headcoder.

**Comment by Chnkr** [comment]
@Iamgoofball for headcoder please.

**Comment by Aranclanos** [comment]
god no, we're so smooth and fine right now it's amazing, there's barely any drama
titles turn people into assholes and there isn't any need of 'leadership' besides /balance/
if you want delegate some poor soul as 'balance guide' or whatever, do it, I don't care as long as he doesn't get to merge things that are awful code-wise

**Comment by Shadowlight213** [comment]
Remie 4 headcoder

**Comment by Iamgoofball** [comment]
For reals though, Aranclanos is right. Everything's running pretty smoothly now.

**Comment by optimumtact** [comment]
man jalleo why do you always bring it up

cheridan seems to be doing okay. The headcoder role was mostly ceremonial anyway, expect for rare case

**Comment by Cheridan** [comment]
I don't have a problem with Jalleo bringing it up. It's one of those things where people could easily be feeling the same way but not want to speak up for one reason or another. 

If you guys want more I'm 100% behind it, if the consensus is that we're fine the way it is I'm 100% fine with that too.

**Comment by xxalpha** [comment]
I don't think getting one more headcoder would be bad.

**Comment by Dorsisdwarf** [comment]
I'd be behind miauw or RR as a headcoder. Miauw because they're a god of coding and RR because they're a sensible person.

**Comment by Jalleo** [comment]
@optimumtact it was more to get it out of the way than anything else i noticed that the thing just stalled last time it was talked about on irc getting it on here makes it solved and done faster with a wsy that its written down. We can then point anyone wondering to this for a while.

**Comment by phil235** [comment]
Having a second headcoder wouldn't be bad, but it won't be me. I'd rather stick to simply coding and merging stuff. I'm supporting Remie and Miauw for headcoder.

**Comment by Miauw62** [comment]
>promoting Miauw

lmao do you want to ruin tgstation?

**Comment by Aranclanos** [comment]
please no please no please no please no please no please no

did i say no

**Comment by Iamgoofball** [comment]
I really don't think we need to change things. It's fine as-is.

**Comment by optimumtact** [comment]
I nominate myself, on the basis of 4 years as a professional developer, a university degree and the fact that aran hates me so it would be funny.

**Comment by MrStonedOne** [comment]
I nominate startoad, sticky, and oranges as a head coder triumvirate!

Ok, in all seriousness, remie

**Comment by Miauw62** [comment]
imo oldman, goofball and malkevin would make a good headcoder triumvirate.

i agree with aran tho

**Comment by Aranclanos** [comment]
not a bug

**Comment by Jalleo** [comment]
Status Quo it is then :+1: for quick finish.

**Comment by optimumtact** [comment]
nobody ever took my self nomination seriously :(

**Comment by Cyberboss** [comment]
why you necroing this ree?

**Comment by RemieRichards** [comment]
I won btw.

**Comment by Shadowlight213** [comment]
Mso for headcoder

**Comment by MrStonedOne** [comment]
>Mso for headcoder

**Comment by RemieRichards** [comment]
>I won btw.

**Comment by Iamgoofball** [comment]
I win

**Comment by optimumtact** [comment]
Does remie think they are a headcoder?

**Comment by Jordie0608** [comment]
>Closed this on Aug 29, 2015

**Comment by RemieRichards** [comment]
@optimumtact better than the pathetic never-does-anything slime of a worm we have now.

**Comment by Iamgoofball** [comment]
at least i don't start coups because my boss fired me for saying he sucked a coder's dick

**Comment by Cyberboss** [comment]
No more necroposting
