### ISSUE TITLE
Security borg's hailing module can break

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#11422]
If used fast enough it'll overload and break, and as far as I'm aware, theres no way to fix it.

literally the worst nerf to silicons.

**Comment by Dorsisdwarf** [comment]
@Cheridan

**Comment by Cebasiz** [comment]
did you try recharging? the flash modules can break but they get repaired when you recharge

might be the same for hailer

**Comment by MMMiracles** [comment]
Recharger doesn't fix it.

**Comment by phil235** [comment]
intended. The hailer needs to be spammed quickly for this to happen, and the device gives you two warnings before it overloads and breaks.

**Comment by MMMiracles** [comment]
I didn't get any warnings as a borg when using it, the only message I got was it breaking.

**Comment by Cebasiz** [comment]
as of maybe a week ago the warnings worked for me

it says something like "the security hailer seems to be heating up!" or something like that.

**Comment by SconesC** [comment]
I don't get warnings with the borg one or the normal one

**Comment by phil235** [comment]
I just tested it and I'm getting the warning messages just fine. Maybe you didn't notice them because the hail messages are pretty big so it makes warning messages inbetween them less visible.

**Comment by Jalleo** [comment]
Probably making then show as user danger would solve it. Also can ya do the borg recharger fix the hailer thing please. For consistency @phil235

**Comment by phil235** [comment]
@Jalleo  The last warning already uses the userdanger span class.

**Comment by Dorsisdwarf** [comment]
Notabug Oldissue intendedfunction
