### ISSUE TITLE
AIs in mechs can't use basically all their modules

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11426]
As an AI in an oddy, I couldn't use the gravity catapult, sleeper, or syringe gun at all.
@GunHog

**Comment by GunHog** [comment]
Did you remember to use your middle mouse button? The controls are different, and players are notified of such upon entering the mech. I had to do it this way, because I was not allowed to check for the AI being in a mech whenever it clicked.

**Comment by Anonus** [comment]
You're supposed to use the middle mouse button? Why isn't that in a popup or big red letters or something?

**Comment by GunHog** [comment]
You are told, in bold lettering, upon entering the mech...
![image](https://cloud.githubusercontent.com/assets/4955510/9535108/8df0bf5a-4ce3-11e5-83c3-a38e79d00ce5.png)

**Comment by Dorsisdwarf** [comment]
Closing if nobody can reproduce MMB not activating all mech functions

**Comment by Dorsisdwarf** [comment]
Closing for tested to be not true
