### ISSUE TITLE
Spaghetti and meatballs VV causes client D.c.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#11432]
Spawned in "spaghetti and meatballs" (in maintenance glass observation room just south of Xenobio)
Right clicked
Select View Variable

Get following error:

Network connection shutting down due to read error.
Connection failed.
Reconnecting in 10 seconds...

Reconnects with out issue.

(Mom's Spaghetti)

**Comment by lollerderby** [comment]
Seems to happen for boiled spaghetti too.

**Comment by WJohn** [comment]
But it DOESN'T happen with copypasta.

**Comment by Anonus** [comment]
>copypasta is better

**Comment by Jordie0608** [comment]
Likely same bug as #10881
