### ISSUE TITLE
Hundreds of mobs appearing in nullspace

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11434]
Not sure what caused this, but there were like tone of artificers and xenos, and drones in nullspace in a round on bagil just now.
Only thing I can think of that caused it was xenobio had a chaos carp and was having it shoot bolts of change at stuff to get a xeno. Might have been from the gold slimes as well. Some of the mobs were generic animals. Mobs all lagged the server to hell

**Comment by WJohn** [comment]
To my knowledge nullspace stuff is usually high priority.

**Comment by phil235** [comment]
can't seem to reproduce it with chaos carps or gold slime extracts.

**Comment by Jalleo** [comment]
This might be due to qdel.

**Comment by Incoming5643** [comment]
Chaos carps can't actually produce artificers

**Comment by lollerderby** [comment]
Yeah, just happened again on bagil, there were some xenobio magicarp shenanigans going on as well as revenants and somehow tons of mobs were in nullspace.

**Comment by bgobandit** [comment]
related to https://github.com/tgstation/-tg-station/issues/5785?

**Comment by Shadowlight213** [comment]
It looks like #11464 narrowed down the cause.
"Spawning a nob with a gold slime core puts every mob it didn't spawn in nullspace.

**Comment by Incoming5643** [comment]
Caused by #11277 

One of every type of mob is new'd to check to see if it can be summoned by gold slime reactions (bad)
Then all the mobs that didn't get picked remain spawned but without a loc in nullspace (very bad)

**Comment by Miauw62** [comment]
There's a trick that lets you read variables off of types without
initializing them. Ask some of the other maintainers
Op 29-aug.-2015 23:04 schreef "Incoming5643" <notifications@github.com>:

**Comment by Shadowlight213** [comment]
Needs reproducing can probably be removed

**Comment by phil235** [comment]
@Jordie0608

**Comment by Jordie0608** [comment]
I get why it'd happen, but I still can't reproduce this.
