### ISSUE TITLE
You can extract health implants from people via surgery

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11435]
When the cloner scans you it puts a health implant in you, that lets it keep track of your health. turns out you can remove this implant with surgery, which I'm pretty sure isnt intended.

**Comment by Mark9013100** [comment]
AFAIK, the health implant only monitors the reciever's health from the cloning console.

**Comment by GunHog** [comment]
Yes, it is a good way for a Geneticist to know when to clone you remotely.

**Comment by Core0verload** [comment]
Is there any bugs with removing health implants? If not, it is a 100% feature.
