### ISSUE TITLE
Revenants sometimes randomly spawn in Nullspace

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11442]
Steps to reproduce:
1. Have the revenant event spawn a revenant
2.  Get shoved into the body but everything is dark.  Can't move, can't interact, nothing.
3. Aghost and watch your ghost magically teleport to the arrivals shuttle.
4. Be unable to follow the revenant in the follow verb for ghosts and be unable to play the antag but it's in the twillight zone.

**Comment by WJohn** [comment]
Probably directly related to #11434

**Comment by Shadowlight213** [comment]
This is still happening
