### ISSUE TITLE
Send To on player panel has no cancel

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#11449]
Feature request.

>show player panel
>accidentally click send to button
>no way to cancel, you are now forced to teleport the person somewhere

**Comment by PKPenguin321** [comment]
no wait dont fix this this bug got me an antag token once

just kidding this should really be fixed (although I did get an antag token because of it once) (and i kinda disagree with that not a bug tag)

**Comment by duncathan** [comment]
Why do you disagree? It's not a bug; it's a feature request.

**Comment by PKPenguin321** [comment]
i dont know, it just feels really unintentional
i guess yeah it doesnt classify as a bug, whatever

**Comment by Miauw62** [comment]
certainly a bug.
