### ISSUE TITLE
Swarmer communication states the name of the hearer instead of the sender

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11443]
![whelp](http://puu.sh/jREZw/454e693c98.png)
Swarmer 315 being me, of course.

**Comment by Ergovisavi** [comment]
Yep, known issue. I'll get a PR up for this when I get home after work today.

**Comment by Steelpoint** [comment]
This gets even weirder as this bug also happens if your a ghost, meaning you'll see yourself talking on the swarm channel.
