### ISSUE TITLE
Molotovs and IEDs are ridiculously underpowered.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11452]
MOLOTOVS:
To make: Grab a bottle of vodka and a damp rag, table craft it, light on fire with a zippo, throw.

Get 1 tile of fire that lasts for at most 2 seconds. Awful.

IEDS:
To make: Empty a soda can, fill with welding fuel, put on table alongside cable and igniter. Use to ignite, throw.

Do literally 0 damage to the station, and 1-3 tile radius of fire that lasts half a second. Awful.

I don't see why IEDs were nerfed so hard, if it was because of grief, have the admins handle it. They were actually handy before in revs against security because you could throw them against the windows and maybe eventually break through, while keeping your distance.

Molotovs on the other hand are apparently supposed to be able to accept any fuel, yet they both don't work with napalm *at all* and they do next to nothing with either space beer or with actual vodka (or any other harder beer). This is pathetic. Besides, being able to fill it with any chem you want is worthless since we can literally throw beakers at people to transfer ALL the reagents to them in the exact same way, without losing the beaker.

**Comment by Ergovisavi** [comment]
>Molotovs bad

Instantly lighting someone on fire at range while cranking their fire stacks to 10 plus

Mollies arent about lighting the station on fire I put them in to be used on single targets and they're plenty effective for that

**Comment by WJohn** [comment]
But a flamethrower can also pretty much instantly set people on fire, it can do it to multiple people, and has multiple uses. On top of that, it also greatly increases the surrounding temperature, warding off other people. There's no point in even *trying* to have a fire-stack weapon used on one person, why on earth would you want to set fire to one dude and avoid friendly-fire when the entire NATURE of fire-stacks is to be spread to other people?

**Comment by ninjacha** [comment]
I like this one, someone should buff em

**Comment by PKPenguin321** [comment]
as much as I agree, this seems more fitting for the F E E D B A C K   F O R U M

**Comment by Dorsisdwarf** [comment]
This escaped the brutal scythe of my eternal goal to keep us at <800 issues
