### ISSUE TITLE
All Nano ui broken in byond versions later than 507

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11460]
![bug image](http://i.imgur.com/qCpf37p.png)
Basically this forever on all interfaces that use this method.
I believe it is based on a byond update but it may be due to somthingelse.
ocured in both 507.1286 and 508.1298 after an update from an old version

**Comment by MrStonedOne** [comment]
>I believe it is based on a byond update but it may be due to somthing else.

It would help if you would say what byond version you are currently running.

**Comment by Supermichael777** [comment]
I believe this is a client-side issue fundamental to nano ui if you need any additional details post a list here.

**Comment by MrStonedOne** [comment]
except, it's working for me in 507

So again, tell me the exact version (with the 4 digits after the .) that this is breaking in.

**Comment by Memendia** [comment]
I am on windows 10 using beta and nothing wrong with NanoUI

**Comment by bear1ake** [comment]
Server is 508.1298 (Ubuntu 15.04)
Client is 508.1296 (Windows 8)
Nano UI working fine for me
Server revision is 0e46800fd1e7fadc52572a5fc15b0d72c24a2ad5

**Comment by Supermichael777** [comment]
well flag it as could not reproduce i will try updating again and see if the issue reoccurs

**Comment by optimumtact** [comment]
working for me too

**Comment by Supermichael777** [comment]
even after nano ui updates this still happens. rip me.

**Comment by optimumtact** [comment]
what OS are you using?

**Comment by MrStonedOne** [comment]
[18:03:53] <bauds> i think one guy managed to solve it
[18:04:03] <bauds> he cleared his IE security settings or something

**Comment by Jalleo** [comment]
is this fixed then?

**Comment by tkdrg** [comment]
I assume so, ping me if I'm wrong mso
