### ISSUE TITLE
You can teleport other swarmers away.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#11468]
Via the Ctrl-Click mob teleporter.

**Comment by Ergovisavi** [comment]
This is a weird one. I intended to leave this in as a feature so that one swarmer can teleport another swarmer in an emergency... but if it ends up being swarmers griefing swarmers, I'll remove it.

**Comment by PKPenguin321** [comment]
leave it in so that i can shoo away greedy swarmers that try to eat my metal
