### ISSUE TITLE
Gold slime cores fill the mob list with mobs in nullspace

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11464]
It looks like, for each use of a core, it puts one of each mob it didn't spawn, or couldn't spawn, in nullspace.

**Comment by Anonus** [comment]
I'm not sure how many mobs it nullspaces if you inject plasma as I haven't seen that happen but it very well might be a lot.

**Comment by MrStonedOne** [comment]
dupe https://github.com/tgstation/-tg-station/issues/11434

**Comment by Dorsisdwarf** [comment]
Closed for dupe
