### ISSUE TITLE
Librarian's desk does not emit light

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11463]
The librarian desk sprite clearly has a lit candle and glowy shit on it, yet if you remove all the lights in the librarian's backroom, no light is produced. Not at all. Zero.

This is clearly a huge bug.

**Comment by Marflowerose** [comment]
Also applies to hydro tables AFAIK.

**Comment by WJohn** [comment]
Frankly I think we should fix #9471 first because otherwise we'll end up with a full bright spot in the back room and for all the hydro trays, and that'll be absolutely hideous.

**Comment by freerealestate** [comment]
feature request

@Dorsisdwarf go on, do your duty
