### ISSUE TITLE
Items on tiles can sometimes take up the entire tile

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#11465]
rev: 137f0e0baf43c4d33430c037fc747aec9943015b 

Not quite sure how to reproduce, but in breaches it can happen that even small items like cigarettes are 'highlighted' even when not directly mousing over them. 
In the end, you have to either remove all items from the tile or alt click the tile to fix the breach (to be able to hit 'space').

**Comment by Actionb** [comment]
Correction... this isnt exclusive to items on space tiles. 
![items](https://cloud.githubusercontent.com/assets/10028803/9563892/e6ba0e78-4e93-11e5-8280-27362fd262d3.JPG)

Red dot marks the location of my mouse cursor, aiming for the very top left corner.

**Comment by phil235** [comment]
@RemieRichards Could it be linked to your changes with clicking items in backpack storage?

**Comment by Anonus** [comment]
Looks like fire burning items off people doesn't update it right.

**Comment by Actionb** [comment]
Off the top of my head I remember three incidents where I became aware of this bug.
Two indeed involved a fire: the one in the picture and another where a lighter was left on the ground to light plasma on fire, that eventually burned through the floor.
The other one was after a bomb littered a tile with tons of shards, rods and other items.

**Comment by Jalleo** [comment]
Next time it occurs mark down what that item is and tell a coder if they are on.

**Comment by Lumipharon** [comment]
If something destroys the container, it drops the item with it's full tile sprite thing.
IE: bombs and fire.

**Comment by RemieRichards** [comment]
Bombs don't trigger it anymore, that was fixed and then people stopped reporting it from bombs, so I can only assume it's fixed (it also worked in my testing so, you know)

It's fire, it obviously doesn't remove items correctly.

**Comment by Actionb** [comment]
Okay I think I have a found a reliable way to reproduce this...
Syringes fired by an exosuit syringe gun always occupy the entire tile.
