### ISSUE TITLE
Virology symptoms do not mix when placed in a beaker together. 

### ISSUE THREAD

**Issue by Bluespace** [tgstation/-tg-station#11482]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): Server revision compiled on: 2015-08-29
a72441559375317a72db3f9c4d33c4c887b221fd 

##### Problem Description #####

Virus samples do not mix together in blood samples.

###### What did you expect to happen? ######

Symptoms should begin to stack up, creating a custom made disease.

###### What happened instead? ######

They just replaced each other when placed in the blood beaker.

###### Why is this bad/What are the consequences? ######

You cannot create custum diseases. 

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Use plasma/unstable mutagen to get a desired symptom (worth noting that using virus food/mutagen/plasma DOES cause another symptom to appear on top of what you have already.)
2. Use synap to cut down undesirable symptoms.
3. Use your sneezing + whatever symptom bottles together to mix the blood.
4. Rather than getting sneezing plus symptom 1 AND symptom 2 mixed together, the most recently added symptom simply overwrites whatever is in the blood.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####

Wizard. Summon events + guns happened.

##### Anything else? #####

Supplementary video. 
Ignore the loud and obnoxious dubstep in the background. I didn't realise sound was recorded.
http://puu.sh/jTQDO/508d017277.mp4

**Comment by Marflowerose** [comment]
Huh, I was able to do viro yesterday just fine.

**Comment by Durkel** [comment]
I can confirm it's fucked, Had the same problem with the last injected symptom overwriting the previous one and not mixing.

**Comment by newfren** [comment]
You can still do virology ok by stacking up symptoms on top of each other and creating dupes but it sure makes it a fucking pain in the arse at the end when you're trying to get a specific disease, and it also makes the virus crate entirely useless.
