### ISSUE TITLE
Incinerator Output Pump is unpowered

### ISSUE THREAD

**Issue by joonoro** [tgstation/-tg-station#11502]
The pump leading to space from the incinerator/turbine is turned off when the game starts (I assume it's supposed to default to on, IIRC), and attempting to turn it on gives a message like "the pump seems unpowered." This makes it unusable. Bug has been in for a while.

**Comment by Actionb** [comment]
The pump is off because it is in 'space' and not in area with an APC - no power.
The various injectors in space are also off. Some weeks ago they were already off, then some change happened and they were on, now they are off again.
Can't the turbine area be expanded to include the pump + injector?

**Comment by Shapsy** [comment]
May as well just remove that pump, it's pretty redundant anyway

**Comment by Metacide** [comment]
Can easily be fixed by setting use-power var to 0.

**Comment by joonoro** [comment]
I'd prefer it if it wasn't removed, it's the only way to space gas from the output loop without piping it back into the chamber and venting it entirely. That and also because as I discovered the other day the waste pipe that the pump is connected to is easy to modify to pipe the exhaust fumes from the turbine back into the room.

**Comment by PKPenguin321** [comment]
bump because this is still broken
i'd recommend adding the tile the output pump is on to the incinerator area, but that's just me

**Comment by Metacide** [comment]
@PKPenguin321 - I guess that also lets you repair / replace that pump if needed, rather than var-edit trickery which can never be replicated properly ingame.

**Comment by duncathan** [comment]
Why is the pump in space anyway
That's always bothered me as a tech

**Comment by PKPenguin321** [comment]
that's actually a really good point
why don't we just move the pump to inside
