### ISSUE TITLE
All buttons on the station do not work

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11501]
Problem Description:  It looks like none of the buttons on the station are working.  Medbay lobby, chaplain mass driver, chaplain crematory, toxins ignition switch, nothing.

What did you expect to happen: The buttons to work

What happened instead: They do nothing when you click on them.

Why is this bad/What are the consequences: Large portions of the game are unplayable simply because toxins scientists can't start a burn mix, and chaplains can't incinerate changelings.

Steps to reproduce the problem:
1. Start up game
2. Press buttons listed above
3. Watch them do nothing

Server: Sybil

Possibly related stuff: I checked all the button IDs and they are not the cause, I have no idea what is.

**Comment by Supermichael777** [comment]
@Core0verload

**Comment by Core0verload** [comment]
WTF? I tested it, I tested ALL OF IT!

**Comment by duncathan** [comment]
@Core0verload 
Cheridan once told me that we all get one free pass on causing game-destroying bugs before he starts removing fingers
Looks like you've used yours :^)

**Comment by Marflowerose** [comment]
So a virologist is currently well and truly fucked? Can't mix viruses or leave office :^)

**Comment by Core0verload** [comment]
Okay. It's not a bug, it's a feature! Use assembly igniters and burn lings in toxin fires! Disassemble buttons, remove controllers and connect them to signallers to get a working remote button!

And virologist is fine, his buttons are working.
