### ISSUE TITLE
Swarmers can breach atmos in Engineering maint 

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#11500]
http://i.imgur.com/ubMnpFF.png?1

For clarification, this is just under maint bar under the mining dock.

**Comment by WJohn** [comment]
What are they not supposed to cause atmospheric leaks?

**Comment by Zilenan91** [comment]
They are not supposed to normally be able to do that, they are code restricted from busting any walls or windows within 1 tile of space, and I think the issue in that specific place is that there are floor tiles in space, and the game registers the area as being safe to break when it in fact is not.

**Comment by duncathan** [comment]
These issues might be able to be solved by checking not only for space tiles, but airless tiles (the hard-pathed variety, not just any ol' tile without air)

**Comment by Dorsisdwarf** [comment]
Maybe they can be solved by checking for the space area as well as the space tile.

**Comment by Ergovisavi** [comment]
I'll probably end up checking for the space area, yes. Would solve most problems.

**Comment by Shadowlight213** [comment]
@ergovisavi was this fixed?

**Comment by Zilenan91** [comment]
It got fixed as far as I know

**Comment by Shadowlight213** [comment]
@zilenan91 close the issue then
