### ISSUE TITLE
deaf people can hear cleanbots boop

### ISSUE THREAD

**Issue by cookingboy3** [tgstation/-tg-station#11503]
I got chemically deafened (somehow) and could magically hear a cleanbot making booping noise, but I was unable to hear my own agonizing screams

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/machinery/bots/cleanbot.dm#L154
Cleaning bots booping noise message uses visible_message() instead of audible_message()
