### ISSUE TITLE
Swarmers can eat gang tags

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11517]
What happened: I was swarmer during gang. I CTRL-clicked a gang tag on a wall I was trying to eat. The gang tag disappeared. Got no resources for it, though. I don't know whether it still counted for the gang.

How to replicate: Be swarmer, find graffiti or gang tag on wall, CTRL-click

Why this is bad? WHY DO YOU THINK THIS IS BAD

**Comment by Ergovisavi** [comment]
Not an issue. Drones can and are allowed to do the same thing. If you have a problem with this, you kill the drone. If a swarmer is eating your gang signs, destroy them.

**Comment by duncathan** [comment]
>The gang tag disappeared. Got no resources for it, though.

Isn't this an issue though @Ergovisavi?

**Comment by Dorsisdwarf** [comment]
Aren't you supposed to only be able to eat things with a metal content?

**Comment by Ergovisavi** [comment]
You're confusing "Destruction" with "I am gaining resources from this object". When you see the zappy sparks, you aren't gaining resources. You're destroying the object, in the hopes of rendering it into resources. Swarmers can destroy lots of things, but they're just calling ex_act(3) on the thing when they zap it, which breaks down most structures into metal.

**Comment by Xhuis** [comment]
feature

**Comment by bgobandit** [comment]
it's graffiti though, it's not a structure that can be deconstructed, it is literally just graffiti. it makes no logical sense and it's shitty design too

**Comment by Marflowerose** [comment]
The great masters to come don't want to see shitty gang tags in their new station, which is why swarmers are able to clean blood aswell. If swarmers wouldn't be able to clean tags, they'd actively be helping gangs by making every room zone easy access.

**Comment by Razharas** [comment]
@Firecage said he tested it and its already fixed
