### ISSUE TITLE
Some swarmer bugs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11516]
- Trying to consume an intercom just deletes it immediately

- Regular clicking on a r-wall says it's far too strong to destroy, but ctrl-clicking goes through the process and you can even get down to a girder

**Comment by Ergovisavi** [comment]
That second one isn't technically an issue. It's too strong to destroy by SMASHING into it, which has nothing to do with your Ctrl+Click abilities.

Guess I can look at the first one.

**Comment by Marflowerose** [comment]
The Rwall is so random and laborious that you'll get carpal tunnel before getting through them.
