### ISSUE TITLE
Ghosts can buckle mobs to beds/chairs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11523]
What happened:

Grandmaster Honk is buckled to the roller bed by Fortune Ray!
DEAD: Fortune Ray says, "Uhhhhhhhh"

How to reproduce:

1) Be ghost
2) Find some poor mofo over a bed or chair
3) Fly next to them
4) Buckle them
5) The above message is indeed visible to the player who gets buckled

Why is this bad: Standard metagaming/immersions/potential to fuck with attacks in progress by buckling one party. Also, the possibility of ghost incubi which is horrifying.

**Comment by Razharas** [comment]
ITS LIKE MORGUE TRAYS ALL OVER AGAIN

**Comment by lollerderby** [comment]
Improve don't remove.

**Comment by Bluespace** [comment]
Remove spooky goasts

**Comment by Dorsisdwarf** [comment]
Ergo you said this was a feaaatuuuuuure

**Comment by AlexCrimson** [comment]
Oh shit time to griff before this gets fixed

**Comment by PKPenguin321** [comment]
corpsebuckling Ouija boards when

**Comment by Razharas** [comment]
I FIXED IT PRAISE BE PRAISE BE
