### ISSUE TITLE
Energy dagger has no sprite whatsoever.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11522]
When you turn the energy dagger, it both has no inhand and doesn't even have an icon in your inventory or on the ground. It literally turns completely invisible, and is stealthier to have it on than not.

Further investigation of the PR shows that miauw never actually included any .dmi with the sprites. So there's your problem.

@Miauw62

**Comment by Xhuis** [comment]
god fucking damn it meow

**Comment by Core0verload** [comment]
Fixed. Close it.

**Comment by Dorsisdwarf** [comment]
Fixed in #11550
