### ISSUE TITLE
Watchlist option in investigate verb doesnt work

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11539]
Pressing the watchlift option doesn't do anything at all. This prevents admins from being able to put offline players on the watchlist as the player panel will not work if they are offline.

**Comment by Jordie0608** [comment]
Just tested with Niknak, works fine locally on latest master; this is some server issue.

**Comment by Jordie0608** [comment]
[05:36:52]GAME: SQL ERROR during adding new watch entry. Error : [Unknown column 'adminckey' in 'field list']
@MrStonedOne

**Comment by Shadowlight213** [comment]
So it's just me. Fun.

**Comment by MrStonedOne** [comment]
My b, I didn't look at the sql change log close enough, and missed something
