### ISSUE TITLE
Slaughter demon summoned by a wizard doesnt get the bloodcrawl spell

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11540]
@xxalpha 
It turns out that the demon is given the spell during the admin only event, but not when spawned by a wizard.
This basically leaves them stuck in jaunt without admin intervention.

**Comment by Lumipharon** [comment]
To add to this, as I suspect it was caused by the same thing, but when the admins manually gave us bloodcrawl, we were still slow on exiting blood - dunno if this happens when the demons are admin spawned though.

**Comment by Jordie0608** [comment]
The most sensible thing here would be to give the spell in slaughter demon's New() instead of each instance where it could be made.
