### ISSUE TITLE
Nar-sie is making normal floor tiles instead of cult floor tiles.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#11557]
Old god is losing it in his old age and forgot what kind of tile to lay down.

**Comment by WJohn** [comment]
Misclicks, whoops!

**Comment by xxalpha** [comment]
Dupe? This is a known bug.

**Comment by duncathan** [comment]
Yeah I'm almost certain this is a dupe

**Comment by CosmicScientist** [comment]
Because no-one else went to prove it's a dupe (it takes five seconds with the search box): #10180

**Comment by Dorsisdwarf** [comment]
Closed, dupe of #10180
