### ISSUE TITLE
Lizards who use black slime mutation potions become humans temporarily

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11558]
What happened: I was a lizard and injected myself with mutation potion from a black slime. Normally the process turns you into a part-slimey being before going full slime. However, this seems to have been coded before lizardpeople existed, resulting in tails and appendages and lizardness magically vanishing:

![liz](http://i.imgur.com/tmPT9IE.png)

How to reproduce: Be lizard, inject yourself with black slime mutation potion, you won't believe what happens next

Why this is bad: MY IMMULSIONS, despite the fact that this is a positive change for humanity, fuck lizards

**Comment by Xhuis** [comment]
no great loss
