### ISSUE TITLE
Bibles and Runes: Not Revealing

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11559]
Simply put, revealing of runes used to be attached to the null rod, and it didn't have a chaplain job check...this was eventually moved to the BIble.

There's just one problem; hitting a rune (or near it) with the Bible does nothing...likely because the revealrunes() proc has checks in itself for the null rod, as opposed to the Bible.

**Comment by Core0verload** [comment]
@phil235, fixed.
