### ISSUE TITLE
Datastructure and NTSL is DOSing server

### ISSUE THREAD

**Issue by bear1ake** [tgstation/-tg-station#11567]
Server: BYOND 508.1296 & 508.1298 (Windows 8 and Ubuntu 15.04)
Client BYOND 508.1296
Used script: https://tgstation13.org/wiki/NTSL_Scripts#Less_Annoying_Job_Indicator
I haven't runtime logs, but i'll get it tomorrow, if needed.
Revision: 0efc54e
I think, it related to  #11396

**Comment by MrStonedOne** [comment]
Holy fucking shit is this a shitty issue.

What happened?

What didn't happen?

Can you give any info other here a link to something, its broke?

like holy fucking shit.

**Comment by bear1ake** [comment]
Consended runtimes: https://dropmefiles.com/0eKJI
Raw logfile: https://dropmefiles.com/IjtEY
Screen: 
![10](https://cloud.githubusercontent.com/assets/9455174/9663501/bdd3d470-529f-11e5-8320-3e9e283c445e.png)
DD isn't responde to commands about minute, and i close it by task manager

**Comment by Miauw62** [comment]
remove ntsl 2k15

**Comment by Ergovisavi** [comment]
R E M O V E N T S L 
Always been terrible, always will be.

**Comment by MrStonedOne** [comment]
@RemieRichards

**Comment by MrStonedOne** [comment]
>runtime error: list index out of bounds
>proc name: Top (/datum/stack/proc/Top)

If you had just said that, and nothing more...
just that
The runtime.
This would have been figured out a lot sooner.


@RemieRichards redid some data structures, and it looks to be a bug there.

**Comment by RemieRichards** [comment]
```. = stack[stack.len]```
I have literally no idea how that's possible.
it's own len is longer than it's index bounds?
element 1, is 1 (the first bound)
the final element, is ```.len``` (the last bound)

**Comment by RemieRichards** [comment]
Alright, it's an issue with ```is_empty()```, when I changed it to the Syntax Giacom wanted I messed up a sign, I'm just going to revert to the original syntax, ```?``` is perfectly understandable.
