### ISSUE TITLE
Atmos mystery radiating heat (Heat proliferating through glass)

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11563]
I made a neat turbine setup in atmos where north side would get tons of regular air and south would have scrubbers syphoning it and moving the air via pipes back to north side. I tested out with freezer and heater if gas temperature would affect the turbine performance in any way. When I tried to heat the gases inside the pipes, I noticed I was taking burn damage and the areas with the pipes were getting quite hot. I don't know if this is a bug or a feature but I assumed that Insulated Pipes were removed since regular pipes would become insulated by default. 

Edit. The turbine setup was airthight so the hot air was not escaping from that.

**Comment by Jalleo** [comment]
That sounds like you were using the heat exchange pipes.

**Comment by Marflowerose** [comment]
No science doors, no false walls, no open canisters.

**Comment by Jalleo** [comment]
were there normal airlocks connected to the heated area?

**Comment by Marflowerose** [comment]
No.

**Comment by Jalleo** [comment]
what type of pipe did you use standard or the heat exchange ones?

**Comment by Marflowerose** [comment]
Normal pipes, not heat exchange.

**Comment by duncathan** [comment]
Yeah uh there is no mechanism for a regular pipe to be radiating heat; all that code is under heat heat exchange pipes. While I expect this is user error, as Jalleo's trying to discern, I will say that if this is actually a bug then it funnily would have affected insulated pipes, too. Insulated pipes and simple pipes were actually identical code-wise.

**Comment by Marflowerose** [comment]
Trying to recreate it, seems the pipes did not radiate heat, though I'm still not sure what did it. Wish I had taken a screenshot. Feel free to close this or add higgs buggson.

**Comment by Lumipharon** [comment]
Was that the setup with the turbine just covered in regular glass windows?
Do non r-windows keep out heat? I ask because that change was made to glass airlocks to only block heat transfer if you use r-glass. Or something.

**Comment by Shapsy** [comment]
Wow how convenient, I was actually really impressed when I saw it and I took a snapshot of the main part of it http://puu.sh/jYmZ4/06d74e971d.png

**Comment by Actionb** [comment]
Heat spreads through glass. You should knot that, marflow. You're fired from atmosia. Good day, sir.

**Comment by Jalleo** [comment]
Yep okay this can get closed

**Comment by Marflowerose** [comment]
@Actionb 
Wait, so metal wall doesn't radiate heat but glass does?

**Comment by Lumipharon** [comment]
that's because fastmos is an unworkable mess.
Had a round just now where a plasma fire happened it science - got quickly repaired, but even with the silicons working on bringing atmos back to normal, it was a horrible mess of space wind for the next hour.

**Comment by duncathan** [comment]
I'm willing to bet that it's because of the border objects

**Comment by Jalleo** [comment]
@duncathan it was the use of standard glass since heat does transfer through glass.

**Comment by Jalleo** [comment]
For reference https://github.com/tgstation/-tg-station/blob/45a9e138b2c368c88187a0da513a9148aa9bd146/code/game/objects/structures/window.dm#L433
