### ISSUE TITLE
Canisters(?) sometimes stop processing plasma and oxygen

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#11566]
Sometimes oxygen and plamsa at high temperatures in pipes and canisters just stop reacting for some reason
Their temperature would very slowly drop, but the oxy, plamsa, co2 and burntwhatever vars will stay the same
Not sure how to reproduce, it happens randomly, happened 2 times on sybil at thunderdome the day this issue is made

**Comment by Razharas** [comment]
@Aranclanos

**Comment by Supermichael777** [comment]
If this actually happens I would expect it to have something to do with automatic atmos throttling or the admin killswich.

**Comment by duncathan** [comment]
@MrStonedOne think this had anything to do with dwait?

**Comment by MrStonedOne** [comment]
doubt it, but i'll test.

It *could* be a floating point rounding error, but i doubt it, those would happen at much higher numbers.

**Comment by as334** [comment]
It's because pipenets don't call react(). PR to fix will be up soon.
