### ISSUE TITLE
The drone shell dispenser is 3 tiles long but only 1 of the tiles is dense.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11576]
What the title says. Only the leftmost tile is dense even though the sprite suggests that all 3 tiles should be dense.

![droneshell](https://cloud.githubusercontent.com/assets/7812993/9680368/b638f928-52f6-11e5-9c16-f4bdb0c1844b.PNG)

**Comment by Supermichael777** [comment]
multitile structures suck if they have only on real part.

**Comment by WJohn** [comment]
Well I mean the experimentor and the grav gen are also multi-tile machines, despite note really having any individual parts. Maybe someone can look into how that was done and see if they can do that here, too.

**Comment by xxalpha** [comment]
The experimentor is only one tile dense as well. The gravity generator is multiple objects.

**Comment by Xhuis** [comment]
Intentional, but I _have_ been meaning to change the sprite to a 1-tile one for some time. This is not a bug, however.

**Comment by MrStonedOne** [comment]
IT is a bug.

You can control tile dense-ness on mutitile objects easily. Its called bound_size.

As long as its a multiple of 32, it won't trigger pixel movement.

**Comment by tuypo1** [comment]
I dident even know we had that machine
