### ISSUE TITLE
Few Errant Mineral Amounts

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11584]
At one stage, a sheet of anything contained 3750 worth of materials...now that is down to 2000.

That said, there's a few errant numbers left in the code that are still 3750 (and reference a single sheet), when it should be 2000--this can lead to duplication of materials or someone winding up short of materials when it normally only was meant to require 1 sheet.

list:
- Table Rack Parts (https://github.com/tgstation/-tg-station/blob/cbe76ea2c034a6a9f2a1f1adad6ce84d279f73dd/code/game/objects/structures/tables_racks.dm#L484)
- Pickaxe (https://github.com/tgstation/-tg-station/blob/271b7344f5eb53b80743d06a9bee82c47642f1d6/code/modules/mining/mine_items.dm#L68)
- Designs Information ( https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/modules/research/designs.dm#L27)
- Diamond Drill (https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/modules/research/designs.dm#L144)
- Borg Diamond Drill (https://github.com/tgstation/-tg-station/blob/1c05fbcf6ab4f6041a6fa6e3035ec654be590eea/code/modules/research/designs/mechfabricator_designs.dm#L673)
- The RD Console has a lot of hardcoded references to 3750 amounts being one sheet, meaning that if you insert a sheet and eject it, you end up losing materials (https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/modules/research/rdconsole.dm)

**Comment by Kromgar** [comment]
What the fuck is Carbon Dioxide?
