### ISSUE TITLE
NTSL crashing server, again

### ISSUE THREAD

**Issue by bear1ake** [tgstation/-tg-station#11583]
Revision: 7203e33
Runtime raw logs: https://dropmefiles.com/d7Bye

**Comment by ike709** [comment]
@RemieRichards did you break something else

**Comment by Menshin** [comment]
In Expressions.dm, L277, the check ```while(opr.Top()) ``` is never true (rather only true for *null* values on the stack).

```opr.Top()``` either returns the operator on the opr stack or *STACK_UNDERFLOW* (-2) if the stack is empty.

In the same vein, two lines below, the check for damaged stack  ```if(val.Top()) ```  has the same problem.

The *Precedence()* check at L231 may also not working correctly for an empty operator stack.

**Comment by bear1ake** [comment]
Fixed by MSO
