### ISSUE TITLE
Janicart can't be ridden anymore

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11586]
Steps to reproduce:
1. Have keys in hand and attempt to mount janicart
2. have your sprite move on to it but not buckle and can't drive it
3. cry
4. @Razharas  maybe ???

**Comment by ike709** [comment]
Priority: Honk

**Comment by PKPenguin321** [comment]
same with secway
i think buckling is broken in general

**Comment by Lumipharon** [comment]
buckling in general does not work.
