### ISSUE TITLE
Sensors set to binary cause text overlap when the suit sensor console window is expanded.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#11597]
![](http://puu.sh/k18Cz/aaec6dd45e.png)

**Comment by Dorsisdwarf** [comment]
@francinum 
Do you mean that the text wraps around if you make the suit sensors window narrow?

If so, this is Unresolvable

**Comment by francinum** [comment]
#10574
Crew monitoring: If the window is wide enough the health indicator will expand to show full health data (if available).

**Comment by Jordie0608** [comment]
Closing as #11774 is clearer.
