### ISSUE TITLE
Black powder explosions are not logged with explosions

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#11601]
We had a traitor apply six patches of 45 u black powder to a guy and then one patch of 45 u napalm and then lit him on fire making a huge ass explosion.  Now, it was sketchy because this huge blast does not appear in the bombing list, it doesn't appear anywhere.  It was just  a random explosion to admins.  We really should have a place that tracks blackpowder somewhere because god damn, unlogged almost max cap explosions is not a good thing to have so this is kind of priority critical.

Steps to reproduce:
1. Just get a bunch of black powder to blow up in a huge explosion somehow, be it using a human as a vessel or just some way.
2. Watch the blast tear apart a department as if a max cap tank transfer valve went off
3. Be an admin and have no fucking clue how and what just exploded.
4. Panic and ask the players who died and such.
5.  Get this shit logged

**Comment by Iamgoofball** [comment]
Wait, hang on. Which one of these 2 is this:

BLACK POWDER does not state that the explosion was a BP one, but still logs an explosion

There was no explosion logged at all, just a sound

**Comment by Anonus** [comment]
Bonus; if you don't know who did it, there's no effective way to find OUT who did it, even if the explosion itself was logged.

**Comment by Niknakflak** [comment]
What I mean is, of course it logs the explosion, like when it goes boom (4, 7, 16) or whatever but it doesn't log in the bombing list, it doesn't give a message to admins (like it does for a gold slime or life reaction) it doesn't log what did it is what I mean.  The first one you mentioned goofball.

**Comment by Miauw62** [comment]
potassium+water grenades (which can also be maxcap) are also probably not logged.

**Comment by Dorsisdwarf** [comment]
I'm pretty sure chemical grenades are logged on activation?

**Comment by Niknakflak** [comment]
I'm pretty sure they are. Maybe it's anything when it comes to using humans a container to trigger the blast need to be logged in some way.  Human bombs.

**Comment by Iamgoofball** [comment]
This is an easy fix, just add a admin log on the on_reaction() for nitroglycerin, water+potassium, and black powder

**Comment by phil235** [comment]
Except on_reaction() doesn't have user as an argument so logging the perpetrator's key isn't that easy.

**Comment by Dorsisdwarf** [comment]
@Iamgoofball fix ur shitzzle

**Comment by Niknakflak** [comment]
Still not fixed @iamgoofball

**Comment by optimumtact** [comment]
Fix it yourself

**Comment by duncathan** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Saving it for friday

**Comment by PKPenguin321** [comment]
A fix 7 months in the making
