### ISSUE TITLE
Magnitis and Space Retrovirus diseases are impossible to cure with chems.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#11617]
Both Magnitis and the Space Retrovirus appear to be impossible to cure with their suggested chems (iron and mutadone). Even 100u of each chem will do nothing.

**Comment by Supermichael777** [comment]
no cure chance(honk)

**Comment by Tokiko1** [comment]
Is this really not a bug? Then atleast the med scanner descriptions should be updated that these diseases are incurable.

**Comment by Shadowlight213** [comment]
@supermichael777 I don't see anywhere in the code that implies that it would be incurable.

**Comment by Supermichael777** [comment]
code/datums/diseases/retrovirus.dm

    /datum/disease/dna_retrovirus/New()
    ..()
    agent = "Virus class [pick("A","B","C","D","E","F")][pick("A","B","C","D","E","F")]-[rand(50,300)]"
    if(prob(40))
    cures = list("mutadone")
    else
    restcure = 1

Because it cant just be annoying, it has to be assholessly annoying

**Comment by Shadowlight213** [comment]
@Supermichael777 That just means that it has a 40 percent chance of being cured by mutadone, else it is cured by resting.

**Comment by phil235** [comment]
Space retrovirus is curable by rest in 40% of cases so it's not a bug.
Magnitis is indeed uncurable because it lacks its disease_flags lacks the CURABLE bit.
