### ISSUE TITLE
Singularity constantly renews sand on asteroid, but also rips sand off the floor.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11621]
This basically creates an endless loop where the singulo creates gigantic droves of sand, sucks it in, eats the floor, and creates more. Not only does it make an absolutely gigantic amount of energy, but thousands of items get thrown and deleted this way extremely frequently, might be a performance issue. Easiest fix would be to prevent the singulo from turning asteroid sand into its "dug" state.

**Comment by Xhuis** [comment]
ahaha 10/10

**Comment by Jalleo** [comment]
Oh god dangit so after it goes past some sand it gets refilled?

**Comment by bgobandit** [comment]
where the fuck is the FUCK tag

**Comment by Miauw62** [comment]
boty 2k15
