### ISSUE TITLE
Atmos is broken at roundstart

### ISSUE THREAD

**Issue by joonoro** [tgstation/-tg-station#11624]
Atmospherics is broken at roundstart, there is no air flowing in or out of the N2, O2, or Air supply in atmosia (the harmful gas tanks are also broken). All the gas flow meters to the tanks show 0 kPa. Distro loop is at 600 something kPa with a 50/50 mix of O2 and N2. There is no new air moving into distro.

![broke](https://cloud.githubusercontent.com/assets/5191426/9712209/c93a7e36-5551-11e5-8876-1e0d5903d147.png)

**Comment by Jalleo** [comment]
Tanks setting may be on hold if not dear god after a day of no action the station will run out of air.

**Comment by duncathan** [comment]
Fffffuuuuu
