### ISSUE TITLE
Transform sting useless.

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#11628]
The transform sting is useless now, and is bound to get a ling killed quite quickly. Considering after you use it, it takes forever before you can use other ling abilities.

**Comment by Dorsisdwarf** [comment]
Can you detail the change which made transform sting useless? Why it's effect makes it useless? When making an issue like this, it's best to frame it so that people in, say, six month will know exactly what you're talking about.

**Comment by Supermichael777** [comment]
why the hell does this cause the ling genetic damage?

**Comment by Miauw62** [comment]
i literally didnt change transform sting except for making it use the same transform proc as my revamped ling transform.

transform sting is a shitty meme sting and should be removed, but hey.

**Comment by Zilenan91** [comment]
This should go into feedback on the forums.

**Comment by phil235** [comment]
Can't reproduce. Transform sting works fine and doesn't cause any runtime.

**Comment by Dorsisdwarf** [comment]
F E E D B A C K F O R U M

Trans-sting is working as intended right now
