### ISSUE TITLE
Statement issue with start now server verb

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#11640]
Before the game has initialized if you try to start the server it reports that the round has already started when it clearly hasn't this should be fixed to say that its not initialized and wont work until that is complete.

**Comment by duncathan** [comment]
"Initializations complete"
wait for it...
"Welcome to the pre-game lobby!"
Can't start until you're in the lobby.

**Comment by Jordie0608** [comment]
https://github.com/tgstation/-tg-station/blob/889643deaea6d17e3fbb9e341f94aab7e81c3da8/code/modules/admin/admin.dm#L508

The ticker doesn't get to PREGAME until the setup is done. Simple to change the message or add another check.
