### ISSUE TITLE
Borgs are counted when checking for escape alone objective

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11644]
Apparently borgs are causing people to fail escape alone, when they aren't supposed to count.

**Comment by Jalleo** [comment]
Last i checked they arent counted

**Comment by Dorsisdwarf** [comment]
unless silicons are a special mind role, then that code doesn't discount cyborgs, only ais and pais.

**Comment by xxalpha** [comment]
It should just be silicon.

**Comment by Shadowlight213** [comment]
It should discount borgs though.
