### ISSUE TITLE
Remove NTSL

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#11647]
Or fix it, I guess, but it can do bad stuff to the server right now.
Details will not be posted if you've been in coderbus recently, you know what's wrong and how bad it is.

**Comment by optimumtact** [comment]
This is never going to be resolved satisifactorily

**Comment by Anonus** [comment]
Removing NTSL is a solution that fixes the issue related to it.

**Comment by Chnkr** [comment]
Don't allow fresh players to use NTSL, problem solved.

**Comment by Aranclanos** [comment]
if I start a new server all players are new players

**Comment by Anonus** [comment]
Not letting new players make scripts is also a really bad solution because what if some old player gets disgruntled and goes 'now, to ruin'
