### ISSUE TITLE
Blobs and Reagent Transfers

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11660]
This may be me looking at it wrong, but it doesn't seem that there's actually any way to reduce the damage of blobs; wearing a full space suit reduced skin ripper's damage from 25 to 23.

Being naked or in a full space suit had almost negligible effects on the total damage skin ripper smoke from floating blobs did (~3-5 either case).

Is there something wrong here or is this working as intended?

@phil235

**Comment by Marflowerose** [comment]
As I recall, some fire blob also burns through atmos/CE suit as if it doesn't give any protection. 
[Obligatory mention about goonchemblobs being unhinged]

**Comment by phil235** [comment]
@Fox-McCloud I think it's a problem with how I calculated touch protection.

**Comment by phil235** [comment]
Cannot reproduce. Skin Ripper blob does the correct brute and stamina damage against CE hardsuitn that is only 51% of total damage. Permeability protection proc is working correctly, and all hardsuits seems to have the correct permeability coeff.

@Fox-McCloud What kind of hardsuit did you use?

**Comment by duncathan** [comment]
He said space suit; if he actually meant that it could explain why there was so little damage reduction, since IIRC space suit has very little armor.

**Comment by Fox-McCloud** [comment]
It goes by permeability coefficient--of which the space suit has VERY little (which means it's blocking a *lot*).

**Comment by Fox-McCloud** [comment]
I must have been using an outdated build; it's functioning just fine now. Strange.
