### ISSUE TITLE
Slamming someone on a urinal has no click delay.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11663]
This basically means it's an insta kill.

![](http://i.imgur.com/ePLCSno.png)

This happened in about 1 or 2 seconds.

Also there's a grammar issue: "Aliyah Randolph needs to on the urinal." It's missing the "be".

**Comment by xxalpha** [comment]
:mens:

**Comment by CosmicScientist** [comment]
I'd say getting someone to come into the toilets/a choke hold means you deserve this just for the ghost salt.

**Comment by WJohn** [comment]
It is however inconsistent because toilets DO have a click delay.

**Comment by Niknakflak** [comment]
well RIP, fun

**Comment by Aloraydrel** [comment]
Rip

**Comment by PKPenguin321** [comment]
toilets used to have this exact bug, you could get a target to 700 brute in a few seconds with it
do we even have urinals on the map

**Comment by Niknakflak** [comment]
Yes, and you can use them.  Urinals, so underused except if can possibly be used as a weapon

**Comment by optimumtact** [comment]
click code
