### ISSUE TITLE
Stamina Damage Defence Is Not Percentage Based

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#11679]
All armour blocks on a percent base, so 50 defence will block 50% of something.

HOWEVER! For stamina damage it instead removes numerically.

So 50 defence will remove 50 stamina, instead of cutting it in half.

So with Sec Pistols if you shoot a Operative. Your 60 Stamina is now cut to 10 stamina thanks to the 50 defence.

**Comment by Dorsisdwarf** [comment]
Seems intended. Crushed.

**Comment by Steelpoint** [comment]
Except its inconsistent with how the majority of stamina attacks (read: energy weapons) deal their stamina damage.

It also makes it unreliable to use stamina damage for ballistic weapons, such as the riot shotgun or auto rifles with non-lethal rounds (if I get around to it).
