### ISSUE TITLE
chem heater board not contructable

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#11673]
What it says on the tin. If you have all the right levels, it simply isn't listed.

Ausops said something about the path pointing at the cloner pod board something, dunno.

**Comment by Ausops** [comment]
I looked at the files var and upon clicking the chem heater link, it showed 

(E) (C) (M) build_path = /obj/item/weapon/circuitboard/cloning 
(E) (C) (M) build_type = 1 
(E) (C) (M) category = /list (1) 
Medical Machinery = null
(E) (C) (M) construction_time = null 
(E) (C) (M) desc = "Allows for the construction of circuit boards used to build a new Cloning Machine console." 
(E) (C) (M) gc_destroyed = null 
(E) (C) (M) id = "clonecontrol" 
(E) (C) (M) materials = /list (2) 
$glass = 1000 
sacid = 20
(E) (C) (M) name = "Computer Design (Cloning Machine Console)" 
(E) (C) (M) parent_type = /datum/design 
(E) (C) (M) reliability = 100 
(E) (C) (M) req_tech = /list (2) 
programming = 3 
biotech = 3
(E) (C) (M) tag = null 
(E) (C) (M) type = /datum/design/chem_heater 
(E) (C) (M) vars = /list (15)

**Comment by GunHog** [comment]
Line 175 of machine_designs.dm is improperly tabbed.
