### ISSUE TITLE
Table crafting doesn't check tools required

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#11671]
When crafting something, e.g. a flamethrower, you need a screwdriver according to the table crafting recipe because normally you need it to adjust the igniter assembly but it is not consumed in the process.

It lets you make items without the needed tools.

The file:
https://github.com/tgstation/-tg-station/blob/master/code/modules/crafting/table.dm

I don't know at what stage it's meant to check for tools (not as an ingredient), I'd assume it was the check_tools proc but that seems to be there solely for tools as ingredients and the lack of comments/my shortcomings in DM coding means I can't see if it even has a check for tools, let alone a nonfunctional one.

I feel this is needed to be fixed urgently because I cannot bear roleplaying as inspector gadget every time I table craft something.

**Comment by joonoro** [comment]
I just tried it just now and I can't seem to find anything wrong with it. Were you by any chance an engineer when you tried this? I ask that because `check_tools` checks inside all of the users containers, so even if you have a screwdriver on your belt or even a backpack it will be used for crafting as long as you have all the ingredients.

**Comment by CosmicScientist** [comment]
I'll retest this myself to make certain I can do this with a naked spaceman with absolutely no tools within five tiles.

**Comment by CosmicScientist** [comment]
Alright this is an issue with my PR code rather than the actual code. I must have had an engineer's belt on with tools in it thinking I only had to have them on the table to craft with when testing with the proper code.
