### ISSUE TITLE
Space retrovirus can't be cured.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#11676]
Add 1000 units of mutadone
Nothing changes

**Comment by Firecage** [comment]
Well, it has two cures. Mutadone is only a 40% chance to be the cure. The other 60% is just to rest.

**Comment by Tokiko1** [comment]
#11617 This is a feature apparently.

**Comment by Firecage** [comment]
With Magnitis I honestly don't know.

**Comment by Supermichael777** [comment]
code/datums/diseases/retrovirus.dm

> /datum/disease/dna_retrovirus/New()
	..()
	agent = "Virus class [pick("A","B","C","D","E","F")][pick("A","B","C","D","E","F")]-[rand(50,300)]"
	if(prob(40))
		cures = list("mutadone")
	else
		restcure = 1

Because it cant just be annoying, it has to be assholessly annoying

**Comment by Dorsisdwarf** [comment]
Dupe of #11617
