### ISSUE TITLE
Upgraded ore redemption machines multiply miners' points as well.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11690]
As you know, upgrading the ore machine -- which is standard in many R&D rollouts -- multiplies the number of sheets the machine produces per ore. I am pretty sure miners receive points based on what's actually in the machine. This results in an absolutely insane number of points, as in, miners can buy the entire vendor out and have cash left over to buy their family members a space Ferrari each.

Either the multiplication goes, or the high-end mining items get increased in cost (I have some ideas for higher-end items, so this might be viable).

**Comment by Zilenan91** [comment]
I thought this was intended. Afterall, it makes sense that miners would get paid based on the amount of output they can create, upgrades included.

**Comment by Ergovisavi** [comment]
As the creator of the ore redemption unit I want to punch whoever caused this issue.

> Hurr durr infinite feedback loops goliath plate farming with lazarus

**Comment by bgobandit** [comment]
is that a "this issue is intentional bandit you are getting punched" or "this issue is unintentional whoever coded upgrades is getting punched"

**Comment by Lumipharon** [comment]
@Iamgoofball 
I told goof about this shit.
You can make the ore machine give out X4 the minerals, x4 the points (dunno if that also multiples with mineral amount), can't remember what the 3rd upgrade does, makes it process ore faster?

Machines like these were not designed to be upgraded, and it breaks balance by doing so - see recyclers.

**Comment by Iamgoofball** [comment]
Just axe the point X4ing and leave the ore X4ing as is

**Comment by ToadStar** [comment]
At least let the max point increasing go up to x3. Seriously, otherwise miners won't even bother. The ore redeemer upgrades gave miners a reason to start mining again.

**Comment by Iamgoofball** [comment]
@ToadStar the problem is that right now it actually ends up as X8 because the ore stuff gets run, and then the multiplication

**Comment by ToadStar** [comment]
I don't think i've ever actually seen that happen. Like, i've put in an iron ore before when only the matter bin was upgraded. The redeemer got 4 metal sheets, but I still got one point.

**Comment by Iamgoofball** [comment]
huh

could someone doublecheck this bug then

**Comment by Lumipharon** [comment]
Even if it doesn't multiply then multiply again, upgrading the machine with even t3 parts trivialises mining and it's rewards, when the machine was ony added to make delivery minerals to people more convenient.

**Comment by Iamgoofball** [comment]
are the people filing a complaint here the people doing mining or R&D

or the other crewmembers on the station

**Comment by bgobandit** [comment]
I do mining.

**Comment by Iamgoofball** [comment]
Does thisnchange make the game not fun or enjoyable?
