### ISSUE TITLE
Ayylien abductor surgery-for-dummies paper needs to be updated.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11695]
Ever since the surgery overhaul we have had different steps to do organ extractions, but the sheet of paper on the ayylien ships has not been updated with the new steps. This can be confusing to players who aren't familiar with either role, and that's still very common.

**Comment by ike709** [comment]
Couldn't we just change it to a book that loads the Guide to Surgery wiki page, similar to the Space Law book?

**Comment by Core0verload** [comment]
Abductor surgery is still a thing. You can do organ manip, but it's totally unneeded.
