### ISSUE TITLE
Ai can call emagged bots

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11692]
Saw an Ai use the call ability to lure beepsky away from dunking a bunch of crewmembers and into a corner. Since emagging cuts Ai control, this seems like a bug. @GunHog

**Comment by GunHog** [comment]
Provide details. It is very important to know *how* the bot was emagged. Manually emagged bots (using the emag item) should be inaccesable to the AI and borgs, However, a bot emagged by a silicon (hacking) is an exception.

Hacked bots are fully controllable and fixable by any silicon. Please confirm that the bot in question was manually emagged, or attacked by a revenant.

**Comment by Shadowlight213** [comment]
It was an ed209 spawned with the ed209swarm wizard spell. I heard the AI say it couldnt interface with it, so I assume manually emagged. emagged var was set to 2

**Comment by GunHog** [comment]
I have not heard of such a spell. Provide me a link to where it exists, please.

**Comment by Jordie0608** [comment]
https://github.com/tgstation/-tg-station/blob/ccd4137a9dc113f33b304711aa1aa3132ca8a10c/code/datums/spells/conjure.dm#L49

**Comment by GunHog** [comment]
It is a test/admin spell? Just add "remote_disabled" to the newVars() list flagged at 1.

**Comment by Shadowlight213** [comment]
Yeah. I just saw the remote disabled var in the master emag proc
