### ISSUE TITLE
Morph Shift-clicking

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11701]
So when you're playing as a morph you shift-click stuff to disguise as it, but thats the same key combo as examining so you accidentally disguise yourself when you examine something. 
Should change the binding to alt-click or something, don't think thats used for anything.

**Comment by Aloraydrel** [comment]
Alt clicking would actually be better

**Comment by Shadowlight213** [comment]
Isn't alt click ventcrawl though?

**Comment by Aloraydrel** [comment]
whoops I mean CTRL click

**Comment by Bawhoppen** [comment]
Ctrl-click is pull object though, not very useful for Morphs but I could see some uses. Maybe just make it a right click option or something

**Comment by RemieRichards** [comment]
Right click is far too laggy for the situations Morphs are in.

**Comment by AnturK** [comment]
I choose shift click was chosen because it's purely informational. I guess right click could work.

**Comment by Bawhoppen** [comment]
I don't think right click would work well either, cause many players including new ones who don't know the shortcuts exist or choose not to use them will use the right click menu.

**Comment by Dorsisdwarf** [comment]
Morphs only ever need to examine people, to see what kit they have, and they can just do that from a pipe/quickly go back to being a paper in a stack of papers

**Comment by Dorsisdwarf** [comment]
Resolved.

**Comment by Bawhoppen** [comment]
I'd disagree.
