### ISSUE TITLE
loan shuttle to centcom for epidemiology event can kill a whole station/round

### ISSUE THREAD

**Issue by chimerasable** [tgstation/-tg-station#11715]
It's a round killer that infects the crew with too many viruses. Please review it and consider toning it down a bit?

**Comment by Jalleo** [comment]
Link to code https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/modules/events/shuttle_loan.dm#L138

**Comment by bgobandit** [comment]
maybe virology should git gud

**Comment by Marflowerose** [comment]
One distant solution for toning it down would be to have it check if there is a virologist/CMO. It'd be kinda stupid for CentComm to send a crate of viruses to a place without anyone remotely able to deal with it.

**Comment by KorPhaeron** [comment]
@tkdrg 

Not a bug, no obligation to accept the shuttle when they ask to loan

**Comment by tkdrg** [comment]
Yeah this honestly isn't really an issue, there's even a Pandemic in the holodeck now
