### ISSUE TITLE
Metastation: Corporate Display posters displaying incorrect posters.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#11719]
![](http://puu.sh/k7JKy/b7a3eeed85.png)
This also causes description issues.

![](http://puu.sh/k7JP3/db3fa1ca00.png)

**Comment by bgobandit** [comment]
goddamnit

**Comment by duncathan** [comment]
@bgobandit it's likely an issue with roundstart posters. Check them out.

**Comment by bgobandit** [comment]
I don't play on metastation, where is this exactly

**Comment by Marflowerose** [comment]
https://github.com/tgstation/-tg-station/issues/11264 Probably related

**Comment by bgobandit** [comment]
not related, that was a separate bug

**Comment by Dorsisdwarf** [comment]
@Metacide Take a peek, see if you get this too.

**Comment by Metacide** [comment]
Thanks for the heads-up, will look into this.

**Comment by Metacide** [comment]
Not sure why this is happening, nor how to fix it, so fix won't be in the next update. 

Hopefully soon after, though.

**Comment by Metacide** [comment]
I think I'll just make them standard posters, unless there's some child of poster which is NT-approved propaganda.
