### ISSUE TITLE
detectives scaner cant scan lockers

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11710]
it makes finding emagers hard

**Comment by bgobandit** [comment]
Not even from a distance?

**Comment by Supermichael777** [comment]
i didnt check
keep forgeting that works

**Comment by Hamadryad-1** [comment]
@Dorsisdwarf  This is a misunderstanding, not a bug: that's just how it acts!

Step a tile away - The scanner is ranged

**Comment by WJohn** [comment]
That seems really weird and unintuitive that the scanner *has* to be used at range to work. Someone want to change that so it can work up close?

**Comment by Dorsisdwarf** [comment]
No, because it's intuitive that clicking a locker with any item has always resulted in opening it.

Closed, but we really need it to be known for the Scanner is ranged.
