### ISSUE TITLE
Mining bot burn damage repairs.

### ISSUE THREAD

**Issue by Incomptinence** [tgstation/-tg-station#11728]
Due to the opacity of mining bot health I am unsure of the exact nature of this issue but I will continue.

Simple robots now can have burns repaired by unscrewing them with unlocked controls and adding wires. 

The mining bot never got a control menu so it can't be opened up welders will try to repair the damage to no effect probably due to changes to the welder as I understand it isn't a proper simple robot. 

I have emptied entire industrial welders trying and I have also tried to use wire without an ability to open it I just whip the poor little thing.

**Comment by Incomptinence** [comment]
Oh also no free wire on mining if you want to make it a real boy.

**Comment by AlexanderUlanH** [comment]
I think the mining bot is a simple animal, not a bot.

**Comment by bgobandit** [comment]
mining drones are technically hostile simple mobs
