### ISSUE TITLE
R&D and Robotics Machinery: No Access Check

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11720]
Currently the mech fabricators and RD console do not properly deny usage of the machines if you don't have the proper access.

This leads to things like science being able to construct its very own robotics lab/mech fabricator 5 minutes into the round to build their own mechs and borgs. It also means that anyone who can walk into R&D can just print off whatever their heart desires.

On a similar note, since roboticists have access to tech storage, so they can just take the protolathe and destructive analyzer boards from it and sync it up to their own console, 5 minutes in, and they can essentially do R&D's job better than even they can (especially considering that they can just steal the stock parts from R&D that are lying around).

**Comment by Durkel** [comment]
The access was removed on purpose, it's intended that anyone can create the items available otherwise you get cucked when you need to print something half the time.

#5722

**Comment by Fox-McCloud** [comment]
Hm. Interesting.

That has some pretty serious ramifications for self-sustaining self-sufficiency in science--I swear science power creeps more than any other department.

**Comment by Lumipharon** [comment]
Daily reminder that R&D still doesn't have fucking airlocks, like literally every other job in the entire game.

**Comment by xxalpha** [comment]
Not a bug, not an issue.

**Comment by GunHog** [comment]
@Lumipharon: Blame Paprika.

**Comment by Lumipharon** [comment]
Pap changed it because in lowpop he wanted to let robo in to do it. Which is fair enough.
But now we have access based on pop count anyway, so it's redundant, and just lets random fucks swarm into R&D, which itself isn't locked, and print out boh's and shit.

**Comment by Fox-McCloud** [comment]
@Lumipharon 

Not like it really matters; again, the destructive analyzer and protolathe boards in tech storage all but ensure that robotics can pretty much self-sustain itself.

**Comment by Core0verload** [comment]
F E A T U R E

**Comment by Dorsisdwarf** [comment]
Closed for discussion on-forum as to whether robos/RDs should be able to use each other's machines.
