### ISSUE TITLE
Items in backpacks destroyed by fire are layered above the UI

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11730]
Had someone burn to death with a bucket in their backpack. Bucket was layered above the ui, and took up the whole tile when hovering over it with the mouse.
![bug](http://puu.sh/k8nRT/3638fd89b7.jpg)

**Comment by Dorsisdwarf** [comment]
This might be related to the bug where sometimes items would take u[p the whole tile

**Comment by RemieRichards** [comment]
@Dorsisdwarf No, not related in the slightest.

Items just aren't setting their layer back to the standard one when leaving objects that get deleted.

**Comment by Jalleo** [comment]
I also encountered that error yesterday may be new.
It occured with a explosion for me. Items were still existing backpack wasnt.

**Comment by Shadowlight213** [comment]
@RemieRichards yes it may be related. The bucket was taking up the whole tile. If I pointed my mouse over anywhere on the tile, it would say bucket

**Comment by RemieRichards** [comment]
@Shadowlight213 I'm going to be harsh here, you do not get to decide what is and is not related.
It is a coincidence, both issues were caused by items being destroyed by explosions, with their contents surviving, they're not related.

**Comment by Shadowlight213** [comment]
Ok
