### ISSUE TITLE
Thermal Implants: Useless

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11745]
Simply put, there's no point to thermal augmentation, at all. Why?

Here's the tech requirements for thermals in addition to their resource requirements:

Tech: "materials" = 7, "programming" = 5, "biotech" = 5, "magnets" = 5, "syndicate" = 5
Materials: MAT_METAL = 200, MAT_GLASS = 200, MAT_SILVER = 600, MAT_GOLD = 600, MAT_PLASMA = 1000, MAT_DIAMOND = 2000

Here's X-Ray

Tech: "materials" = 7, "programming" = 5, "biotech" = 6, "magnets" = 5
Materials: MAT_METAL = 200, MAT_GLASS = 200, MAT_SILVER = 600, MAT_GOLD = 600, MAT_PLASMA = 1000, MAT_URANIUM = 1000, MAT_DIAMOND = 2000

I think you can see where I"m going with this. The only differnece is that X-ray requires one higher tech level for biotech and requires uranium....both of these are trivial though---if you have diamond, you're going to have uranium. Likewise, if you have the materials for Thermal, you can already push biotech to 6 anyway.

Thermals also reduces your resistance to flashes.

So I ask...with how much harder syndicate tech is to acquire (Yes, I realize it's not THAT hard), why in the world would you ever want to go with thermals over x-ray, ever? It would make sense if their materials cost and tech levels were significantly lower, but at this level, no one is ever going to want to utilize thermals over X-Ray.

**Comment by PKPenguin321** [comment]
known issue, not a bug, iirc thermal implants are just there for the tech levels

**Comment by xxalpha** [comment]
So what is the issue here? If you say R&D I agree completely.

**Comment by PKPenguin321** [comment]
yeah this isn't exactly an issue worthy of the issue tracker, if anything head to the feedback forum

**Comment by xxalpha** [comment]
Upon reaching Biotech level 5, the only way to make the jump to level 6 is by analyzing thermal implants or an alien brain.

This is how the X-ray implants are gated.

**Comment by PKPenguin321** [comment]
we need a "FEEDBACK FORUM" tag

**Comment by Fox-McCloud** [comment]
Actually, the nutriment pump plus implants contain biotech 5 and is significantly cheaper than the thermals (and doesn't require syndicate tech), thus that point isn't really valid, @xxalpha.

**Comment by PKPenguin321** [comment]
yeah but this has syndicate 5
and again, this isn't an issue

**Comment by Fox-McCloud** [comment]
I think you're missing the point.

The point I'm trying to make is that going for thermals is literally pointless and a waste of time, as you'll end up consuming more resources and have to go into an alternative tech branch (Syndicate) just to get them when you can get the vastly superior X-Ray augmentation for less resources, time, and effort.

Game balance wise, that's a poor design to have an inferior tool be harder to make and get than a superior one.

**Comment by Lumipharon** [comment]
Thermals exist so you can blood drain them for syndicate 6 to unlock all the SUPER OP bullshit.

**Comment by Fox-McCloud** [comment]
Uh, what?

Augments don't prevent you from wearing eyeglasses---and thermals harm your flash protection--so there's literally no point to ever building them...likewise, they absolutely were not made to allow you to access the "super OP bullshit" because they had that tech level before that "OP bullshit" even existed.

**Comment by Lumipharon** [comment]
Where did I say they stop you from using eyewear?
I said thermals have an advantage if you using flash protection (like sechuds AND a hardsuit) where as xray is only objectively better when it's combined with nvg or mesons to get full vision. That said, that's still advantagous most of the time - I'm just pointing out there is a niche use.

**Comment by Fox-McCloud** [comment]
Misinterpretted what you stated.

In any event, Xray gives SEE_MOBS...so does Thermals, only thermals has the weakness of reducing flash protection---therefore, I don't see any reason why you'd want thermals+a HUD when xray+HUD would give you the same effect in addition to letting you see objects and turfs.

**Comment by xxalpha** [comment]
>nutriment pump plus implants contain biotech 5

It also requires Biotech level 6.

**Comment by Dorsisdwarf** [comment]
Thermals mostly exist as btech 5. complain elsewhere.
