### ISSUE TITLE
RnD research can be wiped out with a screwdriver. 

### ISSUE THREAD

**Issue by chimerasable** [tgstation/-tg-station#11740]
If someone disconnects the monitor of the rnd computer it will wipe all research.

**Comment by Incoming5643** [comment]
This is why you sync with the server. Save early, save often.

**Comment by Xhuis** [comment]
Research has always been easy to remove. Even the AI can wipe the servers and console to completely destroy _all_ research.

**Comment by Incoming5643** [comment]
That's why if you're extra paranoid you save your favorite recipes to disk and disable the cameras in the server room

**Comment by xxalpha** [comment]
This is not

This is intended behavior.

**Comment by Dorsisdwarf** [comment]
Closed for non-bug intended behaviour. Take it to the feedback Forum.
