### ISSUE TITLE
Slime and jaunt edge cases and bugs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11754]
Bug 1: As a slime, if you feed on a slaughter demon and the demon blood jaunts, you will be dragged in with him. If he resurfaces, you end up in nullspace (black screen).

Bug 2: As a slime, if you feed on a wizard or wraith and they jaunt, you will be dragged in and will actually share control over his movement while he is jaunting. This means you can wrestle with where he will go, or completely control it if he doesn't move.

Bug 3: If you then delete the slime after having done this, it will send the wizard to nullspace, and he will only be able to jaunt in place(?) making a splash of water there, but never re-appearing. Ei nath may be a case where this could happen.

**Comment by phil235** [comment]
Bug 2 and 3 were already fixed when slime feeding was changed to use buckling.
