### ISSUE TITLE
Inconsistency in Origin tech levels and Design Tech levels

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11758]
This may be intentional, but I suspect it's an oversight.

A few of the augmentation and implant tech levels have a mismatch on their origin tech and their design tech requirements (sometimes they give more tech levels than their design requires, other times the tech levels on the design are higher than the item's origin tech)---this may be intentional to gate things, but it does have a few unintended side effects: Simply put, it's currently impossible to attain Syndicate/Illegal tech rating of 6 without sacrificing Syndicate gear. Is this intentional? This currently locks off adrenaline implants from being produced.

**Comment by Lumipharon** [comment]
1: Adrenal implants are seriously OP when you can mass produce them - I've done this several times and it's a joke

2: The experimentor lets you unlock everything easily. http://pastebin.com/wRARdBDv

**Comment by Fox-McCloud** [comment]
Relying on RNG to go your way just to raise a tech level is well..kinda crappy.

**Comment by Lumipharon** [comment]
It's not really an issue considering it's just pressing a the same button over and over again until it works.
Thanks to upgrade ore machine bullshit, you never run out of minerals anyway.

**Comment by GunHog** [comment]
A lot of the tech levels are indeed intended to be that way, and due to how awesome some things are, they have to be gated, else we will not have to chance to get them at all.

**Comment by xxalpha** [comment]
>it's currently impossible to attain Syndicate/Illegal tech rating of 6 without sacrificing Syndicate gear

No shit, syndicate stuff is too good. R&D takes no effort at all, things have to be gated behind hard to get items. This is not a bug, and this is not worth multiple issues. R&D system sucks but it's what we have now and it's working as intended. There are no inconsistencies, that's just how the system is designed.

**Comment by PKPenguin321** [comment]
yeah, research walls have always been a thing (but the experimentor breaks then anyways so iunno)
getting level 10,000 ultra rare mega gun-arm implants shouldn't happen every round (but does anyways if someone uses the experimentor so iunno)
also, **F E E D B A C K    F O R U M**

**Comment by Dorsisdwarf** [comment]
F E E D B A C K F O R U M 

(This is a feature)
