### ISSUE TITLE
Chlorine Trifluoride nerf

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#11752]
Alright so, I just saw how a 10u patch of Chlorine Trifluoride can kill you, no matter what. 

Can it possibly be made harder to obtain, or not allow for it to be harmful in patch form?

**Comment by Iamgoofball** [comment]
1. this isn't the place for this, put this in a feedback thread on the forums
2. i need specifics, we don't know if this guy already had existing damage or not
3. was any attempt to treat him before he died made or was he left to die

**Comment by sirnat** [comment]
Ah sorry then, I'll take it to feedback and explain lot more.

**Comment by WJohn** [comment]
He's not kidding about this, this is unbelievably powerful.

This was tested at full health:

Without an extinguisher: 10 units will be impossible for you to extinguish while rolling on the ground, and it will crit you very quickly.
With an extinguisher: 10 units will STILL crit you even without you being on fire, you *need* medical attention to survive this, and it still doesn't take terribly long for just 10 units of this shit.

**Comment by sirnat** [comment]
Do I need to close this btw? I made a thread on le forum

**Comment by WJohn** [comment]
On further testing it only actually requires about 5 units to crit somebody from full health, even if they're not on fire.

**Comment by Aloraydrel** [comment]
shits cray cray yo

**Comment by Iamgoofball** [comment]
This is probably NOT CLF3, and is probably instead a cause of the changes to Fire recently.

So check out fire, not CLF3.

**Comment by Iamgoofball** [comment]
>5 units does 123 burn damage without any fire involved, 

wait what

something's not right here then

**Comment by sirnat** [comment]
Does that mean it will exit the system quicker?

**Comment by Iamgoofball** [comment]
yeah, it's main balancing factor was the fact it exited the system way way faster than every other chem, so it could do a lot of damage but it goes down 4u every second

phil broke it by accident

**Comment by sirnat** [comment]
Ah cool, so its possibly survivable?

**Comment by Iamgoofball** [comment]
With that PR, it's back to the normal level of survivability IF you're treated properly after it's out of the system.
