### ISSUE TITLE
Slime processor annoying mass clicking

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11765]
When you're grinding slimes, if you have steroided them, and upgraded the processor you have a million slime cores you need to manually click into the fridge, and its really annoying since you go through a lot of slimes in xenobio. There should be a way to like set the processor to autofeed to an adjacent fridge so you don't need to click

**Comment by phil235** [comment]
How about a bag to pick up cores and load them in the fridge, like hydroponics or mining?

**Comment by Bawhoppen** [comment]
Would work aswell, any solution would be fine.

**Comment by RemieRichards** [comment]
just have click dragging cores repeat the action on all cores in the same turf.

**Comment by Bawhoppen** [comment]
While that solution wouldn't be horrible I feel like that one be one of the things that becomes not a secret but not well known, like how double clicking windoors to lock them open or saying :I in front of an intercom to talk on it, instead I think it should be an actual mechanic to transfer it, a bag, feed or something else

**Comment by Lumipharon** [comment]
Being able to link a fridge to the machine, like linking botany trays would be godly.
Could be extended to other machines like kitchen shit/chem master etc.

**Comment by Bawhoppen** [comment]
Yea that was my idea, kind of creating a semi-automated system like factorio or minecraft mods.

**Comment by Aliannera** [comment]
Ever since the slime processor was able to be upgraded, I thought a slime bag would be nice so we could quickly shift the massive amount of slimes it can produce over to storage.

And then you could store a bunch of cores in the bag and spam silver slime cores on the shuttle for food - or gold cores if your an antag and a bunch of plasma in syringes.
