### ISSUE TITLE
Magic event breaks Smart Virus Storage

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#11779]
The magic event that adds names to shit breaks the items inside Smart Virus Storage (probably applies to all fridges). The items are listed but when clicked to withdrawn, they are gone.

**Comment by Incoming5643** [comment]
They must be referencing things by their names

This is <u>dumb as hell</u> and I'll never understand why anyone thinks it's an ok thing to do.

**Comment by phil235** [comment]
@Incoming5643 Yep. And this also causes #4708.
