### ISSUE TITLE
Pulse rifle shots don't light plasma

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11785]
Title. There definitely was o2 and I'd assume they're supposed to light the plasma but maybe its intended they don't.

**Comment by Anonus** [comment]
Lasers don't either, it's a shame.

**Comment by Bawhoppen** [comment]
Since when, and if they're intended to not anymore thats bullshit.

**Comment by Supermichael777** [comment]
the only thing that does it is taser shots because of the sparks they produce when they hit dense objects.

**Comment by Bawhoppen** [comment]
I'm saying that lasers (and pulse shots) should ignite it, I am almost certain of remembering someone lasering to ignite it.

**Comment by Dorsisdwarf** [comment]
They don't, and never have. Some things spark when shot, however, like cyborgs, which might be what you remember.
