### ISSUE TITLE
Ghosts who leave orbit no longer have the floating animation

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#11781]
Go orbit something and jump off and see how you no longer have the spooky floating animation

**Comment by WJohn** [comment]
Already covered in #11777, and fixed by #11778.

**Comment by MrStonedOne** [comment]
@WJohn can you re-open this, This isn't covered in #11777 and isn't fixed by #11778 nor #11847

It's a bit more complicated to fix
