### ISSUE TITLE
Implant breaking is currently TOO EASY, make armor block implanters

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#11789]
Seen this happen too many times and it's getting old. One of the reasons that gangs can spiral out of control wayyyy too fast is when someone gets one of the 20+ slipping tools around the station and wets tiles near the brig/bridge/etc. 

Some security leaves brig, comes by, they slip, you start injecting them and before they realize what's going on or have any ability to stop it - they've joined an enemy gang and basically ensured them victory. 

Virtually every "bad" gang war I've seen, where one side immediately spirals out of control and stomps the station, happened when security got slip n' stabbed, started converting their own and by the time people realized what was going on it was far, far, far too late to stop them. 

Armor+Helmet should work on implant breakers the same way that biosuits/hardsuits work on regular needles. 

This means that converting a member of security takes more effort than just camping chokepoints with  wet tiles under the airlocks.

**Comment by duncathan** [comment]
You know this is feedback forum

**Comment by WJohn** [comment]
I feel like nobody reads the idea or feedback forum compared to here.

**Comment by xxalpha** [comment]
Feedback forum

**Comment by Lumipharon** [comment]
ignoreback forum

**Comment by PKPenguin321** [comment]
holy feedback forum batman
wjohn you nerd it doesn't matter what you "feel," posting things here instead of the feedback forum just circumvents the majority of player input (inb4 "but nobody cares about le feedback foruM! Xd!")

**Comment by Dorsisdwarf** [comment]
This is on the feedback forum, with a direct quote. Closed because I am the law.
