### ISSUE TITLE
Syndiborgs are broken. 

### ISSUE THREAD

**Issue by Bluespace** [tgstation/-tg-station#11797]
2015-09-14
726c72352083370d36a3539bd39cc426bf55d949 

Syndicate cyborgs still cannot use their grenade launcher module.
Furthermore, there appears to be no way to regenerate LMG ammo once it's gone.
This, in effect, makes cyborgs fairly weak. You are basically a door opener. 

Let's actually get this fixed now please.

**Comment by Bluespace** [comment]
I actually got off my ass and made this after being a cuckborg cockswallower 3 times now.

**Comment by WJohn** [comment]
They regenerate LMG ammo all by themselves, always have. It's pretty slow regenning but it does work.
