### ISSUE TITLE
Mining Uniform lockers do not have backpacks unlike every other uniform closet

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#11791]
Really sucks when your backpack explodes due to gibtonite

**Comment by Anonus** [comment]
Uh, no uniform closet has backpacks, only personal closets and department equipment lockers have backpacks.
Though you are right that the equipment lockers don't have backpacks.

**Comment by phil235** [comment]
Pretty sure there's mining backpacks in lockers on the asteroid mining station.

**Comment by Dorsisdwarf** [comment]
I'm pretty sure they are, someone go look.

**Comment by WJohn** [comment]
I just checked, not a bug. Only the mining wardrobe has the shoes, uniform, gloves, and backpacks. The equipment lockers aren't supposed to have them.
