### ISSUE TITLE
Mimes start with a bike horn and clown crayons. 

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11794]
This upsets the balance of the universe.

suspect related to https://github.com/tgstation/-tg-station/issues/11788

**Comment by Niknakflak** [comment]
Feature

**Comment by Miauw62** [comment]
honk

**Comment by phil235** [comment]
Yep, same kind of mistake as 11788. See b3b18d0080253e1af1b1a10aa07e67c7a5d0ddad @AnturK

**Comment by AnturK** [comment]
Whoops
