### ISSUE TITLE
There should be a way to mute the currently-playing MIDI only.

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11795]
When you use the button to toggle hear/silence midis if you unsilence them it picks back up playing the current one, there should be a button to mute the current midi so you can hear future ones

**Comment by WJohn** [comment]
Strange, it worked for me just last night. I guess I'll have to try it out.

**Comment by Bawhoppen** [comment]
why is it so fucked for me though, I can reproduce it every time

**Comment by Bawhoppen** [comment]
Here is the video of it I promised https://www.youtube.com/watch?v=BB21ydDOwy8

**Comment by WJohn** [comment]
Oh, as in it resumes after you turn it back on? Is that even a problem then?

**Comment by Bawhoppen** [comment]
Yes. Thats the whole point.

**Comment by Dorsisdwarf** [comment]
Renaming this issue because your title is misleading. 

Also this is a feature request and is liable to get nuked if nobody codes it in a few days.
