### ISSUE TITLE
Centcomm zlevel teleporter bug 2: Electric boogaloo

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11811]
See: https://github.com/tgstation/-tg-station/issues/4436

Similar concept but now you can directly build the teleporter machinery on shuttle floors.
Same gate mode and such as before.

My suggestion to remove is have the cargo shuttle delete any machinery when it goes back to centcomm just like crates.

**Comment by Lumipharon** [comment]
Shouldn't it just delete EVERYTHING when it goes back to centcomm?
There is no genuine reason for anything to persist there, and I'm sure centcomm would wash out the blood and xenogibs when it comes back.

**Comment by Tokiko1** [comment]
Don't forget that there are buttons, levers, conveyor belts and doors on the shuttle which would probably get deleted too.

**Comment by Bawhoppen** [comment]
Make it so you can't teleport to z2 ever because 'long distance' or something

**Comment by Bawhoppen** [comment]
I just realised this also might work with teleport runes, Didn't test but it seems likely it would.

**Comment by tuypo1** [comment]
you say this like its a bad thing
