### ISSUE TITLE
Sec auto rifles still have fire modes

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#11818]
![secrifles](https://cloud.githubusercontent.com/assets/4043781/9910006/c341ba06-5c92-11e5-9965-fd6666cb72bb.PNG)

the PR specified that it no longer had firing modes, and indeed they don't act differently, but the framework for firing modes is still active on the guns.

**Comment by WJohn** [comment]
@Steelpoint

**Comment by Steelpoint** [comment]
It's inherent to automatic firearms, I can look into it but I dunno I'm not that great a coder at all.

**Comment by Menshin** [comment]
Override the ```ui_action_click()``` proc for the wt550.

>/obj/item/weapon/gun/projectile/automatic/wt550/ui_action_click()
>     return

or whatever you want it to do when clicking the ui icon.

**Comment by Steelpoint** [comment]
I'll put up a fix PR soon (tm).

**Comment by Iamgoofball** [comment]
>shinra auto rifle
