### ISSUE TITLE
You can enter a mech while buckled to a chair

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#11828]
If you do so, you remain buckled to the chair and cannot move unless you resist to unbuckle.

**Comment by phil235** [comment]
`/obj/mecha/MouseDrop_T(mob/M, mob/user)` need a buckled check before and after it calls do_after(). (it might also need other checks like restrained or stat, maybe?)

**Comment by bgobandit** [comment]
tactical chairs

**Comment by Lijah99** [comment]
Addressed in #11934
