### ISSUE TITLE
Docility Slime potions don't have a sprite and might not work either

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11824]
Title. A few days old before reporting this, sorry if its been fixed or is a duplicate issue.

**Comment by WJohn** [comment]
Stiiiill broken.

**Comment by bgobandit** [comment]
more details please

is this every slime potion or just a few

**Comment by Bawhoppen** [comment]
oh I'm autistic, the docility slime potions in specific

**Comment by bgobandit** [comment]
I cannot reproduce this.

**Comment by Bawhoppen** [comment]
might be fixed

**Comment by bgobandit** [comment]
as of earlier today docility potions work fine, I checked the code and nothing looks off, I remember fixing this specifically in an older PR...

**Comment by phil235** [comment]
There's a runtime happening with docility potion, might explain why it looked like it didn't work.

**Comment by bgobandit** [comment]
a) that's sentience potions, not docility)
b) does this happen with ALL things that call for ghost candidates?

**Comment by KorPhaeron** [comment]
I fixed this @phil235

**Comment by Bawhoppen** [comment]
I'll just close it then?
