### ISSUE TITLE
Backpacks, inhands, etc. are broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11839]
What happened: You cannot put anything into backpacks or other containers. You also cannot interact with something in-hand; suppose you have a toolbox in one hand and try to access its contents, you end up toolboxing yourself.

How to reproduce: Try to put something into a container or do the above

Why this is bad: HONK HONK HONK HONK HONK

Other details: apparently this is due to remie's PR being tested, which, good thing it was tested :^)

**Comment by Jordie0608** [comment]
#11786 was being tested on the server and has since been reverted.
