### ISSUE TITLE
outfit datums tryint to create null objects!

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#11835]
@AnturK 
The following runtime has occured 2 time(s).
runtime error: Cannot create objects of type null.
proc name: post equip (/datum/outfit/job/security/post_equip)
  source file: security.dm,250
  usr: null
  src: Security Officer (/datum/outfit/job/security)

**Comment by xxalpha** [comment]
It assumes there is always a tie to attach.

**Comment by AnturK** [comment]
Fixed in the clown/mime pr already
