### ISSUE TITLE
EXPERI-MENTOR Throwing Anchored things

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11833]
Simply put, when the EXPERIMENTOR chews through "space-time" it will throw things---there's two problems here:

- it throws anchored items
- it doesn't spawn off each item thrown, so it throws each item, one at a time, instead of all at once, making the entire process take way longer than it should..

**Comment by GunHog** [comment]
Meeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrrrrggh.
