### ISSUE TITLE
Fireballs being stopped by open firelocks

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#11840]
So, a open firelock will stop your fireballs, resulting in your possible death.

**Comment by phil235** [comment]
Can't reproduce, with either fireball spell or wand, on either map firelocks or player built firelocks.

**Comment by Steelpoint** [comment]
I played Wizard earlier today, this bug did NOT occur for me.

I was firing through a open door in cargo many times, even hitting the door occasionally.

**Comment by Jalleo** [comment]
Its possible its another object that it interacted with on that tile can you link any specific locations this occured at @sirnat

**Comment by Incoming5643** [comment]
Keep in mind that the fireball will jump to and explode on any living mob besides the firer it sees adjacent to it.

Meaning if you fire while standing on top of a guy in crit, the ball will fly back and explode on you.

**Comment by Steelpoint** [comment]
Yeah, the fireball is a higher skill weapon due to the fact that it will detonate adjacent to any still living mob.

So even if someone is in crit and is behind the door it will still explode as the fireball pass through the door, but once the person dies they no longer block fireballs.

**Comment by phil235** [comment]
without new informations I'm going to assume that either sirnat didn't see the thing that actually touched the fireball or that was on an outdated or different repo.

**Comment by RemieRichards** [comment]
>FIREball being stopped by a FIRElock

Clearly not a bug, it's NT brand Firelocks for you!
