### ISSUE TITLE
Syndie Medical Bag: Regular Traitors

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11851]
Not sure if this was an oversight or not, but it seems like one, so posting it here:

- The syndicate medical bag is obtainable on the uplink for regular traitors.

Side note, what is even the point of the Syndi MMI? NUkies don't have access to a robot suit and regular traitors don't either--any traitor/nukie that does will spend 1 extra TC to be able to take over as many borgs as they want PLUS unlock their hidden module.

**Comment by Xhuis** [comment]
IIRC the creator intended for this to be obtainable to traitors. The Syndicate MMI makes the cyborg made out of it not sync to any AI and start off with the Syndicate lawset.

**Comment by Fox-McCloud** [comment]
@Xhuis 

Hm. Don't see a point to that then. It's useless without a robotic suit...and anyone with access to a robotic suit is just going to emag, anyway, as it makes the cyborg not synced to the AI+invisible on the panel as well (PLUS weapons)...not to mention you can emag over and over.

**Comment by PKPenguin321** [comment]
nah nah nah, see, you can make ghetto exofabs

**Comment by Lumipharon** [comment]
I've only used it once... when I got it from a syndie crate and had access to robotics anyway.

It's a neat, if super niche as fuck item, which is inferior to an emag in 99% of cases (fuck emags, seriously cut those functions into several items...), but there is no harm in leaving it in the upload.

**Comment by PKPenguin321** [comment]
it's also nice because it comes with a dufflebag that has no slowdown
but yeah this literally is a non-issue

**Comment by Dorsisdwarf** [comment]
GoodBYEEEEEEE
