### ISSUE TITLE
TK cup grabbing bug

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11867]
Its been 3 fucking years since I first found this bug and it still hasn't been fixed, if you have TK you can pull cups out of the water cooler from anywhere including behind walls/windows.

**Comment by bgobandit** [comment]
feature

**Comment by Bawhoppen** [comment]
say "*/wrists"

**Comment by phil235** [comment]
`/obj/structure/reagent_dispensers/water_cooler/attack_hand(mob/living/carbon/human/user)` needs an adjacency check and drop the cup on the ground instead of puting it in hands if the check fails.
