### ISSUE TITLE
XXX is hit by a bullet in the chest! XXX blows his brains out with Gun

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#11862]
really...

**Comment by xxalpha** [comment]
Did you need the triple X

**Comment by phil235** [comment]
`/obj/item/weapon/gun/projectile/suicide_act(mob/user)` probably needs to add a new argument to its process_fire() call (as suggested by Remie in #11815) that forces the hit zone to be the argument.

**Comment by Iamgoofball** [comment]
hot sexy suicide_act action

**Comment by phil235** [comment]
Fixed by #11815
