### ISSUE TITLE
Dead shadowlings receive "The light burns you!" messages even while dead

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11869]
Hatched shadowlings, to be clear.

How to reproduce:

- Be shadowling
- Die
- Be dead in an area with light
- Be spammed

I'm not sure if this is actually trying to decrement health, all I saw were the messages.

**Comment by phil235** [comment]
`/datum/species/shadow/ling/spec_life(mob/living/carbon/human/H)` needs  an "if(H.stat != DEAD)".

**Comment by Xhuis** [comment]
Intentional. Not a bug, but it might be better if it was removed regardless.
