### ISSUE TITLE
Wand of engine ignition consistency

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#11861]
In the wizard den/shuttle, there's a wand for emergency engine ignition at the south end that has a consistency issue.

On examine:
"That's a wand of emergency engine ignition.
Used in emergency's to reignite magma engines. This one appears spent.
It is a small item.
It has the magic crystal shard installed.
Has 100 charges remaining."

The description says it's spent yet it has 100 charges. Not urgent but a tad immersion breaking.

Server revision compiled on: 2015-09-17
a48254f31a0c0b1a552b40fa8c5d7f6372a2ed90

**Comment by Incoming5643** [comment]
It's not a real thing, someone just renamed a wand of nothing on the map. The charges var can just be set to 0 there.

**Comment by phil235** [comment]
"emergency's"
:frowning:

**Comment by Steelpoint** [comment]
It was me! I was the turkey all along.

Really I just never noticed it, tho someone else is fixing it.
