### ISSUE TITLE
Riot helmet lifting visor doesn't allow you to eat

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11866]
You still need to take off the riot headgear in order to eat, where you would think lifting the visor would work

**Comment by WJohn** [comment]
There's also some ugly sprite issue going on with the south side where the helmet and the chinstrap are shifted up one pixel.

**Comment by phil235** [comment]
`/obj/item/clothing/head/helmet/attack_self()` needs to have `flags_cover &= 0` and `flags_cover = initial(flags_cover)`, just like /obj/item/clothing/mask/proc/adjustmask(var/mob/user) (See #10219)

**Comment by phil235** [comment]
Also, it still protects you from facehuggers, for the same reason you can't eat.
