### ISSUE TITLE
Slime toxin

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#11879]
Can turn you into a plasma man and you die within 30 seconds, pretty shitty race to be turned into.

**Comment by phil235** [comment]
Probably not intended.

**Comment by Tokiko1** [comment]
I'd argue that this has good potential for traitors to abuse and I've seen a few people make special rooms for these plasma people. If you decide to fix this, please don't just outright remove it. Make it into a different reaction or something.

**Comment by bgobandit** [comment]
plasmamen appear to be in the blacklist for this -- can anyone reproduce

**Comment by LatD** [comment]
It's not actually plasmaman, it's "skinbone" or something in health analyzer. It can also make you a lesser shadowling which kills you slowly in light. The skinbone one is the really deadly one and it's usually called just plasmaman in game.
