### ISSUE TITLE
Teleporter can be built on the supply shuttle.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#11874]
No clue how this was done, but cargo built a teleporter setup on the cargo shuttle, and used this to go to centcom

**Comment by PKPenguin321** [comment]
i'm pretty sure it's literally as simple as building a teleporter on the supply shuttle
also this is like 99.9% likely to be a dupe

**Comment by Marflowerose** [comment]
Dupe of https://github.com/tgstation/-tg-station/issues/11811

**Comment by Shadowlight213** [comment]
close 4 dupe
