### ISSUE TITLE
Del()'s that still exist

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11870]
Just a list of things that still have Del() defined for them as opposed to Destroy()

Diseases:
https://github.com/tgstation/-tg-station/blob/825b5794c76b0ba6b4fccec13d12e4978d037936/code/datums/diseases/_disease.dm#L191
DNA Spread Disease:
https://github.com/tgstation/-tg-station/blob/909fcdc9a532f452817f8da85d4b67f46fe156dd/code/datums/diseases/dna_spread.dm#L65
Advance Diseases:
https://github.com/tgstation/-tg-station/blob/825b5794c76b0ba6b4fccec13d12e4978d037936/code/datums/diseases/advance/advance.dm#L72
Signal Datum:
https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/communications.dm#L275
Turfs:
https://github.com/tgstation/-tg-station/blob/15e50de0feb35850e348919d8f20cb63777fafc7/code/game/turfs/turf.dm#L38
LINDA Simulated Turfs:
https://github.com/tgstation/-tg-station/blob/825b5794c76b0ba6b4fccec13d12e4978d037936/code/LINDA/LINDA_turf_tile.dm#L69
Update triggers simulated turfs:
https://github.com/tgstation/-tg-station/blob/bfbe4e997efb3a5953f1de04c20deb191ff3138b/code/modules/mob/living/silicon/ai/freelook/update_triggers.dm#L14
Energy Katanas (this definitely shouldn't even exist):
https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/modules/ninja/energy_katana.dm#L73

**Comment by duncathan** [comment]
For clients, using Destroy() should probably work as long as it returns QDEL_HINT_HARDDEL_NOW. That would do the same thing as what it does currently, but it'd fit within the qdel system.

**Comment by duncathan** [comment]
As for the rest, simply changing Del() to Destroy() and then ensuring that it returns ..() should work.
Energy katanas can just have it removed.

**Comment by MrStonedOne** [comment]
clients can't be added to the qdel system, as clients aren't a child of datum so all those type thingies would fail.

**Comment by Fox-McCloud** [comment]
@MrStonedOne 

I'll remove that one from the list. Thanks; I forgot about that.

**Comment by duncathan** [comment]
Oh right only datums have destroy don't they
Yeah clients should be left as is then
