### ISSUE TITLE
Fore Starboard solar computer does not have a proper icon

### ISSUE THREAD

**Issue by danhibiki** [tgstation/-tg-station#11873]
Simply put, not sure what the issue is. It doesn't seem to be an icon state issue, but its the only thing that would make sense. Instead, its just blank space.

http://i.imgur.com/hH5nXu9.png

http://i.imgur.com/pJh1CgO.png

**Comment by PKPenguin321** [comment]
i think you might have the wrong codebase, these look like hippie sprites, this is /tg/

**Comment by danhibiki** [comment]
absolutely right, sorry about that bub
