### ISSUE TITLE
Mulebot attack text

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11884]
"Shade of Emilee Bloise has drains the life from the Mulebot (#1)!"

The mulebots are alive...
Its some kind of sick conspiracy.

**Comment by WJohn** [comment]
How are they even doing that?

Mulebots are objects.

What wizardry is this????

**Comment by phil235** [comment]
There's no draining happening, the shade's attack verb is "drains the life from", it's just a simple melee attack. Whoever added this attack text didn't think it through.

**Comment by Lijah99** [comment]
Potentially fixed by #11928
