### ISSUE TITLE
Transforming to a monkey as a ling kills your Guardian Spirit

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#11886]
Because the Guardian checks to see if its user mob exists (and it no longer does when it gets replaced by a monkey).

Not sure if it's worth adding snowflake checks to ling code to fix this.

Making this report as a reminder to myself/any suggestions on if its worth fixing.

**Comment by phil235** [comment]
Not just lesser form transform, it's every time monkeyize() / humanize() is called.

**Comment by RemieRichards** [comment]
have guardian's queue their deletion up in the future, and have them check the turf their master was last on for a mob with the same client/ckey.

**Comment by duncathan** [comment]
Just do that check Remie mentioned in destroy() and make it return QDEL_HINT_LETMELIVE if the check passes.
