### ISSUE TITLE
SMG protolathe ammo is lacking material names.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#11880]
![](http://i.imgur.com/cLwzxIQ.png)

What it says on the tin and in the picture. These material requirements don't tell you what type of material is required, just the number.

@Steelpoint

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/pull/11837 addresses this issue, which he derived from https://github.com/tgstation/-tg-station/pull/11849.

**Comment by Steelpoint** [comment]
This was fixed in my bug PR.
