### ISSUE TITLE
Can't see if a vent is welded when vent crawling

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#11893]
1. Be swarmer (don't know if the mob is important, but may as well include it)

2. Ventcrawl

3.Welded vents use the unwelded icon when in the pipes

4.Get confused and stuck

**Comment by Shadowlight213** [comment]
Interestingly enough, the scrubbers show up as welded if you are in then vent pipe system and vice versa if you are in the scrubber system
