### ISSUE TITLE
Couldn't Insert Plasma Sac with Organ Manipulation surgery

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#11894]
I got to the point where you can use the hemostat to take out the persons heart... I made the mistake of taking their heart because I couldn't put the plasma sac in their chest. I kept trying to give the organ to them but instead i kept feeding it to them

**Comment by phil235** [comment]
I think it's because /obj/item/organ/internal/attack() has a weird part with prepare_eat() to make the internal organ into food, which returns TRUE for plasma vessel. It probably happens with all internal organs that don't override prepare_eat (which I think is all of them except brain).

**Comment by Core0verload** [comment]
It's propably lack of feedback. When you try to eat the organ, it silently changes it's type to food. Food-organs have the same sprites and desc as the regular organs, but can't be used for transplantation.
