### ISSUE TITLE
Can't grab Alien queens

### ISSUE THREAD

**Issue by whodaloo** [tgstation/-tg-station#11891]
So I punched a queen to death as a hulk and ran on over to make delicious alien burgers, when I found out queens are immune to being grabbed... for some reason?  So I couldn't put him in the gibber, and using a butcher's knife on the corpse couldn't gib the queen either.  All I wanted was some sweet sweet queen meat.

**Comment by WJohn** [comment]
I swear this was intentional, a while ago queens (and possibly some other creature) were given some special status that makes them bulkier and immune to certain interactions like grabbing. Can't remember the name that status was given, though.

**Comment by GunHog** [comment]
Dead aliens should be grabbable, because the only way you can do surgery on this is to <b>build one directly under them.</b>

**Comment by PKPenguin321** [comment]
iirc, hulks, fat people, and xenomorphs can't be grabbed

**Comment by whodaloo** [comment]
You can grab normal xenos, though, at least as another alien- I've done it before.  I think queens, specifically, are immune to grabs.

**Comment by whodaloo** [comment]
Yeah, so I tested this live on Sibyl with Aloraydrel's help.  Regular humans and non-queen xenomorphs can grab each other with no problem, but alien queens in specific are immune to being grabbed.  It'd be nice if there was consistency across xenos- either ungrabble or not.

**Comment by KorPhaeron** [comment]
@WJohn 

I added the CANPUSH thing for Juggernauts to stop them being choked, thrown around, etc, and gave it to the queen as well (because it's the boss alien, an assistant shouldn't be shoving it about).

Feel free to change it, but it's not a bug.

**Comment by WJohn** [comment]
Then this issue can be closed.

**Comment by GunHog** [comment]
This is still an issue if it prevents surgery on alien queens, due to you not being able to put them on a surgery table. Building a normal table directly under the queen is the only workaround.
