### ISSUE TITLE
Rapid Crates Sender: Does Nothing

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#11907]
Currently the Rapid Crate Sender is in the code---but if you use it on a crate or a closet, it doesn't actually do anything.

What I expect it to do: when I use it on a crate/locker, it pops up a menu to give me the option of which cargo telepad I want to teleport it to.

Related: the RCS is not obtainable or on the map; same goes with cargo telepads/cargo telepad beacons, though that's hardly a bug.

**Comment by PKPenguin321** [comment]
this is pretty much a feature request

**Comment by Dorsisdwarf** [comment]
the RCS is a stub of a depreciated feature left over from Goon.
Ideas forum please.
