### ISSUE TITLE
Vent pumps do not return a qdel hint in Destroy()

### ISSUE THREAD

**Issue by duncathan** [tgstation/-tg-station#11918]
Jesus fuck I can't figure this one out
This is easily reproducible; just qdel a vent in any way and look at the very bottom of the del() log.
`/obj/machinery/atmospherics/components/unary/vent_pump/Destroy()` returns `..()`. Its siblings all return `..()` and they return a qdel hint properly. I'd call this a Buggson, but maybe I'm just missing something.

**Comment by MrStonedOne** [comment]
a proc can exist twice for the same type path, so find sister Destroy() procs up the type path.
