### ISSUE TITLE
Driving on a vehicle leaves footprints

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#11916]
Title.

**Comment by phil235** [comment]
Can probably be fixed by checking if the mob is buckled.

**Comment by Dorsisdwarf** [comment]
@RemieRichards this is YOUR code. (If dezzmont shows up, be careful not to listen to platitudes)

:smile:

**Comment by RemieRichards** [comment]
While it is my code yes, it just needs a buckle check, and probably a lying check too.
