### ISSUE TITLE
Cult walls (shield rune) Dont stop plasma flow

### ISSUE THREAD

**Issue by golfer45** [tgstation/-tg-station#11944]
Inciderary grenades work through cult walls panic

**Comment by Firecage** [comment]
I can confirm.

**Comment by Xhuis** [comment]
This is intended, but I have no problem if it got added. Watching a plasma fire backed up against a spell circle would be pretty neat.

**Comment by Anonus** [comment]
Actually a pretty easy fix, too.

**Comment by phil235** [comment]
Already fixed
