### ISSUE TITLE
humans remove embeded object dangerously refernces a list that does not exist

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11950]
And it means the only way to take embedded stuff out is surgery.
The nonexistant list is embedded_limb

**Comment by RemieRichards** [comment]
Definition:
```"\t <a href='byond://?src=\ref[src];embedded_object=\ref[I];embedded_limb=\ref[org]'>\red There is \a [I] embedded in your [org.getDisplayName()]!</a>"```

Use:
```var/obj/item/organ/limb/L = locate(href_list["embedded_limb"])```

it does exist.
