### ISSUE TITLE
Vents set to a different frequency are still available to all air alarms.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/-tg-station#11953]
They cannot be controlled but are still listed in the individual vent control section.

**Comment by kyrahabattoir** [comment]
Reproduction process:

In a map put multiple air alarms and vents in the same area but group the vents to different air alarms (lets say 1 vent 1 scrubber per alarm)
Unlock the air alarm and use one of the presets (panic syphon, etc...) only the frequency matched vents will respond.

Check the individual vent/scrubber settings: all the vents/scrubbers in the area will show, but only the frequency matched ones will actually "obey" to controls. Seems to me that the UI doesn't filter out vents that do not match the air alarm frequency.

**Comment by Dorsisdwarf** [comment]
I'm pretty sure there are supposed to only ever be one air alarm per area, and that that's enforced by code limits on building them.

**Comment by kyrahabattoir** [comment]
The mapping primer say that multiple air alarms are ok if you assign them their own vents through frequencies.

And if you check on box, there is a bunch of areas with multiple air alarms sharing vents (i'm still convinced that without separating them by frequency, that's bad)
