### ISSUE TITLE
Heart attacks are permanent.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#11962]
Once heart_attack has been set to 1, the human will take oxy damage forever. Setting heart_attack back to 0 won't stop it.

Death will stop the damage, but once the human is revived, damage will continue.

**Comment by phil235** [comment]
Are you sure the mob didn't have initropidril in its reagents?

**Comment by CPTANT** [comment]
I also noticed this a few weeks ago when testing toxins on my own test server. Even if someone is revived and all the reagents gone the oxygen damage continues.

**Comment by Shadowlight213** [comment]
Can confirm. Another admin and I were messing around with emagged defibs in the thunderdome, and the oxy loss did not stop after restarting the heart. Admin healing the mob will sometimes fix it, but not always.

**Comment by xxalpha** [comment]
Yes @phil235, I was testing this in a local server, merely VVing heart_attack to 1 caused it to last forever.

**Comment by Xhuis** [comment]
This might be stacked losebreath from the attack's actual effects.

**Comment by Iamgoofball** [comment]
Yeah, do this test again and check if it's losebreath.

Losebreath doesn't reset on admin revives for some retarded reason. It probably should.

**Comment by kyrahabattoir** [comment]
Should losebreath stack post mortem tho?
