### ISSUE TITLE
After being meat spiked you are permanently upside down.

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/-tg-station#11971]
So yo, after you get meatspiked you get turned upside down permanently.  Stunning and such doesn't seem to reset your sprite.

![image](https://cloud.githubusercontent.com/assets/1363931/10062920/f10384ee-6235-11e5-92c5-7f0bf87d41d6.png)

**Comment by Marflowerose** [comment]
How cool does *flip look when upside down?

**Comment by freerealestate** [comment]
spike goes into your brain
affects your perception

you're actually right-side up

it's the world that's upside down friend

**Comment by feemjmeem** [comment]
i think we should leave this the way it is

**Comment by freerealestate** [comment]
there's also no message when someone is being meatspiked, and you can attempt to meatspike someone while currently meatspiking them
