### ISSUE TITLE
Autorifles have a pointless toggle fire action button

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#11983]
@Steelpoint 

Shouldn't be up there cluttering the screen

**Comment by Steelpoint** [comment]
Blame Paprika.

At least it no longer has the toggle option.

**Comment by KorPhaeron** [comment]
Why is it a child of auto if it doesn't have automatic capabilities?

**Comment by Supermichael777** [comment]
Because it *does* have an automatic fire mode.
It goes to two round burst if you e-mag it.

**Comment by Steelpoint** [comment]
What?
