### ISSUE TITLE
Bodies loop back from space ridiculously often now

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#11997]
>throw body into space
>comes back
>throw it again
>comes back
>again

Etc

Has happened since spacecube was killed.

@Incoming5643 @Miauw62 (I think you changed it?)

**Comment by Anonus** [comment]
Spacecube is dead, long live logical but terrible spaceloops!

**Comment by PKPenguin321** [comment]
this is because we sacrificed mostly-working gameplay for a space-object that obeyed the laws of physics

**Comment by AlexanderUlanH** [comment]
The solution would naturally be to clutter up space with some content.
That would also have the bonus advantage of making it viable to go after corpses when you know from where they were spaced.

**Comment by Incoming5643** [comment]
Actually even adding more space content wouldn't solve some of the spaceloops, because they're only 1 z level wide (i.e. a station to station loop would never pass through any tiles where you could put space content)

**Comment by Miauw62** [comment]
adding some more content will partially mitigate this, also making it easier to throw diagonally.

also
>people getting stuck in eternal loops in space almost every round
>working gameplay
kek

**Comment by KorPhaeron** [comment]
Eternal loops was better gameplay than being unable to dispose of bodies at least. I'm not exaggerating when I say I've spaced the same person three times, at three different angles/locations in a single round.

Without C4/welding fuel gibbing, and with spacing not working, there are very few ways to dispose of a body now which is pretty critical as far as traitor goes.

**Comment by phil235** [comment]
Two things need to be done to fix the problem: change the space torus' loops to always have at least two z levels; add some obstacles to the more empty z levels.

**Comment by Dorsisdwarf** [comment]
Spacing bodies is pretty core gameplay.

**Comment by KorPhaeron** [comment]
Still broken, still terrible. Spaced a guy 4 times and gave up on it last round.

**Comment by Incoming5643** [comment]
Throwing people on diagonals will help break looping, but then it's hard to do that without being in space yourself.

**Comment by Miauw62** [comment]
we just need more z-levels
