### ISSUE TITLE
if your brain gets put in a debrained gangster you can see whos in that gang but are never given a loyalty mesage

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#11996]
is this a bug?

**Comment by PKPenguin321** [comment]
pretty much yeah
however if this happens to you it's a good idea to assume that you're a gangster even though you didn't get the loyalty message

**Comment by Supermichael777** [comment]
note that you dont get the gang symbol yourself. you just see all the others.

**Comment by Jalleo** [comment]
Yeah this is probably a bug in how hud code is working there.

**Comment by tkdrg** [comment]
This does sound like a HUD bug and i have reproduced it but I have no idea why it happens and no idea how to fix it without hacks. from my testing join_hud() is probably not being called on brain insertion so idk why it's still in hudusers, but I can't figure out exactly where the hud is added.
