### ISSUE TITLE
Coming out of blood leaves you unable to hear things being said.

### ISSUE THREAD

**Issue by Aliannera** [tgstation/-tg-station#11995]
After coming out of blood after eating a slaughter demon heart, you are left deaf and unable to hear anything being said by anyone. It does not even show anything you say, along with no message that usually indicates you can't hear anything. It's as if nothing ever is being said despite people saying things. I was able to repeat it a second time after it occurred to me. No clue if this also applies to actual slaughter demons.

**Comment by Xhuis** [comment]
This is definitely the case with humans that bloodcrawl. It isn't the case with slaughter demons. I'm not sure why this is happening.

**Comment by WJohn** [comment]
On further testing, it was discovered that if multiple people do this, they are all deaf to eachother and themselves. You don't even see speech bubbles coming off either of you. You also aren't actually deaf because you can definitely hear sound effects still playing.
