### ISSUE TITLE
Transformation sting doesn't work properly

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#11998]
What happened: 

1. I extracted the clown's DNA with Extract Sting.
2. I stung, on separate occasions, two people who were probably not lings (the HoS and the Captain) with Transformation Sting and clown selected.
3. They got the "convulses wildly" message!...
4. Their appearance changed, but their name and voice did not.

Why this is bad: Because it's an expensive sting that produces a conspicuous message but doesn't work properly.

**Comment by Zilenan91** [comment]
Were the HoS or captain wearing masks? Their PDAs might have disguised them as themselves even though their appearances changed.

**Comment by duncathan** [comment]
>giving the HoS and the Captain CLOWNMUT

damn I never thought of that that's fuckin brilliant

**Comment by bgobandit** [comment]
phil already got this, but no, it's not the mask, and yes, I got an admin to reproduce it because at that point I was like wtf
