### ISSUE TITLE
[Bug] Captain's laser has new, gay name

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12001]
why do it

**Comment by Iamgoofball** [comment]
critical priority

**Comment by Lumipharon** [comment]
Some what related, if you give a gun some random fluff name (or a shit one like fk-69), you don't also need to tack on the end of the name what kind of gun it is.

IE: call a metaba a Unica-6, not a Unica-6 autorevolver.

**Comment by freerealestate** [comment]
i wouldn't know what a unica-6 was tbh

though i didn't know what a mateba was either until i fired it for the first time years back, so
