### ISSUE TITLE
Cardboard box ! easter Egg shares a global cooldown between all boxes

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12006]
@Incoming5643

**Comment by Shadowlight213** [comment]
@Dorsisdwarf This is a bug. Nowhere in the PR does it say this is intended behavior. The cooldowns should be per box.

**Comment by Dorsisdwarf** [comment]
I came back to the wrong tab after checking something out, my apologies.

**Comment by Incoming5643** [comment]
I don't see why this would be true, the egg var isn't global and it's only set to 1 for the local box.

Remember that for the egg to play someone ELSE has to open the box, if you're just going around trying to pop out of boxes and ! people it won't work, that's intended.

Also there's always the chance that someone ran around and triggered all the boxes for fun at roundstart or something.

**Comment by Shadowlight213** [comment]
Wasn't popping out myself. Does opening it when there's nothing inside start the cooldown? If so, that might have been the cause.

**Comment by Incoming5643** [comment]
Not supposed to, but I think I see what's happened here. I'll fix it in the pr I linked above.
