### ISSUE TITLE
Using an emergency oxygen tank to gib yourself (with the suicide verb) destroys your ID

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12013]
AFAIK IDs are meant to survive gibbings now

**Comment by Lijah99** [comment]
spooky

**Comment by feemjmeem** [comment]
I used the standard gib process which seems to be called everywhere else... (high-severity external attacks, singularity, et al). Can you give an example of an event in the game which causes the behavior you'd like to see?

**Comment by feemjmeem** [comment]
I'll just shred the clothing and that fixes several problems I've had with it. Let's see how that goes.

**Comment by Anonus** [comment]
IDs surviving gibbings was(is?) a bug, iirc.

**Comment by freerealestate** [comment]
i don't think it was, gibbers and the crematorium were changed to spit out ids
