### ISSUE TITLE
Gamemodes and traitor objectives prequisites are not checked.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/-tg-station#12018]
As it currently is, wether a traitor objective can be completed or not on the current map is simply ignored.

Gamemodes and traitor objectives should check that the map contains the objects required to complete said objective.

A few examples that currently are not checked:
Steal the reactive teleport armor.
Steal an ablative armor vest.
Steal the self destruct's plutonium core.

The absense of these objects, should prevent those objectives from being selected.

**Comment by bgobandit** [comment]
ablative is a bad example because it's in cargo

**Comment by kyrahabattoir** [comment]
Wait, so people have to steal a cargo shipping basically?

**Comment by Marflowerose** [comment]
It's plausible to get ablative vest from cargo by just asking, it's not really a difficult task when compared to stuff like Hijack or killing a spacefaring miner.

**Comment by kyrahabattoir** [comment]
It's just kind of odd to be asked to steal something that isn't on the station in the first place but i digress...

I believe gamemodes/objectives should do minimal checks to ensure they can be achieved.

**Comment by Dorsisdwarf** [comment]
Make a forum thread I guess.
