### ISSUE TITLE
Some surgeries make corpses partially non-interactable

### ISSUE THREAD

**Issue by Metacide** [tgstation/-tg-station#12016]
**Server revision compiled on: 2015-09-23**
*83452274526d8a7d2aebee716ba15bd32ef15e04*

**Short version:** *Some surgeries (eye-target organ manipulation surgery, perhaps brain surgery?) seem to break mid-way through, causing bodies to become un-grabbable and stopping text appearing when you attack the body. Possibly requires wrong order of tool-use.*

Yesterday on Sibyl I was the chef, got a few bodies, and thought: why not use this full set of surgical tools I have to harvest some organs before gibbing them? Did this merrily for a brain and appendix removal, but then hit this snag: towards the end of the next three surgeries, three bodies became partially non-interactable.

You could pull them with ctrl-click, but could not grab them to put in the gibber. Attacking them sounded like it worked, but gave no text message. Other players in the round had the same issue with the bodies, relogging didn't fix it. I tried aborting the surgeries by using the surgical drapes on the bodies with a cautery in my off-hand, and while it worked it didn't fix the issue. I admin-helped it but I don't think anything seemed that out of the ordinary and was asked to put in an issue report.

I got the issue first by trying to do an organ manipulation on the eyes (hoping to remove them), on what I think was the last step before haemostat / removal. I also got the issue trying to remove eyes again on a second body, and then when trying to remove a brain (I think) on a third. I couldn't remember the order to use the tools in, so was pretty much doing it randomly - perhaps that was the cause.

**Comment by phil235** [comment]
Likely runtimes in /atom/proc/add_blood(). Will fix

**Comment by Metacide** [comment]
Oops, sorry, it was yesterday with:

Server revision compiled on: 2015-09-23
83452274526d8a7d2aebee716ba15bd32ef15e04

So, maybe?

**Comment by Metacide** [comment]
Tried a few times but couldn't replicate it, so presume it was fixed with https://github.com/tgstation/-tg-station/pull/11963.
