### ISSUE TITLE
Nade launcher still fucked for syndie borgs

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#12024]
This bug has been around for fucking ages now - Synie borgs get a grenade launcher. After the syndie pin changes, syndie borgs CANNOT USE THEIR OWN MODULE because they don't have the correct ID for a syndie pin.

**Comment by Dorsisdwarf** [comment]
Maybe if I make it priority: High it will get fixed this time

**Comment by WJohn** [comment]
Oh look that worked!
