### ISSUE TITLE
Making a xenobio spawn sentient will cause the other mobs to murder it

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12037]
1. Create some spiders and carp and stuff
2. They're all peaceful towards you and each other
3. Give one a sentience potion
4.They flip out and begin tearing apart the lab in a quest to murder it

**Comment by Incoming5643** [comment]
A side effect of mob faction keeping.

In game reason: animals can smell a nerd

**Comment by Bawhoppen** [comment]
Isn't this intended though? I assumed it made sense they wouldn't like someone who betrays their natural ways.
