### ISSUE TITLE
The singularity drags footprints. 

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12039]
What happened: Lord singulo is loose, doing loose things, then:

(F) [Common] MAGI says, "I like how it is capable of dragging footprints from floors"

Why this is bad: 

Should be obvious.

Additional details: Sing was level 5 when this happened.

**Comment by RemieRichards** [comment]
can it move other decals? such as blood splatters?
I believe it can, if so, there's really no issue, otherwise you'd have footprints as the only immovable things in the universe.

**Comment by PKPenguin321** [comment]
this isn't even a bug
singulo is literally a black hole, they are more than capable of pulling blood from floors
in fact they are so strong they can pull humans apart molecule from molecule
