### ISSUE TITLE
Bluespace RPED works through cameras.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#12044]
There's grief potential that could happen with these which i'm too scared to even talk about.

**Comment by freerealestate** [comment]
Isn't this intentional?

**Comment by Jalleo** [comment]
No

**Comment by GunHog** [comment]
It is intended, @Iamgoofball

**Comment by WJohn** [comment]
I thought this feature got removed?

**Comment by Shapsy** [comment]
How can this possibly cause grief?

**Comment by Aloraydrel** [comment]
100% sure this is intentional

**Comment by Iamgoofball** [comment]
This is intentional.

@GrayRachnid How would you grief with upgrades? It's one of the most beneficial things science can do.

**Comment by GunHog** [comment]
You could grief with Bags of Holding by remotely sending bombs to people, but that was removed.

You could grief with BSRPED by...umm...making their machines work better? o_O

**Comment by Delimusca** [comment]
maybe you could warp rigged cells, but i don't think that would actually do anything.

**Comment by Miauw62** [comment]
It's intentional, but it's shitty and encourages science never leaving
their fortress and should be removed.
Op 27-sep.-2015 21:38 schreef "Delimusca" <notifications@github.com>:

**Comment by Shapsy** [comment]
I've only seen someone build a camera console in science like... once. It's really not that hard to just walk down the hall

**Comment by Lumipharon** [comment]
>tell people in the thread that this still works
>get told I'm a fucking retard
>literally watch the same guy do it every round

K.

**Comment by PKPenguin321** [comment]
woah woah woah i could've sworn that this got removed, what the fuck

**Comment by GrayRachnid** [comment]
@Iamgoofball Inject bluespace batteries with plasma, browse cameras, swap them those batteries with the ones in SMES, APCs, etc. And they explode leaving absolutely no traces behind as to how they happened.

**Comment by Iamgoofball** [comment]
1. apcs and smeses can't be used with the BSRPED
2. anything that could use a battery and can be BSRPED'd probably wouldn't cause it to explode

**Comment by GrayRachnid** [comment]
Just tested it, APCs can't be BSRPED, but SMES can be.
Also, I was wrong about them exploding. My bad, this doesn't seem to be an issue.
This was reported to me and I just posted it here without testing.

If this is intended then i'm closing it.
