### ISSUE TITLE
Explosions delete people in cardboard boxes

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#12055]
It's hard to replicate, but we had a train of five cardboard boxes going, and when a bomb exploded in our proximity, only one person was left intact - alive, severely damaged, dying from exposure.

The other four people in that train - myself included - were deleted. No giblets, no nothing; our bodies were gone in their entirety.

What could have caused this?

**Comment by bgobandit** [comment]
!

**Comment by PKPenguin321** [comment]
do you get deleted if you get caught by a bomb while in a locker, or just with boxes?

**Comment by Incoming5643** [comment]
There's no special handling for boxes, so I'd assume it'd happen with locker too

**Comment by Miauw62** [comment]
explosions gib people, then call ex_act() on the gibs, deleting them.

**Comment by Shapsy** [comment]
Boxes are so stealthy they leave no trace

**Comment by phil235** [comment]
Can't reproduce

**Comment by Dorsisdwarf** [comment]
IIRC, closets call ex_act on everything inside when ex_act is called on them.

So the closet is gibbing the person when it ex_acts, the gibs spray out, and then the explosion ex_acts the gibs.
