### ISSUE TITLE
Golems are no longer immune to electric shocks

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12051]
As in golems can be shocked by doors, lightning, etc.

**Comment by WJohn** [comment]
I don't recall electrical immunity as ever being one of their traits, but if it was and it stopped working then yeah, bug.

**Comment by Firecage** [comment]
They were immune to shocks before????

**Comment by Anonus** [comment]
Yes, they were, and could touch shocked grilles and doors because they had unremovable insulated gloves.
