### ISSUE TITLE
miners can get the objective to steal a jetpack

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#12059]
an object they can get within their job.

**Comment by Lumipharon** [comment]
Fun fact: The jetpack objective is completely and utterly pointless.
It counts jetpacks that come with certain hardsuits.
Like the syndicate hardsuit.
That traitors can buy in their uplink.

Yeeeah.

**Comment by xxalpha** [comment]
I thought this objective was removed.

**Comment by Bawhoppen** [comment]
The real fix for this would be to remove the objective or change objective to something like 'Steal captain's oxygen jetpack'

**Comment by SconesC** [comment]
"guys we have compact o2 harness jetpacks that move at the exact same speed as the NT jetpacks"
"nice"
"but steal the obviously inferior one anyway lol its really high tech trust me"

**Comment by Lumipharon** [comment]
A jetpack (atleast in game)is literally just a gas canister with a nozzle.

**Comment by Dorsisdwarf** [comment]
The syndies presumably steal them because NT needs them and the syndicate needs them to make into nuke op jetpacks.

**Comment by Bawhoppen** [comment]
I don't think the jetpacks should be IC-rare even if they are gameplay rare

**Comment by bgobandit** [comment]
make traitors have to steal a co2 jetpack

a rare jetpack, powered by an unknown gas

**Comment by Lumipharon** [comment]
meme aside, you can put any gas into any jetpack to make it work.

**Comment by Bawhoppen** [comment]
Not any gas, you can definitely use co2 and o2, but I don't think every other gas works.
Unless thats a bug.
