### ISSUE TITLE
Chameleon trait doesn't work with Dwarf trait.

### ISSUE THREAD

**Issue by TheDreamweaver** [tgstation/-tg-station#12053]
IF you have the dwarf genetic trait, then even if you have the chameleon trait, you don't turn invisible. IS this because dwarf isn't finished, as I notice you cant vent crawl yet.

**Comment by PKPenguin321** [comment]
first part is deffo a bug, but dwarves are not intended to be able to vent crawl at all lol

**Comment by phil235** [comment]
Can't reproduce.
