### ISSUE TITLE
Revenant speech is heard in lobby

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12060]
@Xhuis

**Comment by Xhuis** [comment]
why does this even happen

**Comment by Shapsy** [comment]
Literally how bad did you fuck up revenant speaking @Xhuis

**Comment by Shadowlight213** [comment]
@Xhuis revenant speaking doesn't skip the new player mob. It only checks for stat being dead.

**Comment by Nitrousoxide** [comment]
Def still seeing this as well.

http://i.imgur.com/ar5v1Xw.png
