### ISSUE TITLE
Walls built on resin floors will appear beneath them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12069]
This can basically mean invisible walls which will confuse the hell out of anyone looking at it. I don't think this even used to happen, since they're both layer 2 and it should have the walls placed on top since it's newer, but what do I know?

**Comment by WJohn** [comment]
To clarify, resin floors were set to layer 2 so they do not cover items, and so that blood spilled on them still covers them. Vents and scrubbers are also layer 2.1, so those are displayed above it (allowing easy vent crawling). I'm wondering why walls and floors are even at layer 2 and not something lower. Can't frankly think of really anything else that's at a lower layer. Maybe they could be set to 1.9 just to be safe?

**Comment by Bawhoppen** [comment]
Same with girders and stuff I believe, that is if the resin grows over them.

**Comment by Jalleo** [comment]
@Korphaeron
