### ISSUE TITLE
Ayylien cams bugged (Important) 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12073]
Ayylien camera console has a strange bug where when you first use it, you can use it correctly, but then with subsequent uses it immediately kicks you out of it and you go back to controlling your character. 

If someone else uses it at the same time it won't kick you off (or something), and theres a way you can double-glitch it to stick you in the camera mode if you do cancel camera view at the right time somehow. If you also hold down a direction button while viewing it right at the start you can be in it for a tiny bit longer, until either your character walks out of range of the console or some seemingly random time.

Literally unplayable as the camera is a critical component of the event/mode.

**Comment by AnturK** [comment]
Can't reproduce. More details what were you doing/ how you exited the camera view would be good.

**Comment by Bawhoppen** [comment]
I managed to get a reverse of the bug by using the cancel camera view verb as opposed to the one that is built into the camera view where if I don't move at all it shows me an Xray view of things around me.

**Comment by KorPhaeron** [comment]
I find letting them buckle into a chair fixes sometimes, for whatever reason.

**Comment by tedward1337** [comment]
Re-log. That fixes it.

**Comment by Bawhoppen** [comment]
@tedward1337 I definitely tried that multiple times. Did not work.

**Comment by Zilenan91** [comment]
I had this bug once, but it was so long ago that I don't remember how I fixed it. Try letting the other ayy use it for a bit, then use it again.

**Comment by Niknakflak** [comment]
Only could reproduce by pressing the cancel camera view verb and then it would be fixed the minute you click on the cancel camera HUD button again.  So the camera console isn't really bugged, it's the verb fucking with it

**Comment by tedward1337** [comment]
@Bawhoppen you need to relog using the options and messages window. 
http://puu.sh/ktY03/80b0b1afaf.png
