### ISSUE TITLE
Cult no longer has any gameplay

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12074]
Granted the old gameplay was trash, but still.

You now start with ~8-9 people, pretty much enough to do your objectives, so conversion is not really part of it. You don't have the timesink of researching either, you start with all your stuff unlocked. 

So you have 9 people roundstart, all armed with parapens, who have the objective of having 9 people to end the round (and kill one target before that). 

Cult should just be scrapped at this point. The most intense gameplay that results now is trying to get 9 people to stand in a square.

**Comment by SconesC** [comment]
"get on the FUCKING CIRCLE"
"lol"
"someone get the braindead guy here"
"holy shit soap"

**Comment by Anonus** [comment]
It's almost like cult needs a power system so they have to do stuff other than FUU MAJIN sac rune

**Comment by PKPenguin321** [comment]
technically a feedback forum issue, but i agree cultist scaling should be toned down

**Comment by Zilenan91** [comment]
Can we just disable cult from rotation until somebody does something about it? It's super shit.

**Comment by Supermichael777** [comment]
Someone didn't like how cult had to *gasp* WORK for its tools instead of being handed them at round start like every other antag. so they cut the mechanic without changing the underlying power structure.  this drove cult form op murder-party to ridiculously op murder-party. (if we cut cult, can it come back without the constructs?)

**Comment by Miauw62** [comment]
this is the same as ling with it being shit before and shit now and nobody knows what was more shit

disable it

**Comment by Bawhoppen** [comment]
We really should remove it from the rotation til its fixed, pending hand of god miracle solution.
