### ISSUE TITLE
Arrivals shuttle should not be destroyable/should respawn when someone joins

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12085]
What the title says, I think its bad that someone who just joined starts off in space dying. Plus the idea is you ARRIVE on the shuttle, they wouldn't ferry people over with a destroyed shuttle.

**Comment by Supermichael777** [comment]
yeah it sucks

**Comment by Lumipharon** [comment]
Daily reminder to make the nuke op (and like, arrival shuttle too I suppose...) indestructable again.

**Comment by Bawhoppen** [comment]
I want all shuttles to be destroyable, but made of a much more resilient material, like Hydrosinged Plas-titanium or something, but then have Arrivals shuttle respawn like a new one docks in it's place

**Comment by Dorsisdwarf** [comment]
If you really wanted to, you could always suggest doing it like Bay does, with a shuttle being held at Centcomm where people spawn, which then shuttles them to the station.

Or the arrivals shuttle could be treated like the holodeck, and refreshed with each arrival.

**Comment by Dorsisdwarf** [comment]
ideforum
