### ISSUE TITLE
Stabbing people in the eye has no attack animation

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12088]

**Comment by Marflowerose** [comment]
I think screwdriver eye stabbing doesn't have sound either, not sure if that's been fixed yet.

**Comment by Dorsisdwarf** [comment]
@RemieRichards you did attack animations, didn't you?

**Comment by RemieRichards** [comment]
@Dorsisdwarf I added attack animations in the only sensible place, where an attack occurs.
I'm not to be held liable of certain item "attacks" don't follow the rules.

**Comment by PKPenguin321** [comment]
>I think screwdriver eye stabbing doesn't have sound either, not sure if that's been fixed yet.

it has been fixed

**Comment by freerealestate** [comment]
not really a bug so much as a

# FEATURE REQUEST

or at least

# A CONSISTENCY ISSUE

**Comment by Dorsisdwarf** [comment]
It's a bug because remie damn well didn't intend for screwdrivers to be super-snowflake attackers that dont get called by their attack animations update
