### ISSUE TITLE
Magicarps shooting animation bolts will be attacked by animations

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#12097]
Anyway to make their animations friendly to them?

**Comment by Dorsisdwarf** [comment]
Sounds like Factions aren't being set correctly.

**Comment by Robustin** [comment]
Yea don't fix this.

Magicarps are already super annoying, last thing I want is to have them able to animate entire wings of the station.

**Comment by Incoming5643** [comment]
magicarp with animation bolts aren't that dangerous, because they won't naturally try to target things that can be animated, and can only strike animatable structures by missing shots at mobs.

Still very strange if factions aren't setting right.

**Comment by Marflowerose** [comment]
@Incoming5643 I'd imagine player magicarps can use animation quite effectively.
