### ISSUE TITLE
Fuego Plasma Burrito recipe is broken.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#12090]
/datum/table_recipe/fuegoburrito
	name ="Fuego plasma burrito"
	reqs = list(
		/obj/item/weapon/reagent_containers/food/snacks/tortilla = 1,,
		/obj/item/weapon/reagent_containers/food/snacks/grown/ghost_chili = 2,
		/obj/item/weapon/reagent_containers/food/snacks/grown/soybeans = 1
	)
	result = /obj/item/weapon/reagent_containers/food/snacks/fuegoburrito
	category = CAT_FOOD

**Comment by Dorsisdwarf** [comment]
What the hell is category = CAT_FOOD

**Comment by Profakos** [comment]
The problem is that there are two commas between the tortilla and the ghost chili definition, probably

**Comment by Xhuis** [comment]
@Dorsisdwarf CATEGORY_FOOD

**Comment by Cheridan** [comment]
:joy_cat: :meat_on_bone:
