### ISSUE TITLE
Ling transformation ability's PDA and ID now makes it extremely obvious when someone is a ling

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12091]
It now force-equips an irremovable PDA and ID which match those of who you transformed into, if the slots are free. You can only open access locked doors with PDA/ID in hand and anyone who tries to unequip the PDA and ID (such as security during a search) will be unable to.

The PDA also takes up the belt slot, which is an obvious tell due to 99% of the station making placing their ID into their PDA and their PDA into their ID slot one of the first things they do upon spawn.

I understand the logic behind giving changelings free PDAs and IDs to encourage them to transform more, but this just adds a whole lot more ways of telling a transformed ling apart from a real crewmember and gimps the transform verb itself.

Sorry if this is a duplicate, I didn't see anything when I searched the issue list.

**Comment by RemieRichards** [comment]
>The PDA also takes up the belt slot, which is an obvious tell due to 99% of the station making placing their ID into their PDA and their PDA into their ID slot one of the first things they do upon spawn.

Hilarious, but wrong, this doesn't mean you're a ling, it means you like your ID out of your PDA.

**Comment by freerealestate** [comment]
That's a pretty dumb thing to say. There's no reason why anybody would prefer their ID out of their PDA. All it does it unnecessarily take up your belt slot.

**Comment by RemieRichards** [comment]
You can't argue this, there's a PR up at the moment about PDAs and IDs and there's a good number on BOTH sides, so you cant dismiss them all as changelings every single round rofl.

My stake? I don't like the flesh disguises at all, it's more annoying than anything else.

**Comment by freerealestate** [comment]
People have been asking to start with their ID in their PDA for years.

If you look around the station (I'm not sure how often you actually play), you'll see 99% of players have their ID in their PDA so that the have access to their belt slot.

>My stake? I don't like the flesh disguises at all, it's more annoying than anything else.

Yeah, I checked. You didn't code this or pull it, and if you agree they're annoying, why the condescending and defensive tone?

Even if I were wrong and there were 50% of player who don't use their belt slot and instead hold their PDA there (which is a stupid thing to claim), it wouldn't change any of the other points I've raised about how easy this makes it to test for changelings.

**Comment by RemieRichards** [comment]
@freerealestate because of you flagrant disregard of a portion of the playerbase (of which I am one) which I found funny. While I've seen people who DO put there IDs in PDAs say things about people who don't, I've never seen them even REMOTELY suggested it hinted the person was an Antagonist, which again, I found funny. tl;dr I found it funny and was joking around.

**Comment by freerealestate** [comment]
You never use your belt slot? What purpose does having the ID outside of your PDA serve?

And it has become an antagonist tell with this change, which can be confirmed simply by trying to search the person and attempting to remove the PDA and ID.

**Comment by RemieRichards** [comment]
OMFG I'm not arguing this with you, go to the other PR, read what we've already written over and over.
You using it as an antagonist tell does not make you smart or clever, it makes you stupid, as you're falsely equating the two.

**Comment by freerealestate** [comment]
Clearly it's not always going to indicate an antagonist, but during a changeling round it likely will due to the amount of people who like using their belt slots.

I don't want to argue with you either tbh

**Comment by Delimusca** [comment]
i don't get why the ling transform stuff is nodrop,  they could totally be detachable ling flesh items.

**Comment by Dorsisdwarf** [comment]
F E E D B A C K F O R U M

Week's amnesty to be spotted by relevant coders else it will be ignored under a mountain of "Cannot valid lings with toolbox" and "Security griffed me remove harmbaton" threads.

**Comment by KorPhaeron** [comment]
>coders tell people to go to github to be heard
>people get told to go back to the forums when they post on github

**Comment by freerealestate** [comment]
yeah, feedback/feature requests on here were fine until *SOMEONE* got collaborator 

either way i'm not too worried, over time enough people will roll ling and get a chance to try it out that i think they'll realise how dumb and non-functional it is, creating a consensus which will motivate someone to fix it

**Comment by Firecage** [comment]
I don't see the actual issue here? Especially about the PDA and ID part? Most people don't put their ID's in their PDA's, and even leaves their PDA's on their belt slots.

**Comment by Dorsisdwarf** [comment]
@freerealestate I have a mandate from god to crush issues.

Or maybe Aranclanos & Cheridan.

One of the two

**Comment by freerealestate** [comment]
>I don't see the actual issue here?

Did you read the report?

**Comment by Dorsisdwarf** [comment]
The issue is apparently that having your PDA on your belt is a ling tell.

**Comment by phil235** [comment]
@freerealestate 
When transforming into someone, it puts fleshy duplicates of the target's belongings in the exact same slots that your target used for its stuff. E.g. : target only had a pda (with ID inside) in its ID slot, and no belt, therefor your fleshy disguise will have a PDA in the ID slot and nothing in your belt slot.

Of course, if you don't remove your own ID before transforming, the flesh PDA will appear on your belt. So this isn't a bug or anything. If the ling is caught because of that, it's his fault for not transforming correctly. And if you don't want your target's clothes simply use the Drop Flesh Disguise option in Transform, after you've transformed.

**Comment by Miauw62** [comment]
trying to strip lings from their flesh clothes making it obvious that they are a ling is intended btw.

also i still don't actually see the problem.
if you transform into somebody who had their id in their pda and their pda in the id slot, you will have a fake pda in your own id slot, and it will look to everyone as if you just have your id in your pda in your id slot.
