### ISSUE TITLE
Disablers on swarmers encourages them to combat 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12093]
Swarmers are supposed to be a somewhat non-combat side antag, and the only reason they should need disablers is for defense, however letting them have infinite free ones just encourages them to hunt and fight instead of just CONSUMING. Remove the disabler beams for them or let it cost points

**Comment by Anonus** [comment]
@Ergovisavi please dunk this nerd

**Comment by PKPenguin321** [comment]
f e e d   b a c k    f o r u m

**Comment by Bawhoppen** [comment]
the forum doesn't do anything for something like this, you need to go directly to the problem

**Comment by phil235** [comment]
I definitely agree with this, I've literally been chased and shot by swarmers without ever being aggressive toward them in any way. The disabler should probably be either be removed or replaced by a melee-disabler.

**Comment by Supermichael777** [comment]
swarmers die very easily to lasers. they need a counter and disablers provide it.  its balanced by a long cool down. also people tend to be quite hostile to swarmers going out of their way to ensure they are killed so shoot first is to be expected.

**Comment by Bawhoppen** [comment]
Make the disablers cost resource, so they only use them when they have to.

**Comment by xxalpha** [comment]
I told you this would happen.

**Comment by Zilenan91** [comment]
If it costed resource then swarmers would never ever get anything done. They would suck. Hell, they already kinda suck unless 99% of the crew is dead ot be swarmers.

**Comment by PKPenguin321** [comment]
> the forum doesn't do anything for something like this, you need to go directly to the problem

haha yeah but really though feedback forum

**Comment by bgobandit** [comment]
the thing about swarmers fighting people is the moment they see people they are FUUUUUUUUUUUUCKED unless they can somehow get into a vent before the human comes near with a toolbox or, more likely, disable them.

**Comment by Bawhoppen** [comment]
From the other perspective, its impossible to ever get rid of them. Even if you die you know there will be more swarmers. And ventcrawling is easy

**Comment by Miauw62** [comment]
feedback forum pls
