### ISSUE TITLE
Emping the AI core doesn't cause it to call the shuttle

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12095]
According to https://github.com/tgstation/-tg-station/blob/bfbe4e997efb3a5953f1de04c20deb191ff3138b/code/modules/mob/living/silicon/ai/ai.dm#L370
There's a chance for a shuttle call to happen if the Ai core is Emped. I've seen lings and revenants Emp the core for ages, and this never happened.

**Comment by GunHog** [comment]
It is because of the shuttle call reason update. When EMP'ed, the AI is given a prompt to input the reason instead.

**Comment by Shadowlight213** [comment]
@gunhog it should probably just call the shuttle with an error message as the reason then.

**Comment by Shadowlight213** [comment]
@dorsisdwarf it is a bug silly. This is part of the code that doesn't function correctly due to an update for something else. Definition of a bug.

**Comment by GunHog** [comment]
Agreed, it is, in fact, a bug.
