### ISSUE TITLE
Die a glorious death objective is dumb

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12106]
The objective just encourages people to assassinate whoever, and then just murder til they die as opposed to needing to try and stay alive for the rest of the round, and its just plaint too easy. It should be an admin only objective.

**Comment by Dorsisdwarf** [comment]
F E E D B A C K F O R U M

**Comment by GunHog** [comment]
Why do you leave the issues open after you direct the reporter to the feedback forum? 

On topic, I love the die objective for the same reason you hate it: It is a license to cause as much damage before you go down! That is the whole spirit of it! Would you rather have traitors that get easy objectives such as "Steal a jetpack" to do just that, and nothing more?

**Comment by Durkel** [comment]
The point is to cause chaos and kill as many people, That's exactly what it's supposed to be.

**Comment by Dorsisdwarf** [comment]
I leave them open for a week so bored coders are more likely to swoop on nifty ideas, even if they shouldnt be on the damn issue tracker

**Comment by AlexanderUlanH** [comment]
Glorious death objective is great.  An occasional traitor who can risk everything and go ham and still get greentext without killing literally everyone makes the game a better place.

**Comment by duncathan** [comment]
My best traitor story was about locking myself in a room with my target, planting a syndibomb, buckling into a chair and telling my target that both our lives rest in his hands. He cut the wrong wire.

**Comment by Aloraydrel** [comment]
Only problem with die a glorious death is explosive implants don't exist anymore for traitors

**Comment by PKPenguin321** [comment]
>I leave them open for a week so bored coders are more likely to swoop on nifty ideas, even if they shouldnt be on the damn issue tracker

that kinda defeats the purpose of closing them at all

**Comment by Dorsisdwarf** [comment]
We close them so that we don't get a second wave of the hideous bloat that sent us up from ~400 issues to ~800, and also because it annoys the other maintainers.

**Comment by Dorsisdwarf** [comment]
Closed
