### ISSUE TITLE
Ancient pinpointer sprite bug

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12107]
When you turn on a pinpointer it grows a set of buttons and the shape changes slightly, and the screen is a bit whiter (whiteness prolly intended)

![ss 2015-10-02 at 05 01 32](https://cloud.githubusercontent.com/assets/6510293/10244109/c16fa4ae-68c2-11e5-89db-b9fb6ebb703a.png)

This bug has existed a long time and its just slipped everyone's notice, or people didn't bother to fix or report it ever.

**Comment by Supermichael777** [comment]
most people are too concerned about DAT FUCKKKN DISK to notice
