### ISSUE TITLE
Nuclear codes request should have a different sound

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12103]
If I'm afk and I hear 'new command report created' I assume its something important, not just some chucklefuck clown asking for the auth codes

It also doesn't fit either, Its not a new command report, its a authorization request

**Comment by freerealestate** [comment]
Should be that loud, severe sounding tone that plays when access restrictions are lifted from maint

**Comment by Dorsisdwarf** [comment]
It's a command report because command are reporting that someone's trying to nuke you

**Comment by freerealestate** [comment]
yeah but delta alert is a command report too, as are maintenance restrictions being lifted, are they not? and they each have that severe sounding tone.
