### ISSUE TITLE
Items appearing above darkness.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12119]
![](http://i.imgur.com/WBBooJ2.png)

I have no idea how this happened.

This was over the corpse of a ling, I think? Definitely over a corpse.

**Comment by Dorsisdwarf** [comment]
This is a dupe. Items from destroyed (IE burnt, shreded) backpacks stay on the HUD layer

**Comment by Dorsisdwarf** [comment]
#10511
