### ISSUE TITLE
Can't pick up bullet casings with rubbish bag

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12110]
Also goes for other items of trash in certain conditions too. For example I encountered a couple of ramen cups by themselves and they wouldn't pick up until I moved them onto a pile of trash and picked up the whole pile.

This was with the janiborg's rubbish bag, by the way, if it makes a difference.

**Comment by Supermichael777** [comment]
ramen cup is a known bug with containers and pickup mechanics. someone should get on that.

**Comment by Lumipharon** [comment]
I've definitely been able to pick up casings in the past few months, so it must be a fairly recent bug.

**Comment by phil235** [comment]
I think this is due to #8451 which changed ammo_casing/attackby to not call the parent. So it's been quite a few month apparently.
