### ISSUE TITLE
You can't unbuckle people from pipes

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#12128]
You can buckle a handcuffed person to pipes, and both they and you will have no way to get them free from said pipe unless you remove their handcuffs,

**Comment by Marflowerose** [comment]
I think this is ancient bug that was reported some months ago but it was waved off since "nobody even knows you can cuff people to pipes"

**Comment by duncathan** [comment]
Actually this bug was caused (well, uncovered) by another bug being fixed. 
It used to be that if you buckled someone to a pipe, they started ventcrawling. I can probably fix this.

**Comment by AnturK** [comment]
Might be just missing ..() but to be honest i completely forgot about testing pipe buckling while i was moving it around.
