### ISSUE TITLE
misplaced gas flow meter

### ISSUE THREAD

**Issue by tuypo1** [tgstation/-tg-station#12120]
in maint east of the gateway there is a gas flow meter not connected to any pipes presumably broken in the recent piping overhaul

it just looks ugly and out of place and can make people who don't know about it think somebody is fucking with atmos

Server sybil

server revision c9433333ce605e1b0afc9e73e9e4d3aaedeebb0f

![scrnshot1](https://cloud.githubusercontent.com/assets/13944217/10262647/18d3c922-6a04-11e5-9f12-1c8e131f4fec.png)

its right above the ghost in the center

**Comment by WJohn** [comment]
Oops, my bad!
