### ISSUE TITLE
Pop-up spam is getting unmanageable.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12134]
With holo parasites, revenants, abductors, and ANY CONSTRUCT all giving loud, annoying, control-stealing, keyboard-input-accepting pop ups, it's becoming absurdly easy to accidentally register yes or simply be unable to type because you can have pop ups appear pretty much *every 5 seconds*. We also already have a system in the chat, for swarmers, posibrains, adamantine golems etc who all give much less intrusive requests.

This is both a consistency and usability issue, because we already have a method of requesting ghosts to join in, and it's INCREDIBLY spammy and annoying to accidentally register yes.

**Comment by Iamgoofball** [comment]
remember when I suggested that instead of having popups, it just signs you up for it with an opt-out button and everyone said it was dumb to not use popups for it

**Comment by Lumipharon** [comment]
Pop ups would be fine if it wasn't for the fact that you can spam the shit out of ghosts.

**Comment by PKPenguin321** [comment]
have the button to opt in to roll for the role be in a link in the chatbox

**Comment by optimumtact** [comment]
Should be a bunch of alert action buttons that appear along the side or top of the HUD

**Comment by PKPenguin321** [comment]
or put the opt in button in the chatbox and have a popup that tells you a  special role is available that is closed with an OK button
that way you get all the alertness and accidental button pressing of a popup with none of the accidental opting in

**Comment by bgobandit** [comment]
just add "Never for this round" options like pAIs have

**Comment by WJohn** [comment]
To further this point: It is at its absolute worst when sentient spiders happen. You will get a pop up every 5 seconds for the rest of the round.

It takes your control, accepts keyboard inputs while typing, and is INSANELY spammy and annoying.

**Comment by optimumtact** [comment]
Text popups == bad

chat links + alert icon == good

**Comment by duncathan** [comment]
Once I was typing a response to an ahelp about a bug when an admin offered control of something
It hit "yes" automatically and suddenly I was in control of the station AI
Not a fun time

**Comment by WJohn** [comment]
This is insanely common with holoparasites, too.

**Comment by KorPhaeron** [comment]
@tkdrg @duncathan 

@MrStonedOne one just fixed this
