### ISSUE TITLE
Borgs are immune to bolts of death

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12139]
I hit a borg with two bolts of death from a staff of chaos, did nothing, not even a hit message.

**Comment by Firecage** [comment]
That is strange. Yesterday I saw a syndiborg being hit by a bolt of death from a wand of death. It died.

**Comment by phil235** [comment]
The lack of hit message could indicate a runtime.

**Comment by Zilenan91** [comment]
I did see some other staff of chaos weirdness where magic projectiles were going through the borg and to the side after going onto the same tile as said borg, so that might have something to do with it, but I don't remember seeing the death bolts actually doing anything but hitting the borg.

**Comment by phil235** [comment]
The staff of chaos shoots random bolts, not just bolts of death. How do you know you fired a bolt of death if you had no hit message? @Zilenan91

**Comment by Zilenan91** [comment]
Bolt of death sprite, hit a borg twice with them and it did nothing.
