### ISSUE TITLE
Recycler cannot recycle plasma

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#12131]
Simply put, the recycler cannot extra plasma materials from anything...largely, in part, due to the fact it lacks a plasma materials datum.

https://github.com/tgstation/-tg-station/blob/f9a01d1365aefabc478d747615216120ad90bbcc/code/game/machinery/recycler.dm#L26

**Comment by WJohn** [comment]
Would this be considered a bug or an oversight?

**Comment by Fox-McCloud** [comment]
Well, depends on what you mean by "overisght" vs "bug".

The end effect to players would definitely be viewed as a bug "how come these ores/these plasma coins aren't being turned into sheets?".

From a coding perspective, it would be an oversight--as someone just plain forgot to include plasma in the materials datum.
