### ISSUE TITLE
Monkeys can use Hand Labelers to communicate

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/-tg-station#12141]
Discovered this today. Making a note for myself.

**Comment by feemjmeem** [comment]
They can also turn stun batons on and off

**Comment by freerealestate** [comment]
What's wrong with them turning stun batons on? They can't use computers because they don't have the intelligence and can't read, but the stun baton thing only requires an opposable thumb.

Making anything they write with a hand labeller gibberish to humans makes sense though.

**Comment by feemjmeem** [comment]
They can't fire guns or do anything else which checks advanced tool users. There are a lot of things. This is a consistency issue.

**Comment by WJohn** [comment]
I'd say hand labelers isn't intended, but stun batons being toggleable is fine.

**Comment by Dorsisdwarf** [comment]
Stun batons is an intended feature. The reason they can't use guns is because when they could it was rediculous.

**Comment by feemjmeem** [comment]
Makes sense. I was just including it because someone complained about it when I dunked them with a baton as a monkey the other day.

**Comment by Lumipharon** [comment]
Why did we stop monkeys using guns anyway?
Surely no one can argue that they lack the dexterity to pull a trigger.

**Comment by freerealestate** [comment]
^

**Comment by feemjmeem** [comment]
I agree with that. I'd just as happily fix the inconsistency by removing the advanced tool check for guns, but it sounds like that was done for balance reasons, and that's why I think it's inconsistent.

**Comment by feemjmeem** [comment]
Today I learned that monkeys can also get holoparasites.

**Comment by Supermichael777** [comment]
monkeys can ventcraw. geting into the armory is trivial for them. thats basical the only justification i have

**Comment by Ricotez** [comment]
@feemjmeem holoparasites for Ian and Poly when

http://i.ytimg.com/vi/0BQLfk11QKQ/maxresdefault.jpg
