### ISSUE TITLE
Performance and Odd Redundancy: Pooling

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#12149]
Currently with pooling, the specific datum/atom's Destroy() is called then the vars are resets on it.

That said, what makes zero sense is that when an atom/datum is pulled *out* of the pool the variables of it are reset again. This seems unnecessary as the vars were already reset prior to it being placed in the pool--likewise, its' not really possible for the vars to be modified while it's in the pool.

Performance wise, resetvars is actually quite expensive, so calling it twice on the same object/datum incurs significantly more overhead.

It makes sense to be cautious, but making a process more expensive than it should be (particularly when the whole aim of this system is to increase performance) seems a bit odd.

**Comment by Aranclanos** [comment]
can you put an example? Just to be sure I know what you're talking about

**Comment by optimumtact** [comment]
@MrStonedOne @RemieRichards

**Comment by MrStonedOne** [comment]
Wait. What? Why!

Ya, that should be fixed if true

**Comment by clusterfack** [comment]
Not only that but as I mention in #12152 you can make resetvars exceedingly cheap

**Comment by Fox-McCloud** [comment]
@Aranclanos 

@MrStonedOne  Seemed to understand what I was getting at; simply put, when atoms/datums are placed in a pool, their vars are reset: https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/pooling/pool.dm#L96

then, when an object is pulled back out of the pool, its vars are reset again: https://github.com/tgstation/-tg-station/blob/009a53271ec9eb72ff0bdc181cb2dcc31ba6db62/code/game/pooling/pool.dm#L63

which is redundant as it's already in a de-referenced and clean state by the time its in the pool....likewise, resetvars, as a proc is very expensive, which @clusterfack also seems to be agreeing with.
