### ISSUE TITLE
Xeno larvas don't have me emotes.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12147]
While #11358 added me emotes for xenos and monkeys, the xeno larvas still don't have it. I'm gonna assume this an oversight.

**Comment by Dorsisdwarf** [comment]
If you're gonna tag your own reports, at least stick all the tags on it.

Still waiting for Xeno Wright.

**Comment by PKPenguin321** [comment]
>giving a phallic creature /me emotes

this can only end well

**Comment by Xhuis** [comment]
i feel like this is a bad idea

**Comment by WJohn** [comment]
The other xenos already have me emotes, let's go ALL THE WAY.
