### ISSUE TITLE
typing irc: in chat has wierd and crashing effects

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12148]
Typing irc: will create a link offering to add irc to your byond friendlist
typing irc: then anything directly after it, like for example irc:test will have one of two effects
It will either do nothing, or immediately crash your client.

**Comment by RemieRichards** [comment]
this is due to byond's "irc client" (aka: ancient buggy mess) that comes along with everything else.
Besides maybe some hidden variable to let us disable it OR maybe defining a new verb with it's name that does nothing, I don't think it can be fixed.

**Comment by Chnkr** [comment]
Byond issue: http://www.byond.com/forum/?post=1954473

**Comment by optimumtact** [comment]
not really a bug, so close this one

**Comment by Dorsisdwarf** [comment]
Crushed.
