### ISSUE TITLE
Malf Reactivate Camera ability doesn't remove static near reactivated cameras

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12156]
![yeah @GUN_HOG you fucked up](http://puu.sh/kypUF/ed343723a8.png)

**Comment by GunHog** [comment]
Sometimes the network chunks take a while to update. Also, shuttle areas are horrifically bugged. How long did you look at this after you used the ability? And are you sure the camera was not touched after your power fixed it? With a multitool, you can stealth-disable a camera by killing its focus.

**Comment by Anonus** [comment]
I'm sure it wasn't touched because I was testing my map alone like a nerd.
