### ISSUE TITLE
Goofbal is triggering me

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12174]
First he makes this meme: https://github.com/tgstation/-tg-station/pull/12169
Then he does this outta salt: https://github.com/tgstation/-tg-station/pull/12171
Then he pulls his one outta his ass: https://github.com/tgstation/-tg-station/pull/12173

and he still hasn't finished this: https://github.com/tgstation/-tg-station/pull/11476
and he never did fix this: https://github.com/tgstation/-tg-station/issues/9915

#TRIGGERED

**Comment by Niknakflak** [comment]
I'M BEING OPPRESSED

**Comment by Iamgoofball** [comment]
I'm waiting on 509 to go live so that I can make fulton code not-shit.

**Comment by Niknakflak** [comment]
EXCUSES

**Comment by Niknakflak** [comment]
#9915
