### ISSUE TITLE
Cloning pod should tell percentage complete from examine

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12177]
Right now to see percent you need to be next to it and click it or whatever, snowflakey shit. Make it so it says in the examine, would be very useful

**Comment by GunHog** [comment]
This suggestion belongs here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=30

That being said, your request is simple and very easy to do.

**Comment by Bawhoppen** [comment]
The reason I posted it here was kind of for consistency reasons, because other things you can just examine and see progress/status, while cloner pods you need to specifically snowflake click on

**Comment by duncathan** [comment]
yeah this is fair game as a consistency issue; the current functionality is very snowflake
