### ISSUE TITLE
Morphs dying creates piles with way too many items

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#12180]
Currently EVERY item a morph absorbs gets released into a single pile when it dies. These piles are so large that there is a good chance of locking up the game client when right clicking them. This is of course always an issue with piles containing too many items but the morph amplifies this problem.

proposed solution: spread the items over a 3x3 grid centred on the morph when it dies.

**Comment by Miauw62** [comment]
I wrote a randomstep function for slot machines, this could easily be used
here.
Op 5-okt.-2015 22:33 schreef "CPTANT" <notifications@github.com>:

**Comment by Marflowerose** [comment]
Alt+Click doesn't lag. Also might help if a mild acid was applied to items so some of them would melt.

**Comment by Dorsisdwarf** [comment]
Alt-click sure lags when you click on a morph pile. There can be a thousand objects in a successful morph, easy.

**Comment by CPTANT** [comment]
It is irrelevant that alt-clicking does not cause your game client to crash, for it is not up to the player to loophole around game-crashing bugs. 
A tile that crashes your client when right-clicked kinda sounds like a bug to me.

to fix it, you could also just only release the latest X amount of items a morph has eaten.

**Comment by Marflowerose** [comment]
@CPTANT that applies to most large stacks though, not just morphs. I assume it's some ancient BYOND issue since it hasn't been fixed ages ago, seeing as it's been around forever.

**Comment by CPTANT** [comment]
@Marflowerose 

Which is exactly why we should not create game situations that lead to known problems. Morph stacks are an order of magnitude larger than basically any other stacks that regularly (and not deliberately) occur.

**Comment by Shapsy** [comment]
Make the morph a big piñata and have all the stuff they ate explode out of them!

**Comment by Bluespace** [comment]
As someone who trades antag for morph fairly often I would adore being a literal loot piñata on the shuttle.
Also give morphs regurgitate option when?

**Comment by Dorsisdwarf** [comment]
Idea: When morphs die, they spawn a 0,0,1 biobomb on a 1-second timer, to disperse the lootpile and also scare the crap out of everyone
