### ISSUE TITLE
ResetVariables is Expensive

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#12198]
In datum pooling the proc `resetvars` is quite expensive when it's called---considering the whole point of datum pooling is to make creation of new objects cost less, overall--this is a bit counter-intuitive.

In any event, just posting this here so it's not forgotten, but @clusterfack provided a way to make `resetvars` very speedy:

>The difference in efficiency is almost incomparable, the looping is reduced significantly and initial which if you profile it is not actually that cheap is removed entirely, the cost is only a vars.len loop and a vars.len number of variable assignments which overall has negligible cost

/datum/proc/createVariables()
    pooledvariables[type] = new/list()
    var/list/exclude = global.exclude + args

    for(var/key in vars)
        if(key in exclude)
            continue
        pooledvariables[type][key] = initial(vars[key])

/datum/proc/resetVariables()
    if(!pooledvariables[type])
        createVariables(args)

    for(var/key in pooledvariables[type])
        vars[key] = pooledvariables[type][key]

**Comment by clusterfack** [comment]
Yes essentially the difference is you create a global associative list of the pooled types, each one holding an associative list of the pooled variables initial value (excluding the excluded variables).

This means you don't have to loop through the excluded list anymore, and you don't need to call initial anymore.

**Comment by Chnkr** [comment]
Interesting.

**Comment by Miauw62** [comment]
simple and effective, port he.
