### ISSUE TITLE
Spear embed is blatantly overpowered

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/-tg-station#12195]
60 damage, huge bleed, can't remove it yourself, you're just dead. Why not just change the embed chance to kill the person instead, because that's basically what it does. 

Think about it, it's not a javelin, it's not balanced for throwing. It's a metal rod with a piece of glass tied to it, being able to throw it 1) In a straight, aerodynamic path and 2) with enough force to completely lodge itself inside somebody, is stupid as hell and only remotely likely if the person has an Olympic medal in javelin throwing

**Comment by Miauw62** [comment]
1) :salt:
2) feedback forum
