### ISSUE TITLE
Can't unbuckle from janicart using 'buckled' icon without first removing trash bag

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12193]
You can using 'resist' though

Just a little consistency/QoL request

**Comment by phil235** [comment]
The only easy way to fix it would be to prioritise unbuckling when clicking the janicart. But would people be okay with having to unbuckle each time you want to grab the trashbag from the janicart?

**Comment by freerealestate** [comment]
I've never understood why the rubbish bag can't just go on the belt

It going on the cart has always been clunky

It seems like a holdover from the days before the belt existed, because it can't fit in backpacks
