### ISSUE TITLE
SMG Ammo: Metal Duplication

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#12197]
SABR Ammo (/obj/item/ammo_box/magazine/smgm9mm) costs 2,000 metal to produce, yet yields 30,000 metal when placed into an autolathe.

the magazine for the SABR needs to have 2000 materials for metal--likewise, its children (the fire/ap/tox mags) needs to have 3000 materials for metal.

this would also be a thing for the Autogun mags, too (/obj/item/ammo_box/magazine/wt550m9), only different metal values, of course.

**Comment by WJohn** [comment]
We really should just make it so items produced from autolathes/protolathes etc just keep the material content they were produced with.

Of course, you'd need to also make metal and glass work with it, and then you'd run into the problem of people making MORE EFFICIENT SHEETS OF METAL by effectively running 1 sheet in to get 4 sheets out (at which point they would stop being more efficient to put in).

**Comment by Fox-McCloud** [comment]
@WJohn 

Generally agree, then if you destroy stuff that has say, diamond in it, you don't feel like you wasted that diamond.
