### ISSUE TITLE
Xenomorph Queens cannot into Preatorian Parasite.

### ISSUE THREAD

**Issue by Aredal** [tgstation/-tg-station#12205]
It just gives a message that you need 450 plasma whenever you try to use it on a drone.

**Comment by WJohn** [comment]
Strange, it should work if you have 450 of more plasma. We tested this earlier and it worked.

@GunHog

**Comment by GunHog** [comment]
It...worked in testing....:(

**Comment by GunHog** [comment]
OH! I WAS TRYING TO USE THE TARGET'S PLASMA, NOT THE QUEENS! LOL! Will fix!

**Comment by WJohn** [comment]
No wonder. Should be possible to set it back to 500 plasma, then?

**Comment by GunHog** [comment]
If that is what you like, sure.
