### ISSUE TITLE
We need to decide between British and American spelling in code

### ISSUE THREAD

**Issue by Ricotez** [tgstation/-tg-station#12209]
Color and colour, armor and armour... The code leans heavily toward American spelling, but there are multiple instances of British spelling being used instead. It's not a MAJOR problem, but the less confusion we have the better, and there is at least one example of a piece of code that has a throwaway variable called colour, which might workaround the issue that color is a reserved variable name but is confusing.

So let's please settle for one or the other.

**Comment by Miauw62** [comment]
we have already decided on american spelling, its just that colour sometimes has to be used because color is a reserved byond variable

**Comment by RemieRichards** [comment]
No, it's:
Byond color var
Color or Colour depending on preference for anything else.
We haven't "decided on american", we haven't "decided" anything.

**Comment by Bawhoppen** [comment]
Coloer and Armoer confirmed

**Comment by duncathan** [comment]
Using `colour` as a var is silly, because it's only gonna cause confusion with `color `. Byond itself uses American spelling for its vars, as does most of the codebase. It'd be far easier to standardize the instances of British spelling to American, since there's less of them. 
Note: there's no bias here; I'm from Canada where we use British spelling and I prefer British spelling, but it's just more practical to use American.

**Comment by GunHog** [comment]
I will just leave this here.
>var/list/armor = list(melee = 0, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 0, rad = 0)
var/armo<b>u</b>r_penetration = 0 //percentage of armour effectiveness to remove

**Comment by PKPenguin321** [comment]
:us:

**Comment by xxalpha** [comment]
Using colour instead of color because color is already a variable name is bad practice. Do not do that shit.

**Comment by ike709** [comment]
:us: :us: :us: 
<code>somethingrelevant_color</code> is far better than using <code>colour</code> when <code>color</code> is already in use by byond

**Comment by Niknakflak** [comment]
Remie is just a dirty brit who wants everything to be the british way.  Needless to say, AMERICA

**Comment by kingofkosmos** [comment]
Is this a vote? If yes I vote for american since american spelling is more commonly seen in non-english speaking countries through media.

**Comment by tkdrg** [comment]
This isn't really an issue.

**Comment by Bawhoppen** [comment]
I must remind you guys that closing an issue doesn't remove the problem

**Comment by RemieRichards** [comment]
I must remind you that opening one doesn't prove there's an issue in the first place.

**Comment by Bawhoppen** [comment]
judging by how much this was talked about in the PR about this, I'd say this one is
but it's your codebase
