### ISSUE TITLE
These walls are not smoothing out for some reason

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12201]
![](http://i.imgur.com/4FIqwPL.png)
Problem: These walls in this image are not smoothing out for some reason.
Why this is bad: It looks ugly and something isn't working right
Anything else: Only seem to be doing this here, nowhere else on the mining station.

**Comment by Anonus** [comment]
A tunnel hit it and asteroid walls and asteroid wall updating is dongs

**Comment by Xhuis** [comment]
It happened in the artifact rooms I found earlier today, too.

**Comment by xxalpha** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/modules/mining/mine_turfs.dm#L612
