### ISSUE TITLE
Large glass door is borked

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12212]
I cri errytime o7

ps: its the sprite

**Comment by WJohn** [comment]
We lack the sprites for large airlocks and knew this was gonna happen ahead of time, but the ONLY place we see these used on is the nuke op base.

**Comment by Bawhoppen** [comment]
![ss 2015-10-07 at 09 37 09](https://cloud.githubusercontent.com/assets/6510293/10356326/986db5b4-6d3b-11e5-81fd-ba2368e0f80a.png)

**Comment by WJohn** [comment]
Yeah, I went ahead and made 2x1 glass door overlays for xxalpha. He should be making a PR to fix this tomorrow.
