### ISSUE TITLE
Discussion Needed: Options for Messy Suicides (e.g. Tank Suicide)

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/-tg-station#12224]
Tank suicides had to be reverted to, from a game balance perspective, address the following:

* Stop the destruction of items by players using a simple, everyday object
* Close the loophole which kills alien larvae and other such things (removing corpses for headslugs, etc)

Right now the code is half-in, half-out. Gibbing has been removed but the 'joke' is still there, so here are some options, please tell me which you'd prefer:

1) Remove the joke entirely. A reference to a scene in a movie where someone explodes doesn't work if they don't explode. Revert to no special suicide.
2) Drop all objects, undamaged, throw gibs, and bruteloss the body, so the corpse remains intact and the objects aren't destroyed, but people still get to throw gibs around.
3) Invent a new message which causes oxyloss.

This is also a good place to discuss messy suicides in general. I'd like to have a louder conversation about whether suicides should be text-only (NO FUN ALLOWED) or if, assuming game balance issues as above are maintained, we can throw some organs around from time to time or have entertaining animations, where appropriate.

**Comment by feemjmeem** [comment]
The scene in question:

https://www.youtube.com/watch?v=e4fj3sPBSa0&t=1m29s

**Comment by phil235** [comment]
Number 2 will be inconsistent when it drops torso gibs, heads, etc...

**Comment by feemjmeem** [comment]
There's a generic gib spawner that doesn't drop body parts, just gibs. gibs(loc, viruses, dna)

**Comment by Bawhoppen** [comment]
The gib suicide didn't destroy items.

**Comment by feemjmeem** [comment]
I wrote it; originally it just gibbed the mob, all items included. I submitted a fix which made it shred clothes and drop some items. People were still upset.

**Comment by feemjmeem** [comment]
@Bawhoppen also, you mentioned the telebaton suicide is bugged; howso?

**Comment by WJohn** [comment]
Why not just make it so all the items are dropped first, then you are gibbed?

**Comment by feemjmeem** [comment]
That destroys alien embryos. :(

**Comment by feemjmeem** [comment]
Unless we put a handler in there to make it an instant hatch, but that's a snowflake.

**Comment by feemjmeem** [comment]
Removing the corpse screws revenants and headslugs too. Not to mention things like debrain or impersonate objectives.

**Comment by Aranclanos** [comment]
I personally don't want suicides to be interesting at all, I'd like players to play the game instead.
I mean I didn't like the different texts for each object because of it. And probably knowing that it will eventually end up here.

**Comment by feemjmeem** [comment]
People are going to stop playing. I think having some suicides is superior to just having a bunch of braindead individuals or people throwing themselves into space, both of which we already have. While I understand not wanting to promote suicide, and I can sort of see the argument that not providing any kind of interesting suicide options at all would make people slightly more likely to try to play out the round, I think that at the end of the day people who don't want to play the round simply aren't going to play the round.

And I'd rather have that decision be able to be interesting or entertaining than a silent ghosting or biting off their own tongue -- which already happens.

**Comment by feemjmeem** [comment]
I was really hoping there would be more conversation about this :(
