### ISSUE TITLE
Too many orbiting ghosts = byond client crashes

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#12226]
This is probably firmly in the "byond issue" category, but rather frequently while observing if I jump into an area with many orbiting ghosts my client will crash. I know it's the ghosts because turning them off stops the crashes. Either the visual window will perminantly stop updating while the chat remains unaffected or the whole thing will just stop responding.

It would be nice if multiple rotating ghosts animated as a single image instead of many independent ones, but that is probably more trouble than it's worth.

Occurs both in current stable release and latest beta release. Computer resources don't seem to be capping out or anything BUT my laptop is a piece of shit.

**Comment by WJohn** [comment]
Holy shit, omnighost is a real terrifying thing now?

Not a bug.

**Comment by RemieRichards** [comment]
Likely a byond bug since you mentioned "Jumping" to an area, and Byond is historically shit with loading an entire new screen's worth of content (Bay/VG/Paradise had crashes with this and their lighting)

**Comment by tigercat2000** [comment]
The lighting issues were caused by rampant abuse of `animate()` which I believe orbiting also uses.

**Comment by tkdrg** [comment]
This is pretty much solved with new orbit.

**Comment by Incoming5643** [comment]
yep, just a little thing to remember going forward: If you start flooding clients with animate calls (and I mean A LOT OF THEM) it can start crashing lower end machines.
