### ISSUE TITLE
Nuke terminal layer same as alien weed layer

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#12239]
As a result, the terminal sprite will disappear underneath the weed sprite apparently.

**Comment by WJohn** [comment]
Why on earth is it layer 2? Make it layer 3 like all the other objects and structures in the game.

**Comment by xxalpha** [comment]
This is map edited to be on layer 2.

Salutations to the mystery mapper who did it.

**Comment by Dorsisdwarf** [comment]
New nuke terminal sucks anyway, let the weeds cover it up
