### ISSUE TITLE
Stand battlecry makes 2much spam

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12243]
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"
(F) Holoparasite Orange states, "ChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoChChoCh"

**Comment by KorPhaeron** [comment]
Phil already has a fix for this up

**Comment by Bawhoppen** [comment]
the wounds can never be healed even with a fix
