### ISSUE TITLE
Doubleclicking box as ghost does not make you orbit it

### ISSUE THREAD

**Issue by Ricotez** [tgstation/-tg-station#12248]
Basically what the title says. If you're a ghost and you doubleclick a box, you won't orbit (whoever is inside of) it. You have to wait for the person to pop out before you even know who's inside, so you can't use the Orbit command either unless you enjoy going through every possibility.

**Comment by Anonus** [comment]
same for closets and mechs just let ghosts arbitrarily orbit anything it'll be okay

**Comment by Dorsisdwarf** [comment]
Fixed (?)
