### ISSUE TITLE
Altar/tome desk should be usable

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12249]
They should be actual tables that you can put stuff on, thats all I want so they're not completely pointless. Like the one in the library backroom, it even starts with an item on it so its intended to be supposed to put stuff on it.

**Comment by KorPhaeron** [comment]
@tkdrg 

Kill

**Comment by tkdrg** [comment]
Not a bug yeah

**Comment by Bawhoppen** [comment]
reopen please its still really dumb
