### ISSUE TITLE
Spawning via buildmode is entirely unlogged

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12251]
All that's logged is the admin entering and exiting buildmode, there's no log of what they did with it at all and that's PROBABLY A BAD THING, OKAY.

**Comment by lollerderby** [comment]
If I remember correctly, buildmode stuff IS logged. Just search "build mode" in the logs.

**Comment by Niknakflak** [comment]
It's logged in the admin log.  This does not need a message for everytime an admin does something in buildmode because it's going to get absurdly spammy.

**Comment by Niknakflak** [comment]
It's logged, this can be closed
