### ISSUE TITLE
Dreamstation 3 : HoS has 2 Camera Consoles.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12260]
![](http://puu.sh/kDDCV/be6546b974.png)

![](http://puu.sh/kDDCt/dda31fdfab.png)

**Comment by Anonus** [comment]
I REALLY MADE THIS ERROR, FUCK
one of those should be a sec records console I'll fix it whenever I update the map, which is either next week or whenever it starts failing to compile
