### ISSUE TITLE
Dominator gives "not enough influence" error when enough influence available.

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#12261]
Attempting to spawn the dominator while on an area not on your territory gives two error messages instead of one like below, i spawned it after spraying so I know we had enough for it.

The dominator can be spawned only on territory controlled by your gang.
Not enough influence.

**Comment by Jalleo** [comment]
Those are two different ones spraying areas dont give you points to buy stuff directly it gives points every time a point update occurs.

**Comment by Shad0vvs** [comment]
I had 90 influence, I tried to say I had plenty of influence in the beginning post and that it wasn't the issue, There's no reason for it to say I don't have enough influence when I do just because I didn't spray the area for the dominator. It's an incorrect/buggy check.
Sorry if I made it confusing.
