### ISSUE TITLE
That securitron seems really unpowered you know?

### ISSUE THREAD

**Issue by Aredal** [tgstation/-tg-station#12265]
Securitrons made by robotics and not admin spawned seem unpowered, and do not work, ever.

**Comment by WJohn** [comment]
Works fine when table crafted, but hand assembled securitrons do not work.

Also to note: They only accept RIGHT cyborg arms while table crafting, which is really shitty.

**Comment by GunHog** [comment]
I have determined the issue and will have a fix shortly.
