### ISSUE TITLE
Sneaking Cardborg Box has a pretty big lighting bug

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#12276]
When you go into the box whatever light you were creating gets frozen in space/time until you step out of the box again.

So you light up a dark room, go into the box, wander off, and the room stays mysteriously lit until you leave the box again.

**Comment by Shadowlight213** [comment]
This happens with putting lights into a backpack as well.

**Comment by phil235** [comment]
probably a duplicate issue.

**Comment by PKPenguin321** [comment]
definitely a duplicate issue, happens with any type of locker

**Comment by Aloraydrel** [comment]
This also happens when you throw a light in your bag. Had a issue report on it but was poorly worded

**Comment by Anonus** [comment]
Lights are really broken in general

**Comment by Incoming5643** [comment]
Why is everyone ascribing general errors to boxes

**Comment by Shadowlight213** [comment]
@Incoming5643 Good question

**Comment by RemieRichards** [comment]
because most players don't know a cardboard box is a closet.

**Comment by PKPenguin321** [comment]
turns out closets are very buggy and people haven't noticed until they got a fancy closet that looked like a box

**Comment by Dorsisdwarf** [comment]
Dupe of #9545
