### ISSUE TITLE
AI logging only logs once (critical)

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12280]
So when an AI interacts with something such as a door or APC, it leaves administration a "hidden fingerprint" which tells us that an AI has used that or not so we can piece together situations from it.

It has just been discovered that no matter what happens, these fingerprints will only be left the first time an AI uses a door or APC or alarm.  It will log the first use and then not log it any other time even if the AI uses the APC again.  This is extremely misleading in logs and extremely bad that it isn't logging any other "Print" or use other than the first.

This caused major confusion during an investigation and currently all investigations involving AIs and potentially borgs are useless because we can only see the first time they interact with something.

**Comment by Supermichael777** [comment]
Tag FUCK Priority: CRITICAL Bug and logging

**Comment by Bluespace** [comment]
For reference this almost got me re-permabanned. I was going to test this myself today because I knew I wasn't lying. Glad it's sorted.

**Comment by tkdrg** [comment]
This happens to all mobs, not just AIs/borgs. It also looks intended. I guess I can remove that check, I'm a bit wary of removing seeming pointless checks but whatever.

**Comment by Niknakflak** [comment]
Bull fucking shit.  If this interferes with administration there is no "just deal with it lel".  Get it fixed
