### ISSUE TITLE
Revenants can become drones

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12282]
Click on it and it gives you the prompt to become one

**Comment by Anonus** [comment]
Probably the same for swarmers and posibrains.

**Comment by PKPenguin321** [comment]
i say we make this a feature and cause them to turn into rogue/haunted drones because it could actually be a pretty cool revenant ability

**Comment by Shadowlight213** [comment]
@Xhuis

**Comment by Xhuis** [comment]
This shouldn't happen. Revenants are a simple animal like corgis and... well, drones. The prompt to become a drone only shows when a ghost attacks, a ghost having a stat of DEAD while revenants have a stat of CONSCIOUS. Like I said, I have zero idea why this could happen.

**Comment by Anonus** [comment]
Does drone shell attack_ghost check for stat? I'd assume it doesn't, given that ghosts would normally be the only thing to trigger it.
