### ISSUE TITLE
You can make yourself huge with genetics.

### ISSUE THREAD

**Issue by Bluespace** [tgstation/-tg-station#12297]
Server revision compiled on: 2015-10-10
81880d86082193e7367d08528922cf0764a527b5 

Go to genetics.
Swallow a mutadone pill (immediately reverts all mutations when you get them.)
Find dwarfism block.
Inject self with clean SE with dwarfism defect in it.
You immediately get "Everything around you shrinks!" and then "Everything around you grows!"
Since it happens so fast your sprite never goes small, it's just scaled back up immediately because the game assumes it needs to. 
Repeat until several screens big. 

http://puu.sh/kFha6/ff4a52ee84.png

**Comment by Iamgoofball** [comment]
we are now vorestation

**Comment by Incoming5643** [comment]
Big blurry sprites just make me cry every time I see them.

Bug report theme: https://www.youtube.com/watch?v=m4whcYwfaiA

**Comment by phil235** [comment]
easy fix, just need to call update_transform() in dwarfism's on_acquiring() and on_losing() so the size change is done right away.

**Comment by PKPenguin321** [comment]
FEATURE

**Comment by Jalleo** [comment]
Thy thi tho thumb i smell the blood of a grey tiderman

**Comment by tedward1337** [comment]
F E A T U R E

**Comment by blobbernaut** [comment]
F E A T U R E

**Comment by phil235** [comment]
It might not actually be an easy fix on second though. I'm pretty sure there's a sleep() or something in update_transform() which would be really bad for genetics code.

**Comment by PKPenguin321** [comment]
R I P
