### ISSUE TITLE
Disposals outlet is ejecting stuff diagonally causing it to miss the conveyors.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12298]
![disposal](http://puu.sh/kFrA9/8d81113645.jpg)
Metastation cargo disposals conveyor is shown here, but the same thing happens on box in the crusher room where items will eject and land on the conveyor belt below the crusher, bypassing it completely.

**Comment by phil235** [comment]
From my tests, I think it only happens the very first time the disposal outlet expels something and only if it's items (not mobs). (and only when the disposal pipe underneath points in a direction different from the outlet's.

**Comment by Shadowlight213** [comment]
@phil235 This isn't just happening one time though. I think about half the items are being misejected from what I've seen.

**Comment by phil235** [comment]
Well, I'm testing on box and can't seem to reproduce it more than once. the expel_gas proc of the outlet expels gas that is in the disposal holder which pushes the item away. And the gas expelled is pretty much null every time except for the first time.

**Comment by Lumipharon** [comment]
>shutdown space wind pr fix
>promise their own fix

>never happens

**Comment by Metacide** [comment]
Not at all sure how to fix this - the disposals piping on MetaStation lines up neatly with the exit direction - moreso than Box's, even, with an identical outlet pointing east instead of north. I guess the spacewind can just push stuff down on MetaStation because there isn't a wall at its side to stop that.

**Comment by Shadowlight213** [comment]
@Metacide You could add window panes next to the disposal outlet to block the items. That should help with the issue without taking up too much space.

**Comment by Metacide** [comment]
I think it used to be that but looked a bit janky and might have caused some issues, can't remember exactly what. I'll give it a go, though.
