### ISSUE TITLE
Entire lighting engine

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12292]
how is it still not fixed

we literally have an entire gamemode that relies on lighting and darkness yet the lighting engine isn't fixed

**Comment by WJohn** [comment]
Dupe of a billion and a half issues.

So yeah I guess it's relevant, but mrperson won't fix it. Maybe phil will save us from this, too?

**Comment by CosmicScientist** [comment]
A "lighting" label might go a long way into sorting the dupes and PRs involving them since this is a problem that comes up time and again.

**Comment by MrStonedOne** [comment]
It's broken?

**Comment by phil235** [comment]
No idea what this issue is about.

**Comment by Bawhoppen** [comment]
Like everything bugs when you turn off lights, it doesn't register light changes and stuff, lights don't stack, etc. 
Countless problems that plague it

**Comment by Bawhoppen** [comment]
CODER OPPRESSION, this is a legitimate problem

**Comment by phil235** [comment]
Issue reports need to be specific. Just saying "lighting is broken" is not a useful report. If you add more details about one specific bug I'll reopen the issue.
