### ISSUE TITLE
syndicate pizza bomb cannot be stacked ontop of other pizzaboxes 

### ISSUE THREAD

**Issue by grink** [tgstation/-tg-station#12301]
i tried to put a syndicate pizza bomb ontop of a stack of other pizzas but it would just not work

**Comment by Incoming5643** [comment]
though they're intended to be decoys, in the code they're very different things.

**Comment by Miauw62** [comment]
PRIORITY: CRITICAL
Op 11-okt.-2015 01:10 schreef "Incoming5643" <notifications@github.com>:

**Comment by Xhuis** [comment]
What Incoming said. Pizza bombs are entirely different objects than pizza boxes. I might refactor these eventually, though.

**Comment by neersighted** [comment]
Working on it
