### ISSUE TITLE
Blob talk power makes dead blobbernauts speak in deadchat

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#12302]
DEAD: blobbernaut gurgles, "fuck you guys"
DEAD: blobbernaut gurgles, "fuck you guys"
DEAD: blobbernaut gurgles, "fuck you guys"
DEAD: blobbernaut gurgles, "fuck you guys"

Hilarious but probably not intended.

**Comment by Aliannera** [comment]
I always found this hilarious. Leave it as a feature I say.

**Comment by Incoming5643** [comment]
E V E N  I N  D E A T H  I  S H I T T A L K

**Comment by Iamgoofball** [comment]
fucking keep it in

**Comment by RemieRichards** [comment]
been in since me and goof last touched blob, and should remain so for eternity.

**Comment by Shapsy** [comment]
I remember one time HBL warned the blob spores for spamming deadchat, was top funny

**Comment by JJRcop** [comment]
sorry

**Comment by Iamgoofball** [comment]
:-1:
