### ISSUE TITLE
Lying down is super bugged

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#12312]
More then once now, I have seen myself and other, after the shuttle leaves station, fall over, and never got back up.
If someone else manually shook us up, we'd get up, but otherwise you'd just be stuck lying down for no particular reason.

I'm unsure if this can occur in other situations.

Additionally, if you take damage in this state, you don't actually recieve that damage until AFTER you get back up (one way or another).
For example in the round that just ended, I was stuck lying down, and someone shot me like 7 times with a revolver. Someone shook me up about 10 seconds later, and I was able to walk around fine for another 10sec or so, before I suddenly dropped dead from delayed damage.

No clue what is causing this.

**Comment by Incoming5643** [comment]
kinda sounds like something is holding up human life

**Comment by phil235** [comment]
it sounds like a runtime, yeah.

**Comment by Jalleo** [comment]
@mrstonedone possible mc lag?
