### ISSUE TITLE
Can't debrain aliens

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12311]
Attempting to use a scalpel or circular saw on them after applying the drapes to their head and selecting 'organ manipulation' just results in attempting to butcher them

**Comment by Supermichael777** [comment]
still?
blame whover mad aliens bucherable

**Comment by freerealestate** [comment]
or just removing the butchering ability from the surgical instruments needed to perform surgery on them

or even just making it so you only butcher with them on harm intent

**Comment by Firecage** [comment]
Do you mean the xeno simple animal or the xeno mob?

**Comment by phil235** [comment]
The carbon xeno I presume, since Kor moved butchering from simple animals to mob/living not long ago.

**Comment by duncathan** [comment]
Carbon aliens were actually butcherable before Kor's PR

**Comment by freerealestate** [comment]
The xeno mob

**Comment by Dorsisdwarf** [comment]
Xenobio mobs have never been deorganable for obvious reasons

**Comment by freerealestate** [comment]
uh yes they have

**Comment by phil235** [comment]
We're talking about carbon xenos, not the simple animal ones. @freerealestate is talking about doing surgery on a carbon xeno and the surgery steps requiring the saw triggers butchering because of https://github.com/tgstation/-tg-station/pull/11937/files#diff-b543c2a6b5f34f24bd967d76adce2589R5

**Comment by phil235** [comment]
>or just removing the butchering ability from the surgical instruments needed to perform surgery on them

Not doable since there's also all the ghetto tools. Plus not being able to butcher a corpse with a circular saw would be inconsistent.

>or even just making it so you only butcher with them on harm intent

That's one possibility.
