### ISSUE TITLE
Shades instantly dying

### ISSUE THREAD

**Issue by Aredal** [tgstation/-tg-station#12320]
I clicked yes on one of the pop ups for shades in a cult round. I spawned dead.

**Comment by Dorsisdwarf** [comment]
More info plz

**Comment by Aredal** [comment]
I got a pop up for the soulstones new feature which is that if there is no soul in the body a random ghost can choose yes on the pop up to replace that person, the person apperantly was still in the body though he said that atleast, and then I became his shade but I was automatically dead. So I became a soul of a shade instead of a shade

**Comment by Dorsisdwarf** [comment]
Sounds like the check for letting you in if theres a mind in the body failed.

**Comment by phil235** [comment]
Caused by https://github.com/tgstation/-tg-station/commit/9648402d12e795657b14d98966efa53cf84048b0
