### ISSUE TITLE
Pneumatic Cannon Firing Bug

### ISSUE THREAD

**Issue by Ninja137** [tgstation/-tg-station#12328]
Pneumatic Cannons don't seem to fire properly. As far as I can tell, it's something to do with the intent you're on. If you're on Help? It fires just fine. If you're on Harm? It tries to hit them, even if it's at range, or at least that's what it seems like. The point is, it doesn't actually shoot people.

**Comment by joonoro** [comment]
Yeah it's really counter-intuitive. It fires if you're on any intent *other* than Harm and the only way to stow it in your backpack safely without it going off is to do it with Harm intent.

**Comment by Ninja137** [comment]
Yeah, just confirmed it. If you're on harm, the cannon WILL NOT FIRE. At all. It refuses to, and there seems to be no fucking REASON for it. For the love of god, fix this shit now.

**Comment by Xhuis** [comment]
This was intentional and implemented in order to allow being able to bit things pointblank with the cannon. This is an easy fix and I will work on it when I get home.
