### ISSUE TITLE
tacticool turtleneck

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12337]
For some reason you can't change the level of the suit sensors on this thing. It says it doesn't have sensors.

**Comment by Bawhoppen** [comment]
Thats because its a turtleneck and not a jumpsuit

**Comment by Dorsisdwarf** [comment]
The tacticool turtleneck is literally a toy sweater produced to poke fun at the syndicate. Why would it have sensors.

**Comment by KorPhaeron** [comment]
It has no sensors because otherwise nuke ops would show up on the monitor.

Not a bug @Dorsisdwarf

**Comment by Firecage** [comment]
....Kor misreads the situation again...

**Comment by Bawhoppen** [comment]
Tacticool is the toy version of the Tactical turtleneck, Neither should have sensors.

**Comment by Dorsisdwarf** [comment]
If nobody puts forwards a good reason why the tacticool turtleneck should have sensors, I'll close this soon (because holy shit we have a flood of actual bugs to handle right now)

**Comment by Jalleo** [comment]
@dorsisdwarf i call it a intedended feature.

**Comment by Dorsisdwarf** [comment]
Closed

**Comment by Zilenan91** [comment]
sorry this is late but examining the tacticool turtleneck says it has its sensors enabled

**Comment by Jalleo** [comment]
Welp ^^^
