### ISSUE TITLE
Minimaps generate for Z8

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12348]
Makes loading away missions take a really long time, and would let you build a CMO computer to map them out/spoil them

**Comment by Miauw62** [comment]
i should put images of all the away missions on the wiki

**Comment by KorPhaeron** [comment]
But why?

**Comment by AlexanderUlanH** [comment]
That's a terrible idea.  Exploring them is most of the fun.
Better to add a framework for uploading away missions to the server so we can have away missions that can't be spoiled by reading the map files from the repo.

**Comment by Miauw62** [comment]
after a week or so some people will have explored it and will begin powergaming the loot.

**Comment by KorPhaeron** [comment]
So let us enjoy a week of them instead of trying to sabotage it or encourage such powergaming

**Comment by Firecage** [comment]
Kor. As long as we are open source, it wouldn't matter whether you put them on the wiki or not. It is freely accessible to anyone. And making only 'certain' things closed source would make maintaining or changing things hell.

**Comment by Shadowlight213** [comment]
@Firecage most players won't delve into the map files to see what the missions look like, they are more likely to look at maps on the wiki.
It's not about completely shutting down knowledge of how away missions work, it's about making that knowledge harder to aquire so the average player can't easily spoil it for themselves.

**Comment by Firecage** [comment]
Shadow, I shall repeat what I said. It does not matter whether we put it on the wiki or not. The entire map is already freely available and accessible for anyone. What you are just saying can be described as laziness. We can just aswell put the maps on the wiki, considering anyone can already access it, it would make no difference.

**Comment by Miauw62** [comment]
yeah and powergamers will spoil it for themselves to get to all the loot before your average player can get to it : v

**Comment by kingofkosmos** [comment]
Keeping some things off the wiki just makes code-literate people have an advantage over code-illiterate ones. If it can affect the game balance, it should be on the wiki for everyone to see for fairness.

**Comment by Shadowlight213** [comment]
Fine I guess. I suppose even pretending to have any sort of exploration is impossible with open source and the playerbase.
