### ISSUE TITLE
Possible to kill a Guardian without killing the user

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12343]
If gib() is called on the guardian (such as running into an emagged gibber), or they get hit by a deathbolt or whatever, it's possible to kill them without damage being passed to the user

**Comment by RemieRichards** [comment]
Have ```guardian/Gib()``` call ```owner.Gib()``` or something.
or check for the ```gibbed``` argument in ```guardian/Death()```
