### ISSUE TITLE
Chemists really should have medical storage access

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12347]
You know, this is the one thing that would make sense and we don't have it somehow

**Comment by Marflowerose** [comment]
Generally speaking it's weird that Medbay doesn't function the same way as Science, if you're scientist, all science rooms are available except genetics and robo.

**Comment by xxalpha** [comment]
Chemists aren't medics, therefore they do not need access to the medical supplies.

Feedback forum, not a bug.

**Comment by Bawhoppen** [comment]
They are the ones who create the medical supplies and pharmaceutical chems, and this is a small enough thing where it doesn't deserve to be on the forum

**Comment by Miauw62** [comment]
that is why we have a "minor feedback" thread.
if its not a bug or code-related, it shouldnt be on the issue tracker.

**Comment by Dorsisdwarf** [comment]
CRUSHED UNDER MY COLLABORATORIAL HOOVES.
