### ISSUE TITLE
Chem implanted people can activate the implant by "deathgasping"

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/-tg-station#12353]
/obj/item/weapon/implant/chem/trigger(emote, mob/source)
	if(emote == "deathgasp")
		activate(reagents.total_volume)

You guys thick or something? I NEED the implant to STAY in their body, so ->I<- can activate it when ->I<- see fit.

When someone can just *deathgasp in order to get rid of my morphine implant, chemical implants are useless. Fix that.

**Comment by Shadowlight213** [comment]
I'm pretty sure that's intended. It's been that way for as long as I can remember. There's an action button to activate chem implants as well I think.

**Comment by AssassinT90** [comment]
Intended? INTENDED? Oh god.

Alright, would you guys mind of telling me what is the point of a chemical implant that can be activated by the implantee? Cause I'm really, really confused as to its use right now that I can't use it to threaten people into staying in line.

**Comment by xxalpha** [comment]
Calm down.

**Comment by Dorsisdwarf** [comment]
There's an action button for this you know.

Chem implants are intended for giving to sec officers full of superstims

**Comment by AssassinT90** [comment]
In that case, I guess the issue can be closed.

**Comment by Miauw62** [comment]
i guess we need a separate implant for prisoners vOv

**Comment by AssassinT90** [comment]
Perhaps "using" (attack self) the implant would swap between "remote activation," "local activation," and/or "remote and local activation" modes.

I dare to dream.

**Comment by Shadowlight213** [comment]
@assassinT90 If you're looking for a foolproof solution, I don't think it's possible. I've seen players go to medbay to get themselves cloned to get rid of lethal chem implants.

**Comment by AssassinT90** [comment]
I don't think foolproof is the key for chemical implants - or for anything SS13-related, for that matter.

But I think that if you want to get rid of my ultra-limited implants that I decided to spend on your ass to keep you in line, you should at least have to work A BIT to get rid of them.

Convinced a doctor (or an assistant) to do surgery on you and remove them? Good for you. KILLED yourself so you'd be cloned into an implantless, reborn assistant? Well, that's kinda suspicious, you better pray I don't notice it, but at least your implants are gone.
Locked yourself into a dorm room, pushed a button in your HUD, and went out for a coffee while your character sleeps my morphine implant off? Well, fuck that.
