### ISSUE TITLE
Holoparasites take explosion damage while INSIDE the host

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/-tg-station#12351]
Happened yesterday: We were just about the end of the radius of damage of a sci bomb, so the damage dealt to us was very little: almost negligible. What wasn't negligible, however, was the red text:

"Blood sprays from [my host] as [I] take damage."

A borg saw it, called security, and that was that.

Evidently, if a holoparasite is inside his host, the holoparasite himself should not be taking damage and displaying "my-host-is-a-traitor" messages around.

**Comment by Incoming5643** [comment]
a side effect of ex_act calling ex_act on things contents in most cases.
