### ISSUE TITLE
some dipshit re-added the .int file to the repo

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#12363]
git.exe pull -v --no-rebase --progress "https://github.com/tgstation/-tg-station.git" master

POST git-upload-pack (945 bytes)
remote: Counting objects: 294, done.
Receiving objects: 100% (294/294), 491.93 KiB | 393.00 KiB/s, done.
Resolving deltas: 100% (225/225), completed with 111 local objects.
remote: Total 294 (delta 210), reused 210 (delta 210), pack-reused 83
From https://github.com/tgstation/-tg-station
* branch            master     -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
**tgstation.int**
Please move or remove them before you can merge.
Aborting

git did not exit cleanly (exit code 128) (7641 ms @ 10/12/2015 4:03:51 PM)

# SOMEONE IS GOING TO DIE

**Comment by bgobandit** [comment]
it's me

:(

**Comment by xxalpha** [comment]
quality pr reviewing

**Comment by Chnkr** [comment]
lrn2git @Iamgoofball

**Comment by Shadowlight213** [comment]
^^^^^
This guy right here goof. He's the dead man.
Also, I'm reverting that pr.

**Comment by Iamgoofball** [comment]
# you better be ready for the hell i'm going to unleash upon you, you piece of shit

**Comment by optimumtact** [comment]
>git.exe
>.exe
>exe

HAHAHAHA YOU IDIOT BAKA DUMB IDIOT BAKA

**Comment by Shadowlight213** [comment]
Fixed by #12366

**Comment by optimumtact** [comment]
you can close this
