### ISSUE TITLE
Swarmers can destroy indestructible walls

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12360]
Only really an issue in away missions as they'll never encounter them otherwise

**Comment by Anonus** [comment]
If they're indestructible, swarmers can't destroy them because they work off of ex_act

**Comment by Shadowlight213** [comment]
@KorPhaeron If its what I think you're thinking of, those were regular cult walls. Some had blockers under them, but not all.

**Comment by KorPhaeron** [comment]
Nevermind I was tricked please close this
