### ISSUE TITLE
reliability and crit_fail in research designs

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/-tg-station#12388]
Are there supposed to be more ways for researched devices to break down?  Right now, I see crit_fail doing more to determine what can and can't be used in the destructive analyzer than anything else, with the very notable exception of power cells.

Could we use more depth in the device-failure area, or would it annoy more than amuse?

**Comment by Dorsisdwarf** [comment]
I don't know what to tag this.

tbh this seems more like something for the forums

**Comment by Miauw62** [comment]
f e e d b a c k f o r u m
