### ISSUE TITLE
Medborg emagged acid spray is useless as it barely does damage and doesn't melt items

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12383]
It barely does any damage, and doesn't melt items. It's completely useless compared to how powerful it was before the acid refactor.

**Comment by Lumipharon** [comment]
Acid got nerfed utterly to shit, which is dumb considering it got blacklisted from sprays, and smoke got utterly nerfed into the ground.

**Comment by Zilenan91** [comment]
I mean, it's not like killing an entire Op team instantly with an instantly activated acid smoke grenade was ridiculous or anything.

**Comment by Lumipharon** [comment]
That was an issue with smoke and they way it can spam touch reactions for certain reagents (like mutagen and acid), not the actual acid reagent itself, which got nerfed as well as smoke.

We went from smoke being OP with certain chemicals that were otherwise fine to:
Smoke being UP regardless of chem, with acid being shit regardless of application method.

**Comment by Iamgoofball** [comment]
i'll buff smoke, remove acid from the spray bottle ban list, and check out a new spray hellmix for traitor medborgs

**Comment by PKPenguin321** [comment]
give it oldacid, the way service borgs get oldchloral

**Comment by SpookyDoc** [comment]
Give Mediborgs oldacid, give Engiborgs stungloves, give Secborgs autorifles, give Miningborgs... mining lamps?

**Comment by Shadowlight213** [comment]
@iamgoofball giving then old acid would be the best. The melting effect made fantastic assassins

**Comment by Zilenan91** [comment]
I don't think putting acid into sprays will ever be a good idea. Everybody and their mother will be walking around and the second you even remotely piss them off suddenly you're undefibbable and all your shit is melted.

**Comment by PKPenguin321** [comment]
only for emagged medborgs, not for anything else you dip

**Comment by Zilenan91** [comment]
goofball said he's remove acid from the spray bottle banlist

**Comment by CPTANT** [comment]
This was another bad case of overnerfing. Acid should eat SOME of your items, not melt away everything or be completely useless like it is now.

**Comment by blobbernaut** [comment]
"I mean, it's not like killing an entire Op team instantly with an instantly activated acid smoke grenade was ridiculous or anything."

boy somebody is mad

**Comment by YakumoChen** [comment]
Why is this still an issue after months and months? Hacked mediborgs still have no spray

**Comment by KorPhaeron** [comment]
@Iamgoofball buff acid

**Comment by Iamgoofball** [comment]
easy fix I'll look into this

**Comment by Zilenan91** [comment]
don't buff acid pls
