### ISSUE TITLE
you can gibb people with cuffs on

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#12384]
not salt or anything
seems inconsitent with its normal operation rejecting anything inorganic.

**Comment by Shapsy** [comment]
Only way to deal with lings without chancing them popping back up for the sixth time and saxxing out of there, I say leave it

**Comment by Steelpoint** [comment]
I would imagine this is intentional. I've had several occurrences in the past of me attempting to gib a ling only for it to run out of the machine due to no cuffs.

The alternative is the crematorium is the only reliable way to kill a ling.

**Comment by CosmicScientist** [comment]
Eh? Can you let it revive and then kill it again? I thought it took a while to come back to life and not as soon as you clicked the button? Surely that's enough time to uncuff and throw them in the gibber if they didn't lesser form or acid spit out of the 'cuffs anyway?

**Comment by Steelpoint** [comment]
Its a annoyance at worst and bloody obnoxious at best.

Worst case scenario the Ling will pop off some stabs, ranging from Cyro to whatever.

Either way, once a ling is in cuffs its all but impossible for it to escape once its in the kitchen back room, if it could become a monkey it would have done so earlier on in a more open area and not in a cramped room.

**Comment by CosmicScientist** [comment]
So you have it in cuffs in the kitchen and it won't escape?
So why not kill it again and then use its lengthy death time to uncuff and gib?

**Comment by Steelpoint** [comment]
I'm not going to argue over this.

Overall I consider it to be a quality of life issue, its annoying otherwise if you have to uncuff a dead ling.

Its a minor issue to be frank so I don't care either way what happens, its not something I want to fight over.

**Comment by PKPenguin321** [comment]
not a bug

**Comment by freerealestate** [comment]
inconsistency

**Comment by PKPenguin321** [comment]
doesn't really matter that much

**Comment by freerealestate** [comment]
it matters to changelings

**Comment by veganzombeh** [comment]
I would argue that it isn't even a consistency issue.

If this is a consistency issue, you could argue that it should reject robotic limbs too.

**Comment by freerealestate** [comment]
well it should

**Comment by Dorsisdwarf** [comment]
crushed under mercurial feet
