### ISSUE TITLE
The wall mounted nanomed has more supplies than a nanomed plus.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#12392]
The wall mounted version has a larger selection of items to choose from compared to the larger vending machine oriented ones. It doesn't make much sense that the larger version would have less in it.

**Comment by WJohn** [comment]
I blame the constant back and forth balancing that happened on the 15 or so PRs introducing goofchem with goof and pudl strangling eachother over it.

**Comment by Supermichael777** [comment]
I suggest swapping their lists first.

**Comment by Shapsy** [comment]
Swapping them wouldn't be a big issue

**Comment by Jalleo** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
we must of forgotten to nerf the wall mount supplies when we nerfed the main vendors supplies after pudl buffed it to hell

**Comment by PKPenguin321** [comment]
we should make wallmeds and the nanomed pluses have the same contents (preferably the current contents of the wallmeds), but have the wallmeds contain less of each item IMO

**Comment by Dorsisdwarf** [comment]
@Iamgoofball
