### ISSUE TITLE
Lizards can shave their head with the electric razor.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12393]
The first time, it acts like there's a hair object there being shaved. The second time is when it says "there's no hair," which should happen ALL the time.

**Comment by CosmicScientist** [comment]
I think, if I remember from a previous bug to do with lizards and hair, if you set one of your character slots as human and make them bald and then swap their race to a lizard, you might find they then have no hair to shave.

So if that's true it'd be something to fix inside character creation.

**Comment by WJohn** [comment]
Yeah lizards technically do have hair, it's just hidden when their race is swapped to lizard. Frankly, you shouldn't be able to interact with it either through razors or through radiation.

**Comment by Incoming5643** [comment]
there's already a flag to say that a race doesn't have any hair, the checks just need to be added.

**Comment by duncathan** [comment]
More accurately there's a flag to say that a race does have hair
