### ISSUE TITLE
You can walk on the full glass windows on the derelict.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#12391]
The old single tile windows were replaced with full tile ones but you can walk into them, Mostly noticeable on the bridge between the courtroom and science.

**Comment by WJohn** [comment]
Probably some poorly handled mass replacement.

**Comment by Jalleo** [comment]
It was basically all the tiled windows there are bugged it should be reverted partially.

**Comment by Shadowlight213** [comment]
I recall pointing that out and a maintainer telling me that the derelict being unmaintained like that was intended. Honk.
