### ISSUE TITLE
Machines that are overidden by a malf AI will attack the AI.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12397]
Let's just get it out of the way first: I DED, PLS FIX, ETC.

That said: I was malf AI. I bought a bunch of uses of override machine and used them on the machines in my core because the engiborg got blown before it could finish reinforcing it. After the humans broke in and exposed my core to the general public, my screen was a lot of this:

The AI Chamber Air Alarm attacks C.L.O.W.N.!
The light fixture attacks C.L.O.W.N.!

Why this is bad: If the AI overrides a machine that machine shouldn't turn around and kill the AI, wtf

**Comment by Miauw62** [comment]
just needs some changes to faction vars
