### ISSUE TITLE
Why can I not emag the Robotics Consoles

### ISSUE THREAD

**Issue by Aredal** [tgstation/-tg-station#12414]
Yes I'm salty beucase my master plan failed beucase you can't emag this id lock needed console while you can a communcation bridge console which is id locked too.

**Comment by Dorsisdwarf** [comment]
I ded plz feedback forum

**Comment by duncathan** [comment]
The communication console isn't capable of killing players instantly

**Comment by Aredal** [comment]
Also my intention was to explode a dead cyborg hacked by me so it would not sell me out. And just like the id locked communication console can send messages without an id with acces but to Syndicate, the robotics console when emmaged could be able to explode hacked borgs by an id without the acces needed? Also the thing against it that people could use it to metacheck borgs for being hacked is bassicly near to changing nothing since people can easly check if borgs are hacked via asking them to just state laws, or just cheking their interface. Should I move it to a forum feature request page somewhere and just close this?

**Comment by Dorsisdwarf** [comment]
Yes.
