### ISSUE TITLE
Teleport list has random characters in it, and they change each time you try to teleport.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12433]
![](http://i.imgur.com/nM0sY9i.png)
![](http://i.imgur.com/8Q1KSFi.png)

The random string of characters changes place and hits different area names seemingly at complete random.

**Comment by GunHog** [comment]
What maps?

**Comment by WJohn** [comment]
Also, furthermore, some areas just suddenly appear/vanish out of the list.

**Comment by phil235** [comment]
Couldn't reproduce on a local test server with Boxstation.

**Comment by WJohn** [comment]
Strange, lots of other people are experiencing this. Maybe it's a byond issue?

**Comment by MrStonedOne** [comment]
byond issue blame mso etc etc

basically the newest version of byond broke if (list("blah") & list("blah"))

**Comment by phil235** [comment]
I think it also broke SortList( list1 | list2) (See #12444 and https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/modules/reagents/Chemistry-Machinery.dm#L218)

**Comment by octareenroon91** [comment]
I blame ```\improper``` .  Try removing every instance from the file

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=1969148

**Comment by MrStonedOne** [comment]
ok, its still an issue, but less so now....

wtf.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=1960893#comment17156032 the fix never got checked out into 509.1307

**Comment by phil235** [comment]
still an issue apparently

**Comment by MrStonedOne** [comment]
This was fixed 1310
