### ISSUE TITLE
Camera networks are completely broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12435]
All they return in the prompt is "cancel", you can't view any of the cameras.

**Comment by Bawhoppen** [comment]
Sometimes they work, but I've had this glitch before

**Comment by feemjmeem** [comment]
Noticed this on the PA cameras today on box.

**Comment by CPTANT** [comment]
Every single round I played today had all the camera networks I checked broken. This should get some priority in fixing.

**Comment by francinum** [comment]
High Priority.

**Comment by phil235** [comment]
Most likely same cause as #12433

**Comment by WJohn** [comment]
This is all working now.
