### ISSUE TITLE
Deconstructing chairs gives 2 metal sheets instead of 1.

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#12437]
Server: Sybil

Revision: 2015-10-16
cb58e8dca360b16f6fb362b29ab3e2d367f5db86 

Problem Description: When you build and deconstruct a chair you double the metal used to make the chair. Untested with any chair except the standard one.

What did you expect to happen: To deconstruct a chair and get 1 metal back.

What happened instead: I got 2 back

Why is this bad/What are the consequences: Infinite free metal from 1 sheet.

Steps to reproduce the problem: Build chair, wrench chair.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Pretty ordinary round up until that point.

**Comment by phil235** [comment]
woops
