### ISSUE TITLE
Some items randomy have their hitbox over the entire tile

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#12430]
This makes it nearly impossible to interact with other items on the tile without an alt+click. 
Doesn't happen consistently and with no real theme to which kind of items are affected. When it happens the effect seems permanent. 

Baffling.

**Comment by Dorsisdwarf** [comment]
dupe, lemme look

**Comment by Incoming5643** [comment]
nevermind then, I just assumed something this annoying would have gotten fixed already had it been reported.
