### ISSUE TITLE
Button to make changelog stop auto-appearing is MIA

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#12449]
In the past, there was a buton in the OOC tab, or maybe the Preferences tab that made the changelog stop popping up every time you reconnected/a new round started/the changelog was updated.

This button is now gone.

It is very annoying having to close it constantly.

EXTREMELY HIGH PRIORITY

P A N I C

**Comment by Iamgoofball** [comment]
it only shows up if you have a new thing in the changelog

read the changelog

**Comment by Niknakflak** [comment]
You can't force us to be educated!!

**Comment by Supermichael777** [comment]
Actually it seems we can. Weird how that works.

**Comment by Iamgoofball** [comment]
No one in their right mind is going to add this button.
