### ISSUE TITLE
Botany winter coat hood is also a bucket

### ISSUE THREAD

**Issue by SpookyDoc** [tgstation/-tg-station#12448]
When you put up the botany jacket's hood, this happens 
http://puu.sh/kMNa5/26a8bc207b.png

**Comment by bgobandit** [comment]
feature

**Comment by Niknakflak** [comment]
That's fucking hilarious

**Comment by SpookyDoc** [comment]
Shit, name changes are recorded, I had forgotten.
I had capitalized incorrectly and it was bothering me.

**Comment by Boredone** [comment]
On a related note, I think I've been seeing this happen with cargo and chappy jackets too.

**Comment by Chocobro** [comment]
![ok](https://cloud.githubusercontent.com/assets/5677255/10558001/713a69a4-74b8-11e5-8918-973e757fe331.PNG)

**Comment by phil235** [comment]
That's because whoever added bucket helmet gave its sprite no name. And currently winter coat hood use a trick, the hood sprite is actually on the suit sprite and the hoodie item itself has a blank sprite.. with a blank name, thus the bucket appearing.

**Comment by Supermichael777** [comment]
two peaces of code that are absolutely terrible due to all the issues.
like hair teleporting through coat hoods
