### ISSUE TITLE
Instant death as ghosts become shades

### ISSUE THREAD

**Issue by DocProfSmith** [tgstation/-tg-station#12445]
Basically Laz0r died instantly upon becoming a shade for no discernible reason

**Comment by francinum** [comment]
Any additional information? Time? Server? Were they the original inhibitor of the body or were they brought in as a ghost? This is all very important information.

**Comment by DocProfSmith** [comment]
Ahh sorry, this is the first time I've done one of these. The server was sybil and they were brought in as a ghost. I unfortunately can't say much more about the time other than it happened not long before I filed this report.

**Comment by Dorsisdwarf** [comment]
Dupe of #12320
