### ISSUE TITLE
Ghost teleport verb isn't alphabetical anymore

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12440]
![oh god why](http://puu.sh/kMrK0/e4fe43e06b.png)

**Comment by Shapsy** [comment]
also why does it say booyea

**Comment by WJohn** [comment]
Basically a dupe/continuation of #12433. Teleport list is super mega bugged.

**Comment by Anonus** [comment]
This is similar but it's not the same issue, it's been happening before that issue.
