### ISSUE TITLE
HoS office bugged

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#12450]
This effects a couple of things in the HoS office - namely the light and the red alert swipe thingo, not sure if any thing else is effected, but I suspect it's just anything along that wall.

Basically, since the pr got merged that added hardsuits to the head offices (hos/rd/cmo), the redalert swipe and light in the hos office aren't conected to the hos room apc anymore, so start the round depowered.

The RD and CMO offices may have the same issue, but I haven't checked.

edit: Box station.

**Comment by bgobandit** [comment]
which map

**Comment by WJohn** [comment]
Looks like someone forgot to fix the areas. It's a pretty common oversight to make.
