### ISSUE TITLE
Dreamstation: All camera consoles list zero cameras.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12467]
![](http://puu.sh/kO2ef/cbc73b8b06.png)

**Comment by Shapsy** [comment]
All maps do this, sorta critical

**Comment by Xhuis** [comment]
\>this managed to happen

sign me the FUCK up good shit go౦ԁ sHit thats ✔ some goodshit rightth ere right✔there ✔✔if i do ƽaү so my selｆ :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: Н

**Comment by Jordie0608** [comment]
Dupe of #12435
