### ISSUE TITLE
Constructs take fire damage and are 'on fire' without having a proper sprite

### ISSUE THREAD

**Issue by kpeculier** [tgstation/-tg-station#12463]
Cult/wizard constructs taking damage from fire and are set on fire despite having no sprite for it.

**Comment by Zilenan91** [comment]
Is it a bug that they can be on fire at all? They can't ever put it out on their own.

**Comment by WJohn** [comment]
How... are they getting put on fire? Aren't they simple animals? That shouldn't even be possible.

**Comment by KorPhaeron** [comment]
This is a bug with all simple animals
