### ISSUE TITLE
blue cherry ISN'T blue

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12473]
you're a lemming if you think this:
![ss 2015-10-18 at 12 21 12](https://cloud.githubusercontent.com/assets/6510293/10562687/3b1fd23e-752e-11e5-8eff-91a3537e6fad.png)

is blue

its maybe CYAN at best

**Comment by optimumtact** [comment]
the lighting is making it look green, it really is blue honest

**Comment by Firecage** [comment]
Looks blue to me.

**Comment by Bawhoppen** [comment]
it definitely isn't blue, it has a shade of blue

**Comment by xxalpha** [comment]
Those are the reddest blue cherries I've ever seen.

**Comment by WJohn** [comment]
Can we not clog up the issue tracker with complete non-issues?

**Comment by Bawhoppen** [comment]
bullshit, this is a legitimate sprite error

**Comment by Nienhaus** [comment]
![2015-10-18_09-22-02](https://cloud.githubusercontent.com/assets/285438/10564433/ec5981a8-7579-11e5-8b03-548e9c369505.png)
This is the color of cyan I got from Google.
![2015-10-18_09-22-14](https://cloud.githubusercontent.com/assets/285438/10564438/0553d73a-757a-11e5-989e-4f1bbadbf349.png)
This is for the middle of the sprite in the OP, it's a dark cyan.

**Comment by Bawhoppen** [comment]
i fucked told you so

**Comment by WJohn** [comment]
Still a non-issue. Plenty blue enough.

**Comment by Firecage** [comment]
It is blue still.

**Comment by Bawhoppen** [comment]
there may be blue in it, BUT theres not enough to call it JUST blue

**Comment by Dorsisdwarf** [comment]
Yes there is you mongoloid not everything is a sliding scale of 'maroon-fuschia blend with hints of taupe'

sometimes its fine to just call them fucking blue

**Comment by xxalpha** [comment]
Harsh, but true, no need to call it something fancier than blue unless someone adds cherries that are blue.

**Comment by Bawhoppen** [comment]
@xxalpha I looked at your comment for awhile and I cannot figure out what you intended to say, can you elaborate?

**Comment by xxalpha** [comment]
Until someone adds cherries that are actually blue, you don't need to call these cyan berries "dark cyan beans", blue pomes is fine.

**Comment by Bawhoppen** [comment]
![ss 2015-10-18 at 12 35 18](https://github-cloud.s3.amazonaws.com/assets/6510293/10565391/ca029480-7594-11e5-9f18-5e86349488ac.png)

![ss 2015-10-18 at 12 35 47](https://github-cloud.s3.amazonaws.com/assets/6510293/10565393/cedc7a0c-7594-11e5-9858-71ed8bbad305.png)

**Comment by Bawhoppen** [comment]
(was that a joke im so confused)

**Comment by xxalpha** [comment]
I am trying to tell you that it's alright.

**Comment by Bawhoppen** [comment]
THEY'RE NOT DISTINCTLY BLUE ENOUGH TO BE CALLED JUST BLUE OK

**Comment by Cheridan** [comment]
CYAN IS A TYPE OF BLUE

**Comment by Iamgoofball** [comment]
UGH YOU UNCULTURED FUCKS, STOP TRIGGERING ME WITH YOUR MICROAGRESSIONS AGAINST COLORLESSKIN

NOT EVERYTHING HAS TO HAVE A COLOR!!!

#notallcolors

**Comment by Bawhoppen** [comment]
@Cheridan thats like saying hinduism is an abrahamic religion
