### ISSUE TITLE
Simple Animals: Fireloss = Bruteloss?

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#12491]
Just an oddity I noticed:

https://github.com/tgstation/-tg-station/blob/61d23d8c1112fdc45bce2e8422122ca136aa248b/code/modules/mob/living/simple_animal/simple_animal.dm#L277

Apparently Fireloss is actually bruteloss?

**Comment by Incoming5643** [comment]
simple animals process all damage as brute. They only have the one total

**Comment by Anonus** [comment]
This means you can't make a simple animal take only damage that isn't bruteloss(so you'd have to laser it or shoot toxins at it or whathaveyou), though.
I've been meaning to report that for a while but I keep forgetting.

**Comment by Fox-McCloud** [comment]
Gotcha, thanks.

**Comment by phil235** [comment]
Simple animals used to only use brute damage no matter what damage type hit them (thus the fire damage = brute damage). Apparently this was changed, simple animal can get all sorts of damage types, but someone forgot to remove that damage type switch during the change.

**Comment by Cheridan** [comment]
#14372

You can fix this, but it's more trouble than its worth and will make more bugs than something that works perfectly fine as-is

**Comment by Changelingrain** [comment]
DISRESPECT NOISE #14388
