### ISSUE TITLE
Centcom ferry base turf broken sprite

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12490]
![baseturf](http://puu.sh/kP3Bw/b5a508d2b1.png)

**Comment by Jordie0608** [comment]
Which map?

**Comment by Shadowlight213** [comment]
@Jordie0608 screenshot is from box centcom, but as far as I know, the problem is on ALL of the centcom maps.

**Comment by Bawhoppen** [comment]
wait people still hadn't reported this? the only reason I didn't sooner was because I thought there was already an issue open for it

**Comment by Dorsisdwarf** [comment]
Always report new bugs. If it's a dupe, I'll close it. if its not, its more likely to get fixed
