### ISSUE TITLE
Alternative hydroponics tray changes sprite

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12502]
This alternative tray
![ss 2015-10-19 at 11 22 57](https://cloud.githubusercontent.com/assets/6510293/10583687/029086b2-7654-11e5-888c-d2f6cb03a8bd.png)
Changes sprite to the normal botany tray when something grows in it or has the little indicator that is supposed to appear if theres a lack of nutrients.

These things actually do appear in artifact rooms on mining.

**Comment by WJohn** [comment]
Then they probably shouldn't be appearing in the artifact rooms at all.

**Comment by Bawhoppen** [comment]
:(  that shouldn't be what the problem

**Comment by phil235** [comment]
Related to #4305

**Comment by freerealestate** [comment]
how are these still in the code?
