### ISSUE TITLE
Genetics is apparently broken

### ISSUE THREAD

**Issue by DocProfSmith** [tgstation/-tg-station#12514]
This is an issue raised by the geneticists on sybil just now:

"Reply PM from-Jeerman/(Rubeye Mobile): There was an update where SE were changed, some blocks removed. We saw that there were less blocks, and when we radiated them (the first time was successful) they disappeared completely. Only the denominator for Block 1 remains, nothing else. Also if we save the information of in the DNA Scanner, the target creature, it gives SE: No data. So SE's borked, Geneticists dismayed.  "

**Comment by PKPenguin321** [comment]
@phil235

**Comment by phil235** [comment]
Caused by https://github.com/tgstation/-tg-station/pull/6324/files#diff-f834fc6a0031f9dc384990a7457b14d9R9
