### ISSUE TITLE
Chaplain Hoodie is a bucket.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12519]
![](http://puu.sh/kQv8v/759c9dbfc1.png)

**Comment by Incoming5643** [comment]
a lot of hoodies are now buckets, including hilariously enough, shadowling armor

**Comment by bgobandit** [comment]
@Xhuis

**Comment by Xhuis** [comment]
##### how
#### the
### fuck

**Comment by Shadowlight213** [comment]
feature

**Comment by Chronitonity** [comment]
You left the bucket hat's name blank in the dmi, thats how this happened.

**Comment by Xhuis** [comment]
Just checked, that isn't the case.

**Comment by MrStonedOne** [comment]
Can somebody confirm that this happens locally?

**Comment by Jordie0608** [comment]
Not happening locally.

**Comment by WJohn** [comment]
Apparently all hoodies are just buckets now??

**Comment by Zilenan91** [comment]
The regular winter coat isn't

**Comment by phil235** [comment]
Relevant PR #12459

**Comment by phil235** [comment]
Fixed on sybil, the server was most likely not updated yet when the issue was created.
