### ISSUE TITLE
Ore redemption machine processes ore and has an on-looking sprite with no power.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12525]
What happened: Station lost power due to powersink. Nothing powered, cargo included. Here's what happened with the ore machine

DID happen:
- It accepted and processed ores until none were left on the square
- Sprite had the forge and animation

DID NOT happen:
- Machine was not interactable, the message said "The ore redemption machine seems unpowered."

Why this is bad: Inconsistent.

**Comment by Zilenan91** [comment]
It also accepts your ID when there's no power

**Comment by newfren** [comment]
You can abuse this to smelt ore if you have a crowbar and a screwdriver - have it accept and process the ores, then deconstruct the machine, which will spit out all the (fully processed) ores.

**Comment by Zilenan91** [comment]
No points though
