### ISSUE TITLE
Drone hats broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12526]
The hats that drones wear are invisible and don't appear on the sprite.

**Comment by Niknakflak** [comment]
Priority crtical

**Comment by phil235** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
Only hats?

**Comment by RemieRichards** [comment]
Ok I know what it is, it's rendering the drone as the hat, so you're wearing yourself.
