### ISSUE TITLE
Pin removal tablecrafting can remove the plasma cutter's pin

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12528]
also the process might not need wirecutters either

**Comment by Bawhoppen** [comment]
also the process might not need wirecutters either

**Comment by phil235** [comment]
Pin removal does require wirecutters, maybe you had wirecutters in pockets.

What happens is the plasma cutter is needed as a tool but is a gun, so the tablecrafting code also sees it as the required component if it is on the table and not on you.

There's two easy way to fix it: change the recipe to use something other than a plasma cutter, or require tablecrafting tools to be on the mob and not on the table (but it could lead to player being confused as to why their crafting doesn't work)

The hard way to fix it is to change tablecrafting code to make sure the selected tools can't be used as parts or components.

**Comment by Bawhoppen** [comment]
the reason I said it might not need wirecutters, is because ingame I'm pretty sure it says you need them

**Comment by Bawhoppen** [comment]
also, personally I would go with the first option as the fix, make it use just a welding tool

**Comment by Lumipharon** [comment]
It was made a plasma cutter to avoid any random from being able to depin guns with common tools, just keep in mind.

**Comment by Bawhoppen** [comment]
I think it shouldn't be too hard to remove a pin, just take awhile

**Comment by Zilenan91** [comment]
How about make it require upgraded welding tools from hacked youtools? Only 4 on the map at round start, two publically available in prime tool storage.
