### ISSUE TITLE
Wooden barricades have no hit delay

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12537]
Can hit/destroy them extremely quickly

**Comment by Bawhoppen** [comment]
They do with certain items I believe. Crowbar in specific.

Also while we're at it, pretty sure wooden barricades are bullshit, I used to remember juggernauts couldn't destroy them, making them OP in cult rounds.

**Comment by Zilenan91** [comment]
Spears too. Can we not fix this because fuck wooden barricades in maint

**Comment by freerealestate** [comment]
These had excessive health last I tried breaking one (earlier this year)

**Comment by RemieRichards** [comment]
Apparently they're hardcoded to only have 75% of the incoming brute damage, but 100% of the burn (because it's a wooden barricade I guess)
