### ISSUE TITLE
Bolting as AI/cyborgs

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#12550]
You can no longer give a bolt command while the door is opening and closing as a cyborg and (possibly) the AI.
The door must be fully open or closed.

Note: Any other command works as normal.

**Comment by xxalpha** [comment]
Not a bug, intended.

**Comment by Shad0vvs** [comment]
I don't understand, if you wanted to make the AI more of an annoyance to play you could just go back to the old 2012 camera system instead of coding in new things.
This doesn't add anything or change anything, it just makes you have to spam the door.

**Comment by Shad0vvs** [comment]
Someone fixed this issue at some point please close @Dorsisdwarf .

**Comment by xxalpha** [comment]
Yeah I fixed this. I couldn't find this issue to reference at the time.
