### ISSUE TITLE
Heat exchange pipes runtime at roundstart 

### ISSUE THREAD

**Issue by duncathan** [tgstation/-tg-station#12551]
@duncathan
This has been an issue for a while but I keep forgetting about it so I'm making a report so that I remember
I know exactly what the problem is: process() calls return_air() before atmosinit() is called and so the pipes don't yet have a parent and runtime when trying to return parent.air
Solution: make h/e pipes not dumb and ensure that anything exclusive to atmos machinery (pipenets and their gas mixtures; nodes) is contained within process_atmos() instead of process() because that's the WHOLE POINT OF THE FORMER

**Comment by Jordie0608** [comment]
I noticed this happening mostly when the pipes are on airless turfs like space, not sure if it's exclusive to that however.

**Comment by duncathan** [comment]
dupe of #11118
