### ISSUE TITLE
Discstation: Morgue door blocked.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12568]
![](http://puu.sh/kSMPH/1411d8a1b0.png)

**Comment by Dorsisdwarf** [comment]
@Strathcona

**Comment by Strathcona** [comment]
This will be fixed in #12600

**Comment by JJRcop** [comment]
This issue can be closed because #12600 was merged

**Comment by Strathcona** [comment]
Yes it can be.

**Comment by francinum** [comment]
And this is why you use the auto-closing system...
