### ISSUE TITLE
Discstation terrible design. 

### ISSUE THREAD

**Issue by tarktheshark** [tgstation/-tg-station#12563]
The mining loading dock is inaccessible to miners. They can get from the actual loading dock into cargo general, but not from their to the rest of the station. This means that they have to either talk to the AI or cargo techs if they want to go from the mining to work or back. Also security is a byzantine maze and their aren't any shotguns in the armory. 

I do like the extra wide hallways though.

**Comment by Anonus** [comment]
Security doesn't have cell timers either.

**Comment by Jordie0608** [comment]
Post this stuff on the forum thread for the map; it probably won't get read by the map maker here.
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3871
