### ISSUE TITLE
Emagging an air alarm will show the attack animation with the emag visible above the air alarm.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12565]
Pretty sure emagging something shouldn't show it being attacked by the emag.

**Comment by francinum** [comment]
Vending machines as well.

**Comment by Shadowlight213** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
I stand by this being intentional.
You shouldn't be emagging with people around.

**Comment by Shadowlight213** [comment]
It's a consistency issue since it is the ONLY machine that shows the visual.
