### ISSUE TITLE
Traitors spawning without items vital to their objectives

### ISSUE THREAD

**Issue by DocProfSmith** [tgstation/-tg-station#12571]
Seems to be an issue I only see once in a blue moon but basically the run down is as such:

Not long before I made this post TheWulfe spawned as a traitor on sibyl with the objective to steal the nuke core. They spawned without the equipment they need to do so, such as the instructions or the container. Fair enough if I'm wrong and they're not supposed to spawn with these things but I'm pretty sure they are, so hoping this can get fixed.

**Comment by Bawhoppen** [comment]
They're supposed to spawn with the equipment to extract the core.


Also
>sibyl

You mean SYBIL?

**Comment by PKPenguin321** [comment]
could be fixed by adding these items to the uplink as free, single purchase items but making them only purchasable to people with the objecitves

**Comment by Marflowerose** [comment]
@PKPenguin321 That would help with consistency and stealth. A big red syndiebox in the inventory is kinda easy to notice when searched.

**Comment by xxalpha** [comment]
I don't know if this occasional bug happened before the Outfit datum, but my guess is something is preventing the gamemode code from giving the traitors the boxes.

Changing it to uplink would be fine.
