### ISSUE TITLE
Blob health/power display is really blurry

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#12579]
I dunno why it's probably a byond thing but ISSUES
![fuck](http://puu.sh/kPkO8/75816f86cf.png)

**Comment by xxalpha** [comment]
Looks like it was stretched. Stretched icons look blurry.

**Comment by Dorsisdwarf** [comment]
A lot of the old text and stuff is actually slightly blurry in the sprites. It's like someone tried to do antialias but failed
