### ISSUE TITLE
unwrenching a high presure air pipe sends you flying at absouloutly rediculos speeds

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#12575]
from the doors to the central hall loop on box to the arrivals vending row instantaneously.

**Comment by WJohn** [comment]
That... doesn't seem right. There should probably be a range limit to this thing, at the very least.

**Comment by PKPenguin321** [comment]
no wait don't patch this i use this for instantaneous space travel

**Comment by Marflowerose** [comment]
There should be instead a chance to have the pipe fly through the head of wrencher, otherwise it's too easy to sabotage pipes.

**Comment by Dorsisdwarf** [comment]
WHOOSH

**Comment by phil235** [comment]
The formula used is `user.throw_at(general_direction,pressures/10,pressures/50)` , where the second argument is the range and the third is the speed (number of tiles moved per 0.1 second). 
This means a pipe at 300kPa will throw you 30 tiles in half a second. And at 4500kPa it's 450 tiles in half a second.

**Comment by xxalpha** [comment]
That is definitely excessive, should be /10.

**Comment by joonoro** [comment]
If someone's gonna make changes to unwrenching pressurized pipes, I'd also like to mention that if you unwrench a pipe that is directly beneath you it sends you flying in no direction at all (you spin in place and don't take damage).

**Comment by Bawhoppen** [comment]
@joonoro you would hit the ceiling

**Comment by Jalleo** [comment]
@remierichards since you added this what do you think the upper limits should be

**Comment by Miauw62** [comment]
air pressure violates locality confirmed

**Comment by Dorsisdwarf** [comment]
@RemieRichards 

This really needs to be /200 for distance at the least, so 300kpa throws you 1 tile, but 4500 sends you like 15
