### ISSUE TITLE
Sawn-off improvised shotgun lacks a sprite

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#12576]
The on character sprite is also the full length version too.

EDIT: WAIT NO ITS NOT

EDIT 2: FUCK

EDIT 3: GOING FOR THE EDIT RECORD. MAIN ISSUE IS STILL TRUE.

**Comment by Lumipharon** [comment]
It had a sprite at some point, for certain.

**Comment by bgobandit** [comment]
yo, was it a shotgun sling

because that's the only way I can think of for this not to work

**Comment by Bawhoppen** [comment]
I believe it is fixed now

**Comment by Bawhoppen** [comment]
ah ye it is the sling one
