### ISSUE TITLE
Phil your change to reagent dispensing from beakers missed glasses and shakers and thus bartender is near impossible to play.

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#12587]
Server: Sybil

Revision: 2015-10-22
e59d4fe17245a493176a913b6bb3023233c15c49 

Problem Description: Can't change the amount dispensed from glasses and the shaker using either the old method (right click) or the new (use in hand).

What did you expect to happen: I expected the new method of clicking the glass/shaker in hand to work to change reagent dispensing. It functioned correctly for the large and small beakers I tried it with.

What happened instead: Jack shit when I tried either new or the old method.

Why is this bad/What are the consequences: Some people actually make drinks as a bartender and now it's a little bit harder to make everything. Also drone bartender is hard as balls.

Steps to reproduce the problem: Take glass in hand. Attempt to use in hand. Weep.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I was a drone but K Peculiar told me he tried it as a human and it still did not work.

Why does everyone forget about the bar container updates break it every time they're merged.

**Comment by WJohn** [comment]
I wish we had an oversight tag.

**Comment by phil235** [comment]
@newfren, you can add @phil235 in your message instead of putting my name in the title, it will notify me.

**Comment by newfren** [comment]
Thanks @phil235, I really have no idea how most of github works.
