### ISSUE TITLE
Syndicate simple animal blocking is unbalanced

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12607]
No click delay when attacking them, snowflakey, seemingly blocking all damage from eswords. Reminder to myself to rewrite the whole thing.

**Comment by KorPhaeron** [comment]
Hitting a mob without click delay while doing zero damage is so a bug

**Comment by Zilenan91** [comment]
They also don't take bullet damage as far as I know. Either that or they have a ridiculous amount of health because I've emptied C-20Rs them into them and they gave no shits.

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

Shadowlight fixed this, please close it
