### ISSUE TITLE
windows blew up with a bomb, I got a "1" on my chat screen

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#1260]
What happened: I was in the shuttle, round end, a bomb blew up and took a lot of windows and grilles with it. I got a "1" in the chat.

I believe it's related to windows because not too long ago someone reported the same issue and I believe it was fixed.

some user << "1" is around there pls remove

**Comment by phil235** [comment]
I'm closing this, it's been a year and a half and noone seemed to have complained about this since then.

**Comment by Miauw62** [comment]
it is a mystery.

**Comment by RemieRichards** [comment]
the greatest mystery, forever unsolved.
