### ISSUE TITLE
Spider mobs inject poison through hardsuits.

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/-tg-station#12616]
Needless to say this is really stupid.

**Comment by WJohn** [comment]
Should probably check for thick materials, in the same way you can't inject through certain suits with a syringe.

**Comment by KorPhaeron** [comment]
They're giant spiders. They do damage when attacking your hardsuit so its not a stretch that its being pierced

**Comment by Cheridan** [comment]
agree with kor
