### ISSUE TITLE
Grabbing someone and washing them in the sink will wash the grab.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12611]
![](http://i.imgur.com/a3F7f4I.png)

What it says on the tin.

**Comment by Aloraydrel** [comment]
Deepest lore

**Comment by TrustyGun** [comment]
can this be done for armblades as well?

**Comment by RemieRichards** [comment]
Just have sinks check for ABSTRACT or NODROP.
also it makes sense for armblades because it's basically your arm.
