### ISSUE TITLE
You can become a different sentient monster, while already being one

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#12648]
- Be lucky and a ghost
- Have xenobio make multiple mobs and make those mobs docile
- Say "yes" to all prompts
- Become a player controlled mob
- Suddenly become a different mob, because RNGsus was smiling that day
- Old mob turns into an NPC again(?)

**Comment by KorPhaeron** [comment]
This is easily fixable by replacing the sentience code with PollCandidates() which it should be using anyway

**Comment by Incoming5643** [comment]
Pollcandidates was partially based off sentience code anyways, so why this isn't apparently the case is really baffling.
