### ISSUE TITLE
NPC mobs are cluttering up the ghost follow list

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12650]
Bunch of mining creatures, dead xenobio monkeys, slimes, etc. Makes it a pain to find things sometimes.

Is there any reason ghosts need mobs that aren't players to be listed?

**Comment by Incoming5643** [comment]
I always use the wizard's experiment to quickly jump to the den at roundstart.

Dead simple animals with no attached player can probably be culled from the list though.

(Don't ask me why the wizards pet is suffocating again, someone fucked up the atmos or something)
