### ISSUE TITLE
Security barriers don't have a click cooldown

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12656]
Are we enjoying this? Are these barriers really solid?

**Comment by optimumtact** [comment]
I'm enjoying it personally

**Comment by xxalpha** [comment]
I enjoy breaking through them easily.

**Comment by bgobandit** [comment]
I can't reproduce this.

**Comment by Anonus** [comment]
Steps to reproduce: hit barrier with item five times in a second.

**Comment by phil235** [comment]
Are you talking about the wooden barricade? Because I can't reproduce with the security deployable barrier.

**Comment by xxalpha** [comment]
It was probably fixed, just look at the code. Security barriers have been forever without a click cooldown and you could destroy them with an extinguisher in like two seconds tops.
