### ISSUE TITLE
Ignore doesn't actually ignore

### ISSUE THREAD

**Issue by Ricotez** [tgstation/-tg-station#12652]
I tried to ignore someone, but their messages still showed up in OOC. This happened just now, on the build currently running on the servers.

I typed in the Ignore command, and selected a certain name in the list. Then I pressed enter. I got the pop-up message that I was ignoring them, but their messages still showed up. I even tried to restart the client, but their messages were still showing up.

The strange part is that if I chose their name again it said that I was no longer ignoring them. So the game DID register my ignore request, but didn't actually ignore them.

**Comment by freerealestate** [comment]
@Jordie0608 
also let us ignore admins
