### ISSUE TITLE
TK throwing doesn't respect any sort of click cooldown

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12655]
You can instakill people using a chainsaw and TK(or a spear and TK or honestly anything and TK) by just spamclicking next to them or in front of them, because the TK throwing doesn't respect the click cooldown, doesn't put the item on the tile of the hit person, and the throwforce of most items is higher than their force by a noticeable amount.

**Comment by Supermichael777** [comment]
absolutely terrible. and they said the darklord box was useless.

**Comment by Jalleo** [comment]
@Aranclanos , @phil235 , @duncathan 2 monthly reminder of how OP this can be with spears.

**Comment by optimumtact** [comment]
@duncathan @Cheridan @Aranclanos @WJohn @phil235 @RemieRichards @Razharas
