### ISSUE TITLE
SIngularity can pull shuttle docking points.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12677]
@phil235 Your pr allowing the sing to pull anchored objects had an unintended side effect.

So yeah, shuttle ports are indestructible meaning that they just fly around inside the sing until the shuttle arrives.

**Comment by duncathan** [comment]
:+1:

**Comment by Aloraydrel** [comment]
Tactical shuttle drops

**Comment by Bawhoppen** [comment]
not a bug :(

**Comment by phil235** [comment]
I didn't do that PR, it was hornygranny afaik.

This is simple to fix, just add a 

```
obj/docking_port/singularity_pull(S, current_size)
	return
```

**Comment by Metacide** [comment]
Ho ho, just saw this. Lots of confused people who just about survived to where the shuttle should be, but not for much longer after they realised it wasn't there.

**Comment by Anonus** [comment]
WHERE'D THE SHUTTLE GO
THE SHUTTLE IS ON MINING NOW

**Comment by KorPhaeron** [comment]
Feature

**Comment by MrStonedOne** [comment]
@phil235 Please don't assign yourself to issues you don't plan to fix.

I delayed making a pr for this because I thought you had planed to bundle it one of your fix prs

**Comment by phil235** [comment]
Sorry about that, I forgot to remove my assignment after adding the Easy Fix label.
