### ISSUE TITLE
Hivelord core organ runtime

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12681]
@Core0verload 
runtime error: Cannot execute null.adjustBruteLoss().
proc name: on life (/obj/item/organ/internal/hivelord_core/on_life)
  source file: mining_mobs.dm,278
  usr: null
  src: the hivelord remains (/obj/item/organ/internal/hivelord_core)
  src.loc: Allen Guess (/mob/living/carbon/human)
  call stack:
the hivelord remains (/obj/item/organ/internal/hivelord_core): on life()
Allen Guess (/mob/living/carbon/human): Life(2)
Allen Guess (/mob/living/carbon/human): Life(2)
Mobs (/datum/subsystem/mobs): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()

**Comment by GunHog** [comment]
And now we know why it was not working!
