### ISSUE TITLE
Dropping a chainsaw removes hitsound and damage

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#12683]
How to reproduce:
1. Pick up a chainsaw and turn it on.
2. Drop it.
3. Notice that the sprite still suggests that it's on.
4. Pick it back up and try to hit anything with it.
5. Notice that it no longer does any damage and the hitsound is the generic one.

This can get quite confusing when you are in combat and get disarmed. Switching modes fixes this.

**Comment by tkdrg** [comment]
Yeah thanks for the report I see what's going on here. I'll fix it in a sec.
