### ISSUE TITLE
Jump to area verb is missing areas

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#12684]
e.g. Cargo Bay, Cargo Office, Prison Wing

**Comment by xxalpha** [comment]
Update your local before you report bugs.

**Comment by MrStonedOne** [comment]
this is a byond bug. downgrade to 1305 or below or wait until 1311

**Comment by xxalpha** [comment]
It's a bug that was fixed by #12479

**Comment by MrStonedOne** [comment]
Nope.

It's a bug in byond caused by 1305, fixed in 1309, but breaks something else that will get fixed in 1311.

**Comment by freerealestate** [comment]
>Update your local before you report bugs.

did i bang your wife, officer?
i keep catching you following me around the repo, looking for excuses to cite me
i apologise, if i'd known she was yours i'd have taken the back route

**Comment by neersighted** [comment]
@MrStonedOne is this one fixed?

**Comment by tkdrg** [comment]
fixed in 509
