### ISSUE TITLE
Revenants are absolute garbage

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12705]
All I wanna be is a spookghost, but when my essence doesn't regenerate up to what I have absorbed it to, I can't even use any of my abilities to attempt to be spooky or do anything at all since they cost so much. They're shit. Their essence badly needs to regenerate (even slowly) up to the stolen essence you have.

**Comment by PKPenguin321** [comment]
f e e d b a c k

**Comment by Zilenan91** [comment]
nevermind i take back everything oh my god

**Comment by Anonus** [comment]
Revenants become more powerful as they eat the station, and even more powerful if they keep getting lucky with living players to harvest.

**Comment by Dorsisdwarf** [comment]
Took back everything?
