### ISSUE TITLE
Revenants can't hear deadchat and like to talk on deadchat

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12704]
This is somewhat confusing and mildly meme-y.
Relatedly, revenants might not be able to hear other revenants(and if they can it's impossible for them to tell what revenant is talking)

**Comment by Shadowlight213** [comment]
Revenants being unable to hear deadchat is intentional and not a bug. Deadchat is technically ooc while revenant chat and transmit is IC.
