### ISSUE TITLE
Metastation : "Dominator at Hallway"

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#12713]
Last I recalled the AI sat exterior maintainence tunnel with the glass windows to space was named AI Satallite Exterior, not "Hallway"
Ilostplsnerf.

**Comment by joonoro** [comment]
Amusing

**Comment by WJohn** [comment]
Probably just needs the areas to be renamed there, super easy to fix.

**Comment by Metacide** [comment]
Just had a look, seems that for whatever reason you can no longer search specifically for renamed area entries, making this rather more tiresome to fix. Doing some in-game tests now.

**Comment by Metacide** [comment]
The area in question - MiniSat Exterior - is a renamed, unused area - /area/construction/hallway. It's named properly and correctly. There are a fair few of these on the map, and I've not had any issues with them previously. The area works correctly on the powernet, and the Jump-To-Area verb.

Perhaps this is an issue with the way the area name is retrieved in the code for the dominator placement announcement?

**Comment by KorPhaeron** [comment]
Ironically enough it uses the default name to make sure someone doesnt use the CEs blueprints and make it impossible to find

**Comment by Jordie0608** [comment]
@Metacide Define new areas for metastation and replace the name-changed ones with them, it's what the map system is for after all

**Comment by MrStonedOne** [comment]
I think the easier way would be to store the initial name in New() and have the dominator (and admin alerts) use that.

This way admins can var edit areas and have that still be used.

**Comment by as334** [comment]
Actually wouldn't just using initial() work for that?

**Comment by MrStonedOne** [comment]
Thats what it's doing now.

The issue is that map renamed areas don't take the new name.

**Comment by Anonus** [comment]
A variant of this is a problem on dreamstation; if someone put a dominator in the bridge storage, it'd show up as "Head of Staff Meeting Room" instead of "Bridge Storage", and similar for other areas.
Though no areas are excessively changed, it's notable.
