### ISSUE TITLE
Box viro/xenobio disposal chute is broken.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#12711]
Items aren't ejected into space and are instead shot behind the outlet chute that's in space.

**Comment by WJohn** [comment]
Probably just needs a trunk, or is missing a pipe under a window or something, very easy fix.

**Comment by KorPhaeron** [comment]
The trunk is complete. I think it's airflow doing this (do disposals leak air?) since bodies still get spaced
