### ISSUE TITLE
The bio bag cannot quickly pick up slime extracts

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#12712]
Clicking slime extracts with the bio bag does nothing.

Other bags, like the plant or chem one, allow you to leftclick with it in your hands to immediatly pick up all the items on said tile that the bag can hold. Considering the bag was added to make xenobio work a bit quicker, this seems to be a bug.

Note that the bio bag is capable of holding slime extracts, but you need to put them them in one by one with the slime extract in your hand which kind of defeats the purpose.

Also seems to happen with syringes which this bag is also supposed to pick up.

**Comment by bgobandit** [comment]
yeah I noticed this too

will look into it

**Comment by WJohn** [comment]
Closed because the above mentioned issue report is more detailed.
