### ISSUE TITLE
Gibbed zombies leave behind an "infection holder"

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12710]
literally just a naked NPC zombie named infection holder that doesn't attack anyone and can be killed.

**Comment by duncathan** [comment]
@KorPhaeron put `qdel(infection_holder)` or whatever the var is called in zombie's `Destroy()`

**Comment by WJohn** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Needs an if(!istype(loc, /mob/living/carbon/human)) qdel(src)

In holders life. Also to be density 0 and invisible. Just in case

**Comment by optimumtact** [comment]
what thats gross
just qdelete it in the zombie destroy so it all gets garbage collected.

**Comment by KorPhaeron** [comment]
The infection goes in human mobs not zombies.

I dont want to add checks to human life for zombies

**Comment by KorPhaeron** [comment]
@dorisdwarf I fixed this
