### ISSUE TITLE
Flashbangs make revenants deaf forever,  and humans in crit 99% of the time don't give perfect souls

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12723]

**Comment by Anonus** [comment]
Please don't put two issues in one report also perfect soul mechanics require the target human to be alive, have a ckey(ie: be a player) and for you to get more than 90 essence from them(it's between 75 and 100 essence for living human w/ ckey)

If you get a perfect soul it gives a different feedback message, as well as a message after the drain finishes.
I know what causes the deafness, though(why is deafness defined at /mob when it's supposed to be carbon only holy fuck)

**Comment by Zilenan91** [comment]
Sorry about the double issue.

On the perfect souls, I know for a fact that I had several harvests that gave me more than 90 essence who were in crit. I must've absorbed at least 10 dying humans/lizard in crit, and only one of them ever gave me a perfect soul. I also couldn't find the perfect soul counter, but I could've just missed that.

**Comment by Anonus** [comment]
Did you check if the server was updated? The perfect soul counter appears correctly for me, so it might just have been the server not being updated.

**Comment by Zilenan91** [comment]
It was. Chainsaw surgery had been merged a few rounds before and the server updated. There were chainsaw people walking around. The refactor got merged a day or so before the chainsaw surgery.
