### ISSUE TITLE
Invisible Gasmask

### ISSUE THREAD

**Issue by TehPear** [tgstation/-tg-station#12729]
Was informed of this very recently by another player. The bug pretty much allows you to make your gas mask appear invisible. Thus I went ahead and reproduced it afterwards to get the steps down.
How to reproduce:
1. Get a welding helmet.
2. Put the welding helmet on your head and toggle helmet down.
4. Get a gasmask and put it on your mask slot.
5. Toggle welding helmet up.
6. Invisible mask.

Viola...hidden gas mask. You retain the benefits of the gas mask without looking suspect. Just tested with any mask item. It also works with any other the masks as well. 

Screenshot for example.
![bug](https://cloud.githubusercontent.com/assets/4440225/10825301/d5682124-7e3a-11e5-9282-94927c1cab82.jpg)

**Comment by TehPear** [comment]
Probably should have tested further. This works with any item that counts as a mask.

**Comment by Shadowlight213** [comment]
Drones wearing gas masks also have it appear invisible

**Comment by KorPhaeron** [comment]
Sounds like the cover flags arent set properly when being toggled, should be an easy fix

**Comment by Zilenan91** [comment]
I was messing around with this as a lizard and had a few good laughs. Still needs to be fixed.

**Comment by Invisty** [comment]
This also affects mimes. Put a welding helmet over a mime's mask, toggle the helmet, mime mask is invisible.

**Comment by WJohn** [comment]
This is still around.

**Comment by KorPhaeron** [comment]
@tkdrg 

Didn't you end up fixing this?

**Comment by tkdrg** [comment]
yes
