### ISSUE TITLE
box upload turrets bugged

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#12733]
The turrets are still shooting at people regardless if they are actually on or not.
I watched and tested it a couple times where the captain would turn off the turrets in the upload and they still shot and functioned.  This happened on box station as far as I know only, I have no idea about the other maps or if it's universal.

**Comment by WJohn** [comment]
Yeah I noticed this a few days ago, not sure what's causing it. Maybe the area names no longer being improper? I dunno.

**Comment by tkdrg** [comment]
Turrets are no longer area based so that shouldn't be the case.

**Comment by Jordie0608** [comment]
Dupe of #12634
