### ISSUE TITLE
Security sensor augmentation for AIs doesn't show loyalty implants or criminal status

### ISSUE THREAD

**Issue by Sligneris** [tgstation/-tg-station#12732]
AIs that set their sensor augmentation to Security cannot see whether the person has implants, nor their criminal status.

**Comment by GunHog** [comment]
Intended. I designed them to not be able to view implants to avoid certain scenarios involving disguised antags and such.

As for criminal status, I was simply not allowed to add it to the AI, despite how basic and useful it would be. I would change it if I had permission to do so.

That being said, the AI's security HUD is functioning as designed; this is not a bug.
