### ISSUE TITLE
Lich phylactery beam thingy is permanent

### ISSUE THREAD

**Issue by Darkgenerallord** [tgstation/-tg-station#12747]
It doesn't disappear until you revive and then it just moves. This is from experience.

**Comment by Incoming5643** [comment]
Why is everything I'm coding breaking before it's even settled?

When you say "moves" do you mean that the beam actually follows you around, or do you mean that it's static on the ground even if you leave?

**Comment by Darkgenerallord** [comment]
It remains on where the phylactery was, and won't move from where it is, until you revive. It will then move to wherever you revived at.

**Comment by Incoming5643** [comment]
And it just sticks there forever afterwards?

**Comment by Darkgenerallord** [comment]
Yep.

**Comment by Incoming5643** [comment]
I don't suppose you noticed if it happened to be about midnight server time when it happened?

**Comment by Darkgenerallord** [comment]
I have no clue what timezone the server is in.

**Comment by Incoming5643** [comment]
it's listed on the status tab.

If it happened today I'm asking if you saw this roughly 5 hours ago

**Comment by Darkgenerallord** [comment]
Oh, no. Like ten minutes before I posted the issue.

**Comment by Jordie0608** [comment]
@Incoming5643 This happened just last round; ~1 am server time. The beam was static to when it was created.
Also someone managed to drag a section of the beam around.

**Comment by Incoming5643** [comment]
Crestfallen, I must exclude the idea that maybe beam code just doesn't have good protection from midnight rollover.

Was there a runtime?

**Comment by Jordie0608** [comment]
runtime error: Cannot read null.z
proc name: Start (/datum/beam/proc/Start)
  source file: beam.dm,35
  usr: null
  src: /datum/beam (/datum/beam)
  call stack:
/datum/beam (/datum/beam): Start()
Beam(the floor (90,147,1) (/turf/simulated/floor/plasteel), "drain_life", 'icons/effects/effects.dmi', 20, 1e+031, /obj/effect/ebeam (/obj/effect/ebeam))

runtime error: Cannot read null.z
proc name: Start (/datum/beam/proc/Start)
  source file: beam.dm,35
  usr: null
  src: /datum/beam (/datum/beam)
  call stack:
/datum/beam (/datum/beam): Start()
Beam(space (88,157,1) (/turf/space), "drain_life", 'icons/effects/effects.dmi', 30, 1e+031, /obj/effect/ebeam (/obj/effect/ebeam)

**Comment by Incoming5643** [comment]
line 35 is sleep(sleep_time)

Whaaaaaat

**Comment by tkdrg** [comment]
Chances are either `origin` or `target` no longer exist, so the check always fails.

**Comment by Incoming5643** [comment]
I've figured it out. How this shit works locally for me I will never understand
