### ISSUE TITLE
Unable to open cache file

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#12755]
Possibly an issue on my end or byond thing but I've been getting message "Unable to open cache file" on chat log frequently when joining /tg/station server and clicking Changelog or Join Game. They'll eventually work after a bit of loading so it might be join load issue.

**Comment by MrStonedOne** [comment]
Your system hard drive is full.

Clear some space.

**Comment by Marflowerose** [comment]
Must be the byond cache then, I'll try it out, thanks.

**Comment by Marflowerose** [comment]
After clearing the cache it still occurs, there's 320 gigs free hard drive space so I doubt that's the issue either
