### ISSUE TITLE
Wizard constructs need a way to communicate with their wizard and vice-versa

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/-tg-station#12761]
Self-explanatory.

**Comment by Bawhoppen** [comment]
I'd disagree. Personally I hate the fact that theres even an indicator for ops to show who is also an op.

**Comment by feemjmeem** [comment]
Ops have radios, though.

**Comment by Bawhoppen** [comment]
I can see the gameplay reason, and you can justify it for constructs by 'magic bullshit', but how would an op know that it wasn't someone impersonating their ally? Its kind of dumb.

**Comment by Supermichael777** [comment]
iff eye implant paired with their gun authentication implants.

**Comment by Bawhoppen** [comment]
And theres no way to physically impersonate that? Nonsense.

**Comment by Supermichael777** [comment]
Its exactly like sechuds showing loyalty implants. its actualy simpler form a design perspective because its just a transmitter with an encrypted handshake that operates the guns electronic safety and squad identifier instead of the voodoo anti brainwashing chip in the NT stuff.

**Comment by Bawhoppen** [comment]
There is no specific equipment you need to view that they're a syndicate ally as opposed to a sechud or something.

**Comment by Dorsisdwarf** [comment]
Syndicates have Weapon Auth implants by default. Clearly they also have a built-in Syn-D-HUD in their eyes

deepest lore

**Comment by Dorsisdwarf** [comment]
feature request how did I not notice
