### ISSUE TITLE
Syndicate shuttle roundstart move deletes some objects on the syndie base

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12766]
There should be a door, a blastdoor, a button, a noticeboard, and a table in this shot.
![fuck](http://puu.sh/l3EEv/a675cc8aed.png)

**Comment by WJohn** [comment]
Pretty sure this has been around for a while.

**Comment by Anonus** [comment]
>close issue
>issue not fixed
>#13738
