### ISSUE TITLE
Breathing from oxygen tank inside box

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#12764]
Steps to produce:

Take oxygen tank in hands
Put mask on face
Put tank back in your box
Put box in your backpack
You're still using internals.

**Comment by blobbernaut** [comment]
I believe it is intended behavior that you're able to access stuff inside a container in your backpack, but NOT a container inside of that container, based on one of the comment lines I saw on a file when I was looking through the code.

**Comment by blobbernaut** [comment]
You can open up a medkit in your backpack by click-dragging onto your character and releasing

**Comment by francinum** [comment]
The tank part is unintended, being able to fully use a container inside a container, One layer deep, IS intended.

**Comment by xxalpha** [comment]
Pretty sure you're not supposed to breathe from a tank that is not in your pockets, belt, hands or suit storage.

**Comment by sirnat** [comment]
I tried it with a second way:

Take oxygen tank from box

Turn on internals

Store tank inside backpack

Internals don't work. 


Basically it works when in a box inside your backpack, but not inside your pack its self.

**Comment by tkdrg** [comment]
I can't reproduce this by following either one of your instructions.

**Comment by phil235** [comment]
Can't reproduce. Closing.
