### ISSUE TITLE
Borg unbuckle UI button doesn't work

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#12763]
**Server:** Sybil
**Revision:** Server revision compiled on: 2015-10-30
58c828ccfefca24f3d1a4a5571527924ff8d90d6 

**Problem Description:** As a borg, unbuckling from a chair using the UI button that shows up when you're buckled doesn't appear to work.

**What did you expect to happen:** For when I click the UI button to be ejected from my seat and to fall into the singularity not more than one tile diagonally away.

**What happened instead:** I had to type out the resist command as I was getting no feedback from whether or not the unbuckle button was working.

**Why is this bad/What are the consequences:** Consistency! Since I can get out using resist, I'd expect to be able to get out using the button. Misleading! I can't tell if I'm meant to be able to unbuckle myself as a soulless automaton or if resist was overlooked.

**Steps to reproduce the problem:** Be a cyborg, buckle yourself to a chair, look for the UI button showing a chair (indicating you're buckled) to show up, click it, try to move/notice the button is still there meaning you're still buckled!

**Possibly related stuff:** On the escape shuttle in escape, I was buckled to a chair by another player, I was also a secborg.

**Comment by Darkgenerallord** [comment]
Did you have a tool selected?

**Comment by CosmicScientist** [comment]
Uh, maybe? I don't think so?

**Comment by newfren** [comment]
I was playing as runtime and buckled myself to a chair and the same shit happened to me - using the button did nothing, but typing resist freed me.
