### ISSUE TITLE
Slimeperson splitting says it can't connect to your original body if you try to swap back

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#12784]
I managed to get enough jelly to split, but after hitting the swap button, it said it couldn't connect to my other body, even though I was right next to it. The button itself vanished after being clicked so I couldn't try it a second time.

**Comment by Jordie0608** [comment]
@Incoming5643

**Comment by Jordie0608** [comment]
Actually seems like the servers haven't updated since #12746 was merged so this may be fixed, I'll leave it open for now just in case.

**Comment by Incoming5643** [comment]
Yeah I'm pretty sure this is just that bug, servers just need to updoot

**Comment by Incoming5643** [comment]
Server's updated, let me know if this is still a problem

**Comment by MMMiracles** [comment]
@Incoming5643 

Swapping works now.

**Comment by Incoming5643** [comment]
then you should close this

**Comment by MMMiracles** [comment]
ayy
