### ISSUE TITLE
Tooth implants are completley unlogged

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12790]
ADMIN LOG: Explosion with size (2, 6, 13, 0) in area Holodeck Alpha (93,81,1)

And can make fairly large explosions if filled with blackpowder. I only know who did it because I saw a dead medbay guy in the blast area and asked him if he'd been using a tooth (yes)

@Incoming5643

**Comment by Incoming5643** [comment]
More than anything, I'm impressed

**Comment by Incoming5643** [comment]
This is at least partially a dupe of #11601

**Comment by KorPhaeron** [comment]
@Incoming5643 

He was doing it unlogged with phlog stuff as well

**Comment by Incoming5643** [comment]
you say potato, I say goofchem.

I dunno, I'll see what I can do

**Comment by Darkgenerallord** [comment]
Sadly, smoke dermal implants are not a thing. Explosive smoke is kill :(
