### ISSUE TITLE
Chainsaw sound is insanely loud.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#12809]
Tone it down please, it's painful to hear.

**Comment by Zilenan91** [comment]
Yeah it's wicked loud, I have to turn my volume WAY down to make it even bearable.

**Comment by optimumtact** [comment]
RIP AND TEAR YOUR GUTS

**Comment by freerealestate** [comment]
I've said it before but the game's sounds aren't very consistent in terms of loudest --> quietest

In a Pathologic remake Kickstarter update the sound designer was describing the process of designing sound for the game, which involved first figuring out the loudest and quietest sounds and then ordering the rest between them

Kind of need to do that for /tg/station

Would be a lot of work though, and on the spot fixes for egregious issues like this one work too
