### ISSUE TITLE
Dental implants can revive you from death and can also be used multiple times if you spam click the HUD for it.

### ISSUE THREAD

**Issue by kpeculier** [tgstation/-tg-station#12815]

**Comment by Incoming5643** [comment]
You wanna elaborate?

**Comment by kpeculier** [comment]
According to the Ahelp the player did have multiple pills in his mouth, but was able to use them repeatedly regardless.

**Comment by Darkgenerallord** [comment]
Pill reagent may not have transferred twice, but it does have a double message, I think?

**Comment by Incoming5643** [comment]
yeah the message might have doubled, but I don't think the dose would
