### ISSUE TITLE
Girders have a hilariously low layer

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12821]
As in it's lower than alien weeds, pipes, wires, etc.

**Comment by Supermichael777** [comment]
Layers on a lot of objects are really low. We really need an atom layering overhaul

**Comment by WJohn** [comment]
Sounds like #12069 is related to this.

**Comment by optimumtact** [comment]
An atom layering overhaul that this would imply is not an easy fix

:smile:

**Comment by phil235** [comment]
It's been like this for a very long time. I think the low layer of girders and walls was intended to make pipes and wires appear above them so that fixing pipes that goes through walls is easier.

**Comment by chimersable** [comment]
I think it was set this way to keep people from hiding stuff in solid metal walls.

**Comment by Jalleo** [comment]
What @chimersable said false walls included (child of girders i believe

**Comment by Anonus** [comment]
You can't hide stuff in solid metal walls anyway, they're not related to girders, and you can hide stuff in false walls and I'd call that a feature.
