### ISSUE TITLE
Issue Count Rising

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#12838]
Despite valiant crushing from heroes of the Code Empire, issues continue to climb towards 900.

can anyone stop their tide?

Only the great chemperordan can save us now

**Comment by Marflowerose** [comment]
And someone just recently cleaned up the obsolete issue reports. What a time to be alive.

**Comment by WJohn** [comment]
PHIL WILL SAVE US IF WE BELIEVE HARD ENOUGH.

THIS I KNOW TO BE TRUE.

**Comment by Iamgoofball** [comment]
Reminder that 212 are Not A Bugs

**Comment by Jalleo** [comment]
One solution is ask people who have worked on areas that have reports after this and ask was this fixed or did you notice this after your work on this area?

**Comment by Chocobro** [comment]
then why don't you make a pr to get rid of those numbers
instead of adding to them

**Comment by Jalleo** [comment]
Imma starting tomorrow i had only a hour free today

**Comment by ike709** [comment]
this literally just adds another issue just to tell everyone something we already know

**Comment by Dorsisdwarf** [comment]
I didn't have time to find cheridan in coderbus to propose a freeze yesterday

**Comment by Dorsisdwarf** [comment]
We're reaching a critical limit for being able to just squeeze the issue pack while adding features, someone is going to have to back down and fix a bug soon
