### ISSUE TITLE
Bottles made by pandemic have points you can click on that hit underneath them.

### ISSUE THREAD

**Issue by wflagg** [tgstation/-tg-station#12837]
Bottles made by the pandemic have a point where if you click on them you click on the object (usually a table) underneath them. 

Top half, near the neck

Suspect the image file for them just has blank pixels there.  Probably fixable by adding something transparent there.

Common example, when the bottle is on a table in virology, and you click on it with a dropper, the dropper goes onto the table on top of the bottle, instead of drawing the material.

**Comment by newfren** [comment]
Oh shit yeah, you have to either click on the "spout" of the bottle or the blood itself to pick it up, the gap where there's no blood doesn't work. 

Total pain in the arse.

**Comment by octareenroon91** [comment]
That part of the sprite is transparent.

I'd imagine there's more than one report of this issue, but it still needs fixt.

**Comment by phil235** [comment]
Can't reproduce. And I remember fixing this bug myself some time ago.

**Comment by PKPenguin321** [comment]
is this still an issue?
