### ISSUE TITLE
You dont fall over when having a seizure

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12830]
You just stand there, not shaking or anything, wondering why the hell you cant move.

**Comment by kingofkosmos** [comment]
Cannot reproduce. If epilepsy mutation is what you're talking about, I just tested it; fell down during an epilepsy seizure.

**Comment by Shadowlight213** [comment]
Odd. Yeah, it was touretts mutation.

**Comment by phil235** [comment]
Looking at the code (https://github.com/tgstation/-tg-station/blob/0ca14adc8412120fb7052e427991601d7d4b2985/code/datums/mutations.dm#L325), this seems intended (if it was Tourettes). No idea why Tourette was given a 10 second stun, it's been like that since it was introduced years ago apparently.
