### ISSUE TITLE
Slime consoles don't work while buckled, can contain negative monkeys

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#12832]
You can't move the aiming-brackets-square-thingy while buckled into a chair

Also, you can get negative monkeys by reclaiming one and then popping one out. I ended up with -0.8 monkeys.

**Comment by Bluespace** [comment]
The second issue is already fixed.

**Comment by KorPhaeron** [comment]
Duplicate issue @dorisdwarf

**Comment by Dorsisdwarf** [comment]
# CRUSH #
