### ISSUE TITLE
Tooltips can have hyperlinks which can't be clicked.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#12844]
Good example is the posibrain alert, which has the click to enter hyperlink in the tooltip.

**Comment by freerealestate** [comment]
these tooltips look super fucking modern
we're like 2014 or some shit now
seriously we need like

yeah

**Comment by tkdrg** [comment]
Well they're just HTML, of course they can have hyperlinks. This is more of a bug about the posibrain alert than anything.
