### ISSUE TITLE
Clicking ghost alerts for revival doesn't immediately put you in the thing

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#12843]
Instead of even popping up the "do you wanna be the thing" message, it just teleports you to where the thing is, which is REAL SHIT

**Comment by Dorsisdwarf** [comment]
Explain further. This isnt enough info to do anything meaningful about @Anonus

**Comment by tkdrg** [comment]
This is what I intended, though. I guess it could put you inside the thing, but I'm concerned about the issue of misclicks.

**Comment by Anonus** [comment]
If you click one of the ghost alerts, it just teleports you to whatever made the alert instead of trying to put you in whatever made the alert, if applicable.
