### ISSUE TITLE
Z levels on dream station mesured at 500 x 255

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#12846]
500 tiles wide to be exact
Map was dream station but issue occurred on generic maps too
edit: should note I confirmed my xy with a gps. the extra area was empty.

**Comment by freerealestate** [comment]
drifting in space has always been awful due to the limited view range and the lack of land masses 
this might be a way to deal with that

**Comment by WJohn** [comment]
Z levels are all stuck to 255x255 sizes each. You're probably just not running into anything in space due to our lack of space content and due to our current space loop system.

**Comment by freerealestate** [comment]
hypothetically though do they actually need to be that big? the station has a lot of empty space around it.

**Comment by WJohn** [comment]
That's entirely up to the map maker, any I'm sure players will be complaining about it being too big.

Whether we could reduce the map size to 200x200, I mean I GUESS that should be possible but I think you'd need to reduce every map to that or whatever size you want, as long as it's the same across all of them.

**Comment by Marflowerose** [comment]
One problem is also fact that space loop system changes occasionally which makes designing maps that much more difficult, at least when considering the prospect of permanent loop. The most annoying Z-level is the one with absolutely nothing in it so navigating that is much more difficult, even with a handheld crew monitor. I suppose some kind of GPS can help determining current coordinates but that's a hassle aswell.

**Comment by Dorsisdwarf** [comment]
He confirmed via GPS that the map is the wrong size apparently.

At last, proof that we can unanchor the size of space from the size of the station

**Comment by Supermichael777** [comment]
it was super annoying because jetpacks have terrible fule economy

**Comment by Anonus** [comment]
Is this a dreamstation issue or did someone fuck a zlevel up because I'm pretty sure dreamstation's added zlevels are both 255x255

**Comment by Jordie0608** [comment]
BYOND scales all z-levels to the size of the largest one when loading the maps. The stations don't need to have consistent 255x255 sizes (and currently don't) but for most of them there isn't much that could be reduced mostly due to syndie shuttles being placed in the empty space around the stations.

That aside, Dreamstation isn't 500 tiles tall, so this is some weird error.

**Comment by Anonus** [comment]
This is not actually a dreamstation error and is probably an away mission that's far too large.

**Comment by Jordie0608** [comment]
I did a quick check of all the away missions, none are that big either from what I recall.
