### ISSUE TITLE
AsteroidStation: Brig cells don't auto-lock and unlock lockers

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12858]
Annoying as hell when you are security, used to Box's system, and then have prisoners screaming over the radio "SHITCURITY DID'T UNLOCK MY LOCKER". (Or vice versa, and then the prisoner gets their PDA out and emags everything.)

**Comment by WJohn** [comment]
Probably needs a unique locker, or some ID tag or something.

**Comment by xxalpha** [comment]
Who even maintains asteroid?
