### ISSUE TITLE
Bucket quick-equip defaults to your head slot. 

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#12856]
The amount of times I've managed to dump water over my head when trying to stash a bucket in my bag is reaching concerning levels.

**Comment by RemieRichards** [comment]
Not solvable, helmet slot takes priority over backpack.
Would you rather never be able to quick equip helmets or occasionally spill water on you?

**Comment by MrStonedOne** [comment]
Really this should be handled on a per-item base with some sane defaults.

Sounds like a job for OBJECT ORIENTED PROGRAMMING
