### ISSUE TITLE
Derelict windows in all sorts of silly directions.

### ISSUE THREAD

**Issue by Saegrimr** [tgstation/-tg-station#12866]
I tried to upload a screenshot but it wont let me.

Anyway almost all of the fulltile glass windows on the derelict on boxstation are in all sorts of weird and fucky directions. Some dir = 8, dir = 5, solid on the top side but can walk through left/right/bottom.

Basically all acting as if they were single direction windows with the fulltile sprite.

**Comment by Jalleo** [comment]
Dupe
