### ISSUE TITLE
Shadowlings can hatch after having already hatched previously

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12883]
Happened during a round today, quite weird.

**Comment by KorPhaeron** [comment]
Admin let him rehatch, not a bug

**Comment by Zilenan91** [comment]
Why'd he need to rehatch?

**Comment by KorPhaeron** [comment]
Nightvision broke or something, ask Oldman

**Comment by Niknakflak** [comment]
Close this issue then
