### ISSUE TITLE
Metastation: Lower cargo shuttle conveyor belt facing the wrong direction

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12888]
http://puu.sh/lc9NL/0427935068.webm

**Comment by Metacide** [comment]
Damn, issue with standardising the shuttle over all maps. Guess we have to go back to the other layout of the conveyors once more, even if it's a pain - short conveyor will be input, long will be output.

Thanks for the heads-up.

**Comment by francinum** [comment]
No, the upper one goes in the correct direction
Both of them face out.

**Comment by Jordie0608** [comment]
@Metacide Shuttles aren't standardised, they're per-map

**Comment by MrStonedOne** [comment]
Ya, @metacide, this entire thing was done to make it easier for mappers to edit shuttles without having to override z2

The shuttles should all start on the station z-level so you can just edit the conveyer on the shuttle

**Comment by Metacide** [comment]
Oh, how embarrassing.

Will fix, thanks for the heads-up.
