### ISSUE TITLE
Beepsky provides no criminal level if the target is an alien

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12894]
[Security] Officer Beepsky says, "Arresting level  scumbag the alien praetorian in the Command Hallway."

**Comment by Zilenan91** [comment]
Speaking of beepsky, if you put an oxygen tank on the back of a monkey securitrons flip out and start arresting the shit out of them. Though I think that's more of an "intended" bug.

**Comment by Dorsisdwarf** [comment]
@Zilenan91 They arrest monkies for not having an ID if set to IDcheck, not for having a tank
