### ISSUE TITLE
Buckling tooltip is misleading for janicart/secway

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12893]
The buckling tooltip says "you're buckled and cannot move," but janicart/secway work off buckling. Not so much an issue with the secway because anyone playing warden (hopefully) knows how it works, but noobs might roll janitor. Easy fix, just edit the text.

**Comment by Miauw62** [comment]
anybody using the janicart is a skrublord tbh

**Comment by bgobandit** [comment]
@swankcookie

**Comment by swankcookie** [comment]
I'll take a look

**Comment by swankcookie** [comment]
Looking at it, I don't really see an issue. It's probably better to leave it on, as newbies might accidentally get on without knowing how too get off, and the tooltip will give them something too go off of.
