### ISSUE TITLE
Firing range targets randomly change icons

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#129]
Project Member Reported by Kortgstation, Jan 20, 2013
Revision that this bug was encountered on (REQUIRED!! Type 'show-server-
revision' ingame to find out - note that 'current revision' isn't
helpful!):
r5579

Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2,
Facepunch, Pinkstation, /VG/... etc.)
Sibyl1

Problem Description (What did you expect to happen? What happened instead?
Why is this bad/What are the consequences?):
Randomly swaps icons. This only seems to happen on a client by client basis, not for the whole game.

http://i.imgur.com/tJrd6yU.png

(That tree is a target)

**Comment by WJohn** [comment]
This is a recent instance of it. Also this bug is now 2 years old!
http://i.imgur.com/5j6hMcK.png

**Comment by WJohn** [comment]
http://i.imgur.com/SaOCOvf.png Happened again today, this was its icon state.

**Comment by Thunder12345** [comment]
Done some testing, I can reproduce this on syndie targets, and only syndie targets.
* Stick syndie target in stake
* Get prototype SMG
* Use a standard firing pin (No idea if this affects it but I might as well mention it)
* Set the SMG to three round burst
* Shoot target
* It turns invisible, but the bullet holes remain visible, and it can be interacted with

Can I have a medal now?

**Comment by WJohn** [comment]
So it has something to do with getting spammed by bullets?

**Comment by CorruptComputer** [comment]
Maybe if the number of bullet holes is too high it breaks?

**Comment by ike709** [comment]
Fixed in #9488 but wasn't closed since aran is dumb
