### ISSUE TITLE
Oil slime extract doesnt log who set it off

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#12902]
wew

**Comment by KorPhaeron** [comment]
At least this means they're finally worth using over other explosives!

**Comment by phil235** [comment]
Same problem as with #11601 there's no reference to the mob or client in the proc that we can easily use for this.

**Comment by KorPhaeron** [comment]
@Phil235

We can use the last fingerprints, same way as gold slime reactions do

Or I could finish turning them into actual grenades so we wont have to duplicate code
