### ISSUE TITLE
Some away missions spawn NODROP Hardsuit helmets

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12907]
![](http://puu.sh/ld4uu/fa62c06b6b.png)

**Comment by WJohn** [comment]
They're simply very old, this was back before we had retractable hardsuit helmets that were nodrop items. Easy fix, just remove them.

**Comment by MMMiracles** [comment]
If you know any more past the station collision please let me know so I can fix those too.

**Comment by Firecage** [comment]
I think the emitter maze has one.
