### ISSUE TITLE
Away Mission Issues

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12917]
**GENERAL**
`APCs are strange`
`Blast doors are broken`
`Shutter buttons are broken`
*BMPacker:*
`Generic Meat Snack items`
*Challenge:*
`Hardsuit helmet at 119,104`
*Example:*
`Exterior walls are not indestructable, it is possible to escape to the edge of the Z and see the second floor.`
`Sprite-less tiles`

![](http://puu.sh/ldrmS/6287421c26.png)

**Comment by francinum** [comment]
@MMMiracles

**Comment by Shadowlight213** [comment]
@francinum Challenge emitter thing is not a bug. Those are energy cannon emitters. They dont need power.
