### ISSUE TITLE
Mining vouchers don't work

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#12926]
What happened: I tried to use a mining voucher on an ore redemption points machine thing
What I expected to happen: It to work like it always did
What happened: It did nothing.
Other details: Asteroid Station. Roundstart, everything powered. Clicking the ore machine seemed fine, but of course I had no points then. Neither redemption machine worked.

**Comment by GunHog** [comment]
Maybe you were looking for the *equipment locker*?

**Comment by bgobandit** [comment]
no it was the right machine I just forgot its name

**Comment by francinum** [comment]
@bgobandit Mining Rewards Vendor?

**Comment by phil235** [comment]
Are you sure you're not confusing the Ore Redemption Machine and the Mining Equipment Vendor? Vouchers only work on the latter.

**Comment by bgobandit** [comment]
I am 100% sure it is the right machine, it is the one that you put your ID in and it gives you a list of shit to buy (this part works)

**Comment by bgobandit** [comment]
that said it worked for me this round on ass, what teh fuck
