### ISSUE TITLE
That's an universal recorder.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#12928]
AN

![](http://puu.sh/levho/32a13a5df6.png)

**Comment by phil235** [comment]
Also "uranium deposit", "uranium ore", "used slime extract", "universal enzyme bottle", "uranium airlock assembly", "uranium airlock", "uranium wall", "uranium floor", "urinal",

**Comment by francinum** [comment]
Anything starting with U.

**Comment by duncathan** [comment]
This is an issue with byond's \an macro.

**Comment by duncathan** [comment]
This is an issue with byond's \an macro.

**Comment by freerealestate** [comment]
I wish you could define custom macros
