### ISSUE TITLE
Timestop sometimes do not unanchors the mobs it anchored.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#12922]
I'm not sure how to reproduce this, but during a wizard round one of the humans who was caught in at least one timestop ended up staying anchored. The mob probably got out of the timestop area somehow.
In any case, the timestop() proc is ugly and bound to cause such bugs, it needs to be rewritten so it enables no edge case.

**Comment by MrStonedOne** [comment]
>The mob probably got out of the timestop area somehow.

ya, there are a few ways this can happen, singulo being the most obvious

make it store a list of things it's stopped so this doesn't become an issue
