### ISSUE TITLE
MMIs + HoG

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#12936]
HELP: Onearmedyeti/(Crazy Diamond) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): For some reason I got a message saying  thge following deconversion messages when being put from mmi into a new body "Your mind has been cleared from the brainwashing the followers have done to you.  Now you serve yourself and the crew." Cyborg(?|F) looks like their faith is shattered. They're no longer a cultist! 

This happened during a nuke round

@RemieRichards @tkdrg

**Comment by RemieRichards** [comment]
Looks like tk missed some arguments to make those deconversions silent.
or they should probably check the conversion is there in the first place.
@tkdrg

**Comment by tkdrg** [comment]
They have always announced. I guess I could make them all silent.
