### ISSUE TITLE
"Challenge" awaymission is impossible

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#12947]
The gateway at the end of it is blocked by invisible shutters that cannot be opened. There is a button nearby but it lacks electronics to actually open the shutters.

**Comment by Incoming5643** [comment]
the "intended solution" is that there's a c4 somewhere on the map that can be used to blow up a shutter.

If you use it anywhere else, for anything else, the map is impossible to leave. Good game design!
