### ISSUE TITLE
C4 explosive runtime

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#12951]
Add a signaler to a C4. Plant the C4 on anything (this makes the C4's loc null). Trigger the C4 with a second signaler before the C4's 10 second timer is over. The code is trying to explode the C4 and look for the turf via get_turf() but can't find it since loc is null. You get this runtime:

runtime error: Cannot execute null.ex act().
proc name: explode (/obj/item/weapon/c4/proc/explode)
  source file: explosives.dm,98
  usr: Maximus Robusticus (/mob/living/carbon/human)
  src: C-4 (/obj/item/weapon/c4)
  usr.loc: the floor (144,143,1) (/turf/simulated/floor/wood)
  src.loc: null
  call stack:
C-4 (/obj/item/weapon/c4): explode(null)
/datum/wires/explosive/c4 (/datum/wires/explosive/c4): explode()
/datum/wires/explosive/c4 (/datum/wires/explosive/c4): UpdatePulsed(1)

**Comment by PKPenguin321** [comment]
oh
i thought not being able to signal planted C4s was intentional, not a runtime
if this is fixed, does it mean you can insert a signaler, plant a C4, then signal it?

**Comment by phil235** [comment]
@PKPenguin321 Yep
