### ISSUE TITLE
You can't pull imbedded objects out of yourself

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12978]

**Comment by tkdrg** [comment]
@RemieRichards

**Comment by phil235** [comment]
Actually, you can, clicking the alert icon only makes you examine yourself but the embedded item appears in the examine text and can be clicked to pull it out.of you. I guess the clickable embedded text could be made more visible.

**Comment by KorPhaeron** [comment]
Still an issue for people who cant click chat links without crashing

**Comment by Zilenan91** [comment]
@phil235 I was spam clicking the imbedded item after clicking on myself and it did nothing.

**Comment by phil235** [comment]
@Zilenan91 In that case I couldn't reproduce that bug. Can you give more info about how that bug happened?

**Comment by Zilenan91** [comment]
@phil235 An explosion shot a metal rod into one of my arms and I was unable to pull it out. I had to wait for it to fall out on its own.

**Comment by PKPenguin321** [comment]
i think this was a byond bug from a while back, certain byond client builds made links in the chatbox unclickable
