### ISSUE TITLE
Slaughter Demons can eat players they've already eaten

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#12983]
I think this comes about because they're still technically "pulling" dead people who are now placed inside of their stomach to burst out when they die.

**Comment by Dorsisdwarf** [comment]
what? How do they do this if they can't click on the person?

**Comment by Zilenan91** [comment]
I have no idea, I assume it's because they're still pulling the dead guy in their stomach and when they blood jaunt again they both get the heal and the "stun" when eating it.

**Comment by phil235** [comment]
yep, need to add a stop_pulling() in the bloodcrawling proc.
