### ISSUE TITLE
Veil Renders are fucking hilarious (but overpowered)

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#12995]
Veil renders make mini Nar-Sies that turn everything into cult tiles and people into harvesters. While this is funny, five of them are not.

**Comment by duncathan** [comment]
Note to self: never trust kor code

**Comment by KorPhaeron** [comment]
@duncathan 

Hey it worked when I originally made it ~4 years ago, but Nar-Sie was changed since then (including the mini wizard version that was made for veil render)

**Comment by KorPhaeron** [comment]
I should probably put a cap on them as well
