### ISSUE TITLE
Super Priority Omega Alert: Tasers only fire two shots now.

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#13012]
God damnit

**Comment by Robustin** [comment]
Haven't been able to replicate it on Box yet, this took place on ass-teroid station with a roundstart locker taser. Tested it several times there and could never fire more than 2 shots after a full charge.

**Comment by Shadowlight213** [comment]
Needs low priority tag.

**Comment by WJohn** [comment]
Did this happen consistently over multiple rounds? You know that explosions can damage a cell's capacity, even when it's in a gun. Was the locker caught in an explosion at some point? It may have been affected.

**Comment by Robustin** [comment]
there was an explosion, had no idea that it could damage cells to the extent they would hold a lesser charge... theres no indicator for this.

**Comment by Shadowlight213** [comment]
>It happened once with a single taser
>couldn't reproduce it again.
>PRIORITY CRITICAL! EVERYTHING IS BROKEN!
Nice.

**Comment by Jalleo** [comment]
Okay this can be closed make a different issue report explaining the power charge isnt easily explainable.
