### ISSUE TITLE
Swapping to different slime people as a thrall removes the thrall icon from your characters

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#13019]
Does it to the shadowling icon as well

**Comment by tkdrg** [comment]
That's weird, since it uses `transfer_to()`, which should handle that.

**Comment by Incoming5643** [comment]
sounds like something about those statuses isn't properly mind attached

**Comment by tkdrg** [comment]
AAAAAA I JUST FOUND THE CAUSE FOR THIS ISSUE PLEASE KILL ME
