### ISSUE TITLE
You can turn into a catperson at will and back and ignore the catperson job restrictions entirely.

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#13014]
Switching your selected character ingame with the game preferences panel allows you to turn into a catperson at will. For example, join as a regular human in a job that is not avaible for a catperson, then go into the preferences panel, make another character and give them custom ears/a tail and click save. Then, change your clothing and you will suddenly gain ears/a tail. May have to wear clothing that updates the whole body, like a hardsuit.

This also works backwards, so a catperson could become a human to be spared by the silicons for example.

**Comment by tkdrg** [comment]
@MrStonedOne possibly related to your in-game preferences thing.

**Comment by Iamgoofball** [comment]
# cat ears would be admin only they said
# they'd never be common access they said

**Comment by MrStonedOne** [comment]
@tkdrg it is but only because who ever coded underwear shit fuck up

**Comment by Shadowlight213** [comment]
@Ricotez

**Comment by Shadowlight213** [comment]
I'm assuming this is still a thing.

**Comment by tkdrg** [comment]
Nope. Fixed up by #13899
