### ISSUE TITLE
UO45 and MO19 lockers are still invisible.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13030]
I see you decided to replace *some* of the lockers with default ones, but you realize I put custom made ones specifically to avoid having round-start items being spawned into those, right? So not only are some of the lockers still invisible, but all the lockers you replaced now have all the default equipment plus everything that was on that tile, leading to quite a few duped items.

Also one of the walls in UO45 is still a shuttle wall, and there's still a wall in front of one of the maint doors in the main lobby.

EDIT: And an extra wall next to the elevator bathroom.
EDIT2: And an extra wall next to the vendors in the lobby area.

Come on, man.

EDIT3: All the invisible lockers on MO19 are still invisible. This wasn't fixed at all! Additionally, all the indestructible walls that form the border of MO19 (and likely UO45) are bugged and look like default walls. You need to swap them with turf/indestructible/riveted walls, and then icon swap them all to "rock".

**Comment by MMMiracles** [comment]
fak
