### ISSUE TITLE
Causing revs/loyalists to loose due to braindeadness is unfair

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#13039]
As it says in the title, it is unfair. Sure, it has a legitimate use, but not everyone has a 100% super never-fail internet connection, nor does everyone have a PC which never crashes. And on rare occasions, even dream seeker may crash for a player for a weird reason.

In short, this means that you can get disconnected for a reason beyond your control, and suddenly your entire side looses.

**Comment by Marflowerose** [comment]
There could just be a timer for like a minute after it counts you as dead, best of both.

**Comment by CosmicScientist** [comment]
A timer would be nice. Especially for those of us who sit through the adverts to play.

**Comment by Firecage** [comment]
But would that be enough? I know personally that Byond has sometimes caused me to redownload everything when trying to reconnect after I got disconnected.

**Comment by CosmicScientist** [comment]
How long does the redownload take usually?

**Comment by Firecage** [comment]
On a fast day, not long, on a slow day, long.

**Comment by CosmicScientist** [comment]
Well... why not a timer and an antag swap? So it picks a random rev if any exist to be the new revhead if the first one can't get back in time? It might be an arse to code but I'm just throwing an idea up that won't mean people will go "Oh, why didn't the round just end then instead of us waiting 10 minutes to find out we lost 10 minutes ago?"

**Comment by PKPenguin321** [comment]
honestly, it shouldn't count for losing, and if a revhead/head goes braindead that should just get handled by admins.

**Comment by Nitrousoxide** [comment]
For rev's at least you could drop a popup on all the other revs asking if they would like to have their soul placed in the rev head's body.

Obviously you can't just switch rev heads because that could get them out of the gulag or perma.
