### ISSUE TITLE
Exiting a transit pod after attempting to resist out can break the resist command

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13046]
>be on fire
>run into pod
>try to roll
>YOU TRY TO ESCAPE THE POD
>walk out of pod normally
>can't resist anymore at all
>burn to death

**Comment by duncathan** [comment]
Another one to add to the ol "reasons transit tubes are disgusting" list

**Comment by tkdrg** [comment]
Can't reproduce. Do note that after attempting to use resist to break out of a container, you have a 10 second cooldown before you can attempt to resist again, and that resisting from containers has a higher priority than rolling. I suspect that this is what happened here, and if so, then this isn't quite a bug. @duncathan @Dorsisdwarf

**Comment by Dorsisdwarf** [comment]
Requesting someone confirm that the container resist cooldown is what's happening here

**Comment by tkdrg** [comment]
You can easily test it yourself if you'd like: set own health really high (or keep healing yourself by modifying your burnloss, don't use the heal adminverb as that will extinguish you), set yourself on fire , enter a tube, resist, then leave the tube, wait ten seconds, and try to resist again.
