### ISSUE TITLE
Dust() while you have a hardsuit helmet up will destroy the helmet

### ISSUE THREAD

**Issue by Nitrousoxide** [tgstation/-tg-station#13041]
Be traitor
Order holoparasite
Get space suit with deployable helmet
Deploy Helmet
Die and get turned into bones
Spacesuit drops but helmet can't be deployed again.

**Comment by Zilenan91** [comment]
So when you die inside a hardsuit while you have a holoparasite, the hardsuit dissapears?

**Comment by Nitrousoxide** [comment]
Just the helmet disappears, but yeah you got it.

Basically:
Be traitor
Order holoparasite
Get space suit with deployable helmet
Deploy Helmet
Die and get turned into bones
Spacesuit drops but helmet can't be deployed again.

**Comment by Nitrousoxide** [comment]
I should note this may also be an issue for other stuff that turns you into bones when you die.  Haven't check those though.

**Comment by Anonus** [comment]
Normally the dust() proc would delete all your items, so this is instead only an issue for stuff that tries to unequip everything before killing you.
Probably applies to the airtank suicide as well.

**Comment by PKPenguin321** [comment]
@Nitrousoxide you should change the title of this issue to
"Dusting while you have a hardsuit helmet up will destroy the helmet"

**Comment by Invisty** [comment]
This isn't the only bug related to hardsuit helmets. There's a variety of cases where you can end up with the helmet stuck on and not wearing the hardsuit, too.
