### ISSUE TITLE
Used Spellbook Mindswap kicks the person who didn't read the spellbook to the lobby

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#13054]
Mindswapped into an individual after reading a previously read spellbook of fireball. The person previously inhabiting that body was sent to the lobby and had to rejoin as an observer. Serious bug. 

Occured on Sybil around 3:40 PM, 11/16.

**Comment by Incoming5643** [comment]
Also probably a problem in the mass mindswap summon event
