### ISSUE TITLE
PR Announcements aren't "OOC"

### ISSUE THREAD

**Issue by Invisty** [tgstation/-tg-station#13067]
1. Mute OOC
2. Get spammed by PR announcements.

It seems to me that these should really be OOC, or players should at least have some means of muting them. Currently I see these messages when I have OOC muted, which ruins muh immersions.

**Comment by Anonus** [comment]
There's a game preference for them, in game preferences, which can be accessed from the preferences panel.

**Comment by Invisty** [comment]
Doh.
