### ISSUE TITLE
Hand of god healing fountain doesn't heal

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#13066]
It should also work off of process instead of only updating when clicked, and a fountain should NOT be able to heal enemy followers.

**Comment by tkdrg** [comment]
@RemieRichards

**Comment by PKPenguin321** [comment]
i think it might dispense doctor's delight instead of actual medicine

**Comment by RemieRichards** [comment]
@Anonus it doesn't heal the enemy.

**Comment by Anonus** [comment]
Right now it doesn't heal anyone, but the check for adding the healing chem is "is this guy a hand of god follower" and not "is this guy a follower and on the right team" so yes, it would heal enemy followers.

**Comment by RemieRichards** [comment]
Hmph.
Those checks are wrong.
