### ISSUE TITLE
Autochangelog still makes changelog despite tags not closing

### ISSUE THREAD

**Issue by JJRcop** [tgstation/-tg-station#13071]
## #13062 
In the description you can see ```:cl:``` like normal, but oranges mistakenly closed it with ```/ :cl:```, instead of ```/:cl:``` This results in the changelogger not closing properly, and after parsing everything correctly, it dumps the rest directly into the changelog file, seen here: e351c7e3858b1ef6913ad9115839aba41cd1e0a4

What I would expect to happen is that the bot fails and doesn't do anything if the tag is not properly closed.

@MrStonedOne

**Comment by MrStonedOne** [comment]
I had already fixed this by the time you opened thus bug report =P

@WJohn You forgot the blame mso tag
