### ISSUE TITLE
Cyborg Toner not refilling in charger.

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#13073]
There's this verb called print image that uses toner stored in a borg to print an image
This can only be refilled with a toner catridge from cargo, NOT a borg charger
1. Max capacity of a borg is enough for 2 pictures
2. Ordering toner from cargo is extremely annoying and getting a human to apply it to you every time you print two photos..
3. Everything else is replenished by a RECHARGER, not an external item
4. There's no harm in making it replenished by a charger. It's not like it's going to throw things out of balance :^)

**Comment by duncathan** [comment]
:^)

**Comment by kevinz000** [comment]
isnt this more of a consistency thing because I doubt there's other cases where an expendable material a borg starts out with has to be refilled from outside sources

**Comment by Anonus** [comment]
Engiborg welding fuel?

**Comment by WJohn** [comment]
Not sure if an oversight, so I won't be putting a bug/not a bug tag.

**Comment by AndroidSFV** [comment]
I coded it intentionally that borgs would need outside help to spam the place with photos, but I think its something that can be talked about changing.

**Comment by kevinz000** [comment]
I just don't feel potential harm in this, what harm could a borg do with photo spam? Lag?
Or maybe put a cooldown?
Main issue I'm annoyed at is having to have a player refill this for you. In fact, I wouldn't even complain about that if it didn't have a capacity of a measly 2 photos.
Engiborg welding tool = equip tool, make sure it's off, click tank
Camera film = Human pls put this in me (Not even sure if you need cover opened, I can't read code pls help)
