### ISSUE TITLE
Disc Station Cargo is awful

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#13072]
-The supply shuttle is airless and probably open to space because the thruster windows don't exist.
-You can't get crates out because of the lack of air causing space wind
-disposals ejectors spew trash out in the wrong direction
-There's a wall mounted radio in the mining dock under the window
-ore redemption takes ore from the wrong direction
-no QM office silver coin
-For such a gigantic highpop station, Disc Cargo is noticeably smaller then other stations, aside from the gigantic Delivery Office room
-There's a random toolbox embedded in a Delivery Office window
-QM office has too many doors, and one leads straight out to the main hallway
-Cargo completely lacks a maintenance entrance despite being adjacent to one.

Pretty awful.

**Comment by JJRcop** [comment]
@Strathcona

**Comment by JJRcop** [comment]
Also @YakumoChen there is a feedback thread for the map here:
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3871

Please use that next time

**Comment by Strathcona** [comment]
I'll check it out, thanks for the heads up.
