### ISSUE TITLE
Synthflesh kills you

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#13087]
if(iscarbon(M) && M.stat != DEAD)
		if(method in list(PATCH, TOUCH))
			M.adjustBruteLoss(1.25 * reac_volume)
			M.adjustFireLoss(1.25 * reac_volume)
			if(show_message)
				M << "<span class='danger'>You feel your burns and bruises healing! It stings like hell!</span>"

Hilarious but bad.

**Comment by Shapsy** [comment]
Tracked to the rebalance that Xhuis did in PR #13062
UNDOCUMENTED CHANGES HO

Also styptic/silver sulf/synthflesh now uses danger text for the "you feel your wounds healing" message, which is hardly fitting

**Comment by Iamgoofball** [comment]
# n i c e

**Comment by Anonus** [comment]
Well, it is dangerous because it's killing you~

**Comment by optimumtact** [comment]
I don't see what the problem is

**Comment by Iamgoofball** [comment]
saved us from having to balance it, I say it's fine as is
