### ISSUE TITLE
Engineering cyborg unable to refill cable coils

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#13086]
An engineering cyborg on Sybil was unable to refill the cable coil module from cable coils, maybe this has changed or something but it definitely used to be possible. It also had 250 floor tiles, dunno if that's supposed to be the case.

Replicated by spawning myself as a borg with the rudimentary transformation and then selecting the engineering module, using up all my coil with awful wire art, and then spawning a cable coil and trying to refill. Unsuccessful.

**Comment by Nitrousoxide** [comment]
does refilling via recharging work still?

**Comment by KorPhaeron** [comment]
You refill via charging, not a bug

**Comment by KorPhaeron** [comment]
@tkdrg

**Comment by tkdrg** [comment]
it's still possible with metal and stuff though, I think it's useful to refill faster than recharging
was it really supposed to remove this one
