### ISSUE TITLE
Space Hotel's APC is missing a terminal

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13082]
And therefore can't connect to the SMES/power the area properly

@MMMiracles since you seem to be updating away missions

**Comment by WJohn** [comment]
The APC should be making one automatically, that's odd.

You sure it's not the SMES that's missing one?

**Comment by tkdrg** [comment]
It really is the APC, the SMES looks fine. Even proccalling the APC to make_terminal() didn't work.

**Comment by WJohn** [comment]
Is the APC on plating? I've definitely seen APCs with terminals work just fine on MO19 and UO45, but those were placed over regular floors (that you had to crowbar to reveal). I wonder if it won't happen on plating or some other floor type.

**Comment by WJohn** [comment]
Oh, now that I took a look at it's really obvious:

The APC is in the wrong direction, it should be dir 1, not 2.

Easy-ass fix.
