### ISSUE TITLE
mounted chainsaws are deleted if the user is monkeyed

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#13092]
Pretty sure this happens because mounted chainsaws have the ABSTRACT flag. Removing it's not an option, since I believe that means if you get monkeyed it would drop the mounted chainsaw at your feet, which is never supposed to happen.

I'm not sure of any good way of fixing this short of spawning a chainsaw when a target is monkeyed and they're holding a mounted chainsaw, but I'm not certain how I'd do that.

**Comment by WJohn** [comment]
Similarly, being monkeyed while you're a space ninja will delete the ninja suit.

**Comment by PKPenguin321** [comment]
@Dorsisdwarf what disqualifies this as a bug
