### ISSUE TITLE
Alien queens sprite is so large that it cant attack people

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13094]
You cover them almost entirely if they're north of you, which can be an issue in maint when you cant circle to a better angle.

@Wjohnston

**Comment by Dorsisdwarf** [comment]
Unresolvable unless we go back to diddy queens or  wj does something incredibly clever

**Comment by Marflowerose** [comment]
Isn't there a cursor priority? Considering that xenos literally never need to touch themselves in any way, wouldn't it be better if their cursor prioritises in everything else aside from herself.

**Comment by WJohn** [comment]
Yes, this was a problem I knew we were gonna run into. I can't really think of any clever way to handle this outside of something like two separate sprites overlayed on top of eachother, the inner one being what you can click on and the outer one being the rest of the queen, and unclickable.

However, this is counterbalanced by tail swipe and the queen's huge health buff, she's still vastly more powerful than before.

**Comment by Marflowerose** [comment]
A more hasty fix could be to make xenos unable to click themselves, unless there is a legit reason for them to ever bite themselves.

**Comment by RemieRichards** [comment]
@Marflowerose not clicking yourself != clicking through yourself onto the enemy below
```mouse_opacity``` is universal, effects anyone who clicks you.

**Comment by duncathan** [comment]
>xenos literally never need to touch themselves

Uh wow kinkshaming much

**Comment by Dorsisdwarf** [comment]
I thought of a super-sneaky idea

Have the queen see herself as the old queen sprites.

boom

**Comment by Incoming5643** [comment]
Tactical alien queen asses

**Comment by Zilenan91** [comment]
@WJohn Queens may be better than they ever have been before, but it's inexcusable balance wise that they cannot fight if someone is above them, which is a hilariously easy place to get to if you're in maint, or literally anywhere else.

**Comment by PKPenguin321** [comment]
a really hacky fix would be making humans render one layer above the queen so they appear on top of her
>Have the queen see herself as the old queen sprites.

probably the best fix

**Comment by WJohn** [comment]
That'd be really really ugly, PK. She'd be under almost everything by comparison, it's why we raised both the queen and the praetorian's layers to 6 or so.

**Comment by PKPenguin321** [comment]
yeah i never said it was a good fix

**Comment by Lumipharon** [comment]
can't queens just tailswipe nerds next to them anyway?

**Comment by Zilenan91** [comment]
They can but then they just immediately run above them again and the same problem arises

**Comment by Lumipharon** [comment]
can't they neurocuck them?

**Comment by Zilenan91** [comment]
You can, but sometimes it's on cooldown.

Also, the fact that you literally can't hit people above you because your sprite is too huge is the problem here, not that yuo don't have ways to kill people.

**Comment by Lumipharon** [comment]
Well the obvious solution is to make the sprite normal sized, since mechanically it only occupies one tile, and everything in the game is designed around that.

The big sprite is nice, but it's not exactly practical.

**Comment by Nitrousoxide** [comment]
Can you make only objects on the tile north of her render on top of her?  That's the only one that has the issue, all the others are fine.

**Comment by PKPenguin321** [comment]
closed why

**Comment by KorPhaeron** [comment]
Never going to be fixed/impossible to fix

**Comment by PKPenguin321** [comment]
still a valid issue

**Comment by Lumipharon** [comment]
>impossible to fix

Reverting back to a normal sized sprite fixes it perfectly.
The new sprite is nice to look at, but it's clearly not practical. That means it's a simple choice. Practical sprite or pretty sprite.
