### ISSUE TITLE
Traitor panel runtime

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13109]
runtime error: Cannot read null.name
proc name: edit memory (/datum/mind/proc/edit_memory)
  source file: mind.dm,391
  usr: Violet Lotsu (/mob/dead/observer)
  src: Reese Diyu-Nailao-Marcotte (/datum/mind)
  usr.loc: the floor (105,69,1) (/turf/simulated/floor/plasteel)
  call stack:
Reese Diyu-Nailao-Marcotte (/datum/mind): edit memory()
/datum/admins (/datum/admins): Show Traitor Panel(Saiga Pi-Nailao-Niao (/mob/living/carbon/human))
/datum/admins (/datum/admins): Topic("_src_=holder;traitor=\[mob_89]", /list (/list))
Shadowlight213 (/client): Topic("_src_=holder;traitor=\[mob_89]", /list (/list), /datum/admins (/datum/admins))

Player used swap forms as a ling and the other player got kicked. Not sure if related.

**Comment by PKPenguin321** [comment]
related to #13107
