### ISSUE TITLE
Secret bar flooring

### ISSUE THREAD

**Issue by ChokinandTokin** [tgstation/-tg-station#13113]
Pulled up all the wood flooring, placed down metal tiles, and the broken wood tiles replaced the metal ones.

http://prntscr.com/94fnk3

**Comment by duncathan** [comment]
What map is this? It looks like meta to me but I haven't played on meta in quite some time

**Comment by WJohn** [comment]
Yeah definitely metastation.

**Comment by ChokinandTokin** [comment]
yessir

**Comment by Strathcona** [comment]
Probably caused by the wood tiles being sprite edited plassteel ones.

**Comment by Metacide** [comment]
Will look into, thanks

**Comment by MMMiracles** [comment]
This was already fixed pls close.
