### ISSUE TITLE
Bio Bags: Rapid Pick up

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#13127]
The rapid pick up feature does not work on the following items for the bio-hazard bags:

- Slime Extract
- Syringes
- blood bags

**Comment by Anonus** [comment]
What do all of these have in common gee I wonder.
They're all reagent containers.

**Comment by Fox-McCloud** [comment]
Actually, slime extracts aren't reagent containers, per se.

**Comment by tkdrg** [comment]
dupe of #13116 etc
