### ISSUE TITLE
Asteroid stations mine counts as part of the station

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13126]
Which is an issue for

1. Gangs. Good luck finding a dominator in Mine

2. Blob. Since its part of the station, you can grow safely in the mine/win without having to fight or even damage the station

More issues with this I'm sure.

**Comment by Anonus** [comment]
As a note, blob parts in space DO count for its win objective, it's just that never really comes up(I've never seen a blob lattice to the edge of the zlevel, then place a plating to burst on ever)

**Comment by Zilenan91** [comment]
A fix would be to make it so Blobs spreading over asteroid rock/space don't count for the objective, and making the Mine part of the Asteroid not able to be claimed by gang spray cans like we did for the Toxins Test Satelite.
