### ISSUE TITLE
White gloves have an entire tile's clickspace

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#13136]
Even if you hover over the area of the tile not covered by it, you will only be able to click the gloves instead. Possibly an issue with tranparent pixels around the icon.
Thanks TehWulfe for reporting this to me.

**Comment by Durkel** [comment]
This is happening to a couple items  actually, internal boxes come to mind.

**Comment by phil235** [comment]
Are you sure this happens to all white gloves and this doesn't come from the current bug with boxes and explosion?

**Comment by tkdrg** [comment]
I'm not aware of that bug, so no idea. I'd have to ask TehWulfe.

**Comment by phil235** [comment]
I couldn't reproduce on Box with any type of white gloves. It's definitely the aforementionned bug, not sure how to reproduce it but it used to happen when commiting suicide with an oxygen tank.

**Comment by Boredone** [comment]
I think I remember this, guy got blown up or something, and all his stuff covered the whole tile. 95% sure its the explosion bug thing.

**Comment by tkdrg** [comment]
Alright then, I'm closing this.
