### ISSUE TITLE
Genetics powers have a 100% manifest rate.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#13144]
Injectors at least, haven't tried the machine lately. Shouldn't have to state why this is bad.

**Comment by Zilenan91** [comment]
HHHHHHHHHHHHHHNNNNNGGGHHHHH

**Comment by Iamgoofball** [comment]
t   o   p
o
p

k   e   k
e
k

**Comment by Bluespace** [comment]
I'm unsure if this is true?
I played genetics yesterday and it wasn't the case.

**Comment by Durkel** [comment]
I dropped genetic Se's outside medical, at least 15 of them and every single one of them manifested at least hulk,dwarf, and cold resistance. Every power I activated and tested always appeared on the first injection. Either my rng was insane that round or it's 100%

**Comment by Bluespace** [comment]
http://puu.sh/luWdF/bdee2b7cc6.png
http://puu.sh/luWgu/3312b45a70.png

Note block 4.
I definitely think RNG on injectors has been increased however, but it's pretty nice, and goes a way to sorting out some genetics problems.

**Comment by Bluespace** [comment]
After extensive testing I can firmly say that it's definitely not 100%, HOWEVER, the manifestation rate for incredibly high values has been increased. Get an e00 and you get like a 50% chance, which is great.

**Comment by Dorsisdwarf** [comment]
Isn't this a feature from the whole temporary injector PR?

**Comment by KorPhaeron** [comment]
@dorisdwarf

That got reverted but the manifest chance didnt

**Comment by AnturK** [comment]
Someone botched up in that string of reverts and/or did the dumb thing and didn't use git functionality

**Comment by duncathan** [comment]
@AnturK

I only made the console name old injectors instead of the new ones you made. I didn't want to completely revert all your changes. Guess I must have missed the fact that you changed the old ones.

**Comment by AnturK** [comment]
I didn't really change old ones, just how console assigns the powers. Old ones transferred SE and that automatically called the power rolls. The timed ones transfer se and set forced mutation lists on the injector.

**Comment by Bluespace** [comment]
As probably the best geneticist on tg, I can say genetics is fine as is. 
If you're seeing hulk every round on everyone it's because I'm distributing it. 
Like 3 people, myself included, know how to break and power game genetics to get powers 10 minutes in. 
Genetics does not need to be reverted right now.

**Comment by Bluespace** [comment]
I suggest nerfing me instead because holy shit I am so obnoxiously lucky with hulk rng I keep cucking antags with mass hulk it's quite upsetting really.

**Comment by Zilenan91** [comment]
Even as a non-antag Hulk is really bad. No matter how much gear you have, sanic speed hulks just run up to you and keep slapping you in the dick until you die.
