### ISSUE TITLE
Transformation sting is still broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#13147]
https://github.com/tgstation/-tg-station/issues/11998, basically; as of a few days ago this is not actually fixed. What happens when you use transformation sting:

- The person you sting receives the appearance of the DNA you selected, but not their name.
- You receive the name of the DNA you selected, but not their appearance.
- You are promptly cremated because you suddenly have the name and voice of Greys-Her-Tide just as someone in the crowd became a lizard

since https://github.com/tgstation/-tg-station/pull/13138 is happening happening HAPPENING! this is the perfect time to fix this bug for good

**Comment by Profakos** [comment]
This seems to be just a one word fix. https://github.com/tgstation/-tg-station/blob/a0e0a50204b70048c1fc7d26d793c51fd0b70139/code/game/gamemodes/changeling/powers/tiny_prick.dm#L104 in this line, user.realname should be C.realname

**Comment by PKPenguin321** [comment]
i would fix this but i don't want to conflict with #13138
@Xhuis maybe you should look at this

**Comment by Xhuis** [comment]
Transform sting is being removed in the overhaul, so I guess that would work as a fix ._.

**Comment by PKPenguin321** [comment]
a temporary fix until your pr is merged might be good though
