### ISSUE TITLE
Mention-bot is fucking annoying

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#13142]
I've been auto-tagged in like five PRs SO FAR, IN ONE DAY, with nothing to do with me.

**Comment by duncathan** [comment]
So far it's been accurate with me

**Comment by duncathan** [comment]
Analysis of blame data indicates @bgobandit, @none, and @bgobandit as potential reviewers.

**Comment by ike709** [comment]
Why did you close this? I think it is pretty annoying too, and it doesn't even tag me.

**Comment by duncathan** [comment]
The issue tracker exists to inform contributors of issues that they may be able to fix. This issue is unresolvable by anyone except the head coder.
