### ISSUE TITLE
Lasers do no damage to wooden barricades.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13154]
What it says on the tin, I fired a bunch of lasers directly at one (clicking on it) and checked its health, didn't go down at all.

**Comment by phil235** [comment]
Apparently /obj/structure/barricade/wooden never had a bullet_act() proc ....

**Comment by octareenroon91** [comment]
I thought lasers went right through them

**Comment by phil235** [comment]
Projectiles have a chance to go through yeah, but the issue is that the barricade doesn't do anything when hit by the projectile, because it has no bullet_act() proc.
