### ISSUE TITLE
the supermatter sword

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#13170]
the supermatter sword that the wizard can buy

that is all

**Comment by daman997** [comment]
i concur

**Comment by Shapsy** [comment]
http://puu.sh/lvqoq/f9ef6c0904.png
The supermatter sword from an admin's point of view

**Comment by PKPenguin321** [comment]
not to mention the radiation pulse that has a range of the entire station and instantly KOs that can be used infinitely on anything

**Comment by Anonus** [comment]
It can even be used on space!
Yes, you can spamclick space and instakill everyone within 10 tiles of you.

**Comment by PKPenguin321** [comment]
you can even instakill the admin logs! wowie

**Comment by PKPenguin321** [comment]
this was pretty much fixed by #13175
although the issues with it spamming adminlogs still exists but whatever
