### ISSUE TITLE
HoG can possibly select Captain as a cultist at round start

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13177]
I heard people talking about this in OOC, and I'm not sure if it's true or not.

**Comment by tkdrg** [comment]
This was the case for a while, but it was supposed to be fixed with #13017
Please double-check with that person whether this is still happening as of the past week.

**Comment by WJohn** [comment]
Not sure if a bug or not.

**Comment by Dorsisdwarf** [comment]
Implanted people are never roundstart antags

**Comment by tkdrg** [comment]
It is a bug if it happens, which I honestly find unlikely unless I missed something really obvious here.

**Comment by PKPenguin321** [comment]
Wasn't this fixed?

**Comment by tkdrg** [comment]
i fixed this like twice, and hog is basically dead anyway
