### ISSUE TITLE
Sleeping Carp can't used ranged weaponry at all

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13182]
I got converted to the gang, and without even using one of the scrolls I was totally unable to use my pneumatic cannon.

**Comment by phil235** [comment]
This is intended afaik.

**Comment by Zilenan91** [comment]
From what I know, the coder of sleeping carp said that they need to use the scroll to gain any benefits/debuffs the carp gang gives. If regular gangers can't use ranged weapons then that explains why they never win.

**Comment by Lumipharon** [comment]
sleeping carp gang is awful as fuck.

Sure, if you can melee someone 10 times you can roundhouse kick their head off or whatever, but why bother with that when I can just 1 hit stun you with a baton, or better yet shoot you because I'm not a gimped gangster?

**Comment by Zilenan91** [comment]
Also this is a bug, because it's intended for you to use the carp scroll to gain the deflect and disuse of ranged weapons.

**Comment by Zilenan91** [comment]
@WJohn  ^^^

**Comment by Xhuis** [comment]
Intentional, not a bug.

**Comment by Zilenan91** [comment]
@Xhuis As I said above, it was intended for you to use the carp scroll to gain the buff of projectile deflect, and also the inability to use ranged weapons. This isn't intended behavior.

**Comment by Xhuis** [comment]
Yes, it is. Sleeping Carp are not meant to use ranged weapons even after conversion. I mean what I fucking say.

On an unrelated note, I don't have any problem with changing this. Go for it.

**Comment by duncathan** [comment]
Intended; feedback forum
