### ISSUE TITLE
EMHolo machines can be disassembled

### ISSUE THREAD

**Issue by matillo** [tgstation/-tg-station#13183]
Emergency Medical machines (Sleeper, Chem master) can be disassembled into real non-holographic parts. These can then be researched or reassembled elsewhere at no cost.

**Comment by Anonus** [comment]
@SuperSayu

**Comment by SuperSayu** [comment]
Okay uh that makes sense.  I guess the easiest way to deal with it would be a no-deconstruct flag.  I can get to that soon if nobody beats me to it.
