### ISSUE TITLE
Shadowling hatching doesn't work properly on space tiles

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#13185]
As in, walls don't appear on space tiles, the floor doesn't appear on space tiles, and the chrysalis in general does not have normal heat and pressure during the hatching.

**Comment by PKPenguin321** [comment]
hatching in space is a fucking horrible idea in the first place, if you do it at all you're fucked already
this isn't really an issue

**Comment by Steelpoint** [comment]
^ True but the game should not even allow you to do so in the first place.

**Comment by MMMiracles** [comment]
>hatching in space

the absolute madman
