### ISSUE TITLE
Buttons don't work in away missions.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13200]
Tested with shutter/blast door buttons, these don't work at all in away missions. Uses the same paths as the ones on station (though different IDs). Nothing happens when I use them. Yes, there was power in the areas for equipment, lighting, and environment, and I also tried it with an emag.

**Comment by MrStonedOne** [comment]
might be an issue with it not getting initialized right.

**Comment by KorPhaeron** [comment]
Anturk fixed this
