### ISSUE TITLE
Sending a pod to the asteroid is bugged as shit

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#13210]
What happened: Me, the captain and a couple other people are in the pod, en route to CentComm. Someone apparently sends the pod to the asteroid. The pod disappears, and everyone in the pod is ejected to the hyperspace area, where they near-instantly die. The hyperspace area arrives at the escape pod docking area like so:

![FUCK](http://i.imgur.com/e6sIsg9.png)

DEAD: Spike Christman says, "I was inside the pod"
DEAD: Spike Christman says, "some retard"
DEAD: Spike Christman says, "sent it to the mining"
DEAD: Spike Christman says, "asteroid"
DEAD: Simon Prevatt says, "makes sense."
DEAD: Christopher Evans says, "sorry"
DEAD: Spike Christman says, "obviously the pod dissapears"
DEAD: Spike Christman says, "Jesus man"
DEAD: ANOTHER WIZZY WUZZY RUND asks, "yeah, was it not supposed to?"
DEAD: Yeshua Ha-Nozri says, "the pod just disappears and the hyperspace tiles stay"
DEAD: Monty Todd says, "yeahhh kor broke something"

@KorPhaeron

**Comment by AnturK** [comment]
This is more of a feature request than issue but this should really send only one not all pods.

**Comment by KorPhaeron** [comment]
It only sends one.

I thought there was already a check to stop shuttles in transit from being sent but the escape pod transit is probably weird.

Easy fix though
