### ISSUE TITLE
You can bring the server to a standstill with containment fields

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13212]
If you leave a single tile of space between a containtment field and a wall/window, then put an object (lockers are good because no throwforce) in the gap, it will be thrown continously (without delay as far as I'm aware) generating a shit ton of sparks.

Throw needs a cooldown

**Comment by Durkel** [comment]
Could have sworn someone fixed this once, I remember this crashing the server years ago.

**Comment by phil235** [comment]
The loop is due to the fact that the field throws the object which hits and bounces off the wall pretty much intantly, pushing it and making it bump with the field again.

**Comment by Bluespace** [comment]
Containment fields throwing people is standard and pretty hilarious. I'd go with the half second cooldown. 
Nothing like a nuke op getting pinged into space off the field.

**Comment by Nitrousoxide** [comment]
Alternatively you could make it so all objects thrown by containment fields have a minimum throw force so they'll break the windows and stop the loop.

A cooldown would still leave an infinite loop of throws on objects with no throwforce.

**Comment by KorPhaeron** [comment]
@Nitrousoxide 

Okay but then what if a wall

**Comment by Nitrousoxide** [comment]
@KorPhaeron 

Hmm true.  Actually a cooldown would probably stop the infinite loop now that I think about it some more.  Since it'll have lost the movement when it bumps into the field.  Fields can't reflect like walls or windows right?  Unless there's something else there like a singulo there to keep pulling the object it shouldn't hit the field anymore.

**Comment by xxalpha** [comment]
Break the objects.

**Comment by Shadowlight213** [comment]
>priority high

**Comment by tkdrg** [comment]
I fixed this on #15338
