### ISSUE TITLE
Cult girders use the old deconstruction method.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#13222]
Normal girders are welder,wrench,screwdriver.

Cult girders are welder,wrench,welder.

Looks like oranges forget to change these when he changed the deconstruction method.

**Comment by PKPenguin321** [comment]
this isn't even the old deconstruction method, it's just a completely different one

**Comment by Durkel** [comment]
The method was changed to use the welder twice for a short period, people bitched and it was changed again.

**Comment by PKPenguin321** [comment]
oh yeah true
so this is the older-but-not-THE-old method
