### ISSUE TITLE
 Revenant blight spell illness resets mutantrace species colors

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13228]
The illness "Unnatural Wasting" changes a persons color var in its last stage to be a dark purple for a short time. When this is over the color is reset, but for mutant races that use colors its not reset to the actual normal color the character had, but rather to a different one (probably the default color for that race).

**Comment by Anonus** [comment]
If this happens, it also happens for the electrocution animation, because that's where I copypasted the code from.

**Comment by tkdrg** [comment]
It should be fine if you just store the old color in a var and then reset to that instead of using initial(color) or whatever.

**Comment by RemieRichards** [comment]
I suspect this is more to do with this being a virus that is cured, thus being deleted/losing it's ```affected_mob``` ref, that to do with my extra arguments in those mutant procs.

AND this was never reported with electrocution animations:
![liz](https://cloud.githubusercontent.com/assets/4043781/9305649/ebc45bd8-44ea-11e5-8a33-75390cfe9c0c.gif)

**Comment by Anonus** [comment]
Oh yeah that'd probably be it, I can fix this pretty easily.
