### ISSUE TITLE
Can't open PDA in lockers

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13233]
HELP: Cancer_Engine/(Farley McBlunderson) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): I found an interesting peculiarity that I think has something to do with the new byond version. the pda messenger won't open if you're in a locker

@MrStonedOne I guess

**Comment by tkdrg** [comment]
Works for me. Did he try using the PDA before the assets were sent (meaning, under one minute after logging in)? That would explain it.

**Comment by KorPhaeron** [comment]
As an update: you can use the PDA, but not the messenger

**Comment by tkdrg** [comment]
Oh I have an idea about what might be causing this then.
