### ISSUE TITLE
Ranged syndie mobs appear to auto-track projectiles

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#13240]
Is it just me or is their bullets TRACKING you?
On a gateway mission I was moving due to stimulents at the maximum speed possible for humans (pretty sure it was anyways) and I was teleporting when hit from reactive armor
I had 2 of the ranged syndicate mobs tracking me
All of their bullets hit. Even if I teleport 6 tiles perpendicular to the angle they shot it at, they still hit
What is up with that? That seems a bit overpowered as you can't dodge it and the only way to SURVIVE is it somehow close the distance (on the very open gateway map) and make it stop shooting or push something as a shield which doesn't work that well either.

**Comment by Dorsisdwarf** [comment]
I'm not aware of any way they could possibly be tracking you, but I will have a look when I get home tonight. Were they the hardsuit syndies or tacticool syndies, for future reference?

**Comment by KorPhaeron** [comment]
>Were they the hardsuit syndies or tacticool syndies

Same mob type, same code

**Comment by phil235** [comment]
>Is it just me or is their bullets TRACKING you?

Yup, https://github.com/tgstation/-tg-station/blob/50467f672b8d547c28583d3012b9832bd99dcce8/code/modules/mob/living/simple_animal/hostile/hostile.dm#L253
it should be current = get_turf(user)

**Comment by AnturK** [comment]
Simple mobs should all probably just use dumbfire kind projectiles.

**Comment by KorPhaeron** [comment]
Would they ever be able to hit anyone ever if they were firing at turfs? It's not like someone is going to code them to lead shots

**Comment by Zilenan91** [comment]
No wonder the C20 ones were so deadly fucking hell. The only way to fight them currently is to have a shield or hide around a wall so the bullets hit the wall.

**Comment by newfren** [comment]
Yo you just juice yourself up on styptic powder and epinephrine and they cannot kill you. Then once you kill one of them you steal their C20r and shoot the rest of them.

Styptic powder is still not very balanced.

**Comment by Bawhoppen** [comment]
is it me or do turrets also track you

**Comment by kevinz000** [comment]
Newfren. You can try doing that when there's 5 of them chasing you and see how well it turns out :^)
