### ISSUE TITLE
Hivelord Core Stabilizer missing sprite / doesn't work

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#13259]
Tried out new miner today and when I bought the thing, it lacked a sprite / was invisible. I could still have it in hand / in my bag. When I found a hivelord core, I tried to use the stabilizer on it to no effect. Had both in each hand, tried to use stabilizer on core, tried to use core on stabilizer, nothing worked.

**Comment by bgobandit** [comment]
HONK I KNEW I FORGOT A SPRITE BUT I COULDN'T REMEMBER WHICH

**Comment by Dorsisdwarf** [comment]
@bgobandit Honk
