### ISSUE TITLE
Lava burns things it shouldn't burn

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#13252]
Like jaunt holder objects and other effects, as well as things that shouldn't burn because they have a burn state of -1 THIS IS WHY THEY HAVE A BURN STATE OF -1 @KorPhaeron

**Comment by KorPhaeron** [comment]
It's really hot

**Comment by KorPhaeron** [comment]
In all seriousness I'm trying to think of the least ugly way to have actually fireproof things while still letting lava burn up mechs and lockers and the like

**Comment by Anonus** [comment]
`burn_state = -2` and tweaking the burn code slightly so that doesn't break anything(if it would break anything in the first place)

**Comment by KorPhaeron** [comment]
Should work I guess. I thought about that but was worried that I'd be in trouble for changing burn code in general just to work around one dumb turf.

**Comment by tkdrg** [comment]
lava is snowflake

**Comment by KorPhaeron** [comment]
I think lava is the opposite of snow

**Comment by Jalleo** [comment]
What about having a flag to have the object ignore the burn stuff entirely?

**Comment by tkdrg** [comment]
@KorPhaeron fix this

**Comment by KorPhaeron** [comment]
k
