### ISSUE TITLE
Lava can be burned/damaged to look like plating

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13256]
Reminder for myself to fix this

**Comment by tkdrg** [comment]
you can just override make_plating() to return
see engine floors, plating, etc

**Comment by KorPhaeron** [comment]
@tkdrg 

It doesn't turn into plating, it just gets a scorched plating sprite when damaged in blasts is all. It will still burn you to step on it.

**Comment by tkdrg** [comment]
override burn_tile() and break_tile() to return then
again, see engine turfs

**Comment by KorPhaeron** [comment]
@tkdrg 

Alright, thanks
