### ISSUE TITLE
AIs can jump to other AIs even if they're off-camera

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#13266]
This led to a situation where a malf AI was discovered and promptly killed because a newly-build AI was able to jump to it, even though it wasn't on cameras.

**Comment by Zilenan91** [comment]
Can we just remove our hide and seek gamemode

**Comment by PKPenguin321** [comment]
^

i think this is fine as a nonissue, AIs shouldnt be playing hide and seek anyways
that or make their core trackable with the pinpointer once the station goes delta

**Comment by Anonus** [comment]
AIs are always on camera because they have an inbuilt camera.

**Comment by GunHog** [comment]
Yet another reason why https://github.com/tgstation/-tg-station/pull/9360 was a bad idea. Makes AIs blind on shuttles, slow to update while the AI is moving, the AI cannot follow itself when being moved as a core, etc.

**Comment by Dorsisdwarf** [comment]
I told you guys it was a bad idea. I think.

**Comment by Shadowlight213** [comment]
:ok:

**Comment by Dorsisdwarf** [comment]
not a bug. Shitty balance, but not a bug.
