### ISSUE TITLE
Gateway doesn't require direct powernet power despite being hooked up to a node.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13272]
According to the pamphlet, and how it is mapped, the gateway should require power from the grid directly and apc power. However, it only seems to use the power from the apc.

**Comment by Bawhoppen** [comment]
its immersion~~~

nobody wanted to make an off sprite for it

**Comment by Shadowlight213** [comment]
@Bawhoppen that doesn't even make any sense. It still becomes unpowered if the APC is shut off.

**Comment by Bawhoppen** [comment]
oh
well rip
guess I'm wrong then
