### ISSUE TITLE
Slime People should be able to swap bodies in critical and when dead

### ISSUE THREAD

**Issue by julsruls** [tgstation/-tg-station#13270]
seriously, the whole point of splitting is to have a spare body to swap into, especially when slime people arnt really considered humans and can be fucked over by the ai at any time.

**Comment by PKPenguin321** [comment]
nah, them not being able to do this is intentional

**Comment by Dorsisdwarf** [comment]
Intended Feature

You have to jump before you get critted, thereby making you look like a dip who's lost all his items if they werent trying to kill you

will crush l8r

**Comment by Shadowlight213** [comment]
I ded pls buff.

**Comment by KorPhaeron** [comment]
@tkdrg

Kill

**Comment by tkdrg** [comment]
Yeah intended
