### ISSUE TITLE
There is no prompt that pAI personalities are available on actively searching pAI devices

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#13274]
I like downloading pAIs relatively often, and on occasion playing them, but it always feels like guesswork when one is ready to be downloaded.

Back when I played on /vg/ I'd get a prompt when I could download one, but I've never heard or seen the prompt on tg when I try for pAIs.

I rooted around the code and found that the code for the prompt exists in both, but I've never gotten it on tg before. Am I deaf / blind or is the proc simply not applying on tg?

**Comment by Jalleo** [comment]
Its how the feedback is given on very chatty rounds you wont see the notification in the chat window.

**Comment by newfren** [comment]
No I think it probably doesn't fire off Jalleo, I've used pAI a bunch and haven't seen a notification for them once, I end up just checking them every couple of minutes.

**Comment by Jalleo** [comment]
Where do you store your pAI?

**Comment by newfren** [comment]
Pockets and PDA.

**Comment by Jalleo** [comment]
@phil235 is a visible message noticeable from inside a pda? https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/game/objects/items/devices/paicard.dm#L130

**Comment by phil235** [comment]
@Jalleo No, it wont be noticeable (it's logical, nobody can see the pai screen flash if it's inside your pocket.
The solution would be to use audible_message() instead and change the text to say the Pai is making a sound for example.

**Comment by Jalleo** [comment]
Alright ill try out your suggestion later and pr a fix if it works.
