### ISSUE TITLE
You can create laser beams that are frozen in time using an emagged holodeck

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#13277]
Repro:
1. Emag the Holodeck console
2. Select Holdout Bunker
3. Turn the simulation off
4. GOTO 2
They're stackable and are actually capable of dealing damage

**Comment by phil235** [comment]
@SuperSayu

**Comment by SuperSayu** [comment]
I can look into it but it seems more like an issue with energy guns not sanitizing themselves on delete

**Comment by SuperSayu** [comment]
Yeah okay that's my fault.  Odd I didn't see it in testing.

The holodeck was tracking contents of spawned objects, and at the same time, when I derez an object I eject its contents so real things can't get deleted by putting them in a holobox.  But the actual energy projectile is stored in the ammo casing stored in the gun, so when the gun is created, the casing is tracked, and the projectile is ejected.

I will put a fix up shortly.

**Comment by Zilenan91** [comment]
This also happens with the atmos sim. It spawns a bunch of lasers frozen in the air that are supposed to light the fire.

**Comment by SuperSayu** [comment]
That is not how the atmos sim works

**Comment by Zilenan91** [comment]
It still spawns floating lasers for the atmos sim though.

**Comment by SuperSayu** [comment]
It spawns after the holdout ends, and they do not disappear because they are not tracked.  Jumping straight into atmos when no lasers are there should not create any.
