### ISSUE TITLE
Ghosts cannot read papers posted on noticeboards.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13273]
They can just examine the board and see that it IS a notice board, nothing else.

**Comment by WJohn** [comment]
Similarly they can't read the contents of a book or a folder or a bookcase or a ton of other things.

**Comment by neersighted** [comment]
NanoUI will fix this -- any NanoUI object can be interacted with by ghosts.
See #13348

**Comment by KorPhaeron** [comment]
@tkdrg

Neersighted allegedly fixed this and notabug

**Comment by tkdrg** [comment]
He didn't fix it yet but it will fix itself as soon as notice boards get nano. Workaround: spawn yourself and use invisimin.

**Comment by Shadowlight213** [comment]
Invisimin shows up on sec huds. Which really nerfs its usefulness.

**Comment by tkdrg** [comment]
16:01 < neersighted> all html UIs will eventually be tgui
16:01 < neersighted> pointless to have a bug FRing a specific interface
