### ISSUE TITLE
Corpse spawners don't set race properly

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#13284]
Setting the mob_species var doesn't seem to do anything as the corpses will still spawn as a human.

**Comment by KorPhaeron** [comment]
You have to set the var as /datum/species/skeleton or whatever, not "skeleton"

**Comment by KorPhaeron** [comment]
This isnt bugged

**Comment by MMMiracles** [comment]
probably should of been some side comment about that

**Comment by KorPhaeron** [comment]
(I just figured it out myself trying to fix it)

**Comment by KorPhaeron** [comment]
@MMMiracles 

You fixed this

**Comment by MMMiracles** [comment]
i forgot to link this with the pr

honk
