### ISSUE TITLE
Wizard Acadamy Wizards

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13294]
When they KO people with their fireballs, they don't keep hitting or shooting fireballs ot make sure they're dead.

Also there needs to be a medkit in the headmasters office because bleeding exists.

**Comment by GunHog** [comment]
That is normal NPC behavior.

**Comment by Zilenan91** [comment]
Yeah but they don't have any actual lethality when someone is in a firesuit. They just keep fireballing them and themselves until one or the other die. They need to keep shooting.
