### ISSUE TITLE
Revenant blight sometimes does nothing

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13307]
I was playing as a revenant and sometimes it would make people vomit up gallons, and other times do absolutely nothing.

**Comment by swankcookie** [comment]
increase toxin dealt by revblight, maybe?

**Comment by Zilenan91** [comment]
I guess, but for some reason it seemed to effect some people heavily and others almost not at all.

**Comment by tkdrg** [comment]
@Anonus

**Comment by tkdrg** [comment]
apparently this is intended
