### ISSUE TITLE
Shuttle launch sound plays even when the shuttle fails to launch

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13324]
Such as in rev

**Comment by Xhuis** [comment]
Intended. I figured that the engines would wind up automatically, then the shuttle's computer would receive the signal from Central Command not to launch which, in turn, wound down the engines.

**Comment by KorPhaeron** [comment]
@Xhuis 

I get the wind up noise, but it makes the launching boom noise as well. A stuttering shut down noise like the millenium falcon plays in the original trilogy when the hyperdrive fails would be cool.

Easiest solution would be to get @Cuboos to split the file into two parts, and only have the second part play if it actually goes.
