### ISSUE TITLE
If the singularity eats the gateway, you can still warp to it

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13325]
And you end up in nullspace

**Comment by swankcookie** [comment]
Like if you are on an away mission  and you warp back?

**Comment by KorPhaeron** [comment]
Yes

**Comment by duncathan** [comment]
Nullspace is not a fun time, folks

**Comment by Jalleo** [comment]
This is to do with qdel right?

**Comment by Shadowlight213** [comment]
The away gate should probably check for a non eaten station gate and automatically deactivate if the station gate is destroyed.

**Comment by PKPenguin321** [comment]
or or or
if the singulo hits a gateway it teleports through
:^)

**Comment by swankcookie** [comment]
i like this idea
