### ISSUE TITLE
MAXIMUM GAME BREAKING SERVER CRASH BUG

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#13349]
![incomingpls](http://puu.sh/lF68w/f955486c6b.jpg)

@Incoming5643 anyway to fix this?

**Comment by optimumtact** [comment]
@Cheridan @WJohn @Aranclanos @Jordie0608 @Razharas @duncathan

**Comment by Incoming5643** [comment]
unfortunatly, since : is a channel character, we can't really remove it from the filter. We could change the character used to use emoticons though?

How do you feel about *salt*?
