### ISSUE TITLE
Wooden barricades can be walked through, even though their density is 1.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13355]
What it says on the tin. This seems only to happen with spawned barricades and ones placed on the map, like on the hotel away mission.

Path is /obj/structure/barricade/wooden

**Comment by swankcookie** [comment]
I believe this has too do with canpass() being set to 0 in order to let bullets pass it, which, to be honest doesn't really even make sense too me. (https://github.com/tgstation/-tg-station/blob/a5f582a2ea987813730f8c67ab25f358976c9b7c/code/game/machinery/deployable.dm#L128)

**Comment by Anonus** [comment]
No, it's not that.
Presumably the bug is humans walking through barricades? If so, it's not a bug if they had the dwarfism mutation.

**Comment by WJohn** [comment]
Hm, perhaps its just a stroke of shitty mapping somewhere, it doesn't seem to be happening on other away missions.
