### ISSUE TITLE
Hitting Yes on the Are you sure you want to say this in OOC for the IC in OOC safety doesn't actually send the message to OOC 

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13353]
@Incoming5643

**Comment by Incoming5643** [comment]
It did locally, doesn't on live servers. Weird.

**Comment by MrStonedOne** [comment]
@Incoming5643 @Shadowlight213 

are you sure you hit yet. as in did you actually fucking read the button? or did you just assume the first button was yes?

**Comment by Incoming5643** [comment]
no it's not tha- ok it's that.

I just tested it on low pop sybil and it worked fine, even if other people used ooc in the middle. Either it's only a problem during high pop, or it'se not actually a problem at all.

**Comment by Shadowlight213** [comment]
That may have been what happened tbh.
Although I sweat I read the button and it said yes.
