### ISSUE TITLE
Pipenet Runtime

### ISSUE THREAD

**Issue by neersighted** [tgstation/-tg-station#13357]
```
runtime error: Cannot modify null.update.
proc name: update parents (/obj/machinery/atmospherics/components/proc/update_parents)
  source file: components_base.dm,157
  usr: null
  src: the Testing Lab air scrubber #... (/obj/machinery/atmospherics/components/unary/vent_scrubber)
  src.loc: the floor (162,155,1) (/turf/simulated/floor/plasteel)
  call stack:
the Testing Lab air scrubber #... (/obj/machinery/atmospherics/components/unary/vent_scrubber): update parents()
the Testing Lab air scrubber #... (/obj/machinery/atmospherics/components/unary/vent_scrubber): scrub(the floor (162,155,1) (/turf/simulated/floor/plasteel))
the Testing Lab air scrubber #... (/obj/machinery/atmospherics/components/unary/vent_scrubber): process atmos(0.5)
Air (/datum/subsystem/air): process atmos machinery()
Air (/datum/subsystem/air): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
```

**Comment by duncathan** [comment]
I know the round in question. This happened after the MC failed for some reason, and unfortunately the Testing Lab was destroyed before I could try to force a network rebuild to see if that fixed the problem. 
If anyone with +DEBUG sees this issue on live, call the `build_network()` proc of any of the things runtiming. That should fix it, but I can't be sure without a reliable way to reproduce this.

**Comment by Strathcona** [comment]
This has intermittently come up with the Bridge vent on DiscStation, maybe once every 10 rounds or so? I can't seem to fix it via mapping and it's only ever that one vent.

**Comment by duncathan** [comment]
Oh and this specific occurrence was on asteroid.

**Comment by tkdrg** [comment]
@duncathan is it safe to build_network() with SSair runnning? because stopping it is more trouble than it's worth

**Comment by duncathan** [comment]
@tkdrg yes, it's safe. The suggestion to turn off SSair was more me panicking trying to think of a solution than anything. 
There might be a slightly better way of going about it though; I'll check to make sure.

**Comment by securitycopper** [comment]
I can put in a null check to avoid the run-time error, but I don't know why the pipeline parent was null (PARENT_I)

@duncathan if your for the null check, I'll make a pull request.

**Comment by duncathan** [comment]
@securitycopper I'd rather it runtime tbh; the real problem is parent being null, not the runtime itself
