### ISSUE TITLE
Safeties overload make bots unresponsive

### ISSUE THREAD

**Issue by Sligneris** [tgstation/-tg-station#13363]
When an AI overloads a bot's safeties, the bot becomes unresponsive, making it impossible to change its settings.

That's proper behavior if the safeties are removed by a crewmember with an emag, but it shouldn't happen when the AI does it.

**Comment by tkdrg** [comment]
@AnturK

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/bot/bot.dm#L764

That should be `if(!hacked)`

If Anturk does not catch it, I will when I make my Diagnostic HUD PR.
