### ISSUE TITLE
Mindswap event works incorrectly if you are in critical

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#13372]
You switch bodies, but you stay in critical even if the target body's health was above the crit level. I was lying down on the floor and the target was a braindead engineer inside a locker, if it matters. @Incoming5643 I guess

**Comment by Incoming5643** [comment]
Crit status is ALL body... I hope. I don't understand how this could be possible. I don't think crit people are supposed to be swapping either. This seems all sorts of weird, let me look into it.
