### ISSUE TITLE
Chest augmentation removes person's heart; can't defib them as a result

### ISSUE THREAD

**Issue by Deputi** [tgstation/-tg-station#13379]
I wanted to live out my Deus Ex fantasy by augmenting dead people with heavily damaged bodies and defibbing them back to life, but I noticed that augmenting the chest removes their heart so they can't be defibbed. You can get around this by augmenting the limbs other than the chest, but it doesn't feel as good as rebuilding their entire body. I think one way to fix this would be to have augmented chests retain their heart or have a mechanical heart that can still be defibbed.

**Comment by Incoming5643** [comment]
Honestly, this seems intentional. That said an alternate way of jumpstarting aug people could be fun.

**Comment by Deputi** [comment]
Yea, there should be a way to revive augmented people. I just think the easiest way would be to not have their heart fall out when doing chest augmentation.

**Comment by PKPenguin321** [comment]
>Honestly, this seems intentional. That said an alternate way of jumpstarting aug people could be fun.

jumper cables when

**Comment by WJohn** [comment]
Not sure whether to label this as a bug or not.

**Comment by Firecage** [comment]
Why not both?

**Comment by Firecage** [comment]
Why not both?

**Comment by Zilenan91** [comment]
It's probably a bug, I doubt it's intentional they can't be defibbed.

**Comment by Dorsisdwarf** [comment]
It's not a bug that their heart is removed. It's shitty balance though

**Comment by GunHog** [comment]
It should not be possible to survive without a heart unless you are also an aug, but I suppose that would cause issues with Abductors, if they remove the heart and fail to place one of their synthetic organs, and then chest augs would have to add a new robot heart.

**Comment by tkdrg** [comment]
Why would a defib work if you have no heart? Not an issue as far as I'm concerned.
