### ISSUE TITLE
Snowman outfit sprite is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13371]
What it says on the tin, it has the green SUIT tag in the top right as opposed to any actual sprite.

**Comment by PKPenguin321** [comment]
@swankcookie i thought you fixed this already

**Comment by swankcookie** [comment]
i did. ill take a look

**Comment by swankcookie** [comment]
@WJohn its just the suit, right?

**Comment by swankcookie** [comment]
So it looks like someone's PR in the last week got rid of it. the mob sprite is there in the branch that got merged, but it's not there now. So someone else deleted it. Sabotage...

**Comment by Dorsisdwarf** [comment]
Sounds like someone merged a merge conflict

**Comment by Dorsisdwarf** [comment]
Whoops

**Comment by swankcookie** [comment]
@Dorsisdwarf want me to just make a PR of just the sprite?

**Comment by Jordie0608** [comment]
I'll fix this as part of #13326 while I'm already resolving merge conflicts there
