### ISSUE TITLE
Button/door ID not linking during game

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#13389]
I can't seem to link buttons and shutters/blastdoors via VV

Process:
Spawn shutter
spawn door button
VV button and shutter ID to a number i.e. 151
Press button. Nothing.

**Comment by tkdrg** [comment]
Well yeah, of course it wouldn't work. They don't check for the ID whenever you use them, they just use the ID to find an assembly and link to it. If you want it to work, you should mark the shutter (dropdown menu -> mark datum), then VV the button's device var to the shutter.

**Comment by peoplearestrange** [comment]
What about blast and rolling shutters? There are no assemblies for those.

**Comment by tkdrg** [comment]
I'm not sure. Antur is making these easier to use, either way, so it's a moot point.
