### ISSUE TITLE
Guys not everything needs a changelog entry

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13382]
It's great everyone's on board with the easy changelog generation, but I'm seeing a lot of really tiny things getting log entries, or relatively minor things getting multiple log entries. 

It's great folks want to keep the playerbase abreast of changes, but if the log is full of: 

<b>*bugfix: changed a pixel on a admin only clothing item*</b> 

then the substantial changes can get buried in a log that's too long for most people's attention spans.

**Comment by Anonus** [comment]
:cl: Joan
rscadd: Changelog entries.
/:cl:

**Comment by Jordie0608** [comment]
Why would you make this an issue report

**Comment by Incoming5643** [comment]
So I can point to it later condescendingly.

**Comment by Incoming5643** [comment]
T H E  P R O P H E C Y
