### ISSUE TITLE
Styptic Powder patches don't immediately heal brute wounds

### ISSUE THREAD

**Issue by Chronitonity** [tgstation/-tg-station#13397]
https://github.com/tgstation/-tg-station/blob/953becdfdc6171fabccb3ab86d1bc7cbae5b551c/code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm#L210

should be getBruteLoss, not getFireLoss

**Comment by Zilenan91** [comment]
I was wondering why the brute patches in the brute kits didn't heal me immediately.

**Comment by Iamgoofball** [comment]
HOW DID THIS GO UNREPORTED FOR SO LONG, FUCK
