### ISSUE TITLE
Repairing windows doesn't seem to work

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#13418]
You hit the window with the welding tool instead.
@SuperSayu

**Comment by duncathan** [comment]
Did you make sure you were on help intent? AFAIK it doesn't work otherwise.

**Comment by Anonus** [comment]
I was a drone, so yes I was on help intent. Also, the progress bar and "you start repairing the window" message both appeared.

**Comment by bgobandit** [comment]
confirmed, this isn't just drones either.

**Comment by SuperSayu** [comment]
I think it isn't so much that you don't repair it, as you just hit it again
with the tool afterwards.  I will fix it later.
