### ISSUE TITLE
Clicking on a bot as cyborg from afar causes you to punch them if harm intent is on.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#13415]
From ktccd|codern00b in #coderbus
>coderbus, I got literally seconds before I gotta leave for a lecture, so here goes: The new bots, at least medibot, can be hit from a distance by cyborgs! I tried clicking on it to change it's patrol, but I ended up hitting it since I had harm-intent. But I was in another room when I did it!

**Comment by AnturK** [comment]
Will fix in a moment.
