### ISSUE TITLE
Asteroid walls leave fully-aired asteroid tiles behind

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#13423]
I think the path you were looking for was /plating/asteroid/airless , rather than /plating/asteroid

@KorPhaeron

**Comment by KorPhaeron** [comment]
@dorisdwarf

I thought new turfs copied the air around them?

Easy enough fix if not

**Comment by Dorsisdwarf** [comment]
This is pretty much certain to be the problem. The static mapped areas of the roid and the secret rooms both use /airless. We had the asteroid at 70kpa a few rounds back.
