### ISSUE TITLE
Smooth lava isn't smoothing

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/-tg-station#13421]
http://puu.sh/lHKaa/5710ba10ad.png
See screenshot

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Won't be home for a bit, but in the meatime, does it smooth when placed up against normal metal walls? I think setting it to smooth with walls was how I broke it, because it worked testing.

**Comment by Thunder12345** [comment]
Hold on, checking

**Comment by Thunder12345** [comment]
Yeah, smooths with regular walls, and nothing else, not rwalls, not rusty walls

**Comment by Thunder12345** [comment]
And while you're at it, why does smooth lava have plating as its default baseturf?

**Comment by KorPhaeron** [comment]
Alright so the issue is I set smoothing to true, and without a list of what it smoothed with, it defaulted to smoothing with itself. Forgot to add it to the list once I added walls (which overrode the default)

And are you sure the baseturf is actually plating and not just bugging out icon wise?

**Comment by Thunder12345** [comment]
Didn't remember to check the vars, but it was definitely regular plating, not the honk plating of a missing sprite
