### ISSUE TITLE
Grilles don't protect solars at all from space dust.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13441]
![](http://i.imgur.com/LlgRIDm.png)

What it says on the tin. That's a sad display of defense. That was 15 grilles it chewed through without any trouble.

**Comment by Supermichael777** [comment]
grills are for shocking those ignorant of throw damage and making windows look good. TBH those grills are for navigation/aesthetics anyway.

**Comment by Jalleo** [comment]
It was actually done to defend the solars from requiring repair when we werent able to repair them.
Solution to this is add a way for engineers to more efficently repair the solars and add more glass and metal supplies.

**Comment by AlexanderUlanH** [comment]
Their aesthetic comes from the fact that it seems like they have a purpose.
It makes sense that grilles would offer some protection from space dust anyway.

**Comment by Bawhoppen** [comment]
What do you think kicked up that sand and dust. Just think about it.

**Comment by Dorsisdwarf** [comment]
Grilles arent meant to stop spacedust, they're there to look cool, IIRC

**Comment by Jalleo** [comment]
@Dorsisdwarf wrong i remember from ages ago that it was done to protect solars lemme try to find the PR about solar panels.

**Comment by Jalleo** [comment]
Part one here lemme find info that grilles were placed to defend solar panels https://www.theforgottenzone.com/hosted/archive/tgss13/viewtopic.php?f=7&t=7393&p=82485&hilit=solar+panel#p82479

**Comment by WJohn** [comment]
Yeah that's what I thought was the intent, and it's why we have grilles on top of our huge atmos tanks outside atmospherics. If it can't do that, then why have those there at all?

**Comment by WJohn** [comment]
This wasn't fixed, by the way. Still happening:

![](http://i.imgur.com/9YKAUbK.png)

**Comment by Bawhoppen** [comment]
we agreed on another PR this was intended
