### ISSUE TITLE
Nano UI is not potato computer compatible

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13460]
![d10_icon](https://cloud.githubusercontent.com/assets/4176358/11606326/2ca3310a-9aeb-11e5-8c39-6327a312f2dc.png)

One of the great things about SS13 is that it can be run on machines that are absolutely not suited for gaming. Calling out for all the spessmen with poverty tier computers here. It stings pretty bad that some people are probably getting shut out of a fairly critical part of the game due to this. 

Is there anything that can be done to give the affected people some sort of fallback for these things, even if it doesn't look quite so slick?

**Comment by tkdrg** [comment]
@neersighted

**Comment by ike709** [comment]
People still use XP/Vista...? Why?

**Comment by Jordie0608** [comment]
Since BYOND doesn't track it we pulled stats from the website as a vague indication of the server's population. Less than 3% of users have a pre-7 windows environment. I wouldn't consider this much of a concern.

**Comment by Iamgoofball** [comment]
it's 2015, nearing 2016

if you literally can't afford to upgrade from XP then ffs 
![emot-filez](https://cloud.githubusercontent.com/assets/4081722/11606535/bc37dfee-9ad9-11e5-86e7-03d1b87c5ca2.gif)

**Comment by Incoming5643** [comment]
How does this impact people running a non-windows OS?

**Comment by Iamgoofball** [comment]
mac players aren't a thing because BYOND flat out doesn't work in wine on there and linux players probably can either 1. dualboot ![emot-filez](https://cloud.githubusercontent.com/assets/4081722/11606542/15e45d24-9ada-11e5-802a-bea4d58fe345.gif) or 2. do wine magick with their neckbeards to get it working

**Comment by tkdrg** [comment]
wine can't run IE9+ consistently, so this means it becomes basically unplayable on linux

**Comment by Firecage** [comment]
Soo....An update is made which exludes people who have pre-Win7, or a non-windows OS, and it apparently isn't a concern. And it also requires the worst browser there is...

**Comment by Jordie0608** [comment]
@Firecage BYOND isn't supported on Linux or Mac and thus neither is SS13. IE is the native browser that BYOND uses, we can't change that. The percentage of our population that demographic covers however is very small.

**Comment by Lo6a4evskiy** [comment]
Well I have IE 9 and I cannot update it. NanoUI seems to work though, tried cryo and suit sensor monitor, also locked APCs and air alarms. What exactly does this add to the functionality to warrant such restrictions though?

**Comment by Iamgoofball** [comment]
@Firecage jesus fucking christ did you completely blot out from your memory the spot where we said "you dont have to use IE you nerd, you just need it installed and updated for BYOND to hook into" in the IRC

**Comment by tkdrg** [comment]
embedded IE is the default HTML renderer for windows applications, almost all games use it. you just don't notice it most of the time. I dislike this change because I was on that "very small percentage" of yours, but since apparently people don't mind this I have no choice.

**Comment by tkdrg** [comment]
we tested this on #coderbus and apparently this fixed itself at some point. i guess this can be closed, ill ask someone to remove the motd later if i remember

**Comment by Iamgoofball** [comment]
What are your computer specs?

**Comment by JJRcop** [comment]
Is this an issue in the webclient?

**Comment by neersighted** [comment]
The MOTD was just @KorPhaeron flipping out. NanoUI /sort of/ works on old versions of IE. However, I am currently rewriting the frontend to use modern Javascript and still be backwards compatible (polyfills), so please hold on for that. I'll close this issue once the rewrite drops.

**Comment by KorPhaeron** [comment]
I was asked to put the motd up by @tkdrg, please dont accuse me of flipping out

**Comment by tkdrg** [comment]
it's true, i had multiple reports of it being broken so i asked kor to add it

**Comment by neersighted** [comment]
Its okay @KorPhaeron we :heart: you.
