### ISSUE TITLE
No clear way to unbuckle simple-animal bots.

### ISSUE THREAD

**Issue by octareenroon91** [tgstation/-tg-station#13466]
Get a medibot.
Get a secway or other chair.
Buckle the medibot to it.
Now what?

**Comment by newfren** [comment]
Can you click the chair to unbuckle it? That's how you do it for most shit.

**Comment by tkdrg** [comment]
@AnturK i guess

**Comment by AnturK** [comment]
What's exactly is the issue here? This is consistent with all other simple animals/humans.

**Comment by WJohn** [comment]
Yeah you can just unbuckle it like everything else by clicking on the chair. This is perfectly normal.
