### ISSUE TITLE
RPD can be used to make infinite obstacles for no cost

### ISSUE THREAD

**Issue by Deputi** [tgstation/-tg-station#13473]
A gang used this to stump the crew for 800 seconds.
![sybil expensive station x-ray 2015-12-06 020550](https://cloud.githubusercontent.com/assets/4474395/11612194/9cf017f6-9bbe-11e5-96aa-72e70ad5dd94.png)
pls nerf

**Comment by MMMiracles** [comment]
balanced.

**Comment by Zilenan91** [comment]
Holy shit. Now THIS is pod racing

**Comment by Supermichael777** [comment]
it realy needs a metal/cmc cost.
seriously.

**Comment by PKPenguin321** [comment]
top fucking kek

**Comment by MMMiracles** [comment]
@Zilenan91 
You can only wrench bins down if there's a trunk under it, so no.

**Comment by Shadowlight213** [comment]
Maybe make bins not dense while not wrenched down? Fixing the atmos network for an area requires a LOT of pipes. Making pipes require metal cost would make the RPD almost useless.

**Comment by Lumipharon** [comment]
Just make all that shit non dense until wrenched down.
Seems the simplest way to resolve this.

**Comment by octareenroon91** [comment]
Dense unwrenched bins make building more complicated, too.

The one counter to this tactic would be another RPD on 'eat pipes', I imagine?

**Comment by AlexanderUlanH** [comment]
Why not just remove bins/chutes from the RPD?  Those aren't needed for most repairs, and at most you'll need one or two, so you can just grab one from the full-size dispenser.

**Comment by Shadowlight213** [comment]
^ that would work well. You don't need a large number of bins

**Comment by MMMiracles** [comment]
Good luck setting up public disposal traps when having to lug around chutes or the dispenser itself.

Just make them non-dense.

**Comment by Zilenan91** [comment]
How would them being non-dense work? People could just walk right over them right?

**Comment by PKPenguin321** [comment]
until they're wrenched down, yeah

**Comment by octareenroon91** [comment]
I submit that this was probably an unintended consequence from some other code changes.  Note the repathing in c853ec49a95969b8ab6942df949217cd84537e01 for example

**Comment by duncathan** [comment]
@octareenroon91 yeah, this is an unintended consequence of the RPD being able to make disposals pipes. that commit you linked is completely irrelevant.
