### ISSUE TITLE
Beepsky acts like aq sec headset

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#13471]
you can hear the sec channel standing next to him.
This is bad

**Comment by swankcookie** [comment]
rsadd: beepsky is now a radio station.

**Comment by tkdrg** [comment]
@AnturK

**Comment by bgobandit** [comment]
this is actually the case for ANYONE with the sec headset, including secborgs and officers/captains/etc

**Comment by MightyRadcon** [comment]
Is there a reason beepsky needs a sec radio built in?
