### ISSUE TITLE
You can't load 4.6x30mm bullets back into wt550 magazines.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13477]
I'm doubtful that this is intended, but it's inconsistent with every other magazine in the game.

Also can we get rid of 4.6x30mm and put it back to 9mm? It's identical to 9mm with the express purpose of not being printable. You need to have an auto rifle in the first place, and people NEVER order these things.

**Comment by Zilenan91** [comment]
Yeah why did we remove them needing 9mm, all it did was make them a complete pain in the ass to put to use.

**Comment by Shapsy** [comment]
Because being able to print out near infinite amounts of ammo was ridiculous, and since someone refused to just remove the autorifles completely, we were left with what we have now

**Comment by WJohn** [comment]
Also, if we DO leave being unable to load bullets back into these magazines, it should be made abundantly clear that they cannot be loaded in. That way we can have em use 9mm and still prevent you from slamming infinite amounts back in.

**Comment by Zilenan91** [comment]
@Shapsy But cargonians can already order combat shotguns and have bandoliers full of ammo in their backpack full of shotgun slugs, how is this any different with auto rifles?

**Comment by Shapsy** [comment]
A bandolier holds 7 shotgun shells and is a normal sized item and has to be loaded one at a time, an ammo box is a small item that holds 20 rounds and can top off a magazine with three clicks

**Comment by Zilenan91** [comment]
Then nerf the gun, not make it a pain in the ass to use the gun.

**Comment by Dorsisdwarf** [comment]
Steelpoint refused

**Comment by Bawhoppen** [comment]
I'd argue that it wouldn't be OP anymore even if we did make it into a standard ammo type again, 

main reason it was OP in the first place was because you got like 4 for free in armory roundstart, now you need to order from cargo

**Comment by Iamgoofball** [comment]
This reminds me, we need to change shotguns to make ammo come in shell boxes and load them in by clicking on the gun with the box

if you say "muh skill based nerfs" then I say **fuck you im doing it anyways**

**Comment by Zilenan91** [comment]
Please make shotgun slugs come in boxes. It's so fucking annoying as a bartender having to waste your internal box space on ammo. Would be really nice if the bartender had a box of beanbags in the back rather than the ones in his inventory to help with late-joiners and inventory conservation.

**Comment by Iamgoofball** [comment]
That'd be the plan, prespawned ammo and autolathe shells on the station would come in boxes instead of strewn about, and clicking on the shotgun with the box loads the shells in.

**Comment by Zilenan91** [comment]
If possible, can you also make it so the double barreled auto-ejects shells or would that be out of the scope of that pr?

**Comment by Bawhoppen** [comment]
@Zilenan91 having it auto-eject would be dumb and would be for it's own PR I guess considering this isn't even a PR

**Comment by Zilenan91** [comment]
yeah that is pretty dumb thinking back on it
