### ISSUE TITLE
Denial of Service via completed_asset_jobs topic calls 

### ISSUE THREAD

**Issue by Chnkr** [tgstation/-tg-station#13481]
You can manually call the [asset_cache_confirm_arrival topic](https://github.com/tgstation/-tg-station/blob/2f0a221c8c822ae77487bcf4d377e054d81727d9/code/modules/client/client%20procs.dm#L25), to insert new items into the [completed_asset_jobs list](https://github.com/tgstation/-tg-station/blob/a6304bc60ae5549654e5ab95cc5c9388224dc8db/code/modules/client/asset_cache.dm#L25) which resides inside the client datum.

list insertions, modifications, and removals are godawful, and thus allow any potential attacker to completely grind the server to a stopping halt by repeatedly calling the [asset_cache_confirm_arrival topic](https://github.com/tgstation/-tg-station/blob/2f0a221c8c822ae77487bcf4d377e054d81727d9/code/modules/client/client%20procs.dm#L25) using one, or more clients.

**Comment by MrStonedOne** [comment]
literally anything can be ddos'ed via topic.


Also, list insertions aren't expensive only |= is, += isn't.

**Comment by Chnkr** [comment]
Yeah, after a short discussion on IRC, it's just me being a idiot.
