### ISSUE TITLE
Syndicate Turrets are literally unkillable

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#13498]
The defense turrets on the syndicate shuttle, even if you manage to 'break' it, will keep tracking and shooting targets.

The variables showed the broken turrets that were still firing at 0 HP so that probably isn't intended.

**Comment by optimumtact** [comment]
Don't go near it then

**Comment by MMMiracles** [comment]
yeah but they aren't meant solely for the op shuttle so go away tangerine.
