### ISSUE TITLE
Booze and Soda Dispensers now dispense in fucking annoying amounts.

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#13508]
The addition of the 25u dose is nice, the removal of literally everything but that, 10u, and 5u is not.

Please add back 20 30 and 50 doses to the bar machine because it's suffering trying to brew a lot of drinks now.

Leave the 25 though because that makes a few of them a lot easier - basically the ones that are mixed in multiples of 4.

**Comment by duncathan** [comment]
@neersighted

**Comment by neersighted** [comment]
@newfren, this is a side effect of making dispense amounts dependent on the reagent container. I can alter the reagent dispense amounts of glasses and the like.

**Comment by newfren** [comment]
If that makes them easier to brew again then yes, please do that.
