### ISSUE TITLE
Air alarms will sometimes not update their icons when changing alert levels

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13531]
This seems to happen much more often when air levels return to normal. Most air alarms in a room will not update their icons from flashing red or yellow, while the interface reports all green.

**Comment by tkdrg** [comment]
@neersighted maybe

**Comment by Shadowlight213** [comment]
@tkdrg this was a bug long before NanoUI air alarms.

**Comment by neersighted** [comment]
Probably a missing update_icon() call in the radio code.

**Comment by tkdrg** [comment]
neer fixed this apparently
