### ISSUE TITLE
beer-goggles, armor, and beanbags don't spawn in the bar backroom

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13536]
Quite a problem for late-joining bartenders being without everything they need but their gun (which probably got stolen by the clown by that point)

**Comment by newfren** [comment]
Don't late join bartenders have armour and sunglasses on them when they spawn in?

**Comment by Zilenan91** [comment]
@newfren From what I remember, no.

**Comment by newfren** [comment]
I just tested this and they do in fact spawn in with armour, beer goggles, and 4 beanbag slugs.

**Comment by Zilenan91** [comment]
Wait what, they didn't do that a few weeks ago, I wonder if that got snuck in as part of a stealth change or something.

To be fair though, the problem still persists if someone that's not the bartender transfers over to the job and is without any of the gear, so this still merits fixing

**Comment by newfren** [comment]
It probably merits a spare pair of sunglasses spawning in the back but I really don't see the rest of that being necessary for people transferring into bartender.

**Comment by Zilenan91** [comment]
The armor is actually very necessary. Depending on the time of day, you're either gonna get no bar fights, or a retarded amount of them. One round I remember had so many bar fights that I had alcohol on me from bottle-smashing all the way to centcom. I killed like 7 people, so many to the point that greyshirts started setting up a ring of tables so people could fight me. Eventually got robusted by an assistant with those dank one-hit KO's, and the armor carried the fuck out of me. Great round.

Sorry for going off on that tangent, but they really do need the armor. The beanbags they can get from cargo so those aren't really necessary.

**Comment by Dorsisdwarf** [comment]
If a bartender transfer needs a vest, he can get it from sec / the HOP / the detective / cargo

**Comment by Zilenan91** [comment]
Yeah that's what I always do, but there are times when there's no sec, sec doesn't listen, or they're all dead. It isn't that big of a problem tho tbh
