### ISSUE TITLE
space battle away mission misc small issues 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13548]
(the one with the artillery in case I'm wrong about the name) 

at the syndie dropships, there is bloodred suits + helmets, even though the helmets are integrated into the suit now, I believe if you pick these up you can never drop them again
same thing with some engineer hardsuits in the ship

around the ship there are bullet casings and shotgun slugs but they're not actually spent like they should

there is a misplaced untextured tile on one of the dropships aswell

also its a really shit away mission holy FUCK

**Comment by WJohn** [comment]
I swear that first point was fixed.

Also almost all away missions are absolute shit.

**Comment by Bawhoppen** [comment]
I think you fixed it on one of the ships, but not all of them

**Comment by Shadowlight213** [comment]
Reee I spent like half an hour fixing those tile sprites when I was fixing away missions since I didn't realize I could do it easier in notepad.
