### ISSUE TITLE
Entering the gateway should immobilize you for a moment, to prevent you from instantly going through it again.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13545]
What it says on the tin, it's very easy to accidentally jump back into the mission when you didn't mean to because you moved one tile too many.

**Comment by Supermichael777** [comment]
The clown: HONK *SHOVE*

**Comment by xxalpha** [comment]
This is a duplicate issue.

**Comment by CosmicScientist** [comment]
Of which one @xxalpha?

**Comment by tkdrg** [comment]
Dupe of #2717

**Comment by Dorsisdwarf** [comment]
#CRUSHED#
