### ISSUE TITLE
Anti-ick in ock filter switch the spots where the yes/no options are

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13549]
There is a longheld precedent of YES being on the left, and NO being on the right, lets change it before it gets too ingrained so we can have some consistency
also for new players

**Comment by Incoming5643** [comment]
intentional. It's so people who mash the prompt don't just send it anyways.

Actually if anything swapping all the other filters to how i-cooc does it might be better, it'd solve some issues about accidentally agreeing to roles and such.

**Comment by Bawhoppen** [comment]
I realised it was intentional, but I would argue that it would still be better to have it be consistent with other prompts aswell as just in general about how humans look at something like that.

**Comment by PKPenguin321** [comment]
not an issue at all

**Comment by Bawhoppen** [comment]
maybe you think so, but I actually play the game

**Comment by Bawhoppen** [comment]
wait shit wrong issue i meant to reply to FUCK

**Comment by PKPenguin321** [comment]
oh boy oh boy somebody's accused me of not actually playing for the first time
i've been waiting for this

**Comment by Bawhoppen** [comment]
i said it was a reply to the wrong issue without reading and just clicking in my email

**Comment by Incoming5643** [comment]
don't take this moment from him, he's so excited.

**Comment by Shadowlight213** [comment]
The filter should be less agressive and more specific. Maybe limit it to only activating if it detects channel prefixes after a player types :
Keep the current detection for ;

**Comment by Incoming5643** [comment]
The thing about more specificity in the check is that every OOC message in the game has to go through those checks,so I kept the checks down as much as possible to reduce the workload. How many messages do you start with a `:` that aren't emoji (which is handled).

**Comment by Shadowlight213** [comment]
@incoming5643
>what other messages do you use

:^)  :^D 
I sometimes forget coders don't play. Honk.

**Comment by Incoming5643** [comment]
but those are emoji.

They just aren't <b>supported emoji</b>

**Comment by RemieRichards** [comment]
@Incoming5643 false, those are emoticons.
emoji are singular characters, emo coming from emotion, "ji" meaning character or letter in Japanese.

**Comment by Incoming5643** [comment]
;◎ܫ◎

**Comment by Bawhoppen** [comment]
Why don't we make a pref toggle for it? This will prevent new players doing it but not annoy the vets who have played eyars without it.

**Comment by Shadowlight213** [comment]
@bawhoppen good plan. As an added bonues, IC ooc will now be a month ban! Turn the pref off at your own peril.

**Comment by Iamgoofball** [comment]
there is a long held precedent in UI design that states that if there is a popup yes/no box, and if hitting yes will potentially cause problems, that the yes and no will be swapped from their default positions so that muscle memory responses dont cause problems.

**Comment by duncathan** [comment]
Yeah this is a good thing, not a bad thing

**Comment by Bawhoppen** [comment]
I'd disagree. Every other one in the game (and usually in other things) has it the other way around, so we will be trained to autoclick 'woops, no' on the right, insteaf of yes. I know I've done this enough.

**Comment by duncathan** [comment]
Too bad. The default is triggered accidentally far more often than the other choice. Hell, pressing just about any key will pick the default for you. This is definitely the best way to have it laid out, sorry.

**Comment by Bawhoppen** [comment]
give me the stats

**Comment by duncathan** [comment]
Jesus Christ you are unbearable

We don't fucking have stats idiot, but it's pretty easy to figure out. 

Things that make you accidentally press yes:
* clicking yes thinking it's no

Things that make you accidentally press no:
* clicking no thinking it's yes
* continuing to type

Scenarios where you want to say yes:
* typing emoticons that aren't whitelisted
* memeing on people

Scenarios where you want to say no:
* accidentally saying something in ooc instead of say

Consequences of saying no accidentally:
* you have to retype your message

Consequences of saying yes accidentally:
* bwoink
* potential round ruining meta knowledge
* OOC: :b okay operatives what's the plan

Continuing to type while saying things is extremely common. If we switched the default positions, it'd defeat the point of having the filter anyway, as more often than not people would still accidentally let it through.

**Comment by Bawhoppen** [comment]
My point was you said the first thing as a fact, so either you had stats or you were going on empirical evidence. 
The best option of all would to make it be a different shape and layout of the yes/no prompt so nobody would make any mistakes about it.

**Comment by duncathan** [comment]
My (admittedly anecdotal) evidence is my own experience coupled with those friends I have who I know play the game.

The fact that you're the only one complaining gives me a clue, too.

**Comment by duncathan** [comment]
Also
>different shape and layout

Literally not possible, sorry again

**Comment by Bawhoppen** [comment]
Make it it's own special window?

**Comment by duncathan** [comment]
Maybe if there were more than one person complaining about this

**Comment by Bawhoppen** [comment]
I see. I'm fucked unless Jordie comes to my rescue now. Very well.

**Comment by duncathan** [comment]
Like I'm sorry dude but nobody wants to go through the effort of making a browser window for just one person's complaint

If you can prove that plenty of other people agree with you, things will be slightly different

**Comment by Bawhoppen** [comment]
I was being a meme in the last comment I'm not salty it was just a yolk

**Comment by Iamgoofball** [comment]
Go away, you aren't going to win this one.

**Comment by Bawhoppen** [comment]
I'm not trying to
i already ended it  :mahjong:
