### ISSUE TITLE
Mass mindswap doesnt spare the wizard

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13540]
Despite having code that should make it spare them.

**Comment by tkdrg** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
are you sure it wasn't an apprentice?

**Comment by Shadowlight213** [comment]
@Incoming5643 the apprentice doesn't count as a wizard? Odd. Yeah It may have been an apprentice actually.
