### ISSUE TITLE
ctrl-click pull/unpull toggle is bad 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13551]
Maybe its just me, but since there is an inherent delay in everything in this game, it takes a moment before your pull actually registers, so you will click multiple times. But if you click multiple times now, you also stop pulling it which can fuck you over bigtime, especially if it involves dragging cuffed people

I didn't want to go full Mr. Retard but pls fix this shit

**Comment by tkdrg** [comment]
I dunno, I don't really mind this. I always just clicked once and waited until the pull icon appeared in the lower right corner. @neersighted I guess

**Comment by RemieRichards** [comment]
if you know about the delay, why do you spamclick?

**Comment by WJohn** [comment]
I've... never clicked something multiple times to start dragging it. Because the game always responds very quickly for me. Maybe it's different for other people, but click spamming isn't exactly necessary anymore since click delay removal.

**Comment by PKPenguin321** [comment]
i, too, spamclick to drag, especially when i'm trying to drag things out of space wind
making pull/unpull a pref would be pretty cool

**Comment by MrStonedOne** [comment]
It seems like it would be better to exempt the current pulled thing from unpull

**Comment by RemieRichards** [comment]
@MrStonedOne what else would you unpull? you can't unpull something you're not pulling.

**Comment by duncathan** [comment]
>just make it so that you can only stop pulling things that you aren't pulling

mso are you high

**Comment by MrStonedOne** [comment]
what i mean, is if you control click anywhere else, that isn't near you, and can't be pulled, that unpulls.

**Comment by Shadowlight213** [comment]
That seems like a good idea.
