### ISSUE TITLE
chasm turf's straight_down subtype actually sends you straight_up

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#13567]
i think that plus you put there was suppose to be a minus.

@KorPhaeron

**Comment by KorPhaeron** [comment]
Z1 sends you to Z2 sends you to Z3, etc. This is intended.

**Comment by Dorsisdwarf** [comment]
Seems like **Intended Feature*** here

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

Please close it then, we have enough issues as is
