### ISSUE TITLE
Broken solar panels can be deconstructed for the sheet of glass

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#13592]
If a solar panel breaks by a player smashing/shooting it, you can pry out the glass sheets to rebuild it.

There also seems to be an issue with ex_act(maybe?) that causes it to drop a shard as well, meaning you can technically get 1 extra glass sheet out of it.

**Comment by WJohn** [comment]
So it gives you a full sheet of glass instead of a shard?
