### ISSUE TITLE
Airlock animation problem 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13606]
When airlocks try to auto close, if there is a mob in the way, they'll reopen, however there is no animation for it reopening

its just something thats slipped by us for a long time because it just looks like lag and how laggy this game is normally

**Comment by WJohn** [comment]
@xxalpha

**Comment by duncathan** [comment]
This is a bug????

**Comment by Shadowlight213** [comment]
@duncathan 
Yes. Who would've guessed.

**Comment by xxalpha** [comment]
the goyim know

shut it down
