### ISSUE TITLE
Syndicate shielded mobs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#13607]
The syndicate mobs with eshields don't reflect energy weapons and block SOME bullets and melee like it's supposed to
They're simply immune to ranged damage
No, not Idedplsnerf, CONSISTENCY :/

**Comment by Banana-Fist** [comment]
Not sure if bad RNG or a problem but this has happened to me numerous times. My weapons, ballistic or energy, have always been virtually useless against these mobs. Coupled with the fact you can spawn alone surrounded by three or four, it leaves no probability for success. 

I have entered the gateway with fully Goliath plated hard suit armor, two stacks of regeneration and an effective arsenal of weapons, only to go down immediately upon entering the gateway with no ability to fight back. 

Halp.

**Comment by Zilenan91** [comment]
Yeah they're intentionally immune to ranged damage. You gotta melee them.

**Comment by Zilenan91** [comment]
Also this isn't a bug

**Comment by Shadowlight213** [comment]
They actually aren't immune. They have a 60% chance to block the shot. It just seems rng is a dick with blocking.

**Comment by Zilenan91** [comment]
as far as I remember, Kor made a PR a while ago making it so that these mobs didn't take damage from ranged weapons.

**Comment by Shadowlight213** [comment]
@Zilenan91 nope
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/hostile/syndicate.dm#L61

**Comment by optimumtact** [comment]
it makes them retardedly strong and most of the away missions with these mobs are impossible.

**Comment by KorPhaeron** [comment]
Their tankiness was probably buffed too much.

170 health and 50% of projectiles blocked means you need an average of 17 laser hits to kill them

**Comment by Zilenan91** [comment]
Just swarm them. Once one goes down have a dude grab the eshield, esword, and armor, then he can 1v1 them easy peasy.

**Comment by Shadowlight213** [comment]
@KorPhaeron the projectile reflect chance could probably be lowered. I wanted to make it the same chance as an esword eshield combo, but reflect code is really fucking confusing.
The health buff was to compensate for the removal of melee blocking since I saw people just solo them all once one was killed as the player's shield blocked attacks while the mob's didn't.

**Comment by Banana-Fist** [comment]
Honestly it might be less an issue with the mob strength and more the gateway's random placement, if you get dropped in between three or four of these, there isn't a chance you can survive, at least with their current stats. However if you nerf them, they might not be a threat if you're able to approach them strategically.

**Comment by kevinz000** [comment]
I just had a gateway fight. Three people were dumping eguns and SMGs onto a melee simple mob because they didn't know it's immune to ranged
If it was 50% , there's no possible way 6 guns worth of shots didn't hit. They were all blocked. Not misses. The syndicate melee mob was fighting me and standing still for about 20 seconds while everyone around me shot at it. It blocked every single projectile. Considering it died from 6 hits with a crowbar after my damage to it there's absolutely no way a single projectile hit it since two would probably kill it at that point.

**Comment by Shadowlight213** [comment]
@kevinz000 I literally just linked the code showing 50% chance. It seems to be a problem with rng or something. The only real change I did to it was lower the chance since they were never blocking shots before. Which means that something is fucked with prob(50) check

**Comment by kevinz000** [comment]
can we please do something? It definately isn't 50/50 when I unloaded two combat shotguns with buckshot into a mob and died 
AND seeing people who don't know of this magdumping with no result and then dying is kinda sad .

**Comment by Zilenan91** [comment]
Yeah they block all ranged damage.
