### ISSUE TITLE
Away mission smoothing isn't entirely fixed

### ISSUE THREAD

**Issue by Changelingrain** [tgstation/-tg-station#13617]
Not as common as before, but it's still happening.
![sybil pizza hazard ten 2015-12-13 175438](https://cloud.githubusercontent.com/assets/3886584/11770037/c54e2990-a1c2-11e5-82ec-bc900db3f847.png)

**Comment by WJohn** [comment]
Aaaaand it's back again! 
![](http://i.imgur.com/jT7BvSA.png)

**Comment by Cheridan** [comment]
#14262
