### ISSUE TITLE
Bluespace artillery mission spawn bug

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#13615]
You get spawned in random locations, often with enemies that you cannot kill.

Can you fix this and make it spawn you in the dorms room where you're meant to be spawned?
Here is the correct spawning area:
http://puu.sh/lUuSY/9ab5abdaa9.jpg

**Comment by KorPhaeron** [comment]
It's not a bug its sadistic mapping.

I'll probably remove the deadlier spots when I update the map though

**Comment by tkdrg** [comment]
@KorPhaeron is this fixed

**Comment by KorPhaeron** [comment]
Steelpoint has a fix up for it and it isnt a bug anyway
