### ISSUE TITLE
Chem dispensers stop working if there is no power

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#13611]
If the equipment power is off or the APC gets destroyed, chem dispensers won't work at all. You can't put anything in a beaker even though the machine still has power in it and what's even worse is that you can't even eject the beakers.

It used to be that if the power goes out the machines stop regenerating power but they still work normally as long as there is power stored in the machine. You can't even see when the power goes out and by putting a beaker in it just gets stuck with no ways of ejecting it. This might be a bug that came with the new Nano UI system.

**Comment by Shadowlight213** [comment]
It's likely the nanoui is checking if the machine is powered as most other machines shouldn't be able to work if depowered. It probably didn't account for snowflake chem dispenser still operating.

**Comment by optimumtact** [comment]
why is a machine not working when it loses power a bug?

**Comment by Lumipharon** [comment]
because the chem dispenser has an internal power thing - that's how it generates chemicals.

**Comment by neersighted** [comment]
Not a NanoUI bug -- super is checking nopower... someone fix that.

**Comment by neersighted** [comment]
I'm not quite sure how to go forward with this -- chem dispeners have an idle power draw, which implies they require power. Either the internal store is not a 'battery' and they should require power like any other machine, or the internal store is a battery, they should have no idle power usage, and instead deplete the internal battery when disconnected.

**Comment by LatD** [comment]
They have a battery and a capacitor as their parts so it has at least some battery. I haven't checked how the power usage works for them but it would make sense to only use power when refilling the chem storage.

**Comment by neersighted** [comment]
I tried to recode chem dispensers to draw power from APC and portable ones to use cells -- too much work, as I don't know power code. Someone can rewrite them to remove their snowflake power system and use standard cells and then all will be well.

**Comment by LatD** [comment]
Do you know what changed it then? It used to work without power before. I don't know what's the situation at the moment if someone has touched that code.

**Comment by neersighted** [comment]
Super is checking NOPOWER I believe...

**Comment by tkdrg** [comment]
fixed by neer
