### ISSUE TITLE
Simple mobs attacking crit/sleeping people

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#13628]
Not a bug, but damn it was a dumb change.

**Comment by tkdrg** [comment]
Intended.

**Comment by lzimann** [comment]
I know it is intended, but I still think it was a really stupid change

**Comment by Shodansbreak** [comment]
Simple Mobs don't attack crit/sleeping people because that person is "playing dead". This was a focus of Mining if I remember correctly, because miners if they got more than they could chew, they'd fall asleep.
Just like dealing with space bears.

**Comment by Anonus** [comment]
GET GUD VIRO, GET GUD

**Comment by KorPhaeron** [comment]
>GET GUD VIRO, GET GUD

Please stop making non bug issue reports. Researching a healing virus does not entitle you to automatically complete an away mission.
