### ISSUE TITLE
Nuke borgs too cheap

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#13623]
As discussed on coderbus the purchase rate and the TC efficiency for the Syndicate assault borg should be 110 TC and the mediborg 90-95 TC.

Reason for this is the obvious imbalance of an all access, immune to conventional stun, AI killing, 200 health pool robot with an esword, a L60 MG, grenade launchers, Emag and other tools is too cheap for 50 TC with the Mediborg following behind shortly with fire weapons and almost infinite tier 1 healing chemicals.

**Comment by Cebasiz** [comment]
is the consensus that ops are too weak?

i'm okay with nerfs to syndiborg as long as you buff other, unused things like the non-bulldog weapons etc.

if you don't intend a flat nerf, give consideration to buffing underused equipment.

**Comment by LanCartwright** [comment]
This is a buff to underused equipment; you actually need to use equipment now.

There will be no buff to anything else. This is pure balance.

No other equipment needs to be balanced bar energy shield and c20r, both of which are borderline seldom used because everyone buys the Borg.

**Comment by Cebasiz** [comment]
>hugely nerf the capability or effective arsenal of a nukeop team
>not a nerf

>thinks the energy shield isn't good

profoundly puzzling

**Comment by LanCartwright** [comment]
I don't think you understand balancing.

Whether a it is a nerf or a buff, it is still being balanced.

Balancing does not need to be compensated in an equal and opposite direction. 

If two chocolate cakes are made more expensive than two normal cakes, I am not going to compensate that cost by making the chocolate cakes bigger.


And no. I never said the energy shield is bad. I say it's less used because most people rather spend points on the borg. In fact the energy shield is the next item to balance because it's profoundly overpowered.

**Comment by Robustin** [comment]
Nothing about your posts seems coherent.

Overall the Nukeops have a pretty balanced win rate right now.

It's a completely legitimate sentiment regarding balance if you double the cost of syndieborg so that most teams won't get it, then Nukeops needs some buffs elsewhere to make up for losing their cheap and easy "do everything" robot.

Those buffs don't have to be in TC costs.

Not saying I agree with the approach, I'd prefer borgs just get a hit to their utility (giving them an LMG AND Grenade Launcher was silly).

**Comment by LanCartwright** [comment]
Actually, NukeOps have a fairly inbalanced winrate from personal experience rather than logging.
Unless there was some serious reasons, no nukeop should ever lose unless whatever they're fighting is equally robust. Considering the sec population and the activity of players before nukeops board, I'm calling equal winrates bullshit.

NukeOps already have buffs elsewhere. They have a 20 shot detective revolver, they have a 3 hit gun with a grenade launcher, they have a revolver that has 60 rounds, they have a mech capable of fighting Deathsquad mechs.

The Borg is powerful not because of it's LMG or grenade launcher, but it adds an all access silicon with an emag to the team. The LMG is worthless compared to that aspect.

Think of this as a balance to NukeOp because it wasn't balanced before.

What do you want me to do? Make nukeops have c20r roundstart?

I don't think you know what balancing is if you think if nerfing a borg absolutely positively requires that we buff someone else in return. Borg shouldn't have been that price in the first place. This is correcting a mistake not changing mgame mechanics.

**Comment by Cebasiz** [comment]
you are lowering the capability of the nukeop team.

it is a nerf. they have nothing else that can replace the capabilities of the borg, really, so massively increasing it's price is a major nerf which they don't really need.

you list all of their strengths but forget to mention that they are outnumbered in many cases 10:1 and can easily be done in by firelocks, door bolts and thrown spears from greyshirts.

besides, buffing nukeop weapons is only tangentially related to the nerf of the borg; they should really be buffed anyway as they are currently pretty worthless, however the effective removal of the borg means that it will be desperately needed.

**Comment by LanCartwright** [comment]
The Borg should not have been the metagame of nukeops anyway. It is clear nukeops are meant to be 5 man and any more is novelty and luxury rather than the metagame.

They have the medical Borg if they really want to take on the AI, and a mech if they want firepower. I don't know what you're talking about they don't have anything to replace it.

Actually given the population of players, say a healthy 70 players vs 5 nukeops, you will have about 5-10 people that contribute nothing to the round and do not assist, a good 5-10 people that suicide, 5 that intentionally cause trouble and get killed or arrested pre-emptively, not to mention pacifists and those that derelict their job, 70% of nuke rounds are 5 operatives vs 35-40 players not to mention the superior firepower and coordination and the lack of preparation the station staff usually have.

Name one weapon in the NukeOp set that should be buffed. 

C20r - 20 shot detective pistol, 2 round burst, drops and exhausts.
C90gl - 30 shot carbine, 3 rounds to crit, grenade launcher, 3 round burst.
L60 SAW - 60 shot LMG, 2 rounds to crit, 5 round burst.
Bulldog shotgun - cheap ammo, free at roundstart, 2 shot crit w/ slugs.
Stetchkin - free at start, 4 shot crit.

No other weapon on station matches any of these. 
Tell me which one you'd like buffed and justify it because it would be more logical to nerf the guns right now.

**Comment by LanCartwright** [comment]
Attendum:
The argument of 5 vs 20+ will not work on several basis:
If it were a real 5 v 20+ then they'd need real equipment to fight hordes of assistants and crew members. This never happens.

Look at any nuke round.
Most players do not die unless the NukeOp specifically decides to kill them. A 74 player nuke round had most of the players killed in the nuke explosion, with a further few retreating to mining asteroid.

Despite the fact it was 74 vs 6, those 6 individually never fought more than 6 people at once. And a NukeOp sure can take on more than 3 individuals on his own.

The fact of the matter was, most of the chemists, MedBay staff, science staff, all these staff did nothing. They didn't come out and fight. The librarians didn't try to welderbomb me or floor tile me.


And that's the problem. You think it was 74 vs 6 when really at any time it was pretty much 6 vs 40 because more than 6 people had committed suicide and several players were completely pacifist and stayed inside the department or with their groups of friends in the chapel. The best part was several people had already been arrested and was permabrigged.

Stop and think effective and actual players rather than player count.

**Comment by Cebasiz** [comment]
>nuke has weapons to fight large crowds and frequently does

flashbang, tear gas, viscerator, various shotgun slugs like dragonbreath, pellets etc.

>name one weapon in the nukeop set that should be buffed

literally all of them besides the fucking bulldog because they never see use

>6 vs 40

yeah okay that's still gruesomely outnumbered in a game where numbers is an enormous part of actually succeeding at anything. in the last round there was a nukeop team which achieved absolute and complete surprise, killed the AI and bombed tcomms before anyone noticed. they still died due to the inevitable attrition that comes with fighting the crew, even with the overpowered syndiborg and all of those 'broken' weapons.

how many times have you even played nuke dude? i'm starting to wonder because you don't seem to understand fuck all about combat and you think the eshield is bad.

**Comment by LanCartwright** [comment]
Starting off, I never said eshield is bad. In fact I consider it overpowered for giving the reflective benefits of two Esword whilst allowing another weapon hence why the incredibly overpowered C20r and shield combo when C20rs were roundstart.

The reason why they never see use is because of how incredibly strong and cheap the bulldog shotgun ammo is combined with the fact they rarely have enough points after buying a Borg and other essentials.

The prices are fairly balanced. Just because one item is ridiculously overpowered and outshines does not mean the others need a buff.

The guns are anything but balanced if you compare arsenals of the station to the operator.

I'm not interested in individual rounds where nukeops fluked because what I witness is a majority. I've been in a round with a mech instead of a Borg and I've seen more than enough rounds where the Borg was literally the first item bought to know it's overpowered.

As for fluking, operatives are not meant to fight attrition, and even then unless they'd purchased no weapons, they should win in any scenario against any crew member.

I don't know you quite understand that a 6 vs 40 effective players never occur. If it did we'd see more than 6 people fighting an operative at once. That never happens. Operatives group. Players don't nearly as much.
If you seriously think you should balance operatives on how many they fight as a group overall rather than how many they actually fight, you're wrong.

Buffing other weapons is for another topic. I suggest it's left at that because this is for discussion of the Borg, not whether or not NukeOps need more ammo bags.


I've seen ops flop against a cmo, a chef and a cargo tech and I've seen ops win against a 18 players in the brig. How they win or lose is entirely dependant on the Borg at this point.

And regarding the Borg. Having a Borg means most crew are dead due to it's infinite LMG, crowd control potential and melee combat capability.

So what is it going to be? A Borg is for "systematic elimination of non-syndicate personnel" and will further reduce the amount of players alive to fight operatives.

**Comment by TheNightingale** [comment]
Syndicate cyborgs aren't overpowered, they're just the only reliable way to get rid of the AI - which is why they're used so often. If you want to encourage defensive borg use, make the Assault cyborg ~70TC and the Medical cyborg stays at 50. They're completely shut down by a flash, flashbang or ion rifle, and at the first hint of an Operative team, you can bet Security will be breaking those out.

**Comment by LanCartwright** [comment]
Actually, they are overpowered because as it's been previously stated:

Reliable way to shut the AI out.
All access.
Personal, undroppable armoury.

And completely risk free to Operatives; an op won't go on a suicide mission to kill crew members, but a Borg can without risk at all.

And the reason why it's so pricy is because they outshine the mechs. Why would anyone even buy a Mech at this point?

**Comment by duncathan** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod eget ex vel aliquet. Donec elementum tellus nisi, vel tincidunt sem imperdiet vitae. Proin porta maximus ante. Cras eleifend, mi sed placerat feugiat, sem urna tempus tellus, ac malesuada neque est non orci. Maecenas commodo sit amet tortor ut tincidunt. Aliquam tempor mauris justo, non fringilla enim euismod in. Curabitur malesuada tincidunt dignissim. Duis faucibus, massa et egestas lobortis, lectus sapien aliquam augue, ut fermentum quam dolor vitae risus. Duis lacinia imperdiet lacus ut interdum. Fusce id rutrum ante, non euismod nisi. Vivamus convallis, purus a tincidunt varius, nibh ipsum ullamcorper urna, id gravida augue nibh non neque. Nunc venenatis dictum felis, eget lobortis orci auctor et. Sed ante nulla, finibus nec nibh at, ultrices molestie augue.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur quis ante varius, dapibus leo nec, mattis neque. Aenean sodales laoreet facilisis. Donec risus metus, suscipit eu eros at, interdum hendrerit tellus. Vestibulum cursus tristique nunc. Nunc sit amet lacus quis justo iaculis tincidunt rutrum eu quam. Quisque maximus sem in lacus porttitor egestas. In a commodo justo. Nullam dapibus lorem id lacus ultricies, vel consectetur orci pharetra. Nulla blandit tortor erat.

In nunc augue, ultricies eget felis quis, faucibus pharetra mi. Curabitur ac velit sed libero pellentesque vehicula. Vestibulum varius diam massa, id molestie velit vestibulum ac. Aliquam a tincidunt velit, id commodo purus. Morbi vestibulum felis eu erat commodo, vitae varius elit dapibus. Vestibulum eget diam commodo, tincidunt nibh eget, condimentum elit. Aenean eu arcu posuere purus molestie imperdiet.

Aliquam erat volutpat. In congue sed eros ut hendrerit. Suspendisse malesuada ex eget dolor tincidunt lobortis. Donec eros lectus, malesuada ut metus a, rhoncus porttitor enim. Proin congue aliquam erat eget sodales. Praesent ac magna id ante posuere rutrum. Cras viverra urna mauris, a pharetra augue imperdiet nec. Nullam ut pellentesque mi. Etiam sit amet elementum felis.

Vestibulum bibendum in orci malesuada facilisis. Duis venenatis lorem sapien, vel iaculis velit tempus ac. Integer elementum iaculis pellentesque. Ut arcu eros, gravida volutpat pharetra vitae, euismod vitae metus. Proin vestibulum aliquam tellus. Suspendisse potenti. Suspendisse gravida elementum tellus, ac pulvinar orci. Maecenas eu consequat nulla. Duis feugiat mattis nunc, at iaculis ex efficitur a. Morbi vehicula id tortor ac egestas. Sed tellus tellus, gravida et facilisis vel, molestie ut dui. Donec in arcu elit. Morbi ac libero sit amet lorem egestas congue non nec quam.

**Comment by LanCartwright** [comment]
solved in https://github.com/tgstation/-tg-station/pull/13818
