### ISSUE TITLE
Nuke borgs are bugged

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13625]
I saw a nuke borg being able to shoot seemingly infinitely, which I don't think should happen, since I remember nuke borgs having much much less ammo than what I saw that nuke borg in particular use.

**Comment by KorPhaeron** [comment]
/obj/item/weapon/stock_parts/cell/secborg
	name = "security borg rechargable D battery"
	origin_tech = null
	maxcharge = 600	//600 max charge / 100 charge per shot = six shots
	materials = list(MAT_GLASS=40)
	rating = 2.5

/obj/item/ammo_casing/energy/c3dbullet
	projectile_type = /obj/item/projectile/bullet/midbullet3
	select_name = "spraydown"
	fire_sound = 'sound/weapons/gunshot_smg.ogg'
	e_cost = 20

Its not bugged, it just has 30 shots and constantly recharges

**Comment by Zilenan91** [comment]
wtf 30 shots did that get buffed recently. I think it used to have way way less than that because I would run out near instantly.

**Comment by KorPhaeron** [comment]
I dunno but please close the issue report, we don't need more nonbug issues
