### ISSUE TITLE
Plasmic fusion can overconsume gases

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13630]
<img src="https://dl.dropboxusercontent.com/u/4842454/misc/uh.PNG">

I don't want to know what UNKNOWN is.

**Comment by xxalpha** [comment]
Unknown is N2O.

**Comment by bgobandit** [comment]
what the fuck is unknown

< / obligatory>

**Comment by duncathan** [comment]
Lol

**Comment by as334** [comment]
That's weird, I guess something went wrong with the safety check. The fix is going to go up when I get home

**Comment by KorPhaeron** [comment]
@duncathan @tkdrg 

I believe this was fixed
