### ISSUE TITLE
Floor burning doesn't reveal hidden pipes

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#13632]
The semitransparent pipes in this image are pipes I manually varedited to be 0 invisibility. The burning was caused by PLASMATIC FUUUUSION
![space station 13 2015-12-14 012523](https://cloud.githubusercontent.com/assets/3886584/11774307/b9ca132e-a201-11e5-985f-b1ad0b8ad1aa.png)

**Comment by Jalleo** [comment]
Its a really old issue not sure if we have a old issue report for this.

**Comment by WJohn** [comment]
I don't see an existing issue report for this. A bug nonetheless.

**Comment by Shadowlight213** [comment]
Same thing.happens with explosions

**Comment by KorPhaeron** [comment]
@tkdrg 

This got fixed at some point, I've seen plenty of pipes floating in space when techs burn down atmos with fusion
