### ISSUE TITLE
NanoUI for gas cannisters is shit

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#13641]
Cannister UI is so trash, it's impossible to use at any speed except 'excruciatingly slow'. Twice in one shift now I've gone to fill plasma tanks, put the tank in, waited for it to fill, pressed close, waited for it to say close, then pressed eject, only for the cannister to suddenly undo it's 'close' and then eject the tank and spill fucking plasma all over engineering.

How am I supposed to rely on this without waiting 5000 light years to make sure it actually closes when the UI says it closes before ejecting?

**Comment by GamerGambit** [comment]
This doesn't just apply to canisters but everything that uses NanoUI. Keep in mind that the game itself is pretty choppy on the performance side of things as well.

I'm not saying this shouldn't be looked into, just that it's not a unique situation.

**Comment by tkdrg** [comment]
Keep in mind that NanoUI is being completely rewritten right now, and the rewrite is much more responsive since it uses events instead of polling.

**Comment by YakumoChen** [comment]
I don't remember the old UI reopening the tank by itself and spilling shit everywhere. I do know it was slower, but at least it was consistent about shit.

**Comment by duncathan** [comment]
@YakumoChen how long has it been since you last used one of those? They've been doing this shit for years

**Comment by MrStonedOne** [comment]
duncathan, i fixed a bug in june that caused this with canisters.

Nanoui's bay port re-added the bug

New nanoui will fix it again.

**Comment by duncathan** [comment]
@neersighted
