### ISSUE TITLE
Connector keeping gases with nothing connected to it

### ISSUE THREAD

**Issue by Knigga** [tgstation/-tg-station#13700]
So I was doing more fusion stuff and I was trying to fill up a canister with the stuff at a "normal" pressure. I had a passive gate set up to do so, but before I could even turn it on the canister connected to it instantly filled up to the absurdly high fusion pressures. I tried it without a pump or anything connected to the connector, and the same thing happened.
![sybil hut romeo 2015-12-16 100746](https://cloud.githubusercontent.com/assets/11097070/11844794/8e39002e-a3de-11e5-9cc3-d7990204f534.png)
Before I wrenched in the canister
![sybil hut romeo 2015-12-16 100756](https://cloud.githubusercontent.com/assets/11097070/11844801/9a6db74a-a3de-11e5-9141-f5cc4017cd60.png)
After I wrenched it in

At first I just unwrenched/rewrenched the connector and left the pump turned off, but it still filled up with gas. Then I tried to unwrench/rewrench the pump and the gasses still got in. It kept happening until I had both the pump and the connector unwrench then put back into place

**Comment by Knigga** [comment]
Here's a bonus picture of the highest pressure I got with fusion in one canister during this
![more_powah](https://cloud.githubusercontent.com/assets/11097070/11844871/09fc50b2-a3df-11e5-9f44-9e85e40f44cd.PNG)

**Comment by tkdrg** [comment]
I had no idea that connectors also counted as pipes as far as keeping gas goes. @as334 @duncathan I guess

**Comment by MrStonedOne** [comment]
yep, they sure do, easy fix thou, set volume to 0

**Comment by as334** [comment]
Yeah connectors keep gas inside of them, that's why it's considered good practice to drain them so you don't get gas contamination, but yeah we can likely fix this pretty easy

**Comment by duncathan** [comment]
This is intended afaik but also a really easy fix

**Comment by Dorsisdwarf** [comment]
Canisters are definitely supposed to burst at that kind of pressure...
