### ISSUE TITLE
revenant's count a loyal crewmember for hijack

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#13705]
Yeah, you fail hijack when a revenant is on board. Doesn't really make sense that they would count as a loyal crewmember for the objective. Kinda sucks because they can just go invisible.

**Comment by tkdrg** [comment]
@Anonus

**Comment by KorPhaeron** [comment]
Did the revenant have objectives?

**Comment by bgobandit** [comment]
this looks like a job for datum antags @Incoming5643
