### ISSUE TITLE
Oil stain reacts randomly

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#13708]
So, while setting up the turbine on Metastation, I hear the usual chemical reaction sound, and in chat I see the oilstain icon next to the usual reaction message. There was no one else in the room or nearby who may have caused a reaction.

There was also a mouse in the room, and it squeaked at about the same time as the reaction occured, it may have stepped on the stain or something.

**Comment by Anonus** [comment]
Oil reacts when heated, there was probably a stain in the turbine chamber.
