### ISSUE TITLE
Medgun problems

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13712]
1. You can heal someone up to 8 tiles away, one tile out of your range of sight. FALSE ADVERTISING.
2. It is not possible to cancel healing someone outside of walking out of range.
3. It is not possible to swap healing to somebody else without walking out of range of your current target.
4. The sprites look as though the beam is going to the healer, not the target.
5. The medbeam will be broken if it collides with a wall, even if your target is still in your line of sight. This can be annoying for when there are corners and walls around all over the place (such as really just about everywhere in medbay and brig).
6. The beams dont explode when crossed.
@AnturK

**Comment by Fox-McCloud** [comment]
@WJohn 

You can just put it in your backpack or drop it, and that will also cancel it---but yeah, I was *just* about to make an issue report about that.

**Comment by Iamgoofball** [comment]
@nienhaus we need to implement your sprites

**Comment by neersighted** [comment]
I thought you guys were joking about hugbox needing something huggier than cryo...

**Comment by Iamgoofball** [comment]
@neersighted it's for ERT/Nuke Ops only right now

I'll probably add a backpack variant as an R&D item at some point
