### ISSUE TITLE
Turrets will fire at simple animals even if they are both in the same faction.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13711]
What it says on the tin. The turret will NOT fire at monkeys, humans, xenos, or cyborgs if they're in the same faction, but don't care in the slightest if it's a simple animal and will shoot at those anyway.

**Comment by KazeEspada** [comment]
What kind of turrets?

**Comment by Incoming5643** [comment]
syndicate turrets, but I'd imagine it's probably a general problem

**Comment by WJohn** [comment]
Oh yeah I meant to say syndicate turrets. I haven't tested this with other turrets, but it's definitely the case with syndie ones.

**Comment by KazeEspada** [comment]
syndie turrets were coded to check for factions so that they targetted a var that couldn't be faked by the crew. Someone pointed out that factions have become a list of sorts, so "string" and "lists" can't be compared.
