### ISSUE TITLE
Give beakers the option to transfer 20u instead of 15u

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#13748]
Now that the new chem dispenser UI uses the allowed transfer amounts of the reagent container for injection amounts, you can't inject in 20u increments, which sucks because 20u is a hell of a lot more useful than 15u. Could the 15u option be changed to 20u?

![](http://puu.sh/lZzJB/9820280bbb.png)

**Comment by WJohn** [comment]
I swear this is like the third issue report on this.

**Comment by Shapsy** [comment]
Oh, so it is. I asked neer about it yesterday on the server since he did the change that caused this and he said to make an IR about it so here we are
