### ISSUE TITLE
Goliath Plates Suggestion

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#13747]
A feature request none the less, but in any event:

Hardsuits were changed at one point to have their helmets integrated into them.

Suggestions related to goliath plates and this change:

 - Make it so that using a plate on the hardsuit also boosts the helmets armor, as well.

Related suggestion:

- Goliath plates can be used on any hardsuit
- Plates improve bomb resistance?

**Comment by KorPhaeron** [comment]
@tkdrg 

Not even remotely a bug

**Comment by Jalleo** [comment]
Please close this issue @Dorsisdwarf and place feature request like this in minor feature requests on feedback on the forum
