### ISSUE TITLE
UI Fails to Load

### ISSUE THREAD

**Issue by Arctophylax** [tgstation/-tg-station#13756]
Server: Bagil
Server revision compiled on: 2015-12-17
6676ae938b4e10a7fe3eb7d31b43ab68cc9281f1
Problem Description: The UI for APCs, Cannisters, Atmos Alarms, Tanks, Cryo, and Chem Dispensers does not load.
What happened: When I click on one of the items an empty window with the N logo and rotating circles appears.
Possibly related stuff:
I have tested with Fancy UI set both on and off.
I already tried clearing Byond's cache and reconnecting.
I tested this with Byond versions: 509.1316, 509.1315, and 508.1299.
I am running Windows 7 64 bit with Internet Explorer 11.

**Comment by tkdrg** [comment]
@neersighted

**Comment by neersighted** [comment]
You seem to be hitting an edge case. Make sure IE11 is fully patched. Also please test on Sybil. If it persists I'd love to use TeamViewer or something to troubleshoot.

**Comment by Arctophylax** [comment]
I tested it again.
The UI works normally on Sybil:
Server revision compiled on: 2015-12-18
a05bb0ab2f06215921bbea71e8e189817bb08097

I would assume that the PR NanoUI Reduction #13703 which was merged between the two versions fixed it.

**Comment by neersighted** [comment]
Thanks!

**Comment by tkdrg** [comment]
Alright then, closing this as resolved.
