### ISSUE TITLE
AI bugs with using APCs and Air Alarms and Cameras

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#13762]
I play AI a lot and I've been having a lot of issues with APCs and Air Alarms lately.

first of all the maintenance APCs don't work for AIs. They exist on a turf the AI can't access off camera, because the turf is the floor adjacent to the wall, not on camera. Despite this, I can still use the breaker toggle hotkey to disable them, despite no interface popping up.

Air Alarms are also buggy and I find a lot of them just can't be interfaced, even in plain view of cameras. The most glaring one is the one in escape on Box, which is pretty vital for when there's a plasma flood, as escape often becomes a big target for flooding (whether that means removing the plasma or pumping it in). However it would be highly time consuming to find and list all the ones that don't work. I'm not sure of the reason yet, but I suspect it might have something to do with distance from cameras.

Also the blind hack for AIs no longer works, it doesn't load the APC UI and if someone kills the power to your APC and leaves you, you just die. (this killed a whole triumvirate of AIs in a recent round)

Also I've found that cameras are just buggy as well. The main complaint is that Xray upgrades no longer work on cameras, I believe. There's no easy way to test it or what the bug is with it, but I had problems with it in a recent round trying to use xray to spy on a xeno pen in xenobio.

**Comment by tkdrg** [comment]
@neersighted probably related to get_turf_pixel() in the nano default canusetopic()

**Comment by neersighted** [comment]
Can you give an example as to an APC that does not work? I can't fix this if I can't reproduce it. Also yeah, camera code sucks and I plan to work on it sometime.

**Comment by KorPhaeron** [comment]
@neersighted 

Grav gen apparently

**Comment by KorPhaeron** [comment]
Also SMES

**Comment by YakumoChen** [comment]
Treatment Center is one that always sticks out (as tator AI I use it to kill cyro). Medbay too but I don't even think I can see that with cams in the first place.
