### ISSUE TITLE
AI sat "secure storage" area is a very vague name.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13769]
The AI sat's little storage area at the bottom has its area named "secure storage". This is entirely too generic a name, and doesn't help describe where it might be at all. Should probably be renamed to something like "AI satellite storage" instead.

This is mainly a problem during things like gang mode, where the placing the dominator will tell the crew the area's name. If the area's name is poorly made like this, people can get confused as to where it might be.

EDIT: Oh, this is on box by the way, though it might be present across all maps?

**Comment by Strathcona** [comment]
It's across all maps where the mapper hasn't var edited and renamed the default areas.
