### ISSUE TITLE
Choose ghost orbit (in game prefs menu not pref tabs) doesn't actually work

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13778]
![ss 2015-12-18 at 02 08 19](https://cloud.githubusercontent.com/assets/6510293/11906264/d5eb095e-a590-11e5-84f5-bd9a16f08d61.png)
It brings up your ghost sprite menu instead

**Comment by RemieRichards** [comment]
Yep, the button just has the wrong ref is all.
