### ISSUE TITLE
Bizzare interactions if two people ever share a body

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13774]
>get made a holoparasite
>decide I don't really want to play
>offer control to ghosts
>some time later I transform self to human 
>it ghosts the guy in my old parasite body

>mekhi having trouble with new AI malf verbs
>take over for a minute to check and make sure the tab is there
>put him back in (relogging fixed it)
>turn myself into a human later for something unrelated
>it ghosts him and detraitors him

Basically if your body ever gets taken over by a ghost, and you get a new body, it fucks with the old body

**Comment by Xhuis** [comment]
Not sure if this is related, but there's a similar, long-standing issue with cyborgs. If the borg is controlled by one player and the MMI by the other, the borg won't be able to move around or do anything.

**Comment by tkdrg** [comment]
Did you adminghost? (yes, it matters) This is probably because afaik adminghost doesn't reset your `mind.current`, so when you get a new mob it probably tries to ghostize your "old" mob which is the last one you entered.

**Comment by KorPhaeron** [comment]
I did yes.

**Comment by WJohn** [comment]
Oh yeah, I'd like to point out:

Make yourself a human
Put someone else in your body
Make yourself a human again elsewhere
It'll drag that person into the new body.

**Comment by KorPhaeron** [comment]
This happens with offer control to ghosts as well

**Comment by KorPhaeron** [comment]
Alright I fixed this
