### ISSUE TITLE
Double Tailed Lizards

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#13783]
![d10_icon](https://cloud.githubusercontent.com/assets/4176358/11908762/17991136-a5ad-11e5-87ab-dcecf8e2e858.png)

Not sure how this occurred but I saw a lizard with two tails, one properly used and the other stuck in its southern facing sprite in all dirs.

Later when the lizard got tail removal surgery, they lost both tails, but only one dropped.

**Comment by tkdrg** [comment]
@bgobandit
