### ISSUE TITLE
Wild West has a large number of roundstart active turfs

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13798]
103, 122, 8 
102, 123, 8 
104, 123, 8 
102, 124, 8 
104, 124, 8 
102, 125, 8 
104, 125, 8 
101, 126, 8 
104, 126, 8 
100, 127, 8 
104, 127, 8 
96, 128, 8 
98, 128, 8 
99, 128, 8 
100, 128, 8 
104, 128, 8 
92, 129, 8 
93, 129, 8 
96, 129, 8 
97, 129, 8 
98, 129, 8 
106, 129, 8 
108, 129, 8 
112, 129, 8 
113, 129, 8 
114, 129, 8 
91, 130, 8 
92, 130, 8 
95, 130, 8 
98, 130, 8 
106, 130, 8 
107, 130, 8 
108, 130, 8 
111, 130, 8 
112, 130, 8 
91, 131, 8 
94, 131, 8 
95, 131, 8 
97, 131, 8 
98, 131, 8 
107, 131, 8 
108, 131, 8 
110, 131, 8 
111, 131, 8 
91, 132, 8 
94, 132, 8 
96, 132, 8 
98, 132, 8 
107, 132, 8 
108, 132, 8 
110, 132, 8 
110, 133, 8 
113, 133, 8 
114, 133, 8 
113, 134, 8 
111, 135, 8 
112, 135, 8 
113, 135, 8

**Comment by KazeEspada** [comment]
There are mines that spawn plasma and the NPCs step on them.

**Comment by Anonus** [comment]
Those aren't roundstart so they don't count.

**Comment by WJohn** [comment]
I suggest we turn off wildwest because it is full of bugs and also absolutely hideous. It has lots of holes leading to space in the faithless maze, which means huge amounts of air gets drained right away.

**Comment by KorPhaeron** [comment]
Not real holes, just a sprite error

**Comment by Firecage** [comment]
Wjohn. Why turn off one of the best awaymissions though? It is way better than the boring exploration ones.

**Comment by Jordie0608** [comment]
This is caused by the \engine\cult tiles in space at the entrance to the cult vault.
