### ISSUE TITLE
Humanized monkeys with a players brain cannot be entered by the players ghost

### ISSUE THREAD

**Issue by rev-benji** [tgstation/-tg-station#13797]
So in a round there was an ei nath wizard.  He gibbed someone, I took that persons brain to medical.  I humanized a monkey in genetics, surgically removed its brain, inserted the brain of the player, and defibbed the body.  They appeared as catatonic, after being healed.  I removed the players brain - which at that point was named as the humanized monkey not the player - and put it in an MMI.  It showed as totally unresponsive. 

After the round I asked the player about it, and they said they could not enter their brain.  I'm not sure exactly at what point they tried, and I'm almost certain they weren't in the brain when I actually put it in the body. 

 Anyway, this used to work flawlessly, leading me to believe its a bug.

edit: In my totally amateur opinion based on nothing but wild speculation pulled out of my ass, I'd guess that this is related to the new way organs are handled, being more modular or whatever. in the old days brain surgery didn't have a selector menu to choose the organ, maybe there was some code there that tied the brain to the body more.... closely?  I dunno like I said I have no idea what I'm talking about.

**Comment by Dorsisdwarf** [comment]
I believe I encountered something similar, except putting it in a normal monkey

**Comment by LanCartwright** [comment]
Is it something to do with ghosting?

Afaik sometimes you can't ghost out of brain item unless you force ghost (OOC ghost).

**Comment by phil235** [comment]
Most likely the same bug as #15263
