### ISSUE TITLE
DEAD: Alice Mellison says, "golem runes are broken if you've ever orbitted someone"

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13793]

**Comment by WJohn** [comment]
@MrPerson

**Comment by xxalpha** [comment]
Elaborate. I was orbiting a golem rune when I became a golem a few rounds ago.

**Comment by Zilenan91** [comment]
It's something someone in dead chat said, people were complaining about not being able to use golem runes.

*shrug

**Comment by MrStonedOne** [comment]
already fixed before this issue was made =P #13791
