### ISSUE TITLE
Bar dispensers are broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13795]
Put any amount of units of something in a glass in the soda dispenser

Put it in the booze dispenser

watch as the units magically dissapear

**Comment by tkdrg** [comment]
@neersighted maybe

**Comment by tkdrg** [comment]
misclicked

**Comment by Zilenan91** [comment]
But yeah this makes bartender a lot harder because most drinks aren't able to be made at all unless you want to shittily micro full glasses of one unit. So if you want to make whiskey cola I pity you.

**Comment by Xhuis** [comment]
Unable to reproduce on a local server, latest build.

**Comment by Zilenan91** [comment]
Strange, I'll try to test it on-server next time I'm on because I know it deleted units.

**Comment by PKPenguin321** [comment]
So is this confirmed yet

**Comment by Zilenan91** [comment]
I haven't gotten around to it. Try putting like 25 cola in a glass then transferring it to the booze dispenser. That's the exact liquid that I used that caused it to disappear.

**Comment by neersighted** [comment]
looks fine to me:
![2015-12-31_17-48-19](https://cloud.githubusercontent.com/assets/1049222/12069147/b5d2d056-afe6-11e5-9477-cf3d4352d480.png)

**Comment by neersighted** [comment]
![2015-12-31_17-50-33](https://cloud.githubusercontent.com/assets/1049222/12069152/022fac94-afe7-11e5-8007-b54696e19ecd.png)
