### ISSUE TITLE
Saber SMG has an enormous ammo capacity.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#13812]
The prototype saber SMG that R&D can print out has 42 rounds per mag, on top of a 3-round burst fire mode. This means you never ever have to stop shooting. It got buffed to these ludicrous levels because for a while we had the similarly overpowered steelrifles in. Now that those are gone, these things stayed buffed and are still insanely powerful.

Should be dropped to at least 30 rounds per magazine, the burst fire and 9mm refillable bullets are already a gigantic upgrade over steelrifles, on top of being manufactured here on the station rather than ordered by cargo.

**Comment by Zilenan91** [comment]
Yeah it's insanely overpowered
