### ISSUE TITLE
cultists can't locate or retrieve a missing geometer shell

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#13834]
if it gets taken or spaced they have no mechanic to locate it. they should be able to spend an orb to summon it back

**Comment by Shadowlight213** [comment]
Isn't this the same situation as the nuke in ops though? Where if the nuke gets spaced they have no way to find it?

**Comment by KazeEspada** [comment]
Nuke ops dont deploy the nuke until the end. Narsie shell is deployed early to be filled.

**Comment by Anonus** [comment]
Maybe make using a summoning orb in-hand while the shell is active give you a yes/no prompt to summon it as long as it's not active?

**Comment by tkdrg** [comment]
You actually don't need to deploy the shell until you have enough orbs, though. But sure, I'll do what Joan suggested.
