### ISSUE TITLE
You can use the same tool at multiple tiles at once

### ISSUE THREAD

**Issue by SouDescolado** [tgstation/-tg-station#13850]
If, lets say, you have a screwdriver and a crowbar, and wants to open 3 adjacent reinforced windows, you can select the screwdriver and click the 3 in sequence, and the cooldown will start on the 3.

**Comment by RemieRichards** [comment]
This isn't a bug.

**Comment by SouDescolado** [comment]
Really? Shouldn't the cooldown of the first you clicked reset as soon as you click the second one?

**Comment by RemieRichards** [comment]
You're allowed to perform that 1 action on the 8 tiles surrounding you, with their own cooldowns.
