### ISSUE TITLE
Gang tags are bugged as heck

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#13859]
At least on Meta Station.

Case 1: I was able to tag the same room next to enemy gang tag.
Case 2: I was not able to tag over some enemy gang tags, it gave me "not suitable location" error.
Case 3: I tried to tag over Gang A in one spot, it gave me message the place is tagged already by gang B and I have to remove it first.

**Comment by LatD** [comment]
Are you sure all the tags were real tags? It's easy to make fake tags in Meta since it has the public autolathe that can make fake spray cans. This could explain cases 1 and 3.

And I've got that case 2 sometimes too. I'm not sure if it happens when you click the tag instead of the wall behind the tag or something but it always lets me tag the place after moving my cursor around a little.

**Comment by Lumbermancer** [comment]
I believe so. The gangs in play were Max, Waffle and Cyber. In Case 3, I tried to tag over Cyber tag on the holodeck, but it told me place is already tagged by waffle and I need to remove it first.

**Comment by KazeEspada** [comment]
Um, that gang round was Max, Waffle, Omni. The cybers were fake.

**Comment by bgobandit** [comment]
Yeah someone was tagging a bunch of fake gang tags

**Comment by LatD** [comment]
That should then explain cases 1 and 3. Case 2 should still be a bug. Needs reproducing if it's not the one I suggested.

**Comment by bgobandit** [comment]
Case 2 can still happen normally, fake gang tags don't give a fuck about location

**Comment by LatD** [comment]
I think I got it with a normal gang tag on box once and after clicking carefully it let me spray the tile eventually. This happened a week or 2 ago so I don't remember it that well. Maybe if someone sprays a fake tag on top of a normal tag and you click that fake tag or something?

**Comment by Lumbermancer** [comment]
>Um, that gang round was Max, Waffle, Omni. The cybers were fake.

Well that's what Shaps told me, so it may have led me in the wrong way. Maybe they were all fake after all.

**Comment by KorPhaeron** [comment]
@tkdrg 

Sounds like this guy got rused
