### ISSUE TITLE
Humans with Cats Tails are unable to stop wagging.

### ISSUE THREAD

**Issue by Arctophylax** [tgstation/-tg-station#13867]
Server: Bagil
Server revision compiled on: 2015-12-20
862f7e35102c0a4727ddf6949c5b57470b0c3e58

Problem Description: Humans with cat tails are unable to stop wagging their tails.

What did you expect to happen: The *wag emote to stop tail wagging for humans with cat tails.

What happened instead: The "[name] wags his tail." message is displayed. Sprite still shows a wagging tail.

Steps to reproduce the problem: Be a human with a cat tail. Use the *wag emote twice. Tail is still wagging. I only tested this with round start mutant humans.

The logic for the wag emote seems wrong for mutant humans. It checks
`<(dna.features["tail_human"] != "None")>`
to start tail wagging then skips over the else branch to stop wagging if this is true.
The check for stopping the wagging of human tails is more specific being
`("waggingtail_human" in dna.species.mutant_bodyparts)`
and may be better to be checked for first. Placing the more general check to start wagging in the else branch.

**Comment by Bawhoppen** [comment]
>bug
