### ISSUE TITLE
Blob overmind speech is very easy to lose in all the attack messages

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#13872]
@Anonus 

Could stand to be LARGE AND BOLD

Look at me being a hypocrite using issues for non bugs hahaha

**Comment by Incoming5643** [comment]
The people who actually need to see blob overmind messsages are other blob overminds, who can literally see no other message than these.

**Comment by KorPhaeron** [comment]
@Incoming5643 

http://i.imgur.com/eAuHjGv.png

**Comment by Anonus** [comment]
I don't think I really have an effective way to limit the message spam but I could easily make overmind speech fukken huge.
