### ISSUE TITLE
Assignment text error

### ISSUE THREAD

**Issue by swankcookie** [tgstation/-tg-station#13888]
Spawned in as an officer.  It declared that i was assigned too "!".
![officer](https://cloud.githubusercontent.com/assets/15881946/11940804/9d020b76-a7f0-11e5-9fba-c1bc62291b44.png)

**Comment by PKPenguin321** [comment]
just curious, what map was this on?

**Comment by swankcookie** [comment]
box

**Comment by swankcookie** [comment]
where is the assignment code even held?

**Comment by tkdrg** [comment]
Do you remember whether you had any of the assignment armband?

**Comment by swankcookie** [comment]
I did not

**Comment by Thunder12345** [comment]
This is what happens if all the departments have officers and you get spawned as a non-departmental officer
