### ISSUE TITLE
Cable pieces outside box

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#13897]
Two cable pieces out in space south of arrivals.

Boxstation

**Comment by Bawhoppen** [comment]
I dont know how to actually fix this cause the whiteship is in the way

**Comment by Bawhoppen** [comment]
after talking to IRC this is near unresolvable

**Comment by Jalleo** [comment]
Its likely cables being moved from active turfs but Bawhoppen cant find them

**Comment by Bawhoppen** [comment]
I already told you, they are there immediately as the server starts, I just tested it

**Comment by tkdrg** [comment]
it's probably not unresolvable but it certainly doesn't look like an easy fix

**Comment by Bawhoppen** [comment]
when else do you get a chance to use unresolvable
there is no clear solution in sight

**Comment by xxalpha** [comment]
When it's known that it is unresolvable.

**Comment by Bawhoppen** [comment]
which is rare

**Comment by tkdrg** [comment]
so what? it doesn't need to be common

**Comment by Bawhoppen** [comment]
:no_entry_sign: :laughing: :no_entry_sign:
