### ISSUE TITLE
NanoUIs closing for AI when they should not

### ISSUE THREAD

**Issue by GunHog** [tgstation/-tg-station#13892]
When using a NanoUI interface as AI, moving the AI eye off-screen causes the interface to close. 

This is inconsistent with how non-Nano interfaces work, as well as being quite frustrating with how divided an AI's attention tends to be. This will become a much more significant issue the more NanoUIs are made, so I believe addressing this now will prevent further headache.

@neersighted

**Comment by YakumoChen** [comment]
wait this wasn't a bug to stop me from turning off Tcomms as killer AI wherever I wanted?

**Comment by GunHog** [comment]
That would not even work...you could just switch off/on the HUB instead, which is not NanoUI like the APC.

**Comment by MrStonedOne** [comment]
I think this might have been done as a performance concern, but it actually has an easy fix.
