### ISSUE TITLE
The autolathe cannot dispense glass

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13893]
It dissapears

**Comment by swankcookie** [comment]
was it a map-spawned one, or did you build it?  which map?

**Comment by Zilenan91** [comment]
map-spawned, ass station

**Comment by WJohn** [comment]
Strange, I've definitely got the autolathe on metastation to dispense glass just yesterday.

**Comment by xxalpha** [comment]
Can't reproduce.

**Comment by Zilenan91** [comment]
The glass dissapeared when I tried to print glass off of it

**Comment by xxalpha** [comment]
Nope, it works fine.

**Comment by Zilenan91** [comment]
strange

**Comment by tkdrg** [comment]
closing as can't reproduce unless we can get more info on this
