### ISSUE TITLE
Simple mob humans can move in space

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13913]
fucking bullshit

**Comment by tkdrg** [comment]
simple_animal aren't humans and i think we already have an issue for simple_animal moving in space

**Comment by Bawhoppen** [comment]
i know they're not human but I meant the ones that are supposed look human like syndie agents

**Comment by KorPhaeron** [comment]
We have 2-3 "simple animal movement is shit" issues yeah.

**Comment by WJohn** [comment]
I thought it was possible to set whether a simple animal could move around freely in space or not? Or can they all do whatever they want in 0G?

**Comment by Bawhoppen** [comment]
some can and some can't. this is one that shouldn't be able to

**Comment by KorPhaeron** [comment]
Wjohn it is for player controlled mobs, but the pathing that the AI uses checks for density and nothing else

**Comment by Anonus** [comment]
The pathing used is literally a byond proc, so it doesn't give a shit about any of our movement rules.

**Comment by tkdrg** [comment]
anonus astar is our own. Byond doesn't implement any builtin movement algorithm afaik. Mrperson was working on making client Move and mob Move the same but I don't think he finished it

**Comment by Anonus** [comment]
?????
Simple animals use walk_to(), which is a byond proc.

**Comment by tkdrg** [comment]
They use that inside Move though, don't they? Doesn't really keep us from adding a gravity check.
