### ISSUE TITLE
gibbing zombies doesn't drop their old items

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#13919]
probably should

**Comment by KorPhaeron** [comment]
Gibbing people never drops items. Strip them first if you want stuff from them

**Comment by LatD** [comment]
Can you even strip zombies?

**Comment by KorPhaeron** [comment]
Yes

**Comment by Bawhoppen** [comment]
I'm saying it should even if gibbing doesn't normally
you need to butcher zombies on the fly quickly so stripping isn't a good solution

**Comment by Dorsisdwarf** [comment]
Detected and crushed. Risk the respawn if you want the captain's ID.

**Comment by Bawhoppen** [comment]
just force closing the issue doesn't remove the problem

**Comment by Dorsisdwarf** [comment]
If you think a zombie has something you need, strip it before axing, don't gib it then post a feture request because you destroyed the clown's all-access ID.

**Comment by Bawhoppen** [comment]
I'm saying this is a retarded arbitrary way to delete important items

**Comment by duncathan** [comment]
It's not arbitrary; it's consistent with all other gibbing

**Comment by Bawhoppen** [comment]
yes but gibbing deleting stuff itself is arbitrary

**Comment by Dorsisdwarf** [comment]
No, it's "something you don't like".

**Comment by Bawhoppen** [comment]
I haven't heard an explanation why hitting a zombie body with a glass shard will cause body chunks to fly everywhere and implode everything its wearing

**Comment by Dorsisdwarf** [comment]
Because we dont have dismemberment so we can't have the requirement to destroy the head

**Comment by Bawhoppen** [comment]
no its still arbitrary and could be fixed (probably pretty easily too)

**Comment by Dorsisdwarf** [comment]
And now we're back to "I dont like it so its a bug and should be fixed".

Besides, if gibbing drops items, nuke ops can roflstomp the station even harder (stun -> minibomb -> grab rucksack -> scoot)

**Comment by Bawhoppen** [comment]
thats an actual explosion though which is meant to explode items? slicing a corpse with a knife shouldn't obliterate everything they are carrying from existence

**Comment by Dorsisdwarf** [comment]
:shipit:

**Comment by Bawhoppen** [comment]
even non-zombie gibbing should drop items, just because your body assplodes into chunks of meat doesn't mean everything on it does
