### ISSUE TITLE
Salicyclic Acid is pretty much useless

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#13922]
Salicyclic Acid has a 50% chance to heal 1 brute and has a OD threshold, while the similarly hard to make Oxandrolone has a 100% chance to heal 2 burn if you have >50 brute, and heals 0.5 burn otherwise. And the much simpler Saline-Glucose Solution, which can even be made without a chem dispenser, heals 1 brute and 1 burn 33% of the time.

Salicyclic acid should probably have the same effects as Oxandrolone, because in it's current state it is essentially useless.

**Comment by Iamgoofball** [comment]
sal. acid is supposed to be a painkiller

**Comment by bgobandit** [comment]
but we don't have pain

**Comment by Iamgoofball** [comment]
yes we do

you know how you slow down when injured

**Comment by Buggy123** [comment]
But it doesn't fix that.
