### ISSUE TITLE
Zipties can be only used once per round

### ISSUE THREAD

**Issue by Sligneris** [tgstation/-tg-station#13932]
If you use zipties once, you can never use zipties again. Not only those, but any zipties at all.

When detaining someone with zipties a second time, clicking at people with them does absolutely nothing.

**Comment by Zilenan91** [comment]
yeah because they break, this isn't really something that belongs on git

**Comment by TheNightingale** [comment]
"Not only those, but any zipties at all."
How to reproduce:
1) Use zipties on somebody
2) Use another pair of zipties on someone else

**Comment by Cebasiz** [comment]
zil pls read issue thx

**Comment by WJohn** [comment]
I'm gonna label this high priority because most officers have only zipties, and I'm not sure if this affects cyborgs. If it does, it'd mean secborgs could only ever arrest just one person.

**Comment by Cebasiz** [comment]
it doesn't effect secborgs as of maybe 2-3 hours ago.

**Comment by xxalpha** [comment]
Tested this on live server, couldn't reproduce.

**Comment by Sligneris** [comment]
Secborgs are not affected, but I know it happened to me when I play as Captain.

**Comment by LatD** [comment]
This only happens with certain cuffs, like the ones Beepsky uses I think.

**Comment by Thunder12345** [comment]
Can't reproduce here either, need more info

**Comment by AssassinT90** [comment]
Can't reproduce either.

**Comment by phil235** [comment]
Can't reproduce, even with beepskie's cuffs.

**Comment by Sligneris** [comment]
I see. I suppose it might have been a mistake on part. Something to this effect happened to me twice, but I might have simply attempted to use another broken pair.

Closing for now, I might ask for it to be reopened if proven to be an actual issue.
