### ISSUE TITLE
Venus human traps kill each other

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13938]
Something is fucky with their factions

**Comment by tkdrg** [comment]
@RemieRichards

**Comment by Iamgoofball** [comment]
you know damn well there should be only 1 Audrey II

**Comment by Zilenan91** [comment]
The kudzu eventually gets so widespread that it's flat-out spamming these things. They're kinda weak but good god it's hilarious seeing an assistant axing kudzu only to have ten come and eat him.

**Comment by RemieRichards** [comment]
Factions altogether are a bit fucky lately.
Failed removals, Failing to count, etc.

I'll look into the Audreys atleast.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Line 89 of venus_human_trap.dm, where it chooses new grasp victims, has no faction check so far as I can see

And it directly attacks grasped victims once it reels them in/bypasses all the usual targeting stuff

**Comment by Zilenan91** [comment]
The venus human traps also move around, is that supposed to happen?

**Comment by RemieRichards** [comment]
@Zilenan91 I'm undecided. so yo, and nes.
