### ISSUE TITLE
Femaly synths do not do the pixel removal for clothing

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13944]
left: Synth, right: human
![image](http://puu.sh/m5HlB/7afd6016ce.jpg)
This also occurs with jumpsuits and stuff.
@RemieRichards

**Comment by swankcookie** [comment]
@RemieRichards

**Comment by Incoming5643** [comment]
it's because synths don't have genders.

For the sake of dixels, they probably should, even if the sprite for male and female are 100% the same
