### ISSUE TITLE
Tesla Energy Ball Destroy()

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#13948]
It doesn't `return ..()`

it just `..()` meaning it doesn't function properly.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
shiiiiittttt

**Comment by duncathan** [comment]
Don't worry it doesn't break anything
I just get mad at you if you forget to do it
Just remember that the return value of Destroy() is important
