### ISSUE TITLE
You can start a narsie shell on mining but once it actually tries to spawn narsie it just deletes itself

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#13940]
It just goes back to code red as if it was killed.
Shell shouldnt be able to be made on mining anyways probably.

**Comment by tkdrg** [comment]
i was on this round and they still summoned nar-sie somehow. no idea what happened there, there aren't any checks against spawning nar-sie on mining

**Comment by Zilenan91** [comment]
So can you spawn nar-sie on the white ship?
