### ISSUE TITLE
atmos is incredably broken

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#13971]
You  use the analyzer on  the canister [Plasma].
Results  of analysis of  the canister [Plasma].
Pressure: 34.1 kPa
Nitrogen: -315 %
Oxygen: 106 %
CO2: 110 %
Plasma: 197 %
Temperature: -240 °C
this is after canister ignition of burnmix. 66/33 plasma/ox
imedeatly befor i heated it to this tempature it was -1400000 k and psi

**Comment by as334** [comment]
@duncathan I honestly have no idea, do you have any other information on how this happened? Did you just ignite the mix and it did this?

**Comment by duncathan** [comment]
Fascinating

Yeah we need as much information as possible for this one. Let us know exactly what you did.

**Comment by Supermichael777** [comment]
I just heated the mix in the testing lab heaters till 100c and let it rise.
