### ISSUE TITLE
Regular spiders and ice spiders kill eachother

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13979]

**Comment by Bawhoppen** [comment]
not an issue? they're different species

**Comment by WJohn** [comment]
Easy fix, just give em the same spiders faction. Factions are lists after all.

**Comment by Bawhoppen** [comment]
it doesn't need a fix because its intended

**Comment by Zilenan91** [comment]
Who coded ice spiders?

**Comment by Bawhoppen** [comment]
fuck if I know but I know ice is not compatible with non-ice

**Comment by Zilenan91** [comment]
Also by that logic shouldn't space carp and mega space carp kill eachother since they have to be different species to be so different

**Comment by Bawhoppen** [comment]
no you cuckold they're both space fish 
its complex

**Comment by MMMiracles** [comment]
ice spiders are literally just a subtype of the regular spiders, so this is probably more of an issue of all spiders attacking different variants of eachother.

**Comment by swankcookie** [comment]
shouldnt /mob/living/simple_animal/hostile/poison/giant_spider/hunter/ice be /mob/living/simple_animal/hostile/poison/giant_spider/ice/hunter?

**Comment by swankcookie** [comment]
SHOULDNT /mob/living/simple_animal/hostile/poison/giant_spider/hunter/ice BE /mob/living/simple_animal/hostile/poison/giant_spider/ice/hunter?

**Comment by KorPhaeron** [comment]
I need more steps on how to reproduce this @Zilenan91

**Comment by Zilenan91** [comment]
It happened in xenobio, gold core hostile ice spiders and gold core hostile regular spiders. They fought.

Should work without them being from xenobio too.

**Comment by KorPhaeron** [comment]
Did you make one of them sentient?

Did one of them lay eggs? Or did they just go nuts in the pen upon spawning?

**Comment by Zilenan91** [comment]
They both layed hundreds of eggs after getting out of xenobio, and flooded the station and killed everyone so it was a big melee between what ice and non-ice spiders that weren't players walking around.

**Comment by KorPhaeron** [comment]
Giving them sentience changes up their factions to match the potion users.

I just spawned two of them in the thunderdome and they coexisted peacefully.

This might not be a bug.

**Comment by Zilenan91** [comment]
So what if a sentient spider lays eggs. Will the offspring fight eachother?
