### ISSUE TITLE
Goliaths can walk through lava and live

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#13982]
![bug](https://cloud.githubusercontent.com/assets/13275673/11989125/eae80db4-a9ac-11e5-9d6d-313ab2d6dc14.png)

THROUGH THE FIRE AND FLAMES

Tentacle spam from that many was not fun

**Comment by WJohn** [comment]
They should definitely at least avoid stepping on it, but I'd buy them being able to survive being pushed onto it.

**Comment by MMMiracles** [comment]
Fun fact, majority of those goliaths inside the lava are actually dead, the sprite just doesn't update for whatever reason when enough damage is accumulated. 

Also yes by the 30 minute mark theres usually 15-20 dead goliaths sitting in the lava because they're too dumb to realize lava is hot.

**Comment by Zilenan91** [comment]
They all had tentacles hitting me

**Comment by Zilenan91** [comment]
Also fun fact if enough goliaths tentacle you at the same time you're instastunned no matter how long you were in them

**Comment by Incoming5643** [comment]
unrelated but probably a good idea: Don't let the various mob spawners start spawning mobs until players actually make it to the away mission

**Comment by Zilenan91** [comment]
Yeah that'd be nice because being greeted by a smashing eight basilisks in a hallway is something even deathsquads can defeat yepyepyep

**Comment by MMMiracles** [comment]
there wouldn't be 8 because it only spawns a max of 3 per spawner.

**Comment by Zilenan91** [comment]
There was an area where they could overlap and that was a bit of a hyperbole


Also holy shit there's way too many hivelords in that one room with all the spawners to ever deal with without a shitload of people

**Comment by KorPhaeron** [comment]
They die in lava. They just have 200+ health so it might take a bit
