### ISSUE TITLE
Cyborg guns don't appear to actually lose or cost charge

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#14007]
A security cyborg fired its disabler like 25 times in less than a minute, and I'm pretty sure it's supposed to have like 10 shots and not 25.

**Comment by xxalpha** [comment]
It drains from the borgs power, which is large.

**Comment by Anonus** [comment]
The gun used to have an internal cell and gradually recharge that instead of taking from power I guess this isn't technically a bug.

**Comment by Zilenan91** [comment]
Yet another reason to remove secborgs

**Comment by Cebasiz** [comment]
it was changed to drain directly from the battery, like how the secborg lasergun works.

**Comment by xxalpha** [comment]
It could have some sort of cooldown, I think the taser has it?

**Comment by WJohn** [comment]
I think we could just do a balance pass over the numbers, because firing lasers is wildly cheaper than disablers or originally tasers.

**Comment by Dorsisdwarf** [comment]
That was intentional, because tasers are better than lasers.

**Comment by duncathan** [comment]
This was intentional; feedback forum
