### ISSUE TITLE
"Failed Travis" tag is redundant

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#14015]
If Travis fails the PR gets a little X to signify that. You don't need a tag to say the same thing. 

The X/✓ Travis mark also updates automatically when a new commit is added to the pull, while if someone sets the tag it can languish on a working PR for days until someone bothers to complain that the issue was fixed.

Stap.

**Comment by WJohn** [comment]
Yeah I don't see why we have this.

**Comment by Incoming5643** [comment]
Gonna assume it was there before the little X/✓ was

**Comment by PKPenguin321** [comment]
if anything, it's hindering, since you can fix travis but the tag won't remove itself

**Comment by duncathan** [comment]
@dorsisdwarf

**Comment by MrStonedOne** [comment]
You can search by tag or lack of tag, you can't search by that checkmark.

But its ok, i'll work on making a bot that can automate that.

**Comment by MrStonedOne** [comment]
>you can't search by that checkmark.

This isn't true apparently,

https://help.github.com/articles/searching-issues/#search-based-on-commit-status

**Comment by Dorsisdwarf** [comment]
Resolved
