### ISSUE TITLE
bombs are nearly imposible to properly make anymore

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#14012]
BECAUSE FUSION IS SHIT.
it makes the cans go funny.

**Comment by Jalleo** [comment]
Dupe

**Comment by as334** [comment]
How the fuck are you guys even building mixes where the oxygen gets below 10%. The ideal ratio is 10:1 oxygen:plasma for fucks sake, that should like, never happen.

**Comment by Fox-McCloud** [comment]
Proper burn chamber and indirect conduction heating of canister, when?

**Comment by as334** [comment]
anyways, this is less so fusion being broken and moreso people not actually knowing how bombs work and accidentally making a reactor, which is pretty funny.

**Comment by Tetsukiba** [comment]
I could just post a how-to right here that will give you a radius of 25-tiles but i wont

**Comment by Tetsukiba** [comment]
Hmm I'll post it anyway for 5 minutes.
2 Plasma 1 Oxygen, Release canister in gas chamber and empty the product into an empty canister. Cook until 90k kpa+. Cool Pure Oxygen to 150 below 0. Clear tanks, using the Air Siphon. Add 800kpa of pure 150 below 0 oxygen to the oxygen tank. Max the oxygen tank with pure room temp plasma. Add 50kpa of pure plasma to the plasma tank, Max the rest with the heated mix. Boom 25 tiles.

**Comment by duncathan** [comment]
ITT: oldfags buttblasted cuz they're forced to come to terms with the fact that they actually suck at toxins

Use a decent burnmix, faggots
Git gud

**Comment by duncathan** [comment]
Feedback forum
