### ISSUE TITLE
command headset text is way too big

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14010]
its bigger than a goddamn megaphone text
should be only slightly larger

**Comment by lzimann** [comment]
good feature but holy shit it's so huge

**Comment by Shapsy** [comment]
Please add some way to toggle the OH SHIT text size or have it activate only when the person with the headset uses !! because I don't want to draw that much attention as CMO whenever I joke around or say something that isn't urgent

**Comment by Bawhoppen** [comment]
I say make it like alien queen's text in hive chat

**Comment by GunHog** [comment]
Or you could...add the job tag to radio transmissions, which I very often did myself as AI using NTSL. Because there is no replacement, we get...well..this instead...

**Comment by Bawhoppen** [comment]
its still too big even if its a toggle
reopen please
