### ISSUE TITLE
The SABR's still invisible.

### ISSUE THREAD

**Issue by TheNightingale** [tgstation/-tg-station#14014]
The SABR's still invisible when it's loaded (it appears as a little yellow line - an ammo casing?).

**Comment by Thunder12345** [comment]
What the fuck, I could've sworn this was JUST fixed

**Comment by TheNightingale** [comment]
It Keeps Happening™ (I warned you about SABRs, bro. I told you, dog.)

Yeah, the sprite is fine when it's unloaded, but when it has a magazine inside (any sort of magazine), it turns into an ammo casing.

**Comment by KorPhaeron** [comment]
I thought the sabr got changed to 30 rounds, not 21. There was much arguing in the PR. My bad. Will fix it for real.
