### ISSUE TITLE
People keep merging meme prs

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#14018]
<img src="https://i.warosu.org/data/g/img/0411/35/1396484774033.jpg">

**Comment by Cebasiz** [comment]
[not a bug]

**Comment by Thunder12345** [comment]
![image](https://cloud.githubusercontent.com/assets/5479091/11998487/039a3106-aa99-11e5-8de6-fc22a7fcdabb.jpg)

**Comment by duncathan** [comment]
Holy shit fuck off

**Comment by Incoming5643** [comment]
But it's true

**Comment by duncathan** [comment]
Not an issue

**Comment by AlexanderUlanH** [comment]
Alternately: "People aren't taking spacemen as seriously as I want them to."

**Comment by Incoming5643** [comment]
I'm absolute fine with that, it's when it starts messing with game balance that I start getting worried.
