### ISSUE TITLE
You can remove guns from the holodeck if it is set to Holdout

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#14035]
Emag holodeck/have a silicon disable the safety
Set to Holdout
Grab gun
Leave holodeck
Blast losers with gun
Gun and you have many adventures and good times
Change the settings of the holodeck and your gun pal will vaporize however

**Comment by KorPhaeron** [comment]
Hacking the holodeck makes things real.

Not really a bug

**Comment by Man-Shroom-** [comment]
this BR existed for all of a minute
