### ISSUE TITLE
The spaces between the ribs of reanimated skeletons...

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14041]
Can be clicked through, meaning you can click the floor when you meant to hit them.

**Comment by KorPhaeron** [comment]
>when you click on the ground you click on the ground

good bug report

**Comment by Zilenan91** [comment]
It's clicking through the skeleton sprites, which I don't think should happen.

**Comment by Jalleo** [comment]
Easy fix of alpha transparent in between right? @Wjohn

**Comment by Man-Shroom-** [comment]
>implying that you stabbing BETWEEN the ribs is not intentional
