### ISSUE TITLE
Emagging an airlock doesn't show any sparks

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#14047]
When you emag an airlock with an emag, it looks like nothing happens at first and then the door opens and is correctly emagged. The airlock-emagged-open animation isn't playing. That same animation works fine for windoors.

**Comment by WJohn** [comment]
@xxalpha

**Comment by AssassinT90** [comment]
Fixed, chaps (https://github.com/tgstation/-tg-station/pull/14050)

![image](https://cloud.githubusercontent.com/assets/6020070/12004454/55c2d9e2-ab39-11e5-884b-af4fe00e8047.png)
