### ISSUE TITLE
Plasma and oxygen tank nano UI instantly closes after opening as ghost

### ISSUE THREAD

**Issue by LatD** [tgstation/-tg-station#14044]
Happens at least with the orange plasma tanks, air tanks and emergency oxygen tanks. Canisters and all other nano UIs seem to work fine.

**Comment by xxalpha** [comment]
@neersighted

**Comment by neersighted** [comment]
This is intended behavior. What is unintended is for it to open and then close. I think I'll revise NanoUI code to allow ghosts to open ANY ui.
