### ISSUE TITLE
Either do_after is broken or the players are idiots

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#14052]
[That's what went through my head when I read this](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=5487#p142842)
`If the drain progress is about half-way complete, it doesn't matter if they drag you away because it'll still finish and the revenant gets the points. I've done it multiple times to people.`
For reference, revenant draining uses do_after

**Comment by tkdrg** [comment]
@MrStonedOne

**Comment by ike709** [comment]
>Either do_after is broken or the players are idiots

implying it can't be both

**Comment by KorPhaeron** [comment]
@Anonus 

There is like a half second window where if you move someone just as the drain is finishing it won't matter. Unresolvable issue probably.

**Comment by Jalleo** [comment]
Byond and fuck tag please.

**Comment by Anonus** [comment]
From the description it sounds like it's happening like halfway through the drain and not just in the tiny third-of-a-second window where you could drag them without it mattering
