### ISSUE TITLE
Corpses can laugh via N20

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14082]

**Comment by PKPenguin321** [comment]
Hahahahaha

**Comment by Durkel** [comment]
Death is no laughing matter.

**Comment by Bawhoppen** [comment]
this is fucking art

**Comment by xxalpha** [comment]
Reflex.

**Comment by phil235** [comment]
Can't reproduce. Need more info.

**Comment by Durkel** [comment]
Could have possibly been a changeling in regen? I remember they would still gasp while "dead".

**Comment by Zilenan91** [comment]
It was a blob round

**Comment by PKPenguin321** [comment]
Has anybody reproduced this?

**Comment by Zilenan91** [comment]
I don't want it fixed even if they have
