### ISSUE TITLE
Cardboard Boxes are Kinda OP

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#14083]
Carboard boxes are kinda OP for a number of reason

- Grant full slip immunity, even to lube
- flashbang relics will not stun the person inside
- they block all taser/disabler fire from all sides

Yes, I know pulling lockers is a time honored tradition of blocking taser/disabler shots, but it's always been from a single direction.

While the boxes are amazing, they confer a large number of advantages to them, even when you account for their slow movement.

**Comment by Zilenan91** [comment]
They die to a few laser shots but yeah they're really powerful. Also they delete hte person inside of them if the box dies to an explosion.

**Comment by Incoming5643** [comment]
you could also, you know, walk up to the box that can only move at walk speed and open it.

**Comment by Zilenan91** [comment]
Then they jump out with a stunprod and you're dead. As it stands right now just going on the other side of a door usually works.

**Comment by Incoming5643** [comment]
They also burn like nobody's business

**Comment by Zilenan91** [comment]
That too yeah, and since IEDs are getting buffed you should reliably be able to make flames that aren't total dogshit.

**Comment by Incoming5643** [comment]
For real though I can't really think of any way to nerf it if it needs nerfs. It's very common on some maps (looking at you birdboat) but for the "mains" of box and meta I very intentionally only put down one or two assured spawns.

**Comment by Zilenan91** [comment]
Yeah they're hard to get, and they used to be even better. You used to be able to get through plastic flaps with them, which was hilarious so it was a ghetto all access card for certain departments.

**Comment by Fox-McCloud** [comment]
They're not really that hard to get--you need 4 sheets of cardboard to get them---that's pretty trivial, to be honest.

But yes, I realize they b urn and you can laser them super easily, but an officer shouldn't have to carry these things on him just to deal with someone who has a...cardboard box.

Also, as I said, using a flashbang relic inside one of these (or any closet, really) is pretttty bad.

**Comment by Incoming5643** [comment]
unless I'm confused, we don't have flashbang relics

**Comment by LatD** [comment]
Just make the vision limited, like with welding protection. That should nerf it enough to allow those stun and flash immunities.

**Comment by KorPhaeron** [comment]
>Cardboard Boxes are Kinda OP

This is like a parody thread or something

**Comment by KorPhaeron** [comment]
@Fox-McCloud 

Please stop using our issue tracker for minor balance discussion this is meant to be for bug reports

**Comment by duncathan** [comment]
See above
