### ISSUE TITLE
AI turrets have the wrong faction

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14097]
So I fixed the bug where turrets wouldn't respect simple animal factions.

But the default for turrets is "neutral" meaning AI core turrets will basically ignore half the simple animals in the game (notably stands, and anything xenobio makes).

I could change the turret default to something like "silicon" but then any turrets people build in hallways will target Ian forever.

I don't really want to edit 7 maps AI turrets to silicon either.

What is the best solution to this?

**Comment by Zilenan91** [comment]
Set them to silicon. Who cares if they kill Ian if it creates a lot of problems otherwise.

**Comment by Jalleo** [comment]
Set it to silicon and neutral with a ability to turn off neutral if possible else set to silicon and say it was due to copying a older version of ED bot code lore wise.

**Comment by Shadowlight213** [comment]
@KorPhaeron why are stands neutral?
Also aren't AI turrets and the turrets people build different in targetting? Like built turretshave options for their targetting while AI turrets will target anything that's not a borg.

**Comment by Jordie0608** [comment]
Turrets in the AI core have the same targeting options; the AI's just start on anti-silicon mode

**Comment by KorPhaeron** [comment]
Stands are neutral because they copy the faction of the user, which is usually neutral

**Comment by Shadowlight213** [comment]
@Jordie I don't think you can actually set a built turret to silicon only mode and you can't set an AI turret off silicon only mode.
Unless that was changed.

**Comment by optimumtact** [comment]
do the right thing and edit the map, anything else is a silly hack
