### ISSUE TITLE
Core game issue: /tg/station has become (or always was) a complete mess of worshipping random numbers and build orders instead of concrete 2d spessman gameplay

### ISSUE THREAD

**Issue by Dawgas** [tgstation/-tg-station#14091]
MrPerson> There's literally so much that people are missing the forest for the trees
MrPerson> Plus it's good to like
MrPerson> Get it all out there
MrPerson> Because everyone agrees with the statement
MrPerson> And then it's like "oh well, time to do other stuff!"
MrPerson> I think having a list would make it more concrete and actionable

I don't see why we need a list when its fucking obvious as shit to anyone who isn't retarded:

Genetics, virology, botany and xenobiology rely on rolling dice to do anything, which isn't any fun - even though the results may let you have fun (and collect tears - hulk), the fact that you have to go fuck yourself in a corner to do so is not fun or good for any sort of real game

The rest of Science is ultimately completed by finding out an autistic build order and completing it at maximum efficiency - toxins, R&D, etc and there's no real novel gameplay that results from this

There is also the fact that such todo lists exist elsewhere, like cargo always grabbing their insulated gloves and toolbelts and the autistic insistence that everyone initially gears up at the start of the round instead of doing something that could actually be novel and fuck it

to fix this issue this is what I would suggest as a lowly incoherent user of your software product
- [x] scream incoherently at the computer
- [ ] remove all instances of substituting novel gameplay for masturbating with BYOND's RNG or literally doing the same exact thing every round with no variation to get the desired result
- [ ] yes this means removing your pet project
- [ ] this probably means that the end products may need to be awarded elsewhere or simply become standard gear available to anyone (or removed from the code rest in peace genetics & viro NOBODY LOVES YOU GET OUT)
- [x] wonder why nobody tried making this issue before now
- [x] insult iamgoofball at least once
- [x] insult playerbase
- [x] go to bed and make a coherent point later
- [ ] talk about examples of good RNG like battle for wesnoth or fuck I dunno and explain why what we have is not that and fucking stop being a hinderance to the existence of the project
- [x] be passive aggressive with a list

**Comment by Zilenan91** [comment]
A lot of the problems with /tg/ stem from the fact that we don't have any actual developers, just a bunch of people who add their own things for their own reasons. It makes the game very unfocused, but we get a lot more content in general to compensate.

I feel one of the best designed roles we have is Mining even though it's mostly the same thing every round with you going out to the asteroid, killing a few things, getting your minerals and leaving, with interesting gear and also the loot rooms to give much needed spice so it isn't boring.

**Comment by Zilenan91** [comment]
Also I feel like a topic such as this would be more fitting to the forums.

**Comment by Dawgas** [comment]
discussion about most other content is probably something best left for a different issue -

mining falls under this though, and the mining overhaul that ergovisavi did just made mining more tedious and boring - and the vaults honestly aren't really worth searching for with how unlikely anything of note will spawn

(also have you looked at any forum topic or even singulo, all our not completely retarded people are gone and this IS an issue with the game)

**Comment by xxalpha** [comment]
Need more details.

**Comment by Incoming5643** [comment]
If I'm understanding this you're frustrated that some aspects of the game are either utterly predictable or utterly random.

I argue that this consitutes roughly 100% of the game.

The problem is people get too used to things, get too complacent in how things operate. At times like these I feel like the best thing to do is to take a break from the spessmen, step back, get a nice breath of fresh air, and then come back later.

**Comment by duncathan** [comment]
What is concrete 2d spessmen gameplay?
The fact is, that question can't easily be answered. 
This is a discussion I'm fine with us having, but not fine with having in the issue tracker. Feel free to continue discussing it here, or make a feedback forum thread (preferably). Thanks.

**Comment by ike709** [comment]
If someone makes a forum thread for this, please link it here so I don't have to put forth much effort to find it myself.

**Comment by Anonus** [comment]
I'm just going to note here that there are solutions, like random plants/mutations for botany, varying sets of accessible genetics powers per-person, and removing viro, to note on some of the more extreme examples.
