### ISSUE TITLE
[Not an issue]

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14105]
I'd like to congratulate everyone who has done work for nukeops, because we have managed to make it un-shit again.

Everyone have a happy holidays and a new year 
:smiley: :frog:

**Comment by Bawhoppen** [comment]
I know this will be closed soon enough but we did a good job making a gamemode good without stealing from goon

**Comment by Jalleo** [comment]
There is always room for improvement.
@Dorsisdwarf 
Please close this.

**Comment by Bawhoppen** [comment]
Theres no rush for closing
just everyone give yourself a pat on the back

**Comment by Shadowlight213** [comment]
No appreciation allowed here.

**Comment by tkdrg** [comment]
no fun allowed everyone go home
