### ISSUE TITLE
Spraying burning items and structures with water doesnt put out the fire.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14106]

**Comment by Jalleo** [comment]
There is a thing called burn stacks look up the code for it to see how it works and what your exact issue is

**Comment by Zilenan91** [comment]
Works with fire extinguishers but not actual water itself. Water out of sprayers aren't supposed to put fires out. Close this please.

**Comment by WJohn** [comment]
I find this to be more a consistency issue, even if its not a bug. Worth a discussion I guess.

**Comment by KazeEspada** [comment]
I mean the fire extinguisher didn't put them out.

**Comment by newfren** [comment]
You know how when fire fighters spray water at a fire and it doesn't instantly go out because there's too much fire?

Same principle.

**Comment by KazeEspada** [comment]
There was no fire in the entire room except for a few burning tables and I unleased an entire extinguisher of water at it.

**Comment by optimumtact** [comment]
They probably had a stupidly high firestack thanks to a bug or a stupid chemical or something
