### ISSUE TITLE
AI UI bug makes it impossible to interact with atmos pumps, APCs, air alarms

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#14108]
hi. been getting this for the last day or so now and it's making it a pain to play AI who's entire point is to do stuff like this. very annoying as it persists through a restart of the client. seems pretty random(?)
![fug](https://cloud.githubusercontent.com/assets/10738550/12013383/07c6e15e-acdb-11e5-9e1c-4471c4785dd2.png)

**Comment by tkdrg** [comment]
Known bug with NanoUI. I get the same issue as well. @neersighted

**Comment by neersighted** [comment]
This has been fixed as of #14130; NanoUI has been replaced.

**Comment by duncathan** [comment]
@Cheridan points for neer
