### ISSUE TITLE
Space lube can slip you even if you're on a janicart

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14117]

**Comment by xxalpha** [comment]
dupe?

**Comment by Zilenan91** [comment]
find the dupe one and I'll close this

**Comment by AnturK** [comment]
Intended.

**Comment by xxalpha** [comment]
https://github.com/tgstation/-tg-station/issues/11234

**Comment by phil235** [comment]
Intended. You can ride a janicart on wet tiles but riding on lubed tiles makes you fall from your janicart.
