### ISSUE TITLE
You can "save" combos with martial arts

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14118]
For example, in plasma fist, executing all but the last stage of your gib combo on person A, then saving it until you feel like instant gibbing person B with a single attack.

**Comment by AnturK** [comment]
Semi intended since i assumed using the combos in a crowd would be a pain. It probably needs a timeout so it's actually combo, not AAA 20 minutes pass B.

**Comment by KorPhaeron** [comment]
@AnturK 

You can drag around a corpse/monkey person as well, and I think maybe even do the combo start on yourself
