### ISSUE TITLE
Bear Traps slow you down if you're holding them

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14116]
If you drop them it's fine though, I think Kor's slowdown from handheld items pr broke them.

**Comment by Jalleo** [comment]
I think this should be intended. Although they are bearly used anyhow so better to remove slowdown in hand to encourage more use.

**Comment by optimumtact** [comment]
>bearly used

A) damn you

and 
B)
probably a factor of them being large items to only fit in backpacks or something

**Comment by Zilenan91** [comment]
They fit in bags, whereupon the slowdown goes away. It's just annoying that you have to do that because janitors tend to juggle their inventories.

**Comment by optimumtact** [comment]
sure the hand slowdown thing never really made sense because inventory weight was never considered either.
