### ISSUE TITLE
Water can't clean out of a spray bottle

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14129]
It can't clean anything, not blood or graffiti, no matter how many units you put on it. I'm not sure if its lack of cleaning ability is even intended or not, but hey if I can get more excuses to slip people and say it's my job I'll take them.

**Comment by WJohn** [comment]
Uh, water is not supposed to clean things when sprayed. It has been intended like this pretty much forever. Use space cleaner, and dilute it with water.
