### ISSUE TITLE
destruction of grilles & windows by explosives inconsistent and annoying

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#14126]
is it possible to somehow set it up so that things on 'top' must be destroyed before things inside/under can be damaged? as it is, grilles are frequently destroyed INSIDE R-windows and it's really obnoxious. likewise, i think floors can get damaged (and won't support walls, floors, etc) without the tile above them actually being destroyed.

i'd appreciate it, as deconning R-windows to replace the grilles inside them which were apparently vaporized somehow by the blast is really annoying.

**Comment by xxalpha** [comment]
I am sure this is a duplicate, but might as well get another report.

**Comment by phil235** [comment]
related to #3513
