### ISSUE TITLE
Admins get notified that "emitter lost power" when they shouldn't

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#14135]
The point is that the emitter doesn't lose power so it ends up spamming the admins with ~3 lines of false alarms.

**Comment by Jordie0608** [comment]
IIRC this is actually due to emitters checking they have power when the powernet is recalculating.

**Comment by Iamgoofball** [comment]
goofball literally can't EMP it due to the emitter being on the blacklist, so it has to be that power check meme.

**Comment by Shadowlight213** [comment]
This is a dupe of a really old issue I think

**Comment by WJohn** [comment]
Yeah, dupe of #4777

Good catch.
