### ISSUE TITLE
Detective's armor vest can't store telescopic baton

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#14141]
Detective's vest specifies `/obj/item/weapon/melee/baton` while telescopic baton is `/obj/item/weapon//classic_baton/telescopic`

**Comment by xxalpha** [comment]
Why does security have these anyways

**Comment by SouDescolado** [comment]
[jobs.dm.txt](https://github.com/tgstation/-tg-station/files/74200/jobs.dm.txt)

This is with the telescopic baton added at the end. Line 84.
