### ISSUE TITLE
roach guts can't be cleaned by cleanbot or cleaning foam

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#14140]

**Comment by KazeEspada** [comment]
??? That's weird? They are children of /decal/cleanable

**Comment by Incoming5643** [comment]
if I remember correctly for some hideous reason the list of cleanable decals is a whitelist.

**Comment by optimumtact** [comment]
space cleaner should be cleaning it up find

**Comment by phil235** [comment]
Cannot reproduce. Space cleaner foam and spray clean cockroach guts just fine (both adminspawned ones and the guts spawned by killing a cockroach)

**Comment by YakumoChen** [comment]
I only tested it with hacked cleanbot and AI Core foam, but I was assuming either one had cleaning properties.

**Comment by phil235** [comment]
AI Core foam is not space cleaner foam (which is visible because foam with reagents take the color of the reagents, green in the case of space cleaner), it can't clean anything.
