### ISSUE TITLE
Dual wielding not working

### ISSUE THREAD

**Issue by phpminor** [tgstation/-tg-station#14164]
When i attempt to fire with every gun i've tried it doesn't fire the one in my offhand like it says (You can now dual wield guns. Firing a gun will automatically fire the gun held in your off hand if you are on harm intent.) as it says in the changelog. Do i need something specific in order to dual wield and fire both of them?

**Comment by Thunder12345** [comment]
Dual wielding got reverted, Kor was just too lazy to put it in the changelog

**Comment by xxalpha** [comment]
Don't reverts get listed in the changelog?

**Comment by phpminor** [comment]
Oh. Thanks
