### ISSUE TITLE
Nuke Ops: Easy Victory

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#14169]
If the nuke ops declare war on the station, the crew can just immediately call the shuttle to "beat" the nukies---especially since the nukies can't leave for 20 minutes and it only takes the emergency shuttle ~15 minutes to arrive, board, and leave--even less time if code red is instituted.

**Comment by killerx09** [comment]
My opinion of this is that it'll get better as the nukies get better. Off the top of my head, they could emag the communications console to recall and lower the alarm level, drop the drop pod at escape so that the turrets hinder the evacuation or stop buying useless stuff like macrobombs.

**Comment by tkdrg** [comment]
@Fox-McCloud Nope, because the shuttle can only be called after 20 minutes. That's why that time was picked, after all.

**Comment by Iamgoofball** [comment]
War should really increase the shuttle delay to 30 min

**Comment by Incoming5643** [comment]
The crew shuttle delay is a config setting, so on a server with a very low/no delay they can outpace the antagonist delay.
