### ISSUE TITLE
unable to find blood on the blood (detective scanner)

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#14177]
![blood on blood](https://cloud.githubusercontent.com/assets/701959/12059421/8ce16c96-af39-11e5-9107-d7f667f59e57.jpg)

i think i should be able to find blood on the blood. Metastation.

**Comment by bgobandit** [comment]
wow aranclanos you suck at detective work

**Comment by swankcookie** [comment]
look closer, man.

**Comment by Jalleo** [comment]
Is this walking or blood splatter? Also certain was a player or prespawned?

**Comment by swankcookie** [comment]
the gibs imply player, i believe

**Comment by Jalleo** [comment]
@Metacide any fake gibs on metastation?

**Comment by TrustyGun** [comment]
it doesn't work on box station either. i was scanning footprints and blood decals, and they all returned nothing

**Comment by Jalleo** [comment]
Needs to be confirmed as actual blood first not fake roundspawn blood.

**Comment by TrustyGun** [comment]
it was actual blood, roundspawn blood is dry and looks darker

**Comment by bgobandit** [comment]
even roundstart blood should have a different message

**Comment by Jalleo** [comment]
could this be the offending line of code? https://github.com/tgstation/-tg-station/blob/ac7e0cc0367c334c42499bee94e70bc66ff9700e/code/game/objects/effects/decals/Cleanable/humans.dm#L24

**Comment by Jalleo** [comment]
could this be the offending line of code? https://github.com/tgstation/-tg-station/blob/ac7e0cc0367c334c42499bee94e70bc66ff9700e/code/game/objects/effects/decals/Cleanable/humans.dm#L24

**Comment by phil235** [comment]
@Jalleo Apparently yeah, there's a problem when two blood stains merge together, only the dna of one blood stain is kept somehow. But I don't think this is linked to aran's issue.

The bug only occurs with bloody footprints, blood dna isn't transfered to the footprints apparently.

**Comment by Jalleo** [comment]
Must be due to how it is stored on the person before placing the new blood footprint

**Comment by Metacide** [comment]
There is fake gib there on roundstart, yes. You can see it on the [wiki map](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-11-01%2016-19%20MSv41I%20Full.png) east of the experimentation lab.

I can rename it to old giblet or something to make it clearer that it's just fluff, will look into it.

Thanks for the heads-up Jalleo.

**Comment by Dorsisdwarf** [comment]
Footprints do not have blood or DNA on them, #13699

Leaving open due to intertia

**Comment by Metacide** [comment]
I've replaced the gibs and blood with the proper "old" versions so people know they're fluff, meant to get round to it a while back. Will make a pull request with the fix in sometime.
