### ISSUE TITLE
[Not a bug] Borgs doesnt have the comms for their sector

### ISSUE THREAD

**Issue by SouDescolado** [tgstation/-tg-station#14194]
All borgs start with only common radio. When they select a module, I think they should inherit it's radio.

Secborg get secradio
Mediborg get medradio (Maybe chem/genetics/viro too?)
Miningborg get supply radio (Maybe science ?)

Dont know any other implication other than helping the borgs help their sectors.

Noone changes borgs encryption keys.

More love for the borgs

**Comment by TrustyGun** [comment]
this is intended, they are supposed to bug sec/med/engi/whatever and the robotists to get them an encryption key

**Comment by Jordie0608** [comment]
Yeah this is intentional

**Comment by Jalleo** [comment]
The real issue is not being able to get any more than what the station starts with.
