### ISSUE TITLE
Grab can be used to lock and unlock a lockable locker

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14204]

**Comment by KorPhaeron** [comment]
How is this even an issue

**Comment by Jalleo** [comment]
Please explain what you mean

**Comment by KorPhaeron** [comment]
He means clicking lockers with the "grab" item will unlock them, which is the same behaviour for clicking a locker in every other circumstance in the game.

If we blacklisted abstract items from opening lockers it'd just cause more issues (like changeling armblades or chainsaw hands not working).

Complete non issue.
