### ISSUE TITLE
Beam from Turf to another atom returns weird results.

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#14209]
Alright, so, dunno how else to describe this, but.

Calling Beam() on an atom with the mob as the target returns what you expect:

![img](https://i.gyazo.com/e0daafc3db3696911f134baa0db2758d.png)

But calling Beam() on turf the atom is *on* with the mob as the target, returns weird results:

![img](https://i.gyazo.com/1b8aa17bb49ac9d30af3d52d3add8233.png)

Oddly enough though, calling Beam on the *mob* with the same exact turf as the target is ok/non-weird:

![img3](https://i.gyazo.com/aaf9a47b1a8a5e7cf2401fed1ebb2cf7.png)

**Comment by PKPenguin321** [comment]
Are you sure these pictures are even of /tg/ code?

**Comment by RemieRichards** [comment]
@Fox-McCloud pretty sure we don't have this bug.
it's drawing from the loc of the object.
the loc of a turf is an area.

We don't have this any more to my knowledge, you guys are probably behind.

**Comment by Fox-McCloud** [comment]
Nah, we're 100% up to date with `Beam` code regarding you guys; I even tested it on 100% pure TG ocdebase just to be absolutely certain (just didn't feel like taking more pictures), and the quirk is most definitely there for you guys, too.

**Comment by Incoming5643** [comment]
Something is using a turf.loc, returning the area of the bar.

I thought I fixed all these cases, but apparently there's still one left.

**Comment by AnturK** [comment]
iirc beam just grabs .loc once then backtracks if it's area, i left that in the refactor because it's probably faster than get_turf. Might not have been the best idea.

**Comment by RemieRichards** [comment]
idk @AnturK ```get_turf()``` is really fast.

**Comment by AnturK** [comment]
Well in the common scenario it would probably be same speed, one istype check. I don't count the for overhead. Anyway, yeah probably should be changed.
