### ISSUE TITLE
goofjectives still cucked

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14227]
The changelings were:
Bawhoppennn was Kevin Parkinson the Librarian and survived
Changeling ID: Mr. Nu.
Genomes Extracted: 2
Objective #1: Nothing Success!
Objective #2: Assassinate Sarah Hooker, the Scientist. Success!
Objective #3: Protect Sarah Hooker, the Scientist. Fail.
Objective #4: Prevent Sarah Hooker, the Scientist, from escaping alive. Success!
Objective #5: Escape on the shuttle or an escape pod alive and without being in custody. Success!
The changeling has failed.

**Comment by Supermichael777** [comment]
*clapping intensifies

**Comment by tkdrg** [comment]
![2015-12-31-234915_650x121_scrot](https://cloud.githubusercontent.com/assets/6563111/12069814/b7afc518-b02d-11e5-8636-d9476ab7265f.png)

@iamgoofball

**Comment by Anonus** [comment]
I'm pretty sure that humans can get the "prevent organics from being on the shuttle" objective too.

**Comment by Incoming5643** [comment]
The destroy objective is basically a kill objective that only applies to the AI.

Because it's defined as a separate objective it seems to get equal billing with all the others. Which means for every person you have to kill normally you have an equal chance to kill the AI.

This means that on most rounds, nearly half the antagonists will be tasked with destroying the AI

**Comment by YakumoChen** [comment]
Carbons can get the Prevent Organics From Escaping objective

**Comment by Iamgoofball** [comment]
>space ninja
I don't like it's objective code, it's BAD

I got a fix for the OP with the changeling though.

**Comment by YakumoChen** [comment]
Just had a traitor round with four traitors and all of them had the Kill AI objective

**Comment by Iamgoofball** [comment]
I'll look into toning down the kill AI shit or just remove it from randomgen and make assassination objectives able to target it.

**Comment by Iamgoofball** [comment]
Also, any admins reading, if you see an objective reading Nothing or Free objective, VV the guy's mind and give me the path for the objectives marked as nothing/free objective. I've gotten the "guy got a nothing objective" report about 10 times so far and every single time you guys have dropped the ball on giving me required info for fixing it.

**Comment by YakumoChen** [comment]
Non-lings can get Steal Identity objective

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Had a wizard fail because he was on the shuttle with "don't allow organics to escape"

**Comment by tkdrg** [comment]
Caught it this time. The issue with the "Nothing" objectives is people getting the "destroy AI" objective when there is no AI. They get another objective to replace it but the broken AI objective still stays in the mind as a "Nothing",

**Comment by Iamgoofball** [comment]
Fucking destroy AI, I'll kick it's ass qhen I get home

**Comment by Bawhoppen** [comment]
The changelings were:
Anonmare was Sarah Hooker the Animal and survived as headslug
Changeling ID: Ms. Upsilon.
Genomes Extracted: 1
Objective #1: Free Objective Success!
Objective #2: Nothing Success!
Objective #3: Free Objective Success!
Objective #4: Free Objective Success!
Objective #5: Stay alive until the end. Fail.
Objective #6: Escape on the shuttle or an escape pod alive and without being in custody. Success!
The changeling has failed.

**Comment by Iamgoofball** [comment]
Why the fuck does he have 2 escape objectives what the /fuck/

I need to know what those free objectives were

**Comment by Incoming5643** [comment]
also they failed a stay alive objective while alive

**Comment by Bawhoppen** [comment]
goof atleast try

**Comment by Iamgoofball** [comment]
@Incoming5643 that might be the "stay alive until end" crap bugging out due to surviving as an animal.

**Comment by Bawhoppen** [comment]
K Peculier was Ender Shredder the Space Ninja and survived
Objective #1: Nothing Success!
Objective #2: Assassinate Alice Burns, the Cargo Technician. Success!
Objective #3: Nothing Success!
Objective #4: Nothing Success!
Objective #5: Stay alive until the end. Fail.
The space ninja has failed!

**Comment by Bawhoppen** [comment]
goof how do you even

**Comment by tkdrg** [comment]
I got VVs for those
![2016-01-02-013723_1366x768_scrot](https://cloud.githubusercontent.com/assets/6563111/12073227/3b5bd158-b0f2-11e5-8204-271c20c99cf4.png)

**Comment by Iamgoofball** [comment]
I'm going to gut the FUCK out of space ninjas, those fuckers aren't even supported

**Comment by KorPhaeron** [comment]
Stay Alive Until The End fails when the person is alive.

**Comment by tkdrg** [comment]
![2016-01-02-014935_1366x768_scrot](https://cloud.githubusercontent.com/assets/6563111/12075207/78aac6ee-b157-11e5-83f7-7927cd223743.png)

**Comment by Iamgoofball** [comment]
Jesus christ did he get picked for antag like 5 fuckin times or is he a ling

**Comment by Anonus** [comment]
Not just a ling, a traitor ling.

**Comment by Bawhoppen** [comment]
I'm about 2 seconds away from putting a $50,000 hit on goof's head



The traitors were:
bawhoppennn was Kevin Parkinson the Botanist and survived
Objective #1: Steal the station blueprints. Success!
Objective #2: Assassinate Christopher Beckett, the Shaft Miner. Success!
Objective #3: Protect Sarah Hooker, the Roboticist. Success!
Objective #4: Stay alive until the end. Fail.
Objective #5: Steal the heavily radioactive plutonium core from the onboard self-destruct. Take care to wear the proper safety equipment when extracting the core. Success!
Objective #6: Hijack the shuttle to ensure no loyalist Nanotrasen crew escape alive and out of custody. Success!
The changeling has failed!

i spent so long you cuckold

**Comment by octareenroon91** [comment]
Addition to the heap:
![survive-and-fail-survival](https://cloud.githubusercontent.com/assets/12420976/12104089/a8275740-b30d-11e5-852e-1f486d2ccaa1.png)

I'd guess this has to do with "Stay alive until the end" as a silicon objective.

**Comment by optimumtact** [comment]
remove space ninja objectives and just give them rp entries, maybe it will reduce the powergame

**Comment by bgobandit** [comment]
was traitor, got "steal identity"

**Comment by tkdrg** [comment]
@bgobandit intended

**Comment by Iamgoofball** [comment]
@tkdrg not really, it doesn't work with proper ID steals

**Comment by octareenroon91** [comment]
Not that it's a balanced level of challenge, but couldn't anyone can use the genetics machinery for that?
