### ISSUE TITLE
Minor typo on bruise packs.

### ISSUE THREAD

**Issue by arty23** [tgstation/-tg-station#14229]
Description: "A theraputic gel pack and bandages designed to treat blunt-force trauma."
Should be: "A therapeutic gel pack with bandages which treats blunt force trauma."

[Read: theraputic; therapeutic]

**Comment by Supermichael777** [comment]
should be which treats actualy

**Comment by arty23** [comment]
would you believe me if i said i had that originally, but figured that it would look too pompous?
