### ISSUE TITLE
Empty virus boxes in Syndi surplus crates

### ISSUE THREAD

**Issue by Anonmare** [tgstation/-tg-station#14224]
![bagil neckbeard spess junk xiv 2016-01-01 002356](https://cloud.githubusercontent.com/assets/12382984/12069277/1638ca40-b01e-11e5-9a1a-10aac8a52983.png)
Got an empty virus box in a syndicate surplus crate and I'm fairly certain that should nto occur. I'm not a coder so don't ask me for specifics, might want to check the coding there.

**Comment by PKPenguin321** [comment]
Related to https://github.com/tgstation/-tg-station/pull/14107 maybe?

**Comment by LanCartwright** [comment]
https://github.com/tgstation/-tg-station/pull/14225

**Comment by tkdrg** [comment]
Just fixed it
