### ISSUE TITLE
M90gl bundle

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14234]
I must have been drunk when i typed this.

A large dufflebag containing a M90gl, a magazine, and a stimpack.

Should be:
A large dufflebag containing a M90gl, a magazine, four additional grenades, and a pack of Syndicate cigarettes.

**Comment by Zilenan91** [comment]
Don't syndicate cigs explode?

**Comment by LanCartwright** [comment]
No, they contain reagents.add_reagent("omnizine",15).

**Comment by killerx09** [comment]
I'll install git and give it a shot at fixing this, should be easy enough.

**Comment by MMMiracles** [comment]
This was apparently already fixed so should probably close it.
