### ISSUE TITLE
Strange human race

### ISSUE THREAD

**Issue by kustridaren** [tgstation/-tg-station#14246]
Well when xenologist injected me to make me lizard it diden't work and after several attempt i looked like this https://tgstation13.org/phpBB/viewtopic.php?f=2&t=5543. it says that im suffocating because of no plasma but im not and i'm creating a little bit of plasma.

**Comment by kustridaren** [comment]
![monster 4](https://cloud.githubusercontent.com/assets/16508666/12070914/951a34ac-b091-11e5-9269-c69235724021.PNG)
![monster 2](https://cloud.githubusercontent.com/assets/16508666/12070915/98b3a260-b091-11e5-8528-8d39e5b64d6a.PNG)
![monster 3](https://cloud.githubusercontent.com/assets/16508666/12070916/9bd99134-b091-11e5-9bbd-df2b7b2875e1.PNG)
![monster](https://cloud.githubusercontent.com/assets/16508666/12070917/9e957e10-b091-11e5-9f84-925d70419d30.PNG)

**Comment by LatD** [comment]
I think the plasma thing comes when you're a plasmaman even for a while and then get changed to something else. The toxin alert won't go away after it even though you're not taking any damage. I have a PR up already that fixes the plasma part.

The unstable mutation toxin uses all species available (outside the blacklist) so someone probably added a new species which you turned into.

**Comment by kustridaren** [comment]
the combat mode is on the suit

**Comment by LatD** [comment]
Ah, that explains it. No bugs here then.
