### ISSUE TITLE
Smoke makes liches cough

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#14248]
"Why do I keep dropping my fucking guns with this smoke, I just want to shoot people through smoke god damn" -Me as a lich wizard not knowing smoke spell made you drop shit you were holding. No wonder nobody picks it, it's more harmful to wizards then it is good.

**Comment by LatD** [comment]
This spell should really make the caster immune to smoke or something, not just liches

**Comment by phil235** [comment]
Need to add a check to see if the human's species has the NOBREATH specflag.
