### ISSUE TITLE
Engieborg's wire module not refillable from cable coils

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#14240]
**Server:** Sybil

**Revision:** Didn't grab the exact number; it's whatever revision was active around 2015-12-31 15:00 UTC+01:00.

**Problem Description:** Few months ago, refilling your cable coil as engieborg was as simple as clicking a cable coil lying around with it. This doesn't seem to work anymore; when clicking the coil, nothing happens, and no message is displayed.

Didn't see anything along this vein in the changelog, so I'm guessing it's unintended. Might be wrong.

**What did you expect to happen:** The message 'you join the cable coils to form X lengths of wire' to pop up, and the cable coil module to be filled with the corresponding amount.

**What happened instead:** Nothing.

**Why is this bad/What are the consequences:** Means you have to recharge between solars, instead of using one of the conveniently-placed-for-this-purpose cable coils floating around the arrays. Makes it more of a hassle to fix other wiring, when you can't pick up pieces anymore.

**Steps to reproduce the problem:**
1. Activate cable coil module
2. Use up some wire
3. Click cable coil lying on the floor

**Possibly related stuff:** Only tried with the cable coils on the solar arrays.

**Comment by YakumoChen** [comment]
Actually from what I've seen, I've only been able to collect wire from red cable coil as engineer. Might be part of a different but related bug.

**Comment by Braincake** [comment]
I'm having no trouble joining differently coloured coils together as a normal boring human, so I'm guessing it's borg-exclusive. Assuming we're trying the same thing, ofcourse.

**Comment by Braincake** [comment]
Some more experimenting later, and it turns out the cable coils in Engineering work fine, but the ones next to the Solars and the ones in Art Storage don't.
