### ISSUE TITLE
Metastation Soulstone isn't fair

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#14249]
I just lost a round as a lich wizard on metastation because right as I died, right as I hit the RISE button to respawn, the chaplain walks up to me and soulstones me, and I can't respawn. Why the fuck does the chaplain have a soulstone? What would he use it for in any normal circumstance?
It's like, a guaranteed removal from the round for respawning antags, or an antag chaplain's assassinate target.

**Comment by Supermichael777** [comment]
It used to be the unusable kind BUT NO THE POWERGAME DEMANDS THE REAL THING. Should be a resprited glass novelty.

**Comment by killerx09** [comment]
That's pretty much the theme of metastation, people start with extra stuff. Warden starts with an autorifle, there's a clusterbang in the toy display, engineers and atmos technicians start off with foam grenades, etc.

**Comment by KorPhaeron** [comment]
Outplayed

**Comment by Aloraydrel** [comment]
don't die next time tbh

**Comment by CPTANT** [comment]
O no, there is a map in which the completely broken insta respawn lich ability actually has a counter!

**Comment by Cebasiz** [comment]
i ded pls nerf

**Comment by PKPenguin321** [comment]
This would also cuck lings

**Comment by Metacide** [comment]
It's a one use dead-is-dead sort of thing, right? Perhaps a bit shitty / dull to use as an antag on lowpop, but as a crewmember against an antag it sounds more like a mildly neat novelty. I guess perhaps if this happens every round it's a bit tiresome, but eh. 

Crew can't really use it on each other unless certain they're using it on a dead antag. And if they're sure enough you're an antag and you're dead, it doesn't seem that unfair that people can occasionally get around special-snowflake resurrection abilities.

If it gets used a lot people will get used to trying to secure it to prevent its use anyway, so I really don't think this is much of a problem.

**Comment by Dorsisdwarf** [comment]
CRUSHING
