### ISSUE TITLE
Self respiration doesn't actually give you nobreath

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14257]
It just gives you enough Salbutamol to stop oxyloss damage.

Meaning you can actually suffocate in CO2 and N2O knockout, drops stuff due to smoke, ect.

**Comment by PKPenguin321** [comment]
Pretty sure this is a dupe

**Comment by LanCartwright** [comment]
I don't think so.
https://github.com/tgstation/-tg-station/issues/13660 is a different issue.

**Comment by swankcookie** [comment]
Also it's closed now, so it's moot.

**Comment by swankcookie** [comment]
NOBREATH just has too be established

**Comment by AlexanderUlanH** [comment]
I'm pretty sure that's the intended behavior.  It always caused you to produce chemicals which prevented you from taking oxygen damage.  There's no reason that would prevent things like damage from plasma or knockout from N2O.
Players with self-respiration can avoid stuff like that by equipping internals and setting them to 1kPa.

**Comment by Dorsisdwarf** [comment]
Looks like intended feet.

**Comment by tkdrg** [comment]
yes it is
