### ISSUE TITLE
Lava turfs never stop processing once started.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#14260]
Which is an issue for the lava away mission, since the infinitely spawning skeletons, and the goliath and spiders, do not avoid walking on lava. It slowly activates all lava turfs bordering solid floor as more and more skeletons randomly walk around.

https://github.com/tgstation/-tg-station/blob/6483f9bb7870f4af2d3151ffa18b73771a3c4b68/code/game/turfs/simulated/floor/plating.dm#L196
`if(!contents)` is never true because contents is a list. And unfortunately we can't use contents.len instead since there is a light object on every lava turf.

@KorPhaeron

**Comment by KorPhaeron** [comment]
We could just go back to only activating on entered. It'd mean people could slowly, slowly cross lava in fireproof suits by healing after every step, but that is probably better than this.

@RemieRichards help

**Comment by tkdrg** [comment]
`if(contents.len > 1)`?

**Comment by phil235** [comment]
Apparently the infinitely spawning goliath are even worse, they seems to be able to walk on multiple lava floor before dying. 

And there seems to be a bug when they die. Sometimes their icon does not change to the dead sprite.
