### ISSUE TITLE
Containment field shocking a mob gives two shock messages.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#14269]
"The monkey (950) was shocked by Containment Field!"
"monkey (950) was shocked by the Containment Field!"

It happens because electrocute_act() already gives a message, and the shock() proc of the field adds another. https://github.com/tgstation/-tg-station/blob/cb27e966eb58836fe855ca300dc371e6a02199cb/code/modules/power/singularity/containment_field.dm#L96

Also, both messages are missing a "the".

**Comment by Jalleo** [comment]
Its a fair bit of redundant stuff in the containment code.
