### ISSUE TITLE
Wine served on shot glass becomes "...what?"

### ISSUE THREAD

**Issue by coalescentwinter** [tgstation/-tg-station#14267]
Started round as Bartender, so I began placing shot glasses and a bottle of wine on the table. I served them, but they became shot glasses of "...what?".

I tried then to fill the shot glass with Wine from the booze dispenser, but it produced the same effect. Regular drinking glasses do not have this issue.

**Comment by PKPenguin321** [comment]
Shot glasses do this with most drinks, they only work with very specific drinks. Technically it's intended but it's really dumb

**Comment by Supermichael777** [comment]
What kind of craven oaf would drink wine from shot glasses? you need a goblet or stem glass to truly preform a poncy swirl.

**Comment by SouDescolado** [comment]
The text part is easy. But this requires adding a new sprites for new things. At least for what I checked, there is no "purple" or "red" iconstates for the shot glasses.

Also, I vote for, whoever fixes the text, insert Supermichael777 comment as the actual in-game description.
