### ISSUE TITLE
The wizard Moist Nugget thing is really strong

### ISSUE THREAD

**Issue by as334** [tgstation/-tg-station#14265]
They can just shoot massive chains of bullet hell everywhere, could definitely use a nerf.

**Comment by swankcookie** [comment]
Can you elaborate on the "moist nugget thing"?

**Comment by as334** [comment]
Moison Nagant or whatever it's called. It's nickname is the Moist Nugget.

**Comment by Aranclanos** [comment]
please use the proper forums for feedback
