### ISSUE TITLE
Snowed in Away mission mobs are sprites.

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14275]
![sybil military hangar 97 2016-01-01 230614](https://cloud.githubusercontent.com/assets/13142400/12072629/a688ce34-b0e0-11e5-92b4-fb86cf3e31ea.png)
![sybil military hangar 97 2016-01-01 230857](https://cloud.githubusercontent.com/assets/13142400/12072631/b2565376-b0e0-11e5-9348-d725713573c4.png)

These two are floorsprites.

**Comment by swankcookie** [comment]
as in they don't rotate or move?

**Comment by WJohn** [comment]
Could you elaborate at all? What two are floorsprites? The mobs look like floor tiles?

**Comment by swankcookie** [comment]
paging @MMMiracles

**Comment by LanCartwright** [comment]
They do not move or rotate. 
These are not mobs. You cannot attack these.
These can possibly be floor tiles (I didn't crowbar them).

Several mobs seem to be bugged where they show the underfloor Sprite when they move.

Example would be a polar bear that makes the snow tile it's standing on look like a frozen floor tile Sprite

**Comment by RemieRichards** [comment]
![mob1](https://cloud.githubusercontent.com/assets/4043781/12074334/cdf186f0-b144-11e5-9216-58099c90f245.png)
![mob2](https://cloud.githubusercontent.com/assets/4043781/12074335/d643d36c-b144-11e5-953f-d6f6e5572c89.png)

Are you SURE they're not mobs?

**Comment by LanCartwright** [comment]
I'm 100% sure Remie. I mistook that bear and emptied a shotgun only to realise there was nothing there.

Same with the Eskimo. I right clicked it thinking it was a mob I had to kill, but nope it's just a floor Sprite/mob doesn't exist.

**Comment by RemieRichards** [comment]
They're identical to the other mobs on the map though...

**Comment by LanCartwright** [comment]
That's really strange. This will need reproducing then.

I'll try and run a few rounds when I get back from work and I'll feed back then.

**Comment by MMMiracles** [comment]
From what I can tell, the original turf the mobs spawn on will have the mob's icon on them, but not actually be there. The mob will copy the icon of the turf below it and essentially walk around with a plating under it forever afterwards, leaving a 'fake' mob there.

I've only seen similar happen when putting multiple turfs on-top of each other (plating+dust overlay), but the snow plating is just one turf so I dunno. Only happens on the snow plating turf.

**Comment by Anonus** [comment]
The snow plating isn't one turf, you can see it's got normal plating under it.
This looks like turf underlays fucking up and getting stuff they shouldn't underlay as underlays.

**Comment by MMMiracles** [comment]
I don't understand how there's even plating there to begin with when I mass-replaced all of the old snow with the snow-covered plating.

**Comment by Anonus** [comment]
If there's any transparency in a turf sprite, byond won't remove the old turf, instead just putting it as an underlay on the transparent turf.
