### ISSUE TITLE
Cryo constantly beeps when set to manual eject with a healthy person in it.

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#14288]
As the title - when a healthy person has been trapped in cryo by setting it to manual eject the cryo tube will constantly make the cryo opening sound even though it isn't opening.

**Comment by tkdrg** [comment]
I thought this was intended, to warn doctors that he was ready. Also a reminder that this doesn't trap the person, you can just press "resist" and then wait.

**Comment by neersighted** [comment]
Yeah, this is not a bug. It is kind annoying, but its hard to play only once. If someone wants to make it ding only once, go ahead.

**Comment by neersighted** [comment]
Fixed in #14761
