### ISSUE TITLE
escape pod problem

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#14294]
Step 1: be on an escape pod traveling to centcom

Step 2: send pod to mining while in transit to centcom

Step 3: escape pod gets sent to mining but your mob stays on the travel screen in space so you die

Maybe disable being able to send the pod to mining after it has already left to centcom?

**Comment by Zilenan91** [comment]
there's a pr up that's fixing this

**Comment by Dicks1** [comment]
Wow that was fast good work it only took you less than a minute to fix this issue.

**Comment by Zilenan91** [comment]
It was up before this issue report was even made, can you close this?

**Comment by Dorsisdwarf** [comment]
Not until the PR is merged.
