### ISSUE TITLE
Mob being deleted while you are grabbing it irreversibly breaks your movement

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14291]
Reply PM from-IcePacks/(Bryce Pax): you briefly can't move if you grab a mob, since the cockroach(?|F) gets gibbed (and i assume is deleted) it just never ends the delay 

Happened with a roach. Problem persisted even after I ghosted him and made a new body, so it may have fucked up his client.

**Comment by Jalleo** [comment]
Did he try pulling anything else first to see if that fixed the movement?

**Comment by Zilenan91** [comment]
Or dropping the grab?

**Comment by Badspler** [comment]
From experiencing this bug i can say:
The grab disappears from hand when the roach gets killed so you are not able to drop anything (as it is now an empty hand).
Pulling anything does not solve the problem.
As Kor mentioned, a new body did not fix the issue.

**Comment by phil235** [comment]
It only happens when you grab the cockroach and walk over it, squashing it.
