### ISSUE TITLE
player controlled normal hivebots can't die

### ISSUE THREAD

**Issue by fonedsky** [tgstation/-tg-station#14305]
![ehs](https://cloud.githubusercontent.com/assets/16521144/12076447/dfb7e750-b192-11e5-8d30-667ac1ca2839.png)

see this ^
i was repeatedly lasered, then clawed myself like a bunch of times, then suicided, most of those happened in the station, during most of the time i was at 0% health and constantly sparking (which might ignite a fire)
i saw another hivebot sparking like hell too, if this happens to all player controlled hivebots this might be incredibly abusable by evil xenobiologists

**Comment by AnturK** [comment]
#14293 fixes this

**Comment by WJohn** [comment]
Dupe of #14287
