### ISSUE TITLE
holoparasites are not fired upon by AI laser turrets

### ISSUE THREAD

**Issue by Cebasiz** [tgstation/-tg-station#14303]
probably a faction issue, i'd guess. had a holoparasite walk into my core past all my turrets and beat me to death after someone put a c4 on a wall from the storage room. 

at no point did the turrets open or do anything. is this intended? i mean, technically it's probably a sillicon creature.. maybe.

anyway just thought i'd report for curiosity's sake.

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
Dupe issue

https://github.com/tgstation/-tg-station/issues/14097

Already a fix up as well
