### ISSUE TITLE
changeling form swap ability force ghosts the victim

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#14310]

**Comment by hornygranny** [comment]
@Ikarrus very nice

**Comment by Ikarrus** [comment]
I have no idea what this means

**Comment by hornygranny** [comment]
when you use the changeling form swap ability from this pr https://github.com/tgstation/-tg-station/pull/10585 the victim gets kicked out as a ghost and their body is catatonic

**Comment by Metacide** [comment]
You said you were going to put changeling to 0% chance until this is fixed, right?

Perhaps it can stay off until someone rebalances it? Virtually everyone hates it.

**Comment by Ikarrus** [comment]
I made this many months ago and it was fine when I tested it. Perhaps something else broke it?

Either way I'm sorry, I'm so removed from the project these days that any kind of fix from me should not be expected any time soon.

**Comment by hornygranny** [comment]
better just leave ling off

**Comment by Zilenan91** [comment]
I think I remember this being a bug a month or so ago that got fixed and has apparently broken again.
