### ISSUE TITLE
bio bags don't work 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14316]
they don't pick up things en masse

@bgobandit this is your's I think

**Comment by PKPenguin321** [comment]
probably a dupe of https://github.com/tgstation/-tg-station/issues/13116

**Comment by Bawhoppen** [comment]
a dupe of a dupe? whoa

**Comment by PKPenguin321** [comment]
yeah this issue keeps getting reported but never fixed

**Comment by Bawhoppen** [comment]
fucking bgo
