### ISSUE TITLE
research station away mission npcs I guess

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14319]
![ss 2016-01-02 at 02 45 05](https://cloud.githubusercontent.com/assets/6510293/12076979/92ac7748-b18b-11e5-89c8-e0f7ec2f0505.png)

:fried_shrimp:

**Comment by Bawhoppen** [comment]
:gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun:

**Comment by Zilenan91** [comment]
lmao yeah they shoot at eachother all round and hit the walls. Way to fix it would be to make them melee mobs I guess.

**Comment by tkdrg** [comment]
@MMMiracles you probably botched the faction stuff since they're targetting each other

**Comment by tkdrg** [comment]
whoops

**Comment by Bawhoppen** [comment]
they're supposed to be targeting each other cause some are syndies some are nanotrasen

**Comment by MMMiracles** [comment]
yeah theres two different factions, syndicate and nanotrasen. all fights I saw from them finding eachother always ended in one side winning, never a stalemate like this.

i blame infinite bullets.

**Comment by Bawhoppen** [comment]
I'd blame the simple mob AI
