### ISSUE TITLE
L6 Saw LMG has a bunch of unused (broken?) inhand states

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14315]
![unused](https://cloud.githubusercontent.com/assets/8345184/12076823/94c4ff4c-b171-11e5-8e73-ebc9ae01fb8d.png)
Only "l6closedmag" is used.
I'm not sure if these are unused or broken, but if they're unused they can just be removed.

**Comment by WJohn** [comment]
They're just unused, but so are like a trillion other sprites. This is a complete non-issue.
