### ISSUE TITLE
Abandoned crate TK injector doesn't work

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14332]
HELP: Kel the Oblivious/(Immo Late) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): The power injectors found in abandoned crates don't work. Thought they were supposed to be like the TK injector in the sith bundle. Because I just found an X-Ray, and it did nothing for me.

**Comment by Zilenan91** [comment]
I forgot to issue report this, but the laser eyes DNA injector on Snowdin doesn't work either.
