### ISSUE TITLE
Odd behaviour when my ATV was shot

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14358]
My ATV was shot out from under me by a nuke op, leaving me unable to move. Didnt seem to be any messages about the ATV being hit or destroyrd either.

I died shortly after so I didnt get to troubleshoot the issue.

**Comment by phil235** [comment]
You mean it was destroyed? By what kind of projectile or weapon? What kind of mob were you?

**Comment by KorPhaeron** [comment]
Human, riding snowdin ATV, shot by some sort of rapid fire nuke op gun (the carbine or the c20r)

It's also possible that I got stunned and the atv kept moving without me, but I definitely got frozen in place and my ride vanished

**Comment by Durkel** [comment]
Sounds like a case of the ghostride(r)

**Comment by tkdrg** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
Not sure what could cause this.

**Comment by Dorsisdwarf** [comment]
I saw this, the nuke op had the syndie carbine, without grenades.

**Comment by KorPhaeron** [comment]
Hasn't been reproduced
