### ISSUE TITLE
cockroach guts are all snowflakey

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14359]
why can they be dragged

**Comment by swankcookie** [comment]
I'm on the case.

**Comment by phil235** [comment]
Because some shitty old coder didn't think it would be good to give anchored = 1 to obj/effect/decal/cleanable , and prefered to manually give it to each and every child of it...

**Comment by KazeEspada** [comment]
Cleanables are draggable? Who knew?
