### ISSUE TITLE
Metastation Janitor's Closet

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14374]
The level 3 biohazard locker keeps getting pushed around by what I assume to be air every round near roundstart.

**Comment by KorPhaeron** [comment]
Are you sure it isnt the lizard?

**Comment by Zilenan91** [comment]
I'm pretty sure, but it might be the lizard. I didn't think that it would be able to move around lockers since most mobs of that size can't push things.

**Comment by WJohn** [comment]
Little lizards can definitely push around lockers, I just tested this.

**Comment by Zilenan91** [comment]
Gonna close this then and start killing the lizard because it's really annoying.

**Comment by duncathan** [comment]
I thought we were talking about liggers

**Comment by Zilenan91** [comment]
lmao yeah the janitor on Meta has a pet little lizard called Wags-his-tail I think
