### ISSUE TITLE
Unable to move new Nano UI windows

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#14378]
As the title says, we are unable to click+drag to move the new Nano UI windows that pops up when we use something, making it quite bloody annoying.

This is definitely a usability issue.

**Comment by xxalpha** [comment]
@neersighted

**Comment by neersighted** [comment]
If the default behavior continues to bother you, please change your `tgui Style` pref to `No Frills`.

However, I believe 1f4017855aaffb8e9cf20937b2bba8ae60471265 resolved this as the drag/resize code was rewritten. If not, please provide a video/gif of the problem.

**Comment by neersighted** [comment]
After talking to @Firecage on IRC, it turned out he is on IE8. Either he needs to update or he needs to set his Style to `No Frills`.

**Comment by duncathan** [comment]
If it's shown that no frills fixes this, I'll close it

**Comment by neersighted** [comment]
![Demo](http://vgy.me/NmMBcD.gif)

Yes, it does...

**Comment by neersighted** [comment]
This was caused by WebReflection/ie8#24 evidently, which has now been fixed as well.

**Comment by neersighted** [comment]
@Cheridan muh cheribucks pls
