### ISSUE TITLE
Cult bug

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14375]
I don't think it's intentional that harvesters don't have cult chat, they used to have it before the rework.

**Comment by Changelingrain** [comment]
It is intentional, kor changed harvesters to not be cultists.
This doesn't mean it's wise it's kind of silly honestly

**Comment by Zilenan91** [comment]
Can't they just be given the ability to hear and/or use chat without actually being classified as cultists?

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg

I removed harvesters so the round end report was readable, and to end the confusion over whether or not they should kill cultists.

I guess they could get the commune power domehow

**Comment by Dorsisdwarf** [comment]
forumm?
