### ISSUE TITLE
Cabin 6 on metastation has a vestigal air pump

### ISSUE THREAD

**Issue by Arquebusier** [tgstation/-tg-station#14377]
![](http://puu.sh/mj9wI/4035cbbfd0.png)

**Comment by swankcookie** [comment]
Meaning it is unconnected?

**Comment by PKPenguin321** [comment]
it means look with your eyes, dingus, there are two of them

**Comment by KorPhaeron** [comment]
I will fix this when I add a camera to the kill chamber
