### ISSUE TITLE
Implant breakers always get resisted on dead gangster

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14380]
I was a regular goon, got dunked, got implant breakered while dead, and it resisted, ending my round because they immediately spaced me.

**Comment by swankcookie** [comment]
I think it's bad manners to self [important].

**Comment by Zilenan91** [comment]
boo

**Comment by swankcookie** [comment]
Just to be clear: you were loyalty implanted, and then the implant breaker did not work on you?

**Comment by Zilenan91** [comment]
I was not loyalty implanted, I was a regular gangster. I died, and my dead body resisted an implant breaker to degang me so I got spaced

**Comment by swankcookie** [comment]
Sec used an implant breaker on you? Or did they try to loyalty implant you? Implant breakers are gang tools.

**Comment by Zilenan91** [comment]
No a gang boss used an implant breaker on me to get rid of my gang status. Implant breakers from the gang tool.

**Comment by LatD** [comment]
Code seems to check if the person is dead. Either it should give a different message like "The target must be alive" or the dead check should just be removed.

How do other implants work? I can't see a dead check in loyalty implant code.

**Comment by swankcookie** [comment]
Yeah,  I'm not sure why the dead check is there, doesn't seem neccesary too me.
