### ISSUE TITLE
Cockroaches ruin the PA

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14393]
They all run into it and rotate the pieces/send them everywhere

**Comment by Changelingrain** [comment]
Also the cockroach sprite is really, really similar to goon's and it's honestly terrible
![noreally](http://puu.sh/mjLIf/7c5122f99f.png)
![guess which](http://puu.sh/mjLHi/377ab8a6c1.png)

**Comment by optimumtact** [comment]
that's hilarious

**Comment by phil235** [comment]
I see two solutions:
* making cockroaches not spawn in engineering.
* creating a PASSMACHINERY flag just for the cockroach and rewrite the CanPass() proc of all machinery objects so that the cockroach passes through the PA parts instead of pushing them.

**Comment by optimumtact** [comment]
I prefer players not whining about something that isn't really an issue.

**Comment by Dorsisdwarf** [comment]
1) squash cockroach
2) put PA back
