### ISSUE TITLE
Fusion completely fucks up pipes/ no way of removing fusion pressures from pipes

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#14396]
Pipes in which fusion happen go to pressures and temperatures of over 10^10. There is nothing in the game that can handle removing such insane pressures, meaning the pipes stay at these extreme pressures the rest of the game.

**Comment by KazeEspada** [comment]
Unwrench them, that will release the pressure.

**Comment by CPTANT** [comment]
Yes that is very nice except for the pressure wave of 10^10 Kpa at 10^11 Kelvin obliterating the side of the station you are in.

**Comment by Changelingrain** [comment]
rcd the floors around the pipe, brace yourself against a welding fuel tank, and unwrench

**Comment by Supermichael777** [comment]
Fun fact:pipes do nothing when unwrenched but throw you back. they don't even add pressure to the tile. also fuck fusion its so broken it has no real use and damages the usability of other features

**Comment by CPTANT** [comment]
pipes don't release contents any more? I am almost certain that they used to release their content when unwrenched.
