### ISSUE TITLE
Fusion cannister does not release contents

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#14398]
Despite having pressures and temperatures above 10^10 certain cannisters refuse to expel their contents when opened.

Probably caused because while these cannisters have extreme pressures, they contain a tiny amount of moles.

related to issue #13671 but concerns tanks releasing to the outside.

**Comment by Supermichael777** [comment]
absouloutly terible. literally removes value from the game by making features more obtuse than they need to be. It would be a neat feture if thier were ways to work around it but it makes the only way to reliably heat gas to the tempitures required for *fun* useless

**Comment by killerx09** [comment]
Not true, if you open the valve, the fusion gas inside will flow out. The sheer temperature will break the gas cannister though.

**Comment by CPTANT** [comment]
it IS true for a lot of cannisters, the ones with a lot of moles in them still work.
