### ISSUE TITLE
[Important] Caves.dmm Construct bug that kicks several people out of their clients

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14408]
I got shaded with a soulstone and my Dream Seeker was constantly crashing to the point that I literally couldn't even play the game. This needs to be fixed pronto because it makes the game completely unplayable.

Until this is fixed please disable cult from rotation because this kicks people out of the entire game at the moment.

**Comment by swankcookie** [comment]
>[Important]

**Comment by swankcookie** [comment]
Do you know if anyone else has had this problem?

**Comment by Zilenan91** [comment]
Yeah all constructs have been bugged for a while. Whenever someone is shoved into a shell they mysteriously ghost out a few minutes later. Their client gets fucked, and the only way the constructs reactivate is if an admin puts someone else inside of them.

**Comment by KazeEspada** [comment]
Its not constructs. Its Caves.dmm.
