### ISSUE TITLE
Caves.dmm spawns WAY WAY WAYYYYYYYYYYYYYYY to many skeletons.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14411]
So many in fact that it causes the entire Z-level to crash all clients(on the Z-level) as Byond goes into an infinite loop for some reason trying to render them all.

**Comment by Zilenan91** [comment]
So should I close my other issue?

**Comment by MrStonedOne** [comment]
Its not the skeletons, its lava pits burning them.

This was a bug introduced by me on the recommendation of RR

**Comment by Zilenan91** [comment]
I knew it, I lagged super hard when I saw all the burning skeletons

**Comment by MMMiracles** [comment]
Never enough skeletons.

**Comment by hornygranny** [comment]
i turned off caves until this is fixed
