### ISSUE TITLE
Players not being put in control of shades/constructs

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#14418]
I've seen constructs and soul stones inexplicably have no ckey despite being created from a non-jobbanned player several times.

**Comment by tkdrg** [comment]
@AnturK

**Comment by AnturK** [comment]
Not sure what i have to do with this but i can look into it.

**Comment by tkdrg** [comment]
Oh I thought it was related to your mindless shade fix. My bad.
