### ISSUE TITLE
Artificer didn't get cult HUD

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14415]
HELP: Gouty/(Artificer (698)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): why don't I have a cult HUD? I can't see who is cult 

Reply PM from-Gouty/(Artificer (698)): Messagebox, I clicked yes to be a shade, then I was put in an Arti shell 

Reply PM from-Gouty/(Artificer (698)): I was a Arti before and died, and then got back in the game as a shade 

His traitor panel said he was a cultist and he was on the round end report

**Comment by tkdrg** [comment]
This is probably because of the hacky way that the "turn ghost into shade" thing works (setting the shade's client without transferring mind) violates some of the assumptions of the HUD code.
