### ISSUE TITLE
holoparasite user death breaks internal helmets on space suits

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#14413]
@KorPhaeron 

my guess is that the check for unequipping all their equipment fails on the helmet, so it gets qdel'd

**Comment by KorPhaeron** [comment]
Dupe issue

**Comment by KorPhaeron** [comment]
Also no idea how to fix it

**Comment by hornygranny** [comment]
isn't that how the sprayer works

**Comment by phil235** [comment]
HG is correct, this bugs happens every time we try to unequip everything on a mob (admin's Drop Everything, holoparasite user death, etc..)
