### ISSUE TITLE
The changes to Salicyclic Acid were unintentionally reverted

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#14410]
At some point after PR #13941, Salicyclic Acid was accidentally reverted to it's previous, largely useless state, possibly by the PR that added Haloperidol.

**Comment by optimumtact** [comment]
Your changes appear to be present on  the master branch, where did you test this?

**Comment by optimumtact** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/chemistry/reagents/medicine_reagents.dm#L390

for reference

**Comment by Buggy123** [comment]
Whoops, I double checked and apparently I was browsing a older version of the code at the time, sorry about that.
