### ISSUE TITLE
Windows pop up keeps opening after you close them

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14424]
This issue was observed in mulebots mainly, which the window keep refreshing and keeps opening after you close it. I also experienced with Beepsky, but not really sure how to reproduce.

**Comment by tkdrg** [comment]
@neersighted

**Comment by neersighted** [comment]
Probably some updateUsrDialog nonsense... I might as well tgui these things.

**Comment by bgobandit** [comment]
still happening, mulebots in particular
