### ISSUE TITLE
Summon Events' change faces does not change human/lizard speech

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#14431]
Which means that you can be swapped to a human voice and ssstill talk like thisss.

**Comment by KorPhaeron** [comment]
It's magic aint gotta explain shit

**Comment by Incoming5643** [comment]
It's change faces, not swap voices. Could be fixed, but not really a bug.

**Comment by Dorsisdwarf** [comment]
Also wait I have a mandate to crush feature requests
