### ISSUE TITLE
Large cardboard boxes remove all contents inside when burned

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/-tg-station#14445]
**Problem Description:** When you set a large cardboard box on fire, after it's done all that remains is ashes.

**What did you expect to happen:** I expected items inside to be ejected after the box burns.

**What happened instead:** Items and a mob have been removed from the plane of existance.

**Why is this bad/What are the consequences:** It can be used to get rid of bodies, permanently.

**Steps to reproduce the problem:** 
1.Spawn a box.
2.Spawn plasma somewhere nearby.
3.Ignite the plasma, get inside the box.
4.Make sure to set the box on fire.

**Server:** Basil

Server revision compiled on: 2016-01-04
797bfe01efdea70ce8202a318183b8acc833fc81 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):** Stepped on a bwoink mine while moving inside the box with plasma in the air.

**Comment by Jalleo** [comment]
Ill check the code tomorrow if nobody beats me to it.

**Comment by Zilenan91** [comment]
They also delete everything inside of them if they get blown up too, even on an explosion that wouldn't have killed somebody.
