### ISSUE TITLE
Negative pressure/temperature at fusion/space interface

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#14443]
Released a fusion cannister near space, measured the resulting temperatures, vastly negative Kelvin.

[img]http://i.imgur.com/KabrJDP.png[/img]

**Comment by Zilenan91** [comment]
Wait hang on, does this mean you can release something like this in atmos and it'll pipe out ungodly cold air through the pipes?

**Comment by CPTANT** [comment]
I have no idea how vents and such react to negative pressures.

**Comment by Zilenan91** [comment]
Wait negative pressure? Is that even physically possible irl? I think the ungodly low temperature could probably be a feature but not the pressure.

**Comment by CPTANT** [comment]
No, both are retarded in a physical sense.

It is minus 15,000 KELVIN

**Comment by duncathan** [comment]
Oh my god I'm so happy that this bug exists
Looks like there's an issue with the logic of `temperature_share()` causing this which is likely also the cause of the problems I've been having with listmos

**Comment by duncathan** [comment]
Also the negative pressure occurs because of the negative temperature; this is simply a temperature bug

**Comment by CPTANT** [comment]
found something similar.

Had fusion going on in a room, opened the door, temperature and pressure in the door DROPPED. Not to negative levels but they kept dropping for a while, then the fusion suddenly did spread.

**Comment by WJohn** [comment]
God atmos is so broken since fusion.

**Comment by Zilenan91** [comment]
How do you even harvest energy from fusion? It straight up breaks the turbine so I don't know what the functional use of this is outside of mass murder of the entire station with a single canister.

**Comment by duncathan** [comment]
@Wjohn atmos was broken before fusion; fusion just revealed the breaks

**Comment by CPTANT** [comment]
Atmos wasn't broken, it just wasn't designed to handle such extreme numbers as fusion introduces to the game.

Also fusion for turbine is pointless, max turbine output is around 100,000W anyway.

**Comment by Jalleo** [comment]
We really need to redesign a few things.

**Comment by xxalpha** [comment]
Just drag a picture to the text box to upload it to github, @CPTANT.

**Comment by newfren** [comment]
Atmos wasn't broken someone just exceeded the factor of safety.

You wouldn't say a rope bridge was broken if it wasn't strong enough to handle a fuel tanker (except maybe afterwards, when the tanker has torn the rope bridge from its bonds).
