### ISSUE TITLE
Buttons no longer work when spawned in

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#14467]
Steps to reproduce
spawn door control button, the ones that control shutters and what not
spawn in some shutters or poddoors/blast doors
set the IDs to the exact same thing "test" or something
press button and nothing happens

I've reproduced it over and over again so unless I'm doing something wrong, buttons are broke, but the ones on the existing maps seem to work fine.

**Comment by swankcookie** [comment]
I had this same problem attempting too fix #13894, but i just assumed i was doing something wrong.

**Comment by WJohn** [comment]
I swear I made an issue report on this, but yeah I noticed this a couple months back where buttons don't work in away missions.
