### ISSUE TITLE
The asteroid appears to have abnormally high uranium spawn rates.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#14461]
This is 100% a higgs-bugson at the moment, but anecdotally, uranium spawns MUCH more frequently on the Box/Meta/etc asteroid than on, say, AsteroidStation, which uses a different map. This is consistent among many, many mining rounds I've played. I didn't touch spawnrate in my changes; I suspect the culprit is the spiky asteroid somehow. Currently the points and R&D systems are calibrated for uranium being rarer than it is, so idk.

(also please fix lootrooms with the spiky asteroid goddamn)

**Comment by AlexanderUlanH** [comment]
![321a39e06d6401301d80001dd8b71c47](https://cloud.githubusercontent.com/assets/4391822/12160497/93074132-b4ba-11e5-9010-133c3ecd7896.gif)

**Comment by KazeEspada** [comment]
I think I have the answer. Ore load size, plasma and iron generate bigger deposits. The spiky asteroid has less room for the big deposits so they fail more often, and instead it generates a smaller deposite such as uranium.

**Comment by bgobandit** [comment]
By "ore load size" do you mean spread, or do you mean ores per deposit? The latter should be random 1-5 across the board unless someone else fucked with it.

**Comment by newfren** [comment]
Pretty sure he means like how plasma and iron ore comes in "chunks" of ores where there's often several ore tiles near each other, but the spiky asteroid doesn't allow for all those chunks of ore next to each other so it has it spawn more uranium (and presumably, diamond) on the spiky asteroid.

**Comment by KorPhaeron** [comment]
@KazeEspada 

Please do not wildly make shit up, that doesn't help fix the bug at all

@bgobandit 

Spawn rates are determined by RNG/the weighting from the type of mine turf (random, high chance, low chance, or none).  It's possible the asteroid remap put more high chance turfs.

**Comment by KorPhaeron** [comment]
Also this is not at all higgs-bugson.

Add debug text to give you the total number of mineral turfs, and the total number of mineral turfs that spawn uranium. Run both maps and see what numbers you get.

**Comment by tkdrg** [comment]
The asteroid remap put around 1.4% more high chance turfs. Not sure if that would be perceivable.

**Comment by bgobandit** [comment]
I'm not sure that's the culprit because this happens everywhere including very close to the mining station, which shouldn't be high-chance turf territory.

I'm serious about this, play a bunch of mining on box/meta and then on Asteroid and see the difference.

**Comment by KorPhaeron** [comment]
>Add debug text to give you the total number of mineral turfs, and the total number of mineral turfs that spawn uranium. Run both maps and see what numbers you get.

**Comment by duncathan** [comment]
Did kor's test but forgot to screenshot. There was like, a 1% difference. Seems to be placebo
