### ISSUE TITLE
Detomatix cartridges require being an operative to use.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14470]

**Comment by swankcookie** [comment]
At what point did it not work? Could you open your PDA? Did  it just act as though nothing was inserted?

**Comment by KazeEspada** [comment]
Upon hitting the detonate button it didnt work.

**Comment by KorPhaeron** [comment]
Did it give you an error message or anything or just nothing happened when you hit the button?

**Comment by swankcookie** [comment]
See if it threw up a runtime,  as well.

**Comment by PKPenguin321** [comment]
were you trying to blow up your assassination target's PDA? because if it was DA and he was also a traitor, it's hardcoded to fail

**Comment by KazeEspada** [comment]
It gave an error message, and I dont think it caused a runtime. I think it was DA and he was also a traitor.

**Comment by PKPenguin321** [comment]
non-issue then, this is 100% intended and functional
