### ISSUE TITLE
SimpleAnimal bots vanish when hit with resurrecting bolts.

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14473]
Shoot them with bolts of resurrection. They just completely dissapear.

**Comment by newfren** [comment]
Why would you title an issue report like a clickbait article.

READ INSIDE FOR 8 COOL BUGS YOU CAN ABUSE ON SIMPLE BOTS!

**Comment by Zilenan91** [comment]
I couldn't fit that many words in the title

**Comment by newfren** [comment]
o ok

cool bug

**Comment by Dorsisdwarf** [comment]
Is simple ja
