### ISSUE TITLE
Revenants can't harvest braindeads

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14478]
It says their soul is too strong but they don't have souls anymore

**Comment by WJohn** [comment]
Do you mean ghosted or braindead AFK? If it's the latter, it's a balance issue.

**Comment by Zilenan91** [comment]
Both really since they don't actually have souls left in their bodies. If this gets fixed I'd settle for just catatonics.

**Comment by ChangelingRain** [comment]
This is a feature request honestly and I'm gonna say no, because it's kind of out of theme AND really shitty to DC and then return to a corpse.

**Comment by Zilenan91** [comment]
What about catatonics
