### ISSUE TITLE
Spray tan doesn't tan.

### ISSUE THREAD

**Issue by lordpidey** [tgstation/-tg-station#14477]
Problem Description: Spray tan does not change color of humans.

What did you expect to happen: After applying or overdosing on spray tan, the human would change color.

What happened instead: The human remained the same color.  All other overdose effects remain.

Why is this bad/What are the consequences: 

Steps to reproduce the problem:  Play as human with Caucasian skin. Mix spray tan (oil + orange juice), create 10 patches of 1 unit each.  Apply patches.  Notice lack of skin color change.

Server: Sybil

Revision: What revision was the server running? Server revision compiled on: 2016-01-06
475918b22dba7eb16091bb5972104354fd7a9273 

Possibly related stuff:  Works properly for lizardfolk.  Back when you could see people's skin on examine, it would show the proper skin color on examine.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Wasn't added by me

**Comment by lordpidey** [comment]
I'm the one that added the chemical originally, but the code for the chemical itself hasn't changed.
