### ISSUE TITLE
Discstation issues (esp. botany and kitchen)

### ISSUE THREAD

**Issue by Kuromoi** [tgstation/-tg-station#14486]
Especially regarding Botany, as that's what I was:

Smartfridge does not work, making transferring shit to Kitchen difficult.

Kitchen-Botany windoors face the wrong way.

Botanist Lockers do not have uniforms.

Seed machine is in an awkward place, would be better on the other side of the glass table with a second sink where it currently is.  

Escape shuttle's security wing is accessible by anyone via the external airlock doors, letting prisoners escape.

Fridges and cooking resources (milk etc) that should be in Kitchen are instead in Botany, requiring botany to hand resources over to the chef that hey shoudl already have.

**Comment by Strathcona** [comment]
Thanks for these. These issues, and many more, will be fixed in a complete overhaul of Discstation that is underway.

**Comment by bgobandit** [comment]
should this be closed since disc is no longer supported

**Comment by ChangelingRain** [comment]
Yes.
