### ISSUE TITLE
Metastation maint autodrobe requires wrong access

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14484]
It requires theatre access to use, which is inconsistent with autodrobes on other maps that aren't in the theatre.

**Comment by Metacide** [comment]
Will fix, thanks for heads-up

**Comment by Zilenan91** [comment]
@Metacide Can you also fix the multi-belt that spawns on the map? It's typo'd to be mutli-belt.

**Comment by Metacide** [comment]
@Zilenan91 - have fixed with my latest changes, yup. Just trying to work out an issue before pull-requesting.

**Comment by Zilenan91** [comment]
Has this been fixed?
