### ISSUE TITLE
Spacewind is teleporting people

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14491]
Seen this happen once with an engineer trying to leave containment, and now once with myself.

Space wind is capable of moving you several tiles at once, and it does not do so smoothly. It will teleport you when it pushes.

@neersighted took this gif

http://vgy.me/0AzGzl.gif

@MrStonedOne @duncathan

**Comment by tedward1337** [comment]
Can confirm, also happens at the mining airlock as well.

**Comment by Durkel** [comment]
Seen this happen on the escape shuttle. We were getting lobbed off the shuttle by 5-6 tiles and lost about 10 people from this shit.

**Comment by KorPhaeron** [comment]
That would explain the "help I got spaced from the middle of the shuttle" adminhelps

**Comment by newfren** [comment]
Saw this happen on the wild west away mission as well while trying to enter the maze part.
