### ISSUE TITLE
Experimentor bug

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14496]
After you use it once, and you close the window it will give you a bugged message and bring the window back up again

also readd selfxeno to experimentor while you're at it :wink:

**Comment by tkdrg** [comment]
What's a "bugged message"?

**Comment by Bawhoppen** [comment]
it gives the generic use message, just try it. you'll see
it will keep doing it

**Comment by GunHog** [comment]
I could fix this myself...or wait and let someone else do it for me...hrm...

>also readd selfxeno to experimentor while you're at it :wink:

I loved that feature myself, but it would be too powerful now - do it with a humanized monkey and you have yourself free xeno guts to harvest for surgery and a brain to get Bio 6 easily.

**Comment by Bawhoppen** [comment]
>implying becoming a fucking insta infinite-stun hands vent crawling hyperspeedy antag isn't powerful

**Comment by GunHog** [comment]
You can ban a guy for doing that to himself on purpose. Doing it to a monkey for the sole purpose of looting it is more of a balance issue.
