### ISSUE TITLE
Help/disarm/grab don't work on monkeys 

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14492]
Nothing happens when you click them on these intents

**Comment by phil235** [comment]
It's my fault, I'm retarded, I removed the relevant code in https://github.com/tgstation/-tg-station/pull/14356 , thinking it was code that monkey use to grab people...
:disappointed:

**Comment by swankcookie** [comment]
Why dont you want monkeys to grab people?

**Comment by phil235** [comment]
@swankcookie Monkeys do not have grab or disarm intent in their UI, I thought someone forgot to remove the related code.

**Comment by swankcookie** [comment]
ah
