### ISSUE TITLE
Spray painted graffiti has "drawn in crayon" in its desc

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#14498]
spraycans just make the same thing that crayons do, so its called 'A graffiti drawn in crayon' which doesn't make much sense

Also gangtags place the graffiti on the wall tile itself so its visible on both sides of the wall which doesn't make much sense either

**Comment by KorPhaeron** [comment]
I think this was an intended change so people wouldn't meta that paint=actual gangs

**Comment by Bawhoppen** [comment]
but they couldn't meta it if spraycans made non-crayon too

**Comment by duncathan** [comment]
How often do spraycans get made without gangs around

**Comment by Bawhoppen** [comment]
considering they're a good premade stun without any work not that uncommonly

**Comment by Bawhoppen** [comment]
besides its pretty easy to meta it when theres several of a specific gangtag that are literally on the tile of a wall where you can'tactually get to to draw without dissassembling the wall

**Comment by tkdrg** [comment]
You can also see the desc of a gang can which will have "suspicious paint".
