### ISSUE TITLE
Admin AI interaction

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#14490]
Admin's can still activate canisters/jetpacks, even with admin AI interaction off. Seems like it was missed when it got changed.

**Comment by Shadowlight213** [comment]
That wasn't me actually. @neersighted added that to nanoui stuff.
I focused on stuff the AI could interact with, so it wasn't added to the toggle.

**Comment by neersighted** [comment]
Yeah, this is not a bug. Admins can interact with any tgui. Do you want it moved behind the toggle for safety purposes? tgui interaction is a normal ghost feature (admins can just read and write), where as Admin AI interaction is the admin pretending to be an AI.

**Comment by lzimann** [comment]
I think it would be great to have everything under admin AI interaction, better than clicking in accident something.

**Comment by tkdrg** [comment]
fixed by neer apparently
