### ISSUE TITLE
Snowdin mapping error

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14517]
http://i.imgur.com/ooN497U.png?1

I think 2 pieces of snow walls were mistakenly put there, this means that it's impossible for anyone to get down there to a bunch of mobs and loot without deconstructing/destroying 2 rwalls

**Comment by xxalpha** [comment]
>i think this is a mistake

Did you try asking the map author

**Comment by Zilenan91** [comment]
Why would a mapper make there be no way to get to a certain area without destroying the base they put down.

**Comment by bengin-polyp** [comment]
maybe as a challenge area for when you've bored yourself / acquired all the neato tech for the mission and still want more to do. It also could have been that they thought you could use the sonic jackhammers littered throughout the high risk areas to access other places. Although it is quite annoying that sonic jackhammers don't take down snow walls.

**Comment by Zilenan91** [comment]
Yeah if there was any way to break down snow walls this would be fine but you can't. I tried everything, welders, shovels, all kinds of stuff. I even had one of us shoot fireballs at it and the wall didn't blow up.
