### ISSUE TITLE
Deck of Cards can't be removed from pocket

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#14519]
**Server:** Sybil.

**Revision:** a065241a6931d27eb85a678458845e34b02112f3

**Problem Description:** The usual method of picking up a deck of cards (dragging it onto your sprite) doesn't seem to work when the deck is in your pocket. Clicking it takes a card, as usual.

Removing the pocket slots (removing your uniform) does drop the deck.

**What did you expect to happen:** For the click-drag method to put the deck in your hand.

**What happened instead:** Nothing.

**Why is this bad/What are the consequences:** Makes it annoying to drop decks, the horror!

**Steps to reproduce the problem:**
1. Equip any uniform
2. Put deck of cards in pocket
3. Attempt to remove said deck of cards from said pocket

**Comment by PKPenguin321** [comment]
have you tried dragging them to your hand slot

**Comment by Braincake** [comment]
Yeah, that does work. But consistency, you know.

**Comment by KorPhaeron** [comment]
Clickdragging to your handslot IS consistent with how other items work though (like backpacks)

**Comment by Braincake** [comment]
You make a compelling argument. I suppose this isn't an actual issue.
