### ISSUE TITLE
Syndicate Commando bug

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14516]
If a ghost possesses one of these with the possess verb, they cannot move. Their legs don't work and they're stuck. The only way for them to move is to fire any guns they might have.

The bug seems to exclusive to the hardsuit syndicate simple mobs.

**Comment by Aloraydrel** [comment]
yea seems it was only effecting the hardsuit guys

**Comment by Zilenan91** [comment]
Yeah I think I know what the bug is, the hardsuit mobs seem to permanently lack a gravity effect, so while they can't move with their legs, they can move with their guns.

**Comment by WJohn** [comment]
It's really more an inconsistency. Simple animals can move through space and 0 grav without a problem, but it seems you become a REEL BOY when you take control and have to obey the normal rules??

**Comment by Zilenan91** [comment]
No like even when there's gravity I think the game treats it as there being gravity so you can't move normally as that mob while all the other ones can.

**Comment by tkdrg** [comment]
Fixed by anturk
