### ISSUE TITLE
firearms authentication implant can be removed

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14525]
literally no reason to remove this. QOL fixes.

Maybe make two (one for operator, one for awaymission/loot).

**Comment by KorPhaeron** [comment]
What?

**Comment by LanCartwright** [comment]
You can remove the implants that allow Syndicate firing pins to be used.

Not technically a bug, but this should probably be a fix like Exile+ implant.

**Comment by KorPhaeron** [comment]
Why would you remove it?

**Comment by LanCartwright** [comment]
It just happened.

**Comment by swankcookie** [comment]
Why remove functionality? every other implant can be removed, why should this one be different? maybe i want to be a deep cover agent, and so i have them check me for the implant. Not likely, but whylose something for no gain?

**Comment by PKPenguin321** [comment]
non-issue, this is literally and non-jokingly a feature

**Comment by Zilenan91** [comment]
Yeah close this this isn't an issue

**Comment by Firecage** [comment]
Wasn't the point of the weapons which are restricted to the syndicates, that they shouldn't be usable by the normal crewmembers though? If we are able to remove them, and considering if we remove implants we can use them again, wouldn't that just made said feature slightly redundant?

**Comment by tkdrg** [comment]
not a issue at all
