### ISSUE TITLE
Nukepod seems to be able to be locked by AI

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#14527]
Must reproduce and test.

![image](https://cloud.githubusercontent.com/assets/13142400/12210853/fcef1052-b654-11e5-8072-9709ddd59cf2.png)

**Comment by KorPhaeron** [comment]
Hmm

**Comment by GunHog** [comment]
When the AI tries to access an airlock with the AI wire cut, it enters a 2 minute wait to hack the airlock before gaining access. You can just emag one of the doors open to counter this.

**Comment by KorPhaeron** [comment]
Oh, didnt occur to me to ask. Was this as soon as the pod touched down or after a hack?

**Comment by LanCartwright** [comment]
Probably after a hack.

I'll say a good 95% chance it was hacked by the AI.

**Comment by WJohn** [comment]
Still? I thought this was fixed.

**Comment by KorPhaeron** [comment]
The AI can hack things that are disabled, this is not bugged

**Comment by Bawhoppen** [comment]
ye close this seems intended

**Comment by Zilenan91** [comment]
close it, it's a dupe

**Comment by tkdrg** [comment]
ok then
