### ISSUE TITLE
Critical blood loss knocks you out forever

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#14538]
I'm fine with temporarily falling unsconsious due to blood loss. 
Being in a perma-stun, however, is bad gameplay.

**Comment by KorPhaeron** [comment]
Before someone closes this for "not a bug" please keep in mind you can't succumb in this state, so you're forced to stay unconcious forever (or ghost, and become unclonable)

**Comment by Zilenan91** [comment]
This is also the same with that fucking virus J_Madison made. You're stuck KO'd for a stupid amount of time and can't even ghost out.

**Comment by Buggy123** [comment]
Which virus?

Also, yeah this is a pretty big issue IMO, i've been in this state before and it isn't fun.

**Comment by Shadowlight213** [comment]
N2O does the same exact thing.

**Comment by Zilenan91** [comment]
You wake up from N20 occasionally so you aren't permastunned on the ground though

**Comment by Shadowlight213** [comment]
Nope. You don't wake up. Maybe with super super low concentrations, but I've never woken up from it.

**Comment by Dorsisdwarf** [comment]
I've never *not* woken up from it (in a visible density cloud) at least once. You usually get 1-2 chances to gtfo, of about 2 seconds each, when you run into a cloud. If you're under the pumping vent you're SOL though because you'll hit medical-grade concentrations in seconds.
