### ISSUE TITLE
Derelict chapel mass driver doesn't work properly

### ISSUE THREAD

**Issue by yackemflam** [tgstation/-tg-station#14535]
In the direlect station, the chapel's launcher door does not open in the count down nor does it open when you use the computer to open the door

**Comment by xxalpha** [comment]
Shouldn't be intended, must have broken at some point.

**Comment by Supermichael777** [comment]
i think its in an unpowered area. you can crowbar it.

**Comment by KorPhaeron** [comment]
Dupe

**Comment by Aloraydrel** [comment]
I reported this before tbh

**Comment by Jordie0608** [comment]
#11286
