### ISSUE TITLE
Sleeping carp attacks have no animation.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#14530]
There's nothing to indicate you're hitting people once you've used the scroll. I'm not even sure if the special attacks them self work.

**Comment by Dorsisdwarf** [comment]
@WJohn not a bug?

**Comment by Iamgoofball** [comment]
@Xhuis please respond

**Comment by Xhuis** [comment]
They worked fine last time I tested them. Try reproducing this on the latest build.

**Comment by Durkel** [comment]
Watched a mime run around with it today, no attack animation except on bots. Nothing on humans.
