### ISSUE TITLE
Ministation has a chef

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14566]
It shouldn't have a chef, the chef has none of the access it needs and the bartender has all of it. It needs to be removed.

**Comment by swankcookie** [comment]
This is connected to #14373.  Also, are you sure you were a chef, or were you just an assistant that spawned in the chefs area?

**Comment by Zilenan91** [comment]
I was the bartender, and also a traitor, so I murdered the chef who spawned next to me, and was unable to open the doors to get out with her ID.

**Comment by Zilenan91** [comment]
Gonna close this anyways because I know it's a dupe, but it needs fixing fast.
