### ISSUE TITLE
Wild Shapeshift is unreasonably bad due to how it functions

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14567]
Now that I've learned what this spell does, good god it's fucking horrible. There's one really really terrible mob (corgi) one really good mob (spider) and two middling ones, the megacarp and the construct. The problem with these is that, yeah, they're fun to be, but if you can't choose when you want to be a spider to get around through vents, a construct when you need some brute strength, a carp if you need to go around fast, or a corgi when you need to go incognito it makes it horrible.

It's a spell with tons of versatility that can be literally useless to you since you're not allowed to choose what you turn into and when, which means that all the potential it has is wasted. It needs to change.

**Comment by Zilenan91** [comment]
Hey WJohn can you remove the bug label from this? I misunderstood how the spell worked.

**Comment by swankcookie** [comment]
Just FYI, since there is a :snowman: going on right now, this won't be worked on for, at the very least, 20 days. This will be hidden behind approx. 100 other issue reports by then.  I would close this and re-request after the freeze.

**Comment by Zilenan91** [comment]
I'm still gonna leave this up, I might make a forum thread in a day or two.

**Comment by Iamgoofball** [comment]
@Dorsisdwarf @Zilenan91 @WJohn requesting close so it's not filling up the issue tracker

feature requests/not-a-bugs should be mandatory forum only and they should be closed immediately upon opening
