### ISSUE TITLE
Handheld Crew monitor bad resource file runtime

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#14572]
runtime error: bad resource file
proc name: send asset (/proc/send_asset)
  source file: asset_cache.dm,44
  usr: Samuel Vimes (/mob/living/carbon/human)
  src: null
  usr.loc: the floor (142,125,1) (/turf/simulated/floor/plasteel)
  call stack:
send asset(AssassinT90 (/client), "minimap_8.png", 1)
Minimap (/datum/subsystem/minimap): sendMinimaps(AssassinT90 (/client))
/datum/crewmonitor (/datum/crewmonitor): sendResources(AssassinT90 (/client))
/datum/crewmonitor (/datum/crewmonitor): show(Samuel Vimes (/mob/living/carbon/human), null)
the handheld crew monitor (/obj/item/device/sensor_device): attack self(Samuel Vimes (/mob/living/carbon/human))
Samuel Vimes (/mob/living/carbon/human): Activate Held Object()

**Comment by Incoming5643** [comment]
sounds like it's trying to grab the minimap for the away mission, which is loaded after minimap generation I think.

**Comment by Shadowlight213** [comment]
@Incoming5643 yeah, when I tried to see the minimap for space battle, I noticed the map didn't load.

**Comment by MrStonedOne** [comment]
I could have sworn i fixed this,

**Comment by MrStonedOne** [comment]
@neersighted YOU BROKE IT.

I had it checking the initialized zlevels for a fucking reason.

**Comment by neersighted** [comment]
Shhhhh
