### ISSUE TITLE
Deconstructing dead turrets has no progress bar.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#14576]
Title says it all.

**Comment by PKPenguin321** [comment]
you mean crowbarring a dead turret, right?

**Comment by Durkel** [comment]
Yeah, my bad.

**Comment by Iamgoofball** [comment]
@WJohn @Dorsisdwarf tag this one Easy Fix, this probably just needs a sleep/spawn/whatever changed to a do_after
