### ISSUE TITLE
tacticool turtlenecks have same armor as real things

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14587]
https://github.com/tgstation/-tg-station/blob/02603d4f93a123942873f388bb5847ef38fb1f33/code/modules/clothing/under/syndicate.dm

While this *might* be intended, it certainly looks like somebody forgot about inheritance when making this item.

**Comment by Dorsisdwarf** [comment]
clearly intended!!!!!!1!

**Comment by duncathan** [comment]
Sounds like a balance meme to me
Feedback forum so it doesn't clog up our precious tracker

**Comment by PKPenguin321** [comment]
You fuckin wot

**Comment by duncathan** [comment]
Even if it's unintended, this isn't a bug; it's a balance issue
It's been around long enough that to change it now is not to fix a bug but to change the balance
I don't like balance memes
