### ISSUE TITLE
Spelling error: NAD

### ISSUE THREAD

**Issue by whoisthere** [tgstation/-tg-station#14584]
Nuclear Authentication Disc is called a Nuclear Authentication Disk when it's clearly a disc.

**Comment by RemieRichards** [comment]
"Disks
A disk refers to magnetic media, such as a floppy disk"

The Nuke disk is a floppy disk.

**Comment by duncathan** [comment]
Not an issue

**Comment by PKPenguin321** [comment]
>Disc vs. disk. There is no consensus on the difference between disc and disk, and in many contexts the two are used interchangeably. Disk is the standard spelling for computer-related terms such as hard disk and floppy disk.
