### ISSUE TITLE
Handcuffed in Locker bug.

### ISSUE THREAD

**Issue by Ronnoc1** [tgstation/-tg-station#14593]
Server: Basil

Revision: Server revision compiled on: 2016-01-11
360086c74fdc513c148d6213dc4936813b3119ce 

Problem Description: While handcuffed I was able to break myself out of a locked Captain's locker while handcuffed by using resist. I was not able to break myself out of an unlocked Fire-safety locker while handcuffed.

What did you expect to happen: I expected to be able to just push open the locker by using resist and leave but I was not able to.

What happened instead: Nothing happened when I used resist or tried any other way I could think of to open the locker.

Why is this bad/What are the consequences: This is a little incongruous. It would be fine if you could not bust out of a locked locker and were not able to open an unlocked locker, but being able to open a locked locker from the inside and not an unlocked locker makes no sense. (While handcuffed)

Steps to reproduce the problem: Get handcuffed and have someone close a normal hallway fire-safety locker with you inside.

Thanks!

**Comment by WJohn** [comment]
That's strange, I was under the impression that you could open an unlocked locker's door by just moving, even while handcuffed. Maybe something broke somewhere.
