### ISSUE TITLE
Away Mission with Energy Cannons on Syndicate Ship

### ISSUE THREAD

**Issue by maconverse** [tgstation/-tg-station#14597]
Hey there - I found a small bug. The Energy Cannon away mission accessed via the gateway has an energy cannon facing the wrong way. It is facing the wall when it should be facing outwards towards all the other cannons.

I have attached an image of the error, hope it helps!
![away mission bug](https://cloud.githubusercontent.com/assets/6054936/12256068/31893b06-b8af-11e5-9c49-ffb3058ada51.png)

**Comment by PKPenguin321** [comment]
honestly, it's hard to tell if this is a bug. i figured that the cannons in this mission were super random on purpose.

**Comment by maconverse** [comment]
I believe its supposed to be a matrix of lasers that you have to navigate. Every other cannon is facing outwards except this one, and its leaving a gap in the run. Not a big deal just something small I noticed while playing

**Comment by GunHog** [comment]
Ah yes, the emitter maze. I do not believe that was intended, perhaps the mapper just set the one direction for that particular emitter.
