### ISSUE TITLE
Xeno APC slashing is broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14618]
>be Drone
>slash AI core APC
>AI is still able to switch turret modes and kill me
>lights are still on
>nothing is depowered
>APC isn't even draining

thanks

For real though this is actually really critical to fix because xenos very badly need to be able to kill APCs

**Comment by ChangelingRain** [comment]
You have to slash it until the wires are cut, did you do that?

**Comment by Zilenan91** [comment]
Yep.

**Comment by tkdrg** [comment]
Did you slash it enough? Xeno APC cutting got a cooldown recently.

**Comment by Zilenan91** [comment]
Yep. Admins tested it and they said it was very much bugged. Ask K Peculiar if you need verification.

**Comment by Shadowlight213** [comment]
@KorPhaeron
Ya broke it.

**Comment by Zilenan91** [comment]
All he added was a cooldown so I don't know how he'd have broken it, but BYond is BYond I guess.

**Comment by KorPhaeron** [comment]
I am not going to have time to fix this in the near future

**Comment by KorPhaeron** [comment]
Also what zilenan91 said

**Comment by tkdrg** [comment]
I asked K Peculier. According to him, he and another admin tried to slash an apc on metastation as a xeno and all it would do was open up the apc. No wire cutting action at all.

**Comment by KorPhaeron** [comment]
Not sure how adding a cooldown would cause that

**Comment by ChangelingRain** [comment]
You have to slash it once after it's open to cut the wires.

**Comment by Zilenan91** [comment]
I've been trying to verify it myself but nobody wants to spawn me in the Thunderdome.

**Comment by WJohn** [comment]
This bug doesn't even exist. Everything works perfectly fine. I just saw a hunter cut an APC's wires and power went out as expected.
