### ISSUE TITLE
Bots attempt to path through plastic flaps, but cannot actually pass.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#14616]
Been seeing this happen a lot as AI when trying to call a bot to a location. A good example would be trying to call the clean bot in chem to the hop line on box.
The bot will go to medbay's mulebot entrance, but fail to pass through the flaps, saying unable to reach destination after a few seconds.
Attempting to try it again will result in the bot not moving and giving the failed path error again.
It seems like the pathing system sees it as a valid route, but the bot itself cannot pass.

**Comment by Menshin** [comment]
This isn't limited to bots, but to every path finding mobs, thanks to the *spaghetti* plastic flaps code...

I'll fix this when i'll find some free time (i.e later in the week), if no one beats me to it.

**Comment by Incoming5643** [comment]
flaps omit/allow mobs based on the very rarely ever used mob_size var.

**Comment by Shadowlight213** [comment]
Well, shouldn't it be fixed both ways though? If a mob can't fit through the flaps, it shouldn't try to path through them.
@Incoming5643 they also have some hardcoded exceptions, such as allowing mulebots through.

**Comment by bengin-polyp** [comment]
if this does get fixed by altering how it works, e.g. replacing the mob_size var with something else, please remember to apply it to drones as well. sometimes sneaking through the catflap is the only way you can escape a murderous greyshirt

**Comment by Menshin** [comment]
>if this does get fixed by altering how it works, e.g. replacing the mob_size var with something else, please remember to apply it to drones as well. sometimes sneaking through the catflap is the only way you can escape a murderous greyshirt

Don't worry, this is more a problem with how A* decides a turf is "passable".
