### ISSUE TITLE
Cameras do not operate off of area power

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14619]
When a room is depowered cameras continue to ~~rotate and look around, seemingly powered. This is most likely an issue with the sprites not switching to deactivated.~~ function normally.

maintainereditedkidtestedmotherapproved

**Comment by WJohn** [comment]
Cameras have historically never used power or required areas or anything of the sort, they're fully functioning. This'd be a major balance change to mess with.

**Comment by Zilenan91** [comment]
Well yeah but that's always been stupid. If someone manages to kill the power they should be rewarded with, you know, the power going out and cameras being disabled like they should be.

**Comment by Dorsisdwarf** [comment]
Please respond if the issue has been renamed incorrectly. As far as I can tell, this is a complaint about the fact that cameras do not disable when area power goes off?

**Comment by Zilenan91** [comment]
Yeah it's fine now.

**Comment by GunHog** [comment]
I do not personally recommend addressing this issue, as it would be a major nerf to AIs, and would drastically reduce the usefulness of camera lights as well as making an AI helpless to restore power to an area that has been switched off. (APCs still require camera visibility to operate, barring the AI's own)

I would be okay with a cameranet's power needs being fed from the AI's APC or other central location, but this would otherwise be devastating in crisis management.

**Comment by PKPenguin321** [comment]
>it would be a major nerf to AIs

this is a bad thing????

**Comment by WJohn** [comment]
I mean it'd also be a ridiculously gigantic buff to powersinks. Slap that thing on anywhere and you blind the AI from the whole entire station.

Cameras ought to run on environmental power, besides this, to help prevent the likelyhood of station-wide blackouts without it definitely being a powersink.

**Comment by Zilenan91** [comment]
Powersinks cost like 10 TC anyways, half your TCs to blind the AI is fine. It'd also be something that Nuke Ops could do against the AI without penetrating it or sending a borg.

**Comment by GunHog** [comment]
I do not believe that any of you are giving any consideration to the player whose experience you are degrading. It is a common problem with nerf proposals.

**Comment by xxalpha** [comment]
Yes guys, lets blind the AI with a simple APC hack or EMP.

**Comment by Zilenan91** [comment]
Oh man, the AI is blind, so is everybody else because it's pitch fucking black.

**Comment by xxalpha** [comment]
Have you ever played AI, son.

**Comment by Zilenan91** [comment]
>oh no I'm blind
>I'm no longer an all-seeing god
>whatever shall I do
>i know i'll tell my borgs to go fix it

**Comment by KorPhaeron** [comment]
Powersinks dont even knock out power anymore, they're just shitty bombs.

And how the fuck is the AI supposed to kill power to a room if it blinds itself in the process?

**Comment by Ausops** [comment]
Cameras are already really easy to break. APC's being in maintenance half the time already make departments vulnerable to sabotage.

**Comment by WJohn** [comment]
The only reason you can see APCs in maintenance in the first place is because there are cameras that view the wall, and APCs are pixel shifted onto that wall so you can interact with them. This means cutting environmental power would totally blind an AI pretty much permanently, with next to now downside for the crew.

**Comment by Zilenan91** [comment]
>i know I'll tell my borgs to go fix it in 2 seconds

**Comment by GunHog** [comment]
Because every AI certainly has borgs!

**Comment by Zilenan91** [comment]
It's hard to find an AI that doesn't have borgs. The only situation it wouldn't would be in lowpop, but in lowpop things tend to move so slowly that even the crew would fix things for you.

**Comment by xxalpha** [comment]
Stop

**Comment by Memendia** [comment]
Man you guys really hate AI / AI players

**Comment by GunHog** [comment]
Sad, is it not?

**Comment by PKPenguin321** [comment]
AI a shit

**Comment by Memendia** [comment]
@GunHog It's super sad :c

**Comment by tkdrg** [comment]
This really isn't a bug, it's basically key to a lot of a rogue AI's tactics, and gameplay always trumps realism.
