### ISSUE TITLE
oh god my hair!

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#14614]
1. Be a human with a nice haircuit
2. Fight blob.
3. Die.
4. Become Blob zombie.
5. Be killed as a blob zombie
6. Suddenly be bald for whatever reason.
7. Curse blobs for making all things worse

**Comment by Zilenan91** [comment]
Why they eat your hair away of course.

**Comment by PKPenguin321** [comment]
Yeah, when they latch onto your brain they eat your hair in the process. I always figured this was intended.

**Comment by Niknakflak** [comment]
It only just started happening, I'm almost positive this wasn't happening a couple months ago.

**Comment by Incoming5643** [comment]
This has always happened, the blob eats your hair because some styles (like big afro) would poke through it and look weird.

**Comment by Niknakflak** [comment]
Couldn't you just put the hair back after the blob zombie dies?  If not or whatever, close the issue.

**Comment by tkdrg** [comment]
Make a thread in the ideas forum, I guess.
