### ISSUE TITLE
Doomsday module and other modules don't like to work

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#14620]
So I was just in a malf round as AI and I bought Camera Upgrade, Factory, Overload, then finally Doomsday just as the shuttle was about to leave. I didn't get the doomsday button, however, so I couldn't activate it and admins didn't respond until it was way too late to do anything. 

I even tried hacking another APC to see if that would make it appear, but nope.

Is there a minimum hack rate for certain modules? I hacked a LOT of APCs that round and some stuff didn't appear till I had hacked a bunch, Doomsday I had to hack the full 13 for but it never showed.

EDIT: Was just told that I have to relog to get the button, well ok

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg

Malf powers not appearing is such an old bug that the malf victory text actually advised you to relog.

**Comment by WJohn** [comment]
That's just sad.

**Comment by GunHog** [comment]
Try using the "return to core" button on your HUD. Purchases do not seem to show up until you do that.

**Comment by Shadowlight213** [comment]
Likely Byond issue. Testing showed that setting the client eye past 12 tiles away from the mob caused the verbs to stop updating in the client. Moving it back within 12 tiles caused it to start updating again.
Bug report was made. http://www.byond.com/forum/?post=2018444
