### ISSUE TITLE
Standing under a shower behaves oddly regarding covered clothes

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#14622]
Just had this recently - I was wearing a hardsuit over a bloody jumpsuit, stood under the running shower and then took off the hardsuit - jumpsuit did not get clean. I walked out from under the shower and then back under it and the jumpsuit got clean instantly.

**Comment by xxalpha** [comment]
That's because it uses Cross or Crossed, should be an easy fix calling the one of these procs that does the cleaning when turning it on.

**Comment by WJohn** [comment]
This bug's been around forever.

**Comment by Dorsisdwarf** [comment]
Dupe of #9713
