### ISSUE TITLE
Snowdin away mission still has a scroll of teleportation

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14627]
I HOPE YOU LIKE VISCERATORS

BECAUSE WE HAVE 150 OF THEM

ANYWHERE

**Comment by Dorsisdwarf** [comment]
Detail?

**Comment by SpinnerMaster** [comment]
Yeah I was on the syndicate away mission as a normal syndicate agent. Went on a walkabout with some fellow agents, got an iViscirator grenade and a scroll of teleportation from a crate. Teleported to the station and proceeded to act like a fox in a chicken house.

**Comment by WJohn** [comment]
Ah, I see. Syndies from the away mission are supposed to be incapable of leaving due to their exile implants, but the teleportation scroll lets you escape anyway and wreak havoc.

**Comment by Zilenan91** [comment]
There was a pr a while ago that supposedly removed the tp scrolls but I guess it missed one.

**Comment by MMMiracles** [comment]
apprentice scroll is still in the mid-tier loot list. 

i'm probably going to go through that mission and do a lot of reworking on the dungeon area in general to prevent the operatives from just looting all the shit at round-start and terrorizing anyone who dares step to the dungeon area.

**Comment by Zilenan91** [comment]
The tp scroll removal is actually really urgent because what Ops do is beeline for it, get a bunch of viscerator grenades, and end the round because of 1500 eviscerators on the station.
