### ISSUE TITLE
New floor turfs seem to start with 0kpa

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#14633]
>crowbar up tile
>instant pressure loss
>put wood tile on plating
>instant pressure loss
>decide to quickly check plating kpa and check again immediately after placing down bananium tile
>0kpa

**Comment by newfren** [comment]
SHIT THIS WAS WHAT WAS HAPPENING

I was trying to lay some cable in cargo earlier and I kept getting pushed around and it was a giant pain in the dick.

**Comment by duncathan** [comment]
BTW this shouldn't be worth cheribucks cuz it wasn't actually an issue with master, just my branch
