### ISSUE TITLE
MiniStation TEG Broken

### ISSUE THREAD

**Issue by Gartley** [tgstation/-tg-station#14644]
Server revision compiled on: 
f0aab5d791e2e407f757f3b37e5c37211cc86818 

With Tanks connected and valves open there is no gas in pipes.
http://puu.sh/mxhwx/a55117392f.png
The connector ports had to be connected then reconnected for gas to flow.
Confirmed using analyzer.

Restarted server, unfastened connector ports and reconnected, attatched tanks and had gas flow despite manual valves being closed.
http://puu.sh/mxigd/0410e8abc5.png
Same on other side.
http://puu.sh/mximH/3dd3de0c76.png

**Comment by duncathan** [comment]
Fug

**Comment by duncathan** [comment]
I fixed this in #14732
