### ISSUE TITLE
[Runtime] runtime error: type mismatch: "syndicate" |= "\[mob_105]"

### ISSUE THREAD

**Issue by nullquery** [tgstation/-tg-station#14657]
runtime error: type mismatch: "syndicate" |= "\[mob_105]"
proc name: New (/mob/living/New)
  source file: living.dm,27
  usr: (src)
  src: Syndicate Operative (/mob/living/simple_animal/hostile/syndicate)
  src.loc: the floor (159,108,6) (/turf/simulated/floor/plasteel)
  call stack:
Syndicate Operative (/mob/living/simple_animal/hostile/syndicate): New(the floor (159,108,6) (/turf/simulated/floor/plasteel))
Syndicate Operative (/mob/living/simple_animal/hostile/syndicate): New(the floor (159,108,6) (/turf/simulated/floor/plasteel))

Occurs when the game starts up.

**Comment by AnturK** [comment]
Hum. Which away was that, probably mapedited faction

**Comment by nullquery** [comment]
Should I look into this or are you?

From what I've been able to determine the "faction" var is always supposed to be a list, but in a lot of places it's defined as text instead. The quickest fix would be to go through the code and replace all those instances with a list.

A better fix would be to convert the faction variable to a list on `New()`, but I don't know if it's feasible as I didn't write the faction var.

**Comment by AnturK** [comment]
Pushing map fix now, and yeah will probably add to list there for mapedits like this
