### ISSUE TITLE
Removing floor tiles remove airs

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14681]
It was supposed to be fixed, but still happening. Tested with normal floor tiles and wood tiles, both made this happen.

**Comment by duncathan** [comment]
Jesus Christ can you at least tell me what the difference is
Other report said it totally removed airs and my fix solved that

**Comment by lzimann** [comment]
I don't know, a guy ahelped saying that wood tiles were making air disappear when he was removing, I went to test on thunderdome and it happened when I removed normal tiles aswell.

**Comment by feemjmeem** [comment]
I suffocated to death because of this bug today on Sybil, on the bridge.

**Comment by duncathan** [comment]
STEPS TO REPRODUCE AAAAA

**Comment by newfren** [comment]
Steps to reproduce use a crowbar on a tile.

**Comment by duncathan** [comment]
And what
What changes
I fixed this bug before so you guys have to be VERY FUCKING SPECIFIC about what happens
What type of tile? How much gas is lost?

**Comment by newfren** [comment]
I just dicked around on the server a bit to figure that out but when you flip up or put down floor tiles (only tested regular ones in meta tool storage) after flipping a few up you start taking pressure damage and the low oxy warning flashes.

**Comment by Gartley** [comment]
https://dl.dropboxusercontent.com/u/42905350/bandicam%202016-01-17%2013-47-36-845.mp4

Maybe this video will help clearly demonstrate what is happening.

**Comment by duncathan** [comment]
Thanks a bunch @Gartley; I'll see what's screwed up

**Comment by feemjmeem** [comment]
Steps to reproduce:

Use a crowbar on a tile.

Add a tile to an untiled area, such as maintenance, or the place where you just pulled up tiles.

Do you feel silly now?

**Comment by phil235** [comment]
There is an identical bug with portable scrubbers, they remove the air on their turf when you switch them on or off. It likely comes from the same problem.
