### ISSUE TITLE
Blobbernaut bug

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14682]
When a blob dies, any blobbernauts they had lose the chem they were created with which shouldn't happen.

**Comment by GunHog** [comment]
To be honest, the blobbernaut should die if its overmind controller does as well. You failed to protect *your* overmind, so you die along with it.

**Comment by KorPhaeron** [comment]
When a blob dies all the tiles turn white/lose their chem, sounds intentional
