### ISSUE TITLE
Admin crap

### ISSUE THREAD

**Issue by DukeDukington** [tgstation/-tg-station#14690]
Considering an "admins" job is to solve problems. It isnt very well versed on this station. I litterly had someone following me around all round trying to murder me not trying to roleplay at all and the admin on duties response when i filed a ticket was. "Im not security so i cant do anything" That is such bullshit is TGstation basically a no Roleplay zone or something? If so i will never play on this station again. The admin who basically ignored me and told me that is named K Peculier and he is a trial admin.

**Comment by duncathan** [comment]
Not a code issue; take it up on the forum https://tgstation13.org/phpBB/index.php
