### ISSUE TITLE
using view variables on a changeling egg disconnects client

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#14691]

**Comment by tkdrg** [comment]
possible dupe of #10881

**Comment by Miauw62** [comment]
yeah this happens unreproducably on a wide variety of things

**Comment by tkdrg** [comment]
and the things change with each update

**Comment by PKPenguin321** [comment]
I bet this will turn out to be some really stupid and bizarre byond bug

**Comment by hornygranny** [comment]
this is reproducible between rounds but i have no idea why it happens

**Comment by Jalleo** [comment]
Report it on byond maybe lummox can work it out.

**Comment by octareenroon91** [comment]
Unsanitized \improper in a binary stream, anyone?

**Comment by tkdrg** [comment]
dupe
