### ISSUE TITLE
Memesword needs to be its own gamemode, or an opt-out specific to it.

### ISSUE THREAD

**Issue by Kuromoi** [tgstation/-tg-station#14697]
Memesword needs an opt-out specific to it, so you don't have to opt out of being wizard in order to get out of it.  It should be its own gamemode at best.  It's the only gamemode that you don't get a prompt for, so if you're sitting around afking in dead chat whoops suddenly you're revived, and people get pissed at you even though it's not your fault the gamemode is shitty like that.

**Comment by KorPhaeron** [comment]
Duplicate issue

Also please use the actual names of things in issue reports, makes it easier to find

**Comment by Iamgoofball** [comment]
stop putting fucking feature requests on the tracker

this belongs in the forums

requesting a close @Dorsisdwarf

**Comment by Firecage** [comment]
@Iamgoofball Actually, this, for once, is actually a valid issue even if its a feature request. Multiverse sword cloning really needs its own prompt, since fuck prompting out of being a wizard just for it.

>Let's ghost, it sucks being just a dead body. FUUUUCK! I AM A CLONE NOW.

**Comment by Iamgoofball** [comment]
that's a feature request still

fuck off and make a forum thread

**Comment by KorPhaeron** [comment]
It's still a dupe issue with an unsearchable title

**Comment by duncathan** [comment]
This issue has been made so many times
