### ISSUE TITLE
Space tiles are not "pulling" the air to them

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14700]
When you break a window/weld a wall that is open to space, it simply doesn't vacuum the area, while the space itself has no pressure at all. 

[Example](http://puu.sh/mzf9V/8ce7e61c95.png)

I did this at least 10 minutes before creating the bug report, and there is still air.

**Comment by DaedalusGame** [comment]
Query: Did the air pressure decrease or was there just no vacuum effect?

**Comment by lzimann** [comment]
I didn't check the pressure, but the o2 level simply didn't decrease, you can simply make a breach and stay there forever without having to fix it. Yesterday I saw someone breaking the permabrig window and the air alarm never turned orange/red, just stayed green like no breach ever happened.
