### ISSUE TITLE
Mounted chainsaw does not show in examine.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14718]
What it says on the tin. I was confused momentarily as to what it was in someone's hand because I was not used to seeing what that was. It should definitely show, since they're basically always "holding" it in their hand.

**Comment by RemieRichards** [comment]
The item has ```ABSTRACT```, which makes it not show on examine, it's the exact same situation as the Ling Armblade.

**Comment by WJohn** [comment]
Ah, I didn't realize. It definitely should show on both, then.

**Comment by RemieRichards** [comment]
The idea is it's your ARM, otherwise it would say that they are holding it.
you don't hold your arm now do you?
