### ISSUE TITLE
Mutadone + 'You shrink' genetic power can make you HUUUUUUUUGE

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#14729]
How to reproduce:
Swallow mutadone pill. 
Inject yourself with the SE that makes you shrink.
Shrink.
Mutadone kicks in.
You grow back to normal size plus some extra.

Repeat for extra penis size.
![huge](https://cloud.githubusercontent.com/assets/10028803/12405492/fac0ef1a-be44-11e5-9773-14a18201df46.jpg)

**Comment by Bawhoppen** [comment]
feature

**Comment by duncathan** [comment]
Dupe #12297
