### ISSUE TITLE
Pixelshifted objects keep shift when pulled(?)

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14728]
Question mark is in the title because I'm not sure if Pixelshift is the right word to use to describe this.
Steps to easily reproduce:
1. Place object on the very edge of a table
2. Drag the object off of the table and move it around
3. Notice how the object's sprite is positioned incorrectly

**Comment by Dorsisdwarf** [comment]
pixel_x I think.

Not sure if this is even a bug.
