### ISSUE TITLE
[Metastation] Mulebot delivers crate to wrong tile in R&D

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14727]
When a mulebot delivers a crate to the Research and Development lab, it will pass under the plastic flaps, then drop the crate. However, instead of dropping it on the desired tile (which is one tile above it), it drops it one tile down, leaving the crate in maint and also trapping the mulebot inside the plastic flaps.

**Comment by WJohn** [comment]
I swear I got this thing to point to the correct direction when I added it seemed to work just fine. Did something break lately? Maybe with simple animal bots?
