### ISSUE TITLE
Blobbernauts are completely ridiculous.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14724]
Let's add up all their abilities:

They cost 20 points to create.
They do not destroy the factories they come from, so you get these faster and faster later on.
They have 240 health.
They deal 20 brute per hit and apply their chem type.
They cost 20 points to create.
There is no upper limit to how many you can spam.
They have player intellect, meaning they can dodge bullets and cross the entire station by themselves.
They cost 20 points to create.

I just saw a round where about 30 blobbernauts were spammed and they killed literally everything while the actual blobs themselves barely expanded at all. They didn't need to.

Something has gone very wrong with this mode. Please fix.

**Comment by ChangelingRain** [comment]
They shouldn't be doing 20 brute per hit, just 4+chem damage.

**Comment by ChangelingRain** [comment]
I'd be doing something about this, but there's a freeze I can't do balance memes during the freeze!

My ideas for balancing them are; halve factory regen so it takes much longer to do it from a single factory, increase the cost to 25, and then see if they're still getting used and if they are, increasing the damage done to the factory.

**Comment by WJohn** [comment]
25 is absolutely not enough at all. I just saw a round where about 9 all came from a tiny blob and overtook cargo and the 15 people fighting that blob in seconds. It was retarded.

**Comment by ChangelingRain** [comment]
The problem right now is that factories regen way too quickly for the damage dealt to matter; a factory, assuming it's not getting hit otherwise, will usually regen to blobbernaut-usable levels before it can start spawning spores again, which is less than a minute.

It could also be related to the chemical the blob has, as some blobbernaut types have absurd damage, like lexorin jelly and some blobbernaut types just don't do shit.

**Comment by Zilenan91** [comment]
Blobbernauts themselves are fine. It's the Pressurized SLime blobbernauts that are the problem. They give blob a stun, aka water, where they then dogpile on the dude who's down, managing to stun him with stamina damage before he can even get up.

**Comment by WJohn** [comment]
Also I would like to point out I just tested their damage with a pressurized slime blobbernaut. Its damage was reduced down to 11 per hit, but it dealt oxygen and stamina damage on the side that basically allowed it to 4 shot people.

**Comment by Zilenan91** [comment]
Yeah it's just pressurized slime being ridiculous.

**Comment by KorPhaeron** [comment]
http://ss13.eu/tgdb/tg/latest_stats.html#mode_blob

Blob rarely wins.

Blobbernauts are pretty strong with their ability to feint, strike anywhere, etc. They can stall for years if they play carefully. Their actual damage output seems subpar on many types.

**Comment by Zilenan91** [comment]
Like I said, pressurized slime op. The win they had with it was so dominating that I think every single person but the AI died. There were blobbernauts everywhere that were spewing water by pulling bodies and punching them. This caused people to slip and then get mobbed.

**Comment by WJohn** [comment]
There were 9 cryo blobs in cargo bay spammed in the space of 20 or 30 seconds that killed 15 people all shooting at them because they are such ridiculous tanks. All the while blob spores fly in to re-animate the bodies into 15 brute high-speed monsters.

**Comment by optimumtact** [comment]
I disagree that they need balancing, blobbernaut spam meta actually made blob really interesting to play.

**Comment by PKPenguin321** [comment]
imo best revision of blob was when they were able to pop early via an action button and had the split consciousness ability. that gave them good tools without giving them an army of blobbernauts.

**Comment by Lumipharon** [comment]
As the blob player, the mode is now exceedingly dull and shit. This is how it pans outs.
Burst somewhere, avoid getting rekt in the first 5 minutes
Shit out blobnauts
get more nodes and factories
shit out infinite blobnauts
win

The crew is too busy dealing with 10+ nauts raping them in medbay to even try mount an effective attack on the blob. And have you tried being a field medic when nauts can jsut run up and pull crit people away?

On another note, nauts are hilariously ineffective against windows, so you can hide behind a window and laser them, and it will take them a year to break it.

**Comment by duncathan** [comment]
Feedback forum
