### ISSUE TITLE
Players that get put into a blob's body won't burst

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14736]
Blobs don't ever burst on their own. Admins had to help the blobs burst.

**Comment by Iamgoofball** [comment]
What was the time and date of the round?

@MrStonedOne Can you pull runtime logs once Zilenan supplies the needed info?

**Comment by Zilenan91** [comment]
It was yesterday I think, Monday.

**Comment by Iamgoofball** [comment]
time ETA?

**Comment by hornygranny** [comment]
i'm pretty sure this happened because the blob player left before bursting and we had to offer control to ghosts

**Comment by MrStonedOne** [comment]
fucking MINDS!

**Comment by tkdrg** [comment]
Yeah this doesn't always happen, it's very much an edge case

**Comment by ChangelingRain** [comment]
blobs no longer have bodies
