### ISSUE TITLE
Surplus crates don't have any items in it

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#14733]
Just buy a surplus and laugh how there is nothing inside

**Comment by Firecage** [comment]
Well, last person to touch the file in which uplink items are located was @neersighted with #14686

**Comment by Gartley** [comment]
The uplink window also starts stupid small and tool tips are hidden inside window. 
http://puu.sh/mBXcz/31a59aac84.jpg

**Comment by neersighted** [comment]
Yeah it got messed up in a rebase, fix is incoming.
