### ISSUE TITLE
Player-controlled Pingsky issue

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14738]
If Pingsky says something, aka an arrest notice like arresting Urist McGreyshit in Prime Tool Storage, when a ghost attempts to orbit this it only orbits a thing called the virtualspeeker.

**Comment by Shadowlight213** [comment]
I remember this happened a lot with NTSL, and sometimes with the announcement console.
Has something to do with radio message modification and a temporarily created speaker in nullspace or something.

**Comment by AnturK** [comment]
Weird, i'm pretty sure i used standard say for these. I'll look into it
