### ISSUE TITLE
Space tile under maintence door of central outpost on Snowdin

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14740]
In the central outpost that connects to the next part of the mission, there is a four part maintence airlock to the upper left. It has a space tile under it.

**Comment by PKPenguin321** [comment]
i almost reported this but thought it was intentional for some reason, but thinking back, being on an ice cave on a planet and there just being OUTER SPACE right there for no reason really does seem like a bug

**Comment by KazeEspada** [comment]
Actually the space tile is on the surface, but its a planet's surface.
