### ISSUE TITLE
Pizza boxes can't hold custom made pizzas

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14749]

**Comment by bgobandit** [comment]
To clarify (REEEE LEO STEALING REPORTS):

Normally you put a pizza into a pizza box by clicking the open box inhand. This doesn't work with custom pizzas, probably due to a path issue.

**Comment by phil235** [comment]
dupe

**Comment by octareenroon91** [comment]
Sounds like paths. All custom foods inherit from a single 'custom" type, on a different branch than pizzas.

**Comment by neersighted** [comment]
Working on it
