### ISSUE TITLE
mob/new_player/Login() is super laggy

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#14753]
On the profile:
/mob/Login               34.391       39.085       39.086          257 calls

The reason is because it calls ..() (added in https://github.com/tgstation/-tg-station/pull/12869/files#diff-c3d8d983e2c6ebdd2156952858c6907bR2)

Something to do with mob/Login(), the game tries to create a mob at the first location it can Move() to. And the new player fails Move() for every turf or something (I got approximately 600k new_player/Move() calls for each Login() on my profile).

**Comment by MrStonedOne** [comment]
>The reason is because it calls

can't be, self and total are too close.

it has to be something in new player's login itself.

**Comment by phil235** [comment]
I must say I'm not knowledgeable on Login stuff, but I did test the issue locally and reverting mob/new_player/Login() to a version before "..()" was added (like this https://github.com/Menshin/-tg-station/blob/2f9c5b38f05638cb3042a071d5a0ed4a53f167ad/code/modules/mob/new_player/login.dm) fixes the issue.

**Comment by RemieRichards** [comment]
The issue is probably Byond's attempt at placing the player's mob as close to 1,1,1 as possible

**Comment by Menshin** [comment]
>The issue is probably Byond's attempt at placing the player's mob as close to 1,1,1 as possible

Bingo
