### ISSUE TITLE
Revenants can be glomped by slimes.

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#14750]
When visible, anyway. Of course, I rather doubt this damages them - however, I was found in a revenant round by someone trying to pet a friendly sime and instead dragging "me" (I was nowhere near the slime at that time, but it latched on to me while I was sucking a corpse earlier) off of it.

**Comment by WJohn** [comment]
I'm having a very hard time even reading what you said. Maybe that's just me, but please rewrite it to make it easier to understand what you experienced.

**Comment by Iamgoofball** [comment]
i think he means that slimes can latch onto and absorb from Renevants like they can do with monkeys

**Comment by WJohn** [comment]
Yeah we tested that in the thunderdome but they stop feeding as soon as the revenant goes invisible. I'm not sure if that's really even a bug? They didn't get to do any damage so maybe it is.

**Comment by ChangelingRain** [comment]
Revenants are immune to CLONE damage, slimes do CLONE damage, probably not a bug if it latched on instead of attacking normally(though kind of weird, I guess?)

**Comment by Firecage** [comment]
@ChangelingRain I don't think thats a bug that they do brute damage to simple animals, considering simple animals can't take clone loss and toxin damage. Take like a corgi, makes sense that a slime can feed on it. Same with most simple animals.

**Comment by ChangelingRain** [comment]
That's entirely incorrect; simple animals have handling procs for clone and toxin damage(as well as all the other damage types), they just use brute to track all damage types.
I know this because I made it work that way.

**Comment by demonfiren** [comment]
Well, the problem I was getting at is: the slime never stops feeding on you. It technically remains "stuck" to a revenant (irrespective of actual position or distance between the two) until someone pulls that slime off the revenant, at which point any cover the Rev might have had is blown.

**Comment by ChangelingRain** [comment]
In any case my PR fixes it, as the revenant will both not take damage from the slime and the slime will immediately stop feeding on it.
