### ISSUE TITLE
Gangs can apparently only have one Dominator

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14767]
Said over OOC and on the forums, needs reproducing/testing.

**Comment by Dorsisdwarf** [comment]
for people who don't want to trawl everywhere checking this is a bug: They're supposed to get 2 attempts per gang

**Comment by Incoming5643** [comment]
they only get one attempt if they wait until the shuttle arrives.

The check is very cruddy and it's getting removed in datum antags barring a real argument to its existence.

**Comment by tkdrg** [comment]
yeah what incoming said, this is intended for now
