### ISSUE TITLE
The escape shuttle can hit your leg, causing it to only deal the damage cap of 75 damage.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#14778]
It should probably do the damage as direct equally spread out brute. rather than to only one bodypart.

**Comment by KazeEspada** [comment]
MUH LEG!

**Comment by PKPenguin321** [comment]
Readd shuttle gibbing W H E N

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/173ad9d331cb73109955de0261f6032197ecd399/code/modules/shuttle/shuttle.dm#L454
