### ISSUE TITLE
Unbuckling after shuttle landing causes fall

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#14774]
If you unbuckle as any shuttle docks you will fall over. This works up to about 5 seconds after landing, after that time you will not fall.

Also admin moving the ferry shuttle doesnt seem to knock people over anymore, unless they are buckled and meet the above conditions.

This was tried on Metastation so far on both the ferry and mining shuttle.

**Comment by peoplearestrange** [comment]
To reproduce:
Buckle into seat.
Move shuttle
Shuttle lands
Unbuckle before 5 seconds (roughly) has elapsed.
Fall on your face as you unbuckle. (tried both icon unbuckle and traditional chair click)

**Comment by phil235** [comment]
I think there's two problems here:
* you get weakened despite being buckled when the shuttle reaches its destination
* you can unbuckle yourself despite being weakened.

**Comment by duncathan** [comment]
There's a very good chance that phil's first point is my bug
