### ISSUE TITLE
MACROBOMB MESSAGES 

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#14770]
They're ITALICIZED, AND RED. Attack text is BOLD RED. Way too hard to spot.

**Comment by PKPenguin321** [comment]
They have a noise. Just be aware of your surroundings, captain tinyweiner.
Non-issue.

**Comment by MMMiracles** [comment]
It's funny watching everyone crowd around the ominously beeping body as the beeping gets faster and faster till that region of the station doesn't exist anymore.

Git gud.

**Comment by GunHog** [comment]
>It's funny watching everyone crowd around the ominously beeping body as the beeping gets faster and faster till that region of the station doesn't exist anymore.

https://www.youtube.com/watch?v=VVQNgSRrdbQ

**Comment by Shadowlight213** [comment]
I ded tag needed.

**Comment by Cheridan** [comment]
working as intended
