### ISSUE TITLE
Wildwest is trash and out of date.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14777]
As one of the earliest away missions, it is also one of the shittiest away missions. The reward(the wish granter) cucks you while giving its reward. The entire mission goes from the AI killing themselves to 200 faithless in a giant room. It makes no sense and last but not least it looks like trash.

Please. Do the world a favor and retire this away mission with dignity.

**Comment by PKPenguin321** [comment]
I think it's cool

**Comment by WJohn** [comment]
Agreed, it's absolute garbage. For some reason away missions tend to receive next to no effort whatsoever with their mapping, like holy shit it is pathetic. I don't know why people don't make it even close to as detailed as boxstation, but something like this mission is completely unacceptable.

**Comment by KazeEspada** [comment]
This away mission is old. Its older than me. Its older than when we even allowed gateway use.

**Comment by KorPhaeron** [comment]
This is one of my favourite missions.

This is not what the tracker is used for either.

@Wjohn

Because we had like 4 people make 10 missions in a couple weeks to get enough stuff for the gateway to function. Box has been developed for years, of course it is nicer.

**Comment by KorPhaeron** [comment]
@dorisdwarf @tkdrg @duncathan

Not a bug

**Comment by Niknakflak** [comment]
Why does kor like shitty things

**Comment by PKPenguin321** [comment]
Fight me memenak

**Comment by Zilenan91** [comment]
We should get rid of space battle too

**Comment by Kokojos** [comment]
Plz remove forever.

**Comment by Jordie0608** [comment]
Why would you make an issue report like this

**Comment by KazeEspada** [comment]
This is still more valid than @MrStonedOne and @Iamgoofball issues and subsequent pull requests.
