### ISSUE TITLE
Mining rocks on the asteroid creates air

### ISSUE THREAD

**Issue by Yiu113** [tgstation/-tg-station#14772]
When a rock is mined on the asteroid, air is produced. This is most easily noticed when an explosive goes off, as the wind pushes the materials mined to outside of the blast zone.

**Comment by WJohn** [comment]
Strange, last I checked asteroid turfs were supposed to replicate the air contents of nearby tiles. Perhaps this broke with all the latest atmos updates.

**Comment by PKPenguin321** [comment]
especially noticeable when gibtonite takes out a large amount of rocks.

**Comment by tkdrg** [comment]
@duncathan

**Comment by KazeEspada** [comment]
feature.

**Comment by PKPenguin321** [comment]
forgot to mention that this bug is really bad since a lot of mining equipment requires 0 pressure to function at full power, so this gimps KAs and RIPLEYs and probably some other stuff I can't think of severely

**Comment by tkdrg** [comment]
it's doubly bad because it activates like the entire asteroid, which is awful for performance

**Comment by bear1ake** [comment]
Some proof: http://imgur.com/JGJjmDo
Active turfs have "ACTIVE" maptext.
