### ISSUE TITLE
voice analyzer + flash assemblies are terrible

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#14779]
exhibit A: they don't parse speech well, meaning that you can make the trigger "s" and it will trigger on any word with an s in it. you can easily make them to affect every value

exhibit B: there is no sanity checking for range, so if they hear someone say the trigger over the radio, they flash that person

**Comment by PKPenguin321** [comment]
Wait what
You can flash people from across the station via the radio?
That's beyond hilarious

**Comment by hornygranny** [comment]
i made five of them for a, e, i , o, u. you could not talk without getting flashed

**Comment by Lumipharon** [comment]
That's hilarious. Voice analyser bombs/nades don't do that, why does it happen with flashes?

**Comment by MrStonedOne** [comment]
They flash on view(null,5) but view(null) defaults to usr

**Comment by PKPenguin321** [comment]
I'm guessing because part A of this issue with text parsing is actually on the fault of voice analyzers themselves, whilst part B is the lack of an adjacency check with flashes when they are triggered remotely. The two independent bugs combined into one glorious bug.

**Comment by hornygranny** [comment]
correct

**Comment by Shadowlight213** [comment]
Also, from testing the flash assembly seems to be EMP immune and immune to burnouts.

**Comment by kevinz000** [comment]
shadowlight no it burns out but it's VERY rare 
... and your emps made it flash.. I think? but it didn't burn out

**Comment by kevinz000** [comment]
we should have a day of abusing this allowed right before it gets fixed because ayy lmao why not 2funny5me :^)

**Comment by kevinz000** [comment]
Leave this as an adminspawn item and make it ACTUALLY not burn out for that item

**Comment by newfren** [comment]
Bug of the year candidate right here.

**Comment by MartiUK** [comment]
+1 Bug of the year.

**Comment by kevinz000** [comment]
Bug of the year yo :D +1
