### ISSUE TITLE
Sunglasses/eyewear do not show underneath helmet visors.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/-tg-station#14780]
Not sure if this is a bug at all, but I recall being able to see sechuds beneath helmets before.

**Comment by phil235** [comment]
You mean seeing sec hud through the blindness overlay?

**Comment by TheRealGLH** [comment]
No, I think what he means is that the security helmets, probably the SWAT ones too,  have this little glass panel on them that covers your eyes, but is transparent. When you're wearing both shades and a helmet, the shades become invisible.

**Comment by xxalpha** [comment]
Are they actually transparent or just should be transparent?

**Comment by Dorsisdwarf** [comment]
1) yes, they're transparent
2) This happens with the warden's hat, too.

**Comment by TechnoAlchemisto** [comment]
sumbody please god
