### ISSUE TITLE
Tesla engine is shit.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#14786]
Only 1 bolt is lame, bring back muti-bolts!

It doesn't shrink,

It always grows slowly

It keeps resetting then re-shifting it's pixel z/y for no rhyme or reason such that it flicks to the lower left randomly

Linear progression of power and ball count is shit, as it causes the engine to go from meh, to way excessive really quickly, should be exponential.

It bounces around too much, making avoiding be based to just rng. Having a better attention span and reaction time doesn't help like it does with the singlo. and skill-less dangers are no fun.

**Comment by Iamgoofball** [comment]
# ARE YOU THIS FUCKING AUTISTIC

**Comment by tkdrg** [comment]
not a bug
