### ISSUE TITLE
VVing a welding tool (any kind) will disconnect you.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14782]
What it says on the tin.

**Comment by phil235** [comment]
Happens consistently on every round, on both Basill and Sybil. It only seems to happen when access VV through rightclick. VV'ing a toolbox and then clicking the weldingtool in its content opens the weldingtool's variable window just fine.

Also, I can't reproduce this locally with a 2-3 weeks old tg code.

**Comment by tkdrg** [comment]
That same old byond bug again I'd wager.  We have like 4 reports of it. Someone complain on the byond forums please

**Comment by PKPenguin321** [comment]
probably definitely related to https://github.com/tgstation/-tg-station/issues/14691 and also many of the other similar issues reported in the past, such as the one for VVing radio headsets

**Comment by Shadowlight213** [comment]
Yeah. Dupe of that issue which is a dupe of another issue. Honk.

**Comment by tkdrg** [comment]
dupe

**Comment by optimumtact** [comment]
of #10881
