### ISSUE TITLE
Syndicate Uplink crashes BYOND a little (15 seconds?) every time I open it

### ISSUE THREAD

**Issue by Cheimon** [tgstation/-tg-station#14790]
Server: Sybil

Revision: 2016-01-22

Problem Description: When I used the syndicate uplink as a nuke op (but also previously as a traitor), it opens, the bar at the top changes to a standard windows one for a few seconds, the whole BYOND interface freezes for about 5 seconds, and then it goes to 'not responding' for a few more before I can order anything.  

Once it is responsive again, I also can't move the uplink UI to a secondary screen, and it consistently 'feels' a bit slower than other interfaces.  That's not a good description, though, and the 15 second crash-lite is the big issue here.

What did you expect to happen: I expected the syndicate uplink to open, allow me to immediately order things, and also allow me to move it to my secondary monitor.  

What happened instead: It stopped me from doing anything in BYOND for about 15 seconds, and kept things laggy afterwards.

Why is this bad/What are the consequences: It's important that nuke ops and traitors be able to order things smoothly and efficiently.  Even if the price of that is removing the pretty graphics and reinstating the older functional ones.  

Steps to reproduce the problem: Be traitor or nuke op.  Open your syndicate uplink.  Watch it bug out.  Try to move it to another screen after BYOND has started working again.  

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Other similar UIs seem to work fine, this bug reminds me of the crew monitoring console not responding bug in its style at least.  Also similar in style to the bug where links freeze byond for a few seconds, though I've never had BYOND fail to recover from trying to open a syndicate uplink.

**Comment by RemieRichards** [comment]
@Cheimon what is your Internet Explorer version on your computer? if you don't have internet explorer, then you have Internet explorer 6 (it's built into windows for some core components)

**Comment by neersighted** [comment]
The secondary monitor bit is a feature. You can disable it in prefs. I would also suggest disabling 'fancy' tgui in prefs as well.

**Comment by Cheimon** [comment]
I assume it's IE 6, since I never normally use it for browsing.

**Comment by RemieRichards** [comment]
Earlier versions don't support the fancier features of tgui, so either disable them or upgrade IE, even if you don't use IE having it autoupdate is good to avoid issues and it lets you use the nicer parts of tgui.

**Comment by Cheimon** [comment]
Huh...microsoft.com says I've already got the latest version installed

**Comment by neersighted** [comment]
Cheimon, I'll be on in a bit. Ahelp me and I'll troubleshoot this with you.

**Comment by neersighted** [comment]
This should be resolved by #14761, just forgot to tag it.
