### ISSUE TITLE
Tabling is shit

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#14795]
2 second stuns are lame, bring back 5 second stuns!

**Comment by WJohn** [comment]
do we have a reverse "i ded" tag

**Comment by xxalpha** [comment]
why do you need a reverse

**Comment by WJohn** [comment]
Tabling used to be something people whined about as an "i ded" thing because of how easy it was to spam stuns, so it got nerfed. Now goofball wants it back to its bullshit levels.

**Comment by tkdrg** [comment]
not a bug
