### ISSUE TITLE
Flash remote-signalling devices flash to powerfully

### ISSUE THREAD

**Issue by swankcookie** [tgstation/-tg-station#14801]
If your throw a flash-signalling assembly down, and then walk across the station and signal it, you still get the white screen and "your eyes sting".

**Comment by Boredone** [comment]
Likely related to #14779 and probably fixed by #14784.

**Comment by PKPenguin321** [comment]
yep
literally a dupe

**Comment by xxalpha** [comment]
just get some sunglasses

:do_not_litter:
