### ISSUE TITLE
Atmos tgui issues

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#14805]
rev 739d98a9d992babb15172f22646933d0fe8a3bd6

Gas Filter tgui shows NaN instead of a proper output pressure value.
The Gas Supply Control Computers have no buttons to manipulate the injector or the vent in the supply tank with.

**Comment by tkdrg** [comment]
@neersighted this is still broken after your thing apparently

**Comment by neersighted** [comment]
Should be an easy fix, I think I made a typo.
