### ISSUE TITLE
Deaf people can 'hear' the compli-o-nator

### ISSUE THREAD

**Issue by ATDoop** [tgstation/-tg-station#14812]
The audio for it is muted, but they can still see the text.

**Comment by Shapsy** [comment]
Not even in death can you escape THE LAW

**Comment by phil235** [comment]
The compli-o-nator is using visible_message instead of audible_message. https://github.com/tgstation/-tg-station/blob/e3e6fc13a919ed50a1777471f44deaf04340be7e/code/modules/clothing/masks/hailer.dm#L168
