### ISSUE TITLE
It's impossible to remove embedded items

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#14815]
examine doesnt have clicjable links anymore

**Comment by WJohn** [comment]
This buffs spears to ludicrous throw-and-forget levels.

**Comment by Shapsy** [comment]
I just saw someone pull a throwing star from their chest on sybil, maybe it's not a 100% thing?

**Comment by Anonmare** [comment]
There's also no surgery guide for removing embedded objects from others if anyone with a wiki account wants to get on that as well.

**Comment by tkdrg** [comment]
i dunno shaps i tried it a few times on the thunderdome and it did nothing

**Comment by PKPenguin321** [comment]
I suspect there's some kind of problem with clickable text links on some systems. I have an issue similar to this where none of the (F) links actually work.

**Comment by Zilenan91** [comment]
I have the problem where there are clickable links to remove items, but clicking them does nothing to get the items out.

**Comment by KorPhaeron** [comment]
@tkdrg 

You click yourself with help intent, not examine self

**Comment by tkdrg** [comment]
oh you're right nevermind me I'm dumb
