### ISSUE TITLE
Plasma gas can get trapped inside of firelocks

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14828]
It is then released when the firelock is opened. This might be a dupe, and if it is it's so old I don't even want to attempt to find it.

**Comment by duncathan** [comment]
Closed ones?

**Comment by duncathan** [comment]
Firelocks are designed to not let any atmos through. This is intended AFAIK.

**Comment by PKPenguin321** [comment]
this is a really odd bug that happens with airlocks, too. airlocks shouldn't let atmos pass, but at the same time they shouldn't trap atmos inside of them, either.
