### ISSUE TITLE
You can spam trying to break out of a locker/animal crate.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14839]
![](http://i.imgur.com/qliIu46.png)

Doing so will reset the progress bar, but you will still break out "early" as if you've never interrupted the first attempt, and will break out after that first attempt's time has elapsed. You probably shouldn't be able to "interrupt" yourself like that in the first place.

**Comment by WJohn** [comment]
By the way, this spamming can be achieved through either attempting to move or clicking the resist button (and I guess typing in resist, too)

**Comment by PKPenguin321** [comment]
>Doing so will reset the progress bar, but you will still break out "early" as if you've never interrupted the first attempt, and will break out after that first attempt's time has elapsed.

You can do this with a TON of things (such as spam-clicking a window with a screwdriver or stripping somebody of multiple objects at once). You're not interrupting yourself, you're just starting a second progress bar that renders over the old one. This is a non-issue.

**Comment by WJohn** [comment]
Well, perhaps there should be a general "You are already performing that action!" warning any time you try to spam the same time-consuming action.
