### ISSUE TITLE
Autolathe hacking lights are broken

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14831]
Please revert this, knowing that the green light is always contraband is such a helpful thing. I don't know why on Earth somebody ever changed it when it was completely fine how it was.

They also sometimes don't even show the contraband light at all, meaning you literally have to randomly cut wires until you get it right like on an autolathe.

**Comment by Jalleo** [comment]
Please explain do you mean randomised between rounds or all machines are different for same round?

**Comment by Zilenan91** [comment]
I don't know, I just know the wire lights are different, which means that blue lights won't hack autolathes sometimes.

**Comment by Jalleo** [comment]
As i know of wires between rounds are different. This is for balance to make it dangerous hacking to start with. Aka round 1 it can be wire 1 round 2 wire three etc etc. It has been like this for a long time as i know of.

**Comment by PKPenguin321** [comment]
no no no
the actual light colors on things like vending machines correspond with different things.
for example, the green light controls the contraband products. the color *wire* that triggers the green light is randomized round to round. the *light* used to not be randomized, but now it is, which is really stupid.

**Comment by neersighted** [comment]
The wire is not randomized. There is a bug with autolathe hacking, that is all.

**Comment by neersighted** [comment]
/datum/wires/vending/get_status()
	var/obj/machinery/vending/V = holder
	var/list/status = list()
	status += "The orange light is [V.seconds_electrified ? "on" : "off"]."
	status += "The red light is [V.shoot_inventory ? "off" : "blinking"]."
	status += "The green light is [V.extended_inventory ? "on" : "off"]."
	status += "A [V.scan_id ? "purple" : "yellow"] light is on."
	status += "The speaker light is [V.shut_up ? "off" : "on"]."
	return status

**Comment by Jalleo** [comment]
Ah okay i was thinking of the airlocks then my mistake.

**Comment by neersighted** [comment]
@WJohn the bug is fixed in #14800, and this is not a tgui bug, but a wire datums bug.
