### ISSUE TITLE
The snowdin away mission can spawn wizards and the spawned wizards can summon guns and stuff

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14836]
it's pretty hilarious but also really, really bad
either remove the wizard spawner or make the spawned wizard only be allowed a select few spells, such as anything but summon guns/magic/events

**Comment by TechnoAlchemisto** [comment]
you have to roll a 20

**Comment by TechnoAlchemisto** [comment]
on the dice

**Comment by PKPenguin321** [comment]
that's better odds than actually rolling wizard

**Comment by SpinnerMaster** [comment]
I can't say I have ever had wizard powers without an admin or snowdin op

**Comment by KorPhaeron** [comment]
So there are 8 away missions in rotation

And there is a 1.6% chance of the die of fate spawning in the loot thing

And a 5% chance of actually rolling wizard on the die.

I don't think an astronomically small chance of a wizard showing up in nuke is the worst thing in the world.

**Comment by duncathan** [comment]
That's a 0.01% chance, for the record.

**Comment by MMMiracles** [comment]
the fact it even happened for this issue to be open is a beautiful thing

**Comment by PKPenguin321** [comment]
i believe the actual odds are 0.0001 for away mission wizards and about 0.0012... for real ones

so yeah, *technically* for every 10 real wizards, there will be an away mission wizard. that doesn't mean very much when the odds for both are so low, however.

take that as you will i guess

**Comment by Incoming5643** [comment]
Yes the fact that this happened was miraculous.

The only real issue here is more a policy thing: The snowden op spawned at their base and went backwards through the away mission until they found the dice and completely went off the rails.
