### ISSUE TITLE
Camera takes time to snap back to you after exiting a morgue.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14841]
Your camera can take a while to snap back to you after leaving a morgue, feels clunky.

![](http://i.imgur.com/25AKlEo.png)

The X is where my camera is, the person circled in red is where I moved to in that time frame before the camera snapped to me. Can take up to 1 second to do so.

**Comment by PKPenguin321** [comment]
Just for the record these are two very different issues of varying difficulty and grouping them together will cause an issue tracking headache when somebody inevitably only fixes half of it

**Comment by lordpidey** [comment]
The 2 light thing is a colorblind fix.  My colorblind roommate literally could not tell when a morgue was occupied, so I made a small change he could see.

**Comment by WJohn** [comment]
Oh, I wasn't aware of that, just seemed like a bug.
