### ISSUE TITLE
Moving a shuttle with atmos pipes on them breaks their connections.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#14859]
![](http://i.imgur.com/cuF2Xnq.png)

**Comment by PKPenguin321** [comment]
i feel awful for the atmos tech that did all that work for nothing

**Comment by francinum** [comment]
I did that work for nothing.

**Comment by duncathan** [comment]
The unfortunate thing is that the pipes would've worked fine but you had no way of knowing that

**Comment by MrStonedOne** [comment]
pipes need an on shuttle rotate, i think this only happens if the shuttle rotates.

**Comment by francinum** [comment]
@MrStonedOne The shuttle didn't rotate between leaving the station and jumping to Deep Space.

**Comment by neersighted** [comment]
There should probably be something like
```
pipe = locate(/obj/machinery/atmospherics/components)
if(pipe)
  pipe.build_network()
```

In the shuttle's rotate proc.

**Comment by MrStonedOne** [comment]
heres the thing, there is no reason the pipes should be coming undone then.

**Comment by MrStonedOne** [comment]
shuttles are suppose to be just changing locs, so things that are connected will be connected at the new loc. there is no reason to be calling build network.

any bug fix should focus on not requiring snowflake.

**Comment by MrStonedOne** [comment]
ha! knew it,


https://github.com/tgstation/-tg-station/blob/master/code/ATMOSPHERICS/atmospherics.dm#L282

**Comment by francinum** [comment]
Moving the shuttle causes pipes to empty their air contents, and may cause them to become completely uninteractable. @MrStonedOne
