### ISSUE TITLE
Hacked Autolathe repeat

### ISSUE THREAD

**Issue by yackemflam** [tgstation/-tg-station#14860]
When I pulsed the autolathe for the illegal tools and then cut the same wire i get a repeat of the illegal tools.
![better to show](https://cloud.githubusercontent.com/assets/16517871/12539745/a50adade-c33c-11e5-9ead-c80039ce38c0.PNG)

**Comment by neersighted** [comment]
Well I'll be.

**Comment by neersighted** [comment]
Thanks!
