### ISSUE TITLE
#14761 Secretly nerfed Cryoxadone

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#14897]
Inside the massive PR (#14761) Neersighted reduced the amount Cryoxadone heals per tick for normal damage by 2/3, lowered the rate it heals clone loss to a QUARTER of what it was, and reduced the amount of oxyloss it heals at cryo temperatures to a FIFTH of what it was.

At no point was this change mentioned in the PR or in the comments, presumably it went unnoticed along with the 115 other changed files. And I can't see how "tgui wires; refactor wire datums; more to come" relates to major balance changes on medical reagents.

Cryoxadone is now literally worse than conventional healing chems, the only reason to use it is because its one of the only chems that heal cloneloss. Styptic powder/Silver Sulf heal more brute/burn over time AND heal when applied, Salbutamol heals more oxyloss. Even trek chems in sleepers heal more.

There is now literally no reason to use a cryotube except when healing cloned people. EVER.

**Comment by CPTANT** [comment]
The fuck is that PR doing anyway, You don't need 100 changed files to change wire UI.

There seem to be changes everywhere to descriptions, which is also unmentioned.

Also are pizza bombs even remotely related to tgui wires?

Isn't this basically completely against the policy of having PR's contain changes to a single system?

**Comment by CPTANT** [comment]
Also is it me or does that PR merge heaters and freezers into one machine, which is also undocumented?

**Comment by PKPenguin321** [comment]
@neersighted what are you doing fam??

**Comment by MMMiracles** [comment]
He added states of effectiveness depending on body temperature, which oddly enough, even the 'best' state you can get from an upgraded cryo's coldness isn't even as good as it was originally before he changed it.

Still, @neersighted what are you doing man.

**Comment by CPTANT** [comment]
How are those changes even remotely related to the PR title?

**Comment by neersighted** [comment]
I was trying to move all healing out of cryo (cryo rewrite was one of the redone machines in that PR), the numbers lined up for -99 -> 100 when timed, however freezer rewrite changed that. In my next PR the specific heat is fixed.

**Comment by ChangelingRain** [comment]
it's not else ifs, it's just ifs

**Comment by CPTANT** [comment]
#neersighted 

So why again was this done undocumented in a completely non related PR?

**Comment by neersighted** [comment]
Because one thing led to another... tgui freezers meant rewriting them as they shared every line of code with heaters (and thus should have been consolidated), and reworking freezers meant cryo had to be redone (well, the way I redid them); removing the heal from cryo meant buffing/tweaking cryox to apply the extra heal at lower temps, and the oxy change is because I fixed bloodloss doing a constant, un-removable 4 oxyloss. The cloneloss appears to have been a typo, but the redic. oxyloss regen was there to try and outheal a bug with blood setting `oxyloss` directly instead of `getOxyLoss`.

The point is please read all the code and commit messages before jumping to conclusions. I'm glad to revert any changes as balanace is not my specialty -- I just timed time from -99 to full to try to get ~similar numbers. It was demo'd and gif'd in coderbus and no one objected.

**Comment by Buggy123** [comment]
To summarize:

Pre nerf, cryo heals:
4 clone per tick
10 oxy per tick
3 brute per tick
3 burn per tick
3 tox per tick

Post nerf, while in un upgraded cryo, it heals:
2 clone per tick
7 oxy per tick
3 brute per tick
3 burn per tick
3 tox per tick

IF upgraded(never happens), cryo heals:
7 clone per tick
9 oxy per tick
5 brute per tick
5 burn per tick
5 tox per tick

It wasn't as large of a nerf as it seemed, sure, but it's still significant. Halved cloneloss heal rate is pretty big. And this also nerfs ghetto cryo, and the secret ice-cryoxadone technique.

**Comment by neersighted** [comment]
The comments are milsleading, You usually hit the second level, and even the third with regular cryo. Its just slower to get there without better freezers. Realisticly someone will probably be fully healed if not in crit before stage 3 kicks in.

You do realize that with the way new cryo works (suspends environment/breath, does not heal directly) this is actually a nerf?

**Comment by Buggy123** [comment]
I hadn't seen how new cryo works, I couldn't find it. But I was under the impression that cryo only lowered your temperature, it didn't heal you directly at all.

**Comment by neersighted** [comment]
Exactly. So to revert the changes would mean less overall healing. You are not as likely to hit stage 3 healing with unupgraded cryo unless you strip someone or they are really hurt. Regardless, if you think cryo is slow, buff freezers, as the are the biggest factor in cryo performance. Also, running over to R&D to get a new matter bin is a piece of cake, they'll even give you a RPED!

**Comment by neersighted** [comment]
@CPTANT Also, I don't think you realize how our codebase works. Wires are hooked into everything; to rewrite wires you must update all the hooks. Pizza bombs had shit code and when I went to fix their wires the things obviously needed a rewrite. As with most things, once you make one small change many others follow (if you want to do it right, at least).

**Comment by duncathan** [comment]
he may not have included all the changes in the pr body which is something he needs to work on; but his changes were all declared in coderbus and reviewed
this isn't an issue
