### ISSUE TITLE
The British are coming to wiring. [Gray vs Grey]

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#14901]
![](http://i.imgur.com/bpBwFdz.png)

**Comment by neersighted** [comment]
BUG OF THE YEAR

**Comment by francinum** [comment]
:us::us::us::us:

**Comment by Iamgoofball** [comment]
:us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us::us:

**Comment by Shapsy** [comment]
tbqh I'm american and I still don't know which way is american/british

**Comment by Nienhaus** [comment]
US is gray, Bristish is grey iirc.

**Comment by Niknakflak** [comment]
I'm american but I use grey more than gray mostly because it all the games I've played they use grey.
???
