### ISSUE TITLE
lizards can use abductor weaponry

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14909]
![wew](http://puu.sh/mJOoB/0f350d16ef.png)
probably not actually a feature

**Comment by Zilenan91** [comment]
Feature.

**Comment by GunHog** [comment]
Intended. 
https://github.com/tgstation/-tg-station/blob/ac75a418a1f3eab99917712ce8e32b19db42fe16/code/game/gamemodes/miniantags/abduction/abduction_gear.dm#L319

**Comment by GunHog** [comment]
Not an issue :)

**Comment by Anonmare** [comment]
This is a pretty big bug tbh, add game-breaking and High Priority tag plz
Fix ASAP

**Comment by RemieRichards** [comment]
it's not a bug, it's intended in the code.
<i>now whether that intention is stupid...</i>

**Comment by demonfiren** [comment]
Remie, it's about as stupid as lizards being barred from hulk with no replacement.

Probably less so.

**Comment by Dorsisdwarf** [comment]
intended feature.

**Comment by Jalleo** [comment]
Reference to xcom thats why its intended

**Comment by PKPenguin321** [comment]
reminder that lizard players got btfo
