### ISSUE TITLE
Test Bomb wires

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14915]
HELP: Fllpz/(Bruce Banner) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Possible bug. http://i.imgur.com/qGadfG8.png . The bomb has double the amount of wires. And when you cut one, two wires get cut at the same time. 

@neersighted

**Comment by PKPenguin321** [comment]
OH OH YEAH I FORGOT TO REPORT THIS
C4 has two wires now too for some reason, and I'm guessing it's the same deal as this! Super weird stuff.

**Comment by neersighted** [comment]
C4 is intended to have two wires (both boom). As for duplicate syndiacate bomb wires, I'm unable to reproduce in my testing. @KorPhaeron when was the round so I can check runtimes.

**Comment by KorPhaeron** [comment]
@neersighted 

Ongoing

**Comment by neersighted** [comment]
I tested live on the thunderdome, and was unable to reproduce. I'm calling bugson on this one, as the wires are assigned in `New()` and there should have been no way for them to be produced twice. I thought it might be a bug since I only ever tested spawning one syndicate bomb, but even up to a dozen I could not reproduce it.

**Comment by PKPenguin321** [comment]
the bomb in the OP is a training bomb which resets its wires after it's done being used. maybe that has something to do with it.

**Comment by neersighted** [comment]
OHHH

**Comment by neersighted** [comment]
Reproduced, I'll attach a fix to my wire colors PR.

**Comment by Lumipharon** [comment]
c4 used to only have 1 wire though. I've never seen it have 2.

**Comment by neersighted** [comment]
A second was added in my wire PR to make 2 wires common to all 'explosives'. They both just boom, its just cosmetic.
