### ISSUE TITLE
Cyborgs cannot close chargers on themselves when out of battery.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14938]
I swear this issue has been made like 6 times already but it keeps coming back.

**Comment by phil235** [comment]
quite an old bug. #8052 #991

**Comment by WJohn** [comment]
Yeah and those issues have dupes of their own. This bug has persisted and returned over and over.

**Comment by Jordie0608** [comment]
This is pretty much by design; if you don't keep track of your power then you suffer consequences, see #6170 for expanded reasoning on this.
The actual issue with this is you can't tell when a borg is out of power, as mentioned in the above.

**Comment by CPTANT** [comment]
"by design"?

That's fucking dumb, who designs a recharger that can't be used by a borg actually needing the power?
