### ISSUE TITLE
Clusterbangs spam admin logs

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14934]
Since the change to announce every grenade detonation (why?), every sub cluster logs going off, then then every single grenade part logs going off as well, resulting in giant walls of text for admins and an unreadable chat.

**Comment by drynwyn** [comment]
Looked over, tricky to fix without copypaste code.  Could be done by overwriting the attack_self for clusterbang fragments and clusterbang flashbangs (the flashbangs they produce are already their own child of flashbang) but that'd mean that people would have to change things in three places if they wanted to change grenade functionality. 

Oh, hang on. Best way to do this would be to add a var. Right, vars exist. Duh.

**Comment by optimumtact** [comment]
They should not be announcing to admins, they were supposed to go to the admin log
