### ISSUE TITLE
Clicking on a table will open the table crafting menu.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#14943]
You're supposed to do this by dragging the table onto yourself.

Also, dragging tables onto yourself will not give the little box icon under your mouse to indicate it is a drag-able thing.

Also it's kind of inconsistent feeling that there HAS to be an item on a table in order to bring up table crafting. I think any time you drag a table onto yourself, item or not, it should bring up the menu.

**Comment by neersighted** [comment]
Probably my bad, I made structure `attack_hand` `interact()`... Easy fix, tables should just ignore `attack_hand`.
