### ISSUE TITLE
reactive tele armor covers all limbs

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#14957]
should only cover the torso.
if this isnt fixed im either making the activation chance way lower or removing it. @kevinz000 :^)

**Comment by kevinz000** [comment]
you're a bug. :(

**Comment by PKPenguin321** [comment]
the meme of the day is grudgecoding after all

**Comment by KorPhaeron** [comment]
Intended and has functioned this way for 3 years now.

**Comment by YakumoChen** [comment]
it's coded that way, according to Kor. Don't see them problem other then 'uncreative teslanerf memes'

**Comment by PKPenguin321** [comment]
RTA *is* a meme, and just because it's coded that way doesn't mean it's good at all. I could code an object that instantly ends the round and just because it would work intentionally doesn't mean it would be a good item. *shrug*

**Comment by Zilenan91** [comment]
If you want to nerf the RTA just toss it on the derelict and all the problems will go away.

**Comment by kevinz000** [comment]
Or youcan emagged defib or lube the guy..

**Comment by 9600bauds** [comment]
You could code an object that instantly ends the round, but it wouldn't be the thing we're talking about, or even close to it. Also probably wouldn't last 3+ years as a semi-easily obtained item.

**Comment by PKPenguin321** [comment]
Bullshit, nobody targets the arms and even if you do you wont always hit the limb you're aiming for anyways. It's a fine counterplay.

**Comment by MMMiracles** [comment]
Not true, I aimed for the legs once when killing a warden during rev.

Then I wasted an entire energy gun's worth of lasers and several harmbatons on them because I kept consistently hitting their left leg. Then they beat me to death.

What I'm saying is aiming for the arms/legs will usually end with you hitting their arms/legs fairly consistently so the armor would become null/void if it only protected the chest region. Also fuck damage caps.

**Comment by Lumipharon** [comment]
RTA has worked this way for 3 years.
It has also had a significant slowdown attached to it for the majority of that time.

Nerf it in some way, it is far, far too OP in it's current state, thanks to powergamers abusing the every loving shit out of it.

**Comment by duncathan** [comment]
RNG can't be nerfed

**Comment by KorPhaeron** [comment]
@duncathan 

We could lower the chance of the RNG occuring.

Or give it the slowdown I originally did

**Comment by PKPenguin321** [comment]
or add a cooldown between warps so you can't dodge 40 consecutive attacks
lots of options for nerfing here

**Comment by Zilenan91** [comment]
Or just throw it on the derelict so there's even more of a point to go out there.

**Comment by Dorsisdwarf** [comment]
I like the idea of a short cooldown to the RTA's teleport, so i-

waaait, I've been baited into discussing ideas on a feature request on the github.
Away with ye,
