### ISSUE TITLE
Minimaps crash local servers.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#14951]
When a local server tries to prepare the minimap subsystem, it gets hung up for so long that the server crashes(or at least Windows forces a crash since the server isn't responding).

I am currently unable to test my code and I am frazzled.

**Comment by PKPenguin321** [comment]
we know. https://github.com/tgstation/-tg-station/pull/14950

**Comment by KazeEspada** [comment]
Im gonna run a server, and hopefully it works this time and close the issue.

**Comment by KazeEspada** [comment]
It's not minimaps now, its wires that are runtiming to hell and back.

**Comment by xxalpha** [comment]
Well change the PR title and description.

**Comment by MrStonedOne** [comment]
Fixed
