### ISSUE TITLE
EMP breaks AI's ability to interact with tgui

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#14969]
rev c5cf2b3dca0999c9b0cf87eac1d9e5bf68361200 

I was just EMPed as an AI and even after several minutes all buttons on any tgui was greyed out.

**Comment by xxalpha** [comment]
@neersighted

**Comment by neersighted** [comment]
Reproduced, the UIs are disabled due to `incapacitated()` returning true. This appears to be because the AI mob has its `stunned` set to 3. Not quite sure what expected behavior of `stunned` is here.
