### ISSUE TITLE
You can teleport via mulebots

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#14966]
rev: 0debb6cb68829429f4d53f0e52e30dcbc0abcbf6

H2Repr0duce420noblazetelep0rt:
0. Turn off 'return home after delivery' on mulebot
1. Have your mulebot deliver you somewhere
2. Try to climb back onto the mule
3. Get blocked by flaps, you don't end up on the mulebot
4. Send mulebot home/somewhere else
5. Wait
6. Get teleported to the mule's latest drop point

**Comment by phil235** [comment]
Something to do with buckling. You're buckled despite not being able to get on top of the bot.

**Comment by Actionb** [comment]
Even if I move between step 3 and 4, I will still get teleported once the mule reaches its drop point. 
It even works out of disposals pipes.
Moving usually unbuckles you off a mule, no?

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/42cb52d9e2fc6fe7a44cc42e570d989b44223860/code/modules/mob/living/simple_animal/bot/mulebot.dm#L368
