### ISSUE TITLE
Can't adjust SMES input/output

### ISSUE THREAD

**Issue by Grazyn** [tgstation/-tg-station#14965]
The pop up window when you try to change the input/output says: New input target (0-0). If you type any number it will just set it to 0. Using arrow buttons will set it to 0 as well and grey out the arrows.
Also deconstructing the SMES won't return a capacitor, but you need it to rebuild.

This was on ministation btw

**Comment by Grazyn** [comment]
Rebuilding the SMES apparently fixes it. You still have to get another capacitor though

**Comment by neersighted** [comment]
This is a mapping error, something is wrong with the max input/output levels on that SMES unit.

**Comment by feemjmeem** [comment]
This is pretty major.

**Comment by Grazyn1** [comment]
I confirm SMES are bugged on other maps as well

**Comment by Grazyn** [comment]
I confirm they are bugged on other maps as well

**Comment by neersighted** [comment]
Nevermind, its a construction error. @Razharas somehow removed the capacitor from the default SMES components, and capacitors are used to calculate input/output max.
