### ISSUE TITLE
Slaughter demon event is happening when it shouldn't

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#14972]
There is even a comment in the weight of the event. And the timer is kinda wrong aswell, since they spawn really near roundstart.
>weight = 0 //Admin only

**Comment by KorPhaeron** [comment]
I think it is kinda funny when it happens and think we should have more rare round altering events and gamemode crossovers anyway.

**Comment by lzimann** [comment]
I totally agree, but clearly the weight 0 here is not working, even if we want more random and deadly events to happen.

**Comment by Actionb** [comment]
Ehhhh, a slaughter demon gibs people, which can fuck up rounds like gangs or rev pretty badly.

**Comment by MMMiracles** [comment]
I'd take a slaughter demon over a revenant.
