### ISSUE TITLE
You can't unbuckle by clicking on the object you/someone else is buckled to

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#14970]
If you buckle yourself to a chair/bed, you can unbuckle by resisting or clicking the alert icon in the top right part of the screen, but clicking the chair or bed itself has no effect. This also holds true for unbuckling other people, which means you can't unbuckle others at all.

**Comment by phil235** [comment]
This doesn't happen with vehicle though.

**Comment by phil235** [comment]
Here's the culprit: https://github.com/tgstation/-tg-station/commit/87642fa588e63e515c9515f8f1fe25b14855edd3#diff-ac67a04d0e99b8458714248c84118bedR36
Needs a `. = ..()`
