### ISSUE TITLE
Malf AI shuttle recall

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#14990]
traitormalfs don't have a shuttle recall. Having no way to postpone till you have points to nuke because your points were wasted on bugged abilities is no fun.

**Comment by Zilenan91** [comment]
I think this is a feature tbh

**Comment by KorPhaeron** [comment]
The AI is not currently required to nuke so I don't think this is a big deal.

Nuke is your BONUS MAJOR VICTORY, you're not gonna be able to do it every time

**Comment by Anonmare** [comment]
Eh, rogue AIs don't need a recall ability in my opinion (as a usual AI player). Plus it would make some, *certain* players even more sodium chloride than they already are about the AI.

**Comment by octareenroon91** [comment]
>abilities are bugged
>add a new feature
>new feature changes balance and obviates roleplay.

It still sucks to find you've wasted resources on useless stuff, but I don't think adding a recall power will fix that.

Just manipulate a human with comms console access to buy time.
