### ISSUE TITLE
Camera network upgrade is bugged (the malf power)

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#14993]
HELP: Sligneris/(Avalon) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): I tried to upgrade camera(?|F) network and it did brighten everything up, but it didn't give X-ray vision like it did before. 

It is in malf_modules.dm if anyone would like to take a look

**Comment by GunHog** [comment]
I coded this. Give me a moment to test. Try to get more data from the player if you can.

**Comment by KorPhaeron** [comment]
@GunHog 

It was ages ago sorry, I just remembered to put it up now (didn't want to do it while the round was ongoing and give them away)

**Comment by GunHog** [comment]
I...am not able to run a local copy right now. It keeps crashing at loading. When this is fixed, I will test it then.

**Comment by GunHog** [comment]
Someone changed cameras to not include assemblies. I will patch it up soon.
