### ISSUE TITLE
Blobs cannot expand onto a tile using the verb if there's a blob spore there

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#14991]
It hits the blob spore and doesn't expand. Very bad.

**Comment by ChangelingRain** [comment]
This is in theory a very easy fix, except the fix causes other problems for no reason I can figure out.
The fix being to have it check CanPass() in expand instead of density, except blob tiles can apparently pass a bunch more things than expected.

I'll fix it like, tomorrow.

**Comment by Zilenan91** [comment]
Can you also remove the RnG on expanding over walls? I expanded on a wall like 6 times and wasted 30 resources just to make a girder pop and have to expand on that 2 more times.
