### ISSUE TITLE
all camera networks broken AGAIN

### ISSUE THREAD

**Issue by CPTANT** [tgstation/-tg-station#15006]
Can't view any camera on cam consoles. fucks with AI etc. etc.

**Comment by neersighted** [comment]
Dupe of #14985

**Comment by CPTANT** [comment]
that one says AI cant use camera's

ALL camera's are broken

**Comment by neersighted** [comment]
Its an issue with all cameras. Please read the other issue that was closed as dupe in favor of that one.
Regardless, it is the same problem. And a PR is up.

**Comment by Dorsisdwarf** [comment]
Closed due to a near-dupe of #14985. A fix is inbound already.
