### ISSUE TITLE
Parrots can't path to potential items to steal if they're pearched

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#15028]
If a parrot is on a pearch A* will incorrectly surmise that there's no possible paths from the tile, even if there are.

Practical effect: Poly won't try to steal items once he finds a perch unless said items happen to be cardinally adjacent to him.

**Comment by Menshin** [comment]
A* is working fine in the case of an nonpassable start tile :

![astarworks](https://cloud.githubusercontent.com/assets/7117411/12684066/00f47048-c6bd-11e5-9aae-87e3aea68902.gif)


What bug makes you think it isn't the case ?

**Comment by Incoming5643** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/parrot.dm#L611

Uses A* to see what items it can path to pick up items, but if poly is perched on a computer or the like he won't ever try to steal items unless he can do so without moving from his perch

Maybe something is getting passed to A* wrong then.

**Comment by Incoming5643** [comment]
Alright so poly has trouble pathing for items even if he has a nondense perch.

So this is **parrot problems**

**Comment by Menshin** [comment]
It's rather a problem of passflag not taken into account by Astar for some objects passibility.
I'm working on it.
