### ISSUE TITLE
Condiment Bottle unit transfer issue

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15025]
I set the unit transfer amount to 5, drank a swig, and it made me drink 10.

**Comment by PKPenguin321** [comment]
i dont believe transfer amount has any hold on how much you drink from a bottle with any bottle

**Comment by Zilenan91** [comment]
Really? That's weird, if it's transferring something you'd think it'd transfer the same amount inside of you.

**Comment by neersighted** [comment]
Drink code doesn't account for transfer amount.

**Comment by Zilenan91** [comment]
gotcha
