### ISSUE TITLE
Drop bomb verb not dropping bombs on my ghost.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#15036]
In the same round when buildmode gen was screwing up, I was also changing through my view ranges constantly. At the end, the drop bomb verb was dropping bombs off centre from my ghost.

**Comment by Shapsy** [comment]
Did you move from when you initially pulled up the menu, cause it decides the location from where you pulled up the menu, not where you actually are when you hit "okay"

**Comment by Aloraydrel** [comment]
^^ this tbh

**Comment by KorPhaeron** [comment]
The same thing reportedly happened when using a bomb while blood jaunting

**Comment by Ausops** [comment]
>cause it decides the location from where you pulled up the menu

that's really not nice but it might have been that, I'm not sure
