### ISSUE TITLE
Swarmers can dupe resources with the crusher

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15040]
HELP: redacted (?) (PP) (VV) (SM) (FLW) (TP) (REJT): you can use the swarmer deconstruction icons to produce resources, apparently, if you deconstruct one on a conveyor the tile moves and the tile rolls into the crusher, making metal

**Comment by Anonmare** [comment]
The Swarmer's blue tile things are also affected by space wind too. It's hilarious.

**Comment by tkdrg** [comment]
Probably just needs to be anchored
