### ISSUE TITLE
CTF Flag can be duplicated in-hands

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#15054]
**How to do:**
Play CTF, pick up a flag (I did it with the blue flag), click on the flag in your one hand with your empty hand, you now have a flag in your other hand and the sprite is invisible (inhands is visible so other people can see you're waving around two of the enemy's flags).

**Why this is bad:**
The first flag can be dropped and people can think it's safe because no-one holds it and hey it even teleported back to where it's supposed to be until you see the big red letters that the other team won.
The duplicate flag can be used exactly the same as the original and slows you down exactly the same as the original.

I imagine other items related to it might also be affected if this wasn't some weird higgs bugson.

**Server revision compiled on: 2016-01-29**
42530f1e960224dd4a0bddbf66d2627f073e73c4

**Comment by MrStonedOne** [comment]
oh wow....

**Comment by CosmicScientist** [comment]
That wasn't sarcastic right? I'm not being an ignorant igloo am I?
