### ISSUE TITLE
Space drugs are lame

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#15063]
I mean, their low-dosage effects haven't changed a ton, but high doses used to be a lot more interesting. At 999U, you'd hallucinate things attacking you constantly, hear a barrage of voices, and fall over every 5 seconds. Now there's no difference between 50U and 900.

After testing, I think hallucination itself may have been nerfed. Even manually setting hallucination to 999 doesn't have the same effect as it used to.

**Comment by freerealestate** [comment]
ok to be honest all their effects are lame as fuck

**Comment by Buggy123** [comment]
Other drugs are at least useful. Space drugs do literally nothing but make you hallucinate, so they should do it fucking well.

**Comment by PKPenguin321** [comment]
100% real legitimate issue, completely a bug

**Comment by freerealestate** [comment]
some hitler decided relatively recently all issues had to be bugs??
and that any other type of issue be relegated to the feedback forum where it won't be seen??

issue tracker wasn't serious business for like the first three years

**Comment by Iamgoofball** [comment]
I'm sorry, but fucking TAKE IT TO THE FEEDBACK FORUM.
