### ISSUE TITLE
Toxin is very weak

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#15064]
Drank three bottles the other day and it put me into slightly dark green health

Was going to approach Goofchem about buffing it instead of making an issue but then I didn't

**Comment by Iamgoofball** [comment]
i need to know what bottles you drank and if they were straight from the poison kit or not

**Comment by Shapsy** [comment]
He probably means the generic toxin in hacked vendors that deal 1.5 tox per tick. Are you sure you didn't have a healing virus or something?

**Comment by Firecage** [comment]
Shapsy, to be fair though. Most of the toxins in the chemicle kit are kinda weak, when used alone. You have to make a toxin cocktail from them, which makes sense.

**Comment by Iamgoofball** [comment]
The generic toxin from the vendor is really weak, yeah.

**Comment by freerealestate** [comment]
Yeah I meant the toxin bottles in medivends or whatever they're called

**Comment by PKPenguin321** [comment]
that toxin only exists in the first place to be a reagent in other recipes, it itself doesn't have to be super strong

**Comment by freerealestate** [comment]
no, it doesn't have to be anything, but it would useful for traitorous doctors and frankly make more sense if it was

**Comment by PKPenguin321** [comment]
there are so many traitor chems already

**Comment by Shapsy** [comment]
1.5 tox per tick is pretty good if you stack it with other easily made toxins like cyanide and unstable mutagen

**Comment by octareenroon91** [comment]
All toxins take time. The plain 'toxin' is for making plant and pest killer.

**Comment by Dorsisdwarf** [comment]
Balance meme
