### ISSUE TITLE
CTF flags can sometimes vanish

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15061]
They won't reset properly, no clue why

**Comment by optimumtact** [comment]
This cucked me hard

**Comment by Incoming5643** [comment]
If someone's deleted while holding the flag (by say the round ending) then the flag will delete with them.

Do what the black box recorder does and create a new instance of the flag on the flags destruction.

**Comment by KorPhaeron** [comment]
Oh that makes sense

Thanks @Incoming5643
