### ISSUE TITLE
You can pull people carrying the CTF flag

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15062]
To bypass the slowdown

**Comment by GunHog** [comment]
A faster thing which can pull can other things (such as a guy on speed drugs pulling someone severely hurt) will bypass the slowdown of the slower thing.

I do not know how you plan to fix this without changing how pulling works. (Which I do not recommend.)

**Comment by Iamgoofball** [comment]
I'd argue that this is a feature, encourages teamwork. Also, pull is better than grab because it doesn't have the slowdown stuff in general for humans. Please don't nerf pulls over this.

**Comment by KorPhaeron** [comment]
Relax I'll just extend the nopush flag to pulls and give it to them on spawn or something

**Comment by Iamgoofball** [comment]
That works

**Comment by Dorsisdwarf** [comment]
This is pretty much how the game works. Fast things can move slow things faster than slow thing on its own.
