### ISSUE TITLE
Some people are blurry and small

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#15060]
Dwarfism through genetics I believe? It looks like shit, why is that allowed?

**Comment by xxalpha** [comment]
The real question is why is this allowed.

**Comment by bgobandit** [comment]
not a bug, come on man

**Comment by duncathan** [comment]
I think it looks good

Subjective issue; feedback forum

**Comment by Jordie0608** [comment]
Also the blur is BYOND's fault and we can do jack all about it

**Comment by freerealestate** [comment]
really gotta stop kicking sand into xxalpha's vagina

also to be fair it's the maintainer who pulled the code's fault for thinking the presentation was of acceptable value

**Comment by PKPenguin321** [comment]
aw shit who invited this guy back

**Comment by duncathan** [comment]
Of course it's acceptable it's fuckin hilarious
