### ISSUE TITLE
It's not possible to put the new bras on as a man or a woman from the dresser

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#15077]
Important to note that when trying as a woman I was either made into a woman via (I assume) admin intervention or surgery.

Also I don't think it's possible to actually put on any of the female restricted clothing? I just didn't know what the rest of them looked like.

**Comment by neersighted** [comment]
I don't think anything is gender restricted in a mirror.

**Comment by MMMiracles** [comment]
Dressers have always been a way to put on gender-restricted clothing.

**Comment by Incoming5643** [comment]
I was able to yesterday, are you sure the server was actually updated enough for those outfits? Basil might be lagging behind for whatever reason

**Comment by newfren** [comment]
Turns out I'm just and idiot who thought that the bra was separate from the underpants and kept covering it with an undershirt.
