### ISSUE TITLE
Lizard hissing is broken.

### ISSUE THREAD

**Issue by TheNightingale** [tgstation/-tg-station#15086]
How to reproduce:
1) Be a lizard.
2) Say anything with 's' in it.
3) Nothing happens, you speak like a human.
4) Cry.
(Basil, 16:00 GMT, 30/01/2016)

**Comment by duncathan** [comment]
This is a known issue of our 510 branch; it will be fixed before merge to master
Just so you know it'll only happen in basil; your hissing is around on sybil
