### ISSUE TITLE
Chaplain could somehow see ghosts

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15107]
He said it was after he put on mesons

http://imgur.com/MeLPvYv

He unfortunatley got put into crit right after I asked him for a screenshot, but as you can see on the far right, ghosts were visible to him even in his body

His see invisible was set to 45, even with the mesons off.

Putting his mesons on myself did not reproduce the bug.

**Comment by PKPenguin321** [comment]
double check if admin intervention happened at any point

**Comment by bgobandit** [comment]
was it summon events

**Comment by GunHog** [comment]
Could be related to his magic camera, I see it in his pack.

**Comment by freerealestate** [comment]
accidental fun

**Comment by phil235** [comment]
You need a see_invisible of 60 to see ghosts. 45 is pretty much normal vision.

**Comment by KorPhaeron** [comment]
Never been reproduced
