### ISSUE TITLE
The bottom of the chat box is cut off in the latest skin change

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#15100]
About 8 px of the chat box is clipped offt the bottom!

<img src=http://i.imgur.com/uO47CWj.png>

specifically scrolling down to the bottom leaves the scrollwheel there, short of where it should be.

Caused by #15047

**Comment by neersighted** [comment]
Delete `C:\Users\incoming\Documents\BYOND\Skins`

**Comment by Incoming5643** [comment]
telling every player to manually delete a folder isn't going to be a valid solution. Isn't there any way to force an update?

**Comment by xxalpha** [comment]
Revert everything, let's not touch this again.

**Comment by MrStonedOne** [comment]
This isn't a skin cache issue.

its a you fucked up neersighted issue =P

The chat box NOT THE INPUT BAR is fucked up.

**Comment by neersighted** [comment]
Screenshot please?

**Comment by Incoming5643** [comment]
I would but by definition it'd catch bits of the round in progress, just get on sybil

**Comment by Iamgoofball** [comment]
incoming just spam Who and then screencap it

**Comment by Incoming5643** [comment]
screencap added
