### ISSUE TITLE
Can't make/remove blob from a person via the traitor panel.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#15115]
Can't make/remove blob from a person via the traitor panel.

On a related note, blobs from the transform option in the PP don't seem to have working resource nodes.

**Comment by KorPhaeron** [comment]
Stop trying to shirk your blob related duties

**Comment by ChangelingRain** [comment]
Blob code right now is dumb, but datum antags will fix that.

Resource nodes should always work, given that they work off a ref to the overmind that placed them.

**Comment by ChangelingRain** [comment]
blob, like swarmers and revenants, is now a mob-based antag so this bug no longer exists
resource blobs also always work unless specifically edited to have a different/no overmind
