### ISSUE TITLE
Chamo skin genetic power + death/crit

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15111]
If you're dead or critical you shouldn't be invisible
1. Dead bodies can NEVER be found
2. From a realism point of view, your cells are dead, they shouldn't be blending in anymore and you should gradually return to your normal self.

**Comment by KorPhaeron** [comment]
Get good

**Comment by Lumipharon** [comment]
>Get good

**Comment by Iamgoofball** [comment]
ahahaha

thanks for the body hiding idea

**Comment by PKPenguin321** [comment]
>My powergaming tool has a drawback, must be a bug

Nice issue report friendo :)

**Comment by Ausops** [comment]
The cold resistance power persists upon death so you'd have to change that, as well as other powers.

**Comment by Anonmare** [comment]
That's the downside to the chameleon power.
X-ray makes you flashable through walls
Cold resistance makes you unable to use cryogenics
Hulk makes you unable to use guns

TK and Shadowmeld are really the two powers with no downsides

**Comment by kevinz000** [comment]
@PKPenguin321 pls for once I'm not even abusing this it's that I notice someone dead on suit sensors and I can't find them and I use point-to and realize they're invisible.

**Comment by Shodansbreak** [comment]
Shadowmeld doesn't exist anymore Anonmare

**Comment by Dorsisdwarf** [comment]
@kevinz000 Then it looks like people who go down with this mutation aren't totally SOL
