### ISSUE TITLE
Killing a shunted AI core prevents AI Nuke

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#15114]
fucked me over in two different rounds now, if I shunt in desperation, and my AI core is killed, it counts as killing the AI for the purposes of ending the Doomsday timer, even if my Shunt APC is fine. The shuttle is then free to go away, thus ruining any objectives I may have had related to nuking (like Hijack or generally killing my target with a nuke)

**Comment by KorPhaeron** [comment]
Considering the nuke isn't required anymore and the fact that the nuke going off at all is somewhat controversial, I might just leave this as is. 

Being forced to abandon your core means you lose the nuke.

**Comment by Anonmare** [comment]
Shunted Ai counts as a separate mind, if I am correct, so there's no point to shunting at all

**Comment by Shadowlight213** [comment]
Nuke is actually inside the AI core itself, so killing the core causing the nuke to stop makes perfect sense.

**Comment by xxalpha** [comment]
Are you supposed to win malf if the nuke is disabled?

**Comment by Shadowlight213** [comment]
@xxalpha malf is ded. This isn't malf. AIs just think nuking is required so they can get their sweet valids on by killing everyone at once.
