### ISSUE TITLE
all non engineering smes start full

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15127]
While telecomms, AI and grav gen should start full, currently every non engineering smes on map starts full including solars smes and electrical maint smes.

**Comment by PKPenguin321** [comment]
Does this mean the AI dies as soon as its APC drains?

**Comment by Shadowlight213** [comment]
updated to include AI

**Comment by Jalleo** [comment]
@WJohn please tag easy fix and fix it please. Second is not a requirement.
