### ISSUE TITLE
Simple animals scanned with the health analyzer show bizzare amounts of HP

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15124]
For example, a blobbernaut with 240 hp, is 240% healthy

**Comment by ChangelingRain** [comment]
There's an 100% chance it's displaying [health]%, which works fine for humans and literally nothing else.

**Comment by phil235** [comment]
If that's the case, the fix is easy, just use `round(health/maxHealth)` or something.
