### ISSUE TITLE
Point blank fire is bugged

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15131]
If you are one tile away, doesn't matter where you aim, it will always trigger the execution, BUT, it will only work if you are aiming for mouth. If you aim for anything else, it will trigger it, but even after the whole bar is completed it will cancel as if you walked away

**Comment by phil235** [comment]
Can't reproduce on my 3 weeks old branch. Aiming at a mob right next to us properly shoots the mob point blank, unless we target the mouth which triggers the execution mode.

**Comment by lzimann** [comment]
It has been happening recently.

**Comment by KorPhaeron** [comment]
Happened to me while aiming for the chest on help intent

**Comment by phil235** [comment]
Probably linked to  #15026

**Comment by Zilenan91** [comment]
Happened while aiming at the head for me, was using a double-barreled shotgun.

**Comment by KazeEspada** [comment]
So being adjacent will always trigger execution shot even when aiming for anywhere but the mouth?

**Comment by KorPhaeron** [comment]
Yes

**Comment by KazeEspada** [comment]
To be honest, this is slightly better then the old functionality which was to melee instead.

**Comment by lzimann** [comment]
Well but you can't pointblank people, and the execution won't even work if you aren't aiming for the month(it triggers but will always fail)

**Comment by KazeEspada** [comment]
Should I restore old functionality or add the ability to actually shoot an asshole in melee range(without the execution timer).

**Comment by lzimann** [comment]
I feel like how it was working was already good, with no real reason to change.

**Comment by phil235** [comment]
How it should work when next to the target mob:
- if harm intent: melee attack
- if help intent, execution mode if mouth selected otherwise pointblank shot.
