### ISSUE TITLE
Metastation Chapel

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#15130]
Metastation Chapel area has three air alarms. There are two in the mass driver section and one in the main room.

**Comment by octareenroon91** [comment]
too many or too few?

**Comment by Dorsisdwarf** [comment]
Too many. There are two literally across the room from each other.

**Comment by Metacide** [comment]
I'll remove the duplicate in the mass driver room, but having one in each of the other rooms seems fair.
