### ISSUE TITLE
Industrial welding tool is listed twice in hacked autolathes

### ISSUE THREAD

**Issue by TrustyGun** [tgstation/-tg-station#15142]

**Comment by Buggy123** [comment]
Was this last round? I may have hacked it twice accidentally or some shit.

**Comment by TrustyGun** [comment]
it was the round with the blob and nuke ops; how can you hack it twice

**Comment by Buggy123** [comment]
I pulsed the wire and then cut it, maybe it stemmed from that or something?

**Comment by Buggy123** [comment]
Also thats the round yeah.

**Comment by octareenroon91** [comment]
I have also been seeing the autolathe double up on hacked designs.
