### ISSUE TITLE
Stuffing a monkey into a processor creates a bucket.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#15156]
I... what? Why?

**Comment by KorPhaeron** [comment]
Dupe

**Comment by Niknakflak** [comment]
Not a bug

**Comment by octareenroon91** [comment]
Bucket of blood. Feature.

There was a bug where you couldn't do anything else with the processor after that.

**Comment by drynwyn** [comment]
Bucket of blood, yeah. This is part of the Old Wisdom.

**Comment by freerealestate** [comment]
monkey-bucket sprites?
