### ISSUE TITLE
(usability issue) Ordering multiple cargo crates is horrible and inefficient.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/-tg-station#15158]
We need a way to buy and authorize multiple crates at once, getting a bunch of crates one by one is incredibly slow and tedius when you're ordering a lot of them.

**Comment by Lumipharon** [comment]
order crate
go back
repeat
go into orders menu and approve everything

**Comment by Buggy123** [comment]
What if i want to order 40 crates, that takes like 8 minutes.

**Comment by Dorsisdwarf** [comment]
If you have the points for 40 crates you have the time to order them.

**Comment by neersighted** [comment]
You'll be glad to hear that I'm working on a tgui cargo console then.

**Comment by Buggy123** [comment]
Wew!

**Comment by neersighted** [comment]
![Demo](http://i.imgur.com/FrHWec7.gifv)

**Comment by Buggy123** [comment]
Any ETA on this?

**Comment by neersighted** [comment]
Well, its included  in #15135

**Comment by Dorsisdwarf** [comment]
hnnnnghghg
