### ISSUE TITLE
Revheads shouldn't instalose if they disconnect

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15159]
>inb4 feedback forum

here is why:
1. only 3 heads of staff, so the game scales it down to there only being 1 revhead
2. said revhead's internet decides to shit itself 40 seconds into the round
3. the round instantly ends
4. the revhead reconnects and is met with anger/a ban

**Comment by WJohn** [comment]
I say that antags who lose upon leaving the z level or hiding in a locker should be given some grace timer when disconnecting, maybe 3 mins or something.

**Comment by PKPenguin321** [comment]
Especially so admins can have a chance to react and maybe put a new player in the body.

**Comment by Dorsisdwarf** [comment]
thats hilarious

**Comment by tkdrg** [comment]
Just make it message admins and then wait like 30 seconds, sorta like mulligan does

**Comment by Dorsisdwarf** [comment]
Wait at least a minute because le byond ad memes

**Comment by PKPenguin321** [comment]
this could probably do with a priority tag as i've seen more than one round get instacucked by this

**Comment by ChangelingRain** [comment]
Duplicate of #13039
