### ISSUE TITLE
You can put a grab in the trash.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#15161]
Blame @KorPhaeron

**Comment by xxalpha** [comment]
:put_litter_in_its_place:

**Comment by Incoming5643** [comment]
It's funny because Kor is all about putting grabs in the trash

**Comment by tkdrg** [comment]
@KorPhaeron 
phil said this is caused by https://github.com/tgstation/-tg-station/commit/621c59ad3da908ba28dc547e321aff2f1808d95e#diff-4b6c20ec7d37222630e7524d9577e230L312

**Comment by nukeop** [comment]
I just saw this again the other day. Hilarious.

**Comment by nukeop** [comment]
I just saw this again the other day. Hilarious.

**Comment by nullbear** [comment]
fixed with https://github.com/tgstation/-tg-station/pull/16901
