### ISSUE TITLE
NarSie Summoning on white ship is overpowered

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15166]
It only has ONE place to enter from without a hardsuit. A lot of constructs can camp out and artificer MM can NAIL anyone trying to enter. Unless you have a bomb you're not going anywhere near the shell if its in center and arties have already built a ton of walls.
OH AND CULT WALLS ARE NOT DECONSTRUCTABLE.
Cultists alternatively can make some wall runes and the ship will be impentrable without welding or bombs.
By the time you manage to get in the 3 minute timer will be long over and narnar will eat you :)

**Comment by newfren** [comment]
i ded tag please.

**Comment by Skullyton** [comment]
Why can you summon narsie anywhere off the station Z Level?

**Comment by StormAGeddonz** [comment]
what @Skullyton said and since you can, why does summoning narsie off station count as a cult win if their mission is to take over the station?

also its super easy to summon an ELDER GOD

**Comment by Lumipharon** [comment]
If cult walls are indestructable, also cult runes, any semi-robust cult can do this literally anywhere - other then being able to move the ship nonstop to chain stun, what makes the white ship special?

**Comment by AdamElTablawy** [comment]
I think they could initiate the summoning on the white ship and then fly it off into deep space immediately?

AKA you don't even stand a fucking chance, gl finding the white ship in space.

**Comment by PKPenguin321** [comment]
@StormAGeddonz the white ship can be flown to the station and therefore be a part of the station, you dip

**Comment by Lumipharon** [comment]
Wait, I'm not terribly familiar with neonewcult mechanics.
As I understand it, you summon narnar shell, sac nerds and stuff the shell with summon orbs.
Summon orbs I think also let you summon the shell to you? (Pretty sure I remember the option from yesterday).

Now not saying the whiteship isn't abusable, but I'm trying to understand exactly what this thread is saying can be done that can't already be done with cult walls and wall runes.

**Comment by Zilenan91** [comment]
Summon orbs are stuffed in the immobile shell to START the summon. Also they weren't summoning narnar off-station in the white ship, they were landing it on the station and then starting the summon with the whole ship fortified, most likely.

**Comment by Iamgoofball** [comment]
why can't you summon Dominators on the White Ship and pull the same tactic?

Just port the gang area blacklists to narsie summoning and call it a day

**Comment by Lumipharon** [comment]
It's actually really gay that you can't drop a dom in maint anymore - lots of interesting places you used to be able to use as a base.

**Comment by PKPenguin321** [comment]
This can be closed now that newcult is reverted

**Comment by Zilenan91** [comment]
It'll still happen, and still be awful, but yeah this should probably be closed.
