### ISSUE TITLE
Rogues AI's turning on doomsday flips out

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#15170]
AI was on the station the whole time and this keeps happening
![ss 2016-02-03 at 09 24 05](https://cloud.githubusercontent.com/assets/13092039/12785188/44ceab2c-ca59-11e5-9e88-b2e8324b3ee4.png)

had to delete the AI and respawn it to get it to stop

**Comment by Shapsy** [comment]
Someone mentioned in OOC that spawning an additional self destruct device might help solve the issue, but spawning both a self destruct device and a nuke ops nuke did nothing to stop the spam

**Comment by xxalpha** [comment]
Only happens if AI is not on the station's z level.
