### ISSUE TITLE
Unable to put bible into crusader armor exosuit slot

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15189]
Oversight most likely, you can do it on the robes.

**Comment by KazeEspada** [comment]
Balance

**Comment by Zilenan91** [comment]
Actually reopening this because of the new weapon pr, you have no place to put your bible if you take a claymore or something because you need the claymroe on your back

**Comment by Dorsisdwarf** [comment]
Wear the robes then

**Comment by KorPhaeron** [comment]
> you have no place to put your bible if you take a claymore or something because you need the claymroe on your back

Intended that the larger item will give your inventory management problems as a tradeoff to being stronger

**Comment by Zilenan91** [comment]
Well yeah but the bible doesn't really benefit you at all, all it does is heal other people. I don't see why you should code in chaplains being selfish.

**Comment by Dorsisdwarf** [comment]
Spriting chaplain armor was a mistake.

**Comment by PKPenguin321** [comment]
Close this its 200% feedback forum
