### ISSUE TITLE
Autolathe hacking is completely broken to lizards

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15181]
when trying to get at the wires, says it's offline
persisted even after reconstructing the entire thing, and there was power in the room

Edit : later saw a human able to hack these perfectly and I still couldn't access the lathe what the fuck is going on

**Comment by PKPenguin321** [comment]
probably caused by https://github.com/tgstation/-tg-station/pull/15143

**Comment by xxalpha** [comment]
Is this recent?

**Comment by Zilenan91** [comment]
Today yes

**Comment by xxalpha** [comment]
Can't reproduce.

**Comment by Boredone** [comment]
If I remember this, I hacked it by just using a multitool on the autolathe to open the wire menu when it was screwed open.
Still, would probobly be best if you didn't need to use a multitool/wirecutter on a screwed open autolathe to open the window.

**Comment by Zilenan91** [comment]
Did they change it so that you have to use a tool to open wires now? Like you screwdriver it and you can't just click on it to open up the wires?

**Comment by neersighted** [comment]
Yeah this is a bug in machines in general, attack_hand bails if the panel is open.

**Comment by Dorsisdwarf** [comment]
non-issue... I think?
