### ISSUE TITLE
As A+ blood type, I died to toxin damage from A- and O- blood.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#15184]

**Comment by BananaPoop** [comment]
I tried to reproduce this but failed. Are you sure the species of both donor and receiver matched, eg Human and human.

**Comment by KazeEspada** [comment]
Bloodbags. The only outside damage was spesscarp.

**Comment by Incoming5643** [comment]
there is always the chance that someone used that O- minus bloodbag, then an inept doctor had someone with a different bloodtype donate into it. That would create a mislabeled blood bag that could poison you.

**Comment by KazeEspada** [comment]
These were spawned in the freezer.

**Comment by PKPenguin321** [comment]
They could have placed the refilled bags back in the freezer, especially if it was deliberate sabotage.

**Comment by Jalleo** [comment]
We need a positive verification from a admin or coder.

**Comment by phil235** [comment]
Can't reproduce, my guess is a tainted bloodbag. If you put a A+ blood bag in an iv drip and have someone donate even a tiny amount of their B+ blood, then all the blood in the bag is now B+.

**Comment by Incoming5643** [comment]
B+? shouldn't it, if anything, turn into AB+

**Comment by phil235** [comment]
Can reproduce now!
