### ISSUE TITLE
Guns don't have any feedback when they are out of ammo

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15198]
They used to *click* when they had no more ammo, now they don't do anything, which can fuck you pretty bad.

**Comment by KorPhaeron** [comment]
@KazeEspada

**Comment by Buggy123** [comment]
While we're at it could we change the beep some guns make to something that DOESN'T sound like a alarm clock? Because nothing is worse than playing spessmens and then suddenly hearing "BEEP BEEP BEEP WAKE UP YOU FUCK YOU GOTTA GO TO WORK"

**Comment by KazeEspada** [comment]
Gun code is a mess of spaghetti, and fixing the spaghetti reveals that it was fucking broken the entire time.

**Comment by Lumipharon** [comment]
but the *click *click did work previously.

**Comment by KazeEspada** [comment]
Yes, because guns were checking that upon firing rather then before firing. They had a proc that handled making sure it can shoot before firing, but this proc was never called until i fixed it.

**Comment by Steelpoint** [comment]
I enjoy having good features be broken and never fixed.

**Comment by phil235** [comment]
Seems fixed, I can't reproduce it.
