### ISSUE TITLE
Breaching slug magazines have no sprite and are filled with meteorshot instead of slugs containing meteorshot

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15215]
There's no sprite for the breaching slug magazine, and if you unload the actual slugs from the invisible magazines, it just pops out actual meteors that you can throw at people or drop on the ground or whatever, and whoever bumps into them will get sent flying. I assume they're supposed to be filled with meteorshot instead

**Comment by Shapsy** [comment]
oh yeah @mmmiracles

**Comment by MMMiracles** [comment]
I probably mistyped the icon name for the magazine but how is actual meteors coming out of the magazine. It's literally a child of regular meteorshot like what the actual fuck.

**Comment by RemieRichards** [comment]
@Shapsy vv and get me the type of the meteor please, I think it's just a projectile that looks like a meteor (Remember we used to be able to catch bullets midflight, so you can pick them up)

**Comment by KorPhaeron** [comment]
The casings probably have the icon set as a meteor instead of the bullet for whatever reason

**Comment by Shapsy** [comment]
the type is /obj/item/projectile/bullet/meteorshot/weak and it's the actual projectile, you can walk into it and it'll hit you and delete itself as if it was fired, and you can't load it into shotguns

**Comment by RemieRichards** [comment]
so it's not "actual meteors", it's the bullet, as I thought.

**Comment by Shapsy** [comment]
Er right sorry, I meant actual as in not the shell containing it, my bad

**Comment by LanCartwright** [comment]
https://github.com/tgstation/-tg-station/pull/13863
For sprites I messily hacked together.

**Comment by phil235** [comment]
Fixed by  #15647
