### ISSUE TITLE
Shadowlings are immune to light while moving around in a cardboard box

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15222]
How to reproduce: Be sling, get box, close box, Solid Snake around the main fully lit hallways, fail to die

Why this is bad: Because people were torn when I asked whether this was an intended feature or not so it can't hurt to open an issue to get more opinions.

**Comment by Niknakflak** [comment]
Feature

**Comment by PKPenguin321** [comment]
balanced imo

**Comment by Cebasiz** [comment]
it's probably pretty dark inside the box

**Comment by TheNightingale** [comment]
Keep it, but only if your vision is restricted when inside a box.

**Comment by WJohn** [comment]
That'll be a thing with phil's upcoming PR, so all bases are covered here already.

**Comment by PKPenguin321** [comment]
shouldnt we leave it open until phil's PR is merged?
