### ISSUE TITLE
Cargo shuttle does not retrieve crates when returning to centcom.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#15228]
Crates do not get collected upon return to centcom, so cargo cannot retrieve the points, and the crate piles just build up.

**Comment by optimumtact** [comment]
It seems to be empty crates from my random testing - crates with a stamped manifest, or other gear in them got collected.

Things not in crates were also not collected.

**Comment by neersighted** [comment]
The bug is only with empty crates. In addition, cargo is paid their points but the crates are not deleted. Easy fix however.
