### ISSUE TITLE
Silicons seem to be immune to melee damage from humans

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15227]
Just saw this on sybil, a borg was smashing an AI with a fire extinguisher, and in turn got smashed with a stunbaton by some human, and neither took any damage from it. I tested this in the thunderdome, and melee'ing the borg/AI core with a fire axe/welding tool on harm didn't do anything, so it happens with both brute and burn damage. Simple mobs were still able to deal melee damage to them, as were ranged weapons.

Attack logs of the borg:
[03:37:37] Has been attacked by Phoebe Lotsu(shaps) with energy axe(INTENT: HARM) (DAMTYPE: BRUTE) (NEWHP: 100)(129,78,2) = null 
[03:37:38] Has been attacked by Phoebe Lotsu(shaps) with energy axe(INTENT: HARM) (DAMTYPE: BRUTE) (NEWHP: 100)(129,78,2) = null 
[03:37:43] Has been attacked by Phoebe Lotsu(shaps) with energy axe(INTENT: HARM) (DAMTYPE: BRUTE) (NEWHP: 100)(129,78,2) = null

**Comment by PKPenguin321** [comment]
test it again in a different round. a lot of weird stuff has been happening to me lately including taking damage and it not having any actual effect on me until about a minute later, and i think something is just fucky with the game in general lately.

**Comment by Shapsy** [comment]
Just did it again the next round, this has happened on all 4 silicons its been tested on

**Comment by phil235** [comment]
This must be something very recent, because I can't reproduce it on my master that I updated just a couple days ago.

**Comment by tkdrg** [comment]
@ChangelingRain
