### ISSUE TITLE
Corpses never seem to run out of blood

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#15230]
Janitor already cleans very slowly and even a janitor borg finds it difficult to keep up with the trails

They'd work better as a relatively scarce, scary signifier, than paint we take for granted

**Comment by PKPenguin321** [comment]
non issue its been this way forever

**Comment by freerealestate** [comment]
Huh?

**Comment by TheRealGLH** [comment]
I like this, because it allows me to fuck with any janitors that sarcastically point towards wet floor signs after slipping.

**Comment by Dorsisdwarf** [comment]
This has been brought up before, but it's unresolvable. After all, how would you track blood remaining except with a mob's blood variable, right? and of course, that increments down... and suddenly you've got uncounterable no-defib kills on any bleeding person using nothing but shoves/stunprods/ water slips, and even if you survive you're crippled and will probbably pass out.

**Comment by Shadowlight213** [comment]
@dorsisdwarf that's not really an issue though. If you want to have a no defibs kill, just hit the dead body a bunch to get past the damage limit?
Just use a cloner or something.

**Comment by Dorsisdwarf** [comment]
But the point being you dont even have to kill them with a weapon. Just locate a bleeder, shove/slip, and drag around really fast and watch as all their blood flies out

**Comment by Shadowlight213** [comment]
@Dorsisdwarf the obvious solution is make a slaughter demon spawn if there's enough blood on station.

**Comment by Dorsisdwarf** [comment]
No stations should have more blood.

My ultimate mission is to make ss13 like VCD

**Comment by Jalleo** [comment]
@KorPhaeron please state a design lead position on this a limit on blood pouring out or no limit and prevent clowns from preventing defibs from working on lots of people after a explosion.
