### ISSUE TITLE
Can't re-admin yourself

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#15241]
If you de-admin yourself then someone has to reload admins, the button to do it yourself doesn't have any effect.

**Comment by neersighted** [comment]
Most likely related to 510 and `splittext`.

**Comment by neersighted** [comment]
Someone mind trying on 509? If it doesn't happen on 509 its probably a 510 bug as `splittext` was changed to work like our old text2list.

**Comment by Shadowlight213** [comment]
Was fixed.
