### ISSUE TITLE
pAI Controlled Mulebots are kinda unbalanced.

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#15259]
So, two main problems with the Mulebots personally.

1: They stun longer then a securitron when they knock someone over by running into someone. Better then murder I suppose, but pretty sure they can't control Securitrons because that would be OP.
2. They have 150 Health, and assuming I read the code correctly, cut Brute damage in HALF, with Burn doing 30% less damage.

So, this means that a hacked Mulebot with a pAI in it can be pretty easily used as makeshift securitron you can ride on, with the only disadvantage of the top of my head being that you might shoot them on accident since you can't shoot over it, which may not even be a problem if you ride it.
Or the fact you probobly have to hack it first I suppose.

**Comment by PKPenguin321** [comment]
feedback forum tho?

**Comment by WJohn** [comment]
Put in feedback, please.
