### ISSUE TITLE
Suit Storage Units on the shuttle on metastation don't work

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15258]
They claim to be depowered when they're not

**Comment by WJohn** [comment]
Wait, SSUs need power?

Also yeah it makes sense that they wouldn't work. I don't know exactly how shuttle areas work but I don't think they're powered? Maybe they are, I dunno.

**Comment by tkdrg** [comment]
They need power now, due to a recent change.

**Comment by MrStonedOne** [comment]
they aren't checking their power correctly then.

Shuttle areas are always powered.

**Comment by PKPenguin321** [comment]
To be more in-detail, I was able to remove everything from an SSU, but when I screwdrivered it and tried to open the menu to hack it, it claimed to be depowered. Either the shuttle SSUs are broken, or hacking SSUs is broken.

**Comment by Metacide** [comment]
Just checked this and can't find anything wrong, should be fine to close this.

**Comment by PKPenguin321** [comment]
I'll take your word for it
