### ISSUE TITLE
Cook has no job icon on the sechud.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#15251]
To reproduce:
- wear a pair oh sechud sunglasses (or get sechud by any other means)
- look at a cook (not a "chef") that is wearing his ID.
- nothing appears above his head.

That's because the hud thing has icon_state = "hudcook" when the sprite for it is named "hudchef".

**Comment by bgobandit** [comment]
does anything use hudchef or should it just be renamed

**Comment by KorPhaeron** [comment]
@bgobandit 

The chef does

**Comment by bgobandit** [comment]
reeee fine I'll just make a new sprite
