### ISSUE TITLE
Wizard ei nath bugs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15263]
It makes you have no body. The brain that you become has no ckey or something. Meaning you're out of the round even if the brain is borged

**Comment by Incoming5643** [comment]
nothing about ei nath has changed recently. The problem must exist in transfer_identity() or brainmobs

**Comment by phil235** [comment]
Caused by https://github.com/tgstation/-tg-station/commit/db7177ae66bae42140095e9715fed5d8f7b3a4d2#diff-efddbd8123f78adfcf6b25e25faea982R64

brain/transfer_identity() doesn't transfer the mind if the mind's current mob isn't dead. which is the case here.

**Comment by kevinz000** [comment]
kek, happend again today. Kek.
