### ISSUE TITLE
Possible stamina damage bug

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15260]
OOC: Kevinz000: WHY DOES STAMINA DAMAGE GO OVER 100 NOW?!
OOC: Kevinz000: THE SECBORG GAVE ME 200 FUCKING STAMLOSS

**Comment by PKPenguin321** [comment]
unless this is intended,
F E E D B A C K
F O R U M

**Comment by WJohn** [comment]
Pretty damn sure this is a bug.

**Comment by phil235** [comment]
The adjustStaminaloss() proc says the max for stam damage is 200 and that proc hasn't been changed in years.

**Comment by phil235** [comment]
Ok, it's actually my fault, I removed a "setStaminaLoss(health - 2)" that was called when your stamina damage weakens you.
