### ISSUE TITLE
Feature Request: Debug verb to locate an object by name or path

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15264]
A lot of the times I've had to try and find an object in the world that I have no idea where it is. A verb to list all the objects in world that fit that path or name would be awesome as it would really help investigations needing touch logs.

**Comment by tkdrg** [comment]
SQDL2 can already do that
`SELECT /my/path`
`SELECT /my/path WHERE name == "blah"`
Closing this as redundant
