### ISSUE TITLE
Teleporter accident can KO you permanently

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#15268]
rev 978b0fafaf89b070f37f8722803c7309ecaa0735 

reproduce:
- use teleporter until you turn into a fly
- be weakened/stunned/KO for all eternity "You feel weak." xInfinity

**Comment by Supermichael777** [comment]
smells like super-matter. its annoying bullshit half a station stun gives that message

**Comment by xxalpha** [comment]
Probably intended.

**Comment by phil235** [comment]
my bad. I removed some code and now radiation doesn't decrease naturally if above 100. Will fix asap.
