### ISSUE TITLE
Stamina damage goes over 100

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15261]
I was nukeop with shielded hardsuit and I was down for 2 minutes in what seems to be Crit (health doll says so!) after Igot hit with disabler a bit more then 10 times
Its kinda unbalanced if YOU CAN GIVE PEOPLE ABOVE 100 STAMINA DAMAGE as they'll be stunned for a very, very, very long time

**Comment by PKPenguin321** [comment]
F e e d b a c k
F o r u m
