### ISSUE TITLE
Plant bags unable to pick up carrots

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#15279]
Well...the title basically says the entire issue.

**Comment by bgobandit** [comment]
is this related to shivs

**Comment by Firecage** [comment]
Most likely, but can't be sure.

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/commit/1b4b672af938c2f3991cffed359c1a72c3e8e1e6#diff-3bd676c304e1bd87f9b3fba920f7ab48R895

carrot/attackby() doesn't call ..()

**Comment by tkdrg** [comment]
@PKPenguin321
