### ISSUE TITLE
Can't connect oxygen tank to mask

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15275]
This has happened to me and several other people. No clue what causes it, or how to reproduce.

Basically though no matter what mask you have on your face, the button to hook up the oxytank in nanoui will be greyed out.

Apparently the hud button still works to connect internals, so it is a UI problem

@neersighted

**Comment by Actionb** [comment]
On that note, it appears the HUD icon doesn't update properly. I've started suffocating in space while the icon was green. Toggling it off and on fixes it though. Still very confusing.

**Comment by phil235** [comment]
@Actionb I'll handle the hud bug

**Comment by neersighted** [comment]
Working on the tgui bug.

**Comment by tkdrg** [comment]
the hud bug is fixed now
