### ISSUE TITLE
Weird Overlays in Cryo

### ISSUE THREAD

**Issue by Hatfish** [tgstation/-tg-station#15282]
![sybil mime city oscar 2016-02-07 132114](https://cloud.githubusercontent.com/assets/8237862/12874250/25298290-cd9e-11e5-9ab7-869c3bcf7e03.png)
This was also overlayed over the blind/sleeping darkness.  Don't have any idea what could be causing it, apparently nobody else but me could see it.

**Comment by phil235** [comment]
Err, actually it's not fixed yet, this one is a different bug from the others. Working on a fix right now.
