### ISSUE TITLE
blob core/node "natural growth" doesn't harm humans, letting them on top instead

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#15297]
you can end up with a human on top of a strong blob, unable to be harmed by overmind attacks
@ChangelingRain

**Comment by ChangelingRain** [comment]
I'm pretty sure this only happens if they're lying down, like if they get knocked out, and get back up due to a healing virus or something, as it definitely doesn't happen to humans that get expanded at normally.

**Comment by tkdrg** [comment]
He didn't expand on him manually. the blob grew naturally due to being rightt next to the strong blob, trapping him on top and now immune to overmind attacks

**Comment by ChangelingRain** [comment]
They use the same proc to do it.

**Comment by tkdrg** [comment]
Well then I dunno but he was just some random greyshirt, no fancy viruses or anything, who happened to be right next to the blob. Maybe he rested or something?

**Comment by ChangelingRain** [comment]
If he rested I could sort of fix it, by not expanding onto awake mobs, but if he slept or got knocked into crit and got out of crit with a healing virus there's nothing you can really do.

**Comment by tkdrg** [comment]
you could make it so people take damage for standing on top of a blob or something

**Comment by ChangelingRain** [comment]
That's already done, though I might up the damage if they're actually on a blob.

**Comment by ChangelingRain** [comment]
I'm pretty sure this doesn't even happen besides healing viruses/other healing chems and oh well those aren't a blob issue

**Comment by tkdrg** [comment]
Why does it have to be a blob issue in order to stay open? Blobs aren't the only thing in the game. And it's still an issue that some duse can just punch the blob scot-free.

**Comment by ChangelingRain** [comment]
ding dong issue squashed

**Comment by ChangelingRain** [comment]
i was super wrong it *is* possible to fix because I just did it wee woo
