### ISSUE TITLE
AI seeing the Z2 (lobby) z-level roundstart

### ISSUE THREAD

**Issue by Anonmare** [tgstation/-tg-station#15291]
This has been happening to me consistently whenever I spawn as AI

![image](https://cloud.githubusercontent.com/assets/12382984/12876105/994befb6-cdf1-11e5-8843-a6b9f2f661c8.png)
Mentioned it to Peoplearestrange but no issue report so I'm making one.

**Comment by neersighted** [comment]
@phil235

**Comment by lzimann** [comment]
Dupe of #15095
