### ISSUE TITLE
blob help icon is broken

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#15296]
it doesn't work according to an ahelp
@ChangelingRain

**Comment by ChangelingRain** [comment]
Was the button broken? 
I know the icon isn't incorrect or missing.

**Comment by PKPenguin321** [comment]
The blob help action button in the top left doesn't work *before you pop,* as in you can click it but no text appears and effectively nothing happens. After you pop it works fine. I noticed this when I rolled blob the other day but forgot to report it.
