### ISSUE TITLE
Lesser Summon Guns + Lich is OVERPOWERED

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15294]
OVERPOWERED COMBINATION AS BAD AS MAGIC MISSILE + DISINTERGRATE!
Either remove either of the spells, or make that particular combination unbuyable because what the fuck man LSG gives you the most stopping power in the game. The guns do more damage then a pulse rifle, their bullets are almost invisible, AND ITS INFINITE. With lich you can kill the entire crew without anyone being able to stop you because anyone able to stop you will be dead. Or, lower the damage of the damned bolt action enchanted rifles.

**Comment by neersighted** [comment]
i ded please nerf

**Comment by TheNightingale** [comment]
Bulletproof armour?

**Comment by Zilenan91** [comment]
There's a pr removing LSG

**Comment by Aloraydrel** [comment]
I ded pls rage

**Comment by KorPhaeron** [comment]
>more damage than a pulse rifle

???

Also I nerfed the shit out of LSG to the point that it is objectively worse than a cheaper spell that has existed for years, but Lich is still gonna be fire/bleed/hunger/cold/poison/oxygen immunity on top of infinite lives.
