### ISSUE TITLE
grabbing a meat spiked person gimps your movement speed

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#15304]
Try to use a grab on someone who is meat spiked and you will be moving at a walking pace forever. Have had to respawn people to fix it.

**Comment by tkdrg** [comment]
they can fix it somehow without respawn, i've seen it before
@KorPhaeron either way

**Comment by phil235** [comment]
It's my fault, although technically I only made an existing bug visible. Will fix.
