### ISSUE TITLE
Disposal pipes can blind blind you forever

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15305]
Reply PM from-Snackbar/(Taylor Garrison): Well, I was going down the pipes and could not see when I gout out  

@phil235

**Comment by phil235** [comment]
oh boy, I thought I had fixed that bug during my branch testing.

**Comment by phil235** [comment]
Can't reproduce, was he inside a closet or something? Was he ejected through the normal outlet or through an open pipe, or was the pipe he was in broken? What kind of mob was he?

**Comment by KorPhaeron** [comment]
He was a miner on mining iirc (which probably means he had mesons, if that matters)

**Comment by phil235** [comment]
Found the problem.
