### ISSUE TITLE
Cryo vision is weird

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15308]
You can't see if it's closed and turned on if you're inside of it which is very strange.

**Comment by neersighted** [comment]
Due to @phil235's vision refactor

**Comment by WJohn** [comment]
This is the case with any form of unconsciousness and blinding, isn't it? Unless phil's vision changes made you truly blind when unconscious.

**Comment by phil235** [comment]
Because you can ventcrawl into cryo... ugh. Will fix.
