### ISSUE TITLE
Stamina damage is reduced at a flat rate rather than percentile

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15316]
Torsion is probably full of shit but I seriously doubt it's intended that stamina works in such a snowflakey way.

**Comment by phil235** [comment]
The stamina damage going too high was a bug, fixed by #15281

**Comment by Zilenan91** [comment]
No I mean if armor has like 30 energy resist, rather than taking 30% less stamina damage per beam you take 30 less stamina damage per beam.

**Comment by Zilenan91** [comment]
Not sure if this was fixed, want to know if I can close it.

**Comment by Steelpoint** [comment]
This has been a problem ever since Stamina was introduced.

Blame Paprika.

**Comment by CPTANT** [comment]
Its not reducing at a flat rate, its applying the block twice.

Shooting a riot suit which has 10 energy resist with a 36 stamina disabler does 29.16 stamina damage.

Shooting a reflective vest with 50 energy resist does 9 stamina damage.

I can't pinpoint the problem though, energy blocking seems to be handled the same as the other damage types.
