### ISSUE TITLE
Masks layer over the chaplain hood

### ISSUE THREAD

**Issue by ATDoop** [tgstation/-tg-station#15315]
Seen here with a gas mask, it's more obvious with stuff like the plague doctor mask and ski hood.

![jbdaxr8](https://cloud.githubusercontent.com/assets/1959416/12880628/93b2e554-ce10-11e5-8993-ba9a1a99c34f.png)

**Comment by WJohn** [comment]
Dupe of #6275

**Comment by phil235** [comment]
Actually it's not a dupe of that bug. It's the same issue as  #11924. It was fixed for wintercoats and carp/ian costumes but not chaplain hoodie.
