### ISSUE TITLE
Blowing a borg kills their MMI

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15312]
Was immediately dead when my borg got blown. Had a red damage overlay, tried speaking and it went to deadchat. Trying to move ghosted me as with any other corpse.

**Comment by neersighted** [comment]
@phil235 life refactor?

**Comment by xxalpha** [comment]
Were you hacked?

**Comment by KorPhaeron** [comment]
Hacked borgs being blown deletes the MMI

**Comment by phil235** [comment]
@KorPhaeron Did your mmi had crosses on its eyes (dead icon) ?
My guesss is that the explosion killed your brain. maybe.

**Comment by phil235** [comment]
Can't reproduce. Blowing the borg with the RD console drops a healthy mmi brain. Even if I manually kill the brain mob inside the borg before blowing I still do not get any damage overlay.

**Comment by KorPhaeron** [comment]
roundstart cyborg. Dont remember seeing the Xs on my MMI.

i did get a "you hear something flatline message" randomly during the round, and got this the previoud round as well.

Maybe because I had been running around in space?

**Comment by phil235** [comment]
Getting the red overlay even when dead will be fixed soon by #15327
