### ISSUE TITLE
Reagant reactions happen too quickly

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15322]
HELP: Lexorion/(Logan Skyler) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): the "Speed reagent reaction code" messes up entirely,instead of making me sleep it causes me to pass out for a very short amount of time,before I get up again  

Reply PM from-Lexorion/(Logan Skyler): I injected myself with 40u of chloral hydrate and it should make you sleep,right? Now , it only knocks me down for a  short bit,before I get up again,over and over. 

@neersighted or @phil235 maybe

**Comment by phil235** [comment]
*sighs*

**Comment by neersighted** [comment]
Yeah this isn't me, I just improved reagent `reaction()` performance. This is just a case of touching vars you should not instead of using the proper procs.
