### ISSUE TITLE
You can smash a disposal unit while you're inside of it

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#15321]
If you're a mob type that's able to smash things like disposal units and you can drag yourself inside of one, you're able to smash it while inside of it.

**Comment by KorPhaeron** [comment]
Doesn't that make sense though? You're clearly close enough to smash it if you are inside of it

**Comment by TheRealGLH** [comment]
Maybe I've interpreted the way the machines look, but I always assumed they were just flat surfaces attached to the floor. 
I also forgot to mention (because I wanted to make a separate issue for it) that if you're inside a unit while it's being smashed, you lose your vision.

**Comment by phil235** [comment]
The vision loss is the same bug as #15305
