### ISSUE TITLE
Roundstart fails to start-up

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#1533]
LOGS:

Error setting up secret. Reverting to pre-game lobby.
Welcome to the pre-game lobby!
Please, setup your character and select ready. Game will start in 120 seconds

other stuff: I haven't seen a rev round in like forever, it might be the reason. If it isn't, then I encourage anyone to add a better feedback message for asay.

**Comment by Cheridan** [comment]
Marking this as fixed.
