### ISSUE TITLE
Alien Larva do not take damage

### ISSUE THREAD

**Issue by Ultimate-Chimera** [tgstation/-tg-station#15334]
I witnessed and experienced myself being an Alien Larva and I took zero damage when being attacked.

**Comment by phil235** [comment]
Can't reproduce. Give us more info. What kind of attack? Did the larva go into crit?

**Comment by neersighted** [comment]
@ChangelingRain

**Comment by Ultimate-Chimera** [comment]
The one I saw was taking damage from a circular saw about 50 times (exaggeration) and then me, I was being hit by a hatchet I think when I became one shortly after, took no damage.

**Comment by bgobandit** [comment]
is this the simple mob issue again

**Comment by ChangelingRain** [comment]
not my fault if this is happening on a version after the revert #15247

**Comment by KazeEspada** [comment]
Larva are carbons.

**Comment by WJohn** [comment]
Yeah I can't reproduce this either. Took damage fine from melee brute, lasers, fire stacks, heat etc.

**Comment by Ultimate-Chimera** [comment]
Strange, maybe something else was causing it. I did see that larva biting the person chasing it around surgery so maybe biting heals larva rapidly?

**Comment by Dorsisdwarf** [comment]
Biting living animals heals larva and causes them to evolve more rapidly, IIRC

**Comment by Ultimate-Chimera** [comment]
Odd.

**Comment by PKPenguin321** [comment]
???

**Comment by Ultimate-Chimera** [comment]
It seems it was a one-time thing. I've never seen it happen anymore.
