### ISSUE TITLE
Suiciding with oxygen tanks destroys implants

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15341]
I tested it with loyalty and tracking implants, both were removed when gibbing yourself with oxygen tanks, but it didn't happen with the standard necksnap suicide or typing suicide with a loaded gun.

**Comment by WJohn** [comment]
I wouldn't call this an issue, I mean you've basically obliterated your body, what are the chances the implants survive it?

**Comment by PKPenguin321** [comment]
you see, the pressure from the oxygen tank is so intense that it blows the implants straight out through your skin.

**Comment by Shapsy** [comment]
A greyshirt blew himself up with an oxytank after getting loyalty implanted during rev and it threw us off since our antag HUD wasn't showing him as being implanted. I just assumed it was a bug since none of the other suicides remove implants
