### ISSUE TITLE
There are 180,000 things getting qdeleted at round start

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#15348]
Still haven't figured out what they were, as the list was too big to vv.

**Comment by MrStonedOne** [comment]
/dmm_suite/preloader - 245648 times

**Comment by AnturK** [comment]
I'll change this to reuse single instance since this is global and unique anyway.

**Comment by lzimann** [comment]
How does this even happen?

**Comment by KazeEspada** [comment]
Minimaps?

**Comment by Menshin** [comment]
Added in  #12153 (not like i mentioned qdel'ing was useless for the preloader there).

Basically, the _preloader_ global var is set for each atom instanciation based on the read attributes list.
If the list is empty, the preloader is deleted and the atom is created with default values.

This was changed to GC the preloader if the attribute list is empty (hinting to DELNOW or whatever).

**Comment by RemieRichards** [comment]
@KazeEspada no, it's the map preloaders, a datum that instantiates atoms from a map file in the same way byond would, it's how the map loader works.
The map loader reads the file and passes an atom (built from the typepath it last parsed) and sets each of the vars in that atom to what they were edited to be in the map file (such as door names)
Except this datum doesn't need to be destroyed, and could be worked to only require one instance which is reused, but atm it's destroyed and recreated a LOT of times.

**Comment by duncathan** [comment]
@Menshin the issue is the thousands of deletions. My PR is responsible for making that not happen silently, so fuck off.

**Comment by Menshin** [comment]
>  the issue is the thousands of deletions.

That's obviously the main issue here (something from the legacy code i should have changed when i was refactoring the maploader).
Still, no need for unnecessary overhead, especially for a dedicated functionality only called once a round.

**Comment by duncathan** [comment]
If we make it only delete once, the overhead of qdel is negligible v
