### ISSUE TITLE
Resize is broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15346]
Changing the resize var doesn't do anything.

**Comment by phil235** [comment]
Because I removed https://github.com/tgstation/-tg-station/blob/7caab87021dab5e7b83468267314b5fb52278238/code/modules/mob/living/life.dm#L55

Life() was calling update_canmove() which called update_transform() which handle resizing.

Easiest way to fix is to add to living/life() this:
```
if(resize != RESIZE_DEFAULT_SIZE)
	update_transform()
```
