### ISSUE TITLE
Canister gas transfer over to an unrelated air pump.

### ISSUE THREAD

**Issue by yackemflam** [tgstation/-tg-station#15356]
So i'll explain what i did to achieve this weird bug.

Box stations testing lab.

If you connect cooler DIRECTLY to a connector port, and wrench an oxygen canister to it. And use the air pump in toxins to empty a Over time it'll transfer over to the toxins portable air pump. Pressure, temperature, and all.
It's extremely strange and i can't explain why this would happen.
Also, I don't know if this is related but I also wrench a plasma canister directly to the testing lab's heater.

**Comment by Jalleo** [comment]
Need a image your explanation is somewhat hazy.
@duncathan.

**Comment by duncathan** [comment]
@neersighted related to the pump thing. Not resetting AIR1 and AIR2?

**Comment by neersighted** [comment]
I know this is related to the embedded pumps, but I'm not sure WHY it happens. I need a more coherent description and screenshots please.
