### ISSUE TITLE
Open crates don't block movement

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15352]
While the crate is closed, it blocks the path normally(you bump into them), but if they are open you just go throught them

**Comment by AnturK** [comment]
@neersighted

**Comment by Jalleo** [comment]
This is fine imo. It stops crate forts and make them act more like closets.

**Comment by neersighted** [comment]
Side effect of merging crate code with closet code it seems. I'm fine with leaving it... Does anyone really want this fixed?

**Comment by ChangelingRain** [comment]
This is not the previous functionality and neersighted should fix it.

**Comment by tkdrg** [comment]
This was intended. He said he would do it and I said we should give it a try, with the caveat about plastic flaps.

**Comment by newfren** [comment]
Crates stacking on top of each other and not being able to be pushed while open makes my job as a cargo tech a lot harder.

**Comment by neersighted** [comment]
Its one line to force density even when the crate is open, however I'm still interested in more player feedback on this.
