### ISSUE TITLE
Holodeck safeties cannot be turned off

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15376]
Something fucky, wasn't exactly clear. Ask shaps if you need more info.

**Comment by Shapsy** [comment]
@lzimann was a rogue AI trying to disable the safeties on the holodeck as a rogue AI so he could flood plasma, but said that he wasn't able to for some reason. I switched on admin AI interact, and everytime I clicked on the disable safeties button, the button just disappeared and nothing happened (reopening the window brought it back, but nothing changed with the safeties)
