### ISSUE TITLE
Disposal chutes sometimes don't shoot out its contents

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15375]
Happened during a round on Metastation on the disposal chute in the bar. There was a plasma fire in the room, and all power was on, but the disposal chute wasn't sending anything out. Only sent after I actually died.

Could be that it had previously send something and hadn't refreshed but I don't remember that happening to anything.

**Comment by phil235** [comment]
Yeah, most likely the disposal unit was still recharging.

**Comment by Zilenan91** [comment]
I'm gonna keep this open for a bit just in case anyone else experiences this
