### ISSUE TITLE
AI couldn't move camera after shunted

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15383]
Tried cancel camera view, didn't work after that either. Camera was just locked on his new APC.

**Comment by PKPenguin321** [comment]
I'm pretty sure it's always been this way. You lose camera view (and most of your functions) once you shunt. Not a bug

**Comment by KorPhaeron** [comment]
Seems like an utterly worthless power if it is basically suicide then.

**Comment by PKPenguin321** [comment]
It's a relic of malf, where you'd hold people off of your core as long as you could then go on the defensive by cowering in an APC. I'm not saying it's any good, just that it's intentional.

**Comment by KazeEspada** [comment]
Shunting used to not disable the doomsday device, so it bought you some precious time before BOOM went the station.
