### ISSUE TITLE
Strange xray/welding tank interaction

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15397]
HELP: Improvedname/(Reiyo Fluke) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): it seems shooting a welding tank brings the explosion to the tile your standing one 

Needs reproducing, obviously

**Comment by PKPenguin321** [comment]
closed why?

**Comment by KorPhaeron** [comment]
It wasn't real
