### ISSUE TITLE
Wizard HUDs not working properly/mindswap not transferring HUD icons

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15409]
Both of us mindwapped, then ended up meeting again and neither of us could see the others HUD icon  (and I ended up killing him)

Related: I mindswapped into a guy wearing secHUD glasses, and didn't see sechud stuff until I took them off and put them on again.

I kept the apprentice icon above my head (from my perspective) throughout though.

**Comment by KorPhaeron** [comment]
@phil235

**Comment by WJohn** [comment]
Dupe of #9601, it's been around for a while.
