### ISSUE TITLE
Wild Shapeshift is really buggy

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15411]
You can't change back to human form if you were a lizard, leaving you stuck as the mob.

**Comment by Dorsisdwarf** [comment]
>Insert lizard joke here<

**Comment by Incoming5643** [comment]
I don't think being a lizard has anything to do with this bug, but I couldn't tell you what could be.

Was anything else weird going on in that round? Had you done anything odd previous to this? I know wild shapeshift worked in testing.

**Comment by Zilenan91** [comment]
Really early on in the round, I think it was Judicator who was doing a TC trade with me to get the spell but I'm probably wrong.

**Comment by AnturK** [comment]
This was during the time action buttons were broke, did you have the spell in spell tab ?

**Comment by Zilenan91** [comment]
Yep.
