### ISSUE TITLE
MetaStation's Sergeant Araneus has a string faction

### ISSUE THREAD

**Issue by neersighted** [tgstation/-tg-station#15430]
`faction` is a list, this is a bad mapedit.

The following runtime has occured 2 time(s).
runtime error: type mismatch: "spiders" |= "\[mob_102]"
proc name: New (/mob/living/New)
  source file: living.dm,27
  usr: (src)
  src: Sergeant Araneus (/mob/living/simple_animal/hostile/retaliate/bat)

**Comment by duncathan** [comment]
@Metacide
