### ISSUE TITLE
Any spider can be clicked on by ghosts to be controlled

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15446]
Previously player controlled spiders created spiders that could be controlled by players (and it was pop up spam)

Now any spider can be clicked on at any time regardless of origin, leading to frequent spider apocalypses.

**Comment by Zilenan91** [comment]
intended I think

**Comment by PKPenguin321** [comment]
definitely not lol

**Comment by Zilenan91** [comment]
shh

**Comment by Buggy123** [comment]
shhhhhh

**Comment by Lumipharon** [comment]
Giant spiders are literally the spawn of satan.

**Comment by Zilenan91** [comment]
shhh i'll keep enjoying my nurse spiders on snowdin every round
