### ISSUE TITLE
announcements don't make sound anymore

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15443]

**Comment by PKPenguin321** [comment]
something to do with the announcement mute preference?

**Comment by ChangelingRain** [comment]
@Shadowlight213

**Comment by Shadowlight213** [comment]
Did you try toggling it? For some reason sometimes it starts off

**Comment by KorPhaeron** [comment]
@Shadowlight213 

Rename the pref to "disable announcement sounds" and inverse the check

**Comment by bgobandit** [comment]
is this the cleanbot bug again
