### ISSUE TITLE
vents/scrubbers pipes are sticking out with floor tiles ontop of them

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#15442]
![cuck picture](https://cloud.githubusercontent.com/assets/13092039/12997549/71736e00-d108-11e5-8376-7710249d43dd.png)
wew

**Comment by duncathan** [comment]
Does this happen every time?

**Comment by phil235** [comment]
Happened on my local test server as well, so I'd stay it's every time.

**Comment by Aloraydrel** [comment]
Yea it's every round
