### ISSUE TITLE
Plasma gas regens xeno plasma WAY to slowly.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#15451]
After three solid minutes of standing in a decent amount of plasma, I only got three points of xeno plasma.

**Comment by YakumoChen** [comment]
plasma doesn't regen xeno plasma, weeds do??

**Comment by KazeEspada** [comment]
No, xenos can breath plasma to generate a ton of xeno plasma. However, plasma is a double edged sword since it can ignite, and burning plasma is an instant dead xeno.

**Comment by PKPenguin321** [comment]
i think it depends on the pressure of the plasma
for instance, standing in the atmos tank thing fills a queen's plasma reserves instantly
leaking one canister in science won't fill you very fast at all

**Comment by GunHog** [comment]
They inhale plasma and exhale oxygen, ensuring that even a pure plasma environment will have oxygen. It is as if they are sexually attracted to fire!

**Comment by WJohn** [comment]
Confirmed, it's based on the pressure. Barely inhaling any will net you 0.1 plasma, while inhaling lots will give you 2-3.
