### ISSUE TITLE
Monkeys can pick up wall radios

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15452]
HELP: Scaredofshadows/(monkey (406)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): as monkey I can pick up wall radios 

He was indeed picking up and dropping an intercomm from the inside of an escape pod

**Comment by Zilenan91** [comment]
Huh.

**Comment by Zilenan91** [comment]
Actually can anyone do any more testing to see if they can pick up and drop anything else?

**Comment by PKPenguin321** [comment]
im guessing this is because they can't actually interact with them ("You don't have the dexterity to do this!") and since that fails they do the next best thing and pick it up..?

**Comment by neersighted** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by newfren** [comment]
haha what
