### ISSUE TITLE
Wizard "flaming hands" spews out a plasma fire

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15458]
Not a bug, more of a balance thing, when you have a fireproof guy firing up the station.

**Comment by KorPhaeron** [comment]
>opening an issue for something not even in the game

Bravo

**Comment by kevinz000** [comment]
>realizes that
FUCK.

**Comment by The-Albinobigfoot** [comment]
>Mekhi in charge of not fucking up.

:+1:  :100:
