### ISSUE TITLE
Turrets are very weird and buggy??

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#15467]
So turrets on boxstation seem to work totally fine, but on efficiency station, when I updated all the turrets to the new /ai version, they specifically do not try to stun humans. Lethal mode works perfectly fine, and they will attempt to tase simple animals, but if I stand in their sight while they're on lethal and they're busy shooting at me, and I turn their setting to taser, they will turn off like I'm not a target.

I swear these things are actual magic, I am so god damned sick of turrets and their consistently non-functioning behavior after all these years. SOMEONE REWRITE THEM FOR REAL THIS TIME.

Also, as a mostly unrelated side note, turret controls are seemingly the only machine (or generally THING) in the whole entire game that require you to stand on the same exact tile as them to interact with them. Nothing else does this, you can normally click on them 1 tile away.

**Comment by KorPhaeron** [comment]
This happens on box sometimes as well. The humans had to fight the death hallway, but the actual core just straight out ignored them.

**Comment by Sligneris** [comment]
Turrets not stunning humans also happens on Box Station's AI upload.

**Comment by Jalleo** [comment]
Who touched the turret code last?

**Comment by KorPhaeron** [comment]
@oranges did a rewrite I think

**Comment by KazeEspada** [comment]
@optimumtact

**Comment by optimumtact** [comment]
@WJohn are you overriding the default syndicate faction? because they won't shoot at anything that shares that faction with them.

@KorPhaeron, I'll take a look at that, are you sure that the AI didn't configure the weapons to not shoot at people who are allowed in the AI core areas? There is quite a comprehensive perp_checking code that bases the threat value of a given human on a number of settings (has weapons, is allowed etc).

**Comment by KorPhaeron** [comment]
@optimumtact 

The old behaviour of the AI core turrets was they shot anyone that wasn't a robot while on. Ideally that'd still be the default as well.

Checking for access levels or whatever might be why the captain can just waltz into the AI core and beat it to death.

**Comment by optimumtact** [comment]
But I didn't even write that logic, it's always been there.

maybe it was just broken.

**Comment by optimumtact** [comment]
oh I see what I did

**Comment by optimumtact** [comment]
@WJohn could you try again with the newest codebase and making sure you didn't override the factions?

**Comment by WJohn** [comment]
I didn't touch any of the factions, but I'll test this out on there.
