### ISSUE TITLE
Poly's cracker mechanic is mathematically ridiculous

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15482]
speak_chance is a percentage out of 100. Normally it starts at 3.

3
6
12
24
48
96
192
stupidly bigger and bigger numbers that are pointless because it's a percentage out of 100

exponents go up fast, kids

**Comment by Iamgoofball** [comment]
i dont see a problem here

**Comment by octareenroon91** [comment]
Crackers are expensive.
Are you worried about overflow?
We could put exponential decay on `(100-speak_chance)` instead if you like

**Comment by bgobandit** [comment]
exponential decay would be better, yes

and they're not that expensive, someone managed to cheese the var up to like 1900 last round

**Comment by Buggy123** [comment]
lets just cap it at 100.

**Comment by Incoming5643** [comment]
If you're going to dedicate to making one cracker, you can easily dedicate to make ten crackers.

:point_right: F E A T U R E :point_left:
