### ISSUE TITLE
Clown does not spawn with a backpack.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#15488]
@KazeEspada

**Comment by KazeEspada** [comment]
What was his settings? And was it no backpack or grey one?

**Comment by WJohn** [comment]
No backpack. I think it's that people's settings were not adjusted appropriately, even though this change worked fine with everyone else.

**Comment by KazeEspada** [comment]
Is it reproduceable?

**Comment by KazeEspada** [comment]
@WJohn Close this. I spent 15 minutes, selecting backpacks, spawning as clown, and then restarting my local server and not once did I spawn without a backpack.

Unreproducible, and little information. So unless this comes back again, use your coder rank powers to interrogate the guy as well to see what his settings looked like.

**Comment by lzimann** [comment]
@KazeEspada What I saw it happening, was a clown spawning without his special backpack(with the departmental backpacks selected).

**Comment by KazeEspada** [comment]
Ok. Thats weird.

**Comment by KazeEspada** [comment]
Still unable to determine this bug. Expect it to stay open for a few years. I'm gonna redo some stuff, and fix a minor issue. That might fix it, but no promises.
