### ISSUE TITLE
Unscrolled Sleeping Carp can apparently use ranged weapons

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15493]
Based off of the forums, unintended behavior, Carp aren't supposed to be able to use ranged weapons at all.

**Comment by neersighted** [comment]
The check is based on if you have the martial art... So not sure if this is a bug or not.

**Comment by KazeEspada** [comment]
Not a bug.

**Comment by ChangelingRain** [comment]
This wasn't a bug even when the scroll was added, though the PR appears to no longer be in the PR list or recorded in history, so I can't actually confirm that.
