### ISSUE TITLE
R&D objects are stuck at default reliability

### ISSUE THREAD

**Issue by Deputi** [tgstation/-tg-station#15506]
It seems like doing research isn't raising reliability like it should. For example, pico manipulators should normally be at least at 78 reliability after research is done, but now they're still stuck at their default value of 73 reliability. Researching the previous tier of parts also isn't raising their reliability anymore either.
![broke](https://cloud.githubusercontent.com/assets/4474395/13030742/1564821c-d283-11e5-9609-6fccb3170e18.PNG)

**Comment by WJohn** [comment]
How many PRs have we had which remove reliability?

Why is this still a thing?

**Comment by PKPenguin321** [comment]
doesnt upgrading the destructor thingy make reliability go up

**Comment by TheNightingale** [comment]
Upgrading the destructothingy means you can research less reliable parts; reliability itself goes up through either deconstructing that part (most commonly seen with advanced energy guns - decon a few and they'll work much better) or through just doing research (which only increases it by a few points, but those few points are all that you'll need a lot of the time).

**Comment by GunHog** [comment]
Probably broken by https://github.com/tgstation/-tg-station/pull/15394. @AnturK
