### ISSUE TITLE
Wizards going blind after jaunting.

### ISSUE THREAD

**Issue by Ronnoc1** [tgstation/-tg-station#15518]
I spawned as a wizard, objective hijack the shuttle, and used my points on 3 apprentices (2 destruction, 1 bluespace manipulation), ethereal jaunt and magic missile. I used my teleport scroll to go to the prisoner education chamber and then jaunted and went in the armory. When I reappeared in the armory suddenly my screen went completely black, I did not even get to see my own character as if I was blind. I regained vision when I jaunted again, but as soon as I re materialized, I would go back to the black screen. I soon found out that if I re materialized on top of a wall I was able to see, but only on top of a wall, and nothing else. As you can probably infer, I got rekt by security while running around with no sensory perceptions and died. At the end of the round my apprentice of bluespace manipulation reported the same thing happening to him, and he said that reconnecting to the server fixed the problem, not permanently, but he would have to reconnect every time he jaunted.

**Comment by Saegrimr** [comment]
Can confirm, gave myself jaunt and it causes a black screen 100% of the time, but returns to normal while you are mid-jaunt. Goes black again when finished.

**Comment by Buggy123** [comment]
Again, why is EVERYTHING causing permanent blindness?

**Comment by YakumoChen** [comment]
I think the brain PR did it.

**Comment by tkdrg** [comment]
@phil235

**Comment by phil235** [comment]
SOrrrrryyyyy
