### ISSUE TITLE
restoring a dead AI perma-blinds it on restore

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#15517]
@phil235

I shouldn't even be able to be blinded as AI?

Blind in the restore console, blind on a card, blind in my core. Can't see a damn thing.

**Comment by Buggy123** [comment]
What is with this damn blind shit, why is everything going blind permanently?

**Comment by PKPenguin321** [comment]
the vision code rewrite
@phil235

**Comment by GunHog** [comment]
It generally works like this:

Functional, low-bug count, but messy code -> Refactor >> Clean, but buggy code -> Extensive bug fixes >> Functional, but partially messy code.

**Comment by optimumtact** [comment]
we'll get there, these refactors are important to allow the codebase to grow larger sanely, the tradeoff is they tend to cause bugs for a while.
