### ISSUE TITLE
>spiders on snowdin away map can pass through gateway

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#15528]
While admins can ban/badmin to fix it on a per round basis, it really needs a code solution fast to stop rounds from degenerating into australia each time.

**Comment by MMMiracles** [comment]
If spiders are getting that far that either means players are getting control of the spiders and trekking them cross the map or people are kiting them there.

Spiders literally can't find their way to the gateway without player intervention.

**Comment by KazeEspada** [comment]
Players are controlling them.

**Comment by xxalpha** [comment]
player controlled spiders was a mistake

**Comment by PKPenguin321** [comment]
consequence of https://github.com/tgstation/-tg-station/issues/15446

**Comment by Zilenan91** [comment]
Yeah they just take control the purple eyed spiders in the Op level, break out, kill all the mobs, respawning when necessary, then carting a bunch of dead bears to a room, spawning as a nurse spider, laying a billion eggs, and then going through the gateway.

**Comment by Shad0vvs** [comment]
Relevant: Mob wizards from the wizard academy away mission can also pass though the gateway, unlike the player ones who have exile implants.

**Comment by tkdrg** [comment]
player control is getting fixed so this is getting mitigated

**Comment by YakumoChen** [comment]
F E A T U R E
This is hilarious and fun to do, please keep. Did it three times in a row with excellent results, me and my spider gang defeated an ERT followed by a deathsquad, leading to hilarity.

**Comment by optimumtact** [comment]
Fixed/mitigated
