### ISSUE TITLE
Toxins and TTV's are beyond fucked

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#15530]
I made plenty of comments when MSO introduced this shitty change. Was told it wouldn't change much.

Now I can barely get Toxins to function like it used to. I can put a full tank of 50,000+ degree hot plasma in one tank and -200 degree pure oxygen in another tank, open the TTV, and nothing happens. Instead I literally get two tanks of pure oxygen at like 700 degrees and the oxygen/co2 literally disappears into then air.

Alternatively I can put in a tank that's superhot and still burning and opening the TTV will just destroy the plasma tank (but the sprite wont update so it looks like its intact). 

All this for what? Fire that still burns out in 10 seconds?

**Comment by duncathan** [comment]
Your burn mix is bad
Don't try to pull your "ancient knowledge of the game" either; it has been proven that the standard burn mix people use is shit

In other words
Git gud

**Comment by Robustin** [comment]
I've used a dozen different mixes, its still bugged dipshit
