### ISSUE TITLE
Someone broke spawn atom

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#15537]
runtime error: Cannot create objects of type null.
proc name: Spawn (/datum/admins/proc/spawn_atom)

Normally if you hit enter straight away, or input an invalid path it'll show you a window of the closest guesses, or close.

Now it runtimes.

**Comment by phil235** [comment]
@AnturK needs an `if(!chosen) return` after https://github.com/tgstation/-tg-station/commit/e93fbcd2a0a404157d7145fc279cd5be00b5a518#diff-08955c4954d03922b61a042ae2e757caR622
