### ISSUE TITLE
Strange gas behavior when opening a TTV

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#15531]
If I put one full tank of plasma at +50,000 degrees C and one full tank of oxygen at -200 degrees C into a transfer valve, the result is two tanks of oxygen at +700 degrees C. The plasma seems to be disappearing. 

Additionally, I can put in a tank that's superhot and still burning and opening the TTV will just destroy the plasma tank (but the sprite wont update so it looks like its intact).

**Comment by ChangelingRain** [comment]
It works fine if you have the right mix. Ask lzimann, they've got one. I dunno if they'll tell you, though.

**Comment by Robustin** [comment]
Jesus H. Christ do you people just read the title?

A MIX SHOULD NEVER RESULT IN HALF OF THE CATALYSTS COMPLETELY DISAPPEARING.

**Comment by PKPenguin321** [comment]
robustin, when making an issue report, be concise. more people will read it that way

**Comment by phil235** [comment]
And some steps to reproduce the issue helps a lot.

**Comment by duncathan** [comment]
>don't close an issue you know nothing about
>he says to the maintainer who knows the most about atmos aside from aran

lmao

Gimme a couple minutes to give you a better answer

**Comment by duncathan** [comment]
BTW I wrote you a better report you're welcome
