### ISSUE TITLE
Borgs who get revived/rebooted in RD have strange vision problems

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15548]
HELP: Gouty/(Dangerbot 3000) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): by the way, I can see through walls at the moment, and I have no Idea why

Reply PM from-Gouty/(Dangerbot 3000): I died, and then was rebooted, I have damaged wires

**Comment by KorPhaeron** [comment]
@phil235

**Comment by Saegrimr** [comment]
Happens to lings too after they regenerate.
