### ISSUE TITLE
You can get telescience round start again

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15555]
Apparently deconstructing the abandoned teleporter gives you bluespace crystals, which is enough to finish the thing.

Not strictly a bug, but I thought "using a calculator to place a bomb on any tile of the map/steal everything" was removed for a reason.

**Comment by KazeEspada** [comment]
Abandoned teleporter?

**Comment by TheNightingale** [comment]
If you deconstruct the abandoned teleporter, you can't get back easily.

**Comment by KorPhaeron** [comment]
@TheNightingale 

Except for the hand tele in the same room that you get to the abandoned teleporter from, or going directly north to the white ship

**Comment by Buggy123** [comment]
This still requires you to do enough research to make the boards, keep in mind. The only difference is you don't have to beg mining for minerals.

**Comment by KazeEspada** [comment]
You are out in the middle of space? How is this roundstart?

**Comment by KorPhaeron** [comment]
>walk to teleporter
>go through to abandoned tele
>warp home

**Comment by Buggy123** [comment]
Again, this is NOT roundstart, by the time you get to this point in research mining will usually have brought minerals and you can just make your own crystals, if they bring anything at all. This just lets you get telesci without mining, not a huge advantage.

**Comment by KorPhaeron** [comment]
Well okay then
