### ISSUE TITLE
Making cable coils in autolathe doesn't work

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#15550]
PM: (Cuts-The-Throats)->Ausops/(Gast Hehum Ansrace Warnow): If I make something stackable (metal, glass) then attempt to make cable coils, it attempts to make the stackable items previously made. So, I make 1 metal, then make 10 cable coils, recieve 10 metal, 11 total. It's odd.

reproduced

**Comment by KorPhaeron** [comment]
@Buggy123

**Comment by Buggy123** [comment]
Fuck.
