### ISSUE TITLE
IC in OOC detector menu

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15563]
The Yes and No options are inverted compared to every other prompt in the whole game which means that if I want to hit no I accidentally hit yes and vice versa

**Comment by ChangelingRain** [comment]
Intended so that you don't hammer enter and accidentally say something in OOC

**Comment by Zilenan91** [comment]
Well yeah but the message is already sent, if it comes up and you see it you're gonna automatically hit no because you know it's the IC in OOC detector, but they're inverted so you hit the wrong answer and send it anyways.
