### ISSUE TITLE
Unable to wrap things as Giant Spider

### ISSUE THREAD

**Issue by darkpaladin109** [tgstation/-tg-station#15571]
As the title says, I tried playing as a Giant Ice Spider, but found that I wasn't able to wrap anything inside a cocoon, as whenever I tried, it only made what seems to be a empty cocoon while leaving the thing I was using it on where it was before.

Sorry if this has been reported before, or if I missed something, but it seems like it's a new bug, as the last time I play as a spider a day or two ago, I was able to wrap things just fine.

**Comment by KazeEspada** [comment]
What were you wrapping?

**Comment by darkpaladin109** [comment]
Spider corpses, mostly.

**Comment by KazeEspada** [comment]
Spiders will attempt to wrap spider corpses and then fail.

**Comment by darkpaladin109** [comment]
Ah, that makes sense. Thanks for explaining!
