### ISSUE TITLE
Floor is lava causes a lagspike

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15573]
I don't remember this behavior originally/in testing. 

Maybe it was the spawn that got added

**Comment by xxalpha** [comment]
spawns are slow

**Comment by tkdrg** [comment]
this is probably just ChangeTurf() overhead which is a lot higher than setting a var

**Comment by KorPhaeron** [comment]
Doesnt change turfs, just changes the icon on areas.

**Comment by xxalpha** [comment]
It does a few things.
