### ISSUE TITLE
No message when you lit a cigarette

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15584]
Neither for me and neither for anyone that is near you.

**Comment by phil235** [comment]
relevant code: https://github.com/tgstation/-tg-station/blob/6bfa738a246ce4cfba3c621c8c26c5de5961a49c/code/game/objects/items/weapons/cigs_lighters.dm#L168

**Comment by PKPenguin321** [comment]
from what i can gather from this code, you need to change "flavor_text = null" into "flavor_text = lighting_text"
im probably super wrong though

**Comment by phil235** [comment]
I think it should be ` proc/light(flavor_text)`
