### ISSUE TITLE
AI-Hacked APCs cannot be crowbarred open

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15608]
I haven't had a chance to reproduce this yet, but from what I gathered in a traitor-AI round last night,

1. AI hacks an APC (it turns blue and reduces the AI's doomsday timer)
2. Hack APC to unlock the interface
3. Disable the cover lock
4. Try to crowbar it
5. Literally nothing happens (what SHOULD happen is that the cover swings open, allowing you to take out the power cell with your bare hands)

Why this is bad: Unless you're carrying an explosive to damage the APC, there is no way to deconstruct a malfunctioning APC, meaning you cannot increase the AI's doomsday timer.

**Comment by optimumtact** [comment]
Are you sure this isn't intended? I thought you had to break them to slow the AI down

**Comment by PKPenguin321** [comment]
yeah, you've been for the longest time able to normally deconstruct malf APCs. this is a recent bug

**Comment by Shadowlight213** [comment]
@Pkpenguin321 I'm pretty sure the doomsday timer is fixed and doesn't vary based off of the number of apcs.

**Comment by PKPenguin321** [comment]
that must have changed since malf was removed and AI doomsday was added to traitor AI, then

**Comment by KorPhaeron** [comment]
You have to bash the APC panel first. Hit it with an extinguisher a couple times.

**Comment by PKPenguin321** [comment]
That's generally only for APCs that have already been damaged by an explosive. I'm not sure why this would have changed.

**Comment by GunHog** [comment]
I imagine this is a bug. Deconstucting APCs is the primary way to kill a shunted AI.

**Comment by ShadowDeath6** [comment]
This is intended, just whack it until the succulent powercell exposes itself. 

Even says if you examine the APC, "The cover is broken. Look like it'll be hard to force open."

**Comment by ChangelingRain** [comment]
Not a bug, intended five-year-old recently-fixed behavior.
