### ISSUE TITLE
Ghosts enter cuboards/closests when orbiting someone

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#15612]
On Basil.

Following (orbiting) a wizard, with a few other ghosts.
Wizard enters closet, ghosts orbiting are "pulled" in with him.
When wizard exits closet ghosts re-emerge and are now no longer following.

Can move out the closet as a ghost before they emerge and can re-follow once person has left closet.

More a pain in the ass than a major bug.

**Comment by phil235** [comment]
Happens to any mob entering a closet. Closet code seems to forceMove the ghost inside the closet which shouldn't happen, and break the orbiting.
