### ISSUE TITLE
Walls cant be constructed using the /fifty metal subtype.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15621]
Had someone try to build a wall using metal sheets obtained from the shuttle. the stack spawned on the shuttle is the 50 subtype, which didn't work, while a regular stack did.

**Comment by phil235** [comment]
You can build a girder with it but not apply the stack onto the girder to finish the wall. Same with reinforced girder.

**Comment by xxalpha** [comment]
Weird, is it checking for exact type in the construction code?

**Comment by duncathan** [comment]
Probably `if(foo.type == bar)` instead of `if(istype(foo, bar))` yeah
