### ISSUE TITLE
Experimentor can apparently produce fungal tuberculosis

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15622]
So, regular traitor round suddenly had fungal tuberculosis fucking everyone up.
According to OOC at round end, it was caused by the experimentor. Looking through code, this shouldn't be possible.

**Comment by AnturK** [comment]
Experimentor can produce primed chem grenades, TB has one.

**Comment by WJohn** [comment]
This is station destroying levels of chaos, alongside it originally turning people into xenos and summoning meteors, this probably has to go, too.

**Comment by tkdrg** [comment]
Don't tell me it just picks random fucking grenades

**Comment by GunHog** [comment]
I found that quite hilarious. Yes, after looking, it seems that it will just select a random grenade type from the chem nade list and activate it. The CLF3 grenade is especially an interesting choice. Could simply have a whitelist of grenades that keep their destruction contained to the actual chamber.

**Comment by bgobandit** [comment]
restore telescience when

**Comment by Buggy123** [comment]
I still don't get how telescience was THAT overpowered, it's range was shit unless mining brought you minerals or you deconstructed a teleporter. I guess the only reason it's considered balanced now is because you have to build it, and almost no one ever bothers.

**Comment by Lumipharon** [comment]
Because deconstructing the teleporter took 5 seconds from round start, then you could loot anything and everything, which was terrible.

**Comment by Aloraydrel** [comment]
Shoot the experimentor in the head please

**Comment by Dorsisdwarf** [comment]
technically not a bug, even if FUUUUUUUUUUUUUUUU

**Comment by Dorsisdwarf** [comment]
Crush'd

**Comment by PKPenguin321** [comment]
Reopen this is def. unintended
