### ISSUE TITLE
Swarmers can breach space on BoxStation

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15620]
![bug](https://cloud.githubusercontent.com/assets/13275673/13166185/ad8f4a96-d679-11e5-81a9-bb91582e245f.png)

**Comment by ChangelingRain** [comment]
It was breached by a revenant, the grilles don't stop atmos so the swarmer ate the grilles.

**Comment by Zilenan91** [comment]
Ohh ok
