### ISSUE TITLE
Transforming message for morph is wrong

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#15627]
Messages usually end up like 
The donut box suddenly twists and changes shape, becoming a copy of the donut box!

Since the message is suppose to be

The (x) suddenly twists and changes shape, becoming a copy of the (y)!

Doesn't tell you what it was originally in the text

**Comment by PKPenguin321** [comment]
probably a line ordering error
the message should be given before the morph's name changes
