### ISSUE TITLE
Dead cyborgs hear binary twice

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#15634]
If you're a dead cyborg in your body (not ghosting), you will hear binary twice. One of the messages will have the (F) link.

**Comment by KazeEspada** [comment]
One is your body, one is the ghost inhabiting your body.

**Comment by ChangelingRain** [comment]
This is likely to happen for most chats that have a follow link and check if the mob is in the dead mob list.

**Comment by Jalleo** [comment]
It also happens if you are following a person hearing their headset.
