### ISSUE TITLE
Lava floors deal burn damage to cyborgs instead of brute.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#15633]
Burn damage on cyborgs is reserved for EMPs.

**Comment by PKPenguin321** [comment]
idk man i mean this kinda makes sense
borgs can get burn damage in more than EMPs too, like immovable rods hitting them (dont ask how i know ;-;)

**Comment by xxalpha** [comment]
I'll rephrase that. Burn damage on cyborgs is reserved for internal damage.

**Comment by PKPenguin321** [comment]
well maybe the floor being lava heats their internal wiring and damages it then?

**Comment by ShadowDeath6** [comment]
Welding a borg on harm intent will burn it.

**Comment by KorPhaeron** [comment]
I'm not sure lava burning things is an issue

**Comment by xxalpha** [comment]
Cyborgs can't jump on a table.

**Comment by KorPhaeron** [comment]
Floor is lava and lava are two different things

**Comment by KazeEspada** [comment]
chairs and lockers are "lava" proof.

**Comment by Dorsisdwarf** [comment]
Closed because borgs DO take burn damage elsewhere, so there's no point saying lava can't do it.

**Comment by xxalpha** [comment]
It's not from fire dorsisdwarf. It's from EMP and explosions.
