### ISSUE TITLE
Smashing someones head against a urinal is a notice spanclass and not danger.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#15637]
As an attack, it should be danger(red text) rather then notice(which is blue).

**Comment by PKPenguin321** [comment]
It's only a notice to the person that slams, but it's danger to everybody else. Non-issue
[The line, for reference](https://github.com/tgstation/-tg-station/blob/2a9444a891c3684042c5bf2e1b4f77898b10b88b/code/game/objects/structures/watercloset.dm#L136)

**Comment by KazeEspada** [comment]
Toilet smashing is danger. This is a minor inconsistency.

**Comment by kingofkosmos** [comment]
You're correct, it should be danger.

The logic behind this IMO should be:

* notice: you do something usual.
* warning: you fail at something.
* danger: you inflict damage!
* userdanger: you're getting hurt!
