### ISSUE TITLE
Hivelord heal not working

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15646]
HELP: Laimfu/(Spike Christman) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): coders broke the hivelord(?|F) remains I think, they don't seem to heal 

When you shove it on your face

**Comment by GunHog** [comment]
I thought it was changed to require surgical implantation.

**Comment by Zilenan91** [comment]
Implanting it just makes you have regen over time. If you kill a hivelord and then smush the remains all over your face to heal yourself it will fully heal you.

Guy might've waited too long and his hivelord core decayed so he couldn't use it. Could be a non-issue.

**Comment by PKPenguin321** [comment]
needs reproduction tag pls

**Comment by KorPhaeron** [comment]
Nah @phil235 said he knows what it is/can fix it
