### ISSUE TITLE
Announcements are not showing at all

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15653]
They do happen(I can see in the admin log), but it's not visible to anyone.

**Comment by lzimann** [comment]
Kinda high priority, since it affects the game quite a bit...

**Comment by PKPenguin321** [comment]
this is pretty big
it just made an AI traitor round very strange because the game never announced that the AI activated the doomsday device, and the shuttle wouldn't launch but nobody could figure out why

**Comment by AdamElTablawy** [comment]
also means blobs can actually legit stealth blob if nobody checks the maint hidey holes
