### ISSUE TITLE
Check antagonist panel has follow buttons under names.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#15666]
![](http://i.imgur.com/mslvJ6u.png)

This occured during a rev round. I'll see if this happens across other round types.

**Comment by KazeEspada** [comment]
Width issue?

**Comment by tkdrg** [comment]
i pinged @Shadowlight213 about this on IRC but i don't think he saw it

**Comment by Shadowlight213** [comment]
Picture would have been like 10 times more helpful had it not had the antags censored out. Just post that kind of data after round end.
I'm going to assume the regular revs are the ones at the bottom. I probably forgot to remove a line break for regular revs. I'll fix it once I get home.
