### ISSUE TITLE
Using the Nuke Op reinforcement spawner just plops people into the role

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#15665]
It should probably give ghosts a prompt, because otherwise it could spawn in people who are afk.
Other roles like Stands, Wizard Apprentices, Away Mission NPCs and Xenobio mobs all get a prompt. It wouldn't be a bad idea to add one to the reinforcement spawner, in my opinion.

**Comment by xxalpha** [comment]
Prompts are shit because some people will never click in time.

**Comment by ChangelingRain** [comment]
Oh, I dunno, every 5-second blobbernaut prompt gets a ghost, so I don't think that's an issue.

**Comment by xxalpha** [comment]
The issue is some people never having a turn because they weren't spam clicking and had good latency.

**Comment by SweaterKittens** [comment]
While I never ever mind getting spawned as a Nuke Op, it really should give you a prompt, in case you're waiting to get cloned, wanting to stay in deadchat, etc. etc. I've never had any issue missing a prompt unless I was afk or not paying attention, but if that's common, maybe the timer should be increased. As @TheRealGLH said, if all of our other roles prompt you first, we should at least be consistent.

**Comment by xxalpha** [comment]
A timer doesn't help, everyone is prompted and it's first come first served. People with better latency are going to win every time.

**Comment by SweaterKittens** [comment]
Unless it was changed, my understanding was that it compiled everyone who hit yes in the 5-10 second timer and picked one randomly.

**Comment by YakumoChen** [comment]
iirc all the prompts that bring up a window are randomly selected, while all the ones that just generate a message in the text log are first-come, first served (ie spammy ones like swarmer, drone, spoider, golem, etc)

**Comment by Dorsisdwarf** [comment]
This is the way all traditional antag_spawners and events worked (syndiborgs, apprentices, etc.),(aliens, ninja etc) 

It's only the recent proliferation of 100 billion post-death roles and events that resulted in the irritatingly loud spam of popups. Would YOU like to be a spider?
