### ISSUE TITLE
Using monkeys in the gibber drops human skin

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#15664]
as opposed to monkey skin

**Comment by KorPhaeron** [comment]
@Firecage

**Comment by Firecage** [comment]
Wait, we can put monkeys into gibbers now??????

**Comment by Aloraydrel** [comment]
Yea

**Comment by bgobandit** [comment]
where is the FUCK tag when you need it

**Comment by Anonmare** [comment]
Monkeys confirmed for Human. Checkmate Silicons.

**Comment by Jalleo** [comment]
@WJohn FUCK!

**Comment by Aloraydrel** [comment]
Atheists 1

Christians 0

**Comment by duncathan** [comment]
T-template pls
