### ISSUE TITLE
Super protokinetic accelerator is shit when it should have been buffed.

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#15674]
### What is the problem?
It is 1x1 instead of 3x2
### Why is it a problem, or what should have happened?
Nobody asked for this. It should have had 3x the range and destroyed more tiles per blast.
### How can the problem be reproduced?
Spawn yourself one and try it.
### What revision did the problem happen on? (Helpful, but not required)
today. wasn't like it a few weeks ago.

**Comment by Iamgoofball** [comment]
# FEEDBACK FORUM

**Comment by LanCartwright** [comment]
This is not feedback. This is a bug.

**Comment by Niknakflak** [comment]
This is feedback, not a bug

**Comment by ChangelingRain** [comment]
It's the hyper-kinetic accelerator that has the splash and increased range, super only has slightly higher damage.

**Comment by LanCartwright** [comment]
what the fuck

**Comment by PKPenguin321** [comment]
super kinetic != hyper kinetic my friend
