### ISSUE TITLE
Turning off roundstart AI as a testmerge also breaks making new AIs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15688]
### What is the problem? 

Due to a check for config in https://github.com/tgstation/-tg-station/blob/10788ec5152824330c641b179b17a7590a987616/code/game/objects/structures/ai_core.dm, you cannot make an AI (the MMI "doesn't seem to fit") if roundstart AIs are disabled.

### Why is it a problem, or what should have happened?

For obvious reasons this interferes with testing no roundstart AI for balance reasons. You're testing an entirely different thing.

### How can the problem be reproduced?

Try to make an AI

### What revision did the problem happen on? (Helpful, but not required)

All with roundstart AI disabled

**Comment by Iamgoofball** [comment]
The config option isn't for disabling roundstart AI, it's for disabling AIs entirely.

Hence why it makes the hub listing show up as "AI disabled"

**Comment by bgobandit** [comment]
true but it's being mentioned to the playerbase as "no roundstart AI," I got an adminhelp about this earlier

**Comment by KorPhaeron** [comment]
Listen to iamgoofball

**Comment by GunHog** [comment]
The nightmare continues.
