### ISSUE TITLE
Space cat doesn't have sit or stretch icons. Cause disappearance of mob

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#15694]
When the simplemob "space cat" changes to a sitting or stretch position it causes it to reference a none existing icon state.
Changes to spacecat_sit or spacecat_rest

### Why is it a problem, or what should have happened?
Mob disappears completely when in these states.

### How can the problem be reproduced?
Spawn space cat, wait until the sit animation takes place

### What revision did the problem happen on? (Helpful, but not required)
Current.

**Comment by PKPenguin321** [comment]
Pretty sure this is a dupe

**Comment by tkdrg** [comment]
I think @bgobandit reported this before?

**Comment by bgobandit** [comment]
dupe
