### ISSUE TITLE
Issue with augment surgery/health

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15706]
HELP: PupGaming/(Gases-The-Nerds) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): so I think there is a bug where when you get full aug the client things that the last part auged is still injured whne its not 

http://i.imgur.com/h1qPesj.png

At half health but no damage

**Comment by phil235** [comment]
It's an issue of health not being updated. There's a missing updatehealth() in the limb augmentation proc.
