### ISSUE TITLE
You can unweld a locker by wrapping it in paper.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/-tg-station#15721]
### What is the problem?
A welded locker can be opened without unwelding it first.
### Why is it a problem, or what should have happened?
You shouldn't be able to open a welded locker by hand.
### How can the problem be reproduced?
Weld a locker shut then wrap it in paper, tear the paper off and while the sprite still displays a welded locker, it can be opened by hand.

**Comment by optimumtact** [comment]
wu-wei my friend, wu-wei

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/2a6a63253bb411826b6f4dd831c2e6e1dfe91671/code/modules/recycling/sortingmachinery.dm#L22

To prevent a mob inside a wrapped locker from resisting and opening the locker while inside the wrap, the code makes the locker welded = 1 when you wrap it, and it unwelds it on unwrap. HACKY CODE.....

**Comment by Supermichael777** [comment]
doesn't that imply wrapping paper is as strong as wielded steel? That seems wrong. Then again crappy space man spot wields probably aren't that strong seeing as you can break them.
