### ISSUE TITLE
RPD can make invisible pipes

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15738]
http://puu.sh/nkkQT/6292937b6c.png

Despite there being a sprite in the examine text, the object is invisible (although it does have inhands).

To do this, simply get an RPD, and do not change the setting off of the default. The default setting creates these invisible pipes. The RPD menu when this pipe is selected can be seem in [this image.](http://puu.sh/nkkUz/1d1bded7b9.png)

**Comment by duncathan** [comment]
This is a good report but it'd be nice if you used the template 1
