### ISSUE TITLE
Invisible wall on box

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#15732]
### What is the problem?
An invisible wall in the chapel.
### Why is it a problem, or what should have happened?
No invisible wall.
### How can the problem be reproduced?
Start map, wall.

![Wall](http://puu.sh/nk5RP/157fdd8946.png)
Invisible wall one block under me.

**Comment by WJohn** [comment]
Perhaps the mass driver controls are for some reason dense?

**Comment by Buggy123** [comment]
fuuuuuuuck
