### ISSUE TITLE
Arm cannon implant doesn't give the action button for it.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15749]
@PKPenguin321

**Comment by PKPenguin321** [comment]
Probably caused by phil's rewrite thing, I haven't touched arm cannons in a while. I'll try to look into it.

**Comment by phil235** [comment]
Nope, it's you @PKPenguin321  https://github.com/tgstation/-tg-station/pull/13983/files#diff-f608a761777696caf7e69c7e3d022b97R311 You didn't call ..() in your New().

**Comment by PKPenguin321** [comment]
Ah. Well, Core0Verload is fixing it in his awesome rewrite anyways.
