### ISSUE TITLE
Using the admin rejuvenate verb on a monkey makes them a human

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#15746]
See the title

**Comment by phil235** [comment]
That's my fault. The revive proc removes mutations that are negative, which race mut apparently is. I'll change it so only humans get their bad mutation removed.

**Comment by duncathan** [comment]
The template exists for a reason @pkpenguin321

**Comment by PKPenguin321** [comment]
yeah but why would i fill out like 30 fields when i can fill out the title and be done
