### ISSUE TITLE
Chamaleon kits only come with the cham jumpsuit

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#15754]
If you buy the kit(which is also in the wrong category, "item category:") it will only gives you the jumpsuit.

**Comment by Supermichael777** [comment]
weird

**Comment by Dorsisdwarf** [comment]
@Iamgoofball

**Comment by bgobandit** [comment]
GOOF DID YOU EVEN TEST THIS SHIT

**Comment by PKPenguin321** [comment]
cucked

**Comment by Iamgoofball** [comment]
I TESTED EVERTHING BUT THE UPLINK FUCK
