### ISSUE TITLE
Backpack sprayer nozell stays in hand and can go on belt

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#15764]
What is the problem? 
sprite glitch, inventory error

Why is it a problem, or what should have happened?
sprite should have disapered and it should go back into pack

How can the problem be reproduced?
mess with janitor backpack

**Comment by PKPenguin321** [comment]
needs to have it's belt slot flag removed

**Comment by Crushtoe** [comment]
Mister doesn't have a belt_slot flag, both the water tank and the mister itself.
