### ISSUE TITLE
Photocopiers produce paper that appears blank

### ISSUE THREAD

**Issue by newfren** [tgstation/-tg-station#15778]
### What is the problem? 
When you photocopy a piece of paper that has writing on it, instead of the copies looking like they have writing on them too they just look like blank pieces of paper

### Why is it a problem, or what should have happened?
They should look like paper with writing on them

### How can the problem be reproduced?
Photocopy a piece of paper

### What revision did the problem happen on? (Helpful, but not required)
Current

**Comment by PKPenguin321** [comment]
i think this may be a dupe

**Comment by PKPenguin321** [comment]
yeah, this is probably caused by whatever's causing https://github.com/tgstation/-tg-station/issues/15601
