### ISSUE TITLE
Breaking a chair over something doesn't stun it

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#15798]
### What is the problem?
Title
### Why is it a problem, or what should have happened?
If I'm understanding it right breaking a chair over something should stun it
### How can the problem be reproduced?
Break a chair over something
### What revision did the problem happen on? (Helpful, but not required)
c49a4b71a36ac1f41b91679643cdb64757082617

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/2f688f2b6466c1933c905781bf9db341f740c3a5/code/game/objects/structures/beds_chairs/chair.dm#L260
It only weakens carbons, and only if their health is below 50%. And the weaken effect only lasts one second.

**Comment by Zilenan91** [comment]
>kaze nerfing an 8 brute weapon this hard
