### ISSUE TITLE
Changing the burst_size var on wands has no effect

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15796]
### What is the problem?
Changing the burst_size variable on wands doesn't affect how many shots it fires, its still only one shot at a time
### Why is it a problem, or what should have happened?
Varediting the burst size variable on normal guns can lead to hilarious hijinx, and it'd be really nice if it worked on the harmless wand of nothing too
### How can the problem be reproduced?
Spawn a wand of nothing (or any wand), change the burst_size variable, shoot it

This is hardly a big issue and may be closer to a feature request than a bug, but having the burst_size var working for wands would be very much appreciated by admins.

**Comment by phil235** [comment]
Same issue happens with energy weapons, the problem is that the second shot isn't loaded so when the gun tries to fire it fails (energy weapons do "click" , wands do "XYZ fizzles")
