### ISSUE TITLE
Some places in the code still use gc_destroyed

### ISSUE THREAD

**Issue by Menshin** [tgstation/-tg-station#15801]
There's still some places in the code that use ```gc_destroyed``` to check if an object has been qdel'd.

This a problem since ```gc_destroyed``` is set during ```Queue()``` and not ```QueuingForQueue()``` and this allows some objects to be qdel'd twice (most notably objects eaten by singulo, making loads of runtimes for ```/obj/machinery``` subtypes that tries to unload contents in null space).

These should be replaced by ```qdeleted()```, but this raises possible concerns about performances in case of lots of garbage collection during one tick.
For example, if singulo eat X ```obj/```, then ```tobequeued``` is traversed 2X times (growing each time) to check for if the object is GC'd.

**Comment by MrStonedOne** [comment]
I'll fix tobequeued to mark gc_destroyed with -1 so we don't need to search thru it in qdeleted()

**Comment by Menshin** [comment]
Fixed by #15807 and  #15916.
