### ISSUE TITLE
Augmenting someone's chest removes their lungs

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15813]
### What is the problem?
Augmenting someone's chest removes their lungs, which means they can't breathe or speak, with no way for them to breathe
### Why is it a problem, or what should have happened?
Having a robo chest should simulate having lungs like it does for a heart, since they're kinda important
### How can the problem be reproduced?
Augment someone's chest

**Comment by WJohn** [comment]
@Core0verload
