### ISSUE TITLE
Reloading admins doesn't give any notification to admins who are re-admin'd

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15844]
### What is the problem?
Reloading admins doesn't give any notification to admins who are re-admin'd
### Why is it a problem, or what should have happened?
If someone is deadmin'd to play security/antag/whatever and I reload admins for some reason, there's no warning for the other admins to re-deadmin unless the one who readmin'd it warns the others

**Comment by Jordie0608** [comment]
The notification is when all your admin verbs come back and you start seeing admin messages. I don't think there really needs to be more than that.

**Comment by Shapsy** [comment]
When you're playing, that first message you see could be one that spoils the gamemode. Yesterday during a traitor round we had to reload admins to add someone to the admins.txt which readmin'd a traitor and the HoS a little before I mentioned the AI was rogue in deadchat, spoiling them both

Can the "so and so reloaded admins" message not be displayed until after everyone's readmin'd?

**Comment by Jordie0608** [comment]
The problems you describe aren't issues with the reload verb nor would be fixed by adding more notification; even if there was a note that they'd been re-adminned they still would've seen your first spoiling message.

**Comment by optimumtact** [comment]
More accurately the deadmined status should just persist through a reload.
