### ISSUE TITLE
Simple mobs (human) corpses have a randomized name

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15864]
### What is the problem?
See title. For example, a Clown simple mob who dies leaves behind a corpse named Fortune Ray instead of named Clown.

### Why is it a problem, or what should have happened?
Should be named Clown.

### How can the problem be reproduced?
Just kill a simple animal Clown

**Comment by KazeEspada** [comment]
They always reverted to humans you monster.

**Comment by GunHog** [comment]
They convert to a corpse so you can loot or do other horrible things to their corpses as you would a real human.

**Comment by KorPhaeron** [comment]
Intended. They've done this for 3-4 years now.

**Comment by bgobandit** [comment]
The bug isn't that they convert to a human the bug is that they convert to a NAMED human

So instead of "Clown" they'd become "Braydon Williams" or whatever

**Comment by bgobandit** [comment]
dupe
