### ISSUE TITLE
Bolas don't work properly in space

### ISSUE THREAD

**Issue by Lexorion** [tgstation/-tg-station#15887]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Bolas snare can easily be undone in space. After they hit a target and snare it they stay on the floor. Picking them up removes the slowdown effect,even tho they are supposed to be wrapped around the targets legs.

### Why is it a problem, or what should have happened?
They aren't supposed to stay on the floor after hitting a target, it shouldn't remove the bolas from the target if you pick it up.

### How can the problem be reproduced?
Throw bolas at someone in space,e.g. outside of escape on boxstation. The bolas hit the target but stay on the floor. 

### What revision did the problem happen on? (Helpful, but not required)

current

**Comment by phil235** [comment]
Same issue happens with thrown items embedding themselves into mobs in space. Somehow the item's location is set to be in the mob, then it's immediately set back to the turf. It's a problem with throwing.
