### ISSUE TITLE
Player kittens are weird and buggy

### ISSUE THREAD

**Issue by Sligneris** [tgstation/-tg-station#15890]
### What is the problem?
Everything is a problem.

NPC kitten emotes and related sprite changes still occur while controlled by a player.

While moving with a 'sit' or 'rest' sprite, the sprite doesn't update when the direction of movement changes.

### Why is it a problem, or what should have happened?

Everything is a problem and it should be fixed.

To be specific, kittens shouldn't get paralyzed by some actions and the sprite should change depending on the direction of movement.

Ideally, the mob wouldn't sit or rest while controlled by the player, unless the player uses a relevant verb - in which case, the inability to move while resting would be understandable.

### How can the problem be reproduced?

1. Play as a kitten.
2. Wait until your sprite changes to 'sit' or 'rest'.
3. Attempt vent-crawling
4. Attempt to move

or

1. Play as a kitten.
2. Wait until your sprite changes to 'sit' or 'rest'.
3. Buckle yourself to a chair.
4. Unbuckle yourself.
5. Attempt to move

### What revision did the problem happen on? (Helpful, but not required)
Something is test merged, so I only get this: https://github.com/tgstation/-tg-station/commit/39254dd678dda0893bc8d0f72856dd90b3fd8004

**Comment by tkdrg** [comment]
Possibly fixed by #15805 
@bgobandit

**Comment by bgobandit** [comment]
yes all of these are fixed

**Comment by Sligneris** [comment]
Yay, freedom to kittens!
