### ISSUE TITLE
Simple animals breed with reckless abandon before round start

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#15897]
## What is the problem?
If a mommy simple_animal and a daddy simple_animal see each other before round start they can and will produce dozens of babies before the round starts, ignoring child limits (probably because said limits use a list not initialized until roundstart.

## Why is it a problem, or what should have happened?
The CMO is drowning in newborn kittens

## How can the problem be reproduced?
2cat

A reminder for myself if nothing else

**Comment by TheNightingale** [comment]
"The CMO is drowning in newborn kittens"
Github is for problems, this is the opposite of a problem.

**Comment by GunHog** [comment]
Perhaps Runtine has learned breeding techniques from the previous neko CMO?

**Comment by Iamgoofball** [comment]
WE PORTED THE CATSPLOSION

**Comment by Aliannera** [comment]
> Perhaps Runtine has learned breeding techniques from the previous neko CMO?

Sorry.
