### ISSUE TITLE
Mimana and bluespace bananas have no sprite

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#15914]
### What is the problem?

See title

### Why is it a problem, or what should have happened?

Should be obvious

### How can the problem be reproduced?

Have a mimana or bluespace banana

**Comment by ShadowDeath6** [comment]
Mimana peel should be invisible for slip-miming.

**Comment by Incoming5643** [comment]
carpet is also invisible now, as most new ages plants probably are.

This happened because no one handled #13602 and someone who wasn't aware it was a problem saved over the file

**Comment by Core0verload** [comment]
Fixed in #15944.
