### ISSUE TITLE
Can't take shit out of depowered hardsuit storage

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#15927]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
depowered hardsuit storage units let me crowbar them open but I can't get the shit out
### Why is it a problem, or what should have happened?
Items can get stuck in there potentially forever if someone breaks the APC
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by phil235** [comment]
An easy way to fix it that might work is to switch the ssu's open_machine() argument to be TRUE by default, and to change all the instances of it in suit_storage_unit.dm accordingly. Then the content would be dumped when the machine is pried open with a crowbar.

**Comment by PKPenguin321** [comment]
Dupe https://github.com/tgstation/-tg-station/issues/15164
