### ISSUE TITLE
Timber away mission rabbits spam emotes.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15925]
The rabbits on the away mission keep spamming hop emotes due to the large number of them

**Comment by Dorsisdwarf** [comment]
This annoys me with away missions full of spiders too (Fucking lavaland secret room)

**Comment by KazeEspada** [comment]
Make ghost ears not listen to clientless mobs?

**Comment by KazeEspada** [comment]
This is fixed.
