### ISSUE TITLE
Bluespace Banana pells

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15926]
### What is the problem?
Slipped on a bluespace banana peel, locked into place. I can do any action but I can't actually move around
### Why is it a problem, or what should have happened?
After the stun you should be able to move
### How can the problem be reproduced?
Slip on bluespace banana peel, try to move, and you can't
###Server Revision
480583da322b4e120ade58cce05f4910d83423b3

Honestly bluespace peels were overpowered anyways as if you slip on a max potency one and go into space it's instant death sometimes :/

**Comment by kevinz000** [comment]
Nevermind, didn't notice untill later that it was a testmerge of stock market. This could be related..?

**Comment by YakumoChen** [comment]
Second time I've seen a goof merge cause bluespace peels to do this.

**Comment by phil235** [comment]
If you can't move afterwarf it's because some proc forgot to call your mob's update_canmove() proc.

**Comment by Jordie0608** [comment]
At the time the peels were infinitely looping
@Iamgoofball you had the runtimes of this

**Comment by Incoming5643** [comment]
This was either the cause of, or a symptom of, a master controller infinite loop.

**Comment by Iamgoofball** [comment]
i think it's the cause since there were 14 infinite loops from bluespace peels that round alone

**Comment by optimumtact** [comment]
the only possible cause I can see is a teleport range of zero triggering a continous loop of crossed/do teleport, so you're stuck in place endlessly teleporting.

**Comment by Iamgoofball** [comment]
@optimumtact 
we think that someone teleported onto a banana that was qdeleting and killed the MC

**Comment by kyrahabattoir** [comment]
Yes for a scream sound, NO NO NO for the Wilhelm scream.
