### ISSUE TITLE
Washing same monkey cube twice produces two monkeys

### ISSUE THREAD

**Issue by Aliannera** [tgstation/-tg-station#15942]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
When washing a monkey cube, if you click on the sink again while your washing it you end up producing two monkeys instantly.

### Why is it a problem, or what should have happened?
You should only be getting one per cube, not two. So it's more of a balance issue than anything.

### How can the problem be reproduced?
Go to sink, click once with monkey cube to start washing, click again to instantly finish that wash and wash it again somehow to produce lmao two monkey.

**Comment by Buggy123** [comment]
This is a duplicate. #14667

**Comment by ChangelingRain** [comment]
ddddupe
