### ISSUE TITLE
Portal storm uses full server name.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15947]
Attention personnel of /tg/Station Bagil [ENGLISH] [BYOND 510]: Fist Object 42: incoming portal storm!

My immersions are ruined.

**Comment by MrStonedOne** [comment]
Thats not the station name, thats the server name.

Thats why.

Also, we need easier ways to change the output of the hub panel without changing the server name, as i'd like to go back to sybil and basil for the server names since they show up in memos.
