### ISSUE TITLE
Cultwalls can not be fully deconstructed without a RCD

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#15949]
### What is the problem?
Cult walls can be welded to become a cultgirder, but you can't wrench or otherwise get rid of that
### Why is it a problem, or what should have happened?
You should be able to deconstruct them like regular walls.
This makes them kinda powerful because unless you're an engiborg or you have tons of stuff to feed a RCD with a couple of these will block you completely

**Comment by PKPenguin321** [comment]
Might be a dupe

**Comment by Durkel** [comment]
#13222 Probably related.

**Comment by Core0verload** [comment]
You can just apply a welder to the girder again. It destroys the girder.
