### ISSUE TITLE
Admin antag hud doesnt work for ninja

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#15973]
No antag hud icon is shown.
@lordpidey

**Comment by lordpidey** [comment]
Fuck.
How was the ninja spawned?  Random event, or adminfuckery?

**Comment by Shadowlight213** [comment]
I used both the view variables  make into ninja button and the spawn space ninja button in the fun tab

**Comment by lordpidey** [comment]
Aright, I should be able to fix this later today or tomorrow.

**Comment by Dorsisdwarf** [comment]
@lordpidey Are you living on mercury

**Comment by lordpidey** [comment]
>.>  Righto I'll work on this now.
