### ISSUE TITLE
Github reaction nonsense is horrible

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16031]
What is this, facebook? 

Is there any way to turn this off?

**Comment by PKPenguin321** [comment]
it's just :+1: spam but not spam, it's fine you dingus

**Comment by ChangelingRain** [comment]
I'm pretty sure we can't have fun

**Comment by Aloraydrel** [comment]
Like my post

**Comment by GunHog** [comment]
Github is now Facebook.

**Comment by bgobandit** [comment]
github buzzfeed now

**Comment by Giacom** [comment]
Oh god why.

Please like if you agree, for every like = 1 prayer.

**Comment by TrustyGun** [comment]
for serious though, it looks tacky af

**Comment by GunHog** [comment]
Actually, the "Like" and "Dislike" functions effectively replace the " :+1: " comments in a PR. Now they can be consolidated and easily counted in the OP.

**Comment by Giacom** [comment]
Not easily if you add both a like and a dislike.
