### ISSUE TITLE
Metastation's mining station is missing a huge chunk

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#16044]
### What is the problem?
The problem happened on Sybil with the Metastation map (but isn't happening on Basil with Metastation apparently,  different revision I guess). A huge chunk of the mining station is now space. The area just outside the mining shuttle and east of it is only space.

### Why is it a problem, or what should have happened?
Miners can't do their job, there's no hardsuits available, they can't leave their mining shuttle without ending up in space.

### How can the problem be reproduced?
load metastation map and go to the mining station.

Server revision: https://github.com/tgstation/-tg-station/commit/2652382b3b86f7c44a22192b54f3f7b387981e8f

**Comment by KorPhaeron** [comment]
This is my fault and because of the test merge. I cut/pasted part of Z5 to my lavaland file to work off of it, accidentally committed Z5. Not an actual bug.
