### ISSUE TITLE
stripping click drag error

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#16045]
HELP: (Paxium LXIX): what the fucking fuck did you fucking do to stripping you fucking clowns how the fucking fuck am i gonna fucking pickpocket when I DRAG PEOPLE ONTO MY FUCKING TILE WHEN I TRY TO PICKPOCKET THEM FOR FUCK'S FUCKING SAKE I MEAN FUCKING CHRIST IT FUCKING LOOKS LIKE I'M FUCKING THEM - heard by 5 non-AFK admins who have +BAN.

### What is the problem?
click drag to self drags the person onto yourself
### Why is it a problem, or what should have happened?
click drag usually just opens a stripping menu, it doesn't move the mob
### How can the problem be reproduced?
click drag person to self

**Comment by KorPhaeron** [comment]
This is awful

**Comment by phil235** [comment]
My guess is that it has something to do with buckling.

**Comment by PKPenguin321** [comment]
@KorPhaeron critical tag is for security breaches/server crashers (and the occasional meme tagging)

**Comment by phil235** [comment]
@RemieRichards

**Comment by optimumtact** [comment]
A lot of salty powergamers, please leave this as is
