### ISSUE TITLE
map loading hanging on sybil

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16051]
### What is the problem?
Something during map initialization on sybil has a pretty good chance of choking the server until it dies.

### Why is it a problem, or what should have happened?
The server dies

### How can the problem be reproduced?
Play the game

Finger of blame might be on lavaland

**Comment by KorPhaeron** [comment]
Probably lavaland. I took it off the server and will try fixing it when I wake up

**Comment by MrStonedOne** [comment]
ya, it seems its something to do with smoothing, as all of the self cpu was in smooth_icon

**Comment by KorPhaeron** [comment]
So not actually ruins then. I will replace the lava with old lava sprites and see what happens
