### ISSUE TITLE
Blobs can still burst on Toxins Test Satelite

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16056]
I think it was MrPerson who stopped this from happening a long time ago and it seems to have broken again.

**Comment by xxalpha** [comment]
I don't see what the problem is, you can contain and snipe the blob from there pretty easily.

**Comment by Zilenan91** [comment]
It's boring and safe. Blobs just sit there forever and don't interact with anyone or fight them. It used to be particularly bad when space tiles counted towards blob victory.

**Comment by xxalpha** [comment]
It's not safe at all.

**Comment by Zilenan91** [comment]
It really is because who ever checks that thing

**Comment by xxalpha** [comment]
You have no space to expand.

**Comment by Zilenan91** [comment]
You can expand into space and build up resources, even if it means you don't have those count towards your win.

**Comment by KorPhaeron** [comment]
@ChangelingRain 

Up to you

**Comment by ChangelingRain** [comment]
I have a PR up that fixes this accidentally so I'm just gonna go with 'it was a feature but I'm removing it now'
