### ISSUE TITLE
Teleporting causes ghosts to stop orbiting you

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#16057]
Repro:

1. Have ghosts orbiting you
2. Grab hand tele
3. Use it
4. Ghosts are no longer orbiting you

Server revision compiled on: 2016-03-11
b82e4b8d594ff26429eeda4f303981570d838e55

**Comment by phil235** [comment]
Probably due to forceMove()

**Comment by phil235** [comment]
Can't reproduce with a teleport wand, or by manually calling forceMove().
