### ISSUE TITLE
~~~ SEMI-FREEZE UNDERWAY; READ DESCRIPTION ~~~

### ISSUE THREAD

**Issue by duncathan** [tgstation/-tg-station#16061]
In #16026 I'm about to begin my efforts of repathing every turf in the code. Because of the magnitude of this change, I'm effecting a semi freeze (with Cheri's permission) to save me from the hellhole of conflicts that would otherwise arise. 
- No new changes to existing maps (open prs are unaffected) will be accepted. 
  - ~~Entirely new maps will be accepted, but further changes beyond the initial pr will not.~~
- Changes to existing turfs may or may not be accepted, at my discretion. 
  - Any path changes to turfs (including additions) will not be accepted. 

Sorry if this inconveniences anyone, but there's just too much for me to change without effecting this.

**Comment by PKPenguin321** [comment]
we should have had something like this for dismemberment

**Comment by duncathan** [comment]
Let bygones be bygones

**Comment by optimumtact** [comment]
Why don't you just write some python code to rewrite maps for you? Is it not a pretty basic path change with some vars ?

I did the same for my AI turrets change to maintain sanity

**Comment by Aranclanos** [comment]
MY LEGACY

**Comment by duncathan** [comment]
If not for aran none of this would be possible

**Comment by KazeEspada** [comment]
Soon.tm

**Comment by duncathan** [comment]
It's coming don't worry
I'll get a bunch of work done next week cuz I've got the whole week off from school

**Comment by duncathan** [comment]
Alright, since this is approaching completion I'm tightening up the rules a bit:

NO map changes will be accepted now; not even additions.

**Comment by PKPenguin321** [comment]
its over...............................
