### ISSUE TITLE
Meta: Part of the HoP's office can be seen through the wall.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#16069]
Rev 84a1192114652960a13124ac59a3eca622daa25d

![](http://i.imgur.com/byARJlP.png)

**Comment by KazeEspada** [comment]
Basil Right?

**Comment by francinum** [comment]
Yep

**Comment by YotaXP** [comment]
[It's friggin magic](https://i.imgur.com/fMrpWrt.gifv)

**Comment by PKPenguin321** [comment]
What the fuck
