### ISSUE TITLE
Show Server Revision doesn't show testmerged prs

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#16062]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Show server revision is supposed to show if a pr is testmerged #16042 and it doesn't.
### Why is it a problem, or what should have happened?
It should show a testmerged pr, and doesn't.
### How can the problem be reproduced?
Testmerge a pr, click show server revision, see no testmerged pr.
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)
N/A due to testmerge

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by optimumtact** [comment]
did it at least show the appropriate commit from the tip of the PR?

**Comment by ChangelingRain** [comment]
I'm not sure, because I don't know what prs were merged at the time besides #16033 and the commit number thingy doesn't match any of the commits from that pr.

**Comment by Jordie0608** [comment]
During a test merge the head commit isn't the same as the ones from the PR due to some git shenanigans which I'm not sure are resolvable or worth figuring out.

**Comment by optimumtact** [comment]
Well it's because the head commit will be a merge commit.
