### ISSUE TITLE
Chameleon under suit only works as a black jumpsuit

### ISSUE THREAD

**Issue by kpeculier** [tgstation/-tg-station#16086]
**### What is the problem?**

Chameleon jumpsuit for /under/ does not change icon when used to anything other than a black jumpsuit.

**### Why is it a problem, or what should have happened?**

It should be working as intended rather than just being a black jumpsuit.
**
### How can the problem be reproduced?
**
Whenever a chameleon /under/ suit is in the game.

**Comment by KorPhaeron** [comment]
@Iamgoofball
