### ISSUE TITLE
Plasmaman jumpsuit extinguishes soaked (but not on fire) wearer

### ISSUE THREAD

**Issue by erwgd** [tgstation/-tg-station#16091]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
While wearing a plasmaman helmet and jumpsuit with extinguisher canisters, if your character is doused in water via a shower or fire extinguisher then their canisters will be used up to 'extinguish' them.

This seems to be because the extinguish proc in [miscellaneous.dm](https://github.com/tgstation/-tg-station/blob/e0b45691654cc9a0ab49529cf6b81fb2fd479860/code/modules/clothing/under/miscellaneous.dm#L510) checks if you have any number of fire stacks. If you're soaked then you have a non-zero number of fire stacks so you'll be extinguished.

[plasmamen.dm](https://github.com/tgstation/-tg-station/blob/3c8652e34617c15554d96b512bb6a55a91ac9e27/code/modules/clothing/spacesuits/plasmamen.dm#L25) is also affected by this bug.
### Why is it a problem, or what should have happened?
To be soaked with water does not mean that one is on fire. The plasmaman jumpsuit should leave the soaked person alone instead of wasting extinguisher canisters.
### How can the problem be reproduced?
Join a game as a plasmaman. Douse yourself in water; ways to do this include walking under an active shower, using a fire extinguisher or splashing water. 
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)
84a1192114652960a13124ac59a3eca622daa25d

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by phil235** [comment]
I think you meant to reference this: https://github.com/tgstation/-tg-station/blob/3c8652e34617c15554d96b512bb6a55a91ac9e27/code/modules/clothing/spacesuits/plasmamen.dm#L25
