### ISSUE TITLE
You can receive a traitor hud when you change your mob and you are a traitor

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#16092]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
- When you get selected for traitor(I didn't test for other gamemodes, but only saw it happening in traitor so far) and then you change your mob somehow(for example, you die and get cloned, or die and an admin spawn you in another mob) you will get the traitor hud, which is the one admins can activate by the Toggle AntagHUD.

### Why is it a problem, or what should have happened?
- Traitors aren't supposed to have a traitor hud by any means.

### How can the problem be reproduced?
- Spawn in, traitor yourself and change your mob, you will notice a "T" in your HUD, which will show up above all traitors.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by PKPenguin321** [comment]
High priority

**Comment by duncathan** [comment]
Does this happen to non admins?

**Comment by lzimann** [comment]
@duncathan Yes

**Comment by lordpidey** [comment]
aww hell, I thought I fixed this with #16023

I'll try and figure this out.
