### ISSUE TITLE
Banana potency isn't affecting slip time.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#16103]
### What is the problem?
Peels at 100 potency are slipping for incredibly low time, less than a bar of soap.
### Why is it a problem, or what should have happened?
Why even bother with potency if isn't gonna slip?
### How can the problem be reproduced?
Make peels, throw them security officers, watch as they slip,get up, and beat you.
### What revision did the problem happen on? (Helpful, but not required)
39e356c55cf6223162814135ba54512af7481cac

**Comment by bobdobbington** [comment]
Tower cap tray sprites are also gone, and bluespace tomatoes should just slip when run over not teleport like bluespace bananas. Bluespace teleport when thrown or if the player hits Z.

**Comment by PKPenguin321** [comment]
@Core0verload

**Comment by Core0verload** [comment]
A fix is already included in #16082.

**Comment by KorPhaeron** [comment]
People started ahelping about hackers/cheaters when they got up too fast from the slip, funny stuff

**Comment by Supermichael777** [comment]
maxpotency bananaspam was cancer this fixed it please no

**Comment by YakumoChen** [comment]
stealthbuff to the clownship clown shoes
