### ISSUE TITLE
ORM decimals

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#16101]
THIS IS ALL YOUR FAULT KOR
![](https://i.gyazo.com/512f7921a5bafb49ce7e346fca25ccbe.png) :^(
Paste images with `![](image url here)`

**Comment by PKPenguin321** [comment]
![https://gyazo.com/512f7921a5bafb49ce7e346fca25ccbe](ayylmao)

**Comment by kevinz000** [comment]
Ok so the image broke but BASICLLY THERES DECIMAL POINTS IN MUH ORE REDEEMER

**Comment by MMMiracles** [comment]
I don't think you needed to test code when he literally made varying upgrades only give a 1.2-2x bonus at max.

I can't see how this wouldn't be intended.

**Comment by KazeEspada** [comment]
This is intended, if you get to the next whole amount, you get another piece of ore.

**Comment by Lumipharon** [comment]
mehki please go. Why would there not be decimals in the ORM? The alternatives are rounding (which is retarded) or simply hiding them (which serves no useful purpose).

**Comment by KorPhaeron** [comment]
Of course there are decimal points though. Otherwise you'd have to round down every sheet (and lose the bonus) or round up every sheet (and the change is undone).

**Comment by KorPhaeron** [comment]
Save your decimals up one day you can buy a full ore sheet.
