### ISSUE TITLE
Tablecrafting could use improvements

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16107]
These are some issues with tablecrafting that I gathered after a long and back-and-forth discussion in coderbus. There are probably more issues, but these are the big ones.

1. **REQUIRING A TABLE TO CRAFT IS AWFUL.** Make it something like a UI button to open the crafting menu, and pull the items from a 3x3 radius around the player or something.

2. Recipes that require more than two tools are bizarre and unclear. You can't hold more than two things, so what do you do? Pick 2 of the 3? Put the third one on the table with the ingredients? ???

3. It can't exclude child objects. See https://github.com/tgstation/-tg-station/issues/13229 for an example of this.

4. It lacks the discovery aspect of manual crafting, as well as the feeling of actually doing work to craft things that manual crafting has. This is probably unresolvable unless we make it like a minecraft-crafting type system (which probably nobody will do).
**Edit: Another issue has shown up:**

5. It lacks support for outputting more than one item from a single recipe, which means it cannot be used for deconstructing, among other things (such as gun pin removal giving back the gun and the pin).

**Comment by phil235** [comment]
4 only became a problem when we made all possible recipes visible a couple months ago.

**Comment by Iamgoofball** [comment]
1. it should also pull from your inventory and equipped items too
2. solved by ^
3. this is gonna be a tough one to crack

4 isn't a problem

**Comment by RemieRichards** [comment]
Making all recipes visible was /requested/ so no, it's not a problem, it's literally the future you chose.

**Comment by PKPenguin321** [comment]
I personally have no issue with recipes being shown, but that was a complaint I heard more than once on coderbus.

**Comment by KazeEspada** [comment]
New Idea: Item Recipes.
Upon New() every item would search through the recipe datums and add any recipes that contained itself to its own recipe list.

When two items are hit together, the item would compare it's recipe list with the other items. If they had any matching recipes. It would check if the mob had the rest of the ingredients in it contents, or maybe the tile if your attacking something on a tile(IE on a table). 

If it found a complete recipe, it would then make it. If it found multiple complete recipes, then it would popup a menu or tooltip to select the one you want.

**Comment by Jalleo** [comment]
That while sounding good is actually really bad @KazeEspada.

**Comment by nullbear** [comment]
Compromise for the recipes being shown: Have some recipes be "secret", and only appear if all required materials are already on the table. Or even just "One" of the required materials.

Outputting more than one item from a recipe could be easily added. As for the pin from a gun, this could just be done in the resulting guns checkparts, dropping the original pin, instead of deleting it.

3 Could be partially done in some cases via checkparts().

**Comment by PKPenguin321** [comment]
Dorsi, a lot of this is still unresolved
