### ISSUE TITLE
Bananna bug

### ISSUE THREAD

**Issue by sirnat** [tgstation/-tg-station#16106]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
You can not eat the clown banana you spawn with.
### Why is it a problem, or what should have happened?
Not a huge problem its just you can't eat it, every time you try it it says, "There is no more of your banana left!" and then drops it on the ground.
### How can the problem be reproduced?
Just spawn as a clown and try to eat the banana in your backpack.
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by bgobandit** [comment]
@CoreOverload

**Comment by sirnat** [comment]
It isn't major, just thought I'd report it.

**Comment by Core0verload** [comment]
Thanks for report!

The clown banana was created with a special snowflake var, which was incompatible with my plants updates. I included a fix in #16082.

**Comment by CoreOverload** [comment]
Hey all,

I think I am being mistakenly included on these emails...

Best regards,

*Benjamin Quesnel*

*Phone: *     403-483-5340 <4034835340>

*Website:*    RightDesign.ca <http://rightdesign.ca>
*LinkedIn:*   Connect via LinkedIn <https://ca.linkedin.com/in/benquesnel>

**Comment by bgobandit** [comment]
HONK

**Comment by Shadowlight213** [comment]
Hahaha. Sorry dude. 0 versus O.

**Comment by CoreOverload** [comment]
Damn you! Lol.

*Benjamin Quesnel*

*Phone: *     403-483-5340 <4034835340>

*Website:*    RightDesign.ca <http://rightdesign.ca>
*LinkedIn:*   Connect via LinkedIn <https://ca.linkedin.com/in/benquesnel>

**Comment by Buggy123** [comment]
Uhh... is CoreOverload a bot?

**Comment by Iamgoofball** [comment]
nope

**Comment by bgobandit** [comment]
it's not a bot it's *Benjamin Quesnel*

*Benjamin Quesnel*, there should be an option to unsubscribe on the github issue page
