### ISSUE TITLE
Using a pen to change a sign on a wall resets their pixel shift(?), resulting in weirdness

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16117]
Note the med-sci-eng sign on the corner in this picture:
![before](http://puu.sh/nGOen/46df48ae00.png)
now see it after I've transformed it into a biohazard sign with a pen:
![after](http://puu.sh/nGOfK/400008213d.png)

another example:
![before](http://puu.sh/nGOv4/0e3f5861d7.png)
![after](http://puu.sh/nGOwo/a7a9ac2971.png)

**Comment by ChangelingRain** [comment]
Yeah whoever did these didn't ensure compatibility with all of the signs on the station

**Comment by Xhuis** [comment]
I was the one who added this - it was quite a while ago and the code is pretty out-of-date. Easy fix.
