### ISSUE TITLE
Species datums dont inherit icon stuff properly

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16125]
I made a /datum/species/lizard/ashwalker, with only the NOBREATH flag added (and obviously a new species ID) and while the lizard mutant parts (tail, frills) were visible, the main body/head was not.

However icon updates are set up for lizards is not compatible with inheritance.

**Comment by KorPhaeron** [comment]
Nevermind it is only the ash walker eggs, I must have made the mutantrace wrong

**Comment by KazeEspada** [comment]
If I am not mistaken, species icons are based on id.

**Comment by KorPhaeron** [comment]
Gross
