### ISSUE TITLE
Carpet chemical mysteriously destroy metal

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#16130]
### What is the problem?
carpet chemical overwrites the turf its on

### Why is it a problem, or what should have happened?
logically the carpet should just cover the floor

### How can the problem be reproduced?
spill Carpet reagent

[Admins]: # (If you are reporting a bug that occured AFTER you used buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by PKPenguin321** [comment]
Non issue

**Comment by xxalpha** [comment]
That's not how carpet works. Carpet is a floor type.

**Comment by duncathan** [comment]
Intended

**Comment by xxalpha** [comment]
@duncathan is there any reason it can't be an object?

**Comment by PKPenguin321** [comment]
Turf code is too shit for that afaik
