### ISSUE TITLE
Cuban Pete is Obsolete

### ISSUE THREAD

**Issue by yackemflam** [tgstation/-tg-station#16143]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?

The free bomb from the Outbomb Cuban Pete Arcade isn't a good bomb at all.

### Why is it a problem, or what should have happened?

I'm pretty sure it's supposed to be a maxcap.

### How can the problem be reproduced?

Beat the arcade, use bomb

**Comment by lzimann** [comment]
It is a minibomb sized bomb

**Comment by Supermichael777** [comment]
its an oldbombcap bomb whitch means little in our age of station crushingly powerful weapons. I dont think any atempet to buff the emag more would be apreciated

**Comment by yackemflam** [comment]
It's not even minibomb sized. It barely scuffed the floor.

**Comment by duncathan** [comment]
Feedback forum
