### ISSUE TITLE
The skateboard sprite is almost indistinguishable from a spiderling on floor

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#16144]
see title

**Comment by duncathan** [comment]
Pics

**Comment by Supermichael777** [comment]
i blame this on a lack of kick-ass paint-jobs and spider-lings having a shit sprite.  Also 
<B>GEDDOF MUH LAHWN YA DAMN PUNKS!</B>

**Comment by PKPenguin321** [comment]
>I blame this on a lack of kick-ass paint-jobs

i like this idea
