### ISSUE TITLE
Borgs get stunned by 'stuff in locker'

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#16141]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
The stuff in locker stuns people, borgs weren't set to be immune to this.
### Why is it a problem, or what should have happened?
No stun for being stuffed. (It does the unconsciousness stun like being emp'ed or flashed for the stun duration, so like 2 seconds)
### How can the problem be reproduced?
Stuff a borg in a locker. (I think its using the grab verb)

**Comment by phil235** [comment]
relevant code : https://github.com/tgstation/-tg-station/blob/e43b3a891de6b4c62599b497b80634ed265205a9/code/game/objects/structures/crates_lockers/closets.dm#L263
