### ISSUE TITLE
revolver loading doesn't have a progress bar

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#16158]
apply .38 speedloader to empty .38 revolver, get feedback that loading started, no progress bar

**Comment by hornygranny** [comment]
trying to load 357 into it also seems to fail silently, as does trying to reload an already-full revolver

**Comment by hornygranny** [comment]
the 357 also still reloads instantly

**Comment by Iamgoofball** [comment]
i think this is more of a consistency problem that the .38 doesn't load instantly, it's a speedloader

**Comment by phil235** [comment]
Relevant code: https://github.com/tgstation/-tg-station/blob/84a1192114652960a13124ac59a3eca622daa25d/code/modules/projectiles/ammunition/magazines.dm#L68

The 38 loading taking time was an intended change by https://github.com/tgstation/-tg-station/pull/15825
