### ISSUE TITLE
Lava is dark

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16157]
Lava produces no light. That mean's in the dark it's easy to step into. This make's no sense, since lava is so hot it glows.

**Comment by KorPhaeron** [comment]
No it isn't?

**Comment by Supermichael777** [comment]
lava glows in the dark. I have literally seen this with my own eyes, its not very bright compared to the sun, but it does glow.

**Comment by KorPhaeron** [comment]
No I mean lava in the game literally is not dark

**Comment by Supermichael777** [comment]
oh it might be because the lava is generated in a way that its lighting doesn't initialize.

**Comment by KazeEspada** [comment]
I will test this when I get home.
