### ISSUE TITLE
Plasma reaction ratio is too low

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#16154]
### What is the problem?
plasma reacts with far to little o2
### Why is it a problem, or what should have happened?
I'm told the mix for full consumption should be 2 mol oxygen per mol plasma.  from my math plasma is being burned at almost 4 times this rate
### How can the problem be reproduced?
Mix up a can of plasma and o2, light on fire using heater by heating to above 400k
### What revision did the problem happen on? (Helpful, but not required)
314afedfef3bc267d7c18fb896e7023d7fd4c926

**Comment by optimumtact** [comment]
Doesn't this just mean you got told wrong originally?

**Comment by duncathan** [comment]
Yeah the 2:1 ratio thing is a myth and has been for as long as I'm aware
