### ISSUE TITLE
Forcedodge projectiles go through walls with values of 1

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#16175]
[Everyone]: # (Please fill in your information on the line AFTER the header.)

### What is the problem?
Projectiles with forcedodge set to 1(or possibly higher) go through walls.
### Why is it a problem, or what should have happened?
[See this comment on the forcedodge variable, which states that forcedodge 1 goes through objects and forcedodge 2 goes through walls.](https://github.com/tgstation/-tg-station/blob/master/code/modules/projectiles/projectile.dm#L42)
### How can the problem be reproduced?
Fire xray laser through wall. Xray lasers have forcedodge 1.
### What revision did the problem happen on? (Helpful, but not required)
[If you're including this]: # (Type find-server-revision ingame to find it. "Current" isn't helpful.)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by duncathan** [comment]
Can this be reproduced with projectiles besides x-ray lasers with forcedodge 1?

**Comment by phil235** [comment]
Looking at the code, the bug is fairly obvious.
https://github.com/tgstation/-tg-station/blob/master/code/modules/projectiles/projectile.dm#L105
The question is, was it always broken?
