### ISSUE TITLE
Retrovirus can have a plasmaman as patient zero

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16182]
With predictably awful results

**Comment by PKPenguin321** [comment]
heh

**Comment by Supermichael777** [comment]
FEATURE

**Comment by octareenroon91** [comment]
Pretty sure this should classify as a bug. The retrovirus should probably obey `NOTRANSSTING` for the same reason changelings are disallowed from turning people into plasmamen.

https://github.com/tgstation/-tg-station/blob/d7f81ba4338464fb382f0721f241958179263ea5/code/modules/mob/living/carbon/human/species_types.dm#L511
```specflags = list(NOBLOOD,RADIMMUNE,NOTRANSSTING,VIRUSIMMUNE)```
