### ISSUE TITLE
Lizards can't be ops anymore

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16219]
Said by a lizard player (the unloved rock) in OOC post-round, he said he was turned into a human.

**Comment by francinum** [comment]
#16075

**Comment by Aloraydrel** [comment]
FEATURE

**Comment by Zilenan91** [comment]
Kor shouldn't make misleading pr titles and shove stealth changes through

**Comment by KorPhaeron** [comment]
I said exactly what it did in the PR body, and that I could fix it an alternate way if someone wanted me to.

**Comment by Zilenan91** [comment]
Not in the title though, if the title says it's fixing something, the pr should be fixing what it says it's fixing. You snuck in the no lizard ops thing in the pr body to as to not, "bogged down in the ensuing argument."

I mean I'm not truly angry about this or anything it'd just be nice if your pr titles were transparent about what they're doing rather than not.

**Comment by PKPenguin321** [comment]
cry me a river

**Comment by duncathan** [comment]
get over yourself

**Comment by Zilenan91** [comment]
> I mean I'm not truly angry about this or anything it'd just be nice if your pr titles were transparent about what they're doing rather than not.
