### ISSUE TITLE
It's hilariously easy to walk off a cliff

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16223]
### What is the problem?
Cliffs just let you run/walk right off them without any sort of hesitation.

### Why is it a problem, or what should have happened?
In the real world humans actually have a lot of instinctive protections against inadvertently walking off cliffs, in spessmen it's as easy as holding a button a few deciseconds too long. This is really rough considering the penalty for falling off a cliff is instant death with no chance for corpse recovery.

### How can the problem be reproduced?
Take a long walk off a short cliff.

**Comment by kevinz000** [comment]
Where do we have cliffs?

**Comment by KazeEspada** [comment]
This gives me an idea for lava too

**Comment by Incoming5643** [comment]
@kevinz000 lavaland, moreso now that killing the spines create pits

**Comment by MMMiracles** [comment]
Probably should make it so walking causes you to stop at the turf, I really doubt you could stop yourself from falling if you're running straight into it.

Also make it so standing next to a cliff with clumsiness has a chance for the person to slip into it, because honk.

**Comment by Ausops** [comment]
well maybe spessmens should take a hint from their long lost ancestor, the human race, and not run while near chasms. You know, walk. That long lost art of moving your legs slowly as a conscious choice, not as a (somewhat rare) automatic reflex only triggered by the sight of wet floor tiles.

**Comment by Lumipharon** [comment]
Pretty much. If you're running at break neck speed next to a gaping chasm then it's your fault for falling in.

**Comment by PKPenguin321** [comment]
lag tho?

**Comment by YakumoChen** [comment]
treat it like a wall?

**Comment by Supermichael777** [comment]
needs an willy coyote style animation

**Comment by ShadowDeath6** [comment]
Lifeweb cliff mechanics, make it so you can break your legs and live so you suffer forever in the pit

**Comment by coiax** [comment]
Proposed ingame solution to this in #17053

**Comment by Dorsisdwarf** [comment]
Fixesd
