### ISSUE TITLE
Revenant issue

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16222]
If a locker is closed on a revenant their camera stops updating until they log out and back in

**Comment by ChangelingRain** [comment]
Happens for anything with incorporeal move enabled

**Comment by phil235** [comment]
The revenant is moved inside the closet.

**Comment by ChangelingRain** [comment]
It'd happen for anything with incorporeal move enabled though, wouldn't it?

**Comment by phil235** [comment]
yeah
