### ISSUE TITLE
Fly people don't get nutriment from their vomit

### ISSUE THREAD

**Issue by ATDoop** [tgstation/-tg-station#16235]
### What is the problem?
Fly people aren't getting nutriment from their vomit
### Why is it a problem, or what should have happened?
Fly people get hungry, but can never recover
### How can the problem be reproduced?
Wait until you're hungry and try to eat your vomit.
### What revision did the problem happen on? (Helpful, but not required)
16210

**Comment by Zilenan91** [comment]
dupe
