### ISSUE TITLE
reactive tele armor ignores bullets

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16236]
1. Wear reactive teleport armor
2. Get shot by detective's revolver
3. Warp
4. Notice that you are not stunned or damaged in any way

**Comment by Zilenan91** [comment]
Reactive telearmor is balanced and RnD is a shining exemplar of well designed gameplay elements

**Comment by YakumoChen** [comment]
the warp completely negates any damage projectiles would have on you

**Comment by PKPenguin321** [comment]
what the fuck why

**Comment by YakumoChen** [comment]
Because it warps before the projectile actually hits you, its in the message the armor puts out

**Comment by PKPenguin321** [comment]
but why

**Comment by Dorsisdwarf** [comment]
Because thats the point of the armor are you fucking kidding me.

it teleports you away instead of getting hit jesus.

**Comment by PKPenguin321** [comment]
why not apply damage/stuns then teleport? I could have sworn that was how it was supposed to work

**Comment by Aloraydrel** [comment]
is this a meme?

**Comment by PKPenguin321** [comment]
no but reactive armor is jesus christ

**Comment by Dorsisdwarf** [comment]
No, it's not.

Reactive Teleport Armor teleports you away from harm instead of reducing the damage you take.
