### ISSUE TITLE
Tablecrafting recipe for improvised shotguns lists a pipe as a "fitting"

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16233]
I get that it's a pipe *fitting* but this has confused numerous people, myself included. I assume this is because in the recipe it's pathed as the parent pipe object instead of a normal straight pipe or whatever.

**Comment by Zilenan91** [comment]
Everything that uses pipes in the tablecraft recipe uses fitting, pneumatic cannons notably.

**Comment by duncathan** [comment]
```
/obj/item/pipe
    name = "pipe fitting"
```
not a bug
