### ISSUE TITLE
Ashwalker nests should be at the bottom of the orbit menu

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16240]
Like all the other lavaland ghost spawners are so ghosts don't have to aimlessly search everywhere for the tendril with the eggs on it.

**Comment by KorPhaeron** [comment]
It isn't a spawner, it's a mob that creates spawners

**Comment by KazeEspada** [comment]
Ashwalker eggs are the spawner.

**Comment by Zilenan91** [comment]
Yeah but it's hard actually finding the eggs when you can't find the nest.

**Comment by KorPhaeron** [comment]
The nests are in the orbit menu though. If there are no eggs, you can't spawn anyway
