### ISSUE TITLE
Can't open lockers with items in your active hand... again.

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#16244]
### What is the problem?
If you click on a closed locker with something in your active hand, nothing happens.

### Why is it a problem, or what should have happened?
The locker used to open when you did this. At some point this bug occurred, but it got fixed. Dunno why it's happened again, but it's been in for a bit.

### How can the problem be reproduced?
Try open a locker with something in your active hand.

**Comment by phil235** [comment]
I can only reproduce it with an unlit welder.

**Comment by Lumipharon** [comment]
Really? I was having a cry about this just yesterday with all sorts of items.

**Comment by PKPenguin321** [comment]
yeah i noticed this too

**Comment by phil235** [comment]
Which items?

**Comment by PKPenguin321** [comment]
Any item at all, as long as it's not an ID or a welder, could be used on a closed locker with no lock to open it.

**Comment by phil235** [comment]
Oh, I got confused, I thought you the issue was about locking/unlocking by clicking the locker with an item, my bad.

**Comment by Shad0vvs** [comment]
Happens to borgs with an active item as well, we're forced to right click to open, which shouldn't be the case. (and that horrible right click lag)
