### ISSUE TITLE
Plants mutate even with ezy nutriment

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#16242]
### What is the problem?
When plants fully mature, they under go a random mutation, even when fertillized with ezy nutriment.

### Why is it a problem, or what should have happened?
The harvest one and left4zed are both supposed to cause mutations like this, but ezy nutriment isn't. Because it does, it means it's impossible to maintain your carefully cultivated mutations (100 potency etc) since you can't stop it from mutating.

### How can the problem be reproduced?
Grow plants.

This didn't used to happen - I assume the bug occurred after one of the botany refactors that has happened semi recently?

**Comment by Notamaniac** [comment]
Wasn't it that ez nutriment caused minor mutations, left 4 zed doubled the mutations but only let you get one yield, and robust harvest doubled the yield but stopped any mutations?

**Comment by Grazyn** [comment]
Not a bug. From the wiki:
E-Z-Nutrient: Makes your plant mutate once every time it's ready for harvesting, and has no effect on the yield.
Left 4 Zed: Makes your plant mutate twice, but it will only produce one plant at most - if the plant's yield is 0, then nothing is produced! You'll have to use another fertilizer to harvest the normal yield of the plant.
Robust Harvest: Makes your plant produce twice as much, and will never mutate it. Useful if you already have good stats, are using unstable mutagen and don't want random mutations to interfere, or simply don't want to bother with mutating at all.

**Comment by newfren** [comment]
Lumi you have your fertilizers backwards lmao

Robust Harvest doubles yield and does nothing to stats that's the one you want.

E-Z Nutriment is literal trash that has no purpose

Left-4-Zed can mutate plant species if you are without mutagen and also hate yourself.

**Comment by Lumipharon** [comment]
Ok maybe I'm insane, but I swear it wasn't like this before.
Ignore me and close this if I'm just retarded.

**Comment by MrStonedOne** [comment]
just kill the bad mutations like a good like intelligent designer.

**Comment by Man-Shroom-** [comment]
mutations intended

realistic simulation of evolution
