### ISSUE TITLE
Venus Human Traps layer under kudzu

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16253]

**Comment by KazeEspada** [comment]
IF YOU CANT SEE ONE OF THESE TECHNICOLOR PIECES OF GARBAGE YOU DESERVE TO GET THROWN AGAINST A WALL UNTIL YOU SUICIDE.

**Comment by Zilenan91** [comment]
They are literally invisible under some mutations, particularly hardened and the darker ones.

**Comment by KorPhaeron** [comment]
I got attacked by one earlier in thick kudzu, was more or less invisible. Might be a feature though

**Comment by Zilenan91** [comment]
It probably shouldn't because of how much damage they do and how rapidly they can spawn if the kudzu that spawns them spreads out
