### ISSUE TITLE
new inventory close button

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#16268]
Its a little too small
make it slightly larger

**Comment by phil235** [comment]
@kingofkosmos

**Comment by kingofkosmos** [comment]
I'm not sure what people exactly want. How much bigger? Is the button otherwise ok, or should we get a proper spriter to do it?

**Comment by Bawhoppen** [comment]
yea button looks fine just make it the size of the old x 
being hard to click is a problem alot of sprites in this game have, eswords being a good example

**Comment by KorPhaeron** [comment]
Feedback forums

**Comment by duncathan** [comment]
I TOLD YOU TO CHANGE IT SO MANY TIMES AAAAAAAAAAA
