### ISSUE TITLE
Catsplosion STILL happening.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16272]
@Incoming5643 
![cat](http://puu.sh/nPfod/499dd298af.jpg)
Cmo literally drowned in pussy

**Comment by optimumtact** [comment]
We're pretty sure this is a byond bug causing cat's to be spawned

**Comment by Incoming5643** [comment]
I've got another attempt in me

**Comment by Ricotez** [comment]
we need a new label for this called "cat-astrophe"
