### ISSUE TITLE
Gibtonite visible message is wrong

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16281]
Observers see the message

"**You** use the gimped advanced mining scanner of the sea -2 to locate where to cut off the chain reaction and attempt to stop it..."

Probably should not say I stopped the reaction if I'm merely watching.

Reminder to myself to fix at some point

**Comment by phil235** [comment]
I don't understand what the issue is actually refering to.

**Comment by ShadowDeath6** [comment]
He's saying that it says "you" to anybody watching, implying that the ghost used the mining scanner to stop gibtonite.

**Comment by phil235** [comment]
Oh, right, it's much clearer now.
