### ISSUE TITLE
Stamina damage is permastunning people

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/-tg-station#16299]
Probably due to the new health stuff

**Comment by tytynguyen** [comment]
A temporary fix for this in game is to rest and get back up again(Just as it says you need to when analyzing.)

**Comment by phil235** [comment]
I can't do anything without more details.....
This is why we need the issue template :tired_face:

**Comment by KorPhaeron** [comment]
@phil235 

HG lowered the starting health to 50, and death to -50

I don't know if it counts as a bug if it's the result of admins messing around

**Comment by Dorsisdwarf** [comment]
the maniac

**Comment by GunHog** [comment]
Perhaps HG should not be touching things without **testing** it first!

**Comment by duncathan** [comment]
It IS a fucking **test** @GunHog holy shit
This bold **testing** meme you're doing is as annoying as goofball's giant text

**Comment by Iamgoofball** [comment]
# like this?
