### ISSUE TITLE
The blackbox can be used to bypass check antagonists

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16292]
The blackbox contains stat information on what kinds of items were bought that round. Using this information an admin can use the blackbox to check the round type WITHOUT using the antag panel.

Viewing variables is not logged, only changing them.

**Comment by KorPhaeron** [comment]
Admins can also open the player panel without logging (which shows all antags)

Admins can also spawn themselves items which gives no message, so its unlikely it will ever be seen.

Admins can toggle build mode/AI interaction, which gives a message, but leaves little indication of what they actually did.

Admins can view vars on anything without it logging.

Admins can have deadchat on while alive, and this saves between rounds.

And so on. Admins should just deadmin before the round starts if they're going to play seriously (anything other than wandering in circles as an assistant shouting stupid shit on the radio).

**Comment by Dorsisdwarf** [comment]
Unsurprisingly, admins have a lot of ways of viewing game data, and a disinclination to want even more bold blue messages popping up.

Admins shouldn't really be playing jobs where this is an issue without deadminning anyway.

**Comment by YotaXP** [comment]
Consider auto-deadmining when rolling certain jobs?  Or at the very least, bring up a prompt.

**Comment by Jordie0608** [comment]
I think it's fair to say this is a personnel issue of the admins rather than a code concern and either way not one that can be solved without a frankly obstructive level of logging; we've got thus far without major issues from this.
