### ISSUE TITLE
Flypeople and Starvation

### ISSUE THREAD

**Issue by Nrsw** [tgstation/-tg-station#16319]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

So Flypeople have recently been added, and in order to eat they have to vomit.  The problem is the act of vomiting causes more of a loss of nutrition than slurping the vomit up.  This means flypeople will end up permanently starved.

**Comment by Zilenan91** [comment]
@LanCartwright

**Comment by PKPenguin321** [comment]
dupe
