### ISSUE TITLE
PDA Atmospheric scanner is casting all percentages to int

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/-tg-station#16329]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Plasma is dangerous at values lower than 0.5% however the Atmospheric scanner function on pdas doesn't display decimals, making it impossible to ensure that a contaminated area is truly plasma free.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by KazeEspada** [comment]
Also analyzers too.

**Comment by duncathan** [comment]
They're rounded intentionally. Just need to change the degree to which they're rounded.
