### ISSUE TITLE
Posi brains can see ghosts?

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#16332]
Player was reporting that he was seeing ghosts as a posi-brain. Mainly when he was in the AI core he was able to see ghosts orbiting him.

**Comment by KorPhaeron** [comment]
This happened to me as well

**Comment by Aloraydrel** [comment]
I tested it in the thunderdome and I was able to see ghosts

**Comment by duncathan** [comment]
This isn't just posibrains. Earlier today on Basil humans were seeing ghosts too. For some reason ghosts have `invisibility = 0`.
To fix the issue in game execute this SDQL2 call:
`UPDATE /mob/dead/observer SET invisibility=100`
