### ISSUE TITLE
Shaft miners should probably be excluded from rev head

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16352]
The head revolutionaries were:
ckey was Nonie-Larson the Shaft Miner and survived while fleeing the station

30 second rev round.

**Comment by Incoming5643** [comment]
label: Lack of common sense

**Comment by Zilenan91** [comment]
Gloom? If it's not it's his own fault if he decided to leave the zlevel.

**Comment by Shadowlight213** [comment]
Bagil. But it seems counterintuitive that a job meant for off station stuff can lose for doing their job.

**Comment by Zilenan91** [comment]
Then they shouldn't do their job.

**Comment by Incoming5643** [comment]
It's impossible to miss the blue R. Either the guy had no idea what revolution mode was, wasn't thinking at all, or just did it for laughs.

**Comment by Zilenan91** [comment]
Nah Nonie is an old player. He should've known what revolution was.

**Comment by Cheridan** [comment]
Not a bug. Just don't go off z-level as a revhead.

**Comment by Shadowlight213** [comment]
Valid point I guess.
Could snowflake it and have a popup that occurs specifically for rev head shaft miners saying "DON'T GO OFF MINING!"
