### ISSUE TITLE
Bug: hydraulic crowbar (borg crowbar) unable to be used for surgery

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#16360]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
The hydraulic crowbar cannot be used in surgery when a normal crowbar would be able to do so.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Tytynguyen** [comment]
I just tested this with organ manipulation and it worked just fine. What surgery did it fail with?

**Comment by coiax** [comment]
I think it was organ manipulation targeting the head of a plasmaman, I am however suddenly worried that I might have mistakenly thought I could use a crowbar when I wouldn't have been able to. If you've had no problems, then I guess I was in player error.

**Comment by Core0verload** [comment]
Looks like a player error with action intents or such. Borg crowbar is a simple subtype of crowbar without any changes in code, there is no reason for a specific fail.

**Comment by Cheridan** [comment]
Yeah, PEBKAC probably
