### ISSUE TITLE
TK cannot be used on Doors with Access

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#16371]
Simply put, when you have TK, you can open/close doors, from afar, if they do not have any access on them.

That said, if they do have access on them, you cannot utilize TK on them; this seems highly inconsistent; it would see that you *should* be able to use TK on doors and it should check the access which you posses.

**Comment by ChangelingRain** [comment]
This doesn't sound like a bug; if you're not next to the door, how can it read your ID card?

**Comment by optimumtact** [comment]
http://tvtropes.org/pmwiki/pmwiki.php/Main/DevelopersForesight?from=Main.TheDevTeamThinksOfEverything

**Comment by ChangelingRain** [comment]
YEAH LET'S SAY THIS IS INTENDED
