### ISSUE TITLE
The bartender sleeper on the beach away mission/lavaland ruin is a roundstart one

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16379]
Meaning it spawns a catatonic bartender instead of waiting for a ghost.

Will fix after mapping freeze.

**Comment by Lumipharon** [comment]
Also Kor, Yesterday I noticed this bug... because lavaland had THREE DIFFERENCE BEACH INSTANCES.

Like, wew, there was as much beach as there was lava.

**Comment by KazeEspada** [comment]
Beach2 has this fixed.
