### ISSUE TITLE
Hearty Punch cannot be made

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16374]
15 units of Absinthe
15 units of Brave Bull
4 units of Whiskey Cola
15 units of Syndicate Bomb
It is a tiny item.

It's supposed to take 5 absinthe, 5 brave bull, and 5 syndi bomb for 1 unit of Hearty Punch.

**Comment by KazeEspada** [comment]
Use a welder on it

**Comment by ChangelingRain** [comment]
It needs to be heated.

**Comment by Zilenan91** [comment]
Oh wow really? It didn't say that anywhere in the pr

**Comment by PKPenguin321** [comment]
It did

**Comment by Zilenan91** [comment]
Actually would a zippo be enough heat to make Hearty Punch?

**Comment by PKPenguin321** [comment]
Probably
