### ISSUE TITLE
Lava land golems can't use the mining equipment vendor

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#16397]
Since they start with no ID and they can't transfer points from the ORM

**Comment by phil235** [comment]
what the fuck is a mining golem?

**Comment by Aloraydrel** [comment]
Golems in lavaland should of changed it actually

**Comment by optimumtact** [comment]
Golems aren't supposed to mine anyway?

**Comment by ChangelingRain** [comment]
The lavaland golems are tho.

**Comment by RandomMarine** [comment]
https://github.com/tgstation/-tg-station/pull/16385

**Comment by coiax** [comment]
Don't know if this can be fixed though while the map freeze is in effect, without changing how the ORM and Points Redeeming system works.

**Comment by KorPhaeron** [comment]
I think this was fixed
