### ISSUE TITLE
You can enter a already-used golem shell and spawn in nullspace

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#16395]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
If someone has already entered a golem shell, trying to enter it with the ghost button will place you in nullspace instead of failing.
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by KorPhaeron** [comment]
Pretty sure this is a dupe

**Comment by ChangelingRain** [comment]
Nope, not a dupe.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/-tg-station/issues/16037

To be fair I had to search several times to find it

**Comment by ChangelingRain** [comment]
This isn't quite the same issue because it can happen at any point after the golem shell is taken and the alert exists but yes same cause

**Comment by KorPhaeron** [comment]
Fixed
