### ISSUE TITLE
Bug: Atmospherics - gas leaks through reinforced directional windows.

### ISSUE THREAD

**Issue by Theomund** [tgstation/-tg-station#16415]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Problem Description:** In building a gas chamber, the gas leaked through reinforced windows, even though the windows were completely sealed. I consulted an admin about this, but to no avail, no solution was reached.

**What did you expect to happen:** An evenly-distributed mixture of N2O in my chamber, without leaks.

**What happened instead:** A massive gas leak prompted a shuttle call; the gas extended way beyond range of the windows.

Image: http://imgur.com/fcg6JCQ

**Why is this bad/What are the consequences:** This affects unique designs utilizing atmospherics, prohibiting directional windows from being used.

**Steps to reproduce the problem:**
1. Build a gas chamber, akin to this: http://imgur.com/4UWWgVt
2. Using the air alarm, set the pressure output for vents to about 500 kPa.
3. Voila - a massive air leak, causing a hazard to the station.

**Server:** Sybil

**Revision:** _e5b081ea88d0a38a834b53cd712fc6fec318fd4f_ 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):** Building a gas chamber; testing atmospheric capabilities.

**Comment by Shad0vvs** [comment]
I believe a specific type of airlock is required to contain atmospherics, but I don't remember which.

**Comment by xxalpha** [comment]
Are those windows properly secured?

**Comment by Theomund** [comment]
Yes, I made sure they were properly secured (Screwdriver-Crowbar-Screwdriver).
