### ISSUE TITLE
New Hybrid Taser's laser mode displays no sprite

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/-tg-station#16416]
>Hold your taser
>Swap to "kill" mode
>Watch as it becomes invisible

**Comment by PKPenguin321** [comment]
/>TESTED
/>CODE

**Comment by CPTANT** [comment]
hmmm, odd must be a result of the merge conflict in the icons file.

**Comment by PKPenguin321** [comment]
Yeah, gun sprites are a serious bitch, especially when they have multiple firing modes. There is practically no documentation on it to boot.
