### ISSUE TITLE
the new ghost preferences don't save between rounds from the preferences menu

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16427]
@Ricotez 

It defaults back to the haired ghosts no matter what every round

REEEEEEEEEEEEEE

**Comment by Ricotez** [comment]
wait what? I tested this, are you absolutely sure?

**Comment by Incoming5643** [comment]
it didn't seem to save from the verb in game on the preference tab, maybe it does from the preference screen in pregame?

**Comment by Ricotez** [comment]
ah that would be it yeah, there are no calls to save_preferences() in the toggles

prefs save just fine from the setup window until I write a fix and it gets merged
