### ISSUE TITLE
LEAVE CLEANBOT ALONE (Bee Issues)

### ISSUE THREAD

**Issue by stapler2025** [tgstation/-tg-station#16420]
What's Wrong:  ![CLEANBOT DINDU NUFFIN](http://i.imgur.com/9sj7LrR.png) CLEANBOT DINDU NUFFIN

Real talk:  Bee's seem to enjoy targeting and following around simple machines (cleanbot, beepsky etc).

How to fix:  Probably make them not select machines as their target?

**Comment by RemieRichards** [comment]
not a bug, bees hate everything.

**Comment by stapler2025** [comment]
I guess I could state that there was no "The bee stings CLEANBRO", it was just following it around acting like it pays rent.

**Comment by RemieRichards** [comment]
That might need looking into, but if it's an issue it's probably not bee-specific as they just use mostly regular hostile AI.

**Comment by Incoming5643** [comment]
bees really need to not enjoy attacking people so much, they will completely stop ANYTHING they're doing and just angry try to path to you if there's literally anyone around not in a beesuit/plant person

**Comment by Durkel** [comment]
That's because bees are asshole. Fuck bees

**Comment by PKPenguin321** [comment]
it's hip to fuck bees

**Comment by GunHog** [comment]
They are bees, not genetically engineered military wasps! Bots seem to take damage from a lot of things that should not bother them in the slightest, such as hot air or bee stings. They are made of metal, not weak human flesh.

**Comment by KazeEspada** [comment]
They are infact genetically engineered wasp bees. DONT BELIEVE REMIES LIES.
