### ISSUE TITLE
Pills have a delay for self application

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#16433]
[Here](https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/reagent_containers/pill.dm#L12) it gives 0 delay for self applications(which is called in line 32 in the same file), but when you try to swallow a pill(given by yourself) you get a wait time.

**Comment by Supermichael777** [comment]
FUUUUUUUUUCCCCCKKKKKK

**Comment by phil235** [comment]
This is fixed
