### ISSUE TITLE
[April Fools Branch] The crit hallucination will leave you with unrecoverable stamina damage

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16443]
@lzimann 
stamina damage doesn't auto decrease over time leaving you with a crit health icon and slowdown 2

**Comment by KorPhaeron** [comment]
This sounds plain unpleasant, not even amusing

**Comment by PKPenguin321** [comment]
the whole "no stuns on april 1st" thing wasnt that funny to begin with tbh

**Comment by Incoming5643** [comment]
Fix or remove before the first please
