### ISSUE TITLE
Nanomachine reagent bees don't work properly?

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#16455]
Last night a traitor traded his tcs for 15u of nano machines in which he used it on bees. Bees were stinging people but nobody was being infected with nano machines.

**Comment by Incoming5643** [comment]
it might not have been injecting enough nanomachines to actually infect people

**Comment by PKPenguin321** [comment]
He did it wrong anyways. The strat is to inject them into a monkey then capture its blood and replicating the virus from it.

**Comment by KazeEspada** [comment]
Bees dont take viruses from blood.

**Comment by PKPenguin321** [comment]
lame

**Comment by coiax** [comment]
The nanites reagent is [here] (https://github.com/tgstation/-tg-station/blob/cc3ea6ddbb34f61c35308fdf4d6673fe6b3853a6/code/modules/reagents/chemistry/reagents/other_reagents.dm#L770)

If bees are supposed to transfer the reagents with method INJECT then this is some sort of bug. Unless bees use a bee-specific method?

**Comment by LatD** [comment]
Bluespace transferring nanomachines some days ago. Seems like the only way for the nanomachines to turn into the virus is when the nanomachines go through mouth, meaning that a pill must be swallowed, food eaten or by drinking. Even injecting nanomachines with a syringe, syringe gun or applying a patch does not start the virus. 
And the virus also cannot be transfered through blood. So having a monkey with the virus and injecting its blood does not give the virus.

**Comment by Aloraydrel** [comment]
I just tested it this morning and injecting it via syringe gave me the virus

**Comment by LatD** [comment]
Then I don't know what's going on. I haven't tested it myself but was talking with Bluespace about it while he was doing testing.

**Comment by Incoming5643** [comment]
The bees might not be specifying that they're adding reagents via injection

**Comment by Shadowlight213** [comment]
This has been a bug for ages. I encountered it a long time ago with mech syringes.
Basically, yeah the nanomachines only actually have an effect if they are ingested. Syringes seem to override it if they are injected by hand for some reason.

**Comment by phil235** [comment]
>If bees are supposed to transfer the reagents with method INJECT then this is some sort of bug. Unless bees use a bee-specific method?

DING DING DING DING! We have a winner!
https://github.com/tgstation/-tg-station/blob/cc3ea6ddbb34f61c35308fdf4d6673fe6b3853a6/code/modules/mob/living/simple_animal/hostile/bees.dm#L225
