### ISSUE TITLE
Aparies produce infinite numbers of queen bees instontaniously

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#16462]
Which means getting rid of say nano-machine bees is impossible.

**Comment by PKPenguin321** [comment]
@RemieRichards it's hip to fuck bees

**Comment by RemieRichards** [comment]
Well this is objectively false, Apiaries do not create queen bees.

**Comment by Dorsisdwarf** [comment]
Not resolvable, apparently
