### ISSUE TITLE
You can fall off the shuttle into the necropolis of lava land.

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16469]
Dick Longson fell off the shuttle and suddenly spawned within a wall of the necropolis of lavaland.

**Comment by KorPhaeron** [comment]
Thats because the transit turfs dont actually trigger Z transitions, they just chuck you at a random Z level

**Comment by Jordie0608** [comment]
Actually it's because they pick a z level between SPACEMIN (3) and SPACEMAX (7), and lavaland is 5

**Comment by Core0verload** [comment]
Solution: revert Lavaland.
