### ISSUE TITLE
Napalm and Hooch require the same reagents

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16498]
Hooch: 1 unit sugar, 2 units ethanol, 1 unit welding fuel, plus enzyme.

Napalm: 1 unit sugar, 1 unit ethanol, 1 unit welding fuel.

If you try to make the mix first without the enzyme it will make napalm and this is really confusing.

**Comment by optimumtact** [comment]
so they don't require the same mix then?

**Comment by lordpidey** [comment]
Honestly, the best solution sounds like turning Hooch's recipe into 3 units napalm, 1 unit ethanol.

**Comment by KazeEspada** [comment]
Plus enzyme as a catalsyt.
