### ISSUE TITLE
You can use a guardian creation thing multiple times

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16490]
1. Player got two in a surplus kit. Used both.

2. One player got two from the same one. I assume they just spam clicked or something.

I assume hasparasites isn't tested (though it'd be a massive fucking pain to test by yourself to be fair)

**Comment by ChangelingRain** [comment]
It was tested, but there was no check after they selected a parasite type, so if you opened two selection windows you'd be able to select both parasites without getting stopped.

**Comment by ChangelingRain** [comment]
>not a bug tag
>was a bug

???
