### ISSUE TITLE
Librarians do not have access to their maint door.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/-tg-station#16506]
Probably just an oversight

**Comment by duncathan** [comment]
which map?

**Comment by TechnoAlchemisto** [comment]
woops, box.

**Comment by PKPenguin321** [comment]
afaik this is intentional but I wouldn't mind giving librarians a bit of maint

**Comment by swankcookie** [comment]
I'll throw up a PR for it

**Comment by swankcookie** [comment]
Intententional. request to change denied by @Cheridan .

**Comment by duncathan** [comment]
k
