### ISSUE TITLE
NT employment contracts dont appere round start

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#16513]
Probably because their generation occures befor players actualy exist

**Comment by duncathan** [comment]
...employment contracts? what?

**Comment by Jordie0608** [comment]
Likely referencing a #16501 test merge

**Comment by lordpidey** [comment]
To help me track down this bug:  Was it producing blank contracts, or not?

**Comment by Supermichael777** [comment]
it was not producing contracts for round start employees
