### ISSUE TITLE
Locker stuffing

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#16520]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
If you begin to stuff someone into a locker, and they move or flee or whatever, they get stunned where they ran to no matter how far once the stuffing completes.

**Comment by phil235** [comment]
probably because the stuffing's do_after() doesn't check if the target mob has moved.
