### ISSUE TITLE
Gibtonite explosions cause vacuum on lavaland

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16524]
>shoot gibtonite
>wait
>enjoy a weird atmos anomaly and get burned by the cold

**Comment by duncathan** [comment]
hmm

**Comment by coiax** [comment]
puny humans, being affected by the temperature, and needing to "breathe"

**Comment by lzimann** [comment]
it happens with hyper KA aswell...

**Comment by duncathan** [comment]
dupe
