### ISSUE TITLE
Free Golems are not being named properly

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16547]
>spawn in free golem sleeper
>name is Free Golem
>everyone else is named Free Golem
>also have underwear on for some reason

@coiax

**Comment by coiax** [comment]
I'm on it.

**Comment by coiax** [comment]
Kor, I'm on commit f145c0bb7971f83ffc1f2da9bfbef3e9eb4293c6 and I have no such error with my own local server instance, spawning in a /obj/effect/mob_spawn/human/golem/adamantine and activating that as a ghost. No underwear, a proper new-style name.

Is this on the main server? The one running april fools?

**Comment by Cheridan** [comment]
lingerie golems are my fetish

**Comment by coiax** [comment]
Pretty sure this was a server config issue, and can be closed, cuz it's fixed.
