### ISSUE TITLE
all of my slippery slopes are coming true

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#16552]
>lizards
>i said they would be made player allowed and invite lots of creepy furries to the game
>they said it would be admin only
>look who was right

>cat people
>i said they would be made player allowed and invite even more creepy furries to the game
>they said it would be admin only
>look who was right

>re-adding trekchem recipes
>i said they would use it as an excuse to remove goonchem elements and reagents and to rebuff DD back to its original OP level
>they said no chems would be removed and that DD wouldnt get a buff
>guess who's gonna be right

>ponies
>i said people would start trying to actually balance it and try and get it added as normal, also it breaks copyright
>they said it was april fools only forever, they pulled the xeno card
>guess who's gonna be right

:ok_hand:

**Comment by TrustyGun** [comment]
> adding ponies

beginning of end, boys.

**Comment by PKPenguin321** [comment]
You're wrong on the trekchems one though, removing the goofchems would be retarded
DD buff I wouldn't mind considering it literally requires omnizine to make and is a straight downgrade

**Comment by Cheridan** [comment]
working as intended
