### ISSUE TITLE
VV-ing the chattyness var on SNPCs does not appear to have an effect

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#16572]
@sawu-tg 

No matter what I change the chattyness var on an SNPC to, even 100 or 0, there appears to be no appreciable effect on how often they speak. This is an issue because sometimes you want to spawn SNPCs but not have them spam chat constantly.

**Comment by sawu-tg** [comment]
This is because it's an if/else not an if/elseif.

It's an easy fix and it'll be in the next SNPC patch.

**Comment by Shadowlight213** [comment]
Workaround is to vv their functions list and remove chatter.
