### ISSUE TITLE
Intent selection now goes clockwise rather than selectively

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16585]
So instead of being able to change your intent from harm to disarm or disarm to help your intent moves clockwise through the intent thing rather than being specific. What caused this change, and was it even intentional because this is shit, this isn't 2014 anymore.

**Comment by ChangelingRain** [comment]
It's a preference, 'Toggle Intent Selection Style' in the prefs tab, check if you accidentally disabled it

**Comment by Zilenan91** [comment]
I don't even know why that's a preference, it's specifically inferior.
