### ISSUE TITLE
Hugging people reveals their gender

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#16597]
Repro:

1. Wear disguise that hides your gender
2. Be hugged
3. Hug text clearly states that the hug makes "him" or "her" feel better

Sure, you could rationalize this by saying you're touching their chest, but a true spessmen does not know the difference between manboobs and regular ones.

**Comment by Supermichael777** [comment]
Captain hugs space ninja
![hugs in ss13](http://static.tvtropes.org/pmwiki/pub/images/Crotch_Grab_2184.jpg)

**Comment by Shapsy** [comment]
I don't think the /His macro respects disguises, examine code has special checks in place for hiding gender

**Comment by PKPenguin321** [comment]
could just change the /his to them idk
