### ISSUE TITLE
Metastation kitchen has some inconsistencies

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#16596]
The airlock leading to hydroponics in the kitchen (labelled "Service Door") can be accessed by the chef, but the airlock from the public room cannot be opened by people with kitchen access.
There is also no locker with chef clothing.

**Comment by Metacide** [comment]
Will look into this.

**Comment by Metacide** [comment]
Ok, had a look at this. The service door thing is as intended, but I've added a chef's locker in place of the chef's crate in there at the moment.
