### ISSUE TITLE
Being borged counts as surviving for die a glorious death.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#16590]
I was borged after suicide bombing my target. Both our brains were thrown in the blast and we were both borged. However, he counted as dead for my objective, while my "die glorious death" was counted as failure.

Picture for reference : http://i.imgur.com/xP7OhV0.png

**Comment by ChangelingRain** [comment]
I'm gonna claim this as technically not a bug because *you aren't dead now, are you?*

**Comment by RandomMarine** [comment]
Being borged isn't very glorious, is it?

**Comment by TheRealGLH** [comment]
Killing yourself also counts as a "glorious death", that's even less glorious than being borged.

**Comment by Durkel** [comment]
Alright, let me ask you this then. If I blow myself up in a glorious explosion that kills me and my target, but both our brains remain intact, how the fuck am I supposed to prevent this?

**Comment by Anonmare** [comment]
Don't re-enter your corpse when it gets put in an MMI?

**Comment by ChangelingRain** [comment]
Fuck up fighting carp and get killed?

**Comment by Supermichael777** [comment]
valid-hunt until you get killed permanently?

**Comment by Cheridan** [comment]
Not a bug. What @RandomMarine said.

**Comment by Durkel** [comment]
Hol up hol up. Hitting yourself to death, dying to shocked random grille, or just passing out because your o2 tank is empty is ok for a glorious death, but dying in fucking massive explosion and having your remaining brain borged isn't?

You can't control if your brain is throw from a gibbing, and If I go out taking six others with me, and my brain happens to survive the explosion from something I can't really control isn't glorious? Spamming shitty memes asides I shouldn't have to find some awful reason to get myself killed as a borg, or just out right deny the borging.

**Comment by duncathan** [comment]
You could've ghosted though?

**Comment by coiax** [comment]
This is a bit of a weird consistency issue.

If you have an assassinate objective, a person being a cyborg is fine, they count as dead.
But if you have die gloriously, which is just an assassination objective targeting yourself, then being a cyborg means you count as alive?
