### ISSUE TITLE
Security holo barrier projector counts barriers put up wrongly

### ISSUE THREAD

**Issue by CosmicScientist** [tgstation/-tg-station#16602]
When trying to put up a new one after the previous ones were all or mostly destroyed, I was informed that I had reached my limit. I had to use it in hand to "remove" all previous barriers before I could start using it again.

My guess is it just doesn't keep track of the barriers or barriers don't tell it when they're destroyed.

**Comment by ChangelingRain** [comment]
duplicate of #15910

**Comment by CosmicScientist** [comment]
Sorry!
