### ISSUE TITLE
Energy Guns can't recharge when all the ammo is used up

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16617]

**Comment by xxalpha** [comment]
Is it possible to describe this in more detail? I was playing yesterday and this was working fine, unless something related to energy guns / rechargers got merged after that.

**Comment by Aloraydrel** [comment]
Are you sure the charger had power in it?

**Comment by Zilenan91** [comment]
Completely, I even checked the APC in the room. It was the egun that spawns in the HoP's locker, I'd used all the shots on the lethal setting to shoot windows, and tried to charge it in the Medbay sec checkpoint.

**Comment by KorPhaeron** [comment]
Sounds made up, works fine for me. Maybe you gun got blown up/had the cell damaged
