### ISSUE TITLE
Space is pressurized and inconstant

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#16643]
After #16026 space now has a lot of pressure, and it is not constant, some turfs have 10k pressure, some have 90, some have 3k. Don't really know how to describe and what causes it, but every round is being like this.

**Comment by optimumtact** [comment]
For some people this seems to be 509 related

**Comment by duncathan** [comment]
509 related? What the hell?

**Comment by KazeEspada** [comment]
One round space was a high pressure mix of oxygen and nitrogen, but it acted like it had plasma in large quantities despite saying 0% plasma.

The next round, space was made out of cold -20 degree mix of oxygen and nitrogen. And I managed to find a single tile that had 0 pressure and no gases.

**Comment by MrStonedOne** [comment]
Space shares an air datum, that part is working, so that was it varying as things dumpped air onto a any space tile correctly, triggering a blanking of the space tile's atmos, or incorrectly, causing air to come on it until something triggered the right procs to cause it to disperse to nothingness.
