### ISSUE TITLE
"Signs" convert to blank signs when removed from wall

### ISSUE THREAD

**Issue by masonhales** [tgstation/-tg-station#16645]
There are signs all over the station. "Medbay" "Chemistry" "Science" "Danger:Space" all those little signs pointing where the departments are. These signs can be removed with a wrench, at which point they automatically convert to blank signs. When you put the sign you just removed back on to a wall, it's a "blank sign" with a brown icon. Every sign in the game has this problem and you should be able to remove signs and put them other places. This problem has been in the game a loooong time and I'm pretty sure it's actually common knowledge at this point. Please fix this.

**Comment by KazeEspada** [comment]
You can use a pen to change their icon.

**Comment by masonhales** [comment]
Yes I'm well aware, but the signs shouldn't automatically convert to blank when you take it off the wall.

**Comment by masonhales** [comment]
Actually that reminds me of another bug, when using a pen on a not-blank sign, the sign moves to the tile your character is on after you've changed the sign. It SHOULD stay on the wall.

**Comment by optimumtact** [comment]
The second thing is actually a bug and has been reported before iirc

**Comment by phil235** [comment]
Second bug is already fixed
