### ISSUE TITLE
Reagents do not heat up in burning corpses

### ISSUE THREAD

**Issue by Lexorion** [tgstation/-tg-station#16644]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

### What is the problem?
A burning corpse with black powder is supposed to explode, yet the reagents in it seem to ignore the body temperature and they do not heat up.

### Why is it a problem, or what should have happened?
The reagents should heat up, e.g. if I inject a corpse with black powder and light it on fire,it is supposed to explode. If I inject a living person with the powder and ignite it, it does explode.

### How can the problem be reproduced?
Inject a corpse with black powder for example and ignite it, observe the result (no explosion).

### What revision did the problem happen on? (Helpful, but not required)
current

**Comment by phil235** [comment]
Reagents are not metabolized when inside a corpse.

**Comment by KorPhaeron** [comment]
Not a bug, mobs are NOREACT

**Comment by duncathan** [comment]
Lame tbh
