### ISSUE TITLE
Windows never break from overpressure alone

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16651]
I could have sworn they used to. As it stands right now this only happens with the assistance heat and/or a hotspot.

**Comment by lordpidey** [comment]
They never did.  If that were the case, the atmos tanks would all blow their windows.

**Comment by PKPenguin321** [comment]
^
Not a bug, technically

**Comment by duncathan** [comment]
Yeah I don't think this is really an issue
