### ISSUE TITLE
Space heater's "Set" button does not work

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#16665]
If you screwdrive a space heater, you can modify its target temperature. The arrows to reduce or increase that target temperature work fine, but using the "Set" button to give a custom temperature value always set the target temperature to 0, no matter what value you input.

**Comment by stapler2025** [comment]
type 600, get 60.

**Comment by phil235** [comment]
the issue is the input is the temperature in Kelvin apparently. Needs to do newtemp = input + 273
