### ISSUE TITLE
I enjoy breathing (still being sent to "space")

### ISSUE THREAD

**Issue by ram001400** [tgstation/-tg-station#16675]
"Centcom is glad to announce the end of sending workers to our control group for space exposure testing, a fake station in "space" that noticeably had air in "space". " If this means that the station had no air, pressure, or heat, then this fake station still exists.... or doesn't.  So far unless i'm doing something wrong (and I haven't changed anything except for the admin list) the station still seems to just be glorified space.

**Comment by duncathan** [comment]
Please update your byond to version 510. An unforeseen difference between native byond regex and BYGEX (what's used for regexes in byond releases prior to 510) causes this issue. It's on our radar but we're not sure when it can be fixed.
