### ISSUE TITLE
Hideous lag

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16672]
Constant, periodic lag from before roundstart onward apparently unattached to the master controller is live as of about two hours ago, pointing to a pull within the last day (Before #16632)

I kept mentioning this in IRC but no one was willing to give me an answer on who if anyone was looking into this, so into the issue tracker it goes.

**Comment by Durkel** [comment]
I can confirm that it's pretty bad lag.

**Comment by optimumtact** [comment]
@MrStonedOne @duncathan 

tagging likely culprits

**Comment by duncathan** [comment]
incoming for fuck's sake you're a Coder in game; run a profile and figure out what's actually lagging

will reopen when you do so

**Comment by optimumtact** [comment]
@duncathan there's no need to be rude

**Comment by duncathan** [comment]
You're right
Sorry incoming

**Comment by Incoming5643** [comment]
It was oddly rhythmic network lag, that's why I couldn't figure out out

**Comment by duncathan** [comment]
oh well network lag isn't even our issue!
