### ISSUE TITLE
Station spawns without air in 509

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#16687]
On my testing server the station spawns completely without air.

**Comment by duncathan** [comment]
Workarounds: use 510

**Comment by KazeEspada** [comment]
But our downstreams? They may still use 510, also, the servers and code is all still set to 509 as the recommended.

**Comment by duncathan** [comment]
I added a compile time warning should people be compiling on 509
You just have to use 510 until I fix it
