### ISSUE TITLE
Temperature changes in atmos are very slow / space is warm

### ISSUE THREAD

**Issue by LatD** [tgstation/-tg-station#16714]
Hull breach caused by a bomb sucked out air with a normal rate but temperatures weren't changing at all. This at least wasn't the case before so something seems to be wrong. Here's a picture showing a hull breach and air alarm info just next to the breach after some minutes.

http://puu.sh/o9He9/eee8c6b5d0.png

**Comment by MrStonedOne** [comment]
@duncathan

**Comment by lzimann** [comment]
This might be related to h/e pipes not cooling when in a space tile aswell.
