### ISSUE TITLE
Blob passive regen outpaces fire damage

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#16711]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
Fires don't seem to fire_act() nearly as often as they used to, meaning blob health regen outpaces the damage fires would otherwise do to blobs.

**Comment by duncathan** [comment]
This is a blob balance issue

**Comment by ChangelingRain** [comment]
it was caused by slow atmos and is now fixed because atmos is fast again
