### ISSUE TITLE
All simple animals ranged cooldowns are too short

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16731]
Each simple animal had a cooldown, in life ticks. These were converted to cooldowns in deciseconds, at a ratio of 10 deciseconds/1 second per life tick . All simple animals can fire too fast now, resulting in stuff like goliaths chainstunning people.

I'm not sure what the exact life tick/second ratio is, but I'm guessing it's closer to 1.5

**Comment by RemieRichards** [comment]
I don't think the cooldowns are in seconds, we do things in deciseconds around here usually.

**Comment by RandomMarine** [comment]
Life ticks were every two seconds, right?
