### ISSUE TITLE
Drone toolboxes+tools refund nearly all of the resources used to create the drone

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#16734]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
Drones cost 800 metal and 350 glass to make.
The toolbox, and its contents(a wrench, screwdriver, welder, wirecutter, multitool, crowbar, and full cable coil) are worth 1275 metal and 250 glass.

The problem is obvious.

**Comment by ChangelingRain** [comment]
A drone shell is worth -475 metal and 100 glass to create~

**Comment by Lumipharon** [comment]
Just up the cost of drones - they're retardly cheap.

**Comment by coiax** [comment]
I think cable coils and toolboxes being added to the autolathe recently may have pushed the values over the edge.

Just change it to 1500 metal, 350 glass? Plucking numbers out of thin air is fun.

**Comment by TheNightingale** [comment]
There are better ways of getting infinite materials than relying on a willing ghost role to take a drone shell, commit suicide, take another drone shell, recycle the original materials, build a new drone shell, commit suicide...

**Comment by RandomMarine** [comment]
That, it's a lot of tedium for a little more than a quarter sheet's worth of metal.
