### ISSUE TITLE
Thermite continues to melt a wall forever.

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/-tg-station#16744]
-Pour Thermite on a wall and light it on fire

-Watch how the wall continues to burn despite the model being melted under the hotspot

-Can't walk through it

**Comment by Supermichael777** [comment]
how much did you use? 5 u is enough for a normal wall

**Comment by Aloraydrel** [comment]
I had a full 100u beaker and tested on both types of walls. It will continue to burn and not melt

**Comment by Dorsisdwarf** [comment]
Yeah, thermite is broken as heck right now

**Comment by duncathan** [comment]
thermite code is god awful
