### ISSUE TITLE
Stuffing currently worn items into the locker causes the desync bug

### ISSUE THREAD

**Issue by Core0verload** [tgstation/-tg-station#16740]
1. Open a locker.
2. Click-and-pull your ID into it.
3. Wait.
4. You have one ID card in two places at once! Enjoy your fresh desync bug!

Well, I like my desync bugs. They allow me to do some weird/cool stuff like make eguns or batons charge themselves. But this one is just _too_ easy to reproduce.

High priority I think.

**Comment by PKPenguin321** [comment]
we should have just left lockers with using grabbing instead of trying to be cool and hip and changing it to clickdragging and causing 10000 bugs

**Comment by phil235** [comment]
Either we make stuffing only work with items on the ground, or we call drop_item() to make sure the item is no longer in our hand after the stuffing.

**Comment by duncathan** [comment]
I don't think this was even done with grabbing, @PKPenguin321
Grabbing only affects mobs; this is about items
