### ISSUE TITLE
Holopads (and possibly other decals/objects) layer on top of the bluespace shelter

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#16752]
@KorPhaeron 

![Imgur](http://i.imgur.com/aw7zUFR.png)

**Comment by swankcookie** [comment]
why are holos layered so high anyway? I actually ran into this problem adding a machine.

**Comment by KorPhaeron** [comment]
Because people complained they got lost under crayons and shit

**Comment by ChangelingRain** [comment]
they layer on top of walls, as would be expected, but below the sign object which is on top of the wall.

**Comment by swankcookie** [comment]
maybe i'm imaging holopads wrong, but shouldnt they be under walls?

**Comment by swankcookie** [comment]
I thought they were supposed to be attached to the floor
