### ISSUE TITLE
Running a server relies on a beta build of byond with stability issues

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16769]
Currently you need to run the beta build of 510 byond on the server to have atmos work right (due to #16026) but doing so has revealed that components of byond (byondcore.dll) are actually failing on the live severs. These failures probably have something to do with the server crashes and bad lag we've been experiencing these last few days.

**Comment by duncathan** [comment]
I'm crying

**Comment by optimumtact** [comment]
Pfft so? This is byond, it crashes when you sneeze in it's general direction anyway.

**Comment by Incoming5643** [comment]
Just in general having any part of the game reliant on a beta version of byond is a really bad idea

**Comment by merklaw** [comment]
I would like to add that cargo consoles (Supply Consoles and Supply Request Consoles) do not work if you compile with BYOND 509. They do work if you compile with BYOND 510. There are more details in issue #16612.
