### ISSUE TITLE
Eshields block and reflect when hit from the back

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#16780]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
An eshield blocks taser shots(and probably all other laser related shots) from behind.
What's the point in the shield model if they block from all sides and you don't have to face them to reflect/block.
I don't think it was always like this....

**Comment by coiax** [comment]
This is more of a balance issue than a bug. Eswords block ranged energy projectiles from all directions as well. If you changed this, then it's not really a bugfix but a nerf.

**Comment by Shad0vvs** [comment]
The dual esword one makes sense, but the shields, are you telling me they were always like this? If so then just close this, but I really don't think they were...

**Comment by coiax** [comment]
They cost like 14 TC or something obscene. If you make a "directional eshield" you could make it a lot cheaper.

**Comment by KorPhaeron** [comment]
We've never had any directional combat stuff until my mech change this week
