### ISSUE TITLE
Golems are unable to wear coats

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#16785]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Golems used to be able to wear scientists lab coats, and certain other jackets. Now they can no longer do so. They should be able to wear this new goliathmurder cloak at least.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by KorPhaeron** [comment]
Not a bug

no_equip = list(slot_wear_mask, slot_wear_suit, slot_gloves, slot_shoes, slot_w_uniform)

Line 336 of species_types.dm

**Comment by coiax** [comment]
I didn't say it was a bug.

Just they used to be able to wear labcoats, definitely, and that's been taken away.

Also, it's sad that the natives cannot enjoy the benefits of #16771 since you'd think they'd be able to.
