### ISSUE TITLE
Suit Storage Units not manipulating loc and contents properly

### ISSUE THREAD

**Issue by Isratosh** [tgstation/-tg-station#16784]
@bgobandit PR #16576 broke SSUs completely by calling the master proc open_machine() when the "open" interface button is pressed. The proc dumps the contents, which is not the desired function. Contents should only be removed when the specific piece of equipment is dispensed from the machine. In the current state, opening the machine, moving the suit elsewhere, and then dispensing the suit will teleport that suit to the SSU's loc.

**Comment by octareenroon91** [comment]
This is still happening.

The unwary might get stripped of their suit randomly...

**Comment by PKPenguin321** [comment]
can confirm that this is still happening and it still sucks, suits randomly disappear off your body, and it gets even stranger when the suit has a built in helmet

**Comment by bgobandit** [comment]
bro I'm on vacation will fix after
