### ISSUE TITLE
Present icons are broken

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16799]
Presents have no icon when spawned.
item is /obj/item/weapon/a_gift

**Comment by phil235** [comment]
My bad, I forgot to change its icon_state to "giftdeliverypackage3" . see https://github.com/tgstation/-tg-station/commit/15d8e0a96fde69feaba800d219bf20e52135c1d1#diff-3f3ef94f4aa2be2d10fed5da6b67b072R14
