### ISSUE TITLE
Catsplosion still happening

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16793]
The kitten stretches out for a belly rub.
The kitten wags its tail.
The kitten wags its tail.
The kitten stretches out for a belly rub.
The kitten shakes out its coat.
The kitten shakes its head
The kitten grooms its fur.
The kitten shakes its head

end my suffering pls

**Comment by Incoming5643** [comment]
I've tried everything. There is nothing left but cats.

**Comment by Shapsy** [comment]
Can we just like remove cats mating or something until it gets figured out??

**Comment by bgobandit** [comment]
>shaps is in favor of removing kittens

why is this man an admin again

**Comment by PKPenguin321** [comment]
okay here's my super hacky idea
make a check on roundstart for kittens in the CMO office
delete them

**Comment by bgobandit** [comment]
>pkpenguin in favor of deleting kittens

jesus

**Comment by PKPenguin321** [comment]
too many kittens spoils the broth

**Comment by xxalpha** [comment]
Drown the kittens.

**Comment by Niknakflak** [comment]
I haven't seen the Higgs Bugson tag in awhile

**Comment by Shapsy** [comment]
@bgobandit it's not funny it's annoying and has overstayed its welcome

**Comment by ATDoop** [comment]
eventually it'll stay around so long that it will be funny again though

**Comment by Aloraydrel** [comment]
going back to dwarf fortress roots

**Comment by bgobandit** [comment]
it's not supposed to be funny it's supposed to be adorable, because :cat: s

**Comment by PKPenguin321** [comment]
a thousand kittens on top of each other forming an ancient lovecraftian horror of tails and stretched out arms does not scream "adorable," it screams "OH GOD PLEASE KILL ME I'M AN ABOMINATION"

**Comment by optimumtact** [comment]
isn't this directly related to the fact that byond will sometimes replace the icon proc with the cat new?

**Comment by bgobandit** [comment]
in all seriousness though there has to be a dumb hacky way to fix this at least

**Comment by Mercenaryblue** [comment]
Clearly the only solution is to have your butchers work faster

**Comment by Incoming5643** [comment]
This might have been fixed with #17165 

I haven't seen any recently at least
