### ISSUE TITLE
Revert the revert of goofgrabs

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#16802]
It really sucks being grabbed and not being able to tell because of the tiny little red text mixed in with a trillion other things when I'm trying to just survive for a couple minutes. Please make the grab text big again.

**Comment by PKPenguin321** [comment]
I never reverted the text size change.

Also, **FEEDBACK FORUM**

**Comment by Dorsisdwarf** [comment]
This is not an issue report
