### ISSUE TITLE
Toggle-Darkness brings up an odd window

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16809]
Server revision compiled on: 2016-04-11
Test merge active of PR #16789 
Based off master commit eb9b834b8bffbac11f782e98f053fea71f98a20f 

http://i.imgur.com/IQDUbZE.png

I'm getting it on log in as well, and some players are reporting getting it when attacking or taking damage.

It went away when we switched off meta back to box.

EDIT: Updated to master, still doing it (and on box as well)

**Comment by Niknakflak** [comment]
Haven't gotten that when I toggled it

**Comment by phil235** [comment]
it's an admin test proc being called somehow.

**Comment by KorPhaeron** [comment]
@lzimann had it happen as well

**Comment by TrustyGun** [comment]
same thing is somehow happening in #16804, despite being a completely different situation

**Comment by lzimann** [comment]
It happened for me while toggling darkness aswell. And when I was messing around with a hook, I would hook a mob and it would get me this prompt

**Comment by KorPhaeron** [comment]
It is happening to me when I log in as well

**Comment by swankcookie** [comment]
not admin-only

**Comment by xxalpha** [comment]
Uhhh Critical Priority? Could this be 510's fault?

**Comment by Shapsy** [comment]
This just happened to me every time I stepped onto a hotspot fire?

**Comment by lollerderby** [comment]
I've also had this come up when I was looking at a crew monitoring console.

**Comment by swankcookie** [comment]
fuuuuck

**Comment by Aloraydrel** [comment]
had a blobbernaught attacking me and the window was popping up as well

**Comment by TrustyGun** [comment]
is this the new cleanbot?

**Comment by optimumtact** [comment]
likely just needs the server to be recompiled

**Comment by KorPhaeron** [comment]
Clicking on the current revision thing does nothing by the way

**Comment by KorPhaeron** [comment]
@MrStonedOne

**Comment by PKPenguin321** [comment]
a lot of things have been triggering this, such as teleporting (probably by any method) and landing in a wall

**Comment by MrStonedOne** [comment]
this SHOULD be fixed now, could somebody confirm it's still happening.

**Comment by KorPhaeron** [comment]
Have not seen it since last night when I told you about it

**Comment by MrStonedOne** [comment]
@Dorsisdwarf @KorPhaeron @phil235 close please
