### ISSUE TITLE
Heat transfer pipes don't cool air in space anymore.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#16825]
>Heat transfer pipes don't cool air in space anymore.

>heat transfer pipes used to cool air in space e.g. cooling loops

>this is technically more realistic????

**Comment by LatD** [comment]
Might be related to #16714

**Comment by xxalpha** [comment]
High Priority

**Comment by lzimann** [comment]
Was not related to #16714, it simply doesn't cool.

**Comment by Jalleo** [comment]
@duncathan quick call the engineer to replace the cooler in space!

**Comment by duncathan** [comment]
just fuck my shit up
