### ISSUE TITLE
Roller Beds - Cannot pull while someone is buckled onto it

### ISSUE THREAD

**Issue by Hliey** [tgstation/-tg-station#16824]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

The roller beds, though not many use them, are made irrelevant by the fact that for some reason you can now no longer pull them with someone buckled to them. It can easily be reproduced, just by simply buckling someone to a roller bed and trying to pull it. It'll stay stuck in place.

**Comment by Shapsy** [comment]
Can confirm

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/pull/16512/files#diff-ac67a04d0e99b8458714248c84118bedR106
