### ISSUE TITLE
You can blow open locked crates with an improvised firebomb

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#16859]
I don't think this was ever intended and it's a balance issue.

**Comment by Zilenan91** [comment]
I think it's fine personally. It gives assistants/revs ways to blow open sec lockers without killing an officer.

**Comment by Dawgas** [comment]
to be blunt: what most coders intend end up being ways that make the game stale, boring, and repetitive.

feels like everything's working as intended so if this is going to be a badly thought out discussion - people having fun is not bad, stop ruining the fun

**Comment by PKPenguin321** [comment]
I agree with dawgas, minus the ranting sweeping "coders hate fun" generalization

This is fine

**Comment by AdamElTablawy** [comment]
it's an explosion, it should probably smash some wimpy ass crate

**Comment by coiax** [comment]
Improvised firebombs are composed of welding fuel, cables and drinking cans, they're not hard to make.

The question is, why are the crates locked? To stop people who don't have the access from getting the contents? Anti-greytide?

Could compromise, and make some locked crates "hardened" (eg. an uncontroversial example, supermatter shard), making them highly resistant to explosions, and maybe whine if they're tampered with.

**Comment by Zilenan91** [comment]
Nah it's fine

**Comment by Dorsisdwarf** [comment]
If the players like it, and it isnt too ridonkulous, Feedback Forum time
