### ISSUE TITLE
Atmos and fires are super slow

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16854]
I couldn't seem to find an issue report for this surprisingly.

Atmos is currently at about pre-fastmos speeds, possibly even slower.
Fires seem to take ages to spread, and I saw a 1x1 produce almost no noticible change to a room's atmos for about an entire minute or so.

**Comment by CPTANT** [comment]
Yes this is an issue, Sometimes opening a plasma cannister takes ages to process, which is usually a bad thing in situations where you are opening a plasma cannister.

Perhaps it is an idea to let plasma process faster/ before other gasses?

**Comment by duncathan** [comment]
@CPTANT not feasible.

Anyway this issue is odd because it wasn't going this slowly when turfs was being tested and the only changes I've done since then to maybe impact performance affect only round start.

**Comment by MrStonedOne** [comment]
This is because their are a fuck ton of z2 active turfs at round start, so by the time anybody does anything interesting with atmos it has 5k active turfs on top of what ever gets activated on the station

**Comment by Shadowlight213** [comment]
Shouldn't all the turfs on z2 be unsimulated? Since they don't need to be processed at all. Is making shit unsimulated even possible with the new system?

**Comment by MrStonedOne** [comment]
its not possible, that was the point. you could prevent them from being active by finding all the holes and closing them up.
