### ISSUE TITLE
Wood chairs in the holodeck can be picked up and carried out

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16867]
Apparently, the wooden chairs in the holodeck stop being holographic once picked up. This basically means infinite wood.

Steps to reproduce:
1. Enter holodeck
2. Set holodeck to Lounge (or maybe it's called Lobby, I don't recall 100%)
3. Pick up a wooden chair by dragging it to your character
4. Carry it out of the holodeck
5. Place the chair and notice how it does not disappear
6. Wrench chair and get free wood

You can also bash a mob with a chair until it breaks to get the wood.

**Comment by coiax** [comment]
The Holodeck is a source of such free materials at the moment, if that standing on glass tables is still in.
