### ISSUE TITLE
Can Use The Same DNA Injector on Multiple People

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#16872]
Provided you start the injection on multiple people, before the first finishes injecting, you can use the same DNA injector on multiple people.

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/35bfb9abb6d3e7952d14a1781c9ffc3a68d2df00/code/game/objects/items/weapons/dna_injector.dm#L72

```
		if(!do_mob(user, target))
			return
```

should be:

```
		if(!do_mob(user, target) || used)
			return
```
