### ISSUE TITLE
Losing a holoparsite to a chasm doesn't kill the owner.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#16884]
Watched a miner have his holo eaten by a chasm today, The holo died but the miner was left alive. Pretty honk worthy.

**Comment by coiax** [comment]
Chasms directly qdel() anything that enters them, which only calls a guardians' Destroy(), but not death() or gib().

You'd either need to add a check in Destroy() to kill the host (which may have been left out intentionally for debugging purposes), or put some sort of kill or death proc in the chasm when living things fall in.

**Comment by PKPenguin321** [comment]
just override holoparasite's Destroy() to call death() then ..()

**Comment by octareenroon91** [comment]
This makes no sense: holoparasites are generally yanked back to their masters.

**Comment by drynwyn** [comment]
Also they can fly, so.... Why would they give a single solitary shit about a hole?

**Comment by coiax** [comment]
Chasms on lavaland don't move anyone, they just delete anything that moves onto them to simulate FALLING FOREVER. Kor's suggestion of making flying creatures immune to chasms is the best solution, I'll code that in.

**Comment by coiax** [comment]
This was fixed by #17012

**Comment by phil235** [comment]
@coiax You can add "Fixes #numberoftheissuehere" to your PR to automatically close the issue when it's merged.
