### ISSUE TITLE
Crates that are open at roundstart are dense

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#16882]
You're supposed to be able to walk over open crates now. Crates that start open, however, are still dense until you close and reopen them.

**Comment by TheRealGLH** [comment]
I thought walking over open crates was a bug.

**Comment by PKPenguin321** [comment]
nope

**Comment by ChangelingRain** [comment]
Tbh I'd prefer if open crates were dense, but you could climb and walk on crates a la tables, which wouldn't be too hard to do.

**Comment by Jordie0608** [comment]
I'm not sure this is intended, the PR by @neersighted which added this was meant to be purely a code refactor

**Comment by neersighted** [comment]
Looks like a bug in the crate code. They're intended to not be dense when open... Should be simple enough to fix, however.
