### ISSUE TITLE
Ghost role sleeper Human species have no tongue organs

### ISSUE THREAD

**Issue by FantasticFwoosh** [tgstation/-tg-station#16892]
In both the lavaland prisoner crashed shuttle ruins and other sleeper created ghost occupants such as the space bartender (self contained in space ruins), they do not have a tongue organ in which to speak with. (theoretically contributed to being made prior to tongue PR implementation) 

The ability to not speak or communicate coherently majorly effects these RP centric roles.

**Steps to reproduce** - Observe and jump into a ghost role with a human species product, and attempt to speak - _OR_ - admin-create a sleeper running off the same identical code and possess/force a ghost inside and test linguistics.

**Comment by Incoming5643** [comment]
Humans coming about without tongues point towards a situation where a human mob exists without a species datum. This is an error almost as grave as a human without dna at all.

**Comment by Incoming5643** [comment]
This comes down to the fact that humans not created from players never call set_species()

**Comment by Core0verload** [comment]
Another instance of the same bug: #16840
