### ISSUE TITLE
Slime processor is only taking in one slime automatically

### ISSUE THREAD

**Issue by LatD** [tgstation/-tg-station#16894]
Slimes going in automatically was added in #16773 / #16870
Now the processor is only taking in one slime. Using the processor makes it take a new one in again. It should automatically take in everything that's on it.

Would the fix just be removing the check ` 		if(slime.loc == src)
			return` or is that needed for something else?

https://github.com/tgstation/-tg-station/blob/57d9a1b43dc5b3213109e30c3fd87606bb6dc63d/code/modules/food%26drinks/kitchen%20machinery/processor.dm#L36

**Comment by coiax** [comment]
Looks like it
