### ISSUE TITLE
/obj/item/toy/talking/skeleton/proc/skelly_say() requires byond 510 beta to function

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#16897]
#16792 
@coiax 

**Don't use features not in the stable release**

**Comment by ChangelingRain** [comment]
I always say "why are we using the unstable release" but nobody answers

**Comment by Incoming5643** [comment]
We shouldn't be using hte unstable release! A solution was coded so we could back to stable, but I guess we didn't?
