### ISSUE TITLE
extinguisher cabinet can be interacted with by ghosts

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#16909]
Ghosts can open and close extinguisher cabinet's with Alt+Click when orbiting object

This occurred on Basil, on MetaStation.
Appears to be all cabinets.

Steps:
-Be a ghost
-Double click/double alt click on a cabinet so that you are now orbiting it
-Alt click on cabinet
-It opens at closes.

**Comment by Durkel** [comment]
ayy lmao

#16710

@PKPenguin321

**Comment by PKPenguin321** [comment]
wot are you sure

**Comment by PKPenguin321** [comment]
what the fuck are ghosts pathed under mob/living????

**Comment by RemieRichards** [comment]
@PKPenguin321 no, ```/mob/dead/observer```

**Comment by PKPenguin321** [comment]
then how is this bug???????????????????

**Comment by PKPenguin321** [comment]
i thought https://github.com/tgstation/-tg-station/pull/16725/files#diff-f0b62c0d2dbefd44b9b6641086467b1fR70 this line would fix it since i stuck it to mob/living but i guess this line actually does nothing?

**Comment by RemieRichards** [comment]
@PKPenguin321 that path is never checked, so of course it does nothing.

**Comment by PKPenguin321** [comment]
fuck

**Comment by bgobandit** [comment]
I thought this bug got fixed

**Comment by PKPenguin321** [comment]
i thought so too

**Comment by LatD** [comment]
Normal ghosts can't toggle the cabinets. Only when they're orbiting something. Which is really weird.

**Comment by PKPenguin321** [comment]
No, you can still toggle it if you're not orbiting, you just had to be adjacent to it
