### ISSUE TITLE
Template spawning black overlay

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#16910]
Spawning a template via the place verb causes that entire area to be pitch black, forever, no lighting, just a weird black overlay.

@AnturK @KorPhaeron no doubt one of you two did this.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/-tg-station/issues/16060

Is this a dupe, or is it happening in space now?

**Comment by RemieRichards** [comment]
Oh, had no idea, well on Z 5 (lavaland) it's completely pitch black and will never update, but on Z1 (station) you just get ugly block-y lighting instead, but yeah dupe.
