### ISSUE TITLE
You can scoop up dense anchored mobs with lockers

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#16913]
Use pull+click to slide an open locker under a tendril.

Close the locker and pull it around.

Kill it on station for a chasm in the hallway.

Lockers should not be able to close on anchored mobs

**Comment by PKPenguin321** [comment]
a random event that causes an on-station chasm would be kick-ass though let's be real

**Comment by Shadowlight213** [comment]
Curses. The secret to the ash walker lizard factory using legions. Nooo
