### ISSUE TITLE
Slaughter demons can cast spells while bloodcrawling

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#16926]
Step 1: Mindswap a slaughter demon
Step 2: Have fireball
Step 3: walk up to someone, say hi, and blow them up, while you're invulnerable.
Step 4: Jaunt around as you also have incorperal move
Step 5: Taste the salt coming off the players

**Comment by Armhulen** [comment]
hooooooly shit

**Comment by coiax** [comment]
Ethereal jaunt mutes people for this exact reason.

However, applying the same fix to slaughter demons means they won't be able to threateningly gurgle at people without being manifested. And slaughter demon RP is the most precious thing we have. Let me think about it.
