### ISSUE TITLE
Shaft Miner jumpsuits in the mining lockers are the old overall jumpsuits

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#16949]
They should be the turtlenecks

**Comment by Dorsisdwarf** [comment]
The turtlenecks are stupid anyway. Miners should have the overalls

**Comment by Zilenan91** [comment]
They don't fit the aesthetic of their explorer suits though, they'd look like trash.

**Comment by Dorsisdwarf** [comment]
Oh yeah I forgot, lavaland made mining doom and gloom where everything has to be a shade of black, grey, or dark red.

**Comment by Dorsisdwarf** [comment]
This isn't really bugtracker, I guess
