### ISSUE TITLE
Safety caps

### ISSUE THREAD

**Issue by yackemflam** [tgstation/-tg-station#16975]
1. Remove safety cap from foam force bullet
2. Load into empty gun
3. Fire gun
4. Safety cap is fired
5. No murder through toy accident :^)

**Comment by ShadowDeath6** [comment]
Aren't they only supposed to turn into riot darts after you load them with a pen after de-capping?

**Comment by yackemflam** [comment]
@ShadowDeath6 Nope, riot darts a whole different thing
