### ISSUE TITLE
Bots pathfinding is too random

### ISSUE THREAD

**Issue by Core0verload** [tgstation/-tg-station#16979]
For example, cleanbots often go to the other end of room instead of cleaning a turf right next to them, making cleaning a lot slower. 

I think the cause is that simple animals code fails to prioritize nearby targets and goes for the first target in view() list instead.

**Comment by yackemflam** [comment]
This is a problem how?

**Comment by Incoming5643** [comment]
The randomness is intentional to keep mutiple bots in the same area from constantly choosing the same tiles, because it makes their jobs overlap and makes all but one of them useless.

**Comment by Core0verload** [comment]
There is a better solution to this. For example, make the bots check targets of nearby bots.

**Comment by xxalpha** [comment]
spiral_view when fam

**Comment by LatD** [comment]
I found this problem too when I was adding the replace tile option to floorbots. If they're replacing tiles they replace basically every tile which becomes really slow when the bot moves really long distances after each tile and changes tiles on random places (which is why I had to change the bridge mode to work on normal tiles as well)

**Comment by GunHog** [comment]
They used to scan() in a spiral. Who broke this?

**Comment by KazeEspada** [comment]
Incoming made them randomize so they wouldnt stack

**Comment by Incoming5643** [comment]
Even before that they didn't scan in a spiral: they scanned from the top left corner, left to right descending. Which biased them to Move Northwest / North in general.

**Comment by Shadowlight213** [comment]
I think at least for cleanbots, if we make it first check adjacent tiles, then do the normal randomization, it should help a lot. It would let them clean up blood trails correctly. It has the possibility of still running into the stacked bot problem, but we could also add a check where of there's a bot working on the targeted tile, it skips that tile in its check.

**Comment by octareenroon91** [comment]
Why not just put anti-stacking in the bot AI? Make them try to keep 2 tiles between each other and call it good.

**Comment by Dorsisdwarf** [comment]
something, something, forum.
