### ISSUE TITLE
Butchering a morph will not make it drop its contents

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#16977]
I butchered a morph that had eaten the entire armory, and after a short lagspike, the morph disappeared leaving just some meat behind instead of dropping the items.

**Comment by phil235** [comment]
relevant code: https://github.com/tgstation/-tg-station/blob/35bfb9abb6d3e7952d14a1781c9ffc3a68d2df00/code/game/gamemodes/miniantags/morph/morph.dm#L124

https://github.com/tgstation/-tg-station/blob/a064fcdd079d0600830c596272811bb0d2c81832/code/modules/mob/living/living.dm#L957

I don't see any issue in the code...

**Comment by ChangelingRain** [comment]
I had a player report that butchering mining mobs for loot wasn't working, either.

**Comment by Shadowlight213** [comment]
@Phil235 the morph is already dead when you butcher it. Therefore I don't think death is called twice. I may be wrong on this. That then would result in just the butcher results(the meat) being dropped and the rest of the contents get qdel'd. Which seems to be consistent with observed behavior.
