### ISSUE TITLE
Plasma amount in the air check doesn't work properly

### ISSUE THREAD

**Issue by alphaaBeta** [tgstation/-tg-station#17037]
```
Results:
Pressure: 102 kPa
Nitrogen: 78.86 %
Oxygen: 21.12 %
CO2: 0.01 %
Plasma: 0.01 %
Temperature: 22 °C
```
`safe_tox_max` is set to 0.05 and that much plasma is dealing damage anyway.

Using a flamethrower once in a hallway makes it inhabitable without internals for the rest of the round. And it's nearly impossible to get rid of that little plasma.

**Comment by phil235** [comment]
Yeah, something is wrong, the warning/alarm threshold for toxin on the air alarm is 0.1/0.5 which means you're currently taking toxin damage at levels below what the air alarm detects as harmful.

I think safe_tox_max is probably supposed to be 0.5 and the issue is a typo.

**Comment by phil235** [comment]
Found the issue. a typo in species.dm that made the safe toxin max var default to 0.005 isntead of 0.5.
