### ISSUE TITLE
You can pick up a chair whilst in crit

### ISSUE THREAD

**Issue by erwgd** [tgstation/-tg-station#17072]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

If you're in crit you can pick up a chair. As a horizontal spaceman you'll drop it automatically, leaving the upended chair on your turf.

**Comment by phil235** [comment]
an "if(!user.incapacitated)" probably missing.
