### ISSUE TITLE
The collectable HoP cap in the Metastation museum is a reskinned HoS cap

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17084]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

If there's an icon and description for it and its own icon, then it should actually have an entry in the code, rather than being a map specific thing.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by Dorsisdwarf** [comment]
I have no idea what to tag this. I'm tempted to mumble about "feedback forum", but it doesnt even fit there

**Comment by RandomMarine** [comment]
Lots of maps have special varedited objects. I don't see anything wrong with this.

**Comment by octareenroon91** [comment]
Consistency issue
