### ISSUE TITLE
AI malph lockdown opens all doors on all Z levels

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#17095]
So I only just noticed this, but after the lockdown effect that malph AI can run, all doors open. This included the doors on the emergency shuttle which was currently docked at cent comm.

I'm not sure if it effected other shuttles and any other Z levels, but it certainly effected the emergency shuttles airlocks as the all opened at the same time as all other doors would normally do after the lockdown effect.

This was on Basil, on Box as far as I can remember.
(Sorry I dont have more details, I completely forgot to report it at the time).

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/blob/cf8bd9044dfce9c3d45ae946bc8446aa3253247a/code/game/gamemodes/malfunction/Malf_Modules.dm#L164

**Comment by GunHog** [comment]
Check that someone did not screw up Z-levels to make it such that the Centcomm Z-level is equal to the mining Z-level. That is the only plausible explanation I can give.

**Comment by RandomMarine** [comment]
It also opened the doors at the abandoned teleporter.

**Comment by KorPhaeron** [comment]
Wrong line @GunHog 

It's a few lines down under DisableLockdown(), which has no Z_check at all
