### ISSUE TITLE
barmonkey transferring hats/masks include live facehuggers

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#17106]
Put facehugger on punpun/whatever and have round end
Next round, live facehugger on monkey. As in, it's not going to infect the monkey, it's just there, and if you remove it it'll infect the next person it touches
Watch xeno infestation consume the poor griffons.

**Comment by coiax** [comment]
I'm pretty sure this is intended behaviour, it was one of the first things talked about when Pun Pun got round hat carry on.

**Comment by MMMiracles** [comment]
I forget, does the transfer save changed variables or does it just place a new stock variant of whatever was placed the round before?

**Comment by LatD** [comment]
I remember this being talked a lot on the Pun Pun mask PR and it was intended at that time at least

**Comment by KorPhaeron** [comment]
Not a bug
