### ISSUE TITLE
laser gatling gun firing while buckled

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#17105]
step 1. Get robusted by xenos
Step 2. get buckled into a nest
Step 3. watch xeno dance on you to taunt you
step 4. hold LMB on said xeno and watch it die
Step 5. Dchat: BUG AbuSE BAN HE
@KorPhaeron

**Comment by optimumtact** [comment]
Sounds like a hilarious story

**Comment by Dorsisdwarf** [comment]
Doesn't sound like a bug at all, assuming gatling guns are NODROP.

**Comment by Zilenan91** [comment]
It seems pretty cheesey that you're able to fire a gun while buckled to the floor.

**Comment by Razharas** [comment]
Autoclick only applies click() a lot, if you can do it with autoclick then you can do it without it

**Comment by Razharas** [comment]
Also we dont have any special bucklings
There is only one usual buckle and you can buckle to a chair and you should surely be able to shoot while sitting
So this needs something more handcore

**Comment by KorPhaeron** [comment]
Fixed
