### ISSUE TITLE
Changelog doesn't have a section for bug fixes/major work

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17109]
Coders work on a range of issues, and quite a few of them are not new features or nerfs, but bug fixing or overhauls or under the hood stuff. There's no accepted way of mentioning these in the changelog without lowering the signal/noise ratio of just pure changes, which are what most players would care about.

Is it possible to make a changelog that includes bugfixes or a special more technical changelog?

**Comment by RemieRichards** [comment]
Those things don't go on the changelog, you want a technical changelog look at git history.

**Comment by Dorsisdwarf** [comment]
Don't Not A Bug things which aren't even issuetracker material

**Comment by duncathan** [comment]
ITT: people who write changelog worthy code dismiss the value of having recognition for your work from the playerbase

**Comment by Dorsisdwarf** [comment]
This isnt about "Let us put refactors in the changelog (Which usually is done for major refactors anyway" though, this is suggesting creating a "technical changelog" seperate from features. Which already exists - Github history
