### ISSUE TITLE
Chairs cannot be built on escape shuttle

### ISSUE THREAD

**Issue by iamgreaser** [tgstation/-tg-station#1711]
##### In order to fix this bug quickly and effectively we require detailed information. Please try to be as descriptive as possible. Even if you feel like something isn't a significant clue, it can't hurt to include it. #####
I cannot build chairs on the escape shuttle, making my 5-and-a-bit stacks of metal somewhat useless.

There are very few things I can build on there. I can build tables, but not chairs, not closets, nothing particularly interesting.

##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
2013-11-05 eeeeedfc8b76dd0b646c98edae4b0377fc14cc05

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
/tg/ server 1 (Sibyl)

###### What did you expect to happen? ######
I would be able to make a chair on the shuttle.

###### What happened instead? ######
It said I couldn't make a chair because it wasn't on the ground.

###### Why is this bad/What are the consequences? ######
The shuttle could do with more chairs. More accurately, the stacks of metal I mined from the asteroid could do with more love. But still, chairs.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Get some metal sheets.
2. Call the shuttle.
3. Get on the shuttle.
4. Try to build a chair.
5. Cry tears of misery.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
I was a Shaft Miner.

##### Anything else? #####
Nope.

**Comment by Dorsisdwarf** [comment]
This isn't a bug, since it's a feature that nothing can be built on the shuttle

**Comment by Aranclanos** [comment]
it is a bug.
