### ISSUE TITLE
Ruins spawning without air

### ISSUE THREAD

**Issue by Cheridan** [tgstation/-tg-station#17125]
Some areas are spawning with no/improper atmos.

White ship/Animal Hospital/Space Bar/Gym and probably others are all deadly now.

**Comment by Cheridan** [comment]
Apparently the free golem ruin is fine still because ??

**Comment by Cheridan** [comment]
also ash walker ruin doesn't have air either and it's killing all the ash walkers even though they're not supposed to have to breathe?? !???

**Comment by KorPhaeron** [comment]
Guys stop breaking lavaland it makes me sad

**Comment by KorPhaeron** [comment]
Dunc fixed it
