### ISSUE TITLE
Time stop stuns forever

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#17146]
Be atmos tech
Attack wizard with a punch
He timestops
Get stunned by timestop
Timestop ends
Still stunned
Rest
Get up to clear stun

**Comment by Iamgoofball** [comment]
>Rest
>Get up to clear stun

this shouldnt work

**Comment by Iamgoofball** [comment]
this also shouldnt be a permastun wtf

**Comment by phil235** [comment]
duplicate of #15978
