### ISSUE TITLE
Alien weeds don't spread on 95% of tiles

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#17149]
There's not much of a pattern to it either. Weeds won't spread when dropped on the vast, vast majority of tiles in the game. I haven't been able to discern any pattern in what makes certain tiles work and other don't. 

If a tile does start spreading, it will (usually) spread like normal, sometimes it will only spread about 1 tile around it and then stop.

**Comment by ChangelingRain** [comment]
It checks atmos adjecent turfs, so @duncathan
