### ISSUE TITLE
Atmos is 110% fucked

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#17156]
>Put 2 canisters of plasma/oxygen mix into mix tank
>Twice as much as I normally do
>1x1 square of fire ignites, goes out within 60 seconds
>Max'd pumps won't fill the receiving canister, no sign of plasma or fire in the tank

**Comment by yackemflam** [comment]
I've complained about this for a LONG while after the *NO LAG* update

**Comment by optimumtact** [comment]
Pretty concerned that we have no visibility on how often our subsystems check_tick and decide to wait.

The update merely eliminated visual lag, and I fear we're losing ground on the invisible atmos just doesn't update as fast anymore type of lag.

**Comment by yackemflam** [comment]
Update didn't remove visual lag only, I've seen player do things that wasn't possible before.

Like outrunning a bomb exploding.

**Comment by RandomMarine** [comment]
I'm constantly running into tiles where atmos just sits and doesn't do anything until I slap/remove a floor tile on it.

**Comment by Robustin** [comment]
I was successfully using the mix chamber like 2 weeks ago, after the lag update. But then canisters reacting internally was slow as fuck (hence why I had to use the burn chamber). Now the canisters were internally burning as fast as ever but the mix chamber method is FUBAR'd. Couldnt get a single unit of gas out after I pumped 2 cans in.

**Comment by phil235** [comment]
I've reproduced your mix @Robustin , the problem is that the turf atmos does not update. And even force calling air_update_turf() does not fix it.

**Comment by phil235** [comment]
It seems the issue is the same as alien weeds not spreading. Nearly every turf on the map does not have its adjacent turfs calculated. So the air system is thinking there are no neighbour turfs to spread the gas.

**Comment by Robustin** [comment]
Yea I just realized the same thing before I saw this comment. Atmos is completely fucked.

**Comment by Robustin** [comment]
http://imgur.com/33v0was
