### ISSUE TITLE
Chainsaw Augment is broken

### ISSUE THREAD

**Issue by Aliannera** [tgstation/-tg-station#17158]
Put chainsaw on arm.
Try to attack things.
Not be able to attack things and have a useless arm.

**Comment by PKPenguin321** [comment]
You're kidding me
I'll look into it tomorrow, if anybody's able to test this right now I'd be grateful

**Comment by KorPhaeron** [comment]
This happens with the chaplain hand of god as well.

Betting it happens with changeling armblades. NODROP/abstract shit seems to not work

**Comment by KorPhaeron** [comment]
@phil235

**Comment by phil235** [comment]
Kor is correct, I changed standard attack to not work with the ABSTRACT flag, it seemed like a nobrainer.... I'll fix those.
