### ISSUE TITLE
CIRCUIT IMPRINTERS DONT ACCEPT ACID

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#17161]
Circuit imprinters do NOTHING when you use a beaker full of acid on them. Not even an error message
AND NEITHER DOES THE PROTOLATHE ANYMORE

**Comment by kevinz000** [comment]
Happened for 3 rounds in a row already.

**Comment by Jalleo** [comment]
@phil235

**Comment by MMMiracles** [comment]
the nerf RnD needed

**Comment by Robustin** [comment]
>Not making acid-infused bananas, placing the bananas in crates, and then putting those crates through the crusher to get acid-infused metal that you can add to the imprinter

**Comment by coiax** [comment]
> Not having any reagents that are in the beakers when the circuit imprinter is constructed added to the Imprinter's reagent pool.
