### ISSUE TITLE
Putting anything at all into a bag of holding creates a singularity

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#17173]
@Razharas 

Happened to a guy using a medkit, I confirmed by using a spent shell casing.

**Comment by PKPenguin321** [comment]
Lmao

**Comment by TrustyGun** [comment]
👏👏👏👏

**Comment by PKPenguin321** [comment]
@Razharas

Also I'd like to nominate this for bug of the year

**Comment by bgobandit** [comment]
10/10
