### ISSUE TITLE
Most tiles have NO adjacent atmos, WHYYY

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#17170]
I finally solved the mystery behind #17156 and #17149

I checked the vars on tiles around the station, 95% of them have NO adjacent atmos turf. This explains why weeds are broken on most tiles, why the toxins mix tank is borked, why foam isn't spreading, and why syphons and hull breaches don't suck air from the surrounding area. 

SS13 is supposed to be an elaborate atmos simulator masquerading as a game, it shouldn't be doing this: http://imgur.com/33v0was

**Comment by PKPenguin321** [comment]
@duncathan ???

**Comment by LatD** [comment]
This is then probably also the reason for #16714

**Comment by phil235** [comment]
From what I'm seeing, I'm guessing the error is that /turf/open/Initalize_Atmos(times_fired) does not call ..() (which calls /turf/proc/Initalize_Atmos(times_fired) whose only line is "CalculateAdjacentTurfs()"

But I could be wrong.

**Comment by Razharas** [comment]
@MrStonedOne 
@duncathan

**Comment by Jalleo** [comment]
Oh god
