### ISSUE TITLE
Devil Antag bugs

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17184]
1) Lizards can sell their souls for power, but don't seem to be able to gain hulk.
2) A pen is required to sign a contract. Should be possible for the devil to rip a blood red pen from you so you  can sign your soul away.
3) Phase cannot be cast while phased.
4) If a devil dies while phased, and loses sufficent power, they lose the phase spell, and thus the ability to phase back in.

**Comment by coiax** [comment]
@lordpidey

**Comment by PKPenguin321** [comment]
Lizards not getting hulk is intentional
