### ISSUE TITLE
Using Lavaland generator randomly spreads lava about the whole z level

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#17196]
When using the "Lavaland" generator in buildmode it doesnt work properly and ends up spreading single tiles of lava throughout the current Z level.

Steps (tried on basil):
- Toggle buildmode on self
- Toggle through to generator
- Select "/datum/mapGenerator/lavaland"
- Try to click two corners as normal
- Nothing appears, exploring that current Z level you will find single tiles of Lava spread around.

**Comment by Ausops** [comment]
it's very badly behaved, it generates lava outside the corners

**Comment by optimumtact** [comment]
hilarious
