### ISSUE TITLE
Lockers can not lock

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#17195]
Apparently using any item on them will attempt to open so there's now no way to lock secure lockers.

**Comment by RandomMarine** [comment]
Alt-click

**Comment by YakumoChen** [comment]
changelog where

**Comment by Lumipharon** [comment]
pls.

**Comment by Jalleo** [comment]
@phil235

**Comment by phil235** [comment]
not my fault this time.

**Comment by Lumipharon** [comment]
Not long ago clicking lockers with items would try and lock them, and if they didn't have a lock, would try to open them.

Why and how did it change from that to begin with? The change phil mentioned was a bugfix/feature revival, not something entirely new.

**Comment by coiax** [comment]
@ChangelingRain did you fix this? I can't find the PR in the history.

**Comment by coiax** [comment]
@Cheridan this can be closed.
