### ISSUE TITLE
Synthetic peels created by the bananium mk-honk clown shoes will not proc slip

### ISSUE THREAD

**Issue by Mercenaryblue** [tgstation/-tg-station#17191]
[Note]: # The mk-honk shoes creates synthetic peels that won't slip at all.

runtime error: 
[21:46:48]Cannot execute null.Copy().
[21:46:48]proc name: New (/obj/item/weapon/grown/New)
[21:46:48]  source file: growninedible.dm,16

No badmin button or function used, beside the spawn function on a private testing server.
Wasn't working on /tg/station server 1 either.

**Comment by xxalpha** [comment]
The recent mutation updates must have broken it.

**Comment by xxalpha** [comment]
``if(new_seed)
seed = new_seed.Copy()``

**Comment by xxalpha** [comment]
Post byond version this happened on.

**Comment by xxalpha** [comment]
Origin of the bug is an incomplete refactor.

The code that is spawning these was not touched.

In bananashoes.dm
`` new/obj/item/weapon/grown/bananapeel/ specialpeel(get_step(src,turn(usr.dir, 180)), 5) //honk``

**Comment by Core0verload** [comment]
Another peel that is created with old potency thing. Will fix.
