### ISSUE TITLE
Cannot construct new air alarms.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#17200]
>build air alarm frame
>attach to wall
>try to add cable
>cable only smacks frame, cannot proceed further.

Probably caused by #17092

**Comment by RandomMarine** [comment]
If intent matters, I was a drone. No intents to switch.

**Comment by phil235** [comment]
Fuck.. drone are animals so they're always stuck on harm intent, that's a problem :confused:

**Comment by optimumtact** [comment]
simple mobs my ass :smile:

**Comment by phil235** [comment]
wait, @RandomMarine , you sure you didn't just forget to insert the electronics in the alarm first?

**Comment by RandomMarine** [comment]
Absolutely sure. Tried smacking the frame with every other standard tool I had plus electronics.

**Comment by phil235** [comment]
Can't reproduce. If your air alarm frame was empty and you did try electronics, the only possibility is that you had the wrong type of electronics. I can't even reproduce by var editing the drone's intent to harm.

**Comment by Jalleo** [comment]
I think this may of already been reported and fixed.
