### ISSUE TITLE
Throwing an item at an electrified grille will create a tesla shock...

### ISSUE THREAD

**Issue by Hatfish** [tgstation/-tg-station#17204]
...that will crit anyone who isn't wearing a hardsuit and insulated gloves.  This is bad because you can literally kill anyone but the engineers by just standing in a high-traffic area and occasionally throwing a crowbar at an electrified grille.

**Comment by phil235** [comment]
This is technically not a bug since the behavior is intended, but some people agree that this is ridiculous.

**Comment by KorPhaeron** [comment]
It's pretty zany yeah.

**Comment by Aloraydrel** [comment]
fun fact you can generate power from the shock with a tesla coil. Infinite energy

**Comment by Iamgoofball** [comment]
get good

stop hardwiring to the grid

stop throwing shit at grilles to break them without getting electrocuted

take caution near open electrified grilles

**Comment by KorPhaeron** [comment]
>stop throwing shit at grilles to break them without getting electrocuted

It's not about shocking myself, it's about me being able to kill everyone on the bridge by chucking a glass shard in their general direction

**Comment by Iamgoofball** [comment]
Good thing we have admins to ban griefers.

**Comment by Hatfish** [comment]
The problem is that it enables easy murderboning, all you need to kill most of the crew is a hardsuit and insulated gloves.

**Comment by lzimann** [comment]
this feature is stupid

**Comment by Iamgoofball** [comment]
Then nerf the outputted electricity and reduce the bounce radius. Easy fix.

**Comment by Lumipharon** [comment]
>change everything else that has been fine since the begining of time rather then the retarded change that was just recently added, because that's fine and everything else is the problem

Yeah, nah.

**Comment by PKPenguin321** [comment]
lumi learn to read
we can just adjust the range and damage down instead of outright removing it
you cucks overreact to every meme of the day, then wonder why "muh coders always nerf things!!"

**Comment by Lumipharon** [comment]
pk learn to read. I never said anything about removing it.

**Comment by Zilenan91** [comment]
It needs a nerf to 1 tile, it's actually impossible to break people out of jail currently unless you break the windoor which is far far far more durable than the windows to the side and gets you caught.

**Comment by Hatfish** [comment]
why not just have the grille shock only whoever triggered it?

**Comment by Zilenan91** [comment]
That could work but you still wouldn't be able to break people out of jail without luck and lag being on your side

**Comment by RandomMarine** [comment]
@Zilenan91 Ever consider just wirecutting instead of THROWING SHIT.

**Comment by Zilenan91** [comment]
You need gloves for that, which aren't always a thing you can rely on your saviours having.

**Comment by Lumipharon** [comment]
this whole change just added more gear checks to the game, git gud and raid engineering round start for suit and gloves :^)

**Comment by Dorsisdwarf** [comment]
I really disliked this change, since while it's visually cool, it's just another step down "Dealing with a situation = "Have singular counter-situation item yes/no and nothing else working" lane.

**Comment by CosmicScientist** [comment]
>I really disliked this change, since while it's visually cool, it's just another step down "Dealing with a situation = "Have singular counter-situation item yes/no and nothing else working" lane.

We already had a nice middle ground of broken glass from the window you smashed would cut your hand for attacking with it.

I mean what would be wrong with a few sparks to warn it's going to do its thing so you can get out of the way? Or maybe a resistor or transformer or something could be put on wires that just limits the value that gets pushed through to non-lethal by default.

**Comment by Zilenan91** [comment]
This would be a fun feature if the range wasn't 3 tiles. Just nerf it to 1 and it'd be gucci

**Comment by jughu** [comment]
How hard is it to get any type of gloves and use the glass shard on the grille like old times

**Comment by jughu** [comment]
Altough the shock should do less damage tbb

**Comment by Iamgoofball** [comment]
# ps take it to the feedback forums this isnnt a fucking bug

**Comment by duncathan** [comment]
^

**Comment by CosmicScientist** [comment]
K.
[https://www.tgstation13.org/phpBB/viewtopic.php?f=10&t=6557](feedback thread)
