### ISSUE TITLE
People are still dual wielding KAs despite them requiring 2 hands

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#17203]
Fire KA 1

Put in bag

Retrieve KA 2

Fire KA 2

Put in bag

Retrieve KA 1 that is now recharged

Possible solutions: 

1) Won't autocharge (sounds annoying)

2) Won't recharge unless held in hand (What could be the lore behind such a function though?)

**Comment by GunHog** [comment]
Sounds like people hate that change, and want to find a way around it...

**Comment by Hatfish** [comment]
this seems like a lot of hassle to go through to just use two KAs, does it really need a nerf?

**Comment by KorPhaeron** [comment]
Doing 100 damage a cycle instead of 50 is pretty significant, and being able to blow through all the mobs on your own like that discourages teamwork

**Comment by Incoming5643** [comment]
>2) Won't recharge unless held in hand (What could be the lore behind such a function though?

https://www.youtube.com/watch?v=LXC7qZ_iWgM

**Comment by optimumtact** [comment]
I mean if they're autistic enough to juggle their shit like this then who are we to stop them

**Comment by CosmicScientist** [comment]
oranges seems right.

Otherwise just limit how many they have access to if it is causing a real balance problem.

**Comment by lzimann** [comment]
i actually prefered it being manually recharged(for me at least it was a bit faster than the automatic one)

**Comment by kilkun** [comment]
I agree with Lzimann. Plus it felt like actioning a bolt on a rifle, making me feel cool. This semi-auto stuff just makes me feel like a huge nerd.

**Comment by jughu** [comment]
Just remove the 3 extra lockers on mining outpost or remove the 3 lockers at cargo and make the miners start on the outpost

It limits KA to 3
No extra free survival capsules
No extra advanced scanners for faster scanning
Or
Put back daul wielding
Make it knock you down if your holding another gun/Ka so we be able to hold mining bags with it again

Or do them both

**Comment by Fox-McCloud** [comment]
having to be charged every time was quite literally one of the most annoying and tedious things about mining, as it was just "spam hotkey to activate in-hand item" endlessly.

**Comment by coiax** [comment]
I will make a PR that KAs only recharge in your hands, because cooling/bioelectric field/balance reasons.

**Comment by lzimann** [comment]
sounds like too much over a minor thing

**Comment by coiax** [comment]
Given how they were nerfed specifically to avoid dual wielding, I mean, this is just finding an oversight in how we detect dual wielding to get around it.
