### ISSUE TITLE
Detective Revolver Reload Bug

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#17291]
Using literally any object on the detective revolver gives the "You start reloading..." message, when only speedloaders should be doing that.

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/c925a6af95e4cfad92f904057725330ba9a2f48d/code/modules/projectiles/ammunition.dm#L123 and https://github.com/tgstation/-tg-station/blob/3fe4ba3ca6c6ee38995ad56fe01b8fda304315a4/code/modules/projectiles/ammunition/magazines.dm#L68

**Comment by Anonmare** [comment]
>It takes the same amount of time to load a single bullet as it does to load a speedloader

**Comment by xxalpha** [comment]
Epic balance memes, anonmare.

**Comment by PKPenguin321** [comment]
revolver reload delay got removed so i'm gonna assume this is no longer an issue
