### ISSUE TITLE
Lava land ruins randomly have broken "unsmooth" icons

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#17295]
![lava](http://puu.sh/oBR1O/99fd3ba8f6.jpg)
Randomly ruins will have invalid icon states called "unsmooth"
@KorPhaeron

**Comment by ChangelingRain** [comment]
Looks like lava river/cave gen.

**Comment by KorPhaeron** [comment]
Dupe issue. @yotaxp and @duncathan are the ones who could fix this
