### ISSUE TITLE
Legion Heart implantation is bugged

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/-tg-station#17294]
It says it's too big when you try and put it in your chest

**Comment by Zilenan91** [comment]
Also it's basically impossible to get a non-inert legion heart for implantation into you since you can't lazarus the corpses it drops. The inert legion heart should heal as much as the one that works.

**Comment by PKPenguin321** [comment]
>Also it's basically impossible to get a non-inert legion heart for implantation into you since you can't lazarus the corpses it drops. 

you have to buy an item from mining vendors that causes the heart to never expire. i'm guessing you tried inserting an inert heart and since it's no longer technically an "implant" it threw the "too big" message. this needs reproduction/testing.

**Comment by RandomMarine** [comment]
1. Hivelord cores/legion hearts don't become a new object when they expire.
2. They still function when implanted regardless of this.

What exactly happened, @Zilenan91?

**Comment by Zilenan91** [comment]
They have an inferior effect once inspired from what I know. I have not checked the code for this however.

As far as implanting an expired hivelord core was going, I had a lizard chemist inserting it into my chest via the cavity implant surgery, and once he was trying to put it into me he was getting the message that it was too big and could not put the hivelord core inside of me.

**Comment by ToadStar** [comment]
You need to do it via organ manipulation, not cavity implant.

**Comment by PKPenguin321** [comment]
^ this guy gets it

**Comment by PKPenguin321** [comment]
so yeah this is not an issue feel free to close it maintainers

**Comment by Zilenan91** [comment]
Surgery is a fucking mess and the operations make no sense but okay

**Comment by PKPenguin321** [comment]
no not really
cavity implants are for hiding things in a little empty space in your chest cavity
organ manipulations are for wiring up or tearing out organs

**Comment by Zilenan91** [comment]
Yeah but if you're implanting new organs you'd need to have your body grow nerves and veins and valves and shit leading into it so it could function and not instantly rot inside your lnsavdlaenosodj as;aefsd asdf

The cavity implant just seems more accurate for something like this, either way whatever

**Comment by PKPenguin321** [comment]
think of it as dropping an organ into a box versus stapling an organ to the wall of a box
