### ISSUE TITLE
Something broke character saves

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#17297]
:snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: 
All my snowflakes are gone, who screwed up player preferences?
:snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: :snowman: 

Edit: All prefs were reset actually

**Comment by PKPenguin321** [comment]
:snowflake:
