### ISSUE TITLE
Round Start Aliens

### ISSUE THREAD

**Issue by IvanIssaccs** [tgstation/-tg-station#17309]
Im just posting this because the admins cant figure out how exactly this happened.

Crew member chest burst shortly after round start, bar tender, admin logs cant explain it.
Round ending at server time 15:07 on Basil. 
Figure it out?

**Comment by ChangelingRain** [comment]
Facehugger on pun-pun.

**Comment by Bawhoppen** [comment]
yes its known thing

**Comment by LatD** [comment]
Facehugger on Pun Pun is a known feature, not a bug. One issue report about it was just closed some days ago.

**Comment by KorPhaeron** [comment]
Not a bug, but the lamarr thing is
