### ISSUE TITLE
Ghost-examining of spiders doesn't work

### ISSUE THREAD

**Issue by LatD** [tgstation/-tg-station#17321]
When clicking a giant spider, dead or alive, as a ghost with inquisitiveness on, nothing happens. I tried the examine-click with items and other simple mobs like slimes, animals, mining mobs, monkeys and they all work. Only the spider seems to be broken. Normal manual examine still works.

Possible reason could be that there are spiders that players can control when clicked but these ones were just normal uncontrollable npc-spiders.

**Comment by PKPenguin321** [comment]
Probably a missing parent call
