### ISSUE TITLE
Automatic guns are almost impossible to put into slots

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/-tg-station#17356]
TL;DR the autoclick isn't blocked when clicking on the hud, so you very rapidly put the gun into the slot, take it out again, put it back, and so on.

**Comment by optimumtact** [comment]
wtf do you mean by autoclick?

**Comment by Jalleo** [comment]
The gun activating multiple times when you click once i presume.

**Comment by optimumtact** [comment]
hmm I assumed it handled things sanely, instead of generating multiple clicks

**Comment by phil235** [comment]
generating multiple clicks..... who merged this shit.

**Comment by RemieRichards** [comment]
@phil235 Razharas, the person who wrote it.

**Comment by Razharas** [comment]
It was kors pr he stole my code
