### ISSUE TITLE
"Set Admin Volume" defaults to 0 since PR

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#17361]
For some reason the "Set Admin Volume" in preferences is defaulted to 0 rather than 100.
This has confused a lot of admins as they assume they can no longer hear midi/ogg's being played.

It does, after changed, stay at the level it is set to between rounds and log in/out.

Also someone mentioned the "Hear Admin Midi's" toggle button no longer works due to this either (even when at 100) though I have not tested that myself yet.

**Comment by Dorsisdwarf** [comment]
The volume control was a bad idea.
Turn it off if its too loud. 
There are _three seperate buttons_ for if a MIDI/ogg isn't to your liking why do we have three.
