### ISSUE TITLE
Repairing cameras with wire cutters attacks the camera

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17376]
> You screw the camera's panel open.
> You put the screwdriver into the drone dufflebag.
> Drone (256) reactivates the security camera!
> You hit the security camera with the wirecutters!
> You put the wirecutters into the drone dufflebag.
> You screw the camera's panel closed.
> You put the screwdriver into the drone dufflebag.

**Comment by xxalpha** [comment]
Bad ..() somewhere in the attackby.

**Comment by Jalleo** [comment]
@phil235

**Comment by LatD** [comment]
Same thing happens when deactivating the camera

**Comment by PKPenguin321** [comment]
Also related sorta, filling a welding tool causes you to attack the fuel tank in the process
