### ISSUE TITLE
Specflags uses a fucking list to store it's data

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/-tg-station#17378]
jesus christ these are a pain in the ass to work with just look at my code 

var/status = CANSTUN | CANWEAKEN | CANPARALYSE | CANPUSH
  	owner.status_flags &= ~status		// Look at this. status_flags is a bitflag, and is stored as an int.
 	oldflags = owner.dna.species.specflags
 	if(!(MUTCOLORS in owner.dna.species.specflags))
 		owner.dna.species.specflags += MUTCOLORS  // look at this. This is stored as a list.*
 	naturalcolor = owner.dna.features["mcolor"]
 	owner.dna.features["mcolor"] = sanitize_hexcolor("#3DCF13")
 	owner.regenerate_icons()

*NOT JUST STORED AS A LIST IT'S STORED AS A LIST OF NUMBERS THAT ARE POWERS OF 2. LIKE ("2", "4", "16", "8"). THEN IT CHECKS IT WITH 'CONTAINS'. WHY. JESUS.  The whole point of flags is so you can do quick bit operations on it to add and check flags, AS YOU SEE with status_flags.

**Comment by RemieRichards** [comment]
I'm pretty sure this is because more were added during the mutation -> species datum refactor, this pushed them over 16 flags which is the maximum number of flags a bitfield can hold, so a list was required.

The defines still being powers of 2 is just laziness, no <i>requirement</i> to update meant they weren't updated.

**Comment by blobbernaut** [comment]
please remie think of the children

**Comment by RemieRichards** [comment]
I am! a bitfield orphanage doesn't have enough room for the children we're inevitably going to get, where as a list orphanage has functionally infinite room for the younglings!

**Comment by blobbernaut** [comment]
true, true but all of our children will be asking us "Daddy, why am I named 256?" So I'll fix this anyway for consistency and readability's sake.

Why is the limit only 16 bits though, as opposed to 32

**Comment by RemieRichards** [comment]
@blobbernaut
Because mummy says so!

DM's ints only allow bit operations on the lower 16 bits, hence a 16 limit.
And yeah if you want to clean up the defines that'd be appreciated, just to better show they're not actually intended for a bitfield anymore.

**Comment by phil235** [comment]
just fyi, I've fixed this in my upcoming dismemberment PR. And I've also fixed the COLDRES define being fucked because it is defined TWICE (used for the cold resistance mutation name and for this species bitflag).

**Comment by RemieRichards** [comment]
@phil235 by "fix" I do hope you mean changing the define values, and not turning it back into a bitfield.

**Comment by phil235** [comment]
Nope, backt to bitfield I'm afraid. If you really want to, I can remove it from the PR.

**Comment by RemieRichards** [comment]
I'm really not happy with that 16-flag limitation, it WILL become an issue in future, I foresee it.

**Comment by blobbernaut** [comment]
maybe if I ask real nicely they'll give us better bitwise operation support in a future update. 
wait

what

did you say

DM's ints (floats, DM has no ints but hey)

im triggered

**Comment by RemieRichards** [comment]
AAAAAAH WE'RE AT 15 (maybe 16 one of them is in a weird place I can't tell if it belongs) FLAGS FOR SPECFLAGS, WE REALLY CAN'T GO BACK TO A FIELD ;_; @phil235

**Comment by blobbernaut** [comment]
Byond pls add long support.-------- Original message --------

**Comment by RemieRichards** [comment]
heh

**Comment by blobbernaut** [comment]
Don't laugh at my SHAME

**Comment by RemieRichards** [comment]
*laughs again*
