### ISSUE TITLE
You cant access client in varedit

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#17381]
https://github.com/tgstation/-tg-station/commit/10b966b97cd9f2b709a8c8472fb57d374c535cb9
This added var to all datums to check on varedit
BUT GUESS WHAT CLIENTS ARE NOT DATUMS
ANd so you cant open client in varedit anymore

**Comment by Razharas** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
I forgot this dumb thing was a thing

**Comment by Razharas** [comment]
Please fix

**Comment by Incoming5643** [comment]
no proboto
