### ISSUE TITLE
Lockbox is accessible even if locked if you have its inventory open

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#17407]
Cross-reporting from https://github.com/PolarisSS13/Polaris/issues/1163, tested on our server. 

How to reproduce:

Take a lockbox; unlock it; open its inventory by dragging its sprite to your mob; lock it; take the item out of the lockbox. The "It's locked!" message will appear, but you will still take the item. This does not work for putting items back in the lockbox, just for taking them out.

**Comment by phil235** [comment]
some .hide() shit or something missing when you lock the lockbox.
