### ISSUE TITLE
lizards can't  be hulks

### ISSUE THREAD

**Issue by blobbernaut** [tgstation/-tg-station#17437]
dismemberment update should fix the issue with lizards having a human overlay sprite. If it doesn't, I can port my fix. I included an indicator sprite too so you can tell the difference between a hulk lizard and a green lizard.

Let me know if I should PR it, or if you guys are just racists against lizards.

**Comment by RemieRichards** [comment]
This was intended, but I'm leaving the issue open in case my+phil's new human icon code can fix it.

**Comment by PKPenguin321** [comment]
imo hulks should just be a lot bigger like reverse midget mutation

**Comment by Dorsisdwarf** [comment]
GTFO the bug tracker, man. Put it in the coderzone on the forum.

**Comment by blobbernaut** [comment]
i can't forum, i'm banned. I was just letting you know as a courtesy.
