### ISSUE TITLE
Drone dispensers don't take materials correctly

### ISSUE THREAD

**Issue by Knigga** [tgstation/-tg-station#17442]
Take a stack of 49 metal sheets and choose to enter 50 sheets into the dispenser. The dispenser increases in metal supply but you still have your 49 sheets in hand. Works with glass too. Repeat ad infinitum for drone station.

**Comment by PKPenguin321** [comment]
hiiiigh priority

**Comment by xxalpha** [comment]
This machine needs to be updated to use the material container.
