### ISSUE TITLE
Tesla Doesn't Always Ground Out

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#17447]
The Tesla doesn't always respect and adhere to grounding out to grounding rods; if one is standing in engineering, near the PA, you can get shocked by it--previously, prior to a number of nerfs/buffs/changes, it would *always* ground out and you never had to worry about getting shocked in engineering; this is no longer the case and you can definitely get fried by the Tesla now, inside engineering.

This doesn't just apply to mobs, it can also destroy equipment, as well.

@MrStonedOne @Iamgoofball

**Comment by MrStonedOne** [comment]
that is odd... i'll take a look.

**Comment by MrStonedOne** [comment]
alright, i can see an edge case

If the teslaball is dead top center, and you are really close to it, one of the orbiting ball tesla zaps may have a really short range and be unable to reach the grounding rods.
