### ISSUE TITLE
Washing Machines no longer allow items to be dyed

### ISSUE THREAD

**Issue by Z79** [tgstation/-tg-station#17462]
Ever since we had the icon glitch several days or so ago, none of the dyeable items (such as bed sheets and shoes) have been appearing as dyed when you wash them with crayons. 
Can be recreated by simply dropping a pair of shoes and crayon into a washer and turning it on.

I need muh fashions

**Comment by Crushtoe** [comment]
Critical bug.

**Comment by phil235** [comment]
Blame @Robustin https://github.com/Robustin/-tg-station/pull/7/files#diff-94bd5ca9aef0dae0e2103b30cbc6d310R64

**Comment by Robustin** [comment]
Just tested it, it's working fine. Now get off my damn lawn and don't clutter my PR's with these things.

http://imgur.com/NmJbx6C

**Comment by phil235** [comment]
@Robustin Your branch is probably not updated. The bug is reproduceable on sybil.

**Comment by Robustin** [comment]
It's from the PR I was working on today, well if it gave you an excuse to clean up that godawful mess of code when I'm all for it.
