### ISSUE TITLE
Lizards that are turned into monkeys hiss when they chimper

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#17463]
see title

**Comment by Incoming5643** [comment]
I'm not seeing why this is an issue.

**Comment by tedward1337** [comment]
feature

**Comment by PKPenguin321** [comment]
^

**Comment by phil235** [comment]
because the monkey keeps the dna and so the species type.

**Comment by lordpidey** [comment]
Phil, I think it's because they keep their tongue?

**Comment by Incoming5643** [comment]
yes specifically it's the tongue. Again I don't think this is a problem.

**Comment by Dorsisdwarf** [comment]
Closing for non-issue.
