### ISSUE TITLE
AIs upgraded to Malf via the Combat Software Upgrade cannot hack cyborgs.

### ISSUE THREAD

**Issue by GunHog** [tgstation/-tg-station#17471]
AI players, which are non-antagonist but are given the Combat Software Upgrade disk (found in Ashwalker nests), are not given the ability to hack their cyborgs via the robotics console as Malfunctioning (Traitor) AIs are.

This is due to the following code checking for antagonist status only, and not the Malfunction module:
https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/computer/robot.dm#L62
And
https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/computer/robot.dm#L122

Typecasting the robotics console's user as an AI after using `isAI()` to verify that the user is an AI, then checking that the `malf_picker` var is set on that user will fix this bug.

Fixing this bug could be decent practice for a new coder!

**Comment by xxalpha** [comment]
I thought malf was removed.

**Comment by GunHog** [comment]
Technically, Malf AI is now Traitor AI. The _game mode_ was removed, and is now rolled into the Traitor mode. The AI is Malf'ed if it rolls Traitor during any Traitor enabled mode.

**Comment by Anonmare** [comment]
Wait, I thought the Combat Software was meant to be admin-spawn only? When was it added to Ashwalker nests?

**Comment by Dorsisdwarf** [comment]
Some time ago, to make miners want to genocide them.

Is this even a bug? It was always linked to antag status because traitor AIs and malfs got it, it's not a module

**Comment by Dorsisdwarf** [comment]
On deliberation, I'm closing this for no bug. Hacking borgs is an _ inherent antag AI_ power, not a malf module.

**Comment by GunHog** [comment]
I disagree with this decision, but there is nothing I can do about it at this point.

**Comment by Dorsisdwarf** [comment]
Well, other than change how it is in the code.

**Comment by GunHog** [comment]
What is why I made it an issue...I was hoping a newbie could use this for practice. (Also I am lazy)
