### ISSUE TITLE
You can use patches through hardsuits

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#17520]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
You shouldn't be able to patch through something you can't eat a pill or put a syringe through.

**Comment by sirnat** [comment]
This would nerf miners in their hardsuits, and engineers having to deal with carp while wiring solars. 

-1

**Comment by Aloraydrel** [comment]
Miner could lower the hood and apply via head though

**Comment by Zilenan91** [comment]
This is not an issue and is fine

**Comment by PKPenguin321** [comment]
>patches are so much weaker than bruise packs and ointment guys
>goofchem makes medbay challenging again guys

**Comment by Dorsisdwarf** [comment]
Not a bugtracker issue
