### ISSUE TITLE
Champ belt leg drop can dismember

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/-tg-station#17542]
someone nerf dismemberment please, it's ridiculous that doing a leg drop on some makes their leg fly off.

**Comment by TrustyGun** [comment]
the correct term is "hilarious"

**Comment by Dorsisdwarf** [comment]
Will crush later

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by MMMiracles** [comment]
what are you gonna do when hulkamania runs wild on you?

**Comment by peoplearestrange** [comment]
This is my current favourite mental image.

**Comment by AdamElTablawy** [comment]
i mean if a leg drop makes someone drop their leg

it's doing what it's intended to do

**Comment by phil235** [comment]
https://github.com/tgstation/-tg-station/blob/88ba55b8b426304b2e20e6514d555bc90e9818c2/code/datums/martial/wrestling.dm#L391
It's an explosion

**Comment by PKPenguin321** [comment]
i think this is legit fine just leave it be

**Comment by Iamgoofball** [comment]
@phil235 intended
