### ISSUE TITLE
The roundstart emergency shuttle has no air

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#17582]
The default one, looks like, from roundstart. There is a strip of space turfs by the entry airlocks. Probably related to @coiax's shuttle changes EDIT: maybe not.

Fix: Delete the shuttle and re-import emergency shuttle (box)

**Comment by PKPenguin321** [comment]
most recent shuttle changes i can find: https://github.com/tgstation/-tg-station/pull/17555 @coiax 
https://github.com/tgstation/-tg-station/pull/17518 @ChangelingRain 
high priority

**Comment by xxalpha** [comment]
>Also apparently pieces fall off it

Working as intended?

**Comment by coiax** [comment]
Wasn't me, my changes don't touch the default shuttle at all.

**Comment by coiax** [comment]
Fixed by #17607 and #17614
