### ISSUE TITLE
There's no delay for pointing

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#17585]
This wasn't an issue before the pointing hotkey but you can spam the shit out of pointing with the shift/middle mouse thing. There should probably be a cooldown of a second or so in between pointing

**Comment by ChangelingRain** [comment]
![oh god](http://puu.sh/oOBLW/a495df17fb.png)

**Comment by PKPenguin321** [comment]
you could always do this with the verb and with any other "me" or "say" command
just bwoink them if they keep it up
