### ISSUE TITLE
Can't throw people around

### ISSUE THREAD

**Issue by lzimann** [tgstation/-tg-station#17609]
~~#17355 was test-merged at the time(no clue if it affects anything).~~ not caused by this
No matter the grab type, you simply can't throw people around.

**Comment by KazeEspada** [comment]
Good

**Comment by phil235** [comment]
It's my fault. I made ABSTRACT items not throwable (to fix throwing telekinetic grab) but this affects throwing mobs which use the grab item.

**Comment by kevinz000** [comment]
SeE guys I didn't do muffin

**Comment by bgobandit** [comment]
don't worry leo you'll never get to throw girls around
