### ISSUE TITLE
Holodeck bugs involving animals and morphlings

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17612]
- An animal breaking a chair will display the chairs "fading away" message, and drop real materials.
- Someone breaking the tinted glass on the lounge will break the window and get real materials.
- A morphling can eat items, and they will display the "fading away" message when they leave the holodeck.

**Comment by Dorsisdwarf** [comment]
Or is this all a bug, since the items do go away when you leave.

If you can be attacked by holocarp, or beaten up with holoswords, I dont see why morphs shouldnt eat them. The first part is a bug though
