### ISSUE TITLE
Notification Sounds Bug

### ISSUE THREAD

**Issue by hbk2006** [tgstation/-tg-station#17625]
Seems notification sounds aren't working.
Such as: Emergency Shuttle called
Central Command report
etcetc

**Comment by TrustyGun** [comment]
probably because your preference is turned off

**Comment by hbk2006** [comment]
Another player reported it to me at the same time. Might be coincidence

**Comment by hbk2006** [comment]
Just checked announcements were on

**Comment by Shapsy** [comment]
fuck this was my fault I'm on it right now
