### ISSUE TITLE
Cargo bypassing no bio 

### ISSUE THREAD

**Issue by B00tz** [tgstation/-tg-station#17624]
**Problem Description:** When the cargo shuttle is loaned it sends it regardless if it has a person inside. If it does it will auto kill them without leaving a body. I have yet to test to see if it will ignore the other restrictions (bombs/beacons) 

**What did you expect to happen****:** I would expect for it not to launch as the error comes up when you try to normally send the shuttle.

**What happened instead:** It ignores the restriction and kills the player leaving no body.

**Why is this bad/What are the consequences:** Its a clean way to kill someone without leaving a trace that just seems like an error in the code.

**Steps to reproduce the problem:** Have someone in the shuttle, then loan it.

**Server:** Sybil

**Revision:** 
Server revision compiled on: 2016-05-12
Test merge active of PR #17614 
Based off master commit bb2a746390a3541500620735a2878cac9906d1bf 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):

**Comment by Jalleo** [comment]
This requires a FUCK tag for sure.

**Comment by PKPenguin321** [comment]
you'd assume that the shuttle departing to centcomm would be a proc and that cases like these would be covered by the proc

**Comment by yackemflam** [comment]
It`s been a thing for a long ass time, everyone has accepted it as a normal thing.
Like centcom thinks you`re a syndicate agent for trying to sneak on to centcom. So thus they off you for being a no god traitor.

**Comment by coiax** [comment]
Actually it's just probably because anything on arrival at Centcom is qdel'd after checking to see if it can be sold. So the real bug here is that it didn't sell the person's internal organs before deleting them.
