### ISSUE TITLE
revenants can put people into cryo

### ISSUE THREAD

**Issue by LanCartwright** [tgstation/-tg-station#17638]
[Note]:
Dragging you into cryo 4 times.
It's absolute cancer.
This probably applies to sleepers too.

**Comment by KorPhaeron** [comment]
security tag doesnt matter for issue reports

**Comment by Cruix** [comment]
Should all simple animals be unable to do this, or only revenants?

**Comment by LatD** [comment]
Simple animals can't interact with cryo anyway so it seems okay to me to prevent all simple animals from doing this
