### ISSUE TITLE
I'm pretty damn sure that's not an easel.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#17643]
![](http://i.imgur.com/sp7tut8.png)

**Comment by RemieRichards** [comment]
Art has changed in the future...

**Comment by PKPenguin321** [comment]
what map is this on/where is it?

**Comment by francinum** [comment]
It was fixed by reconnecting, probably a BYOND issue.

**Comment by Dorsisdwarf** [comment]
I dont think BYOND showing the wrong icons is solvable. Comment if I am incorrect.

**Comment by Cyberboss** [comment]
Duplicate of #26184
