### ISSUE TITLE
Sentient necropolis tendrils take damage from ash storms

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17646]
They also get attacked by lavaland mobs.

**Comment by KazeEspada** [comment]
Because Ash Storms work off of factions. I shit you not.

**Comment by optimumtact** [comment]
@KazeEspada that's not the worst idea I've ever heard to be honest

**Comment by LatD** [comment]
https://github.com/tgstation/-tg-station/blob/d662b0e45548207b5f52df55563eb7ef76d7fd09/code/modules/mining/lavaland/weather_types.dm#L88
Probably should be replaced with `if(istype(L.loc, /mob/living/simple_animal/hostile/asteroid) || istype(L.loc, /mob/living/simple_animal/hostile/megafauna) || istype(L.loc, /mob/living/simple_animal/hostile/spawner))`

..why aren't all these mobs just behind /mob/living/simple_animal/hostile/asteroid

**Comment by optimumtact** [comment]
I disagree, I think factions are an acceptable way to do this.

Some mobs just need their faction adjusted

**Comment by LatD** [comment]
Tendril faction is the correct mining faction but giving sentience potion changes the faction

**Comment by Armhulen** [comment]
...I don't know why being a smart goliath makes all the other retards angry at it like a kid getting on the shortbus because he missed the normal one

**Comment by KorPhaeron** [comment]
Could add a new list of weather_immunity types that a mob is immune to

**Comment by optimumtact** [comment]
@KorPhaeron also an excellent idea :smile:

**Comment by Armhulen** [comment]
...Or just make it not change the faction, it is still a tentacle from hell, yes?

**Comment by KorPhaeron** [comment]
But then the other tentacles from hell would ignore you while you beat them to death, and that wouldn't be fair to anyone

**Comment by LatD** [comment]
The actual problem here is that using sentience potion on any mining mob will suddenly make it take damage from ash storms, not only tendrils. Weather immunity list/variable should work well.
