### ISSUE TITLE
Progress bars are broken.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#17659]
Progress bars are currently either not updating at all or extremely slowly. I've had several other people claim the same thing. This seems to occur with all instances where they appear.

This has been happening for at least a week so this could possibly be a dupe.

**Comment by phil235** [comment]
just tested butchering a dead animal on Sybil, the progress bar worked fine.

**Comment by RemieRichards** [comment]
It's a Byond bug, update your client.

**Comment by Durkel** [comment]
@RemieRichards 

I'm on 510.1341 and the latest version is .1342,(which released today) What kind of voodoo magic are using to get a client from the future?

(according to motd on the server, .1342 is broken and crashes anyway).

**Comment by RemieRichards** [comment]
I meant 1340 or 1339 (I'm on 1341 and it all works fine),I know it's a byond issue as it only occurred on one version (one of the the two I specified), if it's come back in another beta that sucks, but it's not on our end to fix.

**Comment by Razharas** [comment]
Its not byond issue its just lag

**Comment by RemieRichards** [comment]
@Razharas Yes it IS a Byond version, considering I've seen this first hand *AND* it's been patched twice now, with lummox calling it a "Nasty" bug with images and syncing them up, spoilers: Progress bars are images.
