### ISSUE TITLE
Eguns toggled to stun and back to kill can no longer fire in kill mode

### ISSUE THREAD

**Issue by Metacide** [tgstation/-tg-station#17650]
If you toggle an egun to kill, then back to stun, toggling it to kill again gives a grey bar at the top of the gun, as if there weren't any shots left, and trying to fire just gives you *click* messages. Recharging doesn't help. Stun mode seems to work just fine and you can still freely toggle between the broken kill mode and normally-functioning stun mode.

Needless to say this can get you pretty fucked up if you have a few eguns on stun mode and think you're safe from, say,  spacecarp. Combines nicely with the killer lag of recent times, too.

Found this last round on Basil.

**Comment by coiax** [comment]
Probably related to #17644
