### ISSUE TITLE
Research Upgrades Don't Work Properly

### ISSUE THREAD

**Issue by JustAnotherUserGH** [tgstation/-tg-station#17660]
Problem Description: Upgraded research machinery does not become any more material-efficient until the amount of resources available becomes less than the cost of making items at base level.

What did you expect to happen: Items to be constantly cheaper with the proper installation of upgrades to the Protolathe/Circuit Imprinter.

What happened instead: It still consumes as many resources as it would at base level until there are too few resources to make things at that level, but enough to at the proper one.

Why is this bad/What are the consequences: This makes installing upgrades into research machinery effectively worthless and greatly reduces the efficiency of science in producing things.

Steps to reproduce the problem: Synced Machinery to research terminal as normal. Printed Nano-Manipulator at Protolathe. Printed RPED at Protolathe. Used RPED to install Nano-Manipulator into Circuit Imprinter. Tried making Sleeper Board - any board will suffice. Cost no less cheap

Server: Sybil

Revision: 2016-05-14, Test merge active of PR #17647 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Presumably Gang (round still ongoing), but this has happened to me multiple rounds now. I was doing research as normal, going through a basic plan. No other unusual bugs or happenings of note.

**Comment by GunHog** [comment]
Intended, sadly. This is a nerf by @KorPhaeron, although it is has not be handled properly. (Upgrades doing nothing instead of removing the part that modifies that stat)

**Comment by KorPhaeron** [comment]
This might change soon in LatD's thing, but it's intended
