### ISSUE TITLE
Peacekeeper Borg not regaining Ammo/Chems

### ISSUE THREAD

**Issue by PineappleWolf** [tgstation/-tg-station#17668]
1. Be peacekeeper borg
2. Use Energy Snare to slow people down
3. Run out of Energy Snares.
4. Energy Snares do not regenerate.
5. Go into borg recharger for 5 minutes, no new snares.
6. Get new battery, no new snares.

**Issue: Peacekeeper borgs can run out of energy snares. Steps above also followed and chem dispenser is not replenishing in Peacekeeper borgs either.**

**Comment by PKPenguin321** [comment]
this isn't actually in the game yet, place this in the actual PR as a comment: https://github.com/tgstation/-tg-station/pull/17355

**Comment by PineappleWolf** [comment]
It is in the game, I was just playing it?

**Comment by PKPenguin321** [comment]
it was being test merged

**Comment by TrustyGun** [comment]
It also seems to me like the battery doesn't actually recharge at all if you step into a recharger. I was in a recharger for 5 minutes and my battery never replenished.

**Comment by kevinz000** [comment]
Battery is being recharged in the last testmerge. Gun I know and I think I fixed it but it hasn't updated yet

**Comment by PineappleWolf** [comment]
It's just slow as shit especially if lights on

**Comment by Dorsisdwarf** [comment]
Dupe, all energy weapons are broken as shit apparently. Also this isnt in the game yet
