### ISSUE TITLE
NanoUI JSRender not documented.

### ISSUE THREAD

**Issue by JJRcop** [tgstation/-tg-station#1767]
### Problem
@Faerdan implemented NanoUI and vanished before documenting the template markup. 
#### Details
One day I decided I would try to learn how NanoUI works and found out it uses [JSRender](http://www.jsviews.com/#jsrapi) for its markup.
I saw how to basically use it, except I got scared when I saw Faerdan use carets ("^") after the first and before the second curly braces, ("{^{") and didn't know what they meant, since they are not documented in the official JSRender documentation. (In all of their examples, the usage is "{{", not "{^{".)
I have thus deduced that it is custom syntax and I have absolutely no idea what it means, and when I would want to, and not want to use it.
He was going to write a guide to templates in [/nano/templates/TemplatesGuide.txt](https://github.com/tgstation/-tg-station/blob/63ec19e9eda363863aa59db2bd6bc28d006cd0a3/nano/templates/TemplatesGuide.txt), but didn't even start it and simply linked to JSRender's documentation before disappearing, never to be seen again.
### Solution
The simple solution is for someone to find out the custom syntax and document it in [/nano/templates/TemplatesGuide.txt](https://github.com/tgstation/-tg-station/blob/master/nano/templates/TemplatesGuide.txt); then document the rest of the non-custom syntax which can be found in the JSRender [api documentation](http://www.jsviews.com/#jsrapi).

**Comment by Razharas** [comment]
@neersighted can you do this?

**Comment by neersighted** [comment]
@Razharas Please close, this is no longer relevant.

**Comment by JJRcop** [comment]
@neersighted No need :)
