### ISSUE TITLE
Rpg loot wizard event applies naming to body parts

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#17694]
Test person has torn test person in the enpowered chest of the sea +10 with the enfeebled Fire Axe of the sun -11!
@phil235

**Comment by PKPenguin321** [comment]
Not a bug

**Comment by Shadowlight213** [comment]
@PKPenguin321 Yes it is, because the body part is still on the person.

**Comment by PKPenguin321** [comment]
Nah

**Comment by Shadowlight213** [comment]
Explain how that's not a bug? It's inconsistent with previous behavior.

**Comment by PKPenguin321** [comment]
It's funny enough to justify keeping

**Comment by KorPhaeron** [comment]
That's pretty funny

**Comment by KorPhaeron** [comment]
@Incoming5643 

Your call

**Comment by phil235** [comment]
Who could have predicted that changing the name of every /obj/item would cause issues?

Also, I'm glade I changed bodypart code in my dismemberment PR. The bodypart's name was being used in the code to get the bodypart's corresponding zone, which means that RPG loot would be breaking that if I hadn't changed it.

**Comment by Incoming5643** [comment]
Organs were specifically blacklisted from that event because of that hacky bit of coding.

Now that it's gone there's not really any reason why they need to be exempted.

So this bug is N O T  C A N O N.

**Comment by KorPhaeron** [comment]
Evidently not a bug
