### ISSUE TITLE
Greentext item spams round end

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#17697]
http://pastebin.com/wbCJ32is

After asking the unloved rock WHY this occured, he said that it was normal for this to happen

I've really no clue what caused this.

**Comment by Ausops** [comment]
picking it up and putting it down might cause this

**Comment by Incoming5643** [comment]
it didn't use to do this, you aren't supposed to get the objective until the shuttle leaves the station and even then it's only supposed to trigger once then destroy itself

**Comment by Ausops** [comment]
maybe it does it because greentexts can't be destroyed outside of dropping it in the lava of mt doom
