### ISSUE TITLE
Randomly fucking crit while in space

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#17704]
I've seen this happen 3 times to myself and its been reported by 2 others.

You're in space around the station, then out of nowhere you're fucking crit.

There's no projectile, no indication, no message about what's struck you. Every time its 100% out of the blue with absolutely no hint or suggestion available to players OR ADMINS as to what has happened.

Some people suggest its space dust, I haven't looked at our space dust code but if space dust is literally just a "crits random people in space" mechanic, it needs to go.

**Comment by PKPenguin321** [comment]
if it is actually space dust then you have awful luck

**Comment by Robustin** [comment]
I would bet a significant sum of money that space dust isn't random, but in-fact targets players in space. When I'm less drunk I'll go try to decipher the code but holy shit that's annoying.

**Comment by Knigga** [comment]
I'd take that bet but it's against my morals to gamble with someone so unlucky

**Comment by LatD** [comment]
Wouldn't you get the usual "you got hit by sand" message if it was space dust?

**Comment by PKPenguin321** [comment]
yeah i think this is kinda like the "got killed by a temp gun" issue report lmao
oldman = salt

**Comment by Dorsisdwarf** [comment]
Spacedust goes in the adminlog (but NOT the chat menu) I think, so ask them to check next time it happens

**Comment by Robustin** [comment]
Which adminlog? I've checked the VV combat/damage log and it's never been in there.

**Comment by Supermichael777** [comment]
Random damage in space is retarded BRB
