### ISSUE TITLE
Cow players get no messages when tipped

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17702]
Specifically, players in control of the cow simple_animal.

**Comment by Crushtoe** [comment]
Just need 20 special procs, a new variable to define if a player cow specifically is tipped or not (obviously not binary, needs more states for room to expand functionality in future), a list of 50 messages that are randomly selected when the cow is tipped, and the message broadcasted to all players at once.

**Comment by Supermichael777** [comment]
or you could just remove tipping because cow tipping is a hoax

**Comment by Skullyton** [comment]
@Crushtoe Already happens in https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/simple_animal/friendly/farm_animals.dm for the most part, including the list of messages.

Just needs a to_chat(src, "You have been tipped over!") or something along those lines.
