### ISSUE TITLE
Engine Containment Field breaks, requires admin intervention

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#17711]
I've seen this happen 4-5 times as admin and just released the engine myself, so before I get banned can this get fixed? 

I have some theories as to what causes this, but I can't be 100% sure. 

1) Tesla parts getting knocked around will block a containment field when it starts and it wont ever go  up, sing then proceeds to eat the evidence once it starts up. I recommend that the tesla collectors start the round anchored so we can verify if they are the sole cause of this, or even a cause at all.

2) Powering/Activating the fields in a certain order causes their connection to fail.

**Comment by PKPenguin321** [comment]
sure dude it's totally a bug

**Comment by Shapsy** [comment]
I can testify that I've seen the containment fields acting strange and stopping randomly/not connecting when they should

**Comment by Robustin** [comment]
As an admin I've tried to fix the issue. Sometimes restarting it will work, but there are times where I've watched the player power down the entire field, start it back up, and it's still got a gap in the same spot.

I've only been able to resolve it as an admin by either deleting the entire field and placing new generators or by using VV to manually add a field connection where one refuses to form.

**Comment by Menshin** [comment]
I'll look into that... Any other info on how to reproduce it (i haven't been able to on a test server) ?

There's also the fact that the PA at power level 0 still feed the singularity enough to get to stage 4, to investigate.

**Comment by Jalleo** [comment]
This may be due to the subsystems and how the field generators are programmed.
@MrStonedOne

**Comment by Iamgoofball** [comment]
Containment Field code is REALLY FUCKIN OLD

it needs a refactor
