### ISSUE TITLE
Slimepeople sprites broken

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17715]
Slimepeople are invisible apart from the hair and the eyes; without clothes they are barely noticable.

On commit 561bdd08adfc85f0ad88ec231ee

![image](https://cloud.githubusercontent.com/assets/609465/15296257/727dfe54-1b8c-11e6-9228-357b2770fa06.png)

Possibly #17469 introduced this?

**Comment by Incoming5643** [comment]
Yep, I replaced a var with a flag forgetting that slimepeople are childs of jellypeople and that specflags don't inherit.

Easy fix
