### ISSUE TITLE
The chaplain soulstone on Metastation and Efficiency station is reusable

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17724]
![image](https://cloud.githubusercontent.com/assets/609465/15303779/8174b036-1bb1-11e6-90a4-f00fb26a08dc.png)

This is either balance, or an unintended side effect of Joan's changes, please discuss.

**Comment by Durkel** [comment]
#17722 
Hours ago I made the very same issue, don't call it a grave, this is the future you choose.

**Comment by KorPhaeron** [comment]
Bad balance, but not a bug

**Comment by coiax** [comment]
This issue would be tagged balance and not a bug if we weren't in the freeze, you just closing it to get da numbers down

**Comment by KorPhaeron** [comment]
Yes
