### ISSUE TITLE
You can use a soulstone multiple times on suicided corpses.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#17722]
A soulstone won't be filled/used up if it's used on a suicide. So you can soulstone multiple people with one shard.

Experienced this bug today on 5/16 where I was sharded by a chaplain on eff station, he then proceeded to shard another suicide with the same shard.

**Comment by KorPhaeron** [comment]
This isn't a bug, it was a questionable balance change (it works on all mobs like this)

**Comment by Durkel** [comment]
That's so stupid it hurts.
