### ISSUE TITLE
Pet Mimics

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#1775]
Vicious Mimic becomes as harmless as a puppy.

I would be mauled to death by the chair.

Chair refuses to harm me.

1.Staff of animate a mimic(might be structure specific)
2.???(have it kill someone?) (theory: have it incapicitate someone and pull the body away before it clears its target)
3.receive mimic who refuses to attack(unknown if hostile while provoked)

Chair still smashes windows.

Update: mimic finally switched target to poly and was ripped to shreds by polys claws(because it finally attacked).

Update2: Mimic was not targeting anyone nearby. Mimic was targeting mob 85, i was mob 130.

vars:
http://pastebin.com/KBvET3Uh

**Comment by phil235** [comment]
Did anyone manage to reproduce this?

**Comment by xxalpha** [comment]
not a bug

/mob/living/simple_animal/hostile/mimic/copy/ListTargets()
	// Return a list of targets that isn't the creator
	. = ..()
	return . - creator

**Comment by phil235** [comment]
Yeah, probably fixed.
