### ISSUE TITLE
Security Sprites are causing constant arguments and reverts and counter PRs, and are distracting from our maintainer's precious time

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#17755]
We should look into a way to have ALL security sprites without having to have maintainers waste time arguing over the color of a jumpsuit.

**Comment by PKPenguin321** [comment]
Oh boy this meme again

**Comment by KorPhaeron** [comment]
I assure you my time is worthless, there is no issue here

**Comment by PKPenguin321** [comment]
I can't find it right now because mobile but throwback to MSO's "Tesla is boring and shit" issue report
