### ISSUE TITLE
lube confuses xenos

### ISSUE THREAD

**Issue by anconfuzedrock** [tgstation/-tg-station#17769]
did I mention lube confusion stacks

**Comment by WJohn** [comment]
Latest pro starts: lubricate the xenos.

**Comment by LatD** [comment]
#17693 will fix the confusion and stacking, assuming xenos don't get slipped by the lube. If they do get slipped it makes sense for them to become confused too.

**Comment by Robustin** [comment]
Yea, thats why I kind of want to keep it like it is, minus the stacking.

Hulks and Xenos and whatnot should be confused since its supposed to simulate your ass trying to walk around while covered in lube.
