### ISSUE TITLE
You can't emag the shuttle currently.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#17776]
Attempting to emag the shuttle currently or at least for the round I was (9:18 est/5/18) Results in the error that the shuttle is already about to launch and the emagging failing.

**Comment by PKPenguin321** [comment]
i tried using Head IDs and only one worked, the rest would bring up the prompt to authorize and when i hit authorize nothing happened

**Comment by KorPhaeron** [comment]
@coiax

**Comment by Jalleo** [comment]
@Dorsisdwarf please tag bug.

**Comment by coiax** [comment]
It's a bug introduced by a test merge though, not on mainline. I've fixed it in my PR.

**Comment by Dorsisdwarf** [comment]
Oh, if it's testmerge then ded
