### ISSUE TITLE
Esword can light a cigarette but not ignite plasma

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17771]
CRITICAL IMMERSION FIX

**Comment by Niknakflak** [comment]
not a bug

**Comment by Crushtoe** [comment]
Cigarettes are made of special esword flammable fibers that ignite with the help of one.

Merely lore.

**Comment by PKPenguin321** [comment]
Not a bug, cigarettes are more flammable than plasma

**Comment by Dorsisdwarf** [comment]
FEATURE REQUEST? NOT A BUG? NOT A CRIPPLING BALANCE ISSUE?

GAME OVER
