### ISSUE TITLE
You can remove the reload from kinetic accelerators entirely

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#17782]
Reply PM from-BlessedHeretic/(Blessed H. Legionare): Replication : Shoot gun, put on belt, draw before it recharges  

@coiax

**Comment by KorPhaeron** [comment]
HELP: BlessedHeretic/(Blessed H. Legionare) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): Testing has proven it can be done up to 3, maybe 4 times. mechnically what is happening is your stacking recharges.

**Comment by KorPhaeron** [comment]
HELP: BlessedHeretic/(Blessed H. Legionare) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): had difficulty replicating it with low lag, because the recharge happens quicker than input without lag.

**Comment by kevinz000** [comment]
feature

**Comment by coiax** [comment]
kevinz liked something, quickly coderbus, nerf it

**Comment by Dorsisdwarf** [comment]
You decide

**Comment by xxalpha** [comment]
I coded it, it is a bug but it can be a feature.

**Comment by Robustin** [comment]
Definitely not a "feature", lets you instafuck anything on lavaland.
