### ISSUE TITLE
Drone dispensers aren't working

### ISSUE THREAD

**Issue by coiax** [tgstation/-tg-station#17790]
Apparently.

**Comment by Shadowlight213** [comment]
To clarify. they dont switch to the producing stage when they have enough materials.

The bug seems to only occur with dispensers that spawn any kind of drone, including the preloaded ones. (syndrones, snowflake, and normal) The hivebot and swarmer dispensers function normally

**Comment by xxalpha** [comment]
Did you try turning it off and back on again?
