### ISSUE TITLE
You can infinitely improve a KA with modkits...

### ISSUE THREAD

**Issue by Hatfish** [tgstation/-tg-station#17807]
...Despite it having no extra effect after the first modkit.  It just adds another improved to the name, like so:
![improved improved improved improved improved super-kinetic accelerator](https://cloud.githubusercontent.com/assets/8237862/15432788/a3af5a6a-1e7d-11e6-8a2f-b79046a727e0.jpg)

**Comment by xxalpha** [comment]
It's deep frying all over again!

**Comment by GunHog** [comment]
@Iamgoofball's legacy continues.

**Comment by TechnoAlchemisto** [comment]
working as intended

**Comment by xxalpha** [comment]
blob?
