### ISSUE TITLE
You cannot grind things in grinders.

### ISSUE THREAD

**Issue by TechnoAlchemisto** [tgstation/-tg-station#17813]
Juicing, however, still works.

**Comment by Boredone** [comment]
Still works with plants it seems, but not plasma bars (From what I've seen)

**Comment by TechnoAlchemisto** [comment]
The things I tested were Plasma, Iron, and Uranium.

**Comment by coiax** [comment]
This bug was introduced in e3729033d2bd310dffcf29c75ab62401a16a3201.
@MrStonedOne @RemieRichards

**Comment by RemieRichards** [comment]
Yeah the grinding list is associative, meaning it got kill'd by the updated proc.
