### ISSUE TITLE
Emitters beams are sideways

### ISSUE THREAD

**Issue by Nyvrem** [tgstation/-tg-station#17828]
![sideways emitters](https://cloud.githubusercontent.com/assets/10331933/15450108/11ae32b4-1f93-11e6-9e00-9e45ac415f2a.png)
Well obviously the sprites are in the wrong direction, the beams move horizontally but are orientated vertically.

**Comment by Bawhoppen** [comment]
its a pixel projectiles thing my friend that I was aware of

**Comment by Nyvrem** [comment]
Well now you can add "fixes #17828"

**Comment by phil235** [comment]
This bug comes from the test merge of pixel projectile #17735 , so this the issue comes from that PR, not the current tg code.
