### ISSUE TITLE
Tcomms script bloat the logs with their crap

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#1783]
When a Tcomm script is uploaded, all of their code is saved on the normal logs, but these end up bloating the files, at some points, being 50% of the txt.
The solution would be making a different log for Tcomms script, who instead of changing per round, it would create a new file per week/month.

**Comment by Chnkr** [comment]
Fixed by https://github.com/tgstation/-tg-station/pull/12105

**Comment by Aranclanos** [comment]
ez fix
