### ISSUE TITLE
Traitor Carp Plushie is invisible until after it is sprayed and becomes a mob

### ISSUE THREAD

**Issue by Man-Shroom-** [tgstation/-tg-station#17844]
Purchase a traitor carp plushie and you can see this bug easily. The first time I saw it was in a stealth nuke ops round and then a DA round later the same day. It is very difficult to keep track of items this way.

**Comment by PKPenguin321** [comment]
High priority because cham projector + invisible item = godmode

**Comment by phil235** [comment]
HBL said on irc that the bartender's damp rag was invisible. Both the rag and dehydrated carp use the toy.dmi icon file, so the problem likely comes from there. But since I don't see anything wrong with the dmi, it's probably linked to a test merged PR or something.
