### ISSUE TITLE
Solid Plasma Not Yielding Liquid

### ISSUE THREAD

**Issue by Skorvold** [tgstation/-tg-station#17862]
1. Insert Solid Plasma into a reagent grinder/blender whatever.
2. Grind
3. Receive nothing

**Comment by Boredone** [comment]
Likely fixed if reproduced on Sybil, server is just not updated with the fix. Can't tell on Basil if that's updated or not though.

**Comment by bgobandit** [comment]
specifically, likely due to https://github.com/tgstation/-tg-station/issues/17813

**Comment by ChangelingRain** [comment]
This is basically a dupe of that issue, so.
