### ISSUE TITLE
there are over 200 issues with either the 'feature request' or 'not a bug' tag

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#17861]
this may or may not be one of the reasons why there's almost 900 issues open.

**Comment by bgobandit** [comment]
congratulations for adding one more

**Comment by MMMiracles** [comment]
no this issue doesn't have the 'feature request' or 'not a bug' tag.

**Comment by MMMiracles** [comment]
FUCK

**Comment by Imagebard** [comment]
>Over 800 issues

Casuals.
