### ISSUE TITLE
Traitor Borgs slaved to Traitor AIs don't function properly

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#1796]
Observed issues:
-Borg's law 0 repeatedly gets replaced with "Accomplish your AI's objectives" instead of his own
-Borg is unable to hack itself, or scramble it's codes
-Upon detraitoring, borg suddenly gets the ability to scramble it's codes again
-Game messages keep telling the borg the AI doesn't know of its law 0 after being detraitored

**Comment by Dorsisdwarf** [comment]
@Cheridan 

traitor cyborgs were removed, were they not?

**Comment by Shadowlight213** [comment]
@Dorsisdwarf Traitor borgs were removed. This can probably be closed
