### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#1836]
Randomly, the server can crash at roundstart. Sibyl1, using box map, just now:

Away mission loaded.
Processing Geometry...
OOC: Kevinthezhang: I like the changes to cult
Geometry processed in 1.8 seconds!
Job setup complete
ADMIN LOG: Emitter deleted at (0,0,0 - JMP)
ADMIN LOG: Emitter deleted at (0,0,0 - JMP)
Initializing objects...

and there it finishes, the server stopped responding for everyone.

**Comment by CorruptComputer** [comment]
Was this fixed with Carn's MC rewrite?

**Comment by Aranclanos** [comment]
was this fixed?

**Comment by Jordie0608** [comment]
Yeah

**Comment by Aranclanos** [comment]
by who and when?
