### ISSUE TITLE
handcuff pulling

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#1840]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
2013-11-15
16b2bc833fd647e0abc347d7661111096d2d48ed

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Basil

###### What did you expect to happen? ######
To get removed from the on top of the trashcan

###### What happened instead? ######
My captors could not pull or grab me off the disposals bin

###### Why is this bad/What are the consequences? ######
They had to kill me to move me.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1.get cuffed(root cause)
2.climb into disposals(probably should be checking for cuffs) or something else?
3.get ejected by angry sec officers
4.they can't pull you off
5.honk

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
traitor

##### Anything else? #####
nope

**Comment by astralenigma** [comment]
Honestly I saw this bug too, It happens when for some crazy reason someone cuffs is able to get away from someone else that is pulling him. After they get escape they cannot be pulled again, I guess it has to do with a status var on a mob.

**Comment by phil235** [comment]
Not sure if this is fixed already , but the issue behind this is the buckled and pulling var aren't cleared correctly at one point so it's as if the mob is still buckled or handcuffed+pulled, which prevents pulling the mob.

**Comment by Jalleo** [comment]
@duncathan would the qdel del stuff detect this issue if the object is getting deleted that the mob is buckled to?

**Comment by Dorsisdwarf** [comment]
Who got rid of the "unresolved tag" damnit.
