### ISSUE TITLE
mind deadening handcuffs

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#1842]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
2013-11-15
16b2bc833fd647e0abc347d7661111096d2d48ed

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
basil

###### What did you expect to happen? ######
To woop my captors

###### What happened instead? ######
My telekinesis failed when i was cuffed

###### Why is this bad/What are the consequences? ######
They are hand cuffs not brain cuffs

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1.get tk
2.get handcuffed
3.cry as you cant interact
4.
5.

**Comment by phil235** [comment]
I'm closing this. It's understood that you need to move your hands to use telekinesis. See #6416
