### ISSUE TITLE
runtime error: bad client

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#1853]
runtime error: bad client
proc name: process (/obj/machinery/computer/telecomms/traffic/process)
  source file: traffic_control.dm,63
  usr: null
  src: Telecommunications Traffic Con... (/obj/machinery/computer/telecomms/traffic)
  call stack:
Telecommunications Traffic Con... (/obj/machinery/computer/telecomms/traffic): process()
/datum/controller/game_control... (/datum/controller/game_controller): process machines()
/datum/controller/game_control... (/datum/controller/game_controller): process()

This can crash the master controller

**Comment by xxalpha** [comment]
A null user causes bad client runtimes, that might have been the cause?

**Comment by Aranclanos** [comment]
ntsl removed
