### ISSUE TITLE
potentially infinite loop at server startup

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#1871]
/turf/simulated/mineral/New() handles spreading src.type to surrounding turf/simulated/mineral/New.

/turf/simulated/mineral/random/New() handles changing a turf's type to that of a specific mineral

The problem arises from random/New() immediately calling ..(). This means that mineral/random turfs are spreading to other mineral/random turfs to spawn a new mineral/random turf which then triggers New() and starts spreading....ad infinitum.

Somewhat serious issue, nobody in coderbus gave a flying fuck so making an issue here.

I have a potential solution coded already if you wish to discuss it on irc. I will not port it myself.

**Comment by CorruptComputer** [comment]
Was this fixed with Carn's MC rewrite?

**Comment by Aranclanos** [comment]
was this fixed?

**Comment by Jordie0608** [comment]
Yeah

**Comment by Anonus** [comment]
This was never an infinite loop anyway.

**Comment by Aranclanos** [comment]
by who and when?
