### ISSUE TITLE
Offline Bans do not remain

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#1873]
Revision: I typed !revision and got "Not in history", so this version is from the 21st of this month

Server: Yogstation

Problem Description
Our offline bans are not sticking. So far it does appear to be just offline bans. This is an example got from our logs:
Image

What did you expect to happen? The ban would stay for the duration noted

What happened instead? The ban lifted itself somehow

Why is this bad/What are the consequences?
Griefers got back onto the server

Steps to reproduce the problem:
((Hard to say considering the system unbanned them, not us))
1. Initiate the ban ((Offline banning)
2. Wait for the round to restart
3. They would become unbanned 
4.
5.

Possibly related stuff:

Anything else?

05rhardy of Yogstation's Bug report, Does not have a Github account so I have created the issue.

**Comment by MrStonedOne** [comment]
Somebody is gonna need to define "offline bans" as that term doesn't make any sense to me.

**Comment by Miauw62** [comment]
gotta love that descriptive image.

**Comment by astralenigma** [comment]
I think it's bans given to people not on server.

**Comment by Shadowlight213** [comment]
@RemieRichards was this bug fixed?

**Comment by Aranclanos** [comment]
did this bug ever exist

**Comment by MrStonedOne** [comment]
If the database is offline, and you ban somebody, and the database comes back, that legacy ban sits in limbo.

**Comment by tkdrg** [comment]
Can we just remove legacy bans

**Comment by Jalleo** [comment]
Or we could rework it so instead it sends that legacy ban over to the actual database once its online again.

**Comment by tkdrg** [comment]
That's way too much effort for something that nobody ever uses

**Comment by MrStonedOne** [comment]
Working as intended, legacy bans are not designed to auto integrate with the database, and the database going down mid round is no longer a contingency we support or plan for extensively

**Comment by astralenigma** [comment]
Are you sure this is not about people that leave midway the banning process? So that the database is unable to save the Computer ID and IP?

**Comment by tkdrg** [comment]
That's not how db bans work really
There's no ban "process" per se since the query uses data from the server. The report is about an issue caused due to bad hosting practices (putting the db remotely) which forced the code to use legacy bans, causing trouble once the actual db came back. thus my earlier comment

**Comment by astralenigma** [comment]
I mean sometime ago I tried to ban a person and they evaded ban, their name was still on the database with the ban but they could get in. They just didn't have the computer ID and IP in their list.

**Comment by tkdrg** [comment]
Well that doesn't happen when I ban someone, the ban process just either fails (if the mob ceases existing, as it tries to ban a null ckey) or uses that "get CID and IP from mob" feature that was added.

**Comment by astralenigma** [comment]
Then that probably got fixed haven't tried it recently.
