### ISSUE TITLE
Suiciding Doesn't Update Damage Overlays

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#1877]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
Server Revision: *unknown*

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Sibyl

##### Problem Description #####
Suiciding doesn't update damage overlays.
###### What did you expect to happen? ######
To have loads of visible arm and chest damage from slitting my wrists with a glass shard.

###### What happened instead? ######
No obvious damage, examine showed severe bruising and nothing else.

###### Why is this bad/What are the consequences? ######
You can't become a disfigured corpse from suiciding.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Get an object that does brute or burn on suicide, or both.
2. Suicide with it.
3. Watch as you die with burns/brute and no damage overlays.
4. Cry at lack of disfigured corpse.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
Nope.

##### Anything else? #####
Nope.

**Comment by phil235** [comment]
The problem isn't a specific type of suicide, it's that the damage dealt by suiciding is apparently distributed onto two random limbs, one gets 100 damage, the other 75. No idea why that is, but it means suiciding will sometimes not show any bruises because the limbs chosen are hidden by clothes.
