### ISSUE TITLE
Alt-click stat panel allows AI to see bloodrunes.

### ISSUE THREAD

**Issue by BestName** [tgstation/-tg-station#1951]
Server: Sibyl

Server Revision: 
2013-11-29
9d4a084b3587f3bb84ceb1337a24a34fa3d81c54

~~How to powergame:~~
Steps to reproduce the problem:
1. Become an AI
2. Use your metasenses to find a potential cultist (surprisingly easy)
3. Alt-click on them
4. Receive a list of objects on their tile, including bloodrunes.
5. "Cultist gg"

**Comment by francinum** [comment]
@Miauw62

**Comment by BestName** [comment]
Why? It hasn't been fixed.
