### ISSUE TITLE
APC nanoUI not working

### ISSUE THREAD

**Issue by KazeEspada** [tgstation/-tg-station#1978]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
2013-12-03
97c48e6fbe8c5bbab4fd4c488cddaf6b60913b14

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Basil

###### What did you expect to happen? ######
To be able to unlock the APC

###### What happened instead? ######
I tried to unlock the apc, and the nanoui dissapered.

###### Why is this bad/What are the consequences? ######
It takes two people to hack an APC.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1.get apc thats at very low charge
2.open it with screwdriver
3.hit it with multitool
4.two uis show up, a nanoui for the apc, and a popup for the wires
5.leave the nanoui open
6.pulse the unlock wire
7.nanoui will dissapear
8.You have to walk away(which triggers the nanouis autoclose) to get the Ui to work again.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
I have been having troubles with my plantmodifier ui, due to a var changing that changes the layout. This may be related.

**Comment by Jordie0608** [comment]
This got fixed at some point in time.
