### ISSUE TITLE
People can meta malf by locked blue APCs

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#1983]
Zoey Webb [145.9] says, " yah, APC is locked."
Zoey Webb [145.9] says, " And not unlocked like an Emag woulda left it."

oh god fuck the retarded text i wrote here

let's try again

The issue is not blue APCs themselves, as they have three possible causes: malf AI, emag, or ninja. The issue is that being able to tell that the AI is malfunctioning because a blue APC is locked, a small detail only discernible through metaknowledge, is shitty.

**Comment by Dorsisdwarf** [comment]
Closed by word of god (ITS NOT A BUG OR EVEN MUCH OF AN ISSUE)
