### ISSUE TITLE
AI in card magically comes back to the core

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#2021]
##### Server: 

Sybil

##### Problem Description
I was AI and was carded, at some point of time shuttle arrives, my cardbearer is being in maints not even close to escape, then after a few seconds im teleported from my card back to the core that someone dragged into the shuttle, i loose power and all that stuff
###### What did you expect to happen? 
Not to teleport from card back into core from distance of half the station

###### What happened instead?
I did

###### Why is this bad/What are the consequences?
Thats just very very weird

##### Steps to reproduce the problem:
1. Be AI
2. Be carded
3. Your empty core is dragged to powerless area
4. Some magic happens here
5. You are back into the core and depowered

##### Possibly related stuff:
Nothing

##### Anything else?
Didnt test, maybe unreproducable

**Comment by Dorsisdwarf** [comment]
Sometimes, BYOND just shits itself.
