### ISSUE TITLE
Cannot perform another surgery after completing eye surgery

### ISSUE THREAD

**Issue by Tenebrosity** [tgstation/-tg-station#2065]
I did eye surgery on an Assistant's eyes after they were blinded with a screwdriver. I even did the final step, cauterising the wound, even though it does nothing. For some reason the surgery only improved their vision slightly, so I placed them back on the operating table to perform it again. On help intent, I used the surgical drapes while still aimed at their eyes. I just slapped them in the head with the drapes repeatedly, thankfully doing no damage.

I hate to think this means that after eye surgery (or any surgery perhaps) that a person cannot receive any more surgery.

This brought to mind um, augmentations, which crew routinely get several of, so perhaps the issue is only with eye surgery, or maybe it had to do with me aiming at his eyes with the surgical drapes (I don't think it'd make a difference though).

**Comment by Miauw62** [comment]
Nobody can reproduce this.
