### ISSUE TITLE
Getting into a delivery chute when the adjacent disposal pipe is broken leaves you trapped

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#2101]
![](http://puu.sh/5SYH0.png)

You can't see it, but one of the disposal pipes above the chute isn't there anymore. At least two other people were in this chute with me, trying to get to disposals so they could escape cargo while injured without getting put into critical. I adminhelped and an admin moved me out of it.

This may be intended functionality, but I think it's pretty dumb.

**Comment by Razharas** [comment]
Shit cant be destroyed under walls without walls being destroyed anymore
