### ISSUE TITLE
Medibots, floorbots, cleanbots, securitrons can occupy the same tile as each other

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#2448]
Humans can occupy the same tile too, but only in circumstances like when one is lying down. Little robots can just stand on top of each other. It looks unnatural. When floorbots are set up near each other, they tend to clean the same tile due to this, making having more than one of them in one area redundant. So that's a practical reason to fix this.

**Comment by Dorsisdwarf** [comment]
There's no easy way to add this feature request (which is what it is) without messing up a lot of stuff for no real gain. And nobody seems to want to.
