### ISSUE TITLE
Smokeables bugs

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#2490]
* "You can't put that in the pipe." When lighting the pipe with a lighter.

* Emptying an unlit pipe gives you ashes

* Drying rack produces tiny sprites regardless of size of original produce

**Comment by Cheridan** [comment]
>he wasn't joking

**Comment by phil235** [comment]
About point 2, when you put dry grown in the pipe, you crumble it, which means that having the grown drop on the grown unchanged wouldn't be realistic. So using ashes for this isn't too unrealistic.
