### ISSUE TITLE
You can attack blobs that are behind other blobs diagonally

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#2664]
Basically, if you're the guy circled in red, you can attack the strong blob with the blue X on it.
This happens with all blob parts.
![sybil outpost 2014-02-06 142440](https://f.cloud.github.com/assets/3886584/2102891/d8ba6cb8-8f64-11e3-9d87-2413cb1f3593.png)
20 seconds in paint

**Comment by WJohn** [comment]
It's been deemed that this is an actual bug, even after all this time of being used like a feature.

**Comment by Incoming5643** [comment]
this is not a bug

**Comment by Anonus** [comment]
That previous title was rather unclear, implying that it was all diagonal attacks on blobs and not just the edge case.

**Comment by Miauw62** [comment]
i was about to post "what no?" but i guess this makes more sense.
probably an easy fix.

**Comment by Dorsisdwarf** [comment]
This is still active, tested 27/08/2015

**Comment by phil235** [comment]
I think the way to go is to change obj/effect/blob's density to 1 and then modify simple_animal/hostile's movements toward their target to always try to be in a cardinal direction toward their target (instead of diagonal). This would prevent the blob mobs from failing to attack humans stuck in the middle of the blob area.

**Comment by Anonus** [comment]
Even if it's cardinal, blob mobs won't go through the 'solid' tiles.

**Comment by phil235** [comment]
They do, I tested it.

**Comment by Razharas** [comment]
walk_to byond proc which we use to move mobs fails to move through dense blobs even if their canpass lets the bloblings in
I bet it just checks the density with no other things

**Comment by PKPenguin321** [comment]
look at that vintage green blob in the OP image

why cant we have nice green blobs like those nowadays
