### ISSUE TITLE
Xenobiology Doors Bugged

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#267]
Reported by Kyle.Noske, Feb 9, 2013
In order to fix this bug quickly and effectively we require detailed
information. Please try to be as descriptive as possible. Even if you feel
like something isn't a significant clue, it can't hurt to include it.

Revision that this bug was encountered on (REQUIRED!! Type 'show-server-
revision' ingame to find out - note that 'current revision' isn't
helpful!):
r5673

Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2,
Facepunch, Pinkstation, /VG/... etc.)
TG-Sibyl2

Problem Description (What did you expect to happen? What happened instead?
Why is this bad/What are the consequences?):

Xenobiology airlocks were both perma-locked. I tried unbolting them and they'd just instantly rebolt, hitting the switches on the doors didn't fix it, and trying to use the main control panel on the doors to unlock them just resulted in the new window constantly refreshing. Both doors were listed as 'unlocked'

Steps to reproduce the problem (remember to be specific! Those little
details can save us hours of work!):

1)I have no idea how it happened nor how to reproduce it
2)Mess around with the doors a lot?
Feb 9, 2013 Project Member #1 johnsonmt88
I think it's a problem with our airlock stuff in general. I'm pretty sure I've had this happen ages ago with virology/toxin's mix room doors before too.

**Comment by CorruptComputer** [comment]
Is this still an issue? I believe that cycling doors has been removed from the game.

**Comment by phil235** [comment]
I saw something similar happen with the double airlocks in toxins, but I think the issue was with the scrubber/vent failing to repressurize the space between the two airlocks and getting stuck in repressurizing mode. Did someone witness this with virology airlocks (which don't use pressurizing vents) ?

**Comment by Cheridan** [comment]
fixed by #9504
