### ISSUE TITLE
Officer spawning in maint

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#2707]
HELP: Tsaricide/(Ronald Jerome) (?) (PP) (VV) (SM) (JMP) (CA) : Is it normal to spawn in maint tunnels? 

he was the officer of cargo. He went afk after I answered the adminhelp honk honk

**Comment by Cheridan** [comment]
Doesn't happen anymore as far as I can tell.

**Comment by Aranclanos** [comment]
is it a configuration option to spawn in the rooms of the different departments? Because if it is, this should be re-opened.
Unless APCs changed and im not aware of it

**Comment by Jordie0608** [comment]
This isn't actually fixed, it's just that the teleporting doesn't happen at all due to the gamestate check being wrong.
