### ISSUE TITLE
Telescience is broken

### ISSUE THREAD

**Issue by Knoxon** [tgstation/-tg-station#2709]
Server Revision: 4d32946207c34e9e5c0f2f81e9fd1d9041e60ac4
Server: Basil
When looking at the Telescience computer it will say: No telepad located. 
Please add telepad data. As far as i can tell, there is no way to add the telepad data. No other options are available. On that note, screwdrivering the Telepad computer will dispense 3 bluespace crystals, which you can repeat for infinite bluespace crystals.

**Comment by phil235** [comment]
Is this fixed?

**Comment by Incoming5643** [comment]
it was never broken, just slightly hard to gleam that you have to use a multitool
