### ISSUE TITLE
Going through the away portal doesn't invert your movement direction or cancel your movement

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#2717]
You go up to enter the portal. If you hold it down while travelling through the portal, you end up travelling back. This makes you "flash" as you're travelling so fast. To fix this, travelling through the portal could cancel your movement so you have to release and depress the key again to continue or invert your movement on the other side of the portal so you move downwards while holding up until you release the button.

**Comment by Dorsisdwarf** [comment]
Feeture request
