### ISSUE TITLE
blobs in the shuttle can crash the server

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#2794]
Remember engiborgs using his RCD on the space near the shuttle? well, exactly the same but with blob "walls"

See, the shuttle is surrounded by some crappy objects that make mobs fly away, now, if the proc can be called an infinite numbers of time if the mob doesn't move due to something blocking the way, like a wall or a blob wall. This makes dream deamon freeze in an infinite loop.

**Comment by Jalleo** [comment]
@Carn would you be able to investigate this when you are back from your break on shuttles?

**Comment by Carn** [comment]
throwers were removed from map. issue is obsolete

**Comment by Jalleo** [comment]
@Miauw62

**Comment by Carn** [comment]
That being said, throwers are still technically broken. Maybe I somebody should remove them.
