### ISSUE TITLE
this monkey doesn't die!

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#2798]
![diemonkey](https://f.cloud.github.com/assets/701959/2176785/3f88324c-95df-11e3-988c-2ab508e07806.png)

this monkey had an advanced disease that introduced that oxygen damage. He never stopped gasping, his oxygen damage was at 200 yet he was still alive.

**Comment by phil235** [comment]
can't reproduce so I'm assuming this was fixed.
