### ISSUE TITLE
Cryo is weird for occupant

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#2844]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
2014-02-19
a92cce91639314c181ce71f9f5a7ee35567f6d98

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Private server

###### What did you expect to happen? ######
To have a clear and understandable way of leaving cryo, like moving out or resisting.

###### What happened instead? ######
You will convert to a normal sleep if fully healed.
Then you'll wake up, while still frozen.
When you move out of the cryo or resist to get out after waking up, you take burn damage from the cold.
If you're not fully healed there is no way to get out by yourself.

###### Why is this bad/What are the consequences? ######
This is weird.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
Get in cryo with full health.
Turn it on.
Wake up automatically.

Get in cryo with 99 health.
Turn it on.
Frozen forever.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
#2488

##### Anything else? #####
@Razharas

**Comment by Tenebrosity** [comment]
Still an issue, you really ought to be able to resist out of cryo so you don't get stuck in there for 10 minutes

**Comment by paprka** [comment]
Raz you seriously shouldn't have just removed the one thing that made cryo less shitty for occupants and then not document it in your machines PR

We need to fix this ASAP
