### ISSUE TITLE
Telekinetic grab left on the floor.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#3017]
Spotted on Sybil at about 4:15 AM PST March 7 2014.
![telegrab](https://f.cloud.github.com/assets/6583225/2356822/878d8ffa-a5f3-11e3-84e6-d71ea2d284e1.jpg)
Was observing when I spotted this at the dorms and took a screenshot. Somehow a telekinetic grab object ended up on the tile. Moments later, a player-controlled monkey walked in, picked it up, played around with the locker briefly, then dropped it, properly removing it.
I don't really have any additional data, other than that there was space retrovirus going around, and that there was a vortex anomaly floating around the escape wing.

**Comment by Cheridan** [comment]
this should be fixed. TKgrabs dont have NODROP but they have an overwritten attack procs
