### ISSUE TITLE
Attach signaller

### ISSUE THREAD

**Issue by TomFyuri** [tgstation/-tg-station#3075]
Doesn't seem like you can attach on door wire anything but remote signaller. Yet according to wiki it should be possible to attach for example voice analyser. So is it bug or wiki is wrong?

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
