### ISSUE TITLE
Simple_animals don't see disposals rides properly

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#3076]
1. Possess Ian
2. Go through disposals
3. See your camera stay in place in the Hop's office until you are ejected in disposals

**Comment by phil235** [comment]
This still happens and can be consistently reproduced.

**Comment by phil235** [comment]
Nevermind, still broken...

**Comment by Razharas** [comment]
Tested just now, by both varediting in, stuffing and posess juggling and entering the chute
All works
