### ISSUE TITLE
Chemical Spray working through a hardsuit

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#3201]
One squirt from a spray of unstable mutagen and you're instantly blind, deaf, tourette and seizure even though wearing a spaceproof atmos hardsuit with gas mask and internals. Does it spray some kind of quantum teleportation particles or why does it work through helmets and masks?

**Comment by Dorsisdwarf** [comment]
Was this fixed? @MrPerson

**Comment by Dorsisdwarf** [comment]
Tested and found to be no longer the case. The only reagant working through hardsuits is pepper-spray, because that targets the eyes.
