### ISSUE TITLE
Exploded emagged borg game rejoin glitch

### ISSUE THREAD

**Issue by sitp** [tgstation/-tg-station#3251]
##### In order to fix this bug quickly and effectively we require detailed information. Please try to be as descriptive as possible. Even if you feel like something isn't a significant clue, it can't hurt to include it. #####

I was playing as an emagged borg, and I was locked down and exploded. My connection closed, and when I was to rejoin the game, I was brought back to the lobby.

##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####

2014-03-23
ad43f3ecbac87f557d21662c435529859353f127

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####

Basil

###### What did you expect to happen? ######

I expected to just be a brain after getting blown.

###### What happened instead? ######

I was kicked out of the game and when I rejoined, I was in the lobby!

###### Why is this bad/What are the consequences? ######

People can REALLY abuse this and that's a very bad thing!

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Be an emagged borg (I was an engineering borg if that makes the difference)
2. Get locked
3. Get blown
4. I have a fire extinguisher on slot 1 and a flash on slot 3 (if that makes a difference)

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####

Nothing ordinary.

##### Anything else? #####

I reported it to NikNakFlak in-game, and they sent me here to report this. Hopefully you all can repeat it because that was weird as fuck.

**Comment by Miauw62** [comment]
turns out this is actually a qdel() issue with mmi not being set to null after it's qdelled.
