### ISSUE TITLE
Follow doesn't work

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3256]
I was a ghost and tried to follow an unknown with the command, by typing follow and then selecting the mob from the list.
The unknown was a clown, the ones from the shuttle I think? Maybe not, I'm not sure because I couldn't follow him.
It was something like "Uknown[Clown]"

Double-clicking to follow works.

EDIT: I can reproduce, one moment please.

**Comment by Cheridan** [comment]
clown problems were fixed and this was by proxy
