### ISSUE TITLE
Blobs aren't getting the "YOU'RE GOING TO BE THE BLOB" at roundstart

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3270]
SERIOUSLY BLOBS POP OUT AND THEY HAVE NO IDEA THAT THEY WERE THE BLOBS WHO BROKE THIS

**Comment by phil235** [comment]
Pretty sure most blobs do get a message. Has anyone seen this bug happening recently?

**Comment by Jordie0608** [comment]
I haven't seen anyone with issues about it for a while.

**Comment by Aranclanos** [comment]
then close it fag its a year old very noticeable issue
