### ISSUE TITLE
Everyone freezes

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3299]
apparently everyone can freeze in the spot unable to make any actions for no reason. This lasts like a minute. Players CAN talk in say or OOC.
I have no idea what causes this.

**Comment by Firecage** [comment]
Well, for me this isn't anything new. It happens less these days, sure. But I remember it sometimes happening on other Byond games aswell. Everyone freezing, and only being able to talk. So yah, this is definitely a Byond issue, unless SS13 is producing a similar issue to it somehow. Tis called Screenfreeze.

**Comment by Flecker** [comment]
I have heard before that sometimes the server freezes in game to take a quick log of all objects, but only happens everyone in a while, and has a problem where it does it for a long period of time

Don't quote me on this

**Comment by Cheridan** [comment]
Doesn't seem to happen anymore, marking this as closed.

**Comment by Jalleo** [comment]
I would suggest we compile a list of stuff we should watch out for.
