### ISSUE TITLE
Things that need click cooldown

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3316]
Comment here if you think that someone needs a click cooldown!
-Alien reisins
-Space kuzdu
-Spray bottles
-Turrets
-Overriden machines (aren't those mobs?)
-Spiders
-Bots (beepsky, medborg, etc)
-Welders on borgs (maybe other tools?)
-simple animals

**Comment by Jalleo** [comment]
@tkdrg should we make a new issue report of this and make it using the check listbox?

**Comment by tkdrg** [comment]
Sure why not. Most of these are fixed though.

**Comment by Dorsisdwarf** [comment]
Closing for new, more accurate issue report
