### ISSUE TITLE
Ninja objectives

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3352]
snip was Shinobi Hiro (survived)
Objective #1: Nothing Fail.
Objective #2: Slay Erlang Gaseron, the Assistant. Success!
Objective #3: Download 20 research levels. Fail.
Objective #4: Steal the brain of Chip Moon. Fail.
Objective #5: Stay alive until the end. Success!
Objective #6: Let no one question the mercy of the Spider Clan. Ensure the safety of all non-essential personnel you encounter. Fail.

See: objective 1

**Comment by astralenigma** [comment]
PR #8261 Should have fixed this.

**Comment by WJohn** [comment]
This is still around, I was a ninja earlier today and still had the nothing objective, although I somehow succeeded that (possibly admins? I dunno)

**Comment by astralenigma** [comment]
Honestly nothing objective is always success as far as I saw.
The nothing objective is strange but could be the place where admins put the RP objective.

**Comment by Dorsisdwarf** [comment]
the Nothing objective is now auto-success, not auto-fail, ninjas dont get bumfucked anymore

**Comment by Aranclanos** [comment]
the nothing objective still exists?
