### ISSUE TITLE
Prisoner IDs not working in prison area

### ISSUE THREAD

**Issue by cultist-chan** [tgstation/-tg-station#3402]
Might be a isolated bug. Ask rockben for details.

**Comment by Deantwo** [comment]
That sure is useful to know.
@Rockdtben

**Comment by francinum** [comment]
What do you mean by Not Working?

**Comment by Thunder12345** [comment]
Tried all the doors in perma on box using a prisoner ID, all interior doors opened, and the doors into the prison hallway didn't open, as expected. ID has an empty access list, also expected. Need more details to be able to reproduce this.

**Comment by MrPerson** [comment]
This issue is absolutely useless. I have no idea what the problem is. Make a new one and follow the template.

**Comment by Thunder12345** [comment]
Request console in the gulag to claim your points is missing. Maybe this is what they were referring to?
