### ISSUE TITLE
Changeling doesnt HUD update during power use or death, fringe disaster issue.

### ISSUE THREAD

**Issue by Zelacks** [tgstation/-tg-station#3449]
The problem is that, when you die, the HUD doesnt update.
Also when you use powers, the HUD doesn't immediately update.
Therefore there is a short span where if you die and you cast a power, the power spent will not be displayed properly.

In the following picture, the changeling used the Epherphine Overdose ability, as he was being lasered to death, so it probably occurred just before death.
Of course, this is terrible because the user doesn't understand why they cannot use the power, the HUD clearly shows they have enough chems but in reality they have no chems.
![Changeling power Issue](http://puu.sh/8dt4Y.jpg)

How to reproduce:
1. Be a changeling
2. Gain any power that has a charge cost
3. Gain a method to instantly kill yourself. It is pretty reliable to use the edit variable command to deal a large amount of damage on yourself, enough to instantly kill yourself
4. Cast the power and then IMMEDIATELY KILL YOURSELF. I aligned the deal damage window above the power button so I could quickly press okay after casting the power
5. The HUD should not update once dead, and display the previous value

This example shows the reproduce steps aftermath. See the variables are mismatched with the HUD
![Changeling power Issue](http://puu.sh/8dunr.png)

**Comment by Dorsisdwarf** [comment]
Changelings regenerate chems while dead now, issue no longer an issue

**Comment by Zelacks** [comment]
praise the lord
