### ISSUE TITLE
Explosion blasts wire/pipe on a tile but leaves floor tile intact.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#3513]
SUMMARY:

Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!):
2014-04-15
362a428

Which server were you playing on?:
Basil

Problem Description
What did you expect to happen?:
I expect any explosion that blows a pipe or wire that is hidden under a floor tile to also blow/damage that floor tile. I also expect the undamaged tiles to have protected the wires/pipes below them from damage.

What happened instead?:
The floor tile is pristine clean and the pipes and wires underneath it have been blown to pieces.

Why is this bad/What are the consequences?
This makes repairing the damages into a puzzle game, you have to use the T-ray scanner and crowbar to check under each undamaged floor tile still somewhat close to the explosion to see whether the gas pipes and disposal pipes have been damaged. The blown wires in that situation appears over their undamaged tile (how did it pass through the tile??) which means you have to crowbar the tile to fix the wiring.

Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!):

* Make an explosion
* check below the non damaged floor tiles close to the explosion.
* Find broken wires/pipes

**Comment by Razharas** [comment]
Good way would be to have turf a list of things then are "under" it, like tator bags, pipes wires and disposals
Meh way would be to add the check for being under the tile to ex_act of all these things
