### ISSUE TITLE
VV image

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3551]
![fakedisposal](https://cloud.githubusercontent.com/assets/701959/2812310/d199acfe-ce4e-11e3-92bb-4395cd864872.png)

Sometimes the VV image is incorrect, showing the icon of the last VV window that you opened. I'm not sure what causes this, but it's easy to reproduce.
Usually I get it by opening two VV windows, closing them and then opening a new one. The new one will have their sprite mistaken.

**Comment by Dorsisdwarf** [comment]
Closed for age and unreproducability

**Comment by Miauw62** [comment]
nope, still happens.

**Comment by Dorsisdwarf** [comment]
Closed for your issue report being better
