### ISSUE TITLE
preview on player preferences might not update both images

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3553]
![preferences](https://cloud.githubusercontent.com/assets/701959/2812392/b7f3705e-ce54-11e3-8789-18b8b89a2cc5.png)

![preferencesrandom](https://cloud.githubusercontent.com/assets/701959/2812394/dd6a9dc6-ce54-11e3-851f-a7868d5fc419.png)

One of the two images don't update sometimes.
On the first case, I changed the [high] job, on the second one, I pressed random character. It happens quite frequently, but I don't know what triggers it.
Both left and right might not update, it's not about a specific one.

**Comment by JJRcop** [comment]
Still an issue? #13184 may have fixed it

**Comment by phil235** [comment]
I can't reproduce this no matter how many times I click "Random Body", and I've never witnessed it while playing. So I'm going to assume this is fixed, especially since 13184 changes how previews are done.

**Comment by Aranclanos** [comment]
the previews got revamped so yeah
