### ISSUE TITLE
intercoms don't update their interface on range

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#3587]
UNLESS you're next to it. If you're a borg, that tries to change an intercom's frequency or activate or deactivate the microphone or speaker, the interface won't change, but the inputs will be taken by it.
This DOESN'T happen if the borg is next to the intercoms

pAIs have the same problem with their own station bounced radio

This problem doesn't happen to AIs

**Comment by MrStonedOne** [comment]
@neersighted this sounds like something you could fix by applying some NANO

**Comment by tkdrg** [comment]
fixed by tgui
