### ISSUE TITLE
Status display letters are horrible and blurry

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#3613]
It's hard to even tell what they are.

Yes, I use stretch to fit, but the letters are still blurry when you don't use stretch to fit.

Also, the scrolling is terribly chunky

**Comment by Dorsisdwarf** [comment]
Letters seem crisp to me. Do you mean the aliasing around the edges?

**Comment by Miauw62** [comment]
yes, anti-aliasing makes things look blurry.

**Comment by MrStonedOne** [comment]
Fixed in 509 http://www.byond.com/forum/?post=1959888
