### ISSUE TITLE
Teleporting while jaunting is broken

### ISSUE THREAD

**Issue by Perakp** [tgstation/-tg-station#3622]
OOC:  Bluespace: i jaunted
OOC:  Bluespace: then i teleported
OOC:  Bluespace: and when my jaunt ended, i teleported back
OOC:  Bluespace: and was promptly buttbashed

This is caused by the fact that the jaunt holder object is not teleported when you teleport, but when the jaunt is over you are put at the holder's location. Easiest fix: can't teleport while jaunting.

**Comment by Dicks1** [comment]
Had this happen to me today
Jaunted,tried to teleport,teleport went on cooldown but I didn't move and then was murdered.
