### ISSUE TITLE
Grabs don't prevent restrained people from moving

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#3801]
How to reproduce: cuff or straitjacket a person, then passive or aggressive grab them and watch as they run off because grabs don't stop them from wiggling those feet.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.

**Comment by Anonus** [comment]
Discretion is the better part of not starting a shitstorm.
