### ISSUE TITLE
AI "Bolt and Shock All Doors" Ability Effecting Off-Station Areas

### ISSUE THREAD

**Issue by TimrodDX** [tgstation/-tg-station#3948]
I can't find the template, so here goes:

What Happens: AI uses the 'bolt and shock all doors' malf ability. Doors that are not on station (and not even powered) in areas such as the DJ Station, Derelict, and Abandoned Ship/White Ship will be bolted/electrified.

What Should Happen: These doors should not bolt or electrify, as the AI has no control over them.

**Comment by Jordie0608** [comment]
This was fixed in #6968
