### ISSUE TITLE
Syndicate ending message doesn't include telecrystal cost from syndiborgs

### ISSUE THREAD

**Issue by Changelingrain** [tgstation/-tg-station#3977]
Say you buy a syndiborg and a bunch of other stuff that costs 45 crystals total.
The ending message will show 20 telecrystals spend and not 45.

**Comment by JJRcop** [comment]
Is this still an issue?

**Comment by Anonus** [comment]
I haven't checked recently, but I think it still is.

**Comment by JJRcop** [comment]
I haven't found an effective way to test it on my own yet.
