### ISSUE TITLE
People having surgery being preformed on them can cause the surgery to become uncompleteable

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#3991]
And all they have to do is get up and move a bit, at which point you can't finish or stop the surgery.
:eight: to 4000

**Comment by Anonus** [comment]
I remember this happening a while ago but maybe it got fixed at some point.

**Comment by Jalleo** [comment]
@phil235 @Core0verload this able to be reproduced at all if not shall we close it until a new report occurs?
