### ISSUE TITLE
Ministation - Cryo doesn't work

### ISSUE THREAD

**Issue by SodiumShine** [tgstation/-tg-station#4041]
On the ministation, the cryo cell doesn't fill with any gas and therefore doesn't get cold or use up any chemicals inserted.

Can be quick fixed by un-wrenching the pipe under it and then putting it back, but no indication is given that this is needed. Cell then fills with gas after it is replaced (If gas is available)

**Comment by Cheridan** [comment]
fixed by #6523 i think
