### ISSUE TITLE
Chaplain's bible spawn easily breaks

### ISSUE THREAD

**Issue by Kelenius** [tgstation/-tg-station#4052]
I mean really, the menus are presented to you at roundstart, and if you get a lag spike and disconnect for a moment, or something happens to your internet before you select names, everything breaks. This leads to you not getting a bible (annoying) and not being able to choose name of deity and religion and bible's appearance (very annoying).

I suggest it's made so chaplain starts with an item that, when activated, gives him these choices and spawns bible once you answer the questions.

**Comment by phil235** [comment]
related: #3558, #928
