### ISSUE TITLE
[DISCUSSION] We need an antag datum.

### ISSUE THREAD

**Issue by Giacom** [tgstation/-tg-station#4085]
Currently we have to check for every antag type for all admin tools and gamemodes. We could remove the bloated code by giving the mind datum an antag datum, like the changeling datum. We could then convert the changeling datum to be a child of the antag datum.

This would then make it easier to create different types of antags without having to touch everything to integrate them. This would also allow us to remove equip() code that is created in the gamemode datum and move it to the antag datum. This will then make it easier to make gamemodes which involve more than one antag type.

**Comment by Dorsisdwarf** [comment]
Old abandoned discussion

**Comment by duncathan** [comment]
But closing this makes the milestone completion bar inaccurate nooo
