### ISSUE TITLE
Improper handling of movement and bumping

### ISSUE THREAD

**Issue by balohmatevz** [tgstation/-tg-station#412]
This has been an issue since goon code r4407 all the way up to revision 300 and whatever past we are on github now.

The problem is described in detail in this thread:
http://forums.nanotrasen.com/viewtopic.php?f=7&t=13025

The solutions are:
- Apply the suggested map fix (easy 'quick fix'. The third step is really difficult and time consuming, but required if the second step is applied, so this step might just 'have to do for now(read: ever)')
- Make the proc call Bump() on EVERY object in the object type group that needs to get bumped. (By object type group I basically mean 'nonborder objects on start tile', 'border objects on start tile', 'border objects on target tile', 'nonborder objects on target tile'. So each for loop.)
- Fix any issues this causes (for example, trying to move onto a tile with two electrified grilles would cause you to get shocked twice)

**Comment by Aranclanos** [comment]
haha

**Comment by Miauw62** [comment]
wow rude

**Comment by hornygranny** [comment]
Wow rude

**Comment by RemieRichards** [comment]
edur woW
