### ISSUE TITLE
Can't join as Captain when you're the only player online.

### ISSUE THREAD

**Issue by Limeliz** [tgstation/-tg-station#4120]
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
d497387355dc77560ba92d1b7892744389514863

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Basil

###### What did you expect to happen? ######
Being able to join as captain from the lobby when you're the only player online.

###### What happened instead? ######
"Error setting up secret. Reverting to pre-game lobby."
Lobby countdown restarts from 120s.

###### Why is this bad/What are the consequences? ######
If the server has no players then you can't join it and start playing as captain. If you're alone on the server you'd probably want all-access so you can run the whole station by yourself (or learn every profession).

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Connect to an empty server.
2. Select Captain as your job.
3. Declare ready.
4. Watch as game never starts.
5. Select Head of Personnel as your job instead.
6. Watch as game starts when lobby countdown reaches 0.

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
Secret. I'm the only player.

##### Anything else? #####
Seems like to happen due to Captain not being able to become antag.
Suggested fix: Make it possible to start a game of secret gamemode with no antags, if the all players have choosen jobs which can't be antag.

**Comment by Miauw62** [comment]
According to @firecage, this issue is no longer valid. With protect authority roles from antag off, it will just make you antag captain, and with it on it will give you a role that isnt captain (which is very much intended behavior, since antag rolls are before job selection rolls now)
