### ISSUE TITLE
Disposals and bombs?

### ISSUE THREAD

**Issue by Spacemanspark** [tgstation/-tg-station#4129]
This occured on Sybil.
Near the end of the round, someone constructed a disposals chute that lead to the Cargo disposals area. I happened to walk right into it. When I arrived at Cargo, a bomb was also on the treadmills. It went down the other disposals (Right to the garbage room or whatever it's called.). I quickly dived after it, figuring I might be able to disarm it. I managed to get into the disposal chute when BOOM, it blew up. I was, apparently, invincible (I had the black pressure notification and the freezer notification.), had a black screen, and unable to talk ICly at all. OOC worked just fine, and I was able to move items in my inventory around. Upon relogging, I found I was in space for some reason, drifting away. I also started to take damage again. Dunno what happened here.

**Comment by Fox-McCloud** [comment]
Going to guess that https://github.com/tgstation/-tg-station/pull/11505 may have solved this, but I could be wrong.

**Comment by Spacemanspark** [comment]
I'd forgotten about this issue's existence.

**Comment by MrStonedOne** [comment]
This was mostly fixed in a rewrite of explosion code.

**Comment by tkdrg** [comment]
closing as fixed
