### ISSUE TITLE
Atmos Canister Loop Doesn't Repressurize Correctly

### ISSUE THREAD

**Issue by TimrodDX** [tgstation/-tg-station#4159]
What Happened: I was Atmos. I removed the pump that goes from the right-side canister loop to the waste loop and replaced it with a third freezer. I then filled the pure loop with oxygen using volume pumps going from the oxygen storage tank to the canister loop (Oxygen Out, Oxygen to Pure, Pure to Outlet, Mix to Outlet). I attached three empty canisters to the outlets and started pumping in the oxygen, then set the pumps to 265.15 Kelvin. 

What wound up happening is first that the readings were way off - the freezers stopped pumping at what they said was 265.15 Kelvin, but using an analyzer on the pipes or canisters or looking at the gas meter gave a reading of 285 Kelvin.

I filled my Extended Cap Oxygen Tank from one of the canisters, removing some kPa of Oxygen from it. The canister did not re-pressurize, despite having oxygen constantly pumped in to the max amount (9014.something) by the volume pumps. I disconnected and reconnected the canister,which caused the pressure to shoot up to 9235.something. The freezers were reading in the high 8900s for pressure.

What Should Happen:

The temperature on the pipes and canisters should match the readings on the freezer. The canisters should re-pressurize when pressure is taken out as long as the volume pumps are still pumping in. They also shouldn't magically gain 200-something kPa of pressure simply by being disconnected and reconnected.

**Comment by Dorsisdwarf** [comment]
Better late than never

**Comment by duncathan** [comment]
the best part is that the next issue (#4161) has the atmos tag and that they were made on the same day

**Comment by MrStonedOne** [comment]
this was fixed by me and @duncathan
