### ISSUE TITLE
Atmospherics Bug (Filter related), Generate air out of nowhere!

### ISSUE THREAD

**Issue by borntohonk** [tgstation/-tg-station#4161]
The air comes from nowhere, as seen in the pictures. that filter is producing 4500kpa air out of nowhere, i noticed the meter increasing after i set it there, and decided to analyze the pipes to find out what was going on.

and then i cleared out and backtraced the pipes, and saw that were was no source.

Whose the wizard behind this?

none of the valves were open, and never have been troughout the shift, which is what the red circles is trying to point out, incase that is misinterpreted.

![1](https://cloud.githubusercontent.com/assets/6264306/3586019/2aa008fa-0c2c-11e4-8f95-9352a437188d.jpg)
![2](https://cloud.githubusercontent.com/assets/6264306/3586020/2d3d7c8c-0c2c-11e4-8612-6692681152a7.jpg)
![3](https://cloud.githubusercontent.com/assets/6264306/3586022/2f32184a-0c2c-11e4-9339-6dcf1870a2ae.jpg)
![4](https://cloud.githubusercontent.com/assets/6264306/3586023/31394b68-0c2c-11e4-9773-a7956c1f6b01.jpg)
![5](https://cloud.githubusercontent.com/assets/6264306/3586025/345be422-0c2c-11e4-9a5d-b35e992ae1e5.jpg)
![6](https://cloud.githubusercontent.com/assets/6264306/3586026/368f2434-0c2c-11e4-9656-13363124b0f9.jpg)

**Comment by duncathan** [comment]
This may have been resolved; pipenets have gone through a lot.
