### ISSUE TITLE
DNA and Species issues

### ISSUE THREAD

**Issue by SodiumShine** [tgstation/-tg-station#4171]
Lizardpeople and other species don't seem to work well with DNA and genetic changes.

Injecting a humans DNA into a lizardperson will not stop them from being a lizardperson,and vice versa.

Space Retro virus also does not change the appearances of other species.

**Comment by Dorsisdwarf** [comment]
Can anyone confirm this is Still A Thing?

**Comment by Razharas** [comment]
DNA injectors do not transfer species
It was never intended to transfer species

**Comment by phil235** [comment]
Yes, this is still a thing, it's not really a bug per se and more of a feature request.

**Comment by duncathan** [comment]
feedback forum
