### ISSUE TITLE
Statued mobs can use PDA's

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/-tg-station#4199]
Revision:
2014-07-13
2529ac8cd2065165eecb6d63c43806ff5551587f

Server: Sybil

Reproduction:
Have wizard use statue spell on another human
Have statue'd human use PDA
Statue'd human is able to pull PDA out of it's slot and has full control of PDA, flashlight, ability to send & receive messages, ect.

**Comment by Dorsisdwarf** [comment]
Confirmed and tested 27/08/2015
