### ISSUE TITLE
getting the AI inside of the transport-tube thingie

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#4204]
If you get an AI inside of one of those tubes it's impossible to get them out, the AIs can't move on their own so they end up there, stuck.
I'm talking about the tubes between the station and the AI sat.

**Comment by Jalleo** [comment]
@tkdrg was a fix made for this in the end?

**Comment by tkdrg** [comment]
Nope.

**Comment by xxalpha** [comment]
How did you get an AI inside a pod in the first place? I can't get any kind of structure to enter the transit pod.

Can't reproduce.

**Comment by Aranclanos** [comment]
AIs aren't structures

**Comment by xxalpha** [comment]
They still don't go in.

**Comment by Jordie0608** [comment]
It's definitely happened; I've teleported AIs out of transite tubes after being pushed in (by a borg I think)

**Comment by Jalleo** [comment]
Why not add a simple empty hand click action to eject people?

**Comment by MrStonedOne** [comment]
This was fixed, transit tubes now have an eject contents verb

**Comment by MrStonedOne** [comment]
And on the topic of rather or not this can even happen, inactive ais are structures, active ais are mobs.

Only one of those can go in a tube
