### ISSUE TITLE
latejoin with no gravity mobs don't bounce

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#4225]
if you latejoin with the gravity generator off, your sprite won't "bounce" because of the lack of gravity. 
This confuses players a LOT

**Comment by xxalpha** [comment]
I think this is fixed.

**Comment by tgstation-server** [comment]
Mobs check gravity on life now. So it *should* be fixed

**Comment by Aranclanos** [comment]
gravity being checked in life it utterly shit 👌

**Comment by Iamgoofball** [comment]
:👌)
