### ISSUE TITLE
Corpses bouncing with gravity on.

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#4227]
I don't exactly know how to reproduce, but it's really common to see corpses who died on an explosion and were exposed to space, to see them bouncing on the station, with gravity on.
For example, a bomb blows up and someone dies in space, the corpse starts bouncing in the space breach, once they are dragged back to the station, they don't stop bouncing.

**Comment by phil235** [comment]
Fixed by myself, life() now calls the proc that handles gravity.
