### ISSUE TITLE
stripping and handcuffing don't respect the victim's movement

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#4228]
Basically, if the victim moves and comes back, he will be handcuffed or stripped.
Steps:
1- start handcuffing or stripping a person
2- the victim moves from the spot while you're waiting for the timer to end
3- the victim comes back to the turf where he was at the start of the handcuffing/strip
4- the handcuffing/strip is a success

**Comment by phil235** [comment]
Not sure if this is still a problem. This can still happen but only if the mob moves back pretty quickly. I guess it's only an issue when the code uses do_mob and do_after with a long duration and without adjusting the numtick argument accordingly, which means the checks are in some case done only every 1-2 seconds.
