### ISSUE TITLE
Cultist Shades released by non-cultists is very abusable

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#4276]
HELP: RandolfTheMeh/(Shade of Alias Coldwood) (?) (PP) (VV) (SM) (JMP) (CA) : Alright, this is weird. We were made shades by the cult, but then the HoP was the one who released us, making us bound to the HoP's will, who is not a cultist. What the hell do we do? 

Basically, I'm getting shades with cult vision, status and objectives with non-cultist masters. If they are to remain loyal to their master, then their ability to identify cultists will be very abusable.

Either way it's unintuitive, and would need a code solution.

**Comment by paprka** [comment]
this is fixed now isn't it?

**Comment by Miauw62** [comment]
yeah
