### ISSUE TITLE
Unpowered door behaves as if it had power during certain actions.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#4304]
Revision that this bug was encountered on:
No idea, I found the bug a few weeks ago.

Which server were you playing on?
Sybil

Problem Description

I was clicking a completely unpowered door (no APC power) and pulsing its wires.
What did you expect to happen?

I expected the door clicking w/o the proper access needed not to show the deny animation because of lack of power. I expected pulsing the bolt wire to not toggle the bolts as the test light wire and door power were off.

What happened instead?
Clicking the door w/o access triggered the 'deny' animation of the door, despite having no power. Pulsing the bolt wire toggled the bolts (making them fall or go up, it works in both case) despite  the test light wire and door power being off.

Why is this bad/What are the consequences?
Realism. You can't toggle the bolts when the test light wire has been cut or pulsed to "off", so logically, it also shouldn't work when the test light wire and power are off due to lack of APC power.

Steps to reproduce the problem:

* Remove APC power cell or destroy APC.
* click and pulse the wires of the doors in the now powerless room.

**Comment by MrStonedOne** [comment]
the bolt wire issue was accidentally fixed in #4728 when they merged hasprimarypower into haspower

fix for the deny animation issue coming up.
