### ISSUE TITLE
Ministation: cargo ordered hydrotray have outdated icon.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#4305]
On ministation, ordering new hydrotrays via cargo gives trays with older icon, the tray's icon updates back to normal icon when screwdriving the hose.

**Comment by phil235** [comment]
Closing this since we no longer use Ministation.

**Comment by phil235** [comment]
Reopening since we do use Ministation sometimes.

**Comment by Bawhoppen** [comment]
to be fair if we are using ministation its not for a normal round
