### ISSUE TITLE
same objectives!

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#4314]
Objective #1: Steal the captain's antique laser gun.
Objective #2: Steal the captain's antique laser gun.

This can happen to normal tators, objective 3 being escape alone

**Comment by Dorsisdwarf** [comment]
Will close in a week if not reporoduced due to age

**Comment by Aranclanos** [comment]
just check the code fam

**Comment by AnturK** [comment]
This one's fixed already

**Comment by KorPhaeron** [comment]
@tkdrg 

Anturk says its fixed
