### ISSUE TITLE
Never told of personal antag status

### ISSUE THREAD

**Issue by Zswords** [tgstation/-tg-station#4339]
For one double agent round, I was someone else's target despite the fact that I was not an antag. There was no message at the start of the round, and my notes where empty (barring the usual pin) Yet at the end of the round I still showed up on the list of traitors, and was someone elses target.

**Comment by KorPhaeron** [comment]
@tkdrg 

I think this guy just missed his objectives

**Comment by tkdrg** [comment]
Well yes considering this hasn't happened in literal years, and there's no actual useful information here about it, I think it's probably safe to close this.
