### ISSUE TITLE
Borgs and antag HUD icons

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#4342]
- Borgs synced to a malf AI need a HUD icon, much like rev or cult, that displays to other malf borgs or the AI. This will help them determine whether other borgs are friendly (to them), so that they can ahelp if a borg synced to a malf AI is griefing or just not AI synced (this has happened many times, trust me)

- Syndicate borgs, IE, borgs with the 'syndicate agents' lawset (this includes borgs emagged by syndie borgs or agents) need the syndicate nuke op icon that displays to nuke ops and other nuke op subverted borgs so subverted borg teamkilling doesn't happen. Emagging station borgs as a syndicate borg or nuke agent would be a much more effective strategy this way as well.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
