### ISSUE TITLE
Changelings can absorb some mutantraces they shouldn't

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#4435]
Golems, skeletons...
I'll accept them eating plantpeople and even shadowcreatures but there's nothing to eat in solid stone or walking bones.

**Comment by Dorsisdwarf** [comment]
over a year old and still unloved.
Closed and tagged [unresolved]

**Comment by Aranclanos** [comment]
wait what
don't close issues that still exist wtf
