### ISSUE TITLE
facehugger commits unspeakable lewd acts on dead ian

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#4510]
What happened: http://imgur.com/FMLSl48

When Ian (and/or regular corgis I assume) is dead it screws with the sprite placement for facehuggers, resulting in... that. (When you rotate Ian it appears in the middle of his body - basically it assumes Ian is alive and places the facehugger sprite where it would go if that were the case.

**Comment by phil235** [comment]
How about simply making corgis not huggable? It's weird that you can hug Ian but not Pete or Runtime.

**Comment by WJohn** [comment]
You know I actually have sprites for space carp, goats, and cows to all be huggable. I think it'd be nice to increase the variety of what can or can't be hugged.

**Comment by Cheridan** [comment]
fixed by ##9489 (for real this time)
