### ISSUE TITLE
Particle Accelerator Sprite bug

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#4537]
Don't know how to reproduce, I guess just fiddling with the PA.

I was setting up the engine as a cyborg and controlling the PA remotely, PA had the Power 2 and ON sprite but it wasn't shooting, so I checked its interface and it was off. I turned it on and off and after that it was working normally. Maybe look into it.

**Comment by duncathan** [comment]
Fixed by new sprites
