### ISSUE TITLE
Wizard teleportation ability causes many unnecessary fails

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#4603]
The top (and default) option for the Scroll of Teleportation and the Teleportation spell is Aft Port Solar Array. Since Wizards often have to teleport in a hurry, this very often leads to failure, because spess is like that.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
