### ISSUE TITLE
Alien Infection Icons do not always clean up properly

### ISSUE THREAD

**Issue by Zelacks** [tgstation/-tg-station#4758]
What it says on the tin. Sometimes when you are an alien, the infection icon will not always be cleaned up/deleted. This causes anomalies such as the alien having an infection icon, a mob having an infection icon, ghosts having it etc.
In a particular instance, a person logged out before they were facehugged, and when they burst, the icon did not get cleaned up. I tried to reproduce it this way, but could not.

Examples of the bug:
http://puu.sh/bs4FV/426942b894.png

http://puu.sh/bs3y2/52e2284bbf.png

**Comment by KorPhaeron** [comment]
Ancient and our HUD works differently now
