### ISSUE TITLE
You can determine gender through hardsuits

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#4833]
If you examine them, it'll show what gender they are even if they have a hardsuit or firesuit on.
![ss 2014-09-14 at 10 20 26](https://cloud.githubusercontent.com/assets/3886584/4266499/0f1268de-3c7f-11e4-897c-9465c6b58c22.png)

**Comment by phil235** [comment]
Even more important, the naked human icon next to the name gives away the person's appearance.
