### ISSUE TITLE
Drones can enter but not leave Suit Storage Units

### ISSUE THREAD

**Issue by Ricotez** [tgstation/-tg-station#4904]
A drone can enter a SSU by dragging its sprite onto it. However, it is then unable to leave the SSU, as it cannot actually press any of the buttons in the interface.

Revision I encountered this on: https://github.com/tgstation/-tg-station/commit/1d9cdb07e3c0364d212b93651417c01ed4925816

Steps to reproduce:
1. Become a drone.
2. Drag your sprite onto an open SSU to enter it.
3. Enjoy your newfound prison as you desperately mash the buttons, trying to escape from it.

**Comment by Firecage** [comment]
Well. No other mobs, including, humans, can use the buttons on the interface from the inside. The only way to get out once inside would be to resist out. I thought that this was intentional, since otherwise people could just unlock and open it after being put inside.
