### ISSUE TITLE
You can abuse the TEG using heaters

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#4979]
use the buildable heaters instead of the burn chamber gas heats up faster and higher no burning on lag.

create over 200% postitive energy than what is required to have the heater heat.

Profit since no maintanance engine that lasts forever in a infinite cycle of as long as we got power to power the heater to heat up the engine to power the whole station meaning the heater and heat the engine etc.

Tested with @Cheridan 

Even a non basic heater can generate enough power for the ministation power supply.

Technical details:
The entire engineering APC was requiring just above 5000 watts and the engine was generating 100000 watts and higher to above 150000 and climbing still when testing of this idea stopped.
The station only requires 60000 or so watts to power......

**Comment by paprka** [comment]
This is fixed now from #5902
