### ISSUE TITLE
In nuke ops rounds, Deathsquad chat is usable

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#5010]
This happened to me yesterday. I think this is only in nuke ops rounds. I'm not sure how it's stumbled upon, but it's been stumbled upon in every nuke op round I've been in. If so, it is an obvious metagaming vector.

**Comment by Dorsisdwarf** [comment]
Not a Bug for the moment, since nobody has confirmed Deathsquad to only be available in nuke rounds

**Comment by Shadowlight213** [comment]
@Dorsisdwarf Deathsquad channel was available regardless of round before by tuning to 1441. However, it was recently moved to a much lower channel beyond the range of radios, so this isn't an issue anymore.

**Comment by Dorsisdwarf** [comment]
boom ntsl dead ding dong
