### ISSUE TITLE
Revolution - head of staff names listed multiple times on end of round report

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#505]
##### Revision that this bug was encountered on:
Show-server-revision doesn't work correctly on the Sibyls

##### Server which you encountered the bug on:
Sibyl 2

##### Problem Description:
Head of staff names are listed multiple times on the end of round report.

So if there were four heads of staff, you might get something like:

The Heads of Staff were:
ckey was Captain (survived the revolution)
ckey was HoS (fleed the station)
ckey was CMO (body destroyed)
ckey was RD (died)
ckey was Captain (survived the revolution)
ckey was HoS (fleed the station)
ckey was CMO (body destroyed)

I wish I'd gotten a picture, but you'll have seen this happen before.

##### Steps to reproduce the problem:
1. Play rev
2. Meet one of the ending conditions
3. Read the head of staff part of the end of round report

##### Possibly related stuff:

**Comment by Cheridan** [comment]
Fixed by something
