### ISSUE TITLE
Sudden deafness for everything except local speech (possibly sillicon only)

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#5058]
This issue happened to me thrice last week, twice as AI, and once as cyborg: at some point while playing, radio traffic would simply stop showing. Only local speech (and adminpm's, not sure about OOC) remain unaffected; all radio messages from all channels (including Binary) don't show up anymore.

Unfortunately it doesn't seem to be reproducible, it happened on three of the dozen or so Sillicon rounds I played this week, seemingly at random. On one of the occasions, as AI, the cyborg under me also got the issue at the same time.

Though I couldn't reproduce it reliably, closing the game and relogging fixed it.

**Comment by lordpidey** [comment]
Is this still a thing?  Let's try and clear some of the longstanding open issues.

**Comment by phil235** [comment]
Probably fixed. In 1.5 years, noone complained or opened a duplicate issue of this.
