### ISSUE TITLE
Medbots won't target people on top of tables

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#5101]
Even when they could reach a dude, they'll never inject if he's on top of a table.

**Comment by Dorsisdwarf** [comment]
Medbots WILL inject you if they're on the table with you
Medbots WILL inject you if they are on a table next to you
Medbots WILL shout at you if you're on a table and they're several tiles away
Medbots WILL NOT move to heal you if you're on a table and they're several tiles away
Medbots WILL heal you if you're on a table and they're next to you on the floor
