### ISSUE TITLE
Momentum is acting weird at the borders.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#5167]
1. floating north towards a map edge
2. Suddenly I'm floating south after a z transition

Also experienced suddenly turning around at the western edge of 1 to 6 and turning 90 clockwise from 3 to 6. It seems on every randomly generated cube there's one or two sides that do this.

This is not an intended effect of spacecube

**Comment by duncathan** [comment]
Space cube is kill
