### ISSUE TITLE
Automatic Shuttle call when communication consoles are disassembled / destroyed does not work if consoles are disassembled / destroyed while the shuttle is being recalled.

### ISSUE THREAD

**Issue by dosfox** [tgstation/-tg-station#5287]
If the Emergency Shuttle is in the process of being recalled (I.E.: The ETA timer is counting up to 10:00), and the final Communication Console is destroyed or disassembled, the shuttle will not automatically call once it has 'returned' to Centcom, thus trapping the crew on the station with no way to call the shuttle without Admin involvement.

I have tested this across a few rounds on Badger, running Metastation. I have had NikNakFlak witness and verify this, as well. No AI's were present during this testing, but I suspect that if the AI was deactivated during or before the recall, it would produce the same result.

**Comment by Jordie0608** [comment]
This got fixed at some point.l
