### ISSUE TITLE
The issue tracker is useless in its current state

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#5294]
What it says on the tin currently people easily dont know when bugs are fixed or sorted and we as a community do not have someone managing it or even a bot checking if something is a duplicated report at all.

**Comment by Dorsisdwarf** [comment]
I feel like I wandered into an ancient tomb with a bunch of ancient skeletons around a scattered campfire carrying plaques saying "End nuclear testing now!"
