### ISSUE TITLE
Simple animals never leave blood trails or get your weapon bloody

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#5337]
Attacking simple animals like Ian or cows (who ought to have some blood in them, unlike constructs for example) never result in your weapon or the floor being covered in blood. Also, their dead corpse never leave a blood trail.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
