### ISSUE TITLE
Player can see everything, including ghosts.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#5340]
http://postimg.org/image/sjy8td7b7/

**Comment by MrStonedOne** [comment]
This is most likely a byond bug.

some appearance vars can overflow into others.

like when setting lum to above 6 caused gender benders.

in fact, it was most likely that same bug, ie, fixed.

@Alek2ander @GrayRachnid can we get a report on if this has happened again?

**Comment by tkdrg** [comment]
closing as fixed unless we get more info
