### ISSUE TITLE
Aliens (hunters) leaping through firelocks

### ISSUE THREAD

**Issue by cultist-chan** [tgstation/-tg-station#5355]
Misterstaub admin online. Time @ 7:47 am on Sunday 10/9/2014

**Comment by WJohn** [comment]
This issue doesn't happen anymore, if it ever did.

**Comment by Aranclanos** [comment]
did you test it?

**Comment by WJohn** [comment]
Yes, I did. Doesn't happen anymore. It does however show some border object issues where you will collide with it (and end up on the same tile) regardless of direction. Thankfully you can't teleport through a window this way.

**Comment by Aranclanos** [comment]
leave the link to the new issue here pls

**Comment by WJohn** [comment]
I just made #10479 since apparently no one ever made an issue report on one of the oldest bugs of all time. Maybe it's a dupe, I dunno.
