### ISSUE TITLE
Middle mouse button active-hand-swap doesn't work on unseen tiles

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#5386]
1. Swap active hand by clicking middle mouse button (m3) on any tile you can currently see.
2. Notice how active hand swaps.
3. Click on a tile which you can't see.
4. Notice how it doesn't swap.

One would think you could swap by clicking anywhere on the screen, changing it to work so would make using middle mouse button a lot better.

Revision: fdde99e3cad0e0abc0d3513b82b68bac4e853626

**Comment by Jordie0608** [comment]
Click(), which calls ClickOn(), is just never called when clicking on unseen darkness since there's no atom to be clicked on.
