### ISSUE TITLE
If you're on a table, moving onto someone's square with mutual help intent tables them

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#5403]
How to reproduce:

- Climb onto a table (I used the HoP line because, uh, well)
- Have someone else standing next to you
- Both of you must be on help intent
- Move onto their square. The standard help-intent switching of places will occur, except now they will be on the table, presumably able to move.

**Comment by hornygranny** [comment]
originally tableclimbing was loc manipulation, @MrPerson suggested using movement. not sure how to avoid this. i guess you could fix this and #5933 by making help intent simply not push instead of warp through people

**Comment by tkdrg** [comment]
Changing help intent would make it nigh impossible to traverse crowded 1-wide hallways (eg maint during blob). Not sure if that's a thing we want.
