### ISSUE TITLE
Remap atmos

### ISSUE THREAD

**Issue by Donkie** [tgstation/-tg-station#5416]
With the addition of 4way pipes I'm sure someone can come up with a new great design for atmos on boxstation.

**Comment by Jalleo** [comment]
Cheridan could we have a push for this to be partially/done next feature freeze as it will probably increase the usability and simplicity of atmos as a whole.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
