### ISSUE TITLE
Ninjas have special 'female' versions of both their jumpsuits and suits

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#5465]
...Even though code already exists to convert the jumpsuits and exosuit to female. Very special snowflake shit and no reason two separate icons for female and male jumpsuits need to exist now that we have the overlay.

**Comment by Dorsisdwarf** [comment]
I bet @RemieRichards resolved this one when they made ninja unhorrible

**Comment by Anonus** [comment]
it never actually was resolved but sure okay
