### ISSUE TITLE
Odd behaviour with pipes after an explosion.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#5536]
Atmos was bombed and after we fixed it, I noticed that some of the pipes weren't getting re-pressurized. Un-wrenching and re-wrenching pipes in the affected portions fixed it.

Afterwards I checked distro's pressure and it wasn't going up or down so I undid and redid a pipe, it began falling as it was being used up by the vents connected to distro to re-pressurize rooms but it wasn't getting any pressure in until I shut the distro pump off, un-wrenched and redid it. (None of the pipes in distro itself were damaged, only the ones connected to the airmix before it's pump.)

**Comment by Jalleo** [comment]
@duncathan was this fixed in your work on atmos pipes?

**Comment by duncathan** [comment]
lol i have no fuckin clue

**Comment by duncathan** [comment]
I'd say close this until it ever happens again, if ever

**Comment by Jalleo** [comment]
@phil235 can you test to see if this still occurs?

**Comment by duncathan** [comment]
>I'd say close this until it ever happens again, if ever
