### ISSUE TITLE
Nuke disk respawning needs improvement

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#5537]
The fabled 'stun and minibomb the person with the nuke disk, go to where it's respawned since it'll likely be undefended' strategy is finally getting more popular with new cops who have some kind of coordination.

The nuke disk 'respawning' needs to be removed and it needs to drop wherever it's destroyed like IDs do when you destroy a PDA. This gives the crew a chance to recover it as well as the nuke ops, and doesn't fling it somewhere where the nuke ops can find but the crew can't (likely because the pinpointer was in the captain's backpack as well, see below).

I put the disk pinpointer in the HoS' office on metastation on the NT branch, and I suggest the same is done here on our maps, because the captain has no real reason to have the pinpointer as well. It's pretty obvious who should have the pinpointer in the case of the cap/disk going missing, but often captains throw it at the HoP or forget about it altogether and leave it in their backpacks along with the disk until it's too late.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
