### ISSUE TITLE
Chemistry needs to be updated

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#5547]
https://github.com/EuroNumbers/-tg-station-newchemistry

As we all know this was done a while ago now and we still dont have any clue how much is actually done what needs improving etc etc.

Food also needs a rework and a overhaul of which @Rosenmann has made a simple comment of some parts.
And a conversation today about how the fluid storage and all of that with people should be changed to be less magicy.
There was also a mention today about how reagents is bloated and some of it is redundant. 
(only a mention not confirmed and not quoted)
There are three ways to remove all reagents from something. @MrPerson.

There are other parts that are missing from this which I believe people can easily add in since I am not entirely focued on this right now (as in reporting it). Just edit and update this when required Maintainers.

**Comment by Iamgoofball** [comment]
i think we can close this, i updated chemistry
