### ISSUE TITLE
"Robotic Talk" bug

### ISSUE THREAD

**Issue by masonhales** [tgstation/-tg-station#5562]
You can still hear "Robotic Talk" even when you're suppose to be deaf.

... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...
Robotic Talk, Durandal states, "but be ready to change back in case of structural damages."
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...

**Comment by Dorsisdwarf** [comment]
Closed for unreproducible old issue.
