### ISSUE TITLE
Climbing a table diagonally dumps you on the floor in front of it

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#5620]
see title

**Comment by xxalpha** [comment]
I can't reproduce this at all, none of the information here helps.

**Comment by Jalleo** [comment]
X is wall T is table P is player
XT
P

I presume this is the issue due to us not allowing proper diagonal movement.

**Comment by xxalpha** [comment]
I can do that climb onto the table with no problems, though.

**Comment by Dorsisdwarf** [comment]
P
X T X

is the precise setup this was reproduced with originally.

**Comment by tkdrg** [comment]
xxalpha says he still can't reproduce this, so closing until somebody makes it happen again
