### ISSUE TITLE
Wurmholes can teleport you on top of grilles and other dense objects.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#5640]
Solution: Prevent it from teleporting you in a tile with a dense object. Because right now you can very easily get stuck in a window or in a pile of computers and be unable to move.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
