### ISSUE TITLE
/obj/structure/c_transit_tube use object verbs

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#5675]
stop merging stuff with object verbs.

**Comment by Jalleo** [comment]
This is the file requiring the changes. https://github.com/tgstation/-tg-station/blob/master/code/game/objects/structures/transit_tubes/transit_tube_construction.dm

**Comment by tkdrg** [comment]
Keep in mind you'll need at least 2 different interactions to fix this, since flip is the only way to acquire certain tube shapes due to asymmetry (apart from the RPD dir selector of course).

**Comment by duncathan** [comment]
Tbh everything about transit tubes is terrible; I really need to rewrite them some time

**Comment by tkdrg** [comment]
Well, the main issue with that is you'll break all the maps, but I guess this isn't that big of a deal. Their logic really ought to be dir-based instead of using the icon_state to figure out the connections. Maybe using wall-like bitflag dirs and icon_states would solve this issue somewhat cleanly.

**Comment by MrStonedOne** [comment]
This should be closed, @duncathan
