### ISSUE TITLE
Feature Suggestion: Adding Syndicate Medibots

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#5766]
Currently there's is a type of medibot called the "mysterious medibot" that utilizes the bezerk style medikit (Tactical medical first aid kit): https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/bots/medbot.dm#L45 It injects Dexalin Plus, Bicaridine, Kelotane, and Anti-Toxin. Currently it is not able to be constructed.

My proposition: make these actually constructable from the tactical first aid kit with two changes: 

-Renamed to "Suspicious Medibot" and description updated.
-The mysterious medibot will ONLY heal people with the faction "syndicate"
-Change out the Dexalin Plus for Dexalin

If this may be a bit overpowered, the Tactical First Aid kit could be increased by a few TC in cost.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
