### ISSUE TITLE
Jobs Preference issue - being selected for jobs I don't want

### ISSUE THREAD

**Issue by majorsephiroth** [tgstation/-tg-station#58]
My preferences are set to nothing but assistant. It's on yes, and set to get assistant when other jobs unavailable. Over the past 2 days I have spawned as jobs twice, librarian and mime.

I want to be an assistant, not these jobs.

**Comment by CorruptComputer** [comment]
I just tried to get this to happen, and was unable to reproduce it.

**Comment by Aranclanos** [comment]
At some point pap ported a fix for the roundstart window href from bay that prevented the 'declare ready' once the round was starting, this can be closed.
