### ISSUE TITLE
You can't smelt mineral tiles back into bars/sheets, and it still drains fuel.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#5823]
What it says on the tin. Welding a stack of 4 should return a sheet, though I'm not sure how that should work for plasma.

Mineral tiles also can't be inserted into exosuit fabs or protolathes, and I'm not sure if you can even grind them to get any liquid out of it.

@firecage

**Comment by Jalleo** [comment]
@Firecage
