### ISSUE TITLE
Augmenting your chest doesn't remove the need to breath

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#5826]
Problem Description: The Wiki States that Augmenting your chest will remove the need to breath in the surgery guide section. However, you still take oxyloss damage with an augmented chest.

What did you expect to happen: I expected to no longer need internals with an augmented chest in an airless environment

What happened instead: I took oxygen loss damage as normal.

Why is this bad/What are the consequences: Either the Wiki has misleading information, or this is a bug. 

Steps to reproduce the problem: Augment your chest, go into an airless room, watch as your health still goes down.

Server: Badger

Revision: af45ae00a6b7f49536662bb24e7b4745b4cbacee 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I encountered this with a fully augmented body as well as with just the augmented chest.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
