### ISSUE TITLE
Large rsc files - TGservers have unsustainably high bandwidth usage.

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#585]
http://ss13.eu/phpbb/viewtopic.php?f=3&t=229

Currently, our codebase has a .rsc filesize of 27.2Mb. This is extremely high.
Bandwidth usage for TGservers is almost 2000Gb a month.

This is something we've been saying is an issue for a long long time. It's not only an issue for hosts, but one for clients having to download almost 30Mb on a throttled byond connection.

As I see it we have some key savings we could make:

*Remove unused icon_states! There are loaaaaads.

*Make a MAPPING define, which would set area icons - this way, these icons would not be compiled into release versions where they are not used.

*Making use of the map-merge tools obligatory

*Reduce the colour pallettes of icon files

*Remove identical repeated frames (copypasted) in animated icons. Instead use the repeat frame option (could be particularly helpful on the titlescreen image)

*Remove/replace/reduce sounds which add nothing to the experience. Note, I'm not saying remove anything like sound effects. I am saying stuff like say, if "put a banging donk on it" was a 6Mb Ogg, possibly reducing that to a more acceptable size....as a hypothetical example

*Marking our more-stable revisions so servers do not have to update as often (not sure how you'd judge which ones are more stable)

*Look into hosting rsc files separately. Unfortunately, byond does not support https, so I am unsure how this would work in a practical sense. However, adding -support- for it should be fairly trivial, and would pretty much eliminate most of the bandwidth use whilst not affecting stability (it reverts to the old behaviour of downloading from the server if the rsc file cannot be fetched from the alternative source)

**Comment by Jalleo** [comment]
@Carn should we make a fresh more modular issue report that has more up to date information?

**Comment by paprka** [comment]
gonna do an unused sprite asset cleaning later this week, prepare your butts
