### ISSUE TITLE
Pipe dispensers cannot be built.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#5858]
One of the most complex things we have in the game is the pipe network that runs all over under the station. And we can't reliably get new pipes because only one dispenser exists for its job in the game.

It would be nice if:
1. You could build all 3 kinds of pipe dispensers and
2. You could make air pipes, disposal tubes, and glass transit tubes with the appropriate sheets at a cost.

**Comment by Dorsisdwarf** [comment]
Closed due to being a non-issue with the rise of the RPED
