### ISSUE TITLE
Lizards speaking s's looks like ass

### ISSUE THREAD

**Issue by Intigracy** [tgstation/-tg-station#5866]
Lizards-s-s vs Lizardsss
It also is confusing to tell if they're drunk/stunned or not at first glance.

The s's are always lowercase, even if you're typing in caps.
SHITTER turns into s-s-sHITTER

**Comment by Jordie0608** [comment]
@Miauw62 this was fixed

**Comment by paprka** [comment]
Yeah this can be closed
