### ISSUE TITLE
Tracking implants are unintuitive

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#5870]
They need a pinpointer-esque item that cycles through available implants (all the implants would have IDs) because right now trying to hunt people down with the scanner is unnecessarily stupid.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
