### ISSUE TITLE
Warning signs cannot be removed

### ISSUE THREAD

**Issue by leibniztg** [tgstation/-tg-station#5898]
There should be a way to remove signs (without praying to admins)
Sometimes players do big projects where they rearrange a large area. These areas often contaion signs which cannot be removed, which looks stupid.
So I suggest that a way to remove them should be added. (probably not too easy so they dont get griefed in the first 5 minutes of the round)

A brief and incomplete list of signs:
- Radioactive area (engineering)
- Secure area (telecoms)
- Disposal leads to space
- No smoking
- High voltage
- Docking area

**Comment by Amnestik** [comment]
This should apply to other wall hangings that can't be deconstructed, like the alert screens or fire extinguisher cabinets too.

**Comment by Dorsisdwarf** [comment]
Posters are a kind of sign, so that could be confusing, WJ

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
