### ISSUE TITLE
Slipping on foam when climbing onto a table with foam underneath

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#5965]
If the janitor lets off a cleaning foam grenade, and you're adjacent to a table with foam underneath it, climbing onto the table causes you to slip, as though walking on the foam underneath it.

**Comment by phil235** [comment]
Yeah, the best solution is to make foam appear above table, not below.

**Comment by phil235** [comment]
foam appears below table again.

**Comment by xxalpha** [comment]
Foam over everything looks awful
