### ISSUE TITLE
Event ops get the traitor's uplink instead of the ops uplink

### ISSUE THREAD

**Issue by StuAhpla** [tgstation/-tg-station#6018]
I ended up on a nuke ops team spawned by event and they didn't get a c20r nor anything like extra shotgun ammo or cyborgs.

**Comment by palpatine213** [comment]
Bump. This is still an issue. Kinda screwed an event today.

**Comment by tkdrg** [comment]
This is quite difficult to fix. Maybe after the fabled gamemode rewrite.

**Comment by Shadowlight213** [comment]
Issue fixed. This can be closed
