### ISSUE TITLE
Backpack watertank mister can be used w/o the tank.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#6023]
To reproduce:
* put the janitor backpack watertank in your hand
* toggle the mister to get it in your other hand
* switch to the backpack hand and drop or throw the backpack
* enjoy your working watertank mister
* Additionally move the mister to your other hand and you get "The mister snaps back onto the watertank!" despite the fact that it actually doesn't snap back. You can also put the Mister into any backpack.

Other method:
* put the watertank on your back and toggle the mister.
* Find any backpack and put the mister in it. (that backpack doesn't even need to be in your hand)
* You get "The mister snaps back onto the watertank!" but the mister is definitely in the backpack.
* Enjoy your standalone working mister that can be moved in and out of the backpack w/o snapping back on the watertank.

Somewhat related to #5559 I guess.

**Comment by tkdrg** [comment]
Can't reproduce this, probably fixed somewhere along the way? @phil235
