### ISSUE TITLE
Xray + mesons = night vision

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#6028]
Yet another invisibility interaction issue, I assume. Not sure if this is feasible to fix.

**Comment by Dorsisdwarf** [comment]
If it's an issue we can't resolve, why track it?

The purpose of the bug tracker is to supply bugs for us to fix.

**Comment by tkdrg** [comment]
It can be fixed, but only in a hacky way. The ~right~ way to fix it would be in byond.
