### ISSUE TITLE
Emitter behavior

### ISSUE THREAD

**Issue by d3athrow** [tgstation/-tg-station#603]
d8068198f283827a08c1c6a30358b5884fc74131
When on a powered wire and firing if the wire powering it is destroyed by means other than wirecutters the emitter continues to fire as if the powernet wasn't interrupted. Turning the emitter on and off doesn't change the behavior

**Comment by phil235** [comment]
Cannot reproduce, so I'll assume this is fixed.

**Comment by Aranclanos** [comment]
did anyone change how powernet works?
