### ISSUE TITLE
Closets are 2spooky in lowgravity

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#6123]
If you stand in a closet in low gravity and open + close it while bouncing, your sprite teleports further and further away

![Image of closet in space, it is closed, what does this mean? Why is life](http://puu.sh/d60JD/1d5dcaccd2.png)

![The closet is open, the sprite is wailing and nashing it's teeh, the skeletons are spooking](http://puu.sh/d60JM/5a14fd337d.png)

**Comment by phil235** [comment]
You can now still get the large pixel shift by spamclicking the closet open and closed, but the bug isn't reliable (you really need to spamclick to counter the reset effect of life(), I only managed to get a max shift of 3 tiles before missing a click or getting tired) and you automatically get back to your original position if you stop spamclicking whether you leave the closet open or closed.

**Comment by xxalpha** [comment]
Maybe I am doing it wrong, but I can't reproduce this.

**Comment by optimumtact** [comment]
It's much harder to down now that phil made a change
