### ISSUE TITLE
Rollerbeds are hilariously overpowered and broken

### ISSUE THREAD

**Issue by Ergovisavi** [tgstation/-tg-station#6168]
Description:
Rollerbeds allow you to:
- [ ] A) Use items while attached to one, including guns
- [ ] B) You can use TK to move it around
- [x] C) While attached to the rollerbed, the structure is solid, meaning projectiles hit the rollerbed, not you, and thus you are immune to projectiles
- [ ] D) Turrets do not see you while you are attached to a rollerbed
- [ ] E) You can't slip, and are sanic fast

No, these issues do not cross over to rollerchairs, as you are seen by turrets on them, and you cannot grab them with TK, nor are you projectile immune.

![lolrollerbed](https://cloud.githubusercontent.com/assets/4465459/5248215/2cd7c288-792e-11e4-8554-1c1f952a94fc.gif)
![honkrollerbed](https://cloud.githubusercontent.com/assets/4465459/5248220/35bbdb96-792e-11e4-81fb-608347780b39.gif)

Janicart 2.0

**Comment by phil235** [comment]
Issue "D" only happens when turret are set to stun (they see a mob lying down and don't target it). Lethal mode still shoots at lying mobs until they're dying or dead.
A solution would be to give roller beds a bullet_act() and some health so it can be deleted after too many hits.

**Comment by phil235** [comment]
C has been fixed
