### ISSUE TITLE
Uplink Implant Doesn't Work

### ISSUE THREAD

**Issue by Yakk** [tgstation/-tg-station#6193]
Problem Description: When you inject an uplink implant you don't get a UI button or an *emote prompt to activate the implant.

What did you expect to happen: Things to work

What happened instead: Things didn't work

Why is this bad/What are the consequences: It's a waste of 20tcs that you can't use.

Steps to reproduce the problem: Get off shuttle, buy uplink implant, implant self, receive nothing.

Server: Sybil

Revision: 0b5ae9899ecc3859bf5449a38f8295301a048b3f

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Traitor round

**Comment by Core0verload** [comment]
It's fixed a year ago I think. @phil235, can you close it?
