### ISSUE TITLE
Mapping error: Asteroid Disposals

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#6205]
The recycling area on Asteroid lacks a conveyor under the crusher. Any resources that are recycled are simply dropped there and not forwarded.

It can be fixed manually if one knows how to conveyor, but I imagine it should not be that way.

**Comment by Jalleo** [comment]
Bump @CorruptComputer was this sorted? @Miauw62

**Comment by CorruptComputer** [comment]
The map is dead now.
