### ISSUE TITLE
Braindead AI = Upload proof borgs

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#6215]
So, I was a traitor robotocist, and managed to get a hold of both an ai and cyborg upload board. When trying to upload to the AI, which was braindead at the time, it said no active AIs detected. when trying to upload to the one borg I know we had, it said no active unslaved cyborgs detected.

Basically, this means that if an AI goes braindead, all of its borgs are immune to law changes unless emagged.

Server: Badger
Revision: 0b5ae9899ecc3859bf5449a38f8295301a048b3f

**Comment by xxalpha** [comment]
This isn't a bug. Braindead players aren't guaranteed to never come back, so allowing people to subvert the AI's cyborgs while it is disconnected wouldn't be a good idea.

**Comment by Shadowlight213** [comment]
@xxalpha
>oh shit someone's going to reset my laws!
>close client
>wait 5 minutes
>come back

Honk honk honk honk

**Comment by xxalpha** [comment]
Ban.
