### ISSUE TITLE
Scrubbbers random event ignores welded vents

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#6259]
What happened: Scrubbers backpressure event happened
What I expected to happen: A welded vent would not produce a backpressure cloud. (This one was in the cargo office, for what it's worth.)
What actually happened: A cloud of gas out of a welded vent.
Why this is bad: It makes no sense, immulsions, blocks a potential way of getting around an annoying random event

**Comment by phil235** [comment]
Now that scrubbers can be welded this issue is correct. Welded scrubber can still make a smoke cloud during 'clogged vent' events.
