### ISSUE TITLE
(Winter) Coat hood does not hide some head objects, but wipes faces clean

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#6275]
![winter coat issue](https://cloud.githubusercontent.com/assets/6266927/5351420/c4b21322-7f4d-11e4-8434-5e40618a68d3.png)
I like the new Winter Coat, and have done so ever since it appeared briefly in lockers on Metastation. But its tendency when worn up to delete all your facial features other than eye colour (which makes for a nice Ice Climbers effect, but doesn't seem optimal - I'm not even fond of this feature in the chaplain's hood) and yet its incapability to hide objects like HUDs when they wrap around the head (like medical belts appearing outside labcoats for some reason) is rather strange and a little grating.

**Comment by phil235** [comment]
The issue with glasses appearing above the hood has been solved.

The issue with facial hair being wiped can only be solved by moving facial hair on a new layer just for them, different from the hair layer, and add a HIDE_FACIAL_HAIR bit for clothing.
