### ISSUE TITLE
Simple animals dodge bullets so well it makes Neo look like a joke.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#6322]
For some reason simple animals see bullets, lasers and other projectiles as solid objects that they HAVE to go around, and as such are able to diagonally path around them in a split second. Given #6179 you can actually make a wall of bullets from mechs and simple animals will not be able to move past them.

**Comment by Iamgoofball** [comment]
new meta: become simple animal in nuke rounds
