### ISSUE TITLE
Vision issue in kitchen

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#6485]
So apparently you can see the bar request console unless you're standing right next to the tile it's on from the kitchen. Can't interact with it or anything.

![](http://i.imgur.com/qJtTMkE.png)

![](http://i.imgur.com/vkyrs3L.png)

Yeah.

**Comment by WJohn** [comment]
This is a non issue, this is just how the game works.

**Comment by Jalleo** [comment]
should be changed to not a bug
