### ISSUE TITLE
Honker Blast only stopped by earmuffs

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#6499]
The HONKER blast is only blocked by earmuffs, while many other items have ear-protecting properties (helmets, bowman's headsets.)

I'm in the process of fixing this (or rather testing my fix, which will be a while since i got a new computer since I last worked on ss13 code and don't have a proper test station set up), but is this actually a feature?

**Comment by KorPhaeron** [comment]
@tkdrg 

Joke mech/one of the hardest things to build in RD, not a bug
