### ISSUE TITLE
FOOD Requirements

### ISSUE THREAD

**Issue by sbkatko** [tgstation/-tg-station#6514]
The new food restrictions are ridiculous. You have to eat OFTEN and cant eat just any food... you have to eat either food the chef made (hope your chef doesnt die!) or donk pockets which run out pretty damn quick.  please fix this. I realize the is a RP game but the it shouldn't be centered upon eating the whole time. Thank you.

**Comment by Jalleo** [comment]
@PKPenguin321 do you still feel the same way about how the food works?

**Comment by Cheridan** [comment]
balanced by #6643
