### ISSUE TITLE
Specialized Medibots

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#6517]
This is mostly a feature request for @paprka since he mentioned it in a reply

A while back there was a feature request to utilize the syndicate medikit (Bezerk medkit) to turn into the mysterious medibot (perhaps renamed to suspicious medibot), which has the ability to treat any injury with the associated reagent.

Paprka then suggested adding in multiple specialized medibots, such as O2 kit medbots inject dexalin, regular medkits inject the usual tricord, fire medkits inject kelotane, etc.

I'd like to put this feature request up for consideration again.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
