### ISSUE TITLE
Janitor backpack tank nozzle message duplication

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6551]
When you press E to try to put the backpack water tank nozzle away, and you're wearing a janitor belt, the message you receive is duplicated:

>the janitor spray nozzle is stuck to your hand, you can't put it in the janibelt
>the janitor spray nozzle is stuck to your hand, you can't put it in the janibelt

Additionally, I'm not sure what it means by "stuck to your hand," I would assume the IC reason it can't go in the janibelt is that the hose can't reach that far.

**Comment by Jalleo** [comment]
@Thunder12345 was that fixed anyhow when you were getting that since both were really saying the same thing but had a different check.

**Comment by phil235** [comment]
can't reproduce it either. I'm closing it.
