### ISSUE TITLE
Lost momentum after exiting a mass drivered container mid-flight

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6569]
If you get shot out of a mass driver in an object, say the coffin on the mass driver in the derelict, and unknowingly open it mid-flight for fun, it'll dump you out in the middle of space and the coffin will keep traveling by itself. It's not a bug, it's just unintuitive behaviour.

**Comment by Jalleo** [comment]
@MrPerson would there be a easy solution due to your new space movement changes?
