### ISSUE TITLE
[Feature request] Automatically unmute OOC at the beginning/end of round

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6600]
Pretty self-explanatory. It's easy to lose OOC messages between when the round ends and when you hit the verb to start listening to OOC again. Similarly, it's easy not to realise you have OOC disabled at roundstart when OOC is off from last time you disconnected with it disabled.

**Comment by Jordie0608** [comment]
This was actually just broken and fixed in  #10470

**Comment by MrStonedOne** [comment]
[08:37:21] <MrStonedOne> Jordie, no
[08:37:32] <MrStonedOne> they are talking about the player preference
[08:37:43] <MrStonedOne> not the admin global disable of ooc

**Comment by Jordie0608** [comment]
Sssh I totally read the issue report and not just the title

**Comment by peoplearestrange** [comment]
Jordie: a true gentleman never backs down

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
