### ISSUE TITLE
Clicking stuff while restrained gives no feedback

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#6605]
It should probably give a warning: "You're restrained, you can't do this." or something like that.
It's very confusing for new players. Applies to both handcuffs and straitjackets.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
