### ISSUE TITLE
[Feature Request] Blood needs to dry over time

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/-tg-station#6618]
Hello, guys. I would like to have this very simple (I think) feature in the game: fresh blood turning into dried blood after a while (~5 minutes).

That will definitely help you know whether that blood trail in maint is worth following or not.

**Comment by Jalleo** [comment]
@paprka

**Comment by paprka** [comment]
not @paprika this isn't my shit

**Comment by Jalleo** [comment]
Gotcha I was more wondering your opinion on this and wasnt on irc at the time. I apologise did not convey the message right. So we primarily need a addition of sprites or byond colouring for this to work if we want to do this.

**Comment by paprka** [comment]
Byond coloring for dried blood and vomit would be really fucking excellent actually.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
