### ISSUE TITLE
Office chairs facing north have the wrong layer when dragged

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#6624]
It remains on `FLY_LAYER` even after you drag it around. It should probably switch layers in `handle_rotation()` or something like that.

**Comment by WJohn** [comment]
http://i.imgur.com/1V6y8Tt.png is this what's going on?

**Comment by paprka** [comment]
@RemieRichards Can you investigate? Dunno if it has anything to do with my stuff or not

**Comment by phil235** [comment]
The problem is that the layer isn't updated when moving the chair around, but it is updated when rotating it (via rightclick or object verb) so this produces both cases here.
