### ISSUE TITLE
Log out messages being randomly shown to players

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#664]
##### Revision that this bug was encountered on:
Badgerstation doesn't list the revision properly.
##### Server which you encountered the bug on:
Badgerstation
##### Problem Description:
Sometimes, when a random player logs out, everyone will get shown a log-out message containing their character name, ckey and the time they logged out.

It's not really an issue, but some people like to keep their character name and ckey separate.
##### Steps to reproduce the problem: 
I don't know how you would reproduce it. Get onto a busy server and hope one appears?

**Comment by tkdrg** [comment]
I haven't seen this happen in a few months. I wonder if it's still around.

**Comment by duncathan** [comment]
This is not our bug ;_;7
