### ISSUE TITLE
TK works through shutters

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#6641]
How to reproduce:

- Have a dude behind shutters; in my round this happened when I was chef behind closed shutters (and door, etc) in the kitchen.
- Have someone with TK on the other side of the shutters
- Use TK. You may have to have alt-clicked before hand for it to work, or mouse over.
- IT WORKS

Why this is bad:
- Immulsions. If you can't see it you shouldn't be able to TK it.

**Comment by Razharas** [comment]
Yes altclick could work like this

**Comment by Razharas** [comment]
Or maybe the dude had xray

**Comment by Razharas** [comment]
After consulting with tkdrg it was decided that it is not a bug
