### ISSUE TITLE
NVG/thermal inconsistancy with regards to flash resistance

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#6669]
Thermals have a negative flash resistance, which means if you flash/flashbang them, or they decide to do a little welding, it fucks them pretty hard. This is odd in itself, since thermals you know, show heat, so welding with them would probably be an awful idea, and I have no clue what heat a flashbang is supposed to release, but a flash has none.

NVG's on the otherhand work by enhancing light, yet they don't have a negative flash value. This seems uh, bad, and doesn't really make sense. That said, I wouldn't want to make ops in a hardsuit to vulnerable to flashbangs, since it becomes a ggnore for them.

**Comment by Lumipharon** [comment]
What? Ever since the stun nerf, ops in hardsuits have enjoyed immunity to flashbangs (that don't go off on the same tile as them), I presume combat mode on the helmet would effect this though. And speaking of which, I still completely disagree with with the whole light on in travel mode, simply because even having a light on ever makes no sense with nvg's.

But yeah, getting nvg's from R&D and then being able to merrily weld/stare at flashbangs with no ill effect, while doing so with thermals half blinds you is pretty dumb.

**Comment by paprka** [comment]
I'll do some testing

**Comment by Miauw62** [comment]
this is fixed by #8065
