### ISSUE TITLE
After catwalks get moved you can still place wires on their original tile

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#6709]
@paprka

**Comment by Razharas** [comment]
Moved by singulo or posessed by badmin

**Comment by tkdrg** [comment]
Setting a var on the turf is a pretty hacky solution. Just have the turf check for catwalks on top of it instead. The loss in performance isn't really an issue.

**Comment by paprka** [comment]
Sure, whatever. I'll improve catwalks later this week, especially their smoothing with lattices.
