### ISSUE TITLE
NTRC rarely used

### ISSUE THREAD

**Issue by Tenebrosity** [tgstation/-tg-station#6720]
Few people bother logging into NTRC because they don't expect to find anyone there to talk to. This creates a positive feedback loop, where the low amount of people using it causes even less people to use it.

I have some suggestions to make this great idea actually get used:
* Make NTRC opt-out instead of opt-in because right now no one uses it because there's no one to talk to. 
* Change it so that you get message alerts regardless of whether they mention you, but only for the first unread message. 
* Make message alerts appear regardless of whether your PDA is on the NTRC screen.
* Show a count of the amount of people in the chat, so you know how many people you're talking to

**Comment by tkdrg** [comment]
I'll see what I can do.

**Comment by Lumipharon** [comment]
if it's optin default channel thing, that's literally just general comms, only clunkier.

**Comment by Tenebrosity** [comment]
Except it lets you converse anonymously.
