### ISSUE TITLE
Practice Laser shows up identically to the real laser in combat logs

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#6729]
[10:01:43] Has been shot by Blessed H. Legionare(blessedheretic) with The laser = null 
[10:02:09] Has been shot by Blessed H. Legionare(blessedheretic) with The laser = null

One is with the practice laser and one is with a real one. The projectile should probably be renamed.

**Comment by paprka** [comment]
But that removes all the fun of spooking people with it

**Comment by TZK13** [comment]
You can see that they're firing a practice laser gun in your chat though and seeing as how usually the spook is going to happen when they're on screen holding what looks like a laser gun and firing red lasers at you this doesn't really change that the second you look in your chat you'll find out. All this would really change would be for when somebody firing them from off the screen down hallways and such.

**Comment by paprka** [comment]
True, nevermind.

**Comment by Stickymayhem** [comment]
I'm talking about the actual combat logs found in the VV menus and attack logs, which admins need to reference. 

The player may be able to tell but at a glance it appears to be a laser to an admin and could result in some confusion.
