### ISSUE TITLE
Unpowered Cryo is unejectable, uninteractable

### ISSUE THREAD

**Issue by ChangLing** [tgstation/-tg-station#6744]
Problem Description: So I put this dying guy in cryo, but I didn't notice equipment power was turned off due to a rogue AI.  I click on the thing to turn cryo on, but no feedback, and I wasn't able to eject him, since the screen to turn cryo on and off and open and close it wasn't opening.

What did you expect to happen: Some feedback that shit's unpowered would be nice, or at least it could bring up the panel and have the button THERE be unresponsive.  Would also be nice to be able to re-open it once it's closed.

What happened instead: Shit doesn't open, does not give feedback that it's unpowered.

Why is this bad/What are the consequences: It's kinda shitty to accidentally lock a guy in a cryo tube and be further unable to open that shit back up without hacking the local APC.

Steps to reproduce the problem: Yeah this template is getting a little redundant I think.

Server: Sybil.

Revision: What revision was the server running?
Server revision compiled on: 2014-12-31
cfff3cd3750a153c85e8c14503aa26b7996e0a6a 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Protect Assistant From Antagonist: 0

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us.

Thanks for helping us out!

**Comment by Lumipharon** [comment]
Pretty sure you can crowbar them open. A bit odd you can close it just fine though.

**Comment by Menshin** [comment]
> Cell doesn't open

You're supposed to be able to open it by hand even when powerless. Unfortunately, a general machine check prevent that for now.

I'll add crowbar prying them open, it makes more sense (and is more consistent with the code).

> does not give feedback that it's unpowered

Actually the confusion comes from the cell using the same sprite for _off_ and _unpowered_.
Maybe a spriter could add some lights to _powered_ cells to make up for that (like we did for DNA Scanners, see #5549).

**Comment by WJohn** [comment]
A lot of unpowered things are uninteractable (which makes very little sense). The smart fridge for example can have things loaded into it but can't dispense anything, and I believe the same applies to grinders and chem masters (might be wrong on that one).
