### ISSUE TITLE
Stuns take a period of time to register

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#6745]
http://i.imgur.com/QCGaGDk.png

Recently on a nuke op round, I played as a stealth op. After emptying my shotgun into the captain, he still stayed up long enough to hit me a few times with his disabler to knock me over.

This needs to be changed. It is literally gamebreaking because someone could shoot you in the time it takes for them to fall over because the stun damage won't register. The only reason I ended up losing that round is because science rushed advanced energy guns because they're the only ranged stun weapon that isn't now shit.

**Comment by tkdrg** [comment]
I think this might be because stamina damage is only checked on `Life()` aka once per tick, so you may have to wait up to a tick for a stamina stun to kick in. I might be wrong however.
@paprka please fix
@ergovisavi please explain

**Comment by Ergovisavi** [comment]
Yes, this is because CheckStamina() is only called in life(); I had this fixed in my PR but that didn't get merged.

**Comment by paprka** [comment]
This is fine, stamina damage doesn't instastun once reaching the threshold intentionally. It's not instastun gg no re central anymore, there's plenty of other tools for taking out the captain.

The bulldog is for crowd control, not stealth ops. Use a silenced pistol or a silenced c20r.

**Comment by Xhuis** [comment]
All right, thanks for providing insight.
