### ISSUE TITLE
Graphics bug with manual valves

### ISSUE THREAD

**Issue by Tyrranatar** [tgstation/-tg-station#6746]
The manual valve inside of the research division has a bugged icon. It looks like a regular pipe until you unwrench it and place it back down.

![badvalve](https://cloud.githubusercontent.com/assets/8949092/5594378/0ddcab94-9217-11e4-8644-4eabb8c70099.png)

This is my first time submitting a bug, so let me know if I did this wrong.

**Comment by tkdrg** [comment]
The report looks fine, thanks for taking the time to do it.
@Menshin did you fix this bug in your recent pipe PR?
