### ISSUE TITLE
Cargo Technicians have access to all of Cargo

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#6757]
What is happening: Cargo Techs have mining access and QM office access.
What should be happening: Cargo Techs have no mining access nor QM office access.

**Comment by WJohn** [comment]
Seriously it's like things that have worked forever suddenly change and stop acting like how we want them to. When did mining get access changes to its doors? When did cargo techs get access changes in their jobs? When did access in general get messed with? I can't recall anything related to this as any sort of reason for this going wrong.

**Comment by xxalpha** [comment]
I put minimal effort into investigating this and the problem is not the airlocks, as they have the correct access setting. It's likely something else (IDs).

**Comment by xxalpha** [comment]
access = /list (8) 
1 = 12 
2 = 50 
3 = 31 
4 = 34 
5 = 41 
6 = 51 
7 = 48 
8 = 54

This is what Cargo Techs ID start with.

**Comment by tkdrg** [comment]
This is not happening on sybil. No idea what broke it.

**Comment by xxalpha** [comment]
CONFIG ISSUE
