### ISSUE TITLE
Unable to attach oxygen tanks to mining hardsuits

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/-tg-station#6760]
It is impossible to put an oxygen tank into the suit storage slot. No fancy reproduction instructions, it just does not work.

**Comment by Fox-McCloud** [comment]
This isn't a bug; it's a change made in this PR: https://github.com/tgstation/-tg-station/pull/6530

IMO a bad change it's; miners get screwed over pretty badly by this.

**Comment by tkdrg** [comment]
Not a bug. A bad change perhaps, but not a bug.
