### ISSUE TITLE
Overlays are visible and interactable on cult runes

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#6763]
On top of a cult rune with gibs on it (in the dorms, cabin 2, if it matters)

  That's an overlay.
Fortune Ray points to the overlay
[Common] Ayl Mao (CE) says, "AI OPEN"
Fortune Ray points to the overlay
Fortune Ray points to the overlay
Helps-The-Persons points to the overlay

(There were three overlays, in fact.)

**Comment by tkdrg** [comment]
Hilarious 10/10 professional quality coding.
