### ISSUE TITLE
You can become a harvester infinite amount of times by ghosting

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#6764]
![ss 2015-01-02 at 08 17 52](https://cloud.githubusercontent.com/assets/7247232/5601560/71a243be-92bc-11e4-86cd-bd4d286a0f71.png)

**Comment by TheVekter** [comment]
working as intended :+1:

**Comment by paprka** [comment]
The same thing can be done if you get summoned with a rune as a ghost into a temporary body, you can just do it over and over

**Comment by tkdrg** [comment]
I don't think this is a bug.

**Comment by paprka** [comment]
I will continue filling the end round report then
