### ISSUE TITLE
No way to teleport to the wizard's den as a ghost

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#6765]
Using the 'teleport' command in chat doesn't allow you to teleport to the wizard's den. This is especially annoying now that the wizard's den has been moved to hyperspace.

**Comment by tkdrg** [comment]
To any prospective fixers, do keep in mind that the code for this is awful (see #6014) and it would be 10x easier to fix if it wasn't.

**Comment by Alek2ander** [comment]
You can jump-to-mob Experiment 35b

**Comment by paprka** [comment]
Is that still even on the wizard's den?

**Comment by tkdrg** [comment]
Yes. I guess I can close this issue, then.
