### ISSUE TITLE
Digital valves are broken.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#6772]
1. Place a digital valve
2. Wrench it into place
3. It's invisible and called "Machinery". The icon state is null.

**Comment by phil235** [comment]
@Menshin

**Comment by Menshin** [comment]
_Unreproducible on local with last master._

#6749 fixes some problem with badly normalized direction for valves, that would bust the icon_state but not prevent the d_valve spawning.

#6661 fixes some pathing problems with digital valves, but it should be live on the server now.

**Comment by duncathan** [comment]
I fixed this forever ago

**Comment by phil235** [comment]
@duncathan Are you sure? The bug was still there last time I test it, 2 weeks ago.
