### ISSUE TITLE
Reagent reactions in mobs allows players to detect changelings

### ISSUE THREAD

**Issue by Ergovisavi** [tgstation/-tg-station#6784]
Due to us now having in mob reagent reactions, if you're chugging coffee/tea constantly, the second you're cryostung, it reacts and turns into iced coffee or iced tea, and you hear the bubbling.

**Comment by phil235** [comment]
We could simply remove the ice reagent from cryosting and replace it with more frost oil. I doubt there's an easy reaction that include frost oil.

**Comment by tkdrg** [comment]
That's a balance change which is mostly a nerf however, as it means cryosting will take longer to start acting (since instead of cooling frost oil + ice every tick, it cools only frost oil), though it also means that it would last longer in total.

**Comment by bgobandit** [comment]
Just remove sounds for in-mob reactions?

**Comment by WJohn** [comment]
This is kind of hilarious actually, but yeah removing sounds when reactions happen in people is the way to go.

**Comment by Lumipharon** [comment]
Fool proof way to dethaw/detect cryo sting: Inject yourself with plasma and iron, and you'll poop plasma sheets when a ling cryostings you! This is totally safe.

**Comment by AlexanderUlanH** [comment]
It was always pretty hacky having cryosting use ice and frost oil.  Frost oil is hard to get (exclusively from slimes or mutated hydroponics plants), and has more interesting interactions than other poisons, so I'd advocate making frost oil more powerful.

**Comment by Dorsisdwarf** [comment]
Wait, if coffee now reacts with the ling sting, doesnt that make it less effective at stopping you, since it becomes iced coffee which also cools you?

**Comment by phil235** [comment]
Easiest solution would be to make a new reagent specifically for changeling sting.

**Comment by dannno** [comment]
>This is kind of hilarious actually, but yeah removing sounds when reactions happen in people is the way to go.

yeah this. it's good for reagents to react in humans, but having it make a sound is stupid.
