### ISSUE TITLE
Transformation disease is broken

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#6785]
22:30 <%Razharas> Transformation disease is potato-cell level broken
22:30 <%Razharas> qdel only happens if mob doesnt have mind
22:30 <%Razharas> So any player mob transformed stays invisible forever

This affects roburgers and possibly black slime extracts as well.

**Comment by Miauw62** [comment]
Possibly related to the ling transform bug?
Op 4-jan.-2015 02:34 schreef "tkdrg" <notifications@github.com>:

**Comment by TheVekter** [comment]
Most likely. :+1: here, just had it happen.

Reproduce: Change player into monkey, player switches to human form, is stuck invisible and can't hear anything.

**Comment by Razharas** [comment]
Nope, ling uses starndard monkify proc, disease does all the job itself

**Comment by tkdrg** [comment]
@Razharas was this fixed in your PR?
