### ISSUE TITLE
Wizards can still summon in Ragin' Mages

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#6788]
According to TK, this is a bug. It's off our rotation until this gets fixed, hopefully soon.

**Comment by tkdrg** [comment]
@Iamgoofball please fix.
Also another "bug": Wiz gets spawned waaay too often, and IMO there's too many, too. It needs some rebalancing.

**Comment by Iamgoofball** [comment]
Alright, I'll look into this, summon prolly was a casualty of the merge confllict fix that I didn't notice.
