### ISSUE TITLE
Someone broke the nuke op equipment room [map]

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#6789]
![ss 2015-01-03 at 08 49 35](https://cloud.githubusercontent.com/assets/7247232/5604812/05e4b746-938a-11e4-98e0-1058508c8ec0.jpg)

Sigh

**Comment by Lumipharon** [comment]
atleast there's that 5th locker on the shuttle, so it doesn't assfuck one luckless op.

**Comment by Fox-McCloud** [comment]
There's also 2 syndi toolboxes and 2 welders on the shuttle now; one of which is unreachable unless you climb onto the table or deconstruct it--which is just really poor map design, even if it is reachable.

**Comment by WJohn** [comment]
This has already been fixed a while ago.
