### ISSUE TITLE
Changeling Super Broken

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#6791]
Mid-Round as a lowpop QM on basil, half the crew turns into changelings. We all agree to meet up on the bridge so I just monkey, ventcrawl to the bridge and turn back. After this, I am not able to see any chat or action messages (i.e player has thrown the fireaxe, X has been cleaved by Y with the fireaxe).

I can see OOC, ling chat, and adminhelps. I talked to CrimsonVision about it and apparently I was invisible to him, meaning he couldn't view my vars or anything. In attempt to fix this after the conversation, I killed myself with my arm-blade, succumbed, and my body proceeded to vanish into thin air, only leaving behind the blood I made on the floor.

After dying chat went back to normal as in I could see talking and action messages along with deadchat.

fix your game allen.

**Comment by RemieRichards** [comment]
More info: my ckey is CrimsonVision, so I'm part of this. the changelings were because the only antag logged off.

Potentially linked is that an overlay object appeared where the transform happened, just a /atom/movable/overlay probably left over from the transform.

**Comment by Incoming5643** [comment]
probably the same cause as #6785

**Comment by Miauw62** [comment]
Another issue report was made with overlays randomly appearing, so this is
very probably related.
Op 4-jan.-2015 10:14 schreef "Remie Richards" <notifications@github.com>:
