### ISSUE TITLE
Suggestion: Add Medical Hardsuits

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#6800]
Currently there's medical hardsuits as defined in the code--they have special sprites and have less slowdown than a regular hardsuist--there's just one problem; you can't obtain them, legitimately, in any way.

Might I suggest adding one or two of these to the map in medical (perhaps in an area only the CMO can access)?

Balance wise, they probably shouldn't have any armor at all (minus bio and rad), given they allow slightly faster movement than regular hardsuits.

**Comment by Menshin** [comment]
Purely for information, there's a medical hardsuit on the White Ship in space.

**Comment by TZK13** [comment]
Having one or two for paramedical purposes to rescue people dead in space or in breaches would be really nice but there's definitely a coderbus bias against adding more space suits to the station.

**Comment by paprka** [comment]
Just hardsuits. They're rather overpowered because their helmets aren't built into the suits and flash proof. It won't be so bad once this is reworked.

**Comment by AnonymousNow** [comment]
I've been asking for medical hardsuits to be added to the station forever. I distinctly remember being told that more hardsuits wasn't viable... and then two additional security hardsuits appearing on-station. Security!

I liked what Metastation did - the CMO had a medical hardsuit (love the bubblehead design, by the way). It also makes sense for away teams, which should always have a doctor. You could argue that they could get one from EVA, but it's a lot of extra fuss to get access, and the mindset of people (especially security) sets their priority as "lesser".

**Comment by paprka** [comment]
CMO always has EVA access on box, there's a 'heads of staff' only eva section with two hardsuits for the RD/HoP/CMO that are almost never taken, it's pretty lesser known though

**Comment by optimumtact** [comment]
I'm happy for some basic suits, just not hardsuits :frog:

**Comment by wild-billy** [comment]
Reminds me of this from last time we had this debate on /vg/
![spess_comes_to_medbay](https://cloud.githubusercontent.com/assets/6355724/5609607/7216b684-94ad-11e4-8031-57fcea32d242.jpg)

**Comment by Steelpoint** [comment]
Do we still want a Medical Hardsuit for the CMO?

**Comment by AnonymousNow** [comment]
Yes, please.

**Comment by Saegrimr** [comment]
>They're rather overpowered because their helmets aren't built into the suits and flash proof. It won't be so bad once this is reworked.

Yeah except flashes got nerfed so hard nobody uses them for stunning anything except borgs. Why is this even an issue?

**Comment by paprka** [comment]
flashbangs

**Comment by Dorsisdwarf** [comment]
Also portoflashers use flash protect, and they're the brig's main anti-horde defense

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
