### ISSUE TITLE
Being unconscious does not make you blind

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#6801]
Simply put, you can see everything while unconscious/in crit. This is probably a severe balance issue, as being able to see everything around you while unconscious can obviously be used to metagame information gained while unconscious (you can also examine things).

**Comment by tkdrg** [comment]
@Razharas is this your fault?

**Comment by Razharas** [comment]
Yes, most likely

**Comment by iamgreaser** [comment]
code/modules/mob/mob.dm, line 312: /mob/verb/examinate:
Only check here is the is_blind check (code in code/modules/mob/mob_helpers.dm).

Do we need another check here? I'm guessing "stat != CONSCIOUS" should cancel the examination.

**Comment by tkdrg** [comment]
Fixed in #6847 I believe
