### ISSUE TITLE
Tone down the amount of dirt foot traffic creates

### ISSUE THREAD

**Issue by Tenebrosity** [tgstation/-tg-station#6803]
Janitor is already a pretty frustrating job, what with how easy it is to create a mess and how slow it is to clean it. Foot traffic creating dirty floors is a great idea, but the amount of dirt it's currently creating is impossible to keep up with.

**Comment by paprka** [comment]
I'm already doing this.

**Comment by Jalleo** [comment]
@Miauw62 close this please it was nerfed
