### ISSUE TITLE
Suggestion: Make players completely blind while unconscious 

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/-tg-station#6807]
I realize that the issue with being able to see everything is being fixed, but I think you should only be ab to see your own body, because you shouldn't be able to see anything when you're knocked unconscious.

**Comment by Tenebrosity** [comment]
I would be pro this if crit time was reduced, but 5 minute crit without being able to see anything would be pretty unbearable.

**Comment by optimumtact** [comment]
#6801

Duplicate?

**Comment by optimumtact** [comment]
Will this not be done as part of #6801 ?

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
