### ISSUE TITLE
Getting disconnected removes the re-admin verb.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#6813]
Being disconnected while de-admined removes the re-admin verb. (I'm mostly reporting this as a reminder to myself, but feel free to fix it.)

**Comment by Carn** [comment]
deadmin used to have no readmin verb. This is behaving as would be expected.
This is a feature request.

**Comment by Miauw62** [comment]
we added readmin verbs, carn. so this is not a feature request.

**Comment by Carn** [comment]
readmin was a thing before it was removed, you've readded it.
It used to vanish the first time.
It now vanishes again.
It's expected behaviour if you're just adding a temporary verb. So making it persistent is a feature. =p

Not that it matters.

**Comment by Boggart** [comment]
It's kind of a bug as it wasn't something I intended to have happen when I added the re-admin verb.
