### ISSUE TITLE
Captain's Flask feeding message displaying incorrectly 

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/-tg-station#6815]
I was playing a round last night on sybil and the captain was giving me a drink from his flask; Even though I was straightjacketed I could still see the "you feed [name] from the flask" ("[name]" wasn't really appearing it was my actual name). It's probably a really minor thing but I wanted to post anyway.

**Comment by Xhuis** [comment]
I'm pretty sure this is happening with most reagent containers like drinking glasses and soda cans.

**Comment by Firecage** [comment]
I think this may be my fault due to the span classes stuff from last time.
