### ISSUE TITLE
Readd Quadractic lighting

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#6824]
Please readd the quadratic lighting as it was very nice

:frog:

**Comment by paprka** [comment]
what's the difference, did we change to something else recently?

**Comment by tkdrg** [comment]
Carn removed it in her PR.

**Comment by ike709** [comment]
please provide a comparison for quadratic lighting and whatever the hell we have now

**Comment by Carn** [comment]
Iamgoofball, I was trying to merge 3 things together at once whilst changes were being made constantly, with very little time on my hands.
Sorry. But it'd be nice if you stop this crusade now. I've already given way on EVERYTHING.

**Comment by optimumtact** [comment]
Huh, any chance you can fix the math? Otherwise I'd say we'll let this rest for another time

**Comment by Carn** [comment]
I need clarification on these two conflicting issues.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Coding, Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
