### ISSUE TITLE
Holographic sign projector

### ISSUE THREAD

**Issue by Snipered** [tgstation/-tg-station#6831]
When i'm trying to put this thing into backpack, holographic sign appearing. I mean, when i'm clicking on clothes(in example), this thing creates sign, that means i can't put this into my backpack w/o creating sign on tile.
Sorry for my english, but just try to put this into backpack and u'll understand what i'm trying to say.
![ss 2015-01-06 at 10 17 47](https://cloud.githubusercontent.com/assets/1854678/5622318/5e97d9c2-958d-11e4-9c8e-9c93d47dbb6d.png)

**Comment by paprka** [comment]
Yeah, I understand. This is an issue with some other stuff like hand labellers as well.
