### ISSUE TITLE
ID console broken

### ISSUE THREAD

**Issue by CorruptComputer** [tgstation/-tg-station#6832]
If you try to use the ID console no access buttons show up.

![9bad0515456eda27b2e9aa1d07771b8d](https://cloud.githubusercontent.com/assets/5573038/5622202/2dcdd84c-9505-11e4-9032-a7f1b0199082.png)

**Comment by Tenebrosity** [comment]
Neat

**Comment by bear1ake** [comment]
Host on Windows?

**Comment by bear1ake** [comment]
Earlier, you tag it by BYOND Issue =|

**Comment by Carn** [comment]
maybe this is related to MC change since the job controller was refactored. On it.

Please can somebody do soemthing so I can be assigned to jobs. Even if I have no rights whatsoever, I'm so shit at keeping track of all these things.

**Comment by Miauw62** [comment]
Is this ok?

**Comment by Carn** [comment]
thanks

**Comment by bear1ake** [comment]
YOU EARLIER TAG IT BY BYOND ISSUE!!!
https://github.com/tgstation/-tg-station/issues/6292

**Comment by Miauw62** [comment]
It's not the same bug.
Op 7-jan.-2015 06:34 schreef "bear1ake" <notifications@github.com>:

**Comment by Carn** [comment]
Miauw62 closed this issue from a commit 22 hours ago 
git is silly...

**Comment by Miauw62** [comment]
Wait, is this fixed or not? Your commit explicitly includes "resolved #thisissuenumber". Could just be a typo, ofc.

**Comment by Carn** [comment]
yes it is. I'm just pointing out that it says you fixed it for some reason.

**Comment by Miauw62** [comment]
Ah.
