### ISSUE TITLE
Supply console always gives "invalid request"

### ISSUE THREAD

**Issue by tkdrg** [tgstation/-tg-station#6835]
Even when a cargo request succeeds, it gives an error message to the console user.
@Carn

**Comment by Carn** [comment]
could you clarify? do you mean the authorize request button? I noticed that but I'm pretty sure it was an existing thing (since ordering it from that console automatically authorizes them.
Thanks

**Comment by tkdrg** [comment]
Ordering from that console didn't automatically authorize them before your update. Before, when you request an item, you created a request, just like when ordering from the public console. Then you can click "Authorize request" to confirmit. Previously, it would give a "Your request has been authorized" message, whereas now it gives a "Invalid request" error message, despite the request being approved as intended.

**Comment by Carn** [comment]
ok sorry, I must have confused  FP features with TG
