### ISSUE TITLE
Lockers in map maker no longer accept items placed on top of them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#6838]
http://puu.sh/e8rfX/54ef708856.png

Originally if you placed items on top of lockers in the map maker they would be placed in the locker when the game loaded up, this has just stopped working. @Carn

**Comment by Carn** [comment]
not sure what would have caused this...maybe an order-of-initialization thing?
will look into it. thanks

**Comment by WJohn** [comment]
Should also be tested for things like papers being placed in drawers or on notice boards, I haven't checked on those.
