### ISSUE TITLE
Solar trackers can be built on space tiles (and by extension catwalks) yet will not work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#6839]
I believe this also is the case with regular solars. @paprika

**Comment by paprka** [comment]
Catwalks aren't turfs, they're only for cable laying.

**Comment by WJohn** [comment]
Then solars should not be possible build on non turfs.

**Comment by paprka** [comment]
You can build solar trackers on any space tile, not just catwalks, then. Catwalks only allow turfs to accept cable laying, nothing more.

**Comment by paprka** [comment]
So again @WJohn change the title here to 'solar trackers can be built on space tiles but will not work' because they can
