### ISSUE TITLE
Robust Coffee Makes You Jitter Forever

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#6846]
If you drink around a single cup of coffee, in this case "robust coffee", you'll end up shaking (akin to getting stunned) forever for the entire round.

It's distracting. However I can see it is a weird way to meta against Changelings/Infiltrators. Get your Officers to drink some coffee, and if they stop jittering they're a ling! (Extreme example)

**Comment by phil235** [comment]
can't reproduce, the effects of a full cup of coffee lasts around two minutes.

**Comment by Steelpoint** [comment]
Hmm, seems odd. It was affecting people in a round last night.

Though someone could have tampered with the coffee or something..
