### ISSUE TITLE
Mining stims don't work currently

### ISSUE THREAD

**Issue by iyaerP** [tgstation/-tg-station#6848]
Server: Which server were you playing on? Sibyl

Revision: What revision was the server running? The current one

Problem Description: What is the problem? Hyperzine, and by extension, mining stims, have 0 effect when wearing a rigg suit, rendering the stims a waste of points, and useless.

What did you expect to happen: Why do you think this is a bug? It used to work, but the space speed update broke it, and it remained even after that got fixxed

What happened instead: How is what happened different from what you expected? No sanic speed when expected sanic speed.

Why is this bad/What are the consequences: Why do you think this is an important issue? Because mining sucks without hyperzine.

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue. Get a rigg suit. Use hyperzine. Have no speed change.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us. All gamemodes.

**Comment by phil235** [comment]
Stimpack and hyperzine do have an effect, you're slightly faster whether you're wearing a hardsuit or not.

**Comment by paprka** [comment]
Slightly is the operative word there, it was basically nerfed to shit for miners and made the chem practically useless for its only practical use

**Comment by iyaerP** [comment]
If it does anything, it isn't enough to even notice. And that is bad. We took it hard enough on the chin when a pointless toxin was added to stim pens, we don't need for them to be doing nothing as well.

**Comment by phil235** [comment]
this is fixed, stimpack medipen gives a noticeable boost in speed, plus other stuff.
