### ISSUE TITLE
Marauders/Seraphs Virtually Indestructable

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#6850]
A balance issue.

Marauders, a Nuke Ops and Death Squad mech, and Seraphs, a admin only mech, cannot be destroyed by conventional means, at least in any reasonable fashion.

It eventually took about 50 Ion shots and about 20 Pulse rounds to "delete" a Marauder mech, no wreckage, it just disappeared. The Seraph on the other hand remained standing after 100 Ion shots.

**Comment by Dorsisdwarf** [comment]
Just use the "robo special" and slap a billion mech trackers, then have the RD emp them from his console. See how much fun having an indestructible mech is when the cockpit's on fire, the air tank's ruptured and spewing hot gas, the electrics are all fried and it runs in random directions.

 Or use it to fake a centcomm message to the pilot telling them to withdraw

**Comment by tkdrg** [comment]
They're very strong by design.

**Comment by Dorsisdwarf** [comment]
Admin-only mech and a mech which takes almost all of the nuke ops TC should not be easily killable by any means. This 'balance issue' is a frivolous inflation of the issue count, requesting closure @Cheridan

**Comment by Cheridan** [comment]
They're supposed to be strong
