### ISSUE TITLE
Slime Processor

### ISSUE THREAD

**Issue by dmnwarrior** [tgstation/-tg-station#6860]
Today, I was playing xenobiologist and tried to process a slime to get a core, but to no avail. It seems no matter how many times I processed the slime, even with multiple different slimes, I got no slime core.

**Comment by Miauw62** [comment]
Phil probably caused this, I can't remember his numbers right now.
Op 7-jan.-2015 04:50 schreef "dmnwarrior" <notifications@github.com>:

**Comment by dmnwarrior** [comment]
I don't know if it was a problem on my on or something else, I downloaded the new zip, booted up a server to play with some friends, and tried to go xenobiologist. The processor just wasn't giving anything out and you could freely just remove the slime without anything happening.

**Comment by dmnwarrior** [comment]
Gonna download the new zip today and see if the problem persists.

**Comment by Jalleo** [comment]
What version of byond are you using?

**Comment by Jalleo** [comment]
@dmnwarrior ^^^^^^^^^ Also what OS is your computer?

**Comment by phil235** [comment]
Can you give us each step that you are doing?

**Comment by phil235** [comment]
Closing this, it doesn't seem to have happened again and can't be reproduced
