### ISSUE TITLE
Supply shuttle is broken

### ISSUE THREAD

**Issue by bear1ake** [tgstation/-tg-station#6862]
1. Supply shuttle can't send away to centcom
2. Supply requests isn't avaliable on console

**Comment by Carn** [comment]
which map?
I know for a fact that this was working because I tested it with Aran and again with Cheridan.

**Comment by Carn** [comment]
Also which revision?

**Comment by Carn** [comment]
Also, follow the template

**Comment by Carn** [comment]
Attempting to look into this as it sounds serious. But you've not provided much info to go on.
