### ISSUE TITLE
Ghost follow link doesn't work over radios

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#6873]
Which practically defeats the point of it being there in the first place.
It doesn't work for binary, alien chat, or ling chat either, so it's basically pointless half the time.

**Comment by Miauw62** [comment]
ayy lmao radios use virtualspeakers.
i forgot about that.

**Comment by tkdrg** [comment]
I have no idea how radios work.

**Comment by Miauw62** [comment]
just add if(freq) speaker = speaker:source :V

**Comment by Anonus** [comment]
Also it doesn't work for deadchat.

**Comment by Miauw62** [comment]
just fyi, it doesnt actually defeat the point of the follow link if you turn ghost ears on.

**Comment by Anonus** [comment]
Yes, but ghost ears is butts.

**Comment by Tenebrosity** [comment]
Yeah, I like the idea of ghost ears but functionally it just serves to spam your chatbox.
