### ISSUE TITLE
Butterflies push people around when they move

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#6874]
This is really stupid, butterflies shouldn't be dense or able to push people around.
Same for bees and other small animals that shouldn't be so pushy.

**Comment by Anonus** [comment]
And large objects, too, like crates.
This is very silly.

**Comment by Miauw62** [comment]
the flaps of their wings cause localized tornadoes that push stuff around. :V

**Comment by RemieRichards** [comment]
Nanotrasen scientists have found out that the butterfly effect is much more noticeable in space...

**Comment by Boggart** [comment]
This may affect other simple mobs as well, Poly can't be walked past anymore and can push people, lockers, etc around when he bumps into them.

**Comment by tkdrg** [comment]
You can only walk past them when both the simple_animal and you are in help intent. This applies to all mobs now.

**Comment by dannno** [comment]
I noticed that Runtime's corpse can only be pushed, even on help intent too

**Comment by tkdrg** [comment]
I can't reproduce this. As long as I'm on help intent, I can switch position with the "help" simple animals just fine. The "harm" simple_animals (mining mobs, constructs, aliens, clowns, russians, statues and parrots) can only be pushed and not swapped over, as intended. Do you have more details?

**Comment by Anonus** [comment]
They switch places with people and they're butterflies, it's just silly.

**Comment by tkdrg** [comment]
Could just give them the PASSMOB flag, as with drones.

**Comment by WJohn** [comment]
This also means that butterflies can swap places with people and put them onto tables.

**Comment by Miauw62** [comment]
shouldnt butterflies have all the passflags?
