### ISSUE TITLE
Security lockers spawn in front of each other

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6875]
Security lockers seem to spawn based on the number of security officers now. If there are enough officers, a second row of lockers starts forming in front of the first row, blocking the back ones off and impeding traffic in the tight locker room.

**Comment by Ikarrus** [comment]
Yeah, I only put this in on what was supposed to be an extreme case of server populations higher than 80. At the time there wasn't a real need to make the equipment room any bigger just to fit in lockers that wouldn't normally spawn.

But since tg is stronk now we may need to review this
