### ISSUE TITLE
Cargo shuttle breaks for seemingly no reason

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#6876]
Shuttle is docked in cargo
Empty crates are inside
Click "Send to centcomm" on supply console
It says "The supply shuttle has departed."
I didnt depart in reality, it stays docked in cargo, both supply console and wall mounted displays show that it is still docked
Happened on sybil

@Carn

**Comment by tkdrg** [comment]
it is known, and should be fixed in #6870. There's also another bug report about this.
