### ISSUE TITLE
Critical condition period is very short.

### ISSUE THREAD

**Issue by Cheridan** [tgstation/-tg-station#6881]
Previously, it was like 5 minutes. Currently it's more like 10 seconds. Very short.

**Comment by Tenebrosity** [comment]
I don't understand. Isn't this intentional? Hasn't the game functioned like this for years?

**Comment by Steelpoint** [comment]
I thought health worked from -100 to 100. If you get below 0 health you fall into critical condition, if you hit -100 you die.

**Comment by RemieRichards** [comment]
What @Steelpoint said. Pretty sure this is entirely intentional. 100HP of "Conscious" health and 100HP of Critical condition health.

**Comment by Jalleo** [comment]
Crit is down to -100 health from the 0 point I thought.

**Comment by RemieRichards** [comment]
100 HP (Fine)
0 HP (Crit begins)
-100 HP (Dead)

**Comment by Steelpoint** [comment]
It would be cool if we had a system similar to Goonstation where you can still move around in critical condition.

But I digress, everything is working as intended.

**Comment by Jalleo** [comment]
@Cheridan can you explain more or is it a simple derp?

**Comment by dannno** [comment]
it's joke

**Comment by Razharas** [comment]
No idea what cheri is talking about here

**Comment by Tenebrosity** [comment]
(make it like 2 minutes instead of 5)

**Comment by Boggart** [comment]
Can confirm, oxyloss accumulates rediculously fast now.

**Comment by Carn** [comment]
I have a horrible feeling this may have been me. But I've no idea what would have caused it

**Comment by Carn** [comment]
nevermind, found it
