### ISSUE TITLE
ministation's broken

### ISSUE THREAD

**Issue by syndicute** [tgstation/-tg-station#6888]
Not like many care about it. I do, tho.

**Comment by Jalleo** [comment]
Have you updated your version of the code since two days ago?

**Comment by syndicute** [comment]
Fuck.

**Comment by Jalleo** [comment]
I presume that you didnt then there was a issue with the shuttles which meant a update was required and it got fixed two days ago.

**Comment by syndicute** [comment]
Could you point the commits where it was fixed? I run a modified version of Ministation and need to fix it as well.

**Comment by Jalleo** [comment]
What does your ministation look like?

**Comment by syndicute** [comment]
http://a.pomf.se/oxdvga.jpg
It has some extra jobs and shit

I still need help porting it to latest /tg/ version, btw. What to do about the shuttles thing?

**Comment by Jalleo** [comment]
if you hop onto our IRC on Rizon #Coderbus and wait for carn to appear or ask @tkdrg  or anyone else who can help they will be able to help you fix the shuttles or you could get the pure TG version then copy your changes into that map.

**Comment by tkdrg** [comment]
You can use https://tgstation13.org/wiki/Guide_to_mapping#Shuttles which is an (incomplete) guide to the new shuttles. Feel free to catch me on IRC if you need more help.

**Comment by pudl** [comment]
that station is very, very poorly mapped. you should look into revising it a lot more before you submit it. also, just making it a small station with every job is totally against giacom's original intention.

**Comment by syndicute** [comment]
Players on my station barely know how to walk and they just go around killing everything that moves. Our staff is as well composed by filthy monkeys. You shouldn't had clicked expecting good things.

Got it to work.

**Comment by Jalleo** [comment]
@pudl its their own map its a downstream they do what they want.

**Comment by Jalleo** [comment]
also congrats
