### ISSUE TITLE
ETA missing while emergency shuttle is moving

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#6890]
I'm not sure whether this is a bug or intentional (to prevent shuttle griff?), but there is no ETA indicator on the Status tab while the emergency shuttle is moving at the end of a round.

**Comment by tkdrg** [comment]
Neither am I, to be honest. @Carn

**Comment by Razharas** [comment]
It should be returned either way, im placing bug for now

**Comment by Carn** [comment]
I don't understand what the problem is here. The shuttle timer is still present on the Status tab.

**Comment by bgobandit** [comment]
ETD shows properly when the shuttle is docked, but when it departs, the Status tab shows nothing (if you are on the shuttle, I haven't tested otherwise).
