### ISSUE TITLE
Gateway wait variable does not update in VV.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#6895]
http://i.imgur.com/nGLPYPm.png

It is always frozen at some number (depending on config, I think), at the start of the round, well past its due date, or when the away gate is opened. This was at a 15 minute gateway open time to get this number I think.

Very minor bug though.

**Comment by Menshin** [comment]
The _wait_ var is actually the _world.time_ at which the gateway becomes active.
It's set once and for all on round start.

No issue here, except a misleading variable name.

**Comment by WJohn** [comment]
Oh, I thought it was time remaining.
