### ISSUE TITLE
Cloning can randomly break due to a runtime

### ISSUE THREAD

**Issue by Ergovisavi** [tgstation/-tg-station#6898]
Cloning can sometimes runtime, leaving the attempting var set to 1, causing initialization errors forever and breaking the clone pod until it's reconstructed.

runtime error: Cannot execute null.set cloned appearance().
proc name: growclone (/obj/machinery/clonepod/proc/growclone)
  source file: cloning.dm,186
  usr: Dominic Fiddler (/mob/living/carbon/human)
  src: the cloning pod (/obj/machinery/clonepod)
  call stack:
the cloning pod (/obj/machinery/clonepod): growclone("yamaraya", "Serpentus Serpenti", "ff6ff61ed0f04b7ca404c", "563656420142054462403660642225...", "\[0x2100751a]", /datum/species/lizard (/datum/species/lizard), "888", /list (/list))
the cloning console (/obj/machinery/computer/cloning): Topic("src=\[0x2007d2b];clone=69e2", /list (/list))
Braincake (/client): Topic("src=\[0x2007d2b];clone=69e2", /list (/list), the cloning console (/obj/machinery/computer/cloning))

**Comment by Ergovisavi** [comment]
@Razharas

**Comment by phil235** [comment]
I'm not sure but it may have been fixed by #6847
