### ISSUE TITLE
[Feature request] People can spam the chat with excessively long, copypasted messages

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6905]
When people do this it hinders communication, so there should probably be a character limit on chat messages just like there are on job titles and character names. It shouldn't be too short, but more than two lines is probably excessive.

**Comment by Xhuis** [comment]
~~rip woody's got wood~~
Might be for the best.

**Comment by tkdrg** [comment]
There is a limit. 512 characters I think.

**Comment by Tenebrosity** [comment]
Oh, okay. That's still pretty long in terms of screen real estate.

>rip woody's got wood

You could still read it, it would just force you to break it up into bite sized chunks to prevent spam.

**Comment by PKPenguin321** [comment]
Delet this

**Comment by duncathan** [comment]
I mean, there is a limit
