### ISSUE TITLE
NTSL Script Compile Runtime

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#6906]
runtime error: Cannot read null.value
proc name: ParseFunctionExpression (/n_Parser/nS_Parser/proc/ParseFunctionExpression)
  source file: Expressions.dm,310
  usr: Wilson H. Stockwell (/mob/living/carbon/human)
  src: /n_Parser/nS_Parser (/n_Parser/nS_Parser)
  call stack:
/n_Parser/nS_Parser (/n_Parser/nS_Parser): ParseFunctionExpression()
/n_Parser/nS_Parser (/n_Parser/nS_Parser): ParseExpression(/list (/list), /list (/list), 0)
/n_Parser/nS_Parser (/n_Parser/nS_Parser): ParseAssignment()
/n_Parser/nS_Parser (/n_Parser/nS_Parser): Parse()
/datum/TCS_Compiler (/datum/TCS_Compiler): Compile("$explodeVec = explode($content...")
Security Server (/obj/machinery/telecomms/server/presets/security): compile(Wilson H. Stockwell (/mob/living/carbon/human))
Xhuis (/client): tcscompile()

runtime error: bad client
proc name: process (/obj/machinery/computer/telecomms/traffic/process)
  source file: traffic_control.dm,63
  usr: null
  src: the telecommunications traffic... (/obj/machinery/computer/telecomms/traffic)
  call stack:
the telecommunications traffic... (/obj/machinery/computer/telecomms/traffic): process(2)
Machines (/datum/subsystem/machines): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()

Found on my own test server while experimenting with telecomms scripts. This was the standard 'voice synthesizer' script found on the wiki. It also appears to disappear. I have no idea why this would happen and I still don't know anything about NTSL.

**Comment by ike709** [comment]
Could #6786 have caused this?

**Comment by Miauw62** [comment]
Oh wait this is a dupe. Thanks for reporting anyway.
