### ISSUE TITLE
Suggestion: Rebalance giant spiders

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6910]
They can crit you in four hits, they have a lot of health and most of the crew don't have access to the ranged lethals needed to avoid being hit by them.

**Comment by Ergovisavi** [comment]
Every crew member on the station has access to spears (25 throwforce) and Rods/Floor tiles (10 throwforce) as well as a weak antitoxin (tea)

Git gud, scrubs

**Comment by dannno** [comment]
Yeah they're strong and they cause a ruckus but never really in a way that made me go "Holy shit these need rebalancing".
kinda seem fine as is

**Comment by TZK13** [comment]
They're fine when they're NPCs but I will say that they're extremely powerful when player controlled. Considering that only happens due to admin shenanigans though it's not much of an issue.

**Comment by Lumipharon** [comment]
They're hilariously OP as player controlled, simply because queens can shit out new spiders x20 faster then xenos. Also the poison is deadly as shit if you don't have anti toxin/tea on hand, if you don't, chances are you're going to die.

But they're admin only at the moment so meh.

**Comment by ACCount12** [comment]
Admin-only? Can't random event spawn them?

**Comment by TZK13** [comment]
We both mean player controlled spiders, random event spiders are always NPCs.

**Comment by Tenebrosity** [comment]
Changelings can spawn spiders.

>Git gud, scrubs
You act as though every player powergames by building spears as though they're going to have to deal with something like this.

**Comment by Firecage** [comment]
Even NPC spiders can be hilariously OP though. As several rounds this past week has shown.

**Comment by KorPhaeron** [comment]
@tkdrg 

Not a bug

**Comment by tkdrg** [comment]
yes they're ok to be honest
