### ISSUE TITLE
Admin healing a player who turned himself into a monkey turns him back to human.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#6911]

**Comment by Tenebrosity** [comment]
Seems like intended functionality to me. I'm not certain though.

**Comment by Jordie0608** [comment]
I wasn't able to reproduce this? What server did you encounter this on?

**Comment by GrayRachnid** [comment]
Did you make sure you monkey him using genetics not using admin commands?

And yogstation.

**Comment by Jordie0608** [comment]
Yes.

It's likely this issue is related to yogstation code rather than tg's.

**Comment by GrayRachnid** [comment]
This was probably fixed by mutation datums(?) since yogs hasn't really merged yet,
