### ISSUE TITLE
Syndicate earned Minor Victory when disk was on emergency shuttle

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#6912]
Nuke ops round, I'm all access clown (honk), I take the pinpointer and notice the disk is in the library backroom (so I imagine it probably respawned there). Take the disk, stuff it in giggles von honkerton (not in a box I don't think), get to CentComm and:

Syndicate Minor Victory!
The Research Staff failed to secure the authentication disk but did manage to kill most of the Prima Biotech Operatives!
The syndicate operatives were:
Jagster08 was Joel Niggers (body destroyed)
Stickymayhem was Austin Niggers (body destroyed)
IRazgriz was Walter Niggers (body destroyed)
RumyanyPirozhok was Devon Niggers (body destroyed)
Mime Mimington was Travis Niggers (body destroyed)

dafuqman

**Comment by TZK13** [comment]
Didn't you get the title wrong then? Shouldn't it be "Syndicate earned Minor Victory when disk was on emergency shuttle"?

**Comment by paprka** [comment]
These win states are so fucking broken actually

**Comment by Boggart** [comment]
I recently saw a cult get 0 escaped despite people being on the shuttle.

**Comment by bgobandit** [comment]
boop I'm a moron

my best guess as to what might be causing this: if the disk respawns, is there some sort of flag that doesn't properly get unset?

**Comment by bgobandit** [comment]
I think this might have happened again in a recent sibyl round, no details though sorry

**Comment by tkdrg** [comment]
Should be fixed by #6933

**Comment by Carn** [comment]
Oh, forgot to reference this issue, thankyou.
