### ISSUE TITLE
Emergency shuttle arrival and departure is no longer announced.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#6915]
What it says on the tin, the emergency shuttle departure and arrival aren't announced anymore.
I've noticed this as a human, AI, borg and ghost on multiple rounds. I've also heard at least one person complain about it. Shuttle auth and emag announcements still work.

**Comment by paprka** [comment]
What mob were you? Was this under normal circumstances? What time did this occur?

Use the bug report format for shit like this please.

**Comment by Miauw62** [comment]
Shuttle messages are world << iirc
Op 9-jan.-2015 21:58 schreef "paprka" <notifications@github.com>:

**Comment by Carn** [comment]
what do you mean by announced?

**Comment by Boggart** [comment]
There used to be a voice announcement as well as a large message in the chatbox like a centcomm one. Neither seem to happen anymore. I've edited the first post with more info.

**Comment by Carn** [comment]
I think this is probably due to me copypastaing FP code which looked identical. (FP was based on an older revision of TG)
