### ISSUE TITLE
Gygax construction missing left arm

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#6916]
when you attach the left arm it doesn't show up until the end of construction. very minor.

**Comment by Fox-McCloud** [comment]
Yeah--not surprising; this issue was corrected on our server--I believe one piece is improperly labeled (can't recall which now).

**Comment by Miauw62** [comment]
wait, is this fixed?

**Comment by Jalleo** [comment]
probably not @Fox-McCloud has a different codebase source.

**Comment by Fox-McCloud** [comment]
@Miauw62 

No; it's fixed on our codebase, but not yours.
