### ISSUE TITLE
It's possible to make macros.

### ISSUE THREAD

**Issue by Spacemanspark** [tgstation/-tg-station#6919]
Problem Description: I figured out a way to make macros.

What did you expect to happen: Macros to be unavailable on /tg/ coded servers.

What happened instead: I can make macros.

Why is this bad/What are the consequences: Because lolmacros.

Steps to reproduce the problem: 1. Go to a server using baycode.
2. Click the SS13 icon at the top left hand corner.
3. Make your macro (There's an option for it there.). Make sure it doesn't overlap with any button combinations here already. ![](http://i.imgur.com/l4tbsAK.png)
4. Go to /tg/.
5. Profit.

Server: I was on Sybil when I realized my macro for LOOC had carried over (although I couldn't use it, obviously). Went to Paradise to test it with /me as well, and it does work.

Revision: The latest.

**Comment by Miauw62** [comment]
this is pretty severe.

**Comment by Spacemanspark** [comment]
I'm pretty sure you can do this with any baycode server now, went on a few and tested it, same menu pops up and my macros carry over.

**Comment by tigercat2000** [comment]
You can also hit the 'edit skin' button to directly modify skin.dmf locally. The reason this does not work on goon is due to huge differences to their hotkey systems, I believe.

**Comment by Jalleo** [comment]
someone should contact Tobba on this.

**Comment by HoaxIT** [comment]
lets make this a feature

**Comment by Carn** [comment]
https://github.com/tgstation/-tg-station/blob/ab98b7e94d47813b15ca757f5564dcd2ba691775/code/modules/client/client%20defines.dm#L31
Please report this on the byond forums.

Although, tbh, I think we should allow creation of macros and just start removing bad verbs. I'd much prefer that to what MrPerson is proposing.

**Comment by Spacemanspark** [comment]
http://www.byond.com/forum/?post=1762168

**Comment by Nexendia-** [comment]
Well Daaaaamn glad I stumbled upon this :^)    and I agree with HoaxIT make it a feature

**Comment by Delimusca** [comment]
i noticed the macros stop working for me when a round ands and auto-reconnect happens, that might help with tracking it down.

**Comment by Chnkr** [comment]
There is a workaround for this, i'll PR it soon.

**Comment by Spacemanspark** [comment]
oh wow I'd forgotten about this.

**Comment by Jalleo** [comment]
@MrStonedOne if only byond fixed this already.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access somebody add byond issue to this

**Comment by MrStonedOne** [comment]
This can be closed actually, it was already fixed

**Comment by Spacemanspark** [comment]
I've updated to the latest version of Byond, and I'm still able to do this.

**Comment by duncathan** [comment]
@Spacemanspark
By following the steps listed in the OP?

**Comment by Spacemanspark** [comment]
Yes.

**Comment by Spacemanspark** [comment]
https://www.youtube.com/watch?v=i-DEjzh_j2s Also a crappy video for demonstration.

**Comment by Spacemanspark** [comment]
This is still an issue, though at this point I really doubt this is fixable at all.
¯\_(ツ)_/¯
