### ISSUE TITLE
XRAY Lasers are kind of awfully balanced/maybe should exist at all

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#6928]
It's time we really think about just how fair Xray lasers are. They pretty easy to make, and they're basically just a win item.

examples:

>blob 
>become HUGE
>crew struggling to deal with even a bit of me
>cover all of brig
>a couple of guys stroll up with xray lasers
>2 seconds of shooting, 65-70% total mass is now gone

utter devastation

>hop 
>xeno outbreak
>get buttfucked in the pussy by xenos, fair cop
>watch xenos as ghost
>they're doing really well, taking on the crew pretty good
>1 person walks up with a laser and begins spray&praying through the wall
>queen dead, 2 babies dead, 1 hunter dead
>in one clip

**Comment by dannno** [comment]
woops, accidnetally hit enter

**Comment by paprka** [comment]
You forgot

>Be blob
>Shit on everything
>Riot armor? lol blobbernaut
>There's a counter to blob
>It shits on me

Should I start in science next time to deny them access to the research materials? What about the mining dock to deny them materials?

LOLNO, PLEASE NERF, REMOVE THIS SHIT, UNBALANCED AS FUCK!!!

You sound like a valve fan homie

**Comment by leibniztg** [comment]
This is kind of how the game works, if you are an antag that like to take their time (malf, blob, etc), after a while things come out of the east side of the station, like genetics, robotics, RnD, that have no counter besides stomping them early, and shit all over you.

**Comment by dannno** [comment]
then maybe blob is unbalanced as well?
I don't think the solution to blob being too strong isn't to give people a relatively easy to acquire gun that can be used on everything that ISN'T blob as well

if you're a blob and you start across the station from science, are you supposed to use every point you have slowly crawling towards it in the hope to get there before anyone notices? it feels like it could be improved.

**Comment by dannno** [comment]
Shit shouldn't be a rock/paper/scissors, especially when rock ALSO shits on everything that isn't scissors

this can be improved and I think we should talk about it.

**Comment by Fox-McCloud** [comment]
burst near mining dock or R&D and you pretty much shut down the chances of x-ray ever being a threat--yes, I know there's a backup of R&D in tech storage,but it's going to really slow them down if the main lab gets wrecked.

Xenos are already pretty gamebreaking---I have zero pity for any nerfs they ever get, either directly or indirectly.

**Comment by Lumipharon** [comment]
As far as I know, xray lasers DO NOT go through walls/r-walls, and some other dense shit like that. I've tried with xray and xray lasers, it didn't work.

**Comment by Anonus** [comment]
Last I tested, they went right through walls, because I was blowing up fuel tanks in maint with them from the hallways.

**Comment by AlexanderUlanH** [comment]
This kind of thing is what relocate is for.  If you're that big, you probably have or can easily generate the resources and swap your core out.

I just tested xray lasers, and they did go through everything, walls and machines included.

**Comment by dannno** [comment]
>As far as I know, xray lasers DO NOT go through walls/r-walls, and some other dense shit like that. I've tried with xray and xray lasers, it didn't work.

they do.

**Comment by Fox-McCloud** [comment]
They do, and I'm pretty sure they're meant to.

**Comment by Lumipharon** [comment]
That's odd because I remember like a year ago when I played around with them, I assumed they would go through walls, but when I tested with thermals/xray vision, they didn't go through as far as I could see.
I unno.

**Comment by Fox-McCloud** [comment]
@Lumipharon 

They were only recently changed to allow them to pass through things; a year ago they were pretty much just lasers that did 5 less damage and irradiated.

**Comment by Jalleo** [comment]
The damage the laser from the Xray gives should be reduced per thing it hits including walls (probably a bit more when going through a wall especially a Rwall)

The reason for this it actually gives blobs some time to actually respond to this threat and it gives xenos time to escape especially if that person has xray vision because if they shoot through a wall or two you should be barely damaged its a big slab of metal with more metal on it.

Its more balanced that way creating at least some sort of metagame for it compared to how it is now being either GG no RE or barely beat them then deal with even more because once there is one there is usually more.

**Comment by Fox-McCloud** [comment]
I really don't see the problem, to be honest; X-ray guns are ultra high-end R&D items; it's literally the highest-end item you can currently make and takes a solid 20ish minutes to research--plus you need to wait for miners to bring you back goods for it.

If either of these are disrupted during a blob round (easy to do), then x-ray lasers aren't going to happen.

**Comment by dannno** [comment]
They obviously aren't high end when literally 10ish minutes into a round you can mass produce them under relatively good conditions

Having them decrease damage and even fade away after hitting a certain amount of things is a good idea. I'd say maybe 3-4 things.

**Comment by paprka** [comment]
That only happens if mining, robotics, and rnd are all doing their jobs

Which never happens, especially during blob

You're making a big deal out of a rare case of the crew actually doing their jobs to make a weapon which is a direct counter to blobs, and then complaining when blobs get countered, which isn't that big of a deal since I already told you how to counter that as blob (by bursting in the mining dock, or research, and cutting off their ability to make weapons to fight you)

But naturally you want the PLS NERF casual bullshit

**Comment by Lumipharon** [comment]
Pretty much what pap said. 
Having said that though, xray lasers going unimpeded and undiminished through a dozen walls is a tad OP if you're a tator with thermals etc, as you can basically murder the shit out of people and they have literally no idea where you are.

**Comment by paprka** [comment]
Yeah they shouldn't go through rwalls.

**Comment by dannno** [comment]
Even if they are supposed to be a check to blobs, if you get them on any round that isn't blob they are still retardedly strong, to a point where nothing is really a threat to you if you have one and can use it semi properly
