### ISSUE TITLE
Malf AIs can hide off-station -- Very unfair

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#6934]
It's possible for the AI to have it's borg send it to one of the many powered locations off-station, such as mining.

You'd expect the AI would need to be on the station to take it over. I feel that it's rather unfair to also have the crew comb the asteroid and who knows where in space it could be.

I think the malf countdown should be paused while the AI is off-station.

**Comment by Fox-McCloud** [comment]
Agreed, either that, or prevent the AI being unbolted during malf AI.

**Comment by Miauw62** [comment]
Preventing the AI from being unbolted would be lame though.
Op 10-jan.-2015 05:14 schreef "Fox-McCloud" <notifications@github.com>:

**Comment by Fox-McCloud** [comment]
@ Miauw62

Eh, not really; you can't card a malf AI either.

**Comment by Miauw62** [comment]
yeah, but carding and unbolting are two very different things. carding can only be done by humans which means that itd basically always be bad for the malf AI, and unbolting can be used for shenanigans.

**Comment by Boggart** [comment]
I've seen malf AIs use unbolting to hide in creative places like the toxins burn chamber, making the countdown freeze if the AI is off the z-level makes sense.

**Comment by Jalleo** [comment]
really malf AI needs a redesign.

**Comment by stapler2025** [comment]
http://i.imgur.com/JUWr4uo.png

This shit is unfair, why has it been almost 3 weeks and this not been looked at?

**Comment by Jordie0608** [comment]
Fixed by #8665
