### ISSUE TITLE
Attacks have a 1% chance to hit two zones

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#6935]
From what I can tell, roughly 1% of the time, an attack will be able to hit both the right arm and left leg at once.

Guessing that this should be 11 to 14
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/mob_helpers.dm#L172

And guessing should be 15 to 18
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/mob_helpers.dm#L173

and therefore var/t would be 1,18 instead of 1,17.

**Comment by Dorsisdwarf** [comment]
Hold your arms out in front of you, and stand still while I fetch my sledgehammer.

**Comment by phil235** [comment]
Technically, it doesn't hit the two zones, it only returns the first one, which stops the proc.
