### ISSUE TITLE
Fire cannot spread on shuttle turfs

### ISSUE THREAD

**Issue by Carn** [tgstation/-tg-station#6936]
This is not so much an issue with shuttle turfs, as an issue with fire-spreading code.
This is merely a note for myself to investigate.

**Comment by Anonus** [comment]
Related, #3947 and #3554

**Comment by Jalleo** [comment]
I think Aran mentioned the rewson why somewhere.....

**Comment by Carn** [comment]
Oh, I didn't see those issues. This is a duplicate
