### ISSUE TITLE
Ability to grab borgs allows you to neck grab and therefore stun and kill them by choking them

### ISSUE THREAD

**Issue by Ergovisavi** [tgstation/-tg-station#6945]
Grab borg, neck grab borg, borg is now stunned forever and taking oxyloss.

**Comment by Miauw62** [comment]
lol

**Comment by Steelpoint** [comment]
What's really happening is that your chocking their brains oxygen supply.

**Comment by Jalleo** [comment]
But borgs dont breathe @steelpoint

**Comment by RemieRichards** [comment]
The borg brain needs some kind of oxygen though, but that's fluffy.

**Comment by Steelpoint** [comment]
I'm just imagining the person reaching in and chocking some kind of oxygen/blood tube that feed's the borgs brain.

Tbh this is a bug that should be fixed, I'm just less inclined to see it fixed because there are already few ways for the average joe to contend with a borg.

**Comment by Miauw62** [comment]
>implying borgs dont use spessh majicks to generate oxygen

**Comment by Miauw62** [comment]
borgs dont have lungs so they could probably use some high-density oxygen containing liquid and use that for their oxygen supply.

**Comment by paprka** [comment]
Grabbing borg mobs, realism discussion aside, is clearly a bug.

**Comment by Firecage** [comment]
@paprka , but it appears that it was intentionally made that we are able to grab them. Considering it was made on purpose that secborgs can't be grabbed.

**Comment by Dorsisdwarf** [comment]
Top tip: You can throw borgs into doors to open them. This means that a braindead/dead borg is secretly an all-access ID

**Comment by kevinz000** [comment]
>>Borgs need to breathe
>Oh hi engiborg whos alive and afk in space
