### ISSUE TITLE
Shuttle arrived during a Revolution round

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#6947]
@Carn what it says on the tin all the info I know.

**Comment by RemieRichards** [comment]
if this was yesterday on basil it's not a bug.

**Comment by Jalleo** [comment]
No it was today on Sybil scaredy reported it

**Comment by Carn** [comment]
What is expected to happen? Does it normally always do the fake-recall stuff during nuke?

**Comment by tkdrg** [comment]
On gamemodes with emergencyAlwaysFakeRecall (blob, malf and rev), the shuttle should never arrive, yes. I assume nuke was a typo.

**Comment by Carn** [comment]
Ok so it's a bug with alwaysFakeRecall, thankyou. I'll investigate.
I want to look at fire-spreading on shuttle turfs first

**Comment by Carn** [comment]
problem located... amateur mistake
rand(0.5, 0.8) will not work as it only supports integers. The arguments are rounded to the nearest integer, meaning in some cases alwaysFakeRecall would set fakeRecall to 0 accidentally, meaning the shuttle is never fake recalled.
