### ISSUE TITLE
Malf AI's bolt and shock all doors also works on the away mission

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#6949]
happened on sybil, away mission was UO45. not sure if it's a map issue or something to do with malf coding.

**Comment by Carn** [comment]
Somebody could add in an if(door.z != ZLEVEL_STATION) return check

**Comment by Ergovisavi** [comment]
You'd have to add in an exception for the asteroid as well.

**Comment by Carn** [comment]
Is the AI meant to be able to control the asteroid? Seems a bit odd

**Comment by Chocobro** [comment]
pretty sure it is, the asteroid is considered nanotrasen property imo

**Comment by Carn** [comment]
I meant in a gameplay sense. I thought asteroid was meant to be isolated.

**Comment by Jalleo** [comment]
AI has access to the mining camera network and thus ability to directly interface with the doors. Technically anything in camera range is but this really shouldn't work for the derelict doors and other doors which arent using the nanotrasen circuit airlocks but this needs a huge rework with doors anyhow.
