### ISSUE TITLE
Jump to Area verb is based on type

### ISSUE THREAD

**Issue by Carn** [tgstation/-tg-station#6971]
Jump to area verb is based on area type, which is less than helpful at times.
For example, attempting to jump to any shuttle area will probably jump to syndicate shuttle.
It could potentially be changed to jump to areas based on their names.

**Comment by tkdrg** [comment]
A complicating factor would be that area teleport code is copy-pasted in various places instead of all calling the same proc (see #6014).

**Comment by Carn** [comment]
Working on this issue
