### ISSUE TITLE
You can invoke runes with mutetoxin in your body

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#6977]
Self-explanatory. When you're muzzled you get a message saying you can't speak the words of the rune, but with mutetoxin you can invoke the rune. You won't say the incantation but the rune will still work.

**Comment by TZK13** [comment]
Can't mimes use runes no problem without speaking?

**Comment by Miauw62** [comment]
Sounds like an outdated check that should be can_speak() but that is
is_muzzled() right now.
Op 11-jan.-2015 21:35 schreef "Xhuis" <notifications@github.com>:
