### ISSUE TITLE
Silencers cannot be attached to syndicate pistols

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#6982]
When you hit the pistol with the suppressor (and vice-versa) nothing happens.  Not tested with other weapons.

**Comment by paprka** [comment]
why maintainers should review large prs faster

**Comment by tkdrg** [comment]
Works for me on local.

**Comment by paprka** [comment]
Can you pinpoint what broke this maybe?

**Comment by tkdrg** [comment]
You didn't call ..() in the attackby() you added in the tactical reload PR, so you dropped all generic gun behavior. You could add the following snippet to the beginning of each of the new attackby()s you created:
```
. = ..()
if(.)
    return
```

**Comment by tkdrg** [comment]
Don't forget to do it for both automatic and crossbow, as well.

**Comment by paprka** [comment]
Why that line of code and not just ..()?

**Comment by tkdrg** [comment]
Because any part of the attack chain returning 1 is a signal to interrupt it. It's not that big of a deal in this specific case, but it's technically the correct way.
