### ISSUE TITLE
Jaunted MMIs are immortal, invisible and can still cast spells.

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#6983]
A Jaunting MMI (possible with the Robeless Spells event) is capable of casting spells while being invisible and untargetable. They can't see themselves and otherwise cannot move.

**Comment by Incoming5643** [comment]
Intense Edge but probably pretty easy to fix

**Comment by Stickymayhem** [comment]
It's an edge case but it did result in everyone in medbay being killed by a magic missile meteor spamming MMI

**Comment by Incoming5643** [comment]
That's just a bonus

**Comment by Miauw62** [comment]
I have some brainmob fixes up right now that may fix this.
Op 12-jan.-2015 02:36 schreef "Incoming5643" <notifications@github.com>:
