### ISSUE TITLE
Open to Abuse - Raging Mages

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#6991]
There's nothing stopping wizards from attacking each other while in the den. A wizard can easily spawn camp the latter wizards and take all their spell books for themselves.

This is way too open for abuse, a hole that's too large to be covered by admins alone. I'm calling for a code solution to this as well.

**Comment by Razharas** [comment]
What do you propose?

**Comment by Ikarrus** [comment]
Have it check if the incumbent wizard has left the den before spawning the next one.

**Comment by Razharas** [comment]
Stay in the den - griff the round

**Comment by Ikarrus** [comment]
Separate rooms would also work

**Comment by Anonus** [comment]
If they don't want to griff, they can just leave their spellbook to give some lucky wizard 5x EI NATH

**Comment by Iamgoofball** [comment]
looking into locking spellbooks to people+no spells in the den

**Comment by leibniztg** [comment]
Well, teleport spells are restricted on the centcom z-level, right?
We could just restrict all spells like that.

**Comment by Ikarrus** [comment]
That would be unfortunate, because I always found the den to be an excellent testing ground for new wizards to learn what their spells did before they set themselves on fire on the station. If we have to limit all spells altogether, can we not make it apply to regular wizard rounds?

**Comment by Deantwo** [comment]
Or make a private den for each wizzard?
Just an idea.
