### ISSUE TITLE
No way to identify Wizard apprentices

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#6992]
Needs to be a way to identify when someone's your apprentice, even if they've mindswapped. This'd make going confusion wizard actually worth doing without fucking everything up and accidentally killing each other.

**Comment by Jalleo** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
Rev style icon updates aren't cheap, especially when you have to deal with edge cases of wizards/apprentices who are also Revolutionary Cult Gangsters. There are such things as planning to use identifying code words, wear specific clothing, otherwise signal which team you're on.

I don't really think this is a problem needs solving, more it's an inherent challenge of going full mindswap apprentice.

**Comment by tkdrg** [comment]
Actually, after my antag HUD rewrite, it's really cheap to create and maintain an antag HUD. It's also impossible to have multiple antag HUDs, this applies to all antag types so I don't see how that is an issue here, it's an inherent restriction of placing the HUD on the same position in the screen for all of them. If it is necessary or not it's another question, but it shouldn't be expensive or hard to implement (though I do admit the new antag HUD code is undocumented and a bit dense sometimes).

**Comment by Incoming5643** [comment]
oh? Well I can look into it then.

**Comment by PKPenguin321** [comment]
>not just making wizards into gangsters when they summon an apprentice

**Comment by paprka** [comment]
Apprentices should have randomized scarves.

**Comment by TheVekter** [comment]
I like that idea, actually.

**Comment by AnonymousNow** [comment]
I dunno... it may be hard to make, as it involves checking for both antagonistic status A and antagonistic status B, and variations of their presence, but I kinda like the idea of the HUD icon wiping between all antagonist types associated witht that person every couple of seconds in rotation, faster if there's somehow more than 2.
