### ISSUE TITLE
Cargo Supply manifests are slightly wrong

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#6995]
Currently the number of crates recieved is +1 on all arriving manifests.
Example: You order 6 crates and all 'correct' mainfests read 7 PACKAGES IN THIS SHIPMENT.
If you stamp them with the DENIED stamp, you lose points upon sending the shuttle back - stamping them with the GRANTED stamp gives you the usual extra point.

EDIT: It seems the X PACKAGES IN THIS SHIPMENT is never really checked. Order 6 crates, stamp '8 PACKAGES IN THIS SHIPMENT' as wrong, lose points.

**Comment by tkdrg** [comment]
@Carn

**Comment by optimumtact** [comment]
Looks like the error check was flipped for manifests, so non error manifests got a random len bump of 1 or 2

**Comment by Carn** [comment]
thanks oranges.
It may be a while before I get to this, so feel free to fix it if you can easily.

**Comment by optimumtact** [comment]
#6998
