### ISSUE TITLE
Adminspawned vendors don't work

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#6996]
Booze-o-mats when spawned by an administrator says it has no product loaded when used.  If you use a refiller, it says the booze-o-may is full and you can't load the product.  Upon using the booze-o-mat after this, it still says no product loaded again.  Making it impossible to use.

**Comment by tkdrg** [comment]
You need to deconstruct it and construct it again. No idea why, though.

**Comment by Fayrik** [comment]
For the coders out there: This is caused by the initialize function not being called when the object is created.
For the badmins out there: Atom-Proccall initialize 0, in the mean time.
