### ISSUE TITLE
Timsort is borked

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#6997]
Timsort is borken

>fix one mistake >reveals another bug >reveals a bunch of bugs which relied on that bug
yay

**Comment by optimumtact** [comment]
99 bugs on the wall, 99 bugs on the wall, take one down, patch it around 123 bugs on the wall

:musical_score:

**Comment by Jordie0608** [comment]
I'm going to close this as it tells us nothing about the actual problem and carn sure isn't going to do so either.
