### ISSUE TITLE
Let server leads create in-game polls without needing direct database access

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7003]
Feature Request

I'd like some way for server leads (Headmins, Hosts) to create an in-game poll (Like the ones you can access from the lobby menu) without needing direct database access. Preferably the method should remain in-game.

This may involve @mrstonedone so I'll ping him here.

**Comment by optimumtact** [comment]
Why not from the webinterface

**Comment by Ikarrus** [comment]
What web interface?

**Comment by MrStonedOne** [comment]
Hes talking about my site tools https://tgstaton13.org/tgdb/ (https://tgstation13.org/tgdbsample/ for you non-admins)

The biggest reason at the moment is that the site tools only have SELECT permission on the database.

**Comment by optimumtact** [comment]
We're doomed

**Comment by Carn** [comment]
Just switch over to the byond sql stuff. They could make polls from in-game.
