### ISSUE TITLE
Wielded item equip spam

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7004]
![](http://a.pomf.se/mgxymh.png)

on equip when wielded you get a lot of upset from the game

(happens for all wielded items apparently)

**Comment by tkdrg** [comment]
@Razharas possibly related to that runtime?

**Comment by phil235** [comment]
Tested it and didn't see any runtime happening.

**Comment by phil235** [comment]
Probablt happens to all twohanded weapons when wielded.

The message appears for each and every slot tested, that's the problem.

**Comment by phil235** [comment]
Already fixed
