### ISSUE TITLE
Can't follow deadchat/binary

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7014]
There's no follow link for either of those and ghosts want both, so it's easier to jump to other ghosts or borgs and stuff.

**Comment by tkdrg** [comment]
Intended since it can't be done without re-rendering the message for each ghost hearer.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
