### ISSUE TITLE
Clusterbangs are completely Broken

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7023]
Basically as the titles says; spawn one in, prime it, throw it, then watch as it just deletes itself once it goes off; they literally do nothing at the moment.

If you custom spawn clusterbang segments, they have the same exact issue as well.

**Comment by Jalleo** [comment]
Which server was this on?

**Comment by Fox-McCloud** [comment]
I tested this on tgstation 2.0 map--neither of TG's official server though; just a local copy.

**Comment by WJohn** [comment]
Dupe of #4399
