### ISSUE TITLE
Moving from a table onto someone else's tile.

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/-tg-station#7025]
If you are on a table with help intent activated and there is someone else in a tile adjacent to yours, you can *swap* positions with them. 

That means you'll move onto his tile and he will get on the table.

This can be used by two people to make one of them instantly climb onto the table, without dropping the items on their hand.

**Comment by optimumtact** [comment]
@hornygranny

**Comment by Jalleo** [comment]
Thisis a dupelicate

**Comment by AssassinT90** [comment]
True. #5403.
