### ISSUE TITLE
Bar, brig, and medbay are ridiculously messy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7027]
http://i.imgur.com/UlAQeO4.png
http://i.imgur.com/IAL9WBT.png
http://i.imgur.com/tituKSM.png

These places are horrifically filthy nearly every round now.

**Comment by WJohn** [comment]
Also engine room has TONS of oil all over the place, too.

**Comment by ike709** [comment]
see: #7022?

**Comment by paprka** [comment]
Barman's gotta stop binge drinking.

**Comment by Jalleo** [comment]
It really needs to be toned down

**Comment by paprka** [comment]
I already fixed this 20 hours ago

**Comment by Jalleo** [comment]
I literally saw your pr 5 mins ago thanks for solving this paprika.
