### ISSUE TITLE
Balance: Malf AI countdown Timer

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7028]
In a revert patch (https://github.com/tgstation/-tg-station/commit/08be1b34eb941fb0a66b3011676168e76cbedbff), the Malf AI countdown timer was changed (total countdown time increased to 5400 from 1800 in addition to how it counts down under process()).

https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/malfunction/malfunction.dm#L99

Was this intentional? Correct me if I'm wrong, but won't this result in the malfunction timer counting down by 6 seconds at a time instead of one? This wasn't mentioned in any changelogs, and as far as I know, wasn't really discussed. 

If it's intentional for it to countdown 6 seconds at a time, shouldn't the total time be 10,800 as opposed to 5,400?

**Comment by tkdrg** [comment]
@Carn

**Comment by Carn** [comment]
My changes wouldn't have changed anything. time_of_last_tick was in seconds, and seconds is in seconds.

So now it will decrease by 1 for each second an apc is hacked, independent of how fast the ticker is running.

**Comment by tkdrg** [comment]
I see, my bad. I don't really know what's going on here, then.

**Comment by Menshin** [comment]
I'm pretty sure OP is referring #5004, which main point was solving the malf timer rollover bug.

The malf timer logic was streamlined (and modified a bit) :

__Old__ :
* needed 3 APC hacked to countdown,
* takeover was achieved in 1h at 3 APC,
* each APC removed an additionnal 1/6 second

__New__ :
* needs 3 APC hacked to start countdown, but the countdown only stops at 0 APCs
* takeover isachieved in 1h at 3 APC, 1h30 at 1 APC
* each APC removing an additionnal 1/3 second

I can't find a changelog entry either, so i may have forgotten to do one or it got lost in limbo.

As for discussion, you can see in #5004 that the feedback was overwhelming (i remember the breaker change was coderbus consensus though).

**Comment by tkdrg** [comment]
I see. This is intended, then.
