### ISSUE TITLE
Damage delay can knock you into crit after being administered

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#7031]
I was just mining away, when I got jumped by an extremely lucky goliath. 

The goliath pulverizes Derrick Cobb!
Your armor softens the blow!
The goliath pulverizes Derrick Cobb!
Your armor softens the blow!
The goliath pulverizes Derrick Cobb!
Your armor softens the blow!
Derrick Cobb has sliced the goliath with the sonic jackhammer! (THIS STRIKE KILLS THE GOLIATH)
Derrick Cobb has sliced the goliath with the sonic jackhammer! 
... You can almost hear someone talking ... 
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...

There was a span of about two seconds after the last strike against me, during which the goliath was killed, before I went into crit. I had no toxins in my system; I wasn't cold, I had my oxygen on... there was no external source of damage, other than this goliath hitting me.

What's with the delay? And why is this, like, the fifth game-ending bug I've discovered intimately in the last two weeks or so? Seriously, I turned into an immortal, unmoving zombie last week...

**Comment by Xhuis** [comment]
I really don't know why this is, other than that damage types are checked at certain intervals. I don't know of any way around it.

**Comment by dannno** [comment]
I like it honestly. Like you muster up the rest of your strength for one last action.

**Comment by paprka** [comment]
It's delay because lag

But who cares it makes for some fun shit like someone stunning a traitor just before they pass out from toxins

**Comment by dannno** [comment]
That's basically exactly what I mean and what happened to me twice 
it's got a kind of drama to it that's pretty funny.

**Comment by tkdrg** [comment]
Damage is only checked once per tick on Life() I believe, but I could be wrong.

**Comment by AnonymousNow** [comment]
I'm not sure whether or not this is related, but I got EI NATH'd by a wizard a few tiles away, having brushed past them about two seconds beforehand.
