### ISSUE TITLE
Cyborg Module additions

### ISSUE THREAD

**Issue by ririchiyo** [tgstation/-tg-station#7036]
If you add materials to a robot, you become unable to activate it. Under the assumption that the robot in question doesn't have a metal stack already:
````
/mob/verb/make_material(mob/user)
	var/obj/item/stack/a = new /obj/item/stack/sheet/metal
	var/mob/living/silicon/robot/R = user
	var/amount = input("How many sheets") as num
	a.amount = amount
	
	a.loc = user
	R.module.modules += a
	R.module.rebuild()
````
will add the metal module to the cyborg and display it both under modules and contents, and become unable to be activated.

Edit: It does not make a different between /metal and metal/cyborg for this example, the behavior is the same.

**Comment by Aurx** [comment]
What about /obj/item/stack/sheet/metal/cyborg, does that break too?

**Comment by tkdrg** [comment]
Looks like the issue was "just" needing to put the the new module inside the module object. See e.g. #7102
