### ISSUE TITLE
Spam when trying to quick equip wielded spear

### ISSUE THREAD

**Issue by Tenebrosity** [tgstation/-tg-station#7038]
1. Put spear in active hand
2. Wield spear
3. Press E
4. Receive the following:

Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
Unwield the spear first!
You are unable to equip that.

**Comment by tkdrg** [comment]
@Razharas

**Comment by dannno** [comment]
https://github.com/tgstation/-tg-station/issues/7004

**Comment by phil235** [comment]
The message appears for each and every slot tested, that's the problem.
