### ISSUE TITLE
Over-Riding Door Timings

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7039]
Not sure if this is a bug or not, with how many door changes have happened.

When you over-ride a door's safeties, it's to my understanding it's supposed to make them close extremely quickly  when bumped into or clicked on, as seen here:  https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/doors/airlock.dm#L1014

That said, when door safeties are overridden by the AI and a door is opened, it just stays open indefinitely and never closes by itself.

Is this intentional? Also, if this is a bug and it's meant to close by itself incredibly quickly, there's balance implications of this--namely that unsafe timing overridden doors will indefinitely crush someone by themselves if someone gets caught in them.

**Comment by Jalleo** [comment]
It was changed to stay open due to lag with people getting stuck forever. @tkdrg should be able to confirm i think

**Comment by tkdrg** [comment]
I don't know.

**Comment by Miauw62** [comment]
@paprka

**Comment by paprka** [comment]
@anyone else but me i'm busy and this isn't a hard thing to debug
