### ISSUE TITLE
some Issues with new Chemistry

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#7040]
TKDRG stated:
Some concerns (for the future):
1) Make the chem heater have an actual HTML interface with user feedback on the heating progress.
2) Make the chem heater researchable/constructable and upgradable.

Fox said:
Yeah, currently the chem heater is ...really wonky; the temperature ranges from 1 to 3000 (Goon chem only needs 0 to 1000); likewise, with Goonchem you can slap the beaker in and set the temperature, then start heating/cooling and watch the temperature slowly go up/down...this is especially important in a few chemical reactions like Crank---where improperly making it will blow up in your face.

This is from the PR if any other issues exist please state them here and how they are treat it like a full list of issues so these can be fixed quickly where possible.

**Comment by Iamgoofball** [comment]
I got 0 ideas on how to pull off HTML chem heater that works right

I'll add a way to keep tabs on the temperature though, and i guess crank blows up if improperly mixed so i'll need to add that

**Comment by Jalleo** [comment]
@Iamgoofball were the botnay stuff changed at all when you did your goon chem changes? if not I can make a seperate issue report for updating the botany to make it more interfaced with the new chem

**Comment by tkdrg** [comment]
I'll see if I can improve the heater later
