### ISSUE TITLE
Botany/Food/Drinks need a bit of merging with the new goon chems system

### ISSUE THREAD

**Issue by Jalleo** [tgstation/-tg-station#7043]
They have no interactions at all yet really as we know of and should be reworked where possible to make more fun and to give botany a more greater dynamic and fun if they decide to try and make some "Ol Honkys healing chems"

**Comment by Chocobro** [comment]
literally just finished making hydroponics upgrade 2: electric boogaloo
I suggest you get a new coder to try it as it can be some good practice for them. p sure we get new coders in every few days, so.

**Comment by Jalleo** [comment]
@Iamgoofball does this need a bit more work or do you think it is relatively good and can be closed now?

**Comment by Iamgoofball** [comment]
If someone could make a list of all the bartender drinks that clash with goonchem recipes, and what recipe they clash with, lemme know.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
