### ISSUE TITLE
The spellbook is getting ungainly

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7046]
You know I'm all about more wizbiz, but the spellbook spells page is getting really long as a result.

Someone (maybe me) should look into ways to cut the book into more manageable screens either by introducing more subdivisions (the easy solution) or a more robust datum based spellbook (the cool solution)

**Comment by WJohn** [comment]
Taaaabs.

Everything should get tabs.

**Comment by Jalleo** [comment]
@Incoming5643 we could take a usability example from one of the minecraft mods by splitting different sections into their own pages so there is no need for a scrollbar ill get a example of one of the good ones later
