### ISSUE TITLE
Goonchem patches are too fucking big

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7054]
those sprites are absurdly large compared to ointment and bruisepacks.

**Comment by dannno** [comment]
they also make you scream and give you a healing message even if they don't actually heal anything.

**Comment by Fox-McCloud** [comment]
They're supposed to make you scream; it stings when it makes contact with your skin.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by dannno** [comment]
>They're supposed to make you scream; it stings when it makes contact with your skin.

at full health though?

**Comment by Fox-McCloud** [comment]
@dannno 

Yep, it's intentional.

**Comment by dannno** [comment]
Huh. I was sure it didn't work like that on goon.

**Comment by paprka** [comment]
that's stupid

i would understand if it was like rubbing alcohol but only children scream when that touches their wounds

**Comment by Iamgoofball** [comment]
@paprka your skin is knitting back together

that hurts

**Comment by Iamgoofball** [comment]
oh also the patches aren't causing the screaming, it's the styptic/silver sulf

**Comment by dannno** [comment]
>your skin is knitting back together
>at full health

**Comment by Iamgoofball** [comment]
@dannno fuck realism i give 0 fucks about it

**Comment by paprka** [comment]
We should really block people from using bandaids on themselves if they're at full health though it's stupid gameplay wise

**Comment by Iamgoofball** [comment]
no, because what if that chemical patch has other chemicals in it? what if it's a sorium dark matter clf3 patch?

**Comment by Fox-McCloud** [comment]
Exactly as goofball said. The whole point of goonchem isn't to port it over then essentially put limitations on it; that's the main highlight of Goon chem is that it's incredibly open ended and highly experimental in nature (which is why, long term, if this is a full 100% port+replace, I expect chemistry to become a sub-job of science instead of medical).

**Comment by dannno** [comment]
>fuck realism i give 0 fucks about it

fuck you 
you know I hate realism and I still think it's dumb

**Comment by paprka** [comment]
Is realism a boogyman to you shitcoders or something

**Comment by dannno** [comment]
realism is gay
