### ISSUE TITLE
chemistry heater is shit

### ISSUE THREAD

**Issue by pudl** [tgstation/-tg-station#7060]
a. it can't eject the beakers you put in until it's done heating
b. it doesn't have a gui
c. it heats INCREDIBLY slowly. 2 per tick may not seem too slow, but there is no chemical that is BELOW 200k to heat, so it takes incredibly long most of the time
d. there's no way to tell what the temperature is at the given moment

**Comment by paprka** [comment]
can you not make such terrible issues and instead make a feedback thread in the well-moderated feedback forum thanks

**Comment by pudl** [comment]
whenever people make shit like this in the feedback thread they get locked and are told "make an issue report" so fuck off

**Comment by tkdrg** [comment]
I'm working on a, b and d, i've told you on IRC already
