### ISSUE TITLE
Patches must have mask removed to apply

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#7064]
Makes no sense, especially when not targeting the head.

**Comment by Iamgoofball** [comment]
ah crap, this is what I get for not copypastaing pill code to a new object

will fix

**Comment by Iamgoofball** [comment]
this has been fixed for ages @phil235

**Comment by phil235** [comment]
Alright. Remember to add "Fixes #issueNumber" to your PRs text so it autocloses the fixed issues upon merging.
