### ISSUE TITLE
Stuck in disposals with no disposals tube on the tile

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#7071]
![image](https://cloud.githubusercontent.com/assets/6778786/5751313/960ef716-9c2f-11e4-99ee-7ddb7332956f.png)

On this tile is trapped a multitude of persons all stuck in disposals... that dont exist.

Mekhi Anderson is one of the peoples stuck there I go to that tile everytime I follow Mekhi. Stuck in the twilight zone of disposals and not disposals these poor souls caused a shuttle call

**Comment by MrPerson** [comment]
Duplicate of #7070

**Comment by Kromgar** [comment]
Someone said the people got stuck after someone put rfloor in front of the disposals
