### ISSUE TITLE
20+ Assistants on high population rounds

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7072]
Maybe the slots that aren't strictly limited by department space should scale based on server population.

**Comment by mikecari** [comment]
That's a good idea, but I guess it would make sense that a higher population would mean less employed crew.

**Comment by paprka** [comment]
assistant 30 cap when

**Comment by AlexCrimson** [comment]
Add a player limit to the server already. 60 sounds more than enough. The overflow can observe or play on the second server.

**Comment by Spacemanspark** [comment]
Paradise has a scale for assistants.
The more security officers that are online, the more assistants that can join. I think once all the security officer positions are filled, though, an infinite number of assistants can join.

**Comment by paprka** [comment]
server 2 sucks for sybil players because it doesnt run box and sos is really against server 2 being our overflow server, so...

**Comment by Jalleo** [comment]
@Spacemanspark that is not really a perfect solution really everything would need to be scaled while the server pop is higher.

**Comment by Dorsisdwarf** [comment]
requesting closure, sybil now has a soft population cap. @Cheridan

**Comment by Miauw62** [comment]
yeah we have asscaps and popcaps now so this is definitely not an issue anymore.
