### ISSUE TITLE
Chlorine Trifluoride doesn't produce clouds of acid steam as it consumes the station

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7076]
@Iamgoofball 
HUGE REALISM ISSUE

**Comment by paprka** [comment]
stop making dumb prs please

**Comment by Iamgoofball** [comment]
@paprka 
this isn't stupid actually it's something I forgot to port

clf3 actually does this irl

**Comment by hornygranny** [comment]
clf3 not in game
