### ISSUE TITLE
Dirt from walking around basically never appears

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7077]
It's just as if it was never added, basically.

**Comment by paprka** [comment]
Terrible issue report/10

How long into the round did you wait?

What was the population on the server?

As far as I can tell, on highpop(60-80), it takes about 30 minutes for any dirt to start showing up, which is what I balanced it for

**Comment by mikecari** [comment]
>people complain about too much dirt
>then people complain about too little dirt
fuck off the station is covered with blood 9 times out of 10

**Comment by paprka** [comment]
Anonus is trying to be a shill and get the feature removed, i wish it wasn't so obvious at least
