### ISSUE TITLE
Chem Heater delays release of "finished" heated chemicals."

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#7079]
Because the chem heater alters a chemical's temperature by 2 in the direction of the desired temperature, the following scenario sometimes occurs. The temperature of the chemical in the heater is 1 below the the desired temperature. It is raised by two. Now it is 1 above the desired temperature, so it is lowered by 2. And so on until heat decay randomly corrects the problem.

**Comment by tkdrg** [comment]
I fixed this in #7068 (not live on the server yet)
