### ISSUE TITLE
Turbine vent monitor without cameras

### ISSUE THREAD

**Issue by leibniztg** [tgstation/-tg-station#7093]
In the (new) incinerator there is the turbine, and a "turbine vent monitor" on the wall. (like the toxins launch monitor)
But there are no cameras around the turbine.
I suppose this is a mapping issue.

**Comment by tkdrg** [comment]
@paprka I suppose

**Comment by Miauw62** [comment]
apparently this is a dupe.

**Comment by Miauw62** [comment]
apparently its not, thanks jalleo

**Comment by Jalleo** [comment]
dont presume please wait for conformation first. Some knights of a british king one killed a priest because they heard the king raging then they went back to the king and got some bollocking

**Comment by leibniztg** [comment]
Though it should be considered that the incinerator is traditionally out of the AI's vision range, so maybe removing the monitor would be better.
