### ISSUE TITLE
Chlorine trifluoride + smoke = decimated and spaced rooms

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7094]
not sure if we need to nerf it just yet on account of goonchem only just being added, but yeah.
here's a screenshot. same scenario at escape, arrivals, sec, and a few other high-access areas.
http://i.imgur.com/tfXKiZe.png

**Comment by Jalleo** [comment]
@Iamgoofball

**Comment by RemieRichards** [comment]
and people thought polyacid was bad.

**Comment by Iamgoofball** [comment]
I'm testing some changes, running into lag issues with hotspots.

**Comment by hornygranny** [comment]
clf3 not in game
