### ISSUE TITLE
Neurotoxin(Goonchem) doesnt do anything

### ISSUE THREAD

**Issue by AlexCrimson** [tgstation/-tg-station#7097]
Tried injecting myself with 90 units of the stuff on a private server. It didn't do anything other than knock me down for a few seconds, once. No toxin or brain damage.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by drynwyn** [comment]
Did you spawn in goon neurotoxin, or the other neurotoxin? There are two reagents called neurotoxin, and one DOES do nothing but knock you down for a few seconds.

The knockdown one's ID is "neurotoxin". The new one's ID is "neurotoxin2."

**Comment by AlexCrimson** [comment]
I created it using the recipe on the wiki. Space Drugs in a heater at 200k. I was also monitoring my reagent variables or whatever, the reagent was listed at "neurotoxin2".

**Comment by Iamgoofball** [comment]
it works just fine, I just tested it

ima give it a knockout buff tho
