### ISSUE TITLE
Smoke Chlorine Trifluoride does nothing to mobs

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#7100]
Chlorine Trifluoride Smoke does nothing to mobs, only floors and things. It should probably set you on fire or do toxin damage.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Chocobro** [comment]
#7094

**Comment by Fox-McCloud** [comment]
It should definitely set you on fire--likewise, if you have any reagents inside you that require temperature to react, it should instantly set all their temperatures to 1000.

**Comment by hornygranny** [comment]
clf3 not in game
