### ISSUE TITLE
Monkey's do not Process Chems

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#7108]
![image](https://cloud.githubusercontent.com/assets/6778786/5771468/bbbd0be2-9d0b-11e4-941c-4857b6b92ca7.png)

How am i supposed to form unethical experiments now?

**Comment by WJohn** [comment]
@Carn or @Razharas

**Comment by Miauw62** [comment]
@carn is this fixed? (if it's your fault at all)

**Comment by Carn** [comment]
I've left hun.

**Comment by Iamgoofball** [comment]
@Carn fucking

called

it

**Comment by Miauw62** [comment]
@carn oh ok
