### ISSUE TITLE
Instant Crit

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#7112]
- Get hit by bomb and knocked out in a breach without internals.
- Taking damage, but not in crit.
- Get up from the knockout, desperately try to walk clear of the breach and turn internals on. Still, obviously, not in crit, though very close.
- Fall over, dead.

I didn't go into crit. I just went from standing and severely hurt, to dead. Since people in crit were being retrieved, I probably would've survived if this had worked probably - so this is yet ANOTHER case of glitches truncating my round, of which I swear there's been at least six or so in the past month alone.

Alright, so. What could cause instantly-passing crit?

**Comment by Jalleo** [comment]
I think this has already been reported before hold on while I find the relevant issue.

**Comment by Miauw62** [comment]
im fairly sure this was fixed already.
you could also try to stop complaining about coders trying to improve the game.

**Comment by AnonymousNow** [comment]
I've only encountered it once, and it was well after the update that fixed 15-second crit, which means it's a seperate issue. If anything, it seems like it could be linked to the damage delay issue I reported recently.

**Comment by Miauw62** [comment]
Huh, odd.

@Carn, @Razharas? Not entirely sure what could've caused this.

**Comment by MrStonedOne** [comment]
This has not been reported to happen again.

could be closed. @phil235 @Jordie0608
