### ISSUE TITLE
Alien hunter in leap mode has been stunned by laser particle

### ISSUE THREAD

**Issue by Snipered** [tgstation/-tg-station#7115]
So, i'm probably stunned/weakened by jumping on laser particle.
"The alien hunter (40) smashes into the laser!"
I don't know, is it a bug?

**Comment by phil235** [comment]
Sounds like a bug to me.

**Comment by WJohn** [comment]
Projectiles being solid like they are is causing a lot of problems, like with NPCs trying to dodge around them and you being able to make an un-moving wall of bullets with a mech on the asteroid that will prevent them from chasing you.
