### ISSUE TITLE
Immovable Rods no longer cut through the station (again)

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7117]
We had this issue before, and I fixed it. But it looks like its back again.

Instead of cutting right through the station like they should, they will often be deleted sometime before they make any significant progress. Quite disappointing.

**Comment by WJohn** [comment]
Just saw this happen right in front of me: http://i.imgur.com/h325XKX.png

It cut through 2 windows and 2 walls. Pretty pathetic.

**Comment by TheVekter** [comment]
For whatever reason, ex_act was causing it to just qdel after about 20 tiles or when it hit an rwall.

#10092 should fix that.
