### ISSUE TITLE
Supply positions in the Jobban menu is difficult to read

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7118]
Due to a rather poor choice in color
![screenshot 2015-01-16 09 45 41](https://cloud.githubusercontent.com/assets/9098006/5780050/b60da4d2-9d64-11e4-80f5-2a0f7d1fabe4.png)

**Comment by Jalleo** [comment]
@paprka

**Comment by paprka** [comment]
sorry, i'll make the brown lighter for it
