### ISSUE TITLE
Flashes do not blind, smoke particles are not transparent.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#7121]
When running the game in a Windows 7 virtual machine. Being flashed doesn't blind (no blind effects at all), and smoke particles are not transparent (smoke sprites are on a solid black background). Not sure if there's anything you can do about that, but it's still a bug.

**Comment by naelstrof** [comment]
Might be useful to mention it works fine on my normal Windows 7 install.

**Comment by Iamgoofball** [comment]
Check your rendering settings

**Comment by tkdrg** [comment]
Yeah, sounds like you don't have direct3D set up properly. Run "dxdiag" and look if you have direct3D hardware acceleration.

**Comment by naelstrof** [comment]
Yeah you're right I don't, and I can't enable it without terrible consequences.

So yeah I guess this isn't a bug, but if there's a way to not need directX 3D like the rest of the game it would be nice.

**Comment by tkdrg** [comment]
It's possible, but I believe it is quite a bit slower and probably not worth it. I'm closing this as a non-issue.
