### ISSUE TITLE
Roburgers contain the ERT nanites

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#7122]
Revision ac3c413f24b57ab40ae8da989828ca679c5b45e2 
When checking the reagents in the roburger, it references the ERT's Adminordrazine nanites rather than the regular robotic transformation nanites.

**Comment by tkdrg** [comment]
@steelpoint

**Comment by Steelpoint** [comment]
Never knew there were other in game references to Nanites.
