### ISSUE TITLE
Can't upgrade grip with the "use" shortcut.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#7130]
Grabbing someone in your hands makes it seem as if you can upgrade the grip with the use button (Z), but you *have* to click on the hand instead.

It's inconsistent with the rest of the hand controls, but this may be intended.

**Comment by WJohn** [comment]
Grip upgrade in general is really unwieldy and requires a lot of click spamming to make it do anything.

**Comment by Tenebrosity** [comment]
I always assumed this was intentional to avoid quickchoking. Also, what WJohn said.

**Comment by paprka** [comment]
quickgrabbing was nerfed in other ways, this should be restored

**Comment by Tenebrosity** [comment]
I'm for it :+1:

**Comment by kingofkosmos** [comment]
This has been fixed.
