### ISSUE TITLE
Paper writing area is tiny.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#7132]
It used to be a big window that you could format stuff in easily, now its the tiny one-line input().

![](https://dl.dropboxusercontent.com/u/17793091/writinggotdumb.png)

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=2446&p=59932#p57305

**Comment by Chocobro** [comment]
it has been like this for over a year, didn't know this wasn't intended.

**Comment by tkdrg** [comment]
Someone added sanitization to it and swapped the `as message|null` with `as text|null`. Just replace `as text` with `as message` to fix.

**Comment by Deantwo** [comment]
I just came back from a year of being away and noticed this too right away.

It still works as normal, the input box is just not multi-line.

My guess would be that it was done to once and for all make sure that no one can use HTML code on paper? But I have no clue.

Most of all this is just annoying.

PS/Off-topic: Why is the only places I can freely get paper as an Assistant; Robotics desk, Medbay desk, and Library? Writing my (résumé)[https://tgstation13.org/wiki/User:Deantwo/Sandbox] has never been more annoying.

**Comment by Deantwo** [comment]
It is still an easy fix, but not a single word that need changing.

Writing on paper has been changed to use the [stripped_input](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/__HELPERS/text.dm#L77) function ([here](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/modules/paperwork/paper.dm#L246)). This function is also used many places where a non-multi-line text input makes sense.
Weirdly enough is it not used to in the [rename part of paper](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/modules/paperwork/paper.dm#L79).

Best suggestion would be to make a multi-line version of [stripped_input](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/__HELPERS/text.dm#L77) (if one does not already exist) and just make writing on paper use that.
