### ISSUE TITLE
Penlight has misleading message when used on borgs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7135]
Small fix, but penlight use on borgs claim they have eyes, which they don't:

Tom Arto directs the penlight to M.I.M.E.'s eyes.
Tom Arto directs the penlight to M.I.M.E.'s eyes.

**Comment by RemieRichards** [comment]
Borgs do have eyes.

**Comment by Miauw62** [comment]
Yeah, borgs have eyes.
