### ISSUE TITLE
Proposed Game Mechanics: Losebreath and Silence

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7138]
This is largely for balance reasons with the upcoming implementation of Goonchem, which has a much much stronger focus on losebreath as opposed do direct O2 damage. It's also for realism.

Suggestion: Makes it so that when you're under the effects of losebreath, you cannot speak. You would still be able to emote and do other things, but attempting to speak would result in "*gasp".

This effect would pass once losebreath values had returned to 0 AND you had taken your first breath after it had returned to 0.

**Comment by WJohn** [comment]
in space no one can hear you scream

part deux

**Comment by PKPenguin321** [comment]
I remember reading the goonwiki and seeing this and thinking "Man I sure am glad we don't have that on /tg/, that buffs spacing people even more"
But I don't really know how this plays into goonchem so I guess it's safe to ignore me

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
