### ISSUE TITLE
The defibrilator is a rather mundane item and having it as a steal objective feels out of place

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7144]
There's nothing special about a defibrilator.

**Comment by Incoming5643** [comment]
remember when the laser pointer was a steal objective?

**Comment by dannno** [comment]
defib is also super fucking easy to steal

**Comment by paprka** [comment]
i was going to remove it with the inclusion of smaller belt slot defibs, but yeah feel free to remove it, someone else suggested it would be a good steal objective.
