### ISSUE TITLE
Shuttle should not Auto-Call if the shuttle is already en route to the station

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7149]
Problem:
-Call the shuttle. ETA 10 minutes as usual.
-Force an auto-shuttle call by destroying the AI and all comms consoles
-Shuttle ETA suddenly gets delayed to 25 minutes

Proposed Solution:
Don't let the autocall trigger if the shuttle is already en route to the station.

**Comment by Jordie0608** [comment]
#8393 was a dupe of this and fixed in #8405
