### ISSUE TITLE
Cryostasis beaker not mixing when spilled

### ISSUE THREAD

**Issue by ReallyBigRock** [tgstation/-tg-station#7152]
The cryostasis beaker does not mix when spilled. For instance, when you fill it with potassium and water and dump it on something, they do not react in an explosion.

**Comment by WJohn** [comment]
I don't think any chems actually remain on the floor waiting for new reagents to react with. There are effects like dirt or blood or slippery floor or thermite but I think that's different. Probably just an inconsistent missing feature.

**Comment by Iamgoofball** [comment]
@Cheridan this isn't a bug, i'm not doing feature requests

this is because when you splash shit onto a tile it does reaction() on the tile and it's contents, and then deletes the reagents from existance

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
