### ISSUE TITLE
No board for the white ship

### ISSUE THREAD

**Issue by ReallyBigRock** [tgstation/-tg-station#7153]
Paragraph 2 of this http://www.ss13.eu/wiki/index.php/White_Ship
says the computers can be repaired on the white ship. However, no boards exist that work. The shuttle one and ferry ones just say "missing" when installed there.

**Comment by Tenebrosity** [comment]
Did you secure the computer with a wrench first? It might not work because of shuttle turfs.

**Comment by ReallyBigRock** [comment]
Ya, I built the computers right; it wouldn't let you put in the board until it was wrenched. I tried it with every shuttle related board to no avail. I think it would be a cool feature though.

**Comment by Steelpoint** [comment]
It would not be too hard to make it that you can move the ship.

**Comment by ike709** [comment]
add constructable and moving ships pls

**Comment by quaggaman555555** [comment]
ReallyBigRock, you were looking at the wrong wiki, this is the current /tg/station wiki for the White Ship: https://tgstation13.org/wiki/White_Ship
