### ISSUE TITLE
"Life" and "Strange Reagent" don't work as intended.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7154]
With the Strange Reagent, the code says its suppose to bring a person back to life if their brute/burn is below 80 and turn them into the zombie mutant race. As of right now it does all of those things expect bring them back to life. They do the body twitching and gasp before immediately dying right afterwards.

With the Life chemical, once the heat reaction goes off, your left with the chemical itself, which is useless as of right now.

**Comment by Iamgoofball** [comment]
@MMMiracles Apply some Styptic and Silver Sulf patches to reduce their brute damage, otherwise they die immediately.

I'll check Life not spawning anything.

**Comment by Miauw62** [comment]
>turning people into the shitty halloween zombie mutantrace

is that a thing now? because its hilarious/

**Comment by Pennwick** [comment]
Strange Reagent needs to be applyed with a patch or having the chem splashed on the person. It uses var/method=TOUCH. Also it doesn't seem to have a minimum required dosage. I've been able to split 1 unit into 10 patches and each works fine.

**Comment by tkdrg** [comment]
In fact, using less SR is better, because it is toxic to living people.

**Comment by delaron** [comment]
So life works just fine you need to heat it up to 374 per the code.
