### ISSUE TITLE
Razharas broke cryo cell ejection, here's why

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7157]
https://github.com/tgstation/-tg-station/commit/1685dd3b7a392d2ad68b69bc5e547a3b075eaf4a

This commit removed the release sequence and was undocumented. Control F for 'release sequence'. Completely undocumented feature removal and a nerf to cryo tubes. Makes them a giant pain in the ass for the occupants and medical staff.

Please fix. The current system is bad. Yes you can still resist out, but the release sequence made cryo not complete arse.

@Razharas Fix this shit.

**Comment by Alek2ander** [comment]
#2844
