### ISSUE TITLE
Chem dispencers not in circut imprinter.

### ISSUE THREAD

**Issue by Kaptinalexander** [tgstation/-tg-station#7163]
Server: Sybil

Revision: Server revision compiled on: 2015-01-17
c7e25dfdaa51141f376bd84d4a00eadda3b1ab5e 

Problem Description: Portable Chem dispensers are no longer in the circuit imprinter when appropriate research levels are obtained.

What did you expect to happen: They were in when goon chem was first added, but disappeared when the chem heaters were added to the medical circuit list, leads me to think something got overwritten or something.

Steps to reproduce the problem: 
Like the title says, with the normal R&D of:
Materials five
Plasma three
bio tech three
EMP four
data five

There's no Portable chem dispenser in the circuit imprinter.

**Comment by phil235** [comment]
I think this was fixed by #7137

**Comment by tkdrg** [comment]
Yep.
