### ISSUE TITLE
Inside of shuttle corners shows space

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7167]
http://i.imgur.com/W4NlQRA.png
@Carn 

Possibly related to #6972?

**Comment by Anonus** [comment]
The corners were briefly changed to full-tile walls, but someone reverted that.

**Comment by Carn** [comment]
The commit mentions not to use them for interior corners.
I'm tried of redoing all this stuff people keep reverting without speaking to me. Their problem.

**Comment by WJohn** [comment]
Hm, then I think the shuttles didn't get updated for that. I'll see about fixing it in my PR.

**Comment by Steelpoint** [comment]
You need to write up a guide or some kind of thing for people to read, right now everyone is literally running blind.

**Comment by Carn** [comment]
They were updated.
I literally just said I updated them.
Somebody reverted it

**Comment by Carn** [comment]
I think most of this is happening because people aren't remembering to prepare_map.
If you install the new prepare_map hook, it'll backup every dmm when you switch/checkout
