### ISSUE TITLE
Items render differently depending on position

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7169]
![slipcity](https://cloud.githubusercontent.com/assets/9276171/5792964/ed85541e-9efe-11e4-89c0-e36af3921ff2.png)

I placed the peel down and put the medkit over it. Depending on where you stand the peel is either ontop or under the medkit. Immursions shattered.

**Comment by WJohn** [comment]
I think we all collectively ignored this thing, but it has been around foreeeeever.

**Comment by Miauw62** [comment]
can confirm, this bug is fucking ancient.

**Comment by Miauw62** [comment]
@MrPerson do you know what caused this since you had a layer refactor PR?

**Comment by paprka** [comment]
I'm pretty sure it happens when things are on the same layer

See: pens and paper bins

**Comment by Deantwo** [comment]
It's been around at least ever since I first played AtmosTech.
The MultiTool and WeldingHelmets on the table does this always.

Just think of it as, you can't see it from *that* side.

**Comment by MrStonedOne** [comment]
@Jordie0608 byond bug tag please.

**Comment by duncathan** [comment]
I really don't see this as an issue at all tbh. You just can't see it from that side; it's perfectly immersive. 

Let me know if you have an objection
