### ISSUE TITLE
Humans rest the wrong way up when buckled to rollerbeds

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7170]
they put their feet at the pillow end.
http://i.imgur.com/44sjNxO.png

**Comment by dannno** [comment]
blankets being the way they are, it's actually the rollerbeds that are the wrong way around. someone just needs to flip the sprite.

**Comment by paprka** [comment]
You can't use a blanket on a rollerbed anyway, your mob will be higher than the blanket

**Comment by WJohn** [comment]
Yeah humans were always meant to rotate to the right when knocked down or buckled, these were added long before mrperson's change to make being prone animated. Somehow they've been facing the wrong way for years, but yes the fix is extremely easy.
