### ISSUE TITLE
Broken Table on Nuke Op Base

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7182]
![screenshot 2015-01-18 19 45 43](https://cloud.githubusercontent.com/assets/9098006/5795329/d452b3fa-9f4a-11e4-9f41-6332bf0f33cc.png)
What's the point of even having an ID locked door if it's just open like that with items on the floor? Looks like a bug.

**Comment by paprka** [comment]
mass replacements are bad

**Comment by TZK13** [comment]
I literally just had a round as a nukeop where the table was like that but when I went back to the base after getting on the shuttle before we left to donate the TCs from one uplink to another the table was suddenly there.

**Comment by TZK13** [comment]
That's me in the picture with the paper hat to hide my IC identity (Nukeops given helmets on spawn again when). I dunno if it was Ikky fixing it but after I had boarded the shuttle and came back on to donate the TCs from another uplink to mine I noticed the table was suddenly there.

**Comment by paprka** [comment]
(nuke ops shouldn't be faceless to their teammates, it's more cool when they're a collection of suave squadmates in stylish turtlenecks)

**Comment by Ikarrus** [comment]
Yeah I noticed that and fixed it when I spawned in as the beep ping borg.

**Comment by paprka** [comment]
Ikarrus return to mapping we have separate z-levels now it's amazing pls

**Comment by Steelpoint** [comment]
I've fixed this in my ERT PR

**Comment by WJohn** [comment]
This is confirmed fixed.
