### ISSUE TITLE
Nuke Op radio interception is on the deathsquad channel

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7184]
Everything that gets intercepted shows up as [Deathsquad] instead of, you know, intercepted syndicate signals.

**Comment by GunHog** [comment]
Was there an NTSL script active?

**Comment by Ikarrus** [comment]
Dunno, I was deadmin at the time

**Comment by GunHog** [comment]
I only ask because that is the primary channel for intercepts when my script is in use. If you encounter this again (or already have logs), I can help you determine if that was the cause.

**Comment by TZK13** [comment]
I was a nukeop in this round and I'm fairly certain it was your NTSL script.

**Comment by GunHog** [comment]
Yes, that is with the script's intercept in Non-department mode, due to the AI having its own radio. There is a toggle for that, though.
