### ISSUE TITLE
PDAs sending blank messages

### ISSUE THREAD

**Issue by Plat251** [tgstation/-tg-station#7187]
When using PDA messenger, if you click on someone's name and the input window opens, if you type nothing and press OK or press cancel, the recipient will receive a blank message (even if pressed "cancel").

**Comment by Deantwo** [comment]
That explain one of the messages I got as reply in one of my recent games.

**Comment by Deantwo** [comment]
The [msg_input](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/game/objects/items/devices/PDA/PDA.dm#L757) process returns null if nothing is entered in the text box. Sadly there is no check if null is returned [from the process](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/game/objects/items/devices/PDA/PDA.dm#L772)

All that need to be added is; ```
	if (!t)
		return
``` on [line 773](https://github.com/tgstation/-tg-station/blob/8ddff140d5aa0499d44569553b99d11b94e2f81b/code/game/objects/items/devices/PDA/PDA.dm#L773).
