### ISSUE TITLE
ERT mechs show up on exosuit monitor

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#7192]
The exosuit monitor in the RD's office shows two of the mechs located on centcomm transport. The ripely and Odysseus.

**Comment by Steelpoint** [comment]
Amusing, I'll look at it.

**Comment by TZK13** [comment]
I remember this happening with mechs that spawned in mining asteroid rooms as well a while back but I can't find the issue report for it if there even was one, I don't remember whether it was fixed or not either.

**Comment by Firecage** [comment]
Can't you just make it ignore that Z-level? Considering players would never go to centcom, so it wouldn't matter.

**Comment by Miauw62** [comment]
@Steelpoint was this fixed?

**Comment by Steelpoint** [comment]
I think this is a inherent problem with how mechs function, the only solution I can immediently think of is to get rid of the mechs.

**Comment by palpatine213** [comment]
The main problem with this seems to be that the Ripley and Odysseus spawn with beacons attached to them. A possible way to fix it would be to make the ERT mechs a child of the mechs, and remove their attached beacons, similarly to how the Death Ripley has the beacon removed. Not sure if making a whole new Ripley and Odysseus variant to solve this would be the way to go, but it's an option. The other solution, would be to remove the beacon spawning on the default Ripleys.

**Comment by TZK13** [comment]
https://code.google.com/p/tgstation13/source/detail?r=3824

>Mining mechs, which currently only spawn in secret asteroid rooms, no longer
have tracking beacons

**Comment by palpatine213** [comment]
Fixed by #7509
