### ISSUE TITLE
Braindead human on fire not taking any damage from it

### ISSUE THREAD

**Issue by TZK13** [tgstation/-tg-station#7193]
![harmless fire](https://cloud.githubusercontent.com/assets/5348175/5799301/4621fda6-9f96-11e4-8ed5-1ecac899586e.png)
The braindead BR pictured (Not being racist they were literally braindead IC :^)) was caught in an explosion from a syndie bomb which set him on fire but being on fire did absolutely nothing to him from what I observed over the course of a few minutes.

**Comment by Miauw62** [comment]
@Carn @Razharas ???

**Comment by phil235** [comment]
Fire is handled by increasing the mob's temperature, it doesn't inflict burn damage per se I think. Thus, that atmos tech being close to a breach, he was in a sweet spot fire increasing his temp and cold space decreasing it, that's why he was able to stay alive.

**Comment by phil235** [comment]
Can't reproduce. Also my theory was wrong, apparently when you're on fire your bodytemperature isn't affected by the outside temperature so my guess is that he had chemicals in his system reducing his temperature and/or burn damage.
