### ISSUE TITLE
Ghost and wizard teleport lists are in reverse-alphabetical order

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#7194]
Not sure if intended.

But if it is, it fixed #4603.

**Comment by Carn** [comment]
image please

**Comment by Alek2ander** [comment]
![2015-01-19 21-38-09 booyea](https://cloud.githubusercontent.com/assets/5909770/5805816/8c652896-a023-11e4-9b4b-4e13acdbcc83.png)

**Comment by Alek2ander** [comment]
I actually like it more this way. But it was probably not intended and something else could end up broken for a similar reason.

**Comment by Razharas** [comment]
Was fixed at some point
