### ISSUE TITLE
Syndiborgs running out of ammo way to quickly

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#7200]
Syndicate Cyborgs use a LMG as their weapon. While cool it suffers from running out of ammo very quickly and having no visual indication of how much ammo is left.

I get that it regenerates ammo but that's not good enough.

The weapon should function like the old Laser gun and draw from the borgs power after everyshot. Increase its power cost if you have to.

@Paprka since he changed the system around.

**Comment by Dorsisdwarf** [comment]
Requesting closure, paprika removed syndieborgs' LMGs @Cheridan
