### ISSUE TITLE
Hotspots can burn and burn but the tile reverts to a cool temperature? (Away missions)

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7214]
http://i.imgur.com/I5kXuXJ.png

THIS WAS DONE ON AN AWAY MISSION (UO45)

This fire has been burning for half an hour, there is no tile on the map that by default is beneath 293*K. It got a pretty tiny max temp for something that has been burning that hot for so long (you'd expect it to be in the tens of thousands easily).

POINT OF NOTE: All tiles on UO45 have been made to resist temps up to 1 million degrees so it will never melt through (to try and keep the illusion that this is actually on a planet, but bypassing that with an RCD or explosions is another set of issues in itself.)

**Comment by duncathan** [comment]
Does this even happen

**Comment by duncathan** [comment]
```
(12:07:55 AM) KorPhaeron: that sounds like someone
(12:07:58 AM) KorPhaeron: killed air 
```
he's right
