### ISSUE TITLE
You can staff of change animated objects.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#7218]
If you staff of change an object that was animated with a staff if animation, the mimic mob gets transformed and the stored object is dropped from it.

**Comment by Incoming5643** [comment]
I never considered this much of an issue, many mobs created this way are passive or lacking AI all together and the few aggressive ones have no allegiance to the wizard at that point and will often chomp his ass if given half a chance.

**Comment by GunHog** [comment]
FEATURE!

**Comment by AlexanderUlanH** [comment]
It's a natural consequence of how both staves work.  I could see some special snowflake to make it turn mimics into other mimics, but it's not really a big deal.

**Comment by Boggart** [comment]
You can use it to spam lots of simple mobs but I'm not sure that's a huge issue.

**Comment by Miauw62** [comment]
not really an issue
