### ISSUE TITLE
Chems not processing correctly

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#7223]
![image](https://cloud.githubusercontent.com/assets/6778786/5820820/9d0690be-a095-11e4-87dd-f600e2aa7229.png)

I had fucking 80 at one point in my system no brute damage at all. 

Oh and swallowed a 50u of neurotoxin got knocked down once and only had brain damage and some toxin damage

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
@phil235 
the first one is because the brute damage starts from the addiction cycle

the second one is bad rng rolls

**Comment by phil235** [comment]
The issue for krokodile is how Kromgar didn't get addicted if he had 20+ units in his system?

**Comment by phil235** [comment]
can't reproduce krokodil, the addiction is just slow to come, it might be faster now that metabolization happens every life().

**Comment by Iamgoofball** [comment]
Phil, you didn't make addictions proc every tick did you? If so, that's gonna go badly.

**Comment by phil235** [comment]
No, I was wrong, addiction speed is still the same.
