### ISSUE TITLE
EXPERIMENTOR creates a super capacitor, which gets instantly deleted

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7224]
for posterity, it was a matter bin that turned into a super capacitor.

**Comment by WJohn** [comment]
@sawu-tg

**Comment by sawu-tg** [comment]
Chocobro hasn't provided any screenshots/messages for the error, So i'm going to chalk it down to being not an error, just a coincidental colliding of results. The RNG gods did not smile on him.

**Comment by drynwyn** [comment]
I've had the same thing happen with a micro-manipulator transforming into a nano-manipulator and not actually appearing. No message indicated that the nano-manipulator was destroyed.
