### ISSUE TITLE
Syntiflesh (the meat, not the healing drug) recipe broken by clonex removal

### ISSUE THREAD

**Issue by babinsquared** [tgstation/-tg-station#7226]
Syntiflesh, the cooking recipe which uses blood and clonexadone as reagents, can no longer be created by players as clonexadone was recently removed. Syntiflesh still exists, it's just not craftable.

Perhaps change the recipe to require cryox or something else instead.

I made an account just for this because I love my artificial meat.

**Comment by Lumipharon** [comment]
with new hunger, synthimeat is the only good source for the shitloads of meat you need to feed 50+ people.

**Comment by tkdrg** [comment]
It's supposed to work, but requires cryox instead. Is that not working?
@Iamgoofball
