### ISSUE TITLE
CF3 creates hotspots on walls

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#7228]
Walls don't process atmos so the fire never goes out

**Comment by drynwyn** [comment]
@Iamgoofball 
The fact that the hotspots never ever go out should probably go in the issue header- CF3 is meant to create hotspots on walls, but they are supposed to stop burning at some point.

**Comment by Alek2ander** [comment]
Why would they though. Walls not processing atmos is part of the game mechanics, it's other stuff applying atmos effects to turfs without doing any checks that is bad.

**Comment by drynwyn** [comment]
Because chlorine triflouride is an incredibly dangerous substance that really can cause metal walls to burn.

**Comment by Iamgoofball** [comment]
clf3 is no more

this can be closed

**Comment by Razharas** [comment]
clf3 is back so its time to fucking fix it already

**Comment by Razharas** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Fucking hotspot cod3

**Comment by Iamgoofball** [comment]
so basically the thing that was making hotspots on walls was the initial mixing of CLF3

this is now fixed in the latest goonchem pr, will add a fixes tag
