### ISSUE TITLE
Pentetic Acid formula doesn't work.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#7229]
Ammonia + Welding fuel produces itching powder
Chlorine + Sodium produces salt

required_reagents = list("fuel" = 1, "chlorine" = 1, "ammonia" = 1, "formaldehyde" = 1, "sodium" = 1, "cyanide" = 1)

**Comment by PKPenguin321** [comment]
Would this work with a cryostasis beaker?

**Comment by Iamgoofball** [comment]
uh oh

will look into

**Comment by phil235** [comment]
We could simply change the recipe to use "salt" and "itching powder" directly.

**Comment by Fox-McCloud** [comment]
Change salt's recipe to sodium+chlorine+water, and this will help out even more, for the future.

Might as well change space cleaner to water+ammonia+ethanol, while you're at it, as well...'cause that will also cause issues in the future.

**Comment by hornygranny** [comment]
this was fixed already
