### ISSUE TITLE
More than 5 spells attainable in raging mages

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#7245]
If a wizard comes by another spellbook he can use it to learn more than the 5 (or 7 counting summon guns/magic rebate) spells he normally can. Happens with both wizard's and one-use spellbooks.

An easy fix for this is severely hampered by how painful the spellbook and spell-assignment code is.

**Comment by RemieRichards** [comment]
is this truely an issue though? I think the 5 spell limit is only intended for the 1 Wizard (+Apprentice) actual Wizard game mode. Ragin Mages is a chaotic mess.

**Comment by tkdrg** [comment]
This is only an issue if the wizard learns over 5 of the same spell.

**Comment by Miauw62** [comment]
you can't learn over five of the same spell.
i don't think this is an issue, restricting people to 5 spells would be very arbitrary. (and restrict admin events)

**Comment by tkdrg** [comment]
closing as a non-issue, then
