### ISSUE TITLE
Beakers hold chem heat perfectly

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#7250]
Beakers "hold" chem heat perfectly. Tested by filling a beaker with water, heating it to 500k, emptying beaker, then mixing sorium in beaker. Sorium mix reacted immediately.

Furthermore, you can pick up 3000k beakers with your bare hands.

**Comment by Delimusca** [comment]
i took a look at this, turns out chem temp is stored in the beaker's reagent holder, and the only time it gets modified is in the chem heater i think. a handle_convection thing for containers would be nice, and i think goon has temperature stored in the reagents themselves; that way you can do proper volumetric temperature averaging algorithms and stuff.

**Comment by Deantwo** [comment]
A heated beaker would be an interesting tool. Self-attack to adjust temperature.

But yeah, the temperature of the beaker seem to be very odd.

**Comment by TZK13** [comment]
Iamgoofball said this was intentional when I spoke to them about it before.

**Comment by drynwyn** [comment]
This also carries another issue with it: Chem grenades will never produce chemicals that require heat, because the chemicals involved get transferred to the grenade to react, and the grenade can't be heated.

**Comment by dannno** [comment]
Why would this be intentional

**Comment by Iamgoofball** [comment]
do you want me processing reagent temperature on each individual reagent every single tick for upwards of >1000 starting reagents on the station?

because i think it would cause a shitton of overhead, but i can try it if you want.

**Comment by Delimusca** [comment]
reagents themselves could have static temperature, while reagent containers handle the heat changes. i know food stuff like twinkies are also containers, would an override that returns null or something on reagent_containers/food and stuff help with the overhead?

**Comment by Iamgoofball** [comment]
it would but then people would use twinkies as mix holders so their shit doesn't cool down automatically

**Comment by Deantwo** [comment]
I think it would make more sense just to only have the heat while the beaker is in the ChemHeater.
Reagents do react inside the ChemHeat, so resetting the tempature of the beaker when you pull it out would work.

Thoughts?

**Comment by Delimusca** [comment]
@Deantwo at that point why even have temperature? bathtub brewing, pyrosium tricks, a big part of the brilliance of goonchem is reliant on temperature outside that one chemistry machine.

@Iamgoofball as funny as insulated twinkiebeaker meta would be, i don't see any reason someone would do it. you'd have to grind it to get the reagents out, and i don't see how heat decay would be a problem worth that hassle. heck, unless the chef is putting out factory volume food output, food items having heat decay probably maybe wouldn't cause much trouble.

**Comment by Deantwo** [comment]
Sorry I only know like two formulas that require a temperature.
But then maybe we need a special beaker that can self heat (I did suggest this before).

Also a way to make chem_grenades heat their content on detonation maybe.

**Comment by Iamgoofball** [comment]
i seriously can't "fix" this without creating insane overhead from processing over 2000 reagents a tick and doing temperature math on each one

**Comment by Delimusca** [comment]
i did some testing on goon, there doesn't seem to be heat decay at all, but temps do equalize when two reagents meet, so they must have temps on the reagents themselves. that should be pretty doable.

**Comment by Deantwo** [comment]
I am thinking about trying out my idea here in a few, so leave this to me until then?

**Comment by scrdest** [comment]
To fix the overhead - keep it container-based, freeze the temperature value (no pun intended) at a default room temp constant unless an external heat source acts upon it above a threshold.

Even simpler, faster algorithm - drop temperature to, say, 1/Nth the original value every T seconds and set it to default at N*T. So for N = 4 and T = 1 it would be at, say, 1200K for the first 4 seconds, 900K until 8 s, 600K the next four, and finally stabilize at the default of 300K (27*C) after 12 seconds.

Solution for magic containers - give containers a new var - if temperature is above the var, the container melts into ashes like it does polyacided. Set the var for legit containers to be way above the default so that non-legit containers melt at relatively low temps.

**Comment by Pennwick** [comment]
The temps could still be container based but change when mixed. You'd just need to take the volume * temp of the poured beaker plus the volume * temp of the transferred reagents from the other container and divide it by the new value and set the filled beakers temp again. 

For example if you have 20u of sugar at 10 degrees and pour in 30u of water at 100 degrees it would work out to ((20*10)+(30*100))/(20+30)=64 degrees for the new temp.

This wouldn't solve the issue with beakers staying hot forever but you could mix hot things with cold things to get warm things and you couldn't just use the same beaker over and over to cook drugs.

**Comment by Deantwo** [comment]
But none of this really changes the fact that you can just heat your beaker to an insane temperature and even with slow heat decay it would last for a long time.
My suggestion is still that the heat should only be present while inside the ChemHeater. Once you eject the beaker it pops out of the ChemHeater and has a change to react to the heat while not in the machine for a nano-second before the temperature is reset to default.
Of course if there are any chemicals that need to be heated to function, they will need to be changed.

I am messing around with it in local right now and it works just fine. It means that making *Fluorosulfuric Acid* actually takes 23 seconds (150 to 380 at a rate of 10), plus it makes upgrading the ChemHeater useful!

**Comment by Delimusca** [comment]
@Deantwo that system would still cause issues with doing chemistry outside the chemlab. doing things like making calomel protein shakes out of discount dan's salty slurries as an assistant is my favourite part of goonchem. admittedly right now there's not many ways to get chemicals outside chemistry, but that isn't hard to change.

**Comment by Deantwo** [comment]
Make other ways to heat chemicals?
ChemHeater is buildable i think...
But a ghetto way would be useful yeah.

**Comment by Pennwick** [comment]
Assistant hobos heating their cups of ramen over a burning barrel filled with plasma slag. Warming their cold hands near the flames.

Really though I don't see a problem with beakers retaining heat. With my solution you still can't just heat a beaker to 1000 and use it for reactions later. The volume in the beaker would be 0. So the total heat energy held by the beaker would be 0. It would take on the heat of whatever temp beaker the new ingredients were poured from. 

The only way you could take advantange of it is by heating up 50u of something twice as hot as you might need in the future then adding in 50u of unheated chems to get your reaction. Say heating water to 1000 degrees then adding 25u clorine and mercury to get Calomel. This would cool down your heat holding water by half so you'd need to heat it again if you wanted to repeat the trick.

Capping the chem heaters at a lower temprature would even make this hard to do. If they could only heat chems to 500 degrees that would be enough for any recipe but you couldn't store heat to use in a reaction later very well.

**Comment by Fox-McCloud** [comment]
On Goon, yes, the temperatures are static, likely to prevent exactly what Goofball said.

That said, I'm still not sure if reagents, themselves, hold tmeperature, or if it just normalizes the temperature of reagents when two separate reagents from two separate containers come into contact with one another. 

That said, only allowing heat/cold based reactions to occur in the chemistry heater is boring as hell; if Goof really does round out Goon chem, then making reactions heater only will be incredibly boring.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
