### ISSUE TITLE
Disposal pipe dispenser and RPD bugged

### ISSUE THREAD

**Issue by leibniztg** [tgstation/-tg-station#7253]
The dispenser and the RPD dispense the wrong disposal pipes
pipe->bent pipe
bent pipe->junction
junction->junction in the wrong direction
etc etc

**Comment by Menshin** [comment]
Reviewing/merging #7177, would prevent duplicates like this one (#7181 and #7211).

**Comment by leibniztg** [comment]
Sorry, I'll close it.
