### ISSUE TITLE
Colorful reagent recolors ghosts if they get sprayed by it.

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#7258]
Spooky Scary

**Comment by Incoming5643** [comment]
tags: will not fix

**Comment by CollenN** [comment]
Can we just remove the colorful reagent? It makes things look so ugly and hard to see.

**Comment by paprka** [comment]
^

**Comment by dannno** [comment]
^

**Comment by GrayRachnid** [comment]
Noooo, colorful reagent is the best invention ever!

It's just a bit edgy how it recolors ghosts.

**Comment by Incoming5643** [comment]
Mob recoloring is pretty cruddy anyways, it only looks good on some mutant races (because they were designed with custom color vars in mind, and it permanently marks people in a way that makes them very hard to miss and impossible to hide

**Comment by Alek2ander** [comment]
Make water wash it off. Problem solved.

**Comment by Dorsisdwarf** [comment]
Make showers wash it off, so people will visit the showers.

**Comment by Iamgoofball** [comment]
i put up a pr to make water wash it off

i can fix this too though

**Comment by RandomMarine** [comment]
Make ghosts have to shower it off too. Even if they have to wait for someone to turn it on.
