### ISSUE TITLE
Lizards have taken over the pAI interface.

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#7260]
What you expected:
The last line to read "This process could take anywhere from 15 seconds to several minutes, depending on the available personalities' timelines."

What happened
The last line read "This process could take anywhere from 15 seconds to several minutes, depending on the available personalities' timeliness."

timelinesss.

**Comment by RemieRichards** [comment]
Timeliness is a word. it's not supposed to say timelines.
