### ISSUE TITLE
Most players can't see the fancy new fonts

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#7263]
While you can probably expect people to have Comic Sans installed in their systems, some of the other special fonts are likely to be missing.

**Comment by RemieRichards** [comment]
blame goof for choosing OCR A Extended, pretty sure it's a windows only font.

**Comment by Alek2ander** [comment]
I didn't have OCR A Extended or Vineta, for example. Some complain they don't have Jokerman.

**Comment by ike709** [comment]
heil windows

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Weird as shit, I guess those aren't default windows fonts.

I'll def. Look into this shit, googling told me they were default windows fonts but I guess I was wrong

**Comment by Alek2ander** [comment]
They might be installed with MS Office for example, but not exist in Windows by default.

**Comment by Iamgoofball** [comment]
this has been fixed for ages @phil235
