### ISSUE TITLE
Syndieborgs are locked to robotics access, meaning you can be screwed with by robotics.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7264]
I got de-celled at lightning speed by a non-syndie. Why don't syndieborgs have syndie access locks?

**Comment by WJohn** [comment]
At the end of the round someone said that syndieborgs are roboticist ID, which makes no sense and it really needs to be changed to agent ID (150).

**Comment by Deantwo** [comment]
Simple fix.

[This](https://github.com/tgstation/-tg-station/blob/ab98b7e94d47813b15ca757f5564dcd2ba691775/code/modules/mob/living/silicon/robot/robot.dm#L41 "var/list/req_access = list(access_robotics)") needs to be overridden.
Done by adding ```req_access = list(access_syndicate)``` at [line 1080](https://github.com/tgstation/-tg-station/blob/ab98b7e94d47813b15ca757f5564dcd2ba691775/code/modules/mob/living/silicon/robot/robot.dm#L1080). I think.

**Comment by RemieRichards** [comment]
Yeah @Deantwo I know, already looking into it, but thanks.

**Comment by Deantwo** [comment]
Sorry, I like to do the research and write some information for others. ^^;
And I know that if no one else reply, I can try fixing it. ^^

**Comment by RemieRichards** [comment]
Yeah, thanks anyways.

**Comment by Dorsisdwarf** [comment]
Also I'd like to point out you still somehow shot me twice in the chest with an LMG /after/ I took out your cell.

**Comment by WJohn** [comment]
Yeah how did you not die from that how much of a nerf did LMGs get?
