### ISSUE TITLE
Issues with invisibility power

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7269]
- you don't turn visible when someone drags you
- you don't turn visible if someone swaps spots with you
- you don't turn visible if pushed down or disarmed
- you don't turn visible when bumped around on non-help intent

can we start testing things before merging them

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by dannno** [comment]
You also remain invisible for like, a good second and a half before you become visible when you start moving. It's enough to move across a full screen.

**Comment by dannno** [comment]
You ALSO don't become visible when dragging someone ELSE around (which isn't that bad tbh) but ALSO when you shake people up off the ground. probably anything on help intent.

**Comment by MMMiracles** [comment]
I don't know what you're talking about because I turned visible when all of these things happened to me. The delay could still be cut down though as its pretty easy to haul ass away from an area and get out of range of people before becoming visible again.

**Comment by dannno** [comment]
None of these things made me visible for the entire round, besides pushing me down. That ended up working in the end.

**Comment by drynwyn** [comment]
I'm pretty sure the visibility delay is due to the timing of update_icons()

**Comment by Razharas** [comment]
No delay is because its updated on life, which is once per tick

**Comment by Iamgoofball** [comment]
i don't think we can feasibly update it any faster then updating on life()
