### ISSUE TITLE
Ion rifle in the armory start with no pins.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7270]
This was found on EFFICIENCY 3, I haven't checked to see if firing pins are something you can mess with through vars yet though so it might be something that can be solved through mapping.

**Comment by tkdrg** [comment]
@Cheridan

**Comment by WJohn** [comment]
Apparently this can in fact be fixed through mapping! The "pin" var lets you do this. Thanks cheridan <3

**Comment by optimumtact** [comment]
So it's fixed?

**Comment by Cheridan** [comment]
yeah
