### ISSUE TITLE
Experimenter Research Upgrade Malf Does Nothing Useful

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#7272]
Server: Basil

Revision: #7167

Problem Description: The Experimenter's chance to upgrade the item's research seems to not work at all.

What did you expect to happen: The thing gives higher research when scanned in the experimenter or Destructive Analyzer.

What happened instead: It gave no higher research, and didn't even show a number when put in the destructive analyzer.

Steps to reproduce the problem: Constantly test mess with something in the experimenter untill you get the Research Upgrade malfunction. Try to deconstruct it in the Destructive Analyzer.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): If notable, I found this out with a Durand Weapons Control Board.

**Comment by sawu-tg** [comment]
Is basil updated? this should of been fixed with #7199

**Comment by dannno** [comment]
Basil was updated earlier today, maybe 5ish or more hours ago?

**Comment by sawu-tg** [comment]
It appears that the update didn't include the runtime fix, even though it was merged. Blame @Cheridan.
