### ISSUE TITLE
Cargo jumpsuits broken

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7274]
Yeah not sure whath happened yo
![borked](https://cloud.githubusercontent.com/assets/10235107/5848744/fbeb4eca-a1a9-11e4-8daa-02adfebe65c3.png)

**Comment by dannno** [comment]
already reported

**Comment by PKPenguin321** [comment]
Duplicate of https://github.com/tgstation/-tg-station/issues/7205
