### ISSUE TITLE
Can't var-edit an associative list item's value.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#7275]
Trying to var-edit an associative list item only lets you rename it. If you rename it you're never asked what to set it's value to, it gets set to null.

The only way to change the item's value is to delete and re-create it.
(This came up while trying to fix a bugged smart virus dispenser that wouldn't eject a bottle.)

**Comment by Miauw62** [comment]
wtf raz this isnt a consistency issue
