### ISSUE TITLE
Misleading feedback on internals status

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7276]
Trying to toggle on your internals with the button while your breath mask is down will do the regular message and change the icon to be on, only to turn off a few seconds later without even telling you.

http://i.imgur.com/QmWbNBG.png

It should either not allow it (and tell you that your breath mask needs to be lifted up) or do that for you and automatically strap it back on.

**Comment by dannno** [comment]
This happens with all masks, I'm fairly certain. No idea what to do about it. If a mask doesn't have the ability to be internals, this just happens.

**Comment by drynwyn** [comment]
Danno is correct.
