### ISSUE TITLE
Nuke Ops Win Conditions Still bugged

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7280]
And no, it wasn't fixed.
![ops](https://cloud.githubusercontent.com/assets/10235107/5851571/74f9f582-a1d7-11e4-8e65-c851359d46a1.png)
![ops 2](https://cloud.githubusercontent.com/assets/10235107/5851572/7764f718-a1d7-11e4-969d-1a4960c2a8c6.png)

**Comment by Menshin** [comment]
Yup it was :  #7209 ... just unmerged.
