### ISSUE TITLE
italicized fonts are ugly

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#7283]
@Iamgoofball could you please distinguish things like binary chat in a different way, the robotic font looks bad italicized

**Comment by dannno** [comment]
Remove italics from robotics chat, it's that easy.
Or remove italics from all mobs that are currently using different fonts.

**Comment by Miauw62** [comment]
i'm starting to see gia's point with using span classes.
i love how i said to gia "nah they're not needed nobody is going to add more shit to that anyway"
AND THEN GOOFBALL CAME ALONG ;_;

**Comment by Cheridan** [comment]
fixed by #numbmermbermbwhatever
