### ISSUE TITLE
Cloner pods pump people full of an overdoseable chem

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#7285]
Fresh clones pop out with 30 to 60 units of epinephrine which causes losebreath, stamina loss and toxin damage in large amounts.

**Comment by AnonymousNow** [comment]
I wondered why I was getting a message saying I was full of epinephrine. Why is it in the cloning pod again?

**Comment by Anonus** [comment]
It was previously inaprovaline so that clones wouldn't die to being in crit, but goof find-replaced it with epinephrine like a donk

**Comment by PKPenguin321** [comment]
Why don't we just have inaprov and epine at the same time and make inaprov harder to make or something it would fix so much

**Comment by Iamgoofball** [comment]
i thought I fixed this

shit

**Comment by tkdrg** [comment]
Replace it with perfluorodecalin
