### ISSUE TITLE
Universal Suppressor doesn't attach

### ISSUE THREAD

**Issue by ZergRush000** [tgstation/-tg-station#7286]
On a private server (tg code) yesterday I tried attaching a universal suppressor to a syndicate pistol to no avail. Needs to be confirmed on here, I might've done something. Used a zip that I downloaded at around 2 PM CST from here. Round was traitor and both were spawned from an uplink.

**Comment by AnonymousNow** [comment]
I can second this as a player - I got both in a Syndicate bundle earlier, and despite smacking them together, nothing happened.

**Comment by Boredone** [comment]
A copy of #6982, though that's at least a week old and hasn't been fixed yet sadly.

**Comment by paprka** [comment]
It's literally explained how to fix in the other PR, idk why it hasn't been fixed yet but I can't do it right now

**Comment by tkdrg** [comment]
Dupe
