### ISSUE TITLE
genetics is still ultra fucked

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7289]
https://github.com/tgstation/-tg-station/issues/6861 was not fixed, at least not completely
tested last night, well after SoS updated and the problem should have been fixed

>26 blocks
>even with 95% accuracy you still only really have a less than 25% chance of actually mutating the block you hit and not some other random one
>INJECTING SE's INTO YOU NEVER WORKS AND GIVES YOU A COMPLETELY RANDOM MUTATION
>EVERY
>TIME

hhhhhhhhhhhhnnnnnnnnnnnnnnnnnnn

Unless I'm having a fever dream and somehow this was intended, this issue is still enormous

**Comment by tkdrg** [comment]
@Iamgoofball 
Also @Razharas maybe I guess

**Comment by Iamgoofball** [comment]
well

this is a step up from the SE randomizing every single life() tick

**Comment by dannno** [comment]
it's almost the same, but this time you don't get the privilege of a random disability NOT appearing every time.

**Comment by Razharas** [comment]
Ill test

**Comment by dannno** [comment]
>balance, feature request, not a bug

I'm fairly certain this is a bug...??

**Comment by Alek2ander** [comment]
Adminspawned injectors worked properly when I tested my fix. So seems like this is a problem with the genetics console.

**Comment by drynwyn** [comment]
I have been able to reliably achieve powers with the current code.

**Comment by dannno** [comment]
I think for the most part this might have been resolved somehow. It's weird because I was still getting CRAZY SHIT happening but now for the most part I'm not, with the exception of powers NEVER EVER manifesting via SE injection

**Comment by dannno** [comment]
scratch that. this mutations shit is ab fucking surd. crazy broke.

**Comment by KorPhaeron** [comment]
@tkdrg 

Fixed ages ago

**Comment by tkdrg** [comment]
yea and waay to vague either way
