### ISSUE TITLE
please balance table push (aka chain table)

### ISSUE THREAD

**Issue by syndicute** [tgstation/-tg-station#7291]
https://github.com/tgstation/-tg-station/blob/master/code/game/objects/structures/tables_racks.dm
you normally don't keep five seconds weakened when someone puts you on the table at real life

**Comment by paprka** [comment]
i would prefer grabbing people and hitting a table with the grab slammed them into the table, and click + dragging them onto it put them onto the table, without a stun. It's useful to put people on tables if you're trying to break in with a friend, but for combat it's gimmicky stun crap.

**Comment by Tenebrosity** [comment]
This has always been a great mechanic though. It's very easy to run out of grabs, and this is very helpful in a pinch when you don't have a stun weapon. It still takes some degree of skill to chain tabling and strip the person to get to their items (which presumably is the reason you're chain stunning them).

**Comment by dannno** [comment]
there's no way you would be able to strip someone while chain tabling them without an accomplice anymore.

**Comment by Cheridan** [comment]
We discussed this before and came to the conclusion that, if you could chain-table someone then you could just as easily choke them. So this is basically choking that does no damage and requires more player input to pull off.

I'm not too concerned with it, balance-wise but if others see it as a problem then we can review it.

**Comment by Tenebrosity** [comment]
@danno You can, but it's not easy.

**Comment by phil235** [comment]
Fixed by #10592
