### ISSUE TITLE
Liquid Dark Matter no bueno

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#7297]
It just does NOTHING

**Comment by Dorsisdwarf** [comment]
Did you heat it to 500 degrees? I think that's the limit.

**Comment by GrayRachnid** [comment]
Yes, i've mixed it, spawned it, sprayed it, threw it in a grenade, splashed it on the floor, splashed it on someone it does ABSOLUTELY NOTHING

**Comment by tkdrg** [comment]
@Iamgoofball
