### ISSUE TITLE
Disposal Pipe Dispensor is Dispensing the wrong Pipes

### ISSUE THREAD

**Issue by callanrocks** [tgstation/-tg-station#7299]
There are no straight pipes in the entire thing, half of them aren't even the right ones, it just keeps dispensing corner pipes and those weird t shaped ones. I don't understand how this could possibly happen.

**Comment by Deantwo** [comment]
Maybe related: #7211 and #7253

**Comment by Menshin** [comment]
Fixed, amongst other things, by the recently merged #7177.
Will be live with the next server update.

**Comment by Deantwo** [comment]
I was wondering about that.
Kinda why I asked for the build version it was encountered on.
