### ISSUE TITLE
You can get Laser Eyes via genetics

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#7300]
Laser Eyes are obtainable via genetics like any other power, despite having their DNA block set to NOT_SCANNABLE.

I'm in favor of leaving it this way, but the code isn't doing what it's supposed to be doing.

**Comment by dannno** [comment]
I would rather have a balanced version of laser eyes, separate from the wizard power, for humans rather than removing it entirely
I might give it a shot myself later

**Comment by Miauw62** [comment]
laser eyes being available is debatable, but not intended behavior, so this is a bug for the time being.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
checking it out

**Comment by phil235** [comment]
Is this fixed?

**Comment by phil235** [comment]
Since noone seems to have mentionned geneticists getting laser eyes, I guess this is fixed.
