### ISSUE TITLE
Resonant shriek deafens before the audio is heard

### ISSUE THREAD

**Issue by leibniztg** [tgstation/-tg-station#7301]
1. be near a changeling
2. changeling uses Resonant Shriek
3. you are deaf (for no apparent reason)
4. only the changeling hears the sound (the audio file) of the scream (because they are immune to it)

This is not logical. You go deaf from hearing a horrible deafening sound.
So you should actually hear the thing that is deafening before going deaf from it. 
Like with flashbangs.
(unless it is like some dog whistle that is for humans instead of dogs but whatever)

**Comment by RemieRichards** [comment]
it's not necessarily within the range of human hearing.

**Comment by leibniztg** [comment]
But could you deafen a human with sounds they dont hear?
When does stuff like that happen?

**Comment by RemieRichards** [comment]
Yes you can deafen a human with a sound outside our hearing range that we can't "hear" but by god you'll feel it.

**Comment by Miauw62** [comment]
this is spessh fysiks though, so yeah you should hear it or have some sort of other message.

**Comment by Cheridan** [comment]
This is intended. It's like a dog whistle; humans can't hear it but changelings can. Why? Because otherwise they wouldn't have an indication as to why everyone else is freaking out around them when another changeling uses the power.

**Comment by Miauw62** [comment]
fair enough.

**Comment by leibniztg** [comment]
"Why? Because otherwise they wouldn't have an indication as to why everyone else is freaking out around them when another changeling uses the power."
I didn't suggest that changelings should not hear the scream so what you are saying is not really logical at all.
