### ISSUE TITLE
EXPERIMENTOR's eject breaks the machine, making it unusable & deleting the item

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7302]
it will not only delete the item, but also doesn't realise that it's finished ejecting, and from then on will appear busy.
http://i.imgur.com/cPLuQgK.png

**Comment by Chocobro** [comment]
@sawu-tg

**Comment by Deantwo** [comment]
Related PR: #7278.

**Comment by Chocobro** [comment]
doesn't seem to delete health analyzers, but does with wrenches and welding tools.
mystery.

**Comment by Miauw62** [comment]
@sawu-tg is this fixed by your PR?

**Comment by sawu-tg** [comment]
#7278 should fix this, if people would merge shit I ask them to, this wouldn't happen.
