### ISSUE TITLE
Issues with Cloak of Darkness

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7305]
- It works in areas without shadow, shuttle included
- It is functionally inferior to chameleon; it's the same thing, restricted to darkness (I've heard you can move around without it wearing off? but that doesn't seem like that much of a plus to me with chameleon in the state that it's in)

I been playin a lot of geneticist
Why not make it how it is on goon? Or at least how I remember it; You actually create a cloud of shadow around you, like a reverse flashlight. That's way more interesting and unique.

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by drynwyn** [comment]
It works in the shuttle because the shuttle is unsimulated. 

The big issue is that it only makes you invisible when you're damn near impossible to see anyway.

**Comment by Iamgoofball** [comment]
i'll look into increasing the brightness level

**Comment by dannno** [comment]
Or do it like I said before and not make it just a mediocre chameleon and actually make it a cloak of darkness

**Comment by drynwyn** [comment]
Given the number of lights on the station, you could probably make it "anything less than the brightest" without a balance issue.

**Comment by Dorsisdwarf** [comment]
Cloak of darkness should turn off any lights within 10 tiles of you, like how the AI can click them to turn them off

**Comment by dannno** [comment]
Cloak of darkness actually overrides chameleon. This is irritating. Not sure if it's the same the other way around.

**Comment by dannno** [comment]
And it's still utterly pointless and inferior to chameleon in every way, 0/10
make it anti-flashlight
