### ISSUE TITLE
The Chairs look fucking disgusting and make no sense 

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7308]
They are just awful, especially from behind.

http://imgur.com/6tibLtx

**Comment by dannno** [comment]
AHAHAHAHAHAHA

**Comment by Chocobro** [comment]
that's a nice opinion
you probably should have been looking at the PRs literally up to three days ago
https://github.com/tgstation/-tg-station/pull/7237
dummy

**Comment by dannno** [comment]
They really do look dreadful from the back

**Comment by WJohn** [comment]
I pointed this out like 10 times in that PR, guys god damn.

**Comment by dannno** [comment]
Why was it merged, then??? Why not make a better looking chair with a solid back?

**Comment by hornygranny** [comment]
#7311

**Comment by dannno** [comment]
I'm really at confused at what happened, no one seemed happy with the sprite on the PR. Don't know why it got merged.

**Comment by WJohn** [comment]
Blame perspective.

**Comment by Nienhaus** [comment]
I thought everything besides the south sprite looked fine, I more or less figured people would like the newer chairs even with it.

**Comment by Kromgar** [comment]
Yeahhhh nobody liked those sprites everyone flipped their shit in ooc
