### ISSUE TITLE
Detective's new shoulder holster doesn't work.

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#7309]
I couldn't put me revolver in.

And it has a bandolier sprite.

**Comment by ike709** [comment]
@paprka #7150

please stop merging anything by Paprka without completely reviewing every single line of code

**Comment by Menshin** [comment]
> I couldn't put me revolver in.

The _max_w_class_ variable of the holster should be set to 3.
I think the bandolier sprite is intentional...

**Comment by dannno** [comment]
...Seeing as the PR showed actual holster sprites i'm gonna say no

**Comment by paprka** [comment]
I thought item_state was only for inhands, what the fuck? The on-mob sprite should be using the icon_state.

Jesus, what the fuck is this shitcode I'm dealing with here.

**Comment by ike709** [comment]
mebbe u should test stuffs

**Comment by tkdrg** [comment]
On mob sprites have always used item_state (except for clothes which use item_color).

**Comment by paprka** [comment]
that's so stupid

**Comment by Stickymayhem** [comment]
I didn't realize people could actually be merging stuff without the most rudimentary five minute test on a local server

**Comment by Miauw62** [comment]
when its stuff that's literally a reskinned belt, i don't, no.

**Comment by Stickymayhem** [comment]
Belts don't hold guns though.
