### ISSUE TITLE
Monkeys cannot be given CPR

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7310]
could be related to the recent genetics bug from goonchem.
@Iamgoofball

**Comment by PKPenguin321** [comment]
I think this has been around a really long time actually, I recall a round at least a month and a half ago where we could only save Pun Pun with CPR because he was on death's door but couldn't, since we would just hug him.
tldr it's probably not related to genetics bug from goonchem

**Comment by phil235** [comment]
Yep, this isn't new, you can't CPR monkeys.

**Comment by Miauw62** [comment]
this is probably a dupe btw
