### ISSUE TITLE
chav translates "is" which is stupid

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7312]
![](http://a.pomf.se/aqciqo.png)

**Comment by tkdrg** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
feature

**Comment by dannno** [comment]
but this just looks like it wasn't meant to happen. it looks like an accident, like some idiot didn't consider how many words contain "is". it looks bad, goofball.

**Comment by Deantwo** [comment]
Maybe I don't get because it is freaking early and I am still half asleep.
But what was the person trying to say?

**Comment by dannno** [comment]
"This was a grave error."
the 'is' in ANY word will be replaced with "how what how".
It looks sloppy. Lazy.

**Comment by Deantwo** [comment]
Should at the very least be ```replacetext(message, " is ", " how what how ")``` so it doesn't do it to "is" that is inside words.
but yeah, maybe think of something else to replace it with too. I don't understand how "how and how" make sense. You may be suppose to sound stupid, but that doesn't mean you can't make sense.

Maybe replace " is " with " are " and small stuff like that.

**Comment by Chocobro** [comment]
goof if you need to know how chavs actually sound irl
i'm sure I can get sticky on ts :^)
