### ISSUE TITLE
Cigars and cigarettes not causing mobs to catch fire

### ISSUE THREAD

**Issue by parokki** [tgstation/-tg-station#7315]
So my favourite little trick is to fill a spray bottle with welding fuel, spray someone with it and light them on fire. It's not the absolutely most effective way of killing people, but it's fun and sometimes works if you get the jump on people. Most people will either run for an extinguishers, which means they're not radioing for help, or start rolling on the floor, which means they're not fighting back. 

The problem here is that the rules for lighting up people are kinda vague. I've managed to do it with a lighter and a welder, but apparently poking them with a cigar or throwing cigarettes at them, both of which are clearly super stylish actions that should be encouraged, is not enough. I don't know how exactly it works in the code, but could we change cigarettes, cigars, and other similar items that are clearly on fire to also cause flammable people to catch fire? Shouldn't be too much of a balance change, since anyone can get their hands on a welder, but creates a bit more variety and makes sense within the game world.

Oh and while I'm at it, throwing matches at walls covered with thermite didn't work either the last time I checked. Didn't test, but I guess throwing matches at fuel-covered people or throwing cigarettes at thermited walls don't work either. 

(first time posting on GitHub, sorry if I messed the category or something)

**Comment by ike709** [comment]
Possibly relevant: It works when they are smoking a cigar/cigarette.

**Comment by Delimusca** [comment]
fire code is pretty bare bones. most fire related items (matches, welders etc) will do ignitemob when you whack them with it, but this excludes cigarettes and most smokeables for some reason, may be an oversight. the inverse is true for held/stored items, cigs try to set you on fire every second while matches and lighters do nothing. also, being on fire is just a boolean that raises your body temperature, it's rather sad. 
overhauling fire is near the top of my todo list, but before i take a decade to get to that i'll see if i can throw up a PR to share the attack and process stuff between the common firestarters.

**Comment by Lumipharon** [comment]
Pretty sure a thermite reaction needs very high heat, so that actually makes sense a match doesn't work. Not being able to throw cigs at people to ignite the fuel on them is pretty gay though.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
