### ISSUE TITLE
Teleporter room on the MiniSat lacks an APC.

### ISSUE THREAD

**Issue by GunHog** [tgstation/-tg-station#7316]
@Steelpoint, the MiniSat's teleporter room has no APC, and is thus unpowered:
![screenshot 2015-01-23 20 44 42](https://cloud.githubusercontent.com/assets/4955510/5885873/cc9a812a-a340-11e4-95e8-253a93f64426.png)

**Comment by Steelpoint** [comment]
Most likely a result from https://github.com/tgstation/-tg-station/pull/7313

**Comment by WJohn** [comment]
Oh damn I swear I put one down. Be right there!
