### ISSUE TITLE
Cannot Dispense Straight Disposal Pipes

### ISSUE THREAD

**Issue by Yakk** [tgstation/-tg-station#7319]
1. Go to disposal pipe dispenser
2. Press pipe button
3. Get bent pipe and not straight pipe

All other buttons produce the proper pipe.

**Comment by WJohn** [comment]
@menshin?

**Comment by Deantwo** [comment]
Already reported many times, #7299, being the latest.
And already fixed in #7177. At least I don't think that fix is live on the server yet?
Please state the build version you encountered the bug on!

**Comment by Miauw62** [comment]
yeah, this is a dupe.
