### ISSUE TITLE
Washing insulated gloves with a crayon make them lose insulation

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#7321]
Exactly what it says on the tin.

Repro:
*Toss insulated in a washer
*Add whatever crayon (green, in this case)
*Wash it

Expected: Gloves are still insulated
Actual: Ain't

Build: Latest as of 1/23

**Comment by Deantwo** [comment]
Can you make normal gloves insulated though?

**Comment by TheVekter** [comment]
Haven't tried yet. Might be cool. I'll give it a shot.

**Comment by Deantwo** [comment]
Yellow gloves do exist, so I hope not.
Or at least they did when I played with this a year or two ago.

**Comment by Miauw62** [comment]
erro's shitcode legacy lives on. fairly sure this is a dupe.

**Comment by phil235** [comment]
I can't reproduce this.
