### ISSUE TITLE
View Admin Notes is hard to read

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7337]
Please add line breaks.

![screenshot 2015-01-24 18 27 03](https://cloud.githubusercontent.com/assets/9098006/5889811/a0a3316e-a3f6-11e4-8775-e2f2f26d1f3f.png)

**Comment by paprka** [comment]
>that note from brotemis

**Comment by Deantwo** [comment]
So after this goes live on the server I'll be about to if admins have written anything about me? o.o

**Comment by Deantwo** [comment]
Add ``` + "<br>"``` at the end of this line: [admin/player_notes.dm#L23](https://github.com/tgstation/-tg-station/blob/f7a32789fb160682ff13391c066d9dd2adc30c54/code/modules/admin/player_notes.dm#L23).
I think.

**Comment by JJRcop** [comment]
close this
