### ISSUE TITLE
You can knock on one-way windows from a tile away

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7341]
Perhaps shitty ASCII art will best explain this:

@ <=== you
_ <=== window tile, technically far out of reach

This is a minor bug but a bug it is regardless

**Comment by ike709** [comment]
ASCII art does not best explain this.

**Comment by bgobandit** [comment]
One-way windows act like they occupy the entire tile, even if they are on the tile's far side. This means you can knock on them from one tile away, even when that would appear to be a larger than feasible distance.

**Comment by Anonus** [comment]
This is a good reason to remove them forever because border objects are complete dongs.

**Comment by paprka** [comment]
remov borders REMOVE BORDERS

**Comment by optimumtact** [comment]
Fucking border objects every time godamn ahhhhh
