### ISSUE TITLE
The cargo shuttle looks like ass

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7343]
Pic: http://i.imgur.com/YCk4voM.png

Basically due to the edges, there are what appear to be two hull breaches in the shuttle itself. Shows up on the station too, I just had to take the pic at centcom

**Comment by ike709** [comment]
Issue title is misleading, I see no ass.

**Comment by phil235** [comment]
related to #7167

**Comment by WJohn** [comment]
This just got fixed god damn.

**Comment by bgobandit** [comment]
it isn't fixed, cargo shuttle still looks like ass
