### ISSUE TITLE
Unable to whisper succumb in handcuffs

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7348]
You can succumb in handcuffs, but you can't whisper succumb.

Whisper succumbing is when you whisper in crit to share your last words with whoever is adjacent to you and then die.

**Comment by Miauw62** [comment]
This is odd.

**Comment by Stickymayhem** [comment]
This may be due to the fact you cannot go straight to suicide while cuffed and alive. Deathwhisper might be a child of that or something.

**Comment by Miauw62** [comment]
this appears to be fixed.
