### ISSUE TITLE
Secret Chems.

### ISSUE THREAD

**Issue by nopm** [tgstation/-tg-station#7353]
If there are any secret chem like those in goonstation, could you please tell me? i don't have the time, neither the competence to sit my ass in a chem dispenser to learn these. so, if you please tell me, i would be glad, and don't be like "no,shh", or " no one is gonna tell you, get out of here" because that is just plain assholin'. so PLEASE, tell me if they exist, if not, well, tell me they don't.

**Comment by CorruptComputer** [comment]
You should ask on the forums, no one here is gonna tell you.

**Comment by nopm** [comment]
Asking on the forums is probably going to screw me up, so no, and also, what is the fucking problem in telling me here? do i really need to crack open this game code to see the recipes? man, i said, no assholin'. i need these, my friends want to use them on MY server, and i don't know, please tell me, i don't have the time!

**Comment by Miauw62** [comment]
lyl

**Comment by nopm** [comment]
seems like cracking the game open is the only solution. fucking assholes. seems like telling me will end the world.

**Comment by Miauw62** [comment]
m8, this is literally an open source game.
there are no secret recipes.

**Comment by nopm** [comment]
of course there are, like anima, and some other shit. if someone just told me instead of this bullshitting, it would be so much easier....

**Comment by Miauw62** [comment]
i could give you the recipe for the chem that cures braindamage, if you'd like.
