### ISSUE TITLE
Aliens cannot chestburst from a human that's in a mech

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7354]
bug was found with someone in a durand, so it might only affect the durand, or all mechs. one or the other.

**Comment by WJohn** [comment]
I'm curious in what other ways mech pilots are or are not affected by other diseases. Do they get damaged inside if an explosion happens nearby now with the new explosion properties?

**Comment by paprka** [comment]
pilots are pretty much immune from anything outside mechs except atmos iirc

**Comment by palpatine213** [comment]
Switch control of the mech to the larva.

**Comment by WJohn** [comment]
Alien controlled mech. Yes.

**Comment by kevinz000** [comment]
Holy fuck pls yes alien controlled durand
