### ISSUE TITLE
Give admins the power to bring ghosts back into the lobby

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7355]
Admin Feature Request

I often need to do this to give players a second character. Right now, the workaround is to simple nullify their ckey on their mob, but I'd rather I have a method that sends them back to the lobby without kicking them from the server.

**Comment by Deantwo** [comment]
Maybe it should prevent you from spawning the same character again though.
We have three character slots after all.

**Comment by MrStonedOne** [comment]
that should be up to the admin.

**Comment by Ikarrus** [comment]
It turns out the workaround I was using (editing ckey to null) was breaking say code on the servers.

**Comment by Jordie0608** [comment]
There's a respawn command that lets you choose a ckey to have their character re-created as if they late-joined.

**Comment by Ikarrus** [comment]
That's not the solution I want, though. Sending them back to the lobby lets them make a new character, pick a new job, and fill the slot normally.
