### ISSUE TITLE
Restrained SNPCs cannot be dragged

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7356]
Handcuffed greytide move regardless of being held by someone else.

**Comment by WJohn** [comment]
SNPCs are incredibly shit. Who'da thought?

**Comment by Stickymayhem** [comment]
I hope they become neat ;_;

**Comment by optimumtact** [comment]
@sawu-tg pls

**Comment by Miauw62** [comment]
sawu quit.

**Comment by WJohn** [comment]
Of course he did.

**Comment by palpatine213** [comment]
They still can't be dragged even if dead.

**Comment by Cheridan** [comment]
Basically a dupe of #8324

**Comment by freerealestate** [comment]
You also get a runtime when an SNPC spawns as a head of staff, such as when using the Populate World verb

**Comment by optimumtact** [comment]
it's dead code basically

**Comment by freerealestate** [comment]
Why?

**Comment by optimumtact** [comment]
Nobody else is stepping up to maintain it, I don't see anyone who looks like they will in the near future either.

Happy to be proven wrong

**Comment by Shadowlight213** [comment]
I have a hunch about what's wrong with SNPC movement, but until I understand movement code better, I can't test my hunch.
