### ISSUE TITLE
Jump to Area bug

### ISSUE THREAD

**Issue by An0n3** [tgstation/-tg-station#7360]
During a round someone added a new area using the blueprints, and from that point on when using the "Jump to Area" function in the admin tab it would immediately send us to the new area without any kind of selection menu.

Repro:  create a new area in space, name it with the blueprints, and then try to jump to an area as an admin ghost

**Comment by Menshin** [comment]
Coudn't reproduce...

There's still a bug with Jump to Area which doesn't list the Station areas, because they have no contents (everything is in related areas). So jumping to Engineering, for example, is impossible for now.

I'll fix that if @Carn doesn't want/have time to take care of it.

**Comment by Carn** [comment]
I've left menshin

**Comment by Menshin** [comment]
:disappointed: 
Ok, i'll take care of it.

**Comment by paprka** [comment]
Top carn

**Comment by An0n3** [comment]
Hmm.  Wish I had more info to provide.

**Comment by Tenebrosity** [comment]
Station areas not appearing in the jump to area list isn't fixed in 0ca8750c803dab1e06d80d492acc9c6f1aad13fb. Maybe that PR just needs to be updated though.

**Comment by Deantwo** [comment]
My PR is most likely not up to date Tenebrosity.

**Comment by Tenebrosity** [comment]
Oh, okay. I couldn't be assed to check. I just noticed you opened it today and the fix to this was pulled a couple of days ago, so I assumed you'd have this commit.
