### ISSUE TITLE
ERT Commander Access

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7362]
ERT Commanders should have exclusive access to their own gear. The command gear room being right next to spawn means a mad dash to grab the good gear there which can cause problems.

**Comment by paprka** [comment]
i might remap this when i'm not lazy

**Comment by Steelpoint** [comment]
Not pinging me on this.

I've already committed to giving the ERT Com room Commander Access only.

**Comment by phil235** [comment]
@Steelpoint is this fixed?

**Comment by Steelpoint** [comment]
Paprika fixed it a long time ago.
