### ISSUE TITLE
Paprika a shit

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7364]
Paprika is a shit. Resolve posthaste.
This is my last service to TGstation :smile:

**Comment by optimumtact** [comment]
Closed Wontfix

This is an intended feature, not a bug

**Comment by paprka** [comment]
ow the edge case

**Comment by Nienhaus** [comment]
You forgot a tag @Cheridan

**Comment by Miauw62** [comment]
ayy lmao

**Comment by Iamgoofball** [comment]
ayy lmao

**Comment by S0ldi3rKr4s0** [comment]
ayy lmao

**Comment by Cheridan** [comment]
ayy lmao

**Comment by RemieRichards** [comment]
ayy lmao

**Comment by Kraseo** [comment]
![ss 2015-01-26 at 05 27 31](https://cloud.githubusercontent.com/assets/3855300/5904691/a7153700-a58a-11e4-9361-b94aefb916d2.png)

**Comment by RemieRichards** [comment]
>Attempt #37441 mom laya

**Comment by quaggaman555555** [comment]
@Kraseo Can I get you to send me that python shell in some way? I'm curious as to what you did, but it might be a bit late though. How long did it take to get to ayy lmao? Oh, and look at attempt #37431, aol oyly, who poured oil on AOL?

**Comment by ike709** [comment]
ayy lmao

**Comment by Dorsisdwarf** [comment]
Oaml Y.Y.A

**Comment by quaggaman555555** [comment]
Can I get you to send me that python shell in some way? I'm curious as to what you did, but it might be a bit late though. How long did it take to get to ayy lmao? Oh, and look at Attempt #37431, aol oyly, who poured oil on AOL?

**Comment by TheVekter** [comment]
oaml yya
