### ISSUE TITLE
Editing mob ckey to null can break say code for the rest of the round

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7365]
It's very easy to inadvertently break the round like this. I know admins shouldn't be messing with it now, but a way to protect the say code from breaking would probably be helpful in case anyone else gets the same brilliant idea that I did, or some rogue code does it.

**Comment by Ikarrus** [comment]
Related: #7355

**Comment by Miauw62** [comment]
:x

**Comment by Ikarrus** [comment]
Specific repro:

- Be ghost
- Var edit your ghost mob
- clear the field and press okay (making it null)
- rejoin the server and listen to OOC complain about say code being broken

**Comment by Menshin** [comment]
In case you're looking for the cause :
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L164

> for(var/mob/M in player_list)
       if(M.stat == DEAD && ((___M.client.prefs.toggles___ & CHAT_GHOSTEARS) || (get_dist(M, src) <= 7))&& client)

Manually setting a ghost ckey to _null_ also null the client, so the proc is runtiming at this check and the speech doesn't process.

Correctly fixing this bug would to be fix #7355.

**Comment by Miauw62** [comment]
just adding an if M.client check would work too, thus I'm going to do that.

**Comment by hornygranny** [comment]
this used to be fine to do so older admins are likely to eventually break saycode
