### ISSUE TITLE
Silly Tech is a bit too silly

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7368]
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.
The reinforced window was hit by the silly illegal tech.

Spamming certain illegal techs causes endless spewing of temporary illegal techs. These techs can be picked up, making them permanent and spammable so everyone can join in the laggy fun!

They are actually really fun but a limit of about a thousand would help. It only started getting laggy at around 2000

**Comment by Deantwo** [comment]
This has to do with the Experimentor or what?
I have no clue what *silly illegal tech* is.

**Comment by Stickymayhem** [comment]
I'm not sure what creates it, but it seems to be the result of some kind of experimentor effect on illegal tech you throw in.

When you then click the tech in your hand it produces like 10 more techs that fling out

**Comment by palpatine213** [comment]
I'm pretty sure this happens on the artifacts. Just happened yesterday with what looked like an electric chair called broken object.

**Comment by phil235** [comment]
I think this was fixed by #7769
