### ISSUE TITLE
Science Guard Post Research Monitor doesnt work

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7370]
![screenshot 2015-01-25 21 08 09](https://cloud.githubusercontent.com/assets/9098006/5895235/474b7e7e-a4d6-11e4-84d2-9aca58a2bcfd.png)

**Comment by Jordie0608** [comment]
#7360 is possibly related

**Comment by Jordie0608** [comment]
This got fixed ages back.
