### ISSUE TITLE
Layer bugs in Experimentor room

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7372]
The biohazard suit locker in the top right has a layer exceeding any items put inside when open, making easy access to those items open.

Also, when the western airlock is open, the fire door obscures it making it nigh-impossible to close again without alt+click

**Comment by pudl** [comment]
which map even

**Comment by Stickymayhem** [comment]
boxstation. Sorry.

**Comment by WJohn** [comment]
I don't quite understand this issue, items are supposed to be placed on top of the locker when it's open, they all do this. What's the issue here? Are they somehow appearing above it? Is this still the case?
