### ISSUE TITLE
Condiment bottles from the condiment master aren't labelled

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7375]
This is a feature request, but it would be nice if the bottles you create in the condimaster were named based on the substance inside, like chemistry bottles and condiment packets. This way you wouldn't have to examine them to see what was inside.

**Comment by Chocobro** [comment]
it's been like this for years. :-1: mostly because of nostalgia.

**Comment by Miauw62** [comment]
it should show the main reagent on examine
