### ISSUE TITLE
Destroying lockers causes its content to disappear

### ISSUE THREAD

**Issue by Deantwo** [tgstation/-tg-station#7376]
A Ripley Mech destroyed a **personal locker** that I had filled with a lot of stuff.
Apart from the message about the Ripley using its dill or whatever on the locker, it just vanished with no message along with all its content.

Server revision compiled on: 2015-01-25 39a9283592a444bae84819cbbe0519f4b3cb9600

At the very least a message saying that the locker is crushed along with all its content, rather than just vanishing. Maybe some debris would be a nice touch.
But it would be nice of course if (at least some of) the content survive.

**Comment by Alek2ander** [comment]
Could it have picked up the locker with the clamp instead of drilling?

**Comment by Deantwo** [comment]
I could. I was in a hurry and forgot to read the message in detail.
I just know that it destroyed the locker with something.

**Comment by Lumipharon** [comment]
Nah, I can confirm, it's more then just that. If you set a pulse rifle to destroy, it will destroy the locker with all it's contents.

I wouldn't be surprised if c4/other things also cause it.

**Comment by Deantwo** [comment]
I can try and fix it if no one else wants to.
Would be fun to look into.

**Comment by AlexanderUlanH** [comment]
Pulse rifles and ripley drills both call ex_act, so it's probably unique to explosions.  Doesn't sound all that unrealistic to me.  If you try to use a drill that clears out a three-tile-wide bunch of asteroid to get a locker open, it probably won't work out well.

**Comment by Deantwo** [comment]
Not saying it doesn't make sense that it could destroy it.
But that it just vanished with no message or visible debris is just odd.

**Comment by WJohn** [comment]
I thought this was intentional as some sort of nerf to emmiter blasting crates and lockers open.

**Comment by callanrocks** [comment]
Confirming that this isn't the case for emitters, they drop everything thing.

Maybe a huge drill mark on the tile whenever a drill wrecks something?

**Comment by Deantwo** [comment]
As AlexanderUlanH said:
> [Pulse rifles and ripley drills both call ex_act](https://github.com/tgstation/-tg-station/issues/7376#issuecomment-71553193)

So is most likely just those.
