### ISSUE TITLE
Manifest Chance for powers is absurdly low

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7385]
You go through a ridiculous amount of SE injectors before manifesting ANYTHING, even with all power blocks above E
I'll probably buff this if I ever figure out how the fuck genetics works but that might not be VERY LIKELY HNNNHNH

(yes it's bad luck but holy fuck genetics is composed entirely of RNG we should change this)

**Comment by ike709** [comment]
I've heard talk of about three or four different genetics rewrites since a few months ago yet I'm still waiting.

**Comment by PKPenguin321** [comment]
I think the big genetics rewrite that's been planned won't happen until remie's dismemberment goes through since it utilizes custom limbs or something
I have a lot of hope for it though

**Comment by Lumipharon** [comment]
That's why you don't use injectors. You have the actual DNA machines for a reason you know.
It also makes it harder to be an omni powered god. Whether this is good or bad, you decide.

**Comment by dannno** [comment]
Being required to have two people to abuse the machines is dumb though...?

**Comment by Miauw62** [comment]
@Razharas
