### ISSUE TITLE
Carp can knock down borgs.

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#7394]
What it says on the tin.

**Comment by WJohn** [comment]
I imagine that any other simple animal that has the ability to stun can do this too?

**Comment by Actionb** [comment]
Probably yes. Just had a borg be knocked down by animated objects (wizard's staff).

**Comment by dannno** [comment]
This is still a big issue

**Comment by WJohn** [comment]
Really, the whole "simple animal knockdown" is a huge problem. This, combined with their incredible speed, diagonal movement, and bullet-dodging abilities is really not fun, they're entirely too powerful for even the head of security to take on, and that's just ridiculous.

**Comment by RemieRichards** [comment]
Sorry to use such a lowly argument, but git gud.
If I, surely one of our least robust players FREQUENTLY go out into space and hunt carp every time they're sighted, then surely to god you can defend yourselves.

The only issue here is that borgs can be knocked down.

**Comment by dannno** [comment]
Getting fucked by a single carp because of shitty RNG knockdown over and over isn't something you say "git gud" to
RNG is garbage in combat, why would anyone defend it ever

**Comment by RemieRichards** [comment]
the idea is you don't let it get close to you. if you don't have a range weapon you run, you don't stand your ground.

**Comment by dannno** [comment]
They move at the same rate as you, faster than you if you're in space. 
There is no reason for this RNG shit. It's bad mechanics.

**Comment by RemieRichards** [comment]
if there truely was no reason for it it wouldn't be there.
it exists for variety.

**Comment by Miauw62** [comment]
pls, this discussion is irrelevant. borgs should be unable to be knocked down.

**Comment by dannno** [comment]
>if there truely was no reason for it it wouldn't be there.

this isn't evolution or something, it's spaceman game mechanics
the people who code this game are absolutely not always doing things for the right reasons
and yeah what he said

**Comment by RemieRichards** [comment]
I wasn't saying it was evolution. People have reasons for doing things, were not mindless machines.
Whomever made carp knock people down on RNG had a reason for doing so, or they would not have written the code. Whether that reason is valid to anyone but that person IS up for debate, but I only brought this up because you said there was no reason, which is false.

**Comment by dannno** [comment]
remie please don't get all semantical on me

**Comment by RemieRichards** [comment]
I'm all about semantics.

**Comment by Miauw62** [comment]
>pls, this discussion is irrelevant. borgs should be unable to be knocked down.

**Comment by RemieRichards** [comment]
@Miauw62 yes it's irrelevant, and stop spouting "borgs should be unable to be knocked down" as if it's some counter to either of our arguments, it isn't, both have us have said that borgs being knocked down is an issue.

**Comment by Miauw62** [comment]
im not saying that the discussion is dumb, this just isn't the place to discuss it.
