### ISSUE TITLE
No inhand for space carp plushie.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#7395]
It urgently needs one.

**Comment by TZK13** [comment]
As the person who implemented them I'll look into this.

**Comment by WJohn** [comment]
Carp plushie also needs to be made dark blue(purple?) like the other carp.

**Comment by TZK13** [comment]
They're plushies, they don't need to be the same colour as the real animal and it makes sense that they're lighter in colour and thus cuter.
