### ISSUE TITLE
The lighting engine occasionally just gives up for a tick

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7399]
Rarely but seemingly at random the lighting engine will stop functioning, removing all shadows in sight from view for a tick before pulling its shit back together.

**Comment by xxalpha** [comment]
I think I saw this happen as well. I saw broken lights that for a brief moment emitted light.

**Comment by WJohn** [comment]
Yeah I've seen this happen over a loooooong time. This is an ancient bug.

**Comment by Miauw62** [comment]
Probably fixed with objectlightning.
