### ISSUE TITLE
Continuous Round Wiz has no effect

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7405]
Turning on CONTINUOUS_ROUND_WIZ mid round no longer changes how the round ends. 

Having it on should have meant that the round wouldn't automatically end when the wizard died.

Instead, the round ended when the wizard died.

Repro:
Play wizard round
Use debug-configuration -> config to set continuous_round_wiz to 1
Kill the wizard

**Comment by Incoming5643** [comment]
if(config.continuous_round_wiz)
	return ..()

where ..() is:

	if(SSshuttle.emergency.mode >= SHUTTLE_ENDGAME || station_was_nuked)
		return 1
	return 0

It doesn't leave much room for bugs so maybe the error is in the config options somehow?

Also remember that the round automatically ends no matter what if everyone is dead, so you can't test this by being a wizard in a debug round and then killing yourself.

**Comment by Ikarrus** [comment]
You can still test it if you multikey.

**Comment by Deantwo** [comment]
Was the shuttle docked at the station?

**Comment by Ikarrus** [comment]
No

**Comment by Incoming5643** [comment]
This was fixed in mulligan antagonist
