### ISSUE TITLE
bbcode is not working properly

### ISSUE THREAD

**Issue by Riukanojutsu** [tgstation/-tg-station#7407]
If you try to write one part of the text in bold using [b][/b]. it will write everything after the [b] in bold and ignore the[/b]
Its like that for every fonction.
Makes the fonction useless

**Comment by Deantwo** [comment]
BBCode where?
Did I break something?

**Comment by Riukanojutsu** [comment]
Yea I meant to post it on vg. Sorry for the confusion.
