### ISSUE TITLE
Right arms aren't removing damage overlays properly

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7408]
1. screw up your right arm
2. heal your right arm
3. freak everyone out with your seemingly mangled but not right arm

**Comment by ike709** [comment]
2spooky

**Comment by PKPenguin321** [comment]
Based on other issues like this I've observed, I would bet, but don't quote me on this, that this is an issue of someone writing something like "rarm" instead or "r_arm" or something. These probably aren't the actual terms used in the code and I cannot into code so my word may not be reliable, but that's something to look out for I guess?

**Comment by phil235** [comment]
Can't reproduce so it's probably fixed
