### ISSUE TITLE
MC crashing

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7410]
Just came from a round on Sybil where the server had to be reset because everything froze up.  You couldn't move, you couldn't talk, you couldn't adminhelp, you couldn't use emotes. The only thing you could do was face another direction. Based on seeing this issue a couple of times in the past (the only time I've ever seen restart votes pass) you can probably throw objects to move around too.

I assumed it was fixed because I hadn't heard of it happening again until today. This was apparently the second time it happened.

Sorry if this is a duplicate.

**Comment by Incoming5643** [comment]
Master control is crashing

**Comment by ike709** [comment]
I wonder what caused the crashing.

**Comment by hornygranny** [comment]
judging from the runtimes it is a byond issue

**Comment by WJohn** [comment]
Hopefully we don't get something ridiculously vague like drones being in the presence of the singulo.

**Comment by Madjura** [comment]
Unsure where to post this, but Sybil appears to be crashing regularly at the moment. 
It was up just a few minutes ago, 3 people joined before the round began but from what I could tell only me and another guy actually pressed ready (maybe the third guy was a cyborg, I checked the PDA list and only 1 other guy was listed, RD)
I had a random name, appearance and character and got traitor, spawned as botanist.
Went out of hydro and left towards medbay, RD was sorta sliding to the left, facing the wall. Server then crashed / died. Hope it helps

**Comment by palpatine213** [comment]
This just happened yesterday on Basil. Twice in a row by the way. First time the only thing that still worked was OOC. A restart vote was done but the timer wouldn't count down.
After Scaredy restarted, the game worked for a bit, then it seemed like the gravity cut out and it crashed again. Skorvold tried to restart the server twice, but nothing happened.

**Comment by MrStonedOne** [comment]
This is not a MC crash.

This is caused by byond having a memory error that causes a bunch of lists to become corrupt, causing any proc that uses those lists to runtime, including mob move, most admin stuff, saycode, atmos, etc.
