### ISSUE TITLE
Assassination objective and shuttle

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7413]
The objective to kill a person is fine, I just never understood why it still counted as successful if the target's body is on shuttle, heading straight for centcom for cloning.

It's probably fair to assume that when the syndicate hired you to kill someone, they also wanted you to keep them dead and not just a minor inconvenience that'd get fixed once the shuttle docked. Maybe instead of having them be dead, also have them not be on the z2 level at round-end to count towards greentext (e.g thrown off the shuttle mid-flight, gibbed)?
Keep borged targets as greentext because being turned into a corporate silicon slave is probably enough to appease the syndicate.

It'd also help cut down on those 10-second mad rushes where you quickspam a revolver on your target and play yakkity sax with security till shuttle docks.

**Comment by Xhuis** [comment]
Might be misleading. Wasn't this what the 'prevent from escaping alive' objective was added for? I would actually approve of replacing assassination with the aforementioned alternative because it might allow for more fun ways of doing your objective.

**Comment by Steelpoint** [comment]
From a lore perspective, cloning technology is a really new form of tech that only SS13 has thus far, not even Central Command has any cloning machines.

As such it makes sense anyone brought back to CentCom dead is not going to get cloned any time soon.

**Comment by Ikarrus** [comment]
>From a lore perspective, cloning technology is a really new form of tech that only SS13 has thus far, not even Central Command has any cloning machines.
As such it makes sense anyone brought back to CentCom dead is not going to get cloned any time soon.

Basically this

**Comment by TZK13** [comment]
What, I've never heard of any lore where cloning technology is that limited. That sort of lore would also fuck with a very large amount of people's headcanons that involve Centcom cloning as an explanation for how people can remember certain aspects of previous shifts even if they've been gibbed and shit.

As for the actual issue I don't see it as an issue, I've never viewed the Syndicate assassination objectives as trying to permanently remove people since again the headcanon that a lot of people have includes Centcom genetic backups for cloning. It's just the Syndicate's way to fuck up a shift on SS13 considering a temporary loss of an employee still isn't desirable. Killing them on the shuttle just means more work for Centcom which is perfectly suitable in my mind.

**Comment by Steelpoint** [comment]
Pet peeve but headcannon is just that, headcannon.

Our lore is extremely limited, however of the lore we do have it is clearly stated that SS13 is one of the very few places to have cloning tech as cloning technology is a very new form of technology. In fact Nanotrasen is not the people who created it.

Here's a excerpt about Centcom and cloning.

>As powerful as it (central command) may seem, it still lacks some of the more experimental technologies found on some of their more remote research stations, such as an advanced neural programming lab or a cloning bay to replace lost employees.

**Comment by TZK13** [comment]
>The home office of Nanotrasen's day to day affairs, CentCom is a secure and centralized space station at a classified location. Everything about them is thorough and professional, and to date there have been no successful attacks or infiltrations reported to the company newsletter. It comes fully stocked and self-sufficient at all times and is a safe haven for all employees of Nanotrasen's many holdings. There's even an advanced neural programming lab and vast cloning bay to provide excellent and rehabilitative health care for elite Nanotrasen employees! 

That's what it said until April 15th, 2014 when Jordie for some reason decided to completely reverse it. Headcanon is far, FAR more important than any "lore" dictated by one person.

**Comment by Steelpoint** [comment]
Amusingly I discoverd that when the lore page on the old wiki was made that the above quote was correct, though on December 2013 it was changed to the "no cloning".

Clearly a case of people trying to insert their headcannon into the lore. Though I doubt that will happen ever again.

Irrespective, its a moot point. Afaik a dead body on the shuttle should not fail a antag in their objectives to kill them, I suppose by that the no cloning lore is somewhat correct, or not.

**Comment by TZK13** [comment]
Well I just checked the Centcom away mission and it has cloning, while what some mapper decides to map and what some lore writer decides to write or both basically people adding their own headcanon I'd say things actually in the code have some more precedence.

But yeah dead people on the shuttle should still count for the assassination objective, it just seems a bit obnoxious for them not to be. Sure shuttle assassination are also obnoxious but whatever.

**Comment by Cheridan** [comment]
MUH CANON
