### ISSUE TITLE
The new disabled/enabled in prefs text in the Traitor Panel breaks formatting and makes it difficult to read

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7415]
It used to be that each antag type was kept to it's own line. But the added text caused the lines to wrap around and make it a lot more difficult to read than it used to be.

I suggest either using a different method to show if it's enabled in their prefs, and/or make the window larger.

![screenshot 2015-01-28 18 43 32](https://cloud.githubusercontent.com/assets/9098006/5950940/b31f39da-a71d-11e4-8594-8123f7be7b70.png)

**Comment by RemieRichards** [comment]
Just make the window larger. and also that OP is horribly misleading. it's Rev. Rev is the only one that loops.
