### ISSUE TITLE
It's really hard to type anything with the communications console window open as AI

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7417]
Because the comms console window auto-refreshes every second now that it displays the shuttle timer in real time, it is literally impossible to type anything as the refreshing window constantly steals focus.

Repro:
-Be AI
-Call the shuttle
-Try to make an announcement via console with the comms window still open

**Comment by GunHog** [comment]
It is indeed a major pain. NanoUI would fix it :)

**Comment by Deantwo** [comment]
Make it use NanaUI?
Then again, I guess we have no one that knows how to make NanaUI.

**Comment by phil235** [comment]
related to  #6047

**Comment by KorPhaeron** [comment]
@tkdrg 

Fixed/outdated
