### ISSUE TITLE
Librarian's bookbag can't be worn on the back slot, despite the sprite looking like a backpack

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7425]
if this isn't intended, i'll sprite it.

**Comment by WJohn** [comment]
The bookbag is a "bag" like the mineral or plant bags. You never could wear them.

**Comment by Chocobro** [comment]
then the sprite should be changed to something without back straps.

**Comment by Deantwo** [comment]
Or let them be worn in the back slot?
What would be the harm in that? Or is that because there is no sprite for wearing them?
