### ISSUE TITLE
Desk lamps can be worn on a hazard vest as an accessory

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7427]
![lampdesk](https://cloud.githubusercontent.com/assets/5677255/5963396/c45184ee-a7e3-11e4-90f9-565d51be92d8.png)

**Comment by ike709** [comment]
why did you try to in the first place?

**Comment by Nienhaus** [comment]
I love this. Can this be a feature?

**Comment by Fox-McCloud** [comment]
Second Nienhaus' sentiment; just let it stay--this is positively hilarious without really breaking anything.

**Comment by stapler2025** [comment]
feature

**Comment by PKPenguin321** [comment]
feature
![feature](https://cloud.githubusercontent.com/assets/8345184/5970694/8874f5a2-a7eb-11e4-9138-dafd2a3b0849.jpg)

**Comment by Cheridan** [comment]
:no_entry_sign: :a: :bug:
