### ISSUE TITLE
Acid Grenade Propelling Target and Swapping Items With Mobs

### ISSUE THREAD

**Issue by Steelpoint** [tgstation/-tg-station#7429]
On the server I was attacked by a Chemist with a acid grenade.

I tried to get out of the way but I took a hit, however I was suddenly propelled from below the Warden's Office to a rear Cell, with some of my equipment missing, next to the Chemist who was also thrown, while also wearing the ID/PDA of another Sec Officer caught in the blast.

@Iamgoofball

**Comment by Anonus** [comment]
That sounds like it was a sorium or darkmatter grenade as well as acid.

**Comment by Lumipharon** [comment]
Or lube.

**Comment by RemieRichards** [comment]
The key factor here is it isn't acid's fault. Goonchem brought no changes to acid. Facid for example, is just renamed pacid (same strengths for toxicity and acidpwr)

**Comment by Deantwo** [comment]
Yeah a complete list of the reagents used in the grenade is required.

**Comment by Iamgoofball** [comment]
no fucking clue about the ID swap

but that sounds like Sorium

**Comment by Iamgoofball** [comment]
i've been testing this shit locally

i can't reproduce the ID swap

this is either higgs bugson/mindswap backfiring/whatever

and I sure as hell can't do jack shit until I have a full reagents list
