### ISSUE TITLE
Balance/Buff: Duffelbag's Combind Weight Class

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7432]
Backpacks currently have 7 slots, a max combined weight class of 21, and can hold items up to a weight class of 3; which seems to suggest that the formula for max combined weight class (in the dev's mind anyway) was slots*max weight class = max combined weight class.

Duffelbags were released and they have +2 storage slots, for a total of 9, but they slow you down by 1 level when equipped; that said, they still have a max weight class of 3 and still have a max combined weight class of 21.

My suggestion: give Duffelbags a max combined weight class of 27, for consistency and a bit of a buff to them, considering their downside.

**Comment by Miauw62** [comment]
going to tag this as a bug for now. @danno.

**Comment by dannno** [comment]
They don't have 7 slots. They do have 9. Tested it on the server after the update. 
The thing is that you can't put a box/container in unless it's in one of the first 7 slots; I don't know why it's like that, but that's what confuses people.
Or maybe I did mess up the max combined weight class. I'll look into it.

**Comment by RemieRichards** [comment]
@dannno Backpacks have 7 slots. That's what was said. and yes, it sounds like it's max weight class' fault.

**Comment by dannno** [comment]
Oh woops, misread the thing entirely. I thought the issue was that dufflebags still had 7 slots.
This is a thing I missed that I will fix asap
