### ISSUE TITLE
NanoMed Plus doesn't vend toxin anymore

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7433]
Now I can't make weedkiller to kill space vines. What the fuck coderbus?

**Comment by Fox-McCloud** [comment]
Eventually (key word, eventually), Weedkiller will be Atrazine (Chlorine+Hydrogen+Nitrogen), and hacked Nanomeds will dispense a bottle of pancuronium instead of toxin

**Comment by bgobandit** [comment]
The NanoMeds also do not vend droppers. This is annoying for botanists, who often request droppers for mutagen and don't often want to use up the ones in chem.

**Comment by Iamgoofball** [comment]
goddamn it @pudl

why did you remove droppers and toxin bottles

**Comment by pudl** [comment]
there's a few boxes of droppers in the chemical closet.
also emagged nanomed vends toxins, i thought we already had atrazine

**Comment by babinsquared** [comment]
A smiley face for removing generic toxin. A frowny face for the recipe difficulties this caused.
When "eventually" rolls around, please keep the other toxin recipes in mind! Plant-B-Gone and Pestkiller aren't often made, but they're pretty useful when you know what you're doing. I've put both to good use as a botanist.
