### ISSUE TITLE
cigarette inhands are gone

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7434]
this is awful
what have you DONE

**Comment by ike709** [comment]
@paprka i blame u

**Comment by paprka** [comment]
SHHHH this is actually @TZK13 's fault but i will fix them

apparently cigarettes might be clothing (god why)

**Comment by Nienhaus** [comment]
Isn't the inhand sprite shit?

**Comment by dannno** [comment]
no, it's hard to fuck up a tiny cylinder

**Comment by Nienhaus** [comment]
It's like a green block, also cigarette packs aren't cylinder.

**Comment by dannno** [comment]
Cigarettes. Not packs. The cigarettes themselves.

**Comment by TZK13** [comment]
Whoops, yeah this was my fault I didn't realize cigarettes were clothing.

**Comment by dannno** [comment]
@TZK13 when the fuck are you fixing this heinous wrong you shit

**Comment by TZK13** [comment]
>SHHHH this is actually @TZK13 's fault but i will fix them

Pap offered to do it first, I'll do it now though considering they seem busy.
