### ISSUE TITLE
Balance Suggestion: Space Suits, Hardsuits, and Tanks

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7441]
With the recent nerf to hardsuits and the effective elimination of spacesuits, I suggest a buff to all spacefaring gear: allow spaces suits and all child items to equip large tanks in their exosuit slot, just like hardsuits were once able to do.

**Comment by Dorsisdwarf** [comment]
Hardsuits didn't get a nerf, powergaming did.

**Comment by TheWiznard** [comment]
I don't see how it's powergaming to be able to store a large tank on your hardsuit slot. Even when you could still use them on your hardsuit, everyone who has access to a hardsuit minus the armory maybe already has ext. o2 tanks; which are 100x better than a bulky tank in the first place. 

I think it would make more sense to just remove all the large bulky tanks and replace everything with extended o2 tanks, which any sane person uses anyway.

**Comment by RemieRichards** [comment]
@TheWiznard I believe the nerf being referred to is the fact you can no longer wear a Hardsuit helmet without also wearing the suit. Since wearing just the helmet was a well known powergaming technique to abuse the armour+flash protection of the helmets.

**Comment by TheWiznard** [comment]
Ah, I see then, I thought they were talking about no longer storing large tanks on hardsuits. I still don't see any reason why anyone who has access to a hardsuit (minus the brig) would be carrying around a large tank though, when pretty much everyone who has a hardsuit also has ext tanks. 

What if hardsuits worked similar to a backpack, only with one slot for your tank. It would make sense to carry around your worthless large tank if you had a place to store it securely instead of having to hold it every time you took of your suit when you're inside or something.

**Comment by Deantwo** [comment]
Put the large O2 tank on your back.

But yeah the large O2 tanks are rarely used now because people don't wanna trade it for their backpack.

**Comment by Iamgoofball** [comment]
why would you EVER ditch your backpack

ever

**Comment by Deantwo** [comment]
Jetpack comes to mind.
Defibrillator too. Even though I have yet to correct use one.
The firefighting water tank also goes on your back.

**Comment by Iamgoofball** [comment]
jetpack doubles as jetpack AND gives an air supply
defib lets you revive people from death
water tank is a 500u space lube container that sprays in a 3x3 area

large O2 tank is just a large O2 tank with no other benefits

**Comment by Deantwo** [comment]
What do you say to the NO2 Jetpack then?

**Comment by Iamgoofball** [comment]
only useful if you intend on going into space

**Comment by Dorsisdwarf** [comment]
This balance suggestion appears to have been rejected and is more than a month old. Recommending deletion @Cheridan
