### ISSUE TITLE
Husked Lizards look like husked humans

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7442]
What I expected:
Husked lizards to look like husked lizards

What actually happened:
Husked lizards have no tail and have the same head shape as humans

**Comment by Cheridan** [comment]
the tail and nose is cartilage :^)

**Comment by Miauw62** [comment]
somebody should sprite this or something

**Comment by RemieRichards** [comment]
if this is wanted we should remove the Husk icon state, and replace it with a greyscale to well, grey, plus an overlay of the dark red blood stuff on the Husk icon state.

**Comment by phil235** [comment]
Someone fixed this and forgot to mention the issue number.
