### ISSUE TITLE
ERT Spawn with the same name

### ISSUE THREAD

**Issue by GrayRachnid** [tgstation/-tg-station#7446]
Ling meta rejoice.

**Comment by Cheridan** [comment]
Huh?

**Comment by GrayRachnid** [comment]
When creating an ert using the create antagonist menu, they spawn with the same name that they had. Making it kind of weird when they encounter themselves(lings).

**Comment by Steelpoint** [comment]
I had the ERT use their default names because it made sense.

Though I suppose it might be awkward if you find your own corpse.

**Comment by Miauw62** [comment]
@tgstation/commit-access no idea what to tag this

**Comment by Dorsisdwarf** [comment]
Just make them spawn as [Officer type] [random last name]. That's why we have the huge list of random names available, after all. (That and generating random names at chargen).

**Comment by paprka** [comment]
Honestly, what I'd really love, for nuke ops/ERT/ninja, is getting rid of these huge name lists that should be reserved for random name gen and mob spawning and simply allow people to choose their own name on spawn. I'd love to roleplay my own character in these roles, but that's pretty much an impossibility considering the potential for meta and stuff ruining immersions. Best to just stick with random name gen I guess.

**Comment by Steelpoint** [comment]
I think that would be fine if there is a way for admins to "ban" someone from using a custom ERT/Op/Ninja name and instead use a random name.
