### ISSUE TITLE
Volume Pumps not working

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#7448]
I got an adminhelp about a volume pump from the mixed air tank to the air loop not working. I checked the vars, but nothing seemed wrong. Air didn't transfer, though, and the cyan pipes stayed at 101 kPa, although air was flowing out of the mixed air tank fine.
![2015-01-30 18_00_31-sybil_ beard tomb ten](https://cloud.githubusercontent.com/assets/3975713/5979680/215bfaae-a8aa-11e4-8b37-e8e57aca1df4.png)

He also used the RPED to construct the volume pump.

**Comment by Menshin** [comment]
May be runtime related, did you checked if any ?

**Comment by Miauw62** [comment]
Nope.
Op 30-jan.-2015 21:23 schreef "Menshin" <notifications@github.com>:

**Comment by kingofkosmos** [comment]
I was the guy who adminhelped, tried this again today, everything works perfectly now. Can't reproduce the bug.

**Comment by Miauw62** [comment]
pipeatmos a shit

**Comment by Actionb** [comment]
I've run into this plenty of times. Just messing around with the broken pipes and pumps (replacing them, or adding something to them) usually fixes it.

**Comment by Menshin** [comment]
Do you have any steps for reproducing it or does it happens at random ?

**Comment by kingofkosmos** [comment]
I used the Rapid Pipe Dispenser. Make a volume pipe already rotated correctly, switch default pump off, wrench it out, wrench the volume pump in. I did that first to the pump below Miauw's character, then to Air to Distro -pump. After noticing that the meter values weren't changing, I checked the cyan pipes and adminhelped.

**Comment by ZergRush000** [comment]
I had this happen yesterday, maybe it's caused by a series of volume pumps? I had a set connected up to an air filter, nothing went through.

**Comment by Menshin** [comment]
It's fixed (the air contained inside non-pipe atmos devices was not initialized on construction, so volume pumps were failing to see if there was enough pressure in input), the PR will be up the week.

Thanks for reporting.
