### ISSUE TITLE
Polyacid blob is incredibly OP.

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7458]
A blob that literally melts all your shit instantly is incredibly OP against the crew and basically fucks the whole station over. That's one reagent that never should've been used by the blob. I saw an entire squad of security get their shit kicked in a matter of seconds.

**Comment by dannno** [comment]
who thought this was a good idea
what

**Comment by mikecari** [comment]
Goofball of course you silly :^)

**Comment by ike709** [comment]
@Iamgoofball calm down satan

**Comment by Iamgoofball** [comment]
i have the best ideas

**Comment by Tenebrosity** [comment]
I prompted this :^)

And I'm a terrible blob, I died

**Comment by Actionb** [comment]
Maybe make pacid blob more volunerable to something? Deny it blobbernauts?
I don't want it removed. It's such fun seeing a bunch of retards attacking a pacid blob in melee ('The X-ray Laser Gun melts away!').

**Comment by Tenebrosity** [comment]
Goofball has a nerf PR up but a unique weakness would be interesting.


I know very little about chemistry, but I remember from high school that bases neutralise acids. Maybe the blob could be weak to reagents that would make sense as bases? If I remember correctly, bases are viscous, so something like space lube might work.





Just a thought.

**Comment by Steelpoint** [comment]
I played as a Pacid Blob a week ago.

Its insanely overpowerd in my opinion, a single hit on anyone would melt their weapon and external armour, the second would leave them naked, the third usually crits them

Its fun, don't get me wrong, but it should be nerfed or removed.

**Comment by bgobandit** [comment]
It's not OP, people just don't know to use solely ranged weapons against them yet.

**Comment by Steelpoint** [comment]
Not really though, if you use the hot keys you can very rapidly catch up to a person and attack them before they've got a chance to see what's going on.

People are used to Blobs being slow to move, so when one rare Blob player who knows the hotkeys is able to rapidly expand to them, it can be devastating.
