### ISSUE TITLE
Library Computers cause massive lag when used

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7459]
Admins have to delete it every round now to spare us the 2012 SS13 experience

**Comment by ike709** [comment]
@phil235 was the last person to do something to library comps I believe.

**Comment by Chocobro** [comment]
i've only experienced lag when going to the book database - maybe it's because it has to load over 2000 titles?

**Comment by phil235** [comment]
yep, the lag is due to the book database being loaded every time you access it. tkdrg had made a PR to only load it once but it was't merged.

**Comment by mikecari** [comment]
Is this fixed yet? Librarian is useless otheriwise ;_;.

**Comment by phil235** [comment]
Someone could try to salvage #6555 to reduce how often the database is reloaded.
