### ISSUE TITLE
Invisible mob, slime, non-existent body, med-hud scanner.

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#7460]
An extremely odd case.  
A player adminhelped about how this HoS's sprite was messed up.  However, when I jumped to the player and right click and alt click the tile, there was no body for me to interface with, it did not exist on my screen.  However, he started stripping the body and the items off the body would randomly appear on the floor as he stripped the body.  The player who was once the HoS was a slime at the time through means I am not aware of so the body did not appear in the player panel list because the ckey was associated with a slime.  The body did however appear in the ghost follow panel and would bring you to said invisible body.  The player said they could only interact with the body wearing a medical HUD.  Other players reported randomly turning into slimes this round as well.

The player later reported the items off the HoS's body were dissapearing and clipping or acting as if they were in a head slot or item slot.  The player reported this happened to another player, our host who randomly turned into a slime as well and his body bugged out the same way.  Both players in question has a virus of some sort so it seems to be related to that.

What the hell..

Edit: This indeed does seem to come from a disease that comes from end tier slimes.  Slime transformation?

**Comment by Boggart** [comment]
Sounds like transformations (at least the slime one) are still bugging out.

**Comment by Incoming5643** [comment]
just to clear this up: I had spiked the stations food with slime mutagen, so that's why people were turning into slimes. It's not part of the bug beyond the fact that transformation illness are leaving the old mob intact.

**Comment by Razharas** [comment]
I never touched slime transform proc, no idea why is it happening
