### ISSUE TITLE
Request: Less clutter on the HUD

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#7467]
There's quite a lot information on the screen all the time, when it could be there only when needed.

It would be nice if we had the same basic principle on all HUD status-icons like we do with temperature or pressure: there's no "Temperature: nominal" -icon at all. And this is logical - in real life if the air temperature is fine, you don't notice it. Only when there's a problem (air temperature too high, damage taken to body, you're getting hungry) you notice it, and then an icon appears on the screen.

Second suggestion is that the big red X next to backpack/belt-inventory could be removed, and a new mechanic added that the inventory would be closed by clicking on the backpack again. Simple and intuitive.

Why: My hypothesis is that less clutter --> more immersions --> encouraging more roleplaying. ...Also it pleases my eye. If you guys think that this HUD would not be suited as the default view, it would be awesome to have it at least as one of the HUD-modes through F12.

First picture here is the current HUD for reference:
![normalhud](https://cloud.githubusercontent.com/assets/5420151/5987792/67e6cee2-a948-11e4-8e29-22963e239ed5.png)

Second pic is the HUD I'm suggesting when everything's nominal:
![lessclutterhud](https://cloud.githubusercontent.com/assets/5420151/5987793/685b90c4-a948-11e4-89cf-2c62746fa830.png)

Final picture is the suggestion HUD but you're starting to get hungry:
![lessclutterhudhungry](https://cloud.githubusercontent.com/assets/5420151/5987812/6d28611c-a949-11e4-9f1c-6752db3a568f.png)

**Comment by Razharas** [comment]
Maybe when we will have actual modular HUD
One day, the man can dream

**Comment by Deantwo** [comment]
Maybe the internals icon should only be visibe when wearing a mask.

**Comment by RemieRichards** [comment]
I actually disagree entirely.

On the removal of the big X, nothing is more intuitive for "This will close something" than a big X, hence why every (sane) program on any computer closes itself with an X of some form.
You cannot really argue that the removal of the health icons would be better, because my god, No, it would not be. That is vital information you need to see all the time.
Temperature and hunger are lesser information, hence why they aren't constantly on screen.

Placing all of this in the F12 HUD option? Yeah sure, that's 100% fine, if this is more pleasing to your eye.
Making this the default? No, no thank you.

The only issue with our HUD at the moment that I see is that inventory item boxes (the ones with the big X) are not in line with every other box on the screen, which goes completely against the Gestalt law of Proximity, the potential issue with that is they'd take up a few more pixels on each edge, but this is a removal piece of the UI so it's never a permanent screen blockage.

**Comment by Deantwo** [comment]
While you are talking about containers Remie, the number of boxes are also weird when there are more than 7.
The second row appear only once you add the 8th item, and it shows a full row even though not the whole row is accessible.

**Comment by RemieRichards** [comment]
That's true actually yeah, that's an issue too.

**Comment by paprka** [comment]
i agree with the backpack thing and might do it alter since it's relatively easy

**Comment by Deantwo** [comment]
I do like having a close button for your currently open container though. Aka the big red X.
I use it especially when I am storing through a lot of containers that are laying on the floor.

**Comment by paprka** [comment]
yeah fair enough it'd be hard to click those again compared to just your backpack.

**Comment by Deantwo** [comment]
Maybe the red X could be replaced with an image of the container you are looking in with the red X over it?
That way you will actually know which freaking container your looking in.

**Comment by paprka** [comment]
true, that would be pretty okay

**Comment by kingofkosmos** [comment]
RemieRichards: "Temperature and hunger are lesser information, hence why they aren't constantly on screen."

Incorrect, hunger currently is constantly shown on the screen, that's why I talked about consistency between these status-icons.

So which is vital information and which is not? I suggest bringing all info to the same level of importance which would ease the gameplay because less icons in the way of seeing things and perhaps envoke more reactive actions from players (e.g. suddenly seeing the health doll pointing out the "pain" which is usually not there at all, seeking treatment faster), right now it's not uncommon for minor injuries to go completely unnoticed.

**Comment by Deantwo** [comment]
Can't this be a user option somehow?
So players can chose to have the icons disappear when "EVERYTHING IS OK"?

**Comment by RemieRichards** [comment]
@kingofkosmos I was pretty sure hunger disappeared when not relevant (maybe it used to?) Either way, it's lesser information, your idea of bringing everything to the same level of importance should only ever go one way, and that's displaying ALL of them, as opposed to not displaying any of them.

**Comment by Deantwo** [comment]
I know when I played last year, the hunger indicator disappeared yeah.
Now it just becomes a little transparent when it is of no concern.

**Comment by paprka** [comment]
It's kind of important now that blue hunger can speed you up, but whatever

I'd prefer a 'minimalist hud' option with all the side things completely removed when at their nominal status (blue/green health, no mask equipped, no damage)

**Comment by phil235** [comment]
If the transparent hunger icon are removed, we'll need to add additional feedback either when examining yourself or by sending more messages to the player when reaching specific hunger levels.

**Comment by Dorsisdwarf** [comment]
Not really, no. The alert would come from "Oh look the food indicator popped up, time to grab chow"
