### ISSUE TITLE
Nuke toys are easily spammable

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7470]
You can spam click them and burst the ears of anyone nearby. 

Please put a cooldown on it.

**Comment by MMMiracles** [comment]
The fake nuke has a cooldown, odds are you just met someone who had multiple nukes.

**Comment by Ahammer18** [comment]
Yeah, there really is no limit to how many nukes one can acquire, they probably had a pack full of them.

**Comment by Razharas** [comment]
They already have cooldown

**Comment by phil235** [comment]
I'm closing this, the real issue here was the bug with orion trail arcade that gave loads of prizes. With it being fixed I doubt we'll  still people with 2 nuke toys often in the future
