### ISSUE TITLE
ERT security hardsuit sprite is incredibly similar to nukeops hardsuit

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7472]
a round just ended on sybil because everyone was screaming about nukeops.
unless you stop and actually examine an ERT member in this hardsuit, you won't know that it's an ERT instead of syndies.

shoutouts to ikarrus.

**Comment by xxalpha** [comment]
Why aren't they blue?

**Comment by dannno** [comment]
They really aren't similar at all IMO though
Like not even anything beyond the color red being used is really that similar
Sounds like people just need to adjust

**Comment by xxalpha** [comment]
Why aren't they blue though? It's nanotrasen.

**Comment by RemieRichards** [comment]
@xxalpha blue is already used for the medical ERT officer, each member has a different colour based on their ERT Job.

**Comment by xxalpha** [comment]
I don't see what the problem is then.

**Comment by RemieRichards** [comment]
Neither do I tbh, I can imagine mistaking an ERT suit for the syndicate space suits (Read SPACE, not Hard suit) but I don't even know if they can occur naturally anymore, I know the big bright red ones can be found in some places, but not the Black+Red, Black+Orange etc.

**Comment by TZK13** [comment]
The medical ERT officers are white, it's the command ERT officer that's blue.

**Comment by RemieRichards** [comment]
Eh only ERT I've seen was the other day and our medical officer wore blue so, Idk.

**Comment by dannno** [comment]
this is a non issue tbvqh

**Comment by paprka** [comment]
I don't really mind but it's a legit complaint. It looks pretty similar, but then again, so does the sec hardsuit.

**Comment by Steelpoint** [comment]
Not pinging me about Ararat issues...

Commanders wear Blue
Medical Officers wear White

I think this is a non issue though, we can't stop people from being idiots.

**Comment by Chocobro** [comment]
great I sure can't wait for the millions of shortened rounds from "nukeops" that are just ert

**Comment by Steelpoint** [comment]
Its like saying Security hardsuits should be removed for looking like Nuke Op hardsuits.

The ERT are still a very new thing in the game, so its naturally going to take time for people to get accumulated to them. Also I would hope that there being five other non-red armoured people would help give the impression that they are not Nuke Ops.
