### ISSUE TITLE
Objects dir var refactor

### ISSUE THREAD

**Issue by AndroidSFV** [tgstation/-tg-station#7473]
The issue reported in #7450 (along with it's predecessors) is likely caused by objects having their dir var being anything other than 2 (SOUTH), and not having a specific sprite for that direction. The proc, getFlatIcon(), is not able to handle these instances, and then return a null image. As I see it, there are two potential ways of resolving this:

1) Refactor getFlatIcon to handle these cases.

2) Refactor object dir to a constant for objects that do not have multiple sprites for multiple directions, then have it be not constant for ones that do.

**Comment by AndroidSFV** [comment]
I went with option 3, adding a var to /atom/ if it is an atom that would have multiple sprites for each direction (1), or would not (0).

**Comment by Dorsisdwarf** [comment]
@AndroidSFV You still around?

**Comment by AndroidSFV** [comment]
Hello?

**Comment by Dorsisdwarf** [comment]
Hey, are you still working on a fix for this? I didn't want to close it (even if it's technically not the sort of thing the issue tracker is for) without your permission

**Comment by AndroidSFV** [comment]
No, the best fix for this would be from the beyond devs. Any fix I can think of that we can implement would be clunky and very hard to maintain

**Comment by Dorsisdwarf** [comment]
In that case I'll close it and be vaguely sad.
