### ISSUE TITLE
Wish granter isn't granting wishes

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#7475]
Tried spawning one in for a player event today and it... well, doesn't do anything. I tested one out and clicking on it flashed the screen for a tick, but had no actual effect.

Repro:
* Spawn beacon
* Make yourself meat
* Touch it

Expected: Either it traitors you or gibs you
Actual: It doesn't

**Comment by RemieRichards** [comment]
I assume you mean the Wish Granter and not the Dark Wish Granter?

**Comment by TheVekter** [comment]
Well, both of them, but I'm not 100% on what the Dark one is intended to do. Neither of them do anything right now.

**Comment by RemieRichards** [comment]
I only ask because I'm pretty sure the code for the regular and dark versions are just massive copy pastes of each other, so one being broken doesn't necessarily mean the other is, but you've just stated both are fucked, which is good to know.

**Comment by Shadowlight213** [comment]
Currently dark wish granter works, other one doesn't.

**Comment by Anonus** [comment]
The dark and regular wish granted are supposed to do different things, the regular should just make you a lasereyed tk coldres xray hulk with 'murder everyone'

**Comment by MrStonedOne** [comment]
This refers to the syndicate beacon, not the wish granter.

This is broken because it attempts to read tator info incorrectly

**Comment by Shadowlight213** [comment]
Odd. I've used the beacon and it worked fine for me.
