### ISSUE TITLE
People with any implant can fire syndicate and loyalty pinned guns

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#7478]
Problem Description: Security officers can use syndicate guns

What did you expect to happen: A sec officer would be unable to use a nuke op's gun since it is locked to a authentication implant.

What happened instead: The security officer was able to fire the gun.

Why is this bad/What are the consequences: This completely screws over nuke ops and makes it so if they get stun cuffed, they basically give all their gear to the crew.

Steps to reproduce the problem: Spawn in a nuke op gun, spawn in a sec officer. pick up the gun as the officer and proceed to fire it with no problem.

Server: Sybil and test server

Revision: 46f588b424aa963a6401c5318b33fea66e2f76be  and c09bd7707b064b4a9bb79063de7801b6af221f95 

Possibly related stuff : players with no implant cannot fire the gun.

**Comment by ike709** [comment]
@Cheridan

**Comment by palpatine213** [comment]
upon further testing, it seems that just having an implant allows both syndie pin and loyalty pin guns to be fired. regardless of if it is loyalty or syndi.
