### ISSUE TITLE
Omnizine over dose

### ISSUE THREAD

**Issue by delaron** [tgstation/-tg-station#7481]
per the wiki: Omnizine : Heals 1 of each damage type a tick, no side effects or restrictions. Found in Ambrosia Deus.

Thus why is it possible to over dose to death quickly from this? Either update code or wiki. Also this is a request for documented over dose mechanics. Doctors and Chemists should understand this but it is not documented properly anywhere.

**Comment by Iamgoofball** [comment]
Wiki might as well be written on stone tablets by now, i'm looking into it

**Comment by Deantwo** [comment]
I updated some of the wiki with the new chemicals over the last week.
Most of all the [Guide_to_medicine](https://tgstation13.org/wiki/Guide_to_medicine) page.
I was thinking of adding overdose as an *illness* on that page and list all drugs that can overdose you, but I don't know which can and can't overdose.

Side note, [Kosmos](https://tgstation13.org/wiki/User:Kosmos) and I are working on redoing the [Guide_to_chemistry](https://tgstation13.org/wiki/Guide_to_chemistry) page.
Thinking of adding a type of flags to them, for example "React on mixing", "Overdose-able", etc.

**Comment by delaron** [comment]
That would totally work. If you need help i was data mining in the code and
took notes on the overdose thresholds.

I kinda think there should more chems that you can OD on. There is only 2
or 3 at the moment.

Search "overdose_threshold"

ooc
Nicholas Russell
US2002076354

**Comment by Deantwo** [comment]
Thank you, I will put that to good work over the week.

**Comment by AlexCrimson** [comment]
As ive said several times on the forums, the Chemistry page on the wiki is a mess. Half the chemicals are not listed alphabetically, Space Drugs and Mindbreaker are not listed under "Narcotics" and it does not list Overdose limits or Metabolism Rates.

**Comment by Deantwo** [comment]
Read what I wroute above and/or help fix it.

**Comment by AlexCrimson** [comment]
If i knew how to fix it then i wouldve done it last week when i pointed it out on the forums.

**Comment by Pennwick** [comment]
Here's the overdosing chems if you still need them:

Omnizine: 30u (Really deadly)
Salicyclic Acid 25u
Ephedrine 45u (Addiction at 30u)
Morphine 30u (Addiction at 25u)
Atropine 35u
Epinephrine 30u
Nicotine 35u (Addiction at 30u, not sure its achievable with normal cig use)
Crank 20u (Addiction at 10u, also really deadly)
Krokodil 20u (Addicted at 15u, addiction is what causes skin and bones minus skin)
Histamine 30u (This is what makes Histamines dangerous)

**Comment by Deantwo** [comment]
Thank you! Yeah I hadn't gotten around to working much on that today.
I added your list to then wiki really quickly, they are messy and need to be listed better maybe, but at least the info is there for the wiki users to use too.
