### ISSUE TITLE
Duel blades don't block xeno pounces.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7483]
Alright so you got this scaly purple motherfucker throwing babymakers left and right infecting everyone, all hope is lost. Then, in the darkness, a shining beacon of hope emerges, a traitor willing to risk it all to save the station, using majority of their TCs on a duel blade to go all darth-maul on these motherfuckers.

Then hes pounced by a single hunter and instantly shredded with no remorse.

Honestly this makes no sense to me. Maybe its just me, but when I imagine the duel blade combo, I see someone that can essentially create windmill of deadly laser beams in front of them, which is more or less why they're capable of reflecting most projectiles. You'd think having a xeno trying to run headfirst into spinning energy blades of doom would probably be pretty dumb, right?

I feel like this is enough of a rare case that you'd manage access to a duel blade with a xeno infestation going on that it'd easily balance itself out. People can still disarm duel blades out of your hand so a xeno could too, I just think its pretty stupid a xeno can go headfirst into the windmill of death and come out just fine with no repercussions. 

Essentially, make duel blades block pouncing like riot shields, maybe add a little extra brute/burn damage to let the xeno know that jumping into a hot beam of energy isn't the smartest idea.

**Comment by paprka** [comment]
Put this in the minor ideas thread or something.

**Comment by WJohn** [comment]
I don't think anything in the game aside from being a hulk or in a mech will protect your from a hunter pounce. It's one of the most powerful stunning abilities in the game.

**Comment by paprka** [comment]
which is terrible

**Comment by WJohn** [comment]
At least it got nerfed recently to only be usable against one guy, it's still pretty great as a first move in a fight, even against groups.

**Comment by MMMiracles** [comment]
As a note, I did test it on a local server, and riot shields do actually block pounces 100% of the time.

**Comment by WJohn** [comment]
Hm, I don't recall them being able to do that when it was first added. It might have been added in the nerf?

**Comment by Razharas** [comment]
Dual blades only block energy projectiles
Last time i checked aliens arent make of pure energy, so feature request it is

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
