### ISSUE TITLE
round-start salicyclic acid pills are over the OD threshold

### ISSUE THREAD

**Issue by babinsquared** [tgstation/-tg-station#7493]
The pills of salicyclic acid which are inside medkits at the start of the round. They contain 50u of salicyclic acid.
The OD threshold for sali-acid is 25.

If you eat just one pill, it will hurt you. This is probably unintentional.

I've verified this by grinding the pills (produces 50u) and by popping a single pill and scanning myself to observe the rising brute damage.

On a tangentially-related note, fire first aid kits contain these pills when they probably shouldn't, given that sali-acid heals brute and not burn.

**Comment by ike709** [comment]
@Iamgoofball fix zee bugs!

**Comment by Deantwo** [comment]
Add this to the [Goofball, Fix Your Shit](https://github.com/tgstation/-tg-station/milestones/Goofball,%20Fix%20Your%20Shit) Milestone?
