### ISSUE TITLE
Balance request: simplify Oculine's recipe

### ISSUE THREAD

**Issue by babinsquared** [tgstation/-tg-station#7497]
Has anyone tried to mix oculine? It's bad. Just bad. This is the sort of recipe I'd expect for a secret goonchem, not something you can get from grinding carrots.

Oculine requires atropine, spaceacillin, and saline-glucose solution.

Atropine takes five different chemicals, of which three of them are themselves mixed (phenol, acetone, diethylamine), of which two contain oil which must itself be mixed (phenol and acetone).

Spaceacillin takes two chemicals. Epinephrine itself is a chore to mix, again requiring phenol, acetone and diethylamine. It also takes cryptobiolin, another mixed drug. On a side note, tgstation wiki has spaceacillin's recipe wrong, but that's a wiki problem.

Saline-glucose solution is easy enough to make in large amounts, but it's just yet another mixed drug on top of the others.

The recipe is laughably complex and cumbersome. Using just 5u of the basic chems whenever possible, you still have to repeatedly filter excess chems out of your beaker just to make the atropine and spaceacillin fit in the beaker. It's a lot of moving the beaker back and forth between different machines, organizing all the different chems involved.

All this effort will produce a very large supply of eye medication. It's large because you have to use so many chemicals to make it. How many people come by asking for eye meds? Not nearly enough to be worth it. You'll end the round with 90% of the medicine wasted, almost every time. I suppose you could mix only part of it and use the spare atropine to... I don't know. Nobody uses atropine. The odds are low of a med doctor even knowing what atropine is for in the first place, and it's almost always better to use the (several times buffed) basic standby chems like salglu, styptic, and silversulf. Mix in some perfluorodecalin and synthflesh if you want a super get-out-of-crit-fast patch. If they're near medbay, put them in cryo. Leftover spaceacillin and cryptobiolin are similarly unlikely to serve any purpose in most rounds. Crypto in particular is otherwise only useful for antags, and there are a dozen better options for that.

For comparison, ear medicine is simply charcoal+carbon+water. Charcoal kind of takes time, but it doesn't involve juggling beakers full of six different chemicals for two of its three components. You also have a bunch of charcoal easily available from round start. Brain damage is even easier to fix, which is a good thing because trying to make oculine will fry your head. The pre-goonchem recipe for eye damage was piss easy, as well.

**Comment by Deantwo** [comment]
Agreed.

**Comment by Iamgoofball** [comment]
you got a recipe suggestion? because I'll add it

**Comment by babinsquared** [comment]
Pre-goon recipe was anti-toxin, carbon, hydrogen. It doesn't have to be the same recipe with charcoal replacing anti-tox, but it sounds decent. It doesn't even have to be extremely simple - just simpler than what it is right now, because right now it takes way too many steps for such a narrow and situational drug.

**Comment by scrdest** [comment]
Oil instead of antitox, perhaps? The stuff that's good for eyes in carrots IRL is a fatty acid, so oil would make sense.

**Comment by pudl** [comment]
there's a fuck ton of oculine pills in vendors. the reason the recipe's hard on goon is because they have a shit ton of oculine pills and a shit ton of goggles that fix eyesight (we dont have them)
so basically on goon if you manage to have to MIX oculine, you fucked up and deserve shit.

**Comment by Deantwo** [comment]
We have a box full of [Prescription Glasses](https://tgstation13.org/wiki/Prescription_glasses#Prescription_Glasses) in the medical storage.
Never seen them used though.

Anyway, it seems that peoples biggest complaint about the new chemistry changes is that it is copying GoonStation, so making our own recipe sounds like a good idea.

**Comment by pudl** [comment]
fuck off

**Comment by Deantwo** [comment]
What.

**Comment by paprka** [comment]
@pudl did at any point of typing that the thought of 'this might be stupid' pop into your head

just trying to gauge whether or not you operate under common sense and realize what shit game sense goon coders tend to have.

oculine being readily available but extremely hard to produce is really quite shit.

Here's my suggestion for a rebalance:

1) stop thinking about what goon does, they are not our medical system, and the more things you shove in from goon like roundstart eye fix pills the more you fuck over our system even further
2) remove roundstart oculine pills because this completely defeats the purpose of eye surgery if there are no chemists to make the chemical
3) make oculine require 1 mixed chemical, and 2 readily available chemicals, or perhaps plasma as a catalyst considering it's a magic eye damage fix chemical

mission accomplished

**Comment by Deantwo** [comment]
So, as suggested, change it to charcoal+carbon+hydrogen for now? Don't know if it will conflict with anything else.

**Comment by Iamgoofball** [comment]
@paprka can you clean up the nanovend stuff, i have no idea what the hell happened there and I gotta focus on chemistry itself right now

**Comment by Iamgoofball** [comment]
@Deantwo that works
