### ISSUE TITLE
Filters can't start on in away missions.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7499]
Even though I set them as "on" in the map maker, these two filters do not start on (though you can turn them on in game) meaning that gasses just sorta sit in the pipes should there ever be a toxins leak instead of being filtered out.

http://i.imgur.com/AiAK6Qp.png

**Comment by Menshin** [comment]
Don't worry, it's still on my _to-fix_ list

**Comment by Deantwo** [comment]
I was playing CE today on Badger and noticed that the filters were off when I walked into atmos.
So maybe it is all filters?
