### ISSUE TITLE
RIG suit helms can be taken off and left.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7506]
1. Put on RIG suit.
2. Toggle helm
3. Take off helm, drop/throw it aside
4. Walk halfway across the station and amaze people with your ability to make the helm vanish and reappear on your head.

**Comment by dannno** [comment]
@paprika

**Comment by paprka** [comment]
Whaaat, those are supposed to have the NODROP flag.

Can you be more specific?

**Comment by MMMiracles** [comment]
The mining hardsuits are all I tested with this so far and they did it. I'm also pretty sure its possible to still apply goliath plates to helm, so unless the helm saves the upgrade its probably a waste.

**Comment by paprka** [comment]
Yeah the helmet saves the upgrade because when you 'disengage' the helmet, it just gets stored inside the suit.

**Comment by MMMiracles** [comment]
also for all that is holy add a delay to equipping the helm because right now you can spam it for the noise.

**Comment by paprka** [comment]
you can spam a lot of things for the noise

maybe when someone cooks up an animation i can have a delay for equipping while the cool ded spess animation plays and stuff, we'll see

**Comment by dannno** [comment]
a little unrelated but why don't the EVA suits get this cool featurrrrrreeeeeee whyyyyy my dreaaaaaamsssss

**Comment by paprka** [comment]
because they're more traditional space suits i guess? not super high tech like engineering ones? idk

**Comment by dannno** [comment]
p-please

**Comment by Yakk** [comment]
they look more like hardsuits than not hardsuits tbvh

also it would be balance
you like balance dont you?

**Comment by paprka** [comment]
It doesn't really matter since eva helmets aren't really good for powergaming anyway

**Comment by Yakk** [comment]
they block facehuggers, keep bible thumping from making you retarded, and protect your eyes when welding

**Comment by paprka** [comment]
I removed that last one I'm pretty sure
