### ISSUE TITLE
Xeno bursting time is now insanely fast and two larvae are bursting from one body seemingly at random

### ISSUE THREAD

**Issue by TZK13** [tgstation/-tg-station#7508]
A xeno round just happened on Sibyl where everybody was bursting insanely fast, like less than half the time it used to take. Also two larvae burst from my body and somebody else mentioned the same thing happening to them too in deadchat but other bursted bodies only produced one larva. Both of these combined obviously make the xenos far more OP than even they're supposed to be.

**Comment by WJohn** [comment]
Oh look the xenos figured out how to be more efficient with their hosts.

Good for them.

**Comment by Cheridan** [comment]
It's likely a ticker issue from the new MC

**Comment by phil235** [comment]
Confirmed. Less than 2 minutes from facehugging to bursting.
