### ISSUE TITLE
Admin Request: Don't remove the objectives from an antag when de-antag'd

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7516]
It used to be that making someone not an antag anymore via the TP panel preserved the objectives.
Nowadays, it wipes them.

Preserving the objectives is very important as it allows admins to debug and play around with the antag settings a bit without having to worry or remember what that antag's objectives were.

Automatically wiping them actually makes it more inconvenient for us. Please preserve them.

**Comment by RemieRichards** [comment]
This should instead be a separate button I feel. 9/10 you'll want the objectives gone too.

**Comment by Ikarrus** [comment]
A separate button would be great. But it's not like it's hard to remove all the objectives yourself, either.
