### ISSUE TITLE
Goliaths can use their tentacle attack on space tiles

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7523]
Nope.avi

**Comment by Chocobro** [comment]
i already hated goliaths enough
now space is no protection from their tendrils

**Comment by paprka** [comment]
Monsters really shouldn't even venture into space and retreat if you scuttle away, this 'relentless pursue' shit is absolutely terrible imo. I know it would be easy mode to shoot with a KA, retreat, etc, but if the monsters regenerated health while out of combat, it'd force you into fight one battle with them instead of whittling their health down like a big pussy.

**Comment by Firecage** [comment]
>Be on the asteroid. The exact same conditions as in space due to no atmosphere and stuff. It can't venture into space.

**Comment by paprka** [comment]
Why would a monster chase a miner when it's obviously acting in defense of its own turf, this is like basic behavioral patterns for animals and it seems stupid for a mob to not act in defense and simply worry about getting the threatening miner the fuck away from its little cave instead of chasing it down with this crazy never ending bloodlust

It's pretty lame gameplay too, if you want to get out of the fight you should be able to retreat and not have the monster follow you endlessly unless you get far enough off screen. That's just boring and unfun, you should be able to try and tackle the monsters over and over and retreat if you're losing the fight instead of fucking dying.

**Comment by AlexanderUlanH** [comment]
>endlessly unless...

I don't get your point.  They stop following you if you get far enough away.  And doesn't the new 'hives' thing mean monsters will return to the asteroid once they've lost you?
It's really not hard to escape a goliath.

**Comment by paprka** [comment]
Unless you're in space and drifting and the tentacles magically reach out and knock you over. See: the spine that runs up the middle of the asteroid. If a goliath chases you out there you're fucked. if you're even a little damaged good luck outrunning a goliath or hivelord. Good luck trying to escape from a fight you're losing without getting completely boned because you can't get out of the way of goliath tentacles because the goliath is infinitely chasing you and using its 100 tile ranged tentacles to knock you over which you can't avoid because you're in a cave and there's no safe tile to move to.

Good gameplay, 10/10

**Comment by TZK13** [comment]
The new "nests" thing wasn't merged Alexander, Sawu closed that PR.

**Comment by paprka** [comment]
end of days.
