### ISSUE TITLE
The AI can use binary chat when its APC is disabled

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7531]
Serious balance issue. Completely fucks over OPs who try to take it out. Please remove.

**Comment by kevinz000** [comment]
Well.. Binary does work no matter what unelss your battery is ded.
 Across zlevels.

**Comment by Jalleo** [comment]
It always worked with APC off while your integrity (internal battery is online)

**Comment by RemieRichards** [comment]
As has been stated, Binary works off of the internal cell of the AI.

**Comment by paprka** [comment]
why did you close this even

**Comment by RemieRichards** [comment]
I gave my reasoning in the comment in which I hit "close and comment", you'll see it as the one right above the icon stating I closed this.

**Comment by paprka** [comment]
this is still a major balance issue, though???

**Comment by RemieRichards** [comment]
Not every strategy has to be 100% effective. If you've disabled the AI APC and are complaining that hasn't done anything, you can just go ahead and kill the AI. I have never seen or heard of an OP Squad choosing to break into the AI's chamber, only to break it's APC instead of killing it.

**Comment by paprka** [comment]
remie that's because you don't play the game.

You control-click the AI's APC to depower it, so it can't call for help through its radio, and then kill it. 

Otherwise it will just scream OPS as soon as it hears your guns, esword, or starts taking damage. 99% of the time it will call ops before it dies.

Now, it can just scream OPS!! over borg chat. I admit the AI is pretty much defenseless against this strategy outside of yelling OPS!, but this is literally the ONLY way an AI can get killed this fast before it can call for help, barring a really accurate bombing. If there was a way to disable the AI's ability to use borg chat, via EMPing or something, that would be nice too. But consider balance issues more closely before closing them please.

**Comment by RemieRichards** [comment]
>I don't play the game.

Ask Basil. Ask the Basilmins. You're entire argument is worth squat to me now, and I won't even read it, you started off on a REALLY bad footing there. and my point still stands, even for the cut-throat robustness of the Sybilites.
