### ISSUE TITLE
Transferring a heated chem from a heated container to an unheated container instantly cools that chem

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7534]
See title.

**Comment by Deantwo** [comment]
Expialned by the fact that temperature is saven in the beaker/reagent_holder and not in the reagents them self.
@Iamgoofball  is seemingly working on changing this already.

See: https://github.com/tgstation/-tg-station/issues/7250

**Comment by Iamgoofball** [comment]
not a bug, working as intended, i could write some fluff up about shit if you want

i fixed grenades in #7536 though

**Comment by HoaxIT** [comment]
Not a bug? So if i pour super heated shit into a roomtemp beaker, it becomes roomtemp ... wat

**Comment by Deantwo** [comment]
Seems https://github.com/tgstation/-tg-station/pull/7566 is the current planned change.

But holding a beaker with heat reagents still sound wrong to me.

**Comment by hornygranny** [comment]
dupe
