### ISSUE TITLE
Some big fat warnings in the runtime logs related to goonchem

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7542]
![ss 2015-02-03 at 10 04 13](https://cloud.githubusercontent.com/assets/7247232/6035932/80d4430c-abf1-11e4-8797-e0e91c6963a1.png)

It's probably worth noting that these happened when the server crashed but I dunno. I couldn't seem to find the source of the problem here.

@Iamgoofball 

Honestly who even knows anymore, we might just be at the proc limit. Worth noting at least, there's other examples of this happening in the runtime logs.

**Comment by Menshin** [comment]
This can only happen when the _global_ list _chemical_reagents_list_ somehow lose these two reagents.

Should never happen, except for Byond going fubar with lists (related #7410).

**Comment by Iamgoofball** [comment]
Uh, someone is feeding add_reagent() chemical names and not chem ids

**Comment by Miauw62** [comment]
I got an ahelp stating that they saw this: "person now contains x.xx units of salgluc_sol" or something like that. AKA the issue is probably sleepers

**Comment by paprka** [comment]
Yeah, I figured that was the case menshin. It's hard to debug these things because a) they look like things fucking up when in reality it's byond FUCKING THEM UP, and b) a lot of these runtimes still exist without the list corruption.

I think i've isolated the issue and solved it already, but only time will tell.

**Comment by Iamgoofball** [comment]
i fucking hate the chem ID system

**Comment by Razharas** [comment]
Yes IDs are bad

**Comment by paprka** [comment]
Dunno if this is gonna crop up again now that I've fixed most of the list corruptions and server crashing. We'll see, reopen if need be.
