### ISSUE TITLE
Hardsuit helmets missing in b1a3cde873bc26a33f009130d4cc5dfbae9420c1

### ISSUE THREAD

**Issue by feemjmeem** [tgstation/-tg-station#7550]
CE hardsuit helmet missing from storage unit in at least latest commit  b1a3cde873bc26a33f009130d4cc5dfbae9420c1

Looks like all hardsuit helmets are missing, actually.

**Comment by feemjmeem** [comment]
Engineering hardsuit helmets missing too

**Comment by feemjmeem** [comment]
Actually, it looks like all hardsuit helmets.

**Comment by Miauw62** [comment]
hardsuit helmets are no more

**Comment by dannno** [comment]
to be more clear, hardsuits now contain the helmets within them. the button that pops up at the top left when you equip a hardsuit will equip the helmet.

**Comment by Deantwo** [comment]
Read this: https://github.com/tgstation/-tg-station/pull/7346
