### ISSUE TITLE
Viruses in blood/IVs causes MC to break

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7565]
players can move, but cannot speak. this round has been 20 seconds away from landing at centcomm for about seven minutes, now.

**Comment by Miauw62** [comment]
@paprka

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by WJohn** [comment]
KNEW IT WAS YOU

(I didn't actually know if it was you)

**Comment by hornygranny** [comment]
wrong

**Comment by Chocobro** [comment]
what do you mean 'wrong'
would you like to try giving a concise reply saying why it's wrong
would you like to try giving proof to the contrary

**Comment by hornygranny** [comment]
#7563 
bleeding + viruses looped infinitely and used all the CPU, the MC dying is from something else

**Comment by Chocobro** [comment]
have we identified what that something else could be in particular?
also feature freeze when

**Comment by hornygranny** [comment]
i would bet money it's a byond issue with memory management
