### ISSUE TITLE
Rods spawned in amounts of 2 have icons of amount of 1

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#7570]
@Paprka

**Comment by Chocobro** [comment]
happens with all rods that are a stack of one or two - the sprite only shows a single one until you put a third or higher on it.

**Comment by paprka** [comment]
They should be calling update_icon() on New()

If they aren't, you're var editing the amount, either on the server or in the code that spawns the rods, which isn't really something I know how to fix

**Comment by Razharas** [comment]
Look through all code that spawns rods, fix it all, make it all work nicely
THere are no easy ways about this shit

**Comment by paprka** [comment]
Bummer okay yeah I'll just find all places rods are spawned and make some update_icon() proc calls

**Comment by Razharas** [comment]
Or just make them update on new and have new have argument for amount
In fact i wonder why isnt it like that already since its the most sensible way
