### ISSUE TITLE
You can grind up slimes and monkeys through closed windoors.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7584]
If you grab a slime with a windoor about to close on you (such that it separates you from the slime) and you try stuffing it into the slime grinder, it'll work anyway as if the slime went through the door.

I imagine this is equally bugged with rotating border windows so they would normally block you from the slime too.

**Comment by phil235** [comment]
Probably because the grinder checks the grab and the grab isn't updated beforehand.
