### ISSUE TITLE
Rods.update icon() cause runtime?

### ISSUE THREAD

**Issue by Deantwo** [tgstation/-tg-station#7585]
Fri Feb 06 16:37:43 2015
    runtime error: Cannot execute null.update icon().
    proc name: add to stacks (/obj/item/stack/proc/add_to_stacks)
      source file: stack.dm,204
      usr: Nelandra Librod (/mob/living/carbon/human)
      src: null
      call stack:
    add to stacks(Nelandra Librod (/mob/living/carbon/human))
    the metal (/obj/item/stack/sheet/metal): Topic("src=\[0x20094e4];make=13;multi...", /list (/list))
    Methelod (/client): Topic("src=\[0x20094e4];make=13;multi...", /list (/list), the metal (/obj/item/stack/sheet/metal))

@Paprka this is your new rods update proc?

**Full log:**

    *** Begin Log: Fri Feb 06 11:10:13 2015 ***
    Fri Feb 06 11:10:20 2015
    World opened on network port 2337.
    Welcome BYOND! (5.0 Beta Version 507.1266)
    Running /tg/ revision:
    2015-02-04
    b1a3cde873bc26a33f009130d4cc5dfbae9420c1
    Database connection established.
    Initialized Garbage SubSystem within 0 seconds
    Initialized Air SubSystem within 1.5 seconds
    Initialized Server Tasks SubSystem within 0 seconds
    Initialized Radio SubSystem within 0 seconds
    Initialized NanoUI SubSystem within 0 seconds
    Initialized Objects SubSystem within 0.8 seconds
    Initialized Pipenets SubSystem within 0.2 seconds
    Initialized Power SubSystem within 0.2 seconds
    Initialized Machines SubSystem within 0.7 seconds
    Initialized Bots SubSystem within 0 seconds
    Initialized Diseases SubSystem within 0 seconds
    Initialized Events SubSystem within 0 seconds
    Initialized Jobs SubSystem within 0 seconds
    Initialized Mobs SubSystem within 0 seconds
    Initialized Shuttles SubSystem within 0 seconds
    Initialized Sun SubSystem within 0 seconds
    Initialized Lighting SubSystem within 2 seconds
    Initialized pAI SubSystem within 0 seconds
    Initialized Ticker SubSystem within 0 seconds
    Initialized Vote SubSystem within 0 seconds
    Initializations complete
    Rebooted server.
    Fri Feb 06 12:40:51 2015
    Running /tg/ revision:
    2015-02-04
    b1a3cde873bc26a33f009130d4cc5dfbae9420c1
    Database connection established.
    Initialized Garbage SubSystem within 0 seconds
    Initialized Air SubSystem within 1.4 seconds
    Initialized Server Tasks SubSystem within 0 seconds
    Initialized Radio SubSystem within 0 seconds
    Initialized NanoUI SubSystem within 0 seconds
    Initialized Objects SubSystem within 0.8 seconds
    Initialized Pipenets SubSystem within 0.2 seconds
    Initialized Power SubSystem within 0.2 seconds
    Initialized Machines SubSystem within 1 seconds
    Initialized Bots SubSystem within 0 seconds
    Initialized Diseases SubSystem within 0 seconds
    Initialized Events SubSystem within 0 seconds
    Initialized Jobs SubSystem within 0 seconds
    Initialized Mobs SubSystem within 0 seconds
    Initialized Shuttles SubSystem within 0 seconds
    Initialized Sun SubSystem within 0 seconds
    Initialized Lighting SubSystem within 2 seconds
    Initialized pAI SubSystem within 0 seconds
    Initialized Ticker SubSystem within 0 seconds
    Initialized Vote SubSystem within 0 seconds
    Initializations complete
    Fri Feb 06 16:37:43 2015
    runtime error: Cannot execute null.update icon().
    proc name: add to stacks (/obj/item/stack/proc/add_to_stacks)
      source file: stack.dm,204
      usr: Nelandra Librod (/mob/living/carbon/human)
      src: null
      call stack:
    add to stacks(Nelandra Librod (/mob/living/carbon/human))
    the metal (/obj/item/stack/sheet/metal): Topic("src=\[0x20094e4];make=13;multi...", /list (/list))
    Methelod (/client): Topic("src=\[0x20094e4];make=13;multi...", /list (/list), the metal (/obj/item/stack/sheet/metal))
    send2irc("Server", "Round just started with no adm...")
    Ticker (/datum/subsystem/ticker): setup()
    Fri Feb 06 18:34:39 2015
    runtime error: Safety violation: tried to use shell()
    proc name: send2irc (/proc/send2irc)
      source file: adminhelp.dm,125
      usr: AN0n3 (/mob/new_player)
      src: null
      call stack:
    send2irc("Server", "I need a hug :( (No admins onl...")
    AN0n3 (/mob/new_player): Logout()
    AN0n3 (/mob/new_player): Logout()
    send2irc("Server", "Round just started with no adm...")
    Ticker (/datum/subsystem/ticker): setup()
    runtime error: Safety violation: tried to use shell()
    proc name: send2irc (/proc/send2irc)
      source file: adminhelp.dm,125
      usr: null
      src: null
      call stack:
    send2irc("Server", "Round just started with no adm...")
    Ticker (/datum/subsystem/ticker): setup()
    Stopped server.
    
    *** End Log: Fri Feb 06 18:35:06 2015 ***

**Comment by phil235** [comment]
I think this has been fixed by #7559

**Comment by paprka** [comment]
Bretty sure I fixed this yes
