### ISSUE TITLE
Latejoin trapped at spawn.

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7590]
A latejoin Captain spawned within the lobby screen space fully equipped and alive but obviously trapped. He had not been teleported to his spawn. He latejoined very soon after the round started.

**Comment by Miauw62** [comment]
Which map was this?

**Comment by Stickymayhem** [comment]
Boxstation. It just happened again. Two rounds in a row. Also the Captains are called cobra commander I'm not sure what that's about.

**Comment by Stickymayhem** [comment]
Also this captain was a roundstart one and the office hadn't been touched at all. At a guess I'd say the spawn is just not there

**Comment by Boredone** [comment]
Can confirm this is still happening at least every once in awhile on Sybil. Guys clothes are also renamed  to have cobra commander or commander instead of captain.

**Comment by paprka** [comment]
Pretty sure SoS did some local editing for funnies

**Comment by Cheridan** [comment]
Yeah. Because the corresponding spawn landmark was not renamed, they spawned at the fallback point in the admin prison. 

The fallback point should probably be the arrivals shuttle or something, so this doesn't happen in the future.

**Comment by Miauw62** [comment]
no, the fallback point is in the middle of the start screen.

**Comment by Dorsisdwarf** [comment]
Needs the "Blame SOS" tag, and it doesn't seem to be a bug.

**Comment by Supermichael777** [comment]
issue was admin fuckery this can be closed.

**Comment by phil235** [comment]
As cheridan said, the underlying problem is that the fallback point should be the arrival shuttle.

**Comment by Iamgoofball** [comment]
this has been fixed for months

**Comment by freerealestate** [comment]
I've always wanted to run around on the start screen.
