### ISSUE TITLE
You can wallk through a wall in the HoP's room

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7594]
![ss 2015-02-07 at 08 22 14](https://cloud.githubusercontent.com/assets/7247232/6092765/6c280da4-aea2-11e4-9de0-5c74ea55bed0.jpg)

On the east wall, towards the grav gen

**Comment by phil235** [comment]
can't reproduce. Can you give more details?

**Comment by paprka** [comment]
Are you sure? it was on the server just now. Ian walked through it and died. 8:30 pm PST

**Comment by Deantwo** [comment]
At least get the server's build version.

**Comment by paprka** [comment]
I forgot how to do that,  but I checked the current map and this wall seems fine, so yes, might have been admin fuckery

**Comment by Incoming5643** [comment]
Once in a extremely great while I'll find that that a dense turf miraculously was generated without its density, but it's like finding a four leaf clover except instead of searching through a field of green you're just ramming your face into everything until something gives out.

**Comment by RemieRichards** [comment]
@Incoming5643 the clover is red, the field is green, you are red-green colourblind.
good luck finding it.

**Comment by WJohn** [comment]
Just experienced this bug:
http://i.imgur.com/UZVbHJR.png

**Comment by phil235** [comment]
I managed to reproduce the bug consistently. It happens when a mob teleports onto the wall, making it lose its density.

**Comment by Deantwo** [comment]
And here seems to be the problem: https://github.com/tgstation/-tg-station/blob/f7659eb4e554e1f0cacee132610deccde27092e4/code/modules/admin/verbs/adminjump.dm#L161

**Comment by Miauw62** [comment]
Ah fuck, looks like I forgot resetting the density.
