### ISSUE TITLE
Genetic aide is manifesting on monkeys.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#7597]
As stated, the sprites don't match and leads to some interesting views of monkeys with giant glows around them and green people with tails who quickly turn back into monkeys.

Possibly intended.....?

**Comment by RemieRichards** [comment]
@Razharas

**Comment by Razharas** [comment]
It was fun while it lasted

**Comment by phil235** [comment]
Yet another reason to remove genetic aide.

**Comment by WJohn** [comment]
http://i.imgur.com/qhUMaCF.png

Happens with all of them, it seems! I think the proper way to fix this would be to actually let monkeys manifest powers, but with the proper sprites for it (green hulk monkeys, heat protection actually around them etc)
