### ISSUE TITLE
Beepsky is on crack at the start of the round.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7598]
For the first few destinations of the round beepsky will move at max speed and it's absolutely terrifying, then he slows down as he reaches engineering.

**Comment by RemieRichards** [comment]
gottagofast

**Comment by GunHog** [comment]
I am not yet able to determine the cause of this. I believe it is a problem with the subsystem in the MC.

**Comment by CorruptComputer** [comment]
Feature. He is trying to intimidate those criminals.

**Comment by Niknakflak** [comment]
This is hilarious.  Never fix this please

**Comment by Kraseo** [comment]
feature

**Comment by Xhuis** [comment]
:no_entry_sign: :a: :beetle:

**Comment by dannno** [comment]
This happens with monkeys too.

**Comment by phil235** [comment]
I'm not sure if this is related but I noticed that at the beginning of a round a mob's life() proc is called a whole bunch of times quickly and then goes back to normal.

**Comment by GunHog** [comment]
It is a master controller issue, then. Not just bots.

**Comment by paprka** [comment]
beginning of a round is the best time to beat everyone to death because they'll bleed like crazy

**Comment by Miauw62** [comment]
Things were getting into the processing lists multiple times, so this should be fixed?

**Comment by paprka** [comment]
i think the |= fixed it, who knows

**Comment by phil235** [comment]
I really doubt the change from .Add to |= fixed this.

**Comment by RemieRichards** [comment]
@phil235 the issue is that things were in the processing lists multiple times, increasing how fast they processed. Add() forces the element into the list, |= only adds the element to the list if it is NOT already in it, thus preventing these duplicates.

**Comment by phil235** [comment]
If beepsky being processed mroe than once caused him to move crazy fast it wouldn't stop after a couple seconds.

**Comment by RemieRichards** [comment]
Provide an alternate theory then, since this was the only change that reasonably could have caused it.

**Comment by Razharas** [comment]
At the beginning of the round delay between process calls is minimal for some reason, it then globaly stabilizes to usual
Nothing to do with multiple list entries
