### ISSUE TITLE
Engineering cyborgs metal rods are not working

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#7600]
They are either there and invisible or not there. Notice the empty gap in the inventory.
![scrnshot1](https://cloud.githubusercontent.com/assets/4951579/6093995/e22817e0-af0d-11e4-9983-70cdaad2c4a4.png)

**Comment by WJohn** [comment]
@paprika?

**Comment by paprka** [comment]
Menshin fixed it.
