### ISSUE TITLE
[Box station] Disposal grinder room is drained of oxygen

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7604]
For some reason, every time I enter the disposals room, there's no oxygen in there. There must be an airless plating or something.

**Comment by xxalpha** [comment]
Can't reproduce. Nothing is wrong with the atmos of the crusher room.

**Comment by paprka** [comment]
Did you let it rest for 10-20 minutes and see if the oxygen leaks at all?

**Comment by Durkel** [comment]
Waited twenty minutes to  test this and nothing. I think it's more likely someone left the disposal door to space open or a broken window that had been fixed.
