### ISSUE TITLE
Gulag Point console missing from gulag shuttle on Boxstation

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#7612]
It's impossible to leave without manual intervention now, fairly urgent.

**Comment by Stickymayhem** [comment]
Fairly urgent lads. Would appreciate this being fixed. @steelpoint I guess because boxstation mapping?

**Comment by MrStonedOne** [comment]
and spawning one seems to cause it to get deleted

Might be related, maybe its self deleting?

**Comment by Stickymayhem** [comment]
Can this please get fixed gulag has been broken for like a month now.

**Comment by Steelpoint** [comment]
The urgency of this being fixed directly translates to how important the Gulag is viewed.

I'll take a look at it.
