### ISSUE TITLE
Balance: Changeling Spread Infestation: faction

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7619]
just a suggestion for the "spread infestation" changeling ability: make it so the spider that are eventually generated by it have the same faction as the changeling, so they won't attack it.

Obviously, this could be used, to a very small degree, to metagame if someone is a changeling or not, but fairly niche to the point that I don't believe it would be an issue the vast majority of the time.

**Comment by WJohn** [comment]
I wonder how this should be handled. Should spiders be loyal only to the ling that made them? To all changelings? What about spiders made by changelings, and those found in random events, or in gold cores?

Personally I'd go with all changelings having both "neutral" and "changeling" factions, and all spiders made by changelings to be of the "changeling" faction.

**Comment by Lumipharon** [comment]
Currently infestation can help spread chaos. If the spiders are loyal to the ling, then it can be used to spawn a literal unstoppable army of spiders.

For example you could go in a room, weld the vent, keep spawning spiderlings, wait for them all to grow, then unleash with a hand tele or something.

**Comment by phil235** [comment]
I'm not sure I like it. Like lumipharon said, this will lead to spider armies, with lings dragging spiders behind them to guide it. It's quite a buff.

**Comment by PKPenguin321** [comment]
Pretty sure the original intention of the ability was just to cause chaos and even specifically says that once fully grown the spiders may attack their creator

**Comment by Fox-McCloud** [comment]
Perhaps a new mob could be created instead or a new type of spider---to lessen the power curve, if that's a concern.

**Comment by Stickymayhem** [comment]
Would make a badass ling test though.

CATCH ONE ALIVE. WE'LL PUT JEFFREY IN A ROOM WITH IT AND SEE WHAT HAPPENS.

**Comment by Miauw62** [comment]
>kill jeffrey

"i=it attacked me ;-;'

**Comment by Cheridan** [comment]
@Stickymayhem that was exactly why i had them attack their creators.

**Comment by Anonus** [comment]
They could just stasis if sec did that though, you know.

**Comment by MrStonedOne** [comment]
@tkdrg close, feature request, rejected on top of that.
