### ISSUE TITLE
Shotglass becomes regular glass on use

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#7625]
1. Pour drin-FINEST RUSSIAN VODKA MADE ONLY FROM BEST POTATOES AND CAPITALIST TEARS INTO SHOTGLASS

2. Drink... drink.

Your shotglass has now magically grown into a regular-sized glass. Probably did it at the pouring phase, but eh.

Shouldn't shotglasses be a small, set amount, which forces a single pouring and drinking number?

**Comment by xxalpha** [comment]
@Vekter

**Comment by Cheridan** [comment]
They are ultra hi-tech adaptive NANOGLASSES

**Comment by TheVekter** [comment]
Fffuuuck I know why it's happening. Gimme a bit and I'll look at it.

**Comment by TheVekter** [comment]
I'm pretty sure it's because it's a child of normal glasses so I must've
overlooked that it uses iconstates for whatever is poured into it instead
of just acting like a bottle/flask

I'm afk right now but I'll fix it later today.

**Comment by TheVekter** [comment]
Working on this now.

As for the "set amount", shot glasses default to 10 units, but the mob drink amount is 5. Think I should tone it down to 5 to match the idea behind it? I don't think 5 units of most booze is enough to do jack shit.
