### ISSUE TITLE
Traitor objective exclusion from jobs occasionally doesn't work

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7628]
![ss 2015-02-08 at 10 19 10](https://cloud.githubusercontent.com/assets/7247232/6101886/f1d4cc96-afe0-11e4-957b-0bb7e8d3edc7.png)

```
//Items with special checks!
datum/objective_item/steal/plasma
	name = "28 moles of plasma (full tank)"
	targetitem = /obj/item/weapon/tank
	difficulty = 3
	excludefromjob = list("Chief Engineer","Research Director","Station Engineer","Scientist","Atmospheric Technician")
```
OOC: Scones: i've gotten it as RD

It might be just the plasma objective or all objectives.

**Comment by Cheridan** [comment]
it never works

that code isn't implemented yet
