### ISSUE TITLE
Mining Asteroid produces atmos pipes

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/-tg-station#7634]
Current server version
-----
![mining atmos pipes](https://cloud.githubusercontent.com/assets/9158683/6117907/411e3d1e-b086-11e4-95af-38ed655c452b.jpg)

Sometimes when mining a vertical atmos pipe appears. For the life of me I have no idea why this happens. It also only appears to happen in a certain side of the asteroid if that makes sense; or at least I never encounter it unless I'm mining on this specific side of the asteroid. The Blue circle is where I commonly encounter this phenomenon, the yellow circle is another place I've seen it happen /once/.
![hyqmlwk](https://cloud.githubusercontent.com/assets/9158683/6117984/10a3e192-b087-11e4-8b4f-d6c8d056edf9.png)

I have no idea what causes this or how to fix it, I've looked over these areas in the map editor and haven't found random atmos pipes in the middle of the asteroid. It probably has something to do with rock tiles in general but, like I said I've only encountered this in those two areas while mining before. 

edit: also I've never found pipes inside of the pregen caves, They seem to spawn out of nowhere in the middle of rock tiles.

**Comment by RemieRichards** [comment]
I... what...

**Comment by TheWiznard** [comment]
It's been happening for a while, because I first noticed it a month or two ago, and adminhelped it but then never made an issue cause I'm dumb. I saw it this morning again and decided to leave an issue this time. I also find this hilarious and wondering how this could happen at the same time

**Comment by RemieRichards** [comment]
I'd assume Byond is recycling references.

that or someone really fucked up somewhere.

**Comment by Kraseo** [comment]
feature, atmos now needs mining to get pipe ore

**Comment by Menshin** [comment]
Sometimes, the explanation is simplier than expected...

![explain](https://cloud.githubusercontent.com/assets/7117411/6132668/6077334a-b154-11e4-9847-7d1dc667e515.PNG)

**Comment by Miauw62** [comment]
and that's why you never use text editing on the map.

**Comment by Jordie0608** [comment]
I wouldn't be surprised if this was linked to #6433
