### ISSUE TITLE
Janiborgs can delete AI Holograms

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#7636]
Original Image: http://gyazo.com/5305a49f1967bc1c4b99c15d144ea2f4
![](http://i.gyazo.com/7b32056e2362eed4b44f75f8d0d1347e.gif)

**Comment by WJohn** [comment]
That's actually pretty funny. A hologram's a hologram, right?

**Comment by optimumtact** [comment]
I can't see what is going on here?

**Comment by francinum** [comment]
@optimumtact the fact that the Holopad is active, yet there is no hologram.

**Comment by francinum** [comment]
@optimumtact Gif form

![](http://i.gyazo.com/7b32056e2362eed4b44f75f8d0d1347e.gif)

**Comment by ike709** [comment]
It is cleaning the hologram.

**Comment by optimumtact** [comment]
I might take a look tonight, thanks for taking the time to put in a gif showing the issue :+1:

**Comment by optimumtact** [comment]
Both the mop and the janiborg also qdel effect/overlays/ which suprise suprise, the AI hologram is.

Potential fixes include modifying the AI hologram path, or doing something better with a can_clean(TYPE) or a clean() method on overlays and decal cleanables

**Comment by WJohn** [comment]
Oh, I thought the janiborg had the holo-signs and they could delete the AI's holo with that (which should totally be a feature). This is actually more of a bug though.
