### ISSUE TITLE
Mutadone is extremely obnoxious to make

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7637]
@Iamgoofball  please fix this. welding fuel should not be a component in any chem recipes for most medicines anyway, making mutadone is like pulling teeth and healing people after slime attacks is nearly impossible if cryo is dead.

**Comment by Iamgoofball** [comment]
will look into

**Comment by Deantwo** [comment]
Good thing the venting machine still contain 5 Mutadone (50u) pills.
Dissolve them in a large beaker.

Hell that's how I get it at round start to setup the cryotubes.

Are we removing some of the crap from the venting machine soon?

**Comment by Iamgoofball** [comment]
We are, check the latest goonchem pr

**Comment by Dorsisdwarf** [comment]
@Miauw62  requesting this be closed, issue was fixed but not mentioned in fixing PR
