### ISSUE TITLE
IV drips are extremely slow to refill blood, and admin healing is limited.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7638]
It refills you at a rate of about 1 cl per second, which takes an EXTREMELY long time to fix you. On this server where all other forms of healing are near instant, this really ought to be revised. A syringe does this SO much faster it isn't even a competition.

Furthermore, admin revive can't heal your blood loss. It leaves it at exactly what it was at.

@paprka

**Comment by paprka** [comment]
The issue with IV drips is that they use REAGENTS_METABOLISM define for drawing and giving, IIRC, but that can be overwritten. They're supposed to give like much faster when a blood pack is attached since they're the ideal method of transfusion, but I can buff that pretty easily.
