### ISSUE TITLE
Changeling Regenerative Stasis breaks if used when alive

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#7641]
If you use this while alive, it gives you the "blah blah readapting our chemicals to regenerate" message, followed by putting you into a fake-death state where you are down and unable to get up. This persists for some time until you get the "We are ready to regenerate" message.

But nothing happens. You are grounded, FOREVER, unable to sting/blade/use items (Unless you're buckled to a chair wherein you can hold something for 1.5 seconds). Clicking the power does not toggle the regeneration. Attempts to readapt are met with the message that 'We are incapacitated' by the regen.

Presumed fix in-game is to die and then use it, otherwise, I hope you like rolling around

**Comment by Lumipharon** [comment]
Hm, to get back up, it's a seperate power (regenerate, or some shit) that appears after the 'we're ready to regen message). This worked fine the last time I was a ling.

**Comment by RemieRichards** [comment]
Yeah when you get the "We are ready to regenerate" you get a new verb in your changeling tab, it's called "Regenerate" or "Revive" and it does the actual reviving, it's so you can fake your death with it and choose when to revive.

**Comment by SconesC** [comment]
No, the button never showed up, that's the issue. I was left with no way to cancel the state.

**Comment by paprka** [comment]
This might have been fucked when I renamed it to revival stasis, I'll take a look.

**Comment by paprka** [comment]
Alright apparently I got the button when I faked death while alive and also when dead, but it just said 'you are incapacitated' when I tried to use the revive button. It doesn't seem to be applying the flags properly or something, the FAKEDEATH flags needed for reviving.
