### ISSUE TITLE
Metastation: Not all hardsuit storages spawn helmets

### ISSUE THREAD

**Issue by InfiniKraut** [tgstation/-tg-station#7642]
On Metastation engineering and atmos suit storages don't contain helmets, EVA suit storage units do.

**Comment by dannno** [comment]
That's how it's supposed to be. Hardsuits now contain the helmets within the suits, activated by a button.

**Comment by InfiniKraut** [comment]
Oh.

**Comment by Deantwo** [comment]
For future reference.
This was changed in #7346.
