### ISSUE TITLE
Red and green being used to represent Medbay when it should be blue

### ISSUE THREAD

**Issue by TZK13** [tgstation/-tg-station#7646]
A list of sprites that need to be changed which I intend to handle sometime in the near future, if anybody else can provide other examples they come across it would be appreciated.

-Object sprite for medical winter coat has red cross on it.
-Medical duffel bags have green crosses on them.
-The inhand sprites for bruise packs and ointments have green on them.
-Boxstation Bridge has green trimmed tiles underneath the medical consoles.
-Nurse hat when being worn by a corgi.

*Syndicate affiliated sprites including their medical duffel bags, medical space suits, and mediborg utilize red crosses but I feel like that should just be left alone considering the Syndicate's colour scheme uses red.

**Comment by WJohn** [comment]
Sleepers don't have any crosses on them in the first place...

**Comment by TZK13** [comment]
Upon closer inspection you're correct, what I thought was a tiny red cross was actually a red light on the sleepers.
