### ISSUE TITLE
Non-lethal guns allow suicide, rounds are not used

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#7647]
Committing suicide with a gun is possible regardless of whether that gun is capable of inflicting lethal damage, this includes practice and lasertag lasers. Have not checked with floral rays.

Additionally, committing suicide via firearm does not expend a cartridge or unit of charge.

**Comment by Dorsisdwarf** [comment]
Seeing as how you can kill yourself with a crayon, or by pointing a bannana at your head and saying "bang", I don't think the first half is an issue.

**Comment by Miauw62** [comment]
see you, space cowboy
