### ISSUE TITLE
Gold slime cores injected with blood make hostile creatures instead of passive.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7649]
Originally injecting gold slime cores with blood would make passive creatures that wouldn't attack you no matter what, and plasma was supposed to be used to get hostile ones. Now blood creates hostile ones too.

**Comment by paprka** [comment]
unsure if this has to do with my blood update, check syringes.dm and blood.dm procs

**Comment by Delimusca** [comment]
it seems gold core reactions were changed to use chemical_mob_spawn(), which never sets faction to neutral.

**Comment by Incoming5643** [comment]
additionally plasma reactions are supposed to spawn a few mobs, not just one. That's the trade off, blood reactions spawn one friendly mob, where plasma gives you more but they try to kill you.

**Comment by Iamgoofball** [comment]
Whoops, will fix
