### ISSUE TITLE
Infected blood + IV drip = crasherooni

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7654]
Same issue as https://github.com/tgstation/-tg-station/issues/7563 basically

Basically it's this proc.

https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/iv_drip.dm#L88

Inject_blood() works perfectly fine in syringe code for blood virus transfers but it's causing server crashes in the IV drips for some reason. I'm thinking since drip() used processing in life() that it's the same issue as before but it honestly doesn't make any sense in this case.

Virus2 uses optimized code but this chunk of code here:
https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/blood.dm#L196

..works perfectly fine for syringe transfers, so this obviously isn't the issue. Same for the old issue of blood splatters/blood drips causing server crashes. The virus transfer code was fine but it caused server crashes for some bizarre reason, when it didn't on baycode/goon scheduler.

Maybe we need bay or /vg/'s improved virus transfer procs from virus2? I don't see any runtimes here so it has to be some fucked up process() shit.

**Comment by paprka** [comment]
Yeah this is an extremely frustrating bug and I'm pretty sure it has to do with carn's MC time for seppuku.

**Comment by Chocobro** [comment]
https://github.com/tgstation/-tg-station/issues/7565
remember when i reported this but it was apparently 'wrong'

**Comment by Menshin** [comment]
>for(var/datum/disease/D in injected.data["viruses"]){
var/datum/disease/new_virus = D.Copy(1)
injected.data["viruses"] += new_virus
}

What are you doing here ?!?
This basically multiply by 2 the number of viruses in the blood : while it's unoticeable with syringes (at most three injections), it's done ___every tick___ with iv drips.

The disease list then skyrockets from 1 disease to 32768 in 15 seconds, killing the MC (which has to process 2^n additions to the list at n tick) and the server in less then 30 seconds with enough blood in the beaker...

**Comment by paprka** [comment]
No, it isn't, but they're processing 24/7 instead of just when people are attached due to latency issues with the machinery controller last I tried it. I removed the background setting earlier and it didn't make any real difference.
