### ISSUE TITLE
Carn MC is unmaintained and needs to be replaced

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7655]
Pretty much what the title says. We need to address the fact that Carn has (once again) left a project to rot and do something about it. The goon scheduler volundr provided is a lot better alternative and other codebases (such as /vg/) are using it. I'm sure it would be compatible with carn's shuttle changes as well, we should consider it again.

**Comment by CorruptComputer** [comment]
:+1:

**Comment by dannno** [comment]
shits problematic yo get it done

**Comment by GunHog** [comment]
Port it, Paprika!

**Comment by paprka** [comment]
It's not especially hard but carn's shit is hooked into fucking everything so that's where the issues arise

**Comment by Iamgoofball** [comment]
plus carn changed 500+ files and included un-MC related changes

they also didn't run mapmerge so map changes are gonna be a pain to revert

**Comment by dannno** [comment]
maybe it's time for a freeze to properly unfuck this

**Comment by paprka** [comment]
The only map changes she committed were due to her shuttle changes, which don't have to be reverted. Her shuttles are cool as fuck honestly, a bit buggy, but a much better system than what we had.

We don't need ot touch the map. it's the systems we need to worry about, the places they're hooked into. Which isn't particularly hard, honestly.

**Comment by Steelpoint** [comment]
The biggest in game problem (that is noticeable with players) with the shuttle changes is that its impossible to host "shuttle events" where players build a evac shuttle and ride it around.

Otherwise though the actual map changes to the shuttles are great.

**Comment by paprka** [comment]
That should be still possible, ikarrus did an event the other day on basil and it worked fine

**Comment by optimumtact** [comment]
What is unmaintained about it? It's not the most complex system, it just took all the current items being called in the big ticker loop and split them into sub datums.

**Comment by paprka** [comment]
oranges you're welcome to be the new maintainer and fix any possible bugs with the carn MC including re-implementing building on shuttles and such and fixing broken corner pieces on shuttle interiors

**Comment by AlexanderUlanH** [comment]
Every system doesn't need a specific dedicated maintainer.  The MC's a big part of the game code, there was a big project to make it better, and now there's a big part of the game code which is different but better.  
The old shuttle system was literally the worst, and the shuttle corners used to be hard-sprited.  Those are things that it would be nice to implement, but they don't even really have anything to do with the MC, and they certainly don't justify porting a *whole new* MC.

**Comment by paprka** [comment]
Shuttle corners did not used to be hard sprited. The reason why I suggested goon's scheduler is because it specifically ISN'T as large as carn's subsystems and stuff. /vg/ ported it in a single day.

**Comment by paprka** [comment]
We can revisit this l8r
