### ISSUE TITLE
Tank Transfer Valve Bombs are taking their sweet time to explode

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7665]
1. Open tank transfer valve by any means
2. wait over 10 real world seconds where nothing seems to be happening
3. The bomb eventually explodes at full force

You can manually open a valve, and slowly walk away and get out unscathed. Conversely you can't surprise anyone with a bomb because they have more than enough time to either run away or disassemble the bomb. 

It used to be that opening the valve more or less instantly detonated the bomb.

**Comment by paprka** [comment]
Depends on the mix.

**Comment by Lumipharon** [comment]
>Depends on the mix.

Is pretty much it. Opening the valve/triggering the bomb doesn't, and never has, directly resulted in the bomb exploding. All it does is let the gas between the two tanks mix. Depending on your mix you can make a very large delay before it actually explods, or near instant.

Also remote signallers have their own delay, so there's that too.

**Comment by Incoming5643** [comment]
Alright then let me specifiy: The tank transfer bombs you get out of emagged arcade machines have a ridiculously long delay that at one point they did not.

**Comment by MrStonedOne** [comment]
Fixed by fastmos
