### ISSUE TITLE
Some ERT guys spawn naked

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7667]
When an admin hits the ERT button, and spawns 7, 3 of them spawn naked. There's one of each fully equipped, and 3 nude people. I believe I set up the proc wrong, but it's kind of hard to test 7 ghosts turning into ERT.

Additionally, only one ERT team can be spawned. This should probably be changed.

**Comment by Deantwo** [comment]
When I was playing around with the admin tools on a local server.
 I did notice that ```Select Equipment -> ERT -> Medical Officer``` left you naked.
That could be related.

I just forgot to report it.

**Comment by Steelpoint** [comment]
I knew I should have reported this, I forgot it compleatly.

I found that the Med Officer would always spawn naked, I only tested when spawning in someone manually but I did not think it would affect spawning in officers.

This bug is a result of paprika's PR here: #7509
