### ISSUE TITLE
AIs can't use the buttons/links inside almost any interface/window.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#7671]
Basically, using apcs, air alarms, coms consoles, bot control panels, turret controls, AI Liquid Dispensers, and a whole host of windows don't work for the ai, but do for borgs. By don't work, i mean you can open them, but clicking any topic inside of them don't seem to work.

Tested on: 9e8029e64dbf91d2b1a89e3960b65972591b14c6 (current at time posting)

Not present on: 3afdaabbb2fdaafcae4b026a20c5a7590698e483 (current basil build)

both 506 latest and 507 latest.

Some notes from testing:

Beepskys (and maybe other bots) can be used kinda if the ai spam clicks the button.

The first apc the ai opens can be used, but none after. (this might apply to all nanoui windows) (reports are this can be reset by reconnecting, but its still one interface usable per connection)

Click modifers (control click/shift click) work on all except turret controls.

Door interfaces work.

Intercom interfaces work.

**Comment by GunHog** [comment]
It could be a bug with checking camera chunks. I have encountered this problem with a few APCs in plan view, as well as things my borgs were near but I still could not access.

**Comment by MrStonedOne** [comment]
well, in between the two revisions ai camera chunks were fucked with. so you might be on to something @GunHog
