### ISSUE TITLE
Chairs need a simple overlay for when people are buckled to them

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7674]
Now that we have the capacity for not shitcode, we should make an overlay for when people are buckled to chairs. A simple seatbelt would work for now.

It's sort of a readability issue and a pain in-game at times, people look identical when they're buckled to chairs and it allows them to stealth unbuckle and uncuff which isn't very good.

**Comment by PKPenguin321** [comment]
Seatbelts on a standard chair would be kind of weird, but if the issue is stealth unbuckling and uncuffing, maybe adding an overlay when you're handcuffed and buckled that shows you cuffed to the chair/bed? inb4 used in erp

**Comment by paprka** [comment]
pff

**Comment by Miauw62** [comment]
you're on a fucking space station, of course there's going to be seatbelts on the chairs.

**Comment by dannno** [comment]
...really? Is it THAT certain?

**Comment by paprka** [comment]
meh it would look weird for people just sitting at the bar at tables who don't want to be pushed around. The only real instance this comes up in is the shuttle and the brig. Stealth unbuckling isn't THAT big of an issue for the brig, it means the officer wasn't paying attention, but on the shuttle it's really confusing when there's tons of chairs. We need a subtype of chair that displays overlays when people are buckled to them.

**Comment by mikecari** [comment]
Yeah I've stealth-unbuckled a lot when security put me in the shuttle brig as a traitor. It actually got me my objective once :^)

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
