### ISSUE TITLE
Stimpack doesn't work as advertised in the uplink

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7675]
@Iamgoofball Well done, you caused a team of nuke ops to completely get shit on by tasers since it doesn't actually make you immune to stuns. :laughing: 

Also, there's literally no reason for this to exist, since adrenal implants are the same price and way easier to use.

**Comment by Iamgoofball** [comment]
Quiltyquilty added this, not me. I'll check it out though.

**Comment by paprka** [comment]
lel top code

yeah just remove it to be honest

**Comment by SconesC** [comment]
are they supposed to make you immune to stuns? figured it was just reduction
i know they give you hella speed and some pretty fucking crazy regen, i've emptied into someone on stimpacks and still had them come after me

**Comment by Miauw62** [comment]
The PR to fix stimpacks by goofball still isnt merged.

**Comment by phil235** [comment]
will be fixed by #9014.
