### ISSUE TITLE
Turning into a monkey removes xenomorph foetuses

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#7678]
As reported on singulo, being turned into a monkey removes xenomorph embryos from a human. This gives people a much faster and easier way to prevent chestbursting than surgery.

**Comment by scoopscoop** [comment]
Didn't anatomic panacea remove the embryo too anyway?

**Comment by WJohn** [comment]
Does this happen with other diseases or are they kept?

**Comment by Razharas** [comment]
I thought thats intended

**Comment by WJohn** [comment]
This doesn't make too much sense, but we have all sorts of mechanics for actually removing xenos, and if they're completely beaten totally and fully by turning them into a monkey and back then what's the point of using the intended method?

**Comment by Dorsisdwarf** [comment]
Anatomic panacea doesn't fix xenoes.

**Comment by phil235** [comment]
Other diseases are kept.

**Comment by xxalpha** [comment]
Can't reproduce, this might have been fixed by a recent refactor.
@phil235
