### ISSUE TITLE
Duffel bags can be carried off-hand without any slowdown penalty

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7687]
Come on now at least try to balance shit

**Comment by dannno** [comment]
k ill fix

**Comment by Fox-McCloud** [comment]
so can hardsuits and a plethora of other things; is this really an issue?

**Comment by paprka** [comment]
Yes, if an item has a slowdown while wearing it, you should have a slowdown while carrying it too. I guess this can apply to hardsuits as well but i dunno

**Comment by WJohn** [comment]
I don't mind this, honestly. The alternative is to give everything else that slows you down when wearing it (riot suits, bio suits, space suits and whatever else) slowdowns too.

Expect massive backlash for doing this, though.

**Comment by Cheridan** [comment]
working as intended
