### ISSUE TITLE
Telecomms server on syndicate shuttle superheats the air around it

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7691]
The one next to the nuke. It can cause serious issues.

**Comment by ike709** [comment]
It keeps everyone nice and toasty, not a bug.

**Comment by Miauw62** [comment]
wasnt tcomm heating supposed to be disabled?

**Comment by AnonymousNow** [comment]
Can confirm, nearly knocked me into crit this morning. Had to vent the shuttle in order to survive.

**Comment by paprka** [comment]
@Miauw62 I think so, but the tcomms room is still superchilled so I dunno

I don't think anyone would really even mind if the tcomms room stayed chilled but they don't generate heat, I mean, a cold server room makes sense and all that but people rarely build those machines outside of there.
