### ISSUE TITLE
Grass tiles lack a proper broken states.

### ISSUE THREAD

**Issue by Nyvrem** [tgstation/-tg-station#7698]
![basil rimward frontier 23 2015-02-12 231844](https://cloud.githubusercontent.com/assets/10331933/6184670/40b132c8-b365-11e4-8a41-79ab5573a018.png)
Grass tiles don't break properly when exposed to inferno and when damaged instead display the honk tile.

**Comment by Stickymayhem** [comment]
Honk!

**Comment by phil235** [comment]
Three PRs fixing this and all three got closed :disappointed:
