### ISSUE TITLE
Glass filled with B-52 appears as a "glass of..what?"

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#7701]
It should change its name and its sprite to the B-52 glass. I'm not sure if the bug also happens with other drinks but some drinks are still working fine (manly dorf, Singulo).

**Comment by paprka** [comment]
@Iamgoofball chems have messed with a few drinks here

**Comment by Iamgoofball** [comment]
@paprka @vekter was the last guy in the drink files according to github

**Comment by Dorsisdwarf** [comment]
B-52 is a shot now, it only works in shot-glasses AFAIK

**Comment by paprka** [comment]
oh my god why

**Comment by phil235** [comment]
why can't it work with both?

**Comment by TheVekter** [comment]
Yo, that's on me.

I removed the b-52's iconstate from glasses at the urging of another coder. Starting to seriously regret doing that. This isn't a bug but I can still fix it. I'll look into it.

**Comment by paprka** [comment]
which other coder >:(

**Comment by TheVekter** [comment]
I don't feel comfortable discussing the matter in an open forum.

**Comment by TheVekter** [comment]
For the record, it still actually WAS the drink, it just wasn't changing the sprite.

Pap brought up a good idea for some overall bartender changes that involves making the bartender use specific glasses. I'll revisit this later when we get that coded in, but for now this reverts that change.
