### ISSUE TITLE
Printing a book via SS13BN causes the book list to reload itself 9 times before printing the book

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7704]
it's bad enough even without the game-breaking lag that one reload causes.

**Comment by Lumipharon** [comment]
Someone please fix this shitty machine so I can actually be librarian.

**Comment by phil235** [comment]
related to #7459

**Comment by Dorsisdwarf** [comment]
Wasn't this fixed?

**Comment by Chocobro** [comment]
haven't seen any prs fixing it.
