### ISSUE TITLE
Improvised Shotguns have no onsprite

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#7709]
The improvised shotguns from R&D (Single shot, made from modular receivers) have no on-sprite when worn on your back. Not sure if this was an oversight or if a unique onsprite simply does not exist.

Additionally, they DO have one if you add a wire bandolier to them - But that does literally nothing as far as I can tell besides blow the cover of your weird invisible shotgun. Feels like an unfinished feature similar to the 'modular' receiver as a whole.

**Comment by paprka** [comment]
i'm too lazy to make more improvised weapons because i hate 50000000 suggestions whenever i make a feature
