### ISSUE TITLE
Kinetic accelerators are hilariously deadly. (Not live on server, but in current master)

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#7719]
![goofballbalance](https://cloud.githubusercontent.com/assets/6583225/6198496/3a9fdcfe-b3ba-11e4-9134-655e347877b3.gif)

#7539
>Kinetic charge is buffed a bit and can damage structures and turfs around the kinetic blast (**but not station walls or mobs**). This makes kinetic guns a bit better in mining.

Testing is hard.
@Iamgoofball 
@Cheridan

**Comment by Iamgoofball** [comment]
wait shit this got merged?

**Comment by Cheridan** [comment]
Not seeing the issue :hurtrealbad:

**Comment by phil235** [comment]
Another PR that was merged without being tested :disappointed:

**Comment by Miauw62** [comment]
we do it 4 free

**Comment by dannno** [comment]
sloppy
