### ISSUE TITLE
[Ghost] Toggling darkness off makes other ghosts invisible

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#772]
##### Revision:
Unknown

##### Server:
Sibyl 1 (Approx. 15:45 14 June UTC+12)

###### What did you expect to happen? 
Toggling darkness wouldn't make other ghosts invisible

###### What happened instead?
The darkness disappeared, but so did other ghosts

###### Why is this bad/What are the consequences?
Sometimes it's interesting being able to see how many other people are spectating the same people as you are

##### Steps to reproduce the problem:
1. Ghost
2. Find another ghost
3. Toggle darkness

Result: The other ghost should disappear

**Comment by MrStonedOne** [comment]
AYYY LAMO

UNRESOLVEABLE MY ASS @Cheridan

**Comment by MrStonedOne** [comment]
OH HEY @balohmatevz YOU GET IN HERE TOO.

MR 5 PAGE ESSAY ON WHY IT CAN'T BE FIXED

=P

**Comment by RemieRichards** [comment]
What MSO said. fixed yo.

**Comment by MrStonedOne** [comment]
Just a note, this has been fixable since this bug report was open.

client.images isn't new, sechuds use them
