### ISSUE TITLE
RnD features

### ISSUE THREAD

**Issue by tankistqazwsx** [tgstation/-tg-station#7722]
My ideas for RnD :
  Make 20 levels of research .10 levels can be researched in one shift , but SS13 - not a one-shift station , it made for years of researching
  Make Fusion reactor that can make one reagents from other
  Make xenoarchaeology , for researcning 11-20 levels of research.

Sorry for bad English.

**Comment by Deantwo** [comment]
I think you would be better off suggesting this on the forum first.

**Comment by Miauw62** [comment]
1. too vague
2. do you even know how hard this is
3. too vague
4. not the place for this
