### ISSUE TITLE
Security console can't modify some properties of records

### ISSUE THREAD

**Issue by Szunti** [tgstation/-tg-station#7727]
Can add minor crimes but not delete them, can't add major crimes or notes or comments. The dialog are shown, I fill them in, but the datas are not saved.

As I see canUseSecurityRecordsConsole() miss one argument in the faulty cases.

**Comment by WJohn** [comment]
Security and medical record consoles seriously need to be overhauled to be actually usable in any way. They're entirely too RP centered and there's no a whole lot you can do with them in the map maker either.
