### ISSUE TITLE
Research Upgrade Malfunction in the Experimentor is Useless.

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#7741]
Server: Basil

Revision: #7662 

Problem Description: The Experimenter's chance to upgrade the item's research seems to not work at all.

What did you expect to happen: The thing gives higher research when scanned in the experimenter or Destructive Analyzer.

What happened instead: It gave no higher research, and didn't even show a number when put in the destructive analyzer.

Steps to reproduce the problem: Constantly test mess with something in the experimenter untill you get the Research Upgrade malfunction. Try to deconstruct it in the Destructive Analyzer.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): If notable, I found this out with a Durand Weapons Control Board. Also, this is a copy of #7272 which was closed because it was supposedly fixed. Can't figure out how to just re-open that one.

**Comment by GunHog** [comment]
I have determined the cause and will have a fix ready shortly.
