### ISSUE TITLE
Unable to pull people while riding the secway.

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7748]
Now I can't be the mall cop the station deserves ;_;

**Comment by Xhuis** [comment]
The mental image formed of a fatass cop riding a segway dragging a handcuffed person behind him is hilarious, but this is probably for the best.

**Comment by Dorsisdwarf** [comment]
I was using the secway to drag crit people through space-exposed areas earlier today, so I dunno.

**Comment by paprka** [comment]
This should work perfectly fine, not sure what the issue is

**Comment by mikecari** [comment]
The problem is that handcuffed people can get away when you pull them for some reason. Not sure why.

**Comment by stapler2025** [comment]
Was it the round where the warden was trying to drag away a mime?  Because if that's the round in question, mime kept getting away because handcuffed mimes can still use their fake wall ability for some reason.

**Comment by phil235** [comment]
Reproduced it, it's not that you can't pull people or mimes using their invisible wall, it's that if you are on a secway and pulling a restrained person that person can break free from your pull despite being restrained.
