### ISSUE TITLE
"Solution begins to bubble" - harvesting ambrosia deus is a horror

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#7754]
Description: Harvesting deus from trays/spawning it spams chat with "solution begins to bubble"  and a sound effect for it. Shit plays for every single branch.

What did i expect: Harvest deus, hear no sound effects, chat is spam free.

What did happen instead: My ears exploaded, my chat was spammed with shit and i pee a little.

Steps to reproduction:

1. Plant deus
2. Harvest deus
3. Cry

Code downloaded three hours ago, tested on my private server.

![image](https://cloud.githubusercontent.com/assets/10717398/6204267/fbf80918-b544-11e4-8b27-27a18d7d5190.png)

**Comment by Iamgoofball** [comment]
Any idea what it's mixing into?

**Comment by SeikoTheSeal** [comment]
Nutriment, omnizine, synaptizine, morphine, neurotoxin, vitamin is what i get when i grind it.

Spess drugs mixing into a neurotoxin perhaps?

**Comment by Iamgoofball** [comment]
huh, that's odd. Why would chem temperature get modified by plants?

**Comment by Boredone** [comment]
Huh... Quick check in the code shows that Neurotoxin is made when Space Drugs is heated up to 200 degrees.
Yet when I've used a chem heater, stuff starts out at 300 degrees.
So... Maybe ye need to raise the required heat to make neuro-tox as it looks like its under the default tempature.

**Comment by bgobandit** [comment]
happens to ambrosia vulgaris too

**Comment by Deantwo** [comment]
Because the default temperature for new chemicals seem to be 200°K.
