### ISSUE TITLE
Life aint working.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#7755]
Life reagent wont mix for shit.

Place blood, strange reagent and synthflesh in a beaker, nope, nothing.

![image](https://cloud.githubusercontent.com/assets/10717398/6204317/1adb91cc-b547-11e4-8dd6-4e5ff1513fcc.png)

Code downloaded 3 hours ago or so.

**Comment by Iamgoofball** [comment]
You need to heat it.

**Comment by SeikoTheSeal** [comment]
Totally forgot it required heating. Closing this, im dumb.
