### ISSUE TITLE
Suggestion: Allow players to use the old version of machine menus.

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/-tg-station#7758]
I really dislike the new RnD organization. Please include a setting within the RnD console to switch menu styles (back to the big list). Its simpler than sifting through 8 different sub-menus.

**Comment by paprka** [comment]
use the search bar :+1:

**Comment by Menshin** [comment]
Doesn't the search bar solves that ?

**Comment by Ahammer18** [comment]
I cant see what is unlocked with the search bar.

**Comment by Menshin** [comment]
If you really like the huge list, you can still get it by hitting search with an empty field to list all researched designs.

**Comment by xxalpha** [comment]
Why isn't there an All list?

**Comment by Ahammer18** [comment]
Ah, then that was my fault. I just want it to exist. Mods can close this now.

**Comment by Dorsisdwarf** [comment]
@Ahammer18 

You can close your own issue reports.
