### ISSUE TITLE
Mech ballistics do not fire properly.

### ISSUE THREAD

**Issue by demonfiren** [tgstation/-tg-station#7766]
While testing a mech shotgun (Scattershot) and LMG (Ultra) with a Durand the following issue has been discovered:

Projectiles are spawned on the mech's square and do not move. They can be picked up, and throwing them does deal damage.

**Comment by SconesC** [comment]
this has been around for ages, not sure if it's mech-specific or just gun-specific but shit still happens on Gygax/Phazon

**Comment by Dorsisdwarf** [comment]
Due to budget cuts, the gunpowder in NT standard bullets has been removed, requiring employees to use combat mechs as throwing weapon dispensers.

**Comment by phil235** [comment]
Pretty sure this is a duplicate.

**Comment by WJohn** [comment]
4th time dupe of #6179. Might be the most times we've seen an issue duped, actually.
