### ISSUE TITLE
Ghost-teleport to "escape pod 1" takes you to several places that aren't pods

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7767]
to name and shame, it takes you to: nukeop/syndie shuttle, white ship, escape shuttle

**Comment by MrStonedOne** [comment]
On that note, admin send mob'ing people to arrivals shuttle takes them to the white ship.

**Comment by phil235** [comment]
same thing happens with escape pod 2, 3 and 4.

**Comment by Jordie0608** [comment]
This is because shuttles don't use areas anymore, they're all the same area/space so as far as the game is code is concerned it can take you to any of them.

**Comment by MrStonedOne** [comment]
They really need to either be removed from the area list or readded as area
areas. Just because carn shuttles don't need areas doesn't mean they should
lost that marker that's useful for jumping and other things. You can't send
somebody to the arrivals shuttle anymore as admin
