### ISSUE TITLE
Teleporters should say their lines [Feature request]

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#7772]
Currently, teleporters use something like visiblemessage for their "target calibrated" and so on. This is really weird when you're not the person using it, because it gives feedback in a radius, especially for ghosts.

Since machines can speak now, maybe they should say these things.

**Comment by quaggaman555555** [comment]
I agree, someone might hear a traitor/nuke op using the teleporter to, say, get to the nuke op ship through the teleporter, and use that information to somewhat meta them. If they spoke, however, you wouldn't hear it through a wall.
