### ISSUE TITLE
Slime people goo blood can't be used for viro samples.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#7775]
Slime people have slime goo for blood, which makes perfect sense, but the goo can't be used in the pandemic machine. Which leads to be a bit of a oddity in that you can't take samples of the viruses they have.

Also, the slime goo levels are displayed in sleepers. Just saying.

Potentially not a  bug, just annoying.

**Comment by Incoming5643** [comment]
Viruses are a thing stored in blood, mutantraces without blood or with exotic blood still HAVE traditional blood, it just can't be accessed or depleted in any way. So the viruses in a mutant race just aren't accessible for these sorts of things.

**Comment by WJohn** [comment]
So they both suffer from and still spread disease? I can foresee this being used as extra reasons to cull non-humans.

**Comment by Incoming5643** [comment]
it wouldn't be hard to make bloodless/exotic blood mutantraces disease immune.

How does a skeleton catch a cold anyways?

**Comment by Iamgoofball** [comment]
@Incoming5643 by not drinking enough milk

**Comment by Miauw62** [comment]
:skull:

**Comment by paprka** [comment]
Goo might need to be a child of blood?
