### ISSUE TITLE
Setting the shaker's transfer rate to 25 deletes the shaker

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7779]

**Comment by phil235** [comment]
can't reproduce. Can we have more info on how it happened? (you're talking about the bartender's shaker, right?)

**Comment by Dorsisdwarf** [comment]
No information forthcoming, bug is months old and unable to reproduce, closing.

**Comment by Chocobro** [comment]
i know this is wicked ancient but the entire information was i spawned in as a bartender at round start, changed my shaker to 25 and it disappeared into the shadow realm
