### ISSUE TITLE
Changeling bugs

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#7784]
Revival stasis: Still lets you talk, see, hear, interact with lockers. Just knocks you down.
After the revival duration passes when you try to revive: You are incapacitated. (in red italics)
:-1:

**Comment by kevinz000** [comment]
We are incapacitated*
not you.

**Comment by RemieRichards** [comment]
@kevinz000 
"We are incapacitated" is intended, Changeling uses "We" wherever possible because it's a hivemind creature.
