### ISSUE TITLE
Ninjas no longer have AI control abilities

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#7785]
It seems that with the change to have the ninja use an Intellicard, the special verbs such as rewriting the AI's laws to serve ninjas, the AI hologram, and the law 0 AI wipe malfunction no longer work.

Selecting the AI status option just opens up the default intellicard window, no special commands are available.

**Comment by Jalleo** [comment]
@Cheridan

**Comment by palpatine213** [comment]
Closed by #8261
