### ISSUE TITLE
caffeinated drinks barely make you jitter if at all

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#7789]
The jitteriness drops fast naturally and coffee can only make it go up to 5.
Either the effect must be increased or the natural drop (not resting) must be lowered.

Or, we could alternatively buff the jitter effect and move it to an overdose proc for these drinks.

**Comment by Lumipharon** [comment]
How much do you jitter in real life from drinking coffee that this becomes an issue?

**Comment by WJohn** [comment]
Pretty sure that most things you eat to the point of becoming jittery would kill you IRL. This is all for fun.

**Comment by phil235** [comment]
Fixed by my refactoring of carbon/life()
