### ISSUE TITLE
drunken lizards sound disgusting

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7796]
[Common] Tig-Bitties (Assnt) slurs, "Chchchhee sschchchsschschs'sellsssschch chchchchsch'ssseasssschsschsschchchssch'hellssch doo'wn bbby the' schchsschssssseahssshoore"

what the fuck is this even supposed to mean, why would you apply the slur code and the lizard code at the same time

**Comment by WJohn** [comment]
Drunk AND stunned lizards must be even better.

**Comment by Anonus** [comment]
Ha ha oh god, that's hilarious

**Comment by Iamgoofball** [comment]
imagine this with the unintelligible mutation

**Comment by dannno** [comment]
seems fine to me

**Comment by PKPenguin321** [comment]
feature

**Comment by paprka** [comment]
And?

**Comment by Miauw62** [comment]
10/10

**Comment by Incoming5643** [comment]
Emergent Gameplay

**Comment by dannno** [comment]
really though if you do a tongue twister that has 200x more "ch" "sh" and "s" sounds than any other normal sentence, as a lizard, while drunk
i mean what did you expect
