### ISSUE TITLE
Vanishing bar glasses

### ISSUE THREAD

**Issue by mrpain666** [tgstation/-tg-station#7801]
If you pour tequila in a glass, the glass disappears 5ever.

**Comment by Delimusca** [comment]
[Drinkingglass.dm](https://github.com/tgstation/-tg-station/blob/master/code/modules/food%26drinks/drinks/drinks/drinkingglass.dm#L114) -> "tequilaglass"
[Drinks.dmi](https://github.com/tgstation/-tg-station/blob/master/icons/obj/drinks.dmi) -> "tequillaglass"

shameful find&replace brings dishonour to us all.

**Comment by mrpain666** [comment]
It could be other drinks and combinations too. I only reported tequila because that's what I happened to have found at the time. If I find more should I create separate issues or keep it in this one?

**Comment by Menshin** [comment]
@TheVekter

**Comment by TheVekter** [comment]
Yo that's on me. I'll fix it when I wake up.
