### ISSUE TITLE
You are able to slip on a wet floor while on a segway

### ISSUE THREAD

**Issue by mrpain666** [tgstation/-tg-station#7804]
Go ride over a wet floor while on a segway. Not sure if this was intended but it seems really silly.

**Comment by mrpain666** [comment]
ACTUALLY this might be a good idea, intended or not, because this might lead to security powergaming with MUH NO SLIP

**Comment by paprka** [comment]
it's intended, you hydroplane and fall off so the segway/janicart isn't free noslip
