### ISSUE TITLE
Nar'sie message spam

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7811]
Just happened on sybil, 1:20 PST 2/18.

Three nar'sie messages popped up even though only one spawned.

**Comment by An0n3** [comment]
Multiple nar'sies don't spawn it just makes the message pop up multiple times.  Just happened again on Sibyl 7:09pm EST.

**Comment by paprka** [comment]
I stand corrected

**Comment by An0n3** [comment]
Is that possible?  I thought they would just pass through eachother in the event multiple Nar'Sie collided.
