### ISSUE TITLE
Radio plays "asks" while the live plays "says" (saycode)

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#7812]
[Common] Kylie Graham **asks**, "Can everyone stop stealing the lights in the library, please?"
Kylie Graham **says**, "Can everyone stop stealing the lights in the library, please?"

**Comment by Miauw62** [comment]
rip immulsions

anyway i know what causes this, i never got around to cleaning up the various non-OO say_quote() procs that are spread all over the code.

**Comment by Miauw62** [comment]
I think this is fixed too.
