### ISSUE TITLE
Cargo pizzas have no nutriment.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#7823]
![pizza](https://cloud.githubusercontent.com/assets/6583225/6261003/bcc0c7da-b79c-11e4-9958-1051c11c06d1.png)

The upper far right one is a kitchen-made pizza shown for example.

**Comment by phil235** [comment]
silly me, trying to add "nutrient" to pizzas instead of "nutriment"

**Comment by Miauw62** [comment]
feature, just pretend theyre from domino's
