### ISSUE TITLE
You can procreate with pets

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7827]
1. Get polymorphed into an animal
2. Find the matching station pet of the opposing gender
3. Find a quiet place away from other people
4. Log out
5. Log in
6. Never feel clean again

:cat2: :cat2: :cat2: :cat2: :cat2:

**Comment by TheVekter** [comment]
Why.

**Comment by Incoming5643** [comment]
:cat2:

**Comment by Mandurrrh** [comment]
This is just asking for furry jokes and shitlers doing creepy shit. Joke pr?

**Comment by GunHog** [comment]
DO NOT FIX. DO NOT EVER FIX.

**Comment by RandomMarine** [comment]
Feature

**Comment by Cheridan** [comment]
Puppies! :dog2:

**Comment by Incoming5643** [comment]
Only works with runtime because runtime is female but all generic cats are male. All generic corgi's are male so you'd need to order lisa t- why am I explaining this.

**Comment by Malkevin** [comment]
Feature
