### ISSUE TITLE
Centcomm supply shuttle loan doesn't actually bring anything on the shuttle

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#7832]
You get the message and supply points, but nothing is on the shuttle when it arrives.

To reproduce: have the shuttle be at centcomm. select loan to centcomm. once done, select send to station. be dissapointed when you find an empty shuttle.

This apparently was broken for a while and no one bothered reporting it.

**Comment by phil235** [comment]
Maybe I'm wrong but isn't the shuttle loan supposed to give you points instead of crates? (unlike the spider clan and russian party event)

**Comment by quaggaman555555** [comment]
Ih you're talking about the double supply event, yes, it gives you crates, and the only other ones are the spider clan, russians, and Syndicate "infiltration" event, and all but the spider clan gives crates. The Syndicate one gives a syndicrate, the russians give a party crate, and the double supply one gives food(?) and other random crates.

**Comment by palpatine213** [comment]
I thought the Russian and syndie ones caused some mobs to spawn that you fought. Anyway, the problem is that nothing is appearing on the shuttle at all. No crates, no mobs, nothing.
I've witnessed this with both the Russian and double supply loan events.

**Comment by quaggaman555555** [comment]
Yeah, the Russians spawn in the Russian one, spiders with the spider clan, and Syndicate Operatives with the syndicate one, I was just listing the crates that come.
