### ISSUE TITLE
Slime people no longer have purple hair

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7838]
Their hair seems to be greyscaled as well as their bodies. I'm assuming alien color is supposed to be applied to slime people now too?

Slime people used to be blueish I think, and have purple hair.

**Comment by paprka** [comment]
Correction: They are bald.

**Comment by AnonymousNow** [comment]
I set my alien colour to cobalt, and my slimeness looks damn good.

**Comment by Incoming5643** [comment]
You need to have an alien color set, for some reason a lot of aliens are defaulted to a really unflattering shade of grey in the code.

**Comment by paprka** [comment]
Oh okay, if they adopt alien color all over now, including hair, that's fine.
