### ISSUE TITLE
More verbose Alert system

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#7839]
From this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=2800

Malkevin assembled very nice new code protocols for the alert levels.

Headmins (at least Ikarrus) agreed to have this added in, but Ikarrus wrote:
"Anything more involving than changing the current text strings we get needs to go through coderbus, not us."

**Comment by paprka** [comment]
What is this issue even meant to be, no shit it's a code thing

**Comment by kingofkosmos** [comment]
I'm not sure what the protocol is, I thought "go through coderbus" would be this so you guys are informed.

**Comment by paprka** [comment]
I'll see what I can do, but I'm not renaming delta

**Comment by Dorsisdwarf** [comment]
Should probbably be closed, unless someone's planning on doing this.

#coderbus to pitch ideas like this to the coder,

https://tgstation13.org/phpBB/viewforum.php?f=9 is for ideas.

We're having a problem at the moment with issue inflation, wherein we have no clue how many actual issues we have to fix due to 'discussion', 'feature request' and 'balance request' issues.

**Comment by Miauw62** [comment]
that's why we have a bug tag, you butte.
but yeah people should stop making thousands of feature requests.

**Comment by kingofkosmos** [comment]
>but yeah people should stop making thousands of feature requests.
Why? I've had 100x better luck having my ideas implemented through this than the minor ideas -thread on the forum.

**Comment by Miauw62** [comment]
because this is an issue tracker, not an idea tracker.

**Comment by kingofkosmos** [comment]
Then why were there multiple feature requests before I made mine plus a "Feature Request" tag?

**Comment by Miauw62** [comment]
presence of shittyness is not a reason to make more shittyness.
i don't really know why all these feature requests started happening
suddenly, but it's fairly annoying V:

(i'm not going to crack down horribly on this or anything, just want to
discourage people from making tons of feature requests)

**Comment by kingofkosmos** [comment]
If you have no rules about this, this shouldn't come as a surprise.

It would be fair then to either get rid of future feature requests which clearly belong to the Ideas-forum or make other clear cut rules about how many feature requests per person can be made etc.

I've had multiple of my feature requests gone through here, while on the Ideas-forum there has been only 1 case, just saiyan.

**Comment by Miauw62** [comment]
That doesn't really make them less annoying. I'm the dude who tags all the
untagged issues every now and then, so less bloat is always good for me.
You'll also note that we have almost twice as many issues as we have bugs,
which is dumb.

**Comment by RemieRichards** [comment]
@Miauw62 gotta remember that the issues number is artificially inflated higher than the bug or even actual issue number, because of PRs being counted.

**Comment by Miauw62** [comment]
PRs haven't counted as issues for ages.

**Comment by RemieRichards** [comment]
nobody tells me nuthin.

**Comment by kingofkosmos** [comment]
I wont make any more feature requests on github, but I still think it's not right that some people (mostly coders) can make feature requests here while others can't.

**Comment by Miauw62** [comment]
we don't make feature requests, for the most part. the headmins sometimes
make feature requests about things they'd like to see logged more and
administrative features, but not much else.
