### ISSUE TITLE
Booze dispenser lacks tequila

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#7841]
![hurr](https://cloud.githubusercontent.com/assets/6583225/6285957/0cd56d96-b8b7-11e4-853f-9076a0fdb8e4.png)

@Mandurrrh

**Comment by Mandurrrh** [comment]
It's because they fixed the spelling! I'll fix it thanks :)

**Comment by TheVekter** [comment]
Wasn't me this time.

**Comment by Mandurrrh** [comment]
It was you! You merged the spelling corrector pr after I'd already put the misspelled path in. But let's just blame the original asshole that can't spell tequila!

**Comment by phil235** [comment]
Fixed by 7843
