### ISSUE TITLE
Cell chargers do not respect laws of thermodynamics

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#7842]
```
<RandomMarine> I just found out that you can keep an area powered forever off the grid.
<RandomMarine> With just two cells, a charger, and an unlocked APC.
<RandomMarine> Shouldn't the charger, like, actually use up power.
<Jordie> who needs thermodyanimcs
<RandomMarine> Who needs the singulo.
<RandomMarine> Just have drones ferry cells back and forth between APCs and chargers.
<RandomMarine> That'd make a funny event round, actually.
<RandomMarine> Delete the solars, SMESs, PACMEN, radiation collectors, etc.
<RandomMarine> Spawn a bunch of drone shells and cell chargers in electrical maintenance.
<RandomMarine> Power the station to the best of your abilities, fuckers.
<Jordie> well
<Jordie> that said
<Jordie> the charger should use 200 charge for every 175 it recharges
<RandomMarine> Something is making it disproportional, then.
<RandomMarine> As I just kept a room powered on local server.
<Jordie> with just two cells? for how long?
<RandomMarine> Forever.
<RandomMarine> I even drained one of the cells to nothing with varediting.
<RandomMarine> And let it charge to full, the APC cell was at about 95% then
<Jordie> wat
<RandomMarine> Completely disconnected from the grid, too, all SMESs on the map deleted.
<Jordie> hm yeah
<Jordie> i just charge a 10k cell from full to empty with a 1k cell in the apc
<RandomMarine> >from full to empty
<Jordie> w/e
<Jordie> im a wizard ok
<RandomMarine> Emagging cell chargers to make them drain power when
<Jordie> well
<Jordie> i think i found the problem
<Jordie> charger's process does use_power(200)
<RandomMarine> And let me guess, that's in wattage, not in actual power units.
<Jordie> no wait thats fine..
<Jordie> hm
<Jordie> ok it draws the correct amount of power from the apc
<Jordie> but i think its doing some conversion error
<RandomMarine> Right, though.
<Jordie> charge on apc went down from 2500 to 2476.09 in the time it took cell charger to charge a cell from 0 to 10k
<RandomMarine> Fixing it is going to cause problems.
<Jordie> chargerate var on cell might be the problem? lemme try
<RandomMarine> If the power transfer was correct, you're going to either have chargers taking forever to charge, or chargers instakilling your workplace's APC
<RandomMarine> Just to recharge a defib, mulebot, or borg's battery
<Jordie> yeah ok i havent a clue whats causing this
<Jordie> uh actually maybe
<Jordie> the amount drawn from a cell in an apc is min(cell.charge, CELLRATE * lastused_total)
<Jordie> but comments in the cell charger suggests that CELLRATE isnt used anymore
<Jordie> so yah looks like thats it
<Jordie> to github!
<RandomMarine> But, from a gameplay standpoint.
<RandomMarine> Do we really want trying to charge a 15k to kill your APC dead?
<Jordie> its a balance vs reality issue
<RandomMarine> Maybe make chargers pull from the grid instead.
<RandomMarine> But that would kill their portability, and make wire mapping even more of a mess.
<Jordie> wait tell me if this is wrong
<Jordie> cell charger only drew 205 units per tick
<Jordie> so with the cellrate at 0.002
<Jordie> that means the apc is taking out 
<Jordie> er
<Jordie> 0.40 units per tick
```

**Comment by paprka** [comment]
>cell chargers don't use power

how did this go unchecked for so long

**Comment by RemieRichards** [comment]
the universe is <i>WRONG!</i> :S

**Comment by PKPenguin321** [comment]
Would've reported this already if it occurred to me that it was a bug. This is a bit of a balance issue as it's kind of a hard counter to powersinks, an already underused traitor item (not to mention obsoleting engineering).

**Comment by Lumipharon** [comment]
Surely you can't complain about this. We can produce fully charged cells out of a protolathe, chem dispensor uses a static amount of power for being on, charging does use more same with borg chargers/chargers/literally everything that uses power, beakers stay hot 5evah.

Basically it's a game. Fucking shit all obeys the laws of physics.

**Comment by WJohn** [comment]
This has existed foreeeeeeeeeeever.

But yeah it's still a bug.

**Comment by Jalleo** [comment]
Actually I think this was done on purpose back in svn. This can be sorted by having it workkinda like a emmiter and take power from the net which the apc is connected to instead of the apc.

I do remember how this and charging as a whole got removed due to it being designed to first charge too slowly then charge quickly apcs failed then to this.
Having it be current charge speed but charge from extra power in the grid is optimal if doable.

**Comment by paprka** [comment]
yeah this should charge from the input of the APC not the apc itself because it would drain the apc immediately

**Comment by callanrocks** [comment]
That's why they don't take APC charge anymore, used to drain the whole thing really quickly, easy way to kill cargo, robotics and RnD every other round because someone charged a cell.

**Comment by WJohn** [comment]
If it's made so these chargers need power from the net, then it really should be connected to it with a wire knot.

**Comment by RemieRichards** [comment]
@WJohn that's a bit silly.
It should just be like the majority of powered machinery, wireless APC power

**Comment by callanrocks** [comment]
@RemieRichards It drains all the power in a few seconds, you had to be there and watch the singularity escape for the millionth time because some engineer wanted to get some stungloves.

**Comment by Alek2ander** [comment]
I like this though. It's like the monkey technique. Makes no sense but will be used by robust players to optimize.

**Comment by RemieRichards** [comment]
@callanrocks I still stand by what I said, IF it has to be added at all (Nice little caveat I had which I thought would cover a response like this but ho hum)

**Comment by freerealestate** [comment]
Maybe APCs could have physically larger power cells with a much greater capacity, so borg and gun rechargers can use them to charge borgs and guns, without draining the room? The physical size would prevent them being used in batons or borgs, and the station would start with spares, and more could be order through cargo?

I just don't like the idea of the charger drawing wirelessly from the powernet, it doesn't make sense to me. It's inconsistent with emitters, which you have to wire in. And having to wire in gun rechargers during blob would be a pain in the ass. APCs having limited range wireless power I can buy. Maybe it's just because I'm used to it. Call me an idiot.

**Comment by Miauw62** [comment]
nah

APC cells should have like 500 capacity, after you charge every APC you can turn the engine off and the station will take ages to drain all the APCs + SMES.

but really our entire power system sucks.

**Comment by freerealestate** [comment]
>also it being "wireless" is the entire point of APCs

Yeah, I don't mind this.

**Comment by MrStonedOne** [comment]
I've always thought of apcs controlling induction wire loops that go thru every wall in a room. hence why its room based and not AoE based.

**Comment by Razharas** [comment]
I dunno how to fix this nicely

**Comment by Lumipharon** [comment]
Just leave it. With chargers now being upgradable people can just do shit like charge the battery inside a stun baton etc etc.

Also this is hardly game breaking considering R&D can shit out literally infinite, fully charged super cap cells for a tiny amount of metal and glass, and depleted batteries (if the "issue" was fixed) can be recycled with 100% efficiency via autolathe/crusher/deconstructive.

**Comment by PKPenguin321** [comment]
Yeah, was gonna say this issue is low priority. Might as well be closed.
