### ISSUE TITLE
Object verbs need to have hotkey alternatives

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#7845]
this is a feature request I guess? seems like the best way to grab the attention of a heroic contributor willing to turn every object verb into a hotkey

I'm thinking ctrl-click could work, as long as the item is in your hand/inventory. Alt-click could be useful as well, for items with multiple verbs

pls

**Comment by Firecage** [comment]
Well, ctrl-click and alt-click is already used unfortunately.

**Comment by dannno** [comment]
not on items. see paprika's latest PRs. it works perfectly.

**Comment by paprka** [comment]
Control+click and alt+click are mostly used by silicons for doors AFAIK. I haven't seen them ahve any other functionality in-game, they can be used to replace most object verbs.

**Comment by dannno** [comment]
alt+click has a huge use (seeing everything on a tile without having to right click (holy shit do you remember when you have to right click on big piles of shit what a godsend alt+click is))

but it doesn't matter if you're using it on something in your inventory/hand, so it's still the perfect hotkey to replace object verbs

**Comment by dannno** [comment]
Alright so apparently a lot of people are attached to object verbs despite the stigma on them pushed by like every coder i've ever talked to

this is still a thing that's need as a companion/alternative anyways

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
