### ISSUE TITLE
Balance Suggestion: Rework Hyposprays

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7846]
Currently the hypospray is pretty much only something the CMO can get his hands on, and sadly, it's often times more effective when used as a combat tool than one that is utilized for medicine. It allows the instantaneous delivery of chemicals to a person with barely any notification at all and has no check or balances on it other than it's only available to the CMO. Instantaneous injection with no chemical restriction (currently only hyosprays, syringe guns, and grenades remain) is problematic in that the mechanic gives individuals with chemistry access the ability to use incredibly powerful combat weaponry that can rival what even security has access to.

My suggestion: Rework it to something along these lines:

-Has a whitelist attached to it that consists almost entirely of beneficial medical chems; if something is not on the list the hypospray will remove the reagent. Emagging the hypospray will remove this whitelist.
-can select how much to inject, ranging from as little as 1 to as much as 30.
-When you inject someone it will display a message of "<attacker> injects <victim> with <amount> of <reagent in greatest concentration>"
-Plays a sound when it injects
-More commonly available in medical to chemists and medical doctors alike; potentially also an R&D item.

This helps cut down on the amount of non-restricted instantaneous injections available to crew and keeps the mechanic largely in the hands of traitors; it further helps communicate to the person being injected just what they were hit with; for traitors, they can still emag it and get the benefits of the instantaneous injections, and they can cover their tracks by ensuring their poison of choice is less than the reagent in the greatest concentration.

**Comment by PKPenguin321** [comment]
This kind of thing really, *really* belongs on the forums before it becomes an issue report here. The hypospray has been on the server for a very long time and an overhaul like this is something that should be more in hands of the playerbase. [Please consider opening a thread here.](https://tgstation13.org/phpBB/viewforum.php?f=9&sid=0582dc1fa94bbdd175a4129d1272b1ef)

**Comment by Lumipharon** [comment]
>a one of a kind item can be used offensively, on people that aren't wearing bioproof exosuits
L-Lets nerf it!

**Comment by Dorsisdwarf** [comment]
Fuck no

**Comment by Boredone** [comment]
As a note, this sounds alot like what Goon has their hyposprays like, so you'll probobly get some complaints about us becoming too much like Goon if this actually happens.

**Comment by paprka** [comment]
The hypospray is perfectly fine as is, it's very good and adding another thing to the list of 'lol emag it to make it dangerous' items is really fucking shitty.

**Comment by Miauw62** [comment]
Please make a thread in the feedback section, this doesn't belong on github.
