### ISSUE TITLE
Gauze is still applied even when it says you're already bandaged or aren't bleeding

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#7848]
Upon using gauze on myself (while I'm already bandaged):
"Kyra Gray's bleeding is already bandaged.
Kyra Gray isn't bleeding.
You begin applying the improvised gauze on yourself...
[waiting]
You apply the improvised gauze on yourself."

I'm pretty sure the bandaging operation should be cancelled in those situations.

**Comment by paprka** [comment]
It *should* be but I believe I hooked the bleedsuppress shit into medical stacks wrong.
