### ISSUE TITLE
Drones can pick themselves up (May involve Secways/Janicart)

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#7852]
You'll have to believe me on this one.
As a drone the HoS gave me a secway, my secway was jacked because I was picked up while on it, couldn't move because I lost my keys (dropped on my pickup) and then I got warped back (because the secway got pushed) and then suddenly I clicked myself to find out I was now holding myself.
(ignore my sprite, tis badminnery)

Screenshot of me WEARING MYSELF:
![dronewithitselfonhead](https://cloud.githubusercontent.com/assets/4043781/6311269/4d12031e-b958-11e4-84d0-ec5863f39cfe.PNG)

VVs (Unedited):
![vvs](https://cloud.githubusercontent.com/assets/4043781/6311341/512de9b2-b959-11e4-8824-f0ff4d32050a.PNG)

**Comment by Jalleo** [comment]
Were you able to move after doing this?

**Comment by RemieRichards** [comment]
Yes, once I held myself as an item I could move freely (since someone finally jacked the secway)

**Comment by paprka** [comment]
Well that's hilarious

**Comment by RemieRichards** [comment]
The obvious solution is either:
A: Prevent drones being picked up if they're buckled
B: Unbuckle the drone when it is picked up

I'd prefer A because I was atleast mildly saddened when somebody ran past and jacked my ride :S
