### ISSUE TITLE
Remove Alien Conversions from Experimentor

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7856]
@GunHog

It's reliable enough to be abused by players in a number of ways, including players intentionally aliening themselves specifically to kill antagonists. It's happening often enough for it to become a headache for the administration.

I don't want to have to start writing policies to restrict alien behavior when I think a code solution would be far more elegant and straightforward.

**Comment by mrpain666** [comment]
Yes please do this. This is getting ridiculous.

**Comment by GunHog** [comment]
I had a PR up for warning admins when the gas is created as well as logging for other related bad things. I would ask you to give that one a shot before merging the removal. However, if Admins are set on it being gone regardless, 7860 is there for immediate replacement.
