### ISSUE TITLE
Hulk makes undershirts (and possibly underwear) disappear

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7858]
Pretty much title. Going hulk makes your undershirt invisible, making you nude.

**Comment by Miauw62** [comment]
It should make your undershirt disappear, but your underpants should stay,
obviously.
Op 21-feb.-2015 09:33 schreef "paprka" <notifications@github.com>:

**Comment by Incoming5643** [comment]
has to do with the layer order. Same thing happens to people who augment their torsos, they can't see their body layer clothing

**Comment by RemieRichards** [comment]
Augments was intentional, I recall Aran complaining about random pants in different cases before I switched the layers of augments in the original PR.

If you can put them under the under(shirt/pant)s then be my guest.

**Comment by Incoming5643** [comment]
between this and how impractical #7837 is turning out to implement, I will probably take a good look at shuffling/add some new lays to update_icons soon
