### ISSUE TITLE
Bluespace Wormhole Generator has a Pin when it probobly shouldn't.

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#7859]
Managed to toss up a Bluespace Wormhole Generator in R&D, and was able to fire it without a pin from the armory anywhere I want, because it had an electronic firing pin.

Aka, unlike other stuff from R&D, the Portal Gun comes with an electronic pin.

**Comment by GunHog** [comment]
I believe it was intended...or at least I hope it was. The portal gun is not really a weapon more than it is a site-to-site teleporter. Cooperation from both Sec/Command and Supply is needed to get the research for it (combat shotgun).

If it was NOT intended, then it is an easy fix.

**Comment by paprka** [comment]
I don't think it needs a pin, I think it needs higher resource costs, they're fairly easy to mass produce from what i've seen

**Comment by Miauw62** [comment]
Yeah, it's not a weapon so I don't see why it would come without a pin.
