### ISSUE TITLE
foam is fucked up the ass #2: only one foam reaction can occur ever

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#7863]
@Cheridan 

Problem Description: only 1 foam reaction can occur ever apparently

What did you expect to happen: i expected a second foam burst from the second grenade

What happened instead: only the first ever foam burst happens

Why is this bad/What are the consequences: well foam is kinda worthless right now because of this

Steps to reproduce the problem: 
step 1. get 2 cleaner foam grenades
step 2. throw a foam grenade
step 3. observe foam
step 4. throw a second foam grenade
step 5. observe lack of foam

Server: local testing

Revision: latest build as of 2/21/2015

Possibly related stuff: testing shit locally for goonchem part 4,  haven't touched foam code yet

**Comment by WJohn** [comment]
@cheridan

**Comment by phil235** [comment]
Actually, the bug is that only one foam reaction can occur at any given time. After the reaction is over, you can start a new one.

**Comment by Iamgoofball** [comment]
this appears to be a local issue, nevermind

also @phil235 that wasn't the problem, no extra foam reactions could ever happen
