### ISSUE TITLE
HTML stripping should be replaced with HTML encoding.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#7865]
http://www.reddit.com/r/shittyprogramming/comments/2uaob7/i_wrote_an_htmlstripping_function_that_ended_up/
http://stackoverflow.com/a/1732454/1188035

Stripping HTML isn't great and results in headaches. Replacing it with HTML encoding is probably a far better solution.

**Comment by Menshin** [comment]
Presently, html stripping is done using two (forced) assumptions:
* everything between a _'<'_ and a _'>_' is potentially an html tag, so remove it
* everything between a _'http'_ and a _'://'_ is potentially an hyperlink so remove it (so to also catch https://)

So :
* _Everyone knows that 1 < 3 and, of course, 2 > 1_ => _Everyone knows that 1  1_
* _Please click that https link, it's really great : https://griffon.xxx_ => _Please click that griffon.xxx_

The stripping is done in one pass to avoid unnecessary string traversal and copying (but without any idea what's behind Byond's _findtext()_, it may not be the optimal way).

It's working fine, without significantly impacting performances.
If you feel like replacing it with another (better) system, feel free.

**Comment by Miauw62** [comment]
It's a dumb way and will cause issues, such as the ones you just demonstrated.
html_encode() has none of these issues and preserves user input without forcing them to use HTML escape strings.

**Comment by Menshin** [comment]
It depends, one can see displaying _<i> This a <b> escaped </b> <span style='lol'> sentence</span>_ equally dumb...

HTML_encode() is bound to be faster, since it's a built-in function, but it still won't prevent #7464 though.

**Comment by Miauw62** [comment]
yeah, but in your case it's dumb players typing OOC shit, they should be b&, this is not a code problem.

Also, it should prevent #7464. Those first two are not really related and can't be solved with either proc. They have to do with the fact that the formatting is always present in the string. I have an idea of how to solve this, but I have not had time to implement it. (Basically keeping the formatting in a separate list instead of keeping it in the message itself)

**Comment by Menshin** [comment]
> Also, it should prevent #7464. 

Please type an http link in Say", it's using ```html_encode()```.

**Comment by Miauw62** [comment]
Oh, I think I misunderstood that issue, then.
We could keep the link removal, I don't mind butchering sentences made by people that try to add in links.
The HTML stripping is the part that I don't feel very good about.

**Comment by duncathan** [comment]
we use html_encode() just about everywhere now afaik
