### ISSUE TITLE
Bad wiring in the AI Satellite.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#7876]
There is cabling under a wall in the AI sat, but cables that are under walls are not functional.
![badbad](https://cloud.githubusercontent.com/assets/4951579/6315891/ce26cf10-ba08-11e4-91e4-a944fde72bfb.png)

@Steelpoint

**Comment by Incoming5643** [comment]
Usually never relevant because an AI has to go for a LONG time to wind down the full SMES it starts with

**Comment by xxalpha** [comment]
Relevant because it can be removed.

**Comment by RemieRichards** [comment]
>There is cabling under a wall in the AI sat, but cables that are under walls are not functional.

Where do you get this idea? I see nothing of the sort in cable code or powernet code.

**Comment by xxalpha** [comment]
I learned this because of a recent PR of mine that was merged and had to be reverted because it broke powernets.

The picture is also proof. There is no power on that feed cable, "Available 0W".

**Comment by AndroidSFV** [comment]
So this is only an issue because the terminal for the SMES is under the wall. This should be resolved by a mapper.

**Comment by xxalpha** [comment]
No, it's the cable that connects that terminal that is the problem. I think the terminal would work fine under a wall.

**Comment by Miauw62** [comment]
what map?

**Comment by Steelpoint** [comment]
Box I assume. I'm guessing this is a result of the recent Sat re mappings.

**Comment by Chocobro** [comment]
that's box, yeah
