### ISSUE TITLE
Balance: Buff the Sleepy Pen

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7878]
Just a suggestion for changing around the sleepy pen a little:

-Give it the OPENCONTAINER flag (ie: can refill it)
-Remove the 'you feel a tiny prick' displayed message
-Increase cost from 4 to 7-8

This shifts it even more towards a stealth weapon while also allowing chemists, scientists, botanists, bartenders, and chefs to design their own chemical mixes to utilize against their targets. The increased cost are to balance out the fact you can re-use it multiple times and to discourage its use as an out and out combat weapon.

**Comment by WJohn** [comment]
Originally the sleepy pen used to be a two-use refillable item with chloral in it, while alternatively you could use the less expensive one-use non-refillable parapen with zombie powder in it. They were eventually merged because it was redundant and the sleepypen needed nerfing so it got the axe. Not sure how people would feel about this.

**Comment by Fox-McCloud** [comment]
Thanks for that tidbit, WJohn; always wondered why older codebases had two separate pens.

**Comment by paprka** [comment]
This is an extremely unfun instant win weapon. I don't think it should be buffed at all. I think, at most, it should be completely removed.

**Comment by Fox-McCloud** [comment]
Because security doesn't have a weapon that does the same exact thing or anything like that. I apologize for the sarcasm, but honestly, if you're going to stack the deck that hard against an antag, then it'll eventually reach the point where picking up a toolbox and bashing them on the head (then hoping the for the best) will end up being a better option.

Security has instantaneous melee and ranged weaponry at their disposal; parapen isn't even instantaneous and can't be unless a lot of work is put into it by making zombie powder (with the drinks beepsky smash and neurotoxin being glaring exceptions). Why should antags be singled out for hatred in this case?

I can understand being inherently against the change, and that's more than fine, but "instant win weapon" as an excuse isn't really valid when (1) it isn't (2) security does have instant win weapons.

**Comment by paprka** [comment]
I didn't know tasers muted you, knocked you out for an extremely long period of time, etc etc

**Comment by Fox-McCloud** [comment]
You do have a more than valid point on the silence, though I'd argue that's more of the reagent itself rather than an inherent problem with the pen (which, again, for all practical purposes is an unrefillable hypospray with large transfer capacity).

The other portions of your point go beyond a discussion that can be contained within the parameters of an "issue/suggestion" discussion, but I'd point out that antags are the primary motivators of rounds and that holding them back too much/making the role too difficult will inevitably lead to longer rounds with less activity, though this may be the goal that /TG/ has in mind.

As for why I make suggestions? We're both large codebases and both have large amounts of players; we try to create a balance game experience for generally most players involved in a given round/mode, and from what I can see, /TG/ largely seems interested in similar ideals; I'm merely making suggestions based on my own observations While still attempting to factor in pre-existing knowledge of how players tend to behave (differently) on both codebases.

**Comment by paprka** [comment]
Longer rounds and harder murderboner/antag roles are indeed what /tg/ has in mind. Traitors are meant to be stealthy. If they fail this, they should have really no easy way out. This is why the ebow was a bad item, you could rely on it for easy escapes. Parapen/sleepy pen ruins creativity. Stab someone with something that knocks them out, gg.

Easy traitor killing makes the round longer, because you can do your objectives in 5 minutes then you're basically done.

**Comment by Miauw62** [comment]
i'd much rather remove the sleepypen entirely, but that was vetoed by cheri.
making it refillable was vetoed by aran.

my ideal solution would be to make damp rags more available around the station so you can smother people with 5u of reagents.

**Comment by Fox-McCloud** [comment]
@Miauw62 

Fair enough, thanks for the info!

**Comment by Miauw62** [comment]
Maybe best to make a forum thread or something, I'm not entirely sure if this ought to be an issue report on github.

**Comment by Cheridan** [comment]
parapens 2 OP again thx 2 morphine gg
