### ISSUE TITLE
Borgs can't pass over holotape.

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#7883]
Its currently impossible for a borg to pass over the holotape, making it a pretty damn effective barricade against borgs.

Borgs can't break it either, I tried bashing it with the fire extinguisher as a mediborg on help and harm mode and still couldn't get past it.

**Comment by paprka** [comment]
The attackby proc is likely crap and borked but I don't know how to set them up because in other instances (windows, grilles) they're extremely spaghetti, poorly formatted, and copy pasted.

**Comment by Chocobro** [comment]
i can't get past holotape as a human. you sure the blocking isn't intended?

**Comment by Miauw62** [comment]
you have to walk to get past them
