### ISSUE TITLE
Stun batons won't fully charge.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#7887]
Batons when put in the charger won't fully charge and will be stuck at 99%.

Or at the very least the last percent charges slow as fuck for some odd reason.

**Comment by GunHog** [comment]
Did you turn it off beforehand? This might be related to the Paprika nerf that makes active batons drain their charge over time.

**Comment by Durkel** [comment]
Aw no, and I Wasn't aware that the pr went through. Still annoying and confusing at the very least
