### ISSUE TITLE
Accessing the notes and ban database causes massive lag

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7891]
If I search the bans I've made with the Banning Panel, it causes extreme lag. Same thing happens if I search players with notes using the Investigate Tab on Sybil.

The lag is usually very long, around 10 seconds, and affects everyone on the server.

**Comment by TheVekter** [comment]
I've always thought this was just due to the sheer number of notes/players. Maybe start culling players from the list after a certain amount of time?

**Comment by Fox-McCloud** [comment]
Yup, sounds about right; would be willing to bet Bay has the same exact issues.

**Comment by Ikarrus** [comment]
I should mention this also happens when we fetch the server logs

**Comment by paprka** [comment]
Might be a DB issue?

**Comment by Jordie0608** [comment]
This is about as fixed as it's going to get.
