### ISSUE TITLE
Frag12 Bullets: No Explosive

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7892]
Frag12 bullets are listed as a type of breaching round for 12 gauge shotguns. That said, in actuality, they're just a bullet that does a paltry 25 damage and weakens for a duration of 5. Given that these are effectively nitroglycerin bullets (referring to the reagents in them), shouldn't they be causing an explosion like the gyrojet bullets? Something on the order of:

/obj/item/projectile/bullet/frag12/on_hit(atom/target, blocked = 0)
	explosion(target, -1, 0, 2)
	return 1

**Comment by Miauw62** [comment]
anybody?

**Comment by phil235** [comment]
The frag12 bullet already causes an explosion (-1,0,1)

**Comment by Fox-McCloud** [comment]
Yeah, this was fixed by a PR that added in a way to make these bullets and added in the overstuffed bullets.
