### ISSUE TITLE
Carp Knockdown is Awful - Remove It?

### ISSUE THREAD

**Issue by Metacide** [tgstation/-tg-station#7905]
Opinion: Carp knockdown is common and means you die in most situations. This is not fun.
Suggestion: Remove knockdown chance from carp.

What do folks think of carp balance?

**Comment by dannno** [comment]
dupe

**Comment by Dorsisdwarf** [comment]
Carp were fine when knockdown was broken and didnt work.

**Comment by Chocobro** [comment]
i'd prefer it to just be a lower chance, if it even is changed.

**Comment by dannno** [comment]
dupe https://github.com/tgstation/-tg-station/issues/7394

**Comment by Metacide** [comment]
I would further that having even a relatively small chance of knock-down is unnecessary - if you're knocked down, you're dead by RNG and that's pretty crap. I think carp would be fine without knock-down, but if you wanted to make them tougher then they could have more health and stronger attacks - not RNG stuff.

With regards to @dannno I think 7394 is a specific bug, whereas this is a balance question in general.

**Comment by callanrocks** [comment]
Stamina damage, that would work. So would making them slower on a tile but keeping them fast in space.

**Comment by Miauw62** [comment]
this is a dupe :V

**Comment by Miauw62** [comment]
wait no its not danno, try to keep bugs and balance issues apart :/

**Comment by dannno** [comment]
dupe

**Comment by optimumtact** [comment]
Stamina damage for sure, fit's better with how other stuff works and is an understandable system rather than just oh, i randomly got knocked down

**Comment by RemieRichards** [comment]
Stamina damage, but only if the changelog entry for the change is:
"This just in, Space Carp have been found to have soporific saliva! don't let them bite!"

or something equally as fun but also mentioning the fact that carp will now tire you out.

**Comment by AlexanderUlanH** [comment]
Carpotoxin is used to make zombie powder, so soporific space carp makes sense.  Adding high staminaloss to carptoxin would be a pretty good fix.

**Comment by dannno** [comment]
no. low.

**Comment by AlexanderUlanH** [comment]
It'd be more interesting high, and more balanced too, since it's such a rare ingredient.  You can get maybe 20 units if you get equipped, go carp hunting, find a kitchen knife, butcher the carp, grind the carp, and filter out the nutriment.  It would be easy to balance it for carp bites by just making carp bites a low dose.

**Comment by dannno** [comment]
i misread. I thought you meant every carp bite would have high stamina loss.
