### ISSUE TITLE
Clown stamp cannot be used by traitor clowns

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7909]
I keep meaning to bug report this, and here we are. The clown's rubber stamp cannot be used by non-clowns. But since traitor clowns "overcome their clownish nature" or whatever, they don't count as clowns, and they can't use their stamp.

WHY THIS IS BAD: Potential meta: "Hey clown, stamp this paper or else I'm executing you."

**Comment by RandomMarine** [comment]
"I took mutadone. Honk."
