### ISSUE TITLE
Balance: NOREACT on Shotgun darts

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7912]
Fairly straightforward; shotgun darts have the "NOREACT" flag attached to them. The big nasty thing you can easily accomplish here is putting 1 unit of sugar, potassium, and phosphorus in a shell then loading the rest of it up with fluorosulfuric acid. Even if the target is immune to darts, it still hits them then immediately sprays acid smoke everywhere.

**Comment by Chocobro** [comment]
feature imo. useful for clever tators.

**Comment by dannno** [comment]
that sounds like an awesome feature

**Comment by Lumipharon** [comment]
smoke doesn't react in mobs afaik, so shouldn't that not happen?

**Comment by Delimusca** [comment]
they [handle reactions](https://github.com/tgstation/-tg-station/blob/master/code/modules/projectiles/projectile/bullets.dm#L129) on hit, for some reason.

**Comment by paprka** [comment]
Darts are useless otherwise, even as tranq rounds they take forever to set up.

**Comment by Fox-McCloud** [comment]
@Lumipharon 

Delimusca pretty much covered it; the reaction occurs and smoke literally goes everywhere; this would probably be less problematic if smoke was Goon style as opposed to persistent---or if the darts just didn't handle reactions on hit, regardless of if they're blocked or not.

**Comment by PKPenguin321** [comment]
thought this was a PR at first and was like "fuck yeah that's the coolest feature ever"
pls don't remove this i want to make ghetto explosive rounds with water and potassium

**Comment by Fox-McCloud** [comment]
@PKPenguin321 

Explosion isn't big enough to do anything, I believe; nitro may be a different story.

**Comment by dannno** [comment]
if someone wants to go through the effort of making nitro shells, they deserve this functionality

**Comment by Fox-McCloud** [comment]
I'm more concerned about the polyacid smoke shells than anything

**Comment by paprka** [comment]
Feature, getting a shotgun and darts is hard on /tg/, not something that we should really be concerned about. Preemptive fun removal is bad!

**Comment by Fox-McCloud** [comment]
@paprka 

I would normally agree, but the 2 pre-spawned pieces of silver pretty much ensures a scientist can get 3 improvised shotties up in 15 minutes or less, and that's assuming he does everything himself.

**Comment by Lumipharon** [comment]
There is nothing wrong with this, regardless. 

I was pointing out how this worked with syringe guns yesterday, really the only issue is that acid is still pantsu on head retarded level of robust. Seriously, it applies to EVERY BODYPART, and because of how smoke works, will most likely do it 15 times to you, and delete everything you're wearing.

Basically, someone fix acid, leave this alone.

**Comment by Miauw62** [comment]
Completely intended.

**Comment by PKPenguin321** [comment]
U S A
U S A 
U S A
