### ISSUE TITLE
Unholy water deals brain damage to cultists

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#7915]
This has caused many problems, mainly not being able to invoke runes because you're a gibbering idiot.

**Comment by Mandurrrh** [comment]
Its part of the lore. I did do a test run to turn it down a notch but it is so slow you would never see the effects in a standard cult length round.

**Comment by paprka** [comment]
Isn't that the whole point? For the chaplain to counter cultists and nullify their ability to use runes?

**Comment by Xhuis** [comment]
I'm talking about __un__holy water, not holy water. Unholy water is the result of hitting someone with holy water ingested with a tome. It helps cultists in every other regard.

**Comment by paprka** [comment]
My bad I didn't read sorry

**Comment by Mandurrrh** [comment]
No but go on the wiki and search it. Unholy water has always dealt braindamage. Its part of the lore. You get healed and speedy but brain damage.

**Comment by Miauw62** [comment]
Make a feedback thread, I'm getting tired of our issue tracker being clogged by hundreds of feature requests and balance issues.
