### ISSUE TITLE
Process() speed is insane (bugged stunbatons)

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7916]
Due to the same issue as beepsky running around fast I think (https://github.com/tgstation/-tg-station/issues/7598)

Stun batons drain their charge INCREDIBLY fast at the start of the round, this is really fucking over sec officers. I honestly hadn't anticipated this bug, so I might revert the feature or comment out the process stuff until this is resolved. Rather important we get this fixed, if not, I need to fix this so officers aren't fucked over.

**Comment by phil235** [comment]
I tried to repriduce it and the batons I spawned at roundstart were fine.

**Comment by paprka** [comment]
Try running about for a bit with it on in your belt.

**Comment by phil235** [comment]
Takes 5+ mins to lose 10 % of the charge, didn't see any difference at the beginning of the round.

**Comment by paprka** [comment]
Something weird happened on the server then

**Comment by paprka** [comment]
Okay no this still happens but it's a rare case and not easy to reproduce.

**Comment by Lumipharon** [comment]
Can this cause power to drain from the SMES's faster at round start? Because if so that could be a rather significant issue.

**Comment by paprka** [comment]
I didn't consider that but expect singulo 'accidents' i guess
