### ISSUE TITLE
Balance: Prevent Cultists from summoning Nar'sie before their Sacrifice objective is complete.

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7921]
It makes logical sense after all. Why would Nar'sie grace the cultists with his presence if they can't even sacrifice one guy? Perhaps switch the objective order around with the sac objective first and the summon objective second so the cult doesn't get confused by this. It's hilariously easy to summon Nar'sie with the manifest ghost rune so this would help prevent abuse of that.
Issue is further highlighted here: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=2981

**Comment by Dorsisdwarf** [comment]
Please don't fill the issue tracker with minor feature requests like this. bring it up in #coderbus or just make a thread
