### ISSUE TITLE
MAP: ProtectStation should be on the High Risk module table

### ISSUE THREAD

**Issue by mrpain666** [tgstation/-tg-station#7923]
For reference, this module adds the following:
4. Protect the space station against damage. Anyone you see harming the station is to be no longer considered human, and is a threat to the station which must be neutralized.

This would make something as minor as breaking a bar window a lethal offense by a silicon, and usually does.

This lawset is currently with the "not so bad in the right hands bretty ok" table in the ai core:
http://imgur.com/HGwKYFk

Considering admins have issued warnings against people who upload this as a non antag, ideally it should be placed on the "High Risk module" table aka "DONT TOUCH THIS SHIT SON UNLESS YOU'RE AN ANTAG" table.

**Comment by mikecari** [comment]
I agree, Protectstation is really harmful most of the time. At least Robocop/PALADIN usually leads to a safer station whereas protectstation just forces the AI to kill people that damage shit in an emergency.

**Comment by mrpain666** [comment]
If someone gets dunked by Robocop or PALADIN they probably had it coming. That's why I'd like to leave those alone, yes. I think people have vastly underestimated the robustness of ProtectStation.

**Comment by Alek2ander** [comment]
Neutralized != Killed. Unfortunately, the AI is usually happy to murder whenever it can, so eeeeh.

**Comment by as334** [comment]
For the record that's my corpse sitting in the upload, and we died because the AI got One Humaned, but i agree that it should be in the antag pile.

**Comment by mrpain666** [comment]
Yes that screenshot sucks at what I wanted it to do, which was show everyone exactly where in the upload it was, but I think everyone knows where it is already. Oh well. I'll change it out tomorrow.
