### ISSUE TITLE
Can't activate grenades with TK.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#7926]
In the title, tried to activate my 5 second timer grenade on the ground from a distance with the idea of having the now active grenade chase its target.

But the grenade would not activate and was simply picked up by someone else after i tried to get the grenade back.

**Comment by phil235** [comment]
It's not just grenades, any action done by clicking the object in your hand cannot be done with TK (toggling lamps, activating esword, etc). I'm pretty sure letting TK activate things would be pretty OP though.

**Comment by Miauw62** [comment]
Eeeh, not sure if this is a bug or not.
@tgstation/commit-access ?

**Comment by quaggaman555555** [comment]
If you want to go into a realism discussion, then it would be possible to activate a grenade with TK, as they are made of a bunch of small parts, and with practice, you could influence the pin to come out, while holding the rest of it in place, then have it chase someone. Or you could just use TK to push a button while holding it in place, if that's how it's activated.

**Comment by dannno** [comment]
realism has never ever mattered

**Comment by phil235** [comment]
Actually you can toggle things via telekinesis, it works for closets. The bug is just that the attack_self_tk proc hasn't been added to other relevant items like lamps and grenade.

**Comment by Razharas** [comment]
Just add attack_self as default attack_self_tk
