### ISSUE TITLE
Feature request: no more pixel-accurate clicking in inventory

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#7927]
When you take something out of your pocket-slot, you don't need to click on the object, just the slot, the corner of it or anywhere on the slot.

When you take something out of your backpack or belt, you have to click precisely on the item, which can be difficult (and confusing because inconsistent), especially with some very small objects like screwdrivers, telescopic batons, micro manipulators, etc.

Could it please be made possible that backpack-slots work like other intentory-slots like pockets?

**Comment by quaggaman555555** [comment]
Please make this a thing. It would be so helpful, as I always have trouble getting things out of backpacks and getting manipulators out of RPEDs is annoying because of their size.

**Comment by phil235** [comment]
This isn't easy to do because the storage is one single entity, each square is not an object, the whole thing is.

**Comment by naelstrof** [comment]
Got me killed when I tried to pull out a syndicate pistol and happened to click within the trigger guard.
Did a whole lot of nothing when expecting otherwise.

**Comment by Razharas** [comment]
Interface rewrite please

**Comment by paprka** [comment]
>Interface rewrite please

**Comment by Lumipharon** [comment]
Couldn't you just add an alpha layer or whatever to the sprite, so it's not so tiny?

**Comment by paprka** [comment]
You mean every single sprite? No thanks, clicking on something in a pile and picking something else up because there was an alpha layer is REALLY ANNOYING.

**Comment by Iamgoofball** [comment]
@paprka  maybe adding it as an overlay to the object upon being put in a box/backpack and then removing it when it's taken out would work?

**Comment by paprka** [comment]
seems expensive

**Comment by Lumipharon** [comment]
I meant only the inhand/container sprite, but yeah, I don't know if such a thing is practical.

**Comment by Miauw62** [comment]
That's probably not practical, sadly.

**Comment by JJRcop** [comment]
You can also use the coordinates from the mouse click, I was going to do that but then I didn't.

**Comment by kingofkosmos** [comment]
This was apparently much more complex than what I originally thought.

**Comment by Aranclanos** [comment]
leave it open pretty boy, its an issue still, might not be easy but some day it needs to be done.

**Comment by kingofkosmos** [comment]
Aight.
