### ISSUE TITLE
The MC sometimes ticks very rapidly at roundstart.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#7936]
#7598
#7916

For reasons unknown, the MC sometimes ticks very rapidly at roundstart, causing bots to move quickly, stunbatons to drain quickly, etc. This has not yet been reliably reproduced.

**Comment by paprka** [comment]
Don't worry guys we can maintain the carn MC :^)

**Comment by TheVekter** [comment]
Remind me again why we continue to use something that the creator of which has fucked off permanently and refuses to maintain?

**Comment by Miauw62** [comment]
Because the previous system was worse? The old MC had more bugs and was
harder to maintain than this.
