### ISSUE TITLE
Electrode jitter animation allows for chainstunning (turrets

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7943]
@phil235 

Due to the electrode jitter animation on hit, turrets with electrodes now chainstun indefinitely.

**Comment by phil235** [comment]
can't reproduce with standard AI chamber and AI upload turrets.

**Comment by phil235** [comment]
will probably be fixed by #7986

**Comment by phil235** [comment]
Has someone noticed this bug happening lately?

**Comment by Jordie0608** [comment]
Yeah this was fixed.
