### ISSUE TITLE
Sorium blobs are a waking nightmare to play

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#7948]
Sorium is a chemical that flings shit, a sorium blob will fling everything, including itself, every time it attacks.

That resource node placement? It's out of range now.

Your well protected core? Flung into a hallway or worse/better, floating through deep space.

It basically makes planning impossible unless you never manually attack people. Please either make sorium not affect blob structures or remove sorium blob

**Comment by WJohn** [comment]
I think it'd be pretty awesome if sorium only affected things that weren't the blob. Hitting someone could fling them away, welding tanks and items might be moved around for being near you etc.

**Comment by dannno** [comment]
jesus christ goofball can you just blacklist all the VERY OBVIOUSLY NOT FIT FOR BLOB chemicals already like what are you thinking

**Comment by Iamgoofball** [comment]
flinging itself is a bug, will fix
