### ISSUE TITLE
Admin: Manage Assistant Slots

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7952]
Now that we have assistant caps, it'd be nice if admins were able to edit how many slots were open through the Manage Job Slots verb.

Right now, there's no way to edit it without hopping into the job controller.

**Comment by Ikarrus** [comment]
@paprka

**Comment by paprka** [comment]
Oh, yeah, I can enable this if the assistant cap isn't unlimited.

**Comment by Ikarrus** [comment]
Pap, can you also make it so that if all other jobs are filled, the assistant cap is ignored?
