### ISSUE TITLE
Blobbernaut Death Animations Loop Forever

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#7953]
Title says it all
Should be easy to reproduce, seems to occur most often in space, but it's also happened indoors

Not sure what causes it - Animation goes forever

**Comment by Incoming5643** [comment]
probably related, but if you don't physically see a blobbernaut die, the death animation will play as soon as it comes into view regardless of when it actually died

**Comment by RemieRichards** [comment]
this is probably life()'s fault, setting icon_state = icon_dead multiple times, which is no issue with non animated death states.

**Comment by GunHog** [comment]
I have seen this happen when the dead blobbernaut is moved by something.

**Comment by phil235** [comment]
When the mob starts an animation like nograv floating, it reloads the icon.
