### ISSUE TITLE
Chloral hydrate is lethal at 14u now.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#7956]
![2015-02-24 02_19_26-space station 13](https://cloud.githubusercontent.com/assets/6583225/6347305/c3bf99ca-bbcb-11e4-8e79-ad8b4662a20f.png)
#6329 Changed it on accident when implementing metabolization_rate.

Before that, it metabolized at 0.6u per tick, requiring 41u to kill somebody. Now it's 0.2u and only needs 14, one syringe kill.

**Comment by phil235** [comment]
I'm starting to wonder whether the 0.6u per tick was intended when looking at its code. But nevertheless I'll change it back to its original value.

**Comment by RandomMarine** [comment]
It was intentional. https://github.com/tgstation/-tg-station/commit/4dec21688731ab640130b4fcab609ec1ea3d65a8

**Comment by pudl** [comment]
just to say, with old metab just 20u was lethal. so the "one syringe to kill" is still an issue
