### ISSUE TITLE
Ties missing from Autodrobe

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#7960]
Not a bug, but an issue and probably some sort of oversight - ties are no longer available from the Autodrobe, nor the Clothesmate.

**Comment by Chocobro** [comment]
issue incorrect, ties are still inside the clothesmate. autodrobe never had them.
![ties-clothesmate](https://cloud.githubusercontent.com/assets/5677255/6352886/bcbb64a2-bc3d-11e4-9ba4-47f569c56d14.jpg)

**Comment by AnonymousNow** [comment]
Then why do I remember the ties being in the autodrobe? And why can't I find the ties in the Clothesmate?

I'll have to check this again when I get back.

**Comment by Chocobro** [comment]
your memory may be failing you. alternatively, it's a *~magical mid-round error~* that can't be reproduced.

**Comment by TZK13** [comment]
No he's correct, they used to be in the autodrobe. I was the one to originally put them in the autodrobe in #5648 and then I moved them to the clothesmate in #7643.
