### ISSUE TITLE
Holotape has many bugs

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#7961]
@paprka
* It can be destroyed with ranged and melee weapons but neither give any feedback whatsoever (no animation, no message).
* Clicking an airlock to tape it also activates the airlock. With windows the mob attacks it. 
* Trying to tape an airlock during the holotape cooldown gives no feedback.
* You can spamclick an airlock to place multiple tape on one airlock.
* simple animal and slimes cannot pass holotapes.
* simple animal, slimes, humanoid alien, and larvas cannot attack holotapes.
* You can place a tape line over a tape line (it won't actually be placed but the messages you get at start and finish are the standard ones)
* You can place tape over windows but the tape is then inaccessible and can't be removed/attacked w/o first destroying the window.
* Multiple mob can be on the same tape tile, they don't swap places or push each other, they basically stack like ghosts.
* Trying to move (via push, pull or grab) anything that isn't a mob onto the tape causes a runtime error (shown below).
* A mob on top of a holotape can't be hit a projectile (It only hits the tape), but the mob can fire projectiles at his enemies.

Usability issues: 
* Can't delete the holotapes with the tape projector (like the janitor's sign projector). 
* No clear way to cancel taping after starting it, you have to move the projector or click it when it won't actually place the tape. 

Consistency issue:
* You can make a tape line pass through a taped airlock, you can make two tape line cross, but you can't tape an airlock if there's a tape line on its tile.
* Placing overlapping tape lines (both vertical or both horizontal) is inconsistent. if you start your second line on an empty tile and finish it on a tile where the first tapeline is then the empty tiles will get a tape. But if you started on an occupied tile and finished on an empty one then no tape is placed, and in both cases you get the same standard successful messages.

Runtime:

runtime error: undefined variable /obj/structure/computerframe/var/m_intent
proc name: Bumped (/obj/item/holotape/Bumped)
  source file: holotape.dm,157
  usr: 0
  src: the security holotape (/obj/item/holotape/security)
  call stack:
the security holotape (/obj/item/holotape/security): Bumped(the computer-frame (/obj/structure/computerframe))
the computer-frame (/obj/structure/computerframe): Bump(the security holotape (/obj/item/holotape/security), 1)
the floor (191,132,1) (/turf/simulated/floor/plasteel): Enter(the computer-frame (/obj/structure/computerframe), the floor (191,131,1) (/turf/simulated/floor/plasteel))
the computer-frame (/obj/structure/computerframe): Move(the floor (191,132,1) (/turf/simulated/floor/plasteel), 1)
Alaina Lloyd (/mob/living/carbon/human): PushAM(the computer-frame (/obj/structure/computerframe))
Alaina Lloyd (/mob/living/carbon/human): Bump(the computer-frame (/obj/structure/computerframe), 1)
the floor (191,131,1) (/turf/simulated/floor/plasteel): Enter(Alaina Lloyd (/mob/living/carbon/human), the floor (191,130,1) (/turf/simulated/floor/plasteel))
Alaina Lloyd (/mob/living/carbon/human): Move(the floor (191,131,1) (/turf/simulated/floor/plasteel), 1)
Alaina Lloyd (/mob/living/carbon/human): Move(the floor (191,131,1) (/turf/simulated/floor/plasteel), 1)
Alaina Lloyd (/mob/living/carbon/human): Move(the floor (191,131,1) (/turf/simulated/floor/plasteel), 1)
Alaina Lloyd (/mob/living/carbon/human): Move(the floor (191,131,1) (/turf/simulated/floor/plasteel), 1)
Phil235 (/client): Move(the floor (191,131,1) (/turf/simulated/floor/plasteel), 1)

**Comment by paprka** [comment]
:^DDDD

**Comment by Jalleo** [comment]
More bugs kudzu is prevented from spreading when this tape is put down.
