### ISSUE TITLE
Gulag shuttle doesn't go back to the station

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#7962]
When the gulag shuttle is at Labor Camp and you try to send it to Fore Bay, it ends up back at the gulag. (I'm pretty sure this is actually a bug -- it's possible the AI was doing it as it was malf, but it didn't say anything on the matter.)

**Comment by phil235** [comment]
can't reproduce. Can we have more details? Was it on sybil or basil?

**Comment by bgobandit** [comment]
This was on Sibyl, a few hours ago

**Comment by francinum** [comment]
@bgobandit When the shuttle is inflight, you can change the destination, is it possible there was someone doing that?
