### ISSUE TITLE
Taser Stuns are too Long

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7967]
Fairly simple oversight.

Tasers previously stunned+weakened you for 5 cycles; now, however, they behave differently:

-They immediately stun you for 5 cycles, then, after roughly 2 seconds it will weaken you for 5 cycles--meaning the total incapacitation time is 6-7 cycles.

This was handled in the door shocking animation by making the weaken state last 3 instead of 5.

**Comment by phil235** [comment]
my bad

**Comment by paprka** [comment]
I would prefer if the jitter just played while they were on the ground, weakened, like it was before -- so this wasn't an issue at all

**Comment by Fox-McCloud** [comment]
*shrug* the delayed effect is pretty cool, but it does also mean snowflaking out changes to the electrode every time it changes.
