### ISSUE TITLE
Non-clowns can use the clown stamp

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#7971]
title as description

**Comment by optimumtact** [comment]
https://github.com/tgstation/-tg-station/pull/7922 caused by this

It's probably not worth even fixing, stupid clown gimmicks

**Comment by bgobandit** [comment]
goddamnit fucking clowns

**Comment by phil235** [comment]
Why was the clown stamp restricted to the clown? Afaik anyone can use the stamp of any head of staff, so this is odd.

**Comment by Dorsisdwarf** [comment]
So that he could stamp things and go HONK! and if you saw something with HONK! HONK! HONK! all over it you knew a clown was in the area, and that it was time to get out the big game rifle.

True facts.

**Comment by Miauw62** [comment]
i don't see why other people can't stamp with the clown's stamp.
what next, are we going to restrict the bike horn to clowns?
