### ISSUE TITLE
Suggestion: Num pad limb targetting

### ISSUE THREAD

**Issue by paprka** [tgstation/-tg-station#7973]
![clip 2015-02-24 at 05 10 06](https://cloud.githubusercontent.com/assets/7247232/6363012/03d616b6-bc48-11e4-99af-323d5149b404.png)

Please. Pixel hunting is awful.

**Comment by RandomMarine** [comment]
Does the numpad do anything currently? Who am I kidding, even if it did, who uses it?

**Comment by paprka** [comment]
literally nobody

**Comment by Boredone** [comment]
Um, the numpad is actually kinda useful? It has most of the shortcuts and works as arrow keys.
1/End=Toggle Throw
3/Pg Dn=Use
7/Home=Drop
9/Pg Up=Swap Hands
Don't think 5 does anything though.

**Comment by paprka** [comment]
Then make it only function as targetting in hotkey mode?

**Comment by Incoming5643** [comment]
kind of unfair for laptop players who don't have numpads

**Comment by paprka** [comment]
I have a numpad on my laptop.

I don't really care about fairness. Get a numpad. Usability being shit because some people don't have numpads (it's 2015 holy shit) isn't really my concern.

**Comment by as334** [comment]
I actually use the numpad because the normal keys for 4,5,+,=,-,_ all don't work, so i have to use the numpad ones.

**Comment by paprka** [comment]
how is that a game problem

**Comment by Menshin** [comment]
> Don't think 5 does anything though.

You mean : anything except _allowing Mechs/Janicart/Chameleon suit to jump to the next z_level at will ?_
Fixed though.

**Comment by AlexCrimson** [comment]
Could you not just make the UI element bigger?

**Comment by Fox-McCloud** [comment]
All the more reason SS13 needs support for full key+mouse customization

**Comment by RemieRichards** [comment]
Controller support when.
Kinnect support when.
Wii Motion Controller when.
DDR Dance pad when.
Oculus support when.
Heartbeat monitor support when.

**Comment by Dorsisdwarf** [comment]
Requesting closure due to inactivate denied feature request by banned contributor

**Comment by AlexCrimson** [comment]
He is banned from the game, not from coding, i thought.

**Comment by RemieRichards** [comment]
He's banned from the community.
Forums - [x]
Game - [x]
Contributing to the codebase - [x]

**Comment by dannno** [comment]
how is he going to fix conflicts in his open (and good) PRs

**Comment by Dorsisdwarf** [comment]
Requesting closure again, @Cheridan .

Also this has the wrong feature request tag
