### ISSUE TITLE
Xeno HP got lowered to 1/10th what it was.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#7974]
A queen's current and max HP starts at 25, meaning you can crit it with a single hit from a welding tool or a single shot from a laser gun. This was originally 250. The same applies to all other xenos (except larvas) meaning they're all very weak right now.

**Comment by WJohn** [comment]
Oh. Okay then.

**Comment by Steelpoint** [comment]
"Blame SoS" is pretty ambiguous.

**Comment by PKPenguin321** [comment]
Guessing it means it's a config issue, which SoS handles on the live server, not hardcoded in our codebase

**Comment by Jordie0608** [comment]
It's still 250 in the code, this isn't a bug.

**Comment by WJohn** [comment]
If this is something SoS did for testing or for fun, then it's not an issue and can be closed.
