### ISSUE TITLE
Request: Age Restrictions for Antagonist Roles

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#7978]
Feature Request

Similar to how we restrict new players from playing heads or sec, I'd like to restrict them from playing antags as well.

Not just so newbies don't play as them and ruin everything, but so it can act as a deterrent to people ban evading all the time.

I'd like to suggest at least a week before they can play any antag, and two weeks for team antag roles.

**Comment by Steelpoint** [comment]
:+1:  x :100:

**Comment by paprka** [comment]
i disagree, a week to learn the game would be better

**Comment by Jalleo** [comment]
I think there already is a limit but i cant confirm

**Comment by AlexCrimson** [comment]
Yeah id say apply it to all antag roles. Hell, id also like a way to encourage new players to read the specific wiki guides when they first enable each antag role. Maybe have a "?" next to each role which directs them to the appropriate guide.

**Comment by mikecari** [comment]
+1 to this, about damn time.
Too many shite nuke ops and cultists ruining everything.

**Comment by TZK13** [comment]
Two weeks is by no means a long enough time for nukeops and cultists to git gud. Seriously, the first time you're either of those you're almost certainly gonna be shit.

Besides any sort of wishful thinking that this will improve antagonist play I still support this for it possibly deterring ban evaders.

**Comment by Ikarrus** [comment]
>Seriously, the first time you're either of those you're almost certainly gonna be shit.

Well, there's being shit, and then there's not knowing basic controls like how to use internals or jetpacks.

**Comment by optimumtact** [comment]
This has to be age of actual time on server as well

**Comment by InboundAzimuth** [comment]
Could there possibly be some way that the player, after X amount of time on the server (and are chosen for an antag) have to go through some sort of 30 second exam to 'teach' or see if they are capable of doing it? I don't know exactly, but some sort of age restriction would be amazing.

**Comment by RemieRichards** [comment]
@InboundAzimuth you can run any code in existence based on how long they've been on the server.
this includes some form of segregated teaching.

**Comment by InboundAzimuth** [comment]
@RemieRichards It might be a bit cumbersome for a new player, but it'd be helpful against griefing (accidentally). The only problem with the test would be what would happen if they'd fail? I didn't really think that far. But I do understand.

**Comment by RemieRichards** [comment]
@InboundAzimuth I'd assume if they fail their trial their trial period would simply reset? placing all restrictions back on them (no antag/limited job choice) and giving them the same period of time to learn before repeating the test.

**Comment by InboundAzimuth** [comment]
@RemieRichards So they'd be let back into the world, assuming Assistant. Which means they might have a chance that they could tell the rest of the station (griefing wise) that there are syndicates, or traitors, or whatever the random number generator has chosen. Or would it be that every so often that they'd get a popup pre-round for a test, which would make more sense.

**Comment by RemieRichards** [comment]
@InboundAzimuth Oh no, I wasn't implying putting them back into the SAME round, if they wanted back into that round it'd be observer only, which only risks them blurting out in OOC (which anyone can do anyway)

A Pre round popup might be interesting.

**Comment by InboundAzimuth** [comment]
@RemieRichards Just like what Ikarrus stated of about a weeks length before an antag round is available. Though I feel like a week would be a bit lengthy for a new player that might have grasped the game already. 
Perhaps maybe 3 days until the popup would appear,then maybe every 5 rounds (if they would fail), it would pop-up again, taking the test again.

**Comment by RandomMarine** [comment]
A questionnaire goes too far, and there's too many finer details that players need to learn to become an "effective" operative or cultist.

All the answers would just end up copypasted on the wiki, regardless, defeating the point. Just a hefty age requirement on ops or cult would be good for now, we can see how it plays out.

**Comment by RemieRichards** [comment]
@RandomMarine I suppose all tests can be cheated on.

**Comment by InboundAzimuth** [comment]
@RandomMarine Of course the age requirement for something like nuke-ops would have to be longer But something like traitor there could be a lot lesser of a time. If you make the tests more vague and having to understand more. Things that are not on the wiki, skill based or environment/position based questions.
Something like 'You're in X ENVIRONMENT, surrounded and being attacked, what do you do' Something that would have them think more and would not be written on the wiki.

**Comment by RemieRichards** [comment]
Could also have it be a physical test, as in, actually put them into a situation and assessing their score?
(Obviously that'd require a few things, Better AI for one)

**Comment by InboundAzimuth** [comment]
Maybe assess their actual movement and such inside of the game. Taking note of the certain things that they do. A checklist of sorts that they don't really know about, I don't know. Simple things:
Buckling to chairs, unbuckling, harm intent, doors, deconstruction. Something that would set off some flags before the test would be appearing. To be absolutely sure that they are ready?

**Comment by RandomMarine** [comment]
@InboundAzimuth, again, someone -will- just go check the code and write a GUIDE TO DA QUIZ on the wiki. It's inevitable. And just how do you answer such a question from an objective stance? Stunprod? Yaketysax away? Disarm spam? Secret monkey technique?

Trying to turn the subjective quality of being robust into a bunch of specific checks for specific behaviors before enabling certain roles sounds like a massive headache, and would only serve to actively encourage powergaming in favor of roleplay.

**Comment by InboundAzimuth** [comment]
@RandomMarine And that's understandable, sadly people would do that. But... There should be a way to get around it. Maybe what Remie said, physical test though AI is not that great.

I guess the time lock would be the best overall. Though couldn't they just idle being an assistant somewhere to rack up time?

**Comment by Lumipharon** [comment]
Team based, and lone antag positions need much longer timers, since a complete noob can basically fuck everything up for the team/round.

Traitor and ling, it's not such a big deal if you fuck up.

**Comment by RandomMarine** [comment]
My personal suggestions.

0 days for traitor.
5 days for ling.
Two weeks for headrev, wizard, or roundstart cultist. (Converted revs and cultists shouldn't have an age req. Perhaps a lowered age threshold for raging mages? Since just one dying doesn't end the round.)
Three weeks for nuke op or blob.
Full month for malf. (Do we still have the issue of people who have malf enabed spawning as malf AI before they have the age requirement for AI in general? This would solve that.)
