### ISSUE TITLE
Podpeople/Slimepeople not using mutantcolor

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#7990]
While trying to figure out how to not starve to death as a jelly-person, I noticed that pod/slimepeople are supposed to use mutant colour according to the code I saw. Yet they always seem to be ugly-gray/uncolored ingame. Can someone have a look at that?

I just want to be a beautiful flower.

**Comment by Incoming5643** [comment]
You have to set your mutant color on your preference screen to have color as those races, but the pod person thing is legit a bug by itself, but was already reported.
