### ISSUE TITLE
the air alarm safety override malf power literally does nothing

### ISSUE THREAD

**Issue by mrpain666** [tgstation/-tg-station#7991]
What is this thing supposed to do, exactly? Automatically configure air alarms to flood? Make a button on the air alarms that does so?

I tried it just now and I couldnt see any difference after using it.

**Comment by phil235** [comment]
From #7615 : 
>Air alarms, when emagged or overriden, will gain the Flood environmental mode. This disables vent pressure checks and turns off scrubbers, which causes any gas mix in the pipes to start chugging out.

**Comment by Xhuis** [comment]
There's a button on them. It disables their safeties and lets you use the environmental mode. When I tested there was no problem with it, but let me look again now.

**Comment by mrpain666** [comment]
Maybe I wasnt using it correctly then.

**Comment by Xhuis** [comment]
You gain a verb in the Malfunction tab so atmos techs can't constantly meta-check the air alarms - you have to use the verb first.

**Comment by mrpain666** [comment]
What's that verb called?

**Comment by Xhuis** [comment]
Disable Air Alarm Safeties

**Comment by mrpain666** [comment]
Well, if you've checked everything and everything is working as intended feel free to close this. Maybe I was just using it incorrectly and need to git gud. At the time I saw this I was literally doing 4 things at once, in typical malf AI fashion, so I may have overlooked things.

**Comment by mrpain666** [comment]
Closing this now as apparently it works as intended.
