### ISSUE TITLE
Metal Foam Atmos Tank Spray Doesn't Work

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#7993]
Grab a tank, spray a tile with metal foam and it creates a single tiles blip of foam (not even metal) and then pops.

**Comment by RemieRichards** [comment]
Duplicate, this issue is with Reagent Foam not correctly reacting for the Atmos Tank/Mister objects.
thankyou for the report.

**Comment by Fox-McCloud** [comment]
Oops; sorry! Didn't notice the other report.

**Comment by RemieRichards** [comment]
No worries Fox.
