### ISSUE TITLE
Jetpacks still can't be used as internals

### ISSUE THREAD

**Issue by mikecari** [tgstation/-tg-station#7995]
I thought #7914 was supposed to fix this bug but it didn't seem to work.

**Comment by paprka** [comment]
xxalpha's problem now then

you sure the server has updated?

**Comment by TZK13** [comment]
Shurikens are in which was merged after that PR so the server seems to be updated.

**Comment by xxalpha** [comment]
Did you not test your fix @paprka?

**Comment by paprka** [comment]
:^)

Since I'm still not banned I'll actually fix this I guess, but yeah, those were the only lines connected to the UI thing that I saw. You did repath like, a ton of tanks, so I'll look into it more.

**Comment by xxalpha** [comment]
I'll give you a useful link.
