### ISSUE TITLE
Rods OP, please nerf

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#8005]
So it turns out you can throw metal rods now, and impale the shit out of people. While hilarious, it's pretty bizarre, and rather strong. It's the new floortiles of ghetto combat.

**Comment by mikecari** [comment]
Pretty much this, I see greytiding scum throwing rods all around because it's OP.

**Comment by Lumipharon** [comment]
25 brute on embed, supposedly. That's strong as shit.

**Comment by paprka** [comment]
disposal chute experiments engage

**Comment by RemieRichards** [comment]
I'll move the damage done from embedding to a variable and lower it for rods.
I will however adjust explosion code so that it forces the value to be higher, based on the size of the boom

**Comment by phil235** [comment]
How are rods even managing to embedded themselves, they're not sharp or anything.

**Comment by RemieRichards** [comment]
@phil235 tell that to the famous guy who had a rail gauge (essentially a rod) shot through and into his skull, causing his personality to change (yes, he survived!)

And embedding uses a custom proc, anything that is sharp can embed, but also misc items can be added to embedding without also letting you cut food with them.

**Comment by Dorsisdwarf** [comment]
Yeah, steel rods are definitely capable of impaling people when blasted by an explosion (Just like NoBrain McLuckyAsFuck)

**Comment by Miauw62** [comment]
brb finding a disposals bug that lets me make disposals generate exponential amounts of rods

**Comment by phil235** [comment]
Hm yeah, I forgot about explosions throwing things, but people shouldn't be able to throw  a rod and have it impale someone, they're not supermen.

**Comment by RemieRichards** [comment]
@phil235 yep that's in my balance PR. Explosions or throw_speed 4 (throwing stars are the only item with this value atm) are the only ones that can embed (they still need to be a can_embed() object on top of this though)

**Comment by RemieRichards** [comment]
https://github.com/tgstation/-tg-station/pull/8016
