### ISSUE TITLE
Sec hardsuit helmets are the same as they were before.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8008]
@dannno

For the worn sprites, specifically. This creates a nasty disconnect in style.

**Comment by paprka** [comment]
OId helmets are still in the icons/mob/head.dmi file, rename or remove

**Comment by Steelpoint** [comment]
Easy fix, I'll look into it.

**Comment by dannno** [comment]
They're supposed to be renamed (sec to hos), I'm unsure why they weren't. When I tested they were.

**Comment by RemieRichards** [comment]
The issue number is boob.

**Comment by xxalpha** [comment]
I am glad this is not intentional.

**Comment by dannno** [comment]
i'm fairly certain this is fixed by that ^

**Comment by Dorsisdwarf** [comment]
@Cheridan if this was fixed by 7942, then it should be closed.

**Comment by WJohn** [comment]
Yeah, this has been fixed.
