### ISSUE TITLE
meth recipe typo

### ISSUE THREAD

**Issue by Delimusca** [tgstation/-tg-station#8009]
methamphetamine requires "phosphorous" instead of "phosphorus", making it unmixable.
[Chemistry-Goon-420BlazeIt.dm#L231](https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/Chemistry-Goon-420BlazeIt.dm#L231)

**Comment by Dorsisdwarf** [comment]
How is it unmixable?

Some engineer was rushing around the station injecting everyone with it yesterday.

**Comment by Delimusca** [comment]
the payday joke recipe works, the real one doesn't.

**Comment by mikecari** [comment]
WE NEEDED THOSE COOKS!
