### ISSUE TITLE
Chems in maint, but no way to use them

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8015]
So some chems were added to the maintenance drop table. The only recipe they're used for is making meth, which requires a heater. So there's no way to steathfully make the drug without breaking into chemistry anyways, where the drug you're trying to make could have been made without any of the drops you had collected

And these precursors have no other uses or effects of their own, currently the best use for drops is to chug the contents and take the free 50 unit container

**Comment by Lumipharon** [comment]
Should be able to put a container onto a normal space heater, for uncontrolled, gradual heating.

**Comment by Cheridan** [comment]
fixed by #8083
