### ISSUE TITLE
Chem grenades miss lower-left tiles.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#8019]
![grenade](https://cloud.githubusercontent.com/assets/6583225/6400439/b5e4baf4-bdad-11e4-8555-396c0ef72f17.png)

Left is a carpet grenade. Right was space cleaner detonated in the middle of a 7x7 block of blood.
Chem grenades without a smoke/foam reaction were meant to splash the reagents in a square-shaped area (7x7 for normal, 9x9 for large grenades), but now something's making them ignore tiles to the southwest.

On a slightly less related note. Carpet grenades flood the chatbox with "Floor gets a layer of carpeting applied!" for each affected tile. Add a spamcheck?

**Comment by Lumipharon** [comment]
On the topic of spam check, can that be added to synthiflesh smoke nades? That scream spam, jesus christ.

**Comment by phil235** [comment]
Is this fixed?

**Comment by RandomMarine** [comment]
Nope. Still active.

**Comment by Iamgoofball** [comment]
Pretty sure I removed the message from carpeting.

There's still some spam with smoke and synthflesh but due to smoke changes it's less now.
