### ISSUE TITLE
Per-pixel table placement is wonky with alt-click

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#8020]
Alt-click tile with a table. Try putting something on it. Half of the time item lands outside the table tile.

**Comment by RemieRichards** [comment]
Wait what? Byond is registering the click on the Alt-click menu version of the object... AS AN ACTUAL CLICK?

What even.

**Comment by Delimusca** [comment]
items go to the same spot in the alt-click menu, which is nice for putting multiple things on the same spot. apparently the name is included in this, so you can offset items way to the right by clicking the name. clamping the offset to within +-16p should fix that.

**Comment by RemieRichards** [comment]
Clicking the name actually registering as a pixel-x/pixel-y value OUTSIDE THE BOUNDS OF THE ICON is completely stupid on byond's part. I am annoyed at this, I'll fix it though.
