### ISSUE TITLE
Can't vend virus bottles with the + character in the name.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#8025]
Put a virus bottle named "Eternal Youth+1" inside the smart virus storage to find that it is now trapped forever within the fridge.

I've been using +1 to indicate that it has one other symptom, but I believe it's doing parsing to look for "EternalYouth1" which doesn't exist.

The same results happen with any bottle which has a name with +1 or + 1 in it.

**Comment by Miauw62** [comment]
I think this is a dupe.

**Comment by phil235** [comment]
duplicate of #4708
