### ISSUE TITLE
Balance: X-Ray Lasergun Syndicate Tech

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8026]
Bring this up with the semi-recent removal of syndicate tech on non-syndie items.

the X-Ray lasergun still has syndicate tech attached to it: https://github.com/tgstation/-tg-station/blob/master/code/modules/projectiles/guns/energy/laser.dm#L95

Thus allowing for access to synditech without syndicate gear.

**Comment by dannno** [comment]
solution: remove xray laser gun

**Comment by Fox-McCloud** [comment]
Or remove the syndicate tech....orrrr make it require syndicate tech.

**Comment by AnonymousNow** [comment]
I hope that's sarcasm, dannno.

Also, does this mean illegal tech's being run into the ground as a research path? Because, in a world where TYRANT modules exist, that wouldn't make sense.

**Comment by dannno** [comment]
i never joke

**Comment by paprka** [comment]
i think the xray laser is a little overpowered in that if someone has it, and is fighting a blob, they can shoot a ton of stray lasers into the rest of the station.

while hilarious, it also put me into near-crit once.

as far as research goes i would prefer if there were more ways to gain illegal tech. doesn't the xray laser REQUIRE high illegal tech anyway?

**Comment by Fox-McCloud** [comment]
It doesn't, here's the tech requirements:  "combat" = 6, "materials" = 5, "biotech" = 5, "powerstorage" = 4

Very high end item, but definitely not a high-end illegal item.

**Comment by paprka** [comment]
well that's silly, blob must be a giant pushover now

**Comment by mikecari** [comment]
The problem is that mining never delivers and the xray guns never get built ;(

**Comment by AnonymousNow** [comment]
Yes - I think we're fixing a problem that doesn't exist.

**Comment by dannno** [comment]
i disagree
it might not happen every single time, but when xrays ARE made it's almost unfair
I might be kidding when I say they should be flat out removed, but they should absolutely be balanced better. As they are I don't think whoever added them really put that much thought into it. They shouldn't pass through infinite walls, should maybe be stopped by r-walls, etc.

**Comment by AnonymousNow** [comment]
If they pass through infinite walls, that IS an issue. It needs a decay query, where the projectile loses lifespan/potency when passing through materials of different densities. Biological material offers little resistance, so a shot will pass clean through a blob, but five or six walls, two or three Rwalls, should make it dissipate.

**Comment by dannno** [comment]
>5 or 6 walls

you overestimate just how many walls a beam has to pass to get through the station
6 walls is a LONG way in a lot of places.
if anything, 1-3 walls, and simply not pass through r-walls at all.

**Comment by Dorsisdwarf** [comment]
6 walls from cargo bay will be able to kill the chemist.
6 walls from viro maint and you can kill the AI.

**Comment by AnonymousNow** [comment]
Then give them a small distance decay, too?

**Comment by dannno** [comment]
After some thought, I honestly think even the ability to just pass through a single wall is enough to give the gun a niche. It would double the rate at someone destroys a blob (or more, those things have a huge amount of shots iirc)

**Comment by Dorsisdwarf** [comment]
This issue report is kinda moot now. Some items have syndietech that aren't syndie, it's a known fact.
