### ISSUE TITLE
admin rejuvenate verb doesn't fix embedded items

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#8029]
Tested on a local server with a build downloaded just minutes ago. Rejuvenated a target with several throwing stars in them, and they got back up, but immediately began taking massive damage from the throwing stars again. Maybe make embedded objects get thrown onto the ground out of the subject upon rejuvenating?

**Comment by MrStonedOne** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
UH sure yeah, I'll add it to my current embed PR.
