### ISSUE TITLE
Chem smoke with dark matter crashes server

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#8034]
Dark matter smoke creates vortex on human touch, so humans keep moving into the clouds, clouds keep moving too creating infinite loop of vortexes and somehow crashing the server in the end
@Iamgoofball

**Comment by Razharas** [comment]
It also creates that shit on turf touch so its too bad to be true

**Comment by Lumipharon** [comment]
Well atleast after some hilarious testing, we figured it out.

**Comment by paprka** [comment]
Why does dark matter react with mobs in the first place

I thought it's meant to create vortexes, not turn people into vortexes, that's just asking for lag.
