### ISSUE TITLE
Vodka shot has no sprite

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8045]
Self explanatory

Put vodka in shot glass

**Comment by dannno** [comment]
@TheVekter

**Comment by TheVekter** [comment]
That's odd. Unless someone changed it. I'll look in a few.

**Comment by TheVekter** [comment]
There's no shotglass sprites anymore. They're -gone-. The fuck? I'll fix in a few.

**Comment by Incoming5643** [comment]
probably removed in a lazy conflict resolution

**Comment by phil235** [comment]
It's not just vodka, adding any reagent to a shot glass makes it invisible.

**Comment by TheVekter** [comment]
Right, I fixed it in my latest PR. Somehow all of the shotglass sprites got
removed.
