### ISSUE TITLE
Can walk over cyborg rechargers as human.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#8052]
Cyborg rechargers start closed and you can walk over them if they are not opened and closed again.

Steps to reproduce:
-Round start
-Walk over closed cyborg recharger
-Open and close recharger, can't walk over it anymore

**Comment by Dorsisdwarf** [comment]
Cannot reproduce, can consistently walk over borg chargers after closing and opening them.

You're supposed to be able to walk over them when open anyway.

**Comment by xxalpha** [comment]
Not when they're closed. They're dense when closed.

**Comment by Dorsisdwarf** [comment]
I can confirm that I've been able to walk over the one in the ministation shuttle, even after opening and closing.
