### ISSUE TITLE
Security wardrobe still has santa hats.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8053]
It's almost march, guys. Come on. This might be the case for other wardrobes, too, someone needs to check through em.

Also related: The festivus pole is still in the RD's office.

**Comment by Xhuis** [comment]
not every1; celb; rates christmas in decimber u insensitive shit-head!!!!!

Sarcasm aside, this _really_ needs to be fixed.

**Comment by xxalpha** [comment]
:gift:
