### ISSUE TITLE
Synthflesh (maybe just smoke?) can revive dead simple mobs

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8054]
Description: Sibyl, 7:50ish Eastern. Dragging my poor deceased Runtime to the shuttle as the CMO, she died to fire. I drag the corpse on and apparently someone set off a synthflesh smoke grenade, as I get spammed with a lot of "You feel your burns healing and your flesh knitting together!
You feel your burns healing and your flesh knitting together!" messages. When I walk out of the smoke cloud, Runtime lives.

What did you expect to happen: Not to have a living cat

What happened instead: RUNTIME LIVES

Why is this bad/What are the consequences: It isn't bad at all. It's a feature. LONG LIVE RUNTIME :3. However it is probably unintended.

Other details: The grenade was just synthflesh, however there were also apparently holy water grenades going off.

**Comment by Fox-McCloud** [comment]
This is intentional for styptic, silver sulfa, and synth flesh to heal dead mobs, from what I've talked with Goof in the past---what's...not intentional is them reviving once they are healed; that's what strange reagent is for.

**Comment by PKPenguin321** [comment]
Good to note this revived runtime, a simple mob, not a carbon human

**Comment by MrStonedOne** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
healing dead mobs is intentional, it's for shit like our 

dunno about runtime though, fucking simple animal code is horrifying

**Comment by Dorsisdwarf** [comment]
I remember HGs horror when he helped me with the code for laser-shooting spacecarp back on NT

**Comment by bgobandit** [comment]
changed the title, maybe what is happening is that mobs only have a health % and when they get healed, they instantly show up as alive

**Comment by Dorsisdwarf** [comment]
Actually I'm pretty sure that's it.

Life() is only for carbons , IIRC

**Comment by RemieRichards** [comment]
@Dorsisdwarf Life() is just the mob version of Process(), they all have it, including simple_animals
the most commonly referred to Life() version however, is the one carbons copy pasted all over the place.
