### ISSUE TITLE
Smoke reagent interactions are not proportionate to the actual amounts.

### ISSUE THREAD

**Issue by naelstrof** [tgstation/-tg-station#8060]
1 unit sugar, 1 unit synthflesh, 1 unit potassium, and 1 unit phosphorus can heal huge groups of people of over 200 brute AND burn damage almost instantly.

Similarly, replace synthflesh with Fluorosulfuric Acid and it kills hoards of people instantly.

Is this intended?

**Comment by naelstrof** [comment]
Oh it DOES matter, but since each individual smoke cloud applies the effects each time you walk into it, it stacks up to heal massive damage.

**Comment by Lumipharon** [comment]
I think at this point everyone realises smoke is hella dodgy code.

**Comment by Razharas** [comment]
Rewrite smoke code, we had foam rewrite its time for smoke rewrite too

**Comment by Iamgoofball** [comment]
i've got an idea for smoke code
