### ISSUE TITLE
Coderstrikes sprite back

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#8062]
![image](http://i.imgur.com/wd6QDAo.png)

@WJohn 
@Nienhaus 
@phil235 

Somebody please help this poor burger become good looking again

**Comment by Nienhaus** [comment]
I'm not even sure what you want.

**Comment by Razharas** [comment]
Is there a way to make these overlays look less square and more like food?

**Comment by Nienhaus** [comment]
Well, I have no idea actually.

**Comment by phil235** [comment]
I can readd the random horizontal pixel offset for the ingredients, and I could try to make each of those 2 pixel high when stacked instead of just 1.

**Comment by Razharas** [comment]
Well im mostly concerned with their sqareness and unified colour, looks really bad compared to nice looking top of the burger and okaish looking bottom of the burger(bottom could have colour closed to the top, it feels strange that they are of different colour)

**Comment by WJohn** [comment]
Yeah the hamburgers currently look absolutely awful, it's not so much that it needs pixel shifting from layer to layer as the individual layers are ugly.

**Comment by Iamgoofball** [comment]
yeah @phil235 the pixel offset was added because of the raw colorstacks as seen above

**Comment by TZK13** [comment]
Why IS the bottom of the burger like that? Why isn't it just the bottom half of the normal burger sprites?

**Comment by Jalleo** [comment]
Have a tiny black outline for each overlay?
