### ISSUE TITLE
Carpet smoke(or maybe smoke in general) leaves lightless turfs

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#8063]
Exactly what it says in the name, untill lights are reset by some means turfs occasionally stay unlit

**Comment by Iamgoofball** [comment]
i'm noticing this with other smoke reactions too, i think it's smoke

**Comment by MrPerson** [comment]
I know what causes this. The lighting system is supposed to update nearby turfs as part of atom/movable/Destroy() if src is opaque, except that part isn't called because a later defined version doesn't call ..().
