### ISSUE TITLE
Rechargers breaking on power loss

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#8064]
If you detach a recharger from a area that got depowered with it attached inside, and try to use it again outside the depowered area, and attach it, it won't be powered by the powered APC, just shows charging animation but doesn't charge. Annoying as hell in blob when theres a lot of rechargers, blob just breaks the APC and they are all paperweights now.

**Comment by kevinz000** [comment]
Toggled the open/close because I forgot to put a comment on it.

**Comment by Jalleo** [comment]
related: #7842
