### ISSUE TITLE
Security megaphone not working

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8066]
It makes the annoying sounds, but no text message appears to other people.

**Comment by Jalleo** [comment]
@miauw62 saycode tag and who made it?

**Comment by Miauw62** [comment]
@paprika made this, and he used audible_message() not say().

**Comment by Jalleo** [comment]
okay gotcha thanks for conformation

**Comment by Dorsisdwarf** [comment]
This seems to happen to all megaphones.

**Comment by phil235** [comment]
When does that happen? Can we have details on how to reproduce this ?

**Comment by Dorsisdwarf** [comment]
When it happens: Literally whenever anyone else uses a megaphone. I've never once actually heard what they said, only the BOOEEP noise they make when you use them

**Comment by phil235** [comment]
Found the problem, when Paprika changed its code from using show_message() to audible_message() he forgot to change the proc's arguments.
