### ISSUE TITLE
Golems have some stupid high chance to being weakened if hit without weapon.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8067]
Punching/kicking a golem, regardless of a targetted body part, results in them being weakened 99% of time. Everything is fine when using weapons. Hitting humans seems fine aswell.

![image](https://cloud.githubusercontent.com/assets/10717398/6426734/9d1f118c-bf69-11e4-965b-6ccb5be2778d.png)

How to reproduce - punch a golem using harm intent.

Code downloaded minutes ago.

**Comment by Incoming5643** [comment]
Are you sure you were targeting the mouth with the human, the weaken chance is stronger when targeting the mouth.

In any case not intentional behavior

**Comment by SeikoTheSeal** [comment]
I tested it with all body parts. Hands, legs, mouth, chest, same effect.

**Comment by phil235** [comment]
This seems to happen to both golems and adamantine golems.
