### ISSUE TITLE
light floors sprites missing

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#8070]
The colored sprites for the light floor is missing.

**Comment by RemieRichards** [comment]
smells like a merge conflict issue.

**Comment by TheVekter** [comment]
@Mandurrrh was the last one working on it IIRC.

**Comment by Mandurrrh** [comment]
Icons states kept changing after merging light_on_b changed to light_on-b I just fixed the code and renamed them since it kept renaming them.
