### ISSUE TITLE
Admin spawned blob "stuff" has no icon sometimes

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#8085]
If an admin manually spawns blob stuff like normal, shield, factory, node, or a core using the spawn verb, it will appears colorless (fine) but also sometimes without a proper icon and will have the icon state of "blob_blank" which is invisible.  It always seemed to make nodes invisible but cores would only sometimes be invisible.  One time, when I did this to help out a blob that was getting fucked because it got in it's body late because I had to manually input the ckey into it using vars, apparently all the icons broke because every blob core afterwards had no icon.  
Blob sprites are being weird.  @Iamgoofball

**Comment by Iamgoofball** [comment]
you shouldn't be manually spawning blobs ever

i'll look into a "make X person into blob" button for the game panel if there isn't one already

**Comment by Incoming5643** [comment]
there's one in the player panel

**Comment by RemieRichards** [comment]
I totally fixed invisible cores, and I encountered no invisible cores afterwards in my testing.

So, y'know, MERGE #7607 !!

**Comment by Niknakflak** [comment]
As I said, admins sometimes spawn blobs to help out blobs that are given an unfair advantage such as having ckeys switched.  But it seems a fix is already there.  Good job RR.
