### ISSUE TITLE
Two players can occasionally spawn as the same Head of Staff

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#8086]
Just today, we've had two cases of this happening at round start.

First one was two captains.

Second time was two HoPs.

Not sure what's causing this, but I want to raise awareness that this is happening.

It's been happening with a lot more frequency since we added assistant caps.

**Comment by phil235** [comment]
This happened again just now on Sybil. Two captains. One player had captain set to medium and the other to low. The round type was blob and playercount around 64.

**Comment by Ikarrus** [comment]
Could it be related to assistant caps, perhaps?

**Comment by Ikarrus** [comment]
I asked them both and one of them said he had "Be Assistant if no other jobs are available" set, and lo and behold, the assistant cap was hit that round.

I'm guessing as his preferred jobs were taken, and assistant slots were all filled, he got a random job and got it regardless of available slots. It may be picking head jobs because they tend to get picked first.
