### ISSUE TITLE
Too many implants renders you unable to use RIG's, Welder Helmet/mask/goggles, flashlights, etc

### ISSUE THREAD

**Issue by TheWiznard** [tgstation/-tg-station#8087]
![broken hud](https://cloud.githubusercontent.com/assets/9158683/6429938/6007c2a4-bfb8-11e4-87d9-65479e22c584.jpg)

If you use all the implants from an Implant Kit on yourself you can no longer activate anything that uses one of the top left button things. I didn't test it with flashlights but I couldn't use Welder masks or activate the RIG, they don't have any object tab verbs to use so you're left with not being able to use them at all. I got around the Welder mask by just clicking on it in hand to switch it to the welder protection state. 

Happened on current server revision on Metastation

edit: also, using all the uses you get from the handcuff/emp/adrenaline doesn't remove the implant's button at the top left. Using all the TC you get from the implant also doesn't remove the button

**Comment by RemieRichards** [comment]
I told you we needed to keep the object verbs as spares!

Alternatively uncap the amount of buttons, 5 is stupidly low given how unused that screen real estate is.

**Comment by MrStonedOne** [comment]
>I told you we needed to keep the object verbs as spares!

Fucking this!

Everybody was all like "no! object verbs a shit"

Fucking stop playing the remove game.

This was also an issue with the ai verb massacre of 2014, as a lot of ais used the verbs like you are suppose to, via typing. and the buttons broke their entire workflow.

I still need to look at re-adding the ai verbs as panel less verbs or some shit

**Comment by MrStonedOne** [comment]
#8092 The push against verbs is ignoring certain user experience advantages of them.

**Comment by dannno** [comment]
https://github.com/tgstation/-tg-station/issues/7845 the solution is right here

**Comment by RemieRichards** [comment]
It really isn't, you shouldn't force hotkeys on people, there should always be options.

**Comment by dannno** [comment]
then let there be options
add hotkeys, leave the verbs

**Comment by Miauw62** [comment]
this is a duplicate

**Comment by Dorsisdwarf** [comment]
Why do we have a limit of four actionbutton toggles anyway? There's room for like 10

**Comment by Jalleo** [comment]
Would this be solveable by adding a way to scroll through your current actions avaliable?
