### ISSUE TITLE
maint chem bottle icon is missing

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8088]
@Iamgoofball 

Someones been incorrectly solving icon file conflicts and it ate the bottle

**Comment by Iamgoofball** [comment]
Goddamnit

**Comment by TheVekter** [comment]
Yeah, welcome to my hell.

**Comment by Pennwick** [comment]
Badmin Vodka is also invisible. Oh the thrill of the hunt of right clicking lockers and finding 'secret' goodies.

**Comment by TheVekter** [comment]
Badmin vodka isn't related. I'm trying to fix that now.

**Comment by Iamgoofball** [comment]
Already fixed

**Comment by Iamgoofball** [comment]
this has been fixed for ages @Cheridan the maint bottles no longer exist
