### ISSUE TITLE
The push against verbs is ignoring certain user experience advantages of them. 

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#8092]
I'm mainly referring to things like removing object verbs, removing the ai verbs for buttons, abusing the action buttons, etc.

The issue with REMOVE ALL VERBS is too many players who are good at keyboard use and do not use hotkey mode are able to type, by memory, most common verbs.

One adminhelp I still get every now and then is that the ai user interface update broke the habit to type with in the chatbar and hit enter for track with camera. or track+space+enter

And we have things like this:

https://github.com/tgstation/-tg-station/pull/8013

Moving a functionality to a keyboard modifier + click interface that is killer for new users to pick up on.

The other upside to verbs is how new user friendly they are vs unnamed icons in the bottom bar or upper right corner or keyboard modifier click hotkey, or normal hotkey

Its categorized, its labeled, and its detailed. 

How many people had issues figuring out how to enter a mech when it was switched from an object verb to a drag option?

"but but but mai clutter" Clutter should be looked at, yes, but making it impossible for users to do basic interface things without a wiki read is worst than clutter.

So! I deplore of you, Lets be a bit more sensible about how we go about this verb thing.

**Comment by dannno** [comment]
easiest solution https://github.com/tgstation/-tg-station/issues/7845
seriously. we don't need object verbs if we have this.

**Comment by MrStonedOne** [comment]
nope.

From OP:

>Moving a functionality to a keyboard modifier + click interface that is killer for new users to pick up on.

>The other upside to verbs is how new user friendly they are vs unnamed icons in the bottom bar or upper right corner.

>Its categorized, its labeled, and its detailed.

>How many people had issues figuring out how to enter a mech when it was switched from an object verb to a drag option?

**Comment by Anonus** [comment]
We will run out of good hotkeys. We're already running out of good hotkeys, really.

**Comment by Razharas** [comment]
Problem is the fact that we dont really have any clear vision with what to replace them
Good way is UI buttons but screen object code as shite so thers all kinds of shit proposed chaotically
Also you mixed verbs which are okish with object verbs which are the devil

**Comment by dannno** [comment]
>Moving a functionality to a keyboard modifier + click interface that is killer for new users to pick up on.

they only but need to ask. if it becomes prolific to a point where people being introduced aare told that ctrl/alt + click do secondary actions, people will figure it out just fine.

also, ctrl/alt click work outside of hotkey mode, dumbo.

**Comment by MrStonedOne** [comment]
Alt click has a use already

Control click has a use already

Shift click has a use already

**Comment by dannno** [comment]
Ctrl/Alt click do not have uses on items in your inventory/hands, paprika's PRs proved that they are the perfect keys for secondary and tertiary actions on items like that.

**Comment by Dorsisdwarf** [comment]
Additionally, the AI and borgs also use different alt and ctrl-clicks.

And to be honest, the verb system is no more intuitive than the built=in hotkeys.

And the whole "AIs are used to using track-" is baloney, because THEY HAVE A GREAT BIG BUTTON ON THEIR INTERFACE TO USE INSTEAD. It's like complaining that your fiat was taken away and replaced with a ferrari*, because you were used to the fiat.

(*specifically, because it's better, faster, and is nicer to look at)

**Comment by Ikarrus** [comment]
I don't mind if object verbs stay, but having alternate hotkeys is important imo. It'd be better if we just kept both.

**Comment by PKPenguin321** [comment]
what ikarrus said, i actually type verbs out pretty much all the time and the removal of all of them is no bueno, but at the same time hotkeys are nice to have

**Comment by Supermichael777** [comment]
somebody deiced that all object verbs they don't personally use are the devil. also when i pick up a new item i default to looking at its verbs in right-click and object tab ,taking that away removes any indication it has a function.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Coding,  Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
