### ISSUE TITLE
Changelings reasonant shriek permanently confuses slimes.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8096]
Player controlled slimes that were hit by reasonant shriek are permanently confused (walking like drunk etc). Only way to get rid of this is to split.

**Comment by Incoming5643** [comment]
A brave and noble soul really need to refactor slimes to simple animals already

**Comment by Cheridan** [comment]
Probably not limited to shriek btw.

**Comment by Incoming5643** [comment]
Yeah this happens with stun speech if a slime is hit with a taser too, even though they're actually stun immune.

**Comment by phil235** [comment]
Fixed by slime refactor
