### ISSUE TITLE
Request: Mulligan Delay

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#8105]
We'd like it if there was a brief delay between the death of the primary antagonist and the conversion of the game mode.

We don't think it's going to be fun to have heavily-armed traitors immediately spawn and start shooting at people just as the blob died.

Please give us a ~5 minute break!

**Comment by Ikarrus** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
I'll take care of this but I gotta clarify something here, the system actually WORKED at some point? I thought the blown living check had stopped any mulligans from actually occuring. Or were you just talking hypotheticals

**Comment by Ikarrus** [comment]
Hypotheticals
