### ISSUE TITLE
High-pressure unactivated turfs

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8110]
Apparently it's possible to make turfs that have a very high pressure (4500 kPa and more) but that aren't activated, so you have a single very high-pressure turf that doesn't spread.

```
DEAD: Quinton Bould says, "It's from a destroyed ripley that had its internal pressure set to the canister's max"
DEAD: Quinton Bould says, "so the air on the spot the ripley was destroyed"
DEAD: Quinton Bould says, "is stuck at"
DEAD: Quinton Bould says, "What the output pressure was"
```

mechs a shit, once again.

**Comment by optimumtact** [comment]
Something isn't calling the turf sim update code when it changes things

:flags:
