### ISSUE TITLE
Traitors/Ling can be tasked to steal documents that never existed.

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8111]
Objective 2: Steal any set of secret documents of any organization. Fail.

This objective can be generated in a round where no other antagonist has any task related to documents, and thus none are ever there to steal

**Comment by Ikarrus** [comment]
The vault has secret documents.

**Comment by Incoming5643** [comment]
I hope its not in the safe at least, that's sadisitic

**Comment by Ikarrus** [comment]
Nah, filing cabinet
