### ISSUE TITLE
Blood sprites are fucked up.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#8116]
As tittle

http://imgur.com/ZxvT5sl The silhouette shouldn't be there.

Server revision 539d51fb57cea90ac36c4d02cfb38dc915116e54

**Comment by Miauw62** [comment]
This also happens with jetpack trails.

**Comment by RemieRichards** [comment]
why on earth are drone silhouettes appearing in these situations?
They're set to override os they should be the only thing you see as a drone.

if you're not a drone you aren't seeing these, there's no code that allows you to add these to your ```client.images``` list.

**Comment by Durkel** [comment]
@RemieRichards 
Yeah, The silhouette is just appearing. It's appearing on all blood trails for everyone, and apparently on the little discharge trail of jet packs too.

**Comment by RemieRichards** [comment]
Sounds like a merge conflict on the name of the silhouette OR I fucked up some how...
No idea why it would actually use these icon states.

**Comment by phil235** [comment]
the silhouette sprite is named blank. And apparently blood and jetpack trail used that name already.

**Comment by RemieRichards** [comment]
great...
