### ISSUE TITLE
New Player mobs can see PDA messages

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#8117]
HELP: Nanotransistor/(Nanotransistor) (?) (PP) (VV) (SM) (JMP) (TP) : Aparently, i can listen to PDA messages even if im in the game lobby. 

@mandurrrh

**Comment by Jordie0608** [comment]
It's because /mob/new_player has stat = 2, which is DEAD

**Comment by Miauw62** [comment]
lol im fairly sure i made this exact mistake with lingchat when i first did the saycode overhaul.

**Comment by Mandurrrh** [comment]
I felt so silly lol
