### ISSUE TITLE
Individual mobs occasionally "lock up" and can't move/talk for a short period of time

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8120]
Very recent issue, like last one or two server updates on sybil.

Seemingly at random, individual mobs will essentially stop responding all together. You won't be able to move, and anything you say won't be spoken until after you "snap out of it".

It doesn't happen to everyone at once, but seems to affect many people at least once over the course of a round. Pretty nasty stuff.

**Comment by ZergRush000** [comment]
Happens to me quite a lot when I'm not connected to ethernet, is probably lag related if I'm thinking of the correct issue. Sometimes I do lose connection during the event.

**Comment by Incoming5643** [comment]
I don't think it's lag, because you can still see other mobs moving around and doing stuff while you're "stuck" and if it was a lag issue, you'd see everyone else stop and then "jump ahead" when you stopped lagging

**Comment by Incoming5643** [comment]
Seeing this from the perspective of someone who isn't stuck also produces some interesting effects: If the "stuck" player tries to say something, the speech bubble pops up but no message is shown until the player comes out of the state, and no new speechbubble is made for when it is ACTUALLY said

**Comment by Incoming5643** [comment]
had this happen as both a human and a lizard person, so it's not a species thing.

Also both times I've see it happen, it was right after I tried to click something on a nano ui window

**Comment by Incoming5643** [comment]
Can happen as any mob, even ghosts

**Comment by Incoming5643** [comment]
maybe something from #7854 ?

**Comment by Incoming5643** [comment]
thrilling update: maybe my internet is just being a shit and nothing is wrong :scream:
