### ISSUE TITLE
Wet tile overlay is being applied to walls

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8133]
![2015-03-03 13_12_43-sybil_ pizza installation xiv](https://cloud.githubusercontent.com/assets/3975713/6462169/0f39528e-c1a7-11e4-9c91-306843e417c8.png)

this looks really dumb.
@Iamgoofball @Cheridan whoever the fuck revamped smoke idk.

**Comment by GunHog** [comment]
This is a rather old bug, you know!

**Comment by Cheridan** [comment]
I didn't touch smoke. This is for sure an old thing.

**Comment by Jalleo** [comment]
It works with mops to walls too!

**Comment by Iamgoofball** [comment]
Also probably wasn't me.

**Comment by phil235** [comment]
Fixed, wet walls now have a different wet overlays that doesn't look like a floor tile.
