### ISSUE TITLE
The chemical krokodil is OP

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#8136]
Considering the benefits skeletons enjoy https://tgstation13.org/wiki/Guide_to_races#Skeletons

They're really OP to let chemistry mass produce. Skeletons should not even be player-transformable and should be kept admin-only.

Players are using it to powergame for a free space suit and bleeding immunity.

**Comment by Ikarrus** [comment]
@Iamgoofball

**Comment by MrPerson** [comment]
Why do skeletons have any upsides whatsoever? I was seriously under the impression it was an aesthetic thing only.

**Comment by Ikarrus** [comment]
It started off as an admin joke, then buffed to shit high levels, then added to chemistry of all places.

**Comment by Incoming5643** [comment]
I thought it was just aesthetic too until I actually compiled that page. It use to be before datum based species.

**Comment by Boredone** [comment]
Checking the code, strange reagent can also revive ye as a zombie which has the same benefits, but a speech modifier.

**Comment by Miauw62** [comment]
zombie and skeleton were supposed to be dumb joke races.
skeletons should as only upside have the ability to play xylophone on their ribcage (as an excuse for having a xylophone var)

**Comment by RemieRichards** [comment]
yeah everything the skeletons/zombies have (besides speech mods) can be done by admins for their events anyways, so, it's a non issue to remove that.

**Comment by Incoming5643** [comment]
Skeletons probably shouldn't have blood, but pretty much everything else is pretty easy to cut without being unrealistic.

**Comment by dannno** [comment]
Why did it even turn you into a skeleton anyways what the fuck
like I don't want to say "this isn't goon" AGAIN, but
this ISN'T goon
all of this goofy shit needs to go

**Comment by Ikarrus** [comment]
^^^^^

**Comment by Iamgoofball** [comment]
I completely forgot they were buffed to hell, I thought it was purely cosmetic.

**Comment by Jalleo** [comment]
This is how accidental buffs happen

**Comment by Fox-McCloud** [comment]
Strange reagent doesn't even zombify on Goon anymore because of the abuse it led to.

Krokodil doesn't really make you a skeleton on Goon, either; it gives you this really gross overlay on your mob.

**Comment by Miauw62** [comment]
btw i made the skeleton sprite in five minutes by using the recolor tool on
husk sprites in paint.net
