### ISSUE TITLE
Full windows no longer drop shards

### ISSUE THREAD

**Issue by Ahammer18** [tgstation/-tg-station#8139]
Issue: When broken, full windows (not reinforced) will not drop shards.

How to reproduce: Break a full not reinforced window.

**Comment by phil235** [comment]
can't reproduce

**Comment by Dorsisdwarf** [comment]
I don't get a shard when I open windows by shooting them with projectile weapons.

**Comment by ZergRush000** [comment]
@phil235 try creating a full sized window with regular glass from a stack
it only seemed to work with player created windows

**Comment by phil235** [comment]
Finally, the bug only happens with player created non reinforced full window and only with melee weapon attack.
