### ISSUE TITLE
Xeno suggestions

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8143]
- Better spawn locations. It's pointless to have larva spawn between cargo and HoP office or other extremely busy hallway.

- Xeno Progenitor Antag toggle. The first larvas are the most important ones and I think it warrants it's own antag toggle so that people can differentiate between "I know how to queen" and "I ded pls respawn as hunter". Alternatively, hardcoded that first larva has to evolve to drone and queen or to have rule about it. 

- Apparently biting something organic as larva speeds up the evolution, if true, it'd be great if it was mentioned somewhere, I don't recall it is mentioned. 

- I don't know if the xeno acid blood has been implemented or if it ever will be, but making clothes and armor out of xeno parts would be cool, especially since there is already sprites for most of it. Perhaps also a xenotail spear for that added stabbing.

**Comment by phil235** [comment]
Making a xeno pelt is pretty easy to implement.

**Comment by MMMiracles** [comment]
I thought you could already chop up xenos to get their pelt, same with monkeys as of recent? Pretty sure you can make the xeno suit out of said pelt too.

**Comment by Lumipharon** [comment]
I've heard the claim the chomping mice and shit makes you evolve faster.
I tried it one time, couldn't notice any difference.

A big difference between box and meta, is that meta actually has some vents in maint.
Box has like, the aux power room and that's it.

Let people use a xeno head as an (acid proof) shield.

**Comment by WJohn** [comment]
Honestly I think that xenos should have some of the more basic utility stuff improved, like inhands for facehuggers, examining them for damage, giving them the me emote, and maybe even being able to extract actual acid blood from them now that we have exotic blood.

**Comment by Dorsisdwarf** [comment]
You can too examine xenoes for damage.

I know because I was testing the minigun on them on my local.

Inhands for huggers was my project but I got bored. I'll finish it after miniguns and rumblestation

**Comment by Miauw62** [comment]
you can already get xeno pelts using the meat spikes, fyi.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.

**Comment by Marflowerose** [comment]
Well, the lack of information about biting -> more evolution is sort of a bug, unless it's really a baseless rumor, though to me it seems to speed up evolution when munchin on a monkey.
