### ISSUE TITLE
Lord singuloth is getting laggier

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8154]
Some recent change seems to have made the singularity a bit more prone to lagging everything like mad, especially when there's plenty around to suck in

**Comment by hornygranny** [comment]
can you provide more specific examples to reproduce

**Comment by hornygranny** [comment]
oops

**Comment by optimumtact** [comment]
There's always making it non destructive, since it's the huge amounts of objects getting deleted that mostly causes the lag.

**Comment by MrStonedOne** [comment]
Now and days its the throwing thing that causes it. Maybe make that have a chance depending on how far out the object is?

**Comment by hornygranny** [comment]
@optimumtact specifically it's the turf deletion that causes the lag, everything else is qdel/loc manipulation

**Comment by Incoming5643** [comment]
@hornygranny Spawn a singularity in the center of the station? I don't know man, you kind of have to see it on live to get the picture.

It was running smoothly enough to where you couldn't meta when the singularity was just released, but now it's back to "uh oh the game is lagging, it must be out"

I really think it's the throwing thing, and while I don't have any proof the timeline kind of suggests that it has something to do with when embedding items was added.

Which is a real shame because watching the singularity just huck shit everywhere is REALLY satisfying.

**Comment by hornygranny** [comment]
@RemieRichards are you aware of any performance impact from your feature

**Comment by RemieRichards** [comment]
it'd only happen if it ate drones, if there was any impact at all.

**Comment by Incoming5643** [comment]
huh? I was talking about #7700 specifically.

**Comment by RemieRichards** [comment]
Wait the fuck? Embedding? that one shouldn't have any impact at all lmao.

**Comment by Incoming5643** [comment]
Alright, well only other thing I can think of is if starlight leads to a lot of calculations every time a space tile is exposed

**Comment by RemieRichards** [comment]
Ooh actually, that's LOTS of lighting engine calculations isn't it, and that's notoriously shit.

**Comment by hornygranny** [comment]
@Incoming5643 try commenting out the throwing in singularity_pull() for /obj/item , and try disabling starlight in the config. should be easy to figure out

**Comment by Incoming5643** [comment]
worth a shot I suppose, don't know how much it lags on a test server though, might be able to tell with this shitty laptop here :sunglasses:

**Comment by Incoming5643** [comment]
Yeah it's the starlight. Someone should figure out how to suspend the feature on tiles currently getting eaten by the singularity so lighting doesn't have to check and recheck (up to 8 times I'd imagine for every also eaten tile surrounding the eaten tile) until the singularity is far enough away for those lighting updates to actually maybe matter.

Why should light escape a black hole anyways?

**Comment by Dorsisdwarf** [comment]
Requesting a new tag: "Paprika Broke It"
