### ISSUE TITLE
Meth breaks the space time continuum.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#8158]
1. OD on meth until you start jumping around at random.
2. Hop in a sleeper.
3. Wait a moment.
4. Meth OD warps you out of the sleeper, sleeper thinks you're still inside of it.
4. Get a buddy to constantly pump beneficial reagents into you while you run around robusting people.

This probably also works with other machines/containers.

**Comment by dannno** [comment]
Jesus fucking christ why did you think actual teleportation was an ok thing to do NNNNIGGGGGGGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA GOOFBALL WHAT THE FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUCK

**Comment by Dorsisdwarf** [comment]
This is amazing and beautiful

Drug-based teleportation medicine

**Comment by Iamgoofball** [comment]
Holy shit what

I'll add a location check, fucking sleepers

 @dannno fuck off for a few seconds with the bitching about bugs like it's an intended feature please

**Comment by dannno** [comment]
are you telling me that teleportation when you OD on meth is a bug
because nigga that sounds 100% like some stupid feature you would add intentionally

**Comment by Iamgoofball** [comment]
In this case, yeah, it's a bug.

**Comment by dannno** [comment]
i apologize then
it's a hilarious bug though
