### ISSUE TITLE
Kinetic Accelerator gets stuck reloading

### ISSUE THREAD

**Issue by quaggaman555555** [tgstation/-tg-station#8160]
Reloaded the KA after fully upgrading it and using a screwdriver on it, played reload sound, didn't change sprite. I was unable to reload or fire after that. Scones had to spawn me a new one after attempting to fix it. No idea what could have caused it.

**Comment by TheWiznard** [comment]
using plasma on the KA, which increases it's range; has a chance to break it, it's intended

**Comment by WJohn** [comment]
I think a gun jam that prevents you from reloading for a bit would probably be a better mechanic than it permanently breaking. It should also probably be telling you this.

**Comment by Miauw62** [comment]
>tweaking doesn't have a chance to break KA
>using plasma on it does

??

**Comment by phil235** [comment]
So the real bug here is the lack of feedback when the malfunction happens.
