### ISSUE TITLE
Syndicate Infiltrator Communications Relay STILL superheating air

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8166]
I thought we fixed this???

Unsure how to reproduce - I walked back into the shuttle to go home after I set up the bomb and wandered too close to the relay, started taking heat damage so I fucked off to the cockpit and thankfully it hadn't spread

Maybe this just takes time to happen but fuck is it annoying

**Comment by Miauw62** [comment]
i think this is simulated/unsimulated turf interaction rather than the
comms relay.
BTW the comms relay is entirely obsolete in the first place, syndicates are
now hardcoded to receive all radio broadcasts on their headsets.

**Comment by PKPenguin321** [comment]
>the comms relay is entirely obsolete in the first place

then remove it if all it does it glitch and kill ops, i dont think anyone would mind

**Comment by Cheridan** [comment]
@Miauw62 LINDA should have fixed sim/unsim mixing meltdowns. This might be an issue with the equipment heating up the air but not activating it so you have a local spot that's extremely hot.

Nix the equipment if it's useless, use the space for something fun. :)

**Comment by Miauw62** [comment]
i've had people die on the syndie shuttle fnr, not just on one spot

**Comment by MrStonedOne** [comment]
Its in an enclosed area with only a few tiles, so it would be easy for it to heat that up real quick like, only for it to spread the moment they go to grab the nuke and open that windoor
