### ISSUE TITLE
Mechs aren't targeted by turrets.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#8170]
You can just stroll right into the AIs chamber during a malf round and drill it into the ground with a ripley. Granted, the turrets probably wouldn't output enough damage to stop the mech anyway, it's still a issue.

**Comment by Incoming5643** [comment]
Never forget 2 Phazons, 1 AI

**Comment by phil235** [comment]
That's because unlike turrets portaturrets don't have the checks for mechs and AI turrets have been switched to portaturrets a while ago.
