### ISSUE TITLE
Pens can be thrown and embedded in people, dealing a lot of damage.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8172]
Like a lot. Each embedding does boatloads of damage by itself, and it staying in them is just extra powerful. This seems really contradictory to the fact that it does no throw damage.

**Comment by RemieRichards** [comment]
I can't recall if my rebalancing was added but it allows varying damage levels and COMPLETE customisation of values on when an object embeds.

that'd allow pens to embed without being as power as the almighty rod gods.

**Comment by dannno** [comment]
PS. u need a check so that people in hardsuits don't get shit embedded in them

**Comment by WJohn** [comment]
Armor in general should be able to prevent it from happening.

**Comment by Incoming5643** [comment]
Please don't remove my space ninja star trick throws

**Comment by WJohn** [comment]
This has been dealt with a while ago.
