### ISSUE TITLE
Syndicate Encryption Key: Inaccurate Function/Descryption

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8174]
The encryption key states that it gives you access to the hidden syndicate channel as well as every station channel; it doesn't do this, it only gives you access to the syndicate channel.

A new encryption key would have to be created to fit this functionality (as opposed to giving it to the syndicate encryption key itself), unless, of course, the intended goal is to give nukies the ability to listen in on every channel from round start.

**Comment by AnonymousNow** [comment]
Nuke ops can hear all the station's channels from the off. The upload key must be different somehow.

**Comment by Fox-McCloud** [comment]
Please close this; I was mistaken!

**Comment by xxalpha** [comment]
You can close it yourself, mate.
