### ISSUE TITLE
APC construction, deconstruction, and repair is hellishly bad.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8176]
APCs are impressively terrible to build, and really need to be reworked to both make more sense and require you only to work on one object instead of also on the terminal on the floor.

Cameras are also huge offenders here, too, and definitely need to be redone.

**Comment by RemieRichards** [comment]
Deconstruction doesn't require the terminal anymore, I did this months ago.

**Comment by PKPenguin321** [comment]
on a similar note, I believe SMESs use terminals too
i actually don't see the issue with camera construction though

**Comment by WJohn** [comment]
Camera construction requires you to wrench it while it's on the ground, uselessly asks if you want it on the left or right, then gives you a god damned confirmation box with a timer at the end. Those three things have got to go. Make placing cameras a simple matter of clicking on a wall with it in hand, like a light fixture does.

**Comment by palpatine213** [comment]
Please don't make the camera require hands to build. The way it currently is built, while stupid, let's engie borgs build cameras. Having your borgs be able to build cams in maint is amazingly helpful as an Ai.

**Comment by WJohn** [comment]
Then give them a camera construction and light fixture module.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
