### ISSUE TITLE
Hunger bar is not visible when not hungry, and shows up at the top right when you are.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8178]
I'm not sure if this was an intentional change, but it seems odd to put it at the top right like that.

**Comment by Incoming5643** [comment]
Same thing with charge meter on borgs

**Comment by Lumipharon** [comment]
It's pretty shitty UI design if it's intended.

The rest are grouped in the middle right, so you can see them all at a glance. But now you have to look top right to see how close you are to SLUGSLOW.

**Comment by Jalleo** [comment]
Probably a error caused by something recentish it used to be in the middle right.

**Comment by phil235** [comment]
That's intended (implemented in #8101). I'm okay with that, some people complained about the semi transparent hunger icon was unnecessary and taking screen space.

**Comment by Incoming5643** [comment]
I don't think thematically the hunger bar/power meter fit in with the other alerts like that though. When your under high/low temperature/pressure or lack of oxygen it's a pretty urgent matter, it's a "solve this shit now or die" sort of thing. 

Being mildly hungry or under 75% battery charge not so much.

**Comment by Miauw62** [comment]
I liked the battery charge meter being there all the time, actually.
Although I guess the new system would make it hard for it to be at the top
right.

**Comment by phil235** [comment]
This was very much intended.
