### ISSUE TITLE
You can inject fluorosulfuric acid into spray bottles with syringes or droppers.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8179]
http://i.imgur.com/LOYdHVM.png

Even though it clearly says you shouldn't be able to do this with a beaker transfer.

Should be checked for whatever other chems do this, but it's likely the same problem.

**Comment by Boredone** [comment]
This is actually known, there is a previous attempt to fix it in a PR, but it messed up and the creator ended up closing it and deleting the branch. #7795
His second attempt is #7902 . That one is still open, but possibly abandoned.

**Comment by Sometinyprick** [comment]
#7795 didn't fix it properly because you could add one unit of water to bypass the check
#7902 works but I guess people just want to leave it the way it is.
