### ISSUE TITLE
Admins can no longer edit the icon path for objects that can be picked up.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8180]
If you try to, it says it changed it to "html>" instead of whatever file you designated it to be. Still works fine with mobs, machines, and structures, though.

**Comment by Ikarrus** [comment]
RIP custom icons

**Comment by Jordie0608** [comment]
I'm not encountering this problem at all.

**Comment by tedward1337** [comment]
![](http://puu.sh/gpMYC/4deedc6dcc.png)
Working as intended

**Comment by WJohn** [comment]
http://i.imgur.com/0PtyD3J.png

Am I the only person who even does this?

**Comment by Jordie0608** [comment]
If you see in the picture ted posted, I modified a flashbang's item fine; earlier I also modified the icon of a Robust Harvest bottle.

What items are you trying to modify and how?

**Comment by WJohn** [comment]
I'm not trying to edit the icon to another one in our code, I'm talking swapping the .dmi out to another one I made.

Also I'm trying to edit a burger's sprite to something else.
