### ISSUE TITLE
Slimes have completely ludicrous amounts of health.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8181]
You know, for something so squishy I wouldn't expect it to have a max health of 150 and be able to go down to -150 hp, while regenning at incredible rates. There is absolutely no reason for slimes, both baby and adult, to be this tanky to melee.

Meanwhile a tiny puff of cold or water near instantly kills them. This is shit balance on a lot of levels. Completely unkillable except with a single absolute and instant-win hard counter.

**Comment by WJohn** [comment]
Also, as a further point: Slimes can continue to eat you even when they're dead, it takes several seconds for them to actually stop moving and eating you, though, but you still take the clone damage.

**Comment by Incoming5643** [comment]
it's not that water kills them instantly, it's that when you "focus" a blast of water into a tight space, all the water effects stack on top of each other and hit the slime at the same time.

Also I'm pretty sure for the large part of that negative health, they're immobile and not a threat at all unless you happen to be within eating range.

**Comment by WJohn** [comment]
It seems very stupid to me that they can continue to eat you if they're in their equivalent of crit.

**Comment by xxalpha** [comment]
This is not a problem, everybody knows that you need water to kill slimes.

**Comment by WJohn** [comment]
Yes, that's true, you need water to kill slimes.

If you don't have it you lose completely and totally. You can't even pretend to be able to fight off one single slime without a fire extinguisher.

**Comment by Steelpoint** [comment]
I agree this is a balance problem.

The fact that Slimes are essentially immune to almost any form of attack barring a fire extinguishers is insane. I've seen Aliens be unable to kill a Slime and they themselves be killed by the Slime.

**Comment by Dorsisdwarf** [comment]
It's almost like a semi-sentient blob of goo

is hard to beat to death

with a blunt implement.


ALSO: slimes are also vulnerable to cold. Super vulnerable to cold.

A cup of ice in a spraybottle should sort them out right quick.

**Comment by Jalleo** [comment]
What about acid or burning weapons...

**Comment by WJohn** [comment]
It's almost like we already have semi-sentient blobs of goo that are tough but not completely hopelessly invulnerable to melee attacks that aren't fire.

**Comment by dannno** [comment]
1 fire extinguisher can put a slime down easily, and I guarantee you can find WAY more than 1 fire extinguisher on station. It's not even like slimes get loose often enough that people are finding them hard to deal with or anything.

this is a non-issue

**Comment by xxalpha** [comment]
Exactly, it's really easy to kill slimes with an extinguisher, which are widely available. If you don't have an extinguisher or something else to cool slimes then yeah, that's where they are strong. RPS.

**Comment by WJohn** [comment]
It's not about the hard counter so much as the extremes that are present. If you do have a fire extinguisher, the slime dies basically instantly. If you don't absolutely nothing you use on them, no weapon can possibly save you from a single one.

Make them a little less vulnerable to fire extinguishers and significantly more vulnerable (or less tough in general) towards melee weapons or lasers?

**Comment by AlexanderUlanH** [comment]
Making them less vulnerable to extinguishers will screw over xenobiologists if it applies to baby slimes.

**Comment by WJohn** [comment]
Not if they have significantly less health in general, too.

**Comment by xxalpha** [comment]
I really don't think it's something that needs or should be changed.

**Comment by WJohn** [comment]
I don't think you understand how absolutely ridiculous this is. You can literally empty YOUR ENTIRE LASER GUN into one and will do MAYBE 12 damage. I just saw the HoS do this and do damn near nothing.

**Comment by Incoming5643** [comment]
As I mentioned before:

/mob/living/carbon/slime/adjustFireLoss(amount)
..(-abs(amount)) // Heals them
return

They're beyond immune to laser fire (besides the temperature gun I suppose)

**Comment by callanrocks** [comment]
Fun fact there's a slime that makes frost oil, easy dead slimes.

**Comment by phil235** [comment]
Fixed by slime refactor. As simple animals they now have no crit and die when their health reaches zero.

**Comment by Incoming5643** [comment]
#buffslimes
