### ISSUE TITLE
Aliens can no longer drag themselves into disposal chutes.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8182]
They used to be able to do this for getaways, but now apparently it requires fine manipulation just to jump into a box.

**Comment by dannno** [comment]
uhhhhhhh feature probably? aliens hiding in/on disposals (tiles you can't shoot with guns) fucking sucks, dude?

**Comment by WJohn** [comment]
That hardly makes sense, they already hide in lockers, around corners, can go invisible and have a PLETHORA of other ways to negate your gun use. This seems really weird to be made an exception when they can already use ventcrawl for mobility anyway, why not let them reach cargo through this?
