### ISSUE TITLE
you stand above hydro plants

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#8184]
![](http://a.pomf.se/ugrttq.png)
this probably happens for a lot of other things that i can't think of

**Comment by phil235** [comment]
Just a layer issue, shouldn't be hard to fix.

**Comment by Cheridan** [comment]
your spacewoman's cute btw

**Comment by dannno** [comment]
thank u

**Comment by Chocobro** [comment]
cheridan the waifu guy
