### ISSUE TITLE
Declaring as Silicon doesn't render the special font

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#8192]
As AI/Cyborg/pAI, declaring something (with one exclamation mark) doesn't render the special font the way the other modes of speech do.

Saying, yelling and questioning work fine.

Pretty minor thing, really, but it does make declaring things look slightly suspect.

**Comment by Dorsisdwarf** [comment]
I think it does now? maybe?

**Comment by Jordie0608** [comment]
It does.
