### ISSUE TITLE
Nuke Op Pinpointer Usage Messages are Inconsistent

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8200]
Firstly there are 4 types of pinpointer in the code: I can't discern what advpinpointer or nukeop do differently from the standard - Not sure if these are some weird holdover or what

Anyways the basic pinpointer has 2 messages for when you turn it on/off:
You activate the pinpointer.
You deactivate the pinpointer.

The Operative pinpointer (Spawns in the locker on the syndicate shuttle) however has a unique activation message 
Authentication Disk Locator active.

But when you turn it off, it's just 'You deactivate the pinpointer'

Weird consistency thing, can we just have it say 'Authentication Disk Locator inactive' or better yet replace active/inactive with activated/enabled because that makes boatloads more sense

(Wouldn't kill to give operative pinpointers a unique sprite either)

**Comment by AnonymousNow** [comment]
Four?

I can only think of two - one standard for locating the disk, and one for the Syndicate cyborg that points to the nearest operative...

**Comment by SconesC** [comment]
Yes, four:
- Pinpoint
- Advpinpointer
- Operative
- Nukeop

Pinpointer is the one that spawns on-station, Operative is the one that spawns on the Syndicate shuttle

No idea what Nukeop or advpinpointer do because they seem to behave 100% identically to the normal one

**Comment by WJohn** [comment]
I'd imagine the nukeop pinpointer points to the syndicate, I know cyborgs have one of those.
