### ISSUE TITLE
Insulated gloves lose their insulation when dyed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8203]
Probably not intended!

**Comment by Mandurrrh** [comment]
Ill test this out next round. It may very well be they were the trick insulateds and someone didn't exam. coughcoughscaredycough.

**Comment by phil235** [comment]
can't reproduce.

**Comment by Miauw62** [comment]
this is probably a dupe.

**Comment by phil235** [comment]
duplicate of #7321
