### ISSUE TITLE
Knitting Borg Flesh

### ISSUE THREAD

**Issue by Cheridan** [tgstation/-tg-station#8212]
You feel your burns healing and your flesh knitting together!
You feel your burns healing and your flesh knitting together!

I WAS A SYNDIBORG

**Comment by Chocobro** [comment]
hahahaha

**Comment by Anonus** [comment]
Fun fact borgs are damaged by acid and probably other stuff that does stuff on touch

**Comment by Iamgoofball** [comment]
easy fix
