### ISSUE TITLE
HoS Gun Description was written by a Lobotomy Patient

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8214]
"This is a modern recreation of the antique laser gun. This gun has several unique firemodes, but lacks the ability to recharge over time, its also expensive."

its also expensive

Godammit I'm going to configure git just so this minor conventions error stops bothering me so much

**Comment by RemieRichards** [comment]
```it's```

**Comment by Jordie0608** [comment]
@Steelpoint

**Comment by Fayrik** [comment]
Should probably be rewritten entirely to sound more formal. "This is an expensive, modern recreation of the antique laser gun." etc, etc.

**Comment by SconesC** [comment]
I'm just at a loss as to what 'its also expensive' is supposed to mean

The gun was expensive for the HoS/NT to purchase?
The firing modes are expensive?

**Comment by RemieRichards** [comment]
expensive to make.
also it needs to be it's not its.

**Comment by Steelpoint** [comment]
I let the ball slip simply because at that point I was more convened about getting the PR finished and merged.

I'll fix the spelling.
