### ISSUE TITLE
Mimana plants don't work consistently (plus small botany bugs)

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8218]
Grew 100 potency mimanas, ate one, hoped to be silent 5ever. I could talk right the fuck away and the silencing effect seemed to only kick in randomly. Something to do with chem processing?

also I'm not making a separate issue for this but oat stalks appear as "oat Stalks" and not "Oat Stalks" like the capitalization should be

**Comment by Miauw62** [comment]
probably the reagent adds one to silence every tick, but life subtracts one
from silence every tick.

**Comment by phil235** [comment]
the problem isn't life, it's goofball's change to reagents/metabolize.
