### ISSUE TITLE
Closed hidden doors let gasses pass

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#822]
##### Revision that this bug was encountered on:#####
5b4b541c172e12378ec3ec2f8b7a0597c5d6a6dd

##### Which server were you playing on? #####
Urist McStation (Private server, runs /tg/ code)

###### What did you expect to happen? ######
I expected the hidden door to block gasses.

###### What happened instead? ######
The gasses went right trough the closed hidden door.

###### Why is this bad/What are the consequences? ######
This means that you can't have hidden doors to space and various other things. It also means that gasses like no2 can be used to track down hidden doors.

##### Steps to reproduce the problem: #####
1. Make a hidden door
2. Put it next to a canister of (visible) gas
3. Make sure the hidden door is closed.
4. Open the release valve of the gas canister.
5. Watch as the gas goes right trough the closed hidden door.

##### Possibly related stuff: #####
The door I tested this on was a normal, non-reinforced one.

**Comment by Razharas** [comment]
Ok, its been a long time and none seem to care, so i make a judgement call on this - intended behaviour
Case closed

**Comment by Miauw62** [comment]
rip my first issue report ;~;7
