### ISSUE TITLE
Bug: Mining and Syndi shuttle collide when in transit at the same time.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#8220]
Well almost, if the sydnicate shuttle and the mining shuttle are in "transport" space at the same time the synicate shuttle crashes through the front of the mining shuttle. It looks like some sort of badass chase. But it ends with the mining shuttle missing its front half, including the console IIRC.

Should have taken a pic but it was round end and all happened so fast.

**Comment by MrStonedOne** [comment]
You should change the title, Being in the same z level is not a bug, the entire space station is the same z level. having them occupy the same x an y level is. Most maintainers are gonna skip over this thinking its not something worth looking at.

**Comment by peoplearestrange** [comment]
Ah ok, will change it up.

**Comment by Steelpoint** [comment]
Best guess is that the two ships were put too close together on the transit level.

**Comment by peoplearestrange** [comment]
Seemed to be by about 2 tiles (Sydni shuttle sitting above the mining shuttle). This doesn't really have the potential for harm due to where they collide (engines and front of ship) and the likelihood is pretty minimal, but still, thought it was worth mentioning.

**Comment by Chocobro** [comment]
nabbed a picture from a round just now on sybil! bit hard to see since i was injured, but still.
![syndieminingshuttle](https://cloud.githubusercontent.com/assets/5677255/6642359/f72600dc-c99b-11e4-8c82-a794b4e3a42a.png)
