### ISSUE TITLE
Hulks ignore critical state.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8224]
After hulk recieves 100 or more damage it goes into crit, yet isnt knocked out and can just keep walking, beating people, CPR himself and takes crit oxy damage.

![bug](https://cloud.githubusercontent.com/assets/10717398/6546184/4df405ee-c5aa-11e4-8731-77ef102d4f7a.png)

Reproduce:

-Spawn a human
-Give it hulk
-Deal 100 or more damage

Expectations:

Hulk gets knocked out after recieving some damage and losing its power.

Reality:

Hulk running around in crit, able to suck its own mouth and beat people.

Current code.

**Comment by WJohn** [comment]
I thought hulks lost their power if they went below 40 health? How are they still hulks there?

**Comment by SeikoTheSeal** [comment]
> Expectations:
> 
> Hulk gets knocked out after recieving some damage and losing its power.
> 
> Reality:
> 
> Hulk running around in crit, able to suck its own mouth and beat people.

Beats me.

**Comment by phil235** [comment]
that's my fault. derp

**Comment by SeikoTheSeal** [comment]
You shouldnt be in crit as a hulk in first place tho, you are meant to lose your hulk once below 40 health, like WJohn said.
