### ISSUE TITLE
Drone inactive state is still the old sprite.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8229]
Since we've moved to newer, better sprites, this is kind of a really ugly inconsistency. The new drones actually do have inactive sprites, not sure why they weren't used.

**Comment by WJohn** [comment]
Oh wait hang on, we've reverted to old drone sprites. Why?

**Comment by Incoming5643** [comment]
There's the choice of either

**Comment by WJohn** [comment]
Why do we even have a choice between glorious new sprites and hideous old sprites?

**Comment by RemieRichards** [comment]
Because choice is kind @WJohn, not to mention the entire addition of the new skin was because it was part of a larger cleanup of how drones handled icon states internally, it allowed for multiple skins, so my god am I going to give you multiple skins.

**Comment by dannno** [comment]
choice is nice but I do think it might be better to just stay consistent with one set of sprites for drones.

**Comment by Dorsisdwarf** [comment]
The new drone sprites are too small.
It makes you look like a beetle.
also they're copypasta'd from vg/bay, so there's that too

**Comment by WJohn** [comment]
But the new drone sprites actually look adorable and are very well done, they also mimic the base cyborg module in colors and style very well.

**Comment by Dorsisdwarf** [comment]
They dont look adorable at all. They're exceedingly ugly, like a blob of spikes with some animated legs on the bottom.

Scout drones are quite nice though.

**Comment by RemieRichards** [comment]
@Dorsisdwarf entirely subjective, it's an opinion.
quite a few people (I think the majority actually) prefer them, myself included.
and the fact they're from vg/bay means nothing whatsoever, it's called a port.
