### ISSUE TITLE
You can dupe cyborg modules through cavity implants.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8234]
![bug2](https://cloud.githubusercontent.com/assets/10717398/6547077/7824178c-c5cd-11e4-9352-0ecb1f7973be.png)

Perform a cavity implant surgery, when its time to implant the item use any of the cyborg modules, its now inside a patient. Perform a surgery again to remove the item, humans now can use borgo modules.

Humans can use the modules, but cant drop them or get rid of them in any way. Borg cannot use the module anymore, but have no fear! Use a reclassification board on the borgo, viola! Module works again and doctors now have a fancy borgo hypospray!

 You can put items like borg disablers and lasers inside rechargers, while still having them in hand. Never run out of ammo again!

**Comment by phil235** [comment]
@Incoming5643

**Comment by Incoming5643** [comment]
Not my fault, there's an oversight in surgeries to where it doesn't respect NODROP. All the same I'll fix this now.

Really interesting that humans can use the implanted modules though.

**Comment by Miauw62** [comment]
I wouldn't call it an oversight, I just added NODROP checks to the five
most obvious places and then fixed bugs as they came.
Op 8-mrt.-2015 21:20 schreef "Incoming5643" <notifications@github.com>:
