### ISSUE TITLE
pulling + throwing fast-travelling

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#8239]
Having someone pull you, then grabbing them and throwing them, will cause both you and the person you threw to be moved very quickly to the place you threw the person. Probably not technically a bug but the physics behind it are silly.

**Comment by Pennwick** [comment]
Captain grab my bike horn! ADVENTURE!

(Actually this is the only way I think this could really be abused. Having someone throw you in space while they're dragging you sending you both off at sanic speeds.)
