### ISSUE TITLE
Using a staff of change on maint drone makes them drop an all-access ID card.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#8240]
The ID is the one embedded in the drone letting him open everything.
The drone also drops its toolbox upon being transformed into something else, but that's not a big issue.
And if you can manage to retransform it into a drone then changing him again will drop another all access ID.

And syndrones drop an all access ID but also a syndicate hardsuit helmet that can't be drop once picked up and a usable syndicate uplink.

**Comment by WJohn** [comment]
10/10

**Comment by bgobandit** [comment]
A+

**Comment by Incoming5643** [comment]
Originally reported and fixed in #5557

Looks like the fix stopped working
