### ISSUE TITLE
YOU CANNOT HARVEST PLANTMEN

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#8243]
SOULS TRAPPED IN PLANTS UNTIL THEY DIE
HOW HORRIFYING

**Comment by hanshansenhansson** [comment]
I noticed you can not harvest replica pods that are "uncloneable" for whatever reason, means you do not get seeds at least. Otherwise it worked for me yesterday. You had the process right? Blood in seeds, seeds in pod, and murder the dude before you harvest?

**Comment by Incoming5643** [comment]
Unlike cloning pods, the player isn't actually IN the pod until it's harvested.

But yeah plantman cloning just fails at the step under certain conditions, not sure how much of it is bug and how much is feature.

**Comment by pudl** [comment]
really the best way to solve this is just a message telling you if the person is online when you try to harvest. chances are nothing is broken, it's just a lack of feedback that makes you think it doesnt work

**Comment by dannno** [comment]
Happened to three different people, I really doubt that this is just bad luck

**Comment by Incoming5643** [comment]
Were there aliens/golems/drones about? They might have come back as those things before your plantman was fully grown.

**Comment by pudl** [comment]
i was there and yoshmaster didnt even know whose blood it was, it could have all been the same person
the same alive person even

**Comment by dannno** [comment]
all three syringes had different blood and i can guarantee that

**Comment by Incoming5643** [comment]
If blood samples had managed to have been mixed with each other at any point that could have also put the kibosh on a podman

**Comment by callanrocks** [comment]
Confirming that pods are bugged as hell and have been for years. Its a bit of a tossup if they work or not, the ghost apparently has to be in body before it gets to the last stage or something dumb like that or the thing just breaks.

**Comment by Incoming5643** [comment]
That used to be the case, but it was refactored a long while ago to remove that requirement. All the information needed to clone the person is stored in the blood (which is why it doesn't work if the blood has gotten cocked up in any one of a number of ways)

**Comment by theOperand** [comment]
maybe pods need a complete rewrite
