### ISSUE TITLE
Lings w/ Thermal Eyes not knocked over by Flash

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8244]
The flash reaction, specifically

It does stun you however - Makes you SORT OF OBVIOUS as a ling when everyone but you falls over

**Comment by Lumipharon** [comment]
Can we just remove or nerf ling vision into the ground? Shit is seriously over powered as shit, has NO chem requirement, and just stays on forever.
Thermals and nvgs, seriously, this means there is literally zero risk of ever being snuck up on.

**Comment by Xhuis** [comment]
I made this, so I'll do some balance changes.

**Comment by Lumipharon** [comment]
Sounds good, although I'd say just stop chem recharge altogether/use over time with eyes on, so you can't just leave it on all day

At the moment there's no reason not to buy it, and have it on 24/7.

**Comment by xxalpha** [comment]
@phil235 Since flashes don't knock down anybody, this could be closed?

**Comment by Xhuis** [comment]
Yeah, these changes have been implemented.
