### ISSUE TITLE
Rougelike mode bug? UI lost.

### ISSUE THREAD

**Issue by Antimattercarp** [tgstation/-tg-station#8245]
This happened at random 
![gh](https://cloud.githubusercontent.com/assets/9055110/6548433/c66e50b4-c5ce-11e4-9612-9551ade27f3f.PNG)

**Comment by Jordie0608** [comment]
Somehow your client was set to render in ASCII mode, it can be changed by going to the Icons menu.

**Comment by WJohn** [comment]
How the hell?

We have an ascii mode?

Why.

**Comment by Jordie0608** [comment]
Because BYOND was initially developed for MUDs

**Comment by Incoming5643** [comment]
The only place in the entire code I can think of that uses ascii mode is one of the filter for drone vision

**Comment by Jordie0608** [comment]
I may be wrong, but that filter just replaces the mob's icons with letters, the image in the report is BYOND fully rendering everything it can in ASCII as opposed to 32x32 or 64x64 sprites.

From what I can tell the letters there represent an inventory of a human and not a drone.

**Comment by Alek2ander** [comment]
There's no map though (even consisting of letters), so maybe related to #8231

**Comment by RemieRichards** [comment]
Lack of a map IS indicative of being in nullspace.

**Comment by Dorsisdwarf** [comment]
BYOND definitely has ASCII mode, I once spooked myself by turning it on somehow. Nothing to do with nullspace or drones, afaik.

**Comment by Miauw62** [comment]
ASCII mode is not a bug, nullspace is a bug but this issue report contains no information pertaining to this.
