### ISSUE TITLE
Cloaked Ninjas fire cloaked projectiles

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8249]
Cloak as ninja
Fire egun/laser/disabler

Invisible

Hilarious, but totally broken

**Comment by dannno** [comment]
*REMOVE*
*NINJA*

**Comment by Miauw62** [comment]
REMOVE NINJA remove ninja. You are the worst ninja, you are the ninja
shitcode you are the ninja spaghetti etc etc
Op 9-mrt.-2015 06:44 schreef "dannno" <notifications@github.com>:

**Comment by Incoming5643** [comment]
<i>REFACTOR
NINJA


<i>BUT
NOT
ME
