### ISSUE TITLE
Blobs get disconnected and sent back to lobby when their core is killed

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#8260]
The blob's overmind cursor mob was still alive and moving as well for a short time after the core was killed, then it got deleted and the user disconnected and they came back in lobby.

@Miauw62 @Incoming5643 @Iamgoofball 
This is either a qdel issue, a chemblob issue, or a mulligen issue.

**Comment by WJohn** [comment]
Mulligan also seems to struggle to continue blob rounds, often breaking.

**Comment by Xhuis** [comment]
I know from experience on a local server that getting rid of a mob's ckey while that ckey is still in the mob causes this behavior, so it's probably something to do with the player not becoming a ghost before the cursor is deleted.

**Comment by Boredone** [comment]
As a side note, there was a Hotfix for blob mulligan rounds, but SoS just hasn't updated since the hotfix was merged.
Server (At the time of this issue request unless SoS updated really recently) is updated to #8065 
The hotfix is after that in the pulse list, #8145

**Comment by Incoming5643** [comment]
yeah the mulligan problems had to do with the round not realizing it had been changed in a few instances, which should be fixed at next server update. It has nothing to do with this.

**Comment by peoplearestrange** [comment]
Along the same lines as this bug I noticed it doing some strange things the other day. When forcing someone to blob via the PP it dragged another person in from the observers to play as blob, on the same blob core. Very briefly could even see two "placement cursors" or whatever you call them. They then dropped connection (observer) and could rejoin as a new character.

**Comment by peoplearestrange** [comment]
Oh also the people that are dropped connection from loosing there blob core can rejoin the game again as a player. As if they never played the round at all.

I also noticed a few times where blob cores would self destroy. By which I mean as soon as they blob burst they would drop connection. This was just standard blobs created by the game mode not via the PP.
