### ISSUE TITLE
Right Click menu is obsolete

### ISSUE THREAD

**Issue by dannno** [tgstation/-tg-station#8265]
the only reason I would ever use it anymore is to look at a pile of things that I can't physically reach, which isn't even that important
right click can be used as an alternate hotkey instead 
this way, all object verbs on items could be replaced with right click/alt click/ctrl click (I'm hard pressed to think of an item with more than 3 alternate functions besides tape recorders)

**Comment by kevinz000** [comment]
Time to remove yet another thing that is personally useful for me.

**Comment by dannno** [comment]
explain how

**Comment by WJohn** [comment]
I personally can't be arsed to use alt clicking, and I absolutely despise tabs like that.

Until every function you can have in right clicking gets moved to action buttons or something more sane, I'd like to keep it as-is.

**Comment by dannno** [comment]
that's the plan

**Comment by RemieRichards** [comment]
already said in IRC to danno but stating here for the record:

I'm more literate with my mouse than my keyboard, since my mouse uses my main hand and my off hand is on the arrow keys, I'm not moving all the way to alt unless I know the file of items is going to cause lag.

**Comment by ike709** [comment]
death to alt click!

**Comment by dannno** [comment]
this is a pill that ultimately you will benefit from if you swallow

**Comment by ike709** [comment]
>this is a pill that ultimately you will benefit from if you swallow

death to alt click!

**Comment by optimumtact** [comment]
death to right click menus

**Comment by Dorsisdwarf** [comment]
Right-click cannot be removed. Admin verbs use it (delete, osay, player panel, subtlemessage, etcetera)

**Comment by optimumtact** [comment]
death to admins

**Comment by Chocobro** [comment]
don't fix what isn't broken. what works for you doesn't work for other users - think about that in future

**Comment by Delimusca** [comment]
what if the rightclick context menu was replaced with a simulated one, like a popup version of the alt click thing. it'd probably be slower, but it probably wouldn't freeze/crash the client.

**Comment by Miauw62** [comment]
how would you access object verbs of things that dont have a hotkey without rightclick.

:-1:

**Comment by dannno** [comment]
you're absolute trash

**Comment by Miauw62** [comment]
>says "BOO HOO I WANT TO BE ABLE TO CLICK OBJECT VERBS" in object verb
removal issue
>"hey guys we should remove the right click menu"

???
