### ISSUE TITLE
Spawning "replacement blobs" after mulliganed blob rounds leads to instability/crashing

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8266]
Will figure this out but in the mean time admins please stop doing this.

**Comment by Cheridan** [comment]
There is also and issue with Malf causing a lot of spam after a defeat: 
http://i.imgur.com/1SIjdxl.png

**Comment by Incoming5643** [comment]
haha, alright yeah that's pretty shit let me figure out why that's happening
