### ISSUE TITLE
If you accidently drop item from your hand in a mecha, item is lost 5ever.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8278]
Dropping an item from your hand inside a mech (using hotkeys), the item is added to mecha contents. No way to retrieve the item, game over man, game over. Destroying the mech destroys all contents.

**Comment by RandomMarine** [comment]
Fucking
Mechcode

**Comment by phil235** [comment]
Time to drop the nuke disk :^)
