### ISSUE TITLE
Hotline overdose is fucking crazy.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8280]
Damage Specifics: 0-10-0-19.8
Damage Specifics: 0-25-0-24.6
Damage Specifics: 0-45-0-38.4
Damage Specifics: 0-61-0-55.2
Damage Specifics: 0.666667-71-0-63

Edit. Just saw Goofs PR removing hotline from poppies, but it doesnt change the fact that no matter the way of obtaining it, it will be superior to litteraly everything.

Just fucking wow. 5 ticks to crit. 15u to fuck somene over with brain, brute and tox damage in 5 ticks.

I get it that overdosing this should be lethal and screw you hard, but currently hotline is far superior and just stupid crazy effective as a poison. At least up the overdose to 20u so that one syringe from a syringe gun wont be that crazy lethal.

**Comment by Iamgoofball** [comment]
I also removed hotline from the game in that pr.

**Comment by SeikoTheSeal** [comment]
T'is can be closed then, rip in pieces.
