### ISSUE TITLE
Mice can climb over grilles

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8281]
![mousegrille](https://cloud.githubusercontent.com/assets/5677255/6581338/1a7faed4-c74e-11e4-9e9f-8b6dcf32e72d.png)
normally i'd expect them to just not be able to do this, but now i'd prefer if the mouse can do it except it disappears under the grille.

**Comment by AnonymousNow** [comment]
For such a tiny creature, I'd call this a feature.

**Comment by phil235** [comment]
I intended that.
