### ISSUE TITLE
Station time starts at 11:00. Again.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8284]
What it says on the tin. This is broken again.

**Comment by Incoming5643** [comment]
Blame Daylight Savings Time

**Comment by Incoming5643** [comment]
Add Tag: US Government issue

**Comment by AnonymousNow** [comment]
Maybe we should set it so that shifts start at a decent or semi-randomised hour, like mornings and evenings? Doesn't change anything other than roleplay and fluff, but still.

**Comment by Miauw62** [comment]
Nah, it'd just be annoying. People use the station time to see how long a
round has been going on.

**Comment by Cheridan** [comment]
>Add Tag: US Government issue

THANKS OBAMA

**Comment by Jalleo** [comment]
Just add shift start below station time to have people calculate how long round has been done...

**Comment by Dorsisdwarf** [comment]
This isn't a bug, it's a feature that nobody likes (Station time experiences daylight savings time)

**Comment by Incoming5643** [comment]
See you next march!
