### ISSUE TITLE
You can knock yourself off of tables

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#8295]
You can knock YOURSELF off of the table you are climbing.
it needs to check if the person pushing off is the same as the climber.
this is especially painful for me as my mouse randomly clicks a lot leading to:
Climb --> Knock self off X5

**Comment by phil235** [comment]
@mandurrrh

**Comment by RandomMarine** [comment]
Maybe tablepushing should be moved to disarm intent?
Click somebody with disarm -> check if they're standing and on a table -> Weaken and push them away from the clicker?

**Comment by WJohn** [comment]
@RandomMarine that would be unnecessarily obscure for a useful feature like this. Bartenders and chefs would basically think we just straight up removed it or it was broken.
