### ISSUE TITLE
Silicons exclaiming doesn't use the proper font

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#8301]
AI states, "__Ayy lmao__"
AI queries, "__Ayy lmao?__"
AI declares, "Ayy lmao!"
AI alarms, "___AYY LMAO!!___"

Where bold represents the silicon font and nonbolded represents the normal human speech font.

**Comment by RandomMarine** [comment]
Use screenshots.
![2015-03-11 15_45_51-space station 13](https://cloud.githubusercontent.com/assets/6583225/6608615/cded9ab4-c805-11e4-9ce8-464337eabd51.png)

**Comment by Xhuis** [comment]
Thanks for providing that. As for the lack of a screenshot in the OP, I was lazy, so that's my fault.

**Comment by Iamgoofball** [comment]
Damn it paprika

**Comment by Jordie0608** [comment]
This got fixed at some point
