### ISSUE TITLE
Syndicate Smokes are currently worthless

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/-tg-station#8303]
They come pre-equipped with doctor's delight, which used to be a fairly decent with quick healing in exchange for some TCs. As of right now, doctor's delight does absolutely nothing, so the only reason you would buy the syndicate cigarettes at this point is a red and black cigarette box.

**Comment by Jalleo** [comment]
@Iamgoofball please rebalance.

**Comment by xxalpha** [comment]
>so the only reason you would buy the syndicate cigarettes at this point is a red and black cigarette box.

Which is badly sprited, if I might add.

**Comment by bgobandit** [comment]
goofball fix your shit

**Comment by Iamgoofball** [comment]
i got a plan

**Comment by CandyClownTG** [comment]
I edited the cigs to have Omnizine instead of Doctor's Delight.

**Comment by pudl** [comment]
close this issue
