### ISSUE TITLE
Liberation Station is broken due to #6996

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#8304]
Liberation station is an admin spawned vending machine.  However, because of #6996 in which admin spawned vending machines don't work, it's not usable.  It's said, to fix these admin spawned vending machines, you just need to de-construct the vending machine and then reconstruct it but the liberation station is not de-construct-able like all other vending machines.  Meaning it's un-usable forever until fixed.

**Comment by MMMiracles** [comment]
FUK

**Comment by Jalleo** [comment]
Please merge with main issue report maintainers. @miauw62

**Comment by MMMiracles** [comment]
#8307 will fix this, and as stated in the comments, initialize() can apparently fix the vending machines manually spawned in.

**Comment by Miauw62** [comment]
nah this is ok as a separate bug, liberation station being unrefillable/unconstructable is pretty dumb
