### ISSUE TITLE
Spawned helmets no-drop admin issues

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#8305]
If it is spawned by an admin, for some reason it can't be dropped and is "stuck" to your hand.  This seems un-intentional as the owl suit can be dropped.

**Comment by Jalleo** [comment]
@danno

**Comment by RandomMarine** [comment]
It's meant to be a component of the suit. The helmet should not be spawned on its own.

**Comment by Niknakflak** [comment]
Huh, I guess I got confused. SSU's still have a slot for helmets so I automatically tried to to put a spawned helmet into it.

**Comment by Jalleo** [comment]
Please update main info then please.

**Comment by WJohn** [comment]
Is this the case with other hardsuit helmets?

**Comment by RemieRichards** [comment]
Yes, they have the NODROP flag which prevents them from being unequipped, meaning you can't take them off without toggling the suit's helmet verb.

This has the side effect of meaning if you ever actually held the helmet item (via badminnery in this case) you can't drop it.

It's not a bug.

**Comment by Niknakflak** [comment]
Guess this doesn't need to stay opened then.
