### ISSUE TITLE
Monkey-Hulk hybrid

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#8306]
A monkey had a virus which gave it DN-Aide, it changes into a hulk and thus this happens http://puu.sh/gwzYa/d7b28853df.png
its description still remains the same as normal for a simple monkey sprite. Not sure what can be causing this, and its more aesthetics than game breaking.

**Comment by PKPenguin321** [comment]
this is the monkey manifesting the hulk power and getting the overlay, which is intended for the human sprite

i was under the impression monkeys weren't able to manifest powers in the first place

**Comment by Niknakflak** [comment]
Thats hilarious

**Comment by xxalpha** [comment]
Feature.

**Comment by Jalleo** [comment]
@Razharas what do you think the datums or virus code?
This is helarious though

**Comment by AnonymousNow** [comment]
Monkeys getting powers sounds like it'd be a hilarious feature if the overlay wasn't human.

**Comment by Durkel** [comment]
I already reported this. Honk
https://github.com/tgstation/-tg-station/issues/7597

**Comment by phil235** [comment]
duplicate.

**Comment by tedward1337** [comment]
Then fix it :^)
