### ISSUE TITLE
Roundstart donuts are eaten in one bite

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8308]
You nibble the donut.
it's gone immediately
i'm p sure regular made donuts don't have this problem

**Comment by bgobandit** [comment]
this is probably because of the amount of nutriment, pretty sure how fast you eat food depends on how much is in it

**Comment by Incoming5643** [comment]
Food items that inherit their nutritional values from a parent are generated completely empty if they're somehow generated without the parent. This is the same reason pizzas from cargo have nothing in them and some items from silver slime cores such as cakes slices suffer from the same problem.

**Comment by Jalleo** [comment]
Should we make a random nutrient generator that runs for non person made foods?

**Comment by Dorsisdwarf** [comment]
Yes.
