### ISSUE TITLE
Putting straight pipes on tables causes issues.

### ISSUE THREAD

**Issue by mrmindless** [tgstation/-tg-station#8312]
Problem Description: 
Putting a straight gas pipe onto a table causes it to become a bent pipe.

What did you expect to happen: 
Straight pipes should remain straight pipes when put on tables.

What happened instead: 
It turned into a bent pipe for unknown reasons.

Why is this bad/What are the consequences: 
General strangeness.

Steps to reproduce the problem: 
Create a straight gas pipe through any way, pick it up, then place it on a table.

Server:
Tg station: Sybil.

Revision: 
6f0319e7b7833d3e88909953f5e50b260db0c387

**Comment by Jalleo** [comment]
@menshin got a clue why this occurs?

**Comment by Menshin** [comment]
Putting a pipe on a table uses _Move()_ that changes its dir... which is used for the different pipe orientations.

So putting a pipe diagonally on a table "bends" it and putting it from a cardinal direction "straighten" it up.

**Comment by Miauw62** [comment]
Any reason why it can't just set the loc? It'd also let the chef put food
on the microwave tables which could be pretty convenient.

**Comment by Delimusca** [comment]
i presume it uses move to stop things phasing through dense stuff.

**Comment by phil235** [comment]
No, the move() isn't used to check for dense obstacles. No idea why it's there.

**Comment by duncathan** [comment]
I fixed this forever ago

**Comment by phil235** [comment]
@duncathan Are you sure? The bug was still there last time I tested it, 2 weeks ago.

**Comment by duncathan** [comment]
My bad, it was every other case of this bug (dragging, throwing, etc) that I fixed
