### ISSUE TITLE
Acid Blob Spores create CLOUDS OF ACID on death

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8316]
BALANCE ISSUE

what the actual fuck, it creates ACID SMOKE CLOUDS when a spore dies

holy fuck thats the most op thing ever

**Comment by Durkel** [comment]
Blobbernaughts also attack with acid, melting your gear and weapons. You ever try fighting a 300hp monster naked with your fists?

**Comment by GunHog** [comment]
I am working on EUK (Equipment Upgrade Kit), the first of which will allow you to plate items in gold for acid resistance. Until then, you may wish to consider fighting an acid blob at range. Oh, and biosuits will grant you some defense against the acid.

**Comment by WJohn** [comment]
@gunhog I'd kinda like it if that was handled as a chemical coating so we don't have to worry about having GOLDEN ITEMS.

**Comment by Iamgoofball** [comment]
@WJohn who in their right mind would complain about being able to bling out their gear in gold

**Comment by Jalleo** [comment]
Goofball can you work with gun to make a pr to balance it making a chem and other forms of acid resist?
Glass armor anyone?

**Comment by Marflowerose** [comment]
EUK is not the remedy to acid blob imbalance. If anything, it just highlights that there is such imbalance. Stop trying to sugarcoat it like "Don't fight it melee then" when you cannot not be in melee of blobbernaut and spores and there's limited amount of space suits. Remove acid until it is balanced properly. Cargo should be able to order acid suits, gold/silver coated gear, acid gas shouldn't melt anything outright. Liquid acid sure but gas no.

**Comment by Jalleo** [comment]
@RemieRichards what suggestions do you have?

**Comment by SconesC** [comment]
@Iamgoofball I understand the design intent between blobs/blobbernauts transferring chemicals but holy fuck it has led to so many horrible blob rounds because blob spore clouds transfer them

spore clouds being flurosulph acid clouds is not okay
the brute one leaving clouds of HURT is pretty annoying as well
