### ISSUE TITLE
Aliens can't attack turrets.

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#8321]
Pretty irrelevant since you can slash APC but aliens can't attack turrets.

-"You don't have dexterity.. etc"

**Comment by WJohn** [comment]
Probably something thanks to porta turrets. Surprising it took that much time to get reported, but I guess attacking the core is much harder nowadays, as porta turrets + AI sat happened at around the same time.

**Comment by Jordie0608** [comment]
Porta turrets aren't overriding the default behavior of attack_alien.
