### ISSUE TITLE
Plasma isn't going into space

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8327]
i don't entirely know how to title this issue correctly.
![spaceplasma](https://cloud.githubusercontent.com/assets/5677255/6640777/767f47fe-c991-11e4-871c-33a5501a19a5.jpg)
i can't provide any more information than the image, other than that area is just outside escape on box, sybil. 13 march 2015, 2:50pm GMT-0.

**Comment by Marflowerose** [comment]
Plasma visual tends to stick around even if there's 0.00001kPa which is what we're probably seeing.

**Comment by phil235** [comment]
This issue happens on the tile just outside the incinerator. After using the machine, the tile is full of hot pressurized plasma that never goes away into space.

**Comment by MrStonedOne** [comment]
fixed by #10864
