### ISSUE TITLE
Different parts of turbine/compressor assembly are sometimes broken

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8329]
Some shifts, everything is fine. Sometimes, the console is not finding the compressor, giving the "There is no compressor" message. Sometimes, screwdrivering the compressor open and shut fixes it. Sometimes, this is not working. 

That thing is really strange, no clue whats going on with it

**Comment by phil235** [comment]
This again... 
Probably related to #4312.
@Razharas

**Comment by Razharas** [comment]
I really couldnt pinpoint the reason why this is happeni9ng, the code is very simple

**Comment by AlexanderUlanH** [comment]
It seems to me like there's a problem in the logic of connecting the two parts.  I've had random cases of turbine/compressors' stats being 'BROKEN' when they had something to connect to.
