### ISSUE TITLE
Ghosts can be turned into slimes without any say in the matter

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8331]
>die from syndicate bomb
>hop retrieves my corpse and takes it to genetics
>about to be put into the cloner
>get ready to hit re-enter corpse
>You are now a slime.

all of my candidacies are set to off.

**Comment by Incoming5643** [comment]
It runs on be_alien

**Comment by Chocobro** [comment]
absolutely certain.

**Comment by Incoming5643** [comment]
Could not replicate locally, unless being scanned/cloned in the same tick as the slime looks for a host is part of the bug (would not be surprised)

**Comment by Cheridan** [comment]
There should probably be a Would you like to become a slime? Y/N window or something when this kind of thing happens.

**Comment by Incoming5643** [comment]
I'll look into it
