### ISSUE TITLE
MMIs can take damage and go into... MMI crit?

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8332]
I'm an MMI that got forcibly debrained until security stopped them, the officer are trying to get my brain out of the MMI (they said it was unlocked already, but given the situation it's entirely plausible it wasn't), I tell them to crowbar it. It results in (all attack messages are bold and red, as if they are happening to me, as opposed to my body, which was also there):

Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been attacked with the pocket crowbar.
Fortune Ray has been attacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been attacked with the pocket crowbar.
Fortune Ray has been bludgeoned with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been attacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been bludgeoned with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Myles Stainforth has thrown Man-Machine Interface: Fortune Ray.
Myles Stainforth says, "No good."
Fortune Ray has been bludgeoned with the pocket crowbar.
John Titor asks, "God damn lizard couldn't even unlock an MMI?"
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been bludgeoned with the pocket crowbar.
Fortune Ray has been bludgeoned with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been battered with the pocket crowbar.
Fortune Ray has been battered with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
Fortune Ray has been attacked with the pocket crowbar.
Fortune Ray has been bashed with the pocket crowbar.
Fortune Ray has been whacked with the pocket crowbar.
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...
... You can almost hear someone talking ...

My screen went black (but no HUD), except for that it looks and acts like I am in crit. Also possibly of note: The bashing had no click delay, it seems.

I send an adminhelp like "yo what the fuck", ask whether this is a bug:

-- Administrator private message --
Admin PM from-Sometinyprick: I got rid of all your brute but you should probably report that, the main problem is how you actually recieved damage in the first place
Click on the administrator's name to reply.

-- Administrator private message --
Admin PM from-Sometinyprick: I'm 99 percent sure you shouldn't be able to attack MMIs with a crowbar
Click on the administrator's name to reply.

**Comment by Cheridan** [comment]
I believe that damaging MMIs has always been a feature. The ability for brains to enter crit is new, however, added by #7854

I don't think this is a bug, however there IS a related problem I had someone ahelp where upon being detonated via console, an MMI immediately became critical (probably damage from the explosion)

**Comment by phil235** [comment]
You don't remove a brain from an mmi by crowbaring it, you simply click it.

**Comment by Jalleo** [comment]
Should be made clear in examine of the mmi.

**Comment by phil235** [comment]
Brain can no longer be in crit thanks to the new life refactor, but the problem with brain taking damage when a borg is blown.

**Comment by phil235** [comment]
Can't reproduce the brain taking damage when a borg is blown via console. Closing this.
