### ISSUE TITLE
Secways aren't affected by velocity or space pull

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8333]
![secwaygravity](https://cloud.githubusercontent.com/assets/5677255/6643417/fff8de8e-c9a3-11e4-804b-8a11c239d1e3.jpg)
he stayed there for the entire ride.

**Comment by Incoming5643** [comment]
A side effect of inheriting from chairs

**Comment by phil235** [comment]
Does this also happens with office chairs?
