### ISSUE TITLE
Janicarts can activate MAXIMUM OVERDRIVE with a fire extinguisher

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8335]
So fun I feel guilty reporting it

You can jet around at mach 5 if you're moving in a direction and use a fire extinguisher to boost you, same way it works if you are buckled into a chair

**Comment by Niknakflak** [comment]
A janitor seriously harassed me one round doing this

**Comment by SconesC** [comment]
its so much fun to disarm people or steal prisoners and ZIP THE FUCK OUT

**Comment by dannno** [comment]
leave it in

**Comment by Dorsisdwarf** [comment]
Feature. You don't get any hands free doing this, so the only mechanical bonus is WHEEEEEEEEEEEEE

**Comment by Dorsisdwarf** [comment]
Closed for issuecount
