### ISSUE TITLE
Slimes sometimes don't stop wiggling after they die

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8336]
Though they die, sometimes the slime mob sprite doesn't change to dead. Noticed since the life rewrite.

**Comment by phil235** [comment]
Are you sure the slime wasn't simply in crit?

**Comment by Chocobro** [comment]
i thought simple animals didn't have crit

**Comment by Anonus** [comment]
Slimes aren't simple animals

**Comment by Incoming5643** [comment]
I'm pretty sure it wasn't in crit, unless slimes show their death message while they're still technically in crit

**Comment by phil235** [comment]
The only way I can reproduce it is with crit. You hear the body falling to the ground sound (as if dead) but no death message, the slime keeps jiggling up and down for up to 30 seconds then actually dies.

**Comment by Kromgar** [comment]
The slimes never stop  moving (jiggling) when their unhappy faces appear before they die

**Comment by Incoming5643** [comment]
was fixed in the refactor it seems
