### ISSUE TITLE
Simple animal aliens will plant weeds even if there are already weeds beneath them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8341]
Come on, how was that not tested for?

**Comment by WJohn** [comment]
To clarify: They place nodes on regular weeds, but not on nodes.

**Comment by RemieRichards** [comment]
placing nodes on weeds is fine, lots of human xenos do it all the time.

Not to mention I've already placed lots of simple aliens on basil and they produced a decent nest, yes there were a few nodes close together, but it's fine.

**Comment by WJohn** [comment]
Hm, should probably be changed for both of regular and simple animal versions to be unable to place nodes on existing weeds.

**Comment by RemieRichards** [comment]
Why? If normal xenos want to place nodes on weeds, let them.
This is really a non issue.

**Comment by AnturK** [comment]
Well i suppose i could add some more sophisticated clustering code but then i'd need to probably change their behaviour to go and look for unweeded turfs.

**Comment by WJohn** [comment]
Alright then, I'll close this.
