### ISSUE TITLE
C4 can be placed in the experimentor and planted at the same time

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8342]
![oh god](https://cloud.githubusercontent.com/assets/5677255/6652730/ba4ae04e-ca70-11e4-9459-92a0d3c79d77.png)
AAAAAAA

**Comment by Anonus** [comment]
This happens with the DA as well because C4 is crap and magic.

**Comment by Cheridan** [comment]
fixed by #8483
