### ISSUE TITLE
Podpeople still no colour, ##8247 is a lie

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8345]
Just had a wizard round, where everyone swapped their race. During the first race-swap, all pod-people I saw were gray. Other xeno-races like Lizards and "the other Lizards(?)" and Slimepeople were all coloured. Just not podpeople.

After the second race-swapping for everyone, coloured pod-people appeared. 

--------

Tested in the next round:
Red Lizard -> Grey Podperson

**Comment by hanshansenhansson** [comment]
Hm, just realized the merge was just 24h ago, thought it already went in a while ago. Sorry if it is not updated yet.

**Comment by Incoming5643** [comment]
It's not live no

**Comment by WJohn** [comment]
We'll see if it's ACTUALLY fixed when the server is updated before closing this, I guess.

**Comment by Jordie0608** [comment]
I think #8247 only affects podpeople made from hydroponics

**Comment by Incoming5643** [comment]
Pod people from NOT hydroponics should have never been affected in the first place. I think he false positive'd that because a lot of people never set their alien color and random DNA never grants any other color besides that grey shade.

I'm pretty dang sure this is fixed

**Comment by hanshansenhansson** [comment]
Maybe. 

Just tested it, am finally a beautiful flower. Thanks for fixing it. Can be closed. Can I close it?
