### ISSUE TITLE
Kitchen overhaul broke bread

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#8346]
You get the message "you form a dough", but the dough is nowhere to be found

Critical priority please, 50% of kitchen recipies defunct

**Comment by Incoming5643** [comment]
Is the dough not actually there, or is it invisible on the ground? We've been having a lot of recent sprite accidentally get reverted lately.

**Comment by phil235** [comment]
yeah, I made that PR a bit too fast. I'll fix asap.
Cakebatter should still work though.
