### ISSUE TITLE
Captain and pirate suit make your uniform disappear

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8350]
http://i.imgur.com/DhYenmY.png

I'm wearing a jumpsuit in that pic, but as soon as I put on either of these it vanishes.

This might happen with more than just these two suits.

**Comment by RemieRichards** [comment]
Not really a bug, it's the HIDEJUMPSUIT flag.

**Comment by WJohn** [comment]
There's no reason for these to be hiding your jumpsuit though... Why would there be any need to hide your jumpsuit at any point, anyway? Is it to very barely save on processing power to not have to handle one or two extra overlays around the station?

**Comment by RemieRichards** [comment]
@WJohn some "Suit" objects have inbuilt uniforms, it's for that.
also to prevent uniforms clipping underneath smaller suits.

**Comment by WJohn** [comment]
Oh, I guess it makes sense for the clown's jumpsuit, but that's really just an exception, not the rule. It's fine for that captain's space suit that covers the whole body, but not the pirate suit that's really just a jacket.

**Comment by SconesC** [comment]
@RemieRichards  So when sprite-editing shit the solution is to not use things with the HIDEJUMPSUIT flag?

**Comment by RemieRichards** [comment]
@SconesC can't quite decipher what you're saying (it's late (ok technically early) here)
but:

If the suit has HIDEJUMPSUIT, the uniform/jumpsuit icon will never show up as long as that is worn.
including with sprite edits.

**Comment by WJohn** [comment]
I think this issue is just a matter of going over what should and shouldn't be able to cover your jumpsuit, pirate space coat being one of them that should not, as it's just a jacket.
