### ISSUE TITLE
Egg itemstates fukt up

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#8355]
HOW TO REPRODUCE:
1) hold egg in right hand
2) face right
3) marvel at ability to hold egg with your ass

**Comment by phil235** [comment]
Yep, it's standard raw egg only, the colored and boiled eggs are fine. The "egg" icon in items_righthand.dmi and items_lefthand.dmi lacks a sprite for each direction.

**Comment by Chocobro** [comment]
i've been laughing at this description for several hours
