### ISSUE TITLE
Empty Item Stacks Allow For Infinite Resources

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8357]
If you find a 0 item stack (saw one spat out of the smelter in cargo) and hold it in one hand and then click it with your other empty hand, you can repeatedly grab free materials from the 0 stack without the 0 stack ever deleting.

**Comment by xxalpha** [comment]
How are these stacks being created?

**Comment by Incoming5643** [comment]
In this case it was silver, but I'd imagine that it'd work the same for any stackable

And I'm not sure, other than to say that the ore redemption machine can do it.

**Comment by xxalpha** [comment]
Oh jesus, it's so simple, so terrible.

**Comment by soulgamer** [comment]
You can get one of each zero stack of rare materials just by deconstructing the ore redemption machine. Just tested on server.

**Comment by xxalpha** [comment]
I can't reproduce that soulgamer.

**Comment by Incoming5643** [comment]
it's possible the stack item only exists once minerals are in the machine legitimately

aka it stores the items as a literal stack within the machine (good) but it doesn't delete the stack item when there's nothing in the stack anymore (bad)

**Comment by xxalpha** [comment]
I'll try again.

**Comment by soulgamer** [comment]
I signed up, walked to the redemption machine, emptied it, dissasembled it. Gave me a zero stack of gold, silver, plasma, diamond, and uranium

**Comment by Miauw62** [comment]
Zero stacks should delete themselves when they find out what they have
become, imo
Op 15-mrt.-2015 20:59 schreef "soulgamer" <notifications@github.com>:

**Comment by xxalpha** [comment]
That's what my PR does.
