### ISSUE TITLE
Wounded Jetpacking

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8360]
I noticed that I was slowed down in space after being wounded by carp even though I was just strolling around with a jetpack, not walking on girders. Could've been just space lag but sure seemed to slow down. Wound was mainly on leg if that matters.

**Comment by Lumipharon** [comment]
SLOWSPESS

**Comment by optimumtact** [comment]
Being injured slows you down regardless of jetpack speed, if you feel this is in error I could investigate changing it.

**Comment by Jalleo** [comment]
This should really be only slowing down the jetpack people if the jetpack is damaged...

**Comment by Lumipharon** [comment]
slow down AT ALL in space makes no sense. You are drifting in space. Doesn't matter if your arms and legs are blown off, this shouldn't make you slower since you're drifting.

With a jetpack, the jetpack is propelling you, so again, how does your health effect this in anyway?
