### ISSUE TITLE
Cannot Make Zombie Powder

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#8361]
The problem here is pretty simple.
Zombie Powder requires stoxin, better known as sleep toxin, to be made.
Sleep toxin got cut out of the code besides its recipe (Which is getting fixed)... and it being used for Zombie Powder.
So, should be easy enough to do a quick change to making it require morphine instead of Sleep Toxin.
For reference, Zombie Powder currently requires 5 Stoxin, 5 Carpotoxin, and 5 copper to make 2u or so of Zombie Powder.

**Comment by phil235** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
Pretty sure I made it use morphine, I'll double check.
