### ISSUE TITLE
Ghost-sight/ears are ignored with round start preferences that set them to off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8362]
I have my preferences normally turn ghost ears and ghost sight off from the start, but since the ghost radio addition I have had to manually turn these off in game.

**Comment by Incoming5643** [comment]
already fixed in #8328

**Comment by WJohn** [comment]
Oh, server hasn't been updated then. I'll close this.

**Comment by WJohn** [comment]
This issue is back.
