### ISSUE TITLE
Chameleon genetic power is broken.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#8370]
Doesn't work, or at least it doesn't appear to work every time I've had or given it to someone. Likewise, cloak of darkness seems fugged too. This might need some testing on someones side first to confirm it though.

**Comment by GunHog** [comment]
Chameleon is meant to work as long as the mob does not move. My testing of this reveals that it is not functioning for me. Cloak of darkness seems to be failing me as well. It should work in darkness, thus acting as a counter to night-vision.

**Comment by Iamgoofball** [comment]
Didnt someone fuck with the vars on it recently? That probably broke it

**Comment by RandomMarine** [comment]
Tested. Both powers work correctly.

*however*

If you have both powers, you need to both stand still *and* remain in darkness to stay invisible, a straight downgrade from having either one.

**Comment by Durkel** [comment]
@RandomMarine What revision did you test it on, I've been having no luck with on live servers, and the people I've given it to having been changing either. Keep in mind, that just having the chameleon power manifested makes your character somewhat ethereal, Something I haven't seen occur since I started noticing the problem.

**Comment by Pennwick** [comment]
Its very strange. I tried getting Chameleon power last round and it kept flickering in and out. At the time a number of people had a superpower virus. But as I eradicated the virus I stopped reappearing. It may be that whenever anyone with the power moves or loses the power everyone gets set to visible again. Its some kind of bizarre Chameleon highlander.

**Comment by Durkel** [comment]
Noticed it working today, I guess it's fixed or it's whacky for another reason or other. closing this.
