### ISSUE TITLE
Problem with arrest and changelings

### ISSUE THREAD

**Issue by bornasm** [tgstation/-tg-station#8372]
So I was playing as a changeling, I got set to arrest. Then I absorbed someone and I transformed into them. Then I got arrested because I was set to arrest but I was set to arrest on the old name not the new that I transformed into.

**Comment by Chocobro** [comment]
could be something to do with contents?? i don't think beepsky actually detects lings

**Comment by bornasm** [comment]
Dont know I was arrested by a security officer, he said that "my name" at the time was not set to arrest but rather my old name I used before transforming. Apparently the W tag was left on their huds even after I transformed

**Comment by SconesC** [comment]
This also seems to apply if you get genetics'd into someone else

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

This was fixed

**Comment by Dorsisdwarf** [comment]
crushtime
