### ISSUE TITLE
ED-209 will	chase humans with a "discharged" security status

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8373]
as if they are wanted.

**Comment by Chocobro** [comment]
note: it also sees the floral somatoray as a lethal weapon.
note 2: the human was previously wanted.

**Comment by Boredone** [comment]
As a note, this was just because Discharged+Has a Gun(Floral Somatoray counts)=Arrest!
If the ED/Securitron is set to check weapon authorization anyway, which I believe EDs are by default.

**Comment by RemieRichards** [comment]
Discharged status is worth points to the Threat Assessment system that EDs and Beeksy's use.
the floral somatoray, for logical consistency and good code, is a gun, this one isn't easily solvable unless a variable was added to guns such as ```ignoreThreatAssess``` which beepsky/EDs would register as an instruction to skip that as a gun.

**Comment by Dorsisdwarf** [comment]
I'm fairly sure there IS such a variable, actually, since magical staffs and syringe guns don't get you beepskied.

**Comment by Boredone** [comment]
Yeah, there's a list of guns that arn't actually considered dangerous, like laser tag guns.

**Comment by RemieRichards** [comment]
A list is a pretty shit way of doing it.

**Comment by Chocobro** [comment]
@RemieRichards do you know of anyone that's fixing/changing this? if so, re-open.
