### ISSUE TITLE
Preference savefiles are broken.

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#8375]
At least on Basil. Probably : https://github.com/tgstation/-tg-station/pull/8328

**Comment by Incoming5643** [comment]
Probably same cause as #8352

Someone rush this one oh god

**Comment by AnturK** [comment]
Bumping up the savefile version by two numbers would probably fix this at the cost of everyone's preferences. Which is kinda bad.

**Comment by Miauw62** [comment]
fuck i don't know how savefiles work
