### ISSUE TITLE
Kebab not properly removed

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8376]
When you create a custom kebab (maybe normal kebabs too?) the new kebab ends up on the floor, but there's still something in the hand that was holding the rod. It looks like the rod, but you can't use it for anything and all you can really do is drop it to clear it from existence.

<img src="http://i.imgur.com/hGdPsXl.gif">

**Comment by phil235** [comment]
can't reproduce

**Comment by Incoming5643** [comment]
Both items have to be in your hands both the rod and the thing to stick on the rod. This  also doesn't occur when you ADD something to a custom kebab, just when you first start one.

If you can kebab through tablecrafting that's not what I'm talking about. I'm talking about attacking a rod with a food item.

**Comment by Miauw62** [comment]
phil needs to step up his kebab removal game

**Comment by phil235** [comment]
Can't reproduce on either sybil or basil.

**Comment by Incoming5643** [comment]
That is very strange, let me try it myself

**Comment by Incoming5643** [comment]
![d10_icon](https://cloud.githubusercontent.com/assets/4176358/6675378/58bbe968-cbf6-11e4-8b8a-c3963c7eef75.png)

In this picture (which I just did oh my god IC in OOC) I have placed a bag of chips on a single rod, then moved one square left.

You can see the kabob and the trash from the chip bag on the ground where they were generated. In my hand you can see what appears to be a metal rod, but in my actual hands nothing is there. The hand carrying the "phantom rod" can't pick up anything else until the rod is dropped or placed in a container, no matter how it is removed the rod doesn't actually end up there, it just vanishes.
