### ISSUE TITLE
Why is this not fixed yet, make it stop

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#8384]
The guns on the Mauler (the 140tc nuke op mech) don't work - other then the missile launcher.
This is the scattershot and the AC2. Effects the robotics built ones also.
Both just spawn bullets instead of actually firing them.

I'm certain this bug was reported like, 6 months ago, dunno why it's still around.

Also tangentially related, but the mech missile launcher (which is really shit, does like, no damage) can be rather powerful, due to REASONS.

I just watched a nuke op in a mauler shoot a windoor at point blank, with a nuke op on either side of him.
The explosion destroyed the windoor, which some how propelled rods into the 2 ops like 50 times, and insta killed both of them.

**Comment by Jordie0608** [comment]
Likely related to #6179

**Comment by Kromgar** [comment]
Also maulers can barely break down uninforced walls and can't even break tables with their fists

**Comment by Iamgoofball** [comment]
please make better issue names

**Comment by Kromgar** [comment]
Its not my fault Jordie deleted my descriptive title.
