### ISSUE TITLE
Mauler can't tear down walls or tables and can't shoot bullets

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#8385]
WHAT THE UTTER LOVING FUCK GUYS.

It can't destroy tables in one punch. I had to hit a wall 15 times to break it down A NORMAL WALL NOT REINFORCED.

THEN NONE OF MY GUNS SHOT BULLETS.

Lost us the round

**Comment by Jordie0608** [comment]
Dupliate of #8384
