### ISSUE TITLE
Ninjas can't upgrade suit batteries/drain them inhand

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#8388]
@RemieRichards 
Not sure if this was intended by the rework, if so please close this.

**Comment by RemieRichards** [comment]
Gonna need much more information than that.

All I did related to cell draining was move the cell draining code from cells to gloves, like the rest of the draining code.

Upgrading your suit with a battery is as simple as clicking the suit with the battery, as usual.
This means when you pick up the battery you need to NOT be in the special interaction mode (otherwise you'll drain it, which was the old functionality too iirc)

**Comment by AnturK** [comment]
With interaction enabled:
 - click battery on the floor : it drains it. Old functionality : pickup
 - click battery inhand - nothing. Old functionality : drain
 - battery inhand click on suit - nothing Old functionality : upgrades suit

**Comment by RemieRichards** [comment]
And can you still upgrade the suit. with interaction toggled?

Either way what I can do is prevent draining cell's unless their loc is the user, meaning your holding it.
This means:
* The first click (to pickup) will pickup)
* The second click (inhand) will drain
* The "Other" second click (clicking on suit with battery) would upgrade.

That'd preserve all old functionality AND old usability, would it not?

**Comment by AnturK** [comment]
Yeah,that would be working as before. And i couldn't find any way to actually upgrade the suit.

**Comment by AnturK** [comment]
To be honest removing inhand battery drain is not such a bad idea, removes the backpack hunting and infinite power. The real issue is not being able to upgrade really.

**Comment by RemieRichards** [comment]
@AnturK I'd assume upgrading the suit with the "new" accidental usability would be:
* Toggle Interaction off (to prevent draining)
* Toggle interaction ON (Is it needed on for upgrading? I can't recall)
* Click suit with battery

Either way, we can move ahead to what I've just suggested.

PR2 will be wednesday/thursday, and focus around powers and abilities, but I'll make note to fix this at the same time.

**Comment by palpatine213** [comment]
@RemieRichards Attempting to upgrade the suit seems to be runtiming.
runtime error: Cannot read null.maxcharge

**Comment by RemieRichards** [comment]
@palpatine213

I'm aware, found it the other day, already fixed in my unPR'd [Part 2] which is coming this weekend/next week.

**Comment by palpatine213** [comment]
Alright. good to hear.
