### ISSUE TITLE
Hilariously robust statue is GG with Docility Potion

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8389]
Yeah, that horribly broken mob that you can get from gold cores?

It can be a player controlled gold core docility potion mob.

Revert it's stats to those of a normal mob or remove it from the gold core charts, it's way too fucking strong to have at the command of a xenobiologist. Fast, near-invincible, insanely robust damage.

**Comment by Durkel** [comment]
The description given doesn't give justice to how overpowered they currently are. With first hand experience allow me to list off the problems.

1)They can move regardless  of anyone looking at them, the main drawback of statues
2)They're faster then  normal run speed
3)They do a lot of damage per hit, 60-70 I'd say.
4)They have x ray vision for some reason.
5)They have fifty thousand hp.

As long as AT LEAST problem one is fixed it won't be a major issue anymore.

**Comment by Lumipharon** [comment]
Why can these ones move while looked at? Are you sure? Silicons/people viewing them through cameras/xray etc don't count.

Also related, statues can bleed. So even though they have xbox huge hp, when I was a statue I (apparantly) de-statued because of bleeding out.

**Comment by Incoming5643** [comment]
The "don't move when people are looking at you" mechanic is apparently broken.

Which yes, makes them OP as shit currently

**Comment by WJohn** [comment]
Huh, why can statues bleed? Can all simple animals bleed too? That should probably be removed if they can't even process chems.

**Comment by Incoming5643** [comment]
Lumi staff of animation statues eventually revert to human form, it's probable that you were bleeding before you got stoned and your hidden but still in existence human body continued to bleed while you statued it up. When you unstatued you had to deal with all the blood loss you had accrued in the meantime.

This is a bug because I have a little "stasis field" mechanic for statue mobs to prevent latent damage to the human mob while the player is in the statue mob, but it wasn't updated to account for bleeding.

Will fix that.

**Comment by Incoming5643** [comment]
Actually now that I really think about it I think I know why the statues can move when everyone can see them.

The mechanic isn't broken at all. Statues have a faction check so they can move when they are only seen by their wizard/other statues/other animated objects. Blood reaction gold cores stop hostile mobs from attacking the crew by adding the station faction to them. So a blood reaction gold core animated statue can move in front of every human on the crew manifest.

**Comment by SconesC** [comment]
Back on track, the point is that the statue mob is not only comically broken in the first place, but it can be controlled by a player now. Instant unstoppable destruction - Just tell it to go punch everyone to death.

**Comment by Incoming5643** [comment]
The hard defense against a statue is just to wall it in somewhere.

Which is why it's a big deal that there's a way around that.
