### ISSUE TITLE
"Backup Shuttle" is called even if normal shuttle is on the way

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#8393]
If all communications consoles are broken and the AI is dead, a shuttlecall is automatic, but takes 22 minutes rather than the normal 10. 

This occurs even if the normal shuttle has already been called- the time until shuttle arrival will be forced to 22 minutes, even if the shuttle is about to arrive.

**Comment by Jalleo** [comment]
This was reported before i think need conformation of previous issue report first though.
