### ISSUE TITLE
Chameleon snapping back to visible

### ISSUE THREAD

**Issue by Pennwick** [tgstation/-tg-station#8404]
Chameleon is still broke and I'm not really sure quite how. I late joined as CMO in a fairly slow round. A bloodborne superpower virus got released to about 4 or 5 crew including myself. I cured myself and gave a monkeyman the virus instead and started using him for testing. I picked out the Chameleon power for myself and 10 SEs later I had it. Except I was only partially invisible. 

I went and sat at the medbay front desk for a while and combed through the code, every now and then I'd start fading. Sometimes almost fully invisible before blinking back to mostly visible again. Just on a random hunch I cured my monkeyman subject and the chemist. Giving him TK instead. I seemed to have my invisibility for longer bursts. I eventually tracked down the remaining crew with the power and forcefed them sausages to cure them. Then I was able to stay invisible perfectly.

If I had to guess I'd say everyone for some reason shares the same level of transparency. So if anyone with the power was moving I'd be visible. Or It could be that every time the power cycled off on the people with DNA aide it reset my own alpha levels. Judging by my flicker pattern I'd say its more likely the former though. 

Possibly related to #8370

**Comment by Pennwick** [comment]
Did a little more testing. Seems like as long as there are two people with the mutation it wont work. Had myself and a monkeyman as mutants. Both standing still and neither of us would fade. Gave the monkeyman a clean SE and he I started to fade. Could it be that var/last_location is shared between everyone and not just tied to each mob? That would be my guess.

**Comment by Iamgoofball** [comment]
someone tweaked with the delay stuff for it

might be fucked for some reason

**Comment by phil235** [comment]
@Pennwick is right,  var/last_location is stored in datum/mutation/human/chameleon instead of in the mbon so right now every mob with the mutation share that var.
A fix would be to add a last_location var to all mob/living/carbon/human and update and use it in chameleon/on_life().
