### ISSUE TITLE
Blob zombie event spawns naked husks on bodies

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#8406]
Blob zombie event now spawns a blob spore over corpses. The spore disappears as normal and a naked husked corpse rises instead. The original corpse is left as it was, and if killed, the zombie acts as a normal blob spore, releasing it's gas.

I presume this occurs in normal blob interactions too but I didn't have the chance to test that.

**Comment by Incoming5643** [comment]
This is fixed in #8396 , what you're seeing is how I found that runtime in the first place.

It doesn't effect normal spores because the runtime is from the spore trying to check the chemical of the parent blob (which doesn't exist).
