### ISSUE TITLE
sec hud can detect fake ids with nonstandered job titles

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8407]
it appears to be tied to certain ids.

**Comment by Incoming5643** [comment]
If a HoP gives an ID with a customized job title (unless it perfectly matches one of the initial job titles) it will appear as a grey square on Sec hugs. 

Is this what you were seeing? If so that's not a bug.

**Comment by RemieRichards** [comment]
>Sec hugs

@Incoming5643 Awwww

**Comment by Supermichael777** [comment]
Found it an improperly fogged agent id will not show up with a grey tile on the hud instead no tile will be shown. secmeta confirmed

**Comment by GunHog** [comment]
If you do not spell it EXACTLY as the job title is named, then the Sechud will not find the matching icon. It is technically a 'sprite not found' error. It is *case sensitive* as well.

**Comment by Lumipharon** [comment]
Not a bug, fault of whoever made thier job 'johnson inspector' or head of security instead of Head of Security.

**Comment by RandomMarine** [comment]
I'd call it a feature. Sechuds should check for discrepancies harder than an Arstotzkian border inspector.

**Comment by Marflowerose** [comment]
Wouldn't it be better if the icon was tied to the presets in HoP console rather than title? If you have assistant access but job title of "Station Loiterer", it would shows the assistant icon. If you had broken into Hop office and given yourself captain access but named it Assistant, it would show the captain icon. Surely that would be far more useful arstotzkian border johnson inspection than just comparing job titles. Or why not both.

**Comment by Lumipharon** [comment]
Because then anyone with access they shouldn't have (ie: everyone with an agent card) will no longer fit the 'presets' and immediately be suspicious. And giving yourself sneaky all access will be putting a big 'arrest me' sign over your head.

**Comment by Dorsisdwarf** [comment]
You're missing the point - the point isn't that the HUD doesn't detect badly-spelled ID cards.
It's that while normal ID cards with incorrect names give you a grey square, 
the Agent ID apparently doesn't give a square at all, thus allowing sec to instantly spot stealthops/ninjas/stealthy traitors.

**Comment by astralenigma** [comment]
Well I did a mistake that commit doesn't fix this but this is already fixed.

**Comment by MrStonedOne** [comment]
@Jordie0608 @tkdrg
