### ISSUE TITLE
alternate_worn_icon is buggy

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8413]
I tried changing a skirt's worn sprite to a custom made one I made, and it works fine for me, but not for other people who wear it. Meanwhile another admin edited a coat into something he made and it worked fine for both of us. I used all four .dmis to change the on floor, worn, left and right inhand sprites, while he only changed his worn sprite.

Also the clothing I was editing was a jumpsuit, while his was an exosuit.

**Comment by Incoming5643** [comment]
If you add a sprite while in game, you have to be sure it's on sprite model is copied to the rsc file (because every player downloads that in real time)  so everyone can see it. Don't ask me how to do that from a live server, cause I'm not completely sure.

**Comment by RemieRichards** [comment]
I Fixed it, it was @Incoming5643 's fault :P (Sort of mine too for testing the initial PR on a dude character, thanks RNGesus)
https://github.com/tgstation/-tg-station/pull/9027
