### ISSUE TITLE
Meth, not even once

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#8422]
When overdosing on meth, you still seem to teleport out of various things when you start to flip out.  For example, when riding the transit tube to the AI satellite, I flipped out and suddenly teleported out of the pod and died.  Later when I was brought to medbay and revived using the shockers, I was put into a cyro cell. I proceeded to flip out and suddenly I was outside the cyro cell while it still had the sprite that I was in it, I coudn't actually tell if it still registered me as inside because I had to much brain damage to check.  Needless to say, Meth still has some issues.  @Iamgoofball

**Comment by Boredone** [comment]
Already being addressed by #8233 
Dunno why it hasn't been merged, or if not ready, not finished.

**Comment by Chocobro** [comment]
remove teleportation

**Comment by francinum** [comment]
Dupe of #8158
