### ISSUE TITLE
The new centcom has almost no room to fight in

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8425]
The first checkpoint door has centcom level access, so unless you have a borg with you to lead the charge, your stuck smacking each other in that tiny little area.

Please I gotta get my tussle on

**Comment by Chocobro** [comment]
it's the end of the round shouldn't you be planning your gimmick for the next one

**Comment by Miauw62** [comment]
roundend griff is a proud tgstation tradition.

**Comment by Jalleo** [comment]
Maybe have access turn to standard for round ends?

**Comment by Fayrik** [comment]
This is something I considered while designing that section, but I thought the room remaining would be sufficient, especially with the two adjacent rooms to the north and south.
If I get some feedback on what that section needs to enable griff, I might stand a chance at updating it to be more griff-friendly.

So, what's specifically the issue with having a smaller area to fight in? Surely a smaller area brings you closer to the people you're trying to smash in.

**Comment by Lumipharon** [comment]
What was that alternate station we had for a while? And instead of centcomm, the shuttle/pods just docked at a room full of weapons and shit, and everyone just went to town?

**Comment by Jalleo** [comment]
That was efficency

**Comment by Fayrik** [comment]
My next PR will be focusing on centcom again, so if someone could assign this to me that'd be great.

**Comment by Miauw62** [comment]
Sorry, only maintainers can be assigned. It's a github limitation.

**Comment by RemieRichards** [comment]
And also that'd be like sharing our magical essence, and we don't do that.

**Comment by Fayrik** [comment]
That's perfectly fine. I don't want any dirty maintainer magic.
Everyone, just be prepared for this issue to get dunked.
