### ISSUE TITLE
Suggestion: Re-add Manul IED Construction

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#8429]
The manual method of constructing this was removed a while back when tablecrafting was updated.

Suggestion: re-add it

Tablecrafting is fine, but most things can be manually created (cattleprods, robots, etc)--I don't see why this this should be any different, especially now that it's a pretty weak firebomb as opposed to full out explosive.

**Comment by callanrocks** [comment]
Make everything manually crafted, Tablecrafting a shit.

**Comment by Miauw62** [comment]
It was turned into tablecrafting to standardize the crafting systems away from the rather awful attackby() checks everywhere we used to have.

@razharas

**Comment by Fox-McCloud** [comment]
@Miauw62 

I can kinda understand that, to a degree, but generally speaking every item in the tablecrafting recipe list is also craftable by manual means (with the except of tech bullets) and curiously the IED.

all the attackbys are kinda messy,but when 99% of SS13 history has been utilizing manual crafting, it's kinda hard to get players to do anything other than that methodology.

**Comment by RemieRichards** [comment]
This would be opposite to the goal of tablecrafting.
it's to replace manual crafting.
so reverting the one recipe it's replaced is a tad silly.

I seem to recall it being a goal (perhaps unwritten, as a lot of things) to oust manual crafting completely so, yeah.

**Comment by PKPenguin321** [comment]
ousting manual crafting is a crazy batshit schizophrenic dream/nightmare by a few coders I wont name, just ignore them and readd IED crafting, the things are useless anyways

**Comment by Jalleo** [comment]
I dont like table crating either but would you want to look through 5 more files each time you wwnt to modify one recipie?

**Comment by Fox-McCloud** [comment]
@Jalleo 

Pretty sure Ghettobombs were 100% contained in their own file.

**Comment by Jalleo** [comment]
Those probably are but the proccess to make lets say stun prods are not.

**Comment by Fox-McCloud** [comment]
@Jalleo 

Yeah, and those are still in the code, which is why I question the removal of IEDs =p

**Comment by Jalleo** [comment]
Because that is the way it occured. I would rather rework the whole crafting system to be a lot more interactive and less table set but thats another discussion. Really the only fix is to standardise the lot but people dont like to be controversial and do it. I personally dont mind what way this goes currently but its bad that we have very unintuitive systems as is.
