### ISSUE TITLE
Facehuggers leap onto your face multiple times at once

### ISSUE THREAD

**Issue by callanrocks** [tgstation/-tg-station#8430]
They jump on your face over and over again, doing crazy amounts of brute

**Comment by Chocobro** [comment]
was there only one facehugger, or multiple?

**Comment by callanrocks** [comment]
Multiple

**Comment by Miauw62** [comment]
This is a dupe, in that case.

**Comment by Miauw62** [comment]
I dont know of which issue, but its a pretty old issue.
