### ISSUE TITLE
Booze dispenser + Bucket

### ISSUE THREAD

**Issue by Brolaire** [tgstation/-tg-station#8442]
Apparently you can load a bucket into the Soda dispenser as a beaker, but you can't load it into the booze dispenser. And you can't drink out of buckets. Not sure if this was intentional, but it might be worth looking into.

**Comment by Incoming5643** [comment]
it always bugged me that you couldn't directly drink out of reagent containers unless they were drinking glasses. Drinking from laboratory glassware is a HUGE nono in an actual lab environment, but this is space station 13 we're talking about here.

**Comment by TheVekter** [comment]
It's because drinking glasses are a child of beakers, not the other way around. You can't drink out of buckets because the code isn't there for it. Definitely intentional.

If there's enough people that want booze buckets to be a thing it wouldn't be too hard to code them in.

**Comment by kingofkosmos** [comment]
How about help-intent drinks/feeds someone the reagent, other intents splash? Could be applied to drinking glasses as well for dramatic splashing a drink on someone's face.

**Comment by phil235** [comment]
already fixed apparently.
