### ISSUE TITLE
Changeling sting bugged?

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8443]
I was playing a changeling, got caught and was dragged around for quite a while, I was constantly stinging the dragger with cryosting and hallucination sting but it seemed to have no effect. I'd imagine over 4 cryostings and 3 hallucination stings would do something over several minutes. Target was not a changeling.

**Comment by francinum** [comment]
A: Were you cuffed
B: they might have had coffee in their system, which heats you up, negating cryostings.

**Comment by Marflowerose** [comment]
Yeah, I was cuffed and I was losing the points per sting.

**Comment by Dorsisdwarf** [comment]
Cryostings really weak after some nerfing IIRC

**Comment by Razharas** [comment]
Cuffing doesnt disable stinging

**Comment by phil235** [comment]
Stings work fine when cuffed and pulled. The only issue here is cryosting basically doing nothingn probably because frost oil metabolization rate was nerfed by goofball. I'll make a specific PR about cryosting.
