### ISSUE TITLE
Spawned as bald white male, got my random appearance after putting on a suit.

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8446]
This is not about the few second delay after arriving, the body change happened way later.

Started the round as bald guy, even got a screenshot I made for another issue.
![unbenannt](https://cloud.githubusercontent.com/assets/11201491/6758398/1cc4d092-cf38-11e4-886f-6df597e9a2d8.PNG)

Put on the fire suit and helmet, then I suddenly grew hair out of nowhere.
![image](https://cloud.githubusercontent.com/assets/11201491/6758425/4ae081ce-cf38-11e4-948d-f1f2223b0950.png)

**Comment by Miauw62** [comment]
This is a dupe and should already be fixed (pending merge/server update).

The reason that you got your appearance later is because your icon was not updated. This only happened when you took off the helmet.
