### ISSUE TITLE
Lizard tail goes through capes.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8450]
There should probably be some tag that makes it so certain items go on top of the tail, without necessarily removing it.

**Comment by Incoming5643** [comment]
Might not have to, depends on where the back slot layer is in comparison to where the tail is

**Comment by bgobandit** [comment]
feature, lizard tails poke tailholes in fabric

**Comment by Dorsisdwarf** [comment]
No more features and checks for lizzies
