### ISSUE TITLE
Botany Bugs II

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8453]
- Rice stalks are missing one of their growth sprites in the hydro tray (second-to-last before ready to harvest, possibly the one before) and as a result the hydro tray appears empty.

- Rice and oats still appear as "rice Stalks" and "oat Stalks"

**Comment by Jordie0608** [comment]
Second point was already fixed in #8223. Server may not have been updated yet.

**Comment by Marflowerose** [comment]
Applying nutrient bottle on Hydro tray that has nothing planted results in no change of nutrient level and uses up nutrient from bottle.

**Comment by Jalleo** [comment]
@Marflowerrose was it in the irrigation if sp it could of been spread to the planted trays if not definite bug.

**Comment by Marflowerose** [comment]
Unless they default to irrigated, not that I know.

**Comment by Marflowerose** [comment]
Also occurs on public garden dirt piles.

**Comment by Jalleo** [comment]
Then its possibly a bug but this should of been reported seperately tbh to help garner attention.
