### ISSUE TITLE
Fire alarms still flashing Code Delta after malf AI destroyed

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8457]
Repllicate: Be malf, go delta, get ded, fire alarms will still be flashing yellow despite code delta 

Probably has something to do with Mulligan, this happened for about 30 minutes until we shuttled home

**Comment by Incoming5643** [comment]
Yeah I didn't really consider that for mulligan, I'll look into fixing it.

**Comment by francinum** [comment]
Erm. You can fix this by dropping the alert level as well, IIRC.
