### ISSUE TITLE
Cannot open any menus in SpiderOS

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#8459]
As a ninja, if you open SpiderOS and try to open any of the menus contained in it, nothing happens. The window refreshes and stays the same. The refresh and close buttons seem to be working however.

**Comment by RemieRichards** [comment]
SpiderOS is a shit, and I'll admit I did actually break one of the variables in it while removing the AI
(Spoilers its the one that says whether you can load a page or not)

But SpiderOS is going anyway so, I'll probably patch that variable in my [Part 2] and then completely delete SpiderOS in [Part 3] or whatever.

**Comment by palpatine213** [comment]
Are you going to replace the ninja's built in med suite? Since that and research level management was its main use.

**Comment by RemieRichards** [comment]
Meds will most likely return as simple abilities instead of a big ass menu in SpiderOS
Research levels, Idk if I even want to keep that as an objective, so we'll see.
