### ISSUE TITLE
Certan preplaced airpumps become unusable when wrenched up and placed back down

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8468]
Happens in the local atmos areas in maintenance for sec, science, virology, and that air canister refill room in arrivals maintenance.

**Comment by Razharas** [comment]
@Aranclanos

**Comment by ike709** [comment]
well is it a cannot reproduce or a higgs-bugson?

**Comment by Menshin** [comment]
For what kind of atmos machinery is it failing ? Gas Pumps ? Volume Pumps ? Manual Valves ?...

**Comment by Supermichael777** [comment]
the round start gas pumps in certain places in maintenance when unwrenched picked up and wrenched back down don't connect and visibly glitch

**Comment by Menshin** [comment]
The icon glitch and the air not flowing are two separated issues.

The former is easy to fix, the latter is the last issue that have to be tackled with pipenets (qdel failing probably).
Like in the other PR, any information or setup where you can reliably reproduce the air not flowing is warmly welcome.

**Comment by milocv** [comment]
I managed to reproduce it on the first try by following the instructions he provided.

In the atmos maintenance near security:

Turn off the pump
Unwrench it
Pick it up
Put it back down
Wrench it

Although, the airflow works fine for me, I set the pressure to 4500 kP and the pressure in the pipes increased like normal.
![graphbug](https://cloud.githubusercontent.com/assets/9081305/6849706/1fa01e06-d3d5-11e4-9fba-e464953ced01.png)

**Comment by Menshin** [comment]
The icon glitch happens for binary devices placed on platings, but the devices are generally working fine.

The real problem is the Higgs-Bugson bug that makes devices/pipes pipenet-less. If anyone ever find a way to properly reproduce that, it would be a great step at fixing it.

**Comment by duncathan** [comment]
The icon glitch is long fixed; there's nowhere near enough information to reproduce the main issue.
