### ISSUE TITLE
Default alien color should be green, not grey.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8470]
Now that both lizards and plantmen are greyscale, and that not everyone necessarily ever plays at them willingly (choosing to be a lizard or being revived as a plant man), your alien color should default to green so if you get forced into those roles (botany reviving you or admins lizarding you) you won't be all grey for either.

**Comment by Incoming5643** [comment]
the funny thing is every race actually has a hardset color for if the player hasn't set one, it's just that the savefile DOES set one at FFFFFF

**Comment by hanshansenhansson** [comment]
Why not allow to random the colour as well? Maybe have it random until it is explicitly set.

**Comment by WJohn** [comment]
Because green makes sense for both lizards and plantmen, you can choose some crazy color yourself later.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.

**Comment by Incoming5643** [comment]
I had fixed this anyway
