### ISSUE TITLE
Fire blobs lighting borgs on fire

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8471]
what the fuck why

reproduce: fire blob hit borg
borg ignizzle

**Comment by SconesC** [comment]
@Iamgoofball

**Comment by Lumipharon** [comment]
Seems like a feature to me, what's the issue?
You can light borgs on fire via other means, so it makes sense that this would work also.

**Comment by Marflowerose** [comment]
AFAIK borgs don't take any actual damage from being in flames since they're immune to heat (except laser etc)

**Comment by Xhuis** [comment]
Seems intended to me since it's burning oil splashed onto the borg

**Comment by Miauw62** [comment]
Borgs can't be set on fire in any other way, this is a bug.
Op 22-mrt.-2015 16:02 schreef "Xhuis" <notifications@github.com>:

**Comment by Lumipharon** [comment]
Hm, well you used to be able to set them on fire just like a human. I remember a malf round where there was like a dozen dead borgs lying around, most of them on fire.

**Comment by Iamgoofball** [comment]
was pretty sure borgs could be lit, will change to an iscarbon() check

**Comment by SconesC** [comment]
@Lumipharon Nah this is literally the only instance in which I've witnessed a silicon ignite

**Comment by Lumipharon** [comment]
Well last time I saw it/tried it was a fuckin long time ago so yeah, probs got changed since then.
Silicons on fire is pretty funny though.

**Comment by RemieRichards** [comment]
Borgs have a handle_fire(), called in their life like every other mob that can be set on fire.
There's either no bug here, or the bug is that you can't set them on fire in other ways.

**Comment by Iamgoofball** [comment]
in that case this is not my shit to fix and it's intentional i guess
