### ISSUE TITLE
BLOB BUGS II HOLY SHIT BUGS AND BLOBS

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8472]
BUG ONE: I forgot the name of this kind of bleb (Skin Melter I think) and I can't find it in the blob attack spam, but yeah, p. self-explanatory. The fire wore off in a second or so, but I don't know whether that's part of the bug or space extinguishing the fire.

BUG TWO: Blebs that are dead can still use the Broadcast power

**Comment by SconesC** [comment]
Space extinguishing probably

**Comment by bgobandit** [comment]
ok cool, the point is still that borgs shouldn't be able to get set on fire

**Comment by Miauw62** [comment]
this is a dupe.
