### ISSUE TITLE
C4 doesn't break APCs anymore

### ISSUE THREAD

**Issue by whodaloo** [tgstation/-tg-station#8473]
So I was playing as a fluke recently.  I snuck onboard, mosied on over to the outside of tcomms in maint, c4'd the wall tile that the APC was on, and... the APC was undamaged after the explosion.  I tried again by planting c4 on the wall tile next to it, but that also didn't break the APC. The first bomb I placed outside the wall (from maint), although I'm not entirely sure that makes a difference. APCs definitely used to break from c4 explosions, but if this isn't a bug or something feel free to call me stupid.

**Comment by SconesC** [comment]
Did you try placing C4 on the APC itself?

**Comment by whodaloo** [comment]
I did, iirc I couldn't apply it.

**Comment by Incoming5643** [comment]
You have to remember that the APC actually exists on the tile you're standing on, NOT the wall tile. so you can't reach the apc from the oppose side of the wall, because the APC is actually two tiles away at that point

**Comment by phil235** [comment]
not a bug.
