### ISSUE TITLE
When you're pushed, it makes you say whatever is in your chatbar..

### ISSUE THREAD

**Issue by stapler2025** [tgstation/-tg-station#8477]
How 2 Reproduce:  Type Say " in your chatbar, push yourself.

What happens:  Jebediah Kerman has pushed Jebediah Kerman!
                          Jebediah Kerman says, "Say ""

What should happen?  I should be pushed.

**Comment by stapler2025** [comment]
Appears to only happen when pushing yourself, not others.

**Comment by stapler2025** [comment]
I lied, it happens whenever someone has something typed in.

plx fix

**Comment by Jordie0608** [comment]
This is intended behavior.

**Comment by stapler2025** [comment]
No it is not.

**Comment by stapler2025** [comment]
Please, get on the server, type out "Say "Man eat a dong"" and push yourself.

**Comment by Jordie0608** [comment]
Ok I see what you mean, your description wasn't all that clear.
@Miauw62 
Forcesay is isn't stripping the message precursor (Say) from it's messages.

**Comment by Miauw62** [comment]
fuck, i thought forcesay was deprecated
