### ISSUE TITLE
When you exclaim, it says that you instead yell

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#8478]
When both yelling and exclaiming, the chat log says your character yells. For borgs, they alarm rather than declare.

Sorry for the vague report, but I'm ironically having trouble putting this into words.

**Comment by Miauw62** [comment]
i cant understand, sorry

**Comment by bgobandit** [comment]
How it is supposed to be:

Clown exclaims, "Honk!"
**Clown yells, "Honk!!"**

How it actually is:
Clown yells, "Honk!"
**Clown yells, Honk!!"**

**Comment by Miauw62** [comment]
Ah. I will prepare a fix soon, hopefully.
Op 22-mrt.-2015 15:00 schreef "bgobandit" <notifications@github.com>:
