### ISSUE TITLE
Husks not cremating

### ISSUE THREAD

**Issue by SentinelOfFate** [tgstation/-tg-station#8479]
A Changeling had husked a Medical Officer and attempted to cremate her. He hit the button, it made the working sound and then the ding. But when sec showed up and opened up the furnace, it was still there. I believe husks might not be able to cremate at the moment
EDIT: could not be reproduced after several test runs

**Comment by CreationPro** [comment]
Let me elaborate:
Time and server this occured on : Badger, 2015-03-22 , about 2:00.
How to reproduce: Husk some poor sod as a ling, try and cremate him. Shouldn't work.
Why this is bad: Lings gotta dispose of the bodies somehow, this has the potential to screw someone over badly.

**Comment by Marflowerose** [comment]
Is it possible AI/Borg turned off the equipment from APC that caused the cremation to interrupt?

**Comment by SentinelOfFate** [comment]
There were no silicons

**Comment by RandomMarine** [comment]
Tested with a spawned human. Couldn't reproduce.

**Comment by AndroidSFV** [comment]
Sounds like this is an edge case run time.

**Comment by Jalleo** [comment]
Was the first body clothed at all?

**Comment by CreationPro** [comment]
Yeah, had a medical coat for sure.

**Comment by Jalleo** [comment]
Medical coat would not of effected it. @Iamgoofball there wont be any chems preventing the incinirator from incinirating is there?

**Comment by Iamgoofball** [comment]
I don't think so, no.

**Comment by Marflowerose** [comment]
How would meth OD teleporting behave inside incinerator?

**Comment by Iamgoofball** [comment]
you shouldn't be able to teleport out of it with that

plus it's not even supposed to be teleporting

**Comment by Dorsisdwarf** [comment]
No reoccurences, no issue.
