### ISSUE TITLE
Cavity implant surgery strikes again.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8486]
Cory Stephenson begins to insert the shield-like mass into Jacaline Field's chest.
Cory Stephenson stuffs the shield-like mass into Jacaline Field's chest!

Melissa Burris checks for items in Jacaline Field's chest.
Melissa Burris pulls the shield-like mass out of Jacaline Field's chest!

Edit. 
Medical Cyborg-111 begins to insert the retractor into Jacaline Field's chest.
Medical Cyborg-111 stuffs the retractor into Jacaline Field's chest!

Cory Stephenson checks for items in Jacaline Field's chest.
Cory Stephenson pulls the retractor out of Jacaline Field's chest!

#8235 #8234 Its baaaaaaack.

**Comment by Incoming5643** [comment]
This is bizarre, I know the changeling shield is NODROP. I'll have to look into it.

**Comment by phil235** [comment]
still there.
