### ISSUE TITLE
You can augment any limb with any robot part

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8490]
all you need are heads becase they ar the cheapest

**Comment by WJohn** [comment]
Has this really never been fixed? I swear it's at least been reported before.

**Comment by Chocobro** [comment]
if we can fix this so the used robot part becomes that limb, that'd be great.
heads for legs.

**Comment by Incoming5643** [comment]
I think people have held off on this because they presumed there was a fix in dismemberment.

Not sure if there is, but that's my guess.

**Comment by AnonymousNow** [comment]
Figured this a feature, since cyborg limbs are programmable for various configurations. Though having limbs be for limbs would make more sense.

**Comment by RemieRichards** [comment]
It's invalidated by dismemberment, it's always been invalidated by dismemberment.
But always because of ~reasons~ it never gets in.

It was never worth my time to fix it separately, if you want to, go ahead.

**Comment by Jalleo** [comment]
This is a dupe

**Comment by Dorsisdwarf** [comment]
This is a dupe and frankly it's pretty much just a handy optomisation at this point.

The only reason augmentations aren't a seperate item is pretty much so you have a use for extra cyborg heads/legs that you print out by mistake, since they're literally indestructible and useless.

**Comment by phil235** [comment]
If it's a dupe, I can't find the other issue...
