### ISSUE TITLE
Breaking a bottle on your own head has the wrong gender

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8491]
[tw] magic unmasky poopy butt spell
@Miauw62 
![bottlesmashing](https://cloud.githubusercontent.com/assets/5677255/6771021/3dd6dad0-d0ca-11e4-8c16-7ecb32e041e9.png)

**Comment by Miauw62** [comment]
why pingu me

**Comment by Chocobro** [comment]
because it's say code probably

**Comment by phil235** [comment]
Pretty sure that's my doing, back when I changed attack message to all use "x has attacked Y" instead of "Y has been attacked by X".

**Comment by Miauw62** [comment]
Not saycode
Op 22-mrt.-2015 21:15 schreef "Chocobro" <notifications@github.com>:

**Comment by Chocobro** [comment]
ok!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
