### ISSUE TITLE
Foam Rapidly Replicates Reagents

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8498]
According to a few players, when your caught in foam you get the full dose of whatever chems were in the beaker every so often, with the net result being that if even one person gets caught in the blast, they'll have much more of the chemical in their blood stream that was actually in the mixture.

**Comment by Lumipharon** [comment]
>makes smoke transfer reagent to avoid the issue of infinity reagent smoke
>buffs foam to do the exact same thing.

**Comment by Iamgoofball** [comment]
>implying this is intentional

I'll look into it
