### ISSUE TITLE
Sabotaging Showers Suddenly Suck

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8499]
If you adjust the temperature on a shower with a wretch it becomes cold or hot, in either case the temperature would be applied repeated to the mob while standing in the stream of water until eventually the player would start taking burn damage.

At some recent point this application of temperature changed from "continuously while in the stream" to "once when entering the stream". This has made it useless for murder/ghetto cryo/really anything.

**Comment by WJohn** [comment]
The solution is simple, stranglehold someone and repeatedly move them in and out of the shower.

**Comment by Jalleo** [comment]
Bad solution who changed it?

**Comment by RemieRichards** [comment]
It doesn't look like it was changed at all

```
/obj/machinery/shower/process()
	if(!on || !mobpresent) return
	for(var/mob/living/carbon/C in loc)
		check_heat(C)
```

Check_heat() either freezes the mob's temperature at a low value, or sets it to a high value and adds firedamage, fire DAMAGE, not stacks.

**Comment by phil235** [comment]
Yeah somehow process doesn't seem to be called, I think.
