### ISSUE TITLE
Chlorine Triflouride foam causes placeholder tiles to appear when melting walls

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#8500]
Walls melted by Chlorine Triflouride foam leave behind a HONK tile, which I am pretty sure is a placeholder tile.

**Comment by WJohn** [comment]
@iamgoofball pls man

**Comment by Iamgoofball** [comment]
what

wasn't doing that for me, how the fuck

**Comment by Tokiko1** [comment]
![test342](https://cloud.githubusercontent.com/assets/7812993/6775759/32374734-d136-11e4-86a5-1f21f4eddaaf.PNG)

The other walls also spawn this tile, but it seems to disappear if the foam spreads on top of it.

**Comment by Iamgoofball** [comment]
does this still happen? I haven't seen it for awhile

**Comment by phil235** [comment]
Still happens.
