### ISSUE TITLE
possible ghost chili bug

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#8501]
Touching a ghost chili without gloves will quickly heat up a person's body until they start taking burn damage but eating one doesn't do anything.

I am sure that one of these effects is unintended behaviour. Either eating a ghost chili should heat you up aswell or touching one shouldn't have such an extreme effect.

**Comment by PKPenguin321** [comment]
guessing this is something to do with goonchem and applying reagents by touch/ingestion? @Iamgoofball

**Comment by Iamgoofball** [comment]
not me @PKPenguin321

**Comment by phil235** [comment]
Eating a ghost chili does heat up your body temperature, it has capsaicin so if it doesn't heat enough the problem can be the amount of capsaicin in the chili or the reagent metabolization speed that may still be below its original level.

the burning upon touch is intended.
