### ISSUE TITLE
Energy katana desc is not capitalized.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8504]
"a katana infused with a strong energy"

The a should be capitalized, and there should probably be a period at the end there too.

@RemieRichards

**Comment by pudl** [comment]
99% of descriptions are lowercase for real

**Comment by dannno** [comment]
names should be lowercase but descriptions should have proper syntax
they're full sentences

**Comment by Miauw62** [comment]
Change desc to "a blade of energy waves folded a gorillion times" for
maximum dank meme points
Op 23-mrt.-2015 10:11 schreef "WJohn" <notifications@github.com>:

**Comment by Alek2ander** [comment]
>Priority: High
