### ISSUE TITLE
cant do shit to an emagged windoor

### ISSUE THREAD

**Issue by norill** [tgstation/-tg-station#8510]
cant fix or rcd decon
i think the cause is "operating = -1" instead of 0 in emag act
/ code / game / machinery / doors / windowdoor.dm:250

**Comment by phil235** [comment]
You can deconstruct an emagged windoor, I think.

**Comment by Dorsisdwarf** [comment]
You can decon a windoor any time it's open, use a crowbar.

It's a handy tactic for annoying the HOP.

**Comment by norill** [comment]
checked again in latest build, still relevant

**Comment by phil235** [comment]
Indeed, screwdriving the open emagged windoor does nothing so you can't deconstruct.
