### ISSUE TITLE
Permawanted after getting plastic surgery

### ISSUE THREAD

**Issue by SomeSketchyGuy** [tgstation/-tg-station#8517]
I was set to arrest and got plastic surgery done to me, after the plastic surgery was done not only was I set to arrest on sec HUD, I was completely unable to remove that status and even kept it when unknown. Please fix, Sec HUDs or security consoles couldn't set me off arrest.

**Comment by Incoming5643** [comment]
I think the sec bots have some off by default feature where they check faces against the sec records. You would have to create an entry for your new face before you could toggle the status off. But yeah the arrest status setting should probably reset if your face changes.

**Comment by SomeSketchyGuy** [comment]
Thanks, I'll keep that in mind for the future, but in that round I didn't
see a single sec borg.

**Comment by hanshansenhansson** [comment]
I noticed similar behaviour when deleting all records a while ago. People that were set to "arrest" kept their wanted status, even after their record was gone.

**Comment by Incoming5643** [comment]
The lack of a record precludes changes to the status. So a giant asshole could set someone to arrest and then remove their record and the victim would be screwed.
