### ISSUE TITLE
Pet collars are broken

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/-tg-station#8518]
Very very broken
* Kittens are invisible
* You can't put collars on corgis
* If you set the corgi's accept_collar to 1, the collar is still invisible
* They aren't being coloured (This is more a thing that was forgotten than an actual bug but fix it please)
* There's not a collar crate so you can't get more collars for puppies without ordering animas (As above, missing not broken, fix this shit)

Fix your shit Cheri

**Comment by Szunti** [comment]
And they are not updated after revive.

**Comment by WJohn** [comment]
How the hell did that get merged?

**Comment by Thunder12345** [comment]
No idea, Cheridan more like Buggidan

**Comment by Incoming5643** [comment]
You gotta win the contest next year for bugfixes :ghost:

**Comment by Xhuis** [comment]
but can you wear them

**Comment by Cheridan** [comment]
The only bug here is invisible kittens. Corgis handle their inventory differently than other animals.

**Comment by Szunti** [comment]
Shouldn't you only remove your overlays in update_collar() ?

**Comment by peoplearestrange** [comment]
There also seems to be a odd glitch that if you change a monkies sprite to the pets.dmi it constantly defaults to the collar icon_state and won't let you change it to anything else. I'll try to reproduce it tomorrow to make sure.

**Comment by Cheridan** [comment]
...Then don't change the monkey's sprite??????
