### ISSUE TITLE
People shift in no-grav while stuck to a resin nest.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8522]
I imagine this might be the case with other forms of restraining, but it might be exclusive to this.

EDIT: By shift I mean the up/down motion you do when in no gravity.

**Comment by phil235** [comment]
This happens with all objects that can buckle mobs.I think it's intended, but it could be changed with a simple buckled check.

**Comment by WJohn** [comment]
It doesn't make much sense even if it were intended, if you're restrained and stuck to a chair or surface you shouldn't be floating all over the place.

**Comment by phil235** [comment]
Well the reasoning is that there's always a little wiggle room when buckled and the floating is only 1 pixel up and down.

**Comment by WJohn** [comment]
No longer the case.
