### ISSUE TITLE
Alien nest "restraint" resin does not disappear after the host bursts in it.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8523]
What it says on the tin.

**Comment by WJohn** [comment]
This is back.

**Comment by phil235** [comment]
Actually it was never fixed for the particular case of a dead mob being gibbed. death() procs for many mobs have a sanity check to see if the mob is already dead, which means the unbuckle code isn't run in that case. Fix would be to simply move the unbuckle on death code from mob/living/death() to mob/living/gib() directly
