### ISSUE TITLE
Cig vending machines don't have any cigars/robust gold packs

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#8525]
It's unacceptable.

**Comment by Xhuis** [comment]
did you put a coin in them?
also if my cigar cases pr ever gets merged this won't be an issue

**Comment by Lumbermancer** [comment]
Yes of course I put the coin in.

**Comment by Xhuis** [comment]
guess it's just a bug then

**Comment by stapler2025** [comment]
https://github.com/tgstation/-tg-station/pull/8436

**Comment by phil235** [comment]
duplicate of #8469
