### ISSUE TITLE
You shouldn't be able to examine the contents of a beaker/glass/bottle/etc.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8528]
This is currently making it impossible to spike a drink with poisons if the person just looks at its contents first.

**Comment by Lumipharon** [comment]
This was changed for consistancy reasons, which makes sense. But not being able to spike drinks is gay as shit.
I remember someone suggested (or maybe even make a pr, I think) that you can see how much stuff is in a container, but you'd need science goggles/other, to actually see exactly what it is.

So chemists/scientists would have sciene goggles (which they already have, but are useless), and it was suggested the barman would have beer goggles, which would be functionally identical.

**Comment by PKPenguin321** [comment]
#7402

**Comment by Dorsisdwarf** [comment]
except that #7402 is moths old.  DO NOT MERGE and not everyone likes it, meaning it's uncertain as to whether it'll ever get in.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
