### ISSUE TITLE
Putting a bag of holding in a bag of holding does not give you a confirmation prompt.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8529]
I swear to god we had one of these before.

**Comment by Xhuis** [comment]
New players should learn the ___hard way___.
Jokes aside, this might be a good idea.

**Comment by Lumipharon** [comment]
This is some hand holding shit.

That said, if it doesn't already exist, the description of the BoH should directly say, or atleast allude to the fact that putting a BoH inside a BoH is a terrible fucking idea.

**Comment by bgobandit** [comment]
It's inconsistent. Like, we have a confirmation box for RIPPING A GODDAMN POSTER OMG CHELP but not for releasing lord singulo.

**Comment by GunHog** [comment]
You are referring to NT Station, which had a prompt for BoH. Normal /tg/ does not and never did. It is probably a good idea, though.
