### ISSUE TITLE
Admins should be able to get a full-control mode.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8530]
I find it extremely annoying that there is no ability to open, lock, or shock doors. I can't interact with APCs, doors, lockers, crates, or anything else as a ghost.

Clearly, admins should have the ability to toggle on this greater form of control over objects, like a mix of an AI and human.

**Comment by Jordie0608** [comment]
Use var edit.

**Comment by WJohn** [comment]
Var edit is limited on whether anything gets updated though. Editing a door's density and opacity to 0 isn't exactly great, and doesn't look great either.

**Comment by Miauw62** [comment]
has_unlimited_silicon_privilege MAY work for this if it's a mob var and not
a living var (I'm afraid it may be) , although an addition to canusetopic
would also be desirable.
Op 25-mrt.-2015 01:45 schreef "WJohn" <notifications@github.com>:

**Comment by Alek2ander** [comment]
All interactions have sanity checks which block out ghosties regardless of silicon privilege. Afaik that var is just for ID checks anyway.

**Comment by CorruptComputer** [comment]
I would like this as well, because if you aghost you cannot interact with anything. The easiest thing IMO would be to make aghosts living mobs.

**Comment by WJohn** [comment]
A combination of AI-like abilities combined with a human's ability to open lockers and crate and whatever would probably be best, although I would really like it if they maybe had hands to pick things up with too (that's probably asking for too much though).

**Comment by AnonymousNow** [comment]
Suggestion - give admins a selection of aghost sprites which sets them apart from regular ghosts and allows the dead to better track admin trickery.

This has little to do with the current conversation and does not change much, but it does mean that we can have the Rings of the Mysterons in the game.

**Comment by Amnestik** [comment]
>The easiest thing IMO would be to make aghosts living mobs. 

So all an admin has to do is type 'aghost' to be able to surreptitiously grief players?

**Comment by CorruptComputer** [comment]
Not necessarily, also if they are an admin they should be responsible enough to have power. I mean they can already turn you into a monkey, how can opening a door for someone that's trapped be a bad thing?

**Comment by Amnestik** [comment]
> if they are an admin they should be responsible enough to have power

We've repeatedly seen that that isn't the case.

If admin ghosts can interact with the environment as though they were
alive, without any logging, then it will be very easy for admins to subtly
mess with the round while out of view of other admins/ghosts.

**Comment by WJohn** [comment]
Of course there'd be logging.

**Comment by Amnestik** [comment]
A log for every admin action as a 'living' ghost? That'd be spammy. If you only log significant actions such as cutting a wire (which are already logged and would presumably still get logged for admin ghosts) then you're still allowing admins to aghost and mess with things loglessly. e.g. Admin is in brig cell serving time, aghosts and opens cell door and brig doors, blames the AI. No one can prove it wasn't.




At least with the current limited admin interaction through vars and buttons it's much harder to interact with the game world surreptitiously.

**Comment by WJohn** [comment]
There's already tons of that. Spawning stuff doesn't make big loud logs either.

**Comment by Amnestik** [comment]
Doesn't it? That's odd.

Anyway, the existence of an issue doesn't justify making it worse.

**Comment by Alek2ander** [comment]
Spawn human + invisimin + incorporeal move + godmode

**Comment by Amnestik** [comment]
I see what you mean, but at least those things are logged. If players complain about an invisible, invulnerable immaterial admin griefing them there's evidence left behind to prove it.


As far as I know, aghosting isn't logged, and by no means does it show an intention to interact surreptitiously with the environment the way your method does.




Being able to toggle ghost interactions as an admin, and having it log, instead of having them on all the time would be a decent solution, though it could still be used to surreptitiously gain an in-round advantage the way your method is too obvious to.










​Anyway, I know people will disagree with this and see it as needlessly suspicious/slanderous of the admins.

On Thursday, 26 Mar 2015 at 11:11 pm, Alek2ander <notifications@github.com>, wrote:

Spawn human + invisimin + incorporeal move + godmode

**Comment by Miauw62** [comment]
Yeah, it's needlessly suspicious. Let's remove the ability of admins to
aghost, it's not logged and lets them metagame!!!!!!!!!!!!!!!!!

It's none of our fucking responsibility to ensure admins aren't shitheads.
Tg admins are ok, and if other servers have unreliable admins that's their
own problem. Now stop posting irrelevant bullshit.
Op 26-mrt.-2015 13:47 schreef "Amnestik" <notifications@github.com>:

**Comment by MrStonedOne** [comment]
Just to point out, admins can hit f8 to become invisible while a player

This has been around for like ever, without issue of greifing.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
