### ISSUE TITLE
Have OOC messages fail to send if they start with channel punctuation

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8531]
Mostly a note to myself or someone else who can do it faster. Just filter out OOC messages that start with the symbols used to designate channels for radio. Save players a lot of heartache with accidental IC in OOC

**Comment by Dorsisdwarf** [comment]
OOC :g absorbing AI

we will miss you.

**Comment by WJohn** [comment]
Also make sure to let the player know this failed, not just silently prevent it from sending.

**Comment by Miauw62** [comment]
You should still be able to do ;g absorbing AI on derelict imo
Op 25-mrt.-2015 09:28 schreef "Dorsisdwarf" <notifications@github.com>:

**Comment by Amnestik** [comment]
It'd be neat if internet acronyms IC were changed to be something accepted IC too, i.e. instead of lmao sending a "rolls on floor laughing" emote instead, so people who made this mistake didn't have to be banned for 15 minutes for it.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
