### ISSUE TITLE
Jester Hat On-Body Sprite Not Working

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/-tg-station#8545]
As it says on the tin. Is in the game, but does not appear on your sprite when worn. Tried with a few hairstyles, didn't seem to work.

**Comment by Nienhaus** [comment]
@Miauw62 @WJohn

**Comment by Miauw62** [comment]
Huh. It worked when I tested it.
Op 26-mrt.-2015 00:58 schreef "AnonymousNow" <notifications@github.com>:

**Comment by AnonymousNow** [comment]
Strange. Will attempt to replicate at next opportunity.

**Comment by WJohn** [comment]
Yeah it doesn't work for me.

**Comment by bgobandit** [comment]
fix the jester hat pls

**Comment by Firecage** [comment]
@Miauw62 Well, the reason it is invisible, is since there isn't a Jester hat on-mob sprite in the code, and your PR which added the jester hats didn't add it. #8447
