### ISSUE TITLE
Typo in Pod Person (And lizard??) attack message

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8548]
Adeline Lacon has sliceed Adeline Lacon!

Probs applies for lizards as well

**Comment by WJohn** [comment]
What weapon did you use for this?

**Comment by SconesC** [comment]
@WJohn Bare hands

**Comment by RemieRichards** [comment]
The issue is that attack verbs always automatically add "ed" onto the end, so while the attack verb contains the word "slice" it should actually contain "slic"

**Comment by SconesC** [comment]
do pod people even have claws

**Comment by Incoming5643** [comment]
I could have sworn at some point the pod person verb was something that made it more clear that they were getting like, whipped by vine/arms

**Comment by phil235** [comment]
The problem is that the attack verb is both used as "[attack_verb]" (X has attempted to verb Y) and as "[attack_verb]ed". So whether the attack_verb var is "sliced", "slice" or "slic" we'll still have an issue. The only solution is not to use verbs that end in "e". I changed it to "slash" in my PR.
