### ISSUE TITLE
Welding tools can't be placed in an open locker

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8559]
you can still throw it in, however.

**Comment by WJohn** [comment]
I'm not sure if there's a clean way to do this, just like you can't place a wrench on a regular table. It has to at least tell you the welding tool must be on, but maybe it could also go in at the same time?

**Comment by AndroidSFV** [comment]
It used to work, without it being on. Something is broken here.

**Comment by WJohn** [comment]
Then it has been broken for years.

**Comment by Chocobro** [comment]
except not really because i was able to put welding tools in lockers about a week ago. i do it all the time whenever i'm in cargo and the qm/techs create a shitload of welding tools.
