### ISSUE TITLE
Observing from lobby is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8564]
What it says on the tin. Pushing the observe button while in lobby is broken, it just closes the prompt and says "now teleporting" while never getting you there. Relogging brings the prompt back, but it still doesn't do anything when you try to observe.

EDIT: This stopped happening a round later for no obvious reason?

EDIT2: I'll close this until it shows up again, I'm not sure what caused this but it seemed to be a freak occurrence of the round.

**Comment by PKPenguin321** [comment]
i thought critical priority tags were supposed to be reserved for server-crashers and major security issues

**Comment by WJohn** [comment]
It's also used for when you can delete people's mobs with wirecutters if they were cuffed with zipties. There's a separate security (CRITICAL) tag.

**Comment by WJohn** [comment]
BANDAID WORKAROUND: admin jump to a location, spawn a human, edit your ckey into them, then ghost.

Regular players won't be able to do this, if they're even affected by it.
