### ISSUE TITLE
Nuke Ops Still Lootable by turning corpses into monkeys.

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#8565]
IF you inject a Nuke Op with a syringe turning them into a monkey, all their stuff drops.
Including all the stuff the hardsuit change was supposed to keep unlootable.

Repro Steps
Put on Syndicate Hardsuit, activate the helmet.
Inject self with Monkey injector.
See all your stuff land on the floor under you.

**Comment by WJohn** [comment]
SE injectors seriously need to be treated more like syringes, in that they shouldn't be injectable if the person in question has an exosuit covering the limb you're trying to inject.

**Comment by Steelpoint** [comment]
Don't Nuke Op hardsuits have the "combat" mode option which gets rid of the "No Syringe" flag?

**Comment by ACCount12** [comment]
If you managed to do this, you deserve your loot. Not a bug.

**Comment by Dorsisdwarf** [comment]
What? Wandering along to the dead body that just gets left in the halls and sticking it with the easiest SE to get of all 'deserves the effort'?

**Comment by Cheridan** [comment]
@Steelpoint SE injectors don't consider the THICKMATERIAL flag like syringes do.

They probably should.

**Comment by Supermichael777** [comment]
wait dna injectors and amchens shouldent work on dead people

**Comment by WJohn** [comment]
Also to point out, like ninja suits, this actually destroys the suit. I'm sure the same would apply with any other rig suit when the helmet is turned on, but perhaps it's only the case with these.
