### ISSUE TITLE
Wall-mounted frames are copypasted

### ISSUE THREAD

**Issue by ACCount12** [tgstation/-tg-station#8568]
All wall-mounted frames are copypasted code. It's bad i think. How about making all of it subtypes of /obj/item/wall_frame?

Frames:
/obj/item/apc_frame
/obj/item/alarm_frame
/obj/item/light_fixture_frame
/obj/item/newscaster_frame
/obj/item/firealarm_frame
And maybe more.

**Comment by Jalleo** [comment]
@Razharas would this be a suitable idea?

**Comment by Anonus** [comment]
Only some of them are copypasted, some just have their own unique bullshit, like light fixtures and APCs.

**Comment by ACCount12** [comment]
Move that bullshit to subtypes then.

**Comment by ACCount12** [comment]
I would do this myself, but there is some frames on map. And i dont want to touch the map ever.

**Comment by Core0verload** [comment]
@phil235, it's fixed.
