### ISSUE TITLE
Blob is all fucked up

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#8572]
I don't even know where one bug begins and another ends.

When cores die or sometimes spawn people seem to disconnect and get kicked to the lobby
Whenever a blob is spawned another overmind is pulled from ghosts, even if someone had blobitis and popped normally. 
Sometimes overminds just randomly appear in stacks with no ckeys or anything
A core being destroyed doesn't always kill the overmind when there are multiple blobs

Multibleb is just a clusterfuck and it seems like there are severe bugs all over the place that make the whole thing nigh unplayable for blobs.

**Comment by Incoming5643** [comment]
Some of these things, maybe all of these things, have been reported before

**Comment by Stickymayhem** [comment]
And yet nothing is fixed

**Comment by Incoming5643** [comment]
Blob as a mode is a bit orphaned at the moment in terms of active development, I'm sure someone will get to it soon. Hell I'll get to it soon...ish if no one else does.

**Comment by optimumtact** [comment]
fuck blob

**Comment by Stickymayhem** [comment]
Fuck you

Blob is fun
