### ISSUE TITLE
DEATHSQUAD ARE STILL VULNERABLE TO FLASHBANGS

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8573]
#8041 

Closed but not resolved

They do NOT SPAWN WITH BOWMANS and their helmet does not protect their ears. It is not and was not an issue with their thermals. It is the bang, not the flash, that will stun them. Evidently this issue has been brought up countless times but seriously just give them Deathsquad Bowmans or something.

**Comment by Fayrik** [comment]
I intend to look at this issue in my next PR, so if I could be assigned to this, that'd be great.
