### ISSUE TITLE
Mining shuttle flavour text has a typo in it

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8576]
![omg a typo](https://cloud.githubusercontent.com/assets/5677255/6875254/424d4038-d4b5-11e4-98e4-8b297df6f152.png)

**Comment by Chocobro** [comment]
proof that it's a typo because i know one of you will be like BUT THAT'S THE CORRECT SPELLING really because it isn't
![typoproof](https://cloud.githubusercontent.com/assets/5677255/6875398/159e5364-d4b6-11e4-85fa-14de94d88a55.png)

**Comment by CorruptComputer** [comment]
I before E except after C.

**Comment by RemieRichards** [comment]
@CorruptComputer ... is invalid in this case.

The whole phrase is "I before E, Except after C, apart from Weird words" (the joke being that Weird itself breaks this rule too)

It has more exceptions that cases that follow it.

**Comment by dannno** [comment]
I before E except for in a massive amount of words that go against this rule to a point where it's pointless to even think about it

**Comment by Miauw62** [comment]
lol you should try dutch spelling it's like fifty times worse than this in every way

**Comment by Dorsisdwarf** [comment]
I'm pretty sure that CC was trying to make a joke, seeing as the spelling in question is 'CIE' (correct spelling 'CEI') which means that the rule does in fact apply here.

**Comment by Chocobro** [comment]
dorsisdwarf, stater of the obvious
