### ISSUE TITLE
maintainer headmin vote

### ISSUE THREAD

**Issue by hornygranny** [tgstation/-tg-station#8578]
VOTE OR DIE

i vote for myself

**Comment by Miauw62** [comment]
ayy lmao

**Comment by hornygranny** [comment]
@tgstation/commit-access it's time

**Comment by Nienhaus** [comment]
HG

**Comment by phil235** [comment]
Since I don't know pretty much any of the candidates, let's go with the status quo I guess...

I vote for hornygranny.

**Comment by Miauw62** [comment]
HG

**Comment by Cheridan** [comment]
I also vote for bs12bot

**Comment by Miauw62** [comment]
changing my vote to bs12bot

**Comment by Aranclanos** [comment]
8========D

**Comment by RemieRichards** [comment]
HG

**Comment by Miauw62** [comment]
more seriously, i vote for hg

**Comment by Nienhaus** [comment]
@WJohn

**Comment by Cheridan** [comment]
resolved :^)
