### ISSUE TITLE
Mediborgs are almost entirely incapable of healing

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8580]
Salgluc is so slow and so inefficient that its practically not healing at all, you'd be better off finding a medkit and dragging it over to somebody

Not sure what the solution is because I know they lost omni due to ODing people on accident, but Mediborg is near useless as a result, which sucks because their other new stuff is super good and I want to play them

**Comment by GunHog** [comment]
We need a better superchem for healing to give Mediborgs and Mysterious (NOT THE NORMAL ONES) Medibots. That, or give them more chem choices.

**Comment by Marflowerose** [comment]
Synthflesh spray, charcoal and salbutamol injection?

**Comment by PKPenguin321** [comment]
readd doc's delight and make it admin/mediborgs only when

**Comment by Miauw62** [comment]
@Iamgoofball

**Comment by phil235** [comment]
Was this fixed when we readded trekchem to medibots?

**Comment by GunHog** [comment]
Yes, you should close it now.
