### ISSUE TITLE
D100 name and desc are bad.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8589]
That's a d00.
A die with ten sides. Works better for d100 rolls than a golfball.

d00?

Ten sides?

**Comment by Jordie0608** [comment]
It's correct; a d00 is a d10 with notations in tens instead of ones.

**Comment by RemieRichards** [comment]
In code the d00 also actually only has 10 on the side var.
the result it gives you is simply the side it landed on multiplied by 10
```
	if(initial(icon_state) == "d00")
		result = (result - 1)*10
```
It's not a bug.

**Comment by WJohn** [comment]
Oh, my bad then. I thought it was a 100 sided die.
