### ISSUE TITLE
If you die while dragging someone, you continue to drag that person if someone else drags your corpse.

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8590]
It's like a party train of rigor mortis!

Notes: This happened when I succumbed, unsure if that affects it. My ghost was not in my body. Dying does not disable drags in general -- you can die while pulling runtime for instance and she will stay by your corpse loyally -- but this is a case where it does weird shit.

**Comment by phil235** [comment]
can't reproduce. Need more details. Are we talking pulling or grabbing? Suicide or ghosting? human or another mob?

**Comment by xxalpha** [comment]
Well if you die holding something, it's hard to force your hand to let go of the thing.

*feature*

**Comment by bgobandit** [comment]
- Pulling or grabbing? Pulling. 

- Suicide or ghosting? Neither, I died and then I left my corpse.

- Humans or other mobs? Humans, based on other behavior I assume it happens with other mobs

- Buckled to an item? No, I just died. For context I died trying to drag a dead body to medbay.
