### ISSUE TITLE
Passive gates do not color themselves according to adjacent pipes

### ISSUE THREAD

**Issue by vibarexel** [tgstation/-tg-station#8598]
![evidence](http://puu.sh/gTxIr/7de0c429ae.png)

Compare the passive gate running through the wall to the other devices in the image.

**Comment by Jalleo** [comment]
If someone placed that down they didnt use the pipe painter.

**Comment by vibarexel** [comment]
I had laid that down, and attempting to paint it just gives the usual attack message, at least with the RPD.

**Comment by Jalleo** [comment]
I think you paint it beforehand

**Comment by duncathan** [comment]
This definitely is a bug. Stuff like this should colour automatically.
