### ISSUE TITLE
Changeling Augmented Eyesight Bug

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#8602]
![lingbug](https://cloud.githubusercontent.com/assets/4043781/6883423/64dc2d86-d5a4-11e4-922a-32fcab4d8b7a.PNG)

**Comment by WJohn** [comment]
@xhuis

**Comment by Xhuis** [comment]
Not sure how I might fix this.

**Comment by PKPenguin321** [comment]
i recall a similar issue with keeping hivemind after buying it and resetting (back when hivemind was something you had to buy)

**Comment by SconesC** [comment]
I thought tihs was intended or I wouldve reported ages ago
Same is true for armblade/shield
