### ISSUE TITLE
empty hydrotrays will ignore most reagents

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#8608]
Empty hydrotrays seem to ignore most reagents.

Example: If you have an empty hydro tray that lacks water, no matter how many buckets you empty in them, they will never gain any water. Same goes for the different fertilizers or even things like sugar which is supposed to raise weed/pest levels.

Attempting to add any of these reagents to occupied hydrotrays will work perfectly fine however.

**Comment by Dorsisdwarf** [comment]
Temporary bypass: Hook up the hoses and put a full bucket of water into a tray which isn't quite empty.
