### ISSUE TITLE
Feature Request Limb removal.

### ISSUE THREAD

**Issue by Riktheprick** [tgstation/-tg-station#8609]
http://www.singulo.io/tg/res/28184.html#28866

The ability to have limb removal like that is actually pretty badass and make's roboticist's cyborg limbs much more relevant. I'd love to see something like this on tg station's code.

**Comment by Miauw62** [comment]
https://tgstation13.org/phpBB/viewforum.php?f=9

**Comment by Miauw62** [comment]
oh and somebody is actually working on this.

**Comment by Riktheprick** [comment]
Radical.
