### ISSUE TITLE
Removing hat doesn't update mob's head

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#8612]
A hat can be removed from the inventory but it doesn't update a mob's head var so the game still thinks you're wearing one.

Tried with both a human and a monkey

@RemieRichards

**Comment by RemieRichards** [comment]
No.
It does, because I fixed this in my testing.

I can happily put on and take off hats as a Monkey (tested multiple times)
And I tested it once with a human, and it worked too.

**Comment by phil235** [comment]
Tested it on my updated repo and the bug does happen.

**Comment by RemieRichards** [comment]
Alright, No idea how but the file I put the hat removal code into is now unticked from the dme.
it must have been ticked at some point as that was the only place hat removal code was in.

I'll get a fix up but whomever moved/unticked that file: I hate you.

**Comment by RemieRichards** [comment]
@Jordie0608 @phil235 https://github.com/tgstation/-tg-station/pull/8613 Saaaaanic merge pls.
