### ISSUE TITLE
Chem master icon disappearing when upgraded.

### ISSUE THREAD

**Issue by Turgent** [tgstation/-tg-station#8616]
![ChemMasterBug](http://puu.sh/gUbS9/22d9d0fda8.png)

The chem master icon disappears when a pico manipulator is put inside of it.
It still works.
 Server revision compiled on: 2015-03-27
51a3a8b6aa5942517651a589e4102d9b923054e7 

I was playing on Basil at the time. A Scientist came and built the chem master with a basic manipulator, then he upgraded it with a pico manipulator and it turned invisible.

edit; forgot to add labels and tag the image, apologies.

**Comment by Pennwick** [comment]
I'll look into this tomorrow. Probably just forgot some code.
