### ISSUE TITLE
Bartender's uniform doesn't have a sprite in altclick mode

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#8619]
To reproduce: 
* get a bartender uniform and wear it.
* Alt click it.
* See the 'no suit' sprite appear.

**Comment by Chocobro** [comment]
i can't even find anything related to the bartender's outfit in uniform.dmi. is it under a different name, or something?

**Comment by phil235** [comment]
The uniform's name is "bartender's uniform" I think.

**Comment by Nienhaus** [comment]
Pretty sure it's bar_suit_s

**Comment by Chocobro** [comment]
update, there isn't even an alt version in uniform.dmi. seems like the issue is the code for the uniform was set to 1 mistakenly, or the alt sprite wasn't added in the first place.
