### ISSUE TITLE
stimpacks are worthless

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8621]
they don't work at all. seems they don't actually affect stun or is parallelize much and instead acts as mega heals.i blame goofball.how is syndiesauce weaker then meth.

**Comment by WJohn** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
i think pudl had a fix but he nuked it for some reason, i'll look into it

**Comment by Lumipharon** [comment]
Unless goof changed it already, all goonchems only proc every 3 ticks.
Stimulant therefore reduces stuns by 1 tick, every 3 ticks.
Ephedrine is literally exactly the same only no healing, and synaps is literally 3 times better then this, in terms of stun reduction.

**Comment by Supermichael777** [comment]
ohay so the lowere proc and weeksaucenes make this worthless because tazer spam

**Comment by phil235** [comment]
might be fixed by #9014
