### ISSUE TITLE
Shields do not lose power if the APC powering them has its wires slashed by aliens.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8631]
It may also be caused by other methods, but either it's badly delayed or has stopped working.

**Comment by Jalleo** [comment]
I thought shields were wire powered not by the apc..

**Comment by Jordie0608** [comment]
Shield wall gens (ones in the teleporter) are wire-powered and shutdown after a delay of losing power. Anti-breach shield gens (ones in engineering) are magic and just don't use power at all.

**Comment by WJohn** [comment]
Should probably be changed, then. Lots of things are either of area power, wire power, or both. I guess it makes sense that regular shields shouldn't turn off unless the powernet runs out.

**Comment by WJohn** [comment]
Doesn't appear to be an issue after all, just some weird bit of consistency that isn't problematic enough to care about.
