### ISSUE TITLE
Aranesp - Goofball pls.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8632]
Shit kills you dead in few seconds, is lethal at less than 5u and can be ghetto made using patients room medivend. Really has to be nerfed.

**Comment by Supermichael777** [comment]
@Iamgoofball

**Comment by Jalleo** [comment]
@iamgoofball

**Comment by Lumipharon** [comment]
I did tell goof about this on coderbus yesterday, but no response...

**Comment by Iamgoofball** [comment]
@lumipharon I was probably busy dealing with a severe headache and high ass fever at the time.

I'll look into a nerf.

**Comment by Iamgoofball** [comment]
actually no it's countered by "try any fucking medicine that heals oxygen loss for fuck's sake"

stop trying to heal everything with omnizine and then complaining when it doesn't counter everything

**Comment by Lumipharon** [comment]
This shit kills you in like 5 fucking seconds, doesn't matter if you can counter it with an epi pen when you're crit before you can even open your box, and dead before anyone can even see what's wrong.

**Comment by Iamgoofball** [comment]
okay so here's my problem:

i put a fucking extra 0 on the goddamn oxyloss and forgot to check that

im dumbo the extreme, will fix
