### ISSUE TITLE
Energy Shields are useless vs xenos

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8633]
Riot shields can block tackles but these can't? Lame

**Comment by Xhuis** [comment]
I don't actually see why this would be the case. Energy shields are meant to block energy-based projectiles, and a xenomorph throwing itself at you full-speed would most likely knock you down. Riot shields are more solid and would be okay at blocking them.

**Comment by WJohn** [comment]
I can't remember if energy shields can block melee attacks any, but if they can then they absolutely should be able to block xenos too.

**Comment by Xhuis** [comment]
Looking through the code, it seems like energy shields should already _be_ deflecting pounces.

**Comment by phil235** [comment]
I'm pretty sure the riot shield was never intended to stop xeno pounce. What happens is the riot shield prevents the user from being pushed which means when the xeno leaps it can never reach the riot shield user and there's no impact. This is visible in game, the xeno leap animation doesn't stop once it's right next to its target, it simply continues until maximum leap duration. You basically see a xeno floating in mid-air standing still.

**Comment by Steelpoint** [comment]
I thought it was a feature that Riot Shields block Alien leaping attacks? Because crap leaping attacks are extremely deadly. 

Also Riot Shields have a percent chance to block alien melee attacks, its unreliable but I much prefer the chance to not get stunned to a 95% of getting stunned.
