### ISSUE TITLE
Captain's Hat is not 100% spaceworthy

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8636]
It blocks pressure damage and most temp damage but I still get a little chilly in space sometimes :c

**Comment by Cheridan** [comment]
You've done it now, you fool.

**Comment by Dorsisdwarf** [comment]
Fill your pockets with lit welding torches.

**Comment by Chocobro** [comment]
i'm pretty sure it's not supposed to be
considering it's just a hat
made of cloth and fabrics
and doesn't cover the entire head
and isn't a space helmet
??????????????????????????????????????????????

**Comment by SconesC** [comment]
But I'm the CAPTAIN
I won't stand for this

Nah it's supposed to be spaceworthy that's why it stops pressure damage

**Comment by Chocobro** [comment]
that's dumb muh realism or something

**Comment by dannno** [comment]
this is a dumb issue report

**Comment by WJohn** [comment]
Are we talking the captain's hat or captain's helmet?

**Comment by Razharas** [comment]
Intended behaviour as decided by 3 man vote in coderbus
