### ISSUE TITLE
Chloral hydrate is unreliable

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#8638]
Rather than putting to sleep, it just makes them fade in and out of sleep really fast. They can consistently run or prep calls for help. Sometimes it does this, sometimes it doesn't.

To reproduce: Go on a test server, inject self with chloral.

**Comment by phil235** [comment]
could be the metabolization rate of the chemical

**Comment by Xhuis** [comment]
I think Goonchem causing it to metabolize every 3 ticks rather than every 1 tick might be the issue

**Comment by phil235** [comment]
confirmed fixed by the reorganization.
