### ISSUE TITLE
Drowsiness variable never decreases

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#8643]
What it says on the tin. The variable _never_ goes down. Might just be on my end.
To reproduce: varedit drowsiness to 1

Assuming you _can_ reproduce this, this is a very high priority bug because you can inject someone with 1 unit of chloral and they'll be slow, blurred, and fall asleep constantly until they are cloned

**Comment by Jalleo** [comment]
@iamgoofball
