### ISSUE TITLE
Medical cyborg beaker can be put in cryo cells

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#8646]
The mediborg can place their large beaker in a cryo tube. The borg can no longer get that beaker back, and it is also NODROP for players who pick it up after it has been ejected.

**Comment by Incoming5643** [comment]
I don't get it, we had these things before nodrop was even a thing, were these bugs really ALWAYS here?

**Comment by Miauw62** [comment]
probably yeah

**Comment by Dorsisdwarf** [comment]
Was this fixed?

**Comment by Jordie0608** [comment]
Nope.
