### ISSUE TITLE
Wanted status persists even if you get a gas mask/new ID

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#8654]
1. Get set to arrest
2. Dump your old ID
3. Put on new ID/gas mask
4. Still have a big W above your head, get arrested

**Comment by SconesC** [comment]
This persists through plastic surgery, going unknown, and swapping UI/UE

**Comment by optimumtact** [comment]
hud code seems to use face_name/id_name
https://github.com/tgstation/-tg-station/blob/0367c378bfed7f36136e2e147b475bafe0ae4a43/code/game/data_huds.dm#L148

It's more likely that the hook just needs to get called when your identity status changes, the only way I can see this correctly working is by simply calling the hook on life tick.

Hmm, perhaps you could only do it when a sec hud user is in view

**Comment by Jordie0608** [comment]
Likely same problem as #8517 and #8372

**Comment by optimumtact** [comment]
I think the best solution is to add a ic_identity_changed proc called whenever a users ic identity is changed, then hook the security hud update into that, that may also come in handy later on for other stuff.

From the top of my head
plastic surgery
ling transform (any transform really)
genetics structural code update
face getting covered with obscuring clothing
id being dropped
user being disfigured

**Comment by astralenigma** [comment]
I remember that this didn't usually happen (I do have been gone for a good time), a player usually had 2 identities, the known identity to everyone around that changed with masks and transformations and the real identity usually used for log reasons and restoring the appearance through admin powers.
Someone must have either messed with the identity or wanted status.
