### ISSUE TITLE
Feature Request: Ignore specific users in OOC

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#8656]
Some of our playerbase are consistently lame shitters, so for some people, they may want to ignore the user when they speak in OOC

For each user a list of ckeys for users who we simply do not display their OOC messages, along with a verb to add and remove ignored users

This is so they can still interact via OOC with generally cool people while not enduring a pointless torrent of abuse

edit: this is intended to complement actual admin intervention by allowing the user to react immediately to abuse, rather than to have to wait until administrators can deal with it

**Comment by PJB3005** [comment]
I can see this leading up to a lot of confusion though, there should also be a way to see messages you ignored

**Comment by Chocobro** [comment]
why not just ignore them yourself
ie. with your brain

**Comment by PJB3005** [comment]
"muh chat scrolling"

**Comment by Chocobro** [comment]
ignore it
ie. with your brain

**Comment by PJB3005** [comment]
I've actually seen people on goon complain about their chat scrolling from OOC, which is why they don't like it during a round

I've also seen somebody complain about chat scrolling from a message when you switch hotkey mode

some people man

**Comment by Iamgoofball** [comment]
@PJB3005 nah, goon has OOC disabled in rounds because of the amount of times people would just go "help it says ima traitor what do???" or "FUCK THIS SHITFACE CHANGELING WHO JUST KILLED ME JSOASHAJFHKWAEHJF"

**Comment by PJB3005** [comment]
I didn't mean everybody hates it for that reason, but I've seen a couple who do

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
