### ISSUE TITLE
.45 magazine for m1911 pistol is wonky.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8659]
The holes in it do not update according to how many bullets the magazine actually holds, unlike the magazine for the c20r. This means adding a single bullet to an empty magazine makes it go from "empty" to "full of bullets" visually, when it really should only have just the one bullet on top and have the holes continue to show it as empty.

**Comment by pudl** [comment]
not every magazine has a sprite for every state

**Comment by WJohn** [comment]
Yeah, but the ones that clearly show the bullets in it (through holes or a line or some other way) should.
