### ISSUE TITLE
Space cube isn't working

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8661]
1. Go out escape airlock
2. Hit asteroid
3. Go back way you went
4. Hit other side of asteroid

???

**Comment by RemieRichards** [comment]
Dupe, the space cube is fucked.

**Comment by Lumipharon** [comment]
as far as I understand it, each edge is consistant - if you fly off a z-level on the same edge, you'll always get taken to the same z-level, it's just edge of the new z-level isn't (always) linked to the edge you came from.

Space man.

**Comment by Incoming5643** [comment]
the space cube is exactly as fucked as its always been, its consistent but not bidirectional

**Comment by WJohn** [comment]
I don't see why it needs round-start randomization anyway.

**Comment by RemieRichards** [comment]
@WJohn for the same reason we don't have fixed loot in Maint anymore.

People learn it, People repeat it, People spoil it.

**Comment by Lumipharon** [comment]
Speaking of which, as much as it pain me to say, but why does the abandoned teleporter have a fixed telebeacon thing, like the teleporter room/AI teleporter?

It means you can get the white ship (or loot the old sat) within literally 5 minutes of round start.

**Comment by Miauw62** [comment]
It needs to be bidirectional, really.

**Comment by Jalleo** [comment]
We need the z levles to be connected via space dough-nut movement. Ill explain next time on irc.
