### ISSUE TITLE
Gold slime cores can create "animals" at the very top of the path list, which are invisible.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8667]
What it says on the tin, it shouldn't be able to make these. The chances of this happening are EXTREMELY rare.

http://i.imgur.com/v4GeMre.png

**Comment by Supermichael777** [comment]
having seen this several times its not that rare

**Comment by Jordie0608** [comment]
Gold cores only spawn /mob/living/simple_animal/hostile and have an exclusion list here: https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/Chemistry-Goon-Medicine.dm#L664

The "animal" created here would be something not on that exclusion list, however to fix this it's path would need to be found.

**Comment by phil235** [comment]
"/mob/living/simple_animal/hostile/blob" is the one missing from the list. Fix would be to simply add it to the exclusion list.

**Comment by bgobandit** [comment]
Similarly, silver slime cores can spawn an invisible "snack." There's also a "snack" that looks like a kebab.
