### ISSUE TITLE
Sentience potion mob invisible

### ISSUE THREAD

**Issue by ThatSlyFox** [tgstation/-tg-station#8669]
When using a sentience potion on a mob it has a chance to turn it into the "animal", a invisible mob.

**Comment by WJohn** [comment]
Dupe of #8667 come on man literally right next to you.

**Comment by phil235** [comment]
You sure it's a duplicate? Sentience potions and slime cores aren't the same thing.

**Comment by ThatSlyFox** [comment]
I am most likely mistaken. This can be deleted.
