### ISSUE TITLE
Fire safety closets don't look welded shut when you weld them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8671]
![](http://i.imgur.com/xUm2IPW.png)

This might apply to other closets.

**Comment by Jordie0608** [comment]
I was going to fix this but having looked at all the snowflakey closet update_icon()s and closet.dmi I'm compelled to refactor it instead.

Meanwhile if someone wants to fix this they just need to remove /closet/firecloset overriding update_icon()

**Comment by phil235** [comment]
Fixed by jordie0608's refactor
