### ISSUE TITLE
Foam Not Foaming

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/-tg-station#8680]
Upon adding Surfacant [As a pill] to a beaker filled with X reagent [doesn't matter amount or type from what I've messed with so far] + Water [= amounts of Surf and Water, also tried different magnitudes and still no luck], the mix simply bursts, giving the 'foam appears' message without any foam occurring.

If you need to ask questions [I don't frequent Github or forums], ckey is ExcessiveUseofCobby.

**Comment by Supermichael777** [comment]
you need foaming agent fluoresurfcnt is for something else

**Comment by Lumipharon** [comment]
Are you sure you're using foam surfacant not foaming agent (which is used for metal foam)?

**Comment by ExcessiveUseOfCobblestone** [comment]
This issue seems to be ratified. 

I was using surfacant, which is the required chemical to create foam. Foaming agent is a metal foam exclusive chemical. I have no idea how this got fixed or what was even causing the issue to begin with, but I'm glad it is gone.

**Comment by Iamgoofball** [comment]
This was indeed fixed.

If you want the technical details, turns out locate() defaults to "in world".
