### ISSUE TITLE
Nashville Tennessee (Space Carp Typo)

### ISSUE THREAD

**Issue by buttsmcgee** [tgstation/-tg-station#8681]
![nashville tennesse](https://cloud.githubusercontent.com/assets/10753424/6934789/21186bee-d7ef-11e4-92b7-fef99497b515.png)
It should be "gnashes."

Fuck.

How does something go this long without being noticed? Is everyone just secretly illiterate?
Is it some kind of dank meme I'm not ebin enough to understand yet?

**Comment by dannno** [comment]
you're taking this pretty badly huh

**Comment by Chocobro** [comment]
he's right
"nashes" isn't even a word according to google
i never even thought about it

**Comment by RandomMarine** [comment]
Only tangentially related, but the carp emote spam is hell for anyone observing with ghostsight on.

**Comment by Fayrik** [comment]
Hold up. I tried typing nah on my phone once and it auto corrected it to nash. It's gotta be a thing, even if Google doesn't know it.
(Ironically using the android keyboard when it auto corrected. Hah.)

**Comment by buttsmcgee** [comment]
>you're taking this pretty badly huh
You're goddamn right I am.
I don't think you really appreciate just how insane it is that nobody's noticed this before (myself included).

Like RandomMarine said, the emote is endless, and it clogs up the entire chatbox any time there's carping. It makes me want to turn off ghostsight whenever I'm observing.
I would wager that "The space carp nashes at x" is the most commonly printed line in all of Space Station 13 history, behind "honk" and "x does a flip!" (RIP *flip, we hardly knew ye)

I mean, think about it:
Of all the dozens of codebases that still have carp, all the dozens more servers hosting this code, all the thousands upon thousands of rounds going on day in and day out, and all the endless schools of carp shouting this one phrase endlessly, players must have witnessed it millions of times over the years. 
That's millions of "G"s lost to the ages. Millions of "G"s we will never get back. 

And not a goddamn one of us has ever noticed on any server (myself included).
It's almost scary how something like this happens.

>Hold up. I tried typing nah on my phone once and it auto corrected it to nash
"Nash" is a name and also a liver disease.
Android, for some bizarre reason, keeps lowercase versions of proper nouns in its dictionary. Just try typing a bunch of names in and you'll see what I mean.

Notice, however, that there is no "nashed" anywhere.
