### ISSUE TITLE
New toy guns syndicate firing pins

### ISSUE THREAD

**Issue by Niknakflak** [tgstation/-tg-station#8688]
The new toy guns when spawned, have the syndicate firing pin installed so it makes them useless to the crew who cant play with them.  I dont know if this happens when they are won, I assume yes.

@fayrik

**Comment by Fayrik** [comment]
Which gun were you trying to spawn? The C20R and L6 SAW both come equipped with stun shells by default, and hence come with syndicate pins because they're syndicate weapons.

**Comment by Niknakflak** [comment]
Ok, if this is intended than this is closed.
