### ISSUE TITLE
Genetics is impossible

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8692]
Is this intended or some shit

Completely impossible to isolate powers, people randomly mutating via rads, RNG too strong, etc etc holy FUCK is it broken

**Comment by Incoming5643** [comment]
(Also those goon disabilities that are just tourettes with WACKY LINES are really lame and redundant)

**Comment by Marflowerose** [comment]
Pretty sure DNA injectors have 1/1000000 chance of actually giving powers, though that might just be accidental from rads. Makes solo-geneticist hard to test genes on self or generally giving them out.

**Comment by WJohn** [comment]
The genetics overhaul still might happen once dismemberment is finally merged, but who knows when or if that'll ever happen.

**Comment by SconesC** [comment]
I can't tell if this is because of a recent change though or if it was always like this

**Comment by dannno** [comment]
Genetics is fuck as it is right now. But it was always fuck.
It's just more fuck due to the relatively recent changes.
Manifestation chances ARE much worse
Random mutation is awful
the job itself is RNG UPON RNG UPON RNG UPON RNG UPON RNG
genetics needs a complete overhaul but no one will ever put in the effort

**Comment by PKPenguin321** [comment]
@WJohn I thought remie said she was waiting for the genetics rewrite to be done before dismemberment got pushed

**Comment by chimersable** [comment]
Could there be an easy mode for genetics in server options? I play on a server where rounds last around 40 minutes which nerfs this job beyond viability. Testing 22 strings, each string takes over 5 minutes to force active, the odds of manifest then further hold it up, xray doesn't work, heat is useless, tk and hulk are set to 5% or 1 in 20 mutations to activate, and it's just not possible in 40 minutes.

**Comment by Razharas** [comment]
This issue seems vague
Are too many blocks the problem?
Or something doesnt work at all, like a bug?
Or manifestation chances are too low?

**Comment by dannno** [comment]
literally all three

**Comment by Marflowerose** [comment]
Too many blocks, shit like elvis and swedish doesn't need their own block. Either combine them into a single blockor remove. DNA injectors don't work except for monkey-human or if they do, they only work once in a million. Proper scanner manifest chances are also extremely low.

**Comment by SconesC** [comment]
@Razharas 

Dannno is right, all three are the issue
There are too many blocks, the manifest chances are low, and the random mutations are really common and frustrating

**Comment by Lumipharon** [comment]
I was RD once. The geneticist gave me TWO BOXES of xray injectors.

I used eleven before it actually manifested.

**Comment by Marflowerose** [comment]
I was geneticist and spent the entire round printing out cold resistance hulk injectors from both computers and jabbing them in me. Never got either power during that 30min+ round.

**Comment by phil235** [comment]
related to #7385

**Comment by dannno** [comment]
I have once used over 100 injectors to get 2 out of 6 powers
genetics needs an overhaul but no one has the motivation to make it happen

**Comment by Cheridan** [comment]
I'm gonna close this, most of the stuff in this issue was addressed by #7385 
If you have a more specific complaint then make a forum thread or another issue I guess.
