### ISSUE TITLE
Burn not happening inside pipes

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8693]
Not sure if bug or feature but plasma and oxygen mix won't increase in temperature and burn inside pipes, even at 10000C.

**Comment by callanrocks** [comment]
Exploding pipes 2015: Return of the overpressure failscade.

**Comment by WJohn** [comment]
Wait this is a bug?

I haven't seen pipes burst from temperature or pressure since WAY the hell back near r4407.

**Comment by RemieRichards** [comment]
@WJohn just because Miauw tagged it a bug doesn't make it a bug.

it was most likely removed as a simplification.
(I've definitely seen comments about pipes exploding in the code)

**Comment by Boggart** [comment]
What he means is that you can't burn gasses inside the pipes, you used to be able to get them hot enough with a heater or other method that they'd combust in the pipe, producing CO2 and heat.

**Comment by astralenigma** [comment]
The problem now is that to make bombs we also need to disconnect the canister for the combustion to happen.

**Comment by duncathan** [comment]
ideas forum
