### ISSUE TITLE
Borg suggestions

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#8694]
- Give borgs internal flashlight like drones have. It isn't really a problem for most types of borgs but engi and miner are really slowed down by having to have the lamp on pretty much constantly when in action. It could be a third option in the HUD menu alongside health and sec HUDs.

- Some kind of clearer indicator that borg has run out of power, more clearer examination text and if someone's feeling spritey, to have some kinda red light blinking so that the retarded roboticist knows to put the borg into the recharger. Alternatively, when borg rolls on an open recharger, it'd automatically set borg power to something small like 10 so it'd have ability to recharge itself.

- Nano-armor for minerborg (mainly) as buildable and toggleable upgrade that would use power to very slowly regenerate hull damage.

**Comment by Miauw62** [comment]
https://tgstation13.org/phpBB/viewforum.php?f=9
