### ISSUE TITLE
Cannot scan someone who has commited suicide but survived via virology with the cloner.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#8697]
If you commit suicide and survive due to a virus you cannot be scanned into the cloner, it says: "Subject's brain isn't responding to scanning stimuli."

1. Get infected with a virus that has the oxygen symptom.
2. Commit suicide but survive.
3. Attempt to get scanned in the cloner.
4. Fails with standard suicide message.

The mob's suiciding var was true.

**Comment by Marflowerose** [comment]
This was also happening way before but it still showed the "Has commited suicide" while being alive but the message from examination has been removed.

**Comment by Miauw62** [comment]
the real bug here is surviving suicide.

**Comment by WJohn** [comment]
Yeah it really should instantly kill you, there's no reason for it to deal 190 oxy damage or however much it is, that can be survived by an immediate epinephrine shot and a trip to the sleeper/cryo.
