### ISSUE TITLE
Wizards issues with xray and laser eyes.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#8699]
Using laser eyes you gain from casting mutate, while having xray from the orb, makes you lose xray for a tick.

Buy mutate
Buy orb
Fire laser eyes
Lose xray
Regain xray after a tick

Why is it bad?

Cant see through walls while spamming your lazers of doom.

**Comment by Razharas** [comment]
This is a bug that makes so much sense i vote it to be a feature
