### ISSUE TITLE
You can't place plating, lattice, or wires on asteroid tiles.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8702]
Really just a lack of a feature, since #8022 never got merged.

This is starting to cause problems for an engineer right now trying to build, but it really just comes off as inconsistent or broken since you USED to be able to do this before the floor code rewrite.

**Comment by Chocobro** [comment]
i considerably remember being able to place plating on the asteroid some time ago. either it was removed deliberately (why) or some dumb shit like paper changing slightly broke it.

**Comment by phil235** [comment]
wasn't there an issue with it where you place plating on the asteroid and then if it's destroyed you get a space turf or something?

**Comment by WJohn** [comment]
Yes, that's an issue right now. However you can already melt asteroid turfs and the singulo eats that up anyway, both leaving space tiles.

**Comment by xxalpha** [comment]
I think I can enable the cabling easily. Not sure why you can't platify asteroid turfs though. Lattices should be for space only.

**Comment by Miauw62** [comment]
pliss fix this somebody
