### ISSUE TITLE
Alien leap is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8704]
If you smash into a wall, you get weaken for 2, and it never goes down. Seems to happen on simulated and unsimulated areas, gravity or not. I tested this in the thunderdome, at least. Seems sorta inconsistent on where it happens, but I've definitely had this happen on the station a number of times recently. #8629 and #8644 have NOT been merged at the time of writing.

**Comment by RemieRichards** [comment]
Wrong. It's the Alien Life() that's wrong, Weaken is lowered in life.

**Comment by WJohn** [comment]
I'm just pointing out the var that got changed when it happened :p

**Comment by RemieRichards** [comment]
Yeah but you're blaming me here.

**Comment by Xhuis** [comment]
This shouldn't be happening. I'm not sure the cause of it, because in handle_status_effects the proc has a ..() before the unique part of aliens.

**Comment by WJohn** [comment]
I'm not blaming you D:

I'm just pointing out that this is suddenly broken, could be caused by anything.

**Comment by phil235** [comment]
Found the bug, I made handle_status_effects() use AdjustWeakened() to naturally reduce the weakened var. The problem is that this checks for CANWEAKEN status_flag and aliens don't have it.

**Comment by RemieRichards** [comment]
Yeah I had to stun the xenos manually, ```weakened = 2```, every other "stun" type effect was either also blocked, or shit looking.
