### ISSUE TITLE
Music is still distorted from april fools.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8710]
It hasn't reverted, so playing music is a coin toss on what it's gonna sound like.

**Comment by Incoming5643** [comment]
This has to be fixed on the host's side, we can't actually do anything about a sound file that only exists there.

**Comment by Jordie0608** [comment]
https://github.com/tgstation/-tg-station/blob/51a3a8b6aa5942517651a589e4102d9b923054e7/code/modules/holiday/holidays.dm#L96
