### ISSUE TITLE
NIGHT OF THE SHAVED ZOMBIE IANS

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#8711]
Shaving a dead corgi displays the living shaved-corgi sprite. The corgi does not appear dead upon examining, nor can it die again unless you try to harvest corgi meat.

**Comment by Niknakflak** [comment]
D'awwwwww, ok i'll look into this.

**Comment by Niknakflak** [comment]
also feature

**Comment by phil235** [comment]
that's because shaving set icon_state to corgi_shaved in all cases. Shaving proc needs to first set icon_living and icon_dead and then call update_icons() or something.
