### ISSUE TITLE
Disassembling Telecomms Machines

### ISSUE THREAD

**Issue by NemoVonFish** [tgstation/-tg-station#8715]
Tested on the Subspace Recievers and Processor Units that start in Telecomms, the crowbar step doesn't do anything, despite saying it does.

>Screwdriver: You unfasten the bolts.
>Wrench: You dislodge the external plating
>Wirecutters: You remove the cables
>Crowbar: You begin prying out the circuit board and components...
You finish prying out the components.

But nothing happens. Machine is unchanged, no parts spawned, nothing.

**Comment by francinum** [comment]
Tested on servers, Worked as intended.

**Comment by NemoVonFish** [comment]
You can't disassemble Telecomms machines, and one of the messages is bugged and doesn't do anything. How is that 'working as intended'?

**Comment by phil235** [comment]
Reproduced. This is due to a runtime.
