### ISSUE TITLE
Storing items in food is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8717]
You can no longer put items in cheesewheels or loafs of bread, though it still works for cakes.

EDIT: More specifically it works with at least cheesecakes, I haven't tried the others.

**Comment by Chocobro** [comment]
NO
i must be able to put the disk into cheese wheels
and cheese wheels into cheese wheels
i must.

**Comment by phil235** [comment]
Yeah, you can no longer put stuff in plain or custom bread or cakes, but you still can for recipe cakes and breads. This interfered with the custom food process. Not sure about the cheesewheel. I'll try to fix it.
