### ISSUE TITLE
Pete doesn't make milk anymore

### ISSUE THREAD

**Issue by Lumbermancer** [tgstation/-tg-station#8724]
His "udder" is permanently dry. I'm not sure if it's Pete only or all goats.

**Comment by Chocobro** [comment]
PETE MADE MILK?

**Comment by MrPerson** [comment]
Is this how we immortalize Pete and honor his legacy? By making him buggy?

Actually that's a pretty fitting tribute tbh

**Comment by Jalleo** [comment]
I though pete was a male...

**Comment by WJohn** [comment]
I was going to make a joke on where we got the milk from, but no.

**Comment by Chocobro** [comment]
just tested, it's all goats. this is from a goat ordered via cargo.
![goatbug](https://cloud.githubusercontent.com/assets/5677255/6992737/0894e6fa-dad4-11e4-9452-c0d25943d102.png)

**Comment by RandomMarine** [comment]
Goat's life() proc is broken overall. Goats don't make milk, don't go after vines, only eating them on move(), and don't attack things at random.

**Comment by phil235** [comment]
Well, apparently it wasn't my life refactor who caused this but #8206.
