### ISSUE TITLE
Ninjas are masterfully slicing everything ever

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8725]
The new Energy Katana masterfully slices everything
The floor, consoles, chairs, food, people, clothing, walls, bullets

...But it doesn't do anything, so I'm guessing it's a bug. If I'm not clear, I mean you can't hit the floor or a console or a bread loaf with a stunbaton or a toolbox, nor does it produce a message. 

@RemieRichards 

Yeah shit I don't make sense

**Comment by RemieRichards** [comment]
there's no way to tell if an emag_act() will do anything on an object, so at first there was a message.

Now there's no message at all, you'll know if you've emagged something when it gives you it's usual emag message.

**Comment by Incoming5643** [comment]
CUT

EVERYTHING
