### ISSUE TITLE
Autoprocess no longer automatically scanning people in pod

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#8729]
I had to get the AI to do it for me and I had just upgraded both machines with phasic scanners

**Comment by Incoming5643** [comment]
Don't all three machines need to be upgraded

**Comment by Kromgar** [comment]
How do you upgrade the computer? It doesn't need parts

**Comment by GunHog** [comment]
Did you wait at least three seconds in the scanner? (Not the pod, just the scanner!)

**Comment by SpyroZeppeli** [comment]
Autoprocess is buggy. Sometimes it works, sometimes it doesn't. It's seemingly random.

**Comment by callanrocks** [comment]
Give it a couple of seconds, It takes a moment for it to scan you, half assed code diving confirms the theory that it doesn't actually scan you when you close the door on autoprocess and that's entirely done by the cloning computer deciding by some arcane measure.

**Comment by Dorsisdwarf** [comment]
Closed for unreproducible issue.
