### ISSUE TITLE
anus3 is ruining our server

### ISSUE THREAD

**Issue by TgStationRULES1337** [tgstation/-tg-station#8730]
Problem Description: anus3 was made headmin and is keeping ERP banned, ruining my life, and calling me hitler IRL because I suck.

What did you expect to happen: sos to still be headmin

What happened instead: anus3 was headmin

Why is this bad/What are the consequences: i want sos back

Steps to reproduce the problem:
1. log onto server
2. see anus3 is host
3. panic the fuck out
4. post about this on singulo

Server: both but I'm migrating to vorestation if shit isnt done!!! because Im a poopy butt

Revision: whatever revision Anus3 took over

Possibly related stuff: fucking anus3 has nothing on our overlord scaredofshadows please come back bby ;_;
~~BROUGHT TO YOU BY GOOFBALL'S TUTORIAL SYSTEMS: EDITION "HOW 2 INTO ISSUE REPORT", HAVE A NICE DAY~~

**Comment by An0n3** [comment]
100/10 best report

**Comment by optimumtact** [comment]
You fucking retard, An0n3 is the server host not headmin, closed wontfix, account banned

**Comment by An0n3** [comment]
When are we going to get a "Blame An0n3" tag?

**Comment by Miauw62** [comment]
Stop fucking tagging this bullshit as critical or anything else, it just shits up the fucking tags.
