### ISSUE TITLE
Weird sound delay on ninja sword emaging blast doors

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8738]
Steps to reproduce:
 - Get sick-ass katana
- Apply to blast doors

Blast doors will open and the slicey emag sound plays like a good second and a half after the blast doors have opened

@RemieRichards

**Comment by RemieRichards** [comment]
@SconesC it's the delay of emag_act(), I've already swapped the two lines around so the emag happens during the sound effect.
