### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by CorruptComputer** [tgstation/-tg-station#8740]
code\modules\admin\verbs\getlogs.dm:55: warning: run: run is deprecated.
code\modules\admin\verbs\getlogs.dm:75: warning: run: run is deprecated.
code\modules\admin\verbs\getlogs.dm:90: warning: run: run is deprecated.
code\modules\admin\verbs\getlogs.dm:105: warning: run: run is deprecated.

Just downloaded it, commit 42c7c36a689a9a9c3c4ac93987648734e2fe1433

**Comment by phil235** [comment]
weird, that file hasn't been changed in 7 months.

**Comment by CorruptComputer** [comment]
I updated to byond 507.1280 earlier today if that means anything.

**Comment by RemieRichards** [comment]
Yeah it's not the file, it's byond's fault hence:
>run is deprecated

They've stopped supporting that proc, and have probably removed it.

**Comment by CorruptComputer** [comment]
Should I just go back to the stable release of byond?

**Comment by RemieRichards** [comment]
@CorruptComputer changes nothing, we're going to have to sort it anyway.

**Comment by CorruptComputer** [comment]
Ok

**Comment by Jordie0608** [comment]
http://www.byond.com/forum/?post=1808737

**Comment by MrPerson** [comment]
I wouldn't use 1280 anyway since it's kinda buggy. I downgraded to 1278 and it's been working fine

**Comment by CorruptComputer** [comment]
This had been fixed.
