### ISSUE TITLE
Ninja names showing as MODE at end of round

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8743]
This has been around for a WHILE actually

http://prntscr.com/6pjb5v

**Comment by RemieRichards** [comment]
Probably not just Ninja, a few antags set ```special_role = "MODE"```

**Comment by SconesC** [comment]
I like how nobody asked why there were so many ninjas

**Comment by Incoming5643** [comment]
It can happen in certain instances with nuke ops and wizards too. the MODE stands for "game mode player" which is how antagonist that start offstation get around job selection at roundstart. Strangely ninjas have never been a round start antagonist, so why it's set to MODE doesn't really make sense anyways.

Just blame Ninja Code

**Comment by RemieRichards** [comment]
Don't blame babby ninja, his parent was abusive, it's not his fault!

**Comment by WJohn** [comment]
I reported this as part of #8537, but yeah it should get its own issue report.

**Comment by Dorsisdwarf** [comment]
Do ninjas need to be MODE? Couldn't they just be 'Ninja'? They can't be a roundstart antag since ages, so...

**Comment by Incoming5643** [comment]
As far as I can tell any instance of MODE could replaced with a descriptive name and have exactly the same effect. It just has to not be null to avoid job selection.

**Comment by SconesC** [comment]
I've seen MODE pop up in ragin' mages as well
