### ISSUE TITLE
Security jumpsuit is one pixel too thin, and heart boxers are too large.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8750]
This results in several white pixels outside the jumpsuit, more so with the security jumpsuit as it's a bit thinner around the side sprite's crotch.

![](http://i.imgur.com/UpV99Oq.png)

**Comment by Amnestik** [comment]
Jumpsuits don't hide underwear?

**Comment by phil235** [comment]
duplicate of #8378. I'm closing the old one.

**Comment by dannno** [comment]
jumpsuits can't hide underwear. if you roll a jumpsuit down your bra will be missing if you're a qt grill.
probably undershirts too.
