### ISSUE TITLE
Using Ninja Regen spams message

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8753]
![screenshot_1](https://cloud.githubusercontent.com/assets/9714964/6995891/b311bf68-db1a-11e4-9b71-5141cab407f0.png)

This was for 1 use of healing

Didn't do damage every time ti said that, either

@RemieRichards

**Comment by phil235** [comment]
This is odd, this is obviously linked to the ninjasuit adrenaline boost and other abilities giving you radium in your body, but injecting radium manually into a mob doesn't cause that message spam.

**Comment by phil235** [comment]
The issue is apply_effect() for radiations, that gets called each life() by the radium, and if you have any protection against rads you get that message each time.
