### ISSUE TITLE
Meteors crashed the server... I think

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#8754]
I don't know if it was the meteors or the round length it  was 2 or 3 hour long round ended around 1:45am est 4/5/2015

Meteors crashed the server while we were fighting xenos, 5-6 mechs were running around. A good portion of the crew was deafened and blinded and... you might want to look at the logs. Oh and their were 2 ninjas.

**Comment by SconesC** [comment]
Pretty sure an unrelated plasma cutter bug killed the server
