### ISSUE TITLE
Ninja masterfully slicing backpacks

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8755]
@RemieRichards I'm really sorry I opened this many ninja issue reports

Probably related to #8725 but I didn't want to overlook something

![screenshot_2](https://cloud.githubusercontent.com/assets/9714964/6995973/7c5b24c8-db1f-11e4-8503-52b084478185.png)

On the bright side, I'm a valuable testing service... Right?

**Comment by killerfgs** [comment]
Well y'know having a burning hot energy sword in a backpack is probably gonna slice it up a bit.

**Comment by RemieRichards** [comment]
I removed the message a while back.
