### ISSUE TITLE
Ninja stealth doesn't turn off at 0 power, can be used whenever

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8756]
Though it drains the battery, there's nothing stopping ninja stealth from draining it into negative numbers and so it can effectively be left on forever if you don't mind never using any other powers.

Even if you turn it off you can turn it back on even if you have no/negative power.

**Comment by Jalleo** [comment]
@RemieRichards

**Comment by dannno** [comment]
im MAD
IM
MAD
