### ISSUE TITLE
foam reaction is broken

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#8757]
Only the first foam reaction in a round will work correctly, all other foam reactions will send a message that foam is spreading, but nothing will actually happen.

Also affects the cleaning and metalfoam grenades.

**Comment by optimumtact** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
well shit, I dunno what caused this

nothing I changed recently should cause this

fucking foam code

**Comment by Iamgoofball** [comment]
okay so @Tokiko1 @optimumtact 

i haven't had a chem PR merged in weeks

so this wasn't me, someone else broke it this time

**Comment by Iamgoofball** [comment]
@MrPerson 

this is you probably, last changes to foam code was object pooling on foam

**Comment by RemieRichards** [comment]
For original reference, when I originally tried pooling /effect ages ago FOAM was the only one I couldn't get to work, so I scrapped it.

Perhaps it's reared its head again
