### ISSUE TITLE
Bunnies spawn in space, rather than on the station.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8762]
I'm assuming they're using the carp spawn instead of blob or xeno spawn, which is dumb because it means they just sorta sit there all round rather than making more bunnies and making eggs everywhere.

**Comment by Jordie0608** [comment]
This is intentional, but I have no idea why.
https://github.com/tgstation/-tg-station/blob/master/code/modules/holiday/easter.dm#L32

**Comment by WJohn** [comment]
But... they're stuck in space unable to move. Whether they die or not isn't really the problem, they can't even interact with anybody.
