### ISSUE TITLE
Varediting in certain circumstances leaves no log

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#8764]
You can varedit and if you include a var in the edit, as is asked in the pop up upon changing something, it leaves no log in asay or the secret adminlog

**Comment by Jordie0608** [comment]
Does it log to the server logs?

**Comment by Sometinyprick** [comment]
You can view all varedits in the runtime logs

**Comment by tkdrg** [comment]
This is an actual issue though, despite being minor. I get it that you want to thaw the freeze but jeez

**Comment by Iamgoofball** [comment]
@tkdrg mso said it was fixed in IRC

**Comment by tkdrg** [comment]
@MrStonedOne please clarify

**Comment by MrStonedOne** [comment]
There was an issue where list editing wasn't logged, this was fixed by HG.

If that is what this is talking about, then it's fixed. If it's talking about something else, then who knows.

**Comment by tkdrg** [comment]
yeah I see you must be right
