### ISSUE TITLE
Stabilized flash and sonic powder are extremely weak at any volume

### ISSUE THREAD

**Issue by babinsquared** [tgstation/-tg-station#8768]
Flash/Sonic powder obtained through stabilizing agent seem to only affect those on the same tile, regardless of the amount used.

Fill a bluespace beaker with 300u of either powder and heat it to 374K. It will react, but only apply the disabling effects to those standing on the same tile. This applies whether you're using grenades or simply heating the beaker in a chem heater.

The unstabilized versions work just fine. 15u aluminum, 15u potassium, 15u sulfur will stun people several tiles away. 45u stabilized flash powder? Not so much.

**Comment by SconesC** [comment]
@Iamgoofball
