### ISSUE TITLE
I'm an idiot and created an infinite loop trying to fix a bug

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8770]
Having a fun blob round that isn't a total squash for either side?

Sure hope you like having the entire server crash before either side can resolve it.

**Comment by MrStonedOne** [comment]
runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
proc name: Destroy (/obj/effect/blob/core/Destroy)
Shutting down after encountering too many critical errors

[16:16:28] <kevinz000> I mean, every time ti crashed I saw my shots piling up on a tile
[16:16:31] <kevinz000> Then conenction closed.

**Comment by WJohn** [comment]
I can attest to seeing that happen. Just seconds before the server crashed, I would see those shots pile up on a tile unable to hit the blob despite being in range and then the server dies.

**Comment by Incoming5643** [comment]
Well the bastard who most recently touched that proc was.

Whoops it was me

:scream:

**Comment by RemieRichards** [comment]
@Incoming5643 ur such a poo

Destroy is calling Destroy with arguments when Destroy doesnt even have arguments
qdel() is being called without an argument when it needs one.

**Comment by MrStonedOne** [comment]
This is still happening.

**Comment by MrStonedOne** [comment]
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot read null.ambience_playing
proc name: Entered (/area/Entered)
  source file: areas.dm,333
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
Warning: further proc crash messages are being suppressed to prevent overload...

**Comment by MrStonedOne** [comment]
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
  usr: null
  src: NPCPool (/datum/subsystem/npcpool)
  call stack:
NPCPool (/datum/subsystem/npcpool): fire()
/datum/controller/game_control... (/datum/controller/game_controller): process()
runtime error: Cannot execute null.call bot().
proc name: fire (/datum/subsystem/npcpool/fire)
  source file: npcpool.dm,114
Warning: further proc crash messages are being suppressed to prevent overload...
