### ISSUE TITLE
You can turn on internals with a bandana.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8771]
I don't think I need to explain why that doesn't even make sense. It's a piece of cloth. Even a clown or mime mask at least has some mouth hole you could conceivably fit the air tube into.

**Comment by Chocobro** [comment]
air tube goes in the mouth
muh rp

**Comment by dannno** [comment]
Fairly certain what happens is that the internals toggle on for a few (byond) seconds and then turn off.
This happens with all masks.

**Comment by phil235** [comment]
Danno's right. The underlying issue is the internals button being on for a while.

**Comment by dannno** [comment]
if so, this is a dupe.

**Comment by kingofkosmos** [comment]
The most confusing part is that it says "now running on internals from...". Even though it's not.

**Comment by Jordie0608** [comment]
#7276

**Comment by phil235** [comment]
fixed by #8766
