### ISSUE TITLE
Failed convert roundtypes don't end the round and spam adminlog

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/-tg-station#8774]
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
Unknown gasps!
The mouse runs in a circle
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
The mouse squeeks
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
OOC: Arfeudutyr: Way to fuck up, AI.
ADMIN LOG: Convert_roundtype failed due to round length. Limit is 60 minutes.
ADMIN LOG: MrStonedOne/(Alpha 6) is considering ending the round.

The same thing happens for the dead count check

I've seen this with malf ai and blob.

@Incoming5643

**Comment by Incoming5643** [comment]
All my shit is breaaaaaaking
