### ISSUE TITLE
You have to open a box's inventory to flatten it.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8779]
In order to flatten a box now, you have to open its inventory, THEN use it in your hand to flatten it. It also creates the cardboard sheet in your other hand, and drops it on the floor if that hand is full.

**Comment by Jalleo** [comment]
It got bugged then.

**Comment by Amnestik** [comment]
Unrelated, but I've always wanted syndicate boxes to create syndicate cardboard when flattened so you can craft a syndicate box borg

**Comment by phil235** [comment]
It's been this way for a long time, but yeah, definitely a bug.
