### ISSUE TITLE
Cheridan is absolutely broken

### ISSUE THREAD

**Issue by ACCount12** [tgstation/-tg-station#8783]
He closed two pulls without any discussion just because he personally hates stungloves and anything related to stungloves. #8782 and #8781. This is bad i think.

**Comment by Incoming5643** [comment]
May be related to #6999

**Comment by Jalleo** [comment]
I personally like that stun gloves are gone they were always bad. If it was a antag weapon only then sure.

**Comment by Jordie0608** [comment]
An issue report isn't really the place for this.

**Comment by Cheridan** [comment]
Remember when I told you to not push your luck? I guess you were distracted by the sounds of balalaikas or something, you fucking joker.

**Comment by Chocobro** [comment]
EASY FIX

**Comment by Miauw62** [comment]
>tfw people keep ruining the purity of issue tracker-tan
Op 7-apr.-2015 18:43 schreef "Chocobro" <notifications@github.com>:
