### ISSUE TITLE
Shuttle loan events can break the cargo shuttle.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8790]
It seems to be random which ones cause these, perhaps it requires multiple of these to happen.

**Comment by Miauw62** [comment]
Fayrik has suggested that the event triggering while the shuttle is in
flight may cause this.
Op 6-apr.-2015 19:42 schreef "WJohn" <notifications@github.com>:

**Comment by phil235** [comment]
@Miauw62 I tried triggering the even mid-flight but you can't accept the loan while the shuttle is moving so I couldn't reproduce the bug that way.
