### ISSUE TITLE
Reviver implant doesn't work.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8791]
While it does periodically defib you, the nanites don't have enough time to start healing you at all for the milisecond you're alive, and don't heal you while you're dead.

**Comment by hornygranny** [comment]
@xxalpha please make this work and remove the ability to build it, it should be for deathsquad/admin only

**Comment by An0n3** [comment]
Thank God for this at least.  It shouldn't work.  It shouldn't exist.  It's a terrible idea.

**Comment by Lumipharon** [comment]
While I'd be glad to see this removed altogether, shouldn't this specific issue only exist, if the corpse has almost 200 non oxy damage? That's an intended thing with defibs.

**Comment by WJohn** [comment]
That's up to how healing corpses should work, if at all. You can slap on patches to heal up corpses (while there is no other method in the game) and defib them anyway even though the cause of death was injury. If we're gonna do that, and give the auto-defib implant a super god chem that also heals brute/burn, it should be able to either mimic it or not even attempt it (replace the chem with something much more tame).

**Comment by Lumipharon** [comment]
Patches healing corpses has always struck me as really dumb, as it means anyone with a defib and a few pill bottles full of patches (how does that even work) can revive you essentially regardless of situation.

**Comment by WJohn** [comment]
It's intended, but it's a consistency issue that could either be removed or expanded to all chems and methods of healing.

**Comment by xxalpha** [comment]
I'll be removing this implant as soon as I can dedicate time to this, in about a day or two. I am very busy at the current time.
