### ISSUE TITLE
Picket signs should probably have a cooldown

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#8797]
Right now you can just spam the use key to spam the chat.

**Comment by Jordie0608** [comment]
It just uses click cooldown, I don't remember too spammy but on the other hand that's rather the point of picketing.
https://github.com/tgstation/-tg-station/blob/8d2f92cdd315c35a2c7b3e524950f26f99d419a1/code/game/objects/items/weapons/signs.dm#L25
Could do with a real cooldown I guess. @AnturK

**Comment by Amnestik** [comment]
It is very easy to spam with, considering you can use the z key to send the message about twice a second. I don't think the point of picketing is spamming the chatbox.

**Comment by AnturK** [comment]
Well spamming is their primary use but i guess i can add some minor cooldown.
