### ISSUE TITLE
The inbuilt jetpack on the blood red hardsuit doesn't work for the most part

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8798]
Launched myself out a disposal, jetpack doesn't respond (this is a known bug)

but even after landing, even from rest, the jetpack does nothing. The trails are shown when it's on and it will properly increase your space movement, but you can't actually use it to turn in space

Mysteriously I've seen that it DOES work for engineering hardsuits. Maybe ALL jetpacks don't work if the person has ever been shot out of a disposal?

(also these need UI buttons)

**Comment by Jordie0608** [comment]
@xxalpha

**Comment by WJohn** [comment]
I know for a fact if you're launched out of the mass driver you can't alter your trajectory until you smash into something. I don't think this applies to disposal pipes, but I might be wrong.

**Comment by xxalpha** [comment]
I am going to guess all jetpacks are broken this way, but I'll look into it tomorrow.
