### ISSUE TITLE
Humans and cyborgs can't melee computers to break them.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8806]
I don't know if this was always the case or if it's a recent bug, but both aliens and simple animals can. Seems like a consistency issue and an oversight.

Humans and borgs can still laser computers to break them, for what it's worth.

**Comment by Jalleo** [comment]
I believe we were able to bash computers before.

**Comment by Cheridan** [comment]
This was only ever the case for monkeys and xenos. Humans/borgs breaking computers with simple melee attacks would probably be a balance issue.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
