### ISSUE TITLE
Detectives revolver reskinning is crappy

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8811]
Reskinning the revolver with a simple left-click is shitty. If you do not do it, because you do not think about it, it will trigger and give you the popup as soon as you left click it. Which would be when you would like to shoot a guy instead. 

Hell, I even manage to change into Detectives Armor without triggering the reskinning. But as soon as I want to pewpew, I get locked with that damn popup and get robusted.

What was wrong with the good old right-click menu?

**Comment by fingersticky** [comment]
Coderbus has a hard-on for removing them, for whatever reason.

I would also like to know what is "wrong" with the right-click menu.

**Comment by Miauw62** [comment]
The fact that it's slow and laggy?
Fuck object verbs but there's better ways to do the reskinning than the way
it's done right now
Op 7-apr.-2015 20:16 schreef "fingersticky" <notifications@github.com>:

**Comment by dannno** [comment]
> for whatever reason.

the reason is that they're bad.

**Comment by hanshansenhansson** [comment]
But what is bad about them? They are intuitive and perfectly usable.

**Comment by hanshansenhansson** [comment]
Just paid attention to it:

Leftclicking on revolver in the locker picks it up.
Leftclicking on it in your backpack picks it up.
Pulling it out of your armor slot, to shoot the baddy, it gives you the popup menu.
