### ISSUE TITLE
Magic mirror race changing does not change the color you specify

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#8819]
How can I expect to ERP as a neon pink slimegirl if I can't change myself to neon pink???
@Incoming5643 

To be more specific, it doesn't change to the color it specifies, i.e. if i choose lizard and then a blue color it just defaults to green.

**Comment by Incoming5643** [comment]
If you are testing this on a private server there's a (very needless) config setting you need to toggle to allow for custom alien colors to work. I'll test to make sure the bug isn't JUST because of that.

**Comment by Incoming5643** [comment]
Cannot replicate, guessing it's what I said in the last comment
