### ISSUE TITLE
Gold core slimes can produce head slugs [Bug and/or Feature]

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8825]
Since they aren't blacklisted gold core reactions can rarely spawn head slugs, which can infect the dead with eggs that later spawn a monkey-ling with the same controller as the headslug itself. 

With judicious use of sentience potions and a humanized monkey corpse a player can be brought into the round as an antagless station aligned changeling. This takes a lot of effort to do, and leads to an interesting and rare situation, so my gut is to say "this is a feature!"

At the same time though such a ling could very easily compromise ling chat and potentially out a lot of antagonists, but then, so can the antag lings themselves if they so choose.

**Comment by Cheridan** [comment]
With the same amount of effort you can get sentient statues and alien queens I guess so this probably isn't TOO bad.

I would say that the caveat to this would be that this new changeling shouldn't have a connection to the hivemind, so no Hive Upload/Download or Hivemind chat to antaghunt.

**Comment by WJohn** [comment]
This is so cool. I'm okay with this, actually.

**Comment by AnturK** [comment]
Uh. Right. Can fix this i guess ? Or you know turning gold core to whitelist

**Comment by Incoming5643** [comment]
Unless someone has a real problem with it, I don't think it should be fixed

**Comment by Miauw62** [comment]
Cheri says this is ok, and he's a headcoder so...
Op 8-apr.-2015 17:42 schreef "Incoming5643" <notifications@github.com>:

**Comment by AlexCrimson** [comment]
Now lets just wait for people to ruin the fun and get this "fixed".

**Comment by Cheridan** [comment]
@Miauw62 Well, people are allowed to disagree with me :V

**Comment by Miauw62** [comment]
Sssh you have to be a tyrant to uphold the oligarchy :V
Op 9-apr.-2015 15:38 schreef "Cheridan" <notifications@github.com>:

**Comment by Incoming5643** [comment]
it's a feature
