### ISSUE TITLE
Cryosting does nothing.

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#8831]
To reproduce: 
- get stung
- check that you have frostoil in your reagents
- check your bodytemperature not changing at all.

**Comment by SconesC** [comment]
I think this is frostoil just being ASS 

It needs buffs, badly. Prior to Goofchem, Cryosting was deadly as fuck.

@Iamgoofball

**Comment by tedward1337** [comment]
Thanks @Iamgoofball

**Comment by Iamgoofball** [comment]
secret coderbus conspiracy plot to nerf ling
(I'll look into it)
