### ISSUE TITLE
Adrenal implants now make you pass out

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#8832]
Gee thanks goofball

**Comment by tedward1337** [comment]
This is honestly a serious balance issue. Using the implant once knocks you on your ass after a few seconds.

**Comment by Iamgoofball** [comment]
@Stickymayhem 
Quit being so hostile.

**Comment by dannno** [comment]
said goofball

**Comment by Iamgoofball** [comment]
@dannno i was nice for the first 6 months, shove it up your ass :^)

**Comment by phil235** [comment]
Please, let's try to remain civil and keep criticism constructive guys.

**Comment by Stickymayhem** [comment]
Sorry @Iamgoofball it's just the coderbus version of "Thanks Obama!"
