### ISSUE TITLE
Syndicate bombs generate explosion-like smoke a few seconds before they explode

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#8834]
(Syndicate bombs, as in the things you place for 60secs)

Second time I fell for it. Fix that please, have the smoke be generated after the explosion, not before.

**Comment by Incoming5643** [comment]
Could not replicate, are you sure there wasn't any other kind of explosive in the area that may have caused the smoke, maybe a minibomb?

**Comment by hanshansenhansson** [comment]
No, there was only my syndicate bomb. This happened multiple times already. Might be lag related. Smoke just gets generated before the explosion does. 

I moved to the bomb, saw the smoke, moved in for ~7 tiles, real explosion happened and it gibbed me. Other people on the server saw the same stuff happening.

**Comment by Dorsisdwarf** [comment]
It's a booby-trap.

**Comment by phil235** [comment]
Can't reproduce, the smoke occurs at the same time as the explosion so my guess is a big lag spike caused this.
