### ISSUE TITLE
Taser bolt going through people

### ISSUE THREAD

**Issue by milocv** [tgstation/-tg-station#8836]
I was escaping from someone because I was a traitor scum, so to get ahead, I fire my taser at them. To my surprise the bolt goes right through that person and does not stun them.

I am 100% sure I did not miss because it was in a 1 tile wide corridor in maint, I fired the taser and the bolt went in a straight line and ignored my target. I saw the bolt behind that person. We were both moving.

I do not know for sure what caused this or how to reproduce it, but it got me killed.

**Comment by phil235** [comment]
Pretty sure this happened because the player moved onto the taser bolt's tile once it was right next to him before the taser bolt bumped onto him (there's a 0.1 second time window). It's a known bug which will be fixed by #8687.
