### ISSUE TITLE
Voice Analyzers not triggered by whispers

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8839]
The fact that I cannot explode my maxcap suicide package in crit is a problem

Seriously though, why don't voice analyzers read whispers? No reason why they shouldn't.

**Comment by RemieRichards** [comment]
too quiet :^)

**Comment by Lumipharon** [comment]
you can hear whispers from one tile away - radios (unless they were also changed) can also hear whispers from one tile away. Doesn't make sense if voice analysers can't hear whispers.

**Comment by Miauw62** [comment]
I'll look into it
Op 9-apr.-2015 04:13 schreef "Lumipharon" <notifications@github.com>:
