### ISSUE TITLE
Cyborgs immune to fire damage

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8840]
There really should be a threshold wherein they start taking wiring damage. They're supposed to be vulnerable to burn damage hence the extra steps to fix it when it occurs. Silicons zooming around at mach 5 through a 96k C raging plasma fire is really silly.

**Comment by WJohn** [comment]
They CAN take burn damage from sources like fires, but yeah otherwise they're immune to being set on fire, heat, and hotspots.

**Comment by PKPenguin321** [comment]
if this goes through then i'd like them to still be spaceworthy

**Comment by SconesC** [comment]
They should be spaceworthy, yes, but should they be able to zip through a roaring plasma storm consequence-free? No.

**Comment by xxalpha** [comment]
Yes, because who the fuck is gonna clean it up if not the engineering cyborgs?

**Comment by Dorsisdwarf** [comment]
Borgs should be burnproof but get flame, so as you praise the lord at having closed the escape firelocks as the fire rushes along the corridor, A FLAMING BORG BURSTS THROUGH THE AIRLOCKS AND EVERYONE FLIPS THEIR SHIT AND THEY RUSH INTO SPACE TO AVOID THE FLAMING PLASMA 

and the AI announces:

Burn, babby, Burn

**Comment by Nanotransistor** [comment]
What i had thought about is that heat should hinder their ability to work properly, but not damage them. Like, extreme heat should make them move slower, make their tools malfunction and maybe drain their battery faster.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
