### ISSUE TITLE
Table Crafting Bug 04/08/2015 Report

### ISSUE THREAD

**Issue by DonkHonk** [tgstation/-tg-station#8846]
After an update around this time, it has come to my attention that we cannot use the table to properly craft recipes.

Each time the window is brought up the ingredients will show but it will state the following each time you try to cook a dish.

Construction Failed.

That seems to be it from what I can tell.  Just to be sure I tried cooking on the floor [seeing as a chem addition was added for mixing on the floor when dumping chemicals] though this shows nothing.

**Comment by DonkHonk** [comment]
Additional Note.

Cooking on the table is possible.  However it appears you need to be holding something [anything in fact] in your hand to table craft.

**Comment by Jalleo** [comment]
@phil235

**Comment by phil235** [comment]
Broken by the refactor of do_after(), I think. Will fix

**Comment by phil235** [comment]
Fixed by #8873
