### ISSUE TITLE
New chemistry piles have an issue

### ISSUE THREAD

**Issue by Fallouttec** [tgstation/-tg-station#8848]
When trying out the reagent piles i made a line of 9x 10 unit black powder in the hall, when one exploded it did no damage (insufficient powder), but the reagent pile remained with literally nothing in it, and it cannot be removed outside of an admin deleting the tile itself. Attached are chat screenshot and a game view shot
![scrnshot1](https://cloud.githubusercontent.com/assets/4712399/7061013/048bb95e-de66-11e4-87a7-73faba7923b0.png)
![capture](https://cloud.githubusercontent.com/assets/4712399/7061014/0abd911c-de66-11e4-9f04-cd9ed38aa840.PNG)

**Comment by Jordie0608** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
I'll add a process check

**Comment by Cheridan** [comment]
You shouldn't need a process check if you've covered all the places where this bug would happen...

**Comment by phil235** [comment]
Fixed by #9030
