### ISSUE TITLE
Literally every on mix goon reagent is fucked

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#8849]
Since goof cannot remember things I tell him, here's a pr.

Every single goon chem that has a 'reaction on mix' creates, and leaves over the resultant reagent, rather then consuming it, where as tg 'react on mix' chems create just a reaction, leaving nothing left over.

This was partly addressed following the LDM smoke server crash thing, but chemicals such as Life still have this bug.

**Comment by optimumtact** [comment]
What is the actual bug you are reporting here? Try to be as clear as possible because I'm a little slow

**Comment by Lumipharon** [comment]
When you mix a chemical, such as flash powder etc, it creates a reaction, but doesn't literally leave behind a chemical in the beaker called flash powder.

The new goon chems however, create this excess reagent, which in most cases, is completely inert and cannot do anything, or be used for anything, or as previously in the case of LDM and sorium, could be used to crash the server.

**Comment by Iamgoofball** [comment]
@Lumipharon 
do you know about stabilizing reagent and what it does?

**Comment by Lumipharon** [comment]
This is not to do with stabiliser, this is about the reagent existing without stabiliser. I presume you fixed this for the chems that can be stabilised.

**Comment by Iamgoofball** [comment]
Yeah.

I'll make life work like the other stabilizer chems.
