### ISSUE TITLE
Slime processor broken

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#8850]
Step 1: put in dead slime

Step 2: process

Step 3: process again because the slime didn't get removed from the contents

Step 4: keep processing because it's broken and you can't do anything else now

**Comment by Incoming5643** [comment]
Are you sure the power was on? The processor is on equipment power, which goes before lighting, so it's not always obvious that it's unpowered.

**Comment by Dicks1** [comment]
https://github.com/tgstation/-tg-station/commit/f17f5b9a3676b84ad6d745a27b355f2781cb9068

Say you put in a grey slime, you can keep clicking the processor to get infinite slime cores.

**Comment by Jalleo** [comment]
@Iamgoofball 
https://github.com/tgstation/-tg-station/commit/c06ad7e6b8dcef8445b5e448e36003fa791914d0#diff-4dc4d2887274ed8455f8358324df32a0L22

**Comment by Iamgoofball** [comment]
the weird things byond doesn't throw a compile error over

**Comment by phil235** [comment]
Fixed by #8863
