### ISSUE TITLE
Doorcrushing is really underwhelming

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8862]
For blast doors/airlocks slamming shut on someone, it sure does not do a lot of damage

It's usually pretty hard to line up, as well, so there's no reason why it shouldn't clock you for a good 30 brute, maybe?

**Comment by Incoming5643** [comment]
Thanks to stuns if you get caught in a door it doesn't really matter to much how much damage it does cause you're in a chain stun.

**Comment by SconesC** [comment]
Yeah but it requires someone to be repeatedly slamming the door. Big deal for a loud rogue AI to have its attention focused on crushing one guy to death.

**Comment by Dorsisdwarf** [comment]
Want a secret?
If you set it up right, you can make the doors autocrush, and they just keep crushing everything in them.

That's how I http://i58.tinypic.com/117z0nd.png
