### ISSUE TITLE
Airlocks cannot have electronics installed.

### ISSUE THREAD

**Issue by Arctophylax** [tgstation/-tg-station#8869]
The step of installing the airlock electronics in constructing an airlock does not work.
When installing airlock electronics into a secured and wired airlock assembly the electronics immediately pop back out after receiving the message:
"You start to install electronics into the airlock assembly."
This prevents new airlocks from being constructed without the RCD and airlocks from having their accesses changed.
Server: Basil
Revision: 7e5f6aba3cdc569ae580c40d06f204ce217aa4ad

**Comment by phil235** [comment]
fixed by #8873
