### ISSUE TITLE
Wrong max pressure shown in volume pump dialogue box

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#8870]
~~The atmos setup guide on the wiki says to replace four pumps in atmos with volume pumps and set their output to max. After doing this though, it's impossible to raise the pressure any higher than default (200k out of 4500k). You can lower it, though.~~

Edit:
![](http://i.imgur.com/vW6u0Vy.png)

The range is actually 0-200l/s

**Comment by kingofkosmos** [comment]
I can't find the phrase where it says to "set volume pumps to max". Volume pumps start at their max output which is 200 **l/s** not kPa, which is just the pressure output limit for the normal pump.

**Comment by Amnestik** [comment]
Interesting. It says in the volume pump dialogue box when you're setting the new pressure that the max pressure is 4500k.




You're right though that it doesn't say on the Wiki to change the pressure of the volume pumps. My mistake.

**Comment by kingofkosmos** [comment]
Oh right, thanks for uploading a pic, now I see what you mean.

**Comment by Miauw62** [comment]
honestly the dialogue also confused me at first because i thought the l was a 1.

**Comment by Amnestik** [comment]
Me too.
