### ISSUE TITLE
Ling armshield can be spawned while stunned, and it just drops onto the floor. Also flavor text does not appear upon summoning.

### ISSUE THREAD

**Issue by Man-Shroom** [tgstation/-tg-station#8885]
Be a changeling
Get stunned
Spawn armshield
Marvel as it appears on the floor.
Behold as it does not deliver the red text that says your arm is twisting and mutating into a shield, the way the armblade does.

**Comment by Jalleo** [comment]
@Miauw62 
Simple check addition would that fix it?

**Comment by Miauw62** [comment]
yeah, simple check
