### ISSUE TITLE
Gar glasses are really powerful.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8902]
They deal 10 damage and are among the only items in the entire game that can embed just by throwing them, miners can basically use these as ghetto throwing stars.

**Comment by Miauw62** [comment]
lmfao

**Comment by dannno** [comment]
no problem here

**Comment by RemieRichards** [comment]
No real complaint here either.

for minuscule effort you can build a spear, a much better weapon in terms of damage and the fact it TOO can embed.

**Comment by WJohn** [comment]
A spear on the other hand is really unwieldy and the absolute max you could hold with you is 3 (4 if you drag one). You can just keep on piling gar glasses in your backpack, pockets, and eyes.

**Comment by Cheridan** [comment]
manly as fuck

**Comment by dannno** [comment]
how often do miners decide to put all of their points into a set of glasses to throw at people
(really though i should maybe lower the embed chance and shit)

**Comment by Dorsisdwarf** [comment]
Hell no
