### ISSUE TITLE
Revived spider bugs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8904]
Here's a few:
1. Killing a spider and removing some of its legs then bringing it back with the lazarus injector means it comes back with all its legs. Pretty harmless.
2. Rekilling the spider first shows it to have all 8 legs, but when you start butchering it again it picks up with the number of legs it left off, except you can't harvest legs anymore!
3. I'm hearing multiple cutting sounds going off when I hit a revived spider, I'm not sure if this keeps stacking with each revive, but it definitely sounds like at least 2 are playing at once.

**Comment by phil235** [comment]
Are you sure about 2? Leg harvesting has prob(50) to drop a leg each time you cut one.

**Comment by WJohn** [comment]
Oh, I seem to be mistaken about 2. Perhaps I was just very unlucky with the leg harvesting. However the starting part of 2 is still in effect, where until you start cutting its legs again it'll show all 8 before returning to where it left off.

**Comment by stapler2025** [comment]
should be a feature that you can cut off spider legs and revive it, then keep it as a stationary pet/trophy.

**Comment by phil235** [comment]
3 isn't linked to the mob type but the weapon, so far I can  only reproduce it with a /ustensil/knife
