### ISSUE TITLE
Wizards turned into cyborgs via borgmachine keep their spells

### ISSUE THREAD

**Issue by Chocobro** [tgstation/-tg-station#8905]
this is absolutely going to be claimed as a feature by anyone and everyone, but i feel i should report it for posterity's sake.
only really plausible if there's a malf round that mulligans into wizard, or there's an admin event.

**Comment by WJohn** [comment]
I think this should be expanded to more ways. If a larva bursts form a wizard, it should retain the wizard's power.

**Comment by Lumipharon** [comment]
spells are linked to the brain, so when you get borged (even by machine/staff etc) you keep them.

There was some bitching to have this removed at one point, but I don't really see why.

**Comment by Incoming5643** [comment]
anything with spells keeps spells so long as they're still the same "person". I.E a wizard debrained in an MMI can cast fireball, but a wizard who dies and later is picked to be a xeno can't.

Edgelord and feature. Also I should point out that malf mulliganing into wizard (or visa versa) isn't a thing that can happen [yet].

**Comment by Supermichael777** [comment]
as a prevoiusly borged wizerd you do keep some spells

**Comment by Miauw62** [comment]
feature

**Comment by Iamgoofball** [comment]
feature

**Comment by Iamgoofball** [comment]
oh ffs miauw
