### ISSUE TITLE
Claymore has no belt sprite.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8906]
What it says on the tin, it has a back sprite but no belt sprite.

**Comment by Cheridan** [comment]
>putting a claymore in your belt

that's how you lose your pants :hocho: :jeans:

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Mapping/Spriting, Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
