### ISSUE TITLE
Hardsuits are not syringe-proof?

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#8907]
top funny shoot the nuke ops with neurotoxin for a stun that lasts over 2 minutes

why is this a thing

please god why

**Comment by Lumipharon** [comment]
le ebin combat mode faec.

**Comment by SconesC** [comment]
irrelevant, hardsuit should be syringe immune

nuke ops are so vulnerable so much stupid shit

**Comment by Xhuis** [comment]
Syringe vulnerability was one of the major tradeoffs of combat mode - this was intentional.

**Comment by Lumipharon** [comment]
the whole combat/travel mode makes no sense, considering that
A: ops have nvg's by default
B: space produces light

So the fact travel mode forces some crappy light on to let people see you makes no sense.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
