### ISSUE TITLE
Locker overlays looks stupid

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#8909]
The door now disappears with the Locker overlay rewrite.
We need ones of them open, or to revert it (since the intention was to reduce filesize, I believe, meaning adding extras for doors open would bring it back up.)

Cmon now.

**Comment by Boggart** [comment]
Thanks for reporting this Remie, I meant to do it this morning but I'm still sick and just got on now.

It doesn't seem to affect all the lockers, just most of them. (Emergency O2 lockers, dorm closets are fine while radiation suit, clothing lockers, mechanical and electrical storage lockers aren't. **Not a full list.**)

**Comment by phil235** [comment]
I don't understand what the issue being reported here is. Are locker door disappearing when you open the locker?

**Comment by Boggart** [comment]
Yes.

**Comment by optimumtact** [comment]
@Jordie0608 did you miss any of the overlays?
