### ISSUE TITLE
Enthralling a lizard turns them into a human

### ISSUE THREAD

**Issue by palpatine213** [tgstation/-tg-station#8912]
what the title says, when a lizard is enthralled, they become a human

**Comment by RemieRichards** [comment]
Reported this at the time but:

This is because your species becomes /datum/species/human/thrall
turning you "human" visually.

**Comment by Incoming5643** [comment]
It also means you can to some degree "escape" from thralldom by using green slime mutagen to change your species.

Keeping track of who's thralls probably shouldn't be reliant on species datums.

**Comment by Xhuis** [comment]
Fixed in the update

**Comment by Xhuis** [comment]
This was originally intended to let people find thralls via the different name in the health analyzer but that feature is being removed.
