### ISSUE TITLE
Shadowling auto-declare completion

### ISSUE THREAD

**Issue by AnturK** [tgstation/-tg-station#8922]
Prints unnecessary warning when everything is fine.

**Comment by Incoming5643** [comment]
What's happening here is that EVERY modes auto declare is called at the end of a round, so that message appears for any round in which shadowlings weren't in play (which is nearly all of them)

Also shoulda been a debug message

**Comment by AnturK** [comment]
Well that's how it works. Auto declare is for buttoned in antags right.

**Comment by Xhuis** [comment]
Fixed in the update
