### ISSUE TITLE
Hydroponics crate is missing a sprite.

### ISSUE THREAD

**Issue by Turgent** [tgstation/-tg-station#8926]
I was running around in maintenance and searching storage rooms for nick-nacks to take. 
I found that I was unable to move onto a tile as there was an invisible crate there. The crate's name is "Hydroponics crate."

Server revision compiled on: 
8aa84e0f250b10f6c673ebb5232172307c2bf0b5 

Image of the tile.
![rawrgh](http://puu.sh/hboj8/4ba9b92953.png)

Image of the tile viewed with alt-left click.
![lrawrgh](http://puu.sh/hbon9/d60eabb375.png)

This was on Basil. On the 12th of April, 2015. The time when the pictures were taken was 21:38 GMT +1.

**Comment by phil235** [comment]
@Jordie0608 Related to closet refactor?

**Comment by phil235** [comment]
Fixed by #8936
