### ISSUE TITLE
If all hatched Shadowlings die, Shadowling round ends

### ISSUE THREAD

**Issue by drynwyn** [tgstation/-tg-station#8928]
If several shadowlings hatch, and others don't hatch, and the hatched ones die horribly, the round will end even though their are unhatched shadowlings alive.

**Comment by drynwyn** [comment]
POSSIBLE CORRECTION: This may have been a result of a DIFFERENT bug, wherein thralls are not separated from Shadowlings on the after-round report.

**Comment by Xhuis** [comment]
They are separated. The text is just really hard to read.

**Comment by Xhuis** [comment]
Cannot reproduce.

**Comment by drynwyn** [comment]
Yeah this is erroneous, due to my mistake with the thralls being difficult to tell apart from the lings.
