### ISSUE TITLE
Cablecuffs don't count you as in custody at round end

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8931]
Bug or feature?
leaning feature as non sec have easy access to them

**Comment by hanshansenhansson** [comment]
As far as I know, "in custody" is about your location and not cuffs, means brig cells or the shuttle brig.

**Comment by phil235** [comment]
not a bug

**Comment by Jordie0608** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/objective.dm#L257
