### ISSUE TITLE
Star light is experiencing severe light drop-off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#8939]
Since new lighting, starlight has been able to go into maintenance tunnels. However, its effects drop off from full brightness to near blackness in the course of one or two tiles.
http://i.imgur.com/6n4kGgI.png
http://i.imgur.com/UyQmLAJ.png

Hopefully the intensity of star light can be reduced without requiring another major overhaul.

**Comment by MrPerson** [comment]
It could be reduced, but this is a factor of light being additive. WIthout redoing that (which isn't that hard), the only other option would be to put it back to 1-2 tile range.

**Comment by Incoming5643** [comment]
yeah I've noticed effect giving some unnaturally strong light to lined up computer terminals too, despite those being as weak a light source as possible.

**Comment by Jalleo** [comment]
This was known already @MrPerson is working on a solution i believe

**Comment by WJohn** [comment]
Since we don't have starlight anymore, I guess I'll close this.

**Comment by Incoming5643** [comment]
we actually do, the config option was just turned off
