### ISSUE TITLE
Lipstick is too dark.

### ISSUE THREAD

**Issue by Nyvrem** [tgstation/-tg-station#8944]
All lipstick looks like it is made for goths since it looks like black and maybe, if you look closely, you finally realise it is just really dark.

This makes essentially all lipstick worthless unless you liked black lipstick to begin with.

**Comment by Incoming5643** [comment]
might be someone using a multiply effect when they really want an overlay

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.

**Comment by Incoming5643** [comment]
This wasn't a feature request, lipstick really did change to be always nearly black reguardless of color at some point, it was feature loss.

I don't know why this was tagged as feature request in the first place.

**Comment by Miauw62** [comment]
yeah fair enough lipstick is fucked.

**Comment by WJohn** [comment]
Yeah I just tried jade lipstick on albino skin and it came out fully completely dark. That's not an overlay issue with alpha going on, that's straight broken.
