### ISSUE TITLE
Airhorns + singulo = TONS OF EXPLOSIONS AND LAG AND OH GOD

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8946]
somebody made a FUCKTON of airhorns and put them on a desk, then bohd a boh to make a singulo.
Sybil almost died from all the tiny explosions and sparks. something did this, anyway

**Comment by Dorsisdwarf** [comment]
Why the hell do airhorns make explosions and sparks when singulo'd?

**Comment by Iamgoofball** [comment]
@Dorsisdwarf different problem resulting from spinning items and singularities

**Comment by Incoming5643** [comment]
Airhorns don't have any code that would make them explode

**Comment by Miauw62** [comment]
oh damn.
also the singulo was spawned by bluespace who forgot to mention this
