### ISSUE TITLE
Runtimes when using Malfunction Verbs

### ISSUE THREAD

**Issue by GunHog** [tgstation/-tg-station#8948]
@Incoming5643 The addition of canUseTopic() checks to using Malfunction verbs as a method for checking for dead AIs has resulted in runtimes which completely prevent the usage of Malfunction abilities that have these checks. Example runtime below.

<b>To reproduce:</b> Simply buy and use any of the newer Malf verbs that have had this check added. 

Revision: 853009f7e08a49915cfaea9c6642dd29da3572c3 

runtime error: Cannot read null.x
proc name: checkTurfVis (/datum/cameranet/proc/checkTurfVis)
  source file: cameranet.dm,137
  usr: HAL 9000 (/mob/living/silicon/ai)
  src: /datum/cameranet (/datum/cameranet)
  call stack:
/datum/cameranet (/datum/cameranet): checkTurfVis(null)
HAL 9000 (/mob/living/silicon/ai): canUseTopic(null, 0)
HAL 9000 (/mob/living/silicon/ai): Compile Mecha Virus()
runtime error: Cannot read null.x
proc name: checkTurfVis (/datum/cameranet/proc/checkTurfVis)
  source file: cameranet.dm,137
  usr: HAL 9000 (/mob/living/silicon/ai)
  src: /datum/cameranet (/datum/cameranet)
  call stack:
/datum/cameranet (/datum/cameranet): checkTurfVis(null)
HAL 9000 (/mob/living/silicon/ai): canUseTopic(null, 0)
HAL 9000 (/mob/living/silicon/ai): Initiate Hostile Lockdown()

**Comment by Incoming5643** [comment]
just use canusetopic they said
it'll work fine they said

**Comment by optimumtact** [comment]
it'll work fine when you fix it!
