### ISSUE TITLE
Gold slime cores create invisible mobs

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#8953]
Gold slime cores when used can create invisible crates and animated shooty guns that are invisible and a real nuisance to kill

**Comment by WJohn** [comment]
Still? Follow up of #8667 then.

**Comment by Bawhoppen** [comment]
On the current public server's version it is still the case at the very least even if it was fixed already.

**Comment by WJohn** [comment]
Oh, perhaps the server hasn't been updated yet.

**Comment by phil235** [comment]
I think the invisible crates are due to the closet refactor, not sure. @Jordie0608

**Comment by WJohn** [comment]
But the crates he's talking about are simple animals (mimics), and I don't think they turn into regular crates when killed like with animated crates.
