### ISSUE TITLE
I CAN SEE THE LIGHT

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#8954]
Literally.

Right clicking any tile will show the light object as a selectable thing to do all sorts of stuff with, it should really be made more abstract like whatever the hell "flash" is so normal players can't select it.

**Comment by Jordie0608** [comment]
@MrPerson

**Comment by MrPerson** [comment]
I know about this. I thought it was fixed but I think I reverted that before commiting. Trivial fix though.
