### ISSUE TITLE
Silver slime cores spawn broken foods

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#8955]
Silver slime cores when used to spawn food with the cooking update can now spawn burgers with nothing in them and things like that

**Comment by phil235** [comment]
Did this happen after #8881 was merged and server update?

**Comment by Bawhoppen** [comment]
This is a several days old before I reported this issue, so it may not be accurate anymore, if so my apologies for posting this. I imagine it would be easy to test if this is the case still.

**Comment by phil235** [comment]
already fixed
