### ISSUE TITLE
Grenade launcher description 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/-tg-station#8956]
The grenade launcher description is bugged, supposed to show how many grenades are loaded.  This is has been the case for a long time as I remember seeing it in NT-code

That's a grenade launcher.
a terrible, terrible thing. it's really awful!
It is a bulky item.
It has the electronic firing pin installed.
/list / 3 grenades loaded.

**Comment by Miauw62** [comment]
I promised to report this myself.
sorry ;_;
