### ISSUE TITLE
you can make an infinite number of foors slippy with water

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#8960]
fill a beaker and dump it directly on the floor.
scoop up chempile.
repeat.
this is goofballs stulf right?

**Comment by Supermichael777** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
you need to work on your English skills

this is my fuckup though, i got a fix planned

**Comment by Cheridan** [comment]
piles were removed
