### ISSUE TITLE
Pete no longer provides meat when butchered. Other animals too.

### ISSUE THREAD

**Issue by BillWilsonCIA** [tgstation/-tg-station#8963]
Pete and the Fox no longer provide meat when butchered.

**Comment by BillWilsonCIA** [comment]
Butchering a regular Xeno provides xeno meat, but a Hunter does not anymore.

**Comment by Jordie0608** [comment]
This should be fixed by #8892, servers may not have updated.

**Comment by phil235** [comment]
Actually this is fixed for all animals except foxes because its meat_amount var was never set so it's equal to 0 by default, so you get no meat.
