### ISSUE TITLE
Cannot lay pipes perpendicular over eachother sometimes

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#8973]
![2015-04-14 19_42_02-sybil_ immoral relay nine](https://cloud.githubusercontent.com/assets/3975713/7143204/65b4a2f0-e2de-11e4-82f6-a90fb54e3e89.png)

trying to lay a horizontal pipe in the center of this image results in the message "there is already a pipe at that location", despite there being no pipe. Putting a horizontal pipe there and attemping to wrench a vertical pipe has the same result. I have manually crossed pipes in other locations minutes before this, and it worked just as usual.

**Comment by Miauw62** [comment]
I tried again the round after right after the round started (no other pipes laid), and it worked.

**Comment by Menshin** [comment]
What were your steps for building this configuration ?
Was there a horizontal pipe or manifold (that you unwrenched and stashed away) before ?
Did you retried later into the round ?

That's (possibly) a good hint to reproduce/fix the atmos pipenet lasting bug (when i'll find some time to work on it or anything /tg related...)

**Comment by Miauw62** [comment]
![](http://i.imgur.com/SL2Auyf.png)

Here is how I ended up fixing everything. The filter was present from roundstart, and I just realized that the mixer is misoriented (should be pointing down)
i hadn't built anything else on that tile before. i had the other atmos tech try, but it didnt work for him either.

**Comment by duncathan** [comment]
Did we ever get steps to reproduce this?

**Comment by duncathan** [comment]
I can't reproduce this. It likely was fixed back when I did my pipe construction refactor a few weeks ago.

**Comment by duncathan** [comment]
>It likely was fixed back when I did my pipe construction refactor a few weeks ago.

**Comment by duncathan** [comment]
See above
