### ISSUE TITLE
You can have chemical piles with water in them

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#8977]
![beaker](https://cloud.githubusercontent.com/assets/5659269/7147966/ef0029b0-e2cc-11e4-990b-de67870e25dc.png)

**Comment by Incoming5643** [comment]
chemical piles with liquids in them should really be chemical puddles.

They should also probably evaporate over time

**Comment by WJohn** [comment]
I feel like this is a dupe.

**Comment by Iamgoofball** [comment]
i'm gonna axe chem piles

**Comment by phil235** [comment]
fixed by #9030
