### ISSUE TITLE
Emergency response team has no comms

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#8995]
I've played twice as an ERT member, the comms did not work both times. 
I'm unsure if the headsets use the station comms but that would be really inefficient as you don't usually have comms up when you call for an emergency response team. (It's also really hard to talk to your team)

I was under the impression they would have a channel like the deathsquad.

**Comment by Fayrik** [comment]
Okay, so currently, all headsets require a fully functioning telecomms setup to work. The only exception is the syndicate encryption key.
ERTs and Deathsquads actually share a channel right now, but it still relies on telecomms so if comms are down then they're left without.
Also, there isn't a fully functioning telecomms network at Centcom, which means comms are always down in that area.

I've been looking into this for a little while now, but so far I've not found any easy or clean fix, but it is the highest priority for my next PR.

**Comment by Shad0vvs** [comment]
Doesn't the syndicate have their own tcomms setup on their ship? Is that not possible to just copy over somewhere on the map with a different channel name?
