### ISSUE TITLE
Feature request(?): Nuke Ops unhealable becuase of hardsuits

### ISSUE THREAD

**Issue by Shad0vvs** [tgstation/-tg-station#8996]
If a nuke op is in crit they are unable to be healed by allies, yet there is a medkit on their shuttle.

So basically if you are crit you are dead if you have your hardsuit on unless they get you to medbay or back on your shuttle if the sleepers are even upgraded.

Maybe make it so that nuke ops can also remove other nuke ops hardsuits??

**Comment by WJohn** [comment]
I think perhaps nuke ops should rely on combat hyposprays, like in their syndie medkits. Make them pierce through the hardsuit if they don't already.

**Comment by killerfgs** [comment]
brute patches go through hardsuits, just give them one of those

**Comment by KorPhaeron** [comment]
I don't think nuke ops should have instant heals on top of all that armor they get. I dunno why them losing their armor is a big deal anyway. If the nuke ops split up enough for you to loot them they lost anyway, and if they stay together you're not going to get to loot them/the round will be over soon.

**Comment by leibniztg** [comment]
"If the nuke ops split up enough for you to loot them they lost anyway, and if they stay together you're not going to get to loot them/the round will be over soon."
A competent solo nukeop can do a lot, but if they loot off pinpointers and other stuff off the newbies, then it is a lot harder.
