### ISSUE TITLE
ayy lmao

### ISSUE THREAD

**Issue by optimumtact** [tgstation/-tg-station#9000]
ayy lmao

**Comment by GunHog** [comment]
Dang it, Oranges.

**Comment by Cheridan** [comment]
you fuck

**Comment by Iamgoofball** [comment]
Wow, fuck you oranges.

**Comment by Dorsisdwarf** [comment]
10,000 should be a complete game overhaul where every single bit of text is changed the "FUCK YOU ORANGES"
