### ISSUE TITLE
Upgraded Welding Tool cannot fit in Utility Belt

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9003]
Reproduce: Hack U-Tool or spawn /weldingtool/hugetank, attempt to put it in a toolbelt

The upgraded welding tool is too big for the toolbelt.
![toobig](https://cloud.githubusercontent.com/assets/9714964/7172644/1fcf4048-e3a0-11e4-9991-fa04c4365181.png)

**Comment by WJohn** [comment]
I forgot we even had upgraded welding tools. Honestly it should be renamed to something else and be given an even cooler sprite than the industrial welder, because it's really not obvious it's better.

**Comment by babinsquared** [comment]
I always assumed this was a feature/downside.

**Comment by SconesC** [comment]
If it is, something should probably be changed sprite-wise, they look identical to a normal welder despite the quadruple capacity.
