### ISSUE TITLE
Kudzu could benefit from adminlogging

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9004]
@Cheridan 

feature request

There's currently no way to find this via logs (To my knowledge) and it causes some annoying witch hunts in certain situations

**Comment by optimumtact** [comment]
It could benefit from being removed

**Comment by Incoming5643** [comment]
@optimumtact 
![salty duane](https://cloud.githubusercontent.com/assets/4176358/7186202/027040e2-e436-11e4-94cb-f7177b77f894.gif)

But yeah probably a good idea

**Comment by SconesC** [comment]
kudzu is stupid yeah 

but logging good
