### ISSUE TITLE
possible unintended abduction race change gland behaviour involving slime people

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#9006]
Being abducted and having the race changer gland inserted can turn you into slime people who will produce slime jelly in their bodies. This is highly lethal to anyone but slime people. Having your race switched to something else after you have built up a large amount of slime jelly will then kill you extremely fast.

May or may not be intended behaviour but I'm assuming that the race changing gland was not intended to be this lethal to the victims.

**Comment by WJohn** [comment]
@incoming5643 You mind handling this alongside your wizard mirror race change fix?

**Comment by Incoming5643** [comment]
it's the same problem so yeah
