### ISSUE TITLE
[BUG] Infinite metal rods. Can be used to then make infinite metal sheets.

### ISSUE THREAD

**Issue by WereChipmunk** [tgstation/-tg-station#9007]
I ran into a bug that lets someone make infinite metal rods which can then be converted to infinite metal. Basically I made a looped disposal pipes ride with R-floors at the pipe exits. Every time you burst through the R-floor you get a metal rod. The R-floor will never break so you can throw stuff/moneys in the loop to continuously make metal for you. 

Attached two pictures to illustrate. 
The first is the loop, the second is all the rods created.

![infinite metal2](https://cloud.githubusercontent.com/assets/5678688/7175568/17f61560-e3e4-11e4-8a8e-bbd3ff16f2cf.png)

![infinite metal](https://cloud.githubusercontent.com/assets/5678688/7175553/f3c4e81a-e3e3-11e4-8bc3-984e8d94e901.png)

**Comment by WereChipmunk** [comment]
Welp, images are backwards. Top is created rods, bottom is the loop.

**Comment by WereChipmunk** [comment]
Third picture, an amazing discovery while I played with this. You can stick entire VENDING MACHINES into this.

![infinite metal3](https://cloud.githubusercontent.com/assets/5678688/7175787/76573448-e3e6-11e4-9c17-1837e8d7c627.png)

**Comment by Jordie0608** [comment]
![gif](https://cloud.githubusercontent.com/assets/4343468/7175896/af3d6964-e45c-11e4-80a5-e3aea620b2f8.gif)

**Comment by Lumipharon** [comment]
Spinning is rediculous, but for disposal things, it's pretty funny.

**Comment by Miauw62** [comment]
anybody remember when this would happen with all floors?
except it produced floor tiles, which have p high throwforce.

**Comment by Chocobro** [comment]
this vending machine shit is the funniest thing i've seen all week

**Comment by Incoming5643** [comment]
Anything you can make mobile can fit in one of those standing disposal vents and it is indeed the best thing ever.

**Comment by xxalpha** [comment]
That vending machine juggling is the best thing.

**Comment by drynwyn** [comment]
I want to see this done with a mech.
