### ISSUE TITLE
bugs regarding messages

### ISSUE THREAD

**Issue by g1852505** [tgstation/-tg-station#9010]
Alt+click a pile of garbage in Cargo on the conveyor belt returns the message "you cannot do that while restrained"

Received random messages during gameplay such as "wwhy shrek piss"

**Comment by Dorsisdwarf** [comment]
Random messages may have been admins. They can subtle or global narrate things

**Comment by g1852505** [comment]
admin said it wasn't for me

**Comment by Miauw62** [comment]
i swear if somebody coded "wwhy shrek piss" into the game

**Comment by phil235** [comment]
What was the format of those random messages? Did someone say it? Was it a specific color?

**Comment by PKPenguin321** [comment]
>wwhy shrek piss

bug of the year

**Comment by optimumtact** [comment]
shrek is not a word found in the codebase

**Comment by Cheridan** [comment]
@g1852505 Did you happen to be restrained at the time? :V

**Comment by Cheridan** [comment]
Well barring further response from the issue creator I'm putting this down as user error.
