### ISSUE TITLE
If you put a facehugger in your cargo hold in a ripley it can facehug you when you get in your ripley

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#9020]
Science bitch

**Comment by RemieRichards** [comment]
totally a feature.

**Comment by Kromgar** [comment]
I fucking lost it when I got in my ripley and I got hugged. It was so fuckign funny

**Comment by RemieRichards** [comment]
I mean, it makes sense doesn't it? You put a squirmy little bugger in your cargo hold and he decided to take your seat in the ripley and jump you, Haha.

**Comment by Kromgar** [comment]
I didn't expect it it didn't attack me when I was in my hardsuit

**Comment by WJohn** [comment]
I miss being able to load space carp into your ripley, only to have it eat you from the inside.

**Comment by Chocobro** [comment]
related #7354
