### ISSUE TITLE
Infinite Explosions

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9029]
I'm hesitant to post this due to the massive grief and server crashing potential this has,but...it needs to be posted.

This is a priority #1, HIGHLY CRITICAL, server ending scenario bug.

If black powder is dumped on the floor, then  acted upon by an external explosion, it will explode properly...then the explosion it generates will cause itself to explode---again and again and again, infinitely. Once set off, it will never end, as the reagent inside a chemical pile are never cleared upon the explosion.

This just needs to be changed so that when ex_act_on is called on a chemical pile (or anything with black powder) it creates the explosion AND clears all the black powder as if the chemical reaction had taken place.

This will still allow for the unique interaction of black powder without it exploding literally infinitely.

@Iamgoofball 
@Anyonewhocanhandlethisbecauseitssocritical

**Comment by Menshin** [comment]
Reminds me of the meteors colliding with themselves due to failed qdel.

Either the black powder fails to qdel (probably because of a proc always being active after the qdel call) or the cleaning part is simply borked.

May be a dupe.

**Comment by Iamgoofball** [comment]
so THIS was how they did the infinite explosion

i'll fix it, hold on.

**Comment by Fox-McCloud** [comment]
don't think so, Menshin.

https://github.com/tgstation/-tg-station/blob/master/code/modules/reagents/Chemistry-Goon-Pyrotechnics.dm#L182

There's nothing to clear the reagents when the explosion occurs.

**Comment by Menshin** [comment]
Yeah, nothing elaborate here, you rightly pinpointed the problem.

**Comment by Iamgoofball** [comment]
Yeah, probably were big enough. I was doing big explosions, which would explain it.

Fix was merged.

**Comment by Miauw62** [comment]
this is a dupe, i posted this before.
