### ISSUE TITLE
Spessmen bugs

### ISSUE THREAD

**Issue by Forest3r** [tgstation/-tg-station#9041]
Spacesuit helmets aren't graphically showing up. Player's heads become bald (no hair at all, not even eyebrows.) I was playing on SS13 earlier this day, around 2am EDT, 4/18/2015. While around 10am, upon trying to play the game, this occurred. Also, tracking beacons and requests consoles were, once again graphically, becoming monkeys. At this point, dream seeker, I believe, froze. Upon re-connection, the tracking beacons and requests consoles were once again their respective sprites. While, but the continuation in freezing led me to stop playing. At 12am I started playing again, no freezing for awhile. The spacesuit helmets still made people bald. And, when it froze again, I was observing the engineering area, when some doors there became pianos. I have no idea what is possibly causing this so. Have fun?

**Comment by RemieRichards** [comment]
Just popping in to say that nobody else was having these issues.
So it's probably on your end.

**Comment by Miauw62** [comment]
This is almost certainly a client or serverside issue, not related to our code.
Try clearing your cache or telling the server host to do a clean compile.
