### ISSUE TITLE
Sounds on the shuttle are cutting out or not playing at all

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#9042]
see title, sounds on the shuttle or probably pods are cutting off or just not playing

**Comment by Nanotransistor** [comment]
I noticed the same thing but in the brig. Thought there was something wrong with my speakers.

**Comment by RemieRichards** [comment]
Were they pressurised?

If pressure was missing then the sounds dont travel.
That's how sound works.
Part of a thing I added a while back where sounds' volumes are based on the air pressure around them.

**Comment by PKPenguin321** [comment]
I was there, the sounds stopping weren't cutting out the way they would with no pressure, they would just cut out before finishing. Like, the clown's horn, you know how it goes "hu-hunk"? It would go hu-h-- and just stop really abruptly.

**Comment by Nanotransistor** [comment]
Yeah even the station announcements were cut. Or the AI's words.

**Comment by WJohn** [comment]
This is actually happening throughout various rounds, and seems to manifest quite late in the game. It's like something is refreshing every second and cutting out all sounds. Seems pretty random when it happens.

**Comment by Miauw62** [comment]
this seems to have stopped happening?

**Comment by WJohn** [comment]
No I just experienced it earlier today.

**Comment by RemieRichards** [comment]
https://github.com/tgstation/-tg-station/issues/10077 is a better report.
