### ISSUE TITLE
Ayyliens aren't immune to disease

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#9043]
And they've got a gland that makes a person a carrier for a disease. You see where this is going, don't you?

**Comment by WJohn** [comment]
For a second I thought you meant xenos. We should probably refer to them as greyliens or just call xenos xenos more often.

**Comment by Incoming5643** [comment]
I've been calling the ayliens

**Comment by RemieRichards** [comment]
It has two Ys, Ayyliens

**Comment by Anonus** [comment]
ayy

**Comment by Alek2ander** [comment]
Ayyliens are also not immune to slimes. And one of the glands makes people vomit slimes every minute. And there's an above-zero chance there will be a slime in the ayylien base before they can send the person back to the station.

**Comment by Incoming5643** [comment]
Seems like it'd be easier to just give something to the ayylien teleporter that "activates" the glands on the return trip and have them not work before then.

**Comment by buttsmcgee** [comment]
>From the moment the invaders arrived, breathed our air, ate and drank, they were doomed. They were undone, destroyed, after all of man's weapons and devices had failed, by the tiniest creatures that God, in His wisdom, put upon this Earth. By the toll of a billion deaths, man had earned his immunity, his right to survive among this planet's infinite organisms. And that right is ours against all challenges, for neither do men live, nor die, in vain. 

Feature :^)

**Comment by Supermichael777** [comment]
they give us ayylien aids and are surprised when they get infected?

**Comment by Xhuis** [comment]
Isn't this fixed now?

**Comment by astralenigma** [comment]
This should be fixed by #9115 unless something got botched.

**Comment by AnturK** [comment]
Yeah,  i forgot to put fixes xxx into my pr for autoclosing back there. Sorry for that.
