### ISSUE TITLE
Abductor disguises can be easily seen through via examine

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9045]
Examining an abductor that is disguised will tell you what they're actually wearing, like an agent vest.

![abductor](https://cloud.githubusercontent.com/assets/5659269/7217115/20fed908-e5e7-11e4-8070-4b4b653bd8fd.png)

**Comment by Dorsisdwarf** [comment]
Not a bug, requesting appropriate tagging

**Comment by AnturK** [comment]
Yeah that's intended, they're not meant to be perfect disguise
