### ISSUE TITLE
My abductor squad camera console can only track the wrong abductor soldier guy

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#9046]
Just had an abductor round where my scientist could not track me, but the other abductor. Made it quite uncomfortable for us, as we had to rely on AI cameras.

We also had only a shitty camera console, when I was made abductor in another round via admin-button, we had a fancy "AI-like" camera console, not that shitty "security-like" camera console.

**Comment by GunHog** [comment]
It appears that we may have been the second Abductors, and the Phi ones overwrote your vest camera, and probably gave us the cruddy normal security console, due to mapping issues. (I was your Scientist)

**Comment by AnturK** [comment]
This can be closed, this is irrelevant since advanced cameras.

**Comment by tkdrg** [comment]
k
