### ISSUE TITLE
RPD shows up twice in Autolathe

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9049]
![rpd](https://cloud.githubusercontent.com/assets/9714964/7217269/165c1122-e5d4-11e4-980d-06be3f8d58dd.png)

No idea what even caused this

Search RPD in Autolathe

**Comment by Thunder12345** [comment]
I can only see one copy of it, had anything strange been done to the lathe that round?

**Comment by Jordie0608** [comment]
Can't reproduce with a normal autolathe; something weird must've happened to it.

**Comment by newfren** [comment]
I can reproduce this with all the hacked options.

While Hacking, first pulse with a multitool to turn off the blue light then use wirecutters immediately on the same wire, i.e. before the light turns off. This will produce doubles of all the hacked items. If you allow the light to turn off after multitooling or simply wirecut the correct wire without using the multitool this won't happen.
