### ISSUE TITLE
Staff of Animation causing empty wands to work again

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/-tg-station#9056]
Using a staff of animation on an empty wand that is on the ground results in the newly animated wand firing wildly as if it hadn't used it's charges.

**Comment by WJohn** [comment]
Does this work with guns, too? Projectile or energy? This ought to be tested.

**Comment by GunHog** [comment]
Was this not intended?

**Comment by Jordie0608** [comment]
This got fixed at some point
