### ISSUE TITLE
Being stunned as a borg causes temporary blindness, deafness and muteness.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9061]
If you're stunned by anything as a borg (space carp, alien hit, emp, flash) you become temporarily deaf, blind (one square) and unable to speak. This lasts longer than the stun duration and prevents any attempts to call for help. It also happens if you run out of charge. (Deafness and being mute were normal there.)

This makes subverting or destroying borgs fairly trivial and in most cases no one will even know it happened. I looked in the PR history and couldn't find anything that mentioned this change so I think it might have been a side effect of something else.

**Comment by Miauw62** [comment]
It's not really stunned, you fall unconcious and if you hear anything it gvies the "... You can almost hear somebody talking ..." message.

**Comment by phil235** [comment]
>This lasts longer than the stun duration and prevents any attempts to call for help. It also happens if you run out of charge. (Deafness and being mute were normal there.)

This is the real bug, and it's fixed. Not being able to see or talk while stunned as a borg is intended.
