### ISSUE TITLE
Can't clean graffiti on walls.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#9063]
Fairly self-explanatory. You can shit up all the walls in the station with "fukc lizard" and nobody will be able to do shit about it.

**Comment by RemieRichards** [comment]
Pretty sure you can, as in that RPRev round I talked about I went around spraying graffiti all over the walls. Only to walk back around that corridor clean of my art.

**Comment by Supermichael777** [comment]
try soap?

**Comment by xxalpha** [comment]
Maybe not with the common means, but I think grenades clean walls.

I didn't even know you could crayon the walls.

**Comment by Jordie0608** [comment]
You can clean walls with a mop or soap.
