### ISSUE TITLE
Washing shoes with a clown stamp does nothing, Noslips can not be recolored in the washer.

### ISSUE THREAD

**Issue by Man-Shroom** [tgstation/-tg-station#9066]
What it says on the tin. Noslips one may be intentional for balance.

**Comment by bgobandit** [comment]
rip being cluwne pranking people by giving them squeaky black shoes

**Comment by Thunder12345** [comment]
Noslips are /shoes/syndigaloshes
Brown shoes are /shoes/sneakers/brown

Should probably be a child of brown shoes, to allow recolouring. Right now this lets you wash every pair of brown shoes with a crayon and lynch anyone whose shoes don't change colour.

**Comment by TheVekter** [comment]
I've been meaning to port syndie shoes to a child of sneakers anyway. Gotta figure out how to make it so you can wash them and not lose noslip...

**Comment by TheVekter** [comment]
Looking at this now. TIL noslips have a different description than normal brown shoes, is that intentional? It says "A pair of brown shoes. They seem to have extra grip."

**Comment by TheVekter** [comment]
@Man-Shroom What did washing a pair of shoes with a clown stamp do before?
