### ISSUE TITLE
Shadowlings can lose hatch verb.

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#9067]
A shadowling died, and got cloned while some others incinerated his corpse. He thus lost the hatch verb.
Hatch is also not a spell/proc holder and it probably should be so this can at least be worked around if it occurs again.
@xhuis

**Comment by Xhuis** [comment]
Likely because it's a mob proc, if anyone wants to fix it they can but otherwise it'll take me a bit to get around to it
