### ISSUE TITLE
you can't toggle a welding gas mask while buckeled to a chair

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#9071]
I was not cuffed at the time. seems weird.

**Comment by Boggart** [comment]
You also can't toggle suit sensors or put away/take out water sprayer/atmos foam packs.

**Comment by buttsmcgee** [comment]
The nozzle thing is especially shitty.

Sometimes you just want to roll around on the pussy wagon with the backpack water tank, but you have to get off every time you want to toggle it.

**Comment by WJohn** [comment]
Yeah your ability to do anything while buckled in is weirdly restricted.

**Comment by Aranclanos** [comment]
buckeleled!

**Comment by RemieRichards** [comment]
There's probably one or two ```if(M.buckled)``` that could do with being ```if(M.buckled && M.buckled.buckle_requires_restraints)```

**Comment by Jordie0608** [comment]
@kingofkosmos

**Comment by kingofkosmos** [comment]
What? Do I fix it?
