### ISSUE TITLE
Station Wide Plasma Fires are crippling the server everytime

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#9072]
Good god its horrific

**Comment by callanrocks** [comment]
You could have stopped this.

**Comment by optimumtact** [comment]
Solution: Do not let the AI flood plasma

**Comment by Kromgar** [comment]
It didn't used to be this bad

**Comment by optimumtact** [comment]
Atmos run speed has been turned up so atmos effects will be more noticeable

**Comment by Jordie0608** [comment]
@MrStonedOne

**Comment by chimersable** [comment]
Is there a easy way to turn it down? I think the new atmos settings are causeing lag on my server.

**Comment by Marflowerose** [comment]
If you want faster atmos with less lag, use the room based atmos system rather than tile-based. Though I imagine it has it's own problems maybe.

**Comment by Miauw62** [comment]
"maybe"

>have to redesign entire station to change all airlocks to be "real" airlocks
>accidentally open door to a room that is on fire, room you are in now is also on fire

etc
