### ISSUE TITLE
Trapped in the abductor's room

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#9075]
Quite the situation, an ayylien abducted me into his room by sending me to sleep, I woke up in the middle of the operation and killed him. I ended up trapped in that room with no way out.

**Comment by GunHog** [comment]
This is why you do not tango with a giant spider. Is the teleporter console locked?

**Comment by Kromgar** [comment]
It's an alien spaceship did you think you could operate it?

**Comment by Anonus** [comment]
If you robust the aliens you're still in an alien ship, and are, in fact, trapped in a ship you can't operate.

**Comment by WJohn** [comment]
Yeah but come on, we're robust spessmen here, we can all operate any machinery and perform surgery as the janitor. Besides being trapped in the tiny alien ship with nothing to do is not fun and seems like an oversight.

**Comment by Jordie0608** [comment]
@AnturK

**Comment by RemieRichards** [comment]
Perhaps open the console to all users when all aliens on the ship have died?
That way you can escape if you robust them both, but you cant just get up and walk out with 2 ayyliens staring at your ass as you leave.

**Comment by Dorsisdwarf** [comment]
Maybe you shouldn't robust the aliens when you're trapped on their ship.

**Comment by PsiOmegaDelta** [comment]
Have the ship engage self-destruction protocols when all aliens are dead, problem of being trapped solved.

**Comment by Cheridan** [comment]
^ good solution

**Comment by astralenigma** [comment]
The Agent cannot operate the science gyzmo so I say that if the scientist dies the shuttle should self destruct and the agent should be gibbed or something since he had lost it's purpose.

**Comment by Iamgoofball** [comment]
question: why can't agents operate the science shit?

that seems counter productive, them taking turns going on station sounds like fun.

**Comment by AnturK** [comment]
Because having stun-resistant-armed-teleporting-agent who can send people back himself is no fun for either side. Role swap seems more effort than it's worth.

I'll try to do something about this issue in  the update.

**Comment by Iamgoofball** [comment]
@AnturK Well, add some way for them to be able to take turns doing agent or science if they want to take shifts, as what if one guy wants to be agent and the agent wants to be scientist?

**Comment by astralenigma** [comment]
Honestly as I see the concept being able to change the job seems prone to cause problems what would be a good idea instead is separating the scientist and agent as 2 different flags so people can choose to only be Scientist or agent when they are spawned.

**Comment by Amnestik** [comment]
>Have the ship engage self-destruction protocols when all aliens are dead, problem of being trapped solved.

>punishing people for being robust

pls no

**Comment by Jordie0608** [comment]
A way to escape the ship was added
