### ISSUE TITLE
Wizard den lacks comms

### ISSUE THREAD

**Issue by Dicks1** [tgstation/-tg-station#9077]
Wizards used to be able to hear every channel from the den like nuke ops could but since the new shuttle it was removed.

**Comment by Incoming5643** [comment]
I've wanted to readd this for a while because it also allows for pre insertion RP/shittalking.

How attached at people to the broken ship design these days?

**Comment by Dicks1** [comment]
Can't you just add a wall radio like what used to be there?

**Comment by Incoming5643** [comment]
well yeah, I was just curious

**Comment by Iamgoofball** [comment]
@Incoming5643 i don't even know why the fuck there's a broken ship design on the wizard shuttle, who even added it

it looks like shit

**Comment by TheVekter** [comment]
@Iamgoofball was added by steelpoint

I'll look at fixin' this.
