### ISSUE TITLE
Mulebots are driving around unable to return home

### ISSUE THREAD

**Issue by Blonkz** [tgstation/-tg-station#9081]
Two shifts in a row the mulebots where driving around crazedly. From start of the shift. I was unable to send them back home, via PDA or by manual input.

**Comment by Anonus** [comment]
This seems to happen when the AI calls mulebots to a location, so @GunHog

**Comment by GunHog** [comment]
It is a radio code issue, probably related to filters. Do not expect a fix to this in a timely manner. Radio code is a monster, and it is difficult to track issues with it. Give me as much information as you can - I am not getting reliable reproductions of this on my test code.

**Comment by Anonus** [comment]
I was using the call button to send mulebots places, with all of their settings set to default at first, and after sending them places a few times, one of them stopped trying to automatically return home even though that setting was on.
After that, I turned automatically return home off, and both wouldn't return home when I used the return home button. The initially affected mulebot didn't seem to have a home set at all, and setting a home for it initially didn't work, though it did work after some time later.

**Comment by Anonus** [comment]
Oh, and the important thing; I was doing this on Metastation.

**Comment by Miauw62** [comment]
Happens on box too. The MULEs will just roam around the station all round long.
Can confirm that radio code is a monster too, which is why I moved tcomms code off of it.

**Comment by Anonus** [comment]
Okay no the above is all a different bug, but it looks like when that happens the mulebots are getting their target set to a hallway marker somehow.
