### ISSUE TITLE
Nicotine overdose is rather deadly

### ISSUE THREAD

**Issue by Braincake** [tgstation/-tg-station#9088]
Chainsmoking (as in, consuming a constant stream of nicotine) seems to cause hilariously damaging overdose effects after barely a few cigarettes.

In particular: halfway through the third cigarette, I got spammed with a few dozen "You're smoking too much" messages, puked on the floor a few times, and died. I know smoking kills, but this seems like a slightly overdone aesop.

To reproduce: Chainsmoke.
What I'd expect: Slight overdose effects.
What really happened: Death.
Server revision: b65595a0f1730dc77c3ab787f0243083eeded23d
Other: Guessing it has something to do with the reagent changes from the 20th, since I could chainsmoke just fine yesterday.

**Comment by Boredone** [comment]
So, this was likely because when reagents got changed, the metabolizing thing got removed, so I think stuff never left your body. Otherwise, it actually nerfed nicotine overdose by cutting the damage in half, I think.

**Comment by Miauw62** [comment]
nicotine shouldnt be a thing in the first place

**Comment by Marflowerose** [comment]
I think you get more nicotine by lighting one, smoking if for a minute, stomping it, lighting new one and repeating. I didn't check chem amount with analyzer but seemed to give OD much faster than waiting cig to run out before lighting a new one. This was also before the reagent change and when the glorious *fart was a thing.

**Comment by GunHog** [comment]
Smoking is bad for you. I believe this is working as intended.

**Comment by Niknakflak** [comment]
Gunhog, even like 50 cigarretes right now wont kill you.  It may give you cancer in the future and that will kill you, but 3 cigarretes should do nothing.

**Comment by pudl** [comment]
this IS working as intended, because goof is an idiot. you can survive the whole round on goon without stopping your smoking even once.
