### ISSUE TITLE
Revenant Explosions

### ISSUE THREAD

**Issue by AlexanderUlanH** [tgstation/-tg-station#9092]
Revenants have a lives system which is supposed to give them some second chances if they mess up, but they inherit their ex_act from simple_animal, meaning they get gibbed regardless of stored essence or lives if they're blown up.  It doesn't make sense that a revnant would be damaged by bombs in the first place, but they should at least have the benefit of their remaining lives if they would be killed in an explosion.

**Comment by Xhuis** [comment]
Will look into it
