### ISSUE TITLE
You're able to get up while cuffed during surgery.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9094]
This had been a old problem for awhile now. If you type rest while on a surgery table you will stand off, regardless if you're cuffed or not. Best thing to do here is to make so you can buckle cuff someone, Otherwise the patient will constantly get up unless stunned. This is seem most during abductor rounds.

**Comment by Dicks1** [comment]
Abductors can put people to sleep though so this shouldn't be a problem for them.

**Comment by PKPenguin321** [comment]
if you're doing cruel and usual things on them like gender changes, use sedative like the N2O tank
if you're force-borging them, kill them, since they'll die once the brain is out
if you have a ghetto surgery bay and don't want to murder them but don't have access to stuns, then make a bed with two metal and bucklecuff
>Abductors can put people to sleep though so this shouldn't be a problem for them.

this is not an issue

**Comment by Durkel** [comment]
The point is that you're already cuffed, you're already fucked. You shouldn't be able to get back up constantly.

**Comment by PKPenguin321** [comment]
If they're already cuffed it shouldn't be hard to kill them or sedate them, either

**Comment by RemieRichards** [comment]
you could give the operating table ```can_buckle = ``` and ```buckle_requires_restraints = 1```

**Comment by callanrocks** [comment]
Being cuffed doesn't mean you're fucked, it just means its time for a challenge.

**Comment by PKPenguin321** [comment]
I still think this is a non-issue, having a chance to escape forced surgery if your captor isn't competent enough to subdue you properly isn't a bad thing we should remove.
