### ISSUE TITLE
brainless overlay missing

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#9096]
![brainless overlay](https://cloud.githubusercontent.com/assets/701959/7243562/e4b59eae-e7a4-11e4-9693-fc0096354e6d.png)
see image.
The description text of the human in the floor says that his brain is missing, but the brain overlay isn't showing up.

**Comment by callanrocks** [comment]
Is it hidden under his hair?

**Comment by Aranclanos** [comment]
I don't know

**Comment by phil235** [comment]
Did someone witnessed this bug recently or is it fixed?
