### ISSUE TITLE
cyborg reset/restart module boards have confusing  names

### ISSUE THREAD

**Issue by Aranclanos** [tgstation/-tg-station#9098]
Both reset and restart modules boards have almost the same names, but they accomplish completely different tasks. It's confusing.

**Comment by Miauw62** [comment]
i would like to note that some people also still print "custom" boards because they think they're similar to freeform boards.

**Comment by ike709** [comment]
whats the difference...? ._.

**Comment by TheVekter** [comment]
Restart boards reboot a cyborg after they get beat to hell and "shut down".
Reset boards reset a borg's module to the Standard one so they can choose a new one.

Easy to fix, I'll fuck with it in a minute.
