### ISSUE TITLE
Nicotine lasts forever

### ISSUE THREAD

**Issue by whodaloo** [tgstation/-tg-station#9099]
Smoke a cigarette, enjoy getting spammed with messages for the rest of the shift.  You'll always have however much nicotine you took in, it doesn't metabolize.  I'm not sure if all stuff you smoke stays in your system forever, but nicotine def. does.

**Comment by Iamgoofball** [comment]
A fix for this was merged.

**Comment by whodaloo** [comment]
oh my bad.
