### ISSUE TITLE
Walls can not be deconstructed.

### ISSUE THREAD

**Issue by Summoners** [tgstation/-tg-station#9100]
You can get a wall to girder form but you can never remove the girder, when using a welder on it the game will tell you "You start to disassemble the girder..." yet it never finishes and never deconstructs.

This really needs to be fixed as it makes walls buildable but not deconstructable.

**Comment by WJohn** [comment]
@kingofkosmos oh god fix it fix it panic

**Comment by kingofkosmos** [comment]
WTF
