### ISSUE TITLE
AI Hologram becomes a Shadowling

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9101]
...If the selected person is in fact, a shadowling, hatched or not.

**Comment by Iamgoofball** [comment]
Ahahahahhahahahahahha

Feature/10 DNF

**Comment by pudl** [comment]
if anyone fixes this, i'll flip shit

**Comment by Xhuis** [comment]
So you're telling me that the hologram is a hatched shadowling, regardless of the hatched status of the shadowling? There's no way that should be occurring, so I'm calling it a feature.

**Comment by SconesC** [comment]
@Xhuis Yep, no idea what could cause it but it happened ONCE. Unable to reproduce. 

Hilarious feature, right?

**Comment by Xhuis** [comment]
Totally. I guess we should close this now because it isn't a bug.

**Comment by SconesC** [comment]
Yep.

**Comment by Miauw62** [comment]
what no this can be used to metagame.

**Comment by Dorsisdwarf** [comment]
add Edge Case because it doesnt happen every time reportedly.

**Comment by phil235** [comment]
can't reproduce, whether I'm creating the crew hologram icon before or after hatching, I still get the picture from crew records and not a shadowling (although I only tested with admincreated shadowling).

**Comment by Dorsisdwarf** [comment]
Will be closed if nobody finds evidence of this happening in like a month. Sometimes BYOND just shits itself.
