### ISSUE TITLE
blood consumes plasma

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9102]
Trying to mix blood and plasma will cause a reaction that consumes the plasma while leaving the blood behind. Any amount of blood can consume an infinite amount of reagent plasma without any byproduct

**Comment by Lumipharon** [comment]
it's for virus mutation. Plasma adds a (usually) level 5 or 6 symptom to the virus. Of course if there is no virus in the blood to start with... it gets wasted.

**Comment by Incoming5643** [comment]
not a bug then, I guess
