### ISSUE TITLE
Picking up a sword made me fly into the ether

### ISSUE THREAD

**Issue by Auron1213** [tgstation/-tg-station#9104]
Sorry if this isn't completely correct, but
image:
![poofd](https://cloud.githubusercontent.com/assets/10902851/7259183/950d17de-e82f-11e4-9b22-7ead2396d88b.png)
 
I picked up a sword a cultmember had. A station admin affirmed I was no longer on the game map. We play on a fork of /tg/ but I don't believe we've modified cult in any way.

Trigger:
Picking up a black, glowing sword (was in brig at the time)
Effect: 
Disappeared from the map entirely.

**Comment by SconesC** [comment]
You picked up a cult sword and vanished into the nothing zone?

What server are you playing on?

**Comment by Auron1213** [comment]
Server is irrelevant as we did not modify cult in any way, it should be identical there as here.
As well, we haven't overhauled anything major to /tg/.

**Comment by SconesC** [comment]
Are you able to recreate this?

Server is relevant so I can get the branch and see if I can recreate it

**Comment by Auron1213** [comment]
Alright, branch is
https://github.com/Riesen/-tg-station
I haven't tried recreating it yet

**Comment by tkdrg** [comment]
This hasn't happened in months, closing unless we get steps that can reproduce it consistently..

**Comment by duncathan** [comment]
>cult sword flinging the bearer into null space

At least it was thematic
