### ISSUE TITLE
Riot Shotgun Inhand has brown

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9109]
Probably a holdover from when we used the nice wooden-stocked shotguns (Which I miss)

Not congruent with our current tacticool grey shotguns

**Comment by GoonOnMoon** [comment]
Doesn't appear to have an inhands icon as of now.

**Comment by phil235** [comment]
All shotguns (double barreled, improvised, combat, riot) use the same inhands. To be honest I don't think this is an issue, you can barely see the brown pixels and having an inhand for each type wouldn't be worth it.

**Comment by WJohn** [comment]
Is there a tag for "causes more problems to fix"?

**Comment by Cheridan** [comment]
Not really an issue that needs to get singled out, we have very many inhands that are not really accurate.
