### ISSUE TITLE
Unpinned guns can work in turrets

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#9111]
I put a xray laser in a portaturret and built it
It shot perfectly even though the xray laser didn't have a firing pin.

**Comment by PKPenguin321** [comment]
The real question is if prying the gun back out yields a pinned gun

**Comment by Iamgoofball** [comment]
honestly I'd say this is valid

if prying the gun back out gives a pin too the pin adding should be fixed but considering you're sacrificing mobility and pinning it down in one spot I'd say it's valid salad.

**Comment by Jordie0608** [comment]
It doesn't, this is fine.
