### ISSUE TITLE
Ripley drilling itself

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#9114]
If you are /somehow autistic enough/ to drill space, if you are on a space tile, in a ripley, you end up drilling yourself.

**Comment by kevinz000** [comment]
crap forgot desc let me fix that

**Comment by xxalpha** [comment]
Why is this a bug? Mobs can all attack themselves, why not mechas?

**Comment by Dorsisdwarf** [comment]
The bug is that you can't drill yourself, you drill space underneath you and that drills you
