### ISSUE TITLE
Second time Last Resort = NPC Headslug

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#9116]
Well, basically. After you used last resort, entered a new body, and revived. The second time you use last resort, it makes a NPC Headslug instead of putting you in control of it.

**Comment by Miauw62** [comment]
why do you keep dying in some of the most counterintuitive ways firecage

**Comment by Incoming5643** [comment]
he obviously had a plan to slowly gib the entire crew by head slugging each and every dead body.

Is there any other differences between the first and second times you slugged you noticed?

**Comment by Firecage** [comment]
Well, the first time I was standing up straight, the second time I was laying down on the surgery table?
Thats the only difference.

**Comment by Incoming5643** [comment]
How long ago did this happen? Is there any chance #9052 wasn't live at the time. Because show server revision is broken I couldn't tell you when it went live, but probably only since the last server update, whenever that might have been.

**Comment by Firecage** [comment]
It happened today. Like the round before I made this issue. So 8 hours ago.

**Comment by Firecage** [comment]
@Incoming5643 Welp, seems like it still happens.

**Comment by Ausops** [comment]
Okay, tested it out a bit.

For whatever reason, it'll spawn a NPC headslug if you're lying down on the floor but not when you're standing up.
