### ISSUE TITLE
Follow has a bunch of inactive camera eyes.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9119]
![](http://i.imgur.com/1NycFz8.png)

This was during a nuke op round, they don't actually do anything. Taken on 22/04/2015.

**Comment by Incoming5643** [comment]
they're hiding in the advanced camera consoles in the mothership, they probably shouldn't be generated unless they're actually being used

**Comment by KorPhaeron** [comment]
@WJohn 

This got fixed please close it
