### ISSUE TITLE
Revenant Seed of Draining is Broken

### ISSUE THREAD

**Issue by Tyrranatar** [tgstation/-tg-station#9121]
According to the wiki, Seed of Draining is a revenant spell that's supposed to give the revenant 120E over a steady period of 2 minutes. However, you actually get far below that. When I tested it on a private server, it cost 20E to cast and gave you back a measly 19E, meaning you actually lose essence when you use it. In it's current state, seeding is completely useless.

How to reproduce: Start up a server, spawn a revenant mob, possess it, spawn in a human, then try seeding it.

Note that this issue is being reported before Revenant Update II has been merged.

**Comment by Jordie0608** [comment]
@xhuis

**Comment by AlexCrimson** [comment]
I could be wrong, but im pretty sure the Revenant wiki is out-of-date at this point. Xhuis did mention he nerfed Seed of Draining. Still could be bugged though.

**Comment by Tyrranatar** [comment]
That certainly would explain why it's not 120E. Still, if you get less than you put in, it's useless.

**Comment by Anonus** [comment]
It's gone this can be closed.
