### ISSUE TITLE
Teleporting as abductor to engineering as a chance of going to the singuloth area

### ISSUE THREAD

**Issue by astralenigma** [tgstation/-tg-station#9123]
While using the teleport of the abductor ship to go to Engineering there's a chance of arriving at the singularity's space, instead of the safe area of engineering.
It leads to a fast death of any abductor if the singularity is set up.
The chance seems pretty high so just spamming teleport to engineering should reproduce the problem easily.

**Comment by GunHog** [comment]
You can also get teleported into a slime or containment pen if you choose Xenobiology!

**Comment by RandomMarine** [comment]
And the burn chamber in toxins. Or one of the air tanks in atmos. It's a consequence of an area-based teleport. Wizards have been affected for a long time by this.

**Comment by astralenigma** [comment]
But the engineering one could probably be easily fixed by making the singularity not part of engineering, no?

**Comment by AnturK** [comment]
This will be mostly non-issue after #9115

**Comment by astralenigma** [comment]
@AnturK Next time use "Resolves #9123" to close issues when you make a merge.
