### ISSUE TITLE
Slime species mutation can make you the invisible man.

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#9127]
/datum/species is not blacklisted.
![2015-04-23 14-14-52 yogstation 13 99 lagfree custom map neckbear station iii](https://cloud.githubusercontent.com/assets/5909770/7295939/a151a786-e9c3-11e4-89ac-a4ed4a7f83a5.png)

Also as was already reported multiple times being a slime person at any point in your life makes you die if you turn into anything else due to 100u of slime jelly in your reagents.

**Comment by Miauw62** [comment]
This is a duplicate, but we did not know the cause. Thanks for reporting this.
