### ISSUE TITLE
Door shock cap is gone.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9132]
You can take well over what used to be the 70 damage cap by touching the door just once.

**Comment by phil235** [comment]
Can confirm. I was an ailen queen at full health, one door shock and I was in crit.

**Comment by Lumipharon** [comment]
I reported this a while ago, but was told that there never was a cap or something, but it could only 1 hit dunk you if it targetted your body, or something, since the limbs are capped at 70 odd damage.

**Comment by WJohn** [comment]
How the hell does it even target your torso or head? You're supposed to be touching the door with your arms.

**Comment by AlexanderUlanH** [comment]
Lately I've been seeing shock damage distributed between limbs, so that could be the reason doors are now critting.

**Comment by PKPenguin321** [comment]
This has always been the case, and I always kinda thought it was pretty dumb that limbs were capped for damage in the first place. Doors never had a shock damage cap, it was just that most of the time they would shock limbs, meaning you'd usually never take more than 75~ damage at a time.
I have no problem with it targeting the torso or head, but maybe an actual cap on shock damage would be nice.

**Comment by optimumtact** [comment]
The real question is do we consider it a bug, or should a high power situation cause serious damage?

**Comment by PKPenguin321** [comment]
imo extremely high power in the grid shouldn't be able to instacrit but it should do some *nasty* damage
maybe put an actual cap at like 85 burn that's spread out on the body instead of all in one place or something

**Comment by Marflowerose** [comment]
Extreme high power shock should crit instantly but treshold for what constitutes for extreme high power should be adjusted. Only if all solars and singulo (at stage 3+) are wired to grid should there be enough juice to melt faces, though this is pretty much map-related adjustment. Alternatively, keep the lethal shocking but add an event where player gets message about standing hair etc when next to an electrified door so that there'd be a warning.

**Comment by PKPenguin321** [comment]
Just three solars instacritting people is kinda stupid imo, not to mention singulo outputs several times more than that if it's wired directly in, meaning it'd be extremely easy to set up what is essentially the best damage in the game
Give it a high cap but don't let it instacrit, or if you do let it instacrit make it require something akin to all four solars and a level 3 singulo wired in
