### ISSUE TITLE
Cheesey spraycan tactics in Gang

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9134]
![d10_icon](https://cloud.githubusercontent.com/assets/4176358/7309033/2b13a70c-e9e8-11e4-83f8-d416718d6751.png)

Mildly Cheesy: People can tag the inside of rooms by spraying on the wall from the outside, meaning they never have to actually enter most territory to claim it, as most can be tagged from either the halls or maint.

Dangerously Cheesy: People who know the dark secret of APC areas can tag the ground under an APC to claim a territory without even giving a hint to the people inside they've been tagged.

**Comment by Anonus** [comment]
Area-based anything is bad except for maybe area based teleports(ha ha no those are bad too)

**Comment by Incoming5643** [comment]
Mildly Cheesy can be solved by having spraying on walls actually being on the sprayer's tile pixel shifted to appear on the walls (like what APCs and signs do). As a bonus this would give an illusion of direction to sprays, as you wouldn't be able to see them from the opposite sides of walls.

Can't think of how to fix dangerously cheesy without a major refactor to APCs or a change in gang mechanics though.

**Comment by Ikarrus** [comment]
I was originally going to have them siphon energy off of APCs instead, but since I started developing this someone moved all the APCs to maint. :(

**Comment by Ikarrus** [comment]
and yeah I like what @Incoming5643 said

**Comment by Alek2ander** [comment]
Check for a terminal on the tile when spraying. If there's a terminal, shock the scrub.

**Comment by Ikarrus** [comment]
Yeah that's what I'm going to do. Sans shocking.

**Comment by Alek2ander** [comment]
>having spraying on walls actually being on the sprayer's tile pixel shifted to appear on the walls
Also this. This is good. Also makes them easier to clean, which is a good thing.

**Comment by Miauw62** [comment]
or just make it require multiple tags in an area.
if you're going to make sprays not on walls it'll be really confusing for janitors.

**Comment by WJohn** [comment]
Well this CAN be solved by putting all the APCs back in their actual departments, even if it takes a bit of the "maintenance" out of maint.

**Comment by Ikarrus** [comment]
Dot worry. I have a solution already. terminals/apcs will be forbidden tiles, and you will have to be physically in the area to tag it. So no tagging all the walls from maint.

**Comment by WJohn** [comment]
That works too, I guess.
