### ISSUE TITLE
If you teleport on top of someone as an abductor they immediatly get sent to the shuttle

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#9138]
it hapende landed right on top of the hop.
revision 0611eacfbc273d7a135e3b96d09c4126cd09a017

**Comment by Jordie0608** [comment]
Was this with wizards? If so this is a duplicate of #4214

**Comment by Miauw62** [comment]
didnt i fix teleportation location swapping?

**Comment by Supermichael777** [comment]
its ayyliums was not clear about that

**Comment by Jordie0608** [comment]
Yeah this is the same bug.

**Comment by Dorsisdwarf** [comment]
Totally a feature 10/10
instant telegrab but the scientist doesn't have weapons of his own so you have a chance to get beaten to death by a startled assistant
