### ISSUE TITLE
Balance/Feature Suggestion: Carp Plushie Faction

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9140]
The Spacecarp Plushie is a great traitor item---but not really viable for operatives to use, since the carp will only be loyal to a single person.

I suggest adding the Syndicate faction to plushie carp by default (whether it's "imprinted on" or not); viscerators follow this behavior; I don't really see why space carp shouldn't.

**Comment by AndroidSFV** [comment]
Yes :+1:

**Comment by Marflowerose** [comment]
How would this work with DA or when your target is another traitor or would this only apply to the plushie that operatives can order?

**Comment by Fox-McCloud** [comment]
as far as I know, the only individuals who have the "syndicate faction" are ...syndicate operatives.
