### ISSUE TITLE
defib revive can leave you ghosted while reviving your body

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#9142]
This one may be a bit tricky to reproduce because it needs good timing: If you are dead, ghosting right before you get revived by a defib will revive the body but still leave you as a ghost. You can reenter the body at any time afterwards.

**Comment by phil235** [comment]
that's because the ghost var is defined before the do_after(), so there's a 2 second period where this bug will happen. Just need to move the ghost var after the do_after, easy fix.
