### ISSUE TITLE
Spawning Abductors is broken

### ISSUE THREAD

**Issue by tedward1337** [tgstation/-tg-station#9156]
So far the gamemode only spawns 2 teams of ayyliens instead of 4, and spawning more ayyliens using the create antag button creates two naked humans on the arrival shuttle.

**Comment by WJohn** [comment]
@xhuis

**Comment by Xhuis** [comment]
This isn't my fault, but I can testify that this is what happened.

**Comment by AnturK** [comment]
Hopefully fixed in #9115

**Comment by WJohn** [comment]
Oh right, anturK is the one who made abductors, you made shadowlings, my bad!

**Comment by WJohn** [comment]
This is still broken by the way.

**Comment by AnturK** [comment]
#10129 
Not my fault nobody merges stuff

**Comment by KorPhaeron** [comment]
@Dorisdwarf 

This is fixed
