### ISSUE TITLE
Revenant Bugs

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9158]
@Xhuis

- You can't purchase the overload lighting ability, even if you have more than enough to actually purchase it.
- When you die, it makes you visible and your icon state is set to draining, but the actual src.death() proc is never called--seems sleep prevents it from happening entirely?

**Comment by Xhuis** [comment]
Able to reproduce the overload lighting one, but I have no idea why it might be happening.

**Comment by Fox-McCloud** [comment]
@Xhuis 

If you want to test the death one, locally; just keep var editing your essence to 0--eventually you'll "die", but get stuck in that one loop...forever.

And yeah, no idea why the lighting one is being a butt--it all adds up.

**Comment by Anonus** [comment]
This doesn't happen either close this.

**Comment by Fox-McCloud** [comment]
These were addressed a very long time ago.
