### ISSUE TITLE
'Making' more goliath hides.

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#9162]
Well, don't know if this counts as a balance issue or not, but you can basically get an infinite(or atleast as many lazarus injectors are possible) goliath hides if you keep reviving them and killing them. I take it the same goes for Basilisks and their dropping of diamonds. And I take it the same would go if you revive them with a staff/wand of healing. Infinate goliath plates/basilisk diamonds, which are easily obtainable.

**Comment by phil235** [comment]
Doesn't seem like an issue. The cost of a lazarus injector makes using them to farm goliath hides completely inefficient. It'd be much faster and easier to simply directly hunt goliaths. And for wands, they aren't obtainable in normal circumstances, plus reviving the goliath wouldn't change its faction to yours so you'd still have to fight it.

**Comment by Supermichael777** [comment]
maybe just make revived mobs revert to default alignment if attacked or attack their attacker.

**Comment by Dorsisdwarf** [comment]
No, lazarussed mobs used to only be friendly to miners, and miners would just drag a bunch of goliaths hivelords and basilisks onboard and laz them.

**Comment by Jalleo** [comment]
This is a dupe

**Comment by Dorsisdwarf** [comment]
This is a) not a bug and b) a non-issue. Lazarus injectors are 1000 points, which severely limits any theoretically unfair gain of diamonds or goliath plating.
