### ISSUE TITLE
Magic mirrors can be abused

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9167]
Wizards can set their races to zombie, skeleton, and others in order to avoid the need to breathe, removing bleeding, and giving them spaceworthiness. This seems very unintended. To a lesser degree, abductor species can be used to make invocations silent, although this isn't nearly as bad and I personally like it.

tl;dr https://tgstation13.org/wiki/Secret_mirror_technique is bad

**Comment by Incoming5643** [comment]
It's intended. Wizard robes are already almost spaceworthy and it's actually not that much of a bonus.

The best effects you can really get with the species change are:

*slow healing in light (but you'll get fat): Pod person
*silent casting/team speak with ayypretinces (but no shittalking the crew): Ayyliens
*immunity from bleeding out: A whole bunch of races

I'm never one to call more power to wizards a bad thing, and it's all balanced pretty intensely by that secborg trying to cave your head in the second you land at the station and it becomes obvious you're nonhuman. Also people will call you a power gaming shitlord if you go skeleton without any intention to use it as a gimmick thing, which is its own punishment/reward.

Unless shadowling stuff becomes mutantrace tied (and it should) I don't really see how anything would need to be blacklisted.

**Comment by Incoming5643** [comment]
Also you created that wiki page you cheater 8^y

**Comment by Xhuis** [comment]
All righto. You made this so I see no reason in denying you.

**Comment by Stickymayhem** [comment]
@Incoming5643 

This should probably be reopened

"Also people will call you a power gaming shitlord if you go skeleton without any intention to use it as a gimmick thing, which is its own punishment/reward."

This is a terrible reason to keep something in the game. Using a blatantly overpowered form that literally makes one of the wizard's purchasable weapons obsolete is countered because people will call you shit? No it's terrible. Atmos resistance is a colossal buff and this definitely needs removal. The other species without protection from space are fine.

**Comment by Incoming5643** [comment]
How about this, I'll remove skeletons from the mirror once I finish reworking #7782.

I just want the path to lichmode™ to be there for those that desire it.

**Comment by Stickymayhem** [comment]
Thanks. I'm going to tell people not to do it anymore. It was a bit ridiculous

100% I ded I mad by the way but I did think it was already being addresed.

**Comment by Iamgoofball** [comment]
Or instead we make you only able to choose cosmetic versions so I can be skelebones if I want w/o buffs

**Comment by Stickymayhem** [comment]
Not a bad idea. I like skeletons as a race to use in events and such though.
