### ISSUE TITLE
BoH dedonation while stunned

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#9173]
Aparrently if you try to put one BoH into another and the confirmation appears, even if you are stunned, if you click yes it still makes a singulo.

**Comment by phil235** [comment]
Needs a user.incapacitated() check in https://github.com/tgstation/-tg-station/blob/939b5552add3d0e34634ebafb6448100fbab4627/code/game/objects/items/weapons/storage/backpack.dm#L47

**Comment by TheVekter** [comment]
I'll do it, hang on a sec.
