### ISSUE TITLE
Cybernetic implant injuries do not vanish.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9174]
![](http://i.imgur.com/em55yTw.png)

Steps to reproduce:
1. Perform cybernetic brain surgery on someone
2. Put in nodrop implant
3. Finish with cautery
4. Heal them up with brute pack
5. Observe damage sprite on face remaining

I haven't tested this with other implants or forms of surgery.

**Comment by xxalpha** [comment]
Wrll msybe you should

**Comment by xxalpha** [comment]
So this is because the proc used for healing a limb's damage does not remove overlays and then it breaks the overlay removal.

port baymed when
