### ISSUE TITLE
Movable cursed animal masks.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9175]
You can click drag a cursed animal mask from your face into your hands, however this just gets the mask stuck in your hands, while still having the mask on your face as well. You can repeat the process to have both your hands filled with cursed items ,that you can't remove, and have the same mask still be on your face too.

**Comment by astralenigma** [comment]
Make the mask go to the rest of the body and make it a feature.

**Comment by Wolfie13** [comment]
Cannot Reproduce

**Comment by Razharas** [comment]
2 people said they couldnt reproduce this

**Comment by WJohn** [comment]
Can't do it either.
