### ISSUE TITLE
Napalm/Hooch recipe conflict

### ISSUE THREAD

**Issue by babinsquared** [tgstation/-tg-station#9184]
Hooch
required_reagents = list ("sugar" = 1, "ethanol" = 2, "fuel" = 1)

Napalm
required_reagents = list("sugar" = 1, "fuel" = 1, "ethanol" = 1 )

Trying to mix napalm in your beaker will result in hooch instead.

**Comment by Iamgoofball** [comment]
I fucking hate the bar drinks

**Comment by phil235** [comment]
just make napalm use something other than sugar.

**Comment by Iamgoofball** [comment]
Actually I got a better idea.

**Comment by Supermichael777** [comment]
wait isn't hooch supposed to be sugar and universal enzyme catalyst?

**Comment by TheVekter** [comment]
No, sugar and UE is vodka (I think).

Gonna fix this in a few, let's change Hooch to Ethanol, welder fuel and UE.

**Comment by Dorsisdwarf** [comment]
Maybe napalm should use some of the many new incendiary chems
