### ISSUE TITLE
Mulligan doesn't make new antags

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#9188]
Had a blob round end earlier, Mulligan said it was making Double Agents, never actually made them.

E: Lemme specify, because I was in a hurry earlier when I made this.

Round started as blob, the crew killed the blob fairly quickly. We chose to let Mulligan make more antags, and it said it was creating them (Antag panel said it was DA). However there were never any antags made.

**Comment by WJohn** [comment]
@Incoming5643 
Is it even possible to tame the mighty mulligan beast?

**Comment by Incoming5643** [comment]
It's possible that there's something wrong specifically with mulliganing into DA, as I'm not sure I've ever seen it
