### ISSUE TITLE
Revenants take damage from singularity

### ISSUE THREAD

**Issue by Madjura** [tgstation/-tg-station#9192]
Revision: Server revision compiled on: 
2db2a07e7e6a46804b9228f6ae4bd69b5fbfcbd2
Server: Sybil

Problem Description: 
(logs of me as revenant http://pastebin.com/RvuuE2jN)

I spawned as Revenant, in space, southwest of engineering, a bit below maintenance (previously roundstart observer)
I drained 2 corpses, the first one was in space by the singularity, on the walkway thing, the second one was inside Engineering
I unlocked Seed of Draining
I used it and died instantly (person was alive)
No message about losing a life etc, I just died, MSO said nothing showed up in the logs and told me to report it here
I think maybe radiation from the singularity could have something to do with this but I haven't tested it myself
If round logs are required or help, the round ended 1 minute or so before I made this report, 0:00 GMT +1 April 27

**Comment by Madjura** [comment]
Update:
It seems Revenants take damage from the singularity / radiation

What I did:
I spawned myself as revenant
I stayed in space for a bit, nothing happened
I did rightclick -> "View Variables" on myself
No damage

I repeated the same, but in the vicinity of an active singularity
The result:

madjura / revenant 
BRUTE:48 FIRE:0 TOXIN:0 
OXY:0 CLONE:0 BRAIN:0 STAMINA:0  
/mob/living/simple_animal
/revenant

No powers were active, I was just floating around so not in tangible form
At 50 brute I died, the damage increased by 2 every few seconds or so (I spammed refresh)
I checked again by floating in space, no damage
I checked again by floating around outside the singularity, damage, and I died at 50 with the message "The revenant pulses with an eldritch purple light as its form unwinds into smoke."
No damage was taken when I was inside the RWalls around the singularity
Bonus: Singularity can eat Revenant, not sure if that is intentional?
Bluespace Artillery also seems to damage them

I repeated the test after the singularity escaped and I still took damage in space (to be specific I was just outside the western airlock leading to the singularity on Box)
This is the listing of all the variable stuff:
Noteworthy in my opinion: 0 radiation, but bruteloss is at 18 (the little damage infobox at the top also said BRUTE was 18)
http://pastebin.com/U0au9h1G

This does not explain why I randomly died after using Seed of Draining outside of Engineering, in a hallway, though, but it's probably related?

**Comment by phil235** [comment]
The revenant takes damage only when on a simulated turf with no atmosphere, i.e. a plating in space, like the one around the singularity.
 
It's actually two bugs: the revenant doesn't have its own atmos_requirements list so it has the same as default simple animal which needs some O2 and no toxins. Thus the revenant is slowly asphyxiated.

But it only takes those damages when on a simulated turf because simple_animal/handle_environment() checks the atmos requirements only if the mob is on such a tile, and space is not a simulated turf. QED
