### ISSUE TITLE
Ayyylien shuttle table on the left is not correctly connected.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9194]
![](http://i.imgur.com/VacAbZZ.png)

They both appear to be facing north, leaving a gap in the middle.

**Comment by xxalpha** [comment]
They're alien tables, did you expect a familiar table technology?

**Comment by Memendia** [comment]
Holy shit those sprites

**Comment by WJohn** [comment]
Gotta love ausops.

**Comment by Anonus** [comment]
The main thing I don't like is they don't get space icons under them and that's awfulllll

**Comment by Memendia** [comment]
That's easily fixed by just copying a the wall onto a space tile sprite and copying that back to the wall.dmi

**Comment by Anonus** [comment]
Yeah but there are shuttle walls that do that dynamic generation thing, and that'd be useful for later. Presuming, of course, that the walls aren't just edited sprites.

**Comment by Memendia** [comment]
Wait some of the walls do dynamic space?

**Comment by Dorsisdwarf** [comment]
Yeah, it's possible to place some turfs over other turfs. I have no idea how it works, but it does, and well.

**Comment by Dorsisdwarf** [comment]
The deathsquad shuttle uses it so you can smash into the bridge

**Comment by RemieRichards** [comment]
Turfs over turfs is a lie.
What Byond does is it condenses the turfs from Highest Z pixel to lowest, and adds the lower turfs as underlay images to the highest Z pixel turf, which gets to remain a turf.

Eg:
Turf
Turf
Turf
-->
Turf
underlay of turf
underlay of turf

**Comment by AnturK** [comment]
I'll see what i can do about these dark blotches
