### ISSUE TITLE
Span issue in mopping message

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#9201]
You begin to clean the floor with the mop...
You finish mopping./span>

saycode pls

**Comment by Incoming5643** [comment]
It's only saycode when it's coming out of someone's mouth, this is just a missing less-than sign

**Comment by phil235** [comment]
@kingofkosmos

**Comment by PKPenguin321** [comment]
I'm tempted to try and fix this, since I see how you'd fix it (you add the "<" sign to the unclosed "/span>"), but I have little to no clue as to how to into git. Going to try it anyways. Prepare for disaster

**Comment by TheVekter** [comment]
That or you can make the change in piratepad, post it and I'll include the
fix in my next PR.

**Comment by PKPenguin321** [comment]
[Like this..?](http://piratepad.net/ep/pad/view/ro.U1qEIuK2J1Y/latest)

**Comment by TheVekter** [comment]
Yup. I'll roll it in and credit you for the fix. Thanks!

**Comment by kingofkosmos** [comment]
Sorry, my bad.

**Comment by phil235** [comment]
There's the same issue in the damp rag wiping message. there's a "</span" in the message.
