### ISSUE TITLE
Slime steroid does nothing.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9204]
This is what is says on the wiki.

 Extracts creates a bottle of slime steroid when injected with plasma, a potent chemical mix that will cause a slime to generate more extract. Useful when used on dark purple slimes for that plasma or grey slimes for monkeys. 

But when you use it on a slime core, nothing happens, the item is never used. It's either bugged or I'm retarded and can't figure it out.

**Comment by phil235** [comment]
There's slime steroid and extract enhancer. The first one is to be used on a slime, the second on an extract. The item's description is self explanatory. So maybe the wiki is wrong.
