### ISSUE TITLE
If you drop an item while ventcrawling it is lost forever

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#9206]
As a drone for example. IF the item is the nukedisk it is destroyed when the pipe is unwrench/destroyed.

Pretty similar to #8279

**Comment by RemieRichards** [comment]
Semi related discovery I found today (Which if this weren't true, would actually be a fix for this issue!)
We have a proc ```allow_drop()``` which I assume is for letting the player drop or not drop items inside an atom.

except it's never called or checked, ever.

**Comment by Incoming5643** [comment]
there's a ton of ways to accidentally lose ones hands, so there should probably be some handling for items that end up loose in a pipe, like maybe having them spit out of a nearby vent when they become loose. At the very least they'll need to properly drop if the pipe is unwrenched.

**Comment by Dorsisdwarf** [comment]
Make any items smaller than w_class 2 fall out of the closest vent, and make any larger items/dead mobs get spat out during the scrubber event.

**Comment by astralenigma** [comment]
That would be strange since the scrubber and vent system are completely separated. (At least last time I played it was)

**Comment by Anonus** [comment]
What if someone dies in a pipe? That doesn't seem to be fixed here.

**Comment by phil235** [comment]
The item shouldn't be dropped upon death. I tested it by suiciding as maintenance drone and it didn't drop the item, and unwrenching the pipe makes the dead drone appear and drop the item.
