### ISSUE TITLE
The game start countdown still ticks down while the round start is delayed, takes effect when unpaused.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9209]
If an admin delays the start of the round, the countdown still goes down in the background. (The game doesn't start while delayed though.)

If enough time has passed that it has reached zero, the round immediately starts when un-delayed. This has caught at least a few players and admins off guard, leading them to miss the round start.

**Comment by Ikarrus** [comment]
Request: Could we have the "Delay" button let admins set the time left? I've seen admins do this with debugging the ticker after the server reboots after downtime. It'd be nice if this was an actual button.

With -1 being indefinite, of course.
