### ISSUE TITLE
If the AI has an intercom near it, arrival announcements broadcast through it as says instead of states.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9210]
If an AI has one of the intercoms near it broadcasting, it will pick up arrival announcements and rebroadcast them but the second message will be ```"AI says: "Joe has signed up as assistant." ``` instead of ```"AI states: "Joe has signed up as assistant." ```.

Other radio messages are rebroadcast normally.

**Comment by GunHog** [comment]
Was there a script running?

**Comment by Boggart** [comment]
No idea, I should have asked though. This was pretty much at roundstart.

**Comment by Dorsisdwarf** [comment]
Arrivals announcements are now made by a machine, not the AI itself, so this should no longer occur
