### ISSUE TITLE
Plasma cutter no longer damages blobs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9211]
You can shoot blob walls dozens of times with it and it won't damage them at all.

**Comment by GunHog** [comment]
Plasma cutters were heavily nerfed in https://github.com/tgstation/-tg-station/pull/8794. They are now completely useless against blob, be it melee or range. Unfortunately, it was intended, so there is nothing we can do about it.

**Comment by WJohn** [comment]
Ah. I'll close this then.
