### ISSUE TITLE
Corgies do not show they're facehugged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9215]
If you throw a facehugger at a corgi, it will latch on and do the usual gestation and bursting effects, but no sprite will be put on its face anymore. We used to have one for this but it seems to have stopped working.

**Comment by bgobandit** [comment]
related to https://github.com/tgstation/-tg-station/issues/4510?

**Comment by ike709** [comment]
#4510 was fixed but the issue was never closed, and I don't think it's really related...

**Comment by DaedalusGame** [comment]
facehugger.dm at line 150 doesn't call C.regenerate_icons() after it sets the facehugger.
