### ISSUE TITLE
Metal foam is broken.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9216]
Both pre-spawned and hand-made foam grenades only create one piece of foamed metal in the center, surrounded by foam that spreads and vanishes right after.

@Iamgoofball

**Comment by Iamgoofball** [comment]
@cheridan actually I haven't touched metal foam

**Comment by Miauw62** [comment]
what about this

**Comment by Cheridan** [comment]
Worked fine when I touched them last

**Comment by WJohn** [comment]
They were broken when I tried them like two days ago, unless this JUST got fixed, will test later.

**Comment by Jordie0608** [comment]
I vaguely remember them being broken when I used them a week or so ago.
