### ISSUE TITLE
Dead monkies still scream when patches applied

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#9222]
Server: Which server were you playing on?: 
Sybil

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out.
2db2a07e7e6a46804b9228f6ae4bd69b5fbfcbd2 

Problem Description: What is the problem?
Dead monkies will scream if any kind of medical patch is applied to them.

What did you expect to happen: Why do you think this is a bug?
Then not to say anything (like human corpses)

What happened instead: How is what happened different from what you expected?
Monkey screams

Why is this bad/What are the consequences: Why do you think this is an important issue?
MY IMMERSION!

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue.
The monkey (101) is hit by a bullet in the chest!
The monkey (101) lets out a faint chimper as it collapses and stops moving...
Nomi Dealen forces the monkey (101) to apply the brute patch.
The monkey (101) screams!

**Comment by Incoming5643** [comment]
Jesus Christ

**Comment by Iamgoofball** [comment]
weird as fuck that this is fixed for human corpses but not monkies???

fucking hell

blame the monkey emote code then.

**Comment by peoplearestrange** [comment]
The image of a dead monkey screaming is somewhat disturbing too... I kinda like it.

**Comment by bgobandit** [comment]
(adds FUCK tag)

**Comment by Kromgar** [comment]
AND I MUST SCREAM

**Comment by Dorsisdwarf** [comment]
I fixed a buuuuuuuuug
