### ISSUE TITLE
Alien larvas are extremely hard to kill, if not impossible.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9223]
As a larva, I just took 6 pulse shots at point blank and only had 40 burn dealt to me. I was then dealt 50 brute from an energy sword, and was still alive. I wasn't even suffocating.

**Comment by astralenigma** [comment]
Where you in weeds?

**Comment by WJohn** [comment]
Initially yes, but even after being dragged off I still hit the cap while being repeatedly hit with an energy sword. I was even C4'd and I still did not go beyond 50 brute, 50 burn. No suffocation, no death.

**Comment by PKPenguin321** [comment]
This must be a recent development, I remember dying before I could even move once when I spawned as a larva in an area with a very high temperature

**Comment by Supermichael777** [comment]
larva don't have a oxyloss or bleed out mechanic so they don't suffer extra damage when critted. this means they stay around for a long time and always come back with weeds

**Comment by phil235** [comment]
The issue is that larva are apparently only dying once reaching -125 , despite their maxhealth being 25 (which caps each damage type to 50 because you're supposed to be dead at that point).

**Comment by WJohn** [comment]
I really wish it was possible to set negative max health on all mobs, honestly. It's really restrictive as-is.

**Comment by Boggart** [comment]
A sec officer spent a full clip of lasers into a larva the used a baton while I weldered it until I ran out of fuel and switched to an extinguisher. Finally we just gave up and cremated it.

I'd think we did over 100 damage past crit to it.

**Comment by astralenigma** [comment]
ok that is strange. someone must have messed up with the alien code when noone was looking.
