### ISSUE TITLE
Toggling door lights as AI/cyborg doesn't turn off yellow emergency access lights

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#9230]

**Comment by GunHog** [comment]
Intended, I believe. Door lights are "bolt lights". They do not, nor were they ever intended to be the same as the Emergency Access Lights.

**Comment by Jordie0608** [comment]
GunHog is right; they could stand to be renamed Door Bolt Lights for clarity.

**Comment by Dorsisdwarf** [comment]
There should be a way to turn them off then.

**Comment by xxalpha** [comment]
Why? They're emergency lights.

**Comment by Amnestik** [comment]
So a sneaky silicon can make an airlock all-access without the crew
complaining
