### ISSUE TITLE
Advanced plasma cutter fires invisible bolts.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9236]
Title says it all.

Server revision 13b5e15311c6459eeaf6ce4b9fae77ca37fc075a

**Comment by phil235** [comment]
It's because when used in pressurized environments the weapon's range goes down to 2 or 3 tiles, the projectile reach that range too fast for it to be shown. (same reason why shooting someone with a laser from one tile away doesn't show the projectile)

**Comment by Durkel** [comment]
Should anything be done about this then? You don't notice you're being hit by something unless you look at the chat, It's bit confusing.

**Comment by WJohn** [comment]
Is there a way to change projectile speed, then? I'm fairly certain thrown objects have something like this, so why not for these bolts in higher pressure environments?

**Comment by Supermichael777** [comment]
add obnoxious firing sound?

**Comment by Dorsisdwarf** [comment]
It does?
