### ISSUE TITLE
You can set alternate clothing styles from any distance

### ISSUE THREAD

**Issue by TheRealGLH** [tgstation/-tg-station#9238]
Problem Description: If you Alt + Click on a clothing item with an alternate style (like caps, or labcoats), you can set the style even if it's in a different room. As long as you can see it, you can set the style.

What did you expect to happen: I expected not to be able to do this

What happened instead: I could set the style

Why is this bad/What are the consequences: My immulsions are ruined

Steps to reproduce the problem: Alt-Click on any clothing item with an alternate style on the floor.

Server: Sybil

Revision: 13b5e15311c6459eeaf6ce4b9fae77ca37fc075a 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I was a borg.

**Comment by astralenigma** [comment]
Should a borg even be able to set a style to clothes???

**Comment by AnturK** [comment]
This also works for ghosts. So yeah kinda bad.
