### ISSUE TITLE
Airlocks in construction can be moved.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#9239]
This can result in someone bumping into the airlock and then the airlock construction is finished when the airlock is in the wrong place.

**Comment by astralenigma** [comment]
Shouldn't one of the first steps of building a airlock being secure it? are you sure that you can complete a airlock without wrenching it in place, or are you saying that even after wrenching it in place you can still move it?
https://tgstation13.org/wiki/Guide_to_construction#Airlock

**Comment by xxalpha** [comment]
This guy was pissed at me for accidentally bumping into his airlock. He then had to deconstruct it.
![airlock](https://cloud.githubusercontent.com/assets/4951579/7399485/3eac22a6-eeae-11e4-8fda-c95a381113f1.png)

**Comment by astralenigma** [comment]
That's weird I was unable to reproduce it the only way that would happen would be if he unsecured it before a step and kept constructing from that step which I haven't tested yet as possible.

**Comment by astralenigma** [comment]
What is a possible problem is the cooldown on the securing step but if you make a mistake there just need to unsecure and try again.

**Comment by astralenigma** [comment]
Ok found the steps to reproduce this.
1. Use the metal and make an Airlock Assembly.
2. Wrench it in place.
3. Add Wires.
4. Unwrech it.
5. Add the Airlock Electronics Board to the airlock frame.
6. Screwdriver to finish.

**Comment by xxalpha** [comment]
It's likely a feature, now that I think about it. Use at your own risk, I guess.

**Comment by astralenigma** [comment]
Yea only people that don't follow the right construction procedure would have this problem only way I see to resolve this problem is add a Secure_check() to each step.
