### ISSUE TITLE
Mob fire spreads too fast (IMO)

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#9242]
At least when walking over mobs on the ground. If it took a couple of seconds of standing on the corpse to catch fire, it'd be better. Fire doesn't spread instantly.

Also, a message in the chat would be nice. It's easy to miss you're on fire until the damage overlays start kicking in.

**Comment by Ikarrus** [comment]
What kind of fire is this? Fire doesn't spread like this.

**Comment by RemieRichards** [comment]
@Ikarrus yes it does, I added it a week ago.
Fire spreads fire stacks on contact.

**Comment by Ikarrus** [comment]
Sorry, I meant my suspension of disbelief finds it very hard to believe fire can spread like this, even with SS13 logic. As in I agree with the issue

**Comment by RemieRichards** [comment]
ah, either way, it can't really be fixed.
It's either instant, or not at all.

**Comment by WJohn** [comment]
Is there at least a way to make people stop burning after a while, like a minute or two? It'd be enough to kill them without them being permanent sources of fire.

**Comment by Amnestik** [comment]
Maybe while burning, items could be gradually destroyed, feeding the flames
until there's just a naked body, and after that husks the fire could go
out? Or maybe that'd just be even more irritating for people on fire/who
die to fire.

**Comment by Dorsisdwarf** [comment]
You'd have to add a "flammable" var to all items, so your egun/hardsuit doesn't burn away, but your cardboard box and your jumpsuit do

**Comment by RemieRichards** [comment]
@WJohn it should be disappearing fairly fast anyway.
NOBODY becomes a permanent source of fire, that's not how being on fire works in game.

You have a variable ```fire_stacks```, that is -20 to 20 (-20  being super not flammable, 20 being super flammable) and if you are ```on_fire``` then ```fire_stacks``` continuously goes down, when it hits 0, ```on_fire``` goes back to 0 and you stop taking FireLoss.

Fire spread on contact simply moves half of A's fire stacks (at most, 10) to you, and then attempts to ignite you, provided you have atleast 1-20 stacks.

**Comment by Kromgar** [comment]
Uh remie corpses always  stay on fire

**Comment by WJohn** [comment]
Was them ALWAYS being on fire all the time a bug or intended?

**Comment by RemieRichards** [comment]
if corpses are perma on fire that's a bug with them, to be frank fire should process on dead mobs as much as it does on live ones, it's negligable.

So perma-fire corpses is a bug yes, just not mine, I'll try and find the cause.

**Comment by Amnestik** [comment]
I noticed a corpse on fire in genetics yesterday and you're right, its fire
stacks had been depleted despite the fire overlay remaining. Standing on it
did nothing.

**Comment by chimersable** [comment]
Please don't change fire spread. If you are a changling you can set yourself on fire use fleshmend and get into fights while setting people on fire you run into. I took out a whole sec team a few days ago by running into them on fire.

**Comment by Miauw62** [comment]
sometimes i think "why do tg players powergame everything, the game could be so much more fun"
but then i see things like this and i laugh for days at the ridiculous things some people come up with. 10/10

**Comment by Czarcastic** [comment]
please don't remove this

seeing a crowd of people on fire is simply too hilarious

**Comment by Dorsisdwarf** [comment]
Closed for very old balance complaint. The fires of new feature have died down.
