### ISSUE TITLE
Table crafting is horribly unintuitive.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9243]
So right now table crafting is terrible in several ways:

1. It's only available for about half of our recipes, a large number of things like cable cuffs, assemblies, cooking, and objects created from stacks (metal making rods or floor tiles) are not there.

2. The majority of the recipes are hidden behind a materials barrier. Unlike R&D, which is hidden behind a research barrier, if you don't have at least half of the materials required for the object you won't even know how to make it. In theory this promotes banging rocks together or throwing everything on a table, but given how incredibly specific some of our recipes are such as most tech shells, this is next to impossible to predict. It should show all the recipes at all times, but as greyed out buttons (and possibly red text for missing materials).
To think that before this there was no hint of anything at all, that you had to have exactly all the materials present in order to get a button at all was even worse, and we're weirdly just tip-toeing to a better system.

3. There exists no classification or tabs to order these. Even if we showed all of them at all times, we'd then run into the problem that the autolathe and protolathe had for the longest time. A tab to encompass our 12 tech shells, for our kitchen recipes, for ghetto equipment and so on would be extremely useful.

If all of these are fixed, then perhaps people will actually USE this system, though I know this is a tall order given how many things we can make by hand.

**Comment by CorruptComputer** [comment]
:+1:

**Comment by Boggart** [comment]
It'd be nice to have a search function like autolathes and protolathes do if all recipes are shown.

**Comment by Jalleo** [comment]
Showing all recipies will just make it worse unless you mean show all with x items that i have here.

**Comment by WJohn** [comment]
No, showing all recipes at all times with the parts required to craft them is the only sane solution to what we have right now. Outright HIDING everything behind a materials barrier, unlike anything in the entire game, makes it 100% wiki dependent for no damn reason. You can't reliably bang two rocks together when some of these recipes require several units of very specific chems and we have over 400 chems now.

**Comment by phil235** [comment]
I'm with Jalleo on this one, showing ALL recipes at all time would be counteproductive, having to use a search button or selecting a category each time you want to tablecraft something would seriously slow down cooking. Showing all recipes that use at least one of the items/reagents on the table is probably the only good compromise.

**Comment by WJohn** [comment]
That's still tip-toeing towards a better system, why hide things behind a materials barrier at all? What's wrong with the mentioned tab system if it at least stays open on the same tab?

**Comment by Jalleo** [comment]
Do you want to see how to make a stun prod when you are trying to make a meteor shell?
It makes it so there can still be searches for when you put rods or cable down but for more specialized parts you don't have to load up the whole list. 
Think of it like a filtered list by what items you have on there.

**Comment by WJohn** [comment]
I already pointed it AGAIN that tabs would fix this. In order to prevent clutter we separate these things into their own tabs in the same way the protolathe and autolathe does it: A tech shells tab, a ghetto weapons tab, a cooking tab and so on. It won't even be that cluttered even if those tabs have lots of buttons, because often enough you'll place down mostly only the items you're going to use to craft something with, and usually only just the one button will turn blue for you to click.

If that's STILL not enough, then make it alphabetized. I doubt we'll EVER get so many items that you can craft that'll actually demand a search function with key words.
