### ISSUE TITLE
Cyborg screwdrivers can't decon disposal bins.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#9244]
Power connectors on a disposal bin need to be screwdrivered first for the bin to be deconstructed. 

I would expect engiborg screwdrivers to be able to but a player reported not being able to do so, asked a human to do it, and the human was able to screwdrive it.

**Comment by GunHog** [comment]
If this was the borg "Solar", I was the RD who asked him to remove it. When I used a screwdriver, I got the message that I re-attached the power connection, so the tool DID work. It is either that we simply did not know how to remove the bins, or there might be a problem. Either way, Bins have always been really difficult to figure out how to deconstruct, as an incorrect step may cause you to flush your tool.

**Comment by Boggart** [comment]
Actually, I got Tyra to unscrew it to see if I could use my other tools to finish it. I couldn't, but I could use them on the chute that was blocking maint.

**Comment by Boggart** [comment]
Found the problem. Disposal bins check in attackby for a cyborg, if they're using anything other than a trash bag and the item has the nodrop flag, it returns. (So any module besides the trashbag.)

I've got a fix for this and will submit a PR once I've tested it.
