### ISSUE TITLE
Syndicate carbine grenade mode does not check for syndicate authentication.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9249]
If you nab a syndicate carbine, the 30 round burst-fire gun, its alternate fire that lets you launch grenades does not check if you have a weapons auth implant in you, so you can fire it as a regular crewmember. Yeah, you're likely to only get one shot but the grenade rounds are extremely powerful, and likely to get at least one crit in when fired into the nuke ops team. Isn't the entire point of firing pins meant to deny the crew your equipment, at the very least your guns?

@Cheridan

**Comment by Iamgoofball** [comment]
Does this fire a projectile grenade or a chem grenade?

**Comment by Thunder12345** [comment]
As far as I know, the projectile grenade

**Comment by Iamgoofball** [comment]
Make it fire nitroglycerin nades. Cooler, and then we can add more nades to ops for use with it.

**Comment by WJohn** [comment]
That sounds like all kinds of gross if you were to try and put physical grenade objects in grenade ammo boxes.
