### ISSUE TITLE
lightening bolt instahusk

### ISSUE THREAD

**Issue by norill** [tgstation/-tg-station#9251]
1. charge lightening bolt to max power
2. spam click lightening bolt
3. deal 300 damage under 1 second
4. ???
5. profit!

also after releasing 7 bolts at once the spell timer will count 7 times faster

**Comment by PKPenguin321** [comment]
haha holy shit
@AnturK 
@Incoming5643

**Comment by AnturK** [comment]
Hum,  yeah my fault.  Will put up fix soon
