### ISSUE TITLE
Mulligan still produces ten million traitors.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9258]
So we had a traitor/ling round, and all the antags died. Then it got mulligan'd into TRAITOR. I emphasize this because unlike double agents there aren't supposed to be a dozen traitors in traitor mode.

Yet...

![](http://i.imgur.com/1MjSKHo.png)

@Incoming5643

**Comment by Incoming5643** [comment]
Remember that in this instance that Traitor + Traitor/Ling would mean that there's two scoops of traitors plus a handful of lings, so this might actually be functioning correctly. Let me do some math and see if I can make it work.

**Comment by Incoming5643** [comment]
As of 10 days ago traitor scaling was 7 and changeling scaling was 8, I'm gonna assume that's still the case.

I'm also going to assume that the dead traitors in that list compose of the entire first wave (it was traitor that turned into traitor/ling). That means 5 traitors initially followed by 9 in the mulligan.. Working backwards:

num_traitors = max(1, min( round(num_players()/(config.traitor_scaling_coeff*2))+ 2 + num_modifier, round(num_players()/(config.traitor_scaling_coeff)) + num_modifier ))

5 = num_players()/14 + 2 OR 5 = num_players/7
num_players = 5 * 14 - 2 OR num_players = 5*7
num_players = 68 OR 35

Assuming it's 68 people, which seems reasonable for primetime sybil:

When a round mulligans every living player gets a roll through the mode's make_antag_chance

At 68 players we know at least 63 of them were still alive, but lets be charitable to death and say there were 50 candidates who had there settings on and weren't dead or sec/heads. In make_antag_chance there's a var, tratiorcap, that will give anyone who attempts to gain traitor the status if its at least 2 or more higher than the current number of traitors:

var/traitorcap = min(round(joined_player_list.len / (config.traitor_scaling_coeff * 2)) + 2 + num_modifier, round(joined_player_list.len/config.traitor_scaling_coeff) + num_modifier )

traitorcap = min(round(63 / (7 * 2)) + 2, round(63/7))
traitorcap = min(7,9) = 7

So it would for sure grant at least 5 new traitors, with the potential for up to 7. Except of course that it checks the traitorcap against traitor.len, which still has the existing dead traitors. Meaning this only accounts for up to two additional traitors. Which means:

Something may still be somewhat fucked.

Damn that was a lot of effort just to not get out of it.

---

Anyway yeah it seems like rounds that essentially "double up" and reroll into itself isn't working quite how it's supposed to. I'd be interested to see if a mode without traitors like blob would produce a normal amount of traitors or the party pack. These numbers aren't as insane as they used to be, so I do think I fixed the old issue, there's just something else here I need to consider that I haven't seen yet.

**Comment by Incoming5643** [comment]
but yeah just remember that after the mulligan it was traitor/ling, and initially it was just traitor, I know the screen doesn't make that exceptionally clear. I should probably make "current game mode" read "initial game mode" after a mulligan to clear the confusion.

**Comment by Incoming5643** [comment]
There's actually an inbuilt way to test if its just a traitor + traitor/ling interaction thing:

Force a round to start as extended, then go into the check antagonist panel and click "not creating new antagonists" to read "creating replacement antagonists" this should force a mulligan right away and after 2 to 5 minutes it will become traitor or ling or traitorling.

So long as it doesn't go pure ling the number of traitors made can server as a benchmark against this to see if it's still FIGHTVALE or if there's just some weird interaction.

**Comment by Incoming5643** [comment]
so apparently there were only ~35 people during this... meaning fightvale is still in effect.

WHELP

**Comment by Incoming5643** [comment]
Here's what I don't get:

No matter how you get there, either bylate join antag or mulligan antag, all roads lead to make_antag_chance() and this control:

var/traitorcap = round(joined_player_list.len / (config.traitor_scaling_coeff * 2)) + 2
if(traitors.len >= traitorcap)
	return

There's no other way for antags to be made in mulligans. At 35 people the traitorcap would be 5. There should NEVER be more than 5 traitors at this population, even if the round mulliganed into traitor or traitor ling 5 times over.

Ugh game mode code

**Comment by Incoming5643** [comment]
found the problem
