### ISSUE TITLE
Thunderdome prep room areas have no power.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9260]
This means the rechargers in there do not work. The best way to go about fixing this is to change the areas in there to have power_environ, power_equip, and power_light all set to 1. Probably best to do this for the entire thunderdome, too, which is easy to do.

**Comment by Firecage** [comment]
Strangely, even after doing as you said. They still do not work.

**Comment by Firecage** [comment]
Well, apparently requires_power = 0 interferes with those.

**Comment by WJohn** [comment]
Oh, that's strange... the issue might be a bit deeper than I thought.
