### ISSUE TITLE
Ghosts can eject people from cryo

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9267]
1. Right click cryo as a ghost.
2. Eject Cryo Cell
3. Be spooked

**Comment by Cheridan** [comment]
lol

**Comment by Lumbermancer** [comment]
is it related to cryo sometimes swallowing people? They get stuck in an open cryo, their sprite won't exit and all they can do is yell for help. You then have to close cryo, turn it on/off, and only then person will be able to get out.

**Comment by WJohn** [comment]
I wonder what else this might affect. Can you open sleepers this way too? What about the cloning pod new clones are made in?

**Comment by Boggart** [comment]
Lumbermancer, that's a different bug, right now if you move while in cryo you go into the pipes. (There's a fix up for it.)

**Comment by killerfgs** [comment]
Doesn't work on yog so it's probably a recent problem
