### ISSUE TITLE
Player Controlled Hivelord: Super cool, no cooldown.

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9269]
Player controlled hivelords have no cooldown on their brood spawns so they can be spammed in seconds to server killing levels.

Difficult to get into a hivelord as a player but not impossible. A short cooldown should be in place. Very short or the creature will very easily become useless. Even one or two seconds would help.

**Comment by Dorsisdwarf** [comment]
Is the method "get pink slimes, go to mining, click a hivelord"?
