### ISSUE TITLE
Station integrity over 100%

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#9271]
In a couple of rounds I've been in now (one that just ended and one yesterday) the station integrity report at the end of the game showed the integrity as over 100%. Yesterday it was 100.3%, today it was 100.1%. The roundtype today was nuke ops. I don't remember yesterday's. Probably traitor.

**Comment by Incoming5643** [comment]
integrity is a measure of how many floors, walls, windows, and grills (I think?) there are on the station compared to their initial counts at the start of a round. If you build a lot of new bits (or take care of damage where it arises while adding just a little bit) you can get over 100%

**Comment by Amnestik** [comment]
So, not a bug?

**Comment by norill** [comment]
"integrity" doesn't sound like something that can be higher than 100%. either cap the percentage at 100 or reword "integrity" into something that would go better with numbers above 100.

**Comment by stapler2025** [comment]
Does that mean we can actively combat a blob round by rapidly expanding the station?

If so, lol.

**Comment by Incoming5643** [comment]
No, even though integrity rates were originally built for blob rounds, blobs win based on being a certain number of tiles back. If anything actively destroying the entire station is a more airtight way to keep a blob from winning.

**Comment by Firecage** [comment]
So what would be a better term to use?

Station Mass? Station Size?
