### ISSUE TITLE
Items held by drones who die in pipes disappear

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#9274]
Might apply to other mobs that die in pipes too. You'd expect the items to drop in the pipe, able to be retrieved upon deconstruction, but they don't.

I can see this being an issue if a drone takes an important item, is killed for it while trying to ventcrawl away, and successfully vent crawls before the death registers.

**Comment by Jalleo** [comment]
@remierichards

**Comment by phil235** [comment]
This is pretty much a duplicate of #9206
