### ISSUE TITLE
Genetics is broken in many ways.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9275]
Monkeys have 5+ dna blocks activated at round start, and so do active human players as well. This makes absolutely no sense and needs to be fixed.

It's at the point where I'm not even sure what block is race, because there are three at d+, and two more above 700+. It would also seem that some of blocks do nothing, since the already activated blocks do nothing to a human when injected.

Also of note is that the nano ui for the genetic console is too small and is clipping some of the words on it.

**Comment by Iamgoofball** [comment]
@Razharas come back when

**Comment by AlexCrimson** [comment]
The hell? Monkeys seem fine to me. Only one SE block is above 800. Maybe you are including the UE blocks? The nanoUi interface really needs to move those UE blocks. Easy to confuse them with SE.

Genetics is still in a terrible place though. Injectors take too long to produce, deal way too much radiation damage, all super powers seem to have an extremely low chance to manifest a power to the point it can take 20+ injections to get one. There are 23 damn SE blocks, which means even in rounds that are 1+ hours long you probably wont test them all, let alone get to make an injector with all the super powers. Even if by some miracle you did, you would die of radiation long before you manage to manifest all those powers.

Genetics fucking sucks. Remove those voice disabilities. Lower the amount of radiation injectors give you, and lower the machines cooldown to produce them. Increase the chances of super powers to manifest, and decrease the chances of them disappear when you inject yourself with the same SE(so you can make a single SE with multiple powers and actually get them all to manifest).

**Comment by RandomMarine** [comment]
>Lower the amount of radiation injectors give you, and lower the machines cooldown to produce them.

I did that. Upgrade the machine's micro-laser.

>Increase the chances of super powers to manifest

This is to offset the next point, I believe...

>decrease the chances of them disappear when you inject yourself with the same SE

Because this is gone. Powers should remain activated as long as its SE block stays above its activation threshold.

**Comment by AlexCrimson** [comment]
In my experience they disappear. But i could be wrong i guess. As for manifesting, it does take a stupid amount of injections to get a single power.

**Comment by RandomMarine** [comment]
They shouldn't, not unless someone mucked with it recently. As it stands, it's not hard to get every power you want all at once by upgrading the micro-laser, then hopping into the pod and having your partner mash "Occupant" until you have all the powers you want. Just don't reach 75 radiation and random mutations will never spoil it. (You shouldn't be going past 50, anyway)

Sure, they could lock the pod and hit you with the mute disability. But that's the risk you'll need to take if you want an easy ticket to being an invisible telekinetic maintenance hulk that sees everything and resists space.
