### ISSUE TITLE
Alien floors and grass are now both broken

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9276]
As of current both these tiles are honked. Someone here doesn't know how to resolve conflicts in dmi files correctly.

Open both versions of the dmi, and move the unique sprites from one version to the other version. Placement does not matter within the dmi, only naming and sprites. Then use the version you added the sprites to.

**Comment by phil235** [comment]
can't reproduce, grass and alien floors look fine on the latest build.

**Comment by Xhuis** [comment]
![sybil supply array three 2015-05-01 210541](https://cloud.githubusercontent.com/assets/5659269/7441380/6e5c890c-f0b4-11e4-8ac8-fef555bf434a.png)

Taken yesterday

**Comment by Jordie0608** [comment]
As of latest: abductor tiles are fine; grass placed via tiles are fine; grass present at roundstart on centcomm is iconless.

**Comment by phil235** [comment]
oh, Abductor floor, I thought you meant alien weeds.

**Comment by phil235** [comment]
The faulty grass tiles at centcom are actually turf/unsimulated/floor with icons edited in the map editor, they need to be changed to turf/unsimulated/floor/grass.
