### ISSUE TITLE
Incinerator turbine engine - useless?

### ISSUE THREAD

**Issue by duncathan** [tgstation/-tg-station#9279]
Problem Description: For the entirety of a 1.5 hour long round I just finished, I was trying to set up the turbine engine. Try as I might, it simply would not start.

What did you expect to happen: The first issue I had was that at roundstart, the console in the incinerator does not recognize any part of the engine. I was able to solve that by deconstructing and then reconstructing the compressor; however, the same method did not work for the turbine. I eventually came to the conclusion that it wasn't being found because it was not powered (no wires connecting the turbine to anything. 

What happened instead: I turned out to be completely unable to connect the turbine to power (which I'm unsure is required; problem solving on my part led to that conclusion, and nobody else in ooc knew anything about it) because I could not find a way (again, asked in ooc, no luck) to lay cables on vacuum floors. It's also strange to have to decon then recon the machine to have the console even recognize it.

Why is this bad/What are the consequences: It kind of leaves the whole turbine engine useless if it can't be set up at all. 

Steps to reproduce the problem: First, I checked the console. It said that it did not detect either part of the engine, so I decon'd then recon'd both machines. It then recognized one, but not the other. I then ran a wire through space (laid down platings and tore down one of the walls) to get to the other part of the engine. Just when I got to the last couple cables, I got a message saying I needed to remove the floor tiles (vacuum floor) before laying cable. I tried everything in my toolbelt to remove that vacuum floor, but nothing worked. That's when I gave up.

Server: Sybil

Revision: aa643337a981a9612df114922ed5ab1c7919859d

Possibly related stuff: I think the gamemode was extended.

**Comment by hanshansenhansson** [comment]
I played my fair share of atmos.
If the turbine works is completely random. Some rounds the turbine works, some rounds you can fix it by screwdrivering the parts twice, some rounds it won't work at all.

**Comment by tkdrg** [comment]
This was fixed according to paprika

**Comment by duncathan** [comment]
It was also a dupe of like four separate issues
This was my first contribution
