### ISSUE TITLE
[Feature request] Add toggle PDA light button

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#9280]
I can't count the amount of times I've either chosen to go without light because I didn't want to risk being attacked with the PDA window open or died in the PDA menu trying to turn the light on due to the lack of a shortcut.

This was requested here #7466 too.

**Comment by buttsmcgee** [comment]
You know you can just drag the PDA icon, right?
It's two clicks to turn it on, plus one more to close the window.

**Comment by Marflowerose** [comment]
I'm surprised this hasn't been implemented 5000 years ago in ancient egypt considering that 99,999% everyone puts on the PDA light and the rest intentionally keep it off for stealth. Same goes for ID being outside of PDA which is useful only for clown. Completely useless repeat for every round.

**Comment by Amnestik** [comment]
>You know you can just drag the PDA icon, right?
It's two clicks to turn it on, plus one more to close the window.

I know, but if you closed your PDA in a different menu, you have to backtrack to the main one to turn it on, and you forgot the part where you have to scroll down to get to the button to click on it. I know it's a minor inconvenience, but I think it'd be very helpful for combat and to increase UI efficiency.

**Comment by Dorsisdwarf** [comment]
PDA light should be a hotkey rather than a button, probbably. The HUD is getting quite cramped as it is, I find.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
