### ISSUE TITLE
Metal rods have several bugs.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9287]
Metal rods produced from autolathes in large stacks do not update their icons until used.

We're running into some weird bug where we're getting useless stacks that say "There is enough energy for  metal rods." Cannot reproduce even though I'm looking at it.

Also for some reason they're able to go into stack sizes of 60, I thought it was meant to be 50?

**Comment by chimersable** [comment]
Also the single rod graphic is ridiculous, it can't be much more than three pixels wide making it hard to click on.
