### ISSUE TITLE
If a changeling gets monkey'd it can not restore itself to human form.

### ISSUE THREAD

**Issue by Man-Shroom** [tgstation/-tg-station#9298]
More of a feature request than anything, but if a changeling gets monkey'd, it should be able to rehumanize itself. 

As is, monkeying them is really effective, because it cuts them off from a large portion of powers and prevents them from absorbing(and in (a hopeful)future, biting out appendixes)

**Comment by Dorsisdwarf** [comment]
Hitting monkey twice fixes this, I found.
