### ISSUE TITLE
Curse of the barnyard is misspelled to Barnyward, can't lower the cooldown of the spell.

### ISSUE THREAD

**Issue by Man-Shroom** [tgstation/-tg-station#9299]
What it says on the tin.

Attempting to lower the cooldown will just give you a new instance of the spell, with the same 15/15 cooldown.

**Comment by RemieRichards** [comment]
>Barnyward

is that the wing of the mental hospital they take Barney the dinosaur victims?

**Comment by Firecage** [comment]
....I like this name...

**Comment by xxalpha** [comment]
This shouldn't be funny.
