### ISSUE TITLE
People riding janicarts hit by projectiles are hit for twice that projectile

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9300]
Example: Player A is on a janicart. Player B is firing a laser rifle at him.
Player B fires a single laser.
Player A is hit by two lasers.
Player B fires two lasers.
Player A is hit by four lasers.

This is a bizarre issue and I'm not sure what could be causing it.

**Comment by phil235** [comment]
My guess is something to do with #8687
