### ISSUE TITLE
Chem dispenser UI is weird (Really minor still annoying)

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#9302]
Problem Description: Chem Dispenser UI is thinner than normal for some reason and only has room for 3 columns by default (with lots of space). The text is also centered in the buttons for some reason?

What did you expect to happen: The chem dispenser to have 4 columns like they always have been

What happened instead: It's got 3 columns and a bunch of space, with ugly looking centered text

Why is this bad/What are the consequences: I, and I imagine many other people, have gotten used to the chem dispenser having four columns, and muscle memory is a bitch now. Having to refind all the chemicals in the list is a massive headache, and plus it's just ugly and asymmetrical with this spacing

Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue: Open chem dispenser

Server: Sybil, I would imagine it'd happen on Basil too now

Revision: What revision was the server running? Type 'show-server-revision' ingame to find out: 97b5687d9e44e65ef590f4d771cd13a02c6f1b00 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us: Nope

Pic of what it opens to currently:
http://puu.sh/hzqcj/756f89d54d.png

**Comment by neersighted** [comment]
This has been fixed by tgui.
