### ISSUE TITLE
Duplicated changeling attack messages with spacesuit, blade and a lotta shit

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9304]
What I expected to happen: Not this:

Maymay has hit the reinforced window with the arm blade.
You hit the reinforced window with the arm blade.

Possible influencing factors:

- I had my organic spacesuit on
- I had my mime mask on
- I had my armblade out

**Comment by phil235** [comment]
not just armblade, it's all weapons.

**Comment by kingofkosmos** [comment]
Shit, sorry.
