### ISSUE TITLE
Some reagents add 1.5x of their amount when applied by patch.

### ISSUE THREAD

**Issue by RandomMarine** [tgstation/-tg-station#9305]
![patch](https://cloud.githubusercontent.com/assets/6583225/7443681/9636ce92-f113-11e4-9ed0-9ce1cff49e92.png)

I don't have the time to test this with every single reagent, but results seem to be consistent with each. Some reagents, such as silver sulf (As pictured) give 50% more when applied with a patch. Other reagents, such as water, welding fuel, and sulfur give the proper amount. And then there's styptic powder which gives its amount when self-applied, but has the 1.5x boost when applied to someone else? How the fuck?

**Comment by Iamgoofball** [comment]
Odd. @phil235 did you tweak anything regarding pill/patch code recently?

Also, if you could try this with a pill too that'd be nice.

**Comment by RandomMarine** [comment]
Already tried a variety of pills, they've all functioned normal.

**Comment by WJohn** [comment]
I'm curious exactly how metabolism affects this. I know that at best it can get 1.25x more use out of good chems, but does it just multiply the amount added the instant the chem is injected, or does it affect the actual metabolism rate of every chem?

**Comment by phil235** [comment]
I didn't touch pill/patch code.

**Comment by RandomMarine** [comment]
I suspect it has less to do with pill/patch code itself and more the touch reaction, but who knows?

**Comment by Xhuis** [comment]
Unable to reproduce
