### ISSUE TITLE
Cryopods release all their oxygen into medical air. 

### ISSUE THREAD

**Issue by Summoners** [tgstation/-tg-station#9308]
#9255 COUGH COUGH. PRESSURE AND OXYGEN LEAKING.

Seriously though when the pods open it releases oxygen instead of holding it.

**Comment by Boggart** [comment]
I'll test this on the branch I made those changes on to try to figure out if that's what did it.

**Comment by MrStonedOne** [comment]
This is actually intended, sort of.

In cryo's process_atmos() (used to be process()) it has expell_gas()

This is an odd as fuck proc.

It will put out 1% of cryo's air into the air, but it will heat it up to 20c first for some fucking reason.

I'll most likely change this up to not heat the air up, and only happen once when opened.

@Jordie0608 blame mso tag pls

**Comment by stapler2025** [comment]
they shouldn't be leaking gas when they're open..thats stupid.

**Comment by MrStonedOne** [comment]
Well right now they leak gas when open or closed. and in fact always have.

This is only a noticeable issue recently because of fastmos and my mc refactor that made atmos machinery process air stuff at 4x the rate.

My proposed change would be to make it leak gas once, when opened, rather than consistently over time.

**Comment by Iamgoofball** [comment]
Or just make it not leak gas at all

**Comment by Lumipharon** [comment]
^

**Comment by Cheridan** [comment]
It's kind of neat though. I guess it makes sense now why cryo used to be in a sealed-off room instead of in the main lobby.

**Comment by SconesC** [comment]
Well @Cheridan they aren't in a sealed room so either seal the room or fix this

I don't mind them doing this if they are inside their own space.

**Comment by xxalpha** [comment]
It should expel air once when opened and also create O2+chems smoke for a cool effect.

**Comment by Miauw62** [comment]
cloning pods should expel some smoke, but with the way cryo pods are used
making them expel anything would just get obnoxious.

**Comment by xxalpha** [comment]
Could just make it so they take some time to open. Where does all that liquid we see the spessmen float in go?

**Comment by Miauw62** [comment]
no reason to nerf cryo tubes like that tbh, especially if its just for
COOLNESS

**Comment by xxalpha** [comment]
Making cryo cooler is not a nerf.

**Comment by Miauw62** [comment]
it is if you make it take time to open

**Comment by xxalpha** [comment]
Stop ignoring the obvious joke pls
