### ISSUE TITLE
Occasional massive power drain in all grids.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9309]
I'm not sure how to reproduce this but a round happened earlier where everywhere started losing power. SMES were outputting, APCs said they had a grid connection but wouldn't charge. During this round, the admins were spammed with a lot of emitters lost power messages, more-so than usual.

The power usage on SMES outputs were showing red as if it was hitting their set maximum. Mining and the AI sat APCs ran out of power and shut off. By the time it was reported the round ended before I had a change to investigate.

**Comment by xxalpha** [comment]
Power sink?

**Comment by Boggart** [comment]
Those areas are all on separate powergrids, so one being powersinked wouldn't have affected all of them.

**Comment by xxalpha** [comment]
No no I deleted after I read that.

**Comment by Jordie0608** [comment]
@MrStonedOne

**Comment by Summoners** [comment]
I was the AI on a round where this occured and reported it to @Boggart ingame.

Station's grid reported huge amounts of power and APC's reported 'GOOD' connection to the Grid, yet it seemed pretty random if a room was getting power or not. When the round ended Atmos was exactly 0%, Grav Gen was 0%, Mining was 0% and even both AI Sat SMES and APC's were about 30%.

The SMES and APC's were both being drained in extreme rates. On the next round however the issue didn't appear.

**Comment by xxalpha** [comment]
Was there anything uncommon in the round that touches the powernet, such as power sinks? Was there any directly powered machinery besides the emitters connected? Was there anything different related to the power cables than the initial roundstart state of the map?

This is very likely a bug caused by MSO's recent MC PR and he might have a better idea of what might be causing it.

**Comment by Summoners** [comment]
Nothing that I notice was different, like I said it also drained the powernet for Mining Stations and Outposts which nobody even touched or visits some of those outposts.

**Comment by MrStonedOne** [comment]
I didn't actually touch power much. Just made it so when powernets get deleted they properly clean up so they don't hang around, and moved some code around to more apparate files.

The only thing i could think of that would cause this is either all wires some how being connected to the same powernet in code, and a power sink was placed on one. Or if the mc had a fuck up, and replayed all powernet ticks as if it had never fired and had a bunch of fires queued up.

**Comment by optimumtact** [comment]
Are you sure it wasn't a powerdrain?

**Comment by RemieRichards** [comment]
It was...

![10 000_volt_ghost](https://cloud.githubusercontent.com/assets/4043781/7447486/fb43c27c-f1f4-11e4-8682-9ccb7d470aa6.jpg)

The 10,000 volt ghost!

**Comment by Summoners** [comment]
This issue happened again in a round earlier in the day, just randomly happened for one shift.

I think @RemieRichards might have the best answer for now.

**Comment by Miauw62** [comment]
haha i remember that episode

**Comment by peoplearestrange** [comment]
Could this be to do with this #9350 ?

**Comment by optimumtact** [comment]
Well It could be an underlying bug that is the same for both, but not a direct result, as the smes are meant to be the buffer between the fluctuating input (singulo) and output (network)

**Comment by WJohn** [comment]
This is also spamming the admins with emitter power outages every few seconds, it's really annoying.

**Comment by Jalleo** [comment]
Yeah the cause for this is very old i think your mc stuff just enhanced it possibly @mrstonedone

**Comment by chimersable** [comment]
Mech not using power to move or for lights has been around forever. I don't think it's connected.
