### ISSUE TITLE
Atmos pipes wonky

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#9310]
- Pipes disappear when unwrenched

- Heat Exchange junction sprite points the wrong way when wrenching it in.
![image](https://cloud.githubusercontent.com/assets/11201491/7444645/d79114a4-f18d-11e4-86ad-79a6f3ff8a48.png)
 Still works though, just looks ugly.

- Temperature is wonky. Might be related to the broken cyrotubes. The following setup:
![image](https://cloud.githubusercontent.com/assets/11201491/7444651/32998cd2-f18e-11e4-897f-128d8340248d.png)
Air comes in space cooled in the purple pipes. Behind the pipes it instantly heats up, if I would shut off the cooler, it would even reach room temperature. No temperature is given to the room, though. Cyrotubes be strange.

- It is painful as fuck to use the RPD on walkways in space. You always need to find some 1px sweetspot to get it to work. My guess would be walkway blocks it and you need to hit the space tile behind it?

(But I do love the new RPD, so much cleaner)

**Comment by Jordie0608** [comment]
@MrStonedOne

**Comment by WJohn** [comment]
Also unwrenching pipes deletes them, and I know that at least volume pumps have invisible piping while the overlay is there.

**Comment by Menshin** [comment]
> Pipes disappear when unwrenched

This is probably because of https://github.com/tgstation/-tg-station/blob/bd6d51a0b566fea78b578a626951d431f2a61c0e/code/ATMOSPHERICS/atmospherics.dm#L44 which qdel the pipe obj (not structure) that just got relocate in the structure loc (in ```Deconstruct()```)

Also, two ```/obj/machinery/atmospherics/Destroy()``` procs coexists (given how Byond handles ..(), should probably be fused).

> Heat Exchange junction sprite points the wrong way when wrenching it in.

Apparently some ```Initialize()``` (which now only build the network) calls should have been converted to ```atmosinit()``` (which set node1/2/3, etc).
The ```construction()``` proc also seems to only be calling initialize.

**Comment by MrStonedOne** [comment]
I fixed the initalize shit in #9285

**Comment by MrStonedOne** [comment]
As for the code link,

Ya, I see what's going on. Deconstruct should be nulling that. Ok I'll fix that

**Comment by hanshansenhansson** [comment]
While we are at it: It is painful as fuck to use the RPD on walkways in space. You always need to find some 1px sweetspot to get it to work.

**Comment by Miauw62** [comment]
use alt click

**Comment by Boggart** [comment]
The heat exchange junctions dir vars seem to be messed up, either way horizontal winds up facing left (I think), while either way vertically points up. It doesn't seem to care which way it faces though so long as it lines up with the other pipes.

**Comment by duncathan** [comment]
These are all fixed save the cryo one, which I cannot reproduce.
