### ISSUE TITLE
Pipe Panic: Issue Edition

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#9335]
Something's wrong with the pipes or something. Not sure if duplicate.

>## ERROR: /obj/machinery/atmospherics/pipe/simple/green/visible added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) Nearby: (126, 84, 1)
## ERROR: /obj/machinery/atmospherics/pipe/manifold/general/visible added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) Nearby: (185, 99, 1)

**Comment by Jordie0608** [comment]
This is caused by pipe connection conflicts, usually two of the same pipes in one turf.

**Comment by Boggart** [comment]
Going by the locations, it's gotta be due to filters somehow.
![](https://dl.dropboxusercontent.com/u/83869314/ShareX/2015/05/2015-05-14_13-50-20.png)
![](https://dl.dropboxusercontent.com/u/83869314/ShareX/2015/05/2015-05-14_13-50-54.png)

**Comment by RocKeD** [comment]
I'm going to reference this topic as I believe they go hand in hand: #9468. I wish I knew more about Byond code, I tried taking a look but a lot of the code is still confusing to me. It's much different from the language that I know.
Here are a few points of interest, not sure if they will be of any help whatsoever.
This is where the warning is coming from:
https://github.com/tgstation/-tg-station/blob/0769ed7666929bcaa61d23a4367945c64a49e48b/code/ATMOSPHERICS/datum_pipeline.dm#L73
This is where the singulo from what I can tell affects the pipe net:
https://github.com/tgstation/-tg-station/blob/909217b733f7ae01534c90e015d352b245c6d3f7/code/ATMOSPHERICS/atmospherics.dm#L177

**Comment by Aranclanos** [comment]
I added the warning aaaa, are you sure there isn't two pipes stacking at any place?

**Comment by RocKeD** [comment]
From what it sounds like, the filter is causing this issue because it may be assigned 2 different pipe nets and this is causing a conflict but I of course may be wrong.

**Comment by Boggart** [comment]
I checked all around those spots I marked, there weren't any stacked pipes.

**Comment by Aranclanos** [comment]
prob should test deleting all pipes and testing what kind of pattern causes the error, to see if its really the filters or you just suck at searching pipes stacking

**Comment by MrStonedOne** [comment]
I think I found it.

https://github.com/tgstation/-tg-station/blob/master/code/ATMOSPHERICS/components/trinary_devices/filter.dm#L51

initialize would get called twice, once on new(), and again when the object controller starts up.

Initialize doesn't actually do anything in this context, but build the atmos pipenet. I'm gonna test removing that call and see if that fixes it and doesn't break anything.
