### ISSUE TITLE
You cannot choose your bible sprite

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9336]
There's no preference for it in the character setup. This occurs on both Sybil and Badger at the time of posting.

**Comment by Nienhaus** [comment]
Don't you choose when you spawn?

**Comment by Xhuis** [comment]
No, now religion and deity are determined by a preference in the character setup. There's nothing for sprites there.

**Comment by phil235** [comment]
You must click the bible to choose your sprite. I think I mentionned it either in the changelog or in the PR.

**Comment by Xhuis** [comment]
All right, sorry about that.
