### ISSUE TITLE
Reagant Blob is downright broken. Remove it until you have the faintest idea of how it works. 

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#9340]
Taken from my Feedback Thread, my two most memorable blobs:

*We find the blob in incinerator before the Level 5 biohazard announcement even shows up.

I haul down all the blob fighting tools from security. The crew is alert and prepared.

JK THE BLOB MADE ITS FACTORY RED SO NOW EVERY 10 SECONDS IT SENDS OUT A MINIBLOB THAT HAS SMOKE WHICH LIGHTS EVERYONE ON FIRE WHEN IT DIES.

THE ONLY NON-SPACE ROUTE TO THE BLOB IS A 1x1 MAINT HALLWAY. IF ANYONE ON FIRE, THEY LIGHT EVERYONE ELSE ON FIRE AS THEY PASS THEM.

DID I MENTION THE FIRE SMOKE LASTS NEARLY AS LONG AS IT TAKES THE BLOB TO GENERATE A NEW FIRE SMOKE MINIBLOB?

THE CREW IS NOW PERMANENTLY ON FIRE.

FIRE SUITS DONT BLOCK FIRE DAMAGE, YOU WILL STILL EASILY DIE TO FIRE DAMAGE IN A FUCKING FIRESUIT NOW.

ALSO ACID BLOBS DESTROY ALL YOUR EQUIPMENT THE MOMENT THEY TOUCH YOU.

ALSO EXPLOSIVE BLOBS BECAUSE FUCK EVERYONE AND EVERYTHING.*

and

*Dark green bleb in Viro, crew has it contained to the room. Everyone is responding almost perfectly, no way is the blob going to survive this.

Get splashed several tiles away

YOUVE TAKEN TOO MUCH MORPHINE

Medic drags me away

Literally spend the next 15 minutes in Medbay unconscious

WAKE UP

BACK IN ACTION

JUST KIDDING THE MORPHINE MIMIBLOB SMOKE STILL AFFECTS YOU DESPITE WEARING INTERNALS

YOURE KNOCKED OUT AGAIN NERD, ENJOY ANOTHER 15 MINUTES ASLEEP

JUST KIDDING YOURE GOING TO SUFFOCATE NOW, HOPE YOU HAD FUN WITH THIS BRILLIANT NEW ADDITION TO THE GAME*

**Comment by RemieRichards** [comment]
This is not the right place for this kind of discussion.

**Comment by Robustin** [comment]
Well clearly feedback isn't getting through to you guys either. I don't know how to properly format "ALL THE CODE FOR AN ENTIRE GAMETYPE IS AWFUL" issue thread.

**Comment by RemieRichards** [comment]
Well, for a start, you wouldn't or rather shouldn't format a thread like that.
Because it's wrong.

Reagent blob is nowhere close to 100% of the blob gamemode/event code.
It's about 10-15%, if that.

**Comment by Iamgoofball** [comment]
Hi, counter to morphine OD is first purge it with calomel, 5u should do the trick, and then apply Insulin to wake them the fuck up.

Apparently someone is gonna remove morphine blob soon, and I encourage it.

Acid blob was removed ages ago.

Explosive blob could do with a nerf.

Smoke bypassing internals is Shit and Needs Fixed

I can get rid of permafire. I don't like it very much either. Firesuits not blocking fire damage is literally wtf and needs fixed, can you make a separate issue about it?
