### ISSUE TITLE
Reagant Blob has 100 different things wrong with it. 

### ISSUE THREAD

**Issue by Robustin** [tgstation/-tg-station#9342]
Server: Sibyl

Revision: https://github.com/tgstation/-tg-station/commit/97b5687d9e44e65ef590f4d771cd13a02c6f1b00

Problem Description: Virtually every aspect of Reagant/Chemblob is completely broken or unbalanced

What did you expect to happen: When I see a blob, I expect clear feedback on what is happening to me, what its powers are, and how I can protect myself. 

What happened instead: I spent 15 minutes in a morphine addiction coma because the blob splashed me a few times. Or I burn to death in a firesuit because a fire-factoryblob has a 1x1 maintenance corridor constantly filled with firesmoke that ignites anyone who passes through. Or I walk to to a blob and lose my space suit and all my equipment after it touches me once. Or a blob is able to explode me by splashing from several tiles away. Etc....

Why is this bad/What are the consequences: Why do you think this is an important issue? I played/play this game a lot. I have a good sense of when something is completely broken in terms of balance. Every blob round I've played was either a new player getting welderdunked because he burst in a primary hall or a living nightmare as a split core blob proceeds to melt/ignite/explode/overdose the entire crew with all these absurd abilities it never needs. Splashing? Really? Having an invisible ranged attack that can send you into a coma for 15 minutes should have never been merged. 

Steps to reproduce the problem: Have a decent player get picked for blob. Let the tears flow. 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): It was blob. I used to enjoy Blob before the chemistry change. It was fun, the goals and strategies were nuanced. It had everything a game mode needed with a good shot at winning for both sides. Now its a chemical nightmare where I have absolutely 0 counterplay for most blob types. Between splashing, permafire, firesuit nerfs, acid, overdosing, addiction, splashing, faster blob growth, miniblob smoke that can't be countered with internals, etc. Someone has found a way to put a well-rounded gametype into the garbage can by making what appears to be an extensive effort to turn blob into an extremely unintuitive and hellish experience.

**Comment by RemieRichards** [comment]
This feedback is very broad, and unuseful.
Please focus your issue report towards the particular aspects of blob that are bad, include suggestions to fix them, explain in detail why they're bad.

At the moment you've given us:
* blob reagents suck for counterplay
that's about it.

**Comment by Aranclanos** [comment]
Usually this kind of feedback is forwarded to the feedback forums on tgstation.org, I suggest posting there but its not like you don't know that and I'm completely not sounding like an ass

**Comment by Robustin** [comment]
And the admins keep telling me to post here since I'm getting no coder reaction on the Feedback forums. 

I was also quite specific in a list about what was wrong with Chemblob:

Permafire, firesuit nerfs, acid, overdosing, addiction, splashing, faster blob growth, miniblob smoke that can't be countered with internals.

Since whoever coded this shit doesn't read Feedback and apparently has never played a round of their own Reagantblob, feel free to propose some other way to reach them aside from knocking down their door and lighting them on fire while shouting "HOW DO YOU LIKE IT NOW?!"

**Comment by Iamgoofball** [comment]
Can someone reopen this so I can make changes and call it a bugfix for this? Removal is not the fix, adjusting some shit is.

**Comment by Miauw62** [comment]
on one hand, reagent blob is shit and OP, on the other hand, i'm tired of shitlers shitting up my issue tracker.
please go away, i'll whip goofball.
