### ISSUE TITLE
Recorder picks up sound from my radio headset

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/-tg-station#9343]
Server: Syblil

Revision: 

Problem Description: recorder can hear my earpiece

What did you expect to happen: recorder would record local talking

What happened instead: recorder heard the radio in my ear as well

Why is this bad/What are the consequences: its messy and immersion breaking

Steps to reproduce the problem: turn on recorder and wait for radio chater

**Comment by Nienhaus** [comment]
Was it in your hand, on the same tile, or near a radio broadcasting?

**Comment by Supermichael777** [comment]
in my hand and the redio was my headset sorry that wasent clear

**Comment by Nienhaus** [comment]
I personally think that is kinda cool. Although it might be a bug.

**Comment by Marflowerose** [comment]
Pretty sure that's a kinda feature since nowdays you can hear radio chatter from people next to you. Which means that either the headset is extremely loud or just a speaker that booms out everywhere.

**Comment by Supermichael777** [comment]
still irritating when your trying to take someones statement for official crime fabri- i mean fighting purposes.

**Comment by Jordie0608** [comment]
Eh actually, I guess it makes sense

**Comment by Miauw62** [comment]
literally intended vOv

make a feedback thread or something if you really want this gone, just make it a poll.
