### ISSUE TITLE
Positronic brain popup "never for this round" button isn't respected

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9344]
You can press it, but as long as bepAI is on, you're getting every message

**Comment by GunHog** [comment]
They are the same flag. Did you hit never, then flip the pAI/Posibrain flag back on?

**Comment by Incoming5643** [comment]
no I didn't

**Comment by GunHog** [comment]
Please provide steps for reproducing this issue. (People really do need to follow the issue report guidelines, that info is helpful!)

**Comment by Incoming5643** [comment]
Had the bePAI flag off by default, turned it on midround via Toggle SpecialRole Candidacy, accept position.

Following round get pAI request pop up, first said no then said never, pAI requests stop.
Eventually positronic request shows up, I say never, it keeps showing up.

**Comment by GunHog** [comment]
The code for each is different, leading to this issue. I will have to pick one of these methods to match the other to resolve this issue:

pAI.dm: 		else if (response == "Never for this round")
			asked[C.key] = INFINITY

posibrain.dm: 
		else if (response == "Never for this round")
			C.prefs.be_special ^= BE_PAI

**Comment by Incoming5643** [comment]
Do the postronic brains really need a flag to do what they do? I think they could just as easily be filled in the same way drone shells are, with ghosts clicking the cubes to gain control.

**Comment by Dorsisdwarf** [comment]
I agree. This way you have to press each one you have, wait a few minutes, and keep trying to get a posibrain

**Comment by GunHog** [comment]
Gun Hog did not like this at first. He thought it would be too odd, as it could leave filled brains helpless. But, Gun Hog will code and PR this. He will get opinions.
