### ISSUE TITLE
Posibrain produced cyborgs are never referred to as Androids

### ISSUE THREAD

**Issue by RemieRichards** [tgstation/-tg-station#9345]
This is because Posibrains have names HU-199/RR-12/MSO-45 etc, so they never become:
"Engineering Android-55"

**Comment by GunHog** [comment]
Conditions to reproduce? On the latest master, shoving a Posibrain into a borg gives me this:
Notes are shown as incorrect, by the actual name seems fine.
![screenshot 2015-05-04 22 33 19](https://cloud.githubusercontent.com/assets/4955510/7466679/a54b001a-f2ad-11e4-90c1-5d837c61159e.png)

**Comment by RemieRichards** [comment]
Did it on sibyl just now.
Joined as posibrain HIU-188 and when placed in the cyborg remained HIU-188
maybe the robo named by shell, IDK.

**Comment by Dorsisdwarf** [comment]
Posibrained borgs showed as android for me last time I played AI

**Comment by GunHog** [comment]
This can be closed now
