### ISSUE TITLE
Radiation collectors aren't providing constant power.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#9350]
Radiation collectors don't provide constant power to and connected powernet.
It appears to act like a "burst" of power, going from full output, half output, then to nothing and then back up to full. This cycling is roughly every 2-4 seconds IIRC.

This means the SMES's don't get constant power and fail to charge properly.

To reproduce, get singlo to stage 3 or 4 and with all radiation collectors fully topped up and on. Then hit the output cable with a multitool, spam click and watch it fluctuate.

Could this be anything to do with the recent radiation re-work?

**Comment by Kromgar** [comment]
Radiation Collectors make a check to see if singulo is nearby if it is then it pops

**Comment by AlexCrimson** [comment]
Arnt they used for the Supermatter Shard? How the hell does that work? It isnt a singularity...

**Comment by MrStonedOne** [comment]
Its the other way around. Singularity's send pulses to the rad collectors. I don't think they do it every machinery tick, which might be the cause for this issue. Imma go look.

**Comment by EchoFade** [comment]
Holy crap! This explains why harvesting power from rad-walls doesn't work.
