### ISSUE TITLE
15 Cell drain/a tick as cyborg with no modules active

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#9363]
I have literally no idea how to reproduce this, listing the steps I took in the round.

1. Be a roundstart security cyborg
2.Go respond to a fight in mining
3. Start to head back for a cell change
4. Magic is summoned
5. Notice my cell is draining 15/a tick with no modules active, draining 30 a tick with just my disabler active
6. Cell change does not fix it

Scones could not reproduce it either.

**Comment by KorPhaeron** [comment]
Happened again during another summon guns/magic round, MSO assumed control of my mob and confirmed my power drain was fucked.

**Comment by GunHog** [comment]
It is still happening. All borg cell drain is rapid and crippling.

**Comment by xxalpha** [comment]
Yep, heard a guy saying it took him 10k power to wire a single solar array. Something's fucked.

**Comment by Cheridan** [comment]
This is only during Summon Guns/Magic? Does Summon Events do it as well?

**Comment by WJohn** [comment]
Perhaps related to #9309?

**Comment by GunHog** [comment]
No, Cheri. It happened to me during a traitor round.

**Comment by Boggart** [comment]
I've had this happen to me as well. I wired one solar and had to run for the dorms charger with all my modules off. I barely got there in time and all the other borgs that round complained of quick draining cells.

**Comment by RocKeD** [comment]
This happened to me last night, I was a sec borg and my power started draining so fast I barely made it to a charger in time. I have no idea what could cause this or even how to reproduce, all I did was equip the disabler, cuffs and flashlight then turned the flashlight on.

**Comment by Boggart** [comment]
It does scale with active modules, but even so something seems wrong with the rate of drain.

**Comment by EchoFade** [comment]
i have observed a drain of 5 per tick
