### ISSUE TITLE
Headslug farming doesn't make changelings

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9365]
I know this isn't a bug, but theoretically xenobiology should, with rng, and a lot of effort, be able to make friendly changelings which is a badass end goal for xenobiology and should totally happen. Each changeling takes a minimum of 20 minutes, after like an hour sliming up to gold and spamming until you get headslugs, so this doesn't seem like a balance problem since few rounds are this long.

Anyway this doesn't work. The monkey should be able to be humanized, then I believe cloned, and the changeling should appear, but it doesn't. The subject (From the sentient headslug that bit the corpse) basically just doesn't get changeling and it's a shame.

**Comment by Incoming5643** [comment]
I think it has to do with mind attached portions of what makes a ling a ling, probably fixable pretty easy. Will fix. Sorry someone got all that way finally without the payoff.

**Comment by Stickymayhem** [comment]
It's cool I made their subject a ling anyway

**Comment by Miauw62** [comment]
wasnt this fixed?

**Comment by Incoming5643** [comment]
nope
