### ISSUE TITLE
Portable crew analyzer is bad.

### ISSUE THREAD

**Issue by tristan1333** [tgstation/-tg-station#9366]
It is basically the vigilante's go to tool. Making it portable encourages doctor's to leave medbay. It is a bad idea.

**Comment by Dorsisdwarf** [comment]
It's better than the only crew monitor being heads-only.
(not counting meatstation)

**Comment by Incoming5643** [comment]
I think the portable crew analyzer suffers from "I don't [know how/want] to edit the map so I'll just stick it in the contents of a machine and call it a day"-itis.

Looking at you slime scanner.

**Comment by tristan1333** [comment]
Put the crew monitor into medbay...?

**Comment by RandomMarine** [comment]
If you don't want found, turn off your suit sensors.

**Comment by Cheridan** [comment]
Please keep game design/balance debate to a forum thread.
