### ISSUE TITLE
Gas masks are shown poking through helmets.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9370]
This is inconsistent with how most large full-body suits cover your body, most space suits will readily hide the clown's jumpsuit when you wear them. Their helmets however won't prevent gas masks and other mask items from poking through, which looks quite ugly.

**Comment by Marflowerose** [comment]
I think clown masks should still poke out from helmets even if it'd be inconsistent.

**Comment by Firecage** [comment]
Isn't this a dupe issue?

**Comment by WJohn** [comment]
My bad, will close.
