### ISSUE TITLE
Tasers break after one shot

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9371]
Advanced tasers seem to just poof and lose their sprite when you fire the first shot, after which it's impossible for a player to reselect them. You can continue to fire them but if you put them away it's going to be impossible to get them out again.

So yeah the pretty common spriteless phenomenon. This happened for both of my tasers.

**Comment by Stickymayhem** [comment]
Scratch that SEEMS LIKE ALL GUNS ARE BROKEN.

BRILLIANT.

**Comment by WJohn** [comment]
AYYYY

**Comment by Boggart** [comment]
Yeah, this was my fault. The guns were trying to use icon-states they didn't have due to the amount of charge in their cells.
