### ISSUE TITLE
Cultist communication name tags are broken for harvesters

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9375]
What I expected to happen: The harvester's name to appear before cultist chat, like with others.

What actually happened:

Acolyte ???: I CAN TALK
Acolyte ???: Which way to Nar-Nar?
Acolyte ???: Yeah baby

(three separate people. I think)

Why this is bad:

High-visibility bug that defeats the purpose of having separate name tags in the first place.

**Comment by WJohn** [comment]
I thought this was intentional? Harvesters were meant to be a super-low caste of constructs, so even their communication abilities would be trash.

**Comment by Xhuis** [comment]
Think I know why this happened, I'll see about fixing it
