### ISSUE TITLE
Accidentally agreeing to pop ups while typing

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9381]
If you're typing something and a pop up appears, you'll often automatically select the first option with one of your keystrokes. I don't know there's anything that can be done about this, but it's just rather annoying.

**Comment by WJohn** [comment]
This bug has been around basically since the dawn of time.

**Comment by RemieRichards** [comment]
@WJohn it's not a bug.

It's arguably a feature, you know "Press the first letter of an option to select it", it's in a lot of programs and things like making units in starcraft.

it just sucks in a game where you type most of the time.

**Comment by Cheridan** [comment]
Solution: kill all popups

fuck em

**Comment by Stickymayhem** [comment]
Would it be possible for the windows to appear without losing focus from the game window?

**Comment by RemieRichards** [comment]
We use the little popup windows because they're simple.
We could probably make a custom popup window proc identical to the ones we have now (Just using the black browser datums (not nanoui)) without focus being stolen.

**Comment by neersighted** [comment]
I believe MrStonedOne fixed this

**Comment by duncathan** [comment]
@Cheridan points for mso
