### ISSUE TITLE
Nuking the station doesn't show the full cinematic.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9387]
When the actual nuke detonates, there's supposed to be a cinematic where the station nukes, we also have a dud version where nothing happens. The real one isn't showing the station blowing up, yet everyone still dies and the round ends like normal.

**Comment by stapler2025** [comment]
doesn't that one show when the nuke detonates on a different zlevel?

**Comment by WJohn** [comment]
I think this may have been fixed or just a weird case? I dunno, closing.
