### ISSUE TITLE
Singularities are occasionally getting released for no reason percievable by admins.

### ISSUE THREAD

**Issue by Ikarrus** [tgstation/-tg-station#9388]
Every few rounds or so the singularity containment just decides "Fuck it I give up" and the singularity gets loose early in the round.

SMES are still charged.

Wires appear to be intact (although someone was cutting some on the other side of the station at the time).

Singularity was only 5x5

We really have no idea how it got loose other than bugs. It's been observed at least a few times already by server admins.

**Comment by optimumtact** [comment]
Caused by https://github.com/tgstation/-tg-station/issues/9309

**Comment by Incoming5643** [comment]
#9231
code/controllers/master_controller.dm line 36

- GCD = Gcd(SS.wait, GCD)
+ GCD = Gcd(round(SS.wait*10), GCD)

@MrStonedOne Why did this var change by a factor of 10? The waits for subsystems didn't get reduced by a factor of 10. 

I feel this may be the cause of this issue somehow. I var edited the power subsystem wait down a factor of 10 to compensate and the problems seemed to clear up in some ways.

**Comment by EchoFade** [comment]
I approve of these labels.
