### ISSUE TITLE
"Drop everything" VV command doesn't drop everything.

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/-tg-station#9394]
Items such as the syndicate hardsuit aren't removed from a player when using the Drop everything command from the VV panel's drop down box.

Haven't tried with other hardsuits yet.

Method to reproduce:
Traitor a player, dress them, give them a syndicate hard suit. Open VV for that player mob, select "Drop Everything" from the drop down box. All items are dropped to the floor EXCEPT the hard suit. (Only saw this happen with the hardsuit helmet toggled up and on. Can't be sure of the "mode" the suit was in).

**Comment by Dorsisdwarf** [comment]
This is NODROP, I believe.

**Comment by peoplearestrange** [comment]
Because the helmet is up? That makes sense I suppose. Hmm

**Comment by Miauw62** [comment]
if you want, it's trivial to make it force drop the helmet, but that might cause issues.

**Comment by Jordie0608** [comment]
Delete anything that can't be dropped then?
