### ISSUE TITLE
Reverse chestbursting is all kinds of bugged.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9395]
1. Trying to grab an item (in my case a circular saw from my backpack) will have it drop, you won't be able to hit the alien from the inside. The xeno on the other hand will apparently see this somewhere on their screen.

2. Recalling your energy katana back to you as a ninja will have it teleport into your hand, going through the xeno without damaging them any (it should be a badass instakill). Growing an armblade as a ling is also possible, so normal chestbursting works.

3. Messages from the person inside the stomach will come as both "you feel something rumbling inside your stomach" and that you are hitting them, while the xeno only gets the former.

4. Immediately upon reverse chestbursting, you may get a black screen and your camera will fail to follow your character for a little bit. This corrects itself later though, but it is a bit jarring.

**Comment by pudl** [comment]
dem aliums

**Comment by Dorsisdwarf** [comment]
Fixed in #11677
