### ISSUE TITLE
MMI Mech pilot mining difficulties

### ISSUE THREAD

**Issue by GunHog** [tgstation/-tg-station#9398]
MMIs/Positbrain pilots are unable to mine effectively due to it being impossible for them to utilize mining scanners. Ripley mechs can be equipped with mining scanners, but they are useless to non-human pilots, as they cannot in any way obtain meson vision.

**Comment by xxalpha** [comment]
This is not a bug, it's a limitation of MMIs.

**Comment by Supermichael777** [comment]
still kind of shitty. maybe an integrated meson scanner on the mech? and it realy is an issue. still probably will need to wait till after the freeze.

**Comment by xxalpha** [comment]
No that's stupid. MMIs are not people, they do not have rights.

**Comment by Niknakflak** [comment]
Technicality, an MMI is just a human brain.  They are not bounded by laws and therefore if placed in a mech, they are basically humans with a robot body except only the brain is human

**Comment by xxalpha** [comment]
They are not people and shouldn't be able to do the same things people do. People get to have a head and wear glasses, so they can have meson goggles. MMIs don't.

Unless you want to give every single mob in the game meson scanner vision just in case somebody wants to mine as Ian.

**Comment by Niknakflak** [comment]
Except MMIs have the ability to be placed in a mining mech and mine to limited functionality due to lack of meson and Ian doesnt have hands.  Two different things.  If they are going to mine anyway and have the ability to, might as well not make them useless.

**Comment by xxalpha** [comment]
Why would you ever want to become an MMI on purpose? The answer is, you never do. If you fuck up and become a brain then you can always become a cyborg, bound by the silicon laws, like a good bodyless brain should be. Cyborg Mining module is good enough for mining and even has mesons scanner!

**Comment by GunHog** [comment]
>Cyborg Mining module is good enough for mining and even has mesons scanner!

Play a mining borg for two hours and say to us, with a straight and honest reply that it is "good enough for mining".

**Comment by Marflowerose** [comment]
It's idiotic to apply even more restrictions to MMI mechs as much as there already are. There is no reason to make MMI mechs even more unappealing than they already are and actively discourage the usage of a cool feature. Ideally mesons would be integrated into Ripley as they should be in the HUD options for borgs.

**Comment by Niknakflak** [comment]
That is your opinion xxalpha and its irrelevant because the function to be an MMI mech exists and is intended so it might as well be fixed to not be a useless mechanic that already exists and is intentional.

**Comment by Niknakflak** [comment]
Wow muh grammar

**Comment by xxalpha** [comment]
I completely agree with adding mesons scanner vision to the Ripley.

**Comment by Cheridan** [comment]
Being an MMI mech is so bad in terms of bugs and gameplay issues I'd rather just see the feature taken out.

**Comment by Niknakflak** [comment]
But I like being a brain doctor ;_; 
I mean a brain inside an Odysseus.
