### ISSUE TITLE
Metastation camera issues

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/-tg-station#9399]
On metastation, the warden can see the AI core from his console. Obviously that's a problem because you can casually check if the AI is malf whenever you feel like it

**Comment by xxalpha** [comment]
Can't you also do that on Box? It's very intended, if I am not mistaken.

**Comment by SconesC** [comment]
@xxalpha Supposed to be a sep. camera network for the Science secpost/RD's office

**Comment by xxalpha** [comment]
I see. The last time I used the surveillance I was a science guard, so I thought it was normal.

**Comment by Dorsisdwarf** [comment]
The monitor in the science office is supposed to be the only way the crew can access the AIsat cameras (so you can't spot malf as easily and early).
@Metacide

**Comment by Metacide** [comment]
Thanks for the heads-up, will look into it.

**Comment by Metacide** [comment]
I should actually fix this with the next update, once I've incorporated a few other recent changes.

**Comment by Metacide** [comment]
Fixed in https://github.com/tgstation/-tg-station/pull/10839

**Comment by Dorsisdwarf** [comment]
Fixed.
