### ISSUE TITLE
Stamina Damage Is Completely Nonfunctional

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9402]
Anything that should do stamina damage, like disablers or holoswords, do nothing.

This has been the case for at least a few days.

**Comment by Iamgoofball** [comment]
Holy sweet jesus fuck critical priority critical priority

What the fuck could of caused this?

**Comment by Lumipharon** [comment]
Isn't this the same MC issue that's causing the singulo to constantly get loose, cells to decharge super fast/10 other horrible things?

**Comment by Anonus** [comment]
Five bucks on yes.

**Comment by Incoming5643** [comment]
:question: MAYBE :question:

**Comment by GunHog** [comment]
Confirming this issue as well. The roundstart Secborg came to me saying that its weapon was useless. I asked it to fire on me - the borg completely emptied its disabler, and I was completely unaffected!

**Comment by Alek2ander** [comment]
Could an increased tickrate make you restore stamina faster than you lose it?

**Comment by phil235** [comment]
That's very likely my fault, will fix.
