### ISSUE TITLE
AI can see lights in the static

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#9414]
1. Be an AI
2. Look at all the static/no vision in maint
3. Watch people run around in it because you can see their lights through the static

**Comment by WJohn** [comment]
Does this mean the static is not illuminated? Or are you talking about walls that you do have cameras on being illuminated? Because this happens with absolutely everyone.

**Comment by KorPhaeron** [comment]
I mean the static itself is illuminated, nevermind the walls as well.

**Comment by SconesC** [comment]
Ghetto AI tracking finally gets an issue report

**Comment by WJohn** [comment]
That's strange, static used to be full brightness in the past. Perhaps @mrperson changed something in his light overhaul.

**Comment by Cheridan** [comment]
Have you heard my new band, Lights In The Static?

**Comment by MrPerson** [comment]
This issue was fixed by #9911 and is a duplicate of #9884
