### ISSUE TITLE
Plasmamen Burn on Unsimulated Turf

### ISSUE THREAD

**Issue by Fayrik** [tgstation/-tg-station#9416]
Just been testing Plasmamen on a local copy, and when spawning one at centcom, it immediately burst into flames.
It's a super minor issue, but I'm pretty sure bypassing breath checks on unsimulated tiles would fix this, and would mean any possible future race would be able to stand in the special zones (Centcom, wizard's den, etc) without suffocating or catching fire.

**Comment by WJohn** [comment]
I thought unsimulated tiles still had an air mixture on them, just that they couldn't change or be influenced in any way, along many other invincibility properties.

**Comment by RemieRichards** [comment]
^ this.

It's an annoying thing, but I've told other admins before to:
* Spawn a human
* Equip them with plasmamen gear via Select Equipment
* THEN make them a plasmamen

they'll always be ok that way.

**Comment by Fayrik** [comment]
I thought that unsimulated tiles were supposed to not simulate any atmospheric related properties, which, in my eyes, should include mob based air checks.
I only even ran into this in the first place, as I was trying to do stuff with plasmamen without the equipment, so I had to go find a simulated area that I could easily void of oxygen before filling with plasma. (It's not easy.)
I was also disappointed to find that regular hardsuits don't provide any environmental protection, even when given sufficient plasma supply.

**Comment by Core0verload** [comment]
@phil235, didn't we removed unsimulated tiles? This should be fixed.

**Comment by Anonus** [comment]
Fun fact the wizard's suit is immune to fire completely.
