### ISSUE TITLE
Beepsky infinitely stuns you when on a space tile.

### ISSUE THREAD

**Issue by GoonOnMoon** [tgstation/-tg-station#9418]
Title. Especially obnoxious when you're not moving, next to an exterior wall, and floating. Beepsky will continuously stun you without cuffing you for an indefinite period of time.

**Comment by Supermichael777** [comment]
beepsky has a detain mode where he stuns you forever. this needs extra testing to ensure this is anomalous behavior.

**Comment by SconesC** [comment]
I think that's just him on detain, Beepsky normally gives no fucks and cuffs you when and where it pleases
