### ISSUE TITLE
Message monitoring comms computers cannot have their broken glass removed.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9423]
What it says on the tin. This seem to only affect the message monitoring consoles. You can deconstruct them fine when they're not broken, but they appear to be the only computer you can't repair when broken, even though the other comms computers can be.

**Comment by Jordie0608** [comment]
Apparently this is intentional but I can't fathom as to why.
https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/computer/message.dm#L37
