### ISSUE TITLE
Mechs do not lose charge from moving, turning, or having lights on.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9425]
What it says on the tin. They still lose power if they use their modules, however.

**Comment by xxalpha** [comment]
I can very much confirm this. You only lose power from using your equipment.

**Comment by EchoFade** [comment]
This is now a feature not a bug >_>

**Comment by WJohn** [comment]
This is actually getting in the way of potentially another bug I had trouble testing, where jumping into a charging mech would not give you your exosuit, but that may just be a weird-ass case related to #9309 and other MC failures.

**Comment by RocKeD** [comment]
Could it be related to #9422?

**Comment by xxalpha** [comment]
I don't think the server was running that at the time.

**Comment by Jalleo** [comment]
No it isnt @RocKed that code is all for silicons only which each time life processes use some of their battery power. And due to something wronky in the MC or something caused sudden spikes in processing specific stuff too much.
