### ISSUE TITLE
North and west mining outposts SMES cells start with no power.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9426]
Possibly related to #9309, though this was not a round where it seemed to have struck. The north and west outposts were already experiencing equipment and lights failure only 28 mins into the round. Might be a mapping issue, however.

**Comment by Jordie0608** [comment]
Which map

**Comment by xxalpha** [comment]
The z levels are separate from the station map so it should be the same on all?

**Comment by Jordie0608** [comment]
Meta doesn't use the generic z5

**Comment by WJohn** [comment]
Boxstation.

**Comment by xxalpha** [comment]
I can confirm this.

**Comment by Jordie0608** [comment]
Turns out it was both.
