### ISSUE TITLE
Dragging card decks out of your backpack will not have other items shift to fill its place.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9428]
![](http://i.imgur.com/6mBcYeE.png)

Normally when taking an item from your backpack with other items to the right, those items will shift to the left to fill the now-empty spot. When you click-drag a card deck out of your backpack, this doesn't happen. It's harmless enough and doesn't cause any invisible inventory clogging issues, but it's inconsistent with the rest.

**Comment by PKPenguin321** [comment]
I believe there are other ways to accomplish this, such as having a few rods in your backpack and some rods inhand, then adding the rods from your backpack to the stack in your hand

**Comment by lolnon** [comment]
Some other ways to reproduce this bug:
Drag a paper bin out of inventory
Add rods to a screwdriver'd welder to create a flamethrower
Create a device assembly e.g. igniter - igniter assembly.

**Comment by chimersable** [comment]
Creating stuff in your bag also does this, building a stun prod or carving out the pages of a book will also leave a blank.
