### ISSUE TITLE
Balance: Positronic brains result in way too many borgs

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9430]
Basically with any ghost able to return to the round as positronic brains begin to get spammed, literally every round has a minimum of four or five borgs, with often many more. It's a clusterfuck and a big problem for antags.

It's honestly gotten to the point that handling things as security has gotten more difficult with all the borgs pushing people around as they rush to every AI alert. 

Positronic brains either need to be way more expensive, take fucking ages to make or have some kind of cooldown to prevent this. I understand it's a good way to bring people back into the round but borgs just have way too much impact on things to be freely spammed.

**Comment by WJohn** [comment]
To be fair positronic brains just got added, and with anything new it will get used to death until its hype dies down a week or two later.

**Comment by Anonus** [comment]
Unfortunately, borgs are USEFUL, unlike the rest of those, so people will make them just to have them around.

**Comment by lolnon** [comment]
If you got this impression from recent rounds, it might have been me PUMPING them out all round for a few rounds. I'm not saying they're not unbalanced, just saying.

**Comment by GunHog** [comment]
I was hoping this would not happen. I was told that there would be borg armies. I thought that I would only see an average or 2-3 more borgs in a round at most, barring the more extreme of Robos. I did not want it to be stupidly hard to get or gated behind super rare things.

I will have to consider what we have to do here. I am just not entirely sure without completely making them X-ray implant tier or something awful like that.

**Comment by PKPenguin321** [comment]
Well since mining gets bluespace crystals now, you could make it so once they're printed you need to insert a bluespace crystal to activate them
IC reasoning would be that you're teleporting in an AI from centcomm or something but need the bluespace crystal to do it

**Comment by RemieRichards** [comment]
@PKPenguin321 actually, Bay lore for Posibrains states that the consciousness is housed IN bluespace, so bluespace crystals makes sense.

**Comment by PKPenguin321** [comment]
i had no idea, lucky coincidence

**Comment by Miauw62** [comment]
I PREDICTED THIS
BUT YOU WOULDNT LISTEN

;_;

**Comment by Dorsisdwarf** [comment]
This is exactly like the post-drone addition feedback, when drones were spamrushed every round and armies of the dead took up toolboxes and fixed any station damage with terrifying efficiency and speed, resulting in "Nerf drone!","Remove Drone!", "Make drone high tech!"

Give it a week to lose the novelty and see what happens.
(Yes I know I hate the 'just wait guys' attitude but this is actually relevant here.)

**Comment by Stickymayhem** [comment]
I'm not so sure. Borgs are undeniably extremely powerful and useful and get to have significant impacts on the round. I'm sure a large number of ghosts would want to take part in that.

**Comment by hanshansenhansson** [comment]
Drones do not interfere with the round, though. Borgs are valid-hunters per excellence.

**Comment by Lumipharon** [comment]
Having lots of drones isnt bad though.

Assuming they follow their laws(heh), thenthey're just a passive force for good, repairing the station because the engineers are useless.

Borgs are directly involved in the round, and depending on their laws, can be turbomurderboners.

I can only imagine ghosts seeing that the AI is malf and clamouring for the posibrains.

**Comment by peoplearestrange** [comment]
In terms of code, do positronic brains count as an MMI or a brain? I.e. can you stuff a posi into a human body? That be neat...

**Comment by RemieRichards** [comment]
@peoplearestrange they're MMIs.

**Comment by GunHog** [comment]
Positronic Brains are MMIs for ghosts. They cannot be made into humans, by any means. (Except admin magic) Sorry, but if you want your precious flesh, you will have to take care of it, be robust, and *try* not to die!

Oh, and I agree with Dorisdorf, I want to gauge how big of an issue this truly is before I over-react. I do not want to do to Posibrains what the tech level increase did to Xray implants.

**Comment by peoplearestrange** [comment]
Ok thanks :)
And yeah, they're a new thing, let everyone play with the new toy for a bit and then adjust. I mean look whats happened to drones ;_;7

**Comment by optimumtact** [comment]
I think posibrains are silly when we have drones, why not buff the drones by adding a machine that let you pop out a drone?

**Comment by AlexCrimson** [comment]
RIP Paprika. The Drone fab thing he made wouldve been great, but you guys just had to ban him before me got it merged.

**Comment by Dorsisdwarf** [comment]
It calmed the fuck down. This, unsurprisingly, turned out to be NEW THING WHEEE

**Comment by Miauw62** [comment]
>low-pop on basil
>ai is a traitor
>6 posibrains get made

:V

**Comment by Dorsisdwarf** [comment]
Closed under "Use the forums" mandate
