### ISSUE TITLE
Airlock heat-proofing is extremely snowflakey

### ISSUE THREAD

**Issue by Ricotez** [tgstation/-tg-station#9437]
As it stands right now, there is only one way to make a heat-proof airlock: make it glass and paint it in the Research palette. As a result, glass Research airlocks are the only heat-proof airlocks on the station short from special airlocks that had their variables edited by mappers.

My personal suggestion is to include the option to add plasteel to an airlock during construction. Then when the airlock is finished, set heat_proof to 1. This allows people to make their own insulated airlocks if they have plasteel, which they usually will if they are building an incinerator.

**Comment by WJohn** [comment]
Wait seriously? That's what determines it?

I think instead perhaps if you're gonna make a glass airlock, it should allow you to choose either regular or reinforced glass, where reinforced glass is heat proof and regular is not.

**Comment by Ricotez** [comment]
Then how would you heat-proof a solid airlock?

**Comment by WJohn** [comment]
I thought solid airlocks didn't pass any heat through them? If that's not the case, it should be.

**Comment by spasticVerbalizer** [comment]
Only glass research airlocks have [heat_proof](https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/doors/airlock.dm#L167), and it even [disappears](https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/doors/airlock.dm#L1113) when the airlock gets another paintjob, and all solid airlocks have heat_proof = 0.

**Comment by Cheridan** [comment]
wow

**Comment by spasticVerbalizer** [comment]
Scratch that, the snowflakeyness only applies to glass airlocks, all opaque (non-transparent?) airlocks also [block](https://github.com/tgstation/-tg-station/blob/master/code/game/machinery/doors/door.dm#L278) heat, I missed that the first time.
