### ISSUE TITLE
Destroy AI objective never happens?

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#9439]
There is an objective for traitors that is for destroying an active AI. However the conditions for assigning this objective may be always false at the time the code is executed.

Does anyone remember ever getting or seeing this objective?

@Incoming5643 you know your way around gamemode code, maybe you can verify this.

Code in question:
https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/traitor/traitor.dm#L122

**Comment by Dorsisdwarf** [comment]
http://ss13.eu/tgdb/tg/latest_stats.html will tell you if the objective's been assigned in the last 30 days (pretty sure I saw it there)

**Comment by xxalpha** [comment]
I guess it happens.
