### ISSUE TITLE
Duping metal rods with reinforced walls.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#9442]
Not a big issue, but it's a thing. If you deconstruct a reinforced wall down to just the girder and girder reinforcement and then apply the remaining plasteel you get a fully constructed reinforced wall while the metal rods from the second step of deconstruction remain there unused.

**Comment by Xhuis** [comment]
This so extremely slow and inefficient I highly doubt anyone would bother doing it.

**Comment by xxalpha** [comment]
As I said, it's not a big issue, but it's still an ugly thing.

**Comment by spasticVerbalizer** [comment]
[This line](https://github.com/tgstation/-tg-station/blob/master/code/game/turfs/simulated/walls_reinforced.dm#L68) creates the rods
