### ISSUE TITLE
Morphine Blob is the worst thing since acid

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9446]
...Or even worse than acid, arguably.

You cannot win against Morphine blob. Because of the autistic way spores are coded you are almost guaranteed to get a lethal forever-asleep overdose of Morphine from them, meaning you have a roughly five-minute window to fight the blob before you drop. There is no counterplay here due to the obscene amounts of Morphine being pumped into you, not to mention the fact that you cannot realistically administer calomel or charcoal to every crewman fighting the blob.

The overdose puts you to sleep forever, from what I can tell. It also addicts you and severely injures you. Was this tested, at all? Reagent blob is fucking dumb but having things like this that are so absolutely unbeatable is just retarded.

**Comment by Incoming5643** [comment]
the problem here is that when blob nuggets die they release a gas of the parent blob's chemical, but blob chems aren't actually normal chems is many cases, but metachems that give x number of chems per process. Blob nuggets should be modified to be sure that they can only provide one "dose" of the chems.

Also yeah maybe morphine was made a little too hardcore

**Comment by SconesC** [comment]
After most engagements with a Morphine blob you'll have accumulated about 15 minutes of sleep time.

Morphine is a problem but so is the way that blob spores give chems out.

**Comment by xxalpha** [comment]
Chem blobs would probably benefit from being toned down. Use lesser chemicals and in smaller quantities. Some of these blob varieties are outrageously powerful.

**Comment by Shapsy** [comment]
Honestly morphine is ridiculously OP anyway, anything over 7.2u is a guaranteed KO, and every .2u after that is an additional 3 BYOND seconds (not normal seconds, so multiply that by ~2-3). If you're hit with 30u, which is supposed to be the overdose, you're already clocking ~6 BYOND minutes of knockout, with no effective way of bringing you back short of having 3-4 people shaking you nonstop

**Comment by SconesC** [comment]
@Iamgoofball Not going to make a seperate issue report but read the above post regarding Morphine

@Incoming5643 Honestly regardless of Morphine's state I don't think sleep toxin blob is terribly fun to play against.

**Comment by Iamgoofball** [comment]
I think phil forgot to reduce the paralyse and sleep values and shit from when he moved everything to 1tick, 

i'll check it out

**Comment by Xhuis** [comment]
Nerfed in #9224, if it makes any difference.

**Comment by phil235** [comment]
Morphine blob removed by #10047.
