### ISSUE TITLE
Changelings cannot revive after death.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9456]
If you try to revive after having been killed, you're fully healed, but will remain dead. You can try this again and again until you run out of chems, but will not ever get back up.

This is kind of a problem when one of their main defining features is broken!

**Comment by optimumtact** [comment]
Not really, now we just have an excuse to finally turn this round type off.

**Comment by francinum** [comment]
Rejoice.

**Comment by Ausops** [comment]
Ahelp- "the ling thing seemed to bug at as I tried to move right as I regenerated,leaving me dead, ghosting me and taking allmy chemicals away"

Probably the same bug.
