### ISSUE TITLE
Sometimes the Mecha verbs are not assigned to the pilot.

### ISSUE THREAD

**Issue by xxalpha** [tgstation/-tg-station#9462]
It can happen that when you enter a mech you are not given the control verbs for it, the Exosuit tab doesn't appear and you can't manually use the verbs, leaving you stuck inside the mech. Everything else works (using mech equipment, moving and the skin changes, all normal), but the verbs are not given to you.

How to reproduce: jump in a mech and hope for the worst. It's seemingly random.

**Comment by Miauw62** [comment]
inb4 "mech code is shit it should probably be removed really"

**Comment by WJohn** [comment]
I was gonna report this, but I forgot ;~;

**Comment by optimumtact** [comment]
Good time to remove mech methinks

**Comment by WJohn** [comment]
Improve don't remove etc

**Comment by tgstation-server** [comment]
This is a byond bug. http://www.byond.com/forum/?post=1833666

**Comment by Supermichael777** [comment]
move the eject button so you can eject without the verbs. also make it so you can eject people if you could get in.

**Comment by TheVekter** [comment]
Just had this happen again. Vars still had the verbs assigned to him, he just couldn't use them.

Temp fix:
* Get-mob on pilot
* VV, "Occupant" and restore to default (should make occupant = null)
* Tell pilot to get back in

**Comment by Dorsisdwarf** [comment]
This happened to me. I had to message HBL to save me.

**Comment by xxalpha** [comment]
I've been looking at logs and this doesn't appear to be caused by runtime errors.

**Comment by Firecage** [comment]
Wheal, only way to fix it currently for players are to relog...which is annoying
