### ISSUE TITLE
Singularity is causing immense lag since fastmos update.

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9468]
Any time the singularity gets loose, the server experiences debilitating lag, sometimes crashing the server altogether.

**Comment by Incoming5643** [comment]
Yeah supposedly some recent update was supposed to make the singulo less laggy? Doesn't work.

**Comment by WJohn** [comment]
Atmos isn't the only thing acting up during this. Much more often it's actually just objects going beserk when the singulo's on a rampage. All those thrown objects are apparently very intensive.

**Comment by phil235** [comment]
The vast majority of the lag comes from gas pipes and power wires being destroyed/deconstructed by the singularity pulse. Then there's atmos doing a little bit of lag. Thrown objects causes very little.

**Comment by RocKeD** [comment]
Phil is the man, I'm just speculating here but when gas pipes / power wires are destroyed isn't the power net updated or reconstructed? If this is the case I can see why there would be massive amounts of lag. Would it be possible to somehow delay the check when the singulo is loose to where not all power nets are being constantly updated at the same time?

**Comment by Aranclanos** [comment]
right now, at roundstart the pipes are shouting errors in the console. 
These errors messages are for a reason, until those are fixed, the pipes won't qdel() properly and lag a ton when the singularity is released.
It's just a map fix, read the error and follow their magical clues.

**Comment by Jordie0608** [comment]
@Aranclanos #9335

**Comment by phil235** [comment]
@RocKeD That's correct, destroyed wires and pipes calls propagate_network() and build_network() respectively. Commenting those lines removes most of the lag.

**Comment by Miauw62** [comment]
I wonder if we could get away with only updating the networks the tick after the explosion

**Comment by Aranclanos** [comment]
if you make sure that no cables or pipes (disposals and air) are left without a network, its a 10/10 idea

**Comment by Xhuis** [comment]
Seems mostly better
