### ISSUE TITLE
Sounds randomly start cutting off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9470]
Partway through a round and at times all the way through rounds, all sounds will cut off within a second of being played, sometimes near instantly. This seems to be able to happen for either the entire round or only a certain duration, but I have absolutely no clue what's causing this.

**Comment by Miauw62** [comment]
This might be a dupe
Op 13-mei-2015 03:00 schreef "WJohn" <notifications@github.com>:

**Comment by Marflowerose** [comment]
Also applies to instruments. I was playing Violin, Guitar and piano at the same time (as one does) and only portions of each instrument were played and sometimes all of them just quieted down.

**Comment by Cheridan** [comment]
Dupe of #9042
