### ISSUE TITLE
Fastmos flamethrower and N2O pressure weirdness

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9474]
I was testing out gases with flamethrower, at first I shot several bunches 34% oxygen 66% plasma mix with max pressure (5000) in a room. That didn't have any particular effect on server. 
Several minutes later I shot out 100% Nitrous Oxide that was at about +1100 celsius with max pressure. First odd thing was that there was no N2O effect in the tiles. Using gas analyzer on the tiles showed no unknown particles. After I shot few more times to make sure, a borg opened the door to the room I was testing out and then server was kill after few spikes of lucidity. The flamethrower pressure did say that I had shot out the gas but there was seemingly none of the gas I shot out. Testing was conducted in Construction Room. 

Edit. Apparently I was the only one who got disconnected so it might be just clientside thing.

**Comment by MrStonedOne** [comment]
It is still odd that the n2o didn't end up on the tile. Try doing JUST the n2o test, without the one prior to that. it might be an issue with the flamethrower not properly shooting trace gases.

**Comment by Marflowerose** [comment]
Okay, I redid the test on single player.
Shooting room temperature N2O in room temperature room leaves the regular white effect and Analyzer detects it.
Shooting 860C N2O in same conditions only slightly increase the tile pressure and slightly the temperature. Analyzer didn't detect ANY N2O and there was no N2O effect in tiles. I shot an entire tank full of it.

**Comment by Marflowerose** [comment]
Further testing:
860C N2O did show up on analyzer and eventually did show up on tiles when I shot entire tankful of it in a room that was virtually a vacuum. Seems that superheated N2O instantly stabilizes with room temperature and with that, it's pressure goes waaay down. I don't know if this is intended or if the gas physics are wonky. Haven't had any client problems during these tests so I'll edit the topic to be more accurate.

**Comment by as334** [comment]
Yeah, N2O and trace gases in general are super buggy, and flame throwers are fucky. I'll take a look at it in a little bit if nobody else does.

**Comment by Miauw62** [comment]
"trace gases in general" we only have one tho

**Comment by as334** [comment]
There are two other legacy code ones that can be found sitting around in Gas_Mixtures.DM. You can even still spawn in a tank containing Oxygen Agent B.

**Comment by LNGLY** [comment]
The probable reason it didn't show n20 sprinkles when you shot the hot N20 is because hot gas = less gas, relatively speaking. When you shot the hot gas out into the cool air it was cooled and contracted from say 100 kpa to ~10 kpa, as if you'd cooled a canister. So you essentially shot 10x less gas.

This is why you always fill your flamethrowers with space-cooled gas, friends!

**Comment by duncathan** [comment]
I'll have to take a look at this after listmos (which may well fix this) but I will say that if the gas is too hot then there won't be enough to show the overlay. If the tank itself were at about 40000 K, then there wouldn't be enough gas in the whole tank to appear.

**Comment by duncathan** [comment]
Too few moles to transfer. Try a gas with higher heat capacity or a less heated mix.
