### ISSUE TITLE
Unable to stash Pneumatic Cannon in backpack without firing it

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9481]
Pneumatic Cannon probably shouldn't even fit in the bag but yeah, attempting to place it in a bag results in firing the cannon at the general direction of the cursor.

**Comment by PKPenguin321** [comment]
When placing it in the backpack, did you click on the pack itself in the backpack slot, or the inventory slots that pop up when you open the backpack?

**Comment by Marflowerose** [comment]
I clicked the pack itself.
