### ISSUE TITLE
Skeletons can appear bleeding

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9486]
This is   Caroline Prevatt!
She has   a satchel on her back.
She is wearing   some black shoes on her feet.
She has   a radio headset on her ears.
She is bleeding!
*---------*

I was dead from burns (not bleeding at time of death or thereafter), got necrostoned

**Comment by Iamgoofball** [comment]
bone marrow

**Comment by Xhuis** [comment]
feature

**Comment by Incoming5643** [comment]
It has to do with species with bleeding turning into species that don't bleed while already bleeding. Since the flag just tells the game to ignore the blood system for this character any existing bleeding status remains, even though the actual bleeding stops.

**Comment by Miauw62** [comment]
2spooky4me

**Comment by SconesC** [comment]
I wasn't bleeding though

It was only once I became a skeleton that it said I started bleeding
