### ISSUE TITLE
Split blob doesn't appear on round end report

### ISSUE THREAD

**Issue by ghost** [tgstation/-tg-station#9498]
1)Split/create second blob
2) End round I can't brag because my name isn't in the victorious blob list

**Comment by GunHog** [comment]
Were you my daughter blob that round where we started south of Virology and took the station from there?

**Comment by KorPhaeron** [comment]
I was with TechnoAlchemist on the toxins test site

**Comment by Anonus** [comment]
Fixed via removing split consciousness.
