### ISSUE TITLE
Posibrains knock you back to the menu 

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9500]
>enter posibrain
>you are a posibrain ping ping
> connection closed

relog, i can join game or observe and everything

have not tried to reproduce

**Comment by RemieRichards** [comment]
Rubbish reproduction steps I'm afraid.
I was on Sybil last night and I was able to enter a posibrain and remained fine for the rest of the round.

**Comment by Jalleo** [comment]
Could someone else of been in or getting in it at the same time?

**Comment by GunHog** [comment]
Jello is right, that is exactly what the problem is. I am adding this fix to my current PR.

**Comment by Jalleo** [comment]
Yay i didnt even look or play with posi brains i know this kind of recurring issue too well.

**Comment by Jalleo** [comment]
We should create a framework for this sort of stuff so we dont keep making the same general mistakes and for consistency sake.
