### ISSUE TITLE
The game is still inexplicably breaking (List bug? MC Crashing? BYOND Memory thing?)

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9503]
Rounds that last more than an hour very frequently end in a gamebreaking bug where people can rotate but can't move, some chat methods work sporadically and seemingly at random and no actions can take place. Admins can still use the announce function.

>This is not a MC crash.

>This is caused by byond having a memory error that causes a bunch of lists to become corrupt, causing any proc that uses those lists to runtime, including mob move, most admin stuff, saycode, atmos, etc.

This is severely wrecking sybil, like far more than is acceptable. The game breaks several times a day and it makes any longer rounds essentially impossible. This needs fixing somehow. It can't just be a BYOND bug or other servers would be having identical problems.

**Comment by Jalleo** [comment]
Could we be accidently dereferencing lists but not deleting them then something else starts using it for a different reason and not properly resetting the list?

**Comment by RemieRichards** [comment]
@Jalleo It's a Byond issue, byond is just randomly corrupting large lists and we use a LOT of large lists for very important tasks.

**Comment by Jalleo** [comment]
Okay but if none of the other codebases are getting this and use lots of lists we must be doing something wrong or that causes byond to bug out.

**Comment by Aranclanos** [comment]
When was the last time this happened?

**Comment by Incoming5643** [comment]
Yesterday

**Comment by Stickymayhem** [comment]
Today actually ten minutes or so before I posted this

**Comment by Stickymayhem** [comment]
pls

**Comment by Aranclanos** [comment]
byond is not open source, we can't fix it. We're complaining on their forums tho.

**Comment by Incoming5643** [comment]
It could just be that we have some sort of ludicrously huge list somewhere in the code that only gets problematically huge after a while of running. I saw a low pop server running our code where the bug occurred... after 10 hours of play. So what I'm guessing that if it's our fault it's something that propagates faster on a higher population server, like maybe some sort of improperly cleared of repeated entries mob list?

**Comment by RemieRichards** [comment]
Couldn't we fudge a fix by calling uniqueList() (now turbo fast thanks to me :P) on those lists every time the len is a multiple of 4? (or insert your favourite even number here) (so it's running "often" but not overkill)

**Comment by Aranclanos** [comment]
I would post the link where mso made a report, but byond page is down so waiterino pleaserino

**Comment by MrStonedOne** [comment]
Ya, I've already figured this out, kinda.

Its an issue with byond not deallocating lists when they stop being used, so that they stick around, even after world reboot.

Me, tobba, and lummox have been hot on this bug.

I'm currently running one last test, that should help me finalize figuring this out. Basically we are just waiting for the "event" to trigger and some stats I have being tracked will tell me.

http://www.byond.com/forum/?post=1852790

and 

http://www.byond.com/forum/?post=1854520

**Comment by Aranclanos** [comment]
keep it open

**Comment by MrStonedOne** [comment]
.....

Why?

**Comment by Aranclanos** [comment]
because the byond bug is still present and that's not the only place where you can find a locate() in the code. And your PR is also a temporary fix, until byond fixes it, once your commit is reverted because its not needed, this should be closed.

**Comment by MrStonedOne** [comment]
Locate doesn't cause it, looping in locs does. For looping on locs causes
it. Hence why my PR removed every use of locs in the code.

**Comment by Aranclanos** [comment]
oh alright. Anyways keep it open because at the end of the day they need to be reverted when the byond dudes fix it.
