### ISSUE TITLE
Invisible nuke disk

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9507]
What happened: Latejoined as captain, strolled into my office, WHERE'S MY DISK. Pinpointer points at the table, alt-click...

What I expected to happen: The disk has a sprite

What actually happened: The disk was fucking invisible, acting like any object with no sprite (can be picked up/interacted with via alt-click, added to containers but not removed)

Why is this bad: ......

Additional notes: I ahelped this and Ausops said it'd been happening for a while

**Comment by bear1ake** [comment]
Set icon var to 'icons/obj/items'
