### ISSUE TITLE
Stimulant traitor item doesn't work.

### ISSUE THREAD

**Issue by Durkel** [tgstation/-tg-station#9509]
Here's it's description. 

Stimpacks, a tool of many great heroes, make you immune to stuns and knockdowns for about 5 minutes after injection.

Except it doesn't, stuns and knockdowns still work on you and If I recall it's also supposed to have a minor healing effect.

**Comment by Iamgoofball** [comment]
goddamn it why does this thing keep breaking I don't even touch it most of the time

**Comment by phil235** [comment]
The stimulant reagents has a healing effect only if your health is below 50. Also, it currently reduces stun every tick, so you can get stunned but you get up much quicker than normal. We could buff the anti-stun effect (but that would basically make all the hard drugs like metamphetamin and bath salts useless) or change the traitor stimpack's description. Alternatively, we could make it use a new reagent only accessible to antags and non synthesizable (and black listed from Odysseus).

**Comment by Durkel** [comment]
Being immune to stuns and having them reduced ,slightly I might add. I tested it out on a test server, is totally different. eight tcs in alot to pay for five minutes of one tick less of a stun.

**Comment by Iamgoofball** [comment]
yeah, it should definitely get a reduced TC cost

**Comment by phil235** [comment]
Right now the stimulant reagent is used by the traitor stimpack, the adrenalin implant and the stimulant virus symptom. If we want to buff it, we may want to split it into two reagents.

**Comment by Lumipharon** [comment]
You have that confused Phil.
Ephedrine is just morphine, except it isn't the best poison in the game.

1 syringe of morphine puts you to sleep for close to 10 minutes. Shit's OP as balls.

**Comment by Dorsisdwarf** [comment]
Morphine is exponential due to the OD effect.

**Comment by SconesC** [comment]
Deceptive description and crazy high cost

How does it even keep breaking

**Comment by LNGLY** [comment]
Is it the same stimulants chem that miners get? probably not worthy of being a traitor item if so.
