### ISSUE TITLE
Using an emagged defib on harm intent on a dead body breaks the defib

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#9513]
If you get an unlocked defib (either with an EMP or an emag, you can tell it's unlocked because it'll flash orange and have a "!" on it), use it on the harm intent and target a dead body, it'll show a message saying "The defibrillator lets out an urgent beep and lets out a steadily rising hum..." and then completely refuse to work, no matter what combination of replacing the battery, re-equipping it, intent, target, nothing. You can't defib dead people, you can't shock stun alive people, basically you can't put the paddles on anyone's chest. I'd assume this is related to the change that made harm intenting a live person with the unlocked defib stop their heart, since that was added not too long ago

**Comment by Xhuis** [comment]
I noticed this, too. I'm not sure why it's occurring, especially because the code seems to be fine, but I'll look into it.
