### ISSUE TITLE
Lings can start as Security Officers

### ISSUE THREAD

**Issue by Chiefwaffles** [tgstation/-tg-station#9514]
**Problem Description:** A ling spawned as a security officer in the start of the round.

**What did you expect to happen:** I'm pretty sure this is explicitly not supposed to happen.

**What happened instead:** A roundstart sec officer was a ling.

**Why is this bad:** I'm pretty sure it was decided a while ago to disable sec antag. I guess it may of been overturned and I haven't heard?

**Reproduce Steps:**
1.) Have ling and Security Officer enabled in preferences, be ready at start of round.
2.) Spawn as ling-officer.
3.) Terrorize the crew.

**Server:** Sybil.

**Revision:**
Server revision compiled on: 
6fad0a6b3c35642ee33dddcd5f7345b78f1d319e 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1

**Other:** I believe the gamemode was traitorling.

**Comment by PKPenguin321** [comment]
Fairly certain a captain spawned as a changeling on Badger a week or so ago, too.

**Comment by Shapsy** [comment]
Yeah, Captain spawned as ling yesterday on Sybil too

**Comment by Miauw62** [comment]
@incoming you changed antag roll order right?
Op 16-mei-2015 05:33 schreef "Shaps" <notifications@github.com>:

**Comment by Incoming5643** [comment]
I did, but I swear I've seen this working right for both straight ling and straight traitor. So maybe there's a quirk to traitorling assignment. Will look into.

**Comment by RemieRichards** [comment]
While sad, I am slightly pleased that the new method for doing this also broke, like mine :3
