### ISSUE TITLE
Abducted crewmembers aren't added to antags

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#9517]
For whatever reason, there's no admin logging of people who are abducted by ayyliens, so we get weird shit like people blowing up the cloner showing up as non-antags. It'd be nice if they got added to the antag list.

**Comment by TheVekter** [comment]
@AnturK

**Comment by AnturK** [comment]
Hum. I have vague feeling i fixed this already. Will fix soonish.

**Comment by TheVekter** [comment]
Much appreciated.
