### ISSUE TITLE
Pneumatic cannon construction fail with non-standard welders.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#9523]
Reported by Demonfiren and tested out a bit.

Pneumatic cannon construction reports 'construction failed' if attempted with industrial welders or the welders with the larger tanks etc. Only normal welders seem to work. I don't think it's intentional.

**Comment by Xhuis** [comment]
I have no idea why this isn't working.

**Comment by phil235** [comment]
because the tool checking proc in tablecrafting doesn't use an istype check but needs the exact same object.
https://github.com/tgstation/-tg-station/blob/94de5c997e3f8155b981be4ac6b5e19bf59ebd80/code/modules/crafting/table.dm#L71

**Comment by Xhuis** [comment]
No way to fix that afaik

**Comment by Miauw62** [comment]
>not a bug
