### ISSUE TITLE
Drones should have a resist button on their hud.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9547]
They can use the resist verb (or type it in) and it works just fine, but because it's not on the hud most people don't realize it's an option.

**Comment by buttsmcgee** [comment]
While we're on the subject of drone interfaces, it's always really bugged me that the "E" hotkey doesn't work like it does with people.

This makes fast construction pretty frustrating, especially because you have to manually click to put everything away again.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
