### ISSUE TITLE
Resist button should flash when relevant.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9548]
Currently there's no way of knowing when to use the resist button outside of previous experience where you know it can be used. Having it flash on the hud would make it far more obvious that it's time to use it (when buckled, handcuffed, in a locker or other situations that you can resist out of).

**Comment by kingofkosmos** [comment]
Or just remove the resist-button altogether and make it work through clicking on the screen alerts.

**Comment by WJohn** [comment]
That works too, but if we DO keep the resist button, this would be a way to make it not completely useless.

**Comment by Dorsisdwarf** [comment]
Make a thread, preferably in the Feedback or Ideas section of the forum, please. 
The maintainers all agree that the issue tracker is the wrong place for this kind of feature request.
