### ISSUE TITLE
Wizards can still cast robeless spells as any race

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#9550]
More of a balance thing, really. We had a round where a wizard used a staff of polymorph to turn one of his apprentices into a xeno hunter. That's all well and good, but shouldn't that prevent them from casting spells?

Guy went on to slaughter the entire crew. Any time there was a remote chance of him dying, he just spammed fireball.

Really unfun and should probably be changed.

**Comment by Lumipharon** [comment]
You clearly never saw the time I had a borg army, including 2 fireball spewing syndiborg apprentices.

**Comment by Jordie0608** [comment]
Spells have a human_req var for this.

**Comment by RemieRichards** [comment]
This isn't a bug, the spells that need human have ```human_req``` as @Jordie0608 mentioned.
These spells simply lack the checks for robes, because they're set to be robeless, it's not a bug, it's emergent gameplay.

**Comment by TheVekter** [comment]
:/
