### ISSUE TITLE
SWAT helmet doesn't protect vs pressure

### ISSUE THREAD

**Issue by LNGLY** [tgstation/-tg-station#9551]
Despite the description saying they're spaceworthy. They used to be, also.

They protect versus cold, just not pressure.

So says Assistant: "Realllly delayed, but most likely reason for the pressure thing is the Permability Coeficient thing. Space helmets have it set to 0.01, Swat Helmets don't touch it."

**Comment by Lumipharon** [comment]
Pretty sure it got removed intentionally.

The damn thing doesn't even cover your face, how is it space worthy?

**Comment by LNGLY** [comment]
The description wasn't changed, the NOPRESSUREDAMAGE flag wasn't removed, the var that removes cold damage wasn't changed. You would think one of all of these things would've been edited if it was intentional.

Seems far more likely that whenever the permeability coefficient was added, someone just added it to all the space helmets without realizing the SWAT would need it as well.

**Comment by drynwyn** [comment]
SWAT helmets should really be a child of spacesuit helmets, I suspect.

**Comment by phil235** [comment]
To be immune from pressure damage you now need to have both a headgear and a suit that protects against pressure.

**Comment by LNGLY** [comment]
Yes, the issue is SWAT helms don't protect against pressure

**Comment by Lumipharon** [comment]
SWAT mask literally doesn't cover your face, you can eat etc with it on.

If for whatever reason people want it to be space proof, then that (and the sprite) would need to change.

**Comment by Dorsisdwarf** [comment]
SWAT masks are absolutely /intended/ to be spaceworthy.

Whether they /should/ be is another matter

**Comment by phil235** [comment]
it's spaceworthy again apparently
