### ISSUE TITLE
Ventcrawlers suffocate in the new ventcrawling system.

### ISSUE THREAD

**Issue by GoonOnMoon** [tgstation/-tg-station#9554]
Title. Monkies should either not suffocate at all or suffocate at 1/4 of the rate in which they previously did.

@RemieRichards

**Comment by GunHog** [comment]
Pipes have their own atmos, so if you are suffocating, it means that the pipe you are using is low or devoid of air. Avoid using the waste network if your mob requires air.

**Comment by xxalpha** [comment]
@GoonOnMoon write a more proper issue description. For all we know you were crawling in a vent without enough oxygen.

**Comment by GoonOnMoon** [comment]
I was playing a ling with lesser form and every vent I crawled through had no oxygen, causing me to suffocate very quickly.

**Comment by GoonOnMoon** [comment]
When I say vents, I mean vents, not scrubbers or disposals.

**Comment by xxalpha** [comment]
If the pipes you were in were depressurized or had insufficient oxygen, you suffocate. It's a feature.

**Comment by Marflowerose** [comment]
If the air distro has low pressure or no air at all, you'll take damage. If the air distro has super high pressure, you take damage. If the air distro is full of plasma, you'll take damage. It's a feature.

**Comment by GoonOnMoon** [comment]
Alright, I was unaware of the pressure feature.
