### ISSUE TITLE
Sudden lagspike, singulo spikes up to stage 7.

### ISSUE THREAD

**Issue by Ausops** [tgstation/-tg-station#9555]
Sybil experienced a spike of lag somewhere around 2015-05-18, 12:20. Machines spiked to around 7ds. About a moment later, I got an adminhelp asking why the singulo jumped to stage 7 blue swirly, from a relatively stable existence before.

First time I've seen this happen, no idea why.

**Comment by Miauw62** [comment]
>powernets randomly draining
>singularity randomly popping up to 7

tgstation is haunted

**Comment by Alek2ander** [comment]
praise he :ghost: :cyclone: :ghost:

**Comment by Aranclanos** [comment]
it sounds like it's due to some timing error on the MC, like somebody fucking with next_fire or some sorta integer overflow if the round was particularly long, or maybe even a midnight rollover thing, although I wouldn't expect it to be that.

**Comment by MrStonedOne** [comment]
Fixed, what happens is lag spikes caused subsystems to rapid fire to make up missed ticks, this could cause certain subsystems to fire first(like machinery) blasting the singulo with matter, then the singulo would rapid fire eating the matter and growing, I changed the MC to only fire subsystems 25% faster until missed ticks are made up.
