### ISSUE TITLE
If you space yourself in a coffin, and open the coffin, you stand still in space

### ISSUE THREAD

**Issue by hanshansenhansson** [tgstation/-tg-station#9563]
You completely lose all velocity if you open a coffin while travelling in space. Makes spacing people a bit less robust than it should be, as they can instantly travel back to the station without fighting the coffin-v.

**Comment by ike709** [comment]
Feature, should have welded the coffin shut.

**Comment by spasticVerbalizer** [comment]
Duplicate of #6569
