### ISSUE TITLE
Golem rune doesn't work

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#9564]
The rune didn't change color, it just stayed light-greenish all the time and said that there's no spirit nearby even though my ghost was right above it.

Needs confirmation, since I'm not 100 % sure about this, it might just be my test server, but still making this for just in case.

**Comment by Incoming5643** [comment]
you can't use golem runes if you ghost in a way that leaves you unable to reenter your body (suiciding, going catatonic)

**Comment by Jordie0608** [comment]
I remember trying this recently: the ghost needs a client so you can only locally test it with multilogging into DD, just aghosting over it won't work. I can't recall if the rune lit up however.

Otherwise it does work.

**Comment by kingofkosmos** [comment]
Oh shit, I didn't realize you needed to be unable to re-enter your body. Thanks.
