### ISSUE TITLE
Weird instance of mulligan on malf:

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9566]
1. Have a malf round
2. 2nd AI is created and is malf, but original AI is killed.
3. 2nd AI is moved to mining, considered dead
4. Mulligan swaps to double agents, no agents created
5. Timer is still counting down
6. Explosion was not observed because shuttle arrived at centcom, timer stopped counting down at that point.

I'd definitely like to see what would've occured if the shuttle did not arrive at the time it did. Would the AI have won? Would it have been able to nuke the station?

@Incoming5643

**Comment by TheVekter** [comment]
DA is supposed to be turned off for mulligan.

**Comment by Incoming5643** [comment]
It was able to start a countdown so yes, it could have won. I'll have to look into why DA was picked for a mulligan because I'm dang sure I turned that off before the freeze.

**Comment by Incoming5643** [comment]
Want to stress that this only happened because admins malfed the new AI. Because some bits of malf rely on location checks, creating more than one "true malf" will lead to weirdness such as this.

**Comment by Marflowerose** [comment]
Considering how often admins make the new AI malf aswell, it should become a purchaseable option for the first AI rather than slippery edit on the go.

**Comment by TheVekter** [comment]
Any extra AIs made during malfunction are supposed to have the law. Just
like borgs. It gets edited because there wasn't a mechanism in the game to
automatically do it.

This also removes counter-AI building as a strategy, and I'm alright with
that.

**Comment by WJohn** [comment]
Also @Incoming5643 we just had a wizard round where it mulligan'd into DA, too.

Is it supposed to have antag creation be delayed by a couple of minutes?

**Comment by TheVekter** [comment]
It is, but mulligan should never be rolling DA.

**Comment by Incoming5643** [comment]
there's a separate pull to deal with the DA issue, something got pushed back somewhere, it's single line change.

Alternatively I never actually fixed it but no one ever noticed because the odds of rolling DA compared to traitor/traitorling/ling were too low.

**Comment by TheVekter** [comment]
Either way, it still doesn't make antags.

**Comment by Incoming5643** [comment]
I know that's why I made a pull to disable it until I could get it to behave correctly :cow2: :hammer: :older_man:

**Comment by TheVekter** [comment]
https://youtu.be/1Isjgc0oX0s
