### ISSUE TITLE
Incinerator Air Alarm bug

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9570]
Incinerator room (new) has all-access air alarm that anyone can lock/unlock. I was unable to interact with the Air Alarm in regular fashion (setting vent to vent etc). I asked admin to verify but he could use it just fine. After that, I was able to use it aswell. Air alarm was unlocked when I tried interacting with it.

**Comment by francinum** [comment]
Unable to Reproduce.

**Comment by Marflowerose** [comment]
Okay, it didn't reproduce for me either now, must've been some buggs higgson byond thing or something.

**Comment by duncathan** [comment]
fixed by tgui
