### ISSUE TITLE
Lights need a click delay for burning you

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9576]
It's kind of ludicrous that due to lag, or lack of continuous vigilant patience, you can accidentally crit yourself in a few seconds by spam clicking a light. It's weird, annoying, insanely deadly to shadowlings, who have to spend a lot of time clicking lights and already have to deal with the extremely high level of constant care about the light levels and it's an extremely simple fix. 

Give them a significant click delay between burns so the actions that queue up don't fucking annihilate you in an instant.

**Comment by WJohn** [comment]
It only does 5 burn for clicking it, though? Or are you talking getting shocked when you smash it? Because that should only be happening once.

**Comment by Stickymayhem** [comment]
The issue is with no click delay you can end up hitting it up to a dozen times within a lag spike, then suddenly your chatlog gets slammed with a bunch of them and there is a brief delay before you go into crit.

This is especially the case for shadowlings, who completely die if they tap a light even a few times.
