### ISSUE TITLE
Strange Server Crash With Staff of Animation Mobs

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9580]
Wizard Round
Wizard takes the staff of animation and starts shooting up all the grills
A big group of grills piles up in the science hall
All target the robotocist and try to get through a broken window at once
Ripperoni

What REALLY confuses me is that someone called the crash when he took the staff of animation, so this has happened before apparently?

**Comment by Incoming5643** [comment]
Might be the same mob bug that crashes blob rounds?

Would be nice to get two birds with one stone...

**Comment by MrStonedOne** [comment]
runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
To avoid this safety check, set world.loop_checks=0.
proc name: ishuman (/proc/ishuman)
  usr: Desmond Wise (/mob/living/carbon/human)
  src: null
  call stack:
ishuman(Desmond Wise (/mob/living/carbon/human))
the emergency closet (/obj/structure/closet/emcloset): add fingerprint(Desmond Wise (/mob/living/carbon/human), 0)
the emergency closet (/obj/structure/closet/emcloset): attack hand(Desmond Wise (/mob/living/carbon/human))
the emergency closet (/obj/structure/closet/emcloset): attackby(null, Desmond Wise (/mob/living/carbon/human), null)
the emergency closet (/obj/structure/closet/emcloset): attack hand(Desmond Wise (/mob/living/carbon/human))
the emergency closet (/obj/structure/closet/emcloset): attackby(null, Desmond Wise (/mob/living/carbon/human), null)
the emergency closet (/obj/structure/closet/emcloset): attack hand(Desmond Wise (/mob/living/carbon/human))
the emergency closet (/obj/structure/closet/emcloset): attackby(null, Desmond Wise (/mob/living/carbon/human), null)
the emergency closet (/obj/structure/closet/emcloset): attack hand(Desmond Wise (/mob/living/carbon/human))
the emergency closet (/obj/structure/closet/emcloset): attackby(null, Desmond Wise (/mob/living/carbon/human), null)
....
....
....
Shutting down after encountering too many critical errors
