### ISSUE TITLE
constructed turret option to shoot unidentified life signs does not toggle

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#9581]
The "Neutralize All Unidentified Life Signs" configuration option of constructed turrets does not toggle when clicked, making it impossible to stop turrets from firing at them.

**Comment by Lumipharon** [comment]
I notice that a lot of the turrets controls won't work, when the the turret is trying to shoot things.
If you turn the turret off first, then it toggles fine (or atleast, for me).
