### ISSUE TITLE
Meteorshot and Pulseshot don't do any damage

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#9584]
At least not to humans. Fired five of each at a dummy, she took absolutely nothing.

Fix pls.

**Comment by WJohn** [comment]
That's strange, I tested these out less then a month ago and pulse shot did about 40 burn and meteor did maybe 30?

**Comment by TheVekter** [comment]
Dunno, maybe it's something weird with the thunderdome. I used a combat shotgun to hit a human/dummy with 5 of each and she didn't take damage. I'll try it with a human normal later.

**Comment by TheVekter** [comment]
Whoops.

**Comment by WJohn** [comment]
Human dummies don't work in conventional ways :p
