### ISSUE TITLE
Securitons can see cloaked ninjas

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9594]
@RemieRichards 

Kinda lame if it's a feature

**Comment by GunHog** [comment]
THERE IS NO ESCAPE FROM <B>THE LAW</B>.

**Comment by drynwyn** [comment]
They used to be able to stun and cuff ethereal wizards.

**Comment by AlexanderUlanH** [comment]
Turrets and beepskies and whatnot have always been able to see through chameleon stuff.  AI's used to as well, when there was actual invisibility and not sprite/alpha changes.  Not sure why they wouldn't.

**Comment by Miauw62** [comment]
is this a bug? is it not? not a fucking clue

**Comment by Jalleo** [comment]
Its not a bug its how the code reacts

**Comment by Miauw62** [comment]
nothing is a bug, its just how the code reacts

**Comment by SconesC** [comment]
If its not a bug it's something that needs to change, critical balance issue regarding cloakers

**Comment by KorPhaeron** [comment]
Not a bug. Robots being able to see invisible things has always been the hard counter to cloakers

@tkdrg kill it please

**Comment by tkdrg** [comment]
ok
