### ISSUE TITLE
Weapons authentication implant has a useless action button.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9599]
What it says on the tin. The only implants that have action buttons are explosive, chem, and weapons auth, and the weapons auth one is totally useless. The only people who have them are nuke ops, and there's no reason they'd ever want to not have it active or have it be toggleable. It simply shouldn't have a button, like the loyalty, exile, and tracking implants don't.

**Comment by Lumipharon** [comment]
er, emp, freedom, adren etc have buttons as well, but yeah, nothing button is nothing.

**Comment by WJohn** [comment]
Huh, hadn't seen those. Guess it should be grouped up with this issue too, if a fix is made.

**Comment by Miauw62** [comment]
Eeeh, its convenient to know that the implant is there, i guess?

**Comment by WJohn** [comment]
It's clutter and the other implants that can't be activated don't have buttons.
