### ISSUE TITLE
Brute damage message when checking self for injuries is now misleading due to bleeding implementation

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9600]
So here's what happens when you check yourself for injuries?

You check yourself for injuries.
My chest is bruised.
My head is bruised and numb.
My left arm is bruised.
My right arm is bleeding.
My right leg is bruised.
My left leg is bruised.

"My right arm is bleeding" is the message that's displayed after a certain threshold of brute is met, I forget which, it doesn't matter; however, because bleeding is now in the game, and because this message has nothing to do with whether you are actually bleeding or not, it is misleading.

**Comment by Miauw62** [comment]
Should also probably be "Your" instead of "My"

**Comment by Incoming5643** [comment]
it was changed to match when a limb would normally start bleeding but the mechanics of bleeding is "> X damage" while the description is ">= X damage". So if you have exactly the threshold of damage for it, it will tell you you're bleeding when in fact you're not.

**Comment by bgobandit** [comment]
Yeah but if you're bleeding it tells you at the bottom anyway in red so it's a bit redundant

**Comment by PKPenguin321** [comment]
>it was changed to match when a limb would normally start bleeding

I thought paprika got banned before this was merged

**Comment by spasticVerbalizer** [comment]
Would 'cut', or 'lacerated' be better?
