### ISSUE TITLE
Pipe error on metastation map

### ISSUE THREAD

**Issue by phil235** [tgstation/-tg-station#9607]
Two pipes are on same tile (and same dir) at 106, 89 on Metastation map causing an error during initialization.

**Comment by xxalpha** [comment]
This is likely the same as #9335 if the reported pipes are filters.

**Comment by Metacide** [comment]
Will check, but should have been fixed sometime.

**Comment by Metacide** [comment]
This is fixed in https://github.com/tgstation/-tg-station/pull/11553.
