### ISSUE TITLE
Drones can't use "E" key for quick-equip

### ISSUE THREAD

**Issue by buttsmcgee** [tgstation/-tg-station#9610]
This has come up a few times now, but I really think it deserves its own report.

The "E" key makes constructing things as a human infinitely easier, mostly because it lets you bypass some of the horrible inventory tetris and manual clicking. If you have a tool you want to put back in your belt, pressing "E" is usually the least painful way to go about doing this.

Drones, meanwhile, have to individually click each object to get it back inside their pack. This is especially bad if you carry around a second sack for materials, because it makes you have to either juggle things in hand, or drag the container icon to your sprite.

When attempting to press "E" as a drone, it now yields the message "Unrecognized or inaccessible verb: quick-equip"

**Comment by WJohn** [comment]
Augh, I pointed out that this should be done alongside #9508 but it got merged before that could happen, and now this issue is here.
