### ISSUE TITLE
Bar disposals don't work properly

### ISSUE THREAD

**Issue by Xhuis** [tgstation/-tg-station#9619]
Tested on latest revision as of time of posting.
![feeb](https://cloud.githubusercontent.com/assets/5659269/7785811/335c582e-0170-11e5-8eac-16db58f247ec.gif)

From what I can tell, the disposal trunk is one tile too far to the right.
![space station 13 2015-05-23 172154](https://cloud.githubusercontent.com/assets/5659269/7785813/5d365032-0170-11e5-81ae-5774d746e985.png)

**Comment by Dorsisdwarf** [comment]
90% this happened when the pokertable expansion was added.

**Comment by Lumipharon** [comment]
Why do different tables still link together like that?

It looks so horrible.

**Comment by Xhuis** [comment]
I don't know, it makes me sad

**Comment by Summoners** [comment]
Oh boy, I'll fix this.
