### ISSUE TITLE
Simple animal targeting is uncharacteristically resource intensive

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9624]
Having a bunch of simple animal mobs walking around is fine and dandy, but the second they see someone they want to punch things get extremely laggy.

Apparently THIS is why blob mode is disabled right now, cause the nuggets were lagging shit.

I wish I had more details but no one with any significant insight would be arsed to make a bug report and no one tells me these things.

:scream: :scream: :scream_cat:

**Comment by Miauw62** [comment]
we dont have a lag tag rip in pepperoni

**Comment by Cheridan** [comment]
>miauw doesn't know what performance means

**Comment by securitycopper** [comment]
Should this be closed? @phil235 merge has Fixes 9624
