### ISSUE TITLE
Positronic Brain

### ISSUE THREAD

**Issue by WellingtonSkellington** [tgstation/-tg-station#9626]
I was killed, ejected from my body and went into a positronic brain and was placed in a cyborg shell, my corpse was found and my brain was removed, which forced me out of the cyborg and destroyed the positronic brain. Clearly a glitch.

**Comment by palpatine213** [comment]
To expand on that. when the braindead borg was deconned, there was no posibrain in the parts. It was just gone.

**Comment by Miauw62** [comment]
SPOOKY

**Comment by palpatine213** [comment]
Since posibrain removes traitor status, if a traitor has this happen to them, they get detraitored, and they are removed from check antags.
