### ISSUE TITLE
People bleed through bodybags

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#9636]
1. make somebody bleed
2. put them in bodybag
3. drag around
4. see drops of blood everywhere

as janitor, this makes me cry

**Comment by WJohn** [comment]
spooky

**Comment by PKPenguin321** [comment]
i'm like 90% sure this happens with lockers too but haven't had a chance to test it lately

**Comment by Incoming5643** [comment]
Important note here: Corpses don't bleed at all, blood loss as a system only runs on the living.

That said corpses probably should bleed.

**Comment by Lumipharon** [comment]
it seems ok for lockers, since they're not exactly air tight, let alone water tight.
Bodybags however you would assume are designed to stop that.

**Comment by Miauw62** [comment]
yeah, this also happens with lockers
