### ISSUE TITLE
Fucking pressure tanks

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9637]
@Aranclanos 

Yo these are like dev items or something and are frankly kind of annoying to work with; you can't use an  analyzer on them, and I'm fairly certain there is no way to move/destroy them sans a bomb/singulo. They're still scattered around mining/maint so I assume they aren't made for center stage use

but they're really weird

please fix them

**Comment by WJohn** [comment]
It'd be nice to throw them out in favor of their movable tank counterparts, with a wrench nearby. It'd be far more useful to suddenly find a couple of air tanks in maint like that that you can refill your air at or drag to a location and open to fill the room much more quickly.

**Comment by Aranclanos** [comment]
I have no idea of what you're talking about

**Comment by stapler2025** [comment]
The solid stationary tanks hidden in maintenance.

**Comment by duncathan** [comment]
Like the plasma one in the incinerator on box.

**Comment by Dorsisdwarf** [comment]
The ones that look like medicine capsules

**Comment by kingofkosmos** [comment]
![boxstation 2015-01-18](https://cloud.githubusercontent.com/assets/5420151/7793856/154c9e30-02cd-11e5-8f5e-9f0ec8adcc5b.png)
Just remove these, no one will miss them (at least I've never seen them used) and every new person to the game will be less confused.

**Comment by Incoming5643** [comment]
There is one useful one, the plasma one in the incinerator. There's no other way to actually run the incinerator without it without atmos access.

**Comment by SconesC** [comment]
fuck 'em

can't use an analyzer on them but im 90% sure they are in fact finite

can't be moved or destroyed easily

why do they exist at all

**Comment by Aranclanos** [comment]
if I remember correctly they are just normal pipes. But with a different sprite and spawns with large amounts of gas. Might be wrong tho.

**Comment by as334** [comment]
No they are a defined object, the only real use for them is they have a MASSIVE storage capacity, second only to that of one of those huge scrubbers toxins has.

**Comment by RocKeD** [comment]
That is correct, if I remember correctly they are supposed to have somewhere around 30000-50000 units "moles?" of pressure.

**Comment by Stickymayhem** [comment]
Would be nice if you could wrench them then. Just have them be massive canisters that can only release via piping. It would actually be amazingly useful for big atmos projects like the derelict.

**Comment by xxalpha** [comment]
They're there for emergencies guys. You could even hook up your department's air supply to these and be safe from plasma floods.

**Comment by Aranclanos** [comment]
that's not true, it never happens, they are completely useless

**Comment by Jalleo** [comment]
I have used it when main atmos got bombed a couple of times its rare though but it can keep the station going. Also swear there was another issue talking bout this ages ago.

**Comment by MrStonedOne** [comment]
I like to use these to extend the capacity of distro and smooth it out so that broken pipes don't cut off all air to the station.

**Comment by duncathan** [comment]
non-issue
