### ISSUE TITLE
Chunk of AI upload is missing due to map conflicts.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9642]
![](http://i.imgur.com/1W40xWc.png)

WHY.

**Comment by Cheridan** [comment]
Well, this has a pretty simple explanation.

http://i.imgur.com/YS1PiDh.png

**Comment by WJohn** [comment]
Friggin' map conflicts holy shit.

**Comment by Xhuis** [comment]
GOOD FUCKING JOB
![thumbsup](https://cloud.githubusercontent.com/assets/5659269/7798917/00ff92d8-02ce-11e5-91b5-ecfc82c1cc59.png)

**Comment by Miauw62** [comment]
![](http://www.singulo.io/b/src/1431918577739.png)

**Comment by tgstation-server** [comment]
Feature. AI upload is now more secure.

**Comment by Xhuis** [comment]
:x: :a: :bug:

**Comment by daman997** [comment]
what is the problem here :^)
