### ISSUE TITLE
Body bags will not attach or "pull" with a roller bed.

### ISSUE THREAD

**Issue by RocKeD** [tgstation/-tg-station#9651]
When I really get into the game and start doing things properly I noticed that I could not attach a full body bag to a roller bed to transport around the station, the only way to move them is to drag on the ground using pull, this may not be a bug and if it isn't this should be a feature.

**Comment by Dorsisdwarf** [comment]
[not  a bug]
[feature request]

Bodybags are a subdivision of lockers, and rollerbeds are a type of  bed (which can have mobss buckled to it), but rollerbeds arent designed to have another object buckled to them

**Comment by Miauw62** [comment]
dont really see why bodybags should be able to be buckled into roller beds tbh.
it'd be pretty hacky for a minor fluff thing
