### ISSUE TITLE
Cult-converts' communication does not display name

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9657]
What happened:

You begin slicing open your arms with your fingers!
Acolyte Mara Lohengramm: Is escape okay?
Fortune Ray exclaims, "O bidai nabora se'sma!"
Acolyte Tore Hrafnsson: I have a blood boil rune set up to the starboard bridge entrance, need a third man to activate it if the Ops come by.
Fortune Ray says, "Ayyyy"
Acolyte ???: Ayyyy

What I expected to happen: Acolyte Fortune Ray says, "Ayyyy"

Why this is bad: Confusing, and this one is worse than the harvester bug because new converts are most likely to use this kind of communication when they're fucked and crying out for help.

**Comment by phil235** [comment]
I think this is intended innate cult communication doesn't show the acolyte's name (for humans only).

**Comment by spasticVerbalizer** [comment]
[Intended behavior](https://github.com/tgstation/-tg-station/blob/master/code/game/gamemodes/cult/cult.dm#L39), the normal communicate verb is meant for emergencies as it deals damage, tomes are painless.

**Comment by bgobandit** [comment]
It's weird intended behavior though. The damage dealt is enough to make it for emergencies only. The ??? just means that cult converts have to know that their communication will be anonymous, which isn't intuitive at all especially if they are listening to other people communicate. Took me by surprise and I'm nowhere near a noob.

**Comment by Dorsisdwarf** [comment]
Should just say "indistinct acolyte" or something

**Comment by Dorsisdwarf** [comment]
Intended feature even if fukkenwierd
