### ISSUE TITLE
Fire alarm overlay not appearing on a single tile

### ISSUE THREAD

**Issue by Miauw62** [tgstation/-tg-station#9659]
This happened in metastation, one tile above the door to the CE's office.
A fire alarm overlay was not displayed on this tile. On right-click, the only thing distinguishing it from the surrounding tiles was that the area entry in the right click menu displayed no square instead of a black square.

![2015-05-26 21_18_02-basil_ ork edition mike](https://cloud.githubusercontent.com/assets/3975713/7821137/f7172c7a-03ec-11e5-8ab8-23be0555bb1f.png)
![2015-05-26 21_18_08-basil_ ork edition mike](https://cloud.githubusercontent.com/assets/3975713/7821139/f8828802-03ec-11e5-969b-6b756f00cdcd.png)

**Comment by WJohn** [comment]
Likely just missing an area? Pretty easy fix, if not for the merge conflict boogaloo.

**Comment by Miauw62** [comment]
right click showed the engineering area, though.

**Comment by Metacide** [comment]
Will look into this.

**Comment by Metacide** [comment]
Fixed sometime before https://github.com/tgstation/-tg-station/pull/12133
