### ISSUE TITLE
Spawning without a backpack is broken

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9661]
You just don't spawn with the things you need
- Telescopic Batons
- Handcuffs
- Secway Keys
- Mining Voucher

All things that simply do not show up in your hand or on the ground. This can be fixed by removing the setup option to set backbag to 1 (2 being backpack, 3 being satchel) I think, but I can't tell where to do this. If you don't want a backpack just throw it somewhere.

**Comment by Miauw62** [comment]
this is probably a dupe.

fix: remove spawning without a backpack

**Comment by SconesC** [comment]
Yes, I even provided how to fix it, I just don't know where to apply said fix
