### ISSUE TITLE
Something broke the icons in deram maker

### ISSUE THREAD

**Issue by CorruptComputer** [tgstation/-tg-station#9662]
I just noticed that some things have the wrong icons in dream maker.

![](http://i.gyazo.com/d254100e9c08a7a1711fb81bb64d4885.png)

![](http://i.gyazo.com/b9cf6d6f4a9c7dcac4df4395d4da1fe7.png)

![](http://i.gyazo.com/f1e69a83a60405a2c1a2ac60c806c3b3.png)

**Comment by WJohn** [comment]
This has been around for ages, but yeah.

**Comment by RemieRichards** [comment]
>Something broke the icons in deram maker


>deram maker

well there's your problem!

**Comment by Miauw62** [comment]
deram makr brok ;-;
byund pls

**Comment by Dorsisdwarf** [comment]
I dont see any way we can fix a bug with deram makr.
