### ISSUE TITLE
hostile mobs that have been turned sentient will turn back hostile if controlling player disconnects

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#9664]
What the issue title says. If you apply a sentience potion to a hostile mob(for example, everything spawned by the chem life reaction) and a player accepts, you'll get a nice, friendly human controlled mob that obeys your commands. But when said player disconnects, the mob will turn hostile again, possibly killing everyone around it.

**Comment by Jalleo** [comment]
Has amyone checked what occurs when the player reconnects

**Comment by phil235** [comment]
Because of https://github.com/tgstation/-tg-station/blob/da28ed2138eac20d41ad653fa24f3b6698bab630/code/modules/mob/living/simple_animal/hostile/hostile.dm#L43
This needs to check for mind as well.

**Comment by WJohn** [comment]
I thought this was a feature. The same thing happens with monkeys, at least when I aghost out of them at any rate.

**Comment by Tokiko1** [comment]
You should atleast turn them passive as it has a lot of accidental griefing potential.
