### ISSUE TITLE
Names with apostrophes break AI tracking links

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#9666]
![](https://i.imgur.com/TmdDg2T.png)

**Comment by Miauw62** [comment]
@Aranclanos

**Comment by Miauw62** [comment]
>tfw theres a saycode issue that isnt your fault

**Comment by GunHog** [comment]
In addition to this, names that are modified via Telecoms are also made untrackable though the links. Say a script that adds a person's job, or an anti-AI script which adds a space to the name.

**Comment by Jalleo** [comment]
Split the AI track option from stuff that can be modified?

**Comment by AlexanderUlanH** [comment]
It makes sense that AI tracking would be interfered with by disguising the origin via telecomms.  People can just rewrite their scripts to put the job at the beginning of the message, rather than the end of the name.  That makes more sense anyway.

**Comment by Dorsisdwarf** [comment]
It means you can't do fun stuff like make comms report people as "Engineer Dooley" instead of Allistair Dooley [Station Engineer]

**Comment by GunHog** [comment]
Any modification of $source will cause the tracking link to fail. You could add it to $content or even $say, but I cannot find a way to do that without it looking awful or having someone complain.

**Comment by Aranclanos** [comment]
I don't care about ntsl, sorry.

**Comment by Miauw62** [comment]
Fix your shit, aran
Op 29-mei-2015 03:31 schreef "Aranclanos" <notifications@github.com>:
