### ISSUE TITLE
Emag missing some uses

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9668]
Can't emag cremator
Comms console emag is annoying, should log you in as unknown using the emag as an ID
Can't emag genetics console record delete

**Comment by Miauw62** [comment]
Not being able to emag the comms console is entirely intentional
Op 28-mei-2015 01:26 schreef "SconesC" <notifications@github.com>:

**Comment by Lumipharon** [comment]
what would emagging the cremator even do?
It doesn't require access to use, and already burns anything inside.
Do you mean the button that turns it on?

I'm 99% sure you can emag other buttons (such as the PA shutters), dunno about the crematorium button though.

**Comment by SconesC** [comment]
Yes the crematorium button cannot be emagged and requires Chapel access

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
