### ISSUE TITLE
ore redemption machine has no depowered sprite

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9669]

**Comment by francinum** [comment]
:clap:

**Comment by WJohn** [comment]
I don't think the smelters, stacking machines or ore loaders on mining have depowered sprites either? Could be wrong on that. It'd be pretty easy to do, however.

**Comment by PKPenguin321** [comment]
I think stacking machines bounce when on and don't move when off, but I'm not 100%
