### ISSUE TITLE
Powersinks are useless

### ISSUE THREAD

**Issue by Alek2ander** [tgstation/-tg-station#9677]
The powersink drain is less than the power generation in engineering if the singulo is set up properly, so they can't actually depower anything.

**Comment by xxalpha** [comment]
Could be because of new MC, since the power output of the singulo engine hasn't changed and neither has the power sink drain.

**Comment by Jalleo** [comment]
@MrStonedOne would you be able to get collate basic stats on what could be causing this?

**Comment by pudl** [comment]
i noticed this many a years ago but i thought i was just shit at using powersinks. its a shame because a station with no power is the best kind of station

**Comment by xxalpha** [comment]
>years ago

Must be completely unrelated.

**Comment by pudl** [comment]
i wasnt saying many a years ago seriously, i meant like a few weeks but i was being a meme

**Comment by Lumipharon** [comment]
I can confirm that powersinks seem to be fucked.

Went in as nuke ops, planted a sink on a wire (not a knot) waiting 5 minutes, nothing happened.
Moved the sink onto a knot, waiting 5 minutes, nothing happened.

It was screwdrivered in, and on, just the station wasn't losing any power, dunno why.

**Comment by Dorsisdwarf** [comment]
Coding a fix for this

**Comment by MrStonedOne** [comment]
its the 4th smes, it means they can overload a powersink because sinks only drain at 600kw

**Comment by xxalpha** [comment]
Oh yeah, that happened.

**Comment by duncathan** [comment]
FEED
BACK
FORUM

**Comment by Lumipharon** [comment]
@duncathan 
how is this a FEEDBACK FORUM.
An item has 1 sole intended function. It is currently not working.

This is what experts call a BUG.

**Comment by xxalpha** [comment]
More like an oversight.

**Comment by PKPenguin321** [comment]
yeah, this should be kept open

**Comment by Lumipharon** [comment]
>A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.
