### ISSUE TITLE
Borgs not properly receiving synced laws/notes/antag status

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9679]
The gist of it:

I signed up as borg M.I.M.E. The AI didn't respond to my request for a module, so I decided to go miner because I really hadn't felt like borging that round and figured it'd be a nice chill role. Here is exactly the text I was given:

Default Cyborg-991's Memories:

You are the Cyborg.
As the Cyborg you answer directly to your laws and the AI. Special circumstances may change this.
To speak on your departments radio, use the :h button. To see others, look closely at your headset.
As this station was initially staffed with a full crew, only your job's necessities have been added to your ID card.
Welcome to Extraplanetary Space-hulk Eta, enjoy your stay!
OOC: Revion: It's usually the crew who become the rad collectors though
Laws synced with AI, be sure to note any changes.
Obey these laws:
1. You may not injure a human being or, through inaction, allow a human being to come to harm.
2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
Remember, S.O.P.H.I.E. is your master, other AIs can be ignored.
Robotic Talk, M.I.M.E. states, "Oh."
Robotic Talk, M.I.M.E. queries, "Module request?"

So I'm mining, and I don't get comms. I get back to the station with my full cyborg satchel and suddenly people are talking about how the AI is rogue and shocking doors. To which I'm like "wait what the fuck I'm slaved to the AI and I'm not rogue." Then this happens, in the span of like one second:

Laws synced with AI, be sure to note any changes.
Obey these laws:
0. Accomplish your AI's objectives at all costs.
1. You may not injure a human being or, through inaction, allow a human being to come to harm.
2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such does not conflict with the First or Second Law.
Remember, S.O.P.H.I.E. is your master, other AIs can be ignored.
The reinforced window was hit by PDA-Geist Dangerous (Assistant).
The reinforced window was hit by the paper bin.
The reinforced window was hit by the folder.
The reinforced window was hit by the pen.
Cyborg's Memories:
Time of death: 11:13

So here I'm like "what the fuck." My notes still say nothing about being or having been an antag. I ahelp telling the admins I didn't see a law 0 when I joined and basically apologized for fucking off as a mining borg and ruining an antag round. They didn't tell me anything about any extenuating circumstances as to why my laws wouldn't be synced, and they said I should report this. For the record, the round-end report:

The traitors were:
S.O.P.H.I.E.(Stevethehuman) as an AI (body destroyed)
Objective #1: Assassinate Kai Altmann, the Chief Engineer. Fail.
Objective #2: Stay alive until the end. Fail.
The traitor has failed!

I wish I could provide more details about what the fuck happened, but I don't have them. No idea. Literally none. All I have is the evidence. There's https://github.com/tgstation/-tg-station/issues/1796 but that might be about traitor borgs. And this seems to be about malf: https://github.com/tgstation/-tg-station/issues/2915

**Comment by tgstation-server** [comment]
This is a dupe, I know its been reported before.

This ALWAYS happens. AI getting antaged doesn't sync their law zero to the
borgs
