### ISSUE TITLE
Emag not working on accessible airlocks properly

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#9686]
Clicking an airlock you have access to with the emag causes it to open normally rather than become emagged. If you click again, the airlock closes, and then it sparks and re-opens emagged. If you double click an airlock you have access to, you can sometimes get it to instantly pop open without the animation, so you can immediately run through it without having to wait for it to open.

**Comment by Lumipharon** [comment]
This has the rather significant effect that syndie borgs don't seem to be able to emag doors open at all (atleast when I try), since they have all access.

Pretty sure it works fine for emagging bolted closed shit though.

**Comment by Dorsisdwarf** [comment]
When did this start? This is definitely quite new, I think

**Comment by bgobandit** [comment]
Emags might not be able to emag doors normally either.

**Comment by Stickymayhem** [comment]
If you click, then click with the emag again while the door opening animation is taking place, the door snaps closed for an instant as the start of the emag animation takes place, and it is now emagged.
