### ISSUE TITLE
You are unable to put a deathsquad helmet on Ian.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/-tg-station#9695]
Since Dsquad suits were changed to hardsuits, attempting to spawn a helmet leads to Ian's name changing, but the helmet stays stuck to your hand. Placing the hardsuit on him and using the toggle helmet button does not put a helmet on him.

**Comment by GunHog** [comment]
It will simply have to be removed.

**Comment by PKPenguin321** [comment]
rip

**Comment by Niknakflak** [comment]
Just have the suit cover his entire body and remove the helmet aspect of it.
So the suit will also give his helmet in the sprite
