### ISSUE TITLE
Minor: Normal Cigarettes can hold more Chems then Cigars

### ISSUE THREAD

**Issue by Boredone** [tgstation/-tg-station#9698]
This is kinda simple.
Cigarettes can hold 30u of chems.
Cigars can hold 20u of chems, unless its a Havana Cigar, those can hold 30u.
Cigars could hold more then cigarettes before the nicotine addition I believe.
As a note, I only noticed this while checking the code, so maybe the obvious variable doesn't actually do anything? Not tested ingame.

For related info in case its relevent...
Rollies can hold 50u of chems.
Pipes can hold 100u of chems.

**Comment by Iamgoofball** [comment]
actually they don't

cigarettes have 15u of nicotine in them to start with, and you can't extract it as far as I can tell.

so you actually only have 15u of space, which is what it used to have

**Comment by Boredone** [comment]
While I'm not an expert at reading code, all the cigars and such also have that 15u nicotine I believe due to being a child of cigerates.
So Cigarettes can still hold more chems in em then cigars.

**Comment by Iamgoofball** [comment]
In that case, we need to bump up the storage size on cigars and all that shizzles that manually overrides it by 15u

**Comment by Dorsisdwarf** [comment]
This was fixed in my cigarette/nicotine refactor
