### ISSUE TITLE
Abalative/Laserpoof Armor Doesn't Reflect

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9704]
Basically, abalative/laserproof armor doesn't reflect shots, at all, anymore.

**Comment by Dorsisdwarf** [comment]
Details. Do you mean armor with a high "laser" resist, or the Ablative Armor's special ability?

**Comment by Fox-McCloud** [comment]
The Abalative armor; sorry, was referencing it's code name: "armor/laserproof".
