### ISSUE TITLE
Code Levels Need Updating

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9706]
From my understanding, random searches aren't allowed at code level blue--despite this, they specifically state, within the code, and more importantly, displayed to players---that when the alert level changes to blue (up or down), that random searches are, in fact, allowed.

**Comment by Dorsisdwarf** [comment]
This is a server policy request (Security level messages are a config) Please do not make policy requests in the github, and instead, contact a headmin on the forums

**Comment by Fox-McCloud** [comment]
Well, the wiki and policy of the server *currently*, as far as I know is that random searches *aren't* allowed under blue (again, as it currently is)--just figured that this should be reflected in the code *shrug*.

**Comment by Jordie0608** [comment]
@Dorsisdwarf is correct, this is a server policy issue; the code's config files are just examples.
