### ISSUE TITLE
Oculine does not do anything

### ISSUE THREAD

**Issue by Tokiko1** [tgstation/-tg-station#9707]
Oculine is supposed to heal your eyes but doesn't seem to do anything at the moment.

If you are blind from severe eye damage, it doesn't do anything.
If your vision is slightly reduced(the effect that is identical to the one when wearing a welding helmet), it doesn't do anything.

It doesn't even seem to be healing eye damage before any vision loss occurs. Go weld walls until your eyes are damaged enough to get the "Your eyes are really starting to hurt. This can't be good for you!" message, then inject some Oculine and wait 5 or so minutes for it to metabolize. Attempt to weld another wall and notice that Oculine did not heal your damaged eyes at all because the message still appears.

It's worth noting that blindfolds don't seem to heal eye damage either at the moment, though that may be intended behavior.

**Comment by Cheridan** [comment]
Pregoonchem chemical (imidazoline iirc?) didn't heal blindness to make the eye surgery option more valuable. Though not working at all is a problem of course.

I believe you have to be sleeping for blindfolds to heal your eye damage.
