### ISSUE TITLE
Toxins cannot heat up past a few hundred degrees C.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9711]
Trying to set a burn mixture in the toxins test chamber leaves makes it unable to heat up more than a few hundred degrees celcius. I checked the floor in the toxins burn chamber, and while its max temperature sustained was 11,000 it was actively at just 271. Basically means even cold toxins bombs are not feasible.

The limit seems to be around 285.53 C (558.68 K), and was sitting at 4499.97 kPa.

**Comment by kyrahabattoir** [comment]
then there was this event where this canister after being filled with hot co2 then topped with 66/33 burn mix, when i opened the valve, the pressure started rising on it's own -> https://i.imgur.com/oTwMHoX.png

**Comment by Razharas** [comment]
Atmos is mysterious

**Comment by duncathan** [comment]
Makes me think of the third point of #9310.

**Comment by Dorsisdwarf** [comment]
Yeah, toxins never rises above 300 degrees, but it's not gamebreaking if you know the Canister Furnace trick

**Comment by WJohn** [comment]
Apparently this is actually still a thing. Nevermind me.

**Comment by duncathan** [comment]
Toxins not being able to get hot enough has not been an issue since the addition of fusion
