### ISSUE TITLE
Showers cleaning bloodied clothes under exosuits is clunky

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9713]
How to reproduce:

- Have a uniform and an exosuit item (example: mime wearing suspenders), both bloody.
- Get into the shower. Your exosuit item will be cleaned but your uniform won't, all expected.
- Remove the exosuit item WHILE STILL UNDER THE WATER.

Intuitive behavior: Your uniform, now under the shower, will get clean.
What actually happens: The uniform is not cleaned until you leave and re-enter the running shower.

A small thing but a little annoying (especially if you forget that showers slip now).

**Comment by Stickymayhem** [comment]
This looks a lot like a problem I had with lava. I'll take a look.

**Comment by xxalpha** [comment]
I am going to guess it just cleans you on Enter() or something along those lines. I am not sure if it's worth it adding it to a processing list for a case that doesn't happen often.

**Comment by Stickymayhem** [comment]
Yeah it doesn't have a continuing process for cleaning.

**Comment by phil235** [comment]
Fixed by something.
