### ISSUE TITLE
Security cannot use the Brig External Airlock

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9714]
...Because nobody has external airlock access in Security. Not even the HoS.

Who can currently use it? The CE and the Captain?

Just change it to Security or Brig Control access so that heads of staff + sec can use it.

**Comment by Xhuis** [comment]
:do_not_litter: :a: :bee:

**Comment by SconesC** [comment]
Fuck off Xhuis there is no way this is intended

**Comment by freerealestate** [comment]
do not litter a bee

**Comment by Incoming5643** [comment]
<img src="http://i.imgur.com/Xg5I1QL.jpg"></img>

**Comment by xxalpha** [comment]
This has always been the case, but I can't tell if it's intended or not. It's pretty stupid.

**Comment by WJohn** [comment]
This was just tested, sec officers can open the doors fine. This must have been fixed a long time ago.

**Comment by xxalpha** [comment]
You tested it on tg's servers?

**Comment by SconesC** [comment]
This was fixed but the fix was never tagged in the fixing PR
