### ISSUE TITLE
Can hear "Something is rumbling inside your stomach!" when you're not the alien

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#9718]
Was watching someone stuck in an aliens stomach shaking around. That message kept spamming for me, the ghost watching.

**Comment by PKPenguin321** [comment]
i think this might also happen if you're obese and eat a monkey

**Comment by duncathan** [comment]
Obesity is still a thing?

**Comment by kingofkosmos** [comment]
It's an [audible_message] (https://github.com/tgstation/-tg-station/blob/548e0eb17e1e46e4a686006c80096fd3c3237d97/code/modules/mob/living/carbon/carbon.dm#L41), working as intended although a bit confusing?

**Comment by PKPenguin321** [comment]
yeah obesity is a thing
but no i don't think it's intended, if i am trying to break out of someone's stomach but the game says i feel something in *my* stomach when that is clearly not what is happening then something has gone wrong
