### ISSUE TITLE
Clothes literally blown off

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#9731]
So someone made an explosion, which gibbed everyone else near me, but presumably because of my HoS coat, I wasn't gibbed.

On the other hand, it flung my corpse down the corridor, and literally blew my clothes off.
Every single item was destroyed.

I hope we haven't gone back to that horrifying time where explosions could destroy ANYTHING.

**Comment by WJohn** [comment]
I think explosions should remove socks from your underclothing (and I guess shoes too).

**Comment by Tokiko1** [comment]
Isn't this a feature? Bombsuits also get destroyed but leave your corpse intact.

**Comment by PKPenguin321** [comment]
wow that's awesome
feature

**Comment by SconesC** [comment]
NO NO MORE STRIPSPLOSIONS

**Comment by Razharas** [comment]
The ride never ends

**Comment by KorPhaeron** [comment]
Happened to me thr other day in a syndicate hardsuit, assumed it was a feature

**Comment by Iamgoofball** [comment]
didn't this happen from a Sorium explosion a few months back

i think it's something in throw_at()

and if I recall it also involved an HoS

i think his outfits have some problem involving throw_at()

**Comment by Dorsisdwarf** [comment]
No reoccurrences, closing as Unresolved.
