### ISSUE TITLE
You find yourself unable to speak! spam

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/-tg-station#9734]
Getting "You find yourself unable to speak!" message for no reason while also being fully able to speak. Seems to happen completely randomly.

**Comment by Marflowerose** [comment]
Seems to happen if you try to say nothing, even though you are not muted

**Comment by spasticVerbalizer** [comment]
The message comes from [code/modules/mob/living/say.dm](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L73), and _should_ only trigger when actually trying to speak, as it's in say(). I'm updating my test server now to see what broke it, but this didn't happen when I added it.

**Comment by spasticVerbalizer** [comment]
You're right, it's triggered by [this check](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L166) for an empty message

**Comment by Miauw62** [comment]
that check should really be removed

**Comment by spasticVerbalizer** [comment]
@Miauw62 The check is repeated in say() at [line 96](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L96), should that one be removed or the one in can_speak_basic?

**Comment by Miauw62** [comment]
both, and a replacement added outside can_speak() where neccesary.
