### ISSUE TITLE
Several admin commands are now logged as having been done by *null*.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9738]
Several of the admin messages tied to certain tools are reporting that the person who did them was ```*null*```.

MC restarts, mob renames and some others I can't remember.

**Comment by Dorsisdwarf** [comment]
Needs reproduction. Will be shut down if nobody can reproduce on the live server.

**Comment by Jordie0608** [comment]
It still happens, rarely.

**Comment by Shadowlight213** [comment]
Gibself produces this 100% of the time.
