### ISSUE TITLE
title3.ogg is kinda huge compared to the other title tracks

### ISSUE THREAD

**Issue by Incoming5643** [tgstation/-tg-station#9754]
title1.ogg 799 kb
title2.ogg 346 kb
title3.ogg 10298 kb

A matter of server resources, might not be worth fixing if you can't get it down without losing fidelity, but there is probably some rather painless ways to get that filesize down.

**Comment by WJohn** [comment]
It's only slightly bigger. I think we can let that slide.

**Comment by xxalpha** [comment]
>only slightly bigger

It's more than 10 times bigger, WJ. Maybe @Cuboos should trim it down to pre-round time length.

**Comment by Cuboos** [comment]
WHY THE HELL DID YOU PEOPLE WANT ME TO DO THIS IN THE FIRST PLACE?

**Comment by Incoming5643** [comment]
I'm not saying it's bad, it's not! I'm just saying that a 4 minute ogg file being 9.8 mb makes it a significant part of resource download. You don't have to do anything with it you don't want, I'm just pointing out the quality to size disparity here.

**Comment by Iamgoofball** [comment]
condense that fucker into ultra-compressed 2002 midi mode bby

**Comment by Cuboos** [comment]
Midi sucks
