### ISSUE TITLE
admin abuse

### ISSUE THREAD

**Issue by gabrielm78** [tgstation/-tg-station#9757]
the user lucas325 It is an admin who are known to abuse admin

**Comment by duncathan** [comment]
Uh

**Comment by CorruptComputer** [comment]
Uh

**Comment by xxalpha** [comment]
It seems you are lost.

https://tgstation13.org/phpBB/viewforum.php?f=23

**Comment by optimumtact** [comment]
How do you even function in day to day life?

**Comment by Iamgoofball** [comment]
>easy fix
>blame MSO
