### ISSUE TITLE
Inserting an ID into a PDA while in a disposals bin does not remove the ID from your hand

### ISSUE THREAD

**Issue by lollerderby** [tgstation/-tg-station#9763]
Problem Description: If you are in a disposals bin and put an ID in a PDA, the ID is placed inside the PDA but also remains in your hand.

What did you expect to happen: I expected to put the ID inside the PDA.

What happened instead: By some bluespace sorcery, the ID transcended reality and somehow managed to exist in two places at the same time.

Why is this bad/What are the consequences: Immersions. There's probably a way to abuse this too.

Steps to reproduce the problem: Wearing a PDA and holding an ID in your hand, climb into a disposals bin. Try to insert the ID in the PDA. Notice that the ID is now both in your hand and in the PDA. Cry.

Server: Sybil.

Revision: 2aa0247b0071d5c8ddebb8eaa7669404ebff1b09

**Comment by xxalpha** [comment]
This is because of item drop prevention inside machines.

**Comment by Marflowerose** [comment]
Would this work for any items if you hold bag in one hand and the replicatable item in another?
