### ISSUE TITLE
Xenomorph simple animal issues

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#9774]
Xenomorph simple animals cannot be debrained. This is likely intended (simple animals don't really have brains to remove), but because there is no feedback for this, it appears at a glance to be an issue. A message when attempting to use surgical drapes on a simple animal xenomorph would be an easy fix.

Xenomorph simple animals cannot fit onto the meat spikes in the kitchen, while real xenomorphs can. I can't see any real reason for this, unlike the debraining thing.

**Comment by phil235** [comment]
If using the surgical drapes on the xeno doesn't open the surgery list window then the problem comes from the attempt_initiate_surgery() proc. Butchering doesn't interfere with surgery once a surgery is started.

**Comment by Incoming5643** [comment]
if you started to butcher the xeno, that means it was a simple animal xeno, which don't actually have brains. Not a bug, just kind of a crummy situation.

**Comment by PKPenguin321** [comment]
Oh, it may be what incoming said.
I'll go test it on a private server. If incoming's right then this is a non-issue and I'll close it

**Comment by Supermichael777** [comment]
so science xenos cannot be used for science?

**Comment by Incoming5643** [comment]
fraid not, simple animal xenos are a cruel joke.

We could manually add a xeno brain to the simple animals butchering though

**Comment by WJohn** [comment]
We really shouldn't even have simple animal xenos. They're a very sad and very weak representation of something much more fun, yet people treat it as exactly the same threat, even if they're simply created from xenobio.

At the very least blacklist them from xenobio gold cores.

**Comment by KorPhaeron** [comment]
Letting you get brains out of them would give you bio 8 or whatever it is you need for implants, which I think are supposed to remain rare.

@WJohn 

They're fun to put ghosts into though

**Comment by PKPenguin321** [comment]
Hell, I wouldn't mind, if you can actually get science to collaborate enough to get gold slimes without blowing themselves the fuck up and get mining to help research get that high in the first place I'd say you've earned it at some point. Plus, gold slimes spawning xenos is all RNG anyways, so it's not like it's guaranteed.

**Comment by KorPhaeron** [comment]
@tkdrg 

I fixed the meatspike thing and the other part of this (brains) is intentional balance related right now

**Comment by tkdrg** [comment]
k
