### ISSUE TITLE
De-admin broke

### ISSUE THREAD

**Issue by CorruptComputer** [tgstation/-tg-station#9775]
![image](https://cloud.githubusercontent.com/assets/5573038/7973537/1a3b21cc-0a1c-11e5-9b42-a8d6b1e63db1.png)

**Comment by optimumtact** [comment]
feature

**Comment by Boggart** [comment]
What rank did you have before de-adminning?

**Comment by CorruptComputer** [comment]
Game Master

**Comment by Boggart** [comment]
Was this a local test server? Going by the error I'm guessing it's using admin.txt for auth since it lacks the message saying to check the db connection

**Comment by Boggart** [comment]
Unable to reproduce on a local server running byond 507.1286 and /tg/station revision 05072bcf3140827d89ca6a119f74ed6191df4aa4 using admins.txt

**Comment by CorruptComputer** [comment]
It was a local test server. I just retested and it works fine now, so I
have no idea what caused it.

**Comment by Boggart** [comment]
For this to have happened rank would have had to be null and on the admin.txt system there's not a lot of code to go wrong.

```
var/rank = null
	if(config.admin_legacy_system)
		var/list/Lines = file2list("config/admins.txt")
		for(var/line in Lines)
			var/list/splitline = text2list(line, " = ")
			if(splitline[1] == ckey)
				if(splitline.len >= 2)
					rank = ckeyEx(splitline[2])
				break
			continue
```

Is it possible something was wrong with your admin.txt? This could happen if len was less than two, as rank would still be null.

**Comment by MrStonedOne** [comment]
its checking ckey


but admin.txt takes keys

it needs to lower case

**Comment by Boggart** [comment]
Well now I feel silly.

**Comment by MrStonedOne** [comment]
Hey, i had it happen to me too, and i looked at that proc for 5 hours.

It wasn't until kor said he could never use re-admin on sybil, that i started trying things.
