### ISSUE TITLE
Metal foam grenades are kill

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/-tg-station#9780]
At least the ones that you can adminspawn and that are on the map at roundstart on meta.
They only make foamed metal on the tile they pop on. Then they will foam up everywhere else, but that foam doesn't turn metallic.

**Comment by Iamgoofball** [comment]
there's about 5 issues for this and in each one @cheridan

**Comment by PKPenguin321** [comment]
you're right, checking previous issues shows that this is a duplicate of https://github.com/tgstation/-tg-station/issues/9216
