### ISSUE TITLE
VEIL STILL DOESN'T WORK ON CONSOLES REEEEEE

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9794]
CONSOLE LIGHT KILLS ALL THE TIME REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Iamgoofball** [comment]
https://tgstation13.org/wiki/Reporting_Issues

**Comment by PKPenguin321** [comment]
in human tongue:
Shadowling's veil ability doesn't disable light emitted by consoles. Shadowlings are frequently dying to light emitted by consoles. Reeeee.

**Comment by xxalpha** [comment]
@Xhuis

**Comment by bgobandit** [comment]
tl;dr

:salt:

**Comment by AlexanderUlanH** [comment]
Would it cause huge problems if we just made veil set everything's luminosity to 0?
As long as it toggles flashlights off too, it should be fine.

**Comment by Stickymayhem** [comment]
I think computer consoles are one of the last things forgotten about so a check for those and maybe any other structures with luminosity would be fine really.

**Comment by GunHog** [comment]
Does it work on those horrible, awful glowshrooms?
