### ISSUE TITLE
Shadowling needs scaling

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9797]
Even with 60 players you get like two shadowlings and I've found that about one in ten has the shadowlings barely lose, even when they are all competent (or as competent as people can be at shadowling are at the moment), the last few times I ran it. 

If the scaling gets sorted I'll add it to the rotation.

**Comment by Incoming5643** [comment]
keep in mind that to some degree the number of thralls needed to win needs to scale with the number of antagonists lest we end up with six shadowlings that feasibly only need to convert two or three people each.

**Comment by Dorsisdwarf** [comment]
Thralls to win should be 5x number of shadowlings up to 3 shadowlings, then all addition shadowlings are x3 the number of lings

So 3 shadowlings need 15 peeps
4 need 18
5 need 21

A straight multiplier wouldn't work, because thralling lots of people gets quite hard

**Comment by Stickymayhem** [comment]
I've run two rounds with 6 shaddowlings and neither time could they reach fifteen.

Shadowling is extremely difficult. People don't realize that. The number of thralls needed shouldn't scale yet until we figure out what decent shadowlings are capable of. Shadowling at the moment is crazy unforgiving and on top of that everyone is bad at it right now.

**Comment by kyrahabattoir** [comment]
in my opinion, divide the number a players by the number of shadowlings and add something like ...25-50%
This way not all shadowlings can win.

**Comment by Dorsisdwarf** [comment]
All shadowlings ascend together. It's a team gamemode. How do people not know this?

**Comment by PKPenguin321** [comment]
>If the scaling gets sorted I'll add it to the rotation.

@Xhuis

**Comment by Xhuis** [comment]
I have my event to work on, I can't do this at the moment.

**Comment by Dorsisdwarf** [comment]
Fixed.

**Comment by Xhuis** [comment]
thanks fam
