### ISSUE TITLE
Staff of change is making invisible, dense mobs

### ISSUE THREAD

**Issue by Jordie0608** [tgstation/-tg-station#9812]
Every once in a while when a mob is hit by a staff of change bolt, their icon is being set to null and they become unable to move or interact. It seems to happen more often when being transformed into humans, however that may be purely coincidental.

**Comment by AlexanderUlanH** [comment]
Happened to me.  Possibly related: I was a posibrain cyborg

**Comment by WJohn** [comment]
Still? I swear we fixed this already, and I thought it only occured with gold slime cores.

**Comment by Incoming5643** [comment]
there's no Staff of change black list, it's a white list.

Meaning that either some mob was moved/removed and the SoC list wasn't updated or there's something off about transformations, maybe with posibrain mobs.

**Comment by Jordie0608** [comment]
@WJohn It's not an error with paths

**Comment by Incoming5643** [comment]
runtime error: pick() from empty list
proc name: wabbajack (/proc/wabbajack)
  source file: magic.dm,233

						var/list/all_species = list()
						for(var/datum/species/S in typesof(/datum/species) - /datum/species)
							if(!S.dangerous_existence)
								all_species += S
						hardset_dna(H, null, null, null, null, pick(all_species))

it's a null != 0 error on my part will fix
