### ISSUE TITLE
Lizards have chance of joining with wrong sprite. (Maybe humans too.)

### ISSUE THREAD

**Issue by SvartaSvansen** [tgstation/-tg-station#9815]
So, it was brought to my attention that the coders thought the post-server wars gender bender bug was fixed. But it is still going strong, and has been ever since the server wars.

Basically, when you join the game as a lizard, you appear to have a 50/50 chance of your sprite not matching your genetic gender. A male has a female body and vice versa. It has led to interesting things IC, like a lizard MD specializing in sex change operations for lizards whose bodies were messed up by NT.

I have only observed this happening to lizards, but I never play human characters. It may happen to humans as well.

**Comment by Incoming5643** [comment]
Is this on a downstream server? I've never seen this.

**Comment by SvartaSvansen** [comment]
It happens all the time on Basil. Well-known among regular lizard players, apparently not so much among others. Except those who have regularly heard lizards complain about it over comms.

**Comment by Incoming5643** [comment]
well if it only happens among lizard players who've played that character a long time, it might be a save file thing. They should try toggling their sex back and forth then saving and see if it keeps happening.

**Comment by SvartaSvansen** [comment]
I only say those who regularly play lizards because they have more of a chance of noticing it happening. You could play a transient character for two shifts and never notice it because his/her clothes never come off.

I remember when playing fresh on my private server, one of the first times I spawned myself in it happened. It also happens when I do a rudimentary transform. Regenerate icons immediately fixes it.

I honestly have no idea what it might be. It just seems like a spawn issue. First time I played a new male character, he joined with a female body.

**Comment by Incoming5643** [comment]
I'll look into it. If it's really been doing this this whole time it's gonna be something of a mindfuck for me.

**Comment by Incoming5643** [comment]
It definitely isn't affecting humans
![d10_icon](https://cloud.githubusercontent.com/assets/4176358/8022233/c0bc7118-0c92-11e5-817c-639bb7aa3d9e.png)

**Comment by SvartaSvansen** [comment]
I followed your example and set up a demonstration of my own with 36 naked Lisas, all created by performing a rudimentary transformation on my ghost.
![36lisas](https://cloud.githubusercontent.com/assets/12772255/8022367/b2efb3c6-0c9a-11e5-9673-399ba627943c.png)
Imagine each of these representing an individual time that I join a round. They are all genetically female, and they all show up as "she" when you examine them. They will also all have male sprites if you perform a sex change, or they will all have female sprites if you clone them. It's just the initial spawn that's messed up.

**Comment by Incoming5643** [comment]
Bug confirmed

Currently baffled

**Comment by SvartaSvansen** [comment]
Toldja. It's been a funny IC issue and just chalked up to NT not caring about making genetic mistakes with lizards or whatever.
