### ISSUE TITLE
Spawning Abductors Broke

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#9825]
Using the create antag button

1. Spawn team 1
2. Spawn team 2
3. Hit the button for 3/4 at the same time
4. 4 naked humans spawn in arrivals, gib them
5. Hit the button one last time
6. Two more naked humans spawn and are gibbed

**Comment by Incoming5643** [comment]
This actually never worked, so it didn't break.

**Comment by AnturK** [comment]
Well it should work if not used in parallel, will try to get in some delay in there.

**Comment by KorPhaeron** [comment]
Yes. It still did't work even when I tried one at a time though

**Comment by AnturK** [comment]
Wait. The two first teams didn't spawn either ? Or just 3+

**Comment by KorPhaeron** [comment]
First two teams spawned fine, 3+ didn't

**Comment by KorPhaeron** [comment]
Or to clarify, going by attempts

1 worked
2 worked
3/4 at the same time failed
5 failed

**Comment by Incoming5643** [comment]
team one spawns in the upper left saucer
team two spawns in the lower right saucer

No one ever spawns anywhere else
