### ISSUE TITLE
Window doors do not break from high temperatures like other windows.

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9841]
What it says on the tin. This is inconsistent with other windows, and given that they're destructible and often surrounded by windows I don't think it'd be too far fetched to see these be broken from fire anyway.

**Comment by Lumipharon** [comment]
New meta.

**Comment by PKPenguin321** [comment]
Do they also block heat? If they do, then this might be intentional

**Comment by WJohn** [comment]
That would also be inconsistent since full tile window airlocks don't block heat either. Either way, they ought to let heat through (if they don't already) and be breakable by high heat/pressure and fire just like any window.

**Comment by PKPenguin321** [comment]
Full tile window airlocks do block heat when built with r-glass, and iirc windoors are also built with r-glass.
