### ISSUE TITLE
Still can't color shoes in washing machines with stamps

### ISSUE THREAD

**Issue by Man-Shroom** [tgstation/-tg-station#9846]
RRRRRRRRRRRREEEEEEEEEEEEEEEEE

I tried to put a pair of white shoes into a washing machine with a clown stamp, nothing happened. I need my non-honk, non-slowdown clown shoes

**Comment by phil235** [comment]
That's because clown shoes are not a child of /obj/item/clothing/shoes/sneakers. It may be intended since transforming sneakers into long clown shoes isn't exactly realistic.

**Comment by xxalpha** [comment]
This is a feature request.

**Comment by Firecage** [comment]
@WJohn Why the consistency issue tag though? Since its fully intended that you can't make, like white shoes suddenly into super long clown shoes. Same reason why grey jumpsuits can't be dyed into clown jumpsuits.

**Comment by WJohn** [comment]
Because everything else like gloves, jumpsuits, and bedsheets can be colored by crayon + washing machine. Why not do it with shoes too?

And doesn't a rainbow crayon turn a jumpsuit into a rainbow suit? Then make shoes with a rainbow crayon turn into rainbow shoes, we have those too.

**Comment by Firecage** [comment]
@WJohn ....He is talking about stamps, not crayons. Specifically clown stamps not dyeing shoes into clown shoes, which is 100% intended. Also, we CAN already dye shoes with crayons. The rainbow crayons DOES make shoes into rainbow shoes, he is talking about clown stamps and clown shoes though.

**Comment by WJohn** [comment]
I was pretty tired when I wrote that, I see what he's actually asking now.

**Comment by optimumtact** [comment]
That code is horrible ugh

**Comment by Man-Shroom** [comment]
This isn't a feature request, you used to be able to do this.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
