### ISSUE TITLE
Mini sat and Incinerator Air Injectors into space don't work on MetaStation

### ISSUE THREAD

**Issue by Scout890** [tgstation/-tg-station#9853]
The Air injectors meant for disposing of gases on the mini sat and for the incinerator don't  seem to work. They don't seem to be receiving power and clogs the the mini sat scrubbers.

**Comment by Metacide** [comment]
MiniSat pump fixed in https://github.com/tgstation/-tg-station/pull/10839

Will fix the incinerator outlet.
