### ISSUE TITLE
Cargo Manifests and ID-Locked Crates

### ISSUE THREAD

**Issue by SubtleGraces** [tgstation/-tg-station#9854]
Not necessarily a bug, but a balance issue.

Apparently even impractical crates like the PA can lose certain parts of the shipment due to cargobay RNG; you certainly can't repackage that and send it back. Neither would any CE actually open it to check when they'd have to drag six or seven parts all the way to the intended destination manually.

Could this perhaps be an exception?

**Comment by xxalpha** [comment]
Yeah, this shouldn't apply to certain crates.

**Comment by Dorsisdwarf** [comment]
You dont have to repackage to send the crates back. Just stamp it "NO" and include the stamped crate manifest inside the returned crate for a 100% refund.
