### ISSUE TITLE
R&D still has no doors

### ISSUE THREAD

**Issue by Lumipharon** [tgstation/-tg-station#9862]
R&D had its airlocks removed, apparently so during lowpop, roboticists could use it... because breaking a window was very difficult or some shit.

Now days, during low pop, roboticists get R&D access anyway, so the lack of airlocks just mean that EVERY SINGLE ROUND, random shitters/rogue golems/mysterious squatters/singulo worshippers can swarm into R&D and there's very little you can do about it.

R&D needs airlocks back.

**Comment by callanrocks** [comment]
There are doors on the outside for a reason, double doors.

And a blastdoor.

**Comment by kevinz000** [comment]
>Implying greytiders won't break down a window
Better shock the grills too
Oh, and make the doors accessible to robotics

**Comment by Lumipharon** [comment]
why does the wardens office or armory have doors? there are blast shutter and double airlocks in front of those.

Chemistry? Viro? Literally every other job except R&D?

**Comment by Razharas** [comment]
Just place a button to close the shutters into the R&D room so you can close from the inside

**Comment by Lumipharon** [comment]
Issue with that is you can't leave R&D unattended unless you're the RD and no one else uses the lab.

**Comment by Dorsisdwarf** [comment]
This should be removed, anyone who needs the lab /that/ badly can just blat down the windows with a toolbox/gun

**Comment by Lumipharon** [comment]
Every other job has a door. R&D lost there door for a reason that is no longer relevent, so there is no reason not to put them back in.

**Comment by Dorsisdwarf** [comment]
I was talking in favour of you lumi

**Comment by SconesC** [comment]
>Just place a button to close the shutters into the R&D room so you can close from the inside

That AND doors

Wayward golems/Roboticists should stay out. Sort of silly that Scientists can't get into Robo but Robo can get into the primary R&D workspace (9/10 times to loot it)

**Comment by kevinz000** [comment]
Back when R&D had doors, and HoP wouldn't just pass R&D access out to roboticists, robotics just kept building their own R&D lab :o

**Comment by kevinz000** [comment]
WEll, I'l miss having access to the lab as HoS too :)

**Comment by Dorsisdwarf** [comment]
As a HOS, your R&D lab access is "five laser rifle shots"

**Comment by SconesC** [comment]
undo the great hos access purge

**Comment by WJohn** [comment]
Blame paprika for doing it this way instead of merely having a door accessible by roboticists and scientists.

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request
