### ISSUE TITLE
Burnt Shuttle Tiles

### ISSUE THREAD

**Issue by SubtleGraces** [tgstation/-tg-station#9864]
With the new changes these tiles can be burnt, which assigns them an icon state they don't have.

![shuttletile](https://cloud.githubusercontent.com/assets/9012604/8056795/9a6bad88-0e79-11e5-8c88-03a9354fb5db.png)

**Comment by xxalpha** [comment]
Those are some odd burn patterns.

**Comment by WJohn** [comment]
@Aranclanos

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

This was fixed

**Comment by Dorsisdwarf** [comment]
crushed
