### ISSUE TITLE
Fully upgraded with tier 4 parts Clone Pod will not eject human beings at 100% health

### ISSUE THREAD

**Issue by Kromgar** [tgstation/-tg-station#9865]
As above

Somebody goofed. *cough*

Had to have an admin eject me out of it

**Comment by GunHog** [comment]
I told you about this, @Iamgoofball. Also the runtime with chem dispensers.

**Comment by Iamgoofball** [comment]
I thought I fixed it, weird as shit

I'll check it out again

**Comment by Shadowlight213** [comment]
Pretty sure this was fixed
