### ISSUE TITLE
dark matter blob spore clouds OP

### ISSUE THREAD

**Issue by kevinz000** [tgstation/-tg-station#9868]
We were fighting a blob on sybil and I walked into a cloud of dark matter by a spore dieing in space
Like, 10 lines of red bold text and instant critical :/

**Comment by SeikoTheSeal** [comment]
Happened to me few times since DM blob was added. Appears to happen totally randomly, tried to reproduce this on my own server, but was unable to.

**Comment by Iamgoofball** [comment]
@RemieRichards since spore clouds having the reagent was your thing, i didn't add them to spore clouds myself

**Comment by RemieRichards** [comment]
@Iamgoofball technically right back at you because you added DM blobs.

**Comment by Razharas** [comment]
Add them do blobbernaughts instead of usual spores
ALso apply it on blobbernaughts attack

**Comment by Iamgoofball** [comment]
@RemieRichards TECHNICALLY right back at YOU because i didn't do that part on purpose

**Comment by RemieRichards** [comment]
@Iamgoofball nah man, you added the overpowered chemical, you deal with it, my addition of spore clouds was balanced around the *fairer* chems

**Comment by Fayrik** [comment]
Seems like the simple solution here would be to make Dark Matter Blobs admin only.

**Comment by Iamgoofball** [comment]
No, the solution is to stop dark matter from triggering on smoke

**Comment by SconesC** [comment]
reagent spore clouds are retarded, just remove them

they contribute nothing of value to blob, spores are already a valuable asset and factories are still extremely important even if the mass produced simple mobs dont dump chems all over you

**Comment by Fayrik** [comment]
@Iamgoofball ...I did say simple.
