### ISSUE TITLE
Security Camera Console

### ISSUE THREAD

**Issue by Aurafag** [tgstation/-tg-station#9869]
When playing as Warden, and initially having to deal with scoping out a bombed out area of the station, a lawyer came by and asked me for glasses. I stepped away from the console to get them for him, then stepped back in front of the console, but without prompting it, it would jump back to the same camera I was on before, and wouldn't prompt me with the usual dialog menu to swap between cameras or leave. While this particular console is surrounded, I wasn't able to test whether it was only direct southern proximity that sets it off, but I did find that being directly southeast or southwest to it did not force it to pop up again.

I'm not sure if this was a client-side issue, but I was not activating it or walking into it, and seeing as anyone who needs to manually access one of thees may be in trouble, it warrants looking into.

**Comment by Jalleo** [comment]
cancel-camera view is a verb that you can activate to get out of this main issue is that this isnt deactivating itself from before gonna check if there is a simple way to do so now
