### ISSUE TITLE
People can ventcrawl when buckled to pipes

### ISSUE THREAD

**Issue by Razharas** [tgstation/-tg-station#9890]
Cuff someone
Buckle them to a pipe
Buckled person tries to move
They end up in a pipe
Resist to remove the cuffs
You can now freely ventcrawl anywhere and exit at any vent/scrubber

**Comment by Incoming5643** [comment]
Thank god no one ever uses this feature

**Comment by Razharas** [comment]
Yes absurdity of this bug is compensated by complete redundancy of this feature
Can as well remove

**Comment by freerealestate** [comment]
I'd completely forgotten that you could do this. Might be useful for maintenance murders. You shouldn't remove it if you can help it.

**Comment by WJohn** [comment]
Since when can you buckle people to pipes????

I didn't think we had that.

**Comment by Razharas** [comment]
^ This is how you know your feature is useless

**Comment by freerealestate** [comment]
The game has plenty of  bscure features. It doesn't mean they don't come in handy sometimes.

**Comment by Razharas** [comment]
Literally never seen anyone buckling someone to a pipe
The way it was discovered was accidental
Means none done it ever before since its this easy to reproduce

**Comment by Jalleo** [comment]
Wait does this mean standard humans buckled to a pipe can end up in the pipe?

**Comment by RemieRichards** [comment]
Removing the feature isn't how to fix it, I told you how to fix it when you reported it in the IRC.
just have /atmospherics/relaymove() check that the user is not actually buckled to it, and is actually in the pipe system.

**Comment by Razharas** [comment]
Yes jalleo humans end up in pipes
I saw atmos tech ventcrawl around the station for fun after it happened

**Comment by Miauw62** [comment]
i love this bug

**Comment by palpatine213** [comment]
New perma escape technique just requiring a crowbar and some cuffs. Vent crawl from perma to the armory.

**Comment by duncathan** [comment]
Feature :+1:

**Comment by kevinz000** [comment]
Oh yeah I discovered this by trying to buckle cuff someone to a pipe in main because they were annoying

**Comment by newfren** [comment]
A cult had me handcuffed and accidentally buckled me to a pipe a while back and had literally no idea what had happened. A++ Feature
