### ISSUE TITLE
Hulk is really really really stupid

### ISSUE THREAD

**Issue by SconesC** [tgstation/-tg-station#9892]
It's way too easy to get

Free punch stuns, no % chance just straight up touch = get stunned

**Comment by Iamgoofball** [comment]
@SconesC the reason it happened so fast was because scientists and geneticists were Rev Heads, and we teamed up to rapidly get dat fukken hulk ASAP

this doesn't occur often

**Comment by SconesC** [comment]
irrelevant, im saying hulk is stupid in what it does

not limited to that round

**Comment by Durkel** [comment]
Hulk punches can still miss and be blocked If I recall correctly. that you can just disabler them and throw floor tiles at their ass. If most players worry about toxins making bombs during a rev round, you should also worry that the geneticist has a chance to churn out green muscle bound roid ragers.

**Comment by Razharas** [comment]
i ded plz nerf
On a serious note it has 5% chance of exposure, it means about 20 injections on average
And thats after you actually found it

**Comment by Lumipharon** [comment]
>20 injections

That translates to 20 seconds in the scanner.

**Comment by Dorsisdwarf** [comment]
Yeah, but it's also 20 irradiations, and you gotta manually do it for everyone who wants hulk, unlike the "Leave fifty injectors on the desk, station descends into BRUCEBANNERSTATION anarchy

**Comment by Lumipharon** [comment]
Do you know how the scanner even works?

Other then the initial SE change, it causes 0 irradiation. You just apply minimal duration/strength pulses to literally any block and there's almost zero delay.

**Comment by AlexCrimson** [comment]
Laser hulks into crit = they lose hulk. Its basically just an all-access grief tool. Terrible power.

**Comment by xxalpha** [comment]
hugbox

**Comment by callanrocks** [comment]
Maybe if genetics wasn't broken and rarely used this would be an issue.

**Comment by Aranclanos** [comment]
>each time someone loses in-game is allowed to open an issue in the repo

nonono stop close this send them to hell

**Comment by xxalpha** [comment]
Yep it's getting too frequent.

**Comment by Miauw62** [comment]
maybe you should make a thread in the "feedback" forum.
