### ISSUE TITLE
The power monitoring console in engineering is completely useless

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9898]
Not sure whether this happens in all rounds, but every time I've ever tried to consult it, it shows literally no information, regardless of whether there is power or not. Possibly related to changes to the SMES structure?

**Comment by Razharas** [comment]
Just tested on sybil, it works fine

**Comment by Jalleo** [comment]
What version of byond and windows do you have?

**Comment by bgobandit** [comment]
lol oops
