### ISSUE TITLE
Lizards are classified as Human in telecomms server monitoring consoles

### ISSUE THREAD

**Issue by bgobandit** [tgstation/-tg-station#9899]
Minor-ass bug but:

data packet (b0320e69725325ea37ced4ad1d281874) [X]
Data type: Speech File
Source: Raises-the-Fortune (Job: Assistant)
Class: Human
Contents: "Did the clown jussst admit to doing the entire crew"

(I really was a lizard, none of that fake name shit)

**Comment by Miauw62** [comment]
this is literally never going to be fixed

**Comment by PKPenguin321** [comment]
for a simple fix just change the text "Human" to "Sapien" or something and ignore species altogether
