### ISSUE TITLE
LAG: Placing an APC frame on the asteroid can lag out a server for well over an hour.

### ISSUE THREAD

**Issue by francinum** [tgstation/-tg-station#9905]
![](https://i.gyazo.com/a0b58d3b028e76c86c115c5406556275.png)
After attempting to place down the APC, the entire server froze.

**Comment by RemieRichards** [comment]
Not sure if I'm magic and predicted this or that this used to be a thing AGES ago.
It's due to the large areas that mining are stored in, isn't it?

**Comment by Jalleo** [comment]
Can the asteroid areas be deleted once the creation is done or is it not possible since the mobs will then run amok to the mining outpost?

**Comment by RemieRichards** [comment]
@jalleo I'm almost 1000% sure the mobs don't give 2 shits about areas, so as long as the mobs were created before the area deletion, you could do it, but that doesn't seem like a good idea, as things ALWAYS have an area (like there's always a turf at a coordinate), deleting them would instead cause the asteroid to be /area instead of /area/whatever, which would simply repeat the exact same issue.

**Comment by Jalleo** [comment]
so we cant remove the areas at all and require it to use a blueprint to create a area on the asteroid when wanting to build a new room with a APC there?

**Comment by francinum** [comment]
Thing is, they all have always_unpowered set to 1
Could be causing a runtime.

**Comment by GunHog** [comment]
This is in fact a very old bug, I caused this as a drone trying to crate a fort on the asteroid. With enough time, the process does actually complete! My guess is probably that the code is trying to determine the borders of the area or some set of operations on each turf within the area, which of course is quite massive compared to the station.

**Comment by francinum** [comment]
@GunHog Did you do it on the east side or west side?

**Comment by GunHog** [comment]
Eastern.

**Comment by francinum** [comment]
The eastern section of the asteroid is a different area type. /area/mine/explored
the larger west side is /area/mine/unexplored

**Comment by Dorsisdwarf** [comment]
It's the size which does it, I think. Pretty sure that this would be solvable by making the APC return if placed in a mining area, or by splitting the mining area into a bunch of smaller ones

**Comment by francinum** [comment]
^:+1:

**Comment by AnturK** [comment]
This probably happened on Sybil moment ago. We really could use a fix for this.

**Comment by optimumtact** [comment]
Well it's pretty funny
