### ISSUE TITLE
Upgraded freezers and heaters can basically powersink rooms.

### ISSUE THREAD

**Issue by Boggart** [tgstation/-tg-station#9906]
Upgraded freezers and heaters can draw enough power that their room's apc stops charging and rapidly depletes. When this happens you pretty much have to deconstruct them because when you bring the power back on you don't have the time to shut them off before it dies again. (In fact when I tried to do so in atmos they already seemed to be off and power still died, I had to take them apart.)

The heater in atmos was drawing over 600kW on the environment breaker, the freezer was drawing about 100kW.

@iamgoofball

**Comment by AnturK** [comment]
There's also the fact you can set target temperature below 0K on these. Which doesn't make much sense and possibly breaks something more.

**Comment by Iamgoofball** [comment]
Weird, they should be drawing less power when upgraded.

@AnturK until it is proven things legit break from below 0K, it's a feature cause muh bluespess

**Comment by RemieRichards** [comment]
Negative temperatures in Kelvin are actually SUPER HOT, hotter than high values of kelvin.
it's a quirk of physics, it's real.

**Comment by Razharas** [comment]
I made upgraded heat/freez-erseat electricity proportionally to the temperature delta * heat capacity
On one hand they work like mini powersinks(actually intended), on the other hand thye are insanely effective

**Comment by Iamgoofball** [comment]
@Razharas we need tier -1 parts as traitor orders

**Comment by Jalleo** [comment]
@duncathan this has been proven to be intended its more a issue about how apcs are processing power rather than the freezer/heater.

**Comment by duncathan** [comment]
It is intended, but it is not good

**Comment by Jalleo** [comment]
I think Folix will be able to fix this in their powernet rewrite but this wont be till at least feburary.

**Comment by securitycopper** [comment]
I haven't looked at the code yet

**Comment by swankcookie** [comment]
A good start would be maiking it so they don't draw power unless there is gas running through them

**Comment by securitycopper** [comment]
Pulling down code (created a new branch), I will review and provide an update late tonight.

**Comment by securitycopper** [comment]
Power isn't being calculated correctly. I'm working on a bug fix

**Comment by securitycopper** [comment]
Created Pull request: https://github.com/tgstation/-tg-station/pull/14630
