### ISSUE TITLE
Admin emitter (energycannon) no longer works

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9915]
This emitter is meant to just be an admin thing you can slam down. It fires constantly and needs no power or turning on. It was a pretty useful tool for various things and I'm sure it wouldn't be difficult to bring back.

@Iamgoofball

**Comment by Miauw62** [comment]
it actually existed to be used on the shitty challenge away mission.

**Comment by Iamgoofball** [comment]
I don't even know what the admin emitter is i mighta killed it by accident

Just varedit a normal emitter

**Comment by Stickymayhem** [comment]
Muh ease of use. I'd have to incorp invis a mob just to turn it on or else the sprite doesn't update.

**Comment by Iamgoofball** [comment]
varedit the icon_state

**Comment by Niknakflak** [comment]
Fix your bug you shitdick

**Comment by Iamgoofball** [comment]
fix your attitude you shitdick :^)

**Comment by freerealestate** [comment]
muh stupid op laser thing

**Comment by Stickymayhem** [comment]
It's not an op anything it was just a quick and easy way to build containment fields for events that's now gone because it got caught in goofs constructible emitter stuff

**Comment by Niknakflak** [comment]
Three months later and still not fixed @iamgoofball

**Comment by Iamgoofball** [comment]
I'll consider fixing it when your deadminning occurs

**Comment by Niknakflak** [comment]
>shitty comeback to a bug he still won't fix

Yea ok bud

**Comment by Aloraydrel** [comment]
tick tock

**Comment by Iamgoofball** [comment]
Was niknak deadminned yet?

**Comment by duncathan** [comment]
@Cheridan can you ban goofball from github if someone else fixes this bug

**Comment by Iamgoofball** [comment]
you fucks aren't even admins how is this relevant to you

**Comment by duncathan** [comment]
Tbh goof I'm just pissed cuz you're being a cunt and refusing to fix a simple big for reasons unexplained

**Comment by freerealestate** [comment]
hi

**Comment by Iamgoofball** [comment]
pretty much laziness at this point

it's an easy fix
