### ISSUE TITLE
Shuttle walls cannot be deconstructed by welders

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9916]
Despite giving you appropriate messages and allowing you to begin welding them, and even blinding you, it is impossible to deconstruct them. 

Either this should be removed or it should be possible to construct and deconstruct shuttle walls and floors. Some simple thing like using tiles on a girder instead of metal (Because tiles for shuttle re-entry heat management things? I don't fucking know)

**Comment by Dorsisdwarf** [comment]
The title should be changed to reflect the fact that the bug is that welders give you a message when you try and use them on shuttle walls, since shuttle walls are intended to be indestructible at the moment

**Comment by Stickymayhem** [comment]
Are you sure they're meant to be indestructible because a lot of people including myself really like that they aren't.

**Comment by Shadowlight213** [comment]
Last I tested, shuttle walls can be deconned with a welder. @Dorsisdwarf this can be closed.
