### ISSUE TITLE
Mindswapping into an AI breaks you

### ISSUE THREAD

**Issue by callanrocks** [tgstation/-tg-station#9920]
You are unable to do anything and you are stuck with systems nonfunctional.

Attempts to mindswap further are met with "not while you're incapacitated.

**Comment by optimumtact** [comment]
I'm suprised it's even possible in the first place

**Comment by phil235** [comment]
Apparently you can mindswap with pretty much any mob type. It's probably best to restrict it to humans and monkeys.

**Comment by Iamgoofball** [comment]
@phil235 can i mindswap the blob overmind?

**Comment by callanrocks** [comment]
Don't restrict it, muh depthz, just make it not buggy.

I am going to mind swap aliens and you will like it.
