### ISSUE TITLE
ED-209s and airlock construction text feedback

### ISSUE THREAD

**Issue by WJohn** [tgstation/-tg-station#9924]
It seems that various time-consuming steps with airlocks and ed-209s only show AFTER you've completed them. Outside of the occasional sound effect for various steps it may not be obvious that you've even successfully finished a step (ed-209 especially with mounting guns on, for example).

**Comment by phil235** [comment]
Looking at the ED209 construction code I don't see any step without text feedback, and time consuming steps have both a message at the start and end of the step. (https://github.com/tgstation/-tg-station/blob/909fcdc9a532f452817f8da85d4b67f46fe156dd/code/game/machinery/bots/ed209bot.dm#L544)

**Comment by WJohn** [comment]
That's strange. For the longest time I remember trying to affix a taser onto it (or screwdriver that) and it took a while without giving immediate text feedback.

This will likely be fixed by goofball's progress bar PR anyway.

**Comment by kingofkosmos** [comment]
Tested building an ED-209 and an airlock, couldn't find anything wrong with either of them.

**Comment by Jalleo** [comment]
Do you mean by the sprite it dosent show?

**Comment by WJohn** [comment]
This issue may be outdated then. I believe in the past it didn't give any text feedback and it may have already been fixed since then. Goofball's progress meter will fix this and all issues like this in the future however.
