### ISSUE TITLE
Pneumatic Cannon bug 

### ISSUE THREAD

**Issue by Xarvox** [tgstation/-tg-station#9926]
When attempting to build a Pneumatic Cannon, despite the icon being blue in the tablecrafting menu it would simply fail repeatedly no matter how many times you tried. On a related note, placing a straight pipe onto a table turns them into bent ones. This may be the core issue, but even when both pipes were straight the cannon still refused to be built.

**Comment by Incoming5643** [comment]
the build time for the cannon is very long, and if you move or drop the required tools (or don't have them to begin with) at any time the recipe will fail.

**Comment by Dorsisdwarf** [comment]
Can anyone confirm that the problem here is what incoming says?

**Comment by phil235** [comment]
That's because the check_tools() proc of tablecrafting is looking for the exact type of each required tool. Trying to use any other welding tool other than the default one will fail the crafting.

**Comment by phil235** [comment]
Fixed by #12240 . Make a new issue if you think the crafting time for pneumatic cannon is too long.
