### ISSUE TITLE
Advanced Baton mode switching issue

### ISSUE THREAD

**Issue by Firecage** [tgstation/-tg-station#9935]
It is very annoying to switch between the modes of the Abductor's Advanced Baton, since it uses attack_self to switch between them. So for one, you have may have to switch through several modes to get the one you want, and it can be very easy to accidentally have the wrong mode activated and get dunked when you try to stun someone and instead try to restrain them.

**Comment by AlexanderUlanH** [comment]
What's more convenient or intuitive than attack-self?
I agree that there are a lot of modes, and probing mode could probably be removed to take care of that. But other than that, the abductor baton's pretty convenient.  The modes are in the order you'd want to use them in, so you just stun - z - sleep - z - restrain - z - z, and you're ready for another go.

**Comment by Firecage** [comment]
Pity its bad to use to many action buttons, otherwise we coulda added action buttons for each mode aswell. Or a hotkey for each mode to boot.

**Comment by Dorsisdwarf** [comment]
Attack_self is basically the new standard for cycling through things.
