### ISSUE TITLE
Hand Teleporter: Can't Jump to Particular Objects/Containers

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/-tg-station#9942]
Ok, the the teleporter hub can jump to any beacon it can lock onto, regardless of the location of that beacon---meaning, if it's inside a mob, it'll teleport to that mob's location...if it's in someone's pocket--the pocket owner's location....etc.

That said, the hand teleporter will out and out fail if it's going to take you to a target that is inside something else.

**Comment by Lumipharon** [comment]
Really? If it's outright not working it must be recent, because I used a handtele to teleport to a captain with a beacon a week or two ago.

See if it happens with tracking implants also.

**Comment by Fox-McCloud** [comment]
Yup; made sure I was running the most recent code and such. Can't vouch for or against tracking implants.

Again, things are fine for the teleport hub; you can teleport to beacons in/on people.

**Comment by phil235** [comment]
That's because the doTeleport proc can't find a suitable turf. See https://github.com/tgstation/-tg-station/blob/909fcdc9a532f452817f8da85d4b67f46fe156dd/code/datums/helper_datums/teleport.dm#L103
The teleporter hub works fine because it doesn't use the precision argument.
