### ISSUE TITLE
Some of the new ghost sprites have errors

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#9944]
Tthe fire ghost is shifted two pixels down, and the pinkserbet ghost is shifted a pixel up.
The camo ghost is also awful but that's not actually an error~

**Comment by phil235** [comment]
#9912 fixed the purple whirl ghost sprite.

**Comment by francinum** [comment]
@phil235 I only removed a floating pixel, But sure, I think I can handle these right quick.
