### ISSUE TITLE
Welding vents doesn't use welding fuel

### ISSUE THREAD

**Issue by Anonus** [tgstation/-tg-station#9947]
If you turn your welder off fast enough, you can weld vents without using fuel at all.
The same isn't true of scrubbers, because those actually use fuel when you weld them.

**Comment by phil235** [comment]
It works for both scrubber and vents actually. It's because their attackby returns 1 with a weldingtool so the tool's afterattack (that is used to consume 1 unit of fuel) is never called.

**Comment by Miauw62** [comment]
Shouldn't the welding itself consume fuel?
Op 14-jun.-2015 15:08 schreef "phil235" <notifications@github.com>:

**Comment by Jalleo** [comment]
Yeah welding tool on uses fuel and tyen any action should cost fuel.
