### ISSUE TITLE
Bomb shuttle bugs

### ISSUE THREAD

**Issue by freerealestate** [tgstation/-tg-station#9952]
So a few pizza bombs went off in the shuttle last round, and I noticed a couple of bugs as a result:

- The tiles in the shuttle reveal unmoving space tiles when destroyed, despite the shuttle being in transit.
- The external shuttle airlocks seem indestructible (survived multiple pizza bombs, but I haven't tried it myself with a proper explosion so I can't tell) despite the walls around them being destroyed. I would've commented this there but I couldn't see it.

The shuttle being nearly indestructible has always bugged me, so it was nice to see this change. If only it were consistent, though.

This is semi-related to that bug about the backgrounds of shuttle corner tiles not moving while in transit and reconstructed floors appearing black. I would've commented this there, but I couldn't see it.

**Comment by francinum** [comment]
>The tiles in the shuttle reveal unmoving space tiles when destroyed, despite the shuttle being in transit.
Blame shuttle code.

**Comment by freerealestate** [comment]
Does that mean this won't get fixed? Should I close this?

**Comment by Jordie0608** [comment]
No; leave it open

**Comment by Chocobro** [comment]
closing of #10229 means i'm posting that screenshot here
![spaceweird](https://cloud.githubusercontent.com/assets/5677255/8407540/7508599c-1e5f-11e5-9e88-05f2f1287c07.jpg)

**Comment by freerealestate** [comment]
Thanks

**Comment by KorPhaeron** [comment]
@tkdrg 
 
I fixed this recently

**Comment by tkdrg** [comment]
it's true
