### ISSUE TITLE
Empty hand clicking a locker no longer unlocks it

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/-tg-station#9954]
It used to be that if you had your ID in your slot you can empty hand unlock it, then open it with another click. This was intuitive and easy.

Now when you empty hand click a locker, you get a message that makes no sense. "You cannot close the locker!" and it doesn't open.

This clearly isn't intended because the message makes no sense. The locker is already locked and closed.

**Comment by Jordie0608** [comment]
#9929

**Comment by Stickymayhem** [comment]
Yeah but my issue is more rad
