### ISSUE TITLE
#10000 is going to get wasted

### ISSUE THREAD

**Issue by ike709** [tgstation/-tg-station#9968]
Highest priority issue in the history of /tg/.

#10000 is a very special, unique number. One of you people is going to waste it on some lame joke that is closed a day or two later. We might as well bet on it... My money is on Aran.

**Comment by Jordie0608** [comment]
While it may be true; don't use the issue tracker for something like this dork.

**Comment by ike709** [comment]
It's a very serious issue and it should be tracked ;)
