### ISSUE TITLE
AI is capable of using Ayylien camera network to track the agent everywhere.

### ISSUE THREAD

**Issue by SeikoTheSeal** [tgstation/-tg-station#9975]
Be AI. Go to AI tab, jump to network verb, select abductor, jump to camera, select agent vest camera, have fun tracking the agent through his vest camera litteraly everywhere, including the ayylien ship, even tho he himself is not trackable thanks to his helmet. Ruin the round for abductors like a boss.

**Comment by Anonus** [comment]
AI, ruining antags even after huge nerfs. THANKS AI

**Comment by SeikoTheSeal** [comment]
>No ayy lmao tag

*cries*

**Comment by AnturK** [comment]
Ugh.Completely forgot to remove the vest cam after i made the ai-eye camera. Will put a fix up in a moment
