### ISSUE TITLE
Scorched/damaged sprite for grass is terrible

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/-tg-station#9983]
![github you pissy little shit](http://puu.sh/iqe6o/445ec67a97.png)
That's the sprite for both burnt and exploded and it's terrible for both.
This isn't actually a bug but it really does bug me.

**Comment by freerealestate** [comment]
Didn't even know this was a thing

**Comment by Dorsisdwarf** [comment]
Old grass sprites were beeetteeeeer

**Comment by Dorsisdwarf** [comment]
Also this is a sucky issue and we're #clampdown.
