### ISSUE TITLE
Crushers are overpowered

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#9990]
R&D doesn't need mining anymore, crushers do the work for them.

**Comment by francinum** [comment]
Feature, Mining is sometimes absent. they still need them for uranium.

**Comment by PKPenguin321** [comment]
what did i fucking say in the original PR

**Comment by Iamgoofball** [comment]
hey now this is valid

**Comment by Jordie0608** [comment]
Fiiine

**Comment by Iamgoofball** [comment]
this was fixed
