### ISSUE TITLE
R&D as a whole is broken

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#9992]
it's supposed to be a time gate but it takes like 10 minutes to finish up even without mining

combine with crushers spitting out too many materials and it's insanely good

**Comment by PKPenguin321** [comment]
it's been solved

we need an R&D expert genius like lumi to suggest new research levels for a ton of items and let the community find a new path on their own

the system is good but people have already found the most optimal path (which is good, it's fun to see threads discussing how to max research the fastest/most efficiently), just needs to be scrambled so the community has to solve it again
