### ISSUE TITLE
Virologist isn't too fun to play

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#9993]
it's just RNG: the job: the 3d experience: on ice:

suggest improvements

**Comment by Fox-McCloud** [comment]
Not using Bay's shitty system.

**Comment by PKPenguin321** [comment]
literally a non-issue, this is for the feedback forums

nice job rushing 9999 and 10000, please get banned

(i'm just salty i didn't get them don't worry goof i still love you)
