### ISSUE TITLE
Heat exchangers shouldn't be dense

### ISSUE THREAD

**Issue by duncathan** [tgstation/-tg-station#9994]
No other atmos devices are any more

**Comment by Dorsisdwarf** [comment]
Feedback/Ideas Forum, please. The maintainers all agree that the issue tracker is the wrong place for this kind of feature request

**Comment by duncathan** [comment]
1. It was a consistency issue; last I checked those are legit
2. I fixed this like immediately after I made the issue
3. I was trying unsuccessfully to prevent goof from getting #10000

It's cool tho because I forgot to mention this was fixed when I made my PR
