### ISSUE TITLE
Gibbers are a bit too overpowered when upgraded

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/-tg-station#9998]
they produce way way waaay too much meat, and are way too fast at putting people into them when upgraded

**Comment by Anonus** [comment]
This is your fault though~

**Comment by Iamgoofball** [comment]
and?

**Comment by Lumipharon** [comment]
Can you nerf or fix crushers too?

They're brokenly OP at mking all minerals (except uranium which they can't make for no apparent reason)

**Comment by Iamgoofball** [comment]
what is #9990

**Comment by ike709** [comment]
This is an actual balance issue isn't it...? Why's this closed...? Unless it isn't actually overpowered.

**Comment by Jordie0608** [comment]
Goofball made this (and a bunch of other issues) just to pad the issue count up to #10000

**Comment by ike709** [comment]
I know, but if gibbers are actually overpowered, this is still a legit balance issue. Even if it was just a shitty way to get #10000

**Comment by Jordie0608** [comment]
Fair enough

**Comment by Firecage** [comment]
@Iamgoofball These issues are kinda redundant to be seperate, since they can easily be put into a single one, due to the whole upgrading machines thing which you changed.

**Comment by Niknakflak** [comment]
It was just goofball being a shit human being to raise issue counts, it's ok guys

**Comment by Iamgoofball** [comment]
this can be closed now, nerf was merged

**Comment by Iamgoofball** [comment]
well no one ever upgrades these anyways so
